import { AnimeThemeConfig } from "./types"
import { GiCaveEntrance, GiDaggers, GiCrystalGrowth, GiSawedOffShotgun, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiBroadsword, GiHeartKey, GiCrown } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const arifuretaTheme: AnimeThemeConfig = {
    id: "arifureta",
    displayName: "Arifureta: From Commonplace to World's Strongest",
    description: "Average student Hajime Nagumo is betrayed and left for dead at the bottom of a deadly dungeon. Consumed by the abyss, he emerges remade — cold, merciless, and overwhelmingly powerful, determined to find a way home.",
    fontFamily: "'Exo 2', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Exo+2:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "215 225 242",
        "--color-brand-300": "175 190 222",
        "--color-brand-400": "135 152 200",
        "--color-brand-500": "98 116 176",
        "--color-brand-600": "68 84 150",
        "--color-brand-700": "44 56 120",
        "--color-brand-800": "24 34 84",
        "--color-brand-900": "10 16 50",
        "--color-brand-950": "4 6 22",
        "--brand": "98 116 176",
        "--background": "#020304",
        "--paper": "#070a0e",
        "--color-gray-950": "2 3 4",
        "--color-gray-900": "6 8 12",
        "--color-gray-800": "14 18 24",
        "--color-gray-700": "25 32 42",
        "--color-gray-600": "42 52 68",
        "--color-gray-500": "70 86 110",
        "--color-gray-400": "106 124 155",
        "--color-gray-300": "148 166 196",
        "--color-gray-200": "188 204 228",
        "--color-gray-100": "220 228 244",
        "--color-gray-50": "242 246 252",
    },
    sidebarOverrides: {
        "home": { icon: GiCaveEntrance, label: "Dungeon Base" },
        "schedule": { icon: GiAlarmClock, label: "Escape Schedule" },
        "manga": { icon: LuBookOpen, label: "Dungeon Notes" },
        "lists": { icon: GiFlowerEmblem, label: "Party Registry" },
        "discover": { icon: GiBullseye, label: "New Floors" },
        "torrent-list": { icon: GiSawedOffShotgun, label: "Arsenal Cache" },
        "debrid": { icon: GiCrystalGrowth, label: "Dungeon Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Members" },
        "enmasse": { icon: GiResize, label: "Party Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Floor Reports" },
        "auto-downloader": { icon: LuRss, label: "Dungeon Intel" },
        "community": { icon: GiDaggers, label: "Survivor Circle" },
        "achievements": { icon: GiTrophy, label: "Survivor Trophies" },
        "milestones": { icon: LuFlag, label: "Escape Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Danger Alerts" },
        "theme-manager": { icon: GiPalette, label: "Steel Palette" },
        "extensions": { icon: BiExtension, label: "Dungeon Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Dungeon Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Hajime's Config" },
    },
    achievementNames: {
        "a_first_episode": "Betrayed",
        "a_first_complete": "Floor Cleared",
        "a_hundred_club": "Hundred Floors",
        "a_time_lord": "Dungeon Survivor",
        "a_anime_collector": "Dungeon Archive",
        "a_library_legend": "Survivor Library",
        "a_binge_king": "Dungeon Marathon",
        "a_no_sleep": "All-Night Climb",
        "a_marathon_runner": "Hajime's Run",
        "a_speed_run": "Clear Speed",
        "a_completionist": "All Floors Done",
        "a_mega_completionist": "World's Strongest",
        "a_loyal_fan": "Loyal Party",
        "a_rewatcher": "Replay Dungeon",
        "a_decade_watcher": "Decade Survivor",
        "a_genre_action": "Dungeon Battle",
        "a_genre_adventure": "Escape Journey",
        "a_genre_comedy": "None Here",
        "a_genre_drama": "Betrayal Drama",
        "a_genre_fantasy": "Dungeon World",
        "a_genre_horror": "Abyss Fear",
        "a_genre_romance": "Yue's Love",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Dungeon Power",
        "a_genre_psychological": "Hajime's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Floor Critic",
        "a_perfect_ten": "Perfect Clear",
        "a_harsh_critic": "Survivor Standard",
        "a_daily_streak": "Daily Climb",
        "a_mega_streak": "Endless Dungeon",
        "a_year_long": "Year in Dungeon",
        "a_iron_will": "Hajime's Iron Will",
        "a_hidden_gem": "Hidden Floor",
        "a_cult_classic": "Dungeon Classic",
        "a_classic_connoisseur": "2012 Fan",
        "a_new_years_resolution": "New Year Clear",
        "a_christmas_special": "Winter Dungeon",
        "a_meta_tier_max": "True Strongest",
        "a_meta_completionist": "All Dungeons",
        "a_sequel_chain": "Hajime's Chain",
        "a_zero_to_hero": "Weakest to Strongest",
        "a_night_owl": "Night Climb",
        "a_early_bird": "Dawn Floor",
        "m_first_chapter": "First Descent",
        "m_first_complete": "Arc Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Dungeon Binge",
        "m_completionist": "Full Novel",
        "m_mega_completionist": "Arifureta Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Second Descent",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Escape Chapter",
        "m_genre_romance": "Yue Chapter",
        "m_genre_fantasy": "Dungeon Chapter",
        "m_genre_horror": "Abyss Chapter",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Floor Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Dungeon Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Survivor",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Classic Chapter",
        "m_mangaka_lover": "Chuuni Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Arifureta Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Dungeon Art",
        "m_manga_to_anime": "Adapted Dungeon",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020304",
        primary: "#6274b0",
        secondary: "#445496",
        accent: "#f0e8d8",
    },
    particleColor: "#a0b8d8",
    backgroundDim: 0.32,
    backgroundBlur: 18,
    particleTypes: {
        crystal_shards: { label: "Crystal Shards", maxCount: 14, defaultEnabled: true, defaultIntensity: 50 },
        blue_sparks: { label: "Dungeon Energy", maxCount: 10, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
        1: "Fallen Student",
        5: "Abyss Survivor",
        15: "Cave Dweller",
        30: "Dungeon Conqueror",
        50: "Ruthless Explorer",
        75: "World Traveler",
        100: "World's Strongest",
    },
}
