import { AnimeThemeConfig } from "./types"
import { GiCrown, GiCrossedSwords, GiShield, GiHorseHead, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiScrollUnfurled } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const arslanSenkiTheme: AnimeThemeConfig = {
    id: "arslan-senki",
    displayName: "The Heroic Legend of Arslan",
    description: "Young Prince Arslan of Pars watches his kingdom fall to the treacherous Lusitanian army — now a fugitive prince with a small band of loyal retainers, he must rise to reclaim his throne and create a truly just kingdom.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "242 198 155",
        "--color-brand-300": "225 165 108",
        "--color-brand-400": "205 130 60",
        "--color-brand-500": "180 96 20",
        "--color-brand-600": "145 68 5",
        "--color-brand-700": "106 44 1",
        "--color-brand-800": "68 26 0",
        "--color-brand-900": "36 12 0",
        "--color-brand-950": "16 4 0",
        "--brand": "180 96 20",
        "--background": "#050200",
        "--paper": "#0d0600",
        "--color-gray-950": "5 2 0",
        "--color-gray-900": "12 6 1",
        "--color-gray-800": "22 12 3",
        "--color-gray-700": "36 22 8",
        "--color-gray-600": "58 36 16",
        "--color-gray-500": "90 62 32",
        "--color-gray-400": "130 95 58",
        "--color-gray-300": "172 140 98",
        "--color-gray-200": "205 180 140",
        "--color-gray-100": "228 208 175",
        "--color-gray-50": "245 232 210",
    },
    sidebarOverrides: {
        "home": { icon: GiCrown, label: "Pars Kingdom" },
        "schedule": { icon: GiAlarmClock, label: "War Schedule" },
        "manga": { icon: LuBookOpen, label: "Kingdom Records" },
        "lists": { icon: GiScrollUnfurled, label: "Retainer Registry" },
        "discover": { icon: GiBullseye, label: "New Allies" },
        "torrent-list": { icon: GiCrossedSwords, label: "Weapon Cache" },
        "debrid": { icon: GiShield, label: "Royal Armory" },
        "unmatched": { icon: GiHorseHead, label: "Lost Knights" },
        "enmasse": { icon: GiResize, label: "Great Battles" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Kingdom Feed" },
        "community": { icon: GiCrown, label: "Arslan's Army" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Battle Alerts" },
        "achievements": { icon: GiTrophy, label: "Heroic Trophies" },
        "milestones": { icon: LuFlag, label: "Kingdom Goals" },
        "theme-manager": { icon: GiPalette, label: "Royal Colors" },
        "extensions": { icon: BiExtension, label: "Kingdom Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Pars Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Arslan Settings" },
    },
    achievementNames: {
        "a_first_episode": "Battle of Atropatene",
        "a_first_complete": "Pars Reclaimed",
        "a_hundred_club": "Hundred Battles",
        "a_time_lord": "Kingdom Veteran",
        "a_anime_collector": "Retainer Collection",
        "a_library_legend": "Pars Archives",
        "a_binge_king": "Battle Marathon",
        "a_no_sleep": "Night March",
        "a_marathon_runner": "Arslan's March",
        "a_speed_run": "Daryun's Charge",
        "a_completionist": "All Seasons",
        "a_mega_completionist": "Tanaka Master",
        "a_loyal_fan": "Arslan's Ally",
        "a_rewatcher": "Pars Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Daryun Fights",
        "a_genre_adventure": "Kingdom Journey",
        "a_genre_comedy": "Elam's Moments",
        "a_genre_drama": "Throne Claim",
        "a_genre_fantasy": "Pars Magic",
        "a_genre_horror": "Lusitanian Terror",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Narsus's Counsel",
        "a_genre_psychological": "Just Kingdom",
        "a_genre_mecha": "None Here",
        "a_critic": "Kingdom Critic",
        "a_perfect_ten": "Perfect Strategy",
        "a_harsh_critic": "Narsus Standard",
        "a_daily_streak": "Daily Battle",
        "a_mega_streak": "Endless Campaign",
        "a_year_long": "Year of War",
        "a_iron_will": "Arslan Resolve",
        "a_hidden_gem": "Hidden Arc",
        "a_cult_classic": "Tanaka Classic",
        "a_classic_connoisseur": "1986 Fan",
        "a_new_years_resolution": "New Year Siege",
        "a_christmas_special": "Winter Campaign",
        "a_meta_tier_max": "Heroic Legend",
        "a_meta_completionist": "All Arcs",
        "a_sequel_chain": "Dust Storm Dance",
        "a_zero_to_hero": "Prince to King",
        "a_night_owl": "Night Campaign",
        "a_early_bird": "Dawn Charge",
        "m_first_chapter": "First Battle",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Battle Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Arslan Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Kingdom Return",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Magic Chapter",
        "m_genre_horror": "Invasion Chapter",
        "m_genre_drama": "Throne Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_supernatural": "Counsel Chapter",
        "m_genre_psychological": "Justice Depth",
        "m_critic": "Kingdom Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Kingdom Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Prince Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Tanaka Classic",
        "m_mangaka_lover": "Tanaka Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Heroic Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Arakawa Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050200",
        primary: "#b46014",
        secondary: "#914405",
        accent: "#c8a828",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/arslan-senki.jpg",
    particleColor: "#d49030",
    backgroundDim: 0.35,
    backgroundBlur: 16,
    particleTypes: {
        desert_sand: { label: "Desert Sand", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
        banner_flickers: { label: "Battle Banners", maxCount: 10, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1: "Young Prince",
        5: "Arslan",
        15: "Fugitive Royal",
        30: "Retainer-Led",
        50: "Army Builder",
        75: "Just Kingdom",
        100: "Heroic King",
    },
}
