import { AnimeThemeConfig } from "./types"
import { GiOldWagon, GiSteamLocomotive, GiDeathSkull, GiPistolGun, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiWhistle } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const baccanoTheme: AnimeThemeConfig = {
    id: "baccano",
    displayName: "Baccano!",
    description: "Prohibition-era New York, 1930s — immortals, alchemists, thieves, and railroad gangsters collide across timelines in a blood-soaked, darkly comedic mystery told out of sequence.",
    fontFamily: "'Special Elite', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Special+Elite&display=swap",
    cssVars: {
        "--color-brand-200": "230 185 145",
        "--color-brand-300": "210 155 100",
        "--color-brand-400": "188 122 55",
        "--color-brand-500": "165 90 15",
        "--color-brand-600": "130 68 8",
        "--color-brand-700": "96 48 4",
        "--color-brand-800": "64 30 2",
        "--color-brand-900": "38 16 1",
        "--color-brand-950": "20 8 0",
        "--brand": "165 90 15",
        "--background": "#060400",
        "--paper": "#0e0900",
        "--color-gray-950": "6 4 0",
        "--color-gray-900": "14 10 2",
        "--color-gray-800": "26 18 6",
        "--color-gray-700": "44 30 10",
        "--color-gray-600": "68 48 20",
        "--color-gray-500": "105 78 40",
        "--color-gray-400": "148 118 80",
        "--color-gray-300": "186 158 122",
        "--color-gray-200": "214 192 162",
        "--color-gray-100": "232 216 194",
        "--color-gray-50": "245 236 222",
    },
    sidebarOverrides: {
        "home": { icon: GiOldWagon, label: "New York, 1930" },
        "schedule": { icon: GiAlarmClock, label: "Timeline" },
        "manga": { icon: LuBookOpen, label: "Immortal Files" },
        "lists": { icon: GiDeathSkull, label: "Immortal Registry" },
        "discover": { icon: GiBullseye, label: "Scouting" },
        "torrent-list": { icon: GiPistolGun, label: "Contraband" },
        "debrid": { icon: GiSteamLocomotive, label: "Flying Pussyfoot" },
        "unmatched": { icon: GiWhistle, label: "Unresolved" },
        "enmasse": { icon: GiResize, label: "Gang Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Case Files" },
        "auto-downloader": { icon: LuRss, label: "Underworld News" },
        "community": { icon: GiOldWagon, label: "The Gangs" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Street Alerts" },
        "achievements": { icon: GiTrophy, label: "Immortal Trophies" },
        "milestones": { icon: LuFlag, label: "Immortal Goals" },
        "theme-manager": { icon: GiPalette, label: "1930s Colors" },
        "extensions": { icon: BiExtension, label: "Elixir Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Underworld Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Era Settings" },
    },
    achievementNames: {
        "a_first_episode": "Elixir Found",
        "a_first_complete": "Mystery Solved",
        "a_hundred_club": "Hundred Incidents",
        "a_time_lord": "Immortal Veteran",
        "a_anime_collector": "Immortal Cache",
        "a_library_legend": "Archive Complete",
        "a_binge_king": "Timeline Marathon",
        "a_no_sleep": "All-Night Ride",
        "a_marathon_runner": "Non-Stop Story",
        "a_speed_run": "Ladd's Sprint",
        "a_completionist": "All Characters",
        "a_mega_completionist": "Narita Master",
        "a_loyal_fan": "Jacuzzi's Crew",
        "a_rewatcher": "Timeline Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Train Carnage",
        "a_genre_adventure": "1930s Journey",
        "a_genre_comedy": "Luck and Huey",
        "a_genre_drama": "Immortality Drama",
        "a_genre_fantasy": "Alchemist World",
        "a_genre_horror": "Ladd's Violence",
        "a_genre_romance": "Chane and Claire",
        "a_genre_scifi": "Elixir Science",
        "a_genre_supernatural": "Immortal Elixir",
        "a_genre_psychological": "Huey's Plan",
        "a_genre_mecha": "None Here",
        "a_critic": "Timeline Judge",
        "a_perfect_ten": "Isaac and Miria",
        "a_harsh_critic": "Ladd's Way",
        "a_daily_streak": "Daily Read",
        "a_mega_streak": "Immortal Streak",
        "a_year_long": "Year of Chaos",
        "a_iron_will": "Firo's Resolve",
        "a_hidden_gem": "Hidden Thread",
        "a_cult_classic": "Narita Classic",
        "a_classic_connoisseur": "2007 Fan",
        "a_new_years_resolution": "New Year Mystery",
        "a_christmas_special": "1930 Christmas",
        "a_meta_tier_max": "Immortal",
        "a_meta_completionist": "All Timelines",
        "a_sequel_chain": "Novel Continues",
        "a_zero_to_hero": "Mortal to Immortal",
        "a_night_owl": "Night Train",
        "a_early_bird": "Morning Rush",
        "m_first_chapter": "First Thread",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Chaos Marathon",
        "m_completionist": "Full Series",
        "m_mega_completionist": "Baccano Expert",
        "m_loyal_reader": "Immortal Reader",
        "m_rereader": "Timeline Return",
        "m_genre_action": "Carnage Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Chane Chapter",
        "m_genre_fantasy": "Elixir World",
        "m_genre_horror": "Violence Chapter",
        "m_genre_drama": "Immortal Drama",
        "m_genre_scifi": "Alchemy Chapter",
        "m_genre_supernatural": "Immortal Chapter",
        "m_genre_psychological": "Mastermind Chapter",
        "m_critic": "Story Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Non-Stop Reading",
        "m_year_long": "Year Reading",
        "m_iron_will": "Immortal Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Novel",
        "m_mangaka_lover": "Narita Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Baccano Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "1930s Art",
        "m_manga_to_anime": "Novel Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060400",
        primary: "#a55a0f",
        secondary: "#604408",
        accent: "#c0c0c0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/baccano.jpg",
    particleColor: "#d08040",
    backgroundDim: 0.38,
    backgroundBlur: 18,
    particleTypes: {
        paper_scraps: { label: "Paper Scraps", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        smoke_rings: { label: "Smoke Rings", maxCount: 10, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1: "Mortal",
        5: "Firo Prochainezo",
        15: "Martillo Scamp",
        30: "Flying Pussyfoot",
        50: "Immortal",
        75: "Elixir Keeper",
        100: "1700's Veteran",
    },
}
