import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiSwordWound,
    GiChainedHeart,
    GiMuscleUp,
    GiCrossedSwords,
    GiHorseHead,
    GiFist,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const battleAngelAlitaTheme: AnimeThemeConfig = {
    id: "battle-angel-alita",
    displayName: "Battle Angel Alita",
    description: "Born from the Scrapyard, forged in Motorball. A cybernetic interface of Panzer Kunst precision, berserker fury, and the dream of Zalem.",
    fontFamily: "'Orbitron', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700&display=swap",
    cssVars: {
        // Brand → bronze cybernetic tone
        "--color-brand-200": "225 200 140",
        "--color-brand-300": "215 180 110",
        "--color-brand-400": "200 160 80",
        "--color-brand-500": "180 140 60",
        "--color-brand-600": "155 120 45",
        "--color-brand-700": "125 95 30",
        "--color-brand-800": "90 70 20",
        "--color-brand-900": "60 45 12",
        "--color-brand-950": "30 22 6",
        "--brand": "200 160 80",
        // Dark scrapyard background
        "--background": "#080604",
        "--paper": "#100c08",
        "--color-gray-950": "8 6 4",
        "--color-gray-900": "16 12 8",
        "--color-gray-800": "28 22 16",
        "--color-gray-700": "45 36 26",
        "--color-gray-600": "68 56 42",
        "--color-gray-500": "98 82 64",
        "--color-gray-400": "138 120 100",
        "--color-gray-300": "175 160 142",
        "--color-gray-200": "208 198 184",
        "--color-gray-100": "232 226 218",
        "--color-gray-50": "246 243 238",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Scrapyard" },
        "schedule": { icon: GiAlarmClock, label: "Race Schedule" },
        "manga": { icon: LuBookOpen, label: "Ido's Archives" },
        "lists": { icon: GiCrossedSwords, label: "Hunter Roster" },
        "discover": { icon: GiBullseye, label: "Beyond Zalem" },
        "torrent-list": { icon: GiAnvilImpact, label: "Salvage Drops" },
        "debrid": { icon: GiHorseHead, label: "Motorball Runs" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Cyborgs" },
        "enmasse": { icon: GiResize, label: "Mass Rebuild" },
        "scan-summaries": { icon: TbReportSearch, label: "Body Scans" },
        "auto-downloader": { icon: LuRss, label: "Signal Intercept" },
        "community": { icon: GiEagleEmblem, label: "Factory Guild" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Scrap Alerts" },
        "achievements": { icon: GiTrophy, label: "Kill Trophies" },
        "theme-manager": { icon: GiPalette, label: "Chrome Finish" },
        "extensions": { icon: BiExtension, label: "Body Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Zalem Uplink" },
        "settings": { icon: GiSettingsKnobs, label: "Tuning Bay" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Scrap Pulse",
        "a_episode_counter": "Salvage Counter",
        "a_episode_titan": "Titan-Class Cyborg",
        "a_hours_invested": "Hours Welding",
        "a_time_lord": "Time-Core Master",
        "a_anime_collector": "Parts Collector",
        "a_library_legend": "Ido's Legend",
        "a_first_complete": "First Rebuild Done",
        "a_hundred_club": "Century Scrap Club",
        "a_first_day": "Awakening Day",
        "a_first_rating": "First Calibration",
        "a_ten_thousand_min": "Ten Thousand Revs",
        "a_season_veteran": "Veteran Hunter",
        "a_year_explorer": "Year Scavenging",
        "a_century_watcher": "Hundred-Bout Watch",
        "a_five_hundred_eps": "Five Hundred Strikes",
        "a_thousand_eps": "Thousand Encounters",
        "a_watching_ten": "Ten Fronts Active",
        "a_ptw_hoarder": "Spare Parts Hoard",
        "a_dropped_honesty": "Tactical Jettison",
        "a_five_thousand_eps": "Five Thousand Bouts",
        "a_ten_completed": "Ten Hunts Complete",
        "a_fifty_completed": "Fifty Bounties Claimed",
        "a_five_hundred_completed": "Five Hundred Victories",
        "a_mean_score_tracker": "Average Combat Score",
        "a_unique_studios": "Allied Workshops",
        "a_days_spent_watching": "Days in Scrapyard",
        "a_all_status": "All Deployment Modes",
        "a_first_favorite": "First Bonded Core",
        "a_favorites_collector": "Bonded Cores Arsenal",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Overdrive",
        "a_marathon_runner": "Motorball Marathon",
        "a_weekend_warrior": "Weekend Gladiator",
        "a_non_stop": "Relentless Drive",
        "a_one_more_episode": "One More Round",
        "a_speed_run": "Plasma Blitz",
        "a_double_feature": "Double Impact",
        "a_triple_threat": "Triple Takedown",
        "a_five_a_day": "Five Kills Daily",
        "a_back_to_back": "Back-to-Back Bouts",
        "a_seasonal_binge": "Full Circuit Arc",
        "a_cour_crusher": "District Crusher",
        "a_half_day_watch": "Half-Day Refit",
        "a_full_day_watch": "Full Day Wired",
        "a_power_weekend": "Power Weekend Blitz",
        "a_binge_king": "Binge Circuit King",
        "a_no_sleep": "All-Night Forge Run",
        "a_entire_season": "Rapid Circuit Clear",
        "a_seven_day_challenge": "Seven-Day Endurance",
        "a_hundred_day_binge": "Hundred-Day Siege",
        "a_genre_binge": "Cross-Class Training",
        "a_studio_binge": "Allied Forge Binge",
        "a_season_sweep": "Season Sweep Run",
        "a_forty_eight_hour": "Forty-Eight Hour Clash",
        "a_ep_counter_day": "Daily Kill Tally",
        "a_multi_series_binge": "Multi-Front Assault",
        "a_midnight_binge": "Midnight Scrapheap",
        "a_new_year_binge": "New Year's Charge",

        // ── ANIME GENRES ──
        "a_genre_action": "Combat Specialist",
        "a_genre_adventure": "Beyond the Junkyard",
        "a_genre_comedy": "Scrapyard Laughs",
        "a_genre_drama": "Alita's Resolve",
        "a_genre_fantasy": "Imaginos Body",
        "a_genre_horror": "Berserker Terror",
        "a_genre_mystery": "Zalem's Secret",
        "a_genre_romance": "Heart of Chrome",
        "a_genre_scifi": "Tiphares Tech",
        "a_genre_sol": "Life Below Zalem",
        "a_genre_sports": "Motorball Track",
        "a_genre_supernatural": "Damascus Blade",
        "a_genre_thriller": "Hunter Pursuit",
        "a_genre_mecha": "Berserker Arsenal",
        "a_genre_music": "Iron Resonance",
        "a_genre_psychological": "Desty Nova's Mind",
        "a_genre_ecchi": "Chrome Allure",
        "a_genre_mahou_shoujo": "Plasma Wielder",
        "a_tag_isekai": "Transported Below",
        "a_tag_harem": "Squad Bonds",
        "a_tag_bl": "Comrades Forged",
        "a_tag_gl": "Steel Sisters",
        "a_tag_historical": "Tiphares History",
        "a_tag_military": "Factory Discipline",
        "a_tag_school": "Hunter Academy",
        "a_tag_martial_arts": "Panzer Kunst",
        "a_tag_vampire": "Blood-Iron Body",
        "a_tag_samurai": "Blade Mastery",
        "a_tag_space": "Beyond the Clouds",
        "a_tag_parody": "Scrapyard Parody",
        "a_tag_idol": "Iron Angel Idol",
        "a_tag_post_apocalyptic": "Post-Fall World",
        "a_tag_cyberpunk": "Cybernetic Edge",
        "a_tag_shounen": "Fight or Die",
        "a_tag_seinen": "Harsh Iron World",
        "a_tag_shoujo": "Gally's Devotion",
        "a_tag_josei": "Ido's Compassion",
        "a_tag_survival": "Scrapyard Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Body Rebuild",
        "a_mega_completionist": "Supreme Cyborg",
        "a_completion_rate_50": "Halfway Rebuilt",
        "a_completion_rate_75": "Approaching Zalem",
        "a_completion_rate_90": "Near Full Chrome",
        "a_no_drop": "No Part Abandoned",
        "a_long_runner_complete": "Long Haul Endurance",
        "a_sequel_chain": "Linked Chain Drive",
        "a_clean_list": "Clean Service Log",
        "a_from_ptw": "Orders Executed",
        "a_rewatch_master": "Memory Core Replay",
        "a_short_complete": "Quick Skirmish Won",
        "a_same_day_start_finish": "Same-Day Shutdown",
        "a_revival": "Revived by Ido",
        "a_zero_to_hero": "Scrap to Angel",
        "a_five_genre_complete": "Five-Class Mastery",
        "a_full_franchise": "Full Cyborg Dossier",
        "a_batch_complete": "Batch Refit Clear",
        "a_paused_to_done": "Back from Shutdown",
        "a_completion_spree": "Completion Overdrive",
        "a_multi_rewatch": "Multi-Core Replay",
        "a_dropped_recovery": "Recovered from Heap",
        "a_ten_perfect_scores": "Ten Perfect Marks",
        "a_seasonal_clear": "Seasonal Circuit Clear",
        "a_complete_genre_span": "All-Terrain Cyborg",
        "a_monthly_completions": "Monthly Kill Reports",
        "a_yearly_completions": "Yearly Campaign Won",
        "a_rapid_complete": "Lightning Refit Done",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Scrapyard Soul",
        "a_studio_devotee": "Workshop Devotee",
        "a_rewatcher": "Recon Rewatch",
        "a_triple_rewatch": "Triple Circuit Rewatch",
        "a_annual_tradition": "Annual Remembrance",
        "a_director_fan": "Kishiro's Vision",
        "a_voice_actor_fan": "Voice of Alita",
        "a_ost_lover": "Iron Anthem Lover",
        "a_source_reader": "Original Manga Reader",
        "a_waiting_weekly": "Weekly Signal Wait",
        "a_childhood_revisit": "Return to Scrapyard",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Class Loyalty Badge",
        "a_decade_watcher": "Decade-Long Hunter",
        "a_adaptation_hunter": "Adaptation Recon",
        "a_original_anime_fan": "Original Broadcast Vet",
        "a_long_commitment": "Long-Term Garrison",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Allied Forges",
        "a_complete_catalog": "Complete Scrap Catalog",
        "a_franchise_collector": "Alita Universe Hoard",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Mastery Won",
        "a_staff_follower": "Staff Dossier Track",
        "a_multi_season_fan": "Multi-Season Veteran",
        "a_format_diversity": "Diverse Formats",
        "a_year_dedication": "Year of Dedication",
        "a_season_dedication": "Season of Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Unknown Territory Scout",
        "a_studio_hopper": "Workshop Transfer",
        "a_tag_explorer": "Tag Recon Mission",
        "a_decade_hopper": "Decade Time-Jump",
        "a_hidden_gem": "Hidden Relic Found",
        "a_popular_taste": "Popular Among Hunters",
        "a_retro_appreciator": "Pre-Fall Appreciator",
        "a_modern_viewer": "Modern Cyborg Viewer",
        "a_cross_demographic": "Cross-Class Scout",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Week of Variety",
        "a_foreign_cinema": "Foreign Intel Cinema",
        "a_classic_connoisseur": "Classic War Relic",
        "a_every_season": "Every Season Active",
        "a_award_winner": "Medal of Chrome",
        "a_niche_explorer": "Niche Zone Explorer",
        "a_global_anime": "Global Alliance Entry",
        "a_cult_classic": "Underground Classic",
        "a_random_pick": "Random Scrap Draw",
        "a_new_genre_month": "New Terrain Monthly",
        "a_seasonal_completionist": "Seasonal Circuit Done",
        "a_unpopular_opinion": "Unpopular Calibration",
        "a_top_rated_viewer": "Top-Rated Source",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Junk Dive",
        "a_upcoming_watcher": "Upcoming Op Intel",
        "a_short_series_explorer": "Short Bout Explorer",
        "a_long_series_explorer": "Long Campaign Scout",

        // ── ANIME TIME ──
        "a_night_owl": "Night Shift Cyborg",
        "a_early_bird": "Dawn Patrol",
        "a_lunch_break": "Refit Break",
        "a_golden_hour": "Golden Spark Hour",
        "a_four_am_club": "4 AM Sentry Bot",
        "a_witching_hour": "Berserker Hour",
        "a_new_year_watch": "New Year's Iron Oath",
        "a_midnight_premiere": "Midnight Deployment",
        "a_all_hours": "All-Hours Cyborg",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Refit",
        "a_prime_time": "Prime Time Bout",
        "a_workday_watcher": "On-Duty Watcher",
        "a_sunday_marathon": "Sunday Arena Run",
        "a_rainy_day": "Rainy Scrapyard Day",
        "a_morning_routine": "Morning Calibration",
        "a_night_shift": "Night Shift Forge",
        "a_twilight_zone": "Twilight Below Zalem",
        "a_seasonal_premier": "Season Premiere Bout",
        "a_clock_collector": "Clock Gear Collector",
        "a_weekend_binge_hours": "Weekend Binge Ops",
        "a_late_night_regular": "Late Night Patrol",
        "a_sunrise_watcher": "Sunrise Over Scrap",
        "a_holiday_watcher": "Holiday Guard Shift",
        "a_every_day_of_week": "Every Day Deployed",
        "a_monthly_hours": "Monthly Duty Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Squad Formed",
        "a_party_host": "Arena Commander",
        "a_social_butterfly": "Scrapyard Socialite",
        "a_group_binge": "Group Assault Run",
        "a_party_regular": "Regular Sparring",
        "a_sync_viewer": "Synced Maneuver",
        "a_commentator": "Fight Commentator",
        "a_party_marathon": "Marathon Formation",
        "a_full_house": "Full Squad Ready",
        "a_community_pillar": "Pillar of Scrapyard",
        "a_watch_party_streak": "Formation Streak",
        "a_diverse_party": "Diverse Squad Party",
        "a_late_night_party": "Late Night Brawl",
        "a_party_veteran": "Veteran Squad Lead",
        "a_genre_party": "Cross-Genre Squad",
        "a_weekly_party": "Weekly Gathering",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Hunter's Referral",
        "a_party_completionist": "Party Op Complete",
        "a_social_scorer": "Social Combat Score",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Kill",
        "a_fibonacci": "Fibonacci Sequence",
        "a_palindrome_day": "Palindrome Rift",
        "a_binary_day": "Binary Signal Day",
        "a_full_moon": "Full Moon Berserker",
        "a_leap_year": "Leap Year Skip",
        "a_time_traveler": "Time-Core Memory",
        "a_genre_clash": "Cyborg Genre Clash",
        "a_triple_seven": "Triple Seven Chrome",
        "a_thousand_complete": "Thousand Battles Won",
        "a_pi_episodes": "Pi Calculation",
        "a_synchronicity": "Neural Synchronicity",
        "a_world_record": "World Record Kill",
        "a_nice": "Nice Kill Count",
        "a_power_level": "Berserker Power",
        "a_answer_42": "Answer to Zalem",
        "a_square_number": "Perfect Formation",
        "a_prime_count": "Prime Scrap Count",
        "a_matching_date": "Matching Date Intel",
        "a_century_episode": "Century Episode Hit",
        "a_double_digits": "Double Digit Kills",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Seven Lucky Scraps",
        "a_all_tens": "All Tens Score",
        "a_exact_hundred_eps": "Exact Hundred Bouts",
        "a_year_match_count": "Year Match Kills",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Scout",
        "a_movie_buff": "Cyborg Film Ops",
        "a_ova_hunter": "OVA Relic Hunter",
        "a_ona_explorer": "ONA Scout Run",
        "a_special_watcher": "Special Operative",
        "a_short_king": "Short Bout King",
        "a_variety_pack": "All-Format Pack",
        "a_film_festival": "Iron Film Fest",
        "a_music_video": "Chrome Soundtrack",
        "a_tv_short": "Quick Recon Clip",
        "a_movie_marathon": "Movie Blitz Run",
        "a_double_length": "Double-Length Op",
        "a_anthology": "Scrapyard Anthology",
        "a_mini_series": "Mini Campaign Set",
        "a_theatrical": "Theatrical Deploy",
        "a_format_master": "Format Master Scout",
        "a_long_movie": "Feature-Length Hunt",
        "a_back_catalog": "Back Catalog Files",
        "a_cm_watcher": "Commercial Watcher",
        "a_pv_collector": "Preview Collector",
        "a_format_balance": "Balanced Formats",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Film Op",
        "a_recap_watcher": "Recap Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Patrol Streak",
        "a_mega_streak": "Mega Hunt Streak",
        "a_weekly_warrior": "Weekly Arena Warrior",
        "a_monthly_watcher": "Monthly Garrison",
        "a_comeback": "Return from Scrapheap",
        "a_weekend_streak": "Weekend Bout Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will Cyborg",
        "a_habit_formed": "Regimen Formed",
        "a_consistent_pace": "Consistent March",
        "a_year_long": "Year-Long Campaign",
        "a_double_streak": "Double Streak Hit",
        "a_streak_recovery": "Refit Recovery",
        "a_daily_minimum": "Daily Minimum Duty",
        "a_winter_streak": "Winter Forge Streak",
        "a_summer_streak": "Summer Bout Streak",
        "a_morning_streak": "Morning Drill Streak",
        "a_night_streak": "Night Patrol Streak",
        "a_unbreakable": "Unbreakable Chrome",
        "a_eternal_flame": "Eternal Plasma Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak Filed",
        "a_multi_ep_streak": "Multi-Bout Streak",
        "a_genre_streak": "Genre Streak Run",
        "a_studio_streak": "Workshop Streak",
        "a_perfect_week": "Perfect Iron Week",

        // ── ANIME SCORING ──
        "a_critic": "Scrapyard Judge",
        "a_perfect_ten": "Perfect Ten Score",
        "a_harsh_critic": "Harsh Calibration",
        "a_fair_judge": "Ido's Fair Review",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Full Roster Score",
        "a_wide_range": "Wide Range Scan",
        "a_controversial": "Controversial Call",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Precision Sniper",
        "a_evolving_taste": "Evolving Calibration",
        "a_bell_curve": "Bell Curve Scores",
        "a_picky_watcher": "Selective Hunter",
        "a_100_rated": "Century of Ratings",
        "a_500_rated": "Five Hundred Filed",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Variable Scores",
        "a_masterpiece_hunter": "Masterpiece Hunter",
        "a_contrarian": "Contrarian Cyborg",
        "a_optimist": "Optimist Despite Scrap",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Combat Mean",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Iron Vow",
        "a_valentines_weeb": "Valentine's Chrome",
        "a_pi_day": "Pi Day Calc",
        "a_april_fools": "April Fools Prank",
        "a_international_anime_day": "International Cyborg Day",
        "a_star_wars_day": "Tiphares Empire Day",
        "a_summer_solstice": "Summer Solstice Hunt",
        "a_tanabata": "Tanabata Iron Wish",
        "a_friday_13th": "Friday 13th Berserker",
        "a_halloween_spirit": "Halloween Scrapyard",
        "a_thanksgiving_binge": "Harvest Feast Binge",
        "a_christmas_special": "Midwinter Chrome Fest",
        "a_new_years_eve": "New Year's Final Bout",
        "a_birthday_watch": "Birthday Activation",
        "a_holiday_marathon": "Holiday Marathon Hunt",
        "a_independence_day": "Scrapyard Freedom Day",
        "a_culture_day": "Iron Culture Day",
        "a_spring_equinox": "Spring Equinox Drive",
        "a_earth_day": "Protect This World",
        "a_labor_day": "Factory Labor Day",
        "a_winter_solstice": "Winter Solstice Forge",
        "a_anime_birthday": "Anime Anniversary",
        "a_every_holiday": "Every Holiday Cyborg",
        "a_consecutive_holidays": "Consecutive Holidays",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Core Awakened",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Initiation",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Berserker-Class Rank",
        "a_meta_xp_earner": "XP from Hunts",
        "a_meta_difficulty_easy": "Easy Training Run",
        "a_meta_difficulty_hard": "Legendary Berserker",
        "a_meta_unlock_spree": "Unlock Spree Burst",
        "a_meta_completionist": "Meta Completionist",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Scrap Page",
        "m_chapter_counter": "Chapter Salvage Count",
        "m_chapter_titan": "Chapter Titan Bout",
        "m_reading_hours": "Hours Reading Scrap",
        "m_reading_time_lord": "Time-Core Reader",
        "m_manga_collector": "Manga Parts Hoard",
        "m_library_legend": "Ido's Library",
        "m_first_complete": "First Manga Rebuilt",
        "m_hundred_club": "Hundred-Chapter Club",
        "m_first_day": "First Reading Day",
        "m_first_rating": "First Manuscript Score",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Stockpile",
        "m_year_explorer": "Year of Reading",
        "m_century_reader": "Century-Chapter Read",
        "m_five_hundred_ch": "Five Hundred Chapters",
        "m_thousand_ch": "Thousand-Chapter Run",
        "m_reading_ten": "Ten Manuscripts Open",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Jettison",
        "m_season_reader": "Seasonal Rotation",
        "m_active_reader": "Active Field Reader",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Manga Hunts Done",
        "m_fifty_completed": "Fifty Manga Bounties",
        "m_five_hundred_completed": "Five Hundred Wins",
        "m_mean_score_tracker": "Average Manuscript Score",
        "m_unique_authors": "Unique Author Finds",
        "m_all_status": "All Reading Modes",
        "m_first_favorite": "First Manga Bond",
        "m_favorites_collector": "Manga Bonds Arsenal",
        "m_days_spent_reading": "Days in Archives",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading Blitz",
        "m_marathon_reader": "Reading Marathon",
        "m_weekend_reader": "Weekend Archive Dive",
        "m_non_stop_reading": "Non-Stop Page Turn",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Read Burst",
        "m_double_story": "Double Story Hit",
        "m_triple_read": "Triple Read Assault",
        "m_five_a_day": "Five Reads Daily",
        "m_chapter_chain": "Chapter Chain Drive",
        "m_volume_binge": "Volume Binge Run",
        "m_power_reader": "Power Reader Cyborg",
        "m_half_day_read": "Half-Day Archive Run",
        "m_full_day_read": "Full-Day Manuscript",
        "m_power_weekend": "Power Weekend Read",
        "m_binge_king": "King of Binge Reads",
        "m_no_sleep_read": "All-Night Archive",
        "m_full_series_rush": "Full Series Rush",
        "m_seven_day_challenge": "Seven-Day Intel Run",
        "m_hundred_day_read": "Hundred-Day Reading",
        "m_volume_rush": "Volume Rush Deploy",
        "m_series_sweep": "Series Sweep Clear",
        "m_genre_binge": "Cross-Genre Read",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Tally",
        "m_multi_series_binge": "Multi-Series Front",
        "m_midnight_binge": "Midnight Archive Dig",
        "m_new_year_binge": "New Year's Read Rush",
        "m_forty_eight_hour": "Forty-Eight Hour Read",
        "m_oneshot_binge": "Oneshot Blitz Read",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Manuscript",
        "m_genre_adventure": "Adventure Beyond Scrap",
        "m_genre_comedy": "Comedy in the Heap",
        "m_genre_drama": "Drama of Iron Will",
        "m_genre_fantasy": "Fantasy Imaginos",
        "m_genre_horror": "Horror Manuscript",
        "m_genre_mystery": "Mystery of Zalem",
        "m_genre_romance": "Romance Under Chrome",
        "m_genre_scifi": "Sci-Fi Cyborg Read",
        "m_genre_sol": "Life Below Tiphares",
        "m_genre_sports": "Motorball Manga",
        "m_genre_supernatural": "Supernatural Chrome",
        "m_genre_thriller": "Thriller Intel Read",
        "m_genre_psychological": "Psychological Warfare",
        "m_genre_isekai": "Isekai Scrap World",
        "m_genre_shounen": "Shounen Iron Heart",
        "m_genre_ecchi": "Chrome Charm Read",
        "m_genre_mahou_shoujo": "Plasma Power Read",
        "m_genre_mecha": "Mecha Blueprint Read",
        "m_genre_music": "Iron Song Read",
        "m_tag_isekai_new": "New Scrap World",
        "m_tag_harem": "Squad Bonds Read",
        "m_tag_bl": "Brothers Forged Read",
        "m_tag_gl": "Steel Sisters Read",
        "m_tag_historical": "Tiphares History Read",
        "m_tag_military": "Factory Ops Read",
        "m_tag_school": "Hunter Academy Read",
        "m_tag_martial_arts": "Panzer Kunst Manual",
        "m_tag_vampire": "Blood-Iron Read",
        "m_tag_space": "Beyond Clouds Read",
        "m_tag_parody": "Scrapyard Chibi Read",
        "m_tag_idol": "Iron Angel Read",
        "m_tag_post_apocalyptic": "Post-Fall Read",
        "m_tag_cyberpunk": "Cybernetic Read",
        "m_tag_shoujo": "Gally's Story Read",
        "m_tag_survival": "Survival Read",
        "m_tag_cooking": "Scrapyard Cookbook",
        "m_tag_medical": "Field Medic Read",
        "m_tag_villainess": "Warrior Read",
        "m_tag_samurai": "Blade Master Read",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Full Rebuild",
        "m_mega_completionist": "Supreme Reader",
        "m_completion_rate_50": "Halfway Rebuilt Read",
        "m_completion_rate_75": "Approaching Zenith",
        "m_completion_rate_90": "Near Full Archive",
        "m_no_drop": "No Manuscript Lost",
        "m_long_runner_complete": "Long Run Endurance",
        "m_sequel_chain": "Sequel Chain Read",
        "m_clean_list": "Clean Reading Log",
        "m_from_ptr": "Orders Read",
        "m_reread_master": "Memory Core Reread",
        "m_oneshot_complete": "Oneshot Specialist",
        "m_same_day_start_finish": "Same-Day Read Blitz",
        "m_revival": "Revival by Ido",
        "m_zero_to_hundred": "Scrap to Scholar",
        "m_five_genre_complete": "Five-Genre Read",
        "m_full_collection": "Full Archive Set",
        "m_batch_complete": "Batch Clearance Read",
        "m_paused_to_done": "Back from Hiatus",
        "m_completion_spree": "Completion Barrage",
        "m_format_completionist": "Format Completion",
        "m_catch_up": "Caught Up Serial",
        "m_multi_reread": "Multi-Pass Reread",
        "m_dropped_recovery": "Recovered from Heap",
        "m_ten_perfect_scores": "Ten Perfect Reads",
        "m_complete_genre_span": "All-Genre Reader",
        "m_monthly_completions": "Monthly Read Wins",
        "m_yearly_completions": "Yearly Read Campaign",
        "m_rapid_complete": "Rapid Intel Done",
        "m_author_complete": "Author Works Done",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Archive Reader",
        "m_mangaka_lover": "Kishiro Devotee",
        "m_rereader": "Scout Rereader",
        "m_triple_reread": "Triple Reread Run",
        "m_annual_reread": "Annual Remembrance",
        "m_publisher_fan": "Publisher Ally Fan",
        "m_artist_fan": "Artist Medal Won",
        "m_adaptation_compare": "Manga vs Anime Check",
        "m_source_material_fan": "Source Material Fan",
        "m_waiting_weekly": "Weekly Chapter Wait",
        "m_classic_reader": "Classic Manuscript",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyalty Medal",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "Light Novel Intel",
        "m_original_work": "Original Work Read",
        "m_long_commitment": "Long-Term Commitment",
        "m_up_to_date": "Up-to-Date Reader",
        "m_favorite_mangaka": "Favorite Mangaka",
        "m_complete_portfolio": "Complete Portfolio",
        "m_franchise_collector": "Alita Franchise Hoard",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Mastery Earned",
        "m_multi_series_author": "Multi-Series Fan",
        "m_format_diversity": "Diverse Read Formats",
        "m_year_dedication": "Year Dedicated Read",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Genre Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Territory Scout",
        "m_publisher_hopper": "Publisher Transfer",
        "m_tag_explorer": "Manga Tag Recon",
        "m_decade_hopper": "Decade-Hop Reader",
        "m_hidden_gem": "Hidden Relic Read",
        "m_popular_taste": "Popular Among Readers",
        "m_retro_reader": "Retro Manuscript",
        "m_modern_reader": "Modern Era Reader",
        "m_cross_demographic": "Cross-Class Reader",
        "m_underdog_fan": "Underdog Fan Read",
        "m_variety_week": "Week of Varied Reads",
        "m_manhwa_reader": "Manhwa Intel Read",
        "m_manhua_reader": "Manhua Intel Read",
        "m_classic_connoisseur": "Classic Relic Read",
        "m_award_winner": "Medal-Winning Read",
        "m_niche_explorer": "Niche Zone Reader",
        "m_world_manga": "World Manga Intel",
        "m_cult_classic": "Cult Underground Read",
        "m_random_pick": "Random Scrap Pick",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Read Complete",
        "m_unpopular_opinion": "Unpopular Take",
        "m_top_rated_reader": "Top-Rated Reader",
        "m_source_variety": "Source Variety Read",
        "m_low_score_brave": "Brave Junk Read",
        "m_short_manga_explorer": "Short Manga Scout",
        "m_long_manga_explorer": "Long Manga Scout",
        "m_serialization_explorer": "Serial Explorer Read",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Reader",
        "m_early_bird": "Dawn Patrol Reader",
        "m_lunch_reader": "Refit Break Read",
        "m_commute_reader": "Travel Reader",
        "m_four_am_club": "4 AM Sentry Reader",
        "m_new_year_read": "New Year's Read Oath",
        "m_all_hours": "All-Hours Archive",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Read Marathon",
        "m_morning_routine": "Morning Read Routine",
        "m_night_shift_reader": "Night Shift Reader",
        "m_seasonal_premier_read": "New Release Intel",
        "m_clock_collector": "Clock Gear Read",
        "m_late_night_horror": "Midnight Horror Read",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Read Scout",
        "m_twilight_reader": "Twilight Read",
        "m_midnight_start": "Midnight Read Start",
        "m_weekend_binge_hours": "Weekend Binge Read",
        "m_late_night_regular": "Late Night Regular",
        "m_sunrise_reader": "Sunrise Read",
        "m_every_day_of_week": "Every Day Reading",
        "m_monthly_hours": "Monthly Read Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Kishiro Art Fan",
        "m_webtoon_reader": "Webtoon Intel Read",
        "m_full_color": "Full Color Chrome",
        "m_doujin_reader": "Underground Doujin",
        "m_anthology_reader": "Anthology Read",
        "m_adaptation_reader": "Adaptation Study",
        "m_longstrip_reader": "Vertical Scroll Read",
        "m_4koma_reader": "4-Koma Shorts",
        "m_oneshot_reader": "Oneshot Read",
        "m_format_variety": "Format Variety Read",
        "m_light_novel_reader": "Light Novel Read",
        "m_novel_reader": "Novel Archive Read",
        "m_visual_storyteller": "Visual Narrator",
        "m_colored_classic": "Colored Classic Read",
        "m_webcomic_fan": "Webcomic Fan Read",
        "m_manga_to_anime": "Manga to Anime Check",
        "m_seinen_reader": "Seinen Iron Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Medal-Winning Art",
        "m_debut_work": "Debut Manuscript",
        "m_vertical_scroll": "Vertical Intel Read",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross-Media Intel",
        "m_spinoff_reader": "Spinoff Read",
        "m_remake_reader": "Remake Read",
        "m_collaboration_reader": "Joint Op Read",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read Streak",
        "m_mega_streak": "Mega Read Streak",
        "m_weekly_warrior": "Weekly Read Warrior",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader's Return",
        "m_weekend_streak": "Weekend Read Streak",
        "m_no_zero_days": "No Zero Read Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Read Regimen Formed",
        "m_consistent_pace": "Consistent Read Pace",
        "m_year_long": "Year-Long Read Run",
        "m_double_streak": "Double Read Streak",
        "m_streak_recovery": "Read Streak Recovery",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Read Streak",
        "m_summer_streak": "Summer Read Streak",
        "m_morning_streak": "Morning Read Streak",
        "m_night_streak": "Night Read Streak",
        "m_unbreakable": "Unbreakable Reader",
        "m_eternal_flame": "Eternal Read Flame",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Read Streak",
        "m_completion_streak": "Completion Read Chain",
        "m_rating_streak": "Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Read Week",
        "m_diverse_streak": "Diverse Read Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manuscript Judge",
        "m_perfect_ten": "Perfect Ten Read",
        "m_harsh_critic": "Harsh Read Standards",
        "m_fair_judge": "Ido's Fair Rating",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Full Manuscript Score",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Rating",
        "m_consistent_scorer": "Consistent Read Scorer",
        "m_score_sniper": "Precision Read Sniper",
        "m_evolving_taste": "Evolving Read Taste",
        "m_bell_curve": "Bell Curve Reads",
        "m_picky_reader": "Selective Reader",
        "m_100_rated": "Century Rated Filed",
        "m_500_rated": "Five Hundred Rated",
        "m_mediocre_majority": "Middle Ground Read",
        "m_rating_spree": "Rating Barrage Read",
        "m_score_variance": "Variable Read Scores",
        "m_binge_rater": "Binge Rating Session",
        "m_reread_rerate": "Reread & Re-Rate",
        "m_masterpiece_hunter": "Masterpiece Read",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimist Reader",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Read Critic",
        "m_mean_above_8": "Elite Read Mean",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Read Vow",
        "m_valentines_read": "Valentine's Chrome Read",
        "m_pi_day": "Pi Day Chapter Count",
        "m_april_fools": "April Fools Read",
        "m_international_manga_day": "International Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Solstice Read",
        "m_tanabata": "Tanabata Read Wish",
        "m_friday_13th": "Friday 13th Read",
        "m_halloween_read": "Halloween Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Read Feast",
        "m_christmas_read": "Midwinter Read Fest",
        "m_new_years_eve": "New Year's Eve Read",
        "m_birthday_read": "Birthday Read Gift",
        "m_holiday_marathon": "Holiday Read Marathon",
        "m_independence_day": "Freedom Day Read",
        "m_culture_day": "Culture Day Read",
        "m_spring_equinox": "Spring Equinox Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Winter Solstice Read",
        "m_manga_birthday": "Manga Birthday Read",
        "m_every_holiday_reader": "Every Holiday Reader",
        "m_consecutive_holidays": "Consecutive Holiday Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Read",
        "m_fibonacci": "Fibonacci Chapter",
        "m_palindrome_day": "Palindrome Read Day",
        "m_binary_day": "Binary Read Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven Read",
        "m_thousand_complete": "Thousand Reads Won",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Berserker Chapters",
        "m_answer_42": "Answer to Zalem Read",
        "m_square_number": "Perfect Read Count",
        "m_prime_count": "Prime Chapter Count",
        "m_matching_date": "Matching Read Date",
        "m_century_chapter": "Century Chapter Hit",
        "m_pi_chapters": "Pi Chapter Calc",
        "m_synchronicity": "Neural Sync Read",
        "m_world_record": "World Record Read",
        "m_genre_clash": "Genre Clash Read",
        "m_time_traveler": "Time-Traveling Read",
        "m_double_digits": "Double Digit Read",
        "m_one_two_three": "One Two Three Read",
        "m_lucky_seven": "Seven Lucky Reads",
        "m_exact_hundred_ch": "Exact Hundred Read",
        "m_year_match_count": "Year Match Reads",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Pro",
        "m_manhwa_format": "Manhwa Format Read",
        "m_manhua_format": "Manhua Format Read",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Op",
        "m_doujin_format": "Doujin Format Read",
        "m_novel_format": "Novel Format Read",
        "m_format_master_manga": "Format Master Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Read Core",
        "m_meta_collector": "Reading Badge Hoard",
        "m_meta_category_starter": "Category Start Read",
        "m_meta_tier_climber": "Reading Rank Up",
        "m_meta_tier_max": "Maximum Read Rank",
        "m_meta_xp_earner": "XP from Reading",
        "m_meta_difficulty_easy": "Easy Read Run",
        "m_meta_difficulty_hard": "Legendary Read",
        "m_meta_unlock_spree": "Read Unlock Burst",
        "m_meta_completionist": "Meta Read Complete",
        "m_meta_diverse": "Diverse Read Set",
        "m_meta_dominator": "Meta Read Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#080604",
        primary: "#c8a050",
        secondary: "#9b782d",
        accent: "#5a4614",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        scrap_sparks: { label: "Scrap Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        motorball_trail: { label: "Motorball Trail", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        plasma_glow: { label: "Plasma Glow", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        gear_fragments: { label: "Gear Fragments", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1:   "Scrap",
        5:   "Rebuilt",
        15:  "Hunter-Warrior",
        30:  "Motorball",
        45:  "Panzer Kunst",
        60:  "Berserker",
        80:  "Zalem Rebel",
        100: "Battle Angel",
    },
}
