import { AnimeThemeConfig } from "./types"
import {
    GiCrossedSwords,
    GiBattleAxe,
    GiChainedHeart,
    GiEagleEmblem,
    GiHorseHead,
    GiAnvilImpact,
    GiBullseye,
    GiResize,
    GiMuscleUp,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiSettingsKnobs,
    GiSwordWound,
    GiSkullCrossedBones,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const berserkTheme: AnimeThemeConfig = {
    id: "berserk",
    displayName: "Berserk",
    description: "The Black Swordsman's path. Dark medieval hellscape forged through sacrifice, the Brand, and unrelenting willpower against the God Hand.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "240 190 180",
        "--color-brand-300": "210 140 120",
        "--color-brand-400": "180 80 60",
        "--color-brand-500": "139 0 0",
        "--color-brand-600": "110 0 0",
        "--color-brand-700": "80 0 0",
        "--color-brand-800": "55 0 0",
        "--color-brand-900": "35 0 0",
        "--color-brand-950": "20 0 0",
        "--brand": "139 0 0",
        "--background": "#050201",
        "--paper": "#0d0503",
        "--color-gray-950": "5 2 1",
        "--color-gray-900": "12 5 3",
        "--color-gray-800": "22 10 7",
        "--color-gray-700": "35 18 14",
        "--color-gray-600": "55 30 25",
        "--color-gray-500": "85 55 50",
        "--color-gray-400": "130 105 100",
        "--color-gray-300": "175 155 150",
        "--color-gray-200": "210 195 192",
        "--color-gray-100": "235 225 222",
        "--color-gray-50": "248 243 241",
    },
    sidebarOverrides: {
        "home": { icon: GiCrossedSwords, label: "Midland Outskirts" },
        "schedule": { icon: GiAlarmClock, label: "Eclipse Calendar" },
        "manga": { icon: LuBookOpen, label: "Branded Scrolls" },
        "lists": { icon: GiBattleAxe, label: "Mercenary Roster" },
        "discover": { icon: GiBullseye, label: "Beyond the Darkness" },
        "torrent-list": { icon: GiAnvilImpact, label: "Blacksmith's Cache" },
        "debrid": { icon: GiHorseHead, label: "Horse of the Eclipse" },
        "unmatched": { icon: GiChainedHeart, label: "Branded Lost Souls" },
        "enmasse": { icon: GiResize, label: "Godhand Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Miura's Manuscripts" },
        "auto-downloader": { icon: LuRss, label: "Demon Beacon" },
        "community": { icon: GiEagleEmblem, label: "Band of the Hawk" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Brand of Sacrifice" },
        "achievements": { icon: GiTrophy, label: "Demon Slayer Feats" },
        "theme-manager": { icon: GiPalette, label: "Berserker Armor" },
        "extensions": { icon: BiExtension, label: "Dragonslayer Blade" },
        "sync": { icon: IoCloudOfflineOutline, label: "Skull Knight Link" },
        "settings": { icon: GiSettingsKnobs, label: "Griffith's Command" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Orphan of the Battlefield",
        "a_episode_counter": "Mercenary Kill Count",
        "a_episode_titan": "Apostle-Class Encounter",
        "a_hours_invested": "Hours on the Dark Road",
        "a_time_lord": "Behelit's Cursed Time",
        "a_anime_collector": "Arsenal of the Black Swordsman",
        "a_library_legend": "Flora's Library Legend",
        "a_first_complete": "First Dark Arc Survived",
        "a_hundred_club": "Century of Demon Slaying",
        "a_first_day": "First Day Branded",
        "a_first_rating": "Mercenary Assessment",
        "a_ten_thousand_min": "Ten Thousand Minutes of War",
        "a_season_veteran": "Veteran of Midland",
        "a_year_explorer": "Year in the Darkness",
        "a_century_watcher": "Hundred Episodes of Suffering",
        "a_five_hundred_eps": "Five Hundred Sword Swings",
        "a_thousand_eps": "Thousand Demon Encounters",
        "a_watching_ten": "Ten Battlefronts Watched",
        "a_ptw_hoarder": "Backlog of Blood",
        "a_dropped_honesty": "Strategic Retreat from Hell",
        "a_five_thousand_eps": "Five Thousand Dark Sorties",
        "a_ten_completed": "Ten Dark Campaigns Survived",
        "a_fifty_completed": "Fifty Arcs Conquered",
        "a_five_hundred_completed": "Five Hundred Victories for Guts",
        "a_mean_score_tracker": "Average Combat Rating",
        "a_unique_studios": "Allied Mercenary Bands",
        "a_days_spent_watching": "Days Surviving Midland",
        "a_all_status": "All Deployment Statuses",
        "a_first_favorite": "First Comrade of the Hawk",
        "a_favorites_collector": "Bonds of the Band",
        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Berserk Rampage",
        "a_marathon_runner": "Midland Marathon Runner",
        "a_weekend_warrior": "Weekend Mercenary Run",
        "a_non_stop": "Relentless Like Guts",
        "a_one_more_episode": "One More Chapter of Suffering",
        "a_speed_run": "Dragonslayer Speed Dash",
        "a_double_feature": "Double Eclipse Feature",
        "a_triple_threat": "Triple Apostle Takedown",
        "a_five_a_day": "Five Demons a Day",
        "a_back_to_back": "Back-to-Back Dark Arcs",
        "a_seasonal_binge": "Full Eclipse Arc Clear",
        "a_cour_crusher": "Midland Cour Crusher",
        "a_half_day_watch": "Half Day on the Battlefield",
        "a_full_day_watch": "Full Day of Darkness",
        "a_power_weekend": "Power Weekend Offensive",
        "a_binge_king": "King of the Berserkers",
        "a_no_sleep": "All-Night Brand Vigil",
        "a_entire_season": "Full Dark Arc Clear",
        "a_seven_day_challenge": "Seven-Day Darkness Siege",
        "a_hundred_day_binge": "Hundred-Day Demon Siege",
        "a_genre_binge": "Cross-Genre Dark Fantasy",
        "a_studio_binge": "Studio Alliance Binge",
        "a_season_sweep": "Season Sweep of Blood",
        "a_forty_eight_hour": "Forty-Eight Hour Darkness",
        "a_ep_counter_day": "Daily Sword Strike Count",
        "a_multi_series_binge": "Multi-Front Dark Campaign",
        "a_midnight_binge": "Midnight Brand Session",
        "a_new_year_binge": "New Year's Demon Charge",
        // ── ANIME GENRES ──
        "a_genre_action": "Black Swordsman Combat",
        "a_genre_adventure": "Journey Through Midland",
        "a_genre_comedy": "Puck's Comic Relief",
        "a_genre_drama": "Guts and Griffith Drama",
        "a_genre_fantasy": "God Hand Realm",
        "a_genre_horror": "Eclipse Horror Night",
        "a_genre_mystery": "Behelit's Secret Purpose",
        "a_genre_romance": "Guts and Casca Bond",
        "a_genre_scifi": "Apostle Bio-Weapon",
        "a_genre_sol": "Peaceful Days in the Band",
        "a_genre_sports": "Melee Training Grounds",
        "a_genre_supernatural": "Berserker Armor Curse",
        "a_genre_thriller": "Apostle Chase Thriller",
        "a_genre_mecha": "Mechanical Arm Upgrade",
        "a_genre_music": "Susumu Hirasawa Aria",
        "a_genre_psychological": "Griffith's Inner War",
        "a_genre_ecchi": "Hot Spring Reprieve",
        "a_genre_mahou_shoujo": "Schierke's Witchcraft",
        "a_tag_isekai": "Transported to Midland",
        "a_tag_harem": "Band of the Hawk Bonds",
        "a_tag_bl": "Guts and Griffith Brotherhood",
        "a_tag_gl": "Casca's Shield Sisters",
        "a_tag_historical": "Medieval Midland History",
        "a_tag_military": "Mercenary Military Arts",
        "a_tag_school": "Gambino's Training Camp",
        "a_tag_martial_arts": "Guts' Sword Mastery",
        "a_tag_vampire": "Nosferatu Zodd's Blood",
        "a_tag_samurai": "Eastern Dojo Style",
        "a_tag_space": "Godhand's Dimension",
        "a_tag_parody": "Skull Knight Parody",
        "a_tag_idol": "Griffith's Charisma",
        "a_tag_post_apocalyptic": "Post-Eclipse World",
        "a_tag_cyberpunk": "Mechanical Arm Tech",
        "a_tag_shounen": "Guts' Determined Heart",
        "a_tag_seinen": "Berserk Seinen Reality",
        "a_tag_shoujo": "Casca's Devotion",
        "a_tag_josei": "Jill's Perspective",
        "a_tag_survival": "Surviving the Eclipse",
        // ── ANIME COMPLETION ──
        "a_completionist": "Full Berserk Arc Report",
        "a_mega_completionist": "Skull Knight Commander",
        "a_completion_rate_50": "Halfway to the Eclipse",
        "a_completion_rate_75": "Approaching Griffith's Betrayal",
        "a_completion_rate_90": "Final Brand Nearly Set",
        "a_no_drop": "No Comrade Left Behind",
        "a_long_runner_complete": "Long Dark Journey Complete",
        "a_sequel_chain": "Arc Chain of Causality",
        "a_clean_list": "Clean Mercenary Record",
        "a_from_ptw": "Orders Received and Executed",
        "a_rewatch_master": "Reliving the Eclipse",
        "a_short_complete": "Quick Skirmish Won",
        "a_same_day_start_finish": "Same-Day Demon Elimination",
        "a_revival": "Revived by Skull Knight",
        "a_zero_to_hero": "Orphan to Black Swordsman",
        "a_five_genre_complete": "Five-Genre Dark Mastery",
        "a_full_franchise": "Full Berserk Dossier",
        "a_batch_complete": "Batch Darkness Clear",
        "a_paused_to_done": "Returned from Injury",
        "a_completion_spree": "Completion Dragonslayer Swing",
        "a_multi_rewatch": "Multi-Timeline via Behelit",
        "a_dropped_recovery": "Recovered from Apostle's Jaw",
        "a_ten_perfect_scores": "Ten Perfect Combat Scores",
        "a_seasonal_clear": "Seasonal Darkness Clear",
        "a_complete_genre_span": "All-Terrain Dark Knight",
        "a_monthly_completions": "Monthly Mission Reports",
        "a_yearly_completions": "Yearly Campaign Victor",
        "a_rapid_complete": "Lightning Raid Complete",
        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Berserk Devotee",
        "a_studio_devotee": "Studio Dark Devotee",
        "a_rewatcher": "Eclipse Recon Rewatch",
        "a_triple_rewatch": "Triple Dark Rewatch",
        "a_annual_tradition": "Annual Remembrance of Casca",
        "a_director_fan": "Miura's Vision Follower",
        "a_voice_actor_fan": "Voice of the Swordsman",
        "a_ost_lover": "Forces of Darkness OST",
        "a_source_reader": "Miura's Original Manga",
        "a_waiting_weekly": "Weekly Hiatus Wait",
        "a_childhood_revisit": "Return to the Band",
        "a_saga_tracker": "Saga of the Brand Tracker",
        "a_genre_loyalty": "Dark Fantasy Loyalty",
        "a_decade_watcher": "Decade-Long Black Swordsman",
        "a_adaptation_hunter": "Berserk Adaptation Hunt",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Midland Duty",
        "a_perfect_attendance": "Perfect Band Attendance",
        "a_favorite_studio_5": "Five Allied Dark Studios",
        "a_complete_catalog": "Complete Dark Catalog",
        "a_franchise_collector": "Berserk Universe Collector",
        "a_airing_follower": "Currently Airing Dark Intel",
        "a_genre_master": "Dark Fantasy Mastery",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Arc Dark Veteran",
        "a_format_diversity": "Diverse Dark Formats",
        "a_year_dedication": "Year of Dedication to Guts",
        "a_season_dedication": "Season of Unwavering Service",
        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Known Darkness",
        "a_studio_hopper": "Mercenary Band Transfer",
        "a_tag_explorer": "Tag Recon in Darkness",
        "a_decade_hopper": "Time via Behelit",
        "a_hidden_gem": "Hidden Dark Gem",
        "a_popular_taste": "Popular Among Swordsmen",
        "a_retro_appreciator": "Pre-Eclipse Era Appreciator",
        "a_modern_viewer": "Modern Dark Fantasy Viewer",
        "a_cross_demographic": "Cross-Demographic Swordsman",
        "a_underdog_fan": "Underdog Black Swordsman",
        "a_variety_week": "Week of Varied Darkness",
        "a_foreign_cinema": "Foreign Darkness Cinema",
        "a_classic_connoisseur": "Classic Dark Fantasy Fan",
        "a_every_season": "Every Season in Darkness",
        "a_award_winner": "Medal of Dark Valor",
        "a_niche_explorer": "Niche Darkness Explorer",
        "a_global_anime": "Global Dark Alliance",
        "a_cult_classic": "Berserk Cult Classic",
        "a_random_pick": "Random Dark Assignment",
        "a_new_genre_month": "New Dark Territory Monthly",
        "a_seasonal_completionist": "Seasonal Dark Campaign Clear",
        "a_unpopular_opinion": "Unpopular Eclipse Opinion",
        "a_top_rated_viewer": "Top-Rated Dark Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Dark Intel",
        "a_short_series_explorer": "Short Dark Skirmish Explorer",
        "a_long_series_explorer": "Long Dark Campaign Explorer",
        // ── ANIME TIME ──
        "a_night_owl": "Night Watch in Midland",
        "a_early_bird": "Dawn on the Battlefield",
        "a_lunch_break": "Camp Meal Break",
        "a_golden_hour": "Golden Hour Before Eclipse",
        "a_four_am_club": "4 AM Brand Burning",
        "a_witching_hour": "Apostle Witching Hour",
        "a_new_year_watch": "New Year's Oath to Survive",
        "a_midnight_premiere": "Midnight Darkness Premiere",
        "a_all_hours": "All-Hours Dark Vigil",
        "a_dawn_warrior": "Dawn Warrior of Midland",
        "a_afternoon_delight": "Afternoon Mercenary Rest",
        "a_prime_time": "Prime Time Dark Engagement",
        "a_workday_watcher": "On-Duty Dark Watcher",
        "a_sunday_marathon": "Sunday Eclipse Marathon",
        "a_rainy_day": "Rainy Day in Midland",
        "a_morning_routine": "Morning Mercenary Formation",
        "a_night_shift": "Night Shift Brand Guard",
        "a_twilight_zone": "Twilight Beyond Casca's Mind",
        "a_seasonal_premier": "Season Premiere in Darkness",
        "a_clock_collector": "Clock Tower of Wyndham",
        "a_weekend_binge_hours": "Weekend Dark Binge Ops",
        "a_late_night_regular": "Late Night Regular in Midland",
        "a_sunrise_watcher": "Sunrise Over the Ruins",
        "a_holiday_watcher": "Holiday Darkness Duty",
        "a_every_day_of_week": "Every Day Branded",
        "a_monthly_hours": "Monthly Dark Duty Hours",
        // ── ANIME SOCIAL ──
        "a_first_party": "First Band Formation",
        "a_party_host": "Band of the Hawk Commander",
        "a_social_butterfly": "Camp Fire Socialite",
        "a_group_binge": "Group Eclipse Viewing",
        "a_party_regular": "Regular Sparring Partner",
        "a_sync_viewer": "Synchronized Sword Maneuver",
        "a_commentator": "Battle Commentator of Midland",
        "a_party_marathon": "Marathon Band Run",
        "a_full_house": "Full Band of the Hawk",
        "a_community_pillar": "Pillar of the Mercenaries",
        "a_watch_party_streak": "Consecutive Band Streak",
        "a_diverse_party": "Diverse Mercenary Party",
        "a_late_night_party": "Late Night Barracks Party",
        "a_party_veteran": "Veteran Squad Leader",
        "a_genre_party": "Cross-Genre Dark Formation",
        "a_weekly_party": "Weekly Comrades' Gathering",
        "a_silent_viewer": "Silent Like Guts Observer",
        "a_recommendation_giver": "Black Swordsman's Recommendation",
        "a_party_completionist": "Party Operation Completionist",
        "a_social_scorer": "Social Dark Scorer",
        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Formation",
        "a_fibonacci": "Fibonacci Demon Sequence",
        "a_palindrome_day": "Palindrome Causality Loop",
        "a_binary_day": "Binary Brand Signal Day",
        "a_full_moon": "Full Moon Apostle Form",
        "a_leap_year": "Leap Year Causality Skip",
        "a_time_traveler": "Behelit's Time Memory",
        "a_genre_clash": "Guts vs God Hand Clash",
        "a_triple_seven": "Triple Seven Apostles",
        "a_thousand_complete": "Thousand Battles for Guts",
        "a_pi_episodes": "Pi Causality Calculation",
        "a_synchronicity": "Brand Synchronicity",
        "a_world_record": "World Record Demon Kill",
        "a_nice": "Nice Kill Count",
        "a_power_level": "Guts Power Level",
        "a_answer_42": "Answer to Causality",
        "a_square_number": "Perfect Sword Formation",
        "a_prime_count": "Prime Apostles Slain",
        "a_matching_date": "Matching Eclipse Date",
        "a_century_episode": "Century Episode Darkness",
        "a_double_digits": "Double Digit Kills",
        "a_one_two_three": "Guts Griffith Casca",
        "a_lucky_seven": "Seven Lucky Swordsmen",
        "a_all_tens": "All Tens Combat Score",
        "a_exact_hundred_eps": "Exact Hundred Engagements",
        "a_year_match_count": "Year Match Kill Count",
        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Swordsman",
        "a_movie_buff": "Golden Age Film Arc",
        "a_ova_hunter": "OVA Dark Hunter",
        "a_ona_explorer": "ONA Dark Explorer",
        "a_special_watcher": "Special Episode Darkness",
        "a_short_king": "Short Skirmish King",
        "a_variety_pack": "All-Format Dark Regiment",
        "a_film_festival": "Dark Fantasy Film Festival",
        "a_music_video": "Forces Music Video",
        "a_tv_short": "Quick Dark Recon Clip",
        "a_movie_marathon": "Movie Marathon Darkness",
        "a_double_length": "Double-Length Dark Operation",
        "a_anthology": "Berserk Dark Anthology",
        "a_mini_series": "Mini Dark Campaign",
        "a_theatrical": "Theatrical Darkness Premiere",
        "a_format_master": "Format Master Swordsman",
        "a_long_movie": "Feature-Length Dark Expedition",
        "a_back_catalog": "Back Catalog of Midland",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Darkness Collector",
        "a_format_balance": "Balanced Dark Formats",
        "a_episodic_master": "Episodic Dark Master",
        "a_sequel_movie": "Sequel Darkness Film",
        "a_recap_watcher": "Recap Darkness Briefing",
        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Dark Patrol Streak",
        "a_mega_streak": "Mega Dark Campaign Streak",
        "a_weekly_warrior": "Weekly Dark Warrior",
        "a_monthly_watcher": "Monthly Dark Duty",
        "a_comeback": "Return from the Eclipse",
        "a_weekend_streak": "Weekend Dark Sortie Streak",
        "a_no_zero_days": "No Zero Dark Days",
        "a_iron_will": "Iron Will of the Black Swordsman",
        "a_habit_formed": "Dark Training Regimen Formed",
        "a_consistent_pace": "Consistent March into Darkness",
        "a_year_long": "Year-Long Dark Campaign",
        "a_double_streak": "Double Dark Assault Streak",
        "a_streak_recovery": "Recovery After Eclipse",
        "a_daily_minimum": "Daily Minimum Dark Duty",
        "a_winter_streak": "Winter Dark Campaign",
        "a_summer_streak": "Summer Dark Offensive",
        "a_morning_streak": "Morning Dark Drill Streak",
        "a_night_streak": "Night Dark Patrol Streak",
        "a_unbreakable": "Unbreakable Will of Guts",
        "a_eternal_flame": "Eternal Flame of Survival",
        "a_completion_streak": "Completion Dark Chain",
        "a_rating_streak": "Rating Dark Streak",
        "a_multi_ep_streak": "Multi-Episode Dark Offensive",
        "a_genre_streak": "Genre Dark Streak",
        "a_studio_streak": "Studio Loyalty Dark Streak",
        "a_perfect_week": "Perfect Week of Darkness",
        // ── ANIME SCORING ──
        "a_critic": "Dark Tribunal Judge",
        "a_perfect_ten": "Perfect 10 Dark Rating",
        "a_harsh_critic": "Guts' Harsh Standards",
        "a_fair_judge": "Griffith's Fair Assessment",
        "a_generous_spirit": "Generous Mercenary Spirit",
        "a_score_all": "Full Dark Roster Evaluation",
        "a_wide_range": "Wide Range Dark Assessment",
        "a_controversial": "Controversial Dark Decision",
        "a_consistent_scorer": "Consistent Dark Evaluator",
        "a_score_sniper": "Precision Dark Sniper",
        "a_evolving_taste": "Evolving Dark Strategy",
        "a_bell_curve": "Bell Curve Dark Scores",
        "a_picky_watcher": "Selective Dark Commander",
        "a_100_rated": "Century of Dark Evaluations",
        "a_500_rated": "Five Hundred Dark Reports",
        "a_mediocre_majority": "Middle Ground Dark Strategist",
        "a_rating_spree": "Dark Rating Barrage",
        "a_score_variance": "Variable Dark Ratings",
        "a_masterpiece_hunter": "Masterpiece Dark Hunter",
        "a_contrarian": "Contrarian Dark Scout",
        "a_optimist": "Optimist Despite the Eclipse",
        "a_score_distributor": "Score Distributor General",
        "a_genre_critic": "Genre Dark Critic",
        "a_mean_above_8": "Elite Dark Average",
        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow to Survive",
        "a_valentines_weeb": "Valentine's Dark Bond",
        "a_pi_day": "Pi Day Causality Calc",
        "a_april_fools": "April Fools Eclipse Prank",
        "a_international_anime_day": "International Swordsman Day",
        "a_star_wars_day": "Midland Empire Day",
        "a_summer_solstice": "Summer Solstice Dark Expedition",
        "a_tanabata": "Tanabata Wish for Casca",
        "a_friday_13th": "Friday the 13th Eclipse",
        "a_halloween_spirit": "Halloween Apostle Horror",
        "a_thanksgiving_binge": "Thanksgiving Dark Feast",
        "a_christmas_special": "Midwinter Dark Festival",
        "a_new_years_eve": "New Year's Eve Last Stand",
        "a_birthday_watch": "Birthday Dark Enlistment",
        "a_holiday_marathon": "Holiday Dark Marathon",
        "a_independence_day": "Midland Independence Day",
        "a_culture_day": "Midland Culture Day",
        "a_spring_equinox": "Spring Dark Advance",
        "a_earth_day": "Protect the World from Apostles",
        "a_labor_day": "Mercenary Labor Day",
        "a_winter_solstice": "Winter Solstice Darkness",
        "a_anime_birthday": "Berserk Anniversary",
        "a_every_holiday": "Every Holiday Dark Scout",
        "a_consecutive_holidays": "Consecutive Holiday Darkness",
        // ── ANIME META ──
        "a_meta_first_unlock": "First Dark Power Awakened",
        "a_meta_collector": "Mercenary Badge Collector",
        "a_meta_category_starter": "Category Initiation Eclipse",
        "a_meta_tier_climber": "Rank in the Band",
        "a_meta_tier_max": "Captain-Class Swordsman",
        "a_meta_xp_earner": "XP from Demon Kills",
        "a_meta_difficulty_easy": "Easy Training Exercise",
        "a_meta_difficulty_hard": "Legendary Skullknight Mode",
        "a_meta_unlock_spree": "Unlock Spree Dark Slash",
        "a_meta_completionist": "Meta Dark Completionist",
        "a_meta_diverse": "Diverse Dark Portfolio",
        "a_meta_dominator": "Meta Dominator of Darkness",
        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter of Darkness",
        "m_chapter_counter": "Chapter Dark Counter",
        "m_chapter_titan": "Chapter Apostle Assault",
        "m_reading_hours": "Hours Studying Dark Arts",
        "m_reading_time_lord": "Behelit's Reading Memory",
        "m_manga_collector": "Dark Archive Collector",
        "m_library_legend": "Flora's Archive Legend",
        "m_first_complete": "First Dark Manga Done",
        "m_hundred_club": "Hundred-Chapter Dark Club",
        "m_first_day": "First Day Dark Reading",
        "m_first_rating": "First Dark Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Darkness",
        "m_volume_collector": "Dark Volume Collector",
        "m_year_explorer": "Year of Dark Exploration",
        "m_century_reader": "Century Dark Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Dark Chapters",
        "m_thousand_ch": "Thousand-Chapter Dark Campaign",
        "m_reading_ten": "Ten Dark Manuscripts at Once",
        "m_ptr_hoarder": "Dark Backlog Hoarder",
        "m_dropped_honesty": "Honest Dark Retreat",
        "m_season_reader": "Dark Seasonal Reading",
        "m_active_reader": "Active Dark Field Reader",
        "m_five_thousand_ch": "Five Thousand Dark Chapters",
        "m_ten_completed": "Ten Dark Manga Complete",
        "m_fifty_completed": "Fifty Dark Missions Done",
        "m_five_hundred_completed": "Five Hundred Dark Victories",
        "m_mean_score_tracker": "Average Dark Manuscript Rating",
        "m_unique_authors": "Unique Dark Author Encounters",
        "m_all_status": "All Dark Reading Statuses",
        "m_first_favorite": "First Dark Manga Bond",
        "m_favorites_collector": "Dark Favorites Arsenal",
        "m_days_spent_reading": "Days in the Dark Garrison",
        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Dark Reading Advance",
        "m_marathon_reader": "Midland Marathon Reader",
        "m_weekend_reader": "Weekend Dark Reading",
        "m_non_stop_reading": "Non-Stop Dark Page Turning",
        "m_one_more_chapter": "One More Dark Chapter",
        "m_speed_read": "Dragonslayer Speed Read",
        "m_double_story": "Double Dark Manuscript",
        "m_triple_read": "Triple Dark Reading",
        "m_five_a_day": "Five Dark Reads a Day",
        "m_chapter_chain": "Dark Chapter Chain",
        "m_volume_binge": "Dark Volume Binge",
        "m_power_reader": "Power Dark Reader",
        "m_half_day_read": "Half-Day Dark Archive",
        "m_full_day_read": "Full-Day Dark Study",
        "m_power_weekend": "Power Dark Weekend Reading",
        "m_binge_king": "King of the Dark Reading Corps",
        "m_no_sleep_read": "All-Night Dark Reading",
        "m_full_series_rush": "Full Dark Series Rush",
        "m_seven_day_challenge": "Seven-Day Dark Gathering",
        "m_hundred_day_read": "Hundred-Day Dark Reading",
        "m_volume_rush": "Dark Volume Rush",
        "m_series_sweep": "Dark Series Sweep",
        "m_genre_binge": "Cross-Genre Dark Reading",
        "m_author_binge": "Miura Deep Dive",
        "m_chapter_counter_day": "Daily Dark Chapter Count",
        "m_multi_series_binge": "Multi-Series Dark Reading",
        "m_midnight_binge": "Midnight Dark Archive",
        "m_new_year_binge": "New Year's Dark Reading",
        "m_forty_eight_hour": "Forty-Eight Hour Dark Reading",
        "m_oneshot_binge": "Oneshot Dark Blitz",
        // ── MANGA GENRES ──
        "m_genre_action": "Dark Action Manuscript",
        "m_genre_adventure": "Adventure Beyond Midland",
        "m_genre_comedy": "Puck's Comic Chapters",
        "m_genre_drama": "Drama of the Eclipse",
        "m_genre_fantasy": "Fantasy of the God Hand",
        "m_genre_horror": "Apostle Horror Manuscript",
        "m_genre_mystery": "Mystery of the Behelit",
        "m_genre_romance": "Guts and Casca Bond",
        "m_genre_scifi": "Apostle Technology Manga",
        "m_genre_sol": "Peaceful Band Moments",
        "m_genre_sports": "Mercenary Training Sports",
        "m_genre_supernatural": "Supernatural Berserker Manga",
        "m_genre_thriller": "Thriller Dark Chase",
        "m_genre_psychological": "Psychological Dark Warfare",
        "m_genre_isekai": "Isekai Beyond Midland",
        "m_genre_shounen": "Dark Shounen Heart",
        "m_genre_ecchi": "Hot Springs Dark Chapter",
        "m_genre_mahou_shoujo": "Schierke's Witchcraft Manga",
        "m_genre_mecha": "Mechanical Arm Blueprints",
        "m_genre_music": "Susumu Hirasawa Folk Songs",
        "m_tag_isekai_new": "New World Beyond Darkness",
        "m_tag_harem": "Band of the Hawk Manga",
        "m_tag_bl": "Brothers in Dark Arms",
        "m_tag_gl": "Shield Sisters Dark Manga",
        "m_tag_historical": "Midland History Manga",
        "m_tag_military": "Mercenary Operations Manga",
        "m_tag_school": "Gambino's Training Manga",
        "m_tag_martial_arts": "Guts' Combat Manual",
        "m_tag_vampire": "Dark Blood Manga",
        "m_tag_samurai": "Eastern Blade Master",
        "m_tag_space": "God Hand's Realm Manga",
        "m_tag_parody": "Chibi Dark Corps Manga",
        "m_tag_idol": "Griffith Charisma Manga",
        "m_tag_post_apocalyptic": "Post-Eclipse Manga",
        "m_tag_cyberpunk": "Mechanical Technology Manga",
        "m_tag_shoujo": "Casca's Story Manga",
        "m_tag_survival": "Survival in Darkness Manga",
        "m_tag_cooking": "Camp Rations Cookbook",
        "m_tag_medical": "Field Medic Dark Manga",
        "m_tag_villainess": "Rakshas Dark Manga",
        // ── MANGA COMPLETION ──
        "m_completionist": "Dark Manga Completionist",
        "m_mega_completionist": "Supreme Dark Commander",
        "m_completion_rate_50": "Halfway to Eclipse Truth",
        "m_completion_rate_75": "Approaching Berserker Armor",
        "m_completion_rate_90": "Final Dark Chapter Near",
        "m_no_drop": "No Dark Manuscript Abandoned",
        "m_long_runner_complete": "Long Dark Series Endurance",
        "m_sequel_chain": "Sequel Dark Arc Chain",
        "m_clean_list": "Clean Dark Reading Record",
        "m_from_ptr": "Orders Received Dark Read",
        "m_reread_master": "Eclipse Memory Reread",
        "m_oneshot_complete": "Oneshot Dark Mission",
        "m_same_day_start_finish": "Same-Day Dark Blitz",
        "m_revival": "Revival Through Dark Paths",
        "m_zero_to_hundred": "Orphan to Dark Scholar",
        "m_five_genre_complete": "Five Dark Genres Mastered",
        "m_full_collection": "Full Dark Archive",
        "m_batch_complete": "Dark Batch Clearance",
        "m_paused_to_done": "Back from Dark Hiatus",
        "m_completion_spree": "Dark Completion Barrage",
        "m_format_completionist": "Dark Format Completion",
        "m_catch_up": "Caught Up with Darkness",
        "m_multi_reread": "Multi-Pass Dark Reread",
        "m_dropped_recovery": "Recovered from Eclipse Rubble",
        "m_ten_perfect_scores": "Ten Perfect Dark Scores",
        "m_complete_genre_span": "All-Genre Dark Scout",
        "m_monthly_completions": "Monthly Dark Victories",
        "m_yearly_completions": "Yearly Dark Campaign",
        "m_rapid_complete": "Rapid Dark Processing",
        "m_author_complete": "Miura's Complete Works",
        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Dark Reader",
        "m_mangaka_lover": "Miura Devotee",
        "m_rereader": "Eclipse Rereader",
        "m_triple_reread": "Triple Dark Reread",
        "m_annual_reread": "Annual Eclipse Reread",
        "m_publisher_fan": "Dark Publisher Fan",
        "m_artist_fan": "Miura Art Appreciation",
        "m_adaptation_compare": "Dark Manga vs Anime Compare",
        "m_source_material_fan": "Dark Source Material Scout",
        "m_waiting_weekly": "Weekly Dark Chapter Wait",
        "m_classic_reader": "Classic Dark Manuscript",
        "m_saga_reader": "Saga of the Brand Reader",
        "m_genre_loyalty": "Dark Genre Loyalty",
        "m_decade_reader": "Decade-Long Dark Reader",
        "m_ln_adaptation": "Dark Light Novel Intel",
        "m_original_work": "Miura's Original Dark Work",
        "m_long_commitment": "Long-Term Dark Reading",
        "m_up_to_date": "Up-to-Date Dark Serialization",
        "m_favorite_mangaka": "Miura Honored",
        "m_complete_portfolio": "Complete Dark Portfolio",
        "m_franchise_collector": "Berserk Franchise Collector",
        "m_serialization_follower": "Dark Serialization Tracker",
        "m_genre_master": "Dark Genre Mastery",
        "m_multi_series_author": "Multi-Series Dark Author Fan",
        "m_format_diversity": "Diverse Dark Reading Formats",
        "m_year_dedication": "Year of Dark Reading",
        "m_ongoing_follower": "Ongoing Dark Series",
        "m_genre_loyalty_50": "Fifty Dark Genre Chapters",
        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Dark Genre Territory Scout",
        "m_publisher_hopper": "Dark Publisher Transfer",
        "m_tag_explorer": "Dark Tag Recon Mission",
        "m_decade_hopper": "Dark Decade Hopping",
        "m_hidden_gem": "Hidden Dark Gem",
        "m_popular_taste": "Popular Among Dark Recruits",
        "m_retro_reader": "Retro Dark Manuscript",
        "m_modern_reader": "Modern Dark Era Reader",
        "m_cross_demographic": "Cross-Demographic Dark Scout",
        "m_underdog_fan": "Underdog Dark Fan",
        "m_variety_week": "Week of Dark Readings",
        "m_manhwa_reader": "Dark Manhwa Reader",
        "m_manhua_reader": "Dark Manhua Reader",
        "m_classic_connoisseur": "Classic Dark Connoisseur",
        "m_award_winner": "Medal-Winning Dark Manuscript",
        "m_niche_explorer": "Niche Dark Territory",
        "m_world_manga": "World Dark Manga",
        "m_cult_classic": "Berserk Cult Underground",
        "m_random_pick": "Random Dark Assignment",
        "m_new_genre_month": "New Dark Genre Monthly",
        "m_year_completionist": "Year Dark Completionist",
        "m_unpopular_opinion": "Unpopular Dark Opinion",
        "m_top_rated_reader": "Top-Rated Dark Source",
        "m_source_variety": "Dark Source Variety",
        "m_low_score_brave": "Brave Dark Low-Score Reader",
        "m_short_manga_explorer": "Short Dark Skirmish",
        "m_long_manga_explorer": "Long Dark Campaign Manuscript",
        "m_serialization_explorer": "Dark Serialization Explorer",
        // ── MANGA TIME ──
        "m_night_owl": "Night Dark Reading",
        "m_early_bird": "Dawn Dark Reading",
        "m_lunch_reader": "Camp Meal Dark Reading",
        "m_commute_reader": "Dark Commute Reading",
        "m_four_am_club": "4 AM Dark Sentry Reader",
        "m_new_year_read": "New Year's Dark Reading Oath",
        "m_all_hours": "All-Hours Dark Archive",
        "m_prime_time_reader": "Prime Time Dark Manuscript",
        "m_workday_reader": "On-Duty Dark Reader",
        "m_sunday_read": "Sunday Dark Reading Marathon",
        "m_morning_routine": "Morning Dark Formation Reading",
        "m_night_shift_reader": "Night Shift Dark Reader",
        "m_seasonal_premier_read": "Dark New Release Intel",
        "m_clock_collector": "Wyndham Clock Dark Reading",
        "m_late_night_horror": "Midnight Apostle Horror Read",
        "m_afternoon_reader": "Afternoon Dark Reading",
        "m_golden_hour_reader": "Golden Hour Dark Reading",
        "m_dawn_reader": "Dawn Dark Reading Scout",
        "m_twilight_reader": "Twilight Dark Wall Reading",
        "m_midnight_start": "Midnight Dark Reading Mission",
        "m_weekend_binge_hours": "Weekend Dark Binge Reading",
        "m_late_night_regular": "Late Night Dark Reader",
        "m_sunrise_reader": "Sunrise Dark Ruins Reader",
        "m_every_day_of_week": "Every Day Dark Reading",
        "m_monthly_hours": "Monthly Dark Hours Logged",
        "m_bedtime_reader": "Bedtime Dark Reader",
        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Miura Art Appreciator",
        "m_webtoon_reader": "Dark Webtoon Intelligence",
        "m_full_color": "Full Color Dark Manuscript",
        "m_doujin_reader": "Underground Dark Doujin",
        "m_anthology_reader": "Dark Anthology Reader",
        "m_adaptation_reader": "Dark Adaptation Study",
        "m_longstrip_reader": "Vertical Dark Scroll Reader",
        "m_4koma_reader": "4-Koma Dark Comedy",
        "m_oneshot_reader": "Oneshot Dark Mission Reader",
        "m_format_variety": "Dark Format Variety",
        "m_light_novel_reader": "Dark Light Novel Reader",
        "m_novel_reader": "Dark Novel Archive Reader",
        "m_visual_storyteller": "Dark Battle Narrator",
        "m_colored_classic": "Colored Dark Classic",
        "m_webcomic_fan": "Dark Webcomic Fan",
        "m_manga_to_anime": "Dark Manga to Anime",
        "m_seinen_reader": "Seinen Dark Reader",
        "m_josei_reader": "Josei Dark Perspective",
        "m_award_winning_art": "Medal-Winning Dark Artwork",
        "m_debut_work": "Dark Debut Manuscript",
        "m_vertical_scroll": "Vertical Dark Scroll Intel",
        "m_traditional_format": "Traditional Dark Format",
        "m_cross_media": "Dark Cross-Media Intel",
        "m_spinoff_reader": "Dark Spinoff Mission",
        "m_remake_reader": "Dark Remake Assignment",
        "m_collaboration_reader": "Dark Joint Operation Manuscript",
        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Dark Reading Streak",
        "m_mega_streak": "Mega Dark Reading Streak",
        "m_weekly_warrior": "Weekly Dark Warrior Reader",
        "m_monthly_reader": "Monthly Dark Reader",
        "m_comeback": "Return from Dark Exile",
        "m_weekend_streak": "Weekend Dark Reading Streak",
        "m_no_zero_days": "No Zero Dark Reading Days",
        "m_iron_will": "Iron Will Dark Reader",
        "m_habit_formed": "Dark Reading Regimen",
        "m_consistent_pace": "Consistent Dark Advance",
        "m_year_long": "Year-Long Dark Reading",
        "m_double_streak": "Double Dark Reading Streak",
        "m_streak_recovery": "Dark Reading Streak Recovery",
        "m_daily_minimum": "Daily Dark Minimum Pages",
        "m_winter_streak": "Winter Dark Reading Campaign",
        "m_summer_streak": "Summer Dark Offensive Reading",
        "m_morning_streak": "Morning Dark Formation Reading",
        "m_night_streak": "Night Dark Patrol Reading",
        "m_unbreakable": "Unbreakable Dark Reading Will",
        "m_eternal_flame": "Eternal Dark Flame Knowledge",
        "m_chapter_a_day": "Chapter a Day Dark Discipline",
        "m_genre_streak": "Genre Dark Reading Streak",
        "m_completion_streak": "Completion Dark Reading Chain",
        "m_rating_streak": "Dark Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Dark Streak",
        "m_author_streak": "Miura Dedication Streak",
        "m_perfect_week_manga": "Perfect Dark Reading Week",
        "m_diverse_streak": "Diverse Dark Reading Streak",
        // ── MANGA SCORING ──
        "m_critic": "Dark Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Dark Manuscript",
        "m_harsh_critic": "Guts' Reading Standards",
        "m_fair_judge": "Griffith's Dark Review",
        "m_generous_spirit": "Generous Dark Reader Spirit",
        "m_score_all": "Full Dark Manuscript Assessment",
        "m_wide_range": "Wide Range Dark Scores",
        "m_controversial": "Controversial Dark Opinion",
        "m_consistent_scorer": "Consistent Dark Scorer",
        "m_score_sniper": "Precision Dark Score Sniper",
        "m_evolving_taste": "Evolving Dark Reading Taste",
        "m_bell_curve": "Bell Curve Dark Scores",
        "m_picky_reader": "Selective Dark Reader",
        "m_100_rated": "Century of Dark Ratings",
        "m_500_rated": "Five Hundred Dark Rating Reports",
        "m_mediocre_majority": "Middle Ground Dark Reader",
        "m_rating_spree": "Dark Rating Barrage",
        "m_score_variance": "Variable Dark Manuscript Scores",
        "m_binge_rater": "Binge Dark Rating Session",
        "m_reread_rerate": "Reread and Re-Rate Darkness",
        "m_masterpiece_hunter": "Masterpiece Dark Manuscript Hunter",
        "m_contrarian": "Contrarian Dark Reader",
        "m_optimist": "Optimistic Dark Reader",
        "m_score_distributor": "Score Distributor Dark General",
        "m_genre_critic": "Genre Dark Reading Critic",
        "m_mean_above_8": "Elite Dark Reading Average",
        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Dark Reading Vow",
        "m_valentines_read": "Valentine's Dark Bond Read",
        "m_pi_day": "Pi Day Dark Chapter Count",
        "m_april_fools": "April Fools Dark Chibi",
        "m_international_manga_day": "International Dark Manga Day",
        "m_free_comic_day": "Free Dark Comic Day",
        "m_summer_solstice": "Summer Solstice Dark Reading",
        "m_tanabata": "Tanabata Dark Reading Wish",
        "m_friday_13th": "Friday 13th Apostle Manuscript",
        "m_halloween_read": "Halloween Dark Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Dark Reading Feast",
        "m_christmas_read": "Midwinter Dark Festival Read",
        "m_new_years_eve": "New Year's Eve Dark Final Read",
        "m_birthday_read": "Birthday Dark Reading Gift",
        "m_holiday_marathon": "Holiday Dark Reading Marathon",
        "m_independence_day": "Midland Independence Reading",
        "m_culture_day": "Dark Culture Day Manuscript",
        "m_spring_equinox": "Spring Dark Equinox Reading",
        "m_earth_day": "Earth Day Dark Conservation",
        "m_labor_day": "Dark Labor Reading Day",
        "m_winter_solstice": "Winter Dark Solstice Reading",
        "m_manga_birthday": "Berserk Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Dark Reader",
        "m_consecutive_holidays": "Consecutive Dark Holiday Reads",
        // ── MANGA SPECIAL ──
        "m_round_number": "Dark Round Number Milestone",
        "m_fibonacci": "Dark Fibonacci Chapter Pattern",
        "m_palindrome_day": "Palindrome Dark Reading Day",
        "m_binary_day": "Binary Dark Signal Day",
        "m_full_moon_read": "Full Moon Dark Read",
        "m_leap_year_read": "Leap Year Dark Reading",
        "m_triple_seven": "Triple Seven Dark Walls",
        "m_thousand_complete": "Thousand Dark Victories",
        "m_nice": "Nice Dark Chapter Count",
        "m_power_level_chapters": "Guts-Level Dark Chapters",
        "m_answer_42": "Answer to Causality's Reading",
        "m_square_number": "Perfect Dark Formation Chapters",
        "m_prime_count": "Prime Dark Chapter Count",
        "m_matching_date": "Matching Dark Reading Date",
        "m_century_chapter": "Century Dark Chapter Milestone",
        "m_pi_chapters": "Pi Dark Chapter Calculation",
        "m_synchronicity": "Eclipse Reading Synchronicity",
        "m_world_record": "World Record Dark Chapter Count",
        "m_genre_clash": "Dark Genre Clash Reading",
        "m_time_traveler": "Time-Traveling Dark Reader",
        "m_double_digits": "Double Digit Dark Milestone",
        "m_one_two_three": "Guts Casca Griffith Chapters",
        "m_lucky_seven": "Seven Lucky Dark Chapters",
        "m_exact_hundred_ch": "Exact Hundred Dark Chapters",
        "m_year_match_count": "Year Match Dark Count",
        "m_chapter_match_date": "Chapter Dark Date Match",
        // ── MANGA FORMATS ──
        "m_manga_format": "Dark Manga Format Specialist",
        "m_manhwa_format": "Dark Manhwa Format Reader",
        "m_manhua_format": "Dark Manhua Format Reader",
        "m_ln_format": "Dark Light Novel Format",
        "m_oneshot_format": "Oneshot Dark Format",
        "m_doujin_format": "Dark Doujin Format Reader",
        "m_novel_format": "Dark Novel Format Reader",
        "m_format_master_manga": "Format Dark Master Reader",
        // ── MANGA META ──
        "m_meta_first_unlock": "First Dark Reading Power",
        "m_meta_collector": "Dark Reading Badge Collector",
        "m_meta_category_starter": "Dark Category Initiation",
        "m_meta_tier_climber": "Dark Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Dark Reading Rank",
        "m_meta_xp_earner": "XP from Dark Reading Intel",
        "m_meta_difficulty_easy": "Easy Dark Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Dark Manuscript",
        "m_meta_unlock_spree": "Dark Reading Unlock Barrage",
        "m_meta_completionist": "Meta Dark Completionist",
        "m_meta_diverse": "Diverse Dark Portfolio",
        "m_meta_dominator": "Meta Dark Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050201",
        primary: "#8b0000",
        secondary: "#6e0000",
        accent: "#f0e8d0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        blood_mist: { label: "Blood Mist", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        brand_embers: { label: "Brand Embers", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        hawk_feathers: { label: "Hawk Feathers", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        dark_fog: { label: "Dark Fog", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1: "Orphan of the Battlefield",
        5: "Mercenary Recruit",
        15: "Band of the Hawk",
        30: "100-Man Slayer",
        45: "Eclipse Survivor",
        60: "Black Swordsman",
        80: "Berserker Armor",
        100: "Chosen by Causality",
    },
}
