import { AnimeThemeConfig } from "./types"
import { bleachPlayerIcons } from "./player-icons"
import {
    GiSkullCrossedBones,
    GiDragonHead,
    GiSpiralArrow,
    GiAngelOutfit,
    GiSpellBook,
    GiGhostAlly,
    GiBloodySword,
    GiDeathNote,
    GiSettingsKnobs,
    GiAlarmClock,
    GiEclipseFlare,
    GiTrophyCup,
    GiPalette,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss } from "react-icons/lu"
import { BiExtension } from "react-icons/bi"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { TbReportSearch } from "react-icons/tb"

export const bleachTheme: AnimeThemeConfig = {
    id: "bleach",
    displayName: "Bleach",
    description: "TYBW / Soul Society aesthetics. Black & silver. Shinigami-named achievements.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700;800;900&display=swap",
    cssVars: {
        "--color-brand-200": "215 218 225",
        "--color-brand-300": "180 185 195",
        "--color-brand-400": "140 145 158",
        "--color-brand-500": "105 110 125",
        "--color-brand-600": "75 80 92",
        "--color-brand-700": "50 54 65",
        "--color-brand-800": "32 35 42",
        "--color-brand-900": "18 20 26",
        "--color-brand-950": "8 9 14",
        "--brand": "170 175 190",
        "--background": "#020204",
        "--paper": "#08080c",
        "--color-gray-950": "3 3 6",
        "--color-gray-900": "8 8 14",
        "--color-gray-800": "16 16 22",
        "--color-gray-700": "28 28 36",
        "--color-gray-600": "48 48 58",
        "--color-gray-500": "80 80 92",
        "--color-gray-400": "125 125 140",
        "--color-gray-300": "170 170 185",
        "--color-gray-200": "210 210 220",
        "--color-gray-100": "235 235 242",
        "--color-gray-50": "248 248 252",
    },
    sidebarOverrides: {
        "home": { icon: GiAngelOutfit, label: "Soul Society" },
        "schedule": { icon: GiAlarmClock, label: "Dispatch Orders" },
        "manga": { icon: GiSpellBook, label: "Kidō Archive" },
        "lists": { icon: GiDeathNote, label: "Soul Records" },
        "discover": { icon: GiSpiralArrow, label: "Hollow Hunt" },
        "torrent-list": { icon: GiBloodySword, label: "Soul Transfers" },
        "debrid": { icon: GiDragonHead, label: "Shinigami Ops" },
        "unmatched": { icon: GiSkullCrossedBones, label: "Unclaimed Souls" },
        "enmasse": { icon: GiEclipseFlare, label: "Mass Purification" },
        "scan-summaries": { icon: TbReportSearch, label: "Intel Dossier" },
        "auto-downloader": { icon: LuRss, label: "Soul Messenger" },
        "community": { icon: GiGhostAlly, label: "Gotei 13" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Alerts" },
        "achievements": { icon: GiTrophyCup, label: "Shinigami Ranks" },
        "theme-manager": { icon: GiPalette, label: "Reiatsu Colors" },
        "extensions": { icon: BiExtension, label: "Zanpakutō Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Soul Link" },
        "settings": { icon: GiSettingsKnobs, label: "Captain's Orders" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Konsō",
        "a_episode_counter": "Konsō Tally",
        "a_episode_titan": "Espada Pressure",
        "a_hours_invested": "Dangai Training",
        "a_time_lord": "Temporal Bankai",
        "a_anime_collector": "Soul Armory",
        "a_library_legend": "Urahara's Archive",
        "a_first_complete": "Mission Purified",
        "a_hundred_club": "Hundred Hollows",
        "a_first_day": "Shinigami Oath",
        "a_first_rating": "Combat Eval",
        "a_ten_thousand_min": "Reiatsu Overflow",
        "a_season_veteran": "Veteran Shinigami",
        "a_year_explorer": "Century Service",
        "a_century_watcher": "Hundred Dispatches",
        "a_five_hundred_eps": "Five Hundred Konsōs",
        "a_thousand_eps": "Thousand Purifications",
        "a_watching_ten": "Captain Multitask",
        "a_ptw_hoarder": "Dispatch Backlog",
        "a_dropped_honesty": "Hollow Retreat",
        "a_five_thousand_eps": "Five Thousand Souls",
        "a_ten_completed": "Ten Cleared",
        "a_fifty_completed": "Fifty Purified",
        "a_five_hundred_completed": "Five Hundred Burials",
        "a_mean_score_tracker": "Reiatsu Average",
        "a_unique_studios": "Allied Squads",
        "a_days_spent_watching": "Seireitei Days",
        "a_all_status": "All Statuses",
        "a_first_favorite": "Zanpakutō Bond",
        "a_favorites_collector": "Gotei Bonds",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Shunpo Binge",
        "a_marathon_runner": "Bankai Marathon",
        "a_weekend_warrior": "Seireitei Weekend",
        "a_non_stop": "Mugetsu Blitz",
        "a_one_more_episode": "One More Hollow",
        "a_speed_run": "Shunpo Blitz",
        "a_double_feature": "Double Zangetsu",
        "a_triple_threat": "Triple Getsuga",
        "a_five_a_day": "Five Konsōs Daily",
        "a_back_to_back": "Consecutive Strikes",
        "a_seasonal_binge": "Arc Binge",
        "a_cour_crusher": "Cour Crusher",
        "a_half_day_watch": "Half-Day Bankai",
        "a_full_day_watch": "Soul Palace Day",
        "a_power_weekend": "Kenpachi Weekend",
        "a_binge_king": "Bankai King",
        "a_no_sleep": "Sleepless Seireitei",
        "a_entire_season": "Rapid Arc Clear",
        "a_seven_day_challenge": "Seven Hells",
        "a_hundred_day_binge": "Hundred-Day Siege",
        "a_genre_binge": "Cross-Squad Binge",
        "a_studio_binge": "Squad Binge",
        "a_season_sweep": "Season Bankai",
        "a_forty_eight_hour": "Forty-Eight Vigil",
        "a_ep_counter_day": "Daily Hollow Tally",
        "a_multi_series_binge": "Multi-Front Assault",
        "a_midnight_binge": "Midnight Seireitei",
        "a_new_year_binge": "New Year Getsuga",

        // ── ANIME GENRES ──
        "a_genre_action": "Quincy Warfare",
        "a_genre_adventure": "Wandering Soul",
        "a_genre_comedy": "Kon's Antics",
        "a_genre_drama": "Ichigo's Rain",
        "a_genre_fantasy": "Spirit Realm",
        "a_genre_horror": "Hollow Terror",
        "a_genre_mystery": "SRDI Mystery",
        "a_genre_romance": "Soul Bond",
        "a_genre_scifi": "Urahara's Lab",
        "a_genre_sol": "Squad 4 Life",
        "a_genre_sports": "Shinigami Cup",
        "a_genre_supernatural": "Hollowfication",
        "a_genre_thriller": "Espada Pursuit",
        "a_genre_mecha": "Fullbring Tech",
        "a_genre_music": "Sound Reiatsu",
        "a_genre_psychological": "Inner Hollow",
        "a_genre_ecchi": "Yoruichi's Flash",
        "a_genre_mahou_shoujo": "Spirit Ribbon",
        "a_tag_isekai": "Senkaimon Cross",
        "a_tag_harem": "Zanpakutō Harem",
        "a_tag_bl": "Comrade Blades",
        "a_tag_gl": "Shield Maidens",
        "a_tag_historical": "Soul History",
        "a_tag_military": "Gotei Discipline",
        "a_tag_school": "Shin'ō Academy",
        "a_tag_martial_arts": "Hakuda Master",
        "a_tag_vampire": "Quincy Blood",
        "a_tag_samurai": "Kenpachi's Path",
        "a_tag_space": "Beyond Dangai",
        "a_tag_parody": "Kon Chronicles",
        "a_tag_idol": "Soul Idol",
        "a_tag_post_apocalyptic": "Post-TYBW Era",
        "a_tag_cyberpunk": "SRDI Tech",
        "a_tag_shounen": "Ichigo's Resolve",
        "a_tag_seinen": "Captain's Burden",
        "a_tag_shoujo": "Rukia's Heart",
        "a_tag_josei": "Unohana's Grace",
        "a_tag_survival": "Hueco Mundo",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Registry",
        "a_mega_completionist": "Zero Division",
        "a_completion_rate_50": "Halfway Seireitei",
        "a_completion_rate_75": "Lieutenant Rank",
        "a_completion_rate_90": "Captain Candidate",
        "a_no_drop": "No Soul Left",
        "a_long_runner_complete": "Long Arc Survivor",
        "a_sequel_chain": "Sequential Bankai",
        "a_clean_list": "Purified List",
        "a_from_ptw": "Orders Executed",
        "a_rewatch_master": "Battle Replay",
        "a_short_complete": "Swift Konsō",
        "a_same_day_start_finish": "Same-Day Cleanse",
        "a_revival": "Resurrección",
        "a_zero_to_hero": "Zero to Captain",
        "a_five_genre_complete": "Five-Style Bankai",
        "a_full_franchise": "Full Arc Mastery",
        "a_batch_complete": "Rapid Purification",
        "a_paused_to_done": "Revived Mission",
        "a_completion_spree": "Soul Surge",
        "a_multi_rewatch": "Multi-Arc Replay",
        "a_dropped_recovery": "Hollow Recovery",
        "a_ten_perfect_scores": "Ten Perfect Bankais",
        "a_seasonal_clear": "Seasonal Clear",
        "a_complete_genre_span": "All-Terrain Soul",
        "a_monthly_completions": "Monthly Reports",
        "a_yearly_completions": "Yearly Victor",
        "a_rapid_complete": "Flash Completion",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Gotei Loyalty",
        "a_studio_devotee": "Division Devotee",
        "a_rewatcher": "Bankai Replay",
        "a_triple_rewatch": "Triple Rewatch",
        "a_annual_tradition": "Annual Hollow Night",
        "a_director_fan": "Yamamoto's Follower",
        "a_voice_actor_fan": "Voice Echoes",
        "a_ost_lover": "Asterisk Beat",
        "a_source_reader": "Source Grimoire",
        "a_waiting_weekly": "Weekly Dispatch",
        "a_childhood_revisit": "Academy Return",
        "a_saga_tracker": "Arc Tracker",
        "a_genre_loyalty": "Division Loyalty",
        "a_decade_watcher": "Decade Shinigami",
        "a_adaptation_hunter": "Adaptation Scout",
        "a_original_anime_fan": "Original Soul",
        "a_long_commitment": "Long Assignment",
        "a_perfect_attendance": "Perfect Record",
        "a_favorite_studio_5": "Five Squads",
        "a_complete_catalog": "Complete Catalog",
        "a_franchise_collector": "Arc Collector",
        "a_airing_follower": "Airing Follower",
        "a_genre_master": "Genre Bankai",
        "a_staff_follower": "Staff Tracker",
        "a_multi_season_fan": "Multi-Arc Veteran",
        "a_format_diversity": "Diverse Formats",
        "a_year_dedication": "Year of Service",
        "a_season_dedication": "Season Devotion",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Reiatsu Explorer",
        "a_studio_hopper": "Squad Hopper",
        "a_tag_explorer": "Soul Tag Scout",
        "a_decade_hopper": "Era Traveler",
        "a_hidden_gem": "Hidden Gem",
        "a_popular_taste": "Popular Path",
        "a_retro_appreciator": "Old Soul Scroll",
        "a_modern_viewer": "Modern Dispatch",
        "a_cross_demographic": "Cross-Squad Scout",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Week",
        "a_foreign_cinema": "Foreign Import",
        "a_classic_connoisseur": "Classic Shinigami",
        "a_every_season": "Every Season",
        "a_award_winner": "Kidō Medal",
        "a_niche_explorer": "Rare Zanpakutō",
        "a_global_anime": "World Summit",
        "a_cult_classic": "Cult Blade",
        "a_random_pick": "Random Hunt",
        "a_new_genre_month": "New Style Monthly",
        "a_seasonal_completionist": "Campaign Sweep",
        "a_unpopular_opinion": "Controversial Soul",
        "a_top_rated_viewer": "Top-Rated Source",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Charge",
        "a_upcoming_watcher": "Upcoming Intel",
        "a_short_series_explorer": "Short Skirmish",
        "a_long_series_explorer": "Long Arc Scout",

        // ── ANIME TIME ──
        "a_night_owl": "Midnight Patrol",
        "a_early_bird": "Dawn Guard",
        "a_lunch_break": "Midday Hollow",
        "a_golden_hour": "Golden Dispatch",
        "a_four_am_club": "4 AM Seireitei",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Konsō",
        "a_midnight_premiere": "Midnight Release",
        "a_all_hours": "All-Hours Soul",
        "a_dawn_warrior": "Dawn Shinigami",
        "a_afternoon_delight": "Afternoon Hollow",
        "a_prime_time": "Prime Hollow Hunt",
        "a_workday_watcher": "Workday Soul",
        "a_sunday_marathon": "Sunday Marathon",
        "a_rainy_day": "Seireitei Rain",
        "a_morning_routine": "Morning Zanjutsu",
        "a_night_shift": "Night Patrol",
        "a_twilight_zone": "Twilight Hollow",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Bankai",
        "a_weekend_binge_hours": "Weekend Ops",
        "a_late_night_regular": "Late Night Patrol",
        "a_sunrise_watcher": "Seireitei Sunrise",
        "a_holiday_watcher": "Holiday Duty",
        "a_every_day_of_week": "Every Day Active",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Joint Op",
        "a_party_host": "Squad Commander",
        "a_social_butterfly": "Seireitei Socialite",
        "a_group_binge": "Group Bankai",
        "a_party_regular": "Regular Joint Op",
        "a_sync_viewer": "Perfect Sync",
        "a_commentator": "Battle Analyst",
        "a_party_marathon": "Squad Marathon",
        "a_full_house": "Full Division",
        "a_community_pillar": "Gotei Pillar",
        "a_watch_party_streak": "Joint Op Streak",
        "a_diverse_party": "Diverse Squad",
        "a_late_night_party": "Midnight Ops",
        "a_party_veteran": "Veteran Leader",
        "a_genre_party": "Cross-Genre Squad",
        "a_weekly_party": "Weekly Gathering",
        "a_silent_viewer": "Byakuya's Silence",
        "a_recommendation_giver": "Captain's Pick",
        "a_party_completionist": "Party Clear",
        "a_social_scorer": "Social Score",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Konsō",
        "a_fibonacci": "Fibonacci Souls",
        "a_palindrome_day": "Palindrome Day",
        "a_binary_day": "Binary Dispatch",
        "a_full_moon": "Full Moon Hunt",
        "a_leap_year": "Leap Year Soul",
        "a_time_traveler": "Senkaimon Leap",
        "a_genre_clash": "Blade Clash",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Souls",
        "a_pi_episodes": "Pi Calculation",
        "a_synchronicity": "Soul Resonance",
        "a_world_record": "Hollow Record",
        "a_nice": "Nice Reiatsu",
        "a_power_level": "Over 9000 Reiatsu",
        "a_answer_42": "Soul's Answer",
        "a_square_number": "Perfect Square",
        "a_prime_count": "Prime Hollows",
        "a_matching_date": "Matching Date",
        "a_century_episode": "Century Hollow",
        "a_double_digits": "Double Konsōs",
        "a_one_two_three": "Shikai Bankai Hollow",
        "a_lucky_seven": "Seven Captains",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match Tally",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Dispatch",
        "a_movie_buff": "Cinematic Hollow",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Scout",
        "a_special_watcher": "Special Operative",
        "a_short_king": "Flash Step King",
        "a_variety_pack": "All-Format Soul",
        "a_film_festival": "Soul Film Fest",
        "a_music_video": "Sound Collector",
        "a_tv_short": "Short Dispatch",
        "a_movie_marathon": "Movie Blitz",
        "a_double_length": "Extended Bankai",
        "a_anthology": "Soul Anthology",
        "a_mini_series": "Mini Arc",
        "a_theatrical": "Theatrical Soul",
        "a_format_master": "Format Shinigami",
        "a_long_movie": "Epic Hollow Film",
        "a_back_catalog": "Seireitei Catalog",
        "a_cm_watcher": "Break Watcher",
        "a_pv_collector": "Preview Collector",
        "a_format_balance": "Balanced Formats",
        "a_episodic_master": "Episodic Bankai",
        "a_sequel_movie": "Sequel Film",
        "a_recap_watcher": "Recap Briefing",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Zanjutsu",
        "a_mega_streak": "Mega Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Dispatch",
        "a_comeback": "Soul Comeback",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Zanpakutō",
        "a_habit_formed": "Habit Forged",
        "a_consistent_pace": "Steady Reiatsu",
        "a_year_long": "Year-Long Tour",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable Will",
        "a_eternal_flame": "Ryūjin Jakka",
        "a_completion_streak": "Konsō Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Ep Streak",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Squad Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Soul Critic",
        "a_perfect_ten": "Perfect Zanpakutō",
        "a_harsh_critic": "Byakuya Standard",
        "a_fair_judge": "Fair Captain",
        "a_generous_spirit": "Generous Reiatsu",
        "a_score_all": "Full Assessment",
        "a_wide_range": "Reiatsu Range",
        "a_controversial": "Controversial Pick",
        "a_consistent_scorer": "Consistent Score",
        "a_score_sniper": "Score Sniper",
        "a_evolving_taste": "Evolving Style",
        "a_bell_curve": "Reiatsu Curve",
        "a_picky_watcher": "Picky Shinigami",
        "a_100_rated": "Century Ratings",
        "a_500_rated": "Master Ratings",
        "a_mediocre_majority": "Middle Path",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Hunter",
        "a_contrarian": "Contrarian Soul",
        "a_optimist": "Hollow Optimist",
        "a_score_distributor": "Score General",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Resolve",
        "a_valentines_weeb": "Valentine Shinigami",
        "a_pi_day": "Pi Day Kidō",
        "a_april_fools": "April Hollow",
        "a_international_anime_day": "Soul Society Day",
        "a_star_wars_day": "Galactic Zanpakutō",
        "a_summer_solstice": "Solstice Night",
        "a_tanabata": "Tanabata Bond",
        "a_friday_13th": "13th Division",
        "a_halloween_spirit": "Hollow Night",
        "a_thanksgiving_binge": "Feast of Souls",
        "a_christmas_special": "Winter Soul",
        "a_new_years_eve": "Year-End Cleanse",
        "a_birthday_watch": "Birthday Hunt",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Freedom Bankai",
        "a_culture_day": "Soul Culture",
        "a_spring_equinox": "Spring Awakening",
        "a_earth_day": "Protect Souls",
        "a_labor_day": "Squad 4 Day",
        "a_winter_solstice": "Solstice Patrol",
        "a_anime_birthday": "Anniversary Soul",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Consecutive Feasts",

        // ── ANIME META ──
        "a_meta_first_unlock": "Zanpakutō Awakened",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Division Starter",
        "a_meta_tier_climber": "Rank Climber",
        "a_meta_tier_max": "Captain-Class",
        "a_meta_xp_earner": "Hollow XP",
        "a_meta_difficulty_easy": "Easy Training",
        "a_meta_difficulty_hard": "Espada Challenge",
        "a_meta_unlock_spree": "Bankai Spree",
        "a_meta_completionist": "Meta Captain",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Soul Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Kidō Page",
        "m_chapter_counter": "Grimoire Tally",
        "m_chapter_titan": "Espada Grimoire",
        "m_reading_hours": "Kidō Study",
        "m_reading_time_lord": "Infinite Archive",
        "m_manga_collector": "Grimoire Collector",
        "m_library_legend": "Central 46 Vault",
        "m_first_complete": "Grimoire Cleared",
        "m_hundred_club": "Hundred Grimoires",
        "m_first_day": "Academy Enrollment",
        "m_first_rating": "First Evaluation",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Arsenal",
        "m_year_explorer": "Year Explorer",
        "m_century_reader": "Century Scholar",
        "m_five_hundred_ch": "Five Hundred Verses",
        "m_thousand_ch": "Thousand Incantations",
        "m_reading_ten": "Ten Grimoires",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Retreat",
        "m_season_reader": "Seasonal Scholar",
        "m_active_reader": "Active Scholar",
        "m_five_thousand_ch": "Five Thousand Verses",
        "m_ten_completed": "Ten Complete",
        "m_fifty_completed": "Fifty Archived",
        "m_five_hundred_completed": "Five Hundred Sealed",
        "m_mean_score_tracker": "Average Rating",
        "m_unique_authors": "Unique Mangaka",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Grimoire Bond",
        "m_favorites_collector": "Grimoire Arsenal",
        "m_days_spent_reading": "Archive Days",

        // ── MANGA BINGE ──
        "m_binge_reader": "Shunpo Reader",
        "m_marathon_reader": "Reading Marathon",
        "m_weekend_reader": "Weekend Reading",
        "m_non_stop_reading": "Non-Stop Scroll",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Flash Step Read",
        "m_double_story": "Double Story",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five Reads Daily",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Read",
        "m_full_day_read": "Soul Palace Read",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge Shinigami",
        "m_no_sleep_read": "All-Night Scroll",
        "m_full_series_rush": "Series Rush",
        "m_seven_day_challenge": "Seven Challenges",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Cross-Genre Read",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Tally",
        "m_multi_series_binge": "Multi-Series Front",
        "m_midnight_binge": "Midnight Scroll",
        "m_new_year_binge": "New Year Read Rush",
        "m_forty_eight_hour": "Forty-Eight Hours",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Kidō",
        "m_genre_adventure": "Wandering Tome",
        "m_genre_comedy": "Kon Comedy Tome",
        "m_genre_drama": "Soul Drama",
        "m_genre_fantasy": "Spirit Fantasy",
        "m_genre_horror": "Hollow Horror Tome",
        "m_genre_mystery": "SRDI Case File",
        "m_genre_romance": "Soul Romance",
        "m_genre_scifi": "Lab Report Tome",
        "m_genre_sol": "Slice of Soul",
        "m_genre_sports": "Tournament Tome",
        "m_genre_supernatural": "Hollow Tome",
        "m_genre_thriller": "Espada Thriller",
        "m_genre_psychological": "Inner World Tome",
        "m_genre_isekai": "Senkaimon Tome",
        "m_genre_shounen": "Shinigami Tome",
        "m_genre_ecchi": "Yoruichi's Tome",
        "m_genre_mahou_shoujo": "Ribbon Tome",
        "m_genre_mecha": "Fullbring Tome",
        "m_genre_music": "Sound Tome",
        "m_tag_isekai_new": "New Realm Tome",
        "m_tag_harem": "Squad Bonds Tome",
        "m_tag_bl": "Comrade Tome",
        "m_tag_gl": "Shield Maiden Tome",
        "m_tag_historical": "History Tome",
        "m_tag_military": "Gotei Ops Tome",
        "m_tag_school": "Academy Tome",
        "m_tag_martial_arts": "Hakuda Manual",
        "m_tag_vampire": "Quincy Blood Tome",
        "m_tag_samurai": "Zanpakutō Tome",
        "m_tag_space": "Dangai Tome",
        "m_tag_parody": "Kon's Tome",
        "m_tag_idol": "Idol Tome",
        "m_tag_post_apocalyptic": "Post-TYBW Tome",
        "m_tag_cyberpunk": "SRDI Tome",
        "m_tag_shoujo": "Rukia's Tome",
        "m_tag_survival": "Hueco Mundo Tome",
        "m_tag_cooking": "Barracks Cookbook",
        "m_tag_medical": "Squad 4 Manual",
        "m_tag_villainess": "Arrancar Tome",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Grimoire Registry",
        "m_mega_completionist": "Zero Division Reader",
        "m_completion_rate_50": "Halfway Archive",
        "m_completion_rate_75": "Lieutenant Reader",
        "m_completion_rate_90": "Captain Reader",
        "m_no_drop": "No Scroll Left",
        "m_long_runner_complete": "Long Tome Survivor",
        "m_sequel_chain": "Arc Chain",
        "m_clean_list": "Purified List",
        "m_from_ptr": "Orders Read",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Scroll",
        "m_revival": "Revived Tome",
        "m_zero_to_hundred": "Zero to Scholar",
        "m_five_genre_complete": "Five-Genre Mastery",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Rapid Archive",
        "m_paused_to_done": "Revived Scrolls",
        "m_completion_spree": "Scroll Surge",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi-Pass Reread",
        "m_dropped_recovery": "Hollow Recovery Read",
        "m_ten_perfect_scores": "Ten Perfect Scrolls",
        "m_complete_genre_span": "All-Genre Reader",
        "m_monthly_completions": "Monthly Scrolls",
        "m_yearly_completions": "Yearly Archive",
        "m_rapid_complete": "Rapid Processing",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Gotei Oath Reader",
        "m_mangaka_lover": "Mangaka Devotee",
        "m_rereader": "Scroll Replay",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Ally",
        "m_artist_fan": "Artist Devotee",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Canon Explorer",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Era Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyalty",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "Light Novel Intel",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Caught Up",
        "m_favorite_mangaka": "Favorite Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Franchise Collector",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Mastery",
        "m_multi_series_author": "Multi-Series Fan",
        "m_format_diversity": "Diverse Formats",
        "m_year_dedication": "Year Devoted",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Genre Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Reiatsu Reader",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Scout",
        "m_decade_hopper": "Era Jumper",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Path",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross-Squad Reader",
        "m_underdog_fan": "Underdog Reader",
        "m_variety_week": "Varied Week",
        "m_manhwa_reader": "Manhwa Intel",
        "m_manhua_reader": "Manhua Intel",
        "m_classic_connoisseur": "Classic Connoisseur",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Rare Zanpakutō Read",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Completionist",
        "m_unpopular_opinion": "Unpopular Opinion",
        "m_top_rated_reader": "Top-Rated Reader",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Tome Scout",
        "m_long_manga_explorer": "Long Tome Scout",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Midnight Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Midday Read",
        "m_commute_reader": "Commute Reader",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All-Hours Reader",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "Workday Read",
        "m_sunday_read": "Sunday Marathon",
        "m_morning_routine": "Morning Ritual",
        "m_night_shift_reader": "Night Shift Read",
        "m_seasonal_premier_read": "New Release Read",
        "m_clock_collector": "Clock Collection",
        "m_late_night_horror": "Midnight Horror",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Scroll",
        "m_twilight_reader": "Twilight Read",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Read Ops",
        "m_late_night_regular": "Late Night Regular",
        "m_sunrise_reader": "Seireitei Sunrise",
        "m_every_day_of_week": "Every Day Reading",
        "m_monthly_hours": "Monthly Read Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color Tome",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Read",
        "m_longstrip_reader": "Long Strip",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel Fan",
        "m_novel_reader": "Novel Fan",
        "m_visual_storyteller": "Visual Narrator",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award-Winning Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross-Media Intel",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Joint Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read Streak",
        "m_mega_streak": "Mega Read Streak",
        "m_weekly_warrior": "Weekly Warrior",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Scroll Comeback",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Will",
        "m_habit_formed": "Habit Forged",
        "m_consistent_pace": "Steady Pace",
        "m_year_long": "Year-Long Journey",
        "m_double_streak": "Double Streak",
        "m_streak_recovery": "Streak Recovery",
        "m_daily_minimum": "Daily Minimum",
        "m_winter_streak": "Winter Streak",
        "m_summer_streak": "Summer Streak",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Streak",
        "m_unbreakable": "Unbreakable Reader",
        "m_eternal_flame": "Eternal Flame",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Completion Chain",
        "m_rating_streak": "Rating Streak",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Scroll Critic",
        "m_perfect_ten": "Perfect Scroll",
        "m_harsh_critic": "Harsh Critic",
        "m_fair_judge": "Balanced Judge",
        "m_generous_spirit": "Generous Spirit",
        "m_score_all": "Full Assessment",
        "m_wide_range": "Full Range",
        "m_controversial": "Controversial Score",
        "m_consistent_scorer": "Consistent Scorer",
        "m_score_sniper": "Score Sniper",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Picky Reader",
        "m_100_rated": "Century Critic",
        "m_500_rated": "Master Critic",
        "m_mediocre_majority": "Middle Path",
        "m_rating_spree": "Rating Spree",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread & Rerate",
        "m_masterpiece_hunter": "Masterpiece Hunter",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimist Reader",
        "m_score_distributor": "Score General",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Resolve",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Fool Read",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Solstice Read",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "13th Division Read",
        "m_halloween_read": "Hollow Night Read",
        "m_thanksgiving_binge": "Feast of Scrolls",
        "m_christmas_read": "Winter Read",
        "m_new_years_eve": "Year-End Read",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Marathon",
        "m_independence_day": "Freedom Read",
        "m_culture_day": "Culture Day Read",
        "m_spring_equinox": "Spring Equinox Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Solstice Night Read",
        "m_manga_birthday": "Manga Anniversary",
        "m_every_holiday_reader": "Every Holiday",
        "m_consecutive_holidays": "Consecutive Holidays",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Milestone",
        "m_fibonacci": "Fibonacci Scroll",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven",
        "m_thousand_complete": "Thousand Scrolls",
        "m_nice": "Nice Count",
        "m_power_level_chapters": "Over 9000 Pages",
        "m_answer_42": "Soul's Answer",
        "m_square_number": "Perfect Square",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Matching Day",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Synchronicity",
        "m_world_record": "Record Count",
        "m_genre_clash": "Genre Clash Read",
        "m_time_traveler": "Time Traveler Read",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "Shikai Bankai Hollow",
        "m_lucky_seven": "Seven Chapters",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Match Count",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Scroll Unlocked",
        "m_meta_collector": "Grimoire Collector",
        "m_meta_category_starter": "Category Starter",
        "m_meta_tier_climber": "Rank Climber",
        "m_meta_tier_max": "Maximum Rank",
        "m_meta_xp_earner": "Scroll XP",
        "m_meta_difficulty_easy": "Easy Scroll",
        "m_meta_difficulty_hard": "Espada Grimoire",
        "m_meta_unlock_spree": "Unlock Barrage",
        "m_meta_completionist": "Meta Completionist",
        "m_meta_diverse": "Diverse Portfolio",
        "m_meta_dominator": "Scroll Dominator",
    },
    musicUrl: "/public/themes/bleach-opening.mp3",
    previewColors: {
        bg: "#02020a",
        primary: "#4655a0",
        secondary: "#8090c8",
        accent: "#c0c8f0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/bleach.jpg",
    particleColor: "#3a6fc8",
    backgroundDim: 0.10,
    backgroundBlur: 4,
    particleTypes: {
        butterflies: { label: "Hell Butterflies", maxCount: 6, defaultEnabled: true, defaultIntensity: 60 },
        wisps: { label: "Reiatsu Wisps", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        moon: { label: "Moon & Haze", maxCount: 1, defaultEnabled: true, defaultIntensity: 60 },
        lasNoches: { label: "Las Noches Silhouette", maxCount: 1, defaultEnabled: true, defaultIntensity: 50 },
    },
    playerIconOverrides: bleachPlayerIcons,
    milestoneNames: {
        1:   "Unseated",
        5:   "20th Seat",
        15:  "9th Seat",
        25:  "3rd Seat",
        35:  "Lieutenant",
        50:  "Captain",
        65:  "Visored",
        80:  "Royal Guard",
        100: "Soul King",
    },
}
