import { AnimeThemeConfig } from "./types"
import { GiBasketballBall, GiFeather, GiRunningShoe, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiSoccerBall, GiHeartKey, GiWhistle, GiStopwatch } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const blueBoxTheme: AnimeThemeConfig = {
    id: "blue-box",
    displayName: "Blue Box",
    description: "Taiki Inomaki, a badminton player, falls for upperclassman and basketball star Chinatsu Kano. When they unexpectedly become housemates, their awkward coexistence slowly blossoms into an earnest romantic story.",
    fontFamily: "'Nunito', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "160 210 255",
        "--color-brand-300": "96 172 252",
        "--color-brand-400": "40 132 240",
        "--color-brand-500": "8 96 212",
        "--color-brand-600": "0 66 175",
        "--color-brand-700": "0 42 135",
        "--color-brand-800": "0 24 90",
        "--color-brand-900": "0 10 50",
        "--color-brand-950": "0 4 20",
        "--brand": "8 96 212",
        "--background": "#000308",
        "--paper": "#000810",
        "--color-gray-950": "0 3 8",
        "--color-gray-900": "0 7 16",
        "--color-gray-800": "2 14 28",
        "--color-gray-700": "5 26 48",
        "--color-gray-600": "10 44 78",
        "--color-gray-500": "22 72 122",
        "--color-gray-400": "48 112 172",
        "--color-gray-300": "88 155 215",
        "--color-gray-200": "132 192 244",
        "--color-gray-100": "178 218 252",
        "--color-gray-50": "220 240 255",
    },
    sidebarOverrides: {
        "home": { icon: GiFeather, label: "Sports Club" },
        "schedule": { icon: GiAlarmClock, label: "Practice Schedule" },
        "manga": { icon: LuBookOpen, label: "Sports Journal" },
        "lists": { icon: GiFlowerEmblem, label: "Team Registry" },
        "discover": { icon: GiBullseye, label: "New Rivals" },
        "torrent-list": { icon: GiRunningShoe, label: "Gear Cache" },
        "debrid": { icon: GiBasketballBall, label: "Equipment Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Teammates" },
        "enmasse": { icon: GiResize, label: "Team Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Match Reports" },
        "auto-downloader": { icon: LuRss, label: "Club Feed" },
        "community": { icon: GiWhistle, label: "Sports Circle" },
        "achievements": { icon: GiTrophy, label: "Sports Awards" },
        "milestones": { icon: LuFlag, label: "Training Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Match Alerts" },
        "theme-manager": { icon: GiPalette, label: "Blue Palette" },
        "extensions": { icon: BiExtension, label: "Sports Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Team Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Taiki's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Practice",
        "a_first_complete": "Match Won",
        "a_hundred_club": "Hundred Matches",
        "a_time_lord": "Sports Veteran",
        "a_anime_collector": "Sports Archive",
        "a_library_legend": "Club Library",
        "a_binge_king": "Sports Marathon",
        "a_no_sleep": "All-Night Train",
        "a_marathon_runner": "Taiki's Run",
        "a_speed_run": "Quick Match",
        "a_completionist": "Full Season",
        "a_mega_completionist": "Sports Master",
        "a_loyal_fan": "Club Regular",
        "a_rewatcher": "Replay Match",
        "a_decade_watcher": "Decade Athlete",
        "a_genre_action": "Match Battle",
        "a_genre_adventure": "Sports Journey",
        "a_genre_comedy": "Roommate Comedy",
        "a_genre_drama": "Sports Drama",
        "a_genre_fantasy": "None Here",
        "a_genre_horror": "None Here",
        "a_genre_romance": "Taiki's Love",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Sports Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Sports Critic",
        "a_perfect_ten": "Perfect Match",
        "a_harsh_critic": "Coach Standard",
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Endless Practice",
        "a_year_long": "Year of Sports",
        "a_iron_will": "Taiki's Will",
        "a_hidden_gem": "Hidden Talent",
        "a_cult_classic": "Sports Classic",
        "a_classic_connoisseur": "2022 Fan",
        "a_new_years_resolution": "New Year Goal",
        "a_christmas_special": "Winter Practice",
        "a_meta_tier_max": "True Athlete",
        "a_meta_completionist": "All Matches",
        "a_sequel_chain": "Sports Chain",
        "a_zero_to_hero": "Novice to Pro",
        "a_night_owl": "Night Training",
        "a_early_bird": "Dawn Practice",
        "m_first_chapter": "First Practice",
        "m_first_complete": "Arc Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Sports Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Blue Box Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Re-match",
        "m_genre_action": "Match Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Love Chapter",
        "m_genre_fantasy": "None Here",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Coach Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Training Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Athlete",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Sports Classic",
        "m_mangaka_lover": "Kouji Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Blue Box Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Sports Art",
        "m_manga_to_anime": "Adapted Match",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000308",
        primary: "#0860d4",
        secondary: "#0042af",
        accent: "#f0a030",
    },
    particleColor: "#2090e8",
    backgroundDim: 0.26,
    backgroundBlur: 14,
    particleTypes: {
        blue_sparks: { label: "Court Lights", maxCount: 16, defaultEnabled: true, defaultIntensity: 50 },
        sparkles: { label: "Sports Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
        1: "Rookie Player",
        5: "Club Member",
        15: "Regular Player",
        30: "Starting Player",
        50: "Team Ace",
        75: "Tournament Star",
        100: "Blue Box Champion",
    },
}
