import { AnimeThemeConfig } from "./types"
import {
    GiSoccerBall,
    GiSoccerKick,
    GiSoccerField,
    GiLightningArc,
    GiCrosshair,
    GiBullseye,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
    GiRunningShoe,
    GiFist,
    GiStarFormation,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const blueLockTheme: AnimeThemeConfig = {
    id: "blue-lock",
    displayName: "Blue Lock",
    description: "Devour it all. A striker's interface forged in Blue Lock's ego-driven facility — spatial awareness, chemical reactions, and the hunger to become the world's best.",
    fontFamily: "'Exo 2', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Exo+2:wght@400;500;600;700&display=swap",
    cssVars: {
        // Brand → electric blue
        "--color-brand-200": "128 190 255",
        "--color-brand-300": "77 155 255",
        "--color-brand-400": "38 120 255",
        "--color-brand-500": "0 100 255",
        "--color-brand-600": "0 80 210",
        "--color-brand-700": "0 60 170",
        "--color-brand-800": "0 42 130",
        "--color-brand-900": "0 26 90",
        "--color-brand-950": "0 12 50",
        "--brand": "0 100 255",
        // Deep dark BG
        "--background": "#020408",
        "--paper": "#040810",
        "--color-gray-950": "2 4 8",
        "--color-gray-900": "4 8 16",
        "--color-gray-800": "10 18 32",
        "--color-gray-700": "18 32 55",
        "--color-gray-600": "30 52 82",
        "--color-gray-500": "55 80 115",
        "--color-gray-400": "95 120 160",
        "--color-gray-300": "145 168 200",
        "--color-gray-200": "190 205 225",
        "--color-gray-100": "222 230 240",
        "--color-gray-50": "240 244 250",
    },
    sidebarOverrides: {
        "home": { icon: GiSoccerField, label: "Facility Hub" },
        "schedule": { icon: GiAlarmClock, label: "Match Schedule" },
        "manga": { icon: LuBookOpen, label: "Striker Archives" },
        "lists": { icon: GiCrosshair, label: "Player Roster" },
        "discover": { icon: GiBullseye, label: "Scouting Report" },
        "torrent-list": { icon: GiAnvilImpact, label: "Supply Drops" },
        "debrid": { icon: GiRunningShoe, label: "Fast Break Ops" },
        "unmatched": { icon: GiLightningArc, label: "Lost Strikers" },
        "enmasse": { icon: GiResize, label: "Mass Selection" },
        "scan-summaries": { icon: TbReportSearch, label: "Match Analysis" },
        "auto-downloader": { icon: LuRss, label: "Goal Alerts" },
        "community": { icon: GiStarFormation, label: "Team Formation" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Facility Alerts" },
        "achievements": { icon: GiTrophy, label: "Striker Records" },
        "theme-manager": { icon: GiPalette, label: "Kit Colors" },
        "extensions": { icon: BiExtension, label: "Gear Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "Data Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ego's Orders" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Touch",
        "a_episode_counter": "Shot Counter",
        "a_episode_titan": "Striker Showdown",
        "a_hours_invested": "Pitch Time",
        "a_time_lord": "Spatial Awareness",
        "a_anime_collector": "Striker Arsenal",
        "a_library_legend": "Facility Legend",
        "a_first_complete": "First Goal",
        "a_hundred_club": "Century Striker",
        "a_first_day": "Selection Day",
        "a_first_rating": "Ego's Evaluation",
        "a_ten_thousand_min": "Ten Thousand Minutes",
        "a_season_veteran": "Veteran Striker",
        "a_year_explorer": "Year-Long Contract",
        "a_century_watcher": "Hundred-Match Run",
        "a_five_hundred_eps": "Five Hundred Shots",
        "a_thousand_eps": "Thousand Strikes",
        "a_watching_ten": "Ten-Match Week",
        "a_ptw_hoarder": "Bench Hoarder",
        "a_dropped_honesty": "Tactical Sub",
        "a_five_thousand_eps": "Five Thousand Goals",
        "a_ten_completed": "Ten Wins",
        "a_fifty_completed": "Fifty Clean Sheets",
        "a_five_hundred_completed": "Five Hundred Victories",
        "a_mean_score_tracker": "Average Rating",
        "a_unique_studios": "Allied Clubs",
        "a_days_spent_watching": "Days on Pitch",
        "a_all_status": "All Formations",
        "a_first_favorite": "First Rival Bond",
        "a_favorites_collector": "Rival Collection",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Dribble",
        "a_marathon_runner": "Full-Pitch Sprint",
        "a_weekend_warrior": "Weekend Striker",
        "a_non_stop": "Relentless Offense",
        "a_one_more_episode": "One More Half",
        "a_speed_run": "Counter Attack",
        "a_double_feature": "Double Strike",
        "a_triple_threat": "Hat Trick",
        "a_five_a_day": "Five Goals Daily",
        "a_back_to_back": "Back-to-Back Goals",
        "a_seasonal_binge": "Full Season Arc",
        "a_cour_crusher": "League Crusher",
        "a_half_day_watch": "First Half Grind",
        "a_full_day_watch": "Full Match Day",
        "a_power_weekend": "Power Weekend Blitz",
        "a_binge_king": "King of Strikers",
        "a_no_sleep": "Overtime Thriller",
        "a_entire_season": "Rapid League Clear",
        "a_seven_day_challenge": "Seven-Day Camp",
        "a_hundred_day_binge": "Hundred-Day Trial",
        "a_genre_binge": "Cross-Training Binge",
        "a_studio_binge": "Club Marathon",
        "a_season_sweep": "Season Sweep",
        "a_forty_eight_hour": "Extra Time Siege",
        "a_ep_counter_day": "Daily Shot Count",
        "a_multi_series_binge": "Multi-Match Sprint",
        "a_midnight_binge": "Midnight Practice",
        "a_new_year_binge": "New Year Kickoff",

        // ── ANIME GENRES ──
        "a_genre_action": "Direct Shot",
        "a_genre_adventure": "Pitch Invasion",
        "a_genre_comedy": "Locker Room Laughs",
        "a_genre_drama": "Ego's Philosophy",
        "a_genre_fantasy": "Flow State",
        "a_genre_horror": "Elimination Terror",
        "a_genre_mystery": "Hidden Weapon",
        "a_genre_romance": "Striker's Heart",
        "a_genre_scifi": "Metavision Tech",
        "a_genre_sol": "Off the Pitch",
        "a_genre_sports": "Pure Football",
        "a_genre_supernatural": "Awakened Ego",
        "a_genre_thriller": "Sudden Death",
        "a_genre_mecha": "Iron Defense",
        "a_genre_music": "Stadium Anthem",
        "a_genre_psychological": "Ego Warfare",
        "a_genre_ecchi": "Fan Service Card",
        "a_genre_mahou_shoujo": "Special Ability",
        "a_tag_isekai": "Transported to Pitch",
        "a_tag_harem": "Squad Chemistry",
        "a_tag_bl": "Rival Bonds",
        "a_tag_gl": "Wing Partners",
        "a_tag_historical": "Football History",
        "a_tag_military": "Tactical Discipline",
        "a_tag_school": "Youth Academy",
        "a_tag_martial_arts": "Physical Duel",
        "a_tag_vampire": "Goal Hunger",
        "a_tag_samurai": "Precision Blade",
        "a_tag_space": "World Stage",
        "a_tag_parody": "Chibi Strikers",
        "a_tag_idol": "Stadium Idol",
        "a_tag_post_apocalyptic": "Post-Elimination",
        "a_tag_cyberpunk": "Data Football",
        "a_tag_shounen": "Devour It All",
        "a_tag_seinen": "Pro League Grit",
        "a_tag_shoujo": "Bachira's Dance",
        "a_tag_josei": "Nagi's Genius",
        "a_tag_survival": "Survive Selection",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Match Report",
        "a_mega_completionist": "World's Best",
        "a_completion_rate_50": "Halftime Lead",
        "a_completion_rate_75": "Final Quarter",
        "a_completion_rate_90": "Injury Time Push",
        "a_no_drop": "No Player Dropped",
        "a_long_runner_complete": "Long Season Clear",
        "a_sequel_chain": "Tournament Chain",
        "a_clean_list": "Clean Sheet Record",
        "a_from_ptw": "Called Off Bench",
        "a_rewatch_master": "Match Replay",
        "a_short_complete": "Quick Match Win",
        "a_same_day_start_finish": "Same-Day Blitz",
        "a_revival": "Revival Goal",
        "a_zero_to_hero": "Benchwarmer to Ace",
        "a_five_genre_complete": "Five-Position Master",
        "a_full_franchise": "Full Club Dossier",
        "a_batch_complete": "Batch Selection Clear",
        "a_paused_to_done": "Back from Injury",
        "a_completion_spree": "Goal Spree",
        "a_multi_rewatch": "Multi-Angle Replay",
        "a_dropped_recovery": "Recovery Run",
        "a_ten_perfect_scores": "Ten Perfect Strikes",
        "a_seasonal_clear": "League Clear",
        "a_complete_genre_span": "All-Position Scout",
        "a_monthly_completions": "Monthly Results",
        "a_yearly_completions": "Annual Trophy",
        "a_rapid_complete": "Speed Goal",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Blue Locker",
        "a_studio_devotee": "Studio Devotee",
        "a_rewatcher": "Rewatch Replay",
        "a_triple_rewatch": "Triple Replay",
        "a_annual_tradition": "Annual Kickoff",
        "a_director_fan": "Coach's Vision",
        "a_voice_actor_fan": "Voice of Strikers",
        "a_ost_lover": "Stadium Roar",
        "a_source_reader": "Original Playbook",
        "a_waiting_weekly": "Weekly Match Wait",
        "a_childhood_revisit": "Return to Pitch",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Position Loyalty",
        "a_decade_watcher": "Decade-Long Fan",
        "a_adaptation_hunter": "Adaptation Scout",
        "a_original_anime_fan": "Original Broadcast",
        "a_long_commitment": "Long-Term Contract",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Fav Clubs",
        "a_complete_catalog": "Complete Catalog",
        "a_franchise_collector": "Franchise Collector",
        "a_airing_follower": "Live Match Intel",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Staff Follower",
        "a_multi_season_fan": "Multi-Season Fan",
        "a_format_diversity": "Diverse Formats",
        "a_year_dedication": "Year of Ego",
        "a_season_dedication": "Season of Hunger",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "New Position Try",
        "a_studio_hopper": "Club Transfer",
        "a_tag_explorer": "Tag Scouting",
        "a_decade_hopper": "Decade Dribble",
        "a_hidden_gem": "Hidden Talent",
        "a_popular_taste": "Popular Pick",
        "a_retro_appreciator": "Retro Football",
        "a_modern_viewer": "Modern Striker",
        "a_cross_demographic": "Cross-Field Scout",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Variety Training",
        "a_foreign_cinema": "Foreign League",
        "a_classic_connoisseur": "Classic Playbook",
        "a_every_season": "Every Season Active",
        "a_award_winner": "Golden Boot",
        "a_niche_explorer": "Niche Position",
        "a_global_anime": "Global League Entry",
        "a_cult_classic": "Cult Classic Goal",
        "a_random_pick": "Random Selection",
        "a_new_genre_month": "New Tactic Monthly",
        "a_seasonal_completionist": "Seasonal Champion",
        "a_unpopular_opinion": "Contrarian Tactic",
        "a_top_rated_viewer": "Top-Rated Scout",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Low Odds",
        "a_upcoming_watcher": "Upcoming Match Intel",
        "a_short_series_explorer": "Short Match Scout",
        "a_long_series_explorer": "Long Campaign Scout",

        // ── ANIME TIME ──
        "a_night_owl": "Night Practice",
        "a_early_bird": "Dawn Drills",
        "a_lunch_break": "Halftime Break",
        "a_golden_hour": "Golden Goal Hour",
        "a_four_am_club": "4 AM Training",
        "a_witching_hour": "Midnight Striker",
        "a_new_year_watch": "New Year's Goal",
        "a_midnight_premiere": "Midnight Kickoff",
        "a_all_hours": "All-Hours Striker",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Drills",
        "a_prime_time": "Prime Time Match",
        "a_workday_watcher": "On-Duty Viewer",
        "a_sunday_marathon": "Sunday Derby",
        "a_rainy_day": "Rainy Pitch Day",
        "a_morning_routine": "Morning Warmup",
        "a_night_shift": "Night Shift Grind",
        "a_twilight_zone": "Twilight Kickoff",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge Ops",
        "a_late_night_regular": "Late Night Regular",
        "a_sunrise_watcher": "Sunrise Training",
        "a_holiday_watcher": "Holiday Match",
        "a_every_day_of_week": "Every Day Active",
        "a_monthly_hours": "Monthly Pitch Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Team Play",
        "a_party_host": "Match Captain",
        "a_social_butterfly": "Locker Room Social",
        "a_group_binge": "Group Counter",
        "a_party_regular": "Regular Teammate",
        "a_sync_viewer": "Synced Formation",
        "a_commentator": "Match Commentator",
        "a_party_marathon": "Marathon Formation",
        "a_full_house": "Full Squad",
        "a_community_pillar": "Pillar Striker",
        "a_watch_party_streak": "Formation Streak",
        "a_diverse_party": "Diverse Squad",
        "a_late_night_party": "Late Night Match",
        "a_party_veteran": "Veteran Captain",
        "a_genre_party": "Cross-Genre Match",
        "a_weekly_party": "Weekly Scrimmage",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Scout Recommendation",
        "a_party_completionist": "Party Completionist",
        "a_social_scorer": "Social Goal Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Goal",
        "a_fibonacci": "Fibonacci Formation",
        "a_palindrome_day": "Palindrome Match",
        "a_binary_day": "Binary Signal Day",
        "a_full_moon": "Full Moon Strike",
        "a_leap_year": "Leap Year Goal",
        "a_time_traveler": "Future Sight",
        "a_genre_clash": "Position Clash",
        "a_triple_seven": "Triple Seven Goals",
        "a_thousand_complete": "Thousand Victories",
        "a_pi_episodes": "Pi Calculation",
        "a_synchronicity": "Chemical Reaction",
        "a_world_record": "World Record Goal",
        "a_nice": "Nice Goal Count",
        "a_power_level": "Ego Power Level",
        "a_answer_42": "Answer to Ego",
        "a_square_number": "Perfect Formation",
        "a_prime_count": "Prime Goal Count",
        "a_matching_date": "Matching Date Goal",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three Pass",
        "a_lucky_seven": "Lucky Number Seven",
        "a_all_tens": "All Tens Rating",
        "a_exact_hundred_eps": "Exact Hundred Shots",
        "a_year_match_count": "Year Match Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Fan",
        "a_movie_buff": "Film Session Buff",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Episode",
        "a_short_king": "Short Match King",
        "a_variety_pack": "All-Format Kit",
        "a_film_festival": "Film Festival",
        "a_music_video": "Anthem Collection",
        "a_tv_short": "Quick Highlight",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double-Length Match",
        "a_anthology": "Striker Anthology",
        "a_mini_series": "Mini Tournament",
        "a_theatrical": "Theatrical Debut",
        "a_format_master": "Format Master",
        "a_long_movie": "Feature-Length Film",
        "a_back_catalog": "Back Catalog Files",
        "a_cm_watcher": "Commercial Watcher",
        "a_pv_collector": "Preview Collector",
        "a_format_balance": "Balanced Formats",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Film",
        "a_recap_watcher": "Recap Briefing",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Training Streak",
        "a_mega_streak": "Mega Win Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Grind",
        "a_comeback": "Comeback Goal",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will Striker",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Consistent Pace",
        "a_year_long": "Year-Long Streak",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Camp Streak",
        "a_summer_streak": "Summer Camp Streak",
        "a_morning_streak": "Morning Drill Streak",
        "a_night_streak": "Night Grind Streak",
        "a_unbreakable": "Unbreakable Ego",
        "a_eternal_flame": "Eternal Blue Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Goal Streak",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Loyalty",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Ego's Critic",
        "a_perfect_ten": "Perfect Ten Goal",
        "a_harsh_critic": "Harsh Evaluator",
        "a_fair_judge": "Fair Judge",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Full Roster Score",
        "a_wide_range": "Wide Range Score",
        "a_controversial": "Controversial Call",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Precision Sniper",
        "a_evolving_taste": "Evolving Tactic",
        "a_bell_curve": "Bell Curve Stats",
        "a_picky_watcher": "Selective Striker",
        "a_100_rated": "Century Evaluations",
        "a_500_rated": "Five Hundred Scores",
        "a_mediocre_majority": "Mid-Table Average",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Variable Ratings",
        "a_masterpiece_hunter": "Masterpiece Goal",
        "a_contrarian": "Contrarian Scorer",
        "a_optimist": "Optimist Striker",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Ego",
        "a_valentines_weeb": "Valentine's Striker",
        "a_pi_day": "Pi Day Calc",
        "a_april_fools": "April Fools Card",
        "a_international_anime_day": "International Day",
        "a_star_wars_day": "Star Player Day",
        "a_summer_solstice": "Summer Tournament",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday 13th Red",
        "a_halloween_spirit": "Halloween Horror",
        "a_thanksgiving_binge": "Thanksgiving Feast",
        "a_christmas_special": "Winter Cup Special",
        "a_new_years_eve": "New Year's Finale",
        "a_birthday_watch": "Birthday Match",
        "a_holiday_marathon": "Holiday Tournament",
        "a_independence_day": "Freedom Kick",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Cup Opener",
        "a_earth_day": "Green Pitch Day",
        "a_labor_day": "Labor Day Rest",
        "a_winter_solstice": "Winter Camp",
        "a_anime_birthday": "Anime Anniversary",
        "a_every_holiday": "Every Holiday Active",
        "a_consecutive_holidays": "Consecutive Holidays",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Ego Awakened",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Kickoff",
        "a_meta_tier_climber": "Rank Climber",
        "a_meta_tier_max": "Neo Egoist Rank",
        "a_meta_xp_earner": "XP from Goals",
        "a_meta_difficulty_easy": "Easy Drill",
        "a_meta_difficulty_hard": "Legendary: Rin Itoshi",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Completionist",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page Turn",
        "m_chapter_counter": "Chapter Counter",
        "m_chapter_titan": "Chapter Showdown",
        "m_reading_hours": "Reading Pitch Time",
        "m_reading_time_lord": "Reading Flow State",
        "m_manga_collector": "Manga Arsenal",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Volume Clear",
        "m_hundred_club": "Hundred-Chapter Club",
        "m_first_day": "First Reading Day",
        "m_first_rating": "First Manuscript Score",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Collector",
        "m_year_explorer": "Year Reading Contract",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Chapters",
        "m_thousand_ch": "Thousand-Chapter Run",
        "m_reading_ten": "Ten Active Reads",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Drop",
        "m_season_reader": "Seasonal Reader",
        "m_active_reader": "Active Field Reader",
        "m_five_thousand_ch": "Five Thousand Chapters",
        "m_ten_completed": "Ten Manga Wins",
        "m_fifty_completed": "Fifty Manga Clears",
        "m_five_hundred_completed": "Five Hundred Reads",
        "m_mean_score_tracker": "Average Manga Score",
        "m_unique_authors": "Unique Mangaka",
        "m_all_status": "All Reading Statuses",
        "m_first_favorite": "First Manga Rival",
        "m_favorites_collector": "Favorites Arsenal",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading Rush",
        "m_marathon_reader": "Reading Marathon",
        "m_weekend_reader": "Weekend Reader",
        "m_non_stop_reading": "Non-Stop Pages",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Read Blitz",
        "m_double_story": "Double Feature",
        "m_triple_read": "Triple Read Attack",
        "m_five_a_day": "Five Reads Daily",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "First Half Read",
        "m_full_day_read": "Full Day Reading",
        "m_power_weekend": "Power Weekend Read",
        "m_binge_king": "Binge King Reader",
        "m_no_sleep_read": "All-Night Reading",
        "m_full_series_rush": "Full Series Rush",
        "m_seven_day_challenge": "Seven-Day Challenge",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Binge Read",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Count",
        "m_multi_series_binge": "Multi-Series Sprint",
        "m_midnight_binge": "Midnight Session",
        "m_new_year_binge": "New Year Read Rush",
        "m_forty_eight_hour": "Extra Time Read",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Striker Read",
        "m_genre_adventure": "Adventure Pitch",
        "m_genre_comedy": "Comedy Locker Room",
        "m_genre_drama": "Drama of Ego",
        "m_genre_fantasy": "Fantasy Flow",
        "m_genre_horror": "Elimination Horror",
        "m_genre_mystery": "Hidden Weapon Read",
        "m_genre_romance": "Striker Romance",
        "m_genre_scifi": "Sci-Fi Football",
        "m_genre_sol": "Life Off Pitch",
        "m_genre_sports": "Sports Manga Core",
        "m_genre_supernatural": "Awakened Read",
        "m_genre_thriller": "Sudden Death Read",
        "m_genre_psychological": "Ego Psychology",
        "m_genre_isekai": "Isekai Pitch",
        "m_genre_shounen": "Shounen Striker",
        "m_genre_ecchi": "Fan Service Read",
        "m_genre_mahou_shoujo": "Special Power Read",
        "m_genre_mecha": "Iron Defense Read",
        "m_genre_music": "Anthem Read",
        "m_tag_isekai_new": "New World Pitch",
        "m_tag_harem": "Squad Bond Manga",
        "m_tag_bl": "Rival Bond Manga",
        "m_tag_gl": "Wing Pair Manga",
        "m_tag_historical": "Football History",
        "m_tag_military": "Tactical Read",
        "m_tag_school": "Academy Manga",
        "m_tag_martial_arts": "Duel Manga",
        "m_tag_vampire": "Goal Thirst Manga",
        "m_tag_samurai": "Precision Manga",
        "m_tag_space": "World Stage Manga",
        "m_tag_parody": "Chibi Striker Read",
        "m_tag_idol": "Stadium Idol Read",
        "m_tag_post_apocalyptic": "Post-Selection Read",
        "m_tag_cyberpunk": "Data Analysis Read",
        "m_tag_shoujo": "Bachira's Story",
        "m_tag_survival": "Survival Read",
        "m_tag_cooking": "Team Meal Read",
        "m_tag_medical": "Sports Medic Read",
        "m_tag_villainess": "Villain Striker Read",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Completionist",
        "m_mega_completionist": "Supreme Reader",
        "m_completion_rate_50": "Halftime Reader",
        "m_completion_rate_75": "Final Quarter Read",
        "m_completion_rate_90": "Injury Time Read",
        "m_no_drop": "No Manga Dropped",
        "m_long_runner_complete": "Long Series Medal",
        "m_sequel_chain": "Sequel Chain Read",
        "m_clean_list": "Clean Reading List",
        "m_from_ptr": "Off the Bench Read",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Specialist",
        "m_same_day_start_finish": "Same-Day Read Blitz",
        "m_revival": "Revival Chapter",
        "m_zero_to_hundred": "Zero to Ace Reader",
        "m_five_genre_complete": "Five-Genre Clear",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Clear",
        "m_paused_to_done": "Back from Hiatus",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Badge",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi-Pass Reread",
        "m_dropped_recovery": "Recovered Reader",
        "m_ten_perfect_scores": "Ten Perfect Reads",
        "m_complete_genre_span": "All-Genre Reader",
        "m_monthly_completions": "Monthly Read Wins",
        "m_yearly_completions": "Yearly Read Trophy",
        "m_rapid_complete": "Rapid Read Clear",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Devotee",
        "m_rereader": "Scout Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Appreciation",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Material Fan",
        "m_waiting_weekly": "Weekly Chapter Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyalty Read",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "LN Adaptation Read",
        "m_original_work": "Original Work Read",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Favorite Mangaka",
        "m_complete_portfolio": "Complete Portfolio",
        "m_franchise_collector": "Franchise Collector",
        "m_serialization_follower": "Serialization Follow",
        "m_genre_master": "Genre Master Read",
        "m_multi_series_author": "Multi-Series Author",
        "m_format_diversity": "Format Diversity",
        "m_year_dedication": "Year of Reading",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Loyalty Reads",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer Read",
        "m_publisher_hopper": "Publisher Transfer",
        "m_tag_explorer": "Tag Scouting Read",
        "m_decade_hopper": "Decade Hopper Read",
        "m_hidden_gem": "Hidden Gem Found",
        "m_popular_taste": "Popular Reader Pick",
        "m_retro_reader": "Retro Manga Fan",
        "m_modern_reader": "Modern Manga Fan",
        "m_cross_demographic": "Cross-Demo Reader",
        "m_underdog_fan": "Underdog Reader",
        "m_variety_week": "Variety Week Read",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Connoisseur",
        "m_award_winner": "Award-Winning Read",
        "m_niche_explorer": "Niche Explorer Read",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic Read",
        "m_random_pick": "Random Pick Read",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Completionist",
        "m_unpopular_opinion": "Unpopular Read",
        "m_top_rated_reader": "Top-Rated Reader",
        "m_source_variety": "Source Variety Read",
        "m_low_score_brave": "Brave Low Score",
        "m_short_manga_explorer": "Short Manga Scout",
        "m_long_manga_explorer": "Long Manga Scout",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Halftime Reader",
        "m_commute_reader": "Commute Reader",
        "m_four_am_club": "4 AM Reading",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All-Hours Reader",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "Workday Reader",
        "m_sunday_read": "Sunday Read",
        "m_morning_routine": "Morning Read",
        "m_night_shift_reader": "Night Shift Read",
        "m_seasonal_premier_read": "New Release Read",
        "m_clock_collector": "Reading Clock",
        "m_late_night_horror": "Midnight Horror",
        "m_afternoon_reader": "Afternoon Reader",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Reader Scout",
        "m_twilight_reader": "Twilight Reader",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Read Hours",
        "m_late_night_regular": "Late Night Regular",
        "m_sunrise_reader": "Sunrise Reader",
        "m_every_day_of_week": "Every Day Reading",
        "m_monthly_hours": "Monthly Read Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color Read",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Reader",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel Reader",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Narrator",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award-Winning Art",
        "m_debut_work": "Debut Work Read",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross-Media Read",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collab Read",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read Streak",
        "m_mega_streak": "Mega Read Streak",
        "m_weekly_warrior": "Weekly Read Warrior",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader Comeback",
        "m_weekend_streak": "Weekend Read Streak",
        "m_no_zero_days": "No Zero Read Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Habit",
        "m_consistent_pace": "Consistent Reading",
        "m_year_long": "Year-Long Read Streak",
        "m_double_streak": "Double Read Streak",
        "m_streak_recovery": "Streak Recovery Read",
        "m_daily_minimum": "Daily Min Pages",
        "m_winter_streak": "Winter Read Streak",
        "m_summer_streak": "Summer Read Streak",
        "m_morning_streak": "Morning Read Streak",
        "m_night_streak": "Night Read Streak",
        "m_unbreakable": "Unbreakable Reader",
        "m_eternal_flame": "Eternal Read Flame",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Read Streak",
        "m_completion_streak": "Completion Streak",
        "m_rating_streak": "Rating Read Streak",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Read Week",
        "m_diverse_streak": "Diverse Read Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manga Critic",
        "m_perfect_ten": "Perfect Ten Read",
        "m_harsh_critic": "Harsh Read Critic",
        "m_fair_judge": "Fair Read Judge",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Full Read Scores",
        "m_wide_range": "Wide Range Reads",
        "m_controversial": "Controversial Read",
        "m_consistent_scorer": "Consistent Reader",
        "m_score_sniper": "Precision Reader",
        "m_evolving_taste": "Evolving Read Taste",
        "m_bell_curve": "Bell Curve Reads",
        "m_picky_reader": "Selective Reader",
        "m_100_rated": "Century Read Scores",
        "m_500_rated": "Five Hundred Scores",
        "m_mediocre_majority": "Mid-Table Reader",
        "m_rating_spree": "Rating Read Spree",
        "m_score_variance": "Variable Read Scores",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Re-Rate",
        "m_masterpiece_hunter": "Masterpiece Reader",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimist Reader",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Read Critic",
        "m_mean_above_8": "Elite Read Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Read Goal",
        "m_valentines_read": "Valentine's Read",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Fools Read",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Solstice Read",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Friday 13th Read",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thanksgiving Read",
        "m_christmas_read": "Winter Cup Read",
        "m_new_years_eve": "New Year's Eve Read",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Read Marathon",
        "m_independence_day": "Freedom Read Day",
        "m_culture_day": "Culture Day Read",
        "m_spring_equinox": "Spring Equinox Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Winter Solstice Read",
        "m_manga_birthday": "Manga Anniversary",
        "m_every_holiday_reader": "Every Holiday Reader",
        "m_consecutive_holidays": "Consecutive Read Days",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Read",
        "m_fibonacci": "Fibonacci Chapters",
        "m_palindrome_day": "Palindrome Read Day",
        "m_binary_day": "Binary Read Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven Read",
        "m_thousand_complete": "Thousand Read Wins",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Power Level Chapters",
        "m_answer_42": "Answer to Reading",
        "m_square_number": "Square Number Read",
        "m_prime_count": "Prime Read Count",
        "m_matching_date": "Matching Read Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapter Read",
        "m_synchronicity": "Reading Sync",
        "m_world_record": "World Record Read",
        "m_genre_clash": "Genre Clash Read",
        "m_time_traveler": "Time Travel Read",
        "m_double_digits": "Double Digit Read",
        "m_one_two_three": "One Two Three Read",
        "m_lucky_seven": "Lucky Seven Read",
        "m_exact_hundred_ch": "Exact Hundred Reads",
        "m_year_match_count": "Year Match Reads",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master Read",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Read Unlock",
        "m_meta_collector": "Read Badge Collector",
        "m_meta_category_starter": "Category Kickoff",
        "m_meta_tier_climber": "Read Rank Climber",
        "m_meta_tier_max": "Maximum Read Rank",
        "m_meta_xp_earner": "XP from Reading",
        "m_meta_difficulty_easy": "Easy Read Drill",
        "m_meta_difficulty_hard": "Legendary Read",
        "m_meta_unlock_spree": "Read Unlock Spree",
        "m_meta_completionist": "Meta Read Complete",
        "m_meta_diverse": "Diverse Read Portfolio",
        "m_meta_dominator": "Meta Read Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020408",
        primary: "#0064ff",
        secondary: "#0050d2",
        accent: "#3388ff",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/blue-lock.jpg",
    particleColor: "#2840c0",
    backgroundDim: 0.3,
    backgroundBlur: 25,
    particleTypes: {
        soccer_trails: { label: "Soccer Trails", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        goal_flash: { label: "Goal Flash", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        field_sparks: { label: "Field Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        striker_aura: { label: "Striker Aura", maxCount: 6, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1:   "Candidate",
        5:   "Selected",
        15:  "First Selection",
        30:  "Second Selection",
        45:  "Third Selection",
        60:  "Neo Egoist",
        80:  "World's Best",
        100: "Blue Lock Striker",
    },
}
