import { AnimeThemeConfig } from "./types"
import { GiHeartKey, GiFlowers, GiCandyCanes, GiSun, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiCupcake, GiBowTieRibbon, GiButterfly } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const candyCandyTheme: AnimeThemeConfig = {
    id: "candy-candy",
    displayName: "Candy Candy",
    description: "The irrepressibly cheerful orphan Candice White Ardlay grows up in a children's home, falling in love, suffering heartbreak, and spreading joy wherever she goes — in this legendary shojo classic that defined a generation.",
    fontFamily: "'Pacifico', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Pacifico&display=swap",
    cssVars: {
        "--color-brand-200": "255 192 222",
        "--color-brand-300": "252 152 196",
        "--color-brand-400": "242 108 168",
        "--color-brand-500": "225 66 140",
        "--color-brand-600": "195 28 108",
        "--color-brand-700": "155 4 78",
        "--color-brand-800": "108 0 52",
        "--color-brand-900": "62 0 28",
        "--color-brand-950": "26 0 10",
        "--brand": "225 66 140",
        "--background": "#060002",
        "--paper": "#110005",
        "--color-gray-950": "6 0 2",
        "--color-gray-900": "13 2 6",
        "--color-gray-800": "24 6 12",
        "--color-gray-700": "42 12 22",
        "--color-gray-600": "68 22 40",
        "--color-gray-500": "110 48 74",
        "--color-gray-400": "158 86 118",
        "--color-gray-300": "200 130 162",
        "--color-gray-200": "230 175 200",
        "--color-gray-100": "248 210 228",
        "--color-gray-50": "255 238 248",
    },
    sidebarOverrides: {
        "home": { icon: GiCandyCanes, label: "Candy's World" },
        "schedule": { icon: GiAlarmClock, label: "Daily Schedule" },
        "manga": { icon: LuBookOpen, label: "Candy's Diary" },
        "lists": { icon: GiFlowerEmblem, label: "Friends List" },
        "discover": { icon: GiBullseye, label: "New Adventures" },
        "torrent-list": { icon: GiCupcake, label: "Sweet Cache" },
        "debrid": { icon: GiButterfly, label: "Candy's Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Friends" },
        "enmasse": { icon: GiResize, label: "Candy Group" },
        "scan-summaries": { icon: TbReportSearch, label: "Diary Reports" },
        "auto-downloader": { icon: LuRss, label: "Candy's Letters" },
        "community": { icon: GiFlowers, label: "Candy's Circle" },
        "achievements": { icon: GiTrophy, label: "Sweet Trophies" },
        "milestones": { icon: LuFlag, label: "Life Milestones" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Love Alerts" },
        "theme-manager": { icon: GiPalette, label: "Pink Palette" },
        "extensions": { icon: BiExtension, label: "Sweet Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Heart Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Candy's Config" },
    },
    achievementNames: {
        "a_first_episode": "Candy's First Day",
        "a_first_complete": "Happy Ending",
        "a_hundred_club": "Hundred Smiles",
        "a_time_lord": "Classic Fan",
        "a_anime_collector": "Candy Archive",
        "a_library_legend": "Sweet Library",
        "a_binge_king": "Shojo Marathon",
        "a_no_sleep": "All-Night Tears",
        "a_marathon_runner": "Candy's Run",
        "a_speed_run": "Sweet Speed",
        "a_completionist": "Candy's Journey",
        "a_mega_completionist": "Shojo Master",
        "a_loyal_fan": "Devoted Friend",
        "a_rewatcher": "Encore Story",
        "a_decade_watcher": "Decade Candy",
        "a_genre_action": "None Here",
        "a_genre_adventure": "Candy's Journey",
        "a_genre_comedy": "Sweet Laughter",
        "a_genre_drama": "Candy's Tears",
        "a_genre_fantasy": "None Here",
        "a_genre_horror": "None Here",
        "a_genre_romance": "True Love",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Candy's Heart",
        "a_genre_mecha": "None Here",
        "a_critic": "Sweet Critic",
        "a_perfect_ten": "Perfect Love",
        "a_harsh_critic": "Classic Standard",
        "a_daily_streak": "Daily Smile",
        "a_mega_streak": "Endless Sweet",
        "a_year_long": "Year of Candy",
        "a_iron_will": "Candy's Spirit",
        "a_hidden_gem": "Secret Love",
        "a_cult_classic": "Shojo Legend",
        "a_classic_connoisseur": "1976 Fan",
        "a_new_years_resolution": "Sweet New Year",
        "a_christmas_special": "Winter Love",
        "a_meta_tier_max": "True Candy",
        "a_meta_completionist": "All Sweet",
        "a_sequel_chain": "Candy's Chain",
        "a_zero_to_hero": "Orphan to Lady",
        "a_night_owl": "Night Tears",
        "a_early_bird": "Dawn Smile",
        "m_first_chapter": "First Letter",
        "m_first_complete": "Sweet Arc",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Shojo Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Candy Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Sweet Memory",
        "m_genre_action": "None Here",
        "m_genre_adventure": "Adventure Chapter",
        "m_genre_romance": "Love Chapter",
        "m_genre_fantasy": "None Here",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Tears Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Heart Chapter",
        "m_critic": "Sweet Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Sweet Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Sweet Spirit",
        "m_hidden_gem": "Hidden Letter",
        "m_cult_classic": "Shojo Classic",
        "m_mangaka_lover": "Igarashi Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Candy Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Sweet Art",
        "m_manga_to_anime": "Adapted Sweet",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060002",
        primary: "#e1428c",
        secondary: "#c31c6c",
        accent: "#f8e040",
    },
    particleColor: "#f070a0",
    backgroundDim: 0.22,
    backgroundBlur: 10,
    particleTypes: {
        cherry_petals: { label: "Sweet Petals", maxCount: 20, defaultEnabled: true, defaultIntensity: 60 },
        sparkles: { label: "Candy Sparkles", maxCount: 12, defaultEnabled: true, defaultIntensity: 48 },
    },
    milestoneNames: {
        1: "Little Orphan",
        5: "Sunshine Girl",
        15: "Candy Sweet",
        30: "True Friend",
        50: "Brave Heart",
        75: "Lady Candy",
        100: "Candy Candy",
    },
}
