import { AnimeThemeConfig } from "./types"
import {
    GiDeathSkull,
    GiSwordWound,
    GiMuscleUp,
    GiEvilHand,
    GiSkullCrossedBones,
    GiShadowFollower,
    GiBullseye,
    GiResize,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiSettingsKnobs,
    GiFireworkRocket,
    GiBrain,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const chainsawManTheme: AnimeThemeConfig = {
    id: "chainsaw-man",
    displayName: "Chainsaw Man",
    description: "Make your dreams come true. Denji merges with Pochita, joins Public Safety, and revs up the chainsaw against every devil in his path.",
    fontFamily: "'Bebas Neue', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
    cssVars: {
        "--color-brand-200": "255 210 200",
        "--color-brand-300": "255 168 140",
        "--color-brand-400": "248 110 70",
        "--color-brand-500": "232 64 32",
        "--color-brand-600": "200 38 15",
        "--color-brand-700": "160 22 8",
        "--color-brand-800": "118 12 4",
        "--color-brand-900": "75 5 2",
        "--color-brand-950": "38 2 1",
        "--brand": "232 64 32",
        "--background": "#070301",
        "--paper": "#100804",
        "--color-gray-950": "7 3 1",
        "--color-gray-900": "16 8 4",
        "--color-gray-800": "28 16 10",
        "--color-gray-700": "45 28 20",
        "--color-gray-600": "68 48 38",
        "--color-gray-500": "100 80 68",
        "--color-gray-400": "145 128 118",
        "--color-gray-300": "185 172 165",
        "--color-gray-200": "215 205 200",
        "--color-gray-100": "238 232 230",
        "--color-gray-50": "250 247 245",
    },
    sidebarOverrides: {
        "home": { icon: GiDeathSkull, label: "Devil Hunter HQ" },
        "schedule": { icon: GiAlarmClock, label: "Extermination Calendar" },
        "manga": { icon: LuBookOpen, label: "Devil Reports" },
        "lists": { icon: GiSwordWound, label: "Division 4 Roster" },
        "discover": { icon: GiBullseye, label: "Beyond the Door" },
        "torrent-list": { icon: GiFireworkRocket, label: "Devil Parts Cache" },
        "debrid": { icon: GiEvilHand, label: "Makima's Orders" },
        "unmatched": { icon: GiSkullCrossedBones, label: "Lost Hunters" },
        "enmasse": { icon: GiResize, label: "Mass Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Public Safety Reports" },
        "auto-downloader": { icon: LuRss, label: "Devil Tracker" },
        "community": { icon: GiShadowFollower, label: "Public Safety Agency" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Pochita's Warning" },
        "achievements": { icon: GiTrophy, label: "Contract Feats" },
        "theme-manager": { icon: GiPalette, label: "Chainsaw Colors" },
        "extensions": { icon: BiExtension, label: "Devil Attachments" },
        "sync": { icon: IoCloudOfflineOutline, label: "Denji Link" },
        "settings": { icon: GiSettingsKnobs, label: "Chainsaw HQ" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Starving Devil Hunter",
        "a_episode_counter": "Devil Contract Count",
        "a_episode_titan": "Special-Grade Devil Encounter",
        "a_hours_invested": "Hours on Devil Hunts",
        "a_time_lord": "Pochita's Endless Dream",
        "a_anime_collector": "Division 4 Arsenal",
        "a_library_legend": "Devil Research Legend",
        "a_first_complete": "First Devil Exterminated",
        "a_hundred_club": "Century of Devil Kills",
        "a_first_day": "First Day as Hunter",
        "a_first_rating": "Contract Assessment",
        "a_ten_thousand_min": "Ten Thousand Minutes Hunting",
        "a_season_veteran": "Veteran Devil Hunter",
        "a_year_explorer": "Year Among Devils",
        "a_century_watcher": "Hundred Episodes in Division 4",
        "a_five_hundred_eps": "Five Hundred Chainsaw Revs",
        "a_thousand_eps": "Thousand Devil Encounters",
        "a_watching_ten": "Ten Fronts Simultaneously",
        "a_ptw_hoarder": "Backlog of Devil Contracts",
        "a_dropped_honesty": "Strategic Retreat from Devils",
        "a_five_thousand_eps": "Five Thousand Sorties",
        "a_ten_completed": "Ten Devil Hunt Campaigns",
        "a_fifty_completed": "Fifty Contracts Completed",
        "a_five_hundred_completed": "Five Hundred Devil Victories",
        "a_mean_score_tracker": "Average Contract Rating",
        "a_unique_studios": "Allied Hunter Divisions",
        "a_days_spent_watching": "Days in Division 4",
        "a_all_status": "All Hunter Statuses",
        "a_first_favorite": "First Bond with Pochita",
        "a_favorites_collector": "Division 4 Bonds",
        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Chainsaw Rampage",
        "a_marathon_runner": "Devil Hunt Marathon Runner",
        "a_weekend_warrior": "Weekend Devil Hunter",
        "a_non_stop": "Relentless Like Denji",
        "a_one_more_episode": "One More Devil to Kill",
        "a_speed_run": "Chainsaw Speed Dash",
        "a_double_feature": "Double Devil Feature",
        "a_triple_threat": "Triple Contract Takedown",
        "a_five_a_day": "Five Devils a Day",
        "a_back_to_back": "Back-to-Back Devil Hunts",
        "a_seasonal_binge": "Full Devil Arc Clear",
        "a_cour_crusher": "Division Cour Crusher",
        "a_half_day_watch": "Half Day Devil Hunt",
        "a_full_day_watch": "Full Day Hunting Devils",
        "a_power_weekend": "Power Weekend Offensive",
        "a_binge_king": "King of the Devil Hunters",
        "a_no_sleep": "All-Night Devil Vigil",
        "a_entire_season": "Full Hunter Arc Clear",
        "a_seven_day_challenge": "Seven-Day Devil Siege",
        "a_hundred_day_binge": "Hundred-Day Devil Siege",
        "a_genre_binge": "Cross-Genre Devil Fantasy",
        "a_studio_binge": "Studio Alliance Binge",
        "a_season_sweep": "Season Sweep of Blood",
        "a_forty_eight_hour": "Forty-Eight Hour Hunt",
        "a_ep_counter_day": "Daily Chainsaw Count",
        "a_multi_series_binge": "Multi-Front Devil Campaign",
        "a_midnight_binge": "Midnight Devil Session",
        "a_new_year_binge": "New Year's Devil Charge",
        // ── ANIME GENRES ──
        "a_genre_action": "Chainsaw Combat Specialist",
        "a_genre_adventure": "Journey Through Hell's Door",
        "a_genre_comedy": "Denji's Comic Moments",
        "a_genre_drama": "Aki's Tragic Drama",
        "a_genre_fantasy": "Devil World Realm",
        "a_genre_horror": "Gun Devil Horror",
        "a_genre_mystery": "Makima's True Identity",
        "a_genre_romance": "Denji's Dream Date",
        "a_genre_scifi": "Devil Biology Tech",
        "a_genre_sol": "Peaceful Days in Division 4",
        "a_genre_sports": "Devil Hunter Training Grounds",
        "a_genre_supernatural": "Chainsaw Devil Power",
        "a_genre_thriller": "Control Devil Thriller",
        "a_genre_mecha": "Devil Hunter Equipment",
        "a_genre_music": "Chainsaw Man OST",
        "a_genre_psychological": "Power's Inner World",
        "a_genre_ecchi": "Denji's Hot Spring Dreams",
        "a_genre_mahou_shoujo": "Makima's Control Magic",
        "a_tag_isekai": "Transported to Devil World",
        "a_tag_harem": "Division 4 Bonds",
        "a_tag_bl": "Denji and Aki Bond",
        "a_tag_gl": "Power and Himeno Bond",
        "a_tag_historical": "Devil Contract History",
        "a_tag_military": "Public Safety Military",
        "a_tag_school": "Devil Hunter Training Camp",
        "a_tag_martial_arts": "Chainsaw Blade Mastery",
        "a_tag_vampire": "Blood Devil Pact",
        "a_tag_samurai": "Sword Devil Style",
        "a_tag_space": "Beyond the Door Realm",
        "a_tag_parody": "Chainsaw Parody",
        "a_tag_idol": "Power Idol",
        "a_tag_post_apocalyptic": "Post-Gun Devil World",
        "a_tag_cyberpunk": "Devil Tech Weapons",
        "a_tag_shounen": "Denji's Determined Heart",
        "a_tag_seinen": "Chainsaw Man Seinen Reality",
        "a_tag_shoujo": "Himeno's Devotion",
        "a_tag_josei": "Reze's Perspective",
        "a_tag_survival": "Surviving Devil Attacks",
        // ── ANIME COMPLETION ──
        "a_completionist": "Full Devil Hunt Report",
        "a_mega_completionist": "Public Safety Commander",
        "a_completion_rate_50": "Halfway to Gun Devil",
        "a_completion_rate_75": "Approaching Makima's Truth",
        "a_completion_rate_90": "Final Devil Nearly Down",
        "a_no_drop": "No Hunter Left Behind",
        "a_long_runner_complete": "Long Devil Hunt Complete",
        "a_sequel_chain": "Contract Chain Complete",
        "a_clean_list": "Clean Hunter Record",
        "a_from_ptw": "Orders Received Executed",
        "a_rewatch_master": "Reliving Pochita's Contract",
        "a_short_complete": "Quick Devil Skirmish",
        "a_same_day_start_finish": "Same-Day Devil Elimination",
        "a_revival": "Revived by Pochita",
        "a_zero_to_hero": "Trash Collector to Devil Hybrid",
        "a_five_genre_complete": "Five-Genre Devil Mastery",
        "a_full_franchise": "Full Chainsaw Man Dossier",
        "a_batch_complete": "Batch Devil Clear",
        "a_paused_to_done": "Returned from Near Death",
        "a_completion_spree": "Completion Chainsaw Spin",
        "a_multi_rewatch": "Multi-Timeline Devil Saga",
        "a_dropped_recovery": "Recovered from Devil's Grip",
        "a_ten_perfect_scores": "Ten Perfect Contract Scores",
        "a_seasonal_clear": "Seasonal Devil Campaign Clear",
        "a_complete_genre_span": "All-Terrain Devil Hunter",
        "a_monthly_completions": "Monthly Contract Reports",
        "a_yearly_completions": "Yearly Devil Campaign",
        "a_rapid_complete": "Lightning Devil Raid",
        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Chainsaw Devotee",
        "a_studio_devotee": "Studio Devil Devotee",
        "a_rewatcher": "Devil Contract Rewatch",
        "a_triple_rewatch": "Triple Chainsaw Rewatch",
        "a_annual_tradition": "Annual Pochita Remembrance",
        "a_director_fan": "Nakayama's Vision Follower",
        "a_voice_actor_fan": "Voice of the Devil Hunters",
        "a_ost_lover": "Chainsaw Man OST Devotee",
        "a_source_reader": "Fujimoto's Original Manga",
        "a_waiting_weekly": "Weekly Devil Chapter Wait",
        "a_childhood_revisit": "Return to Pochita's Days",
        "a_saga_tracker": "Saga of the Chainsaw Tracker",
        "a_genre_loyalty": "Devil Fantasy Loyalty",
        "a_decade_watcher": "Decade-Long Devil Hunter",
        "a_adaptation_hunter": "Chainsaw Adaptation Hunt",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Hunter Duty",
        "a_perfect_attendance": "Perfect Division Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Devil Catalog",
        "a_franchise_collector": "Chainsaw Universe Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Devil Genre Mastery",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Arc Devil Veteran",
        "a_format_diversity": "Diverse Devil Formats",
        "a_year_dedication": "Year of Dedication to Denji",
        "a_season_dedication": "Season of Devil Service",
        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Devil Territory",
        "a_studio_hopper": "Division Transfer",
        "a_tag_explorer": "Devil Tag Recon Mission",
        "a_decade_hopper": "Time via Pochita Contract",
        "a_hidden_gem": "Hidden Devil Gem",
        "a_popular_taste": "Popular Among Devil Hunters",
        "a_retro_appreciator": "Pre-Contract Era Appreciator",
        "a_modern_viewer": "Modern Devil Viewer",
        "a_cross_demographic": "Cross-Demographic Hunter",
        "a_underdog_fan": "Underdog Devil Hunter",
        "a_variety_week": "Week of Varied Contracts",
        "a_foreign_cinema": "Foreign Devil Cinema",
        "a_classic_connoisseur": "Classic Devil Fantasy Fan",
        "a_every_season": "Every Season Hunting Devils",
        "a_award_winner": "Medal of Devil Valor",
        "a_niche_explorer": "Niche Devil Territory",
        "a_global_anime": "Global Hunter Alliance",
        "a_cult_classic": "Chainsaw Man Cult Classic",
        "a_random_pick": "Random Contract Assignment",
        "a_new_genre_month": "New Devil Territory Monthly",
        "a_seasonal_completionist": "Seasonal Devil Campaign Clear",
        "a_unpopular_opinion": "Unpopular Devil Opinion",
        "a_top_rated_viewer": "Top-Rated Devil Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Devil Intel",
        "a_short_series_explorer": "Short Devil Skirmish Explorer",
        "a_long_series_explorer": "Long Devil Campaign Explorer",
        // ── ANIME TIME ──
        "a_night_owl": "Night Watch in Division 4",
        "a_early_bird": "Dawn Devil Hunt",
        "a_lunch_break": "Devil Hunter Mess Break",
        "a_golden_hour": "Golden Hour Before Contract",
        "a_four_am_club": "4 AM Devil Sentry",
        "a_witching_hour": "Devil Witching Hour",
        "a_new_year_watch": "New Year's Devil Oath",
        "a_midnight_premiere": "Midnight Chainsaw Premiere",
        "a_all_hours": "All-Hours Devil Vigil",
        "a_dawn_warrior": "Dawn Devil Warrior",
        "a_afternoon_delight": "Afternoon Division 4 Rest",
        "a_prime_time": "Prime Time Devil Battle",
        "a_workday_watcher": "On-Duty Devil Watcher",
        "a_sunday_marathon": "Sunday Devil Marathon",
        "a_rainy_day": "Rainy Day in Division 4",
        "a_morning_routine": "Morning Division Formation",
        "a_night_shift": "Night Shift Devil Guard",
        "a_twilight_zone": "Twilight Beyond the Door",
        "a_seasonal_premier": "Season Premiere Hunt",
        "a_clock_collector": "Devil Clock Collector",
        "a_weekend_binge_hours": "Weekend Devil Binge Ops",
        "a_late_night_regular": "Late Night Regular Hunter",
        "a_sunrise_watcher": "Sunrise Over Devil Ruins",
        "a_holiday_watcher": "Holiday Devil Duty",
        "a_every_day_of_week": "Every Day a Devil Hunter",
        "a_monthly_hours": "Monthly Hunter Duty Hours",
        // ── ANIME SOCIAL ──
        "a_first_party": "First Division 4 Formation",
        "a_party_host": "Division 4 Commander",
        "a_social_butterfly": "Division 4 Socialite",
        "a_group_binge": "Group Devil Viewing",
        "a_party_regular": "Regular Devil Partner",
        "a_sync_viewer": "Synchronized Chainsaw Maneuver",
        "a_commentator": "Devil Battle Commentator",
        "a_party_marathon": "Marathon Division Run",
        "a_full_house": "Full Division 4 Squad",
        "a_community_pillar": "Pillar of Division 4",
        "a_watch_party_streak": "Consecutive Division Streak",
        "a_diverse_party": "Diverse Hunter Party",
        "a_late_night_party": "Late Night Hunter Party",
        "a_party_veteran": "Veteran Division Leader",
        "a_genre_party": "Cross-Genre Devil Formation",
        "a_weekly_party": "Weekly Hunters' Gathering",
        "a_silent_viewer": "Silent Like Aki Observer",
        "a_recommendation_giver": "Devil Hunter's Recommendation",
        "a_party_completionist": "Party Contract Completionist",
        "a_social_scorer": "Social Devil Scorer",
        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Contract",
        "a_fibonacci": "Fibonacci Devil Sequence",
        "a_palindrome_day": "Palindrome Contract Loop",
        "a_binary_day": "Binary Devil Signal Day",
        "a_full_moon": "Full Moon Devil Transformation",
        "a_leap_year": "Leap Year Contract Skip",
        "a_time_traveler": "Pochita's Future Memory",
        "a_genre_clash": "Denji vs Makima Clash",
        "a_triple_seven": "Triple Seven Devil Contracts",
        "a_thousand_complete": "Thousand Devil Battles",
        "a_pi_episodes": "Pi Devil Calculation",
        "a_synchronicity": "Chainsaw Synchronicity",
        "a_world_record": "World Record Devil Kill",
        "a_nice": "Nice Kill Count",
        "a_power_level": "Chainsaw Devil Power Level",
        "a_answer_42": "Answer to Devils",
        "a_square_number": "Perfect Division Formation",
        "a_prime_count": "Prime Devil Count",
        "a_matching_date": "Matching Contract Date",
        "a_century_episode": "Century Episode Hunt",
        "a_double_digits": "Double Digit Devil Kills",
        "a_one_two_three": "Denji Power Aki",
        "a_lucky_seven": "Seven Lucky Hunters",
        "a_all_tens": "All Tens Contract Score",
        "a_exact_hundred_eps": "Exact Hundred Contracts",
        "a_year_match_count": "Year Match Kill Count",
        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Hunter",
        "a_movie_buff": "Chainsaw Movie Operations",
        "a_ova_hunter": "OVA Devil Hunter",
        "a_ona_explorer": "ONA Devil Explorer",
        "a_special_watcher": "Special Devil Episode",
        "a_short_king": "Short Contract King",
        "a_variety_pack": "All-Format Hunter Regiment",
        "a_film_festival": "Devil Film Festival",
        "a_music_video": "Chainsaw Music Video",
        "a_tv_short": "Quick Devil Recon Clip",
        "a_movie_marathon": "Devil Movie Marathon",
        "a_double_length": "Double-Length Devil Operation",
        "a_anthology": "Chainsaw Anthology",
        "a_mini_series": "Mini Devil Campaign",
        "a_theatrical": "Theatrical Devil Premiere",
        "a_format_master": "Format Master Hunter",
        "a_long_movie": "Feature-Length Devil Hunt",
        "a_back_catalog": "Back Catalog Division Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Devil Collector",
        "a_format_balance": "Balanced Devil Formats",
        "a_episodic_master": "Episodic Devil Master",
        "a_sequel_movie": "Sequel Devil Film",
        "a_recap_watcher": "Recap Devil Briefing",
        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Hunter Patrol Streak",
        "a_mega_streak": "Mega Devil Campaign Streak",
        "a_weekly_warrior": "Weekly Devil Warrior",
        "a_monthly_watcher": "Monthly Hunter Duty",
        "a_comeback": "Return from Near Death",
        "a_weekend_streak": "Weekend Devil Sortie Streak",
        "a_no_zero_days": "No Zero Devil Days",
        "a_iron_will": "Iron Will of the Chainsaw",
        "a_habit_formed": "Hunter Training Regimen Formed",
        "a_consistent_pace": "Consistent Devil March",
        "a_year_long": "Year-Long Devil Campaign",
        "a_double_streak": "Double Devil Assault Streak",
        "a_streak_recovery": "Recovery After Devil Attack",
        "a_daily_minimum": "Daily Minimum Devil Duty",
        "a_winter_streak": "Winter Devil Campaign",
        "a_summer_streak": "Summer Devil Offensive",
        "a_morning_streak": "Morning Hunter Drill Streak",
        "a_night_streak": "Night Devil Patrol Streak",
        "a_unbreakable": "Unbreakable Chainsaw Will",
        "a_eternal_flame": "Eternal Chainsaw Flame",
        "a_completion_streak": "Completion Contract Chain",
        "a_rating_streak": "Rating Contract Streak",
        "a_multi_ep_streak": "Multi-Episode Devil Offensive",
        "a_genre_streak": "Genre Devil Streak",
        "a_studio_streak": "Studio Devil Loyalty Streak",
        "a_perfect_week": "Perfect Week of Devil Service",
        // ── ANIME SCORING ──
        "a_critic": "Devil Contract Judge",
        "a_perfect_ten": "Perfect 10 Devil Rating",
        "a_harsh_critic": "Makima's Harsh Standards",
        "a_fair_judge": "Kishibe's Fair Assessment",
        "a_generous_spirit": "Generous Hunter Spirit",
        "a_score_all": "Full Division 4 Evaluation",
        "a_wide_range": "Wide Range Devil Assessment",
        "a_controversial": "Controversial Contract Decision",
        "a_consistent_scorer": "Consistent Devil Evaluator",
        "a_score_sniper": "Precision Devil Sniper",
        "a_evolving_taste": "Evolving Hunter Strategy",
        "a_bell_curve": "Bell Curve Devil Scores",
        "a_picky_watcher": "Selective Hunter Commander",
        "a_100_rated": "Century of Contract Evaluations",
        "a_500_rated": "Five Hundred Devil Reports",
        "a_mediocre_majority": "Middle Ground Strategist",
        "a_rating_spree": "Devil Rating Barrage",
        "a_score_variance": "Variable Devil Ratings",
        "a_masterpiece_hunter": "Masterpiece Devil Hunter",
        "a_contrarian": "Contrarian Devil Scout",
        "a_optimist": "Optimist Despite the Devils",
        "a_score_distributor": "Score Distributor Commander",
        "a_genre_critic": "Genre Devil Critic",
        "a_mean_above_8": "Elite Hunter Average",
        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Devil Vow",
        "a_valentines_weeb": "Valentine's Devil Bond",
        "a_pi_day": "Pi Day Devil Calculation",
        "a_april_fools": "April Fools Devil Prank",
        "a_international_anime_day": "International Hunter Day",
        "a_star_wars_day": "Gun Devil Empire Day",
        "a_summer_solstice": "Summer Solstice Devil Hunt",
        "a_tanabata": "Tanabata Wish for Pochita",
        "a_friday_13th": "Friday the 13th Devil Attack",
        "a_halloween_spirit": "Halloween Devil Horror",
        "a_thanksgiving_binge": "Thanksgiving Devil Feast",
        "a_christmas_special": "Midwinter Devil Festival",
        "a_new_years_eve": "New Year's Eve Devil Stand",
        "a_birthday_watch": "Birthday Hunter Enlistment",
        "a_holiday_marathon": "Holiday Devil Marathon",
        "a_independence_day": "Hunter Independence Day",
        "a_culture_day": "Division 4 Culture Day",
        "a_spring_equinox": "Spring Devil Advance",
        "a_earth_day": "Protect Earth from Devils",
        "a_labor_day": "Hunter Labor Day",
        "a_winter_solstice": "Winter Devil Solstice",
        "a_anime_birthday": "Chainsaw Man Anniversary",
        "a_every_holiday": "Every Holiday Hunter",
        "a_consecutive_holidays": "Consecutive Holiday Hunts",
        // ── ANIME META ──
        "a_meta_first_unlock": "First Devil Power Awakened",
        "a_meta_collector": "Hunter Badge Collector",
        "a_meta_category_starter": "Category Contract Initiation",
        "a_meta_tier_climber": "Rank in Division 4",
        "a_meta_tier_max": "Captain-Class Hunter",
        "a_meta_xp_earner": "XP from Devil Kills",
        "a_meta_difficulty_easy": "Easy Training Exercise",
        "a_meta_difficulty_hard": "Legendary Kishibe Mode",
        "a_meta_unlock_spree": "Unlock Spree Chainsaw Spin",
        "a_meta_completionist": "Meta Hunter Completionist",
        "a_meta_diverse": "Diverse Devil Portfolio",
        "a_meta_dominator": "Meta Dominator of Devils",
        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter of Contracts",
        "m_chapter_counter": "Devil Chapter Counter",
        "m_chapter_titan": "Chapter Devil Assault",
        "m_reading_hours": "Hours Studying Devil Lore",
        "m_reading_time_lord": "Pochita's Reading Memory",
        "m_manga_collector": "Devil Archive Collector",
        "m_library_legend": "Devil Research Library Legend",
        "m_first_complete": "First Devil Manga Done",
        "m_hundred_club": "Hundred-Chapter Hunter Club",
        "m_first_day": "First Day Devil Reading",
        "m_first_rating": "First Devil Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Devil Pages",
        "m_volume_collector": "Devil Volume Collector",
        "m_year_explorer": "Year of Devil Exploration",
        "m_century_reader": "Century Devil Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Devil Chapters",
        "m_thousand_ch": "Thousand-Chapter Devil Campaign",
        "m_reading_ten": "Ten Devil Manuscripts at Once",
        "m_ptr_hoarder": "Devil Reading Backlog",
        "m_dropped_honesty": "Honest Devil Retreat",
        "m_season_reader": "Devil Seasonal Reading",
        "m_active_reader": "Active Devil Field Reader",
        "m_five_thousand_ch": "Five Thousand Devil Chapters",
        "m_ten_completed": "Ten Devil Manga Complete",
        "m_fifty_completed": "Fifty Devil Missions Done",
        "m_five_hundred_completed": "Five Hundred Devil Victories",
        "m_mean_score_tracker": "Average Devil Manuscript Rating",
        "m_unique_authors": "Unique Devil Author Encounters",
        "m_all_status": "All Devil Reading Statuses",
        "m_first_favorite": "First Devil Manga Bond",
        "m_favorites_collector": "Devil Favorites Arsenal",
        "m_days_spent_reading": "Days in Devil Division",
        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Devil Reading Advance",
        "m_marathon_reader": "Devil Hunt Marathon Reader",
        "m_weekend_reader": "Weekend Devil Reading",
        "m_non_stop_reading": "Non-Stop Devil Page Turning",
        "m_one_more_chapter": "One More Devil Chapter",
        "m_speed_read": "Chainsaw Speed Read",
        "m_double_story": "Double Devil Manuscript",
        "m_triple_read": "Triple Devil Reading",
        "m_five_a_day": "Five Devil Reads a Day",
        "m_chapter_chain": "Devil Chapter Chain",
        "m_volume_binge": "Devil Volume Binge",
        "m_power_reader": "Power Devil Reader",
        "m_half_day_read": "Half-Day Devil Archive",
        "m_full_day_read": "Full-Day Devil Study",
        "m_power_weekend": "Power Devil Weekend Reading",
        "m_binge_king": "King of the Devil Reading Corps",
        "m_no_sleep_read": "All-Night Devil Reading",
        "m_full_series_rush": "Full Devil Series Rush",
        "m_seven_day_challenge": "Seven-Day Devil Gathering",
        "m_hundred_day_read": "Hundred-Day Devil Reading",
        "m_volume_rush": "Devil Volume Rush",
        "m_series_sweep": "Devil Series Sweep",
        "m_genre_binge": "Cross-Genre Devil Reading",
        "m_author_binge": "Fujimoto Deep Dive",
        "m_chapter_counter_day": "Daily Devil Chapter Count",
        "m_multi_series_binge": "Multi-Series Devil Reading",
        "m_midnight_binge": "Midnight Devil Archive",
        "m_new_year_binge": "New Year's Devil Reading",
        "m_forty_eight_hour": "Forty-Eight Hour Devil Reading",
        "m_oneshot_binge": "Oneshot Devil Blitz",
        // ── MANGA GENRES ──
        "m_genre_action": "Devil Action Manuscript",
        "m_genre_adventure": "Adventure Beyond the Door",
        "m_genre_comedy": "Denji's Comic Chapters",
        "m_genre_drama": "Drama of Division 4",
        "m_genre_fantasy": "Fantasy of Devil World",
        "m_genre_horror": "Devil Horror Manuscript",
        "m_genre_mystery": "Mystery of Control Devil",
        "m_genre_romance": "Denji's Dream Romance",
        "m_genre_scifi": "Devil Tech Manga",
        "m_genre_sol": "Peaceful Division 4 Days",
        "m_genre_sports": "Devil Hunter Training Sports",
        "m_genre_supernatural": "Supernatural Devil Power",
        "m_genre_thriller": "Makima Thriller Manga",
        "m_genre_psychological": "Psychological Devil Warfare",
        "m_genre_isekai": "Isekai Beyond Devil World",
        "m_genre_shounen": "Devil Shounen Heart",
        "m_genre_ecchi": "Devil Hunter Hot Springs",
        "m_genre_mahou_shoujo": "Devil Magic Manga",
        "m_genre_mecha": "Devil Weapon Blueprints",
        "m_genre_music": "Chainsaw OST Collection",
        "m_tag_isekai_new": "New World of Devils",
        "m_tag_harem": "Division 4 Manga",
        "m_tag_bl": "Brothers in Devil Arms",
        "m_tag_gl": "Shield Sisters Devil Manga",
        "m_tag_historical": "Devil Contract History Manga",
        "m_tag_military": "Public Safety Military Manga",
        "m_tag_school": "Hunter Training Academy",
        "m_tag_martial_arts": "Chainsaw Combat Manual",
        "m_tag_vampire": "Blood Devil Manga",
        "m_tag_samurai": "Sword Devil Master",
        "m_tag_space": "Beyond the Door Manga",
        "m_tag_parody": "Chibi Devil Corps Manga",
        "m_tag_idol": "Power Idol Manga",
        "m_tag_post_apocalyptic": "Post-Gun Devil Manga",
        "m_tag_cyberpunk": "Devil Weapon Tech Manga",
        "m_tag_shoujo": "Himeno's Story Manga",
        "m_tag_survival": "Survival in Devil World Manga",
        "m_tag_cooking": "Division 4 Rations Cookbook",
        "m_tag_medical": "Devil Medic Manga",
        "m_tag_villainess": "Reze Devil Manga",
        // ── MANGA COMPLETION ──
        "m_completionist": "Devil Manga Completionist",
        "m_mega_completionist": "Supreme Devil Commander",
        "m_completion_rate_50": "Halfway to Control Devil",
        "m_completion_rate_75": "Approaching Makima's Truth",
        "m_completion_rate_90": "Final Devil Chapter Near",
        "m_no_drop": "No Devil Manuscript Abandoned",
        "m_long_runner_complete": "Long Devil Series Endurance",
        "m_sequel_chain": "Sequel Devil Arc Chain",
        "m_clean_list": "Clean Devil Reading Record",
        "m_from_ptr": "Orders Received Devil Read",
        "m_reread_master": "Devil Contract Memory Reread",
        "m_oneshot_complete": "Oneshot Devil Mission",
        "m_same_day_start_finish": "Same-Day Devil Blitz",
        "m_revival": "Revival by Pochita's Contract",
        "m_zero_to_hundred": "Trash Collector to Devil Scholar",
        "m_five_genre_complete": "Five Devil Genres Mastered",
        "m_full_collection": "Full Devil Archive",
        "m_batch_complete": "Devil Batch Clearance",
        "m_paused_to_done": "Back from Devil Hiatus",
        "m_completion_spree": "Devil Completion Barrage",
        "m_format_completionist": "Devil Format Completion",
        "m_catch_up": "Caught Up with Devil Serialization",
        "m_multi_reread": "Multi-Pass Devil Reread",
        "m_dropped_recovery": "Recovered from Devil's Grip",
        "m_ten_perfect_scores": "Ten Perfect Devil Scores",
        "m_complete_genre_span": "All-Genre Devil Scout",
        "m_monthly_completions": "Monthly Devil Victories",
        "m_yearly_completions": "Yearly Devil Campaign",
        "m_rapid_complete": "Rapid Devil Processing",
        "m_author_complete": "Fujimoto's Complete Works",
        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Devil Reader",
        "m_mangaka_lover": "Fujimoto Devotee",
        "m_rereader": "Devil Contract Rereader",
        "m_triple_reread": "Triple Devil Reread",
        "m_annual_reread": "Annual Devil Contract Reread",
        "m_publisher_fan": "Devil Publisher Fan",
        "m_artist_fan": "Fujimoto Art Appreciation",
        "m_adaptation_compare": "Devil Manga vs Anime Compare",
        "m_source_material_fan": "Devil Source Material Scout",
        "m_waiting_weekly": "Weekly Devil Chapter Wait",
        "m_classic_reader": "Classic Devil Manuscript",
        "m_saga_reader": "Saga of Chainsaw Reader",
        "m_genre_loyalty": "Devil Genre Loyalty",
        "m_decade_reader": "Decade-Long Devil Reader",
        "m_ln_adaptation": "Devil Light Novel Intel",
        "m_original_work": "Fujimoto's Original Work",
        "m_long_commitment": "Long-Term Devil Reading",
        "m_up_to_date": "Up-to-Date with Devils",
        "m_favorite_mangaka": "Fujimoto Honored",
        "m_complete_portfolio": "Complete Devil Portfolio",
        "m_franchise_collector": "Chainsaw Franchise Collector",
        "m_serialization_follower": "Devil Serialization Tracker",
        "m_genre_master": "Devil Genre Mastery",
        "m_multi_series_author": "Multi-Series Devil Author Fan",
        "m_format_diversity": "Diverse Devil Reading Formats",
        "m_year_dedication": "Year of Devil Reading",
        "m_ongoing_follower": "Ongoing Devil Series",
        "m_genre_loyalty_50": "Fifty Devil Genre Chapters",
        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Devil Genre Territory Scout",
        "m_publisher_hopper": "Devil Publisher Transfer",
        "m_tag_explorer": "Devil Tag Recon Mission",
        "m_decade_hopper": "Devil Decade Hopping",
        "m_hidden_gem": "Hidden Devil Gem",
        "m_popular_taste": "Popular Among Devil Hunters",
        "m_retro_reader": "Retro Devil Manuscript",
        "m_modern_reader": "Modern Devil Era Reader",
        "m_cross_demographic": "Cross-Demographic Hunter",
        "m_underdog_fan": "Underdog Devil Fan",
        "m_variety_week": "Week of Devil Readings",
        "m_manhwa_reader": "Devil Manhwa Reader",
        "m_manhua_reader": "Devil Manhua Reader",
        "m_classic_connoisseur": "Classic Devil Connoisseur",
        "m_award_winner": "Medal-Winning Devil Manuscript",
        "m_niche_explorer": "Niche Devil Territory",
        "m_world_manga": "World Devil Manga",
        "m_cult_classic": "Chainsaw Man Cult Classic",
        "m_random_pick": "Random Contract Assignment",
        "m_new_genre_month": "New Devil Genre Monthly",
        "m_year_completionist": "Year Devil Completionist",
        "m_unpopular_opinion": "Unpopular Devil Opinion",
        "m_top_rated_reader": "Top-Rated Devil Source",
        "m_source_variety": "Devil Source Variety",
        "m_low_score_brave": "Brave Devil Low-Score Reader",
        "m_short_manga_explorer": "Short Devil Skirmish",
        "m_long_manga_explorer": "Long Devil Campaign Manuscript",
        "m_serialization_explorer": "Devil Serialization Explorer",
        // ── MANGA TIME ──
        "m_night_owl": "Night Devil Reading",
        "m_early_bird": "Dawn Devil Reading",
        "m_lunch_reader": "Hunter Mess Reading",
        "m_commute_reader": "Devil Commute Reading",
        "m_four_am_club": "4 AM Devil Sentry Reader",
        "m_new_year_read": "New Year's Devil Reading Oath",
        "m_all_hours": "All-Hours Devil Archive",
        "m_prime_time_reader": "Prime Time Devil Manuscript",
        "m_workday_reader": "On-Duty Devil Reader",
        "m_sunday_read": "Sunday Devil Reading Marathon",
        "m_morning_routine": "Morning Division Reading",
        "m_night_shift_reader": "Night Shift Devil Reader",
        "m_seasonal_premier_read": "Devil New Release Intel",
        "m_clock_collector": "Division 4 Clock Collector",
        "m_late_night_horror": "Midnight Devil Horror Read",
        "m_afternoon_reader": "Afternoon Division Reading",
        "m_golden_hour_reader": "Golden Hour Devil Reading",
        "m_dawn_reader": "Dawn Devil Reading Scout",
        "m_twilight_reader": "Twilight Devil Reading",
        "m_midnight_start": "Midnight Devil Reading Mission",
        "m_weekend_binge_hours": "Weekend Devil Binge Reading",
        "m_late_night_regular": "Late Night Devil Reader",
        "m_sunrise_reader": "Sunrise Over Devil Ruins Reader",
        "m_every_day_of_week": "Every Day Devil Reading",
        "m_monthly_hours": "Monthly Devil Hours Logged",
        "m_bedtime_reader": "Bedtime Devil Reader",
        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Fujimoto Art Appreciator",
        "m_webtoon_reader": "Devil Webtoon Intelligence",
        "m_full_color": "Full Color Devil Manuscript",
        "m_doujin_reader": "Underground Devil Doujin",
        "m_anthology_reader": "Devil Anthology Reader",
        "m_adaptation_reader": "Devil Adaptation Study",
        "m_longstrip_reader": "Vertical Devil Scroll Reader",
        "m_4koma_reader": "4-Koma Devil Comedy",
        "m_oneshot_reader": "Oneshot Devil Mission Reader",
        "m_format_variety": "Devil Format Variety",
        "m_light_novel_reader": "Devil Light Novel Reader",
        "m_novel_reader": "Devil Novel Archive Reader",
        "m_visual_storyteller": "Devil Battle Narrator",
        "m_colored_classic": "Colored Devil Classic",
        "m_webcomic_fan": "Devil Webcomic Fan",
        "m_manga_to_anime": "Devil Manga to Anime",
        "m_seinen_reader": "Seinen Devil Reader",
        "m_josei_reader": "Josei Devil Perspective",
        "m_award_winning_art": "Medal-Winning Devil Artwork",
        "m_debut_work": "Devil Debut Manuscript",
        "m_vertical_scroll": "Vertical Devil Scroll Intel",
        "m_traditional_format": "Traditional Devil Format",
        "m_cross_media": "Devil Cross-Media Intel",
        "m_spinoff_reader": "Devil Spinoff Mission",
        "m_remake_reader": "Devil Remake Assignment",
        "m_collaboration_reader": "Devil Joint Operation Manuscript",
        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Devil Reading Streak",
        "m_mega_streak": "Mega Devil Reading Streak",
        "m_weekly_warrior": "Weekly Devil Warrior Reader",
        "m_monthly_reader": "Monthly Devil Reader",
        "m_comeback": "Return from Devil Exile",
        "m_weekend_streak": "Weekend Devil Reading Streak",
        "m_no_zero_days": "No Zero Devil Reading Days",
        "m_iron_will": "Iron Will Devil Reader",
        "m_habit_formed": "Devil Reading Regimen",
        "m_consistent_pace": "Consistent Devil Advance",
        "m_year_long": "Year-Long Devil Reading",
        "m_double_streak": "Double Devil Reading Streak",
        "m_streak_recovery": "Devil Reading Streak Recovery",
        "m_daily_minimum": "Daily Devil Minimum Pages",
        "m_winter_streak": "Winter Devil Reading Campaign",
        "m_summer_streak": "Summer Devil Offensive Reading",
        "m_morning_streak": "Morning Devil Formation Reading",
        "m_night_streak": "Night Devil Patrol Reading",
        "m_unbreakable": "Unbreakable Devil Reading Will",
        "m_eternal_flame": "Eternal Chainsaw Flame Knowledge",
        "m_chapter_a_day": "Chapter a Day Devil Discipline",
        "m_genre_streak": "Genre Devil Reading Streak",
        "m_completion_streak": "Completion Devil Reading Chain",
        "m_rating_streak": "Devil Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Devil Streak",
        "m_author_streak": "Fujimoto Dedication Streak",
        "m_perfect_week_manga": "Perfect Devil Reading Week",
        "m_diverse_streak": "Diverse Devil Reading Streak",
        // ── MANGA SCORING ──
        "m_critic": "Devil Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Devil Manuscript",
        "m_harsh_critic": "Makima's Reading Standards",
        "m_fair_judge": "Kishibe's Fair Review",
        "m_generous_spirit": "Generous Devil Reader Spirit",
        "m_score_all": "Full Devil Manuscript Assessment",
        "m_wide_range": "Wide Range Devil Scores",
        "m_controversial": "Controversial Devil Opinion",
        "m_consistent_scorer": "Consistent Devil Scorer",
        "m_score_sniper": "Precision Devil Score Sniper",
        "m_evolving_taste": "Evolving Devil Reading Taste",
        "m_bell_curve": "Bell Curve Devil Scores",
        "m_picky_reader": "Selective Devil Commander Reader",
        "m_100_rated": "Century of Devil Ratings",
        "m_500_rated": "Five Hundred Devil Rating Reports",
        "m_mediocre_majority": "Middle Ground Devil Reader",
        "m_rating_spree": "Devil Rating Barrage",
        "m_score_variance": "Variable Devil Manuscript Scores",
        "m_binge_rater": "Binge Devil Rating Session",
        "m_reread_rerate": "Reread and Re-Rate Devil Manga",
        "m_masterpiece_hunter": "Masterpiece Devil Manuscript Hunter",
        "m_contrarian": "Contrarian Devil Reader",
        "m_optimist": "Optimistic Devil Reader",
        "m_score_distributor": "Score Distributor Devil General",
        "m_genre_critic": "Genre Devil Reading Critic",
        "m_mean_above_8": "Elite Devil Reading Average",
        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Devil Reading Vow",
        "m_valentines_read": "Valentine's Devil Bond Read",
        "m_pi_day": "Pi Day Devil Chapter Count",
        "m_april_fools": "April Fools Devil Chibi",
        "m_international_manga_day": "International Devil Manga Day",
        "m_free_comic_day": "Free Devil Comic Day",
        "m_summer_solstice": "Summer Solstice Devil Reading",
        "m_tanabata": "Tanabata Devil Reading Wish",
        "m_friday_13th": "Friday 13th Devil Manuscript",
        "m_halloween_read": "Halloween Devil Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Devil Reading Feast",
        "m_christmas_read": "Midwinter Devil Festival Read",
        "m_new_years_eve": "New Year's Eve Devil Final Read",
        "m_birthday_read": "Birthday Devil Reading Gift",
        "m_holiday_marathon": "Holiday Devil Reading Marathon",
        "m_independence_day": "Hunter Independence Reading",
        "m_culture_day": "Devil Culture Day Manuscript",
        "m_spring_equinox": "Spring Devil Equinox Reading",
        "m_earth_day": "Earth Day Devil Conservation",
        "m_labor_day": "Devil Labor Reading Day",
        "m_winter_solstice": "Winter Devil Solstice Reading",
        "m_manga_birthday": "Chainsaw Man Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Devil Reader",
        "m_consecutive_holidays": "Consecutive Devil Holiday Reads",
        // ── MANGA SPECIAL ──
        "m_round_number": "Devil Round Number Milestone",
        "m_fibonacci": "Devil Fibonacci Chapter Pattern",
        "m_palindrome_day": "Palindrome Devil Reading Day",
        "m_binary_day": "Binary Devil Signal Day",
        "m_full_moon_read": "Full Moon Devil Read",
        "m_leap_year_read": "Leap Year Devil Reading",
        "m_triple_seven": "Triple Seven Devil Contracts",
        "m_thousand_complete": "Thousand Devil Victories",
        "m_nice": "Nice Devil Chapter Count",
        "m_power_level_chapters": "Chainsaw-Level Devil Chapters",
        "m_answer_42": "Answer to Devil Contracts",
        "m_square_number": "Perfect Devil Formation Chapters",
        "m_prime_count": "Prime Devil Chapter Count",
        "m_matching_date": "Matching Devil Reading Date",
        "m_century_chapter": "Century Devil Chapter Milestone",
        "m_pi_chapters": "Pi Devil Chapter Calculation",
        "m_synchronicity": "Chainsaw Reading Synchronicity",
        "m_world_record": "World Record Devil Chapter Count",
        "m_genre_clash": "Devil Genre Clash Reading",
        "m_time_traveler": "Time-Traveling Devil Reader",
        "m_double_digits": "Double Digit Devil Milestone",
        "m_one_two_three": "Denji Power Aki Chapters",
        "m_lucky_seven": "Seven Lucky Devil Chapters",
        "m_exact_hundred_ch": "Exact Hundred Devil Chapters",
        "m_year_match_count": "Year Match Devil Count",
        "m_chapter_match_date": "Chapter Devil Date Match",
        // ── MANGA FORMATS ──
        "m_manga_format": "Devil Manga Format Specialist",
        "m_manhwa_format": "Devil Manhwa Format Reader",
        "m_manhua_format": "Devil Manhua Format Reader",
        "m_ln_format": "Devil Light Novel Format",
        "m_oneshot_format": "Oneshot Devil Format",
        "m_doujin_format": "Devil Doujin Format Reader",
        "m_novel_format": "Devil Novel Format Reader",
        "m_format_master_manga": "Format Devil Master Reader",
        // ── MANGA META ──
        "m_meta_first_unlock": "First Devil Reading Power",
        "m_meta_collector": "Devil Reading Badge Collector",
        "m_meta_category_starter": "Devil Category Initiation",
        "m_meta_tier_climber": "Devil Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Devil Reading Rank",
        "m_meta_xp_earner": "XP from Devil Reading Intel",
        "m_meta_difficulty_easy": "Easy Devil Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Devil Manuscript",
        "m_meta_unlock_spree": "Devil Reading Unlock Barrage",
        "m_meta_completionist": "Meta Devil Completionist",
        "m_meta_diverse": "Diverse Devil Portfolio",
        "m_meta_dominator": "Meta Dominator Devil Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#070301",
        primary: "#e84020",
        secondary: "#c82810",
        accent: "#c8c0b8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/chainsaw-man.jpg",
    particleColor: "#e84020",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        chainsaw_sparks: { label: "Chainsaw Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        blood_splatter: { label: "Blood Splatter", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        devil_smoke: { label: "Devil Smoke", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        fire_burst: { label: "Fire Burst", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1: "Starving Devil Hunter",
        5: "Pochita's Partner",
        15: "Division 4 Recruit",
        30: "Public Safety Agent",
        45: "Chainsaw Devil Unleashed",
        60: "Gun Devil Hunter",
        80: "Makima's Pawn",
        100: "The Chainsaw That Devours Devils",
    },
}
