import { AnimeThemeConfig } from "./types"
import { GiPistolGun, GiSpy, GiBinoculars, GiHeartKey, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiSmokeBomb } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const cityHunterTheme: AnimeThemeConfig = {
    id: "city-hunter",
    displayName: "City Hunter",
    description: "Ryo Saeba is the City Hunter — Tokyo's best sweeper who'll handle any dangerous job, except his only weakness is beautiful women. Get Ryo Saeba on your side with a chalk message on the board at Shinjuku Station.",
    fontFamily: "'Oswald', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Oswald:wght@400;600&display=swap",
    cssVars: {
        "--color-brand-200": "255 195 130",
        "--color-brand-300": "248 162 70",
        "--color-brand-400": "235 128 18",
        "--color-brand-500": "212 96 0",
        "--color-brand-600": "175 76 0",
        "--color-brand-700": "136 58 0",
        "--color-brand-800": "96 40 0",
        "--color-brand-900": "58 22 0",
        "--color-brand-950": "33 12 0",
        "--brand": "212 96 0",
        "--background": "#060400",
        "--paper": "#110900",
        "--color-gray-950": "6 4 0",
        "--color-gray-900": "14 10 2",
        "--color-gray-800": "26 20 6",
        "--color-gray-700": "44 34 12",
        "--color-gray-600": "68 54 22",
        "--color-gray-500": "105 86 42",
        "--color-gray-400": "148 128 82",
        "--color-gray-300": "186 168 120",
        "--color-gray-200": "214 196 158",
        "--color-gray-100": "232 220 192",
        "--color-gray-50": "246 240 226",
    },
    sidebarOverrides: {
        "home": { icon: GiSpy, label: "Shinjuku Station" },
        "schedule": { icon: GiAlarmClock, label: "Job Schedule" },
        "manga": { icon: LuBookOpen, label: "Case Files" },
        "lists": { icon: GiPistolGun, label: "Client Roster" },
        "discover": { icon: GiBullseye, label: "Target Scouting" },
        "torrent-list": { icon: GiSmokeBomb, label: "Ammo Cache" },
        "debrid": { icon: GiBinoculars, label: "Surveillance" },
        "unmatched": { icon: GiHeartKey, label: "Mokkori Cases" },
        "enmasse": { icon: GiResize, label: "Mass Op" },
        "scan-summaries": { icon: TbReportSearch, label: "Client Reports" },
        "auto-downloader": { icon: LuRss, label: "XYZ Messages" },
        "community": { icon: GiSpy, label: "City Network" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "XYZ Alert" },
        "achievements": { icon: GiTrophy, label: "Sweeper Medals" },
        "milestones": { icon: LuFlag, label: "Sweeper Goals" },
        "theme-manager": { icon: GiPalette, label: "Urban Colors" },
        "extensions": { icon: BiExtension, label: "Gun Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "City Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ryo's Settings" },
    },
    achievementNames: {
        "a_first_episode": "XYZ Message",
        "a_first_complete": "Case Closed",
        "a_hundred_club": "Hundred Jobs",
        "a_time_lord": "City Veteran",
        "a_anime_collector": "Gun Cache",
        "a_library_legend": "Case Archives",
        "a_binge_king": "Non-Stop Cases",
        "a_no_sleep": "All-Night Stakeout",
        "a_marathon_runner": "City Marathon",
        "a_speed_run": "Quick Draw",
        "a_completionist": "City Cleaned",
        "a_mega_completionist": "Hojo Master",
        "a_loyal_fan": "Kaori's Partner",
        "a_rewatcher": "Case Revisited",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Sweeper Action",
        "a_genre_adventure": "City Adventure",
        "a_genre_comedy": "Mokkori Comedy",
        "a_genre_drama": "Kaori's Sacrifice",
        "a_genre_fantasy": "City Hunter World",
        "a_genre_horror": "Mob Terror",
        "a_genre_romance": "Kaori's Love",
        "a_genre_scifi": "Tech Gadgets",
        "a_genre_supernatural": "Marksman Skill",
        "a_genre_psychological": "Dark Past",
        "a_genre_mecha": "None Here",
        "a_critic": "City Judge",
        "a_perfect_ten": "Perfect Shot",
        "a_harsh_critic": "Strict Review",
        "a_daily_streak": "Daily Case",
        "a_mega_streak": "Endless Jobs",
        "a_year_long": "Year in Shinjuku",
        "a_iron_will": "Ryo's Will",
        "a_hidden_gem": "Hidden Case",
        "a_cult_classic": "Hojo Classic",
        "a_classic_connoisseur": "87 Classic Fan",
        "a_new_years_resolution": "New Year XYZ",
        "a_christmas_special": "Holiday Case",
        "a_meta_tier_max": "Top Sweeper",
        "a_meta_completionist": "Complete Files",
        "a_sequel_chain": "Angel Heart",
        "a_zero_to_hero": "Soldier to Sweeper",
        "a_night_owl": "Night Stakeout",
        "a_early_bird": "Dawn Patrol",
        "m_first_chapter": "First Case",
        "m_first_complete": "Arc Closed",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Case Marathon",
        "m_completionist": "Full Dossier",
        "m_mega_completionist": "City Master",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Case Revisit",
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "City Chapter",
        "m_genre_romance": "Love Chapter",
        "m_genre_fantasy": "Sweeper World",
        "m_genre_horror": "Dark Case",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "Tech Chapter",
        "m_genre_supernatural": "Skill Chapter",
        "m_genre_psychological": "Past Chapter",
        "m_critic": "City Critic",
        "m_perfect_ten": "Perfect Issue",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Cases",
        "m_year_long": "Year Reading",
        "m_iron_will": "Dedicated Fan",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Manga",
        "m_mangaka_lover": "Hojo Fan",
        "m_source_material_fan": "Original Reader",
        "m_meta_tier_max": "Complete Files",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Hojo Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060400",
        primary: "#d46000",
        secondary: "#883a00",
        accent: "#c8c8c8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/city-hunter.jpg",
    particleColor: "#f0a040",
    backgroundDim: 0.38,
    backgroundBlur: 22,
    particleTypes: {
        city_lights: { label: "City Lights", maxCount: 20, defaultEnabled: true, defaultIntensity: 60 },
        smoke: { label: "Gun Smoke", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1: "XYZ Message",
        5: "Ryo Saeba",
        15: "Kaori's Partner",
        30: "Shinjuku Sweeper",
        50: "City Legend",
        75: "Umibozu's Equal",
        100: "Tokyo's Finest",
    },
}
