import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiSwordWound,
    GiChainedHeart,
    GiMuscleUp,
    GiCrossedSwords,
    GiHorseHead,
    GiFist,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const clannadTheme: AnimeThemeConfig = {
    id: "clannad",
    displayName: "Clannad",
    description: "The place where wishes come true. A warm family-hearted interface woven with Dango spirit, Illusionary World light orbs, and the gentle cherry blossoms of Hikarizaka.",
    fontFamily: "'Nunito', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700&display=swap",
    cssVars: {
        // Brand → soft light blue with warm emotional tones
        "--color-brand-200": "200 215 255",
        "--color-brand-300": "180 200 255",
        "--color-brand-400": "155 178 242",
        "--color-brand-500": "130 155 225",
        "--color-brand-600": "105 130 200",
        "--color-brand-700": "80 105 170",
        "--color-brand-800": "55 78 135",
        "--color-brand-900": "35 52 100",
        "--color-brand-950": "18 28 62",
        "--brand": "180 200 255",
        // Deep blue-tinted dark background
        "--background": "#030408",
        "--paper": "#060810",
        "--color-gray-950": "3 4 8",
        "--color-gray-900": "6 8 16",
        "--color-gray-800": "12 16 28",
        "--color-gray-700": "22 28 46",
        "--color-gray-600": "40 48 70",
        "--color-gray-500": "65 75 100",
        "--color-gray-400": "105 115 142",
        "--color-gray-300": "148 158 180",
        "--color-gray-200": "192 198 215",
        "--color-gray-100": "224 228 238",
        "--color-gray-50": "242 244 250",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Furukawa Home" },
        "schedule": { icon: GiAlarmClock, label: "School Schedule" },
        "manga": { icon: LuBookOpen, label: "Nagisa's Scripts" },
        "lists": { icon: GiCrossedSwords, label: "Drama Club Roster" },
        "discover": { icon: GiBullseye, label: "Beyond the Slope" },
        "torrent-list": { icon: GiAnvilImpact, label: "Bread Deliveries" },
        "debrid": { icon: GiHorseHead, label: "Sunohara Express" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Starfish" },
        "enmasse": { icon: GiResize, label: "Dango Assembly" },
        "scan-summaries": { icon: TbReportSearch, label: "Memory Album" },
        "auto-downloader": { icon: LuRss, label: "Light Orb Signals" },
        "community": { icon: GiEagleEmblem, label: "Town Community" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "School Bell" },
        "achievements": { icon: GiTrophy, label: "Wishes Granted" },
        "theme-manager": { icon: GiPalette, label: "Season Colors" },
        "extensions": { icon: BiExtension, label: "Drama Props" },
        "sync": { icon: IoCloudOfflineOutline, label: "Family Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Bakery Office" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Encounter",
        "a_episode_counter": "Memory Count",
        "a_episode_titan": "Emotional Peak",
        "a_hours_invested": "Hours Together",
        "a_time_lord": "Timeless Moments",
        "a_anime_collector": "Dango Collection",
        "a_library_legend": "Kotomi's Library",
        "a_first_complete": "Story's End",
        "a_hundred_club": "Hundred Memories",
        "a_first_day": "Enrollment Day",
        "a_first_rating": "First Impression",
        "a_ten_thousand_min": "Endless Afternoons",
        "a_season_veteran": "Season Veteran",
        "a_year_explorer": "Year's Journey",
        "a_century_watcher": "Century Watcher",
        "a_five_hundred_eps": "Countless Steps",
        "a_thousand_eps": "Thousand Footsteps",
        "a_watching_ten": "Ten Promises",
        "a_ptw_hoarder": "Wish Hoarder",
        "a_dropped_honesty": "Honest Goodbye",
        "a_five_thousand_eps": "Endless Path",
        "a_ten_completed": "Ten Farewells",
        "a_fifty_completed": "Fifty Endings",
        "a_five_hundred_completed": "Countless Reunions",
        "a_mean_score_tracker": "Heart's Average",
        "a_unique_studios": "Unique Creators",
        "a_days_spent_watching": "Days Together",
        "a_all_status": "Every Feeling",
        "a_first_favorite": "Precious Bond",
        "a_favorites_collector": "Cherished Bonds",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Dango Marathon",
        "a_marathon_runner": "Hilltop Marathon",
        "a_weekend_warrior": "Weekend Warmth",
        "a_non_stop": "Unstoppable Tears",
        "a_one_more_episode": "One More Scene",
        "a_speed_run": "Rushing Home",
        "a_double_feature": "Double Feature",
        "a_triple_threat": "Triple Promise",
        "a_five_a_day": "Five Wishes",
        "a_back_to_back": "Side by Side",
        "a_seasonal_binge": "Seasonal Feelings",
        "a_cour_crusher": "Cour Crusher",
        "a_half_day_watch": "Half-Day Vigil",
        "a_full_day_watch": "Full-Day Devotion",
        "a_power_weekend": "Power Weekend",
        "a_binge_king": "Binge Dreamer",
        "a_no_sleep": "Sleepless Night",
        "a_entire_season": "Whole Season",
        "a_seven_day_challenge": "Seven-Day Wish",
        "a_hundred_day_binge": "Hundred-Day Bond",
        "a_genre_binge": "Genre Warmth",
        "a_studio_binge": "Studio Devotion",
        "a_season_sweep": "Season Sweep",
        "a_forty_eight_hour": "Forty-Eight Hours",
        "a_ep_counter_day": "Daily Moments",
        "a_multi_series_binge": "Multi-Story Watch",
        "a_midnight_binge": "Midnight Tears",
        "a_new_year_binge": "New Year Watch",

        // ── ANIME GENRES ──
        "a_genre_action": "Brave Heart",
        "a_genre_adventure": "Hilltop Path",
        "a_genre_comedy": "Sunohara's Antics",
        "a_genre_drama": "Family Drama",
        "a_genre_fantasy": "Illusionary World",
        "a_genre_horror": "Fading Light",
        "a_genre_mystery": "Hidden Truth",
        "a_genre_romance": "Nagisa's Love",
        "a_genre_scifi": "Orb Science",
        "a_genre_sol": "School Days",
        "a_genre_sports": "Baseball Game",
        "a_genre_supernatural": "Light Orbs",
        "a_genre_thriller": "Heart Racing",
        "a_genre_mecha": "Workshop Craft",
        "a_genre_music": "Dango Daikazoku",
        "a_genre_psychological": "Inner Conflict",
        "a_genre_ecchi": "Warm Feelings",
        "a_genre_mahou_shoujo": "Wish Granter",
        "a_tag_isekai": "Other World",
        "a_tag_harem": "Circle Friends",
        "a_tag_bl": "Brotherly Bond",
        "a_tag_gl": "Sisterly Bond",
        "a_tag_historical": "Town History",
        "a_tag_military": "Firm Resolve",
        "a_tag_school": "Hikarizaka High",
        "a_tag_martial_arts": "Tomoyo's Kicks",
        "a_tag_vampire": "Night Wanderer",
        "a_tag_samurai": "Wooden Sword",
        "a_tag_space": "Starfish Dream",
        "a_tag_parody": "Playful Moment",
        "a_tag_idol": "Stage Light",
        "a_tag_post_apocalyptic": "After Story",
        "a_tag_cyberpunk": "Neon Twilight",
        "a_tag_shounen": "Young Heart",
        "a_tag_seinen": "Grown Wisdom",
        "a_tag_shoujo": "Gentle Soul",
        "a_tag_josei": "Mature Love",
        "a_tag_survival": "Enduring Spirit",

        // ── ANIME COMPLETION ──
        "a_completionist": "Story Fulfilled",
        "a_mega_completionist": "Life Completed",
        "a_completion_rate_50": "Halfway There",
        "a_completion_rate_75": "Almost Home",
        "a_completion_rate_90": "Nearly Done",
        "a_no_drop": "Never Abandoned",
        "a_long_runner_complete": "Long Journey",
        "a_sequel_chain": "Sequel Chain",
        "a_clean_list": "Clean Record",
        "a_from_ptw": "Wish Fulfilled",
        "a_rewatch_master": "Memory Replay",
        "a_short_complete": "Quick Story",
        "a_same_day_start_finish": "Same-Day Finish",
        "a_revival": "Second Chance",
        "a_zero_to_hero": "Growth Arc",
        "a_five_genre_complete": "Five Genres",
        "a_full_franchise": "Full Franchise",
        "a_batch_complete": "Batch Complete",
        "a_paused_to_done": "Returned Home",
        "a_completion_spree": "Completion Spree",
        "a_multi_rewatch": "Multi-Rewatch",
        "a_dropped_recovery": "Recovered Bond",
        "a_ten_perfect_scores": "Ten Perfections",
        "a_seasonal_clear": "Season Clear",
        "a_complete_genre_span": "Genre Span",
        "a_monthly_completions": "Monthly Finale",
        "a_yearly_completions": "Yearly Finale",
        "a_rapid_complete": "Rapid Finish",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Heart",
        "a_studio_devotee": "Studio Devotee",
        "a_rewatcher": "Fond Rewatch",
        "a_triple_rewatch": "Triple Rewatch",
        "a_annual_tradition": "Annual Tradition",
        "a_director_fan": "Director's Vision",
        "a_voice_actor_fan": "Voice Admirer",
        "a_ost_lover": "Dango Song",
        "a_source_reader": "Source Reader",
        "a_waiting_weekly": "Weekly Wait",
        "a_childhood_revisit": "Childhood Revisit",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Genre Loyalty",
        "a_decade_watcher": "Decade Watcher",
        "a_adaptation_hunter": "Adaptation Seeker",
        "a_original_anime_fan": "Original Fan",
        "a_long_commitment": "Long Commitment",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Studios",
        "a_complete_catalog": "Full Catalog",
        "a_franchise_collector": "Franchise Heart",
        "a_airing_follower": "Airing Follower",
        "a_genre_master": "Genre Master",
        "a_staff_follower": "Staff Follower",
        "a_multi_season_fan": "Multi-Season Fan",
        "a_format_diversity": "Format Diversity",
        "a_year_dedication": "Year Dedicated",
        "a_season_dedication": "Season Dedicated",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "New Horizons",
        "a_studio_hopper": "Studio Hopper",
        "a_tag_explorer": "Tag Explorer",
        "a_decade_hopper": "Decade Hopper",
        "a_hidden_gem": "Hidden Gem",
        "a_popular_taste": "Popular Choice",
        "a_retro_appreciator": "Retro Warmth",
        "a_modern_viewer": "Modern Viewer",
        "a_cross_demographic": "Cross Paths",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Week",
        "a_foreign_cinema": "Foreign Cinema",
        "a_classic_connoisseur": "Classic Taste",
        "a_every_season": "Every Season",
        "a_award_winner": "Award Winner",
        "a_niche_explorer": "Niche Explorer",
        "a_global_anime": "Global Anime",
        "a_cult_classic": "Cult Classic",
        "a_random_pick": "Random Pick",
        "a_new_genre_month": "New Genre",
        "a_seasonal_completionist": "Seasonal Complete",
        "a_unpopular_opinion": "Unpopular View",
        "a_top_rated_viewer": "Top Rated",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Choice",
        "a_upcoming_watcher": "Upcoming Watch",
        "a_short_series_explorer": "Short Explorer",
        "a_long_series_explorer": "Long Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Owl",
        "a_early_bird": "Early Bird",
        "a_lunch_break": "Lunch Break",
        "a_golden_hour": "Golden Hour",
        "a_four_am_club": "Four AM Club",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Watch",
        "a_midnight_premiere": "Midnight Premiere",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Light",
        "a_afternoon_delight": "Afternoon Calm",
        "a_prime_time": "Prime Time",
        "a_workday_watcher": "Weekday Watcher",
        "a_sunday_marathon": "Sunday Marathon",
        "a_rainy_day": "Rainy Day",
        "a_morning_routine": "Morning Routine",
        "a_night_shift": "Night Shift",
        "a_twilight_zone": "Twilight Slope",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Collector",
        "a_weekend_binge_hours": "Weekend Hours",
        "a_late_night_regular": "Late Night",
        "a_sunrise_watcher": "Sunrise Watcher",
        "a_holiday_watcher": "Holiday Watch",
        "a_every_day_of_week": "Every Day",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Gathering",
        "a_party_host": "Drama Club Host",
        "a_social_butterfly": "Social Butterfly",
        "a_group_binge": "Group Watch",
        "a_party_regular": "Regular Member",
        "a_sync_viewer": "Synced Viewing",
        "a_commentator": "Commentator",
        "a_party_marathon": "Party Marathon",
        "a_full_house": "Full House",
        "a_community_pillar": "Town Pillar",
        "a_watch_party_streak": "Party Streak",
        "a_diverse_party": "Diverse Gathering",
        "a_late_night_party": "Late Night Party",
        "a_party_veteran": "Party Veteran",
        "a_genre_party": "Genre Gathering",
        "a_weekly_party": "Weekly Gathering",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Kind Suggestion",
        "a_party_completionist": "Party Completionist",
        "a_social_scorer": "Social Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Fibonacci Wish",
        "a_palindrome_day": "Palindrome Day",
        "a_binary_day": "Binary Day",
        "a_full_moon": "Full Moon",
        "a_leap_year": "Leap Year",
        "a_time_traveler": "Time Traveler",
        "a_genre_clash": "Genre Clash",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Complete",
        "a_pi_episodes": "Pi Episodes",
        "a_synchronicity": "Synchronicity",
        "a_world_record": "World Record",
        "a_nice": "Nice",
        "a_power_level": "Power Level",
        "a_answer_42": "Answer Forty-Two",
        "a_square_number": "Square Number",
        "a_prime_count": "Prime Count",
        "a_matching_date": "Matching Date",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Watcher",
        "a_movie_buff": "Movie Lover",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Watcher",
        "a_short_king": "Short King",
        "a_variety_pack": "Variety Pack",
        "a_film_festival": "Film Festival",
        "a_music_video": "Music Video",
        "a_tv_short": "TV Short",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Anthology",
        "a_mini_series": "Mini Series",
        "a_theatrical": "Theatrical",
        "a_format_master": "Format Master",
        "a_long_movie": "Long Movie",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "CM Watcher",
        "a_pv_collector": "PV Collector",
        "a_format_balance": "Format Balance",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Movie",
        "a_recap_watcher": "Recap Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Walk",
        "a_mega_streak": "Mega Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Watcher",
        "a_comeback": "Welcome Back",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Steady Pace",
        "a_year_long": "Year Long",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable Bond",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Episode Run",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Fair Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Harsh Critic",
        "a_fair_judge": "Fair Judge",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Score All",
        "a_wide_range": "Wide Range",
        "a_controversial": "Controversial",
        "a_consistent_scorer": "Steady Scorer",
        "a_score_sniper": "Score Sniper",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Picky Watcher",
        "a_100_rated": "Hundred Rated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Seeker",
        "a_contrarian": "Contrarian",
        "a_optimist": "Optimist",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Wish",
        "a_valentines_weeb": "Valentine's Heart",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Fools",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "May Fourth",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday Thirteenth",
        "a_halloween_spirit": "Halloween Spirit",
        "a_thanksgiving_binge": "Thanksgiving Feast",
        "a_christmas_special": "Christmas Miracle",
        "a_new_years_eve": "New Year's Eve",
        "a_birthday_watch": "Birthday Watch",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Independence Day",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Equinox",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Day",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anime Birthday",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Holiday Streak",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Light Orb",
        "a_meta_collector": "Orb Collector",
        "a_meta_category_starter": "Category Start",
        "a_meta_tier_climber": "Tier Climber",
        "a_meta_tier_max": "Maximum Tier",
        "a_meta_xp_earner": "XP Earned",
        "a_meta_difficulty_easy": "Easy Miracle",
        "a_meta_difficulty_hard": "Hard Miracle",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Complete",
        "a_meta_diverse": "Diverse Path",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter",
        "m_chapter_counter": "Chapter Count",
        "m_chapter_titan": "Chapter Peak",
        "m_reading_hours": "Reading Hours",
        "m_reading_time_lord": "Timeless Reading",
        "m_manga_collector": "Manga Collection",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Completed",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "First Reading Day",
        "m_first_rating": "First Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Collector",
        "m_year_explorer": "Year Explorer",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Read",
        "m_thousand_ch": "Thousand Chapters",
        "m_reading_ten": "Ten at Once",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Drop",
        "m_season_reader": "Seasonal Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Completed",
        "m_fifty_completed": "Fifty Completed",
        "m_five_hundred_completed": "Countless Reads",
        "m_mean_score_tracker": "Average Score",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "Every Status",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Favorites Keeper",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reader",
        "m_marathon_reader": "Marathon Reader",
        "m_weekend_reader": "Weekend Reader",
        "m_non_stop_reading": "Non-Stop Reading",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Read",
        "m_double_story": "Double Story",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five a Day",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Read",
        "m_full_day_read": "Full-Day Read",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge King",
        "m_no_sleep_read": "Sleepless Read",
        "m_full_series_rush": "Series Rush",
        "m_seven_day_challenge": "Seven-Day Read",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Binge",
        "m_author_binge": "Author Binge",
        "m_chapter_counter_day": "Daily Chapters",
        "m_multi_series_binge": "Multi-Series Read",
        "m_midnight_binge": "Midnight Read",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "Forty-Eight Hours",
        "m_oneshot_binge": "Oneshot Binge",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Reader",
        "m_genre_adventure": "Adventure Reader",
        "m_genre_comedy": "Comedy Reader",
        "m_genre_drama": "Drama Reader",
        "m_genre_fantasy": "Fantasy Reader",
        "m_genre_horror": "Horror Reader",
        "m_genre_mystery": "Mystery Reader",
        "m_genre_romance": "Romance Reader",
        "m_genre_scifi": "Sci-Fi Reader",
        "m_genre_sol": "Slice of Life",
        "m_genre_sports": "Sports Reader",
        "m_genre_supernatural": "Supernatural Reader",
        "m_genre_thriller": "Thriller Reader",
        "m_genre_psychological": "Psychological Reader",
        "m_genre_isekai": "Isekai Reader",
        "m_genre_shounen": "Shounen Reader",
        "m_genre_ecchi": "Ecchi Reader",
        "m_genre_mahou_shoujo": "Mahou Shoujo",
        "m_genre_mecha": "Mecha Reader",
        "m_genre_music": "Music Reader",
        "m_tag_isekai_new": "New World Reader",
        "m_tag_harem": "Harem Reader",
        "m_tag_bl": "BL Reader",
        "m_tag_gl": "GL Reader",
        "m_tag_historical": "Historical Reader",
        "m_tag_military": "Military Reader",
        "m_tag_school": "School Reader",
        "m_tag_martial_arts": "Martial Arts",
        "m_tag_vampire": "Vampire Reader",
        "m_tag_samurai": "Samurai Reader",
        "m_tag_space": "Space Reader",
        "m_tag_parody": "Parody Reader",
        "m_tag_idol": "Idol Reader",
        "m_tag_post_apocalyptic": "Post-Apocalyptic",
        "m_tag_cyberpunk": "Cyberpunk Reader",
        "m_tag_shoujo": "Shoujo Reader",
        "m_tag_survival": "Survival Reader",
        "m_tag_cooking": "Cooking Reader",
        "m_tag_medical": "Medical Reader",
        "m_tag_villainess": "Villainess Reader",

        // ── MANGA COMPLETION ──
        "m_completionist": "Completionist",
        "m_mega_completionist": "Mega Completionist",
        "m_completion_rate_50": "Halfway Read",
        "m_completion_rate_75": "Almost Finished",
        "m_completion_rate_90": "Nearly Complete",
        "m_no_drop": "Never Dropped",
        "m_long_runner_complete": "Long Runner Done",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean List",
        "m_from_ptr": "Plan Fulfilled",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Read",
        "m_revival": "Reading Revival",
        "m_zero_to_hundred": "Zero to Hundred",
        "m_five_genre_complete": "Five Genres Done",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Complete",
        "m_paused_to_done": "Resumed Finish",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi-Reread",
        "m_dropped_recovery": "Dropped Recovery",
        "m_ten_perfect_scores": "Ten Perfects",
        "m_complete_genre_span": "Genre Span",
        "m_monthly_completions": "Monthly Done",
        "m_yearly_completions": "Yearly Done",
        "m_rapid_complete": "Rapid Finish",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Lover",
        "m_rereader": "Fond Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Fan",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Fan",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyalty",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Favorite Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Franchise Keeper",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Master",
        "m_multi_series_author": "Multi-Author Fan",
        "m_format_diversity": "Format Diversity",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Explorer",
        "m_decade_hopper": "Decade Hopper",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Taste",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross Demo",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Varied Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Taste",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Niche Explorer",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre",
        "m_year_completionist": "Year Completionist",
        "m_unpopular_opinion": "Unpopular View",
        "m_top_rated_reader": "Top Rated",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Explorer",
        "m_long_manga_explorer": "Long Explorer",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Early Reader",
        "m_lunch_reader": "Lunch Reader",
        "m_commute_reader": "Commute Reader",
        "m_four_am_club": "Four AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All Hours",
        "m_prime_time_reader": "Prime Time",
        "m_workday_reader": "Workday Reader",
        "m_sunday_read": "Sunday Read",
        "m_morning_routine": "Morning Read",
        "m_night_shift_reader": "Night Shift",
        "m_seasonal_premier_read": "New Release",
        "m_clock_collector": "Clock Collector",
        "m_late_night_horror": "Late Night Horror",
        "m_afternoon_reader": "Afternoon Reader",
        "m_golden_hour_reader": "Golden Hour",
        "m_dawn_reader": "Dawn Reader",
        "m_twilight_reader": "Twilight Reader",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Hours",
        "m_late_night_regular": "Late Regular",
        "m_sunrise_reader": "Sunrise Reader",
        "m_every_day_of_week": "Every Day",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Reader",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Storyteller",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga to Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross Media",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collab Reader",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Streak",
        "m_mega_streak": "Mega Streak",
        "m_weekly_warrior": "Weekly Warrior",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Welcome Back",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Will",
        "m_habit_formed": "Habit Formed",
        "m_consistent_pace": "Steady Pace",
        "m_year_long": "Year Long",
        "m_double_streak": "Double Streak",
        "m_streak_recovery": "Streak Recovery",
        "m_daily_minimum": "Daily Minimum",
        "m_winter_streak": "Winter Streak",
        "m_summer_streak": "Summer Streak",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Streak",
        "m_unbreakable": "Unbreakable",
        "m_eternal_flame": "Eternal Flame",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Completion Chain",
        "m_rating_streak": "Rating Streak",
        "m_multi_ch_streak": "Multi-Chapter Run",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manga Critic",
        "m_perfect_ten": "Perfect Ten",
        "m_harsh_critic": "Harsh Critic",
        "m_fair_judge": "Fair Judge",
        "m_generous_spirit": "Generous Spirit",
        "m_score_all": "Score All",
        "m_wide_range": "Wide Range",
        "m_controversial": "Controversial",
        "m_consistent_scorer": "Steady Scorer",
        "m_score_sniper": "Score Sniper",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Picky Reader",
        "m_100_rated": "Hundred Rated",
        "m_500_rated": "Five Hundred Rated",
        "m_mediocre_majority": "Middle Ground",
        "m_rating_spree": "Rating Spree",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Seeker",
        "m_contrarian": "Contrarian",
        "m_optimist": "Optimist",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Resolve",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day",
        "m_april_fools": "April Fools",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Solstice",
        "m_tanabata": "Tanabata",
        "m_friday_13th": "Friday Thirteenth",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thanksgiving Read",
        "m_christmas_read": "Christmas Read",
        "m_new_years_eve": "New Year's Eve",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Marathon",
        "m_independence_day": "Independence Day",
        "m_culture_day": "Culture Day",
        "m_spring_equinox": "Spring Equinox",
        "m_earth_day": "Earth Day",
        "m_labor_day": "Labor Day",
        "m_winter_solstice": "Winter Solstice",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "Every Holiday",
        "m_consecutive_holidays": "Holiday Streak",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number",
        "m_fibonacci": "Fibonacci",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven",
        "m_thousand_complete": "Thousand Complete",
        "m_nice": "Nice",
        "m_power_level_chapters": "Power Level",
        "m_answer_42": "Answer Forty-Two",
        "m_square_number": "Square Number",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Matching Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Synchronicity",
        "m_world_record": "World Record",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time Traveler",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Match",
        "m_chapter_match_date": "Chapter Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Orb Found",
        "m_meta_collector": "Orb Gatherer",
        "m_meta_category_starter": "Category Start",
        "m_meta_tier_climber": "Tier Climber",
        "m_meta_tier_max": "Maximum Tier",
        "m_meta_xp_earner": "XP Earned",
        "m_meta_difficulty_easy": "Easy Path",
        "m_meta_difficulty_hard": "Hard Path",
        "m_meta_unlock_spree": "Unlock Spree",
        "m_meta_completionist": "Meta Complete",
        "m_meta_diverse": "Diverse Reader",
        "m_meta_dominator": "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030408",
        primary: "#829be1",
        secondary: "#6982c8",
        accent: "#b4c8ff",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/clannad.jpg",
    particleColor: "#4890c8",
    backgroundDim: 0.2,
    backgroundBlur: 20,
    particleTypes: {
        dango_float: { label: "Dango Float", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        light_orbs: { label: "Light Orbs", maxCount: 12, defaultEnabled: true, defaultIntensity: 60 },
        cherry_blossoms: { label: "Cherry Blossoms", maxCount: 14, defaultEnabled: true, defaultIntensity: 55 },
        starfish_glow: { label: "Starfish Glow", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1:   "Delinquent",
        5:   "Drama Club",
        15:  "After Story",
        30:  "Family Man",
        45:  "Father",
        60:  "Wish Maker",
        80:  "Illusionary",
        100: "Big Dango Family",
    },
}
