import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiSwordWound,
    GiChainedHeart,
    GiMuscleUp,
    GiCrossedSwords,
    GiHorseHead,
    GiFist,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const claymoreTheme: AnimeThemeConfig = {
    id: "claymore",
    displayName: "Claymore",
    description: "Silver-eyed warriors forged to hunt Yoma. An interface tempered like a Claymore blade — cold steel, relentless precision, and awakened power.",
    fontFamily: "'Oswald', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap",
    cssVars: {
        // Brand → cold silver with steel-blue undertones
        "--color-brand-200": "210 218 225",
        "--color-brand-300": "195 205 215",
        "--color-brand-400": "180 190 200",
        "--color-brand-500": "155 165 178",
        "--color-brand-600": "130 140 155",
        "--color-brand-700": "100 110 125",
        "--color-brand-800": "70 78 90",
        "--color-brand-900": "45 50 60",
        "--color-brand-950": "25 28 35",
        "--brand": "180 190 200",
        // Near-black cold background
        "--background": "#040506",
        "--paper": "#080a0c",
        "--color-gray-950": "4 5 6",
        "--color-gray-900": "8 10 12",
        "--color-gray-800": "18 22 28",
        "--color-gray-700": "32 38 48",
        "--color-gray-600": "52 60 72",
        "--color-gray-500": "78 88 102",
        "--color-gray-400": "118 128 142",
        "--color-gray-300": "158 166 178",
        "--color-gray-200": "195 202 210",
        "--color-gray-100": "225 230 235",
        "--color-gray-50": "242 245 248",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Organization HQ" },
        "schedule": { icon: GiAlarmClock, label: "Hunt Schedule" },
        "manga": { icon: LuBookOpen, label: "Silver Archives" },
        "lists": { icon: GiCrossedSwords, label: "Warrior Roster" },
        "discover": { icon: GiBullseye, label: "Yoma Territories" },
        "torrent-list": { icon: GiAnvilImpact, label: "Blade Forges" },
        "debrid": { icon: GiHorseHead, label: "Black Card Ops" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Warriors" },
        "enmasse": { icon: GiResize, label: "Mass Awakening" },
        "scan-summaries": { icon: TbReportSearch, label: "Yoki Readings" },
        "auto-downloader": { icon: LuRss, label: "Hunt Orders" },
        "community": { icon: GiEagleEmblem, label: "The Organization" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Yoma Alerts" },
        "achievements": { icon: GiTrophy, label: "Silver Marks" },
        "theme-manager": { icon: GiPalette, label: "Warrior Colors" },
        "extensions": { icon: BiExtension, label: "Yoki Extensions" },
        "sync": { icon: IoCloudOfflineOutline, label: "Ghosts' Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Handler Orders" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Yoma",
        "a_episode_counter": "Kill Tally",
        "a_episode_titan": "Awakened Clash",
        "a_hours_invested": "Yoki Endurance",
        "a_time_lord": "Teresa's Memory",
        "a_anime_collector": "Silver Arsenal",
        "a_library_legend": "Archive Legend",
        "a_first_complete": "Hunt Complete",
        "a_hundred_club": "Century Slayer",
        "a_first_day": "Trainee Arrival",
        "a_first_rating": "Warrior Rank",
        "a_ten_thousand_min": "Endless Patrol",
        "a_season_veteran": "Veteran Blade",
        "a_year_explorer": "Year Wandering",
        "a_century_watcher": "Hundred Vigils",
        "a_five_hundred_eps": "Five Hundred Cuts",
        "a_thousand_eps": "Thousand Strikes",
        "a_watching_ten": "Ten Fronts",
        "a_ptw_hoarder": "Orders Hoarded",
        "a_dropped_honesty": "Black Card",
        "a_five_thousand_eps": "Relentless Silver",
        "a_ten_completed": "Ten Hunts",
        "a_fifty_completed": "Fifty Slain",
        "a_five_hundred_completed": "Silver Conquest",
        "a_mean_score_tracker": "Average Yoki",
        "a_unique_studios": "Allied Factions",
        "a_days_spent_watching": "Days Hunting",
        "a_all_status": "All Deployments",
        "a_first_favorite": "First Bond",
        "a_favorites_collector": "Comrade Bonds",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Yoki Surge",
        "a_marathon_runner": "Relentless March",
        "a_weekend_warrior": "Weekend Blade",
        "a_non_stop": "Unstoppable Force",
        "a_one_more_episode": "One More Hunt",
        "a_speed_run": "Quick Draw",
        "a_double_feature": "Twin Swords",
        "a_triple_threat": "Triple Slash",
        "a_five_a_day": "Five Yoma Day",
        "a_back_to_back": "Successive Hunts",
        "a_seasonal_binge": "Full Campaign",
        "a_cour_crusher": "District Purge",
        "a_half_day_watch": "Half-Day Vigil",
        "a_full_day_watch": "Full Day Hunt",
        "a_power_weekend": "Power Awakening",
        "a_binge_king": "Binge Warrior",
        "a_no_sleep": "Sleepless Blade",
        "a_entire_season": "Season Purged",
        "a_seven_day_challenge": "Seven-Day Hunt",
        "a_hundred_day_binge": "Hundred-Day Siege",
        "a_genre_binge": "Cross-Type Hunt",
        "a_studio_binge": "Faction Binge",
        "a_season_sweep": "Season Sweep",
        "a_forty_eight_hour": "Forty-Eight Stand",
        "a_ep_counter_day": "Daily Kill Count",
        "a_multi_series_binge": "Multi-Front War",
        "a_midnight_binge": "Midnight Hunt",
        "a_new_year_binge": "New Year Slash",

        // ── ANIME GENRES ──
        "a_genre_action": "Blade Master",
        "a_genre_adventure": "Wandering Warrior",
        "a_genre_comedy": "Raki's Laughter",
        "a_genre_drama": "Clare's Oath",
        "a_genre_fantasy": "Yoki Realm",
        "a_genre_horror": "Voracious Eater",
        "a_genre_mystery": "Hidden Yoma",
        "a_genre_romance": "Silver Heart",
        "a_genre_scifi": "Forged Science",
        "a_genre_sol": "Peaceful Village",
        "a_genre_sports": "Training Grounds",
        "a_genre_supernatural": "Yoki Awakening",
        "a_genre_thriller": "Priscilla's Hunt",
        "a_genre_mecha": "Steel Construct",
        "a_genre_music": "Silver Requiem",
        "a_genre_psychological": "Inner Yoma",
        "a_genre_ecchi": "Warrior's Rest",
        "a_genre_mahou_shoujo": "Silver Witch",
        "a_tag_isekai": "Unknown Lands",
        "a_tag_harem": "Warrior Sisters",
        "a_tag_bl": "Brothers Sworn",
        "a_tag_gl": "Shield Maidens",
        "a_tag_historical": "Ancient Yoma",
        "a_tag_military": "Organization Rule",
        "a_tag_school": "Trainee Barracks",
        "a_tag_martial_arts": "Blade Technique",
        "a_tag_vampire": "Yoma Bloodline",
        "a_tag_samurai": "Claymore Style",
        "a_tag_space": "Beyond Horizon",
        "a_tag_parody": "Silver Parody",
        "a_tag_idol": "Warrior Idol",
        "a_tag_post_apocalyptic": "Ruined Lands",
        "a_tag_cyberpunk": "Steel Augment",
        "a_tag_shounen": "Young Warrior",
        "a_tag_seinen": "Harsh Reality",
        "a_tag_shoujo": "Clare's Devotion",
        "a_tag_josei": "Miria's Resolve",
        "a_tag_survival": "Survival Instinct",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Purge",
        "a_mega_completionist": "Abyssal Slayer",
        "a_completion_rate_50": "Halfway Awakened",
        "a_completion_rate_75": "Silver Threshold",
        "a_completion_rate_90": "Near Ascension",
        "a_no_drop": "No Retreat",
        "a_long_runner_complete": "Enduring Steel",
        "a_sequel_chain": "Chain of Hunts",
        "a_clean_list": "Clean Ledger",
        "a_from_ptw": "Orders Executed",
        "a_rewatch_master": "Memory Replay",
        "a_short_complete": "Quick Skirmish",
        "a_same_day_start_finish": "Same-Day Kill",
        "a_revival": "Flesh Reforged",
        "a_zero_to_hero": "Trainee Ascends",
        "a_five_genre_complete": "Five-Type Mastery",
        "a_full_franchise": "Full Dossier",
        "a_batch_complete": "Batch Purge",
        "a_paused_to_done": "Wound Healed",
        "a_completion_spree": "Completion Storm",
        "a_multi_rewatch": "Multi Replay",
        "a_dropped_recovery": "Blade Recovered",
        "a_ten_perfect_scores": "Ten Perfects",
        "a_seasonal_clear": "Seasonal Purge",
        "a_complete_genre_span": "All-Terrain Blade",
        "a_monthly_completions": "Monthly Reports",
        "a_yearly_completions": "Yearly Victor",
        "a_rapid_complete": "Swift Execution",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Warrior",
        "a_studio_devotee": "Studio Devotee",
        "a_rewatcher": "Silver Rewatch",
        "a_triple_rewatch": "Triple Return",
        "a_annual_tradition": "Annual Oath",
        "a_director_fan": "Director's Eye",
        "a_voice_actor_fan": "Warrior's Voice",
        "a_ost_lover": "Silver Melody",
        "a_source_reader": "Original Texts",
        "a_waiting_weekly": "Weekly Vigil",
        "a_childhood_revisit": "Return Home",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Type Loyalty",
        "a_decade_watcher": "Decade Warrior",
        "a_adaptation_hunter": "Adaptation Hunt",
        "a_original_anime_fan": "Original Veteran",
        "a_long_commitment": "Long Commitment",
        "a_perfect_attendance": "Perfect Muster",
        "a_favorite_studio_5": "Five Allies",
        "a_complete_catalog": "Full Catalog",
        "a_franchise_collector": "World Collector",
        "a_airing_follower": "Airing Intel",
        "a_genre_master": "Genre Mastered",
        "a_staff_follower": "Staff Dossier",
        "a_multi_season_fan": "Season Veteran",
        "a_format_diversity": "Diverse Formats",
        "a_year_dedication": "Year Dedicated",
        "a_season_dedication": "Season Sworn",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Unknown Territory",
        "a_studio_hopper": "Faction Transfer",
        "a_tag_explorer": "Tag Recon",
        "a_decade_hopper": "Era Hopper",
        "a_hidden_gem": "Hidden Village",
        "a_popular_taste": "Popular Among",
        "a_retro_appreciator": "Retro Silver",
        "a_modern_viewer": "Modern Blade",
        "a_cross_demographic": "Cross Ranks",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Hunts",
        "a_foreign_cinema": "Foreign Intel",
        "a_classic_connoisseur": "Classic Blade",
        "a_every_season": "Every Season",
        "a_award_winner": "Valor Medal",
        "a_niche_explorer": "Niche Territory",
        "a_global_anime": "Global Alliance",
        "a_cult_classic": "Cult Warrior",
        "a_random_pick": "Random Orders",
        "a_new_genre_month": "New Terrain",
        "a_seasonal_completionist": "Season Cleared",
        "a_unpopular_opinion": "Lone Opinion",
        "a_top_rated_viewer": "Top Ranked",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Charge",
        "a_upcoming_watcher": "Upcoming Intel",
        "a_short_series_explorer": "Short Sortie",
        "a_long_series_explorer": "Long Campaign",

        // ── ANIME TIME ──
        "a_night_owl": "Night Sentinel",
        "a_early_bird": "Dawn Patrol",
        "a_lunch_break": "Midday Rest",
        "a_golden_hour": "Golden Yoki",
        "a_four_am_club": "4 AM Watcher",
        "a_witching_hour": "Yoma Hour",
        "a_new_year_watch": "New Year Oath",
        "a_midnight_premiere": "Midnight Hunt",
        "a_all_hours": "All-Hours Scout",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Drill",
        "a_prime_time": "Prime Strike",
        "a_workday_watcher": "On-Duty Blade",
        "a_sunday_marathon": "Sunday March",
        "a_rainy_day": "Rain-Soaked Hunt",
        "a_morning_routine": "Morning Muster",
        "a_night_shift": "Night Patrol",
        "a_twilight_zone": "Twilight Blade",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Collector",
        "a_weekend_binge_hours": "Weekend Surge",
        "a_late_night_regular": "Late Sentinel",
        "a_sunrise_watcher": "Sunrise Watcher",
        "a_holiday_watcher": "Holiday Vigil",
        "a_every_day_of_week": "Every Day",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Formation",
        "a_party_host": "Hunt Commander",
        "a_social_butterfly": "Silver Social",
        "a_group_binge": "Group Assault",
        "a_party_regular": "Sparring Partner",
        "a_sync_viewer": "Synced Blades",
        "a_commentator": "Battle Narrator",
        "a_party_marathon": "Formation March",
        "a_full_house": "Full Squad",
        "a_community_pillar": "Pillar Warrior",
        "a_watch_party_streak": "Formation Streak",
        "a_diverse_party": "Diverse Squad",
        "a_late_night_party": "Late Night Camp",
        "a_party_veteran": "Veteran Leader",
        "a_genre_party": "Cross-Type Squad",
        "a_weekly_party": "Weekly Gathering",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Handler's Tip",
        "a_party_completionist": "Party Complete",
        "a_social_scorer": "Social Ranker",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Formation",
        "a_fibonacci": "Fibonacci Yoki",
        "a_palindrome_day": "Palindrome Rift",
        "a_binary_day": "Binary Signal",
        "a_full_moon": "Full Moon Yoma",
        "a_leap_year": "Leap Year Skip",
        "a_time_traveler": "Teresa's Vision",
        "a_genre_clash": "Type Clash",
        "a_triple_seven": "Triple Silver",
        "a_thousand_complete": "Thousand Purged",
        "a_pi_episodes": "Pi Calculation",
        "a_synchronicity": "Yoki Sync",
        "a_world_record": "World Record",
        "a_nice": "Nice Count",
        "a_power_level": "Yoki Level",
        "a_answer_42": "Answer Sought",
        "a_square_number": "Square Formation",
        "a_prime_count": "Prime Slain",
        "a_matching_date": "Matching Date",
        "a_century_episode": "Century Assault",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Seven Warriors",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Broadcast Blade",
        "a_movie_buff": "Silver Screen",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Scout",
        "a_special_watcher": "Special Ops",
        "a_short_king": "Short Blade",
        "a_variety_pack": "All Formats",
        "a_film_festival": "Film Campaign",
        "a_music_video": "Silver Anthem",
        "a_tv_short": "Quick Recon",
        "a_movie_marathon": "Movie Blitz",
        "a_double_length": "Double Length",
        "a_anthology": "Warrior Tales",
        "a_mini_series": "Mini Campaign",
        "a_theatrical": "Theater Strike",
        "a_format_master": "Format Master",
        "a_long_movie": "Long Feature",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "Brief Watcher",
        "a_pv_collector": "Preview Scout",
        "a_format_balance": "Balanced Arms",
        "a_episodic_master": "Episode Master",
        "a_sequel_movie": "Sequel Strike",
        "a_recap_watcher": "Recap Briefing",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Patrol",
        "a_mega_streak": "Mega Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Vigil",
        "a_comeback": "Warrior Returns",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Regimen Formed",
        "a_consistent_pace": "Steady March",
        "a_year_long": "Year-Long Hunt",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Healed",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable Will",
        "a_eternal_flame": "Eternal Silver",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Strike Run",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Steel Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Teresa's Standard",
        "a_fair_judge": "Fair Handler",
        "a_generous_spirit": "Generous Soul",
        "a_score_all": "Full Assessment",
        "a_wide_range": "Wide Range",
        "a_controversial": "Divisive Rank",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Precision Blade",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Selective Eye",
        "a_100_rated": "Century Rated",
        "a_500_rated": "Five Hundred",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Storm",
        "a_score_variance": "Variable Yoki",
        "a_masterpiece_hunter": "Masterpiece Hunt",
        "a_contrarian": "Lone Dissenter",
        "a_optimist": "Silver Optimist",
        "a_score_distributor": "Score General",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Vow",
        "a_valentines_weeb": "Silver Valentine",
        "a_pi_day": "Pi Day Yoki",
        "a_april_fools": "April Fools",
        "a_international_anime_day": "Warrior's Day",
        "a_star_wars_day": "Empire Day",
        "a_summer_solstice": "Solstice Hunt",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Yoma Friday",
        "a_halloween_spirit": "Yoma Halloween",
        "a_thanksgiving_binge": "Harvest Feast",
        "a_christmas_special": "Midwinter Silver",
        "a_new_years_eve": "Eve's Last Stand",
        "a_birthday_watch": "Birth Rite",
        "a_holiday_marathon": "Holiday Hunt",
        "a_independence_day": "Freedom Day",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Advance",
        "a_earth_day": "World Guard",
        "a_labor_day": "Labor Rest",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Silver Birthday",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Consecutive Feasts",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Awakening",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Started",
        "a_meta_tier_climber": "Rank Climbed",
        "a_meta_tier_max": "Single Digit",
        "a_meta_xp_earner": "Yoki Earned",
        "a_meta_difficulty_easy": "Easy Hunt",
        "a_meta_difficulty_hard": "Abyssal Challenge",
        "a_meta_unlock_spree": "Unlock Storm",
        "a_meta_completionist": "Meta Complete",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Silver Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page",
        "m_chapter_counter": "Chapter Tally",
        "m_chapter_titan": "Awakened Chapter",
        "m_reading_hours": "Reading Hours",
        "m_reading_time_lord": "Teresa's Tome",
        "m_manga_collector": "Archive Hoard",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Finished",
        "m_hundred_club": "Century Reader",
        "m_first_day": "First Reading",
        "m_first_rating": "First Rating",
        "m_ten_thousand_pages": "Ten Thousand",
        "m_volume_collector": "Volume Hoard",
        "m_year_explorer": "Year Explored",
        "m_century_reader": "Century Chapters",
        "m_five_hundred_ch": "Five Hundred",
        "m_thousand_ch": "Thousand Read",
        "m_reading_ten": "Ten at Once",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Drop",
        "m_season_reader": "Season Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Deep Archive",
        "m_ten_completed": "Ten Complete",
        "m_fifty_completed": "Fifty Finished",
        "m_five_hundred_completed": "Silver Conquest",
        "m_mean_score_tracker": "Average Score",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Favorites Hoard",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reader",
        "m_marathon_reader": "Reading Marathon",
        "m_weekend_reader": "Weekend Pages",
        "m_non_stop_reading": "Non-Stop Read",
        "m_one_more_chapter": "One More Page",
        "m_speed_read": "Speed Reader",
        "m_double_story": "Double Story",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five Daily",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Dive",
        "m_full_day_read": "Full-Day Study",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge Ruler",
        "m_no_sleep_read": "Sleepless Read",
        "m_full_series_rush": "Series Rush",
        "m_seven_day_challenge": "Seven-Day Read",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Swept",
        "m_genre_binge": "Genre Binge",
        "m_author_binge": "Author Dive",
        "m_chapter_counter_day": "Daily Chapters",
        "m_multi_series_binge": "Multi-Series Run",
        "m_midnight_binge": "Midnight Pages",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "Forty-Eight Hour",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Reader",
        "m_genre_adventure": "Adventure Bound",
        "m_genre_comedy": "Comic Relief",
        "m_genre_drama": "Silver Drama",
        "m_genre_fantasy": "Fantasy Tome",
        "m_genre_horror": "Horror Scroll",
        "m_genre_mystery": "Mystery Page",
        "m_genre_romance": "Romance Scroll",
        "m_genre_scifi": "Sci-Fi Archive",
        "m_genre_sol": "Peaceful Pages",
        "m_genre_sports": "Training Manual",
        "m_genre_supernatural": "Yoki Manuscript",
        "m_genre_thriller": "Thriller Intel",
        "m_genre_psychological": "Mind Warfare",
        "m_genre_isekai": "Other Worlds",
        "m_genre_shounen": "Young Blade",
        "m_genre_ecchi": "Resting Blade",
        "m_genre_mahou_shoujo": "Silver Magic",
        "m_genre_mecha": "Steel Blueprints",
        "m_genre_music": "Silver Songs",
        "m_tag_isekai_new": "New World",
        "m_tag_harem": "Squad Bonds",
        "m_tag_bl": "Brothers Manga",
        "m_tag_gl": "Shield Sisters",
        "m_tag_historical": "Ancient Records",
        "m_tag_military": "Military Manga",
        "m_tag_school": "Trainee Manga",
        "m_tag_martial_arts": "Combat Manual",
        "m_tag_vampire": "Blood Manga",
        "m_tag_samurai": "Blade Manga",
        "m_tag_space": "Beyond Stars",
        "m_tag_parody": "Silver Parody",
        "m_tag_idol": "Warrior Song",
        "m_tag_post_apocalyptic": "Ruined World",
        "m_tag_cyberpunk": "Steel Future",
        "m_tag_shoujo": "Clare's Story",
        "m_tag_survival": "Survival Scroll",
        "m_tag_cooking": "Ration Recipes",
        "m_tag_medical": "Field Medic",
        "m_tag_villainess": "Awakened One",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Clearance",
        "m_mega_completionist": "Supreme Reader",
        "m_completion_rate_50": "Halfway Through",
        "m_completion_rate_75": "Near Complete",
        "m_completion_rate_90": "Almost Done",
        "m_no_drop": "No Abandonment",
        "m_long_runner_complete": "Endurance Medal",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean Record",
        "m_from_ptr": "Orders Read",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Read",
        "m_revival": "Flesh Rebound",
        "m_zero_to_hundred": "Trainee Scholar",
        "m_five_genre_complete": "Five Genres",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Cleared",
        "m_paused_to_done": "Back Active",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Badge",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi Reread",
        "m_dropped_recovery": "Recovered Read",
        "m_ten_perfect_scores": "Ten Perfects",
        "m_complete_genre_span": "All-Genre Read",
        "m_monthly_completions": "Monthly Wins",
        "m_yearly_completions": "Yearly Campaign",
        "m_rapid_complete": "Rapid Finish",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Fan",
        "m_rereader": "Silver Reread",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Return",
        "m_publisher_fan": "Publisher Ally",
        "m_artist_fan": "Artist Medal",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Scout",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyal",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Vow",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Honored Author",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "World Collector",
        "m_serialization_follower": "Serial Tracker",
        "m_genre_master": "Genre Mastered",
        "m_multi_series_author": "Multi-Series Fan",
        "m_format_diversity": "Diverse Reads",
        "m_year_dedication": "Year Sworn",
        "m_ongoing_follower": "Ongoing Watch",
        "m_genre_loyalty_50": "Fifty Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Scout",
        "m_publisher_hopper": "Publisher Hop",
        "m_tag_explorer": "Tag Recon",
        "m_decade_hopper": "Decade Jumper",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Pick",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross Ranks",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Varied Week",
        "m_manhwa_reader": "Manhwa Intel",
        "m_manhua_reader": "Manhua Intel",
        "m_classic_connoisseur": "Classic Scroll",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Niche Found",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Monthly",
        "m_year_completionist": "Year Complete",
        "m_unpopular_opinion": "Lone Voice",
        "m_top_rated_reader": "Top Rated",
        "m_source_variety": "Source Spread",
        "m_low_score_brave": "Brave Read",
        "m_short_manga_explorer": "Short Manga",
        "m_long_manga_explorer": "Long Manga",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Midday Pages",
        "m_commute_reader": "Travel Reader",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All-Hours Read",
        "m_prime_time_reader": "Prime Reader",
        "m_workday_reader": "On-Duty Read",
        "m_sunday_read": "Sunday Reading",
        "m_morning_routine": "Morning Pages",
        "m_night_shift_reader": "Night Shift",
        "m_seasonal_premier_read": "New Release",
        "m_clock_collector": "Clock Reader",
        "m_late_night_horror": "Midnight Horror",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Hour",
        "m_dawn_reader": "Dawn Pages",
        "m_twilight_reader": "Twilight Read",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Hours",
        "m_late_night_regular": "Late Regular",
        "m_sunrise_reader": "Sunrise Read",
        "m_every_day_of_week": "Every Day",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Pages",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Admirer",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Read",
        "m_adaptation_reader": "Adaptation Read",
        "m_longstrip_reader": "Longstrip Read",
        "m_4koma_reader": "4-Koma Read",
        "m_oneshot_reader": "Oneshot Read",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Blade",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Read",
        "m_cross_media": "Cross Media",
        "m_spinoff_reader": "Spinoff Read",
        "m_remake_reader": "Remake Read",
        "m_collaboration_reader": "Joint Work",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Reading",
        "m_mega_streak": "Mega Reading",
        "m_weekly_warrior": "Weekly Reader",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader Returns",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Reader",
        "m_habit_formed": "Habit Formed",
        "m_consistent_pace": "Steady Pace",
        "m_year_long": "Year-Long Read",
        "m_double_streak": "Double Streak",
        "m_streak_recovery": "Streak Healed",
        "m_daily_minimum": "Daily Minimum",
        "m_winter_streak": "Winter Read",
        "m_summer_streak": "Summer Read",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Streak",
        "m_unbreakable": "Unbreakable",
        "m_eternal_flame": "Eternal Reader",
        "m_chapter_a_day": "Chapter Daily",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Complete Chain",
        "m_rating_streak": "Rating Chain",
        "m_multi_ch_streak": "Multi-Chapter",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Steel Critic",
        "m_perfect_ten": "Perfect Ten",
        "m_harsh_critic": "Harsh Blade",
        "m_fair_judge": "Fair Judge",
        "m_generous_spirit": "Generous Read",
        "m_score_all": "All Scored",
        "m_wide_range": "Wide Scores",
        "m_controversial": "Divisive Score",
        "m_consistent_scorer": "Steady Scorer",
        "m_score_sniper": "Score Sniper",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Selective Read",
        "m_100_rated": "Century Scores",
        "m_500_rated": "Five Hundred",
        "m_mediocre_majority": "Middle Ground",
        "m_rating_spree": "Rating Spree",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Hunt",
        "m_contrarian": "Lone Contrarian",
        "m_optimist": "Silver Optimist",
        "m_score_distributor": "Score Spreader",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Vow",
        "m_valentines_read": "Silver Valentine",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Fools",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic",
        "m_summer_solstice": "Solstice Read",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Yoma Friday",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Harvest Read",
        "m_christmas_read": "Midwinter Read",
        "m_new_years_eve": "Eve's Last Page",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Pages",
        "m_independence_day": "Freedom Read",
        "m_culture_day": "Culture Read",
        "m_spring_equinox": "Spring Read",
        "m_earth_day": "World Read",
        "m_labor_day": "Labor Read",
        "m_winter_solstice": "Winter Read",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "Every Holiday",
        "m_consecutive_holidays": "Consecutive Read",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Milestone",
        "m_fibonacci": "Fibonacci Page",
        "m_palindrome_day": "Palindrome Read",
        "m_binary_day": "Binary Read",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Silver",
        "m_thousand_complete": "Thousand Done",
        "m_nice": "Nice Count",
        "m_power_level_chapters": "Yoki Chapters",
        "m_answer_42": "Answer Found",
        "m_square_number": "Square Count",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Matching Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Yoki Resonance",
        "m_world_record": "World Record",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time Traveler",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Match",
        "m_chapter_match_date": "Chapter Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Unlock",
        "m_meta_collector": "Badge Collector",
        "m_meta_category_starter": "Category Start",
        "m_meta_tier_climber": "Tier Climbed",
        "m_meta_tier_max": "Maximum Rank",
        "m_meta_xp_earner": "XP Earned",
        "m_meta_difficulty_easy": "Easy Task",
        "m_meta_difficulty_hard": "Abyssal Trial",
        "m_meta_unlock_spree": "Unlock Spree",
        "m_meta_completionist": "Meta Complete",
        "m_meta_diverse": "Diverse Reader",
        "m_meta_dominator": "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040506",
        primary: "#b4bec8",
        secondary: "#828c9b",
        accent: "#464e5a",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        silver_sparks: { label: "Silver Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        yoma_mist: { label: "Yoma Mist", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        blade_gleam: { label: "Blade Gleam", maxCount: 10, defaultEnabled: true, defaultIntensity: 60 },
        eye_glow: { label: "Eye Glow", maxCount: 6, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1:   "Trainee",
        5:   "Warrior",
        15:  "Single Digit",
        30:  "Awakened Hunter",
        45:  "Abyssal Foe",
        60:  "Teresa's Will",
        80:  "Beyond Limits",
        100: "Claymore",
    },
}
