import { AnimeThemeConfig } from "./types"
import {
    GiCrystalBall, GiChessKnight, GiChessRook, GiChessQueen,
    GiElectric, GiSwordman, GiScrollUnfurled, GiSpellBook,
    GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss } from "react-icons/lu"
import { BiExtension } from "react-icons/bi"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { TbReportSearch } from "react-icons/tb"

export const codeGeassTheme: AnimeThemeConfig = {
    id: "code-geass",
    displayName: "Code Geass",
    description: "Britannia's iron grip. The Black Knights rise. Geass-eye purple & imperial red.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700;900&display=swap",
    cssVars: {
        "--color-brand-200": "230 180 255",
        "--color-brand-300": "200 130 255",
        "--color-brand-400": "165 80 240",
        "--color-brand-500": "130 40 220",
        "--color-brand-600": "100 20 180",
        "--color-brand-700": "75 10 140",
        "--color-brand-800": "50 5 100",
        "--color-brand-900": "30 2 65",
        "--color-brand-950": "15 0 35",
        "--brand": "145 55 230",
        "--background": "#060008",
        "--paper": "#0e000f",
        "--color-gray-950": "5 0 8",
        "--color-gray-900": "12 0 16",
        "--color-gray-800": "22 4 28",
        "--color-gray-700": "38 10 45",
        "--color-gray-600": "60 20 70",
        "--color-gray-500": "95 40 110",
        "--color-gray-400": "145 80 165",
        "--color-gray-300": "185 125 205",
        "--color-gray-200": "220 170 235",
        "--color-gray-100": "242 215 248",
        "--color-gray-50":  "252 245 254",
    },
    sidebarOverrides: {
        "home":           { icon: GiChessKnight,   label: "Britannian Court" },
        "schedule":       { icon: GiAlarmClock,    label: "Operation Board" },
        "manga":          { icon: GiScrollUnfurled,label: "Intelligence Files" },
        "lists":          { icon: GiChessRook,     label: "Knight Registry" },
        "discover":       { icon: GiCrystalBall,   label: "Geass Sight" },
        "torrent-list":   { icon: GiSwordman,      label: "Resistance Ops" },
        "unmatched":      { icon: GiChessQueen,    label: "Classified" },
        "scan-summaries": { icon: TbReportSearch,  label: "Tactical Reports" },
        "auto-downloader":{ icon: LuRss,           label: "Spy Network" },
        "search":         { icon: FiSearch,        label: "Search" },
        "notifications":  { icon: LuBell,          label: "Orders" },
        "achievements":   { icon: GiTrophyCup,     label: "Conquer Board" },
        "theme-manager":  { icon: GiPalette,       label: "Geass Colors" },
        "extensions":     { icon: BiExtension,     label: "Contracts" },
        "settings":       { icon: GiSettingsKnobs, label: "Emperor's Decree" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Geass Command Issued",
        "a_episode_counter": "Geass Activation Counter",
        "a_episode_titan": "Suzaku-Class Engagement",
        "a_hours_invested": "Hours in the War Room",
        "a_time_lord": "Eternal Zero Strategy",
        "a_anime_collector": "Britannian Archive",
        "a_library_legend": "Emperor's Grand Library",
        "a_first_complete": "First Territory Conquered",
        "a_hundred_club": "Century of Machinations",
        "a_first_day": "Day of Rebellion",
        "a_first_rating": "Strategic Assessment",
        "a_ten_thousand_min": "Ten Thousand Minutes of Planning",
        "a_season_veteran": "Veteran Black Knight",
        "a_year_explorer": "Year of the Requiem",
        "a_century_watcher": "Hundred-Episode Campaign",
        "a_five_hundred_eps": "Five Hundred Knightmare Sorties",
        "a_thousand_eps": "Thousand Geass Commands",
        "a_watching_ten": "Ten Fronts Controlled",
        "a_ptw_hoarder": "Operation Backlog Cache",
        "a_dropped_honesty": "Strategic Retreat",
        "a_five_thousand_eps": "Five Thousand Chess Moves",
        "a_ten_completed": "Ten Campaigns Complete",
        "a_fifty_completed": "Fifty Operations Done",
        "a_five_hundred_completed": "Five Hundred Victories for Zero",
        "a_mean_score_tracker": "Average Battle Rating",
        "a_unique_studios": "Allied Factions",
        "a_days_spent_watching": "Days in Ashford Academy",
        "a_all_status": "All Mission Statuses",
        "a_first_favorite": "First Knightmare Bond",
        "a_favorites_collector": "Order of the Black Knights",
        // ── ANIME BINGE ──
        "a_binge_watcher": "Zero's Binge Strategy",
        "a_marathon_runner": "Black Knight Marathon",
        "a_weekend_warrior": "Weekend Knightmare Pilot",
        "a_non_stop": "Relentless Geass Advance",
        "a_one_more_episode": "One More Chess Move",
        "a_speed_run": "Geass Speed Blitz",
        "a_double_feature": "Double Knightmare Strike",
        "a_triple_threat": "Triple Faction Takedown",
        "a_five_a_day": "Five Commands a Day",
        "a_back_to_back": "Back-to-Back Operations",
        "a_seasonal_binge": "Full Campaign Arc",
        "a_cour_crusher": "District Crusher",
        "a_half_day_watch": "Half-Day War Room Shift",
        "a_full_day_watch": "Full Day Command Session",
        "a_power_weekend": "Power Weekend Offensive",
        "a_binge_king": "King of Geass Ops",
        "a_no_sleep": "All-Night Battle of Narita",
        "a_entire_season": "Rapid Area Eleven Capture",
        "a_seven_day_challenge": "Seven-Day Operation Daybreak",
        "a_hundred_day_binge": "Hundred-Day Siege",
        "a_genre_binge": "Cross-Faction Binge",
        "a_studio_binge": "Allied Force Binge",
        "a_season_sweep": "Season Sweep Knightmare",
        "a_forty_eight_hour": "Forty-Eight Hour Standoff",
        "a_ep_counter_day": "Daily Sortie Count",
        "a_multi_series_binge": "Multi-Front Campaign",
        "a_midnight_binge": "Midnight Reconnaissance",
        "a_new_year_binge": "New Year's Coup",
        // ── ANIME GENRES ──
        "a_genre_action": "Knightmare Frame Combat",
        "a_genre_adventure": "Beyond Britannia",
        "a_genre_comedy": "Ashford Festival Chaos",
        "a_genre_drama": "Tear of the Empress",
        "a_genre_fantasy": "World of C Visitor",
        "a_genre_horror": "Geass Horror",
        "a_genre_mystery": "Zero Mask Investigator",
        "a_genre_romance": "Shirley's Undying Love",
        "a_genre_scifi": "Sakuradite Research",
        "a_genre_sol": "Ashford Academy Life",
        "a_genre_sports": "Ashford Cavalry",
        "a_genre_supernatural": "Geass Power Wielder",
        "a_genre_thriller": "Operation Zero Hunt",
        "a_genre_mecha": "Lancelot Pilot",
        "a_genre_music": "Zero Requiem Anthem",
        "a_genre_psychological": "Geass Mind Games",
        "a_genre_ecchi": "Ashford Pool Episode",
        "a_genre_mahou_shoujo": "World of C Power",
        "a_tag_isekai": "Transported to Area Eleven",
        "a_tag_harem": "Lelouch's Admirers",
        "a_tag_bl": "Rivalz & Lelouch",
        "a_tag_gl": "Kallen & Cornelia",
        "a_tag_historical": "Britannian Empire History",
        "a_tag_military": "Knight of the Round",
        "a_tag_school": "Ashford Academy",
        "a_tag_martial_arts": "Hand-to-Hand Schwarzer Ritter",
        "a_tag_vampire": "Code Immortality",
        "a_tag_samurai": "Todoh's Sword",
        "a_tag_space": "FLEIJA Detonation Zone",
        "a_tag_parody": "Lelouch Lamp Parody",
        "a_tag_idol": "Rivalz Fan Club",
        "a_tag_post_apocalyptic": "Post-Zero Requiem World",
        "a_tag_cyberpunk": "Sakuradite Tech",
        "a_tag_shounen": "Lelouch's Ambition",
        "a_tag_seinen": "War's True Cost",
        "a_tag_shoujo": "Euphemia's Dream",
        "a_tag_josei": "Villetta's Regret",
        "a_tag_survival": "Survival in the Chess Game",
        // ── ANIME COMPLETION ──
        "a_completionist": "All Areas Conquered",
        "a_mega_completionist": "Supreme Commander",
        "a_completion_rate_50": "Halfway to the Throne",
        "a_completion_rate_75": "75% Britannian Territory",
        "a_completion_rate_90": "Almost Emperor",
        "a_no_drop": "Never Abandon the Plan",
        "a_long_runner_complete": "Long Campaign Endurance",
        "a_sequel_chain": "R2 Continuation",
        "a_clean_list": "Clean Service Record",
        "a_from_ptw": "Orders Executed",
        "a_rewatch_master": "Rewind Geass via Code",
        "a_short_complete": "Quick Skirmish Victory",
        "a_same_day_start_finish": "Same-Day Territory Capture",
        "a_revival": "Immortal Code Revival",
        "a_zero_to_hero": "Student to Emperor",
        "a_five_genre_complete": "Five-Front Mastery",
        "a_full_franchise": "Full Zero Dossier",
        "a_batch_complete": "Batch Operation Clear",
        "a_paused_to_done": "Resumed Command",
        "a_completion_spree": "Completion Geass Barrage",
        "a_multi_rewatch": "Multi-Timeline Geass",
        "a_dropped_recovery": "Recovered from the Betrayal",
        "a_ten_perfect_scores": "Ten Perfect Battle Scores",
        "a_seasonal_clear": "Seasonal Offensive Clear",
        "a_complete_genre_span": "All-Front Commander",
        "a_monthly_completions": "Monthly Mission Reports",
        "a_yearly_completions": "Yearly Campaign Victor",
        "a_rapid_complete": "Lightning Zero Strike",
        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Sworn Black Knight",
        "a_studio_devotee": "Sunrise Devotee",
        "a_rewatcher": "Geass Recon Rewatch",
        "a_triple_rewatch": "Triple Requiem Rewatch",
        "a_annual_tradition": "Annual Zero Day",
        "a_director_fan": "Goro Taniguchi's Vision",
        "a_voice_actor_fan": "Voice of Zero",
        "a_ost_lover": "Hitomi Kuroishi Anthem",
        "a_source_reader": "Original Manga Source",
        "a_waiting_weekly": "Weekly Strategy Wait",
        "a_childhood_revisit": "Return to Ashford",
        "a_saga_tracker": "Zero's Saga Tracker",
        "a_genre_loyalty": "Black Knight Loyalty",
        "a_decade_watcher": "Hundred-Year Geass User",
        "a_adaptation_hunter": "Adaptation Recon",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Campaign Duty",
        "a_perfect_attendance": "Perfect Formation Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Britannian Catalog",
        "a_franchise_collector": "Code Geass Universe Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Mastery Achieved",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Season Veteran",
        "a_format_diversity": "Diverse Tactical Formats",
        "a_year_dedication": "Year of Dedication to Zero",
        "a_season_dedication": "Season of Black Knight Service",
        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Known Territory",
        "a_studio_hopper": "Faction Transfer",
        "a_tag_explorer": "Tag Recon Mission",
        "a_decade_hopper": "Decade Hop via Code",
        "a_hidden_gem": "Hidden Underground Intel",
        "a_popular_taste": "Popular Among Black Knights",
        "a_retro_appreciator": "Pre-Rebellion Appreciator",
        "a_modern_viewer": "Modern Britannia Viewer",
        "a_cross_demographic": "Cross-Demographic Scout",
        "a_underdog_fan": "Underdog Number Eleven Spirit",
        "a_variety_week": "Week of Varied Tactics",
        "a_foreign_cinema": "Foreign Intelligence Cinema",
        "a_classic_connoisseur": "Classic Zero Strategy",
        "a_every_season": "Every Season Deployed",
        "a_award_winner": "Medal of Geass",
        "a_niche_explorer": "Niche Territory Explorer",
        "a_global_anime": "Global Alliance Entry",
        "a_cult_classic": "Zero Cult Classic",
        "a_random_pick": "Random Mission Assignment",
        "a_new_genre_month": "New Terrain Monthly",
        "a_seasonal_completionist": "Seasonal Campaign Clear",
        "a_unpopular_opinion": "Contrarian Zero",
        "a_top_rated_viewer": "Top-Rated Intel Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Operation Intel",
        "a_short_series_explorer": "Short Skirmish Explorer",
        "a_long_series_explorer": "Long Campaign Explorer",
        // ── ANIME TIME ──
        "a_night_owl": "Night Watch at Ashford",
        "a_early_bird": "Dawn Sortie",
        "a_lunch_break": "Strategy Room Lunch",
        "a_golden_hour": "Golden Hour Signal Flare",
        "a_four_am_club": "4 AM War Room",
        "a_witching_hour": "Geass Witching Hour",
        "a_new_year_watch": "New Year's Coup Plan",
        "a_midnight_premiere": "Midnight Operation",
        "a_all_hours": "All-Hours Commander",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Strategy Drill",
        "a_prime_time": "Prime Time Engagement",
        "a_workday_watcher": "On-Duty Commander",
        "a_sunday_marathon": "Sunday Knightmare Marathon",
        "a_rainy_day": "Rainy Day in Ashford",
        "a_morning_routine": "Morning Formation",
        "a_night_shift": "Night Shift Operation",
        "a_twilight_zone": "Twilight Zone of Control",
        "a_seasonal_premier": "Season Premiere Sortie",
        "a_clock_collector": "Chess Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge Operations",
        "a_late_night_regular": "Late Night Regular Patrol",
        "a_sunrise_watcher": "Sunrise Over Area Eleven",
        "a_holiday_watcher": "Holiday Guard Duty",
        "a_every_day_of_week": "Every Day Deployed",
        "a_monthly_hours": "Monthly Duty Hours",
        // ── ANIME SOCIAL ──
        "a_first_party": "First Black Knight Formation",
        "a_party_host": "Operation Commander",
        "a_social_butterfly": "Ashford Socialite",
        "a_group_binge": "Group Knightmare Volley",
        "a_party_regular": "Regular Sparring Partner",
        "a_sync_viewer": "Synchronized Operation",
        "a_commentator": "Battle Commentator",
        "a_party_marathon": "Marathon Formation Run",
        "a_full_house": "Full Squad Assembled",
        "a_community_pillar": "Pillar of the Black Knights",
        "a_watch_party_streak": "Consecutive Formation Streak",
        "a_diverse_party": "Diverse Faction Party",
        "a_late_night_party": "Late Night HQ Party",
        "a_party_veteran": "Veteran Squad Leader",
        "a_genre_party": "Cross-Genre Formation",
        "a_weekly_party": "Weekly Black Knights Gathering",
        "a_silent_viewer": "Silent Zero Observer",
        "a_recommendation_giver": "Zero's Recommendation",
        "a_party_completionist": "Party Operation Completionist",
        "a_social_scorer": "Social Combat Scorer",
        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Requiem",
        "a_fibonacci": "Fibonacci Geass Sequence",
        "a_palindrome_day": "Palindrome Code Day",
        "a_binary_day": "Binary Command Signal",
        "a_full_moon": "Requiem Night",
        "a_leap_year": "Leap Year Time Skip",
        "a_time_traveler": "Time via Code",
        "a_genre_clash": "Britannia vs. Zero Clash",
        "a_triple_seven": "Triple Seven Black Knights",
        "a_thousand_complete": "Thousand Operations",
        "a_pi_episodes": "Pi Tactical Calculation",
        "a_synchronicity": "Geass Synchronicity",
        "a_world_record": "World Record Conquest",
        "a_nice": "Nice Kill Count",
        "a_power_level": "Lelouch's Power Level",
        "a_answer_42": "The Answer to Zero's Question",
        "a_square_number": "Perfect Chessboard Formation",
        "a_prime_count": "Prime Number of Victories",
        "a_matching_date": "Matching Intel Date",
        "a_century_episode": "Century Episode Assault",
        "a_double_digits": "Double Digit Victories",
        "a_one_two_three": "Phases One Two Three",
        "a_lucky_seven": "Seven Knights",
        "a_all_tens": "All Tens Battle Score",
        "a_exact_hundred_eps": "Exact Hundred Engagements",
        "a_year_match_count": "Year Match Kill Count",
        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Commander",
        "a_movie_buff": "Knightmare Movie Operations",
        "a_ova_hunter": "OVA Knightmare Hunter",
        "a_ona_explorer": "ONA Scout Explorer",
        "a_special_watcher": "Special Episode Operative",
        "a_short_king": "Short Engagement King",
        "a_variety_pack": "All-Format Regiment",
        "a_film_festival": "Code Geass Film Festival",
        "a_music_video": "Hitomi Collection",
        "a_tv_short": "Quick Recon Clip",
        "a_movie_marathon": "Movie Marathon Blitz",
        "a_double_length": "Double-Length Operation",
        "a_anthology": "Black Knights Anthology",
        "a_mini_series": "Mini Campaign Collection",
        "a_theatrical": "Theatrical Requiem",
        "a_format_master": "Format Master Commander",
        "a_long_movie": "Feature-Length Expedition",
        "a_back_catalog": "Back Catalog Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Tactical Formats",
        "a_episodic_master": "Episodic Campaign Master",
        "a_sequel_movie": "Sequel Operation Film",
        "a_recap_watcher": "Recap Briefing Watcher",
        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Knightmare Sortie",
        "a_mega_streak": "Lelouch's Unbroken Plan",
        "a_weekly_warrior": "Weekly Warrior of Zero",
        "a_monthly_watcher": "Monthly Black Knight Duty",
        "a_comeback": "Return from Exile",
        "a_weekend_streak": "Weekend Sortie Streak",
        "a_no_zero_days": "No Zero Days on Campaign",
        "a_iron_will": "Iron Will of Zero",
        "a_habit_formed": "Training Regimen Formed",
        "a_consistent_pace": "Consistent March Forward",
        "a_year_long": "Year-Long Campaign",
        "a_double_streak": "Double Streak Assault",
        "a_streak_recovery": "Recovered from Betrayal",
        "a_daily_minimum": "Daily Minimum Duty",
        "a_winter_streak": "Winter Campaign Streak",
        "a_summer_streak": "Summer Offensive Streak",
        "a_morning_streak": "Morning Drill Streak",
        "a_night_streak": "Night Operation Streak",
        "a_unbreakable": "Unbreakable Will of Zero",
        "a_eternal_flame": "Eternal Flame of Rebellion",
        "a_completion_streak": "Completion Mission Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Episode Offensive",
        "a_genre_streak": "Genre Streak Sortie",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Week of Service",
        // ── ANIME SCORING ──
        "a_critic": "Zero Evaluator",
        "a_perfect_ten": "Perfect 10 Battle Rating",
        "a_harsh_critic": "Lelouch's Harsh Standards",
        "a_fair_judge": "Schneizel's Fair Assessment",
        "a_generous_spirit": "Generous Knight",
        "a_score_all": "Full Intelligence Report",
        "a_wide_range": "Wide Range Tactical Assessment",
        "a_controversial": "Controversial Command Decision",
        "a_consistent_scorer": "Consistent Evaluator",
        "a_score_sniper": "Precision Zero Sniper",
        "a_evolving_taste": "Evolving Strategy",
        "a_bell_curve": "Bell Curve of Battle Scores",
        "a_picky_watcher": "Selective Commander",
        "a_100_rated": "Century of Evaluations",
        "a_500_rated": "Five Hundred Field Reports",
        "a_mediocre_majority": "Middle Ground Strategist",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Variable Battle Ratings",
        "a_masterpiece_hunter": "Masterpiece Intel Hunter",
        "a_contrarian": "Contrarian Zero",
        "a_optimist": "Optimist Despite the Empire",
        "a_score_distributor": "Score Distributor General",
        "a_genre_critic": "Genre Tactical Critic",
        "a_mean_above_8": "Elite Combat Average",
        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Rebellion Vow",
        "a_valentines_weeb": "Valentine's Geass",
        "a_pi_day": "Pi Day Tactical Calc",
        "a_april_fools": "April Fools Zero Prank",
        "a_international_anime_day": "International Commander Day",
        "a_star_wars_day": "Britannian Empire Day",
        "a_summer_solstice": "Summer Solstice Campaign",
        "a_tanabata": "Tanabata Wish for Zero",
        "a_friday_13th": "Friday the 13th Coup",
        "a_halloween_spirit": "Halloween Knightmare Horror",
        "a_thanksgiving_binge": "Thanksgiving Feast in Ashford",
        "a_christmas_special": "Midwinter Festival Special",
        "a_new_years_eve": "New Year's Eve Final Stand",
        "a_birthday_watch": "Birthday Command Watch",
        "a_holiday_marathon": "Holiday Campaign Marathon",
        "a_independence_day": "Britannian Independence Day",
        "a_culture_day": "Britannian Culture Day",
        "a_spring_equinox": "Spring Equinox Advance",
        "a_earth_day": "Protect the Homeland Day",
        "a_labor_day": "Black Knight Labor Day",
        "a_winter_solstice": "Winter Solstice Campaign",
        "a_anime_birthday": "Anime Anniversary Celebration",
        "a_every_holiday": "Every Holiday Commander",
        "a_consecutive_holidays": "Consecutive Holiday Operations",
        // ── ANIME META ──
        "a_meta_first_unlock": "First Geass Power Awakened",
        "a_meta_collector": "Black Knight Badge Collector",
        "a_meta_category_starter": "Category Initiation Rite",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Knight of One Rank",
        "a_meta_xp_earner": "XP from Battle Plans",
        "a_meta_difficulty_easy": "Easy Training Exercise",
        "a_meta_difficulty_hard": "Legendary: Suzaku-Level Challenge",
        "a_meta_unlock_spree": "Unlock Spree Knightmare",
        "a_meta_completionist": "Meta Completionist Commander",
        "a_meta_diverse": "Diverse Faction Portfolio",
        "a_meta_dominator": "Meta Dominator of Britannia",
        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Black Knight Intel",
        "m_chapter_counter": "Chapter Strategy Counter",
        "m_chapter_titan": "Chapter Titan-Class Assault",
        "m_reading_hours": "Hours Studying War Plans",
        "m_reading_time_lord": "Immortal Code Reader",
        "m_manga_collector": "Geass Files Archive",
        "m_library_legend": "Lelouch's Grand Library",
        "m_first_complete": "First Manga Campaign Done",
        "m_hundred_club": "Hundred-Chapter Club",
        "m_first_day": "Day One Reading",
        "m_first_rating": "First Intel Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Plans",
        "m_volume_collector": "Volume Stockpile",
        "m_year_explorer": "Year of Manga Exploration",
        "m_century_reader": "Century-Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Chapters",
        "m_thousand_ch": "Thousand-Chapter Campaign",
        "m_reading_ten": "Ten Manuscripts at Once",
        "m_ptr_hoarder": "Reading Backlog Cache",
        "m_dropped_honesty": "Strategic Reading Retreat",
        "m_season_reader": "Seasonal Reading Rotation",
        "m_active_reader": "Active Field Reader",
        "m_five_thousand_ch": "Five Thousand Chapters Deep",
        "m_ten_completed": "Ten Manga Campaigns",
        "m_fifty_completed": "Fifty Manga Missions",
        "m_five_hundred_completed": "Five Hundred Manga Victories",
        "m_mean_score_tracker": "Average Manuscript Rating",
        "m_unique_authors": "Unique Author Encounters",
        "m_all_status": "All Reading Statuses",
        "m_first_favorite": "First Manga Bond",
        "m_favorites_collector": "Manga Favorites Arsenal",
        "m_days_spent_reading": "Days Reading War Plans",
        // ── MANGA BINGE ──
        "m_binge_reader": "All-Night Strategizing",
        "m_marathon_reader": "Black Knight Reading Marathon",
        "m_weekend_reader": "Weekend HQ Reading",
        "m_non_stop_reading": "Non-Stop Page Turning",
        "m_one_more_chapter": "One More Plan",
        "m_speed_read": "Knightmare Speed Read",
        "m_double_story": "Double Manuscript Feature",
        "m_triple_read": "Triple Reading Assault",
        "m_five_a_day": "Five Reads a Day",
        "m_chapter_chain": "Chapter Chain Offensive",
        "m_volume_binge": "Volume Binge Bombardment",
        "m_power_reader": "Power Reader Commander",
        "m_half_day_read": "Half-Day Archive Dive",
        "m_full_day_read": "Full-Day Manuscript Study",
        "m_power_weekend": "Power Weekend Reading",
        "m_binge_king": "King of the Reading Corps",
        "m_no_sleep_read": "All-Night Reading Session",
        "m_full_series_rush": "Full Series Rush Attack",
        "m_seven_day_challenge": "Seven-Day Intel Gathering",
        "m_hundred_day_read": "Hundred-Day Reading Siege",
        "m_volume_rush": "Volume Rush Deployment",
        "m_series_sweep": "Series Sweep Operation",
        "m_genre_binge": "Cross-Genre Reading",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Count",
        "m_multi_series_binge": "Multi-Series Reading Front",
        "m_midnight_binge": "Midnight Archive Session",
        "m_new_year_binge": "New Year's Reading Charge",
        "m_forty_eight_hour": "Forty-Eight Hour Reading Siege",
        "m_oneshot_binge": "Oneshot Blitz",
        // ── MANGA GENRES ──
        "m_genre_action": "Knightmare Frame Manga",
        "m_genre_adventure": "Beyond Britannia Manga",
        "m_genre_comedy": "Ashford Festival Manga",
        "m_genre_drama": "Zero's Tragic Drama",
        "m_genre_fantasy": "World of C Manga",
        "m_genre_horror": "Geass Horror Manga",
        "m_genre_mystery": "Zero Mask Mystery",
        "m_genre_romance": "Shirley's Romance Manga",
        "m_genre_scifi": "Sakuradite Sci-Fi Manga",
        "m_genre_sol": "Ashford Life Manga",
        "m_genre_sports": "Ashford Cavalry Manga",
        "m_genre_supernatural": "Geass Power Manga",
        "m_genre_thriller": "Operation Thriller Manga",
        "m_genre_psychological": "Mind Game Manga",
        "m_genre_isekai": "Isekai Britannia",
        "m_genre_shounen": "Shounen Rebellion",
        "m_genre_ecchi": "Ashford Pool Manga",
        "m_genre_mahou_shoujo": "World of C Power Manga",
        "m_genre_mecha": "Lancelot Manga",
        "m_genre_music": "Zero Requiem Manga",
        "m_tag_isekai_new": "New World Beyond Britannia",
        "m_tag_harem": "Lelouch's Fan Club Manga",
        "m_tag_bl": "Zero & Suzaku Bond",
        "m_tag_gl": "Kallen & Cornelia Manga",
        "m_tag_historical": "Britannian History Manga",
        "m_tag_military": "Knight of the Round Manga",
        "m_tag_school": "Ashford Academy Manga",
        "m_tag_martial_arts": "Ackerman-Style Combat",
        "m_tag_vampire": "Code Immortal Manga",
        "m_tag_samurai": "Todoh's Blade Manga",
        "m_tag_space": "FLEIJA Zone Manga",
        "m_tag_parody": "Chibi Zero Manga",
        "m_tag_idol": "Milly Fan Club Manga",
        "m_tag_post_apocalyptic": "Post-Requiem Manga",
        "m_tag_cyberpunk": "Sakuradite Tech Manga",
        "m_tag_shoujo": "Euphemia's Dream Manga",
        "m_tag_survival": "Survival Chess Manga",
        "m_tag_cooking": "Ashford Cooking Club",
        "m_tag_medical": "Field Medic Manga",
        "m_tag_villainess": "Villainous Empress Manga",
        // ── MANGA COMPLETION ──
        "m_completionist": "Complete Conquest",
        "m_mega_completionist": "Supreme Reading Commander",
        "m_completion_rate_50": "Halfway to the Throne",
        "m_completion_rate_75": "Approaching Emperor",
        "m_completion_rate_90": "Zero Requiem Approaching",
        "m_no_drop": "No Manuscript Abandoned",
        "m_long_runner_complete": "Long Campaign Endurance",
        "m_sequel_chain": "R2 Manga Continuation",
        "m_clean_list": "Clean Reading Record",
        "m_from_ptr": "Orders Received: Read",
        "m_reread_master": "Code-Immortal Reread",
        "m_oneshot_complete": "Oneshot Mission Specialist",
        "m_same_day_start_finish": "Same-Day Capture",
        "m_revival": "Code Revival Reading",
        "m_zero_to_hundred": "Number Eleven to Emperor",
        "m_five_genre_complete": "Five-Genre Mastery",
        "m_full_collection": "Full Geass Archive",
        "m_batch_complete": "Batch Clearance",
        "m_paused_to_done": "Resumed from Exile",
        "m_completion_spree": "Completion Barrage",
        "m_format_completionist": "Format Completion Badge",
        "m_catch_up": "Caught Up with Rebellion",
        "m_multi_reread": "Multi-Pass via Code",
        "m_dropped_recovery": "Recovered from Betrayal",
        "m_ten_perfect_scores": "Ten Perfect Manga Scores",
        "m_complete_genre_span": "All-Genre Reading Commander",
        "m_monthly_completions": "Monthly Manuscript Victories",
        "m_yearly_completions": "Yearly Reading Campaign",
        "m_rapid_complete": "Lightning Intel Processing",
        "m_author_complete": "Author's Complete Works",
        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Black Knight Reader",
        "m_mangaka_lover": "Majiko! Devotee",
        "m_rereader": "Geass Rereader",
        "m_triple_reread": "Triple Requiem Reread",
        "m_annual_reread": "Annual Zero Day Reread",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Artist Appreciation Medal",
        "m_adaptation_compare": "Manga vs Anime Intel Compare",
        "m_source_material_fan": "Source Material Commander",
        "m_waiting_weekly": "Weekly Chapter Wait",
        "m_classic_reader": "Classic Geass Reader",
        "m_saga_reader": "Zero's Saga Reader",
        "m_genre_loyalty": "Genre Loyalty Medal",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "Light Novel Adaptation",
        "m_original_work": "Original Manga Work",
        "m_long_commitment": "Long-Term Reading Commitment",
        "m_up_to_date": "Up-to-Date with the Rebellion",
        "m_favorite_mangaka": "Favorite Mangaka Honored",
        "m_complete_portfolio": "Complete Reading Portfolio",
        "m_franchise_collector": "Code Geass Franchise Collector",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Mastery Earned",
        "m_multi_series_author": "Multi-Series Author Fan",
        "m_format_diversity": "Diverse Reading Formats",
        "m_year_dedication": "Year of Dedicated Reading",
        "m_ongoing_follower": "Ongoing Series Follower",
        "m_genre_loyalty_50": "Fifty Genre Loyalty Chapters",
        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Territory Scout",
        "m_publisher_hopper": "Publisher Faction Transfer",
        "m_tag_explorer": "Tag Recon Mission",
        "m_decade_hopper": "Decade Hop via Code",
        "m_hidden_gem": "Hidden Underground Gem",
        "m_popular_taste": "Popular Among Black Knights",
        "m_retro_reader": "Retro Manuscript",
        "m_modern_reader": "Modern Era Reader",
        "m_cross_demographic": "Cross-Demographic Scout",
        "m_underdog_fan": "Underdog Reader Spirit",
        "m_variety_week": "Week of Varied Readings",
        "m_manhwa_reader": "Manhwa Intelligence",
        "m_manhua_reader": "Manhua Intelligence",
        "m_classic_connoisseur": "Classic Geass Manuscript",
        "m_award_winner": "Medal-Winning Manuscript",
        "m_niche_explorer": "Niche Territory Reader",
        "m_world_manga": "World Manga Intel",
        "m_cult_classic": "Zero Cult Classic Reading",
        "m_random_pick": "Random Reading Assignment",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Reading Completionist",
        "m_unpopular_opinion": "Contrarian Reading Opinion",
        "m_top_rated_reader": "Top-Rated Intel Source",
        "m_source_variety": "Source Material Variety",
        "m_low_score_brave": "Brave Low-Score Reader",
        "m_short_manga_explorer": "Short Manga Skirmish",
        "m_long_manga_explorer": "Long Campaign Manuscript",
        "m_serialization_explorer": "Serialization Explorer",
        // ── MANGA TIME ──
        "m_night_owl": "Night Owl HQ Reader",
        "m_early_bird": "Dawn Patrol Reader",
        "m_lunch_reader": "Strategy Room Lunch Reader",
        "m_commute_reader": "Travel to HQ Reader",
        "m_four_am_club": "4 AM Sentry Reader",
        "m_new_year_read": "New Year's Reading Oath",
        "m_all_hours": "All-Hours Archive Access",
        "m_prime_time_reader": "Prime Time Manuscript",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Reading Marathon",
        "m_morning_routine": "Morning Formation Reading",
        "m_night_shift_reader": "Night Shift Reader",
        "m_seasonal_premier_read": "New Release Intel",
        "m_clock_collector": "Chess Clock Reading Time",
        "m_late_night_horror": "Midnight Horror Read",
        "m_afternoon_reader": "Afternoon HQ Reading",
        "m_golden_hour_reader": "Golden Hour Reading",
        "m_dawn_reader": "Dawn Reading Scout",
        "m_twilight_reader": "Twilight Zone Reading",
        "m_midnight_start": "Midnight Reading Mission",
        "m_weekend_binge_hours": "Weekend Binge Reading",
        "m_late_night_regular": "Late Night Regular Reader",
        "m_sunrise_reader": "Sunrise Over Britannia Reader",
        "m_every_day_of_week": "Every Day Reading Duty",
        "m_monthly_hours": "Monthly Reading Hours",
        "m_bedtime_reader": "Bedtime HQ Reader",
        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Majiko Art Appreciator",
        "m_webtoon_reader": "Webtoon Intelligence",
        "m_full_color": "Full Color Manuscript",
        "m_doujin_reader": "Underground Doujin Reader",
        "m_anthology_reader": "Anthology Collection Reader",
        "m_adaptation_reader": "Adaptation Study Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Comedy Shorts",
        "m_oneshot_reader": "Oneshot Mission Reader",
        "m_format_variety": "Format Tactical Variety",
        "m_light_novel_reader": "Light Novel Intel Reader",
        "m_novel_reader": "Novel Archive Reader",
        "m_visual_storyteller": "Visual Battle Narrator",
        "m_colored_classic": "Colored Classic Manuscript",
        "m_webcomic_fan": "Webcomic Underground Fan",
        "m_manga_to_anime": "Manga to Anime Comparison",
        "m_seinen_reader": "Seinen Political Reader",
        "m_josei_reader": "Josei Perspective Reader",
        "m_award_winning_art": "Medal-Winning Artwork",
        "m_debut_work": "Debut Manuscript",
        "m_vertical_scroll": "Vertical Scroll Intel",
        "m_traditional_format": "Traditional Format Reader",
        "m_cross_media": "Cross-Media Intelligence",
        "m_spinoff_reader": "Spinoff Mission Reader",
        "m_remake_reader": "Remake Reading Assignment",
        "m_collaboration_reader": "Joint Operation Manuscript",
        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Geass Reading Streak",
        "m_mega_streak": "Mega Reading Campaign Streak",
        "m_weekly_warrior": "Weekly Warrior Reader",
        "m_monthly_reader": "Monthly Black Knight Reader",
        "m_comeback": "Reader's Return from Exile",
        "m_weekend_streak": "Weekend Reading Streak",
        "m_no_zero_days": "No Zero Reading Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Regimen Formed",
        "m_consistent_pace": "Consistent Reading Advance",
        "m_year_long": "Year-Long Reading Campaign",
        "m_double_streak": "Double Reading Streak",
        "m_streak_recovery": "Reading Recovery from Betrayal",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Reading Campaign",
        "m_summer_streak": "Summer Reading Offensive",
        "m_morning_streak": "Morning Reading Formation",
        "m_night_streak": "Night Reading Patrol",
        "m_unbreakable": "Unbreakable Reading Will",
        "m_eternal_flame": "Eternal Flame of Zero",
        "m_chapter_a_day": "Chapter a Day Discipline",
        "m_genre_streak": "Genre Reading Streak",
        "m_completion_streak": "Completion Reading Chain",
        "m_rating_streak": "Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Dedication Streak",
        "m_perfect_week_manga": "Perfect Reading Week",
        "m_diverse_streak": "Diverse Reading Streak",
        // ── MANGA SCORING ──
        "m_critic": "Zero Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Manuscript",
        "m_harsh_critic": "Lelouch's Reading Standards",
        "m_fair_judge": "Schneizel's Review",
        "m_generous_spirit": "Generous Reader Spirit",
        "m_score_all": "Full Manuscript Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Reading Opinion",
        "m_consistent_scorer": "Consistent Manuscript Scorer",
        "m_score_sniper": "Precision Score Sniper",
        "m_evolving_taste": "Evolving Reading Taste",
        "m_bell_curve": "Bell Curve of Scores",
        "m_picky_reader": "Selective Reading Commander",
        "m_100_rated": "Century of Ratings",
        "m_500_rated": "Five Hundred Rating Reports",
        "m_mediocre_majority": "Middle Ground Reader",
        "m_rating_spree": "Rating Barrage",
        "m_score_variance": "Variable Manuscript Scores",
        "m_binge_rater": "Binge Rating Session",
        "m_reread_rerate": "Reread & Re-Rate",
        "m_masterpiece_hunter": "Masterpiece Manuscript Hunter",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimistic Reader",
        "m_score_distributor": "Score Distributor General",
        "m_genre_critic": "Genre Reading Critic",
        "m_mean_above_8": "Elite Reading Average",
        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Reading Vow",
        "m_valentines_read": "Valentine's Reading Bond",
        "m_pi_day": "Pi Day Chapter Count",
        "m_april_fools": "April Fools Chibi Zero",
        "m_international_manga_day": "International Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Solstice Reading",
        "m_tanabata": "Tanabata Reading Wish",
        "m_friday_13th": "Friday 13th Coup Manuscript",
        "m_halloween_read": "Halloween Horror Reading",
        "m_thanksgiving_binge": "Thanksgiving Reading Feast",
        "m_christmas_read": "Midwinter Festival Reading",
        "m_new_years_eve": "New Year's Eve Final Read",
        "m_birthday_read": "Birthday Reading Gift",
        "m_holiday_marathon": "Holiday Reading Marathon",
        "m_independence_day": "Britannian Independence Reading",
        "m_culture_day": "Culture Day Manuscript",
        "m_spring_equinox": "Spring Equinox Reading",
        "m_earth_day": "Earth Day Conservation Read",
        "m_labor_day": "Black Knight Labor Reading",
        "m_winter_solstice": "Winter Solstice Reading",
        "m_manga_birthday": "Manga Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Reader",
        "m_consecutive_holidays": "Consecutive Holiday Reads",
        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Milestone",
        "m_fibonacci": "Fibonacci Chapter Pattern",
        "m_palindrome_day": "Palindrome Reading Day",
        "m_binary_day": "Binary Command Reading",
        "m_full_moon_read": "Full Moon Requiem Read",
        "m_leap_year_read": "Leap Year Reading",
        "m_triple_seven": "Triple Seven Black Knights",
        "m_thousand_complete": "Thousand Manga Victories",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Zero-Level Chapters",
        "m_answer_42": "Answer to Zero's Reading",
        "m_square_number": "Perfect Chessboard Chapters",
        "m_prime_count": "Prime Chapter Count",
        "m_matching_date": "Matching Intel Date",
        "m_century_chapter": "Century Chapter Milestone",
        "m_pi_chapters": "Pi Chapter Calculation",
        "m_synchronicity": "Geass Reading Synchronicity",
        "m_world_record": "World Record Chapter Count",
        "m_genre_clash": "Genre Clash Reading",
        "m_time_traveler": "Code-Immortal Reader",
        "m_double_digits": "Double Digit Milestone",
        "m_one_two_three": "Phases One Two Three",
        "m_lucky_seven": "Seven Knight Chapters",
        "m_exact_hundred_ch": "Exact Hundred Chapters",
        "m_year_match_count": "Year Match Chapter Count",
        "m_chapter_match_date": "Chapter Date Match",
        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Manhwa Format Reader",
        "m_manhua_format": "Manhua Format Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Operative",
        "m_doujin_format": "Doujin Format Reader",
        "m_novel_format": "Novel Format Reader",
        "m_format_master_manga": "Format Master Reader",
        // ── MANGA META ──
        "m_meta_first_unlock": "First Reading Power Unlocked",
        "m_meta_collector": "Reading Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Reading Rank",
        "m_meta_xp_earner": "XP from Reading",
        "m_meta_difficulty_easy": "Easy Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Manuscript Challenge",
        "m_meta_unlock_spree": "Reading Unlock Barrage",
        "m_meta_completionist": "Meta Reading Completionist",
        "m_meta_diverse": "Diverse Reading Portfolio",
        "m_meta_dominator": "Meta Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg:        "#060008",
        primary:   "#8228dc",
        secondary: "#c050ff",
        accent:    "#ff2020",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/code-geass.jpg",
    particleColor: "#8228dc",
    backgroundDim: 0.30,
    backgroundBlur: 30,
    milestoneNames: {
        1:   "Honorary Britannian",
        8:   "Black Knight Recruit",
        18:  "Knight of the Round",
        30:  "Britannian General",
        44:  "Zero",
        58:  "Order of the Black Knights",
        72:  "Knight of Zero",
        86:  "99th Emperor",
        100: "The Zero Requiem",
    },
}
