import { AnimeThemeConfig } from "./types"
import { deathNotePlayerIcons } from "./player-icons"
import {
    GiDeathSkull,
    GiNotebook,
    GiFeather,
    GiChainedHeart,
    GiEyeball,
    GiScales,
    GiMagnifyingGlass,
    GiBrain,
    GiCrown,
    GiPoliceBadge,
    GiReaperScythe,
    GiCandleLight,
    GiSkullCrossedBones,
    GiLockedChest,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const deathNoteTheme: AnimeThemeConfig = {
    id: "death-note",
    displayName: "Death Note",
    description: "The human whose name is written in this notebook shall die — crimson and black gothic palette, shinigami eyes, and the intellectual warfare between Kira and L.",
    fontFamily: "'Creepster', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Creepster&display=swap",
    cssVars: {
        // Brand → deep crimson red gothic palette
        "--color-brand-200": "220 120 120",
        "--color-brand-300": "200 90 90",
        "--color-brand-400": "180 60 60",
        "--color-brand-500": "160 40 40",
        "--color-brand-600": "140 30 30",
        "--color-brand-700": "120 22 22",
        "--color-brand-800": "96 16 16",
        "--color-brand-900": "72 10 10",
        "--color-brand-950": "48 6 6",
        "--brand": "180 30 30",
        // Deep black backgrounds
        "--background": "#040202",
        "--paper": "#0c0606",
        // Warm blood-tinted grays
        "--color-gray-950": "6 2 2",
        "--color-gray-900": "14 8 8",
        "--color-gray-800": "28 16 16",
        "--color-gray-700": "48 28 28",
        "--color-gray-600": "72 44 44",
        "--color-gray-500": "100 64 64",
        "--color-gray-400": "136 96 96",
        "--color-gray-300": "172 132 132",
        "--color-gray-200": "204 172 172",
        "--color-gray-100": "228 208 208",
        "--color-gray-50": "242 232 232",
    },
    sidebarOverrides: {
        "home": { icon: GiDeathSkull, label: "Shinigami Realm" },
        "schedule": { icon: GiNotebook, label: "Kira's Schedule" },
        "manga": { icon: LuBookOpen, label: "Death Notebook" },
        "lists": { icon: GiFeather, label: "Names Written" },
        "discover": { icon: GiMagnifyingGlass, label: "L's Investigation" },
        "torrent-list": { icon: GiChainedHeart, label: "Chain of Judgment" },
        "debrid": { icon: GiSkullCrossedBones, label: "Shinigami Eyes Deal" },
        "unmatched": { icon: GiEyeball, label: "Unidentified Names" },
        "enmasse": { icon: GiReaperScythe, label: "Mass Judgment" },
        "scan-summaries": { icon: TbReportSearch, label: "Task Force Reports" },
        "auto-downloader": { icon: LuRss, label: "Kira Broadcast" },
        "community": { icon: GiScales, label: "Justice Forum" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Shinigami Alerts" },
        "achievements": { icon: GiCrown, label: "God of New World" },
        "theme-manager": { icon: GiCandleLight, label: "Realm Aesthetics" },
        "extensions": { icon: BiExtension, label: "Notebook Rules" },
        "sync": { icon: IoCloudOfflineOutline, label: "Ryuk's Apples" },
        "settings": { icon: GiLockedChest, label: "Hidden Drawer" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Name Written",
        "a_episode_counter": "Names in the Notebook",
        "a_episode_titan": "Titan of Judgment",
        "a_hours_invested": "Hours Plotting Justice",
        "a_time_lord": "Chrono Shinigami",
        "a_anime_collector": "Evidence Collector",
        "a_library_legend": "Legend of the Death Note",
        "a_first_complete": "First Case Closed",
        "a_hundred_club": "Hundred Souls Judged",
        "a_first_day": "The Day Light Found the Notebook",
        "a_first_rating": "First Verdict Rendered",
        "a_ten_thousand_min": "Ten Thousand Minutes of Scheming",
        "a_season_veteran": "Veteran of the Kira Case",
        "a_year_explorer": "Year of the New World Order",
        "a_century_watcher": "Century of Watched Judgments",
        "a_five_hundred_eps": "Five Hundred Rules Memorized",
        "a_thousand_eps": "A Thousand Deaths Recorded",
        "a_watching_ten": "Ten Investigations Running",
        "a_ptw_hoarder": "Backlog of Suspects",
        "a_dropped_honesty": "Dropped the Notebook Honestly",
        "a_five_thousand_eps": "Five Thousand Entries Written",
        "a_ten_completed": "Ten Cases Solved",
        "a_fifty_completed": "Fifty Judgments Passed",
        "a_five_hundred_completed": "Five Hundred Files Archived",
        "a_mean_score_tracker": "Average Intelligence Rating",
        "a_unique_studios": "Unique Crime Labs Visited",
        "a_days_spent_watching": "Days Spent Under Surveillance",
        "a_all_status": "All Suspect Statuses Filed",
        "a_first_favorite": "First Ally in the Shadows",
        "a_favorites_collector": "Inner Circle Collector",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Surveillance Shift",
        "a_marathon_runner": "Marathon of Mental Warfare",
        "a_weekend_warrior": "Weekend Kira Task Force Raid",
        "a_non_stop": "Relentless Pursuit of Kira",
        "a_one_more_episode": "One More Page Before Midnight",
        "a_speed_run": "Speed-Writing Forty Seconds",
        "a_double_feature": "Double Bluff Executed",
        "a_triple_threat": "Triple Agent Scheme",
        "a_five_a_day": "Five Names Before Sundown",
        "a_back_to_back": "Back-to-Back Confrontations",
        "a_seasonal_binge": "Full Arc of Kira's Reign",
        "a_cour_crusher": "Cour Crusher: L vs Light",
        "a_half_day_watch": "Half-Day Stakeout",
        "a_full_day_watch": "Full Day at Investigation HQ",
        "a_power_weekend": "Power Weekend of Deductions",
        "a_binge_king": "God of the Binge World",
        "a_no_sleep": "All-Night Intellectual Duel",
        "a_entire_season": "The Entire Kira Saga",
        "a_seven_day_challenge": "Seven-Day Investigation Sprint",
        "a_hundred_day_binge": "Hundred-Day Manhunt",
        "a_genre_binge": "Cross-Genre Psychological Deep Dive",
        "a_studio_binge": "Madhouse Archive Marathon",
        "a_season_sweep": "Complete Case File Sweep",
        "a_forty_eight_hour": "Forty-Eight Hour Interrogation",
        "a_ep_counter_day": "Daily Evidence Log Counter",
        "a_multi_series_binge": "Multi-Case Investigation",
        "a_midnight_binge": "Midnight Notebook Writing Spree",
        "a_new_year_binge": "New Year New World Surge",

        // ── ANIME GENRES ──
        "a_genre_action": "Kira's Swift Execution",
        "a_genre_adventure": "Journey Through the Shinigami Realm",
        "a_genre_comedy": "Ryuk's Apple Comedy Hour",
        "a_genre_drama": "The Tragedy of Light Yagami",
        "a_genre_fantasy": "Realm of the Death Gods",
        "a_genre_horror": "Horror of the Shinigami Eyes",
        "a_genre_mystery": "L's Greatest Mystery",
        "a_genre_romance": "Misa's Undying Devotion",
        "a_genre_scifi": "Shinigami Technology Beyond Science",
        "a_genre_sol": "Life as a Model Student",
        "a_genre_sports": "Tennis Match of Wits",
        "a_genre_supernatural": "Supernatural Notebook Powers",
        "a_genre_thriller": "Cat-and-Mouse Thriller",
        "a_genre_mecha": "Mechanical Surveillance Systems",
        "a_genre_music": "Requiem for the Condemned",
        "a_genre_psychological": "Psychological Warfare Master",
        "a_genre_ecchi": "Misa's Magazine Photoshoot",
        "a_genre_mahou_shoujo": "Magical Shinigami Girl",
        "a_tag_isekai": "Trapped Between Two Worlds",
        "a_tag_harem": "Light's Unwitting Pawns",
        "a_tag_bl": "Brotherhood of Detectives",
        "a_tag_gl": "Sisterhood of Justice",
        "a_tag_historical": "History of the Death Note",
        "a_tag_military": "Task Force Military Operation",
        "a_tag_school": "To-Oh University Prodigy",
        "a_tag_martial_arts": "Capoeira at the Rooftop",
        "a_tag_vampire": "Immortal Shinigami Lifespan",
        "a_tag_samurai": "Samurai Code of Justice",
        "a_tag_space": "Shinigami Realm in the Void",
        "a_tag_parody": "Chibi Ryuk Specials",
        "a_tag_idol": "Misa Amane: Idol & Second Kira",
        "a_tag_post_apocalyptic": "World After Kira's Reign",
        "a_tag_cyberpunk": "Digital Surveillance Dystopia",
        "a_tag_shounen": "Battle of Prodigies",
        "a_tag_seinen": "Mature Moral Philosophy",
        "a_tag_shoujo": "Misa's Perspective",
        "a_tag_josei": "Naomi Misora's Investigation",
        "a_tag_survival": "Survival Under Kira's Rule",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Names Accounted For",
        "a_mega_completionist": "Complete Death Note Chronicle",
        "a_completion_rate_50": "Halfway Through the Investigation",
        "a_completion_rate_75": "Closing In on Kira",
        "a_completion_rate_90": "Final Confrontation Imminent",
        "a_no_drop": "No Case Left Unsolved",
        "a_long_runner_complete": "Long Investigation Concluded",
        "a_sequel_chain": "Sequel: Near's Era Begins",
        "a_clean_list": "Clean Evidence Board",
        "a_from_ptw": "Case Pulled from Cold Storage",
        "a_rewatch_master": "Reexamining the Evidence",
        "a_short_complete": "Quick Judgment Delivered",
        "a_same_day_start_finish": "Same-Day Trial and Execution",
        "a_revival": "Resurrection Protocol: Rem's Sacrifice",
        "a_zero_to_hero": "From Student to God of New World",
        "a_five_genre_complete": "Five Methods of Justice Mastered",
        "a_full_franchise": "Full Death Note Universe",
        "a_batch_complete": "Batch Judgment Delivered",
        "a_paused_to_done": "Returned After Case Hiatus",
        "a_completion_spree": "Execution Spree",
        "a_multi_rewatch": "Multi-Viewing Evidence Review",
        "a_dropped_recovery": "Cold Case Reopened",
        "a_ten_perfect_scores": "Ten Flawless Executions",
        "a_seasonal_clear": "Seasonal Case Closure",
        "a_complete_genre_span": "Well-Rounded Investigator",
        "a_monthly_completions": "Monthly Case File Report",
        "a_yearly_completions": "Annual Kira Task Force Review",
        "a_rapid_complete": "Rapid-Fire Judgment",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Servant of Justice",
        "a_studio_devotee": "Madhouse Studio Devotee",
        "a_rewatcher": "Re-Reading the Notebook",
        "a_triple_rewatch": "Triple Analysis of the Case",
        "a_annual_tradition": "Annual Death Note Rewatch",
        "a_director_fan": "Araki's Directorial Vision",
        "a_voice_actor_fan": "Voice of Light and L",
        "a_ost_lover": "The World and Low of Solipsism",
        "a_source_reader": "Ohba & Obata Original Manga",
        "a_waiting_weekly": "Weekly Episode Anticipation",
        "a_childhood_revisit": "Return to Kira's Origin",
        "a_saga_tracker": "Death Note Saga Tracker",
        "a_genre_loyalty": "Psychological Thriller Loyalty",
        "a_decade_watcher": "Decade of the Death Note",
        "a_adaptation_hunter": "Live-Action & Film Adaptation",
        "a_original_anime_fan": "Original 2006 Broadcast Viewer",
        "a_long_commitment": "Long-Term Kira Investigation",
        "a_perfect_attendance": "Perfect Attendance at HQ",
        "a_favorite_studio_5": "Five Studio Case Files",
        "a_complete_catalog": "Complete Evidence Archive",
        "a_franchise_collector": "Death Note Universe Collector",
        "a_airing_follower": "Following the Live Broadcast",
        "a_genre_master": "Genre Mastery: Psychological",
        "a_staff_follower": "Investigation Team Dossier",
        "a_multi_season_fan": "Multi-Arc Veteran Viewer",
        "a_format_diversity": "Diverse Media Judgment",
        "a_year_dedication": "Year of the God Complex",
        "a_season_dedication": "Season of Calculated Moves",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Genre Investigation Branch",
        "a_studio_hopper": "Cross-Department Transfer",
        "a_tag_explorer": "Tag Reconnaissance: Classified",
        "a_decade_hopper": "Evidence Across Eras",
        "a_hidden_gem": "Hidden Clue Discovered",
        "a_popular_taste": "Popular Among Investigators",
        "a_retro_appreciator": "Classic Case File Appreciator",
        "a_modern_viewer": "Modern Kira Successors",
        "a_cross_demographic": "Cross-World Intelligence",
        "a_underdog_fan": "Underdog Detective Spirit",
        "a_variety_week": "Week of Varied Interrogations",
        "a_foreign_cinema": "International Kira Cases",
        "a_classic_connoisseur": "Classic Crime Connoisseur",
        "a_every_season": "Every Season Under Surveillance",
        "a_award_winner": "Case of the Year Award",
        "a_niche_explorer": "Hidden Case File Explorer",
        "a_global_anime": "Global Kira Phenomenon",
        "a_cult_classic": "Cult Classic Notebook",
        "a_random_pick": "Random Name in the Notebook",
        "a_new_genre_month": "New Lead Every Month",
        "a_seasonal_completionist": "Seasonal Investigation Complete",
        "a_unpopular_opinion": "Unpopular Verdict Rendered",
        "a_top_rated_viewer": "Top-Ranked Intelligence Analyst",
        "a_source_variety": "Source Material Cross-Check",
        "a_low_score_brave": "Brave Dive into Red Territory",
        "a_upcoming_watcher": "Upcoming Case Preview",
        "a_short_series_explorer": "Short Case File Explorer",
        "a_long_series_explorer": "Long Investigation Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Midnight Notebook Entry",
        "a_early_bird": "Early Morning Deduction",
        "a_lunch_break": "Lunch Break at Task Force HQ",
        "a_golden_hour": "Golden Hour Confession",
        "a_four_am_club": "4 AM Death Note Writing",
        "a_witching_hour": "Witching Hour: Shinigami Visit",
        "a_new_year_watch": "New Year's Divine Judgment",
        "a_midnight_premiere": "Midnight Case Premiere",
        "a_all_hours": "All Hours Under L's Watch",
        "a_dawn_warrior": "Dawn of a New World",
        "a_afternoon_delight": "Afternoon Potato Chip Moment",
        "a_prime_time": "Prime Time: Kira Broadcast",
        "a_workday_watcher": "On-Duty Task Force Member",
        "a_sunday_marathon": "Sunday Case Marathon",
        "a_rainy_day": "Rainy Day Reflection",
        "a_morning_routine": "Morning Routine: Perfect Student",
        "a_night_shift": "Night Shift Surveillance",
        "a_twilight_zone": "Twilight Between Good and Evil",
        "a_seasonal_premier": "Season Premiere: New Kira",
        "a_clock_collector": "Shinigami Clock Collector",
        "a_weekend_binge_hours": "Weekend Interrogation Hours",
        "a_late_night_regular": "Late Night Regular at HQ",
        "a_sunrise_watcher": "Sunrise Over the Crime Scene",
        "a_holiday_watcher": "Holiday Under Surveillance",
        "a_every_day_of_week": "Every Day a Judgment Day",
        "a_monthly_hours": "Monthly Investigation Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Task Force Assembly",
        "a_party_host": "Task Force Leader Assembled",
        "a_social_butterfly": "Social Manipulator",
        "a_group_binge": "Task Force Watch Party",
        "a_party_regular": "Regular at Headquarters",
        "a_sync_viewer": "Synchronized Deduction",
        "a_commentator": "Matsuda's Commentary",
        "a_party_marathon": "Investigation Watch Marathon",
        "a_full_house": "Full Task Force Assembled",
        "a_community_pillar": "Pillar of the Investigation",
        "a_watch_party_streak": "Consecutive Briefing Streak",
        "a_diverse_party": "Diverse Task Force Composition",
        "a_late_night_party": "Late Night Emergency Briefing",
        "a_party_veteran": "Veteran Task Force Leader",
        "a_genre_party": "Cross-Department Briefing",
        "a_weekly_party": "Weekly Strategy Meeting",
        "a_silent_viewer": "Silent Observer: Near's Method",
        "a_recommendation_giver": "Case Recommendation Filed",
        "a_party_completionist": "Social Manipulation Complete",
        "a_social_scorer": "Social Standing Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number of Deaths",
        "a_fibonacci": "Fibonacci of Criminal Patterns",
        "a_palindrome_day": "Palindrome Date in the Notebook",
        "a_binary_day": "Binary Code Cipher Day",
        "a_full_moon": "Full Moon Shinigami Appearance",
        "a_leap_year": "Leap Year Judgment",
        "a_time_traveler": "Manipulating the Timeline of Death",
        "a_genre_clash": "Clash of Intellects",
        "a_triple_seven": "Triple Seven Lucky Break",
        "a_thousand_complete": "A Thousand Verdicts Passed",
        "a_pi_episodes": "Pi Calculation: L's Method",
        "a_synchronicity": "Synchronicity of Deaths",
        "a_world_record": "World Record: Most Names Written",
        "a_nice": "Nice Kill Count",
        "a_power_level": "Power Level: Shinigami King",
        "a_answer_42": "The Answer to L's Riddle",
        "a_square_number": "Perfect Square of Justice",
        "a_prime_count": "Prime Number of Suspects",
        "a_matching_date": "Matching Death Date",
        "a_century_episode": "Century Episode Evidence File",
        "a_double_digits": "Double Digit Body Count",
        "a_one_two_three": "Rules One Two Three",
        "a_lucky_seven": "Lucky Seven Escape",
        "a_all_tens": "All Tens: Perfect Crime",
        "a_exact_hundred_eps": "Exactly One Hundred Case Files",
        "a_year_match_count": "Year Match Death Toll",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "NHN Broadcast Viewer",
        "a_movie_buff": "Death Note Movie Mission",
        "a_ova_hunter": "Relight OVA Hunter",
        "a_ona_explorer": "Online Special Explorer",
        "a_special_watcher": "Director's Cut Special",
        "a_short_king": "Short One-Shot Side Case",
        "a_variety_pack": "All-Format Evidence Pack",
        "a_film_festival": "Death Note Film Festival",
        "a_music_video": "Opening Theme: The World",
        "a_tv_short": "Quick Deduction Clip",
        "a_movie_marathon": "Live-Action Movie Marathon",
        "a_double_length": "Double-Length Confrontation",
        "a_anthology": "Death Note Anthology Cases",
        "a_mini_series": "Mini Investigation Series",
        "a_theatrical": "Theatrical Premiere Screening",
        "a_format_master": "Format Master Investigator",
        "a_long_movie": "Feature-Length Final Judgment",
        "a_back_catalog": "Case Archive Catalog",
        "a_cm_watcher": "Commercial Break Buffer",
        "a_pv_collector": "Preview Trailer Evidence",
        "a_format_balance": "Balanced Case Formats",
        "a_episodic_master": "Episodic Case Master",
        "a_sequel_movie": "Sequel: L Change the WorLd",
        "a_recap_watcher": "Recap Briefing Viewer",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Notebook Entry Streak",
        "a_mega_streak": "Mega Judgment Streak",
        "a_weekly_warrior": "Weekly Task Force Duty",
        "a_monthly_watcher": "Monthly Surveillance Report",
        "a_comeback": "Return from the Shadows",
        "a_weekend_streak": "Weekend Stakeout Streak",
        "a_no_zero_days": "No Zero Days: Always Judging",
        "a_iron_will": "Iron Will of Kira",
        "a_habit_formed": "Habit of Writing Names",
        "a_consistent_pace": "Consistent Pace of Justice",
        "a_year_long": "Year-Long Cat-and-Mouse Game",
        "a_double_streak": "Double Streak of Deductions",
        "a_streak_recovery": "Case Recovered from Cold",
        "a_daily_minimum": "Daily Minimum: One Name",
        "a_winter_streak": "Winter Surveillance Streak",
        "a_summer_streak": "Summer Investigation Streak",
        "a_morning_streak": "Morning Deduction Streak",
        "a_night_streak": "Night Shift Streak",
        "a_unbreakable": "Unbreakable Resolve of L",
        "a_eternal_flame": "Eternal Flame of Justice",
        "a_completion_streak": "Case Completion Chain",
        "a_rating_streak": "Verdict Streak Filed",
        "a_multi_ep_streak": "Multi-Episode Arc Analysis",
        "a_genre_streak": "Genre Investigation Streak",
        "a_studio_streak": "Studio Loyalty to Madhouse",
        "a_perfect_week": "Perfect Week of Deductions",

        // ── ANIME SCORING ──
        "a_critic": "Death Note Critic's Eye",
        "a_perfect_ten": "Perfect 10: Flawless Plan",
        "a_harsh_critic": "L's Harsh Assessment",
        "a_fair_judge": "Soichiro's Fair Judgment",
        "a_generous_spirit": "Matsuda's Generous Spirit",
        "a_score_all": "Full Case Evaluation",
        "a_wide_range": "Wide Range of Verdicts",
        "a_controversial": "Controversial: Was Kira Right?",
        "a_consistent_scorer": "Consistent Verdict Issuer",
        "a_score_sniper": "Precision Score: Near's Deduction",
        "a_evolving_taste": "Evolving Sense of Justice",
        "a_bell_curve": "Bell Curve of Criminal Data",
        "a_picky_watcher": "Selective Evidence Reviewer",
        "a_100_rated": "Century of Verdicts Issued",
        "a_500_rated": "Five Hundred Case Reviews",
        "a_mediocre_majority": "Average Suspect Rating",
        "a_rating_spree": "Verdict Delivery Spree",
        "a_score_variance": "Variable Judgment Scores",
        "a_masterpiece_hunter": "Masterpiece Crime Hunter",
        "a_contrarian": "Contrarian: Defending Kira",
        "a_optimist": "Optimist Like Matsuda",
        "a_score_distributor": "Score Distributor: Task Force",
        "a_genre_critic": "Genre Critic: Psychological",
        "a_mean_above_8": "Elite Intelligence Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Resolution: New World",
        "a_valentines_weeb": "Valentine's: Misa's Love Letter",
        "a_pi_day": "Pi Day: L's Calculations",
        "a_april_fools": "April Fools: Ryuk's Prank",
        "a_international_anime_day": "International Justice Day",
        "a_star_wars_day": "Lightsaber of Judgment Day",
        "a_summer_solstice": "Summer Solstice: Longest Day",
        "a_tanabata": "Tanabata Wish for Justice",
        "a_friday_13th": "Friday 13th: Unlucky Name",
        "a_halloween_spirit": "Halloween: Shinigami Festival",
        "a_thanksgiving_binge": "Thanksgiving: L's Cake Feast",
        "a_christmas_special": "Christmas Eve Confrontation",
        "a_new_years_eve": "New Year's Eve Final Judgment",
        "a_birthday_watch": "Birthday: The Day Light Was Born",
        "a_holiday_marathon": "Holiday Investigation Marathon",
        "a_independence_day": "Independence from Moral Chains",
        "a_culture_day": "Culture Day: To-Oh Festival",
        "a_spring_equinox": "Spring Equinox: Balance of Good and Evil",
        "a_earth_day": "Earth Day: Cleansing the World",
        "a_labor_day": "Labor Day: Task Force Off-Duty",
        "a_winter_solstice": "Winter Solstice: Darkest Day",
        "a_anime_birthday": "Death Note Anniversary",
        "a_every_holiday": "Every Holiday Under Judgment",
        "a_consecutive_holidays": "Consecutive Holiday Entries",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Rule Discovered",
        "a_meta_collector": "Notebook Rule Collector",
        "a_meta_category_starter": "Investigation Branch Opened",
        "a_meta_tier_climber": "Rank Promotion: Task Force",
        "a_meta_tier_max": "Maximum Clearance: L's Successor",
        "a_meta_xp_earner": "XP: Intelligence Points Earned",
        "a_meta_difficulty_easy": "Easy Case: Petty Criminal",
        "a_meta_difficulty_hard": "Legendary: Outsmarting L",
        "a_meta_unlock_spree": "Rule Discovery Spree",
        "a_meta_completionist": "Meta Completionist: All Rules Known",
        "a_meta_diverse": "Diverse Investigation Portfolio",
        "a_meta_dominator": "God of the New World",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page of the Death Note",
        "m_chapter_counter": "Pages Filled with Names",
        "m_chapter_titan": "Titan Chapter: The Final Showdown",
        "m_reading_hours": "Hours Studying Criminal Records",
        "m_reading_time_lord": "Total Concentration: Reading the Rules",
        "m_manga_collector": "Death Note Manga Collector",
        "m_library_legend": "Legend of Ohba & Obata's Work",
        "m_first_complete": "First Manga Volume Completed",
        "m_hundred_club": "Hundred Chapter Reading Club",
        "m_first_day": "First Day Reading the Notebook",
        "m_first_rating": "First Manga Verdict",
        "m_ten_thousand_pages": "Ten Thousand Pages of Evidence",
        "m_volume_collector": "Volume Evidence Stockpile",
        "m_year_explorer": "Year of Manga Investigation",
        "m_century_reader": "Century-Chapter Case File",
        "m_five_hundred_ch": "Five Hundred Chapters of Judgment",
        "m_thousand_ch": "Thousand Chapters Archived",
        "m_reading_ten": "Ten Manga Under Investigation",
        "m_ptr_hoarder": "Reading Backlog of Suspects",
        "m_dropped_honesty": "Honestly Dropped the Case",
        "m_season_reader": "Seasonal Archive Reader",
        "m_active_reader": "Active Field Investigator",
        "m_five_thousand_ch": "Five Thousand Chapters Reviewed",
        "m_ten_completed": "Ten Manga Cases Closed",
        "m_fifty_completed": "Fifty Manga Verdicts",
        "m_five_hundred_completed": "Five Hundred Manga Files Done",
        "m_mean_score_tracker": "Average Reading Intelligence",
        "m_unique_authors": "Unique Authors Investigated",
        "m_all_status": "All Reading Statuses Cataloged",
        "m_first_favorite": "First Favorite: L or Light?",
        "m_favorites_collector": "Favorites: Inner Circle",
        "m_days_spent_reading": "Days Spent in the Archives",

        // ── MANGA BINGE ──
        "m_binge_reader": "Non-Stop Case File Reading",
        "m_marathon_reader": "Marathon Reading Interrogation",
        "m_weekend_reader": "Weekend Evidence Review",
        "m_non_stop_reading": "Relentless Page Investigation",
        "m_one_more_chapter": "One More Chapter: Can't Stop",
        "m_speed_read": "Speed-Reading Criminal Files",
        "m_double_story": "Double Agent Story Read",
        "m_triple_read": "Triple Reading Analysis",
        "m_five_a_day": "Five Reads Before Curfew",
        "m_chapter_chain": "Chapter Chain of Evidence",
        "m_volume_binge": "Volume Binge at the Archives",
        "m_power_reader": "Power Reader: Task Force Level",
        "m_half_day_read": "Half-Day Investigation Read",
        "m_full_day_read": "Full-Day Evidence Marathon",
        "m_power_weekend": "Power Weekend Deductions",
        "m_binge_king": "King of the Reading Realm",
        "m_no_sleep_read": "All-Night Reading Vigil",
        "m_full_series_rush": "Full Series Speed Investigation",
        "m_seven_day_challenge": "Seven-Day Reading Challenge",
        "m_hundred_day_read": "Hundred-Day Reading Manhunt",
        "m_volume_rush": "Volume Rush Through Evidence",
        "m_series_sweep": "Complete Series Investigation",
        "m_genre_binge": "Cross-Genre Evidence Dive",
        "m_author_binge": "Ohba & Obata Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Evidence Count",
        "m_multi_series_binge": "Multi-Series Investigation",
        "m_midnight_binge": "Midnight Reading Session",
        "m_new_year_binge": "New Year's Reading Purge",
        "m_forty_eight_hour": "Forty-Eight Hour Readathon",
        "m_oneshot_binge": "One-Shot Evidence Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action: Kira's Swift Pen",
        "m_genre_adventure": "Adventure Through Dark Pages",
        "m_genre_comedy": "Comedy: Ryuk's Antics",
        "m_genre_drama": "Drama: Light's Descent",
        "m_genre_fantasy": "Fantasy: Shinigami Lore",
        "m_genre_horror": "Horror: Eyes of the Death God",
        "m_genre_mystery": "Mystery: Who Is Kira?",
        "m_genre_romance": "Romance: Misa's Devotion",
        "m_genre_scifi": "Sci-Fi: Notebook Mechanics",
        "m_genre_sol": "Slice of Life: Student Days",
        "m_genre_sports": "Sports: Mental Athletics",
        "m_genre_supernatural": "Supernatural: Death God Rules",
        "m_genre_thriller": "Thriller: Psychological Warfare",
        "m_genre_psychological": "Psychological: Mind Games",
        "m_genre_isekai": "Isekai: Between Realms",
        "m_genre_shounen": "Shounen: Battle of Intellects",
        "m_genre_ecchi": "Misa's Photoshoot Manga",
        "m_genre_mahou_shoujo": "Magical Shinigami Manga",
        "m_genre_mecha": "Mechanical Surveillance Manga",
        "m_genre_music": "Musical Score: L's Theme",
        "m_tag_isekai_new": "New Realm Investigation",
        "m_tag_harem": "Light's Pawns Manga",
        "m_tag_bl": "Brotherhood of Justice Manga",
        "m_tag_gl": "Sisterhood of Detectives",
        "m_tag_historical": "History of the Notebook",
        "m_tag_military": "Task Force Military Ops Manga",
        "m_tag_school": "To-Oh Academy Manga",
        "m_tag_martial_arts": "Martial Arts of Deduction",
        "m_tag_vampire": "Immortal Shinigami Manga",
        "m_tag_samurai": "Samurai's Code Manga",
        "m_tag_space": "Void of the Shinigami Realm",
        "m_tag_parody": "Chibi Death Note Manga",
        "m_tag_idol": "Misa Amane Idol Manga",
        "m_tag_post_apocalyptic": "Post-Kira World Manga",
        "m_tag_cyberpunk": "Cyberpunk Surveillance Manga",
        "m_tag_shoujo": "Misa's Diary Manga",
        "m_tag_survival": "Survival Under Judgment",
        "m_tag_cooking": "L's Sweets Recipe Manga",
        "m_tag_medical": "Forensic Evidence Manga",
        "m_tag_villainess": "Villainess Redemption: Rem",

        // ── MANGA COMPLETION ──
        "m_completionist": "All Manga Cases Closed",
        "m_mega_completionist": "Supreme Archive Investigator",
        "m_completion_rate_50": "Halfway Through the Case Files",
        "m_completion_rate_75": "Seventy-Five Percent Solved",
        "m_completion_rate_90": "Final Manga Verdict Imminent",
        "m_no_drop": "No Manga Case Abandoned",
        "m_long_runner_complete": "Long Manga Investigation Done",
        "m_sequel_chain": "Sequel Reading: Near's Chapter",
        "m_clean_list": "Clean Reading Evidence Board",
        "m_from_ptr": "Case Accepted from Backlog",
        "m_reread_master": "Reexamining the Manga Evidence",
        "m_oneshot_complete": "One-Shot Verdict Delivered",
        "m_same_day_start_finish": "Same-Day Manga Speed Trial",
        "m_revival": "Revived Interest in the Case",
        "m_zero_to_hundred": "Zero to Hundred Chapters",
        "m_five_genre_complete": "Five Genre Cases Solved",
        "m_full_collection": "Full Death Note Manga Set",
        "m_batch_complete": "Batch Evidence Processing",
        "m_paused_to_done": "Cold Case Manga Completed",
        "m_completion_spree": "Manga Judgment Spree",
        "m_format_completionist": "Format Completion: All Types",
        "m_catch_up": "Caught Up with Serialization",
        "m_multi_reread": "Multi-Reread Deep Analysis",
        "m_dropped_recovery": "Recovered Dropped Manga Case",
        "m_ten_perfect_scores": "Ten Perfect Manga Verdicts",
        "m_complete_genre_span": "All-Around Manga Investigator",
        "m_monthly_completions": "Monthly Manga Case Reports",
        "m_yearly_completions": "Annual Manga Review Board",
        "m_rapid_complete": "Rapid Manga Judgment",
        "m_author_complete": "Ohba's Complete Portfolio",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader of Dark Pages",
        "m_mangaka_lover": "Ohba & Obata Devotee",
        "m_rereader": "Death Note Manga Rereader",
        "m_triple_reread": "Triple Analysis Reread",
        "m_annual_reread": "Annual Death Note Reread",
        "m_publisher_fan": "Shueisha Publisher Fan",
        "m_artist_fan": "Obata's Artwork Devotee",
        "m_adaptation_compare": "Manga vs Anime Comparison",
        "m_source_material_fan": "Original Manga Source Fan",
        "m_waiting_weekly": "Weekly Chapter Anticipation",
        "m_classic_reader": "Classic Psychological Manga",
        "m_saga_reader": "Death Note Saga Reader",
        "m_genre_loyalty": "Genre Loyalty: Dark Thriller",
        "m_decade_reader": "Decade of Reading Death Note",
        "m_ln_adaptation": "Light Novel Adaptation Reader",
        "m_original_work": "Original Manuscript Study",
        "m_long_commitment": "Long-Term Reading Commitment",
        "m_up_to_date": "Up-to-Date with All Releases",
        "m_favorite_mangaka": "Favorite Mangaka: Obata",
        "m_complete_portfolio": "Complete Author Portfolio",
        "m_franchise_collector": "Death Note Franchise Collector",
        "m_serialization_follower": "Serialization Follower",
        "m_genre_master": "Genre Mastery: Psychological",
        "m_multi_series_author": "Multi-Series Ohba Reader",
        "m_format_diversity": "Diverse Reading Formats",
        "m_year_dedication": "Year of Dark Pages",
        "m_ongoing_follower": "Ongoing Series Pursuer",
        "m_genre_loyalty_50": "Fifty Genre Chapters Read",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Investigation Explorer",
        "m_publisher_hopper": "Publisher Transfer Reader",
        "m_tag_explorer": "Tag Reconnaissance: Evidence",
        "m_decade_hopper": "Era-Hopping Reader",
        "m_hidden_gem": "Hidden Gem: Overlooked Clue",
        "m_popular_taste": "Popular Among Investigators",
        "m_retro_reader": "Retro Case File Reader",
        "m_modern_reader": "Modern Successor Reader",
        "m_cross_demographic": "Cross-World Intelligence Reader",
        "m_underdog_fan": "Underdog Detective Reader",
        "m_variety_week": "Varied Investigation Week",
        "m_manhwa_reader": "Manhwa Evidence Reader",
        "m_manhua_reader": "Manhua Evidence Reader",
        "m_classic_connoisseur": "Classic Crime Manga Expert",
        "m_award_winner": "Award-Winning Case File",
        "m_niche_explorer": "Niche Case Explorer",
        "m_world_manga": "International Manga Cases",
        "m_cult_classic": "Cult Classic Dark Manga",
        "m_random_pick": "Random Case Assignment",
        "m_new_genre_month": "New Genre Lead Monthly",
        "m_year_completionist": "Year-End Manga Completionist",
        "m_unpopular_opinion": "Unpopular Verdict: Manga",
        "m_top_rated_reader": "Top-Rated Manga Analyst",
        "m_source_variety": "Source Material Cross-Reference",
        "m_low_score_brave": "Brave Reader in Red Zone",
        "m_short_manga_explorer": "Short Case File Reader",
        "m_long_manga_explorer": "Long Investigation Reader",
        "m_serialization_explorer": "Serialization Archive Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Archive Reader",
        "m_early_bird": "Early Morning Evidence Review",
        "m_lunch_reader": "Lunch Break Case File",
        "m_commute_reader": "Commute to HQ Reader",
        "m_four_am_club": "4 AM Notebook Reading",
        "m_new_year_read": "New Year's Reading Oath",
        "m_all_hours": "All-Hours Evidence Reader",
        "m_prime_time_reader": "Prime Time Manga Reading",
        "m_workday_reader": "On-Duty Reading Session",
        "m_sunday_read": "Sunday Investigation Read",
        "m_morning_routine": "Morning Routine: Study & Read",
        "m_night_shift_reader": "Night Shift Archive Reader",
        "m_seasonal_premier_read": "Seasonal Premiere Read",
        "m_clock_collector": "Shinigami Time Collector",
        "m_late_night_horror": "Late Night Horror Read",
        "m_afternoon_reader": "Afternoon Evidence Review",
        "m_golden_hour_reader": "Golden Hour Reading Session",
        "m_dawn_reader": "Dawn of the Reading Day",
        "m_twilight_reader": "Twilight Between Pages",
        "m_midnight_start": "Midnight Reading Startup",
        "m_weekend_binge_hours": "Weekend Reading Stakeout",
        "m_late_night_regular": "Late Night Regular Reader",
        "m_sunrise_reader": "Sunrise Evidence Reader",
        "m_every_day_of_week": "Every Day a Reader's Duty",
        "m_monthly_hours": "Monthly Reading Hours Filed",
        "m_bedtime_reader": "Bedtime Notebook Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Obata's Masterful Art",
        "m_webtoon_reader": "Webtoon Case Reader",
        "m_full_color": "Full Color Death Note",
        "m_doujin_reader": "Death Note Doujin Reader",
        "m_anthology_reader": "Anthology Evidence Collection",
        "m_adaptation_reader": "Adaptation Case Comparison",
        "m_longstrip_reader": "Vertical Scroll Investigation",
        "m_4koma_reader": "4-Koma: Chibi Shinigami",
        "m_oneshot_reader": "One-Shot Case Read",
        "m_format_variety": "Format Variety Investigator",
        "m_light_novel_reader": "Death Note Light Novel",
        "m_novel_reader": "L Change the WorLd Novel",
        "m_visual_storyteller": "Visual Storytelling Analyst",
        "m_colored_classic": "Colored Classic Death Note",
        "m_webcomic_fan": "Webcomic Fan Investigator",
        "m_manga_to_anime": "Manga to Anime Case Compare",
        "m_seinen_reader": "Seinen Dark Reader",
        "m_josei_reader": "Josei Perspective Reader",
        "m_award_winning_art": "Award-Winning Obata Artwork",
        "m_debut_work": "Debut Manuscript: First Draft",
        "m_vertical_scroll": "Vertical Scroll Death Note",
        "m_traditional_format": "Traditional Panel Format",
        "m_cross_media": "Cross-Media Intelligence Report",
        "m_spinoff_reader": "Spinoff: Another Death Note",
        "m_remake_reader": "Remake Case Reader",
        "m_collaboration_reader": "Collaboration Manga Reader",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Reading Entry Streak",
        "m_mega_streak": "Mega Investigation Streak",
        "m_weekly_warrior": "Weekly Warrior Reader",
        "m_monthly_reader": "Monthly Case File Reader",
        "m_comeback": "Reader's Comeback to the Case",
        "m_weekend_streak": "Weekend Reading Streak",
        "m_no_zero_days": "No Zero Reading Days",
        "m_iron_will": "Iron Will: L's Determination",
        "m_habit_formed": "Reading Habit Established",
        "m_consistent_pace": "Consistent Investigation Pace",
        "m_year_long": "Year-Long Reading Campaign",
        "m_double_streak": "Double Reading Streak",
        "m_streak_recovery": "Streak Recovery: Case Reopened",
        "m_daily_minimum": "Daily Minimum Pages Read",
        "m_winter_streak": "Winter Reading Streak",
        "m_summer_streak": "Summer Investigation Streak",
        "m_morning_streak": "Morning Reading Streak",
        "m_night_streak": "Night Shift Reading Streak",
        "m_unbreakable": "Unbreakable Reading Resolve",
        "m_eternal_flame": "Eternal Flame of Knowledge",
        "m_chapter_a_day": "Chapter a Day Investigation",
        "m_genre_streak": "Genre Reading Streak",
        "m_completion_streak": "Completion Reading Chain",
        "m_rating_streak": "Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Reading Streak",
        "m_author_streak": "Ohba Dedication Streak",
        "m_perfect_week_manga": "Perfect Reading Week",
        "m_diverse_streak": "Diverse Investigation Streak",

        // ── MANGA SCORING ──
        "m_critic": "Death Note Manga Critic",
        "m_perfect_ten": "Perfect 10: Flawless Volume",
        "m_harsh_critic": "L's Harsh Manga Standards",
        "m_fair_judge": "Fair Manga Arbiter",
        "m_generous_spirit": "Generous Reading Spirit",
        "m_score_all": "Full Manga Assessment",
        "m_wide_range": "Wide Range Reading Scores",
        "m_controversial": "Controversial Manga Verdict",
        "m_consistent_scorer": "Consistent Manga Scorer",
        "m_score_sniper": "Precision Manga Rating",
        "m_evolving_taste": "Evolving Reader Palate",
        "m_bell_curve": "Bell Curve of Reading Stats",
        "m_picky_reader": "Selective Manga Reader",
        "m_100_rated": "Century of Manga Ratings",
        "m_500_rated": "Five Hundred Manga Reviews",
        "m_mediocre_majority": "Average Manga Rating",
        "m_rating_spree": "Reading Rating Spree",
        "m_score_variance": "Variable Manga Judgments",
        "m_binge_rater": "Binge Rating Session",
        "m_reread_rerate": "Reread & Re-Rate Evidence",
        "m_masterpiece_hunter": "Manga Masterpiece Hunter",
        "m_contrarian": "Contrarian Manga Critic",
        "m_optimist": "Optimist Manga Reader",
        "m_score_distributor": "Score Distribution Protocol",
        "m_genre_critic": "Genre Manga Critic",
        "m_mean_above_8": "Elite Manga Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Manga Resolution",
        "m_valentines_read": "Valentine's: Misa's Chapter",
        "m_pi_day": "Pi Day: L's Sweet Calculation",
        "m_april_fools": "April Fools: Ryuk's Manga Prank",
        "m_international_manga_day": "International Manga Day",
        "m_free_comic_day": "Free Comic: Death Note Sample",
        "m_summer_solstice": "Summer Solstice Reading Event",
        "m_tanabata": "Tanabata Reading Wish",
        "m_friday_13th": "Friday 13th: Dark Reading",
        "m_halloween_read": "Halloween: Shinigami Chapter",
        "m_thanksgiving_binge": "Thanksgiving Reading Feast",
        "m_christmas_read": "Christmas Eve Manga Read",
        "m_new_years_eve": "New Year's Eve Final Page",
        "m_birthday_read": "Birthday Reading Gift",
        "m_holiday_marathon": "Holiday Manga Marathon",
        "m_independence_day": "Independence Day Reading",
        "m_culture_day": "Culture Day Manga Festival",
        "m_spring_equinox": "Spring Equinox Reading",
        "m_earth_day": "Earth Day: Cleanse Through Pages",
        "m_labor_day": "Labor Day Off-Duty Reading",
        "m_winter_solstice": "Winter Solstice Dark Reading",
        "m_manga_birthday": "Death Note Manga Anniversary",
        "m_every_holiday_reader": "Every Holiday Manga Reader",
        "m_consecutive_holidays": "Consecutive Holiday Reading",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number of Chapters",
        "m_fibonacci": "Fibonacci Pattern in Pages",
        "m_palindrome_day": "Palindrome Reading Day",
        "m_binary_day": "Binary Code Reading Day",
        "m_full_moon_read": "Full Moon Shinigami Read",
        "m_leap_year_read": "Leap Year Case File Read",
        "m_triple_seven": "Triple Seven Lucky Chapter",
        "m_thousand_complete": "Thousand Chapters Investigated",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Power Level: Shinigami King",
        "m_answer_42": "The Answer: L's Manga Riddle",
        "m_square_number": "Perfect Square Chapters",
        "m_prime_count": "Prime Number Evidence Count",
        "m_matching_date": "Matching Date in the Notebook",
        "m_century_chapter": "Century Chapter Milestone",
        "m_pi_chapters": "Pi Chapters Calculated",
        "m_synchronicity": "Reading Synchronicity Event",
        "m_world_record": "World Record Chapter Count",
        "m_genre_clash": "Genre Clash Reading",
        "m_time_traveler": "Timeline Manipulation Reading",
        "m_double_digits": "Double Digit Reading Milestone",
        "m_one_two_three": "Rules One Two Three Manga",
        "m_lucky_seven": "Lucky Seven Chapter Break",
        "m_exact_hundred_ch": "Exactly Hundred Chapters Read",
        "m_year_match_count": "Year Match Chapter Count",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Death Note Manga Format",
        "m_manhwa_format": "Manhwa Dark Format",
        "m_manhua_format": "Manhua Dark Format",
        "m_ln_format": "Light Novel: Another Note",
        "m_oneshot_format": "One-Shot Pilot Format",
        "m_doujin_format": "Doujin Archive Format",
        "m_novel_format": "Novel: L Change the WorLd",
        "m_format_master_manga": "Format Master Dark Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Manga Rule Discovered",
        "m_meta_collector": "Manga Badge Collector",
        "m_meta_category_starter": "Reading Category Initiated",
        "m_meta_tier_climber": "Manga Rank Promotion",
        "m_meta_tier_max": "Maximum Reading Clearance",
        "m_meta_xp_earner": "XP from Case File Reading",
        "m_meta_difficulty_easy": "Easy Manga Case",
        "m_meta_difficulty_hard": "Legendary: Outsmarting L's Notes",
        "m_meta_unlock_spree": "Reading Rule Discovery Spree",
        "m_meta_completionist": "Meta Manga Completionist",
        "m_meta_diverse": "Diverse Reading Portfolio",
        "m_meta_dominator": "God of the Manga World",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040202",
        primary: "#b41e1e",
        secondary: "#d02828",
        accent: "#f04040",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "https://w.wallhaven.cc/full/gp/wallhaven-gpk2d7.jpg",
    backgroundDim: 0.28,
    backgroundBlur: 26,
    particleTypes: {
        death_pages: { label: "Death Pages", maxCount: 18, defaultEnabled: true, defaultIntensity: 65 },
        shinigami_feathers: { label: "Shinigami Feathers", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        apple_cores: { label: "Apple Cores", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        red_eyes: { label: "Red Eyes", maxCount: 8, defaultEnabled: true, defaultIntensity: 55 },
        chain_links: { label: "Chain Links", maxCount: 12, defaultEnabled: true, defaultIntensity: 58 },
    },
    playerIconOverrides: deathNotePlayerIcons,
}
