import { AnimeThemeConfig } from "./types"
import { GiMagicPortal, GiCookingPot, GiForest, GiTreasureMap, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiSpellBook, GiHeartKey, GiBroadsword } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const deathMarchTheme: AnimeThemeConfig = {
    id: "death-march",
    displayName: "Death March to the Parallel World Rhapsody",
    description: "Overworked programmer Suzuki Ichirou falls asleep and wakes up in a game world, inadvertently maxing out his stats with a meteor shower spell. Now exploring this new world as a tourist with godlike power, enjoying all the simple pleasures of life.",
    fontFamily: "'Quicksand', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Quicksand:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 202 158",
        "--color-brand-300": "252 168 98",
        "--color-brand-400": "240 130 42",
        "--color-brand-500": "210 96 8",
        "--color-brand-600": "168 66 0",
        "--color-brand-700": "125 42 0",
        "--color-brand-800": "84 24 0",
        "--color-brand-900": "46 10 0",
        "--color-brand-950": "20 4 0",
        "--brand": "210 96 8",
        "--background": "#060300",
        "--paper": "#110700",
        "--color-gray-950": "6 3 0",
        "--color-gray-900": "13 7 0",
        "--color-gray-800": "24 13 2",
        "--color-gray-700": "40 22 6",
        "--color-gray-600": "65 38 14",
        "--color-gray-500": "104 66 30",
        "--color-gray-400": "152 106 60",
        "--color-gray-300": "196 150 98",
        "--color-gray-200": "226 188 140",
        "--color-gray-100": "245 218 182",
        "--color-gray-50": "255 242 222",
    },
    sidebarOverrides: {
        "home": { icon: GiMagicPortal, label: "Death March World" },
        "schedule": { icon: GiAlarmClock, label: "World Schedule" },
        "manga": { icon: LuBookOpen, label: "Quest Log" },
        "lists": { icon: GiFlowerEmblem, label: "Party Registry" },
        "discover": { icon: GiBullseye, label: "New Regions" },
        "torrent-list": { icon: GiSpellBook, label: "Skill Cache" },
        "debrid": { icon: GiTreasureMap, label: "World Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Skills" },
        "enmasse": { icon: GiResize, label: "Party Op" },
        "scan-summaries": { icon: TbReportSearch, label: "World Logs" },
        "auto-downloader": { icon: LuRss, label: "World Feed" },
        "community": { icon: GiCookingPot, label: "World Friends" },
        "achievements": { icon: GiTrophy, label: "World Trophies" },
        "milestones": { icon: LuFlag, label: "Journey Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "World Alerts" },
        "theme-manager": { icon: GiPalette, label: "Cozy Palette" },
        "extensions": { icon: BiExtension, label: "World Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "World Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Satou's Config" },
    },
    achievementNames: {
        "a_first_episode": "World Awakened",
        "a_first_complete": "Region Explored",
        "a_hundred_club": "Hundred Skills",
        "a_time_lord": "World Traveler",
        "a_anime_collector": "World Archive",
        "a_library_legend": "Quest Library",
        "a_binge_king": "World Marathon",
        "a_no_sleep": "Death March",
        "a_marathon_runner": "Satou's Run",
        "a_speed_run": "Max Level Speed",
        "a_completionist": "Full World",
        "a_mega_completionist": "World Master",
        "a_loyal_fan": "Party Member",
        "a_rewatcher": "New Journey",
        "a_decade_watcher": "Decade Traveler",
        "a_genre_action": "World Battle",
        "a_genre_adventure": "World Journey",
        "a_genre_comedy": "Tourist Comedy",
        "a_genre_drama": "None Here",
        "a_genre_fantasy": "Fantasy World",
        "a_genre_horror": "None Here",
        "a_genre_romance": "Harem Party",
        "a_genre_scifi": "Isekai Science",
        "a_genre_supernatural": "World Magic",
        "a_genre_psychological": "Programmer Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "World Critic",
        "a_perfect_ten": "Max Level",
        "a_harsh_critic": "Debug Standard",
        "a_daily_streak": "Daily March",
        "a_mega_streak": "Endless March",
        "a_year_long": "Year in World",
        "a_iron_will": "Satou's Calm",
        "a_hidden_gem": "Hidden Region",
        "a_cult_classic": "Isekai Classic",
        "a_classic_connoisseur": "2014 Fan",
        "a_new_years_resolution": "New Year March",
        "a_christmas_special": "Winter Camp",
        "a_meta_tier_max": "True Traveler",
        "a_meta_completionist": "All Regions",
        "a_sequel_chain": "Satou's Chain",
        "a_zero_to_hero": "Employee to God",
        "a_night_owl": "Night Programmer",
        "a_early_bird": "Dawn March",
        "m_first_chapter": "First Log",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "World Binge",
        "m_completionist": "Full Novel",
        "m_mega_completionist": "March Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Second March",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Party Chapter",
        "m_genre_fantasy": "World Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "None Here",
        "m_genre_scifi": "Code Chapter",
        "m_genre_supernatural": "Magic Chapter",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Debug Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "March Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron March",
        "m_hidden_gem": "Hidden Region",
        "m_cult_classic": "Classic Chapter",
        "m_mangaka_lover": "Ainana Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "March Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "World Art",
        "m_manga_to_anime": "Adapted March",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060300",
        primary: "#d26008",
        secondary: "#a84200",
        accent: "#50c890",
    },
    particleColor: "#f08030",
    backgroundDim: 0.24,
    backgroundBlur: 12,
    particleTypes: {
        golden_sparks: { label: "Cozy Sparks", maxCount: 16, defaultEnabled: true, defaultIntensity: 50 },
        falling_leaves: { label: "Forest Leaves", maxCount: 12, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
        1: "Overworked Coder",
        5: "Isekai Newbie",
        15: "World Tourist",
        30: "Blessed Traveler",
        50: "Legendary Player",
        75: "Max Level",
        100: "Satou",
    },
}
