import { AnimeThemeConfig } from "./types"
import { GiBinoculars, GiMagnifyingGlass, GiSpyglass, GiGooExplosion, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiWomanElfFace } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const dirtyPairTheme: AnimeThemeConfig = {
    id: "dirty-pair",
    displayName: "Dirty Pair",
    description: "The Lovely Angels — Kei and Yuri — are top agents of WWWA who always solve cases with a 100% success rate, but somehow level a city each time. Officially: the Dirty Pair.",
    fontFamily: "'Audiowide', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Audiowide&display=swap",
    cssVars: {
        "--color-brand-200": "255 180 230",
        "--color-brand-300": "252 130 210",
        "--color-brand-400": "242 75 185",
        "--color-brand-500": "222 25 160",
        "--color-brand-600": "182 14 132",
        "--color-brand-700": "142 8 102",
        "--color-brand-800": "100 4 72",
        "--color-brand-900": "60 2 42",
        "--color-brand-950": "35 1 24",
        "--brand": "222 25 160",
        "--background": "#060206",
        "--paper": "#0f050f",
        "--color-gray-950": "6 2 6",
        "--color-gray-900": "14 5 14",
        "--color-gray-800": "26 10 28",
        "--color-gray-700": "44 18 48",
        "--color-gray-600": "68 30 75",
        "--color-gray-500": "105 52 115",
        "--color-gray-400": "148 90 158",
        "--color-gray-300": "186 132 195",
        "--color-gray-200": "214 168 222",
        "--color-gray-100": "232 205 238",
        "--color-gray-50": "246 238 250",
    },
    sidebarOverrides: {
        "home": { icon: GiWomanElfFace, label: "WWWA HQ" },
        "schedule": { icon: GiAlarmClock, label: "Mission Board" },
        "manga": { icon: LuBookOpen, label: "Agent Files" },
        "lists": { icon: GiBinoculars, label: "Case Roster" },
        "discover": { icon: GiBullseye, label: "Target Recon" },
        "torrent-list": { icon: GiGooExplosion, label: "Explosion Cache" },
        "debrid": { icon: GiSpyglass, label: "Surveillance" },
        "unmatched": { icon: GiMagnifyingGlass, label: "Cold Cases" },
        "enmasse": { icon: GiResize, label: "Mass Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Mission Reports" },
        "auto-downloader": { icon: LuRss, label: "WWWA Signals" },
        "community": { icon: GiWomanElfFace, label: "Lovely Angels" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Kei's Shout" },
        "achievements": { icon: GiTrophy, label: "Mission Medals" },
        "milestones": { icon: LuFlag, label: "Agent Goals" },
        "theme-manager": { icon: GiPalette, label: "Agent Style" },
        "extensions": { icon: BiExtension, label: "Gadget Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "WWWA Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Agent Config" },
    },
    achievementNames: {
        "a_first_episode": "First Assignment",
        "a_first_complete": "Case Closed",
        "a_hundred_club": "Hundred Missions",
        "a_time_lord": "Veteran Agent",
        "a_anime_collector": "Gadget Cache",
        "a_library_legend": "WWWA Archives",
        "a_binge_king": "Non-Stop Chaos",
        "a_no_sleep": "All-Night Mission",
        "a_marathon_runner": "Galaxy Marathon",
        "a_speed_run": "Fast Resolution",
        "a_completionist": "Galaxy Saved",
        "a_mega_completionist": "Top Agent",
        "a_loyal_fan": "Lovely Angels Fan",
        "a_rewatcher": "Case Revisited",
        "a_decade_watcher": "Decade Agent",
        "a_genre_action": "Combat Agent",
        "a_genre_adventure": "Galaxy Explorer",
        "a_genre_comedy": "Collateral Comedy",
        "a_genre_drama": "Agent Drama",
        "a_genre_fantasy": "Space Fantasy",
        "a_genre_horror": "Target Fear",
        "a_genre_romance": "Agent Hearts",
        "a_genre_scifi": "Space Tech",
        "a_genre_supernatural": "Angelic Power",
        "a_genre_psychological": "Agent Mind",
        "a_genre_mecha": "Space Combat",
        "a_critic": "WWWA Judge",
        "a_perfect_ten": "Perfect Mission",
        "a_harsh_critic": "Strict Handler",
        "a_daily_streak": "Daily Mission",
        "a_mega_streak": "Endless Cases",
        "a_year_long": "Year in Field",
        "a_iron_will": "Agent's Will",
        "a_hidden_gem": "Hidden Case",
        "a_cult_classic": "Dirty Pair Classic",
        "a_classic_connoisseur": "80s Action Fan",
        "a_new_years_resolution": "New Mission Year",
        "a_christmas_special": "Holiday Mission",
        "a_meta_tier_max": "WWWA Ace",
        "a_meta_completionist": "Complete Dossier",
        "a_sequel_chain": "Flash Sequel",
        "a_zero_to_hero": "Rookie to Legend",
        "a_night_owl": "Night Op",
        "a_early_bird": "Dawn Mission",
        "m_first_chapter": "First Briefing",
        "m_first_complete": "Case File Done",
        "m_hundred_club": "Hundred Files",
        "m_binge_king": "Case Marathon",
        "m_completionist": "Full Dossier",
        "m_mega_completionist": "Master Agent",
        "m_loyal_reader": "WWWA Reader",
        "m_rereader": "Case Review",
        "m_genre_action": "Action File",
        "m_genre_adventure": "Space Case",
        "m_genre_romance": "Heart File",
        "m_genre_fantasy": "Alien Case",
        "m_genre_horror": "Horror File",
        "m_genre_drama": "Drama Case",
        "m_genre_scifi": "Sci-Fi File",
        "m_genre_supernatural": "Angel File",
        "m_genre_psychological": "Mind File",
        "m_critic": "Case Critic",
        "m_perfect_ten": "Perfect File",
        "m_daily_streak": "Daily Brief",
        "m_mega_streak": "Unbroken Cases",
        "m_year_long": "Year of Cases",
        "m_iron_will": "Iron Agent",
        "m_hidden_gem": "Hidden File",
        "m_cult_classic": "Classic Series",
        "m_mangaka_lover": "Artist Fan",
        "m_source_material_fan": "Source First",
        "m_meta_tier_max": "WWWA Master",
        "m_meta_completionist": "Full Files",
        "m_art_appreciator": "Agent Art",
        "m_manga_to_anime": "Source Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060206",
        primary: "#de19a0",
        secondary: "#960e84",
        accent: "#f0d020",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/dirty-pair.jpg",
    particleColor: "#de19a0",
    backgroundDim: 0.35,
    backgroundBlur: 20,
    particleTypes: {
        explosions: { label: "Explosions", maxCount: 8, defaultEnabled: true, defaultIntensity: 65 },
        sparks: { label: "Sparks", maxCount: 20, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1: "WWWA Rookie",
        5: "Field Agent",
        15: "Kei or Yuri",
        30: "Lovely Angel",
        50: "Top Agent",
        75: "Galaxy Defender",
        100: "Dirty Pair Legend",
    },
}
