import { AnimeThemeConfig } from "./types"
import {
    GiScrollUnfurled,
    GiBrain,
    GiMagnifyingGlass,
    GiAnvilImpact,
    GiCompass,
    GiDeathSkull,
    GiLightningBranches,
    GiResize,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiSettingsKnobs,
    GiCrystalBall,
    GiStarMedal,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const drStoneTheme: AnimeThemeConfig = {
    id: "dr-stone",
    displayName: "Dr. Stone",
    description: "10 billion percent! After 3700 years of stone, Senku's Kingdom of Science will rebuild civilization using the power of human knowledge.",
    fontFamily: "'Exo 2', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Exo+2:wght@400;600;700&display=swap",
    cssVars: {
        "--color-brand-200": "240 255 160",
        "--color-brand-300": "220 245 100",
        "--color-brand-400": "188 220 40",
        "--color-brand-500": "168 204 0",
        "--color-brand-600": "138 168 0",
        "--color-brand-700": "105 130 0",
        "--color-brand-800": "75 95 0",
        "--color-brand-900": "48 60 0",
        "--color-brand-950": "25 32 0",
        "--brand": "168 204 0",
        "--background": "#0a0c06",
        "--paper": "#14180a",
        "--color-gray-950": "10 12 6",
        "--color-gray-900": "20 22 12",
        "--color-gray-800": "34 38 22",
        "--color-gray-700": "52 58 36",
        "--color-gray-600": "78 85 58",
        "--color-gray-500": "112 118 88",
        "--color-gray-400": "155 160 128",
        "--color-gray-300": "192 196 168",
        "--color-gray-200": "220 222 200",
        "--color-gray-100": "240 242 228",
        "--color-gray-50": "249 250 244",
    },
    sidebarOverrides: {
        "home": { icon: GiScrollUnfurled, label: "Senku's Lab" },
        "schedule": { icon: GiAlarmClock, label: "Science Timeline" },
        "manga": { icon: LuBookOpen, label: "Stone World Records" },
        "lists": { icon: GiBrain, label: "Science Registry" },
        "discover": { icon: GiMagnifyingGlass, label: "Resource Survey" },
        "torrent-list": { icon: GiAnvilImpact, label: "Tech Cache" },
        "debrid": { icon: GiCompass, label: "Expedition Intel" },
        "unmatched": { icon: GiDeathSkull, label: "Petrified Files" },
        "enmasse": { icon: GiResize, label: "Mass Revival" },
        "scan-summaries": { icon: TbReportSearch, label: "Science Reports" },
        "auto-downloader": { icon: LuRss, label: "Radio Signal" },
        "community": { icon: GiLightningBranches, label: "Kingdom of Science" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Science Alert" },
        "achievements": { icon: GiTrophy, label: "Science Feats" },
        "theme-manager": { icon: GiPalette, label: "Prism Colors" },
        "extensions": { icon: BiExtension, label: "Chrome's Add-ons" },
        "sync": { icon: IoCloudOfflineOutline, label: "Stone Signal" },
        "settings": { icon: GiSettingsKnobs, label: "Senku's Controls" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Stone World Prisoner",
        "a_episode_counter": "Science Experiment Count",
        "a_episode_titan": "Legendary Invention",
        "a_hours_invested": "Hours of Scientific Study",
        "a_time_lord": "3700 Years in Stone",
        "a_anime_collector": "Science Arsenal",
        "a_library_legend": "Science Library Legend",
        "a_first_complete": "First Invention Complete",
        "a_hundred_club": "Century of Experiments",
        "a_first_day": "First Day with Senku",
        "a_first_rating": "First Science Assessment",
        "a_ten_thousand_min": "Ten Thousand Minutes of Science",
        "a_season_veteran": "Veteran of the Science Kingdom",
        "a_year_explorer": "Year in the Stone World",
        "a_century_watcher": "Hundred Episodes of Discovery",
        "a_five_hundred_eps": "Five Hundred Science Formulas",
        "a_thousand_eps": "Thousand Stone Revivals",
        "a_watching_ten": "Ten Science Campaigns",
        "a_ptw_hoarder": "Backlog of Science Studies",
        "a_dropped_honesty": "Tactical Stone Retreat",
        "a_five_thousand_eps": "Five Thousand Science Sorties",
        "a_ten_completed": "Ten Science Arcs",
        "a_fifty_completed": "Fifty Dr. Stone Adventures",
        "a_five_hundred_completed": "Five Hundred Scientific Victories",
        "a_mean_score_tracker": "Average Science Rating",
        "a_unique_studios": "Allied Science Studios",
        "a_days_spent_watching": "Days in the Science Kingdom",
        "a_all_status": "All Science Statuses",
        "a_first_favorite": "First Bond with Chrome",
        "a_favorites_collector": "Science Team Bonds",
        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Science Marathon",
        "a_marathon_runner": "Science Marathon Runner",
        "a_weekend_warrior": "Weekend Science Warrior",
        "a_non_stop": "Relentless Like Senku",
        "a_one_more_episode": "One More Experiment",
        "a_speed_run": "Ten Billion Speed Run",
        "a_double_feature": "Double Science Feature",
        "a_triple_threat": "Triple Discovery",
        "a_five_a_day": "Five Experiments a Day",
        "a_back_to_back": "Back-to-Back Inventions",
        "a_seasonal_binge": "Full Science Arc Clear",
        "a_cour_crusher": "Science Cour Crusher",
        "a_half_day_watch": "Half Day in the Lab",
        "a_full_day_watch": "Full Day Scientific Study",
        "a_power_weekend": "Power Weekend Science",
        "a_binge_king": "King of Science Marathons",
        "a_no_sleep": "All-Night Lab Session",
        "a_entire_season": "Full Dr. Stone Season Clear",
        "a_seven_day_challenge": "Seven-Day Science Siege",
        "a_hundred_day_binge": "Hundred-Day Science Campaign",
        "a_genre_binge": "Cross-Genre Science Fantasy",
        "a_studio_binge": "Studio Science Binge",
        "a_season_sweep": "Season Sweep of Discoveries",
        "a_forty_eight_hour": "Forty-Eight Hour Science Session",
        "a_ep_counter_day": "Daily Experiment Count",
        "a_multi_series_binge": "Multi-Front Science Campaign",
        "a_midnight_binge": "Midnight Lab Session",
        "a_new_year_binge": "New Year's Science Charge",
        // ── ANIME GENRES ──
        "a_genre_action": "Combat Science Action",
        "a_genre_adventure": "Journey Across the Stone World",
        "a_genre_comedy": "Chrome's Clueless Moments",
        "a_genre_drama": "Taiju's Emotional Moments",
        "a_genre_fantasy": "Stone World Fantasy",
        "a_genre_horror": "Medusa Horror Discovery",
        "a_genre_mystery": "Mystery of Petrification",
        "a_genre_romance": "Taiju and Yuzuriha Bond",
        "a_genre_scifi": "Hard Science Fiction",
        "a_genre_sol": "Village Daily Life",
        "a_genre_sports": "Science Battle Tournament",
        "a_genre_supernatural": "Medusa Device Supernatural",
        "a_genre_thriller": "Science Race Thriller",
        "a_genre_mecha": "Science Mech Technology",
        "a_genre_music": "Dr. Stone OST Collection",
        "a_genre_psychological": "Science vs Tsukasa Ideology",
        "a_genre_ecchi": "Hot Spring Science Discovery",
        "a_genre_mahou_shoujo": "Kohaku's Combat Training",
        "a_tag_isekai": "Modern Boy in Stone World",
        "a_tag_harem": "Science Team Bonds",
        "a_tag_bl": "Senku and Chrome Bond",
        "a_tag_gl": "Kohaku and Ruri Bond",
        "a_tag_historical": "3700 Years of History",
        "a_tag_military": "Science Kingdom Army",
        "a_tag_school": "Pre-Petrification School",
        "a_tag_martial_arts": "Kohaku Combat Style",
        "a_tag_vampire": "Tsukasa's Rule by Power",
        "a_tag_samurai": "Hyoga's Fighting Style",
        "a_tag_space": "Why-Man Signal from Space",
        "a_tag_parody": "Science Parody",
        "a_tag_idol": "Senku's Scientific Progress",
        "a_tag_post_apocalyptic": "Post-Petrification World",
        "a_tag_cyberpunk": "Re-Civilized Technology",
        "a_tag_shounen": "Taiju's Fighting Spirit",
        "a_tag_seinen": "Dr. Stone Scientific Reality",
        "a_tag_shoujo": "Ruri's Village Life",
        "a_tag_josei": "Kohaku's Perspective",
        "a_tag_survival": "Surviving the Stone World",
        // ── ANIME COMPLETION ──
        "a_completionist": "Full Science Report",
        "a_mega_completionist": "Supreme Science Commander",
        "a_completion_rate_50": "Halfway to Revival",
        "a_completion_rate_75": "Approaching Science Victory",
        "a_completion_rate_90": "Final Science Chapter Near",
        "a_no_drop": "No Experiment Abandoned",
        "a_long_runner_complete": "Long Science Journey Complete",
        "a_sequel_chain": "Science Chain Complete",
        "a_clean_list": "Clean Science Record",
        "a_from_ptw": "Science Orders Fulfilled",
        "a_rewatch_master": "Reliving Science Discoveries",
        "a_short_complete": "Quick Science Skirmish",
        "a_same_day_start_finish": "Same-Day Science Mission",
        "a_revival": "Stone World Revival",
        "a_zero_to_hero": "Primitive to Science Master",
        "a_five_genre_complete": "Five-Genre Science Mastery",
        "a_full_franchise": "Full Dr. Stone Dossier",
        "a_batch_complete": "Batch Science Clear",
        "a_paused_to_done": "Returned from Stone World Hiatus",
        "a_completion_spree": "Completion Science Barrage",
        "a_multi_rewatch": "Multi-Timeline Science Journey",
        "a_dropped_recovery": "Recovered from Petrification",
        "a_ten_perfect_scores": "Ten Perfect Science Scores",
        "a_seasonal_clear": "Seasonal Science Clear",
        "a_complete_genre_span": "All-Format Science Fan",
        "a_monthly_completions": "Monthly Science Reports",
        "a_yearly_completions": "Yearly Science Campaign",
        "a_rapid_complete": "Lightning Science Raid",
        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Dr. Stone Devotee",
        "a_studio_devotee": "Studio TMS Entertainment Devotee",
        "a_rewatcher": "Science Recon Rewatch",
        "a_triple_rewatch": "Triple Science Rewatch",
        "a_annual_tradition": "Annual Science Remembrance",
        "a_director_fan": "Director's Science Vision",
        "a_voice_actor_fan": "Voice of Science",
        "a_ost_lover": "Dr. Stone OST Devotee",
        "a_source_reader": "Inagaki's Original Manga",
        "a_waiting_weekly": "Weekly Science Chapter Wait",
        "a_childhood_revisit": "Return to Pre-Stone World",
        "a_saga_tracker": "Saga of Dr. Stone Tracker",
        "a_genre_loyalty": "Science Genre Loyalty",
        "a_decade_watcher": "Decade-Long Science Watcher",
        "a_adaptation_hunter": "Dr. Stone Adaptation Hunt",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Science Duty",
        "a_perfect_attendance": "Perfect Science Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Science Catalog",
        "a_franchise_collector": "Dr. Stone Universe Collector",
        "a_airing_follower": "Currently Airing Science Intel",
        "a_genre_master": "Science Genre Mastery",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Arc Science Veteran",
        "a_format_diversity": "Diverse Science Formats",
        "a_year_dedication": "Year of Dedication to Science",
        "a_season_dedication": "Season of Scientific Service",
        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Known Science",
        "a_studio_hopper": "Science Lab Transfer",
        "a_tag_explorer": "Science Tag Recon Mission",
        "a_decade_hopper": "Decade Science Hopping",
        "a_hidden_gem": "Hidden Science Gem",
        "a_popular_taste": "Popular Among Scientists",
        "a_retro_appreciator": "Pre-Petrification Era Fan",
        "a_modern_viewer": "Modern Science Viewer",
        "a_cross_demographic": "Cross-Demographic Science Fan",
        "a_underdog_fan": "Underdog Science Spirit",
        "a_variety_week": "Week of Varied Experiments",
        "a_foreign_cinema": "Foreign Science Cinema",
        "a_classic_connoisseur": "Classic Science Fan",
        "a_every_season": "Every Season in the Science Kingdom",
        "a_award_winner": "Medal of Science Valor",
        "a_niche_explorer": "Niche Science Territory",
        "a_global_anime": "Global Science Alliance",
        "a_cult_classic": "Dr. Stone Cult Classic",
        "a_random_pick": "Random Science Assignment",
        "a_new_genre_month": "New Science Territory Monthly",
        "a_seasonal_completionist": "Seasonal Science Clear",
        "a_unpopular_opinion": "Unpopular Science Opinion",
        "a_top_rated_viewer": "Top-Rated Science Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Science Intel",
        "a_short_series_explorer": "Short Science Skirmish Explorer",
        "a_long_series_explorer": "Long Science Campaign Explorer",
        // ── ANIME TIME ──
        "a_night_owl": "Night Watch in the Lab",
        "a_early_bird": "Dawn Science Discovery",
        "a_lunch_break": "Lunch Break Experiment",
        "a_golden_hour": "Golden Hour of Discovery",
        "a_four_am_club": "4 AM Science Sentry",
        "a_witching_hour": "Medusa Activation Hour",
        "a_new_year_watch": "New Year's Science Oath",
        "a_midnight_premiere": "Midnight Dr. Stone Premiere",
        "a_all_hours": "All-Hours Science Vigil",
        "a_dawn_warrior": "Dawn Science Warrior",
        "a_afternoon_delight": "Afternoon Lab Rest",
        "a_prime_time": "Prime Time Science Battle",
        "a_workday_watcher": "On-Duty Science Watcher",
        "a_sunday_marathon": "Sunday Science Marathon",
        "a_rainy_day": "Rainy Day Lab Session",
        "a_morning_routine": "Morning Science Formation",
        "a_night_shift": "Night Shift Science Guard",
        "a_twilight_zone": "Twilight Science Discovery",
        "a_seasonal_premier": "Season Premiere Science Reveal",
        "a_clock_collector": "Science Clock Collector",
        "a_weekend_binge_hours": "Weekend Science Binge",
        "a_late_night_regular": "Late Night Regular Scientist",
        "a_sunrise_watcher": "Sunrise After Discovery",
        "a_holiday_watcher": "Holiday Science Duty",
        "a_every_day_of_week": "Every Day a Scientist",
        "a_monthly_hours": "Monthly Science Hours",
        // ── ANIME SOCIAL ──
        "a_first_party": "First Science Team Formation",
        "a_party_host": "Kingdom of Science Commander",
        "a_social_butterfly": "Village Socialite",
        "a_group_binge": "Group Science Viewing",
        "a_party_regular": "Regular Science Partner",
        "a_sync_viewer": "Synchronized Science Maneuver",
        "a_commentator": "Science Battle Commentator",
        "a_party_marathon": "Marathon Science Run",
        "a_full_house": "Full Science Team",
        "a_community_pillar": "Pillar of the Science Kingdom",
        "a_watch_party_streak": "Consecutive Science Streak",
        "a_diverse_party": "Diverse Science Party",
        "a_late_night_party": "Late Night Science Party",
        "a_party_veteran": "Veteran Science Leader",
        "a_genre_party": "Cross-Genre Science Formation",
        "a_weekly_party": "Weekly Scientists' Gathering",
        "a_silent_viewer": "Silent Like Chrome Observer",
        "a_recommendation_giver": "Senku's Recommendation",
        "a_party_completionist": "Party Science Completionist",
        "a_social_scorer": "Social Science Scorer",
        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Science Formation",
        "a_fibonacci": "Fibonacci Science Sequence",
        "a_palindrome_day": "Palindrome Science Loop",
        "a_binary_day": "Binary Radio Signal Day",
        "a_full_moon": "Full Moon Science Ritual",
        "a_leap_year": "Leap Year Time Calculation",
        "a_time_traveler": "3700 Years Time Travel",
        "a_genre_clash": "Senku vs Tsukasa Clash",
        "a_triple_seven": "Triple Seven Science Points",
        "a_thousand_complete": "Thousand Science Battles",
        "a_pi_episodes": "Pi Science Calculation",
        "a_synchronicity": "Senku-Chrome Synchronicity",
        "a_world_record": "World Record Science Count",
        "a_nice": "Nice Science Count",
        "a_power_level": "Ten Billion Percent",
        "a_answer_42": "Answer to Science Life",
        "a_square_number": "Perfect Science Formation",
        "a_prime_count": "Prime Science Count",
        "a_matching_date": "Matching Science Date",
        "a_century_episode": "Century Episode Discovery",
        "a_double_digits": "Double Digit Inventions",
        "a_one_two_three": "Senku Chrome Kohaku",
        "a_lucky_seven": "Seven Lucky Scientists",
        "a_all_tens": "All Tens Science Score",
        "a_exact_hundred_eps": "Exact Hundred Experiments",
        "a_year_match_count": "Year Match Science Count",
        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Science Watcher",
        "a_movie_buff": "Dr. Stone Movie Expedition",
        "a_ova_hunter": "OVA Science Hunter",
        "a_ona_explorer": "ONA Science Explorer",
        "a_special_watcher": "Special Science Episode",
        "a_short_king": "Short Science Skirmish King",
        "a_variety_pack": "All-Format Science Regiment",
        "a_film_festival": "Science Film Festival",
        "a_music_video": "Dr. Stone Music Video",
        "a_tv_short": "Quick Science Recon Clip",
        "a_movie_marathon": "Dr. Stone Movie Marathon",
        "a_double_length": "Double-Length Science Operation",
        "a_anthology": "Dr. Stone Anthology",
        "a_mini_series": "Mini Science Campaign",
        "a_theatrical": "Theatrical Science Premiere",
        "a_format_master": "Format Master Science Fan",
        "a_long_movie": "Feature-Length Science Expedition",
        "a_back_catalog": "Back Catalog Science Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Science Collector",
        "a_format_balance": "Balanced Science Formats",
        "a_episodic_master": "Episodic Science Master",
        "a_sequel_movie": "Sequel Science Film",
        "a_recap_watcher": "Recap Science Briefing",
        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Science Experiment Streak",
        "a_mega_streak": "Mega Science Streak",
        "a_weekly_warrior": "Weekly Science Warrior",
        "a_monthly_watcher": "Monthly Science Duty",
        "a_comeback": "Return from Stone World Hiatus",
        "a_weekend_streak": "Weekend Science Streak",
        "a_no_zero_days": "No Zero Science Days",
        "a_iron_will": "Iron Will of the Scientist",
        "a_habit_formed": "Science Training Regimen Formed",
        "a_consistent_pace": "Consistent Science Advance",
        "a_year_long": "Year-Long Science Campaign",
        "a_double_streak": "Double Science Assault Streak",
        "a_streak_recovery": "Recovery After Petrification",
        "a_daily_minimum": "Daily Minimum Science Duty",
        "a_winter_streak": "Winter Science Campaign",
        "a_summer_streak": "Summer Science Offensive",
        "a_morning_streak": "Morning Science Drill Streak",
        "a_night_streak": "Night Science Patrol Streak",
        "a_unbreakable": "Unbreakable Scientific Will",
        "a_eternal_flame": "Eternal Flame of Knowledge",
        "a_completion_streak": "Completion Science Chain",
        "a_rating_streak": "Rating Science Streak",
        "a_multi_ep_streak": "Multi-Episode Science Offensive",
        "a_genre_streak": "Genre Science Streak",
        "a_studio_streak": "Studio Science Loyalty Streak",
        "a_perfect_week": "Perfect Week of Science",
        // ── ANIME SCORING ──
        "a_critic": "Science Kingdom Judge",
        "a_perfect_ten": "Perfect 10 Science Rating",
        "a_harsh_critic": "Senku's Harsh Standards",
        "a_fair_judge": "Gen's Fair Assessment",
        "a_generous_spirit": "Generous Science Spirit",
        "a_score_all": "Full Science Roster Evaluation",
        "a_wide_range": "Wide Range Science Assessment",
        "a_controversial": "Controversial Science Decision",
        "a_consistent_scorer": "Consistent Science Evaluator",
        "a_score_sniper": "Precision Science Sniper",
        "a_evolving_taste": "Evolving Science Strategy",
        "a_bell_curve": "Bell Curve Science Scores",
        "a_picky_watcher": "Selective Science Commander",
        "a_100_rated": "Century of Science Evaluations",
        "a_500_rated": "Five Hundred Science Reports",
        "a_mediocre_majority": "Middle Ground Scientist",
        "a_rating_spree": "Science Rating Barrage",
        "a_score_variance": "Variable Science Ratings",
        "a_masterpiece_hunter": "Masterpiece Science Hunter",
        "a_contrarian": "Contrarian Science Scout",
        "a_optimist": "Optimist of Science",
        "a_score_distributor": "Score Distributor Science General",
        "a_genre_critic": "Genre Science Critic",
        "a_mean_above_8": "Elite Science Average",
        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Science Vow",
        "a_valentines_weeb": "Valentine's Science Bond",
        "a_pi_day": "Pi Day Science Calculation",
        "a_april_fools": "April Fools Senku Prank",
        "a_international_anime_day": "International Science Day",
        "a_star_wars_day": "Why-Man Signal Day",
        "a_summer_solstice": "Summer Solstice Lab Experiment",
        "a_tanabata": "Tanabata Science Wish",
        "a_friday_13th": "Friday 13th Petrification Risk",
        "a_halloween_spirit": "Halloween Medusa Discovery",
        "a_thanksgiving_binge": "Thanksgiving Science Feast",
        "a_christmas_special": "Midwinter Science Festival",
        "a_new_years_eve": "New Year's Eve Science Stand",
        "a_birthday_watch": "Birthday Science Enlistment",
        "a_holiday_marathon": "Holiday Science Marathon",
        "a_independence_day": "Human Independence Day",
        "a_culture_day": "Science Culture Day",
        "a_spring_equinox": "Spring Science Advance",
        "a_earth_day": "Earth Day Chemistry",
        "a_labor_day": "Science Labor Day",
        "a_winter_solstice": "Winter Science Solstice Night",
        "a_anime_birthday": "Dr. Stone Anniversary",
        "a_every_holiday": "Every Holiday Science Scout",
        "a_consecutive_holidays": "Consecutive Holiday Experiments",
        // ── ANIME META ──
        "a_meta_first_unlock": "First Scientific Breakthrough",
        "a_meta_collector": "Science Badge Collector",
        "a_meta_category_starter": "Category Science Initiation",
        "a_meta_tier_climber": "Science Rank Promotion",
        "a_meta_tier_max": "Kingdom of Science Class",
        "a_meta_xp_earner": "XP from Science Discovery",
        "a_meta_difficulty_easy": "Easy Formula",
        "a_meta_difficulty_hard": "Ten Billion Percent Hard Mode",
        "a_meta_unlock_spree": "Unlock Spree Science Barrage",
        "a_meta_completionist": "Meta Science Completionist",
        "a_meta_diverse": "Diverse Science Portfolio",
        "a_meta_dominator": "Meta Dominator of Science",
        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Science Chapter",
        "m_chapter_counter": "Science Chapter Counter",
        "m_chapter_titan": "Legendary Chapter Discovery",
        "m_reading_hours": "Hours Studying Science Texts",
        "m_reading_time_lord": "Science Timeless Reading",
        "m_manga_collector": "Science Archive Collector",
        "m_library_legend": "Science Library Reading Legend",
        "m_first_complete": "First Dr. Stone Manga Done",
        "m_hundred_club": "Hundred-Chapter Science Club",
        "m_first_day": "First Day Science Reading",
        "m_first_rating": "First Science Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Science Pages",
        "m_volume_collector": "Science Volume Collector",
        "m_year_explorer": "Year of Science Exploration",
        "m_century_reader": "Century Science Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Science Chapters",
        "m_thousand_ch": "Thousand-Chapter Science Campaign",
        "m_reading_ten": "Ten Science Manuscripts at Once",
        "m_ptr_hoarder": "Science Reading Backlog",
        "m_dropped_honesty": "Honest Science Retreat",
        "m_season_reader": "Science Seasonal Reading",
        "m_active_reader": "Active Science Field Reader",
        "m_five_thousand_ch": "Five Thousand Science Chapters",
        "m_ten_completed": "Ten Science Manga Complete",
        "m_fifty_completed": "Fifty Science Missions Done",
        "m_five_hundred_completed": "Five Hundred Scientific Victories",
        "m_mean_score_tracker": "Average Science Manuscript Rating",
        "m_unique_authors": "Unique Science Author Encounters",
        "m_all_status": "All Science Reading Statuses",
        "m_first_favorite": "First Science Manga Bond",
        "m_favorites_collector": "Science Favorites Arsenal",
        "m_days_spent_reading": "Days in Science Garrison",
        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Science Reading",
        "m_marathon_reader": "Science Marathon Reader",
        "m_weekend_reader": "Weekend Science Reading",
        "m_non_stop_reading": "Non-Stop Science Page Turning",
        "m_one_more_chapter": "One More Science Chapter",
        "m_speed_read": "Ten Billion Speed Read",
        "m_double_story": "Double Science Manuscript",
        "m_triple_read": "Triple Science Reading",
        "m_five_a_day": "Five Science Reads a Day",
        "m_chapter_chain": "Science Chapter Chain",
        "m_volume_binge": "Science Volume Binge",
        "m_power_reader": "Power Science Reader",
        "m_half_day_read": "Half-Day Science Archive",
        "m_full_day_read": "Full-Day Science Study",
        "m_power_weekend": "Power Science Weekend Reading",
        "m_binge_king": "King of Science Reading Corps",
        "m_no_sleep_read": "All-Night Science Reading",
        "m_full_series_rush": "Full Dr. Stone Series Rush",
        "m_seven_day_challenge": "Seven-Day Science Gathering",
        "m_hundred_day_read": "Hundred-Day Science Reading",
        "m_volume_rush": "Science Volume Rush",
        "m_series_sweep": "Science Series Sweep",
        "m_genre_binge": "Cross-Genre Science Reading",
        "m_author_binge": "Inagaki Deep Dive",
        "m_chapter_counter_day": "Daily Science Chapter Count",
        "m_multi_series_binge": "Multi-Series Science Reading",
        "m_midnight_binge": "Midnight Science Archive",
        "m_new_year_binge": "New Year's Science Reading",
        "m_forty_eight_hour": "Forty-Eight Hour Science Read",
        "m_oneshot_binge": "Oneshot Science Blitz",
        // ── MANGA GENRES ──
        "m_genre_action": "Science Action Manuscript",
        "m_genre_adventure": "Stone World Adventure Manga",
        "m_genre_comedy": "Chrome's Clueless Chapters",
        "m_genre_drama": "Emotional Science Drama",
        "m_genre_fantasy": "Stone World Fantasy Manga",
        "m_genre_horror": "Medusa Horror Manga",
        "m_genre_mystery": "Petrification Mystery Manga",
        "m_genre_romance": "Taiju and Yuzuriha Manga",
        "m_genre_scifi": "Hard Science Fiction Manga",
        "m_genre_sol": "Village Life Manga",
        "m_genre_sports": "Science Tournament Manga",
        "m_genre_supernatural": "Medusa Supernatural Manga",
        "m_genre_thriller": "Science Race Thriller Manga",
        "m_genre_psychological": "Ideology Battle Manga",
        "m_genre_isekai": "Modern Boy in Stone World",
        "m_genre_shounen": "Science Shounen Heart",
        "m_genre_ecchi": "Hot Spring Manga",
        "m_genre_mahou_shoujo": "Kohaku Combat Manga",
        "m_genre_mecha": "Science Mech Manga",
        "m_genre_music": "Dr. Stone OST Manga",
        "m_tag_isekai_new": "New Science World",
        "m_tag_harem": "Science Team Manga",
        "m_tag_bl": "Senku and Chrome Manga",
        "m_tag_gl": "Kohaku and Ruri Manga",
        "m_tag_historical": "3700 Years Manga",
        "m_tag_military": "Science Army Manga",
        "m_tag_school": "Pre-Stone School Manga",
        "m_tag_martial_arts": "Kohaku Combat Manual",
        "m_tag_vampire": "Tsukasa Power Manga",
        "m_tag_samurai": "Hyoga Combat Manga",
        "m_tag_space": "Why-Man Manga",
        "m_tag_parody": "Science Parody Manga",
        "m_tag_idol": "Science Progress Manga",
        "m_tag_post_apocalyptic": "Post-Petrification Manga",
        "m_tag_cyberpunk": "Re-Civilized Tech Manga",
        "m_tag_shoujo": "Ruri's Village Manga",
        "m_tag_survival": "Survival in Stone World Manga",
        "m_tag_cooking": "Science Kitchen Manga",
        "m_tag_medical": "Science Medic Manga",
        "m_tag_villainess": "Tsukasa Villainess Manga",
        // ── MANGA COMPLETION ──
        "m_completionist": "Science Manga Completionist",
        "m_mega_completionist": "Supreme Science Commander",
        "m_completion_rate_50": "Halfway to Revival",
        "m_completion_rate_75": "Approaching Science Victory",
        "m_completion_rate_90": "Final Science Chapter Near",
        "m_no_drop": "No Science Manga Abandoned",
        "m_long_runner_complete": "Long Science Series Endurance",
        "m_sequel_chain": "Sequel Science Arc Chain",
        "m_clean_list": "Clean Science Reading Record",
        "m_from_ptr": "Orders Received Science Read",
        "m_reread_master": "Science Discovery Reread",
        "m_oneshot_complete": "Oneshot Science Mission",
        "m_same_day_start_finish": "Same-Day Science Blitz",
        "m_revival": "Revival Through Science",
        "m_zero_to_hundred": "Primitive to Science Scholar",
        "m_five_genre_complete": "Five Science Genres Mastered",
        "m_full_collection": "Full Science Archive",
        "m_batch_complete": "Science Batch Clearance",
        "m_paused_to_done": "Back from Stone World Hiatus",
        "m_completion_spree": "Science Completion Barrage",
        "m_format_completionist": "Science Format Completion",
        "m_catch_up": "Caught Up with Science Serialization",
        "m_multi_reread": "Multi-Pass Science Reread",
        "m_dropped_recovery": "Recovered from Petrification",
        "m_ten_perfect_scores": "Ten Perfect Science Scores",
        "m_complete_genre_span": "All-Genre Science Scout",
        "m_monthly_completions": "Monthly Science Victories",
        "m_yearly_completions": "Yearly Science Campaign",
        "m_rapid_complete": "Rapid Science Processing",
        "m_author_complete": "Inagaki's Complete Works",
        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Science Reader",
        "m_mangaka_lover": "Inagaki Devotee",
        "m_rereader": "Dr. Stone Saga Rereader",
        "m_triple_reread": "Triple Science Reread",
        "m_annual_reread": "Annual Dr. Stone Reread",
        "m_publisher_fan": "Science Publisher Fan",
        "m_artist_fan": "Boichi Art Appreciation",
        "m_adaptation_compare": "Dr. Stone Manga vs Anime Compare",
        "m_source_material_fan": "Science Source Material Scout",
        "m_waiting_weekly": "Weekly Science Chapter Wait",
        "m_classic_reader": "Classic Science Manuscript",
        "m_saga_reader": "Saga of Science Reader",
        "m_genre_loyalty": "Science Genre Loyalty",
        "m_decade_reader": "Decade-Long Science Reader",
        "m_ln_adaptation": "Science Light Novel Intel",
        "m_original_work": "Inagaki's Original Work",
        "m_long_commitment": "Long-Term Science Reading",
        "m_up_to_date": "Up-to-Date with Science",
        "m_favorite_mangaka": "Inagaki Honored",
        "m_complete_portfolio": "Complete Science Portfolio",
        "m_franchise_collector": "Dr. Stone Franchise Collector",
        "m_serialization_follower": "Science Serialization Tracker",
        "m_genre_master": "Science Genre Mastery",
        "m_multi_series_author": "Multi-Series Science Author Fan",
        "m_format_diversity": "Diverse Science Reading Formats",
        "m_year_dedication": "Year of Science Reading",
        "m_ongoing_follower": "Ongoing Science Series",
        "m_genre_loyalty_50": "Fifty Science Genre Chapters",
        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Science Genre Territory Scout",
        "m_publisher_hopper": "Science Publisher Transfer",
        "m_tag_explorer": "Science Tag Recon Mission",
        "m_decade_hopper": "Science Decade Hopping",
        "m_hidden_gem": "Hidden Science Gem",
        "m_popular_taste": "Popular Among Scientists",
        "m_retro_reader": "Retro Science Manuscript",
        "m_modern_reader": "Modern Science Era Reader",
        "m_cross_demographic": "Cross-Demographic Science Scout",
        "m_underdog_fan": "Underdog Science Fan",
        "m_variety_week": "Week of Science Readings",
        "m_manhwa_reader": "Science Manhwa Reader",
        "m_manhua_reader": "Science Manhua Reader",
        "m_classic_connoisseur": "Classic Science Connoisseur",
        "m_award_winner": "Medal-Winning Science Manga",
        "m_niche_explorer": "Niche Science Territory",
        "m_world_manga": "World Science Manga",
        "m_cult_classic": "Dr. Stone Cult Classic",
        "m_random_pick": "Random Science Assignment",
        "m_new_genre_month": "New Science Genre Monthly",
        "m_year_completionist": "Year Science Completionist",
        "m_unpopular_opinion": "Unpopular Science Opinion",
        "m_top_rated_reader": "Top-Rated Science Source",
        "m_source_variety": "Science Source Variety",
        "m_low_score_brave": "Brave Science Low-Score Reader",
        "m_short_manga_explorer": "Short Science Skirmish",
        "m_long_manga_explorer": "Long Science Campaign Manuscript",
        "m_serialization_explorer": "Science Serialization Explorer",
        // ── MANGA TIME ──
        "m_night_owl": "Night Science Reading",
        "m_early_bird": "Dawn Science Reading",
        "m_lunch_reader": "Lab Lunch Science Reading",
        "m_commute_reader": "Science Commute Reading",
        "m_four_am_club": "4 AM Science Reader",
        "m_new_year_read": "New Year's Science Reading Oath",
        "m_all_hours": "All-Hours Science Archive",
        "m_prime_time_reader": "Prime Time Science Manuscript",
        "m_workday_reader": "On-Duty Science Reader",
        "m_sunday_read": "Sunday Science Reading Marathon",
        "m_morning_routine": "Morning Science Formation Reading",
        "m_night_shift_reader": "Night Science Guard Reader",
        "m_seasonal_premier_read": "Science New Release Intel",
        "m_clock_collector": "Science Clock Collector",
        "m_late_night_horror": "Midnight Medusa Horror Read",
        "m_afternoon_reader": "Afternoon Science Reading",
        "m_golden_hour_reader": "Golden Hour Science Reading",
        "m_dawn_reader": "Dawn Science Reading Scout",
        "m_twilight_reader": "Twilight Science Discovery Reading",
        "m_midnight_start": "Midnight Science Reading Mission",
        "m_weekend_binge_hours": "Weekend Science Binge Reading",
        "m_late_night_regular": "Late Night Science Reader",
        "m_sunrise_reader": "Sunrise After Discovery Reader",
        "m_every_day_of_week": "Every Day Science Reading",
        "m_monthly_hours": "Monthly Science Hours Logged",
        "m_bedtime_reader": "Bedtime Science Reader",
        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Boichi Art Appreciator",
        "m_webtoon_reader": "Science Webtoon Intelligence",
        "m_full_color": "Full Color Science Manuscript",
        "m_doujin_reader": "Underground Science Doujin",
        "m_anthology_reader": "Science Anthology Reader",
        "m_adaptation_reader": "Science Adaptation Study",
        "m_longstrip_reader": "Vertical Science Scroll Reader",
        "m_4koma_reader": "4-Koma Science Comedy",
        "m_oneshot_reader": "Oneshot Science Mission Reader",
        "m_format_variety": "Science Format Variety",
        "m_light_novel_reader": "Science Light Novel Reader",
        "m_novel_reader": "Science Novel Archive Reader",
        "m_visual_storyteller": "Science Battle Narrator",
        "m_colored_classic": "Colored Science Classic",
        "m_webcomic_fan": "Science Webcomic Fan",
        "m_manga_to_anime": "Dr. Stone Manga to Anime",
        "m_seinen_reader": "Seinen Science Reader",
        "m_josei_reader": "Josei Science Perspective",
        "m_award_winning_art": "Medal-Winning Science Artwork",
        "m_debut_work": "Science Debut Manuscript",
        "m_vertical_scroll": "Vertical Science Scroll Intel",
        "m_traditional_format": "Traditional Science Format",
        "m_cross_media": "Science Cross-Media Intel",
        "m_spinoff_reader": "Science Spinoff Mission",
        "m_remake_reader": "Science Remake Assignment",
        "m_collaboration_reader": "Science Joint Operation Manuscript",
        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Science Reading Streak",
        "m_mega_streak": "Mega Science Reading Streak",
        "m_weekly_warrior": "Weekly Science Warrior Reader",
        "m_monthly_reader": "Monthly Science Reader",
        "m_comeback": "Return from Stone World Exile",
        "m_weekend_streak": "Weekend Science Reading Streak",
        "m_no_zero_days": "No Zero Science Reading Days",
        "m_iron_will": "Iron Will Science Reader",
        "m_habit_formed": "Science Reading Regimen",
        "m_consistent_pace": "Consistent Science Advance",
        "m_year_long": "Year-Long Science Reading",
        "m_double_streak": "Double Science Reading Streak",
        "m_streak_recovery": "Science Reading Streak Recovery",
        "m_daily_minimum": "Daily Science Minimum Pages",
        "m_winter_streak": "Winter Science Reading Campaign",
        "m_summer_streak": "Summer Science Offensive Reading",
        "m_morning_streak": "Morning Science Formation Reading",
        "m_night_streak": "Night Science Patrol Reading",
        "m_unbreakable": "Unbreakable Scientific Reading Will",
        "m_eternal_flame": "Eternal Flame of Knowledge",
        "m_chapter_a_day": "Chapter a Day Science Discipline",
        "m_genre_streak": "Genre Science Reading Streak",
        "m_completion_streak": "Completion Science Reading Chain",
        "m_rating_streak": "Science Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Science Streak",
        "m_author_streak": "Inagaki Dedication Streak",
        "m_perfect_week_manga": "Perfect Science Reading Week",
        "m_diverse_streak": "Diverse Science Reading Streak",
        // ── MANGA SCORING ──
        "m_critic": "Science Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Science Manuscript",
        "m_harsh_critic": "Senku's Reading Standards",
        "m_fair_judge": "Gen's Fair Review",
        "m_generous_spirit": "Generous Science Reader Spirit",
        "m_score_all": "Full Science Manuscript Assessment",
        "m_wide_range": "Wide Range Science Scores",
        "m_controversial": "Controversial Science Opinion",
        "m_consistent_scorer": "Consistent Science Scorer",
        "m_score_sniper": "Precision Science Score Sniper",
        "m_evolving_taste": "Evolving Science Reading Taste",
        "m_bell_curve": "Bell Curve Science Scores",
        "m_picky_reader": "Selective Science Reader",
        "m_100_rated": "Century of Science Ratings",
        "m_500_rated": "Five Hundred Science Ratings",
        "m_mediocre_majority": "Middle Ground Science Reader",
        "m_rating_spree": "Science Rating Barrage",
        "m_score_variance": "Variable Science Scores",
        "m_binge_rater": "Binge Science Rating Session",
        "m_reread_rerate": "Reread and Re-Rate Dr. Stone",
        "m_masterpiece_hunter": "Masterpiece Science Manuscript Hunter",
        "m_contrarian": "Contrarian Science Reader",
        "m_optimist": "Optimistic Science Reader",
        "m_score_distributor": "Score Distributor Science General",
        "m_genre_critic": "Genre Science Reading Critic",
        "m_mean_above_8": "Elite Science Reading Average",
        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Science Reading Vow",
        "m_valentines_read": "Valentine's Science Bond Read",
        "m_pi_day": "Pi Day Science Chapter Count",
        "m_april_fools": "April Fools Science Prank",
        "m_international_manga_day": "International Science Manga Day",
        "m_free_comic_day": "Free Science Comic Day",
        "m_summer_solstice": "Summer Solstice Science Reading",
        "m_tanabata": "Tanabata Science Reading Wish",
        "m_friday_13th": "Friday 13th Petrification Risk Read",
        "m_halloween_read": "Halloween Medusa Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Science Reading Feast",
        "m_christmas_read": "Midwinter Festival Science Read",
        "m_new_years_eve": "New Year's Eve Science Stand Read",
        "m_birthday_read": "Birthday Science Reading Gift",
        "m_holiday_marathon": "Holiday Science Reading Marathon",
        "m_independence_day": "Human Independence Science Reading",
        "m_culture_day": "Science Culture Day Manuscript",
        "m_spring_equinox": "Spring Science Equinox Reading",
        "m_earth_day": "Earth Day Chemistry Reading",
        "m_labor_day": "Science Labor Reading Day",
        "m_winter_solstice": "Winter Science Solstice Reading",
        "m_manga_birthday": "Dr. Stone Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Science Reader",
        "m_consecutive_holidays": "Consecutive Science Holiday Reads",
        // ── MANGA SPECIAL ──
        "m_round_number": "Science Round Number Milestone",
        "m_fibonacci": "Science Fibonacci Pattern",
        "m_palindrome_day": "Palindrome Science Reading Day",
        "m_binary_day": "Binary Radio Signal Day",
        "m_full_moon_read": "Full Moon Science Read",
        "m_leap_year_read": "Leap Year Science Reading",
        "m_triple_seven": "Triple Seven Science Points",
        "m_thousand_complete": "Thousand Science Victories",
        "m_nice": "Nice Science Chapter Count",
        "m_power_level_chapters": "Ten Billion Percent Chapters",
        "m_answer_42": "Answer to Science Life Reading",
        "m_square_number": "Perfect Science Formation Chapters",
        "m_prime_count": "Prime Science Chapter Count",
        "m_matching_date": "Matching Science Reading Date",
        "m_century_chapter": "Century Science Chapter Milestone",
        "m_pi_chapters": "Pi Science Chapter Calculation",
        "m_synchronicity": "Science Reading Synchronicity",
        "m_world_record": "World Record Science Chapter Count",
        "m_genre_clash": "Science Genre Clash Reading",
        "m_time_traveler": "Time-Traveling Science Reader",
        "m_double_digits": "Double Digit Science Milestone",
        "m_one_two_three": "Senku Chrome Kohaku Chapters",
        "m_lucky_seven": "Seven Lucky Science Chapters",
        "m_exact_hundred_ch": "Exact Hundred Science Chapters",
        "m_year_match_count": "Year Match Science Count",
        "m_chapter_match_date": "Chapter Science Date Match",
        // ── MANGA FORMATS ──
        "m_manga_format": "Science Manga Format Specialist",
        "m_manhwa_format": "Science Manhwa Format Reader",
        "m_manhua_format": "Science Manhua Format Reader",
        "m_ln_format": "Science Light Novel Format",
        "m_oneshot_format": "Oneshot Science Format",
        "m_doujin_format": "Science Doujin Format Reader",
        "m_novel_format": "Science Novel Format Reader",
        "m_format_master_manga": "Format Science Master Reader",
        // ── MANGA META ──
        "m_meta_first_unlock": "First Scientific Reading Breakthrough",
        "m_meta_collector": "Science Reading Badge Collector",
        "m_meta_category_starter": "Science Category Initiation",
        "m_meta_tier_climber": "Science Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Science Reading Rank",
        "m_meta_xp_earner": "XP from Science Reading Intel",
        "m_meta_difficulty_easy": "Easy Formula Reading",
        "m_meta_difficulty_hard": "Legendary Senku Manuscript",
        "m_meta_unlock_spree": "Science Reading Unlock Barrage",
        "m_meta_completionist": "Meta Science Completionist",
        "m_meta_diverse": "Diverse Science Portfolio",
        "m_meta_dominator": "Meta Dominator Science Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#0a0c06",
        primary: "#a8cc00",
        secondary: "#86a400",
        accent: "#0080ff",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/dr-stone.jpg",
    particleColor: "#58a830",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        stone_fragments: { label: "Stone Fragments", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        chemical_sparks: { label: "Chemical Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        science_equations: { label: "Science Equations", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        revival_light: { label: "Revival Light", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1: "Stone World Prisoner",
        5: "Awakened Primitive",
        15: "Science Believer",
        30: "Kingdom of Science",
        45: "Inventive Genius",
        60: "Technology Pioneer",
        80: "10 Billion% Effort",
        100: "Science Conquered Stone",
    },
}
