import { AnimeThemeConfig } from "./types"
import { GiDragonHead, GiFist, GiLightningBow, GiMuscleUp, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiFlame } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const dragonBallTheme: AnimeThemeConfig = {
    id: "dragon-ball",
    displayName: "Dragon Ball",
    description: "A boy with a monkey tail finds a strange orange ball — then six more, and an adventure across the world. Young Goku's journey is pure adventure, humor, and heart.",
    fontFamily: "'Bangers', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Bangers&display=swap",
    cssVars: {
        "--color-brand-200": "255 200 120",
        "--color-brand-300": "250 172 60",
        "--color-brand-400": "240 142 10",
        "--color-brand-500": "220 112 0",
        "--color-brand-600": "182 90 0",
        "--color-brand-700": "142 68 0",
        "--color-brand-800": "100 48 0",
        "--color-brand-900": "60 28 0",
        "--color-brand-950": "35 16 0",
        "--brand": "220 112 0",
        "--background": "#060400",
        "--paper": "#110900",
        "--color-gray-950": "6 4 0",
        "--color-gray-900": "14 10 2",
        "--color-gray-800": "26 20 6",
        "--color-gray-700": "44 34 12",
        "--color-gray-600": "70 54 22",
        "--color-gray-500": "108 86 44",
        "--color-gray-400": "152 126 82",
        "--color-gray-300": "190 164 120",
        "--color-gray-200": "218 196 158",
        "--color-gray-100": "234 220 190",
        "--color-gray-50": "246 240 226",
    },
    sidebarOverrides: {
        "home": { icon: GiDragonHead, label: "Kame House" },
        "schedule": { icon: GiAlarmClock, label: "Training Schedule" },
        "manga": { icon: LuBookOpen, label: "Dragon Scrolls" },
        "lists": { icon: GiFist, label: "Tournament Roster" },
        "discover": { icon: GiBullseye, label: "Dragon Ball Hunt" },
        "torrent-list": { icon: GiFlame, label: "Power Cache" },
        "debrid": { icon: GiLightningBow, label: "Kame Energy" },
        "unmatched": { icon: GiMuscleUp, label: "Unknown Warriors" },
        "enmasse": { icon: GiResize, label: "Tournament Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Radar Signals" },
        "community": { icon: GiFist, label: "Z-Fighters" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Dragon Radar" },
        "achievements": { icon: GiTrophy, label: "Martial Arts Trophies" },
        "milestones": { icon: LuFlag, label: "Dragon Goals" },
        "theme-manager": { icon: GiPalette, label: "Gi Colors" },
        "extensions": { icon: BiExtension, label: "Technique Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Korin Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Power Level" },
    },
    achievementNames: {
        "a_first_episode": "Dragon Radar On",
        "a_first_complete": "Wish Granted",
        "a_hundred_club": "Hundred Balls Found",
        "a_time_lord": "Martial Arts Master",
        "a_anime_collector": "Dragon Ball Set",
        "a_library_legend": "Roshi's Library",
        "a_binge_king": "Training Marathon",
        "a_no_sleep": "All-Night Training",
        "a_marathon_runner": "World Martial Arts",
        "a_speed_run": "Goku Sprint",
        "a_completionist": "All Seven Balls",
        "a_mega_completionist": "Dragon Master",
        "a_loyal_fan": "Goku's Friend",
        "a_rewatcher": "Adventure Replay",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Martial Artist",
        "a_genre_adventure": "World Explorer",
        "a_genre_comedy": "Goku's Naivety",
        "a_genre_drama": "Tournament Drama",
        "a_genre_fantasy": "Dragon World",
        "a_genre_horror": "Piccolo Daimao",
        "a_genre_romance": "Chi-Chi's Love",
        "a_genre_scifi": "Nimbus Cloud",
        "a_genre_supernatural": "Dragon Power",
        "a_genre_psychological": "Goku's Heart",
        "a_genre_mecha": "Red Ribbon Army",
        "a_critic": "Roshi's Judge",
        "a_perfect_ten": "Perfect Punch",
        "a_harsh_critic": "Strict Trainer",
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Endless Training",
        "a_year_long": "Year of Adventure",
        "a_iron_will": "Never Give Up",
        "a_hidden_gem": "Hidden Dragon",
        "a_cult_classic": "Toriyama Classic",
        "a_classic_connoisseur": "86 Classic Fan",
        "a_new_years_resolution": "New Year Wish",
        "a_christmas_special": "Holiday Adventure",
        "a_meta_tier_max": "Goku's Level",
        "a_meta_completionist": "Complete Collection",
        "a_sequel_chain": "Z Awaits",
        "a_zero_to_hero": "Village Kid to Master",
        "a_night_owl": "Night Training",
        "a_early_bird": "Dawn Training",
        "m_first_chapter": "First Ball",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Marathon Read",
        "m_completionist": "Full Series",
        "m_mega_completionist": "Manga Master",
        "m_loyal_reader": "Z Fan",
        "m_rereader": "Adventure Revisit",
        "m_genre_action": "Fight Chapter",
        "m_genre_adventure": "Quest Chapter",
        "m_genre_romance": "Chi-Chi Chapter",
        "m_genre_fantasy": "Dragon World",
        "m_genre_horror": "Dark Chapter",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "Tech Chapter",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Deep Read",
        "m_critic": "Toriyama Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Training",
        "m_year_long": "Year Reading",
        "m_iron_will": "Goku's Spirit",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Dragon Classic",
        "m_mangaka_lover": "Toriyama Fan",
        "m_source_material_fan": "Original Reader",
        "m_meta_tier_max": "Dragon God",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Toriyama Art",
        "m_manga_to_anime": "Manga to Dragon",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060400",
        primary: "#dc7000",
        secondary: "#8c4400",
        accent: "#e8c830",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/dragon-ball.jpg",
    particleColor: "#f0a000",
    backgroundDim: 0.3,
    backgroundBlur: 18,
    particleTypes: {
        power_aura: { label: "Power Aura", maxCount: 12, defaultEnabled: true, defaultIntensity: 65 },
        stars: { label: "Stars", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1: "Village Kid",
        5: "Goku",
        15: "Kame Trainee",
        30: "Tournament Fighter",
        50: "World Champion",
        75: "Kami's Ally",
        100: "Dragon God",
    },
}
