import { AnimeThemeConfig } from "./types"
import { GiScooter, GiNightSleep, GiHandcuffs, GiKatana, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiPoliceBadge } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const durararaTheme: AnimeThemeConfig = {
    id: "durarara",
    displayName: "Durarara!!",
    description: "Ordinary high schooler Mikado Ryugamine moves to Ikebukuro and encounters a headless motorcycle rider, color-coded gangs, and an information broker who pulls the strings from the shadows.",
    fontFamily: "'Saira Condensed', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Saira+Condensed:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 235 140",
        "--color-brand-300": "248 218 80",
        "--color-brand-400": "228 195 15",
        "--color-brand-500": "195 162 0",
        "--color-brand-600": "155 126 0",
        "--color-brand-700": "115 92 0",
        "--color-brand-800": "76 60 0",
        "--color-brand-900": "44 34 0",
        "--color-brand-950": "24 18 0",
        "--brand": "195 162 0",
        "--background": "#040400",
        "--paper": "#0a0a02",
        "--color-gray-950": "4 4 0",
        "--color-gray-900": "10 10 2",
        "--color-gray-800": "18 18 5",
        "--color-gray-700": "32 32 9",
        "--color-gray-600": "52 52 16",
        "--color-gray-500": "80 80 28",
        "--color-gray-400": "118 118 55",
        "--color-gray-300": "158 158 95",
        "--color-gray-200": "192 192 135",
        "--color-gray-100": "218 218 172",
        "--color-gray-50": "240 240 212",
    },
    sidebarOverrides: {
        "home": { icon: GiNightSleep, label: "Ikebukuro" },
        "schedule": { icon: GiAlarmClock, label: "City Schedule" },
        "manga": { icon: LuBookOpen, label: "Info Files" },
        "lists": { icon: GiHandcuffs, label: "Character Web" },
        "discover": { icon: GiBullseye, label: "City Scouting" },
        "torrent-list": { icon: GiScooter, label: "Dullahan Cache" },
        "debrid": { icon: GiKatana, label: "Saika Store" },
        "unmatched": { icon: GiPoliceBadge, label: "Unknown Persons" },
        "enmasse": { icon: GiResize, label: "Gang Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Info Reports" },
        "auto-downloader": { icon: LuRss, label: "Dollars Network" },
        "community": { icon: GiNightSleep, label: "Dollars" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "City Alerts" },
        "achievements": { icon: GiTrophy, label: "Ikebukuro Titles" },
        "milestones": { icon: LuFlag, label: "Ikebukuro Goals" },
        "theme-manager": { icon: GiPalette, label: "Night Colors" },
        "extensions": { icon: BiExtension, label: "Info Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Dollars Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Shizuo's Rules" },
    },
    achievementNames: {
        "a_first_episode": "New to Ikebukuro",
        "a_first_complete": "City Web Solved",
        "a_hundred_club": "Hundred Characters",
        "a_time_lord": "Ikebukuro Veteran",
        "a_anime_collector": "Info Collection",
        "a_library_legend": "Izaya's Database",
        "a_binge_king": "City Marathon",
        "a_no_sleep": "All-Night City",
        "a_marathon_runner": "Celty's Ride",
        "a_speed_run": "Shizuo's Charge",
        "a_completionist": "All Threads",
        "a_mega_completionist": "Narita Master",
        "a_loyal_fan": "Dollars Member",
        "a_rewatcher": "City Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Shizuo Fight",
        "a_genre_adventure": "Ikebukuro Walk",
        "a_genre_comedy": "Simon's Sushi",
        "a_genre_drama": "Anri's Sword",
        "a_genre_fantasy": "Dullahan Legend",
        "a_genre_horror": "Saika Terror",
        "a_genre_romance": "Triangle Plot",
        "a_genre_scifi": "Celty's Science",
        "a_genre_supernatural": "Dullahan Power",
        "a_genre_psychological": "Izaya's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Info Judge",
        "a_perfect_ten": "Izaya's Plan",
        "a_harsh_critic": "Shizuo's Verdict",
        "a_daily_streak": "Daily Chat",
        "a_mega_streak": "Non-Stop Chat",
        "a_year_long": "Year in City",
        "a_iron_will": "Celty's Heart",
        "a_hidden_gem": "Hidden Thread",
        "a_cult_classic": "Narita Classic",
        "a_classic_connoisseur": "2004 Fan",
        "a_new_years_resolution": "New Year City",
        "a_christmas_special": "City Christmas",
        "a_meta_tier_max": "City Legend",
        "a_meta_completionist": "All Character Arcs",
        "a_sequel_chain": "x2",
        "a_zero_to_hero": "Bystander to Dollars",
        "a_night_owl": "Night City",
        "a_early_bird": "Morning Ikebukuro",
        "m_first_chapter": "First Encounter",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "City Marathon",
        "m_completionist": "Full Novel",
        "m_mega_completionist": "Durarara Expert",
        "m_loyal_reader": "Dollars Reader",
        "m_rereader": "City Return",
        "m_genre_action": "Fight Chapter",
        "m_genre_adventure": "City Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Dullahan Chapter",
        "m_genre_horror": "Saika Chapter",
        "m_genre_drama": "Anri Chapter",
        "m_genre_scifi": "Celty Chapter",
        "m_genre_supernatural": "Headless Chapter",
        "m_genre_psychological": "Izaya Depth",
        "m_critic": "City Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "City Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Celty Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Urban Classic",
        "m_mangaka_lover": "Narita Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Durarara Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Urban Art",
        "m_manga_to_anime": "Novel Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040400",
        primary: "#c3a200",
        secondary: "#7b6600",
        accent: "#e05050",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/durarara.jpg",
    particleColor: "#e0c820",
    backgroundDim: 0.42,
    backgroundBlur: 22,
    particleTypes: {
        city_lights: { label: "City Lights", maxCount: 20, defaultEnabled: true, defaultIntensity: 65 },
        shadow_bikes: { label: "Shadow Traces", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1: "New to Ikebukuro",
        5: "Mikado Ryugamine",
        15: "Dollars Member",
        30: "City Dweller",
        50: "Info Broker Rival",
        75: "Ikebukuro Legend",
        100: "City Master",
    },
}
