import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiSwordWound,
    GiChainedHeart,
    GiMuscleUp,
    GiCrossedSwords,
    GiHorseHead,
    GiFist,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const elfenLiedTheme: AnimeThemeConfig = {
    id: "elfen-lied",
    displayName: "Elfen Lied",
    description: "Lilium echoes through shattered silence. Diclonius vectors carve the dark, horns crowned in tragedy, as Lucy and Nyu drift between innocence and annihilation.",
    fontFamily: "'Crimson Text', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400&display=swap",
    cssVars: {
        // Brand → rose-red / blood-crimson
        "--color-brand-200": "235 160 175",
        "--color-brand-300": "225 120 145",
        "--color-brand-400": "215 85 115",
        "--color-brand-500": "200 50 80",
        "--color-brand-600": "170 40 65",
        "--color-brand-700": "135 30 50",
        "--color-brand-800": "100 20 38",
        "--color-brand-900": "65 12 25",
        "--color-brand-950": "35 6 14",
        "--brand": "200 50 80",
        // Dark tragic background
        "--background": "#0a0306",
        "--paper": "#140610",
        "--color-gray-950": "10 3 6",
        "--color-gray-900": "20 6 16",
        "--color-gray-800": "35 14 28",
        "--color-gray-700": "55 25 42",
        "--color-gray-600": "78 40 60",
        "--color-gray-500": "108 65 85",
        "--color-gray-400": "148 105 125",
        "--color-gray-300": "182 150 165",
        "--color-gray-200": "212 195 205",
        "--color-gray-100": "235 225 231",
        "--color-gray-50": "248 244 246",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Maple House" },
        "schedule": { icon: GiAlarmClock, label: "Lilium Schedule" },
        "manga": { icon: LuBookOpen, label: "Diclonius Files" },
        "lists": { icon: GiCrossedSwords, label: "Vector Registry" },
        "discover": { icon: GiBullseye, label: "Beyond the Shore" },
        "torrent-list": { icon: GiAnvilImpact, label: "Scattered Shells" },
        "debrid": { icon: GiHorseHead, label: "Escaped Subjects" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Memories" },
        "enmasse": { icon: GiResize, label: "Mass Infection" },
        "scan-summaries": { icon: TbReportSearch, label: "Research Logs" },
        "auto-downloader": { icon: LuRss, label: "Signal Echoes" },
        "community": { icon: GiEagleEmblem, label: "Facility Staff" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Horn Alerts" },
        "achievements": { icon: GiTrophy, label: "Tragic Milestones" },
        "theme-manager": { icon: GiPalette, label: "Bloodstained Hues" },
        "extensions": { icon: BiExtension, label: "Vector Arms" },
        "sync": { icon: IoCloudOfflineOutline, label: "Nyu Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Facility Control" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Vector Awakening",
        "a_episode_counter": "Diclonius Body Count",
        "a_episode_titan": "Queen-Class Encounter",
        "a_hours_invested": "Hours in Captivity",
        "a_time_lord": "Lilium Eternal Memory",
        "a_anime_collector": "Horned Arsenal",
        "a_library_legend": "Kouta's Lost Legend",
        "a_first_complete": "First Tragedy Complete",
        "a_hundred_club": "Century of Vectors",
        "a_first_day": "Day of Escape",
        "a_first_rating": "Subject Evaluation",
        "a_ten_thousand_min": "Ten Thousand Silent Minutes",
        "a_season_veteran": "Seasoned Witness",
        "a_year_explorer": "Year of Sorrow",
        "a_century_watcher": "Hundred-Episode Vigil",
        "a_five_hundred_eps": "Five Hundred Vectors Cast",
        "a_thousand_eps": "Thousand Broken Bonds",
        "a_watching_ten": "Ten Fractures Open",
        "a_ptw_hoarder": "Repressed Memories",
        "a_dropped_honesty": "Merciful Release",
        "a_five_thousand_eps": "Five Thousand Tears Shed",
        "a_ten_completed": "Ten Tragedies Witnessed",
        "a_fifty_completed": "Fifty Sorrows Endured",
        "a_five_hundred_completed": "Five Hundred Laments",
        "a_mean_score_tracker": "Average Pain Rating",
        "a_unique_studios": "Allied Facilities",
        "a_days_spent_watching": "Days Drifting Ashore",
        "a_all_status": "All Emotional States",
        "a_first_favorite": "First Precious Bond",
        "a_favorites_collector": "Cherished Remnants",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Vector Surge",
        "a_marathon_runner": "Shore-to-Shore Marathon",
        "a_weekend_warrior": "Weekend at Maple House",
        "a_non_stop": "Relentless Pursuit",
        "a_one_more_episode": "One More Memory",
        "a_speed_run": "Vector Speed Strike",
        "a_double_feature": "Dual Personality Shift",
        "a_triple_threat": "Triple Vector Lash",
        "a_five_a_day": "Five Fragments Daily",
        "a_back_to_back": "Back-to-Back Horrors",
        "a_seasonal_binge": "Full Tragic Arc",
        "a_cour_crusher": "District Bloodbath",
        "a_half_day_watch": "Half-Day Isolation",
        "a_full_day_watch": "Full Day Confined",
        "a_power_weekend": "Power Weekend Descent",
        "a_binge_king": "Monarch of Despair",
        "a_no_sleep": "All-Night Vigil at Shore",
        "a_entire_season": "Rapid Tragedy Clear",
        "a_seven_day_challenge": "Seven-Day Mourning",
        "a_hundred_day_binge": "Hundred-Day Confinement",
        "a_genre_binge": "Cross-Vector Training",
        "a_studio_binge": "Facility Binge Watch",
        "a_season_sweep": "Season Sweep Purge",
        "a_forty_eight_hour": "Forty-Eight Hour Lockdown",
        "a_ep_counter_day": "Daily Vector Count",
        "a_multi_series_binge": "Multi-Subject Observation",
        "a_midnight_binge": "Midnight Escape Run",
        "a_new_year_binge": "New Year's Vector Surge",

        // ── ANIME GENRES ──
        "a_genre_action": "Combat Vector",
        "a_genre_adventure": "Beyond the Facility",
        "a_genre_comedy": "Nyu's Innocent Laughter",
        "a_genre_drama": "Kouta's Tragic Vow",
        "a_genre_fantasy": "Diclonius Evolution",
        "a_genre_horror": "Horned Terror",
        "a_genre_mystery": "Origin Mystery",
        "a_genre_romance": "Fractured Love",
        "a_genre_scifi": "Vector Technology",
        "a_genre_sol": "Life at Maple House",
        "a_genre_sports": "Diclonius Training",
        "a_genre_supernatural": "Invisible Hand Power",
        "a_genre_thriller": "Facility Pursuit",
        "a_genre_mecha": "Anti-Diclonius Arms",
        "a_genre_music": "Lilium Resonance",
        "a_genre_psychological": "Lucy's Inner War",
        "a_genre_ecchi": "Beach Episode Innocence",
        "a_genre_mahou_shoujo": "Vector Wielder",
        "a_tag_isekai": "Transported to Shore",
        "a_tag_harem": "Maple House Bonds",
        "a_tag_bl": "Broken Brothers",
        "a_tag_gl": "Horn Sisters",
        "a_tag_historical": "Diclonius History",
        "a_tag_military": "Facility Discipline",
        "a_tag_school": "Childhood Academy",
        "a_tag_martial_arts": "Invisible Arm Combat",
        "a_tag_vampire": "Diclonius Bloodline",
        "a_tag_samurai": "Vector Blade Style",
        "a_tag_space": "Beyond the Horizon",
        "a_tag_parody": "Nyu Comedy Parody",
        "a_tag_idol": "Lilium Choir Idol",
        "a_tag_post_apocalyptic": "Post-Outbreak World",
        "a_tag_cyberpunk": "Facility Cybernetics",
        "a_tag_shounen": "Fight for Innocence",
        "a_tag_seinen": "Harsh Truth Unveiled",
        "a_tag_shoujo": "Nyu's Devotion",
        "a_tag_josei": "Yuka's Perseverance",
        "a_tag_survival": "Survival After Escape",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Tragedy Report",
        "a_mega_completionist": "Diclonius Queen",
        "a_completion_rate_50": "Halfway to Remembering",
        "a_completion_rate_75": "Approaching the Truth",
        "a_completion_rate_90": "Vectors Nearly Freed",
        "a_no_drop": "No Soul Abandoned",
        "a_long_runner_complete": "Long Suffering Endured",
        "a_sequel_chain": "Tragedy Chain Link",
        "a_clean_list": "Clean Conscience",
        "a_from_ptw": "Orders: Observe Subject",
        "a_rewatch_master": "Memory Replay Loop",
        "a_short_complete": "Quick Mercy Kill",
        "a_same_day_start_finish": "Same-Day Elimination",
        "a_revival": "Revived Personality",
        "a_zero_to_hero": "Nyu to Lucy",
        "a_five_genre_complete": "Five-Vector Mastery",
        "a_full_franchise": "Full Diclonius Dossier",
        "a_batch_complete": "Batch Containment Clear",
        "a_paused_to_done": "Returned from Amnesia",
        "a_completion_spree": "Completion Vector Burst",
        "a_multi_rewatch": "Multi-Timeline Memories",
        "a_dropped_recovery": "Recovered from Trauma",
        "a_ten_perfect_scores": "Ten Perfect Sorrows",
        "a_seasonal_clear": "Seasonal Purge Clear",
        "a_complete_genre_span": "All-Terrain Diclonius",
        "a_monthly_completions": "Monthly Tragedy Reports",
        "a_yearly_completions": "Yearly Sorrow Victor",
        "a_rapid_complete": "Lightning Vector Clear",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Maple Resident",
        "a_studio_devotee": "ARMS Studio Devotee",
        "a_rewatcher": "Tragedy Rewatch",
        "a_triple_rewatch": "Triple Sorrow Rewatch",
        "a_annual_tradition": "Annual Remembrance",
        "a_director_fan": "Kanbe's Vision",
        "a_voice_actor_fan": "Voice of the Horned",
        "a_ost_lover": "Lilium Eternally",
        "a_source_reader": "Okamoto's Original Text",
        "a_waiting_weekly": "Weekly Signal Wait",
        "a_childhood_revisit": "Return to Kamakura",
        "a_saga_tracker": "Saga of Lucy Tracked",
        "a_genre_loyalty": "Tragic Loyalty Badge",
        "a_decade_watcher": "Decade-Long Witness",
        "a_adaptation_hunter": "Adaptation Reconnaissance",
        "a_original_anime_fan": "Original Broadcast Mourner",
        "a_long_commitment": "Long-Term Confinement",
        "a_perfect_attendance": "Perfect Vigil Attendance",
        "a_favorite_studio_5": "Five Allied Facilities",
        "a_complete_catalog": "Complete Subject Catalog",
        "a_franchise_collector": "Diclonius Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Mastery Achieved",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Season Mourner",
        "a_format_diversity": "Diverse Tragic Formats",
        "a_year_dedication": "Year of Dedication",
        "a_season_dedication": "Season of Silent Grief",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Facility",
        "a_studio_hopper": "Facility Transfer",
        "a_tag_explorer": "Tag Recon Mission",
        "a_decade_hopper": "Decade Memory Shift",
        "a_hidden_gem": "Hidden Diclonius",
        "a_popular_taste": "Popular Among Subjects",
        "a_retro_appreciator": "Pre-Outbreak Classic",
        "a_modern_viewer": "Modern Tragedy Viewer",
        "a_cross_demographic": "Cross-Subject Scout",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Week of Varied Pain",
        "a_foreign_cinema": "Foreign Shore Cinema",
        "a_classic_connoisseur": "Classic Horror Connoisseur",
        "a_every_season": "Every Season Mourned",
        "a_award_winner": "Medal of Sorrow",
        "a_niche_explorer": "Niche Territory",
        "a_global_anime": "Global Infection Entry",
        "a_cult_classic": "Underground Cult Tragedy",
        "a_random_pick": "Random Subject File",
        "a_new_genre_month": "New Grief Monthly",
        "a_seasonal_completionist": "Seasonal Tragedy Clear",
        "a_unpopular_opinion": "Unpopular Mercy",
        "a_top_rated_viewer": "Top-Rated Subject File",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Descent",
        "a_upcoming_watcher": "Upcoming Subject Intel",
        "a_short_series_explorer": "Short Agony Explorer",
        "a_long_series_explorer": "Long Suffering Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Watch at Shore",
        "a_early_bird": "Dawn at Kamakura",
        "a_lunch_break": "Maple House Lunch",
        "a_golden_hour": "Golden Hour Lilium",
        "a_four_am_club": "4 AM Containment Breach",
        "a_witching_hour": "Diclonius Witching Hour",
        "a_new_year_watch": "New Year's Vow",
        "a_midnight_premiere": "Midnight Awakening",
        "a_all_hours": "All-Hours Observer",
        "a_dawn_warrior": "Dawn Vector Warrior",
        "a_afternoon_delight": "Afternoon at Shore",
        "a_prime_time": "Prime Time Emergence",
        "a_workday_watcher": "On-Duty Observer",
        "a_sunday_marathon": "Sunday Tragedy Marathon",
        "a_rainy_day": "Rainy Day at Maple",
        "a_morning_routine": "Morning at Maple House",
        "a_night_shift": "Night Shift Guard",
        "a_twilight_zone": "Twilight by the Sea",
        "a_seasonal_premier": "Season Premiere Horror",
        "a_clock_collector": "Clock Tower Remnant",
        "a_weekend_binge_hours": "Weekend Binge Descent",
        "a_late_night_regular": "Late Night Patrol",
        "a_sunrise_watcher": "Sunrise Over Kamakura",
        "a_holiday_watcher": "Holiday Vigil Duty",
        "a_every_day_of_week": "Every Day Mourning",
        "a_monthly_hours": "Monthly Confinement Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Gathering",
        "a_party_host": "Maple House Host",
        "a_social_butterfly": "Shore Socialite",
        "a_group_binge": "Group Vector Surge",
        "a_party_regular": "Regular Housemate",
        "a_sync_viewer": "Synchronized Vectors",
        "a_commentator": "Tragedy Commentator",
        "a_party_marathon": "Marathon Gathering",
        "a_full_house": "Full House Assembled",
        "a_community_pillar": "Pillar of Maple House",
        "a_watch_party_streak": "Consecutive Vigil Streak",
        "a_diverse_party": "Diverse Gathering",
        "a_late_night_party": "Late Night at Maple",
        "a_party_veteran": "Veteran Housemate",
        "a_genre_party": "Cross-Genre Gathering",
        "a_weekly_party": "Weekly Shore Meeting",
        "a_silent_viewer": "Silent Nyu Observer",
        "a_recommendation_giver": "Kouta's Recommendation",
        "a_party_completionist": "Gathering Completionist",
        "a_social_scorer": "Social Sorrow Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Vector",
        "a_fibonacci": "Fibonacci Horn Pattern",
        "a_palindrome_day": "Palindrome Memory Rift",
        "a_binary_day": "Binary Signal Day",
        "a_full_moon": "Full Moon Awakening",
        "a_leap_year": "Leap Year Time Skip",
        "a_time_traveler": "Lucy's Lost Memory",
        "a_genre_clash": "Nyu vs Lucy Clash",
        "a_triple_seven": "Triple Seven Vectors",
        "a_thousand_complete": "Thousand Tragedies",
        "a_pi_episodes": "Pi Vector Calculation",
        "a_synchronicity": "Diclonius Synchronicity",
        "a_world_record": "World Record Vector",
        "a_nice": "Nice Vector Count",
        "a_power_level": "Diclonius Power Level",
        "a_answer_42": "Answer to Lucy's Pain",
        "a_square_number": "Perfect Horn Formation",
        "a_prime_count": "Prime Diclonius Count",
        "a_matching_date": "Matching Memory Date",
        "a_century_episode": "Century Episode Vigil",
        "a_double_digits": "Double Digit Vectors",
        "a_one_two_three": "Lucy, Nyu, Kaede",
        "a_lucky_seven": "Seven Lucky Shells",
        "a_all_tens": "All Tens Sorrow Score",
        "a_exact_hundred_eps": "Exact Hundred Laments",
        "a_year_match_count": "Year Match Vector Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Witness",
        "a_movie_buff": "Tragic Film Witness",
        "a_ova_hunter": "OVA Lost Memories",
        "a_ona_explorer": "ONA Subject Explorer",
        "a_special_watcher": "Special Episode File",
        "a_short_king": "Short Agony King",
        "a_variety_pack": "All-Format Diclonius",
        "a_film_festival": "Tragic Film Festival",
        "a_music_video": "Lilium Collection",
        "a_tv_short": "Quick Recon Fragment",
        "a_movie_marathon": "Movie Marathon Vigil",
        "a_double_length": "Double-Length Torment",
        "a_anthology": "Diclonius Anthology",
        "a_mini_series": "Mini Tragedy Series",
        "a_theatrical": "Theatrical Sorrow",
        "a_format_master": "Format Master Witness",
        "a_long_movie": "Feature-Length Descent",
        "a_back_catalog": "Back Catalog Files",
        "a_cm_watcher": "Commercial Break Watch",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Tragic Formats",
        "a_episodic_master": "Episodic Tragedy Master",
        "a_sequel_movie": "Sequel Tragedy Film",
        "a_recap_watcher": "Recap Memory Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Vigil Streak",
        "a_mega_streak": "Mega Sorrow Streak",
        "a_weekly_warrior": "Weekly Shore Warrior",
        "a_monthly_watcher": "Monthly Confinement",
        "a_comeback": "Return from the Sea",
        "a_weekend_streak": "Weekend Vigil Streak",
        "a_no_zero_days": "No Zero Days Mourning",
        "a_iron_will": "Iron Will of Lucy",
        "a_habit_formed": "Tragic Habit Formed",
        "a_consistent_pace": "Consistent Descent",
        "a_year_long": "Year-Long Sorrow",
        "a_double_streak": "Double Streak Vector",
        "a_streak_recovery": "Amnesia Recovery",
        "a_daily_minimum": "Daily Minimum Grief",
        "a_winter_streak": "Winter Shore Streak",
        "a_summer_streak": "Summer Kamakura Streak",
        "a_morning_streak": "Morning Vigil Streak",
        "a_night_streak": "Night Patrol Streak",
        "a_unbreakable": "Unbreakable Diclonius Will",
        "a_eternal_flame": "Eternal Flame of Lilium",
        "a_completion_streak": "Completion Sorrow Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Episode Descent",
        "a_genre_streak": "Genre Streak Vigil",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Week of Grief",

        // ── ANIME SCORING ──
        "a_critic": "Facility Tribunal Judge",
        "a_perfect_ten": "Perfect 10 Tragedy",
        "a_harsh_critic": "Lucy's Harsh Judgment",
        "a_fair_judge": "Kouta's Fair Heart",
        "a_generous_spirit": "Generous Nyu Spirit",
        "a_score_all": "Full Subject Evaluation",
        "a_wide_range": "Wide Range Assessment",
        "a_controversial": "Controversial Mercy",
        "a_consistent_scorer": "Consistent Evaluator",
        "a_score_sniper": "Precision Vector Sniper",
        "a_evolving_taste": "Evolving Sorrow",
        "a_bell_curve": "Bell Curve of Pain",
        "a_picky_watcher": "Selective Observer",
        "a_100_rated": "Century of Evaluations",
        "a_500_rated": "Five Hundred Verdicts",
        "a_mediocre_majority": "Middle Ground Mercy",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Variable Pain Ratings",
        "a_masterpiece_hunter": "Masterpiece Tragedy Hunter",
        "a_contrarian": "Contrarian Diclonius",
        "a_optimist": "Optimist Despite Horrors",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Tragic Critic",
        "a_mean_above_8": "Elite Sorrow Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow of Peace",
        "a_valentines_weeb": "Valentine's Fractured Love",
        "a_pi_day": "Pi Day Vector Calc",
        "a_april_fools": "April Fools Nyu Prank",
        "a_international_anime_day": "International Diclonius Day",
        "a_star_wars_day": "Facility Empire Day",
        "a_summer_solstice": "Summer Solstice Shore",
        "a_tanabata": "Tanabata Wish for Peace",
        "a_friday_13th": "Friday 13th Outbreak",
        "a_halloween_spirit": "Halloween Horn Horror",
        "a_thanksgiving_binge": "Thanksgiving Maple Feast",
        "a_christmas_special": "Midwinter Shore Special",
        "a_new_years_eve": "New Year's Eve Last Stand",
        "a_birthday_watch": "Birthday Memory Watch",
        "a_holiday_marathon": "Holiday Tragedy Marathon",
        "a_independence_day": "Diclonius Freedom Day",
        "a_culture_day": "Kamakura Culture Day",
        "a_spring_equinox": "Spring Equinox Bloom",
        "a_earth_day": "Protect This Shore Day",
        "a_labor_day": "Facility Labor Day",
        "a_winter_solstice": "Winter Solstice Vigil",
        "a_anime_birthday": "Anime Anniversary Lament",
        "a_every_holiday": "Every Holiday Mourned",
        "a_consecutive_holidays": "Consecutive Holiday Vigils",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Horn Awakened",
        "a_meta_collector": "Diclonius Badge Collector",
        "a_meta_category_starter": "Category Initiation Rite",
        "a_meta_tier_climber": "Vector Rank Promotion",
        "a_meta_tier_max": "Queen-Class Rank",
        "a_meta_xp_earner": "XP from Vector Kills",
        "a_meta_difficulty_easy": "Easy Containment Drill",
        "a_meta_difficulty_hard": "Legendary: Lucy Unleashed",
        "a_meta_unlock_spree": "Unlock Spree Vector Burst",
        "a_meta_completionist": "Meta Completionist Queen",
        "a_meta_diverse": "Diverse Tragic Portfolio",
        "a_meta_dominator": "Meta Dominator of Vectors",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter of Sorrow",
        "m_chapter_counter": "Chapter Vector Counter",
        "m_chapter_titan": "Chapter Queen Assault",
        "m_reading_hours": "Hours Reading Files",
        "m_reading_time_lord": "Eternal Reading Memory",
        "m_manga_collector": "Diclonius Archive Collector",
        "m_library_legend": "Okamoto's Legend",
        "m_first_complete": "First Manga Tragedy Done",
        "m_hundred_club": "Hundred-Chapter Club",
        "m_first_day": "First Day Reading",
        "m_first_rating": "First Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Grief",
        "m_volume_collector": "Volume Stockpile",
        "m_year_explorer": "Year of Manga Sorrow",
        "m_century_reader": "Century-Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Chapters Read",
        "m_thousand_ch": "Thousand-Chapter Descent",
        "m_reading_ten": "Ten Manuscripts Open",
        "m_ptr_hoarder": "Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Merciful Drop",
        "m_season_reader": "Seasonal Reading Vigil",
        "m_active_reader": "Active Subject Reader",
        "m_five_thousand_ch": "Five Thousand Chapters Deep",
        "m_ten_completed": "Ten Manga Tragedies Done",
        "m_fifty_completed": "Fifty Manga Sorrows",
        "m_five_hundred_completed": "Five Hundred Manga Laments",
        "m_mean_score_tracker": "Average Manuscript Pain",
        "m_unique_authors": "Unique Author Encounters",
        "m_all_status": "All Reading States",
        "m_first_favorite": "First Manga Bond",
        "m_favorites_collector": "Manga Favorites Arsenal",
        "m_days_spent_reading": "Days Lost in Pages",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading Descent",
        "m_marathon_reader": "Shore-to-Shore Reading",
        "m_weekend_reader": "Weekend Maple Reading",
        "m_non_stop_reading": "Non-Stop Page Turning",
        "m_one_more_chapter": "One More Chapter Plea",
        "m_speed_read": "Vector Speed Read",
        "m_double_story": "Dual Personality Story",
        "m_triple_read": "Triple Reading Lash",
        "m_five_a_day": "Five Reads Daily",
        "m_chapter_chain": "Chapter Chain Despair",
        "m_volume_binge": "Volume Binge Torment",
        "m_power_reader": "Power Reader Witness",
        "m_half_day_read": "Half-Day Archive Dive",
        "m_full_day_read": "Full-Day Manuscript Grief",
        "m_power_weekend": "Power Weekend Reading",
        "m_binge_king": "Monarch of Reading",
        "m_no_sleep_read": "All-Night Shore Reading",
        "m_full_series_rush": "Full Series Rush",
        "m_seven_day_challenge": "Seven-Day Reading Vigil",
        "m_hundred_day_read": "Hundred-Day Reading Siege",
        "m_volume_rush": "Volume Rush Descent",
        "m_series_sweep": "Series Sweep Purge",
        "m_genre_binge": "Cross-Genre Reading",
        "m_author_binge": "Author Focused Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Count",
        "m_multi_series_binge": "Multi-Series Reading",
        "m_midnight_binge": "Midnight Archive Vigil",
        "m_new_year_binge": "New Year's Reading Surge",
        "m_forty_eight_hour": "Forty-Eight Hour Reading",
        "m_oneshot_binge": "Oneshot Blitz Attack",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Manuscript Vector",
        "m_genre_adventure": "Adventure Beyond Shore",
        "m_genre_comedy": "Comedy at Maple House",
        "m_genre_drama": "Drama of Lost Souls",
        "m_genre_fantasy": "Fantasy of Horns",
        "m_genre_horror": "Horror Manuscript File",
        "m_genre_mystery": "Mystery of Origins",
        "m_genre_romance": "Romance Torn Apart",
        "m_genre_scifi": "Sci-Fi Vector Science",
        "m_genre_sol": "Slice of Maple Life",
        "m_genre_sports": "Subject Training Sports",
        "m_genre_supernatural": "Supernatural Vector Powers",
        "m_genre_thriller": "Thriller Facility Report",
        "m_genre_psychological": "Psychological Warfare Reader",
        "m_genre_isekai": "Isekai Beyond the Shore",
        "m_genre_shounen": "Shounen Heart of Nyu",
        "m_genre_ecchi": "Innocent Beach Chapter",
        "m_genre_mahou_shoujo": "Vector Power Wielder",
        "m_genre_mecha": "Anti-Diclonius Weapons",
        "m_genre_music": "Lilium Folk Songs",
        "m_tag_isekai_new": "New World Beyond Sea",
        "m_tag_harem": "Maple House Bonds",
        "m_tag_bl": "Brothers in Grief",
        "m_tag_gl": "Sisters in Sorrow",
        "m_tag_historical": "Diclonius History Manga",
        "m_tag_military": "Facility Operations Manga",
        "m_tag_school": "Childhood Academy Manga",
        "m_tag_martial_arts": "Vector Combat Manual",
        "m_tag_vampire": "Diclonius Blood Manga",
        "m_tag_samurai": "Blade Master Manga",
        "m_tag_space": "Beyond the Horizon",
        "m_tag_parody": "Chibi Nyu Manga",
        "m_tag_idol": "Lilium Choir Manga",
        "m_tag_post_apocalyptic": "Post-Outbreak Manga",
        "m_tag_cyberpunk": "Facility Tech Manga",
        "m_tag_shoujo": "Nyu's Story Manga",
        "m_tag_survival": "Survival Manga",
        "m_tag_cooking": "Maple House Cookbook",
        "m_tag_medical": "Facility Medic Manga",
        "m_tag_villainess": "Queen Candidate Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Tragedy Complete",
        "m_mega_completionist": "Supreme Manga Witness",
        "m_completion_rate_50": "Halfway to Truth",
        "m_completion_rate_75": "Approaching the Shore",
        "m_completion_rate_90": "Final Chapter Near",
        "m_no_drop": "No Manuscript Abandoned",
        "m_long_runner_complete": "Long Sorrow Endurance",
        "m_sequel_chain": "Sequel Chain Tragedy",
        "m_clean_list": "Clean Reading Conscience",
        "m_from_ptr": "Orders: Read Subject File",
        "m_reread_master": "Memory Replay Reread",
        "m_oneshot_complete": "Oneshot Mission Done",
        "m_same_day_start_finish": "Same-Day Reading Blitz",
        "m_revival": "Revival Through Amnesia",
        "m_zero_to_hundred": "Nyu to Scholar",
        "m_five_genre_complete": "Five-Genre Mastery",
        "m_full_collection": "Full Archive Collection",
        "m_batch_complete": "Batch Clearance Done",
        "m_paused_to_done": "Back from Hiatus",
        "m_completion_spree": "Completion Barrage",
        "m_format_completionist": "Format Completion Badge",
        "m_catch_up": "Caught Up with Series",
        "m_multi_reread": "Multi-Pass Reread",
        "m_dropped_recovery": "Recovered from Rubble",
        "m_ten_perfect_scores": "Ten Perfect Manuscripts",
        "m_complete_genre_span": "All-Genre Reading",
        "m_monthly_completions": "Monthly Manuscript Wins",
        "m_yearly_completions": "Yearly Reading Lament",
        "m_rapid_complete": "Rapid Intel Processing",
        "m_author_complete": "Author's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Shore Reader",
        "m_mangaka_lover": "Okamoto Devotee",
        "m_rereader": "Tragedy Rereader",
        "m_triple_reread": "Triple Reread Sorrow",
        "m_annual_reread": "Annual Remembrance Reread",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Artist Appreciation",
        "m_adaptation_compare": "Manga vs Anime Compare",
        "m_source_material_fan": "Source Material Witness",
        "m_waiting_weekly": "Weekly Chapter Vigil",
        "m_classic_reader": "Classic Manuscript Reader",
        "m_saga_reader": "Saga of Lucy Reader",
        "m_genre_loyalty": "Genre Loyalty Badge",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "Light Novel Adaptation",
        "m_original_work": "Original Manga Work",
        "m_long_commitment": "Long Reading Commitment",
        "m_up_to_date": "Up-to-Date with Files",
        "m_favorite_mangaka": "Favorite Mangaka Honored",
        "m_complete_portfolio": "Complete Reading Portfolio",
        "m_franchise_collector": "Diclonius Franchise Files",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Mastery Earned",
        "m_multi_series_author": "Multi-Series Author Fan",
        "m_format_diversity": "Diverse Reading Formats",
        "m_year_dedication": "Year of Dedicated Reading",
        "m_ongoing_follower": "Ongoing Series Follower",
        "m_genre_loyalty_50": "Fifty Genre Loyalty",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Territory Scout",
        "m_publisher_hopper": "Publisher Transfer",
        "m_tag_explorer": "Manga Tag Recon",
        "m_decade_hopper": "Decade-Hopping Memories",
        "m_hidden_gem": "Hidden Diclonius Gem",
        "m_popular_taste": "Popular Among Subjects",
        "m_retro_reader": "Retro Manuscript Reader",
        "m_modern_reader": "Modern Era Reader",
        "m_cross_demographic": "Cross-Demographic Scout",
        "m_underdog_fan": "Underdog Subject Fan",
        "m_variety_week": "Week of Varied Reads",
        "m_manhwa_reader": "Manhwa Intelligence",
        "m_manhua_reader": "Manhua Intelligence",
        "m_classic_connoisseur": "Classic Horror Manuscript",
        "m_award_winner": "Medal-Winning Manuscript",
        "m_niche_explorer": "Niche Territory Reader",
        "m_world_manga": "World Manga Intel",
        "m_cult_classic": "Cult Classic Tragedy",
        "m_random_pick": "Random Reading File",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Reading Complete",
        "m_unpopular_opinion": "Unpopular Tragic Opinion",
        "m_top_rated_reader": "Top-Rated Subject File",
        "m_source_variety": "Source Material Variety",
        "m_low_score_brave": "Brave Low-Score Reader",
        "m_short_manga_explorer": "Short Manga Fragment",
        "m_long_manga_explorer": "Long Manuscript Descent",
        "m_serialization_explorer": "Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Shore Reader",
        "m_early_bird": "Dawn Kamakura Reader",
        "m_lunch_reader": "Maple House Lunch Read",
        "m_commute_reader": "Travel to Shore Reader",
        "m_four_am_club": "4 AM Containment Reader",
        "m_new_year_read": "New Year's Reading Vow",
        "m_all_hours": "All-Hours Archive Access",
        "m_prime_time_reader": "Prime Time Manuscript",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Reading Vigil",
        "m_morning_routine": "Morning Maple Reading",
        "m_night_shift_reader": "Night Shift Reader",
        "m_seasonal_premier_read": "New Release Intel",
        "m_clock_collector": "Clock Tower Reading",
        "m_late_night_horror": "Midnight Horror Read",
        "m_afternoon_reader": "Afternoon Shore Reading",
        "m_golden_hour_reader": "Golden Hour Reading",
        "m_dawn_reader": "Dawn Reading Witness",
        "m_twilight_reader": "Twilight Shore Reading",
        "m_midnight_start": "Midnight Reading Vigil",
        "m_weekend_binge_hours": "Weekend Binge Reading",
        "m_late_night_regular": "Late Night Regular",
        "m_sunrise_reader": "Sunrise Over Shore",
        "m_every_day_of_week": "Every Day Reading",
        "m_monthly_hours": "Monthly Reading Hours",
        "m_bedtime_reader": "Bedtime Maple Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Okamoto Art Appreciator",
        "m_webtoon_reader": "Webtoon Intelligence",
        "m_full_color": "Full Color Manuscript",
        "m_doujin_reader": "Underground Doujin Reader",
        "m_anthology_reader": "Anthology Collection",
        "m_adaptation_reader": "Adaptation Study Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Comedy Shorts",
        "m_oneshot_reader": "Oneshot Mission Reader",
        "m_format_variety": "Format Tragic Variety",
        "m_light_novel_reader": "Light Novel Reader",
        "m_novel_reader": "Novel Archive Reader",
        "m_visual_storyteller": "Visual Sorrow Narrator",
        "m_colored_classic": "Colored Classic File",
        "m_webcomic_fan": "Webcomic Underground",
        "m_manga_to_anime": "Manga to Anime Compare",
        "m_seinen_reader": "Seinen Tragedy Reader",
        "m_josei_reader": "Josei Perspective Reader",
        "m_award_winning_art": "Medal-Winning Artwork",
        "m_debut_work": "Debut Manuscript",
        "m_vertical_scroll": "Vertical Scroll Intel",
        "m_traditional_format": "Traditional Format Reader",
        "m_cross_media": "Cross-Media Intelligence",
        "m_spinoff_reader": "Spinoff Mission Reader",
        "m_remake_reader": "Remake Reading File",
        "m_collaboration_reader": "Joint Operation Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Reading Vigil",
        "m_mega_streak": "Mega Reading Streak",
        "m_weekly_warrior": "Weekly Warrior Reader",
        "m_monthly_reader": "Monthly Shore Reader",
        "m_comeback": "Reader's Return",
        "m_weekend_streak": "Weekend Reading Streak",
        "m_no_zero_days": "No Zero Reading Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Habit Formed",
        "m_consistent_pace": "Consistent Reading Pace",
        "m_year_long": "Year-Long Reading",
        "m_double_streak": "Double Reading Streak",
        "m_streak_recovery": "Reading Streak Recovery",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Reading Vigil",
        "m_summer_streak": "Summer Reading Descent",
        "m_morning_streak": "Morning Reading Streak",
        "m_night_streak": "Night Reading Patrol",
        "m_unbreakable": "Unbreakable Reading Will",
        "m_eternal_flame": "Eternal Lilium Knowledge",
        "m_chapter_a_day": "Chapter a Day Vigil",
        "m_genre_streak": "Genre Reading Streak",
        "m_completion_streak": "Completion Reading Chain",
        "m_rating_streak": "Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Dedication Streak",
        "m_perfect_week_manga": "Perfect Reading Week",
        "m_diverse_streak": "Diverse Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Facility Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Manuscript",
        "m_harsh_critic": "Lucy's Reading Standards",
        "m_fair_judge": "Kouta's Fair Review",
        "m_generous_spirit": "Generous Reader Spirit",
        "m_score_all": "Full Manuscript Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Reading",
        "m_consistent_scorer": "Consistent Scorer",
        "m_score_sniper": "Precision Score Sniper",
        "m_evolving_taste": "Evolving Reading Taste",
        "m_bell_curve": "Bell Curve of Scores",
        "m_picky_reader": "Selective Reader",
        "m_100_rated": "Century of Ratings",
        "m_500_rated": "Five Hundred Verdicts",
        "m_mediocre_majority": "Middle Ground Reader",
        "m_rating_spree": "Rating Barrage Filed",
        "m_score_variance": "Variable Scores",
        "m_binge_rater": "Binge Rating Session",
        "m_reread_rerate": "Reread & Re-Rate",
        "m_masterpiece_hunter": "Masterpiece Tragedy Hunter",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimistic Reader",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Reading Critic",
        "m_mean_above_8": "Elite Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Reading Vow",
        "m_valentines_read": "Valentine's Reading Bond",
        "m_pi_day": "Pi Day Chapter Count",
        "m_april_fools": "April Fools Nyu Corps",
        "m_international_manga_day": "International Manga Day",
        "m_free_comic_day": "Free Comic Shore Day",
        "m_summer_solstice": "Summer Solstice Reading",
        "m_tanabata": "Tanabata Reading Wish",
        "m_friday_13th": "Friday 13th Horror Read",
        "m_halloween_read": "Halloween Horror Reading",
        "m_thanksgiving_binge": "Thanksgiving Reading Feast",
        "m_christmas_read": "Midwinter Shore Reading",
        "m_new_years_eve": "New Year's Eve Final Read",
        "m_birthday_read": "Birthday Reading Gift",
        "m_holiday_marathon": "Holiday Reading Marathon",
        "m_independence_day": "Diclonius Freedom Read",
        "m_culture_day": "Culture Day Manuscript",
        "m_spring_equinox": "Spring Equinox Reading",
        "m_earth_day": "Earth Day Shore Read",
        "m_labor_day": "Facility Labor Reading",
        "m_winter_solstice": "Winter Solstice Reading",
        "m_manga_birthday": "Manga Birthday Lament",
        "m_every_holiday_reader": "Every Holiday Reader",
        "m_consecutive_holidays": "Consecutive Holiday Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Milestone",
        "m_fibonacci": "Fibonacci Chapter Pattern",
        "m_palindrome_day": "Palindrome Reading Day",
        "m_binary_day": "Binary Signal Reading",
        "m_full_moon_read": "Full Moon Vector Read",
        "m_leap_year_read": "Leap Year Reading",
        "m_triple_seven": "Triple Seven Vectors Read",
        "m_thousand_complete": "Thousand Manga Tragedies",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Diclonius-Level Chapters",
        "m_answer_42": "Answer to Lucy's Reading",
        "m_square_number": "Perfect Vector Chapters",
        "m_prime_count": "Prime Chapter Count",
        "m_matching_date": "Matching Memory Reading",
        "m_century_chapter": "Century Chapter Vigil",
        "m_pi_chapters": "Pi Chapter Calculation",
        "m_synchronicity": "Diclonius Synchronicity",
        "m_world_record": "World Record Chapters",
        "m_genre_clash": "Genre Clash Reading",
        "m_time_traveler": "Time-Traveling Reader",
        "m_double_digits": "Double Digit Milestone",
        "m_one_two_three": "Lucy Nyu Kaede",
        "m_lucky_seven": "Seven Lucky Chapters",
        "m_exact_hundred_ch": "Exact Hundred Read",
        "m_year_match_count": "Year Match Chapters",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Manhwa Format Reader",
        "m_manhua_format": "Manhua Format Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Done",
        "m_doujin_format": "Doujin Format Reader",
        "m_novel_format": "Novel Format Reader",
        "m_format_master_manga": "Format Master Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Reading Awakened",
        "m_meta_collector": "Reading Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Reading Rank",
        "m_meta_xp_earner": "XP from Reading Intel",
        "m_meta_difficulty_easy": "Easy Reading Drill",
        "m_meta_difficulty_hard": "Legendary Manuscript",
        "m_meta_unlock_spree": "Reading Unlock Barrage",
        "m_meta_completionist": "Meta Reading Complete",
        "m_meta_diverse": "Diverse Reading Portfolio",
        "m_meta_dominator": "Meta Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#0a0306",
        primary: "#c83250",
        secondary: "#aa2841",
        accent: "#eba0af",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        blood_drops: { label: "Blood Drops", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        vector_trails: { label: "Vector Trails", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        sakura_petals: { label: "Sakura Petals", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        horn_glow: { label: "Horn Glow", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Human",
        5:   "Witness",
        15:  "Diclonius",
        30:  "Vector User",
        45:  "Escaped",
        60:  "Queen",
        80:  "Lilium",
        100: "Lucy",
    },
}
