import { AnimeThemeConfig } from "./types"
import {
    GiEagleEmblem,
    GiCrossedSwords,
    GiSwordWound,
    GiChainedHeart,
    GiMuscleUp,
    GiAnvilImpact,
    GiResize,
    GiStarSwirl,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiSettingsKnobs,
    GiSpellBook,
    GiFist,
    GiFlame,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const evangelionTheme: AnimeThemeConfig = {
    id: "evangelion",
    displayName: "Neon Genesis Evangelion",
    description: "Get in the Eva. AT-Fields, Angel battles, NERV headquarters, Third Impact, and the weight of Instrumentality crushing every nerve.",
    fontFamily: "'Oswald', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap",
    cssVars: {
        "--color-brand-200": "210 180 240",
        "--color-brand-300": "185 145 225",
        "--color-brand-400": "165 115 215",
        "--color-brand-500": "136 85 204",
        "--color-brand-600": "108 62 172",
        "--color-brand-700": "82 42 138",
        "--color-brand-800": "56 26 100",
        "--color-brand-900": "34 14 64",
        "--color-brand-950": "16 4 32",
        "--brand": "136 85 204",
        "--background": "#050308",
        "--paper": "#0a0510",
        "--color-gray-950": "5 3 8",
        "--color-gray-900": "12 8 18",
        "--color-gray-800": "22 14 32",
        "--color-gray-700": "36 24 52",
        "--color-gray-600": "55 38 78",
        "--color-gray-500": "82 60 112",
        "--color-gray-400": "120 95 150",
        "--color-gray-300": "162 138 188",
        "--color-gray-200": "200 182 218",
        "--color-gray-100": "228 218 238",
        "--color-gray-50": "244 240 250",
    },
    sidebarOverrides: {
        "home": { icon: GiEagleEmblem, label: "NERV Headquarters" },
        "schedule": { icon: GiAlarmClock, label: "Battle Schedule" },
        "manga": { icon: GiSpellBook, label: "NERV Archives" },
        "lists": { icon: GiCrossedSwords, label: "Angel Kill List" },
        "discover": { icon: GiStarSwirl, label: "Beyond the AT-Field" },
        "torrent-list": { icon: GiAnvilImpact, label: "Evangelion Arsenal" },
        "debrid": { icon: GiFist, label: "Entry Plug Access" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Souls" },
        "enmasse": { icon: GiResize, label: "Mass Production Evas" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "MAGI Signal Feed" },
        "community": { icon: GiMuscleUp, label: "Pilot Union" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Angel Alert" },
        "achievements": { icon: GiTrophy, label: "Synch Rate Rewards" },
        "theme-manager": { icon: GiPalette, label: "Eva Unit Colors" },
        "extensions": { icon: BiExtension, label: "Prog Knife Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Dirac Sea Sync" },
        "settings": { icon: GiSettingsKnobs, label: "MAGI Command" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Sortie in Eva-01",
        "a_episode_counter": "Synch Rate Counter",
        "a_episode_titan": "Angel-Class Encounter",
        "a_hours_invested": "Hours in the Entry Plug",
        "a_time_lord": "Eternal AT-Field Memory",
        "a_anime_collector": "NERV Data Archive",
        "a_library_legend": "Dead Sea Scrolls Vault",
        "a_first_complete": "First Angel Defeated",
        "a_hundred_club": "Hundred Synch Points",
        "a_first_day": "Pilot Candidate Day One",
        "a_first_rating": "First Synch Rating",
        "a_ten_thousand_min": "Ten Thousand Minutes in Combat",
        "a_season_veteran": "Veteran Eva Pilot",
        "a_year_explorer": "Year Defending Against Angels",
        "a_century_watcher": "Century of Battles",
        "a_five_hundred_eps": "Five Hundred AT-Fields Broken",
        "a_thousand_eps": "Thousand Angel Encounters",
        "a_watching_ten": "Ten Units Monitored",
        "a_ptw_hoarder": "SEELE Classified Hoarder",
        "a_dropped_honesty": "Refused to Get in the Eva",
        "a_five_thousand_eps": "Five Thousand Plug Depth Hours",
        "a_ten_completed": "Ten Scenarios Completed",
        "a_fifty_completed": "Fifty Combat Operations",
        "a_five_hundred_completed": "Five Hundred Angel Kills",
        "a_mean_score_tracker": "Average Synch Rate",
        "a_unique_studios": "Allied NERV Branches",
        "a_days_spent_watching": "Days Inside NERV",
        "a_all_status": "All Pilot Statuses Logged",
        "a_first_favorite": "First Soul Connection",
        "a_favorites_collector": "Eva Pilot Bond Archive",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Berserk Mode Activated",
        "a_marathon_runner": "Third Impact Marathon",
        "a_weekend_warrior": "Weekend Pilot Training",
        "a_non_stop": "Non-Stop AT-Field Burn",
        "a_one_more_episode": "One More Angel to Kill",
        "a_speed_run": "Progressive Knife Speed",
        "a_double_feature": "Double Angel Sortie",
        "a_triple_threat": "Triple Eva Deployment",
        "a_five_a_day": "Five Angels in a Day",
        "a_back_to_back": "Consecutive Combat Sorties",
        "a_seasonal_binge": "Full Campaign Arc",
        "a_cour_crusher": "Instrumentality Arc",
        "a_half_day_watch": "Half-Day in the Entry Plug",
        "a_full_day_watch": "Full Day at NERV HQ",
        "a_power_weekend": "Power Weekend Combat Ops",
        "a_binge_king": "Instrumentality King",
        "a_no_sleep": "All-Night Angel Alert",
        "a_entire_season": "Rapid Campaign Clear",
        "a_seven_day_challenge": "Seven Angels in Seven Days",
        "a_hundred_day_binge": "Hundred-Day Siege of Tokyo-3",
        "a_genre_binge": "Cross-Genre Eva Binge",
        "a_studio_binge": "GAINAX Studio Marathon",
        "a_season_sweep": "Season Angel Sweep",
        "a_forty_eight_hour": "Forty-Eight Hour Third Impact",
        "a_ep_counter_day": "Daily Angel Kill Count",
        "a_multi_series_binge": "Multi-Eva Universe Binge",
        "a_midnight_binge": "Midnight NERV Briefing",
        "a_new_year_binge": "New Year's Impact",

        // ── ANIME GENRES ──
        "a_genre_action": "Eva Combat Specialist",
        "a_genre_adventure": "Beyond the AT-Field",
        "a_genre_comedy": "Pen-Pen Moment",
        "a_genre_drama": "Shinji's Burden",
        "a_genre_fantasy": "Rei's Ethereal World",
        "a_genre_horror": "Angel Horror Survivor",
        "a_genre_mystery": "Dead Sea Scroll Mystery",
        "a_genre_romance": "Asuka's Hidden Heart",
        "a_genre_scifi": "Evangelion Technology",
        "a_genre_sol": "Life Inside NERV",
        "a_genre_sports": "Eva Combat Sparring",
        "a_genre_supernatural": "AT-Field Power",
        "a_genre_thriller": "Angel Pursuit Thriller",
        "a_genre_mecha": "Eva Unit Mecha Fan",
        "a_genre_music": "Fly Me to the Moon",
        "a_genre_psychological": "Mind Inside the Eva",
        "a_genre_ecchi": "Asuka's Impact Moment",
        "a_genre_mahou_shoujo": "Rei's Quiet Power",
        "a_tag_isekai": "Transported to Instrumentality",
        "a_tag_harem": "Pilot Program Bonds",
        "a_tag_bl": "Kaworu's Gentle Bond",
        "a_tag_gl": "Female Pilot Alliance",
        "a_tag_historical": "Second Impact History",
        "a_tag_military": "NERV Military Protocol",
        "a_tag_school": "Shinji's School Days",
        "a_tag_martial_arts": "Eva Close Combat",
        "a_tag_vampire": "Angel Blood Type",
        "a_tag_samurai": "Progressive Knife Blade",
        "a_tag_space": "Beyond Human Instrumentality",
        "a_tag_parody": "Shinji Playing Cello Parody",
        "a_tag_idol": "Voice of the Angels",
        "a_tag_post_apocalyptic": "Post-Second Impact World",
        "a_tag_cyberpunk": "MAGI Supercomputer Age",
        "a_tag_shounen": "Get in the Eva Shinji",
        "a_tag_seinen": "Psychological Warfare",
        "a_tag_shoujo": "Rei's Quiet Devotion",
        "a_tag_josei": "Misato's Perspective",
        "a_tag_survival": "Survival Inside the Eva",

        // ── ANIME COMPLETION ──
        "a_completionist": "All Angels Eliminated",
        "a_mega_completionist": "Yui Ikari Memorial",
        "a_completion_rate_50": "Halfway to Third Impact",
        "a_completion_rate_75": "Approaching Instrumentality",
        "a_completion_rate_90": "AT-Field Nearly Dissolved",
        "a_no_drop": "Never Left the Entry Plug",
        "a_long_runner_complete": "Long Campaign Survival",
        "a_sequel_chain": "Rebuild Chain Complete",
        "a_clean_list": "Clean Combat Record",
        "a_from_ptw": "Mission Orders Fulfilled",
        "a_rewatch_master": "Rebirth Rewatch Master",
        "a_short_complete": "Quick Sortie Victory",
        "a_same_day_start_finish": "Same-Day Angel Kill",
        "a_revival": "Eva Awakening Revival",
        "a_zero_to_hero": "Third Child to Legend",
        "a_five_genre_complete": "Five-Genre Mastery",
        "a_full_franchise": "Full Eva Universe",
        "a_batch_complete": "Batch Angel Clearance",
        "a_paused_to_done": "Returned from Introspection",
        "a_completion_spree": "Angel Elimination Spree",
        "a_multi_rewatch": "Multiple Timeline Rewatches",
        "a_dropped_recovery": "Recovered from Rejection",
        "a_ten_perfect_scores": "Ten Perfect Synch Scores",
        "a_seasonal_clear": "Seasonal Angel Clear",
        "a_complete_genre_span": "All-Terrain Pilot",
        "a_monthly_completions": "Monthly Mission Reports",
        "a_yearly_completions": "Yearly Campaign Victories",
        "a_rapid_complete": "Lightning Spear Blitz",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Evangelion Fan",
        "a_studio_devotee": "GAINAX/Khara Devotee",
        "a_rewatcher": "Rebuild Re-watcher",
        "a_triple_rewatch": "Triple Impact Replay",
        "a_annual_tradition": "Annual Impact Day",
        "a_director_fan": "Anno's Vision Follower",
        "a_voice_actor_fan": "Shinji's Voice Fan",
        "a_ost_lover": "A Cruel Angel's Thesis Fan",
        "a_source_reader": "Manga Yui Path",
        "a_waiting_weekly": "Weekly Signal Wait",
        "a_childhood_revisit": "Return to Tokyo-3",
        "a_saga_tracker": "Instrumentality Saga",
        "a_genre_loyalty": "Mecha Genre Loyalty",
        "a_decade_watcher": "Decade of Eva Devotion",
        "a_adaptation_hunter": "Rebuild Adaptation Hunter",
        "a_original_anime_fan": "Original 1995 Fan",
        "a_long_commitment": "Long-Term NERV Service",
        "a_perfect_attendance": "Perfect Combat Attendance",
        "a_favorite_studio_5": "Five Favorite Studios",
        "a_complete_catalog": "Complete Eva Catalog",
        "a_franchise_collector": "Eva Universe Collector",
        "a_airing_follower": "Currently Airing Pilot",
        "a_genre_master": "Genre Mastery Unlocked",
        "a_staff_follower": "Production Staff Tracker",
        "a_multi_season_fan": "Multi-Season Eva Fan",
        "a_format_diversity": "Diverse Eva Formats",
        "a_year_dedication": "Year of Evangelion",
        "a_season_dedication": "Season of Sacrifice",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Angel Territory Explorer",
        "a_studio_hopper": "Studio Transfer",
        "a_tag_explorer": "Tag Recon Mission",
        "a_decade_hopper": "Time Across Impacts",
        "a_hidden_gem": "Hidden NERV Secret",
        "a_popular_taste": "Fan Favorite Angel Arc",
        "a_retro_appreciator": "Retro 1995 Appreciator",
        "a_modern_viewer": "Rebuild Era Viewer",
        "a_cross_demographic": "Cross-Audience Pilot",
        "a_underdog_fan": "Underdog Third Child",
        "a_variety_week": "Week of Varied Angels",
        "a_foreign_cinema": "Foreign Impact Cinema",
        "a_classic_connoisseur": "Classic Eva Connoisseur",
        "a_every_season": "Every Season Deployed",
        "a_award_winner": "Medal of Instrumentality",
        "a_niche_explorer": "Niche Angel Explorer",
        "a_global_anime": "Global NERV Alliance",
        "a_cult_classic": "Cult Classic Evangelion",
        "a_random_pick": "Random Angel Assignment",
        "a_new_genre_month": "New Genre Impact",
        "a_seasonal_completionist": "Seasonal Campaign Clear",
        "a_unpopular_opinion": "Controversial Ending Take",
        "a_top_rated_viewer": "Top-Rated Battle Viewer",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Against Negative AT",
        "a_upcoming_watcher": "Upcoming Rebuild Scout",
        "a_short_series_explorer": "Short Sortie Explorer",
        "a_long_series_explorer": "Long Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Watch at NERV",
        "a_early_bird": "Dawn Alert Pilot",
        "a_lunch_break": "Cafeteria Break",
        "a_golden_hour": "Golden Hour AT-Field",
        "a_four_am_club": "4 AM Angel Alert",
        "a_witching_hour": "Witching Hour Angel",
        "a_new_year_watch": "New Year's Impact Watch",
        "a_midnight_premiere": "Midnight Deployment",
        "a_all_hours": "All-Hours NERV Pilot",
        "a_dawn_warrior": "Dawn Warrior Pilot",
        "a_afternoon_delight": "Afternoon Sync Test",
        "a_prime_time": "Prime Time Combat",
        "a_workday_watcher": "On-Duty Watcher",
        "a_sunday_marathon": "Sunday Marathon Sorties",
        "a_rainy_day": "Rainy Tokyo-3 Day",
        "a_morning_routine": "Morning Sync Session",
        "a_night_shift": "Night Shift NERV",
        "a_twilight_zone": "Twilight AT-Field",
        "a_seasonal_premier": "Season Opening Sortie",
        "a_clock_collector": "Time of Death Collector",
        "a_weekend_binge_hours": "Weekend Angel Campaign",
        "a_late_night_regular": "Late Night Regular Pilot",
        "a_sunrise_watcher": "Sunrise Over Tokyo-3",
        "a_holiday_watcher": "Holiday NERV Watch",
        "a_every_day_of_week": "Every Day in Eva",
        "a_monthly_hours": "Monthly Combat Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Pilot Squad",
        "a_party_host": "NERV Commander",
        "a_social_butterfly": "Children of NERV",
        "a_group_binge": "Group Third Impact Watch",
        "a_party_regular": "Regular Sync Partner",
        "a_sync_viewer": "Synchronized AT-Field",
        "a_commentator": "Battle Commentator",
        "a_party_marathon": "Marathon Angel Battle",
        "a_full_house": "Full Pilot Roster",
        "a_community_pillar": "Pillar of NERV",
        "a_watch_party_streak": "Consecutive Battle Streak",
        "a_diverse_party": "Diverse Pilot Party",
        "a_late_night_party": "Late Night Briefing",
        "a_party_veteran": "Veteran Watch Party",
        "a_genre_party": "Cross-Genre Pilot Party",
        "a_weekly_party": "Weekly NERV Gathering",
        "a_silent_viewer": "Silent Rei Observer",
        "a_recommendation_giver": "Commander's Recommendation",
        "a_party_completionist": "Squad Mission Completionist",
        "a_social_scorer": "Synch Harmony Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Milestone",
        "a_fibonacci": "Fibonacci Angel Sequence",
        "a_palindrome_day": "Palindrome Impact Day",
        "a_binary_day": "Binary AT-Field Day",
        "a_full_moon": "Full Moon Third Impact",
        "a_leap_year": "Leap Year Rebuild",
        "a_time_traveler": "AT-Field Time Traveler",
        "a_genre_clash": "Pilot vs Angel Clash",
        "a_triple_seven": "Triple Seven Units",
        "a_thousand_complete": "Thousand Angel Kills",
        "a_pi_episodes": "Pi Sequence Pilot",
        "a_synchronicity": "Perfect Synch Achieved",
        "a_world_record": "World Record Synch Rate",
        "a_nice": "Nice AT-Field",
        "a_power_level": "Ackerman Power Level",
        "a_answer_42": "Answer to Instrumentality",
        "a_square_number": "Perfect Eva Formation",
        "a_prime_count": "Prime Number of Angels",
        "a_matching_date": "Matching Impact Date",
        "a_century_episode": "Century Episode Angel",
        "a_double_digits": "Double Digit Synch Rate",
        "a_one_two_three": "First Second Third Child",
        "a_lucky_seven": "Seven Lucky Angels",
        "a_all_tens": "All Tens Synch Score",
        "a_exact_hundred_eps": "Exact Hundred Episodes",
        "a_year_match_count": "Year Match Angel Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Pilot",
        "a_movie_buff": "EoE Cinema Fan",
        "a_ova_hunter": "Death and Rebirth Hunter",
        "a_ona_explorer": "ONA Scout Pilot",
        "a_special_watcher": "Special NERV Report",
        "a_short_king": "Short Sortie King",
        "a_variety_pack": "All-Format Pilot",
        "a_film_festival": "Eva Film Festival",
        "a_music_video": "Evangelion OST Collector",
        "a_tv_short": "Quick Sync Clip",
        "a_movie_marathon": "Rebuild Movie Marathon",
        "a_double_length": "Double-Length Mission",
        "a_anthology": "Eva Anthology Archive",
        "a_mini_series": "Mini Eva Collection",
        "a_theatrical": "Theatrical Impact",
        "a_format_master": "Format Master Pilot",
        "a_long_movie": "Feature-Length Instrumentality",
        "a_back_catalog": "Back Catalog Eva Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Tactical Formats",
        "a_episodic_master": "Episodic Angel Master",
        "a_sequel_movie": "Sequel Rebuild Film",
        "a_recap_watcher": "Recap Briefing Pilot",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Pilot Streak",
        "a_mega_streak": "Mega Combat Streak",
        "a_weekly_warrior": "Weekly Warrior Pilot",
        "a_monthly_watcher": "Monthly NERV Duty",
        "a_comeback": "Return from Introspection",
        "a_weekend_streak": "Weekend Sortie Streak",
        "a_no_zero_days": "No Zero Days in Eva",
        "a_iron_will": "Iron Will Pilot",
        "a_habit_formed": "Training Regimen Formed",
        "a_consistent_pace": "Consistent Synch Pace",
        "a_year_long": "Year-Long NERV Campaign",
        "a_double_streak": "Double Sortie Streak",
        "a_streak_recovery": "Medical Corps Recovery",
        "a_daily_minimum": "Daily Minimum Duty",
        "a_winter_streak": "Winter Campaign Streak",
        "a_summer_streak": "Summer Angel Streak",
        "a_morning_streak": "Morning Drill Streak",
        "a_night_streak": "Night Patrol Streak",
        "a_unbreakable": "Unbreakable Will",
        "a_eternal_flame": "Eternal Flame of Humanity",
        "a_completion_streak": "Completion Mission Chain",
        "a_rating_streak": "Rating Report Streak",
        "a_multi_ep_streak": "Multi-Episode Offensive",
        "a_genre_streak": "Genre Streak Sortie",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Combat Week",

        // ── ANIME SCORING ──
        "a_critic": "SEELE Tribunal Judge",
        "a_perfect_ten": "Perfect Synch Rating",
        "a_harsh_critic": "Gendo's Harsh Standards",
        "a_fair_judge": "Ritsuko's Fair Analysis",
        "a_generous_spirit": "Misato's Generous Spirit",
        "a_score_all": "Full Pilot Evaluation",
        "a_wide_range": "Wide Synch Assessment",
        "a_controversial": "Controversial Impact Opinion",
        "a_consistent_scorer": "Consistent Evaluator",
        "a_score_sniper": "Precision AT-Field Sniper",
        "a_evolving_taste": "Evolving Pilot Strategy",
        "a_bell_curve": "Bell Curve of Angels",
        "a_picky_watcher": "Selective Commander",
        "a_100_rated": "Century of Evaluations",
        "a_500_rated": "Five Hundred Field Reports",
        "a_mediocre_majority": "Middle Ground Strategist",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Variable Combat Ratings",
        "a_masterpiece_hunter": "Masterpiece Angel Hunt",
        "a_contrarian": "Contrarian Pilot Opinion",
        "a_optimist": "Optimist Despite the Angels",
        "a_score_distributor": "Score Distributor General",
        "a_genre_critic": "Genre Combat Critic",
        "a_mean_above_8": "Elite Synch Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Pilot Vow",
        "a_valentines_weeb": "Valentine's Third Child",
        "a_pi_day": "Pi Day AT-Calculation",
        "a_april_fools": "April Fools Angel Prank",
        "a_international_anime_day": "International Pilot Day",
        "a_star_wars_day": "SEELE Empire Day",
        "a_summer_solstice": "Summer Solstice Sortie",
        "a_tanabata": "Tanabata Wish for Humanity",
        "a_friday_13th": "Friday 13th Angel Attack",
        "a_halloween_spirit": "Halloween Angel Horror",
        "a_thanksgiving_binge": "NERV Cafeteria Feast",
        "a_christmas_special": "Christmas Impact Special",
        "a_new_years_eve": "New Year's Eve Final Stand",
        "a_birthday_watch": "Birthday Pilot Watch",
        "a_holiday_marathon": "Holiday Mission Marathon",
        "a_independence_day": "Human Independence Day",
        "a_culture_day": "NERV Culture Day",
        "a_spring_equinox": "Spring Awakening Sortie",
        "a_earth_day": "Protect This World Day",
        "a_labor_day": "NERV Labor Day",
        "a_winter_solstice": "Winter Solstice Watch",
        "a_anime_birthday": "Eva Anniversary Day",
        "a_every_holiday": "Every Holiday Pilot",
        "a_consecutive_holidays": "Consecutive Holiday Sorties",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Eva Power Unlocked",
        "a_meta_collector": "NERV Badge Collector",
        "a_meta_category_starter": "Category Initiation",
        "a_meta_tier_climber": "Pilot Rank Promotion",
        "a_meta_tier_max": "Supreme Pilot Rank",
        "a_meta_xp_earner": "XP from Angel Kills",
        "a_meta_difficulty_easy": "Easy Training Scenario",
        "a_meta_difficulty_hard": "Legendary Third Impact",
        "a_meta_unlock_spree": "Unlock Spree Berserk",
        "a_meta_completionist": "Meta Completionist Commander",
        "a_meta_diverse": "Diverse Pilot Portfolio",
        "a_meta_dominator": "Meta Angel Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter in the Eva",
        "m_chapter_counter": "Chapter Synch Counter",
        "m_chapter_titan": "Angel-Class Chapter",
        "m_reading_hours": "Hours in NERV Archives",
        "m_reading_time_lord": "Dead Sea Scroll Library",
        "m_manga_collector": "NERV Manga Archive",
        "m_library_legend": "Yui's Library Legend",
        "m_first_complete": "First Manga Sortie Done",
        "m_hundred_club": "Hundred Chapter Pilot",
        "m_first_day": "First Day Reading",
        "m_first_rating": "First Chapter Rated",
        "m_ten_thousand_pages": "Ten Thousand Pages of Intel",
        "m_volume_collector": "Volume Stockpile",
        "m_year_explorer": "Year Reading Explorer",
        "m_century_reader": "Century Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Chapters",
        "m_thousand_ch": "Thousand Chapter Campaign",
        "m_reading_ten": "Ten Manuscripts at Once",
        "m_ptr_hoarder": "Reading Backlog Hoarder",
        "m_dropped_honesty": "Abandoned Like Shinji",
        "m_season_reader": "Seasonal Reading Cycle",
        "m_active_reader": "Active Field Reader",
        "m_five_thousand_ch": "Five Thousand Chapters Deep",
        "m_ten_completed": "Ten Manga Complete",
        "m_fifty_completed": "Fifty Manga Done",
        "m_five_hundred_completed": "Five Hundred Complete",
        "m_mean_score_tracker": "Average Manuscript Score",
        "m_unique_authors": "Unique Author Encounters",
        "m_all_status": "All Reading Statuses",
        "m_first_favorite": "First Manga Favorite",
        "m_favorites_collector": "Manga Favorites Archive",
        "m_days_spent_reading": "Days in the Archives",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Angel Arc",
        "m_marathon_reader": "Instrumentality Marathon",
        "m_weekend_reader": "Weekend NERV Reading",
        "m_non_stop_reading": "Non-Stop Page Assault",
        "m_one_more_chapter": "One More Angel Chapter",
        "m_speed_read": "Prog Knife Speed Read",
        "m_double_story": "Double Manga Feature",
        "m_triple_read": "Triple Reading Assault",
        "m_five_a_day": "Five Chapters a Day",
        "m_chapter_chain": "Chapter Chain Offensive",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader Pilot",
        "m_half_day_read": "Half-Day Archive Dive",
        "m_full_day_read": "Full-Day Reading Mission",
        "m_power_weekend": "Power Weekend Reading",
        "m_binge_king": "King of the Reading Corps",
        "m_no_sleep_read": "All-Night Reading Session",
        "m_full_series_rush": "Full Series Rush",
        "m_seven_day_challenge": "Seven-Day Reading",
        "m_hundred_day_read": "Hundred-Day Reading",
        "m_volume_rush": "Volume Rush Deployment",
        "m_series_sweep": "Series Sweep Operation",
        "m_genre_binge": "Cross-Genre Reading",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Count",
        "m_multi_series_binge": "Multi-Series Reading",
        "m_midnight_binge": "Midnight Archive Session",
        "m_new_year_binge": "New Year's Reading",
        "m_forty_eight_hour": "Forty-Eight Hour Read",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Manga Fan",
        "m_genre_adventure": "Adventure Beyond Eva",
        "m_genre_comedy": "Comedy in NERV Cafeteria",
        "m_genre_drama": "Drama of Instrumentality",
        "m_genre_fantasy": "Fantasy AT-Field World",
        "m_genre_horror": "Titan Horror in the Eva",
        "m_genre_mystery": "Mystery of the Angels",
        "m_genre_romance": "Love Under the AT-Field",
        "m_genre_scifi": "Sci-Fi MAGI Technology",
        "m_genre_sol": "Slice of NERV Life",
        "m_genre_sports": "Eva Combat Sports",
        "m_genre_supernatural": "Supernatural AT Powers",
        "m_genre_thriller": "Thriller Intelligence Report",
        "m_genre_psychological": "Psychological Warfare Reader",
        "m_genre_isekai": "Isekai to Instrumentality",
        "m_genre_shounen": "Shounen Heart of Shinji",
        "m_genre_ecchi": "Asuka's Chapter",
        "m_genre_mahou_shoujo": "Rei's Quiet Power Manga",
        "m_genre_mecha": "Eva Unit Manga Fan",
        "m_genre_music": "Angel Music Manuscript",
        "m_tag_isekai_new": "New World Summoned",
        "m_tag_harem": "Pilot Squadron Manga",
        "m_tag_bl": "Shinji and Kaworu Manga",
        "m_tag_gl": "Female Pilot Manga",
        "m_tag_historical": "Second Impact History",
        "m_tag_military": "NERV Military Manga",
        "m_tag_school": "Shinji's School Manga",
        "m_tag_martial_arts": "Eva Combat Manual",
        "m_tag_vampire": "Angel Blood Manga",
        "m_tag_samurai": "Prog Knife Blade Manga",
        "m_tag_space": "Beyond Space Manga",
        "m_tag_parody": "Chibi Eva Parody",
        "m_tag_idol": "Yui's Memory Manga",
        "m_tag_post_apocalyptic": "Post-Impact Manga",
        "m_tag_cyberpunk": "MAGI Technology Manga",
        "m_tag_shoujo": "Rei's Story Manga",
        "m_tag_survival": "Survival in the Eva",
        "m_tag_cooking": "NERV Cafeteria Manga",
        "m_tag_medical": "Field Medic Manga",
        "m_tag_villainess": "SEELE Dark Plans",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Campaign Complete",
        "m_mega_completionist": "Supreme NERV Commander",
        "m_completion_rate_50": "Halfway to the Truth",
        "m_completion_rate_75": "Approaching the Core",
        "m_completion_rate_90": "Final Chapter Near",
        "m_no_drop": "No Manuscript Abandoned",
        "m_long_runner_complete": "Long Series Endurance",
        "m_sequel_chain": "Rebuild Chain Complete",
        "m_clean_list": "Clean Reading Record",
        "m_from_ptr": "Orders Read Executed",
        "m_reread_master": "Rebuild Reread Master",
        "m_oneshot_complete": "Oneshot Specialist",
        "m_same_day_start_finish": "Same-Day Angel Read",
        "m_revival": "Revival Through Eva",
        "m_zero_to_hundred": "Third Child to Scholar",
        "m_five_genre_complete": "Five-Genre Mastery",
        "m_full_collection": "Full Archive Collection",
        "m_batch_complete": "Batch Clearance",
        "m_paused_to_done": "Back from Reflection",
        "m_completion_spree": "Completion Barrage",
        "m_format_completionist": "Format Completion Badge",
        "m_catch_up": "Caught Up with the Angels",
        "m_multi_reread": "Multi-Pass Reread",
        "m_dropped_recovery": "Recovered from Despair",
        "m_ten_perfect_scores": "Ten Perfect Scores",
        "m_complete_genre_span": "All-Genre Reading Scout",
        "m_monthly_completions": "Monthly Victories",
        "m_yearly_completions": "Yearly Reading Campaign",
        "m_rapid_complete": "Rapid Intel Processing",
        "m_author_complete": "Author's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal NERV Reader",
        "m_mangaka_lover": "Sadamoto Devotee",
        "m_rereader": "Rebuild Rereader",
        "m_triple_reread": "Triple Reread Expedition",
        "m_annual_reread": "Annual Remembrance Reread",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Artist Appreciation",
        "m_adaptation_compare": "Manga vs Anime Compare",
        "m_source_material_fan": "Source Material Scout",
        "m_waiting_weekly": "Weekly Chapter Wait",
        "m_classic_reader": "Classic Eva Reader",
        "m_saga_reader": "Saga of Instrumentality",
        "m_genre_loyalty": "Mecha Genre Loyalty",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "Light Novel Intel",
        "m_original_work": "Original Eva Manga",
        "m_long_commitment": "Long-Term Reading",
        "m_up_to_date": "Up-to-Date Reader",
        "m_favorite_mangaka": "Favorite Mangaka",
        "m_complete_portfolio": "Complete Portfolio",
        "m_franchise_collector": "Eva Universe Collector",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Mastery Earned",
        "m_multi_series_author": "Multi-Series Author Fan",
        "m_format_diversity": "Diverse Reading Formats",
        "m_year_dedication": "Year of Dedicated Reading",
        "m_ongoing_follower": "Ongoing Series Follower",
        "m_genre_loyalty_50": "Fifty Genre Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Territory Scout",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Manga Tag Recon",
        "m_decade_hopper": "Decade-Hopping Reader",
        "m_hidden_gem": "Hidden NERV Gem",
        "m_popular_taste": "Popular Angel Arc",
        "m_retro_reader": "Retro Era Reader",
        "m_modern_reader": "Modern Era Reader",
        "m_cross_demographic": "Cross-Demographic Scout",
        "m_underdog_fan": "Underdog Shinji Fan",
        "m_variety_week": "Week of Varied Reads",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Warfare Manuscript",
        "m_award_winner": "Medal-Winning Manuscript",
        "m_niche_explorer": "Niche Territory Reader",
        "m_world_manga": "World Manga Reader",
        "m_cult_classic": "Cult Classic Underground",
        "m_random_pick": "Random Assignment",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Reading Complete",
        "m_unpopular_opinion": "Controversial Eva Opinion",
        "m_top_rated_reader": "Top-Rated Source",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Low-Score Reader",
        "m_short_manga_explorer": "Short Manga Explorer",
        "m_long_manga_explorer": "Long Campaign Manuscript",
        "m_serialization_explorer": "Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl NERV Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "NERV Cafeteria Reader",
        "m_commute_reader": "Commute to NERV Reader",
        "m_four_am_club": "4 AM Angel Alert Reader",
        "m_new_year_read": "New Year's Reading",
        "m_all_hours": "All-Hours Archive Access",
        "m_prime_time_reader": "Prime Time Reader",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Reading Marathon",
        "m_morning_routine": "Morning Reading Routine",
        "m_night_shift_reader": "Night Shift Reader",
        "m_seasonal_premier_read": "New Release Read",
        "m_clock_collector": "Clock Collector",
        "m_late_night_horror": "Midnight Angel Horror",
        "m_afternoon_reader": "Afternoon Reader",
        "m_golden_hour_reader": "Golden Hour Reader",
        "m_dawn_reader": "Dawn Reading Scout",
        "m_twilight_reader": "Twilight Wall Reading",
        "m_midnight_start": "Midnight Reading Start",
        "m_weekend_binge_hours": "Weekend Read Hours",
        "m_late_night_regular": "Late Night Regular",
        "m_sunrise_reader": "Sunrise Reader",
        "m_every_day_of_week": "Every Day Reading",
        "m_monthly_hours": "Monthly Hours Logged",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Sadamoto Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color Manuscript",
        "m_doujin_reader": "Underground Doujin Reader",
        "m_anthology_reader": "Anthology Collection",
        "m_adaptation_reader": "Adaptation Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Comedy Shorts",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel Reader",
        "m_novel_reader": "Novel Archive Reader",
        "m_visual_storyteller": "Visual Storyteller",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga to Anime Compare",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award-Winning Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll Reader",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross-Media Intel",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collaboration Reader",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Reading Streak",
        "m_mega_streak": "Mega Reading Streak",
        "m_weekly_warrior": "Weekly Warrior",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader Comeback",
        "m_weekend_streak": "Weekend Read Streak",
        "m_no_zero_days": "No Zero Reading Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Habit Formed",
        "m_consistent_pace": "Consistent Reading Pace",
        "m_year_long": "Year-Long Reading",
        "m_double_streak": "Double Reading Streak",
        "m_streak_recovery": "Reading Streak Recovery",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Reading Streak",
        "m_summer_streak": "Summer Reading Streak",
        "m_morning_streak": "Morning Reading Streak",
        "m_night_streak": "Night Reading Streak",
        "m_unbreakable": "Unbreakable Reader",
        "m_eternal_flame": "Eternal Flame of Reading",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Reading Streak",
        "m_completion_streak": "Completion Chain",
        "m_rating_streak": "Rating Streak",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Dedication Streak",
        "m_perfect_week_manga": "Perfect Reading Week",
        "m_diverse_streak": "Diverse Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "SEELE Manuscript Critic",
        "m_perfect_ten": "Perfect Ten Rating",
        "m_harsh_critic": "Gendo's Reading Standards",
        "m_fair_judge": "Ritsuko's Fair Review",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Full Assessment",
        "m_wide_range": "Wide Score Range",
        "m_controversial": "Controversial Opinion",
        "m_consistent_scorer": "Consistent Scorer",
        "m_score_sniper": "Precision Score Sniper",
        "m_evolving_taste": "Evolving Reading Taste",
        "m_bell_curve": "Bell Curve of Scores",
        "m_picky_reader": "Picky Pilot Reader",
        "m_100_rated": "Century of Ratings",
        "m_500_rated": "Five Hundred Reports",
        "m_mediocre_majority": "Middle Ground Reader",
        "m_rating_spree": "Rating Barrage",
        "m_score_variance": "Variable Scores",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread and Rerate",
        "m_masterpiece_hunter": "Masterpiece Hunter",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimist Reader",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Reading Vow",
        "m_valentines_read": "Valentine's Reading Bond",
        "m_pi_day": "Pi Day Chapter Count",
        "m_april_fools": "April Fools Chibi Eva",
        "m_international_manga_day": "International Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Solstice Reading",
        "m_tanabata": "Tanabata Reading Wish",
        "m_friday_13th": "Friday 13th Angel Read",
        "m_halloween_read": "Halloween Horror Reading",
        "m_thanksgiving_binge": "Thanksgiving Reading Feast",
        "m_christmas_read": "Christmas Reading",
        "m_new_years_eve": "New Year's Eve Final Read",
        "m_birthday_read": "Birthday Reading Gift",
        "m_holiday_marathon": "Holiday Reading Marathon",
        "m_independence_day": "Independence Day Read",
        "m_culture_day": "Culture Day Manuscript",
        "m_spring_equinox": "Spring Equinox Reading",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Reading",
        "m_winter_solstice": "Winter Solstice Reading",
        "m_manga_birthday": "Manga Birthday Read",
        "m_every_holiday_reader": "Every Holiday Reader",
        "m_consecutive_holidays": "Consecutive Holiday Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Chapter",
        "m_fibonacci": "Fibonacci Chapter Pattern",
        "m_palindrome_day": "Palindrome Read Day",
        "m_binary_day": "Binary Read Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Reading",
        "m_triple_seven": "Triple Seven Chapters",
        "m_thousand_complete": "Thousand Manga Complete",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Synch Level Chapters",
        "m_answer_42": "Answer 42 Chapters",
        "m_square_number": "Perfect Formation Chapters",
        "m_prime_count": "Prime Chapter Count",
        "m_matching_date": "Matching Read Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters Read",
        "m_synchronicity": "Read Synchronicity",
        "m_world_record": "World Record Chapters",
        "m_genre_clash": "Genre Clash Reading",
        "m_time_traveler": "Time-Traveling Reader",
        "m_double_digits": "Double Digit Chapters",
        "m_one_two_three": "One Two Three Children",
        "m_lucky_seven": "Seven Lucky Chapters",
        "m_exact_hundred_ch": "Exact Hundred Chapters",
        "m_year_match_count": "Year Match Chapter Count",
        "m_chapter_match_date": "Chapter Match Date",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Manhwa Reader",
        "m_manhua_format": "Manhua Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Eva Power Unlocked",
        "m_meta_collector": "Reading Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Reading Rank",
        "m_meta_xp_earner": "XP from Reading",
        "m_meta_difficulty_easy": "Easy Reading Mode",
        "m_meta_difficulty_hard": "Legendary Reading Challenge",
        "m_meta_unlock_spree": "Reading Unlock Barrage",
        "m_meta_completionist": "Meta Reading Completionist",
        "m_meta_diverse": "Diverse Reading Portfolio",
        "m_meta_dominator": "Meta Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050308",
        primary: "#8855cc",
        secondary: "#6a3eac",
        accent: "#cc3333",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/evangelion.jpg",
    particleColor: "#4c8c50",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        at_field_hexagons: { label: "AT-Field Hexagons", maxCount: 12, defaultEnabled: true, defaultIntensity: 60 },
        eva_eyes: { label: "Eva Eyes", maxCount: 6, defaultEnabled: true, defaultIntensity: 45 },
        angel_fragments: { label: "Angel Fragments", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        eva_blood: { label: "Eva Blood", maxCount: 8, defaultEnabled: true, defaultIntensity: 40 },
    },
    playerIconOverrides: undefined,
    milestoneNames: {
        1:   "Pilot Candidate",
        5:   "First Sortie",
        15:  "AT-Field Active",
        30:  "100% Synch",
        45:  "Eva Berserk",
        60:  "Third Impact",
        80:  "Rei's Clone",
        100: "Instrumentality",
    },
}
