import { AnimeThemeConfig } from "./types"
import { fairyTailPlayerIcons } from "./player-icons"
import {
    GiCastle,
    GiFairyWand,
    GiCrownedSkull,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiCrossedSwords,
    GiResize,
    GiSettingsKnobs,
    GiScrollUnfurled,
    GiStarFormation,
    GiFireRing,
    GiDragonHead,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const fairyTailTheme: AnimeThemeConfig = {
    id: "fairy-tail",
    displayName: "Fairy Tail",
    description: "Join the wildest guild in Fiore — Fairy Tail magic, dragon slayer flames, and bonds of friendship in warm pink-magenta splendor.",
    fontFamily: "'Boogaloo', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Boogaloo&display=swap",
    cssVars: {
        // Brand → warm pink / magenta guild palette
        "--color-brand-200": "220 120 180",
        "--color-brand-300": "210 100 160",
        "--color-brand-400": "200 80 140",
        "--color-brand-500": "180 60 120",
        "--color-brand-600": "155 45 100",
        "--color-brand-700": "130 34 82",
        "--color-brand-800": "100 24 64",
        "--color-brand-900": "70 16 46",
        "--color-brand-950": "44 10 30",
        "--brand": "200 80 140",
        // Dark navy backgrounds
        "--background": "#06040a",
        "--paper": "#0e0814",
        // Warm purple-tinted grays
        "--color-gray-950": "6 4 12",
        "--color-gray-900": "16 10 24",
        "--color-gray-800": "30 22 42",
        "--color-gray-700": "48 38 64",
        "--color-gray-600": "72 58 92",
        "--color-gray-500": "100 84 120",
        "--color-gray-400": "140 120 160",
        "--color-gray-300": "178 162 194",
        "--color-gray-200": "210 198 222",
        "--color-gray-100": "230 224 238",
        "--color-gray-50": "244 240 248",
    },
    sidebarOverrides: {
        "home": { icon: GiFairyWand, label: "Guild Hall" },
        "schedule": { icon: GiAlarmClock, label: "Request Board" },
        "manga": { icon: LuBookOpen, label: "Sorcerer Magazine" },
        "lists": { icon: GiScrollUnfurled, label: "Guild Registry" },
        "discover": { icon: GiBullseye, label: "Grand Magic Games" },
        "torrent-list": { icon: GiCrossedSwords, label: "S-Class Quest" },
        "debrid": { icon: GiDragonHead, label: "Dragon Slayer Cache" },
        "unmatched": { icon: GiFireRing, label: "Dark Guild Targets" },
        "enmasse": { icon: GiResize, label: "Allied Forces" },
        "scan-summaries": { icon: TbReportSearch, label: "Council Reports" },
        "auto-downloader": { icon: LuRss, label: "Lacrima Feed" },
        "community": { icon: GiStarFormation, label: "Wizard Saints" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Guild Alerts" },
        "achievements": { icon: GiTrophy, label: "Fairy Law Rankings" },
        "theme-manager": { icon: GiPalette, label: "Guild Emblem Design" },
        "extensions": { icon: BiExtension, label: "Lacrima Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "Fairy Sphere" },
        "settings": { icon: GiCastle, label: "Master's Orders" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Quest Accepted",
        "a_episode_counter": "Job Request Counter",
        "a_episode_titan": "Dragon Force Unleashed",
        "a_hours_invested": "Hours Spent in the Guild Hall",
        "a_time_lord": "Arc of Time Mastery",
        "a_anime_collector": "Lacrima Collector",
        "a_library_legend": "Legend of the Grand Library",
        "a_first_complete": "First Quest Complete",
        "a_hundred_club": "Century of Guild Deeds",
        "a_first_day": "First Day at Fairy Tail",
        "a_first_rating": "First Wizard Ranking",
        "a_ten_thousand_min": "Ten Thousand Minutes of Magic",
        "a_season_veteran": "Veteran Guild Wizard",
        "a_year_explorer": "Year in Fiore",
        "a_century_watcher": "Hundred-Episode Wizard Journey",
        "a_five_hundred_eps": "Five Hundred Dragon Flames",
        "a_thousand_eps": "Thousand Celestial Spells",
        "a_watching_ten": "Ten Guilds United",
        "a_ptw_hoarder": "Request Board Hoarder",
        "a_dropped_honesty": "Retreated from the Tower of Heaven",
        "a_five_thousand_eps": "Five Thousand Ethernano Pulses",
        "a_ten_completed": "Ten Quests Accomplished",
        "a_fifty_completed": "Fifty Dark Mages Defeated",
        "a_five_hundred_completed": "Five Hundred Battles Won",
        "a_mean_score_tracker": "Average Guild Rating",
        "a_unique_studios": "Allied Magic Guilds",
        "a_days_spent_watching": "Days at the Guild Hall",
        "a_all_status": "All Quest Statuses Filed",
        "a_first_favorite": "First Nakama Bond",
        "a_favorites_collector": "Fairy Tail Family Bonds",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Guild Brawl",
        "a_marathon_runner": "Grand Magic Games Marathon",
        "a_weekend_warrior": "Weekend S-Class Trial",
        "a_non_stop": "Relentless Dragon Slayer Charge",
        "a_one_more_episode": "One More Round at the Bar",
        "a_speed_run": "Fire Dragon Iron Fist Rush",
        "a_double_feature": "Unison Raid Double Strike",
        "a_triple_threat": "Triple Dragon Slayer Combo",
        "a_five_a_day": "Five Quests by Sundown",
        "a_back_to_back": "Back-to-Back Brawl Victories",
        "a_seasonal_binge": "Full Arc Grand Magic Games",
        "a_cour_crusher": "S-Class Exam Crusher",
        "a_half_day_watch": "Half-Day at the Guild Bar",
        "a_full_day_watch": "Full Day Training with Gildarts",
        "a_power_weekend": "Power Weekend in Magnolia",
        "a_binge_king": "King of the Fairy Festival",
        "a_no_sleep": "All-Night Phantom Lord Siege",
        "a_entire_season": "Full Arc Tenrou Island",
        "a_seven_day_challenge": "Seven-Day Dragon Training",
        "a_hundred_day_binge": "Hundred-Day Magic Grind",
        "a_genre_binge": "Cross-Guild Training Arc",
        "a_studio_binge": "A-1 Pictures & Satelight Binge",
        "a_season_sweep": "Season Sweep of Fiore",
        "a_forty_eight_hour": "Forty-Eight Hour Eclipse Gate",
        "a_ep_counter_day": "Daily Guild Patrol Count",
        "a_multi_series_binge": "Multi-Guild Task Force",
        "a_midnight_binge": "Midnight Dragon Slayer Watch",
        "a_new_year_binge": "New Year's Ethernano Surge",

        // ── ANIME GENRES ──
        "a_genre_action": "Dragon Slayer Combat Specialist",
        "a_genre_adventure": "Journey Across Fiore",
        "a_genre_comedy": "Natsu & Happy Comedy Hour",
        "a_genre_drama": "Erza's Tower of Heaven",
        "a_genre_fantasy": "Magic of Earthland",
        "a_genre_horror": "Tartaros Underworld Horror",
        "a_genre_mystery": "Mystery of the Eclipse Gate",
        "a_genre_romance": "Heart of the Celestial Wizard",
        "a_genre_scifi": "Edolas Technology Wonders",
        "a_genre_sol": "Life at the Fairy Tail Guild",
        "a_genre_sports": "Grand Magic Games Arena",
        "a_genre_supernatural": "Dragon Seed Awakening",
        "a_genre_thriller": "Zeref's Dark Pursuit",
        "a_genre_mecha": "Edolas Dorma Anim Mecha",
        "a_genre_music": "Lyra's Melodies of the Heart",
        "a_genre_psychological": "Jellal's Twisted Memory",
        "a_genre_ecchi": "Lucy's Wardrobe Malfunction",
        "a_genre_mahou_shoujo": "Magical Girl Erza Requip",
        "a_tag_isekai": "Transported to Edolas",
        "a_tag_harem": "Lucy's Unwitting Admirers",
        "a_tag_bl": "Brothers in Dragon Slaying",
        "a_tag_gl": "Wizard Duo Partners",
        "a_tag_historical": "Four Hundred Years of Dragon History",
        "a_tag_military": "Magic Council Military Ops",
        "a_tag_school": "Fairy Academy Omake",
        "a_tag_martial_arts": "Hand-to-Hand Combat Master",
        "a_tag_vampire": "Bloodman's Dark Curse",
        "a_tag_samurai": "Erza the Titania Swordswoman",
        "a_tag_space": "Celestial Spirit World",
        "a_tag_parody": "Chibi Fairy Tail Specials",
        "a_tag_idol": "Mirajane's Modeling Career",
        "a_tag_post_apocalyptic": "Post-Acnologia Devastation",
        "a_tag_cyberpunk": "Edolas Machine Technology",
        "a_tag_shounen": "Never-Give-Up Natsu Spirit",
        "a_tag_seinen": "Zeref's Harsh Reality",
        "a_tag_shoujo": "Juvia's Feelings for Gray",
        "a_tag_josei": "Bisca's Perspective",
        "a_tag_survival": "Survival on Tenrou Island",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Guild Wizard License",
        "a_mega_completionist": "Wizard Saint Achieved",
        "a_completion_rate_50": "Halfway to S-Class",
        "a_completion_rate_75": "Approaching Guild Master Status",
        "a_completion_rate_90": "Dragon Force Nearly Mastered",
        "a_no_drop": "No Nakama Left Behind",
        "a_long_runner_complete": "Long Magic War Endurance",
        "a_sequel_chain": "Sequel Quest Chain",
        "a_clean_list": "Clean Guild Record",
        "a_from_ptw": "Request Board Activated",
        "a_rewatch_master": "Fairy Glitter Memory Replay",
        "a_short_complete": "Quick D-Rank Quest",
        "a_same_day_start_finish": "Same-Night Phantom Lord Resolve",
        "a_revival": "Natsu's Revival from the Book",
        "a_zero_to_hero": "Lucy's Journey to S-Class",
        "a_five_genre_complete": "Five Magic Mastery Types",
        "a_full_franchise": "Full Fairy Tail Chronicles",
        "a_batch_complete": "Batch Quest Clear",
        "a_paused_to_done": "Returned After Seven Years",
        "a_completion_spree": "Fire Dragon Roar Spree",
        "a_multi_rewatch": "Multi-Timeline Fairy Sphere Replay",
        "a_dropped_recovery": "Recovered from Tenrou Curse",
        "a_ten_perfect_scores": "Ten Perfect Wizard Scores",
        "a_seasonal_clear": "Grand Magic Games Seasonal Clear",
        "a_complete_genre_span": "All-Around Guild Wizard",
        "a_monthly_completions": "Monthly Guild Report",
        "a_yearly_completions": "Annual Fiore Review",
        "a_rapid_complete": "Lightning Flame Dragon Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Fairy Tail Member",
        "a_studio_devotee": "A-1 Pictures Devotee",
        "a_rewatcher": "Fairy Tail Rewatch Wizard",
        "a_triple_rewatch": "Triple Dragon Slayer Rewatch",
        "a_annual_tradition": "Annual Fantasia Parade",
        "a_director_fan": "Director's Magic Vision",
        "a_voice_actor_fan": "Voice of the Dragon Slayers",
        "a_ost_lover": "Snow Fairy & Strike Back Lover",
        "a_source_reader": "Mashima's Original Manga",
        "a_waiting_weekly": "Weekly Kingdom Broadcast Wait",
        "a_childhood_revisit": "Return to Magnolia",
        "a_saga_tracker": "Fairy Tail Saga Tracker",
        "a_genre_loyalty": "Guild Wizard Genre Loyalty",
        "a_decade_watcher": "Decade-Long Fairy Tail Fan",
        "a_adaptation_hunter": "Magic Adaptation Hunter",
        "a_original_anime_fan": "Original Broadcast Wizard",
        "a_long_commitment": "Long-Term Guild Commitment",
        "a_perfect_attendance": "Perfect Attendance at the Guild",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Magic Catalog",
        "a_franchise_collector": "Fairy Tail Universe Collector",
        "a_airing_follower": "Currently Airing Guild Intel",
        "a_genre_master": "Genre Magic Mastery",
        "a_staff_follower": "Guild Staff Dossier",
        "a_multi_season_fan": "Multi-Season Guild Veteran",
        "a_format_diversity": "Diverse Wizard Formats",
        "a_year_dedication": "Year of Burning Resolve",
        "a_season_dedication": "Season of the Dragon Festival",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Magic Type Explorer",
        "a_studio_hopper": "Guild Transfer Wizard",
        "a_tag_explorer": "Tag Reconnaissance Wizard",
        "a_decade_hopper": "Ancient Fiore to Modern Day",
        "a_hidden_gem": "Hidden Lacrima Discovered",
        "a_popular_taste": "Popular Among Guild Wizards",
        "a_retro_appreciator": "Golden Age Wizard Appreciator",
        "a_modern_viewer": "Modern Fiore Viewer",
        "a_cross_demographic": "Cross-Guild Scout",
        "a_underdog_fan": "Underdog Natsu Spirit",
        "a_variety_week": "Week of Varied Magics",
        "a_foreign_cinema": "Overseas Wizard Cinema",
        "a_classic_connoisseur": "Classic Lacrima Connoisseur",
        "a_every_season": "Every Season Enlisted",
        "a_award_winner": "Grand Prix Winner",
        "a_niche_explorer": "Underground Wizard Explorer",
        "a_global_anime": "Global Guild Network",
        "a_cult_classic": "Cult Classic Fairy Tale",
        "a_random_pick": "Random Quest Assignment",
        "a_new_genre_month": "New Magic Monthly Discovery",
        "a_seasonal_completionist": "Seasonal Quest Complete",
        "a_unpopular_opinion": "Unpopular Guild Opinion",
        "a_top_rated_viewer": "Top-Ranked Wizard Intel",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Darkness",
        "a_upcoming_watcher": "Upcoming Lacrima Debut Watch",
        "a_short_series_explorer": "Short Quest Explorer",
        "a_long_series_explorer": "Long Arc Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Patrol Dragon Slayer",
        "a_early_bird": "Dawn Patrol Wizard",
        "a_lunch_break": "Lunch at the Guild Bar",
        "a_golden_hour": "Golden Fairy Glitter Hour",
        "a_four_am_club": "4 AM Dragon Force Training",
        "a_witching_hour": "Zeref's Witching Hour",
        "a_new_year_watch": "New Year's Guild Oath",
        "a_midnight_premiere": "Midnight Magnolia Premiere",
        "a_all_hours": "All-Hours Wizard on Duty",
        "a_dawn_warrior": "Dawn Warrior of Fiore",
        "a_afternoon_delight": "Afternoon Training Session",
        "a_prime_time": "Prime Time Dragon Showdown",
        "a_workday_watcher": "On-Duty Guild Watcher",
        "a_sunday_marathon": "Sunday Training Marathon",
        "a_rainy_day": "Rainy Day at the Guild",
        "a_morning_routine": "Morning Dragon Slayer Routine",
        "a_night_shift": "Nighttime Guild Shift",
        "a_twilight_zone": "Twilight Eclipse Zone",
        "a_seasonal_premier": "Season Premiere Guild Debut",
        "a_clock_collector": "Horologium Clock Collector",
        "a_weekend_binge_hours": "Weekend Wizard Binge Hours",
        "a_late_night_regular": "Late Night Regular Patrol",
        "a_sunrise_watcher": "Sunrise Over Magnolia",
        "a_holiday_watcher": "Holiday Guild Duty",
        "a_every_day_of_week": "Every Day a Fairy Tail Wizard",
        "a_monthly_hours": "Monthly Training Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Guild Banquet",
        "a_party_host": "Master Makarov's Party Call",
        "a_social_butterfly": "Mirajane's Social Charm",
        "a_group_binge": "Guild Group Watch",
        "a_party_regular": "Regular Training Partner",
        "a_sync_viewer": "Synchronized Unison Raid",
        "a_commentator": "Natsu's Fired-Up Commentary",
        "a_party_marathon": "Grand Magic Games Watch Party",
        "a_full_house": "Full Guild Assembly",
        "a_community_pillar": "Pillar of Fairy Tail",
        "a_watch_party_streak": "Consecutive Gathering Streak",
        "a_diverse_party": "Diverse Guild Team-Up",
        "a_late_night_party": "Late Night Guild Party",
        "a_party_veteran": "Veteran Wizard Social",
        "a_genre_party": "Cross-Magic Party",
        "a_weekly_party": "Weekly Guild Gathering",
        "a_silent_viewer": "Silent Observer Mystogan",
        "a_recommendation_giver": "S-Class Recommendation Letter",
        "a_party_completionist": "Social Wizard Completionist",
        "a_social_scorer": "Social Guild Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Formation",
        "a_fibonacci": "Fibonacci Ethernano Sequence",
        "a_palindrome_day": "Palindrome Time Eclipse",
        "a_binary_day": "Binary Lacrima Analysis",
        "a_full_moon": "Full Moon Dragon Awakening",
        "a_leap_year": "Leap Year Seven-Year Gap",
        "a_time_traveler": "Eclipse Gate Time Traveler",
        "a_genre_clash": "Guild vs. Dark Guild Clash",
        "a_triple_seven": "Triple Seven Dragon Combo",
        "a_thousand_complete": "Thousand Magic Victories",
        "a_pi_episodes": "Pi Calculation of Spells",
        "a_synchronicity": "Celestial Spirit Synchronicity",
        "a_world_record": "World Record Magic Feat",
        "a_nice": "Nice Quest Count",
        "a_power_level": "Dragon Slayer Power Level",
        "a_answer_42": "The Answer to Acnologia's Riddle",
        "a_square_number": "Perfect Formation Number",
        "a_prime_count": "Prime Number of Victories",
        "a_matching_date": "Matching Incident Date",
        "a_century_episode": "Century Episode Magic Arc",
        "a_double_digits": "Double Digit Guild Rank",
        "a_one_two_three": "Spells One Two Three",
        "a_lucky_seven": "Seven Dragon Slayers",
        "a_all_tens": "All Tens Wizard Score",
        "a_exact_hundred_eps": "Exact Hundred Magic Deeds",
        "a_year_match_count": "Year Match Guild Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Lacrima TV Wizard",
        "a_movie_buff": "Dragon Cry Movie Mission",
        "a_ova_hunter": "OVA Memory Days Hunter",
        "a_ona_explorer": "ONA Wizard Explorer",
        "a_special_watcher": "Special Episode Wizard",
        "a_short_king": "Short Rescue Wizard",
        "a_variety_pack": "All-Format Wizard Pack",
        "a_film_festival": "Fairy Tail Film Festival",
        "a_music_video": "Opening Theme Collection",
        "a_tv_short": "Quick Magic Clip",
        "a_movie_marathon": "Phoenix Priestess Marathon",
        "a_double_length": "Double-Length Guild Special",
        "a_anthology": "Fairy Tail Anthology",
        "a_mini_series": "Mini Wizard Series",
        "a_theatrical": "Theatrical Lacrima Debut",
        "a_format_master": "Format Master Wizard",
        "a_long_movie": "Feature-Length Dragon Battle",
        "a_back_catalog": "Wizard Back Catalog",
        "a_cm_watcher": "Commercial Break Wizard",
        "a_pv_collector": "Lacrima Preview Collector",
        "a_format_balance": "Balanced Wizard Formats",
        "a_episodic_master": "Episodic Magic Master",
        "a_sequel_movie": "Sequel Magic Movie",
        "a_recap_watcher": "Recap Briefing Wizard",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Guild Patrol Streak",
        "a_mega_streak": "Mega Dragon Slayer Streak",
        "a_weekly_warrior": "Weekly Warrior Wizard",
        "a_monthly_watcher": "Monthly Guild Duty",
        "a_comeback": "Return After Seven Years",
        "a_weekend_streak": "Weekend Wizard Streak",
        "a_no_zero_days": "No Zero Days in the Guild",
        "a_iron_will": "Iron Dragon's Unyielding Will",
        "a_habit_formed": "Dragon Slayer Regimen Formed",
        "a_consistent_pace": "Consistent Wizard Pace",
        "a_year_long": "Year-Long Dragon War",
        "a_double_streak": "Double Streak Unison Raid",
        "a_streak_recovery": "Wendy's Streak Recovery Heal",
        "a_daily_minimum": "Daily Minimum Patrol",
        "a_winter_streak": "Winter Dragon Streak",
        "a_summer_streak": "Summer Training Camp Streak",
        "a_morning_streak": "Morning Dragon Slayer Streak",
        "a_night_streak": "Night Patrol Streak",
        "a_unbreakable": "Unbreakable Will of Natsu",
        "a_eternal_flame": "Eternal Flame of Atlas",
        "a_completion_streak": "Quest Completion Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Episode Magic Arc",
        "a_genre_streak": "Genre Streak Wizard Run",
        "a_studio_streak": "Studio Loyalty Wizard",
        "a_perfect_week": "Perfect Week of Guild Questing",

        // ── ANIME SCORING ──
        "a_critic": "Magic Council Critic",
        "a_perfect_ten": "Perfect 10 Wizard Score",
        "a_harsh_critic": "Laxus's Harsh Judgment",
        "a_fair_judge": "Makarov's Fair Assessment",
        "a_generous_spirit": "Generous Fairy Spirit",
        "a_score_all": "Full Fiore Evaluation",
        "a_wide_range": "Wide Range Magic Assessment",
        "a_controversial": "Controversial Guild Ranking",
        "a_consistent_scorer": "Consistent Fiore Evaluator",
        "a_score_sniper": "Erza's Precision Score",
        "a_evolving_taste": "Evolving Magic Taste",
        "a_bell_curve": "Bell Curve of Guild Scores",
        "a_picky_watcher": "Selective Wizard Judge",
        "a_100_rated": "Century of Fiore Evaluations",
        "a_500_rated": "Five Hundred Wizard Reports",
        "a_mediocre_majority": "Middle Rank Wizard",
        "a_rating_spree": "Rating Concentration Spree",
        "a_score_variance": "Variable Wizard Ratings",
        "a_masterpiece_hunter": "Masterpiece Magic Hunter",
        "a_contrarian": "Contrarian Fiore Critic",
        "a_optimist": "Optimist Like Natsu",
        "a_score_distributor": "Score Distributor Wizard",
        "a_genre_critic": "Genre Magic Critic",
        "a_mean_above_8": "Elite S-Class Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Wizard Resolution",
        "a_valentines_weeb": "Valentine's Celestial Heart",
        "a_pi_day": "Pi Day Ethernano Calculation",
        "a_april_fools": "April Fools Guild Prank",
        "a_international_anime_day": "International Wizard Day",
        "a_star_wars_day": "Star Wars Magic Crossover",
        "a_summer_solstice": "Summer Solstice Training Day",
        "a_tanabata": "Tanabata Wizard Wish",
        "a_friday_13th": "Friday 13th Tartaros Attack",
        "a_halloween_spirit": "Halloween Fairy Costume",
        "a_thanksgiving_binge": "Thanksgiving Guild Feast",
        "a_christmas_special": "Christmas at the Guild Hall",
        "a_new_years_eve": "New Year's Eve Fantasia Gala",
        "a_birthday_watch": "Wizard Birthday Celebration",
        "a_holiday_marathon": "Holiday Fiore Marathon",
        "a_independence_day": "Wizard Independence Day",
        "a_culture_day": "Fiore Culture Festival",
        "a_spring_equinox": "Spring Cherry Blossom Viewing",
        "a_earth_day": "Earth Day Nature Dragon",
        "a_labor_day": "Guild Labor Day",
        "a_winter_solstice": "Winter Solstice Dragon Hunt",
        "a_anime_birthday": "Anime Anniversary Wizard",
        "a_every_holiday": "Every Holiday Wizard",
        "a_consecutive_holidays": "Consecutive Holiday Quests",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Magic Awakened",
        "a_meta_collector": "Wizard License Collector",
        "a_meta_category_starter": "Magic Category Initiation",
        "a_meta_tier_climber": "Guild Rank Promotion",
        "a_meta_tier_max": "Wizard Saint Rank Achieved",
        "a_meta_xp_earner": "XP from Guild Quests",
        "a_meta_difficulty_easy": "Easy D-Rank Quest",
        "a_meta_difficulty_hard": "Legendary: Acnologia Battle",
        "a_meta_unlock_spree": "Magic Unlock Spree",
        "a_meta_completionist": "Meta Fiore Completionist",
        "a_meta_diverse": "Diverse Wizard Portfolio",
        "a_meta_dominator": "Meta Pillar of Fairy Tail",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter: The Fairy Tail",
        "m_chapter_counter": "Sorcerer Magazine Page Counter",
        "m_chapter_titan": "Dragon King-Class Chapter",
        "m_reading_hours": "Hours Studying at the Guild",
        "m_reading_time_lord": "Total Concentration Reading",
        "m_manga_collector": "Fairy Tail Manga Collector",
        "m_library_legend": "Grand Library of Fiore Legend",
        "m_first_complete": "First Manga Quest Done",
        "m_hundred_club": "Hundred-Chapter Wizard Club",
        "m_first_day": "First Day of Fiore Reading",
        "m_first_rating": "First Manga Wizard Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Magic Lore",
        "m_volume_collector": "Volume Stockpile Wizard",
        "m_year_explorer": "Year of Manga Wizard Study",
        "m_century_reader": "Century-Chapter Magic Reader",
        "m_five_hundred_ch": "Five Hundred Fairy Chapters",
        "m_thousand_ch": "Thousand-Chapter Dragon Slayer Reading",
        "m_reading_ten": "Ten Manga at Once Wizard",
        "m_ptr_hoarder": "Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Wizard Retreat",
        "m_season_reader": "Seasonal Fiore Reading",
        "m_active_reader": "Active Field Reader Wizard",
        "m_five_thousand_ch": "Five Thousand Chapters Deep",
        "m_ten_completed": "Ten Magic Manga Complete",
        "m_fifty_completed": "Fifty Manga Quests Done",
        "m_five_hundred_completed": "Five Hundred Manga Victories",
        "m_mean_score_tracker": "Average Manga Guild Rating",
        "m_unique_authors": "Unique Mangaka Encounters",
        "m_all_status": "All Reading Statuses Wizard",
        "m_first_favorite": "First Manga Nakama Bond",
        "m_favorites_collector": "Manga Favorites Arsenal",
        "m_days_spent_reading": "Days in Fiore Reading Hall",

        // ── MANGA BINGE ──
        "m_binge_reader": "Non-Stop Fairy Reading",
        "m_marathon_reader": "Grand Magic Games Reading Marathon",
        "m_weekend_reader": "Weekend Guild Reading",
        "m_non_stop_reading": "Relentless Page Turning",
        "m_one_more_chapter": "One More Chapter of Fairy Tail",
        "m_speed_read": "Fire Dragon Speed Read",
        "m_double_story": "Double Fairy Feature",
        "m_triple_read": "Triple Reading Magic",
        "m_five_a_day": "Five Magic Reads a Day",
        "m_chapter_chain": "Chapter Chain Combo",
        "m_volume_binge": "Volume Binge at the Library",
        "m_power_reader": "Power Reader Wizard",
        "m_half_day_read": "Half-Day Wizard Study",
        "m_full_day_read": "Full-Day Manga Training",
        "m_power_weekend": "Power Weekend Fiore Reading",
        "m_binge_king": "King of Fairy Manga",
        "m_no_sleep_read": "All-Night Fairy Reading",
        "m_full_series_rush": "Full Series Dragon Rush",
        "m_seven_day_challenge": "Seven-Day Wizard Challenge",
        "m_hundred_day_read": "Hundred-Day Fiore Grind",
        "m_volume_rush": "Volume Rush Reading",
        "m_series_sweep": "Series Sweep Wizard",
        "m_genre_binge": "Cross-Genre Magic Reading",
        "m_author_binge": "Mashima Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Wizard Count",
        "m_multi_series_binge": "Multi-Series Magic Reading",
        "m_midnight_binge": "Midnight Fairy Reading",
        "m_new_year_binge": "New Year's Reading Dragon Roar",
        "m_forty_eight_hour": "Forty-Eight Hour Magic Read",
        "m_oneshot_binge": "Oneshot Fairy Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Magic Manga Specialist",
        "m_genre_adventure": "Wizard Adventure Manga",
        "m_genre_comedy": "Comedy at the Fairy Tail Guild",
        "m_genre_drama": "Drama of the Tower of Heaven",
        "m_genre_fantasy": "Fantasy Earthland Manga",
        "m_genre_horror": "Tartaros Horror Manga",
        "m_genre_mystery": "Mystery of the Eclipse Gate Manga",
        "m_genre_romance": "Celestial Wizard Romance Manga",
        "m_genre_scifi": "Edolas Sci-Fi Manga",
        "m_genre_sol": "Guild Life Slice of Life",
        "m_genre_sports": "Grand Magic Games Sports Manga",
        "m_genre_supernatural": "Dragon Slayer Supernatural Manga",
        "m_genre_thriller": "Zeref Pursuit Thriller Manga",
        "m_genre_psychological": "Psychological Eclipse Warfare",
        "m_genre_isekai": "Isekai Edolas Manga",
        "m_genre_shounen": "Shounen Dragon Heart Manga",
        "m_genre_ecchi": "Hot Spring Chapter Manga",
        "m_genre_mahou_shoujo": "Magical Requip Armor Manga",
        "m_genre_mecha": "Edolas Machine Dragon Manga",
        "m_genre_music": "Lyra's Song Manga",
        "m_tag_isekai_new": "New World Magic Manga",
        "m_tag_harem": "Wizard Guild Harem Manga",
        "m_tag_bl": "Brothers in Dragon Slaying Manga",
        "m_tag_gl": "Wizard Duo Partners Manga",
        "m_tag_historical": "Fiore History Manga",
        "m_tag_military": "Magic Council Military Manga",
        "m_tag_school": "Fairy Academy Manga",
        "m_tag_martial_arts": "Hand-to-Hand Combat Manga",
        "m_tag_vampire": "Bloodman's Curse Manga",
        "m_tag_samurai": "Titania Swordswoman Manga",
        "m_tag_space": "Celestial Spirit Realm Manga",
        "m_tag_parody": "Chibi Fairy Tail Manga",
        "m_tag_idol": "Mirajane Idol Manga",
        "m_tag_post_apocalyptic": "Post-Acnologia Manga",
        "m_tag_cyberpunk": "Edolas Machine Tech Manga",
        "m_tag_shoujo": "Juvia's Love Story Manga",
        "m_tag_survival": "Tenrou Island Survival Manga",
        "m_tag_cooking": "Guild Kitchen Cooking Manga",
        "m_tag_medical": "Wendy's Healing Magic Manga",
        "m_tag_villainess": "Zeref Redemption Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Fiore Manga License",
        "m_mega_completionist": "Supreme Fairy Reader",
        "m_completion_rate_50": "Halfway to S-Class Reader",
        "m_completion_rate_75": "Approaching Full Manga Mastery",
        "m_completion_rate_90": "Dragon Force Manga Mastery",
        "m_no_drop": "No Manga Abandoned Wizard",
        "m_long_runner_complete": "Long Fairy Arc Endurance",
        "m_sequel_chain": "Wizard Sequel Chain",
        "m_clean_list": "Clean Wizard Reading Record",
        "m_from_ptr": "Guild Orders: Read Manga",
        "m_reread_master": "Fairy Memory Reread Replay",
        "m_oneshot_complete": "Oneshot Fairy Specialist",
        "m_same_day_start_finish": "Same-Day Fairy Blitz",
        "m_revival": "Natsu's Revival Reading",
        "m_zero_to_hundred": "Lucy to Wizard Saint Reader",
        "m_five_genre_complete": "Five-Genre Wizard Mastery",
        "m_full_collection": "Full Fairy Manga Collection",
        "m_batch_complete": "Batch Quest Clear Wizard",
        "m_paused_to_done": "Returned from Seven-Year Hiatus",
        "m_completion_spree": "Fire Dragon Reading Spree",
        "m_format_completionist": "Format Completion Wizard Badge",
        "m_catch_up": "Caught Up with Serialization",
        "m_multi_reread": "Multi-Reread Fairy Manga",
        "m_dropped_recovery": "Recovered from Manga Dropout",
        "m_ten_perfect_scores": "Ten Perfect Wizard Scores",
        "m_complete_genre_span": "All-Around Fairy Reader",
        "m_monthly_completions": "Monthly Guild Manga Reports",
        "m_yearly_completions": "Annual Fiore Manga Review",
        "m_rapid_complete": "Rapid Dragon Slayer Clear",
        "m_author_complete": "Mashima's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Fiore Manga Reader",
        "m_mangaka_lover": "Mashima Devotee",
        "m_rereader": "Fairy Manga Rereader",
        "m_triple_reread": "Triple Dragon Slayer Reread",
        "m_annual_reread": "Annual Fairy Reread Tradition",
        "m_publisher_fan": "Wizard Publisher Fan",
        "m_artist_fan": "Magic Artist Appreciation",
        "m_adaptation_compare": "Manga vs Anime Wizard Compare",
        "m_source_material_fan": "Source Material Wizard Fan",
        "m_waiting_weekly": "Weekly Fairy Chapter Wait",
        "m_classic_reader": "Classic Magic Manga Reader",
        "m_saga_reader": "Fairy Saga Reader",
        "m_genre_loyalty": "Genre Loyalty Wizard Medal",
        "m_decade_reader": "Decade-Long Fairy Reader",
        "m_ln_adaptation": "Light Novel Magic Adaptation",
        "m_original_work": "Original Fairy Manga Work",
        "m_long_commitment": "Long-Term Wizard Commitment",
        "m_up_to_date": "Up-to-Date with Fairy Manga",
        "m_favorite_mangaka": "Favorite Magic Mangaka",
        "m_complete_portfolio": "Complete Fairy Portfolio",
        "m_franchise_collector": "Fairy Tail Franchise Collector",
        "m_serialization_follower": "Fairy Serialization Follower",
        "m_genre_master": "Genre Fairy Manga Mastery",
        "m_multi_series_author": "Multi-Series Mashima Fan",
        "m_format_diversity": "Diverse Fairy Reading Formats",
        "m_year_dedication": "Year of Fairy Tail Reading",
        "m_ongoing_follower": "Ongoing Fairy Series Follower",
        "m_genre_loyalty_50": "Fifty Fairy Genre Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Magic Type Genre Explorer",
        "m_publisher_hopper": "Fiore Publisher Transfer",
        "m_tag_explorer": "Wizard Tag Recon Mission",
        "m_decade_hopper": "Era-Hopping Magic Reader",
        "m_hidden_gem": "Hidden Lacrima Gem Manga",
        "m_popular_taste": "Popular Among Fiore Readers",
        "m_retro_reader": "Retro Magic Manga Reader",
        "m_modern_reader": "Modern Fiore Era Reader",
        "m_cross_demographic": "Cross-Guild Reader",
        "m_underdog_fan": "Underdog Fairy Fan",
        "m_variety_week": "Week of Varied Fairy Reads",
        "m_manhwa_reader": "Manhwa Magic Reader",
        "m_manhua_reader": "Manhua Magic Reader",
        "m_classic_connoisseur": "Classic Fairy Manga Connoisseur",
        "m_award_winner": "Award-Winning Fairy Manga",
        "m_niche_explorer": "Underground Fairy Manga",
        "m_world_manga": "World Fairy Manga Intel",
        "m_cult_classic": "Cult Classic Fairy Tale Manga",
        "m_random_pick": "Random Fairy Assignment",
        "m_new_genre_month": "New Fairy Genre Monthly",
        "m_year_completionist": "Year Fairy Manga Completionist",
        "m_unpopular_opinion": "Unpopular Fairy Manga Opinion",
        "m_top_rated_reader": "Top-Ranked Fairy Manga",
        "m_source_variety": "Fairy Source Material Variety",
        "m_low_score_brave": "Brave Fairy Low-Score Reader",
        "m_short_manga_explorer": "Short Fairy Manga Skirmish",
        "m_long_manga_explorer": "Long Fairy Manga Campaign",
        "m_serialization_explorer": "Fairy Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Fairy Reader",
        "m_early_bird": "Dawn Patrol Fairy Reader",
        "m_lunch_reader": "Lunch at the Guild Bar Reader",
        "m_commute_reader": "Commute to Magnolia Reader",
        "m_four_am_club": "4 AM Dragon Study Session",
        "m_new_year_read": "New Year's Wizard Reading Oath",
        "m_all_hours": "All-Hours Fairy Reader",
        "m_prime_time_reader": "Prime Time Fairy Manga",
        "m_workday_reader": "On-Duty Fiore Reader",
        "m_sunday_read": "Sunday Fairy Reading Marathon",
        "m_morning_routine": "Morning Dragon Slayer Reading",
        "m_night_shift_reader": "Night Shift Fairy Reader",
        "m_seasonal_premier_read": "New Fairy Release Reader",
        "m_clock_collector": "Horologium Reading Collector",
        "m_late_night_horror": "Midnight Tartaros Horror Read",
        "m_afternoon_reader": "Afternoon Fairy Reader",
        "m_golden_hour_reader": "Golden Fairy Reading Hour",
        "m_dawn_reader": "Dawn Fairy Reading",
        "m_twilight_reader": "Twilight Eclipse Reader",
        "m_midnight_start": "Midnight Fairy Reading Start",
        "m_weekend_binge_hours": "Weekend Fairy Binge Reading",
        "m_late_night_regular": "Late Night Regular Reader",
        "m_sunrise_reader": "Sunrise Over Magnolia Reader",
        "m_every_day_of_week": "Every Day Fairy Reading",
        "m_monthly_hours": "Monthly Fairy Reading Hours",
        "m_bedtime_reader": "Bedtime Guild Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Mashima Art Appreciator",
        "m_webtoon_reader": "Fairy Webtoon Reader",
        "m_full_color": "Full Color Fairy Manga",
        "m_doujin_reader": "Fairy Doujin Reader",
        "m_anthology_reader": "Fairy Anthology Reader",
        "m_adaptation_reader": "Fairy Adaptation Reader",
        "m_longstrip_reader": "Vertical Fairy Scroll",
        "m_4koma_reader": "Fairy 4-Koma Shorts",
        "m_oneshot_reader": "Fairy Oneshot Mission",
        "m_format_variety": "Fairy Format Variety",
        "m_light_novel_reader": "Fairy Light Novel Reader",
        "m_novel_reader": "Fairy Novel Archives",
        "m_visual_storyteller": "Visual Fairy Narrator",
        "m_colored_classic": "Colored Classic Fairy Manga",
        "m_webcomic_fan": "Fairy Webcomic Fan",
        "m_manga_to_anime": "Manga to Anime Fairy Compare",
        "m_seinen_reader": "Seinen Fairy Reader",
        "m_josei_reader": "Josei Fairy Perspective",
        "m_award_winning_art": "Award-Winning Fairy Artwork",
        "m_debut_work": "Fairy Debut Manuscript",
        "m_vertical_scroll": "Vertical Scroll Fairy",
        "m_traditional_format": "Traditional Fairy Format",
        "m_cross_media": "Cross-Media Fairy Intel",
        "m_spinoff_reader": "Fairy Spinoff Reader",
        "m_remake_reader": "Fairy Remake Reader",
        "m_collaboration_reader": "Fairy Collaboration Manga",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Fairy Reading Streak",
        "m_mega_streak": "Mega Dragon Slayer Reading Streak",
        "m_weekly_warrior": "Weekly Warrior Fairy Reader",
        "m_monthly_reader": "Monthly Fairy Reader",
        "m_comeback": "Fairy Reader's Comeback",
        "m_weekend_streak": "Weekend Fairy Reading Streak",
        "m_no_zero_days": "No Zero Fairy Reading Days",
        "m_iron_will": "Iron Dragon's Reading Will",
        "m_habit_formed": "Fairy Reading Habit Formed",
        "m_consistent_pace": "Consistent Fairy Reading Pace",
        "m_year_long": "Year-Long Fairy Reading",
        "m_double_streak": "Double Fairy Reading Streak",
        "m_streak_recovery": "Fairy Streak Recovery",
        "m_daily_minimum": "Daily Minimum Fairy Pages",
        "m_winter_streak": "Winter Dragon Reading Streak",
        "m_summer_streak": "Summer Training Reading Streak",
        "m_morning_streak": "Morning Fairy Reading Streak",
        "m_night_streak": "Night Fairy Reading Streak",
        "m_unbreakable": "Unbreakable Fairy Reader",
        "m_eternal_flame": "Eternal Flame Reading Spirit",
        "m_chapter_a_day": "Chapter a Day Wizard",
        "m_genre_streak": "Genre Fairy Reading Streak",
        "m_completion_streak": "Fairy Completion Reading Chain",
        "m_rating_streak": "Fairy Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Fairy Streak",
        "m_author_streak": "Mashima Dedication Streak",
        "m_perfect_week_manga": "Perfect Fairy Reading Week",
        "m_diverse_streak": "Diverse Fairy Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Fairy Manga Critic",
        "m_perfect_ten": "Perfect 10 Fairy Manga",
        "m_harsh_critic": "Laxus's Reading Standards",
        "m_fair_judge": "Makarov's Manga Review",
        "m_generous_spirit": "Generous Fairy Reader",
        "m_score_all": "Full Fiore Manga Assessment",
        "m_wide_range": "Wide Range Fairy Scores",
        "m_controversial": "Controversial Fairy Rating",
        "m_consistent_scorer": "Consistent Fairy Manga Scorer",
        "m_score_sniper": "Precision Fairy Score Sniper",
        "m_evolving_taste": "Evolving Fairy Reading Taste",
        "m_bell_curve": "Bell Curve Fairy Scores",
        "m_picky_reader": "Selective Fairy Reader",
        "m_100_rated": "Century of Fairy Manga Ratings",
        "m_500_rated": "Five Hundred Fairy Reports",
        "m_mediocre_majority": "Middle Rank Fairy Reader",
        "m_rating_spree": "Fairy Rating Spree",
        "m_score_variance": "Variable Fairy Manga Scores",
        "m_binge_rater": "Binge Fairy Rating Session",
        "m_reread_rerate": "Reread & Re-Rate Fairy Manga",
        "m_masterpiece_hunter": "Masterpiece Fairy Manga Hunter",
        "m_contrarian": "Contrarian Fairy Reader",
        "m_optimist": "Optimist Fairy Reader",
        "m_score_distributor": "Fairy Score Distributor",
        "m_genre_critic": "Genre Fairy Manga Critic",
        "m_mean_above_8": "Elite Fairy Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Fairy Reading Vow",
        "m_valentines_read": "Valentine's Fairy Reading",
        "m_pi_day": "Pi Day Fairy Chapter Count",
        "m_april_fools": "April Fools Fairy Manga",
        "m_international_manga_day": "International Fairy Manga Day",
        "m_free_comic_day": "Free Fairy Comic Day",
        "m_summer_solstice": "Summer Solstice Fairy Reading",
        "m_tanabata": "Tanabata Fairy Reading Wish",
        "m_friday_13th": "Friday 13th Tartaros Manga",
        "m_halloween_read": "Halloween Fairy Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Fairy Reading Feast",
        "m_christmas_read": "Christmas Guild Hall Reading",
        "m_new_years_eve": "New Year's Eve Fairy Read",
        "m_birthday_read": "Birthday Fairy Reading Gift",
        "m_holiday_marathon": "Holiday Fairy Reading Marathon",
        "m_independence_day": "Wizard Independence Reading Day",
        "m_culture_day": "Fiore Culture Festival Reading",
        "m_spring_equinox": "Spring Cherry Blossom Reading",
        "m_earth_day": "Earth Day Fairy Reading",
        "m_labor_day": "Fiore Labor Reading Day",
        "m_winter_solstice": "Winter Solstice Fairy Reading",
        "m_manga_birthday": "Fairy Manga Birthday",
        "m_every_holiday_reader": "Every Holiday Fairy Reader",
        "m_consecutive_holidays": "Consecutive Holiday Fairy Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Wizard Milestone",
        "m_fibonacci": "Fibonacci Ethernano Pattern",
        "m_palindrome_day": "Palindrome Fairy Reading Day",
        "m_binary_day": "Binary Lacrima Reading Day",
        "m_full_moon_read": "Full Moon Fairy Read",
        "m_leap_year_read": "Leap Year Fairy Reading",
        "m_triple_seven": "Triple Seven Dragon Combo",
        "m_thousand_complete": "Thousand Fairy Manga Victories",
        "m_nice": "Nice Fairy Chapter Count",
        "m_power_level_chapters": "Dragon Slayer Chapter Power",
        "m_answer_42": "Answer to Acnologia's Riddle Manga",
        "m_square_number": "Perfect Wizard Formation",
        "m_prime_count": "Prime Fairy Chapter Count",
        "m_matching_date": "Matching Fairy Reading Date",
        "m_century_chapter": "Century Fairy Chapter",
        "m_pi_chapters": "Pi Fairy Chapter Calculation",
        "m_synchronicity": "Fairy Reading Synchronicity",
        "m_world_record": "World Record Fairy Chapters",
        "m_genre_clash": "Genre Clash Fairy Reading",
        "m_time_traveler": "Eclipse Gate Memory Reading",
        "m_double_digits": "Double Digit Fairy Milestone",
        "m_one_two_three": "Spells One Two Three Manga",
        "m_lucky_seven": "Seven Dragon Slayer Chapters",
        "m_exact_hundred_ch": "Exact Hundred Fairy Chapters",
        "m_year_match_count": "Year Match Fairy Chapter Count",
        "m_chapter_match_date": "Chapter Date Fairy Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Fairy Manga Format",
        "m_manhwa_format": "Manhwa Fairy Format",
        "m_manhua_format": "Manhua Fairy Format",
        "m_ln_format": "Light Novel Fairy Format",
        "m_oneshot_format": "Oneshot Fairy Format",
        "m_doujin_format": "Doujin Fairy Format",
        "m_novel_format": "Novel Fairy Format",
        "m_format_master_manga": "Format Master Fairy Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Fairy Reading Awakened",
        "m_meta_collector": "Fairy Reading Badge Collector",
        "m_meta_category_starter": "Fairy Category Initiation",
        "m_meta_tier_climber": "Fairy Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Fairy Reading Rank",
        "m_meta_xp_earner": "XP from Fairy Reading",
        "m_meta_difficulty_easy": "Easy Fairy Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Fairy Manga Challenge",
        "m_meta_unlock_spree": "Fairy Reading Unlock Spree",
        "m_meta_completionist": "Meta Fairy Reading Completionist",
        "m_meta_diverse": "Diverse Fairy Reading Portfolio",
        "m_meta_dominator": "Meta Fairy Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#06040a",
        primary: "#c8508c",
        secondary: "#e060a0",
        accent: "#ff80c0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/fairy-tail.jpg",
    particleColor: "#e05030",
    backgroundDim: 0.28,
    backgroundBlur: 26,
    particleTypes: {
        fairy_glitter: { label: "Fairy Glitter", maxCount: 18, defaultEnabled: true, defaultIntensity: 65 },
        fire_dragon: { label: "Fire Dragon", maxCount: 12, defaultEnabled: true, defaultIntensity: 70 },
        celestial_keys: { label: "Celestial Keys", maxCount: 14, defaultEnabled: true, defaultIntensity: 55 },
        guild_marks: { label: "Guild Marks", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        heaven_light: { label: "Heaven's Light", maxCount: 16, defaultEnabled: true, defaultIntensity: 60 },
    },
    playerIconOverrides: fairyTailPlayerIcons,
    milestoneNames: {
        1:   "Apprentice Mage",
        8:   "Mage",
        20:  "S-Class Candidate",
        32:  "S-Class Mage",
        46:  "Wizard Saint",
        60:  "Spriggan 12",
        75:  "Etherion",
        90:  "Fairy King",
        100: "Dragon Slayer Legend",
    },
}
