import { AnimeThemeConfig } from "./types"
import { GiHolyGrail, GiAncientSword, GiMagicPortal, GiCastle, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiLightningBow } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const fateZeroTheme: AnimeThemeConfig = {
    id: "fate-zero",
    displayName: "Fate/Zero",
    description: "Ten years before the fifth Holy Grail War, the fourth war commences in Fuyuki City — a brutal conflict narrated with moral ambiguity, compelling Servants, and the tragic figure of Kiritsugu Emiya.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "160 175 220",
        "--color-brand-300": "120 138 205",
        "--color-brand-400": "78 100 185",
        "--color-brand-500": "42 65 162",
        "--color-brand-600": "24 42 132",
        "--color-brand-700": "12 25 100",
        "--color-brand-800": "6 13 68",
        "--color-brand-900": "2 6 38",
        "--color-brand-950": "1 2 20",
        "--brand": "42 65 162",
        "--background": "#000002",
        "--paper": "#030208",
        "--color-gray-950": "0 0 2",
        "--color-gray-900": "3 2 8",
        "--color-gray-800": "7 6 16",
        "--color-gray-700": "13 11 28",
        "--color-gray-600": "22 20 48",
        "--color-gray-500": "36 34 78",
        "--color-gray-400": "62 60 112",
        "--color-gray-300": "98 96 150",
        "--color-gray-200": "138 136 186",
        "--color-gray-100": "175 174 212",
        "--color-gray-50": "215 214 236",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Fuyuki City" },
        "schedule": { icon: GiAlarmClock, label: "War Schedule" },
        "manga": { icon: LuBookOpen, label: "Mage's Files" },
        "lists": { icon: GiAncientSword, label: "Servant Registry" },
        "discover": { icon: GiBullseye, label: "Enemy Scouting" },
        "torrent-list": { icon: GiMagicPortal, label: "Magic Cache" },
        "debrid": { icon: GiHolyGrail, label: "Grail Store" },
        "unmatched": { icon: GiLightningBow, label: "Unknown Servants" },
        "enmasse": { icon: GiResize, label: "War Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Records" },
        "auto-downloader": { icon: LuRss, label: "Mage Association" },
        "community": { icon: GiCastle, label: "Fourth Grail War" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "War Alerts" },
        "achievements": { icon: GiTrophy, label: "War Titles" },
        "milestones": { icon: LuFlag, label: "War Goals" },
        "theme-manager": { icon: GiPalette, label: "Steel Colors" },
        "extensions": { icon: BiExtension, label: "Noble Phantasm" },
        "sync": { icon: IoCloudOfflineOutline, label: "Grail Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Kiritsugu's Rules" },
    },
    achievementNames: {
        "a_first_episode": "War Begins",
        "a_first_complete": "Grail Cursed",
        "a_hundred_club": "Hundred Battles",
        "a_time_lord": "War Veteran",
        "a_anime_collector": "Noble Collection",
        "a_library_legend": "War Archives",
        "a_binge_king": "War Marathon",
        "a_no_sleep": "All-Night Battle",
        "a_marathon_runner": "Kiritsugu's Path",
        "a_speed_run": "Gilgamesh Chains",
        "a_completionist": "All Servants",
        "a_mega_completionist": "Urobuchi Master",
        "a_loyal_fan": "Kiritsugu's Ideal",
        "a_rewatcher": "War Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Noble Phantasm",
        "a_genre_adventure": "War Journey",
        "a_genre_comedy": "Waver's Growth",
        "a_genre_drama": "Kiritsugu's Tragedy",
        "a_genre_fantasy": "Mage World",
        "a_genre_horror": "Grail Horror",
        "a_genre_romance": "Saber's Bond",
        "a_genre_scifi": "Magic Circuits",
        "a_genre_supernatural": "Servant Power",
        "a_genre_psychological": "Kiritsugu's Method",
        "a_genre_mecha": "None Here",
        "a_critic": "War Judge",
        "a_perfect_ten": "Gilgamesh's Vault",
        "a_harsh_critic": "Kiritsugu's Standard",
        "a_daily_streak": "Daily Battle",
        "a_mega_streak": "War Streak",
        "a_year_long": "Year of War",
        "a_iron_will": "Kiritsugu's Wish",
        "a_hidden_gem": "Hidden Servant",
        "a_cult_classic": "Urobuchi Classic",
        "a_classic_connoisseur": "2011 Fan",
        "a_new_years_resolution": "New War",
        "a_christmas_special": "Winter War",
        "a_meta_tier_max": "War Master",
        "a_meta_completionist": "All Servants",
        "a_sequel_chain": "Fate/stay night",
        "a_zero_to_hero": "Child to Magus Killer",
        "a_night_owl": "Night Battle",
        "a_early_bird": "Dawn Assault",
        "m_first_chapter": "First Summon",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "War Marathon",
        "m_completionist": "Full Novel",
        "m_mega_completionist": "Fate/Zero Expert",
        "m_loyal_reader": "War Reader",
        "m_rereader": "Battle Return",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "War Chapter",
        "m_genre_romance": "King Chapter",
        "m_genre_fantasy": "Magic Chapter",
        "m_genre_horror": "Grail Chapter",
        "m_genre_drama": "Tragedy Chapter",
        "m_genre_scifi": "Circuit Chapter",
        "m_genre_supernatural": "Servant Chapter",
        "m_genre_psychological": "Kiritsugu Depth",
        "m_critic": "War Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "War Reading",
        "m_year_long": "Year Reading",
        "m_iron_will": "Magus Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Gen Urobuchi",
        "m_mangaka_lover": "Urobuchi Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Fate/Zero Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "War Art",
        "m_manga_to_anime": "Novel Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#000002",
        primary: "#2a41a2",
        secondary: "#182a84",
        accent: "#d4b030",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/fate-zero.jpg",
    particleColor: "#4060d8",
    backgroundDim: 0.45,
    backgroundBlur: 24,
    particleTypes: {
        magic_sparks: { label: "Magic Sparks", maxCount: 15, defaultEnabled: true, defaultIntensity: 60 },
        war_embers: { label: "War Embers", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
        1: "Master",
        5: "Kiritsugu Emiya",
        15: "War Participant",
        30: "Magus Killer",
        50: "Servant's Bond",
        75: "Grail Seeker",
        100: "Heroic Legend",
    },
}
