import { AnimeThemeConfig } from "./types"
import {
    GiFireFlake,
    GiMuscleUp,
    GiBullseye,
    GiAnvilImpact,
    GiShield,
    GiDeathSkull,
    GiLightningBranches,
    GiResize,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiSettingsKnobs,
    GiCrossedSwords,
    GiSwordWound,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const fireForceTheme: AnimeThemeConfig = {
    id: "fire-force",
    displayName: "Fire Force",
    description: "Devil's Footprints alight. Shinra Kusakabe walks into the inferno to save humanity from the Infernals and uncover the truth of Adolla.",
    fontFamily: "'Bebas Neue', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
    cssVars: {
        "--color-brand-200": "255 210 195",
        "--color-brand-300": "255 168 140",
        "--color-brand-400": "248 110 75",
        "--color-brand-500": "221 34 0",
        "--color-brand-600": "185 20 0",
        "--color-brand-700": "145 10 0",
        "--color-brand-800": "105 5 0",
        "--color-brand-900": "65 2 0",
        "--color-brand-950": "32 1 0",
        "--brand": "221 34 0",
        "--background": "#070302",
        "--paper": "#0f0805",
        "--color-gray-950": "7 3 2",
        "--color-gray-900": "16 8 5",
        "--color-gray-800": "28 16 10",
        "--color-gray-700": "45 28 20",
        "--color-gray-600": "68 48 36",
        "--color-gray-500": "100 78 65",
        "--color-gray-400": "145 125 112",
        "--color-gray-300": "186 170 160",
        "--color-gray-200": "215 205 198",
        "--color-gray-100": "238 232 228",
        "--color-gray-50": "250 246 244",
    },
    sidebarOverrides: {
        "home": { icon: GiFireFlake, label: "Company 8 HQ" },
        "schedule": { icon: GiAlarmClock, label: "Fire Ops Calendar" },
        "manga": { icon: LuBookOpen, label: "Infernal Reports" },
        "lists": { icon: GiMuscleUp, label: "Soldier Registry" },
        "discover": { icon: GiBullseye, label: "Adolla Survey" },
        "torrent-list": { icon: GiAnvilImpact, label: "Fire Cache" },
        "debrid": { icon: GiShield, label: "Company Intel" },
        "unmatched": { icon: GiDeathSkull, label: "Infernal Files" },
        "enmasse": { icon: GiResize, label: "Mass Response" },
        "scan-summaries": { icon: TbReportSearch, label: "Fire Reports" },
        "auto-downloader": { icon: LuRss, label: "Fire Signal" },
        "community": { icon: GiLightningBranches, label: "Special Fire Brigade" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Infernal Alert" },
        "achievements": { icon: GiTrophy, label: "Fire Force Feats" },
        "theme-manager": { icon: GiPalette, label: "Flame Colors" },
        "extensions": { icon: BiExtension, label: "Benimaru's Add-ons" },
        "sync": { icon: IoCloudOfflineOutline, label: "Adolla Link" },
        "settings": { icon: GiSettingsKnobs, label: "Captain's Command" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Rookie Firefighter",
        "a_episode_counter": "Infernal Encounter Count",
        "a_episode_titan": "Legendary Adolla Battle",
        "a_hours_invested": "Hours of Pyrokinetic Training",
        "a_time_lord": "Eternal Flame Bearer",
        "a_anime_collector": "Fire Arsenal",
        "a_library_legend": "Fire Library Legend",
        "a_first_complete": "First Infernal Extinguished",
        "a_hundred_club": "Century of Fire Missions",
        "a_first_day": "First Day with Shinra",
        "a_first_rating": "First Fire Mission Assessment",
        "a_ten_thousand_min": "Ten Thousand Minutes of Fire",
        "a_season_veteran": "Veteran of the Special Fire Force",
        "a_year_explorer": "Year in the Fire World",
        "a_century_watcher": "Hundred Episodes of Flames",
        "a_five_hundred_eps": "Five Hundred Fire Strikes",
        "a_thousand_eps": "Thousand Infernals Witnessed",
        "a_watching_ten": "Ten Fire Campaigns",
        "a_ptw_hoarder": "Backlog of Fire Studies",
        "a_dropped_honesty": "Tactical Fire Retreat",
        "a_five_thousand_eps": "Five Thousand Fire Sorties",
        "a_ten_completed": "Ten Fire Arcs",
        "a_fifty_completed": "Fifty Fire Force Adventures",
        "a_five_hundred_completed": "Five Hundred Pyrokinetic Victories",
        "a_mean_score_tracker": "Average Fire Rating",
        "a_unique_studios": "Allied Fire Studios",
        "a_days_spent_watching": "Days in the Fire Company",
        "a_all_status": "All Fire Statuses",
        "a_first_favorite": "First Bond with Ogun",
        "a_favorites_collector": "Company 8 Bonds",
        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Fire Marathon",
        "a_marathon_runner": "Adolla Marathon Runner",
        "a_weekend_warrior": "Weekend Fire Warrior",
        "a_non_stop": "Relentless Like Shinra",
        "a_one_more_episode": "One More Infernal Ahead",
        "a_speed_run": "Devil's Footprints Speed Run",
        "a_double_feature": "Double Fire Feature",
        "a_triple_threat": "Triple Infernal Takedown",
        "a_five_a_day": "Five Fire Missions a Day",
        "a_back_to_back": "Back-to-Back Infernal Calls",
        "a_seasonal_binge": "Full Fire Arc Clear",
        "a_cour_crusher": "Fire Cour Crusher",
        "a_half_day_watch": "Half Day of Fire Missions",
        "a_full_day_watch": "Full Day of Pyrokinetics",
        "a_power_weekend": "Power Weekend Fire Study",
        "a_binge_king": "King of Fire Marathons",
        "a_no_sleep": "All-Night Fire Watch",
        "a_entire_season": "Full Fire Force Season Clear",
        "a_seven_day_challenge": "Seven-Day Fire Siege",
        "a_hundred_day_binge": "Hundred-Day Fire Campaign",
        "a_genre_binge": "Cross-Genre Fire Fantasy",
        "a_studio_binge": "Studio Fire Binge",
        "a_season_sweep": "Season Sweep of Flames",
        "a_forty_eight_hour": "Forty-Eight Hour Fire Session",
        "a_ep_counter_day": "Daily Infernal Count",
        "a_multi_series_binge": "Multi-Front Fire Campaign",
        "a_midnight_binge": "Midnight Infernal Session",
        "a_new_year_binge": "New Year's Fire Charge",
        // ── ANIME GENRES ──
        "a_genre_action": "Shinra's Fire Combat",
        "a_genre_adventure": "Journey into Adolla",
        "a_genre_comedy": "Shinra's Nervous Smile",
        "a_genre_drama": "Adolla Drama",
        "a_genre_fantasy": "Fire World Fantasy",
        "a_genre_horror": "Infernal Horror",
        "a_genre_mystery": "Mystery of the Evangelist",
        "a_genre_romance": "Tamaki's Lucky Lecher",
        "a_genre_scifi": "Pyrokinetic Technology",
        "a_genre_sol": "Company 8 Daily Life",
        "a_genre_sports": "Fire Force Tournament",
        "a_genre_supernatural": "Adolla Supernatural",
        "a_genre_thriller": "Evangelist Thriller",
        "a_genre_mecha": "Fire Force Mech Technology",
        "a_genre_music": "Fire Force OST Collection",
        "a_genre_psychological": "Infernal Psychology",
        "a_genre_ecchi": "Lucky Lecher Lure",
        "a_genre_mahou_shoujo": "Tamaki's Fire Training",
        "a_tag_isekai": "Transported to Fire World",
        "a_tag_harem": "Company 8 Bonds",
        "a_tag_bl": "Shinra and Arthur Bond",
        "a_tag_gl": "Tamaki and Iris Bond",
        "a_tag_historical": "Ancient Infernal History",
        "a_tag_military": "Special Fire Brigade",
        "a_tag_school": "Fire Force Academy",
        "a_tag_martial_arts": "Benimaru Combat Style",
        "a_tag_vampire": "Infernal Blood",
        "a_tag_samurai": "Benimaru Warrior Style",
        "a_tag_space": "Adolla Universe",
        "a_tag_parody": "Chibi Fire Force Parody",
        "a_tag_idol": "Shinra's Growing Power",
        "a_tag_post_apocalyptic": "Post-Combustion World",
        "a_tag_cyberpunk": "Advanced Pyro Technology",
        "a_tag_shounen": "Shinra's Fighting Spirit",
        "a_tag_seinen": "Fire Force Reality",
        "a_tag_shoujo": "Iris's Devotion",
        "a_tag_josei": "Maki's Perspective",
        "a_tag_survival": "Surviving the Infernal",
        // ── ANIME COMPLETION ──
        "a_completionist": "Full Fire Report",
        "a_mega_completionist": "Supreme Fire Commander",
        "a_completion_rate_50": "Halfway to Adolla",
        "a_completion_rate_75": "Approaching the Evangelist",
        "a_completion_rate_90": "Final Infernal Nearly Done",
        "a_no_drop": "No Fire Mission Abandoned",
        "a_long_runner_complete": "Long Fire Journey Complete",
        "a_sequel_chain": "Fire Chain Complete",
        "a_clean_list": "Clean Fire Record",
        "a_from_ptw": "Fire Orders Fulfilled",
        "a_rewatch_master": "Reliving Fire Missions",
        "a_short_complete": "Quick Infernal Skirmish",
        "a_same_day_start_finish": "Same-Day Fire Mission",
        "a_revival": "Revival Through Adolla",
        "a_zero_to_hero": "Rookie to Special Fire Soldier",
        "a_five_genre_complete": "Five-Genre Fire Mastery",
        "a_full_franchise": "Full Fire Force Dossier",
        "a_batch_complete": "Batch Fire Clear",
        "a_paused_to_done": "Returned from Fire Hiatus",
        "a_completion_spree": "Completion Fire Barrage",
        "a_multi_rewatch": "Multi-Timeline Fire Journey",
        "a_dropped_recovery": "Recovered from Infernal Attack",
        "a_ten_perfect_scores": "Ten Perfect Fire Scores",
        "a_seasonal_clear": "Seasonal Fire Clear",
        "a_complete_genre_span": "All-Format Fire Fan",
        "a_monthly_completions": "Monthly Fire Reports",
        "a_yearly_completions": "Yearly Fire Campaign",
        "a_rapid_complete": "Lightning Fire Raid",
        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Fire Force Devotee",
        "a_studio_devotee": "Studio David Production Devotee",
        "a_rewatcher": "Fire Recon Rewatch",
        "a_triple_rewatch": "Triple Fire Rewatch",
        "a_annual_tradition": "Annual Fire Remembrance",
        "a_director_fan": "Director's Fire Vision",
        "a_voice_actor_fan": "Voice of the Flame",
        "a_ost_lover": "Fire Force OST Devotee",
        "a_source_reader": "Ohkubo's Original Manga",
        "a_waiting_weekly": "Weekly Fire Chapter Wait",
        "a_childhood_revisit": "Return to the Firehouse",
        "a_saga_tracker": "Saga of Fire Force Tracker",
        "a_genre_loyalty": "Fire Genre Loyalty",
        "a_decade_watcher": "Decade-Long Fire Watcher",
        "a_adaptation_hunter": "Fire Force Adaptation Hunt",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Fire Duty",
        "a_perfect_attendance": "Perfect Fire Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Fire Catalog",
        "a_franchise_collector": "Fire Force Universe Collector",
        "a_airing_follower": "Currently Airing Fire Intel",
        "a_genre_master": "Fire Genre Mastery",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Arc Fire Veteran",
        "a_format_diversity": "Diverse Fire Formats",
        "a_year_dedication": "Year of Dedication to Fire Force",
        "a_season_dedication": "Season of Fire Service",
        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Known Fire",
        "a_studio_hopper": "Fire Company Transfer",
        "a_tag_explorer": "Fire Tag Recon Mission",
        "a_decade_hopper": "Decade Fire Hopping",
        "a_hidden_gem": "Hidden Fire Gem",
        "a_popular_taste": "Popular Among Firefighters",
        "a_retro_appreciator": "Pre-Combustion Era Fan",
        "a_modern_viewer": "Modern Fire Viewer",
        "a_cross_demographic": "Cross-Demographic Fire Fan",
        "a_underdog_fan": "Underdog Fire Spirit",
        "a_variety_week": "Week of Varied Missions",
        "a_foreign_cinema": "Foreign Fire Cinema",
        "a_classic_connoisseur": "Classic Fire Fan",
        "a_every_season": "Every Season in the Fire Company",
        "a_award_winner": "Medal of Fire Valor",
        "a_niche_explorer": "Niche Fire Territory",
        "a_global_anime": "Global Fire Alliance",
        "a_cult_classic": "Fire Force Cult Classic",
        "a_random_pick": "Random Fire Assignment",
        "a_new_genre_month": "New Fire Territory Monthly",
        "a_seasonal_completionist": "Seasonal Fire Clear",
        "a_unpopular_opinion": "Unpopular Fire Opinion",
        "a_top_rated_viewer": "Top-Rated Fire Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Fire Intel",
        "a_short_series_explorer": "Short Fire Skirmish Explorer",
        "a_long_series_explorer": "Long Fire Campaign Explorer",
        // ── ANIME TIME ──
        "a_night_owl": "Night Watch at the Firehouse",
        "a_early_bird": "Dawn Fire Drill",
        "a_lunch_break": "Company 8 Lunch Break",
        "a_golden_hour": "Golden Hour of Fire",
        "a_four_am_club": "4 AM Fire Sentry",
        "a_witching_hour": "Infernal Witching Hour",
        "a_new_year_watch": "New Year's Fire Oath",
        "a_midnight_premiere": "Midnight Fire Force Premiere",
        "a_all_hours": "All-Hours Fire Vigil",
        "a_dawn_warrior": "Dawn Fire Warrior",
        "a_afternoon_delight": "Afternoon Firehouse Rest",
        "a_prime_time": "Prime Time Infernal Battle",
        "a_workday_watcher": "On-Duty Fire Watcher",
        "a_sunday_marathon": "Sunday Fire Marathon",
        "a_rainy_day": "Rainy Day in the Firehouse",
        "a_morning_routine": "Morning Fire Drill",
        "a_night_shift": "Night Shift Fire Guard",
        "a_twilight_zone": "Twilight Infernal Encounter",
        "a_seasonal_premier": "Season Premiere Infernal Reveal",
        "a_clock_collector": "Fire Clock Collector",
        "a_weekend_binge_hours": "Weekend Fire Binge",
        "a_late_night_regular": "Late Night Regular Firefighter",
        "a_sunrise_watcher": "Sunrise After Fire Mission",
        "a_holiday_watcher": "Holiday Fire Duty",
        "a_every_day_of_week": "Every Day a Firefighter",
        "a_monthly_hours": "Monthly Fire Hours",
        // ── ANIME SOCIAL ──
        "a_first_party": "First Fire Team Formation",
        "a_party_host": "Company 8 Commander",
        "a_social_butterfly": "Firehouse Socialite",
        "a_group_binge": "Group Fire Viewing",
        "a_party_regular": "Regular Fire Partner",
        "a_sync_viewer": "Synchronized Fire Maneuver",
        "a_commentator": "Infernal Battle Commentator",
        "a_party_marathon": "Marathon Fire Run",
        "a_full_house": "Full Fire Team",
        "a_community_pillar": "Pillar of Company 8",
        "a_watch_party_streak": "Consecutive Fire Streak",
        "a_diverse_party": "Diverse Fire Party",
        "a_late_night_party": "Late Night Fire Party",
        "a_party_veteran": "Veteran Fire Leader",
        "a_genre_party": "Cross-Genre Fire Formation",
        "a_weekly_party": "Weekly Firefighters' Gathering",
        "a_silent_viewer": "Silent Like Iris Observer",
        "a_recommendation_giver": "Shinra's Recommendation",
        "a_party_completionist": "Party Fire Completionist",
        "a_social_scorer": "Social Fire Scorer",
        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Fire Formation",
        "a_fibonacci": "Fibonacci Fire Sequence",
        "a_palindrome_day": "Palindrome Fire Loop",
        "a_binary_day": "Binary Fire Signal Day",
        "a_full_moon": "Full Moon Infernal Activation",
        "a_leap_year": "Adolla Leap Year",
        "a_time_traveler": "Adolla Time Link",
        "a_genre_clash": "Shinra vs Sho Clash",
        "a_triple_seven": "Triple Seven Fire Points",
        "a_thousand_complete": "Thousand Fire Battles",
        "a_pi_episodes": "Pi Fire Calculation",
        "a_synchronicity": "Shinra-Sho Synchronicity",
        "a_world_record": "World Record Infernal Count",
        "a_nice": "Nice Fire Count",
        "a_power_level": "Devil's Footprints Power Level",
        "a_answer_42": "Answer to Fire Life",
        "a_square_number": "Perfect Fire Formation",
        "a_prime_count": "Prime Fire Count",
        "a_matching_date": "Matching Fire Date",
        "a_century_episode": "Century Episode Fire Mission",
        "a_double_digits": "Double Digit Infernals",
        "a_one_two_three": "Shinra Arthur Tamaki",
        "a_lucky_seven": "Seven Lucky Firefighters",
        "a_all_tens": "All Tens Fire Score",
        "a_exact_hundred_eps": "Exact Hundred Fire Missions",
        "a_year_match_count": "Year Match Fire Count",
        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Fire Watcher",
        "a_movie_buff": "Fire Force Movie Expedition",
        "a_ova_hunter": "OVA Fire Hunter",
        "a_ona_explorer": "ONA Fire Explorer",
        "a_special_watcher": "Special Fire Episode",
        "a_short_king": "Short Fire Skirmish King",
        "a_variety_pack": "All-Format Fire Regiment",
        "a_film_festival": "Fire Film Festival",
        "a_music_video": "Fire Force Music Video",
        "a_tv_short": "Quick Fire Recon Clip",
        "a_movie_marathon": "Fire Force Movie Marathon",
        "a_double_length": "Double-Length Fire Operation",
        "a_anthology": "Fire Force Anthology",
        "a_mini_series": "Mini Fire Campaign",
        "a_theatrical": "Theatrical Fire Premiere",
        "a_format_master": "Format Master Fire Fan",
        "a_long_movie": "Feature-Length Fire Expedition",
        "a_back_catalog": "Back Catalog Fire Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Fire Collector",
        "a_format_balance": "Balanced Fire Formats",
        "a_episodic_master": "Episodic Fire Master",
        "a_sequel_movie": "Sequel Fire Film",
        "a_recap_watcher": "Recap Fire Briefing",
        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Fire Drill Streak",
        "a_mega_streak": "Mega Fire Streak",
        "a_weekly_warrior": "Weekly Fire Warrior",
        "a_monthly_watcher": "Monthly Fire Duty",
        "a_comeback": "Return from Fire Hiatus",
        "a_weekend_streak": "Weekend Fire Streak",
        "a_no_zero_days": "No Zero Fire Days",
        "a_iron_will": "Iron Will of the Firefighter",
        "a_habit_formed": "Fire Training Regimen Formed",
        "a_consistent_pace": "Consistent Fire Advance",
        "a_year_long": "Year-Long Fire Campaign",
        "a_double_streak": "Double Fire Assault Streak",
        "a_streak_recovery": "Recovery After Infernal Attack",
        "a_daily_minimum": "Daily Minimum Fire Duty",
        "a_winter_streak": "Winter Fire Campaign",
        "a_summer_streak": "Summer Fire Offensive",
        "a_morning_streak": "Morning Fire Drill Streak",
        "a_night_streak": "Night Fire Patrol Streak",
        "a_unbreakable": "Unbreakable Fire Will",
        "a_eternal_flame": "Eternal Adolla Flame",
        "a_completion_streak": "Completion Fire Chain",
        "a_rating_streak": "Rating Fire Streak",
        "a_multi_ep_streak": "Multi-Episode Fire Offensive",
        "a_genre_streak": "Genre Fire Streak",
        "a_studio_streak": "Studio Fire Loyalty Streak",
        "a_perfect_week": "Perfect Week of Fire Service",
        // ── ANIME SCORING ──
        "a_critic": "Special Fire Force Judge",
        "a_perfect_ten": "Perfect 10 Fire Rating",
        "a_harsh_critic": "Benimaru's Harsh Standards",
        "a_fair_judge": "Hibana's Fair Assessment",
        "a_generous_spirit": "Generous Fire Spirit",
        "a_score_all": "Full Fire Roster Evaluation",
        "a_wide_range": "Wide Range Fire Assessment",
        "a_controversial": "Controversial Fire Decision",
        "a_consistent_scorer": "Consistent Fire Evaluator",
        "a_score_sniper": "Precision Fire Sniper",
        "a_evolving_taste": "Evolving Fire Strategy",
        "a_bell_curve": "Bell Curve Fire Scores",
        "a_picky_watcher": "Selective Fire Commander",
        "a_100_rated": "Century of Fire Evaluations",
        "a_500_rated": "Five Hundred Fire Reports",
        "a_mediocre_majority": "Middle Ground Firefighter",
        "a_rating_spree": "Fire Rating Barrage",
        "a_score_variance": "Variable Fire Ratings",
        "a_masterpiece_hunter": "Masterpiece Fire Hunter",
        "a_contrarian": "Contrarian Fire Scout",
        "a_optimist": "Optimist of the Flame",
        "a_score_distributor": "Score Distributor Fire General",
        "a_genre_critic": "Genre Fire Critic",
        "a_mean_above_8": "Elite Fire Average",
        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Fire Vow",
        "a_valentines_weeb": "Valentine's Fire Bond",
        "a_pi_day": "Pi Day Fire Calculation",
        "a_april_fools": "April Fools Fire Prank",
        "a_international_anime_day": "International Fire Day",
        "a_star_wars_day": "Adolla Force Day",
        "a_summer_solstice": "Summer Solstice Infernal Surge",
        "a_tanabata": "Tanabata Fire Wish",
        "a_friday_13th": "Friday 13th Infernal Spawn",
        "a_halloween_spirit": "Halloween Infernal Attack",
        "a_thanksgiving_binge": "Thanksgiving Fire Feast",
        "a_christmas_special": "Midwinter Fire Festival",
        "a_new_years_eve": "New Year's Eve Adolla Stand",
        "a_birthday_watch": "Birthday Fire Enlistment",
        "a_holiday_marathon": "Holiday Fire Marathon",
        "a_independence_day": "Human Independence Day",
        "a_culture_day": "Fire Culture Day",
        "a_spring_equinox": "Spring Fire Advance",
        "a_earth_day": "Earth Day Firefighter",
        "a_labor_day": "Fire Labor Day",
        "a_winter_solstice": "Winter Fire Solstice Night",
        "a_anime_birthday": "Fire Force Anniversary",
        "a_every_holiday": "Every Holiday Fire Scout",
        "a_consecutive_holidays": "Consecutive Holiday Missions",
        // ── ANIME META ──
        "a_meta_first_unlock": "First Pyrokinetic Awakening",
        "a_meta_collector": "Fire Badge Collector",
        "a_meta_category_starter": "Category Fire Initiation",
        "a_meta_tier_climber": "Fire Rank Promotion",
        "a_meta_tier_max": "Special Fire Soldier Class",
        "a_meta_xp_earner": "XP from Infernal Encounters",
        "a_meta_difficulty_easy": "Easy Flame",
        "a_meta_difficulty_hard": "Legendary Evangelist Mode",
        "a_meta_unlock_spree": "Unlock Spree Fire Barrage",
        "a_meta_completionist": "Meta Fire Completionist",
        "a_meta_diverse": "Diverse Fire Portfolio",
        "a_meta_dominator": "Meta Dominator of Fire",
        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Fire Chapter",
        "m_chapter_counter": "Fire Chapter Counter",
        "m_chapter_titan": "Legendary Chapter Mission",
        "m_reading_hours": "Hours Studying Fire Texts",
        "m_reading_time_lord": "Fire Timeless Reading",
        "m_manga_collector": "Fire Archive Collector",
        "m_library_legend": "Fire Library Reading Legend",
        "m_first_complete": "First Fire Force Manga Done",
        "m_hundred_club": "Hundred-Chapter Fire Club",
        "m_first_day": "First Day Fire Reading",
        "m_first_rating": "First Fire Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Fire Pages",
        "m_volume_collector": "Fire Volume Collector",
        "m_year_explorer": "Year of Fire Exploration",
        "m_century_reader": "Century Fire Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Fire Chapters",
        "m_thousand_ch": "Thousand-Chapter Fire Campaign",
        "m_reading_ten": "Ten Fire Manuscripts at Once",
        "m_ptr_hoarder": "Fire Reading Backlog",
        "m_dropped_honesty": "Honest Fire Retreat",
        "m_season_reader": "Fire Seasonal Reading",
        "m_active_reader": "Active Fire Field Reader",
        "m_five_thousand_ch": "Five Thousand Fire Chapters",
        "m_ten_completed": "Ten Fire Manga Complete",
        "m_fifty_completed": "Fifty Fire Missions Done",
        "m_five_hundred_completed": "Five Hundred Fire Victories",
        "m_mean_score_tracker": "Average Fire Manuscript Rating",
        "m_unique_authors": "Unique Fire Author Encounters",
        "m_all_status": "All Fire Reading Statuses",
        "m_first_favorite": "First Fire Manga Bond",
        "m_favorites_collector": "Fire Favorites Arsenal",
        "m_days_spent_reading": "Days in Fire Garrison",
        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Fire Reading",
        "m_marathon_reader": "Infernal Marathon Reader",
        "m_weekend_reader": "Weekend Fire Reading",
        "m_non_stop_reading": "Non-Stop Fire Page Turning",
        "m_one_more_chapter": "One More Fire Chapter",
        "m_speed_read": "Devil's Footprints Speed Read",
        "m_double_story": "Double Fire Manuscript",
        "m_triple_read": "Triple Fire Reading",
        "m_five_a_day": "Five Fire Reads a Day",
        "m_chapter_chain": "Fire Chapter Chain",
        "m_volume_binge": "Fire Volume Binge",
        "m_power_reader": "Power Fire Reader",
        "m_half_day_read": "Half-Day Fire Archive",
        "m_full_day_read": "Full-Day Fire Study",
        "m_power_weekend": "Power Fire Weekend Reading",
        "m_binge_king": "King of the Fire Reading Corps",
        "m_no_sleep_read": "All-Night Fire Reading",
        "m_full_series_rush": "Full Fire Force Series Rush",
        "m_seven_day_challenge": "Seven-Day Fire Gathering",
        "m_hundred_day_read": "Hundred-Day Fire Reading",
        "m_volume_rush": "Fire Volume Rush",
        "m_series_sweep": "Fire Series Sweep",
        "m_genre_binge": "Cross-Genre Fire Reading",
        "m_author_binge": "Ohkubo Deep Dive",
        "m_chapter_counter_day": "Daily Fire Chapter Count",
        "m_multi_series_binge": "Multi-Series Fire Reading",
        "m_midnight_binge": "Midnight Fire Archive",
        "m_new_year_binge": "New Year's Fire Reading",
        "m_forty_eight_hour": "Forty-Eight Hour Fire Read",
        "m_oneshot_binge": "Oneshot Fire Blitz",
        // ── MANGA GENRES ──
        "m_genre_action": "Fire Action Manuscript",
        "m_genre_adventure": "Adolla Adventure Manga",
        "m_genre_comedy": "Shinra's Smile Chapters",
        "m_genre_drama": "Adolla Drama Manga",
        "m_genre_fantasy": "Fire World Fantasy Manga",
        "m_genre_horror": "Infernal Horror Manga",
        "m_genre_mystery": "Evangelist Mystery Manga",
        "m_genre_romance": "Lucky Lecher Manga",
        "m_genre_scifi": "Pyro Technology Manga",
        "m_genre_sol": "Company 8 Daily Life Manga",
        "m_genre_sports": "Fire Force Tournament Manga",
        "m_genre_supernatural": "Adolla Supernatural Manga",
        "m_genre_thriller": "Evangelist Thriller Manga",
        "m_genre_psychological": "Fire Psychology Manga",
        "m_genre_isekai": "Isekai Fire World",
        "m_genre_shounen": "Shinra Shounen Heart",
        "m_genre_ecchi": "Lucky Lecher Manga",
        "m_genre_mahou_shoujo": "Tamaki Fire Training Manga",
        "m_genre_mecha": "Fire Mech Manga",
        "m_genre_music": "Fire Force OST Manga",
        "m_tag_isekai_new": "New Fire World",
        "m_tag_harem": "Company 8 Manga",
        "m_tag_bl": "Shinra and Arthur Manga",
        "m_tag_gl": "Tamaki and Iris Manga",
        "m_tag_historical": "Ancient Infernal History Manga",
        "m_tag_military": "Special Fire Brigade Manga",
        "m_tag_school": "Fire Academy Manga",
        "m_tag_martial_arts": "Benimaru Combat Manual",
        "m_tag_vampire": "Infernal Blood Manga",
        "m_tag_samurai": "Benimaru Warrior Manga",
        "m_tag_space": "Adolla Universe Manga",
        "m_tag_parody": "Chibi Fire Force Manga",
        "m_tag_idol": "Shinra Power Manga",
        "m_tag_post_apocalyptic": "Post-Combustion Manga",
        "m_tag_cyberpunk": "Advanced Pyro Tech Manga",
        "m_tag_shoujo": "Iris Devotion Manga",
        "m_tag_survival": "Survival in Infernal Manga",
        "m_tag_cooking": "Firehouse Kitchen Manga",
        "m_tag_medical": "Fire Medic Manga",
        "m_tag_villainess": "Evangelist Villainess Manga",
        // ── MANGA COMPLETION ──
        "m_completionist": "Fire Manga Completionist",
        "m_mega_completionist": "Supreme Fire Commander",
        "m_completion_rate_50": "Halfway to Adolla",
        "m_completion_rate_75": "Approaching the Evangelist",
        "m_completion_rate_90": "Final Fire Chapter Near",
        "m_no_drop": "No Fire Manga Abandoned",
        "m_long_runner_complete": "Long Fire Series Endurance",
        "m_sequel_chain": "Sequel Fire Arc Chain",
        "m_clean_list": "Clean Fire Reading Record",
        "m_from_ptr": "Orders Received Fire Read",
        "m_reread_master": "Fire Mission Reread",
        "m_oneshot_complete": "Oneshot Fire Mission",
        "m_same_day_start_finish": "Same-Day Fire Blitz",
        "m_revival": "Revival Through Adolla",
        "m_zero_to_hundred": "Rookie to Special Fire Scholar",
        "m_five_genre_complete": "Five Fire Genres Mastered",
        "m_full_collection": "Full Fire Archive",
        "m_batch_complete": "Fire Batch Clearance",
        "m_paused_to_done": "Back from Fire Hiatus",
        "m_completion_spree": "Fire Completion Barrage",
        "m_format_completionist": "Fire Format Completion",
        "m_catch_up": "Caught Up with Fire Serialization",
        "m_multi_reread": "Multi-Pass Fire Reread",
        "m_dropped_recovery": "Recovered from Infernal Attack",
        "m_ten_perfect_scores": "Ten Perfect Fire Scores",
        "m_complete_genre_span": "All-Genre Fire Scout",
        "m_monthly_completions": "Monthly Fire Victories",
        "m_yearly_completions": "Yearly Fire Campaign",
        "m_rapid_complete": "Rapid Fire Processing",
        "m_author_complete": "Ohkubo's Complete Works",
        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Fire Reader",
        "m_mangaka_lover": "Ohkubo Devotee",
        "m_rereader": "Fire Force Saga Rereader",
        "m_triple_reread": "Triple Fire Reread",
        "m_annual_reread": "Annual Fire Force Reread",
        "m_publisher_fan": "Fire Publisher Fan",
        "m_artist_fan": "Ohkubo Art Appreciation",
        "m_adaptation_compare": "Fire Force Manga vs Anime Compare",
        "m_source_material_fan": "Fire Source Material Scout",
        "m_waiting_weekly": "Weekly Fire Chapter Wait",
        "m_classic_reader": "Classic Fire Manuscript",
        "m_saga_reader": "Saga of Fire Force Reader",
        "m_genre_loyalty": "Fire Genre Loyalty",
        "m_decade_reader": "Decade-Long Fire Reader",
        "m_ln_adaptation": "Fire Light Novel Intel",
        "m_original_work": "Ohkubo's Original Work",
        "m_long_commitment": "Long-Term Fire Reading",
        "m_up_to_date": "Up-to-Date with Fire Force",
        "m_favorite_mangaka": "Ohkubo Honored",
        "m_complete_portfolio": "Complete Fire Portfolio",
        "m_franchise_collector": "Fire Force Franchise Collector",
        "m_serialization_follower": "Fire Serialization Tracker",
        "m_genre_master": "Fire Genre Mastery",
        "m_multi_series_author": "Multi-Series Fire Author Fan",
        "m_format_diversity": "Diverse Fire Reading Formats",
        "m_year_dedication": "Year of Fire Reading",
        "m_ongoing_follower": "Ongoing Fire Series",
        "m_genre_loyalty_50": "Fifty Fire Genre Chapters",
        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Fire Genre Territory Scout",
        "m_publisher_hopper": "Fire Publisher Transfer",
        "m_tag_explorer": "Fire Tag Recon Mission",
        "m_decade_hopper": "Fire Decade Hopping",
        "m_hidden_gem": "Hidden Fire Gem",
        "m_popular_taste": "Popular Among Firefighters",
        "m_retro_reader": "Retro Fire Manuscript",
        "m_modern_reader": "Modern Fire Era Reader",
        "m_cross_demographic": "Cross-Demographic Fire Scout",
        "m_underdog_fan": "Underdog Fire Fan",
        "m_variety_week": "Week of Fire Readings",
        "m_manhwa_reader": "Fire Manhwa Reader",
        "m_manhua_reader": "Fire Manhua Reader",
        "m_classic_connoisseur": "Classic Fire Connoisseur",
        "m_award_winner": "Medal-Winning Fire Manga",
        "m_niche_explorer": "Niche Fire Territory",
        "m_world_manga": "World Fire Manga",
        "m_cult_classic": "Fire Force Cult Classic",
        "m_random_pick": "Random Fire Assignment",
        "m_new_genre_month": "New Fire Genre Monthly",
        "m_year_completionist": "Year Fire Completionist",
        "m_unpopular_opinion": "Unpopular Fire Opinion",
        "m_top_rated_reader": "Top-Rated Fire Source",
        "m_source_variety": "Fire Source Variety",
        "m_low_score_brave": "Brave Fire Low-Score Reader",
        "m_short_manga_explorer": "Short Fire Skirmish",
        "m_long_manga_explorer": "Long Fire Campaign Manuscript",
        "m_serialization_explorer": "Fire Serialization Explorer",
        // ── MANGA TIME ──
        "m_night_owl": "Night Fire Reading",
        "m_early_bird": "Dawn Fire Reading",
        "m_lunch_reader": "Firehouse Lunch Fire Reading",
        "m_commute_reader": "Fire Commute Reading",
        "m_four_am_club": "4 AM Fire Reader",
        "m_new_year_read": "New Year's Fire Reading Oath",
        "m_all_hours": "All-Hours Fire Archive",
        "m_prime_time_reader": "Prime Time Fire Manuscript",
        "m_workday_reader": "On-Duty Fire Reader",
        "m_sunday_read": "Sunday Fire Reading Marathon",
        "m_morning_routine": "Morning Fire Formation Reading",
        "m_night_shift_reader": "Night Fire Guard Reader",
        "m_seasonal_premier_read": "Fire New Release Intel",
        "m_clock_collector": "Fire Clock Collector",
        "m_late_night_horror": "Midnight Infernal Horror Read",
        "m_afternoon_reader": "Afternoon Fire Reading",
        "m_golden_hour_reader": "Golden Hour Fire Reading",
        "m_dawn_reader": "Dawn Fire Reading Scout",
        "m_twilight_reader": "Twilight Fire Mission Reading",
        "m_midnight_start": "Midnight Fire Reading Mission",
        "m_weekend_binge_hours": "Weekend Fire Binge Reading",
        "m_late_night_regular": "Late Night Fire Reader",
        "m_sunrise_reader": "Sunrise After Fire Mission Reader",
        "m_every_day_of_week": "Every Day Fire Reading",
        "m_monthly_hours": "Monthly Fire Hours Logged",
        "m_bedtime_reader": "Bedtime Fire Reader",
        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Ohkubo Art Appreciator",
        "m_webtoon_reader": "Fire Webtoon Intelligence",
        "m_full_color": "Full Color Fire Manuscript",
        "m_doujin_reader": "Underground Fire Doujin",
        "m_anthology_reader": "Fire Anthology Reader",
        "m_adaptation_reader": "Fire Adaptation Study",
        "m_longstrip_reader": "Vertical Fire Scroll Reader",
        "m_4koma_reader": "4-Koma Fire Comedy",
        "m_oneshot_reader": "Oneshot Fire Mission Reader",
        "m_format_variety": "Fire Format Variety",
        "m_light_novel_reader": "Fire Light Novel Reader",
        "m_novel_reader": "Fire Novel Archive Reader",
        "m_visual_storyteller": "Fire Battle Narrator",
        "m_colored_classic": "Colored Fire Classic",
        "m_webcomic_fan": "Fire Webcomic Fan",
        "m_manga_to_anime": "Fire Force Manga to Anime",
        "m_seinen_reader": "Seinen Fire Reader",
        "m_josei_reader": "Josei Fire Perspective",
        "m_award_winning_art": "Medal-Winning Fire Artwork",
        "m_debut_work": "Fire Debut Manuscript",
        "m_vertical_scroll": "Vertical Fire Scroll Intel",
        "m_traditional_format": "Traditional Fire Format",
        "m_cross_media": "Fire Cross-Media Intel",
        "m_spinoff_reader": "Fire Spinoff Mission",
        "m_remake_reader": "Fire Remake Assignment",
        "m_collaboration_reader": "Fire Joint Operation Manuscript",
        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Fire Reading Streak",
        "m_mega_streak": "Mega Fire Reading Streak",
        "m_weekly_warrior": "Weekly Fire Warrior Reader",
        "m_monthly_reader": "Monthly Fire Reader",
        "m_comeback": "Return from Fire Exile",
        "m_weekend_streak": "Weekend Fire Reading Streak",
        "m_no_zero_days": "No Zero Fire Reading Days",
        "m_iron_will": "Iron Will Fire Reader",
        "m_habit_formed": "Fire Reading Regimen",
        "m_consistent_pace": "Consistent Fire Advance",
        "m_year_long": "Year-Long Fire Reading",
        "m_double_streak": "Double Fire Reading Streak",
        "m_streak_recovery": "Fire Reading Streak Recovery",
        "m_daily_minimum": "Daily Fire Minimum Pages",
        "m_winter_streak": "Winter Fire Reading Campaign",
        "m_summer_streak": "Summer Fire Offensive Reading",
        "m_morning_streak": "Morning Fire Formation Reading",
        "m_night_streak": "Night Fire Patrol Reading",
        "m_unbreakable": "Unbreakable Fire Reading Will",
        "m_eternal_flame": "Eternal Adolla Flame Reading",
        "m_chapter_a_day": "Chapter a Day Fire Discipline",
        "m_genre_streak": "Genre Fire Reading Streak",
        "m_completion_streak": "Completion Fire Reading Chain",
        "m_rating_streak": "Fire Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Fire Streak",
        "m_author_streak": "Ohkubo Dedication Streak",
        "m_perfect_week_manga": "Perfect Fire Reading Week",
        "m_diverse_streak": "Diverse Fire Reading Streak",
        // ── MANGA SCORING ──
        "m_critic": "Fire Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Fire Manuscript",
        "m_harsh_critic": "Benimaru's Reading Standards",
        "m_fair_judge": "Hibana's Fair Review",
        "m_generous_spirit": "Generous Fire Reader Spirit",
        "m_score_all": "Full Fire Manuscript Assessment",
        "m_wide_range": "Wide Range Fire Scores",
        "m_controversial": "Controversial Fire Opinion",
        "m_consistent_scorer": "Consistent Fire Scorer",
        "m_score_sniper": "Precision Fire Score Sniper",
        "m_evolving_taste": "Evolving Fire Reading Taste",
        "m_bell_curve": "Bell Curve Fire Scores",
        "m_picky_reader": "Selective Fire Reader",
        "m_100_rated": "Century of Fire Ratings",
        "m_500_rated": "Five Hundred Fire Ratings",
        "m_mediocre_majority": "Middle Ground Fire Reader",
        "m_rating_spree": "Fire Rating Barrage",
        "m_score_variance": "Variable Fire Scores",
        "m_binge_rater": "Binge Fire Rating Session",
        "m_reread_rerate": "Reread and Re-Rate Fire Force",
        "m_masterpiece_hunter": "Masterpiece Fire Manuscript Hunter",
        "m_contrarian": "Contrarian Fire Reader",
        "m_optimist": "Optimistic Fire Reader",
        "m_score_distributor": "Score Distributor Fire General",
        "m_genre_critic": "Genre Fire Reading Critic",
        "m_mean_above_8": "Elite Fire Reading Average",
        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Fire Reading Vow",
        "m_valentines_read": "Valentine's Fire Bond Read",
        "m_pi_day": "Pi Day Fire Chapter Count",
        "m_april_fools": "April Fools Fire Prank",
        "m_international_manga_day": "International Fire Manga Day",
        "m_free_comic_day": "Free Fire Comic Day",
        "m_summer_solstice": "Summer Solstice Fire Reading",
        "m_tanabata": "Tanabata Fire Reading Wish",
        "m_friday_13th": "Friday 13th Infernal Spawn Read",
        "m_halloween_read": "Halloween Infernal Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Fire Reading Feast",
        "m_christmas_read": "Midwinter Festival Fire Read",
        "m_new_years_eve": "New Year's Eve Adolla Stand Read",
        "m_birthday_read": "Birthday Fire Reading Gift",
        "m_holiday_marathon": "Holiday Fire Reading Marathon",
        "m_independence_day": "Human Independence Fire Reading",
        "m_culture_day": "Fire Culture Day Manuscript",
        "m_spring_equinox": "Spring Fire Equinox Reading",
        "m_earth_day": "Earth Day Firefighter Reading",
        "m_labor_day": "Fire Labor Reading Day",
        "m_winter_solstice": "Winter Fire Solstice Reading",
        "m_manga_birthday": "Fire Force Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Fire Reader",
        "m_consecutive_holidays": "Consecutive Fire Holiday Reads",
        // ── MANGA SPECIAL ──
        "m_round_number": "Fire Round Number Milestone",
        "m_fibonacci": "Fire Fibonacci Pattern",
        "m_palindrome_day": "Palindrome Fire Reading Day",
        "m_binary_day": "Binary Fire Signal Day",
        "m_full_moon_read": "Full Moon Fire Read",
        "m_leap_year_read": "Leap Year Fire Reading",
        "m_triple_seven": "Triple Seven Fire Points",
        "m_thousand_complete": "Thousand Fire Victories",
        "m_nice": "Nice Fire Chapter Count",
        "m_power_level_chapters": "Devil's Footprints Chapters",
        "m_answer_42": "Answer to Fire Life Reading",
        "m_square_number": "Perfect Fire Formation Chapters",
        "m_prime_count": "Prime Fire Chapter Count",
        "m_matching_date": "Matching Fire Reading Date",
        "m_century_chapter": "Century Fire Chapter Milestone",
        "m_pi_chapters": "Pi Fire Chapter Calculation",
        "m_synchronicity": "Fire Reading Synchronicity",
        "m_world_record": "World Record Fire Chapter Count",
        "m_genre_clash": "Fire Genre Clash Reading",
        "m_time_traveler": "Time-Traveling Fire Reader",
        "m_double_digits": "Double Digit Fire Milestone",
        "m_one_two_three": "Shinra Arthur Tamaki Chapters",
        "m_lucky_seven": "Seven Lucky Fire Chapters",
        "m_exact_hundred_ch": "Exact Hundred Fire Chapters",
        "m_year_match_count": "Year Match Fire Count",
        "m_chapter_match_date": "Chapter Fire Date Match",
        // ── MANGA FORMATS ──
        "m_manga_format": "Fire Manga Format Specialist",
        "m_manhwa_format": "Fire Manhwa Format Reader",
        "m_manhua_format": "Fire Manhua Format Reader",
        "m_ln_format": "Fire Light Novel Format",
        "m_oneshot_format": "Oneshot Fire Format",
        "m_doujin_format": "Fire Doujin Format Reader",
        "m_novel_format": "Fire Novel Format Reader",
        "m_format_master_manga": "Format Fire Master Reader",
        // ── MANGA META ──
        "m_meta_first_unlock": "First Pyrokinetic Reading Power",
        "m_meta_collector": "Fire Reading Badge Collector",
        "m_meta_category_starter": "Fire Category Initiation",
        "m_meta_tier_climber": "Fire Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Fire Reading Rank",
        "m_meta_xp_earner": "XP from Fire Reading Intel",
        "m_meta_difficulty_easy": "Easy Flame Reading",
        "m_meta_difficulty_hard": "Legendary Evangelist Manuscript",
        "m_meta_unlock_spree": "Fire Reading Unlock Barrage",
        "m_meta_completionist": "Meta Fire Completionist",
        "m_meta_diverse": "Diverse Fire Portfolio",
        "m_meta_dominator": "Meta Dominator Fire Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#070302",
        primary: "#dd2200",
        secondary: "#bb1800",
        accent: "#ff8800",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        fire_sparks: { label: "Fire Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 60 },
        ember_drift: { label: "Ember Drift", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        smoke_wisps: { label: "Smoke Wisps", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        flame_burst: { label: "Flame Burst", maxCount: 6, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1: "Rookie Firefighter",
        5: "Company 8 Trainee",
        15: "Third-Generation Pyrokinetic",
        30: "Adolla Link Detected",
        45: "Special Fire Soldier",
        60: "Knight King Rival",
        80: "Evangelist's Target",
        100: "Shinra Kusakabe — Devil's Footprints",
    },
}
