import { AnimeThemeConfig } from "./types"
import { GiFist, GiDeathSkull, GiFlame, GiDesert, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiSpikyExplosion } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const fistOfTheNorthStarTheme: AnimeThemeConfig = {
    id: "fist-of-the-north-star",
    displayName: "Fist of the North Star",
    description: "In a nuclear wasteland, Kenshiro wanders seeking Yuria — his fists strike the 708 pressure points of Hokuto Shinken, making enemies explode from the inside. You are already dead.",
    fontFamily: "'Anton', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Anton&display=swap",
    cssVars: {
        "--color-brand-200": "255 140 120",
        "--color-brand-300": "248 90 70",
        "--color-brand-400": "235 48 30",
        "--color-brand-500": "212 18 8",
        "--color-brand-600": "175 10 4",
        "--color-brand-700": "136 6 2",
        "--color-brand-800": "96 3 1",
        "--color-brand-900": "58 1 0",
        "--color-brand-950": "33 0 0",
        "--brand": "212 18 8",
        "--background": "#080300",
        "--paper": "#140600",
        "--color-gray-950": "8 3 0",
        "--color-gray-900": "18 8 2",
        "--color-gray-800": "34 16 6",
        "--color-gray-700": "56 28 12",
        "--color-gray-600": "84 44 20",
        "--color-gray-500": "122 70 36",
        "--color-gray-400": "164 108 72",
        "--color-gray-300": "198 148 110",
        "--color-gray-200": "220 182 150",
        "--color-gray-100": "236 212 190",
        "--color-gray-50": "248 238 228",
    },
    sidebarOverrides: {
        "home": { icon: GiDesert, label: "Nuclear Wasteland" },
        "schedule": { icon: GiAlarmClock, label: "Warrior's Schedule" },
        "manga": { icon: LuBookOpen, label: "Secret Scrolls" },
        "lists": { icon: GiDeathSkull, label: "Enemies Roster" },
        "discover": { icon: GiBullseye, label: "Territory Recon" },
        "torrent-list": { icon: GiFist, label: "Combat Cache" },
        "debrid": { icon: GiFlame, label: "Wasteland Fuel" },
        "unmatched": { icon: GiSpikyExplosion, label: "Unnamed Foes" },
        "enmasse": { icon: GiResize, label: "Army Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Intel" },
        "auto-downloader": { icon: LuRss, label: "Wasteland Signals" },
        "community": { icon: GiFist, label: "Fist School" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Enemy Alerts" },
        "achievements": { icon: GiTrophy, label: "Warrior Seals" },
        "milestones": { icon: LuFlag, label: "Fist Goals" },
        "theme-manager": { icon: GiPalette, label: "Scar Design" },
        "extensions": { icon: BiExtension, label: "Technique Unlocks" },
        "sync": { icon: IoCloudOfflineOutline, label: "Wasteland Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Pressure Points" },
    },
    achievementNames: {
        "a_first_episode": "First Strike",
        "a_first_complete": "Already Dead",
        "a_hundred_club": "Hundred Slain",
        "a_time_lord": "Wasteland Walker",
        "a_anime_collector": "Technique Mastered",
        "a_library_legend": "Hokuto Archives",
        "a_binge_king": "Non-Stop Carnage",
        "a_no_sleep": "All-Night Battle",
        "a_marathon_runner": "Endless Walk",
        "a_speed_run": "Teleport Strike",
        "a_completionist": "Wasteland Saved",
        "a_mega_completionist": "Hokuto Master",
        "a_loyal_fan": "Kenshiro's Ally",
        "a_rewatcher": "Return to Wasteland",
        "a_decade_watcher": "Decade Fighter",
        "a_genre_action": "Fist Action",
        "a_genre_adventure": "Wasteland Trek",
        "a_genre_comedy": "Bat Gang",
        "a_genre_drama": "Kenshiro's Grief",
        "a_genre_fantasy": "Martial Fantasy",
        "a_genre_horror": "You Are Dead",
        "a_genre_romance": "Yuria's Love",
        "a_genre_scifi": "Post-Nuke World",
        "a_genre_supernatural": "Death Touch",
        "a_genre_psychological": "Raoh's Will",
        "a_genre_mecha": "None Survived",
        "a_critic": "Fist Judge",
        "a_perfect_ten": "Perfect Kill",
        "a_harsh_critic": "Merciless Judge",
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Endless Journey",
        "a_year_long": "Year Walking",
        "a_iron_will": "Unbreakable Will",
        "a_hidden_gem": "Hidden Technique",
        "a_cult_classic": "Fist Classic",
        "a_classic_connoisseur": "84 Classic Fan",
        "a_new_years_resolution": "New Year Strike",
        "a_christmas_special": "Holiday Battle",
        "a_meta_tier_max": "Fist of the Stars",
        "a_meta_completionist": "Complete Mastery",
        "a_sequel_chain": "Sequel Strike",
        "a_zero_to_hero": "Survivor to Legend",
        "a_night_owl": "Night Walker",
        "a_early_bird": "Dawn Strike",
        "m_first_chapter": "First Strike",
        "m_first_complete": "Volume Survived",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Battle Marathon",
        "m_completionist": "Wasteland Complete",
        "m_mega_completionist": "Hokuto Expert",
        "m_loyal_reader": "Loyal Reader",
        "m_rereader": "Reread Battle",
        "m_genre_action": "Violent Action",
        "m_genre_adventure": "Desert Walk",
        "m_genre_romance": "Love Pursuit",
        "m_genre_fantasy": "Martial Arts",
        "m_genre_horror": "Graphic Horror",
        "m_genre_drama": "Tragedy Drama",
        "m_genre_scifi": "Post-Nuke",
        "m_genre_supernatural": "Death Touch",
        "m_genre_psychological": "Warrior Mind",
        "m_critic": "Death Critic",
        "m_perfect_ten": "Perfect Issue",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Fist",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Dedication",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Classic Violence",
        "m_mangaka_lover": "Buronson Fan",
        "m_source_material_fan": "Original Reader",
        "m_meta_tier_max": "Complete Mastery",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Hara Art Fan",
        "m_manga_to_anime": "Source Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#080300",
        primary: "#d41208",
        secondary: "#880604",
        accent: "#c88040",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/fist-of-the-north-star.jpg",
    particleColor: "#d41208",
    backgroundDim: 0.4,
    backgroundBlur: 22,
    particleTypes: {
        explosions: { label: "Explosions", maxCount: 8, defaultEnabled: true, defaultIntensity: 60 },
        dust: { label: "Wasteland Dust", maxCount: 20, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
        1: "Wasteland Wanderer",
        5: "Village Defender",
        15: "Hokuto Student",
        30: "Kenshiro",
        50: "Successor of Hokuto",
        75: "Conqueror of Shura",
        100: "Fist of the North Star",
    },
}
