import { AnimeThemeConfig } from "./types"
import {
    GiFactory,
    GiGuitar,
    GiRobotGolem,
    GiBrain,
    GiMeteorImpact,
    GiScooter,
    GiChainedHeart,
    GiElectric,
    GiCrossedSwords,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const flclTheme: AnimeThemeConfig = {
    id: "flcl",
    displayName: "FLCL",
    description: "Nothing amazing happens here. Screaming guitars, head-sprouting robots, Vespa-riding chaos, and the raw energy of The Pillows.",
    fontFamily: "'Bungee', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Bungee&display=swap",
    cssVars: {
        // Brand → hot pink (255 105 180)
        "--color-brand-200": "255 180 220",
        "--color-brand-300": "255 150 200",
        "--color-brand-400": "255 120 190",
        "--color-brand-500": "255 105 180",
        "--color-brand-600": "210 80 150",
        "--color-brand-700": "170 60 120",
        "--color-brand-800": "130 40 90",
        "--color-brand-900": "90 25 65",
        "--color-brand-950": "55 12 38",
        "--brand": "255 105 180",
        // Dark background with warm pink undertone
        "--background": "#0a0408",
        "--paper": "#140810",
        "--color-gray-950": "10 4 8",
        "--color-gray-900": "20 8 16",
        "--color-gray-800": "35 18 28",
        "--color-gray-700": "55 32 44",
        "--color-gray-600": "78 50 64",
        "--color-gray-500": "108 78 92",
        "--color-gray-400": "148 115 132",
        "--color-gray-300": "182 155 170",
        "--color-gray-200": "212 195 204",
        "--color-gray-100": "235 225 230",
        "--color-gray-50": "248 242 245",
    },
    sidebarOverrides: {
        "home": { icon: GiFactory, label: "Mabase" },
        "schedule": { icon: GiAlarmClock, label: "Episode Tempo" },
        "manga": { icon: LuBookOpen, label: "Manga Volumes" },
        "lists": { icon: GiGuitar, label: "Track List" },
        "discover": { icon: GiBrain, label: "N.O. Channel" },
        "torrent-list": { icon: GiAnvilImpact, label: "Head Overflow" },
        "debrid": { icon: GiScooter, label: "Vespa Drops" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Signals" },
        "enmasse": { icon: GiResize, label: "Mass Override" },
        "scan-summaries": { icon: TbReportSearch, label: "Scan Frequency" },
        "auto-downloader": { icon: LuRss, label: "Guitar Feed" },
        "community": { icon: GiElectric, label: "Pillows Club" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Brain Alerts" },
        "achievements": { icon: GiTrophy, label: "Swing Count" },
        "theme-manager": { icon: GiPalette, label: "Amp Settings" },
        "extensions": { icon: BiExtension, label: "Mech Parts" },
        "sync": { icon: IoCloudOfflineOutline, label: "N.O. Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Tuning Pegs" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Swing",
        "a_episode_counter": "Riff Counter",
        "a_episode_titan": "Cranial Burst",
        "a_hours_invested": "Hours Jammed",
        "a_time_lord": "Time Overflow",
        "a_anime_collector": "Guitar Rack",
        "a_library_legend": "Amp Legend",
        "a_first_complete": "Song Finished",
        "a_hundred_club": "Century Riff",
        "a_first_day": "Mabase Arrival",
        "a_first_rating": "First Tuning",
        "a_ten_thousand_min": "Ten Thousand Beats",
        "a_season_veteran": "Vespa Veteran",
        "a_year_explorer": "Year Drifting",
        "a_century_watcher": "Hundred Episodes",
        "a_five_hundred_eps": "Five Hundred Riffs",
        "a_thousand_eps": "Thousand Strings",
        "a_watching_ten": "Ten Channels",
        "a_ptw_hoarder": "Signal Hoarder",
        "a_dropped_honesty": "Honest Static",
        "a_five_thousand_eps": "Five Thousand Watts",
        "a_ten_completed": "Ten Encores",
        "a_fifty_completed": "Fifty Solos",
        "a_five_hundred_completed": "Five Hundred Jams",
        "a_mean_score_tracker": "Average Frequency",
        "a_unique_studios": "Studio Hotwire",
        "a_days_spent_watching": "Days Overflowing",
        "a_all_status": "All Frequencies",
        "a_first_favorite": "First Crush",
        "a_favorites_collector": "Heart Collector",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Nonstop Shred",
        "a_marathon_runner": "Marathon Jam",
        "a_weekend_warrior": "Weekend Riot",
        "a_non_stop": "Relentless Noise",
        "a_one_more_episode": "One More Riff",
        "a_speed_run": "Vespa Blitz",
        "a_double_feature": "Double Bass",
        "a_triple_threat": "Triple Fret",
        "a_five_a_day": "Five Swings",
        "a_back_to_back": "Back-to-Back Chords",
        "a_seasonal_binge": "Full Album",
        "a_cour_crusher": "Cour Crusher",
        "a_half_day_watch": "Half-Day Jam",
        "a_full_day_watch": "Full-Day Noise",
        "a_power_weekend": "Power Chord Weekend",
        "a_binge_king": "Binge Overlord",
        "a_no_sleep": "Sleepless Frenzy",
        "a_entire_season": "Rapid Setlist",
        "a_seven_day_challenge": "Seven-Day Surge",
        "a_hundred_day_binge": "Hundred-Day Chaos",
        "a_genre_binge": "Genre Mash",
        "a_studio_binge": "Studio Overdrive",
        "a_season_sweep": "Season Sweep",
        "a_forty_eight_hour": "Forty-Eight Hour Jam",
        "a_ep_counter_day": "Daily Riff Count",
        "a_multi_series_binge": "Multi-Band Fest",
        "a_midnight_binge": "Midnight Shred",
        "a_new_year_binge": "New Year Noise",

        // ── ANIME GENRES ──
        "a_genre_action": "Combat Riff",
        "a_genre_adventure": "Road Trip",
        "a_genre_comedy": "Gag Reflex",
        "a_genre_drama": "Emotional Amp",
        "a_genre_fantasy": "Fantasy Fret",
        "a_genre_horror": "Horror Feedback",
        "a_genre_mystery": "Brain Mystery",
        "a_genre_romance": "Love Frequency",
        "a_genre_scifi": "Robot Science",
        "a_genre_sol": "Mabase Life",
        "a_genre_sports": "Bat Swing",
        "a_genre_supernatural": "N.O. Power",
        "a_genre_thriller": "Thriller Chord",
        "a_genre_mecha": "Canti Core",
        "a_genre_music": "Pillows Track",
        "a_genre_psychological": "Neural Static",
        "a_genre_ecchi": "Hot Frequency",
        "a_genre_mahou_shoujo": "Magic Guitar",
        "a_tag_isekai": "Other World",
        "a_tag_harem": "Signal Tangle",
        "a_tag_bl": "Harmonic Bond",
        "a_tag_gl": "Resonant Pair",
        "a_tag_historical": "Retro Vinyl",
        "a_tag_military": "Mech Battalion",
        "a_tag_school": "School Chaos",
        "a_tag_martial_arts": "Swing Batter",
        "a_tag_vampire": "Midnight Bite",
        "a_tag_samurai": "Blade Riff",
        "a_tag_space": "Cosmic Noise",
        "a_tag_parody": "Fooly Parody",
        "a_tag_idol": "Stage Dive",
        "a_tag_post_apocalyptic": "After Overflow",
        "a_tag_cyberpunk": "Circuit Punk",
        "a_tag_shounen": "Raw Energy",
        "a_tag_seinen": "Grown Static",
        "a_tag_shoujo": "Heart String",
        "a_tag_josei": "Mature Chord",
        "a_tag_survival": "Survive Mabase",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Track",
        "a_mega_completionist": "Mega Encore",
        "a_completion_rate_50": "Halfway Tuned",
        "a_completion_rate_75": "Almost Overflow",
        "a_completion_rate_90": "Near Peak",
        "a_no_drop": "No Dead Air",
        "a_long_runner_complete": "Long Solo Done",
        "a_sequel_chain": "Chain Reaction",
        "a_clean_list": "Clean Signal",
        "a_from_ptw": "Queue Cleared",
        "a_rewatch_master": "Replay Master",
        "a_short_complete": "Quick Riff",
        "a_same_day_start_finish": "Same-Day Burst",
        "a_revival": "Revived Signal",
        "a_zero_to_hero": "Zero to Hero",
        "a_five_genre_complete": "Five Genres",
        "a_full_franchise": "Full Discography",
        "a_batch_complete": "Batch Override",
        "a_paused_to_done": "Unpaused",
        "a_completion_spree": "Spree Mode",
        "a_multi_rewatch": "Multi-Replay",
        "a_dropped_recovery": "Recovered Tune",
        "a_ten_perfect_scores": "Ten Perfects",
        "a_seasonal_clear": "Season Cleared",
        "a_complete_genre_span": "Genre Span",
        "a_monthly_completions": "Monthly Clears",
        "a_yearly_completions": "Yearly Clears",
        "a_rapid_complete": "Speed Clear",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Listener",
        "a_studio_devotee": "Studio Devotee",
        "a_rewatcher": "Rewind Play",
        "a_triple_rewatch": "Triple Replay",
        "a_annual_tradition": "Annual Jam",
        "a_director_fan": "Tsurumaki Fan",
        "a_voice_actor_fan": "Voice Amp",
        "a_ost_lover": "Ride on Shooting Star",
        "a_source_reader": "Source Reader",
        "a_waiting_weekly": "Weekly Wait",
        "a_childhood_revisit": "Mabase Revisit",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Genre Loyalty",
        "a_decade_watcher": "Decade Listener",
        "a_adaptation_hunter": "Adaptation Hunt",
        "a_original_anime_fan": "Original Broadcast",
        "a_long_commitment": "Long Commitment",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Studios",
        "a_complete_catalog": "Full Catalog",
        "a_franchise_collector": "Franchise Haul",
        "a_airing_follower": "Airing Follower",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Staff Tracker",
        "a_multi_season_fan": "Multi-Season Fan",
        "a_format_diversity": "Format Diversity",
        "a_year_dedication": "Year Dedicated",
        "a_season_dedication": "Season Dedicated",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Frequency Scout",
        "a_studio_hopper": "Studio Hopper",
        "a_tag_explorer": "Tag Explorer",
        "a_decade_hopper": "Decade Surfer",
        "a_hidden_gem": "Hidden Frequency",
        "a_popular_taste": "Popular Signal",
        "a_retro_appreciator": "Retro Vinyl Fan",
        "a_modern_viewer": "Modern Listener",
        "a_cross_demographic": "Cross Signal",
        "a_underdog_fan": "Underdog Beat",
        "a_variety_week": "Variety Week",
        "a_foreign_cinema": "Foreign Riff",
        "a_classic_connoisseur": "Classic Amp",
        "a_every_season": "Every Season",
        "a_award_winner": "Award Shred",
        "a_niche_explorer": "Niche Noise",
        "a_global_anime": "Global Broadcast",
        "a_cult_classic": "Cult Classic",
        "a_random_pick": "Random Tune",
        "a_new_genre_month": "New Genre Month",
        "a_seasonal_completionist": "Seasonal Clear",
        "a_unpopular_opinion": "Unpopular Chord",
        "a_top_rated_viewer": "Top Rated",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Noise",
        "a_upcoming_watcher": "Upcoming Signal",
        "a_short_series_explorer": "Short Burst",
        "a_long_series_explorer": "Long Wave",

        // ── ANIME TIME ──
        "a_night_owl": "Night Owl",
        "a_early_bird": "Dawn Riff",
        "a_lunch_break": "Lunch Jam",
        "a_golden_hour": "Golden Hour",
        "a_four_am_club": "4 AM Static",
        "a_witching_hour": "Witching Noise",
        "a_new_year_watch": "New Year Tune",
        "a_midnight_premiere": "Midnight Drop",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Buzz",
        "a_prime_time": "Prime Time",
        "a_workday_watcher": "Workday Beats",
        "a_sunday_marathon": "Sunday Session",
        "a_rainy_day": "Rainy Day Riff",
        "a_morning_routine": "Morning Routine",
        "a_night_shift": "Night Shift",
        "a_twilight_zone": "Twilight Hum",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge",
        "a_late_night_regular": "Late Night Jam",
        "a_sunrise_watcher": "Sunrise Watcher",
        "a_holiday_watcher": "Holiday Watcher",
        "a_every_day_of_week": "Every Day",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Gig",
        "a_party_host": "Band Leader",
        "a_social_butterfly": "Social Buzz",
        "a_group_binge": "Group Jam",
        "a_party_regular": "Regular Gig",
        "a_sync_viewer": "Synced Playback",
        "a_commentator": "Hype Commentator",
        "a_party_marathon": "Marathon Gig",
        "a_full_house": "Full House",
        "a_community_pillar": "Pillar",
        "a_watch_party_streak": "Gig Streak",
        "a_diverse_party": "Diverse Gig",
        "a_late_night_party": "Late Gig",
        "a_party_veteran": "Veteran Gigoer",
        "a_genre_party": "Genre Gig",
        "a_weekly_party": "Weekly Gig",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Recommend Track",
        "a_party_completionist": "Gig Completionist",
        "a_social_scorer": "Social Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Fibonacci Beat",
        "a_palindrome_day": "Palindrome Day",
        "a_binary_day": "Binary Noise",
        "a_full_moon": "Full Moon Howl",
        "a_leap_year": "Leap Year",
        "a_time_traveler": "Time Warp",
        "a_genre_clash": "Genre Clash",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Clears",
        "a_pi_episodes": "Pi Episodes",
        "a_synchronicity": "Synchronicity",
        "a_world_record": "World Record",
        "a_nice": "Nice",
        "a_power_level": "Power Level",
        "a_answer_42": "Answer Forty-Two",
        "a_square_number": "Perfect Square",
        "a_prime_count": "Prime Count",
        "a_matching_date": "Date Match",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast",
        "a_movie_buff": "Movie Buff",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Episode",
        "a_short_king": "Short King",
        "a_variety_pack": "Variety Pack",
        "a_film_festival": "Film Festival",
        "a_music_video": "Music Video",
        "a_tv_short": "Quick Clip",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Anthology",
        "a_mini_series": "Mini Series",
        "a_theatrical": "Theatrical Cut",
        "a_format_master": "Format Master",
        "a_long_movie": "Feature Film",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "Commercial Break",
        "a_pv_collector": "Preview Reel",
        "a_format_balance": "Format Balance",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Film",
        "a_recap_watcher": "Recap Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Streak",
        "a_mega_streak": "Mega Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Watch",
        "a_comeback": "Comeback Riff",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Steady Tempo",
        "a_year_long": "Year-Long Streak",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Clear Streak",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Ep Streak",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Harsh Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Brutal Judge",
        "a_fair_judge": "Fair Judge",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Score All",
        "a_wide_range": "Wide Range",
        "a_controversial": "Controversial",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Score Sniper",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Picky Watcher",
        "a_100_rated": "Hundred Rated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Hunt",
        "a_contrarian": "Contrarian",
        "a_optimist": "Optimist",
        "a_score_distributor": "Score Spread",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Vow",
        "a_valentines_weeb": "Valentine Riff",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Chaos",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "May Fourth",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday Thirteen",
        "a_halloween_spirit": "Halloween Noise",
        "a_thanksgiving_binge": "Thanksgiving Jam",
        "a_christmas_special": "Holiday Special",
        "a_new_years_eve": "New Year Finale",
        "a_birthday_watch": "Birthday Watch",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Independence Day",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Equinox",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Day",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anime Birthday",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Consecutive Holidays",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Unlock",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Start",
        "a_meta_tier_climber": "Tier Climber",
        "a_meta_tier_max": "Max Tier",
        "a_meta_xp_earner": "XP Earned",
        "a_meta_difficulty_easy": "Easy Mode",
        "a_meta_difficulty_hard": "Hard Mode",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Complete",
        "a_meta_diverse": "Meta Diverse",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page",
        "m_chapter_counter": "Chapter Count",
        "m_chapter_titan": "Chapter Giant",
        "m_reading_hours": "Reading Hours",
        "m_reading_time_lord": "Time Lord Read",
        "m_manga_collector": "Manga Rack",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "First Read Day",
        "m_first_rating": "First Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Haul",
        "m_year_explorer": "Year Reading",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Read",
        "m_thousand_ch": "Thousand Chapters",
        "m_reading_ten": "Ten Ongoing",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Drop",
        "m_season_reader": "Seasonal Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Complete",
        "m_fifty_completed": "Fifty Complete",
        "m_five_hundred_completed": "Five Hundred Done",
        "m_mean_score_tracker": "Mean Score",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Favorites Haul",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Read",
        "m_marathon_reader": "Marathon Read",
        "m_weekend_reader": "Weekend Read",
        "m_non_stop_reading": "Nonstop Pages",
        "m_one_more_chapter": "One More Page",
        "m_speed_read": "Speed Read",
        "m_double_story": "Double Story",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five Daily",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Read",
        "m_full_day_read": "Full-Day Read",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge Royalty",
        "m_no_sleep_read": "Sleepless Read",
        "m_full_series_rush": "Series Rush",
        "m_seven_day_challenge": "Seven-Day Read",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Binge",
        "m_author_binge": "Author Binge",
        "m_chapter_counter_day": "Daily Chapters",
        "m_multi_series_binge": "Multi-Series Read",
        "m_midnight_binge": "Midnight Read",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "Forty-Eight Hours",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Pages",
        "m_genre_adventure": "Adventure Pages",
        "m_genre_comedy": "Comedy Pages",
        "m_genre_drama": "Drama Pages",
        "m_genre_fantasy": "Fantasy Pages",
        "m_genre_horror": "Horror Pages",
        "m_genre_mystery": "Mystery Pages",
        "m_genre_romance": "Romance Pages",
        "m_genre_scifi": "Sci-Fi Pages",
        "m_genre_sol": "Slice of Life",
        "m_genre_sports": "Sports Pages",
        "m_genre_supernatural": "Supernatural Read",
        "m_genre_thriller": "Thriller Pages",
        "m_genre_psychological": "Psych Pages",
        "m_genre_isekai": "Isekai Pages",
        "m_genre_shounen": "Shounen Pages",
        "m_genre_ecchi": "Ecchi Pages",
        "m_genre_mahou_shoujo": "Mahou Pages",
        "m_genre_mecha": "Mecha Pages",
        "m_genre_music": "Music Pages",
        "m_tag_isekai_new": "New World Read",
        "m_tag_harem": "Harem Read",
        "m_tag_bl": "BL Read",
        "m_tag_gl": "GL Read",
        "m_tag_historical": "Historical Read",
        "m_tag_military": "Military Read",
        "m_tag_school": "School Read",
        "m_tag_martial_arts": "Martial Arts Read",
        "m_tag_vampire": "Vampire Read",
        "m_tag_samurai": "Samurai Read",
        "m_tag_space": "Space Read",
        "m_tag_parody": "Parody Read",
        "m_tag_idol": "Idol Read",
        "m_tag_post_apocalyptic": "Post-Apocalyptic",
        "m_tag_cyberpunk": "Cyberpunk Read",
        "m_tag_shoujo": "Shoujo Read",
        "m_tag_survival": "Survival Read",
        "m_tag_cooking": "Cooking Read",
        "m_tag_medical": "Medical Read",
        "m_tag_villainess": "Villainess Read",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Read",
        "m_mega_completionist": "Mega Reader",
        "m_completion_rate_50": "Halfway Read",
        "m_completion_rate_75": "Almost Done",
        "m_completion_rate_90": "Near Complete",
        "m_no_drop": "No Drops",
        "m_long_runner_complete": "Long Run Done",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean List",
        "m_from_ptr": "Queue Read",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Read",
        "m_revival": "Revival Read",
        "m_zero_to_hundred": "Zero to Hundred",
        "m_five_genre_complete": "Five Genres Read",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Complete",
        "m_paused_to_done": "Resumed Done",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi-Reread",
        "m_dropped_recovery": "Drop Recovery",
        "m_ten_perfect_scores": "Ten Perfects",
        "m_complete_genre_span": "Genre Span Read",
        "m_monthly_completions": "Monthly Reads",
        "m_yearly_completions": "Yearly Reads",
        "m_rapid_complete": "Rapid Clear",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Fan",
        "m_rereader": "Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Fan",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Fan",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyal",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Fave Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Franchise Haul",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Master",
        "m_multi_series_author": "Multi-Series Fan",
        "m_format_diversity": "Format Diverse",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Scout",
        "m_publisher_hopper": "Publisher Hop",
        "m_tag_explorer": "Tag Scout",
        "m_decade_hopper": "Decade Hop",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Pick",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross Demo",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Variety Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Taste",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Niche Explorer",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre Month",
        "m_year_completionist": "Year Complete",
        "m_unpopular_opinion": "Unpopular Take",
        "m_top_rated_reader": "Top Rated Read",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Manga",
        "m_long_manga_explorer": "Long Manga",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Lunch Reader",
        "m_commute_reader": "Commute Reader",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All Hours Read",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "Workday Reader",
        "m_sunday_read": "Sunday Reader",
        "m_morning_routine": "Morning Reader",
        "m_night_shift_reader": "Night Shift Read",
        "m_seasonal_premier_read": "New Release Read",
        "m_clock_collector": "Clock Collector",
        "m_late_night_horror": "Midnight Horror",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Read",
        "m_twilight_reader": "Twilight Read",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Binge",
        "m_late_night_regular": "Late Night Read",
        "m_sunrise_reader": "Sunrise Read",
        "m_every_day_of_week": "Every Day Read",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Read",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Read",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Narrator",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross Media",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collab Reader",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read Streak",
        "m_mega_streak": "Mega Read Streak",
        "m_weekly_warrior": "Weekly Reader",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader Comeback",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Reader",
        "m_habit_formed": "Habit Formed",
        "m_consistent_pace": "Steady Pace",
        "m_year_long": "Year-Long Read",
        "m_double_streak": "Double Streak",
        "m_streak_recovery": "Streak Saved",
        "m_daily_minimum": "Daily Pages",
        "m_winter_streak": "Winter Streak",
        "m_summer_streak": "Summer Streak",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Streak",
        "m_unbreakable": "Unbreakable Read",
        "m_eternal_flame": "Eternal Reader",
        "m_chapter_a_day": "Chapter Daily",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Clear Streak",
        "m_rating_streak": "Rating Streak",
        "m_multi_ch_streak": "Multi-Chapter",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manga Critic",
        "m_perfect_ten": "Perfect Ten",
        "m_harsh_critic": "Harsh Reader",
        "m_fair_judge": "Fair Reader",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Score All Read",
        "m_wide_range": "Wide Range",
        "m_controversial": "Controversial",
        "m_consistent_scorer": "Consistent Score",
        "m_score_sniper": "Score Sniper",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Picky Reader",
        "m_100_rated": "Hundred Rated",
        "m_500_rated": "Five Hundred Rated",
        "m_mediocre_majority": "Middle Ground",
        "m_rating_spree": "Rating Spree",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Hunt",
        "m_contrarian": "Contrarian Read",
        "m_optimist": "Optimistic Reader",
        "m_score_distributor": "Score Spread",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Vow",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Chaos Read",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Solstice Read",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Friday Thirteen",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thanksgiving Read",
        "m_christmas_read": "Holiday Read",
        "m_new_years_eve": "New Year Finale",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Marathon",
        "m_independence_day": "Independence Read",
        "m_culture_day": "Culture Read",
        "m_spring_equinox": "Equinox Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Solstice Read",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "Every Holiday",
        "m_consecutive_holidays": "Consecutive Days",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number",
        "m_fibonacci": "Fibonacci Read",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven",
        "m_thousand_complete": "Thousand Done",
        "m_nice": "Nice Count",
        "m_power_level_chapters": "Power Level",
        "m_answer_42": "Answer Forty-Two",
        "m_square_number": "Square Number",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Date Match",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Synchronicity",
        "m_world_record": "World Record",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time Traveler",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Match",
        "m_chapter_match_date": "Chapter Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Unlock",
        "m_meta_collector": "Badge Collector",
        "m_meta_category_starter": "Category Start",
        "m_meta_tier_climber": "Tier Climber",
        "m_meta_tier_max": "Max Tier",
        "m_meta_xp_earner": "XP Earned",
        "m_meta_difficulty_easy": "Easy Mode",
        "m_meta_difficulty_hard": "Hard Mode",
        "m_meta_unlock_spree": "Unlock Spree",
        "m_meta_completionist": "Meta Complete",
        "m_meta_diverse": "Meta Diverse",
        "m_meta_dominator": "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#0a0408",
        primary: "#ff69b4",
        secondary: "#d25096",
        accent: "#aa3c78",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.3,
    backgroundBlur: 20,
    particleTypes: {
        guitar_picks: { label: "Guitar Picks", maxCount: 12, defaultEnabled: true, defaultIntensity: 60 },
        vespa_exhaust: { label: "Vespa Exhaust", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        robot_sparks: { label: "Robot Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 55 },
        brain_waves: { label: "Brain Waves", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Ordinary Kid",
        5:   "Struck",
        15:  "N.O. Channel",
        30:  "Canti Ally",
        45:  "Swing Batter",
        60:  "Atomsk Seeker",
        80:  "Fooly Cooly",
        100: "Nothing Amazing",
    },
}
