import { AnimeThemeConfig } from "./types"
import { fullmetalAlchemistPlayerIcons } from "./player-icons"
import {
    GiCastle,
    GiShield,
    GiFist,
    GiMuscleUp,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiLightningBranches,
    GiResize,
    GiSettingsKnobs,
    GiSwordWound,
    GiEagleEmblem,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const fullmetalAlchemistTheme: AnimeThemeConfig = {
    id: "fullmetal-alchemist",
    displayName: "Fullmetal Alchemist",
    description: "Equivalent Exchange — transmutation circles, gold alchemy, and the philosopher's stone in a dark steel world.",
    fontFamily: "'Cinzel Decorative', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700&display=swap",
    cssVars: {
        // Brand → gold/amber alchemy palette
        "--color-brand-200": "240 215 130",
        "--color-brand-300": "225 195 90",
        "--color-brand-400": "210 175 60",
        "--color-brand-500": "200 160 40",
        "--color-brand-600": "175 138 30",
        "--color-brand-700": "145 112 22",
        "--color-brand-800": "110 85 16",
        "--color-brand-900": "75 58 10",
        "--color-brand-950": "45 35 6",
        "--brand": "200 160 40",
        // Dark steel backgrounds
        "--background": "#08060a",
        "--paper": "#100e14",
        // Warm steel-tinted grays
        "--color-gray-950": "8 6 10",
        "--color-gray-900": "16 14 20",
        "--color-gray-800": "30 27 36",
        "--color-gray-700": "48 44 56",
        "--color-gray-600": "72 66 82",
        "--color-gray-500": "100 94 112",
        "--color-gray-400": "140 134 152",
        "--color-gray-300": "178 174 188",
        "--color-gray-200": "210 207 218",
        "--color-gray-100": "232 230 236",
        "--color-gray-50": "246 245 248",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Central Command" },
        "schedule": { icon: GiAlarmClock, label: "Mission Briefing" },
        "manga": { icon: LuBookOpen, label: "Alchemic Texts" },
        "lists": { icon: GiShield, label: "State Registry" },
        "discover": { icon: GiBullseye, label: "Philosopher's Search" },
        "torrent-list": { icon: GiLightningBranches, label: "Equivalent Exchange" },
        "debrid": { icon: GiSwordWound, label: "Homunculus Bounties" },
        "unmatched": { icon: GiFist, label: "Unclassified Chimeras" },
        "enmasse": { icon: GiResize, label: "Amestris Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Military Reports" },
        "auto-downloader": { icon: LuRss, label: "Automail Dispatch" },
        "community": { icon: GiEagleEmblem, label: "State Alchemists" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Central Alerts" },
        "achievements": { icon: GiTrophy, label: "Alchemic Honors" },
        "theme-manager": { icon: GiPalette, label: "Transmutation Design" },
        "extensions": { icon: BiExtension, label: "Automail Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "Gate Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Führer's Orders" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Transmutation Attempt",
        "a_episode_counter": "Alchemic Reaction Counter",
        "a_episode_titan": "Philosopher's Stone-Class Feat",
        "a_hours_invested": "Hours in the Laboratory",
        "a_time_lord": "Master of Equivalent Exchange",
        "a_anime_collector": "Alchemic Tome Collector",
        "a_library_legend": "Central Library Legend",
        "a_first_complete": "First Transmutation Complete",
        "a_hundred_club": "Century of Transmutations",
        "a_first_day": "Day of the State Alchemy Exam",
        "a_first_rating": "First State Ranking",
        "a_ten_thousand_min": "Ten Thousand Minutes of Research",
        "a_season_veteran": "Veteran State Alchemist",
        "a_year_explorer": "Year in the Amestris Military",
        "a_century_watcher": "Hundred-Episode Alchemic Journey",
        "a_five_hundred_eps": "Five Hundred Alchemic Formulas",
        "a_thousand_eps": "Thousand Transmutation Circles",
        "a_watching_ten": "Ten Research Projects Active",
        "a_ptw_hoarder": "Mission Dossier Hoarder",
        "a_dropped_honesty": "Tactical Retreat from Ishval",
        "a_five_thousand_eps": "Five Thousand Alchemic Reactions",
        "a_ten_completed": "Ten Missions Accomplished",
        "a_fifty_completed": "Fifty Homunculi Defeated",
        "a_five_hundred_completed": "Five Hundred State Commissions",
        "a_mean_score_tracker": "Average State Evaluation",
        "a_unique_studios": "Allied Research Laboratories",
        "a_days_spent_watching": "Days Studying in the Library",
        "a_all_status": "All Mission Statuses Filed",
        "a_first_favorite": "First Bond with a Comrade",
        "a_favorites_collector": "Elric Brothers' Bonds",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Alchemic Research",
        "a_marathon_runner": "Promised Day Marathon",
        "a_weekend_warrior": "Weekend at Central",
        "a_non_stop": "Relentless Equivalent Exchange",
        "a_one_more_episode": "One More Transmutation Circle",
        "a_speed_run": "Automail Rush Job",
        "a_double_feature": "Twin Elric Transmutation",
        "a_triple_threat": "Triple Alchemic Reaction",
        "a_five_a_day": "Five Lab Reports a Day",
        "a_back_to_back": "Back-to-Back State Missions",
        "a_seasonal_binge": "Full Arc Alchemic Deep Dive",
        "a_cour_crusher": "State Alchemy Exam Crusher",
        "a_half_day_watch": "Half-Day at the Library",
        "a_full_day_watch": "Full Day Alchemic Training",
        "a_power_weekend": "Power Weekend at Central HQ",
        "a_binge_king": "King of the Alchemists",
        "a_no_sleep": "All-Night Laboratory Session",
        "a_entire_season": "Rapid Arc Transmutation",
        "a_seven_day_challenge": "Seven-Day Philosopher's Quest",
        "a_hundred_day_binge": "Hundred-Day Alchemic Grind",
        "a_genre_binge": "Cross-Discipline Alchemy Study",
        "a_studio_binge": "Bones Studio Marathon",
        "a_season_sweep": "Season Sweep Operation",
        "a_forty_eight_hour": "Forty-Eight Hours in the Fifth Lab",
        "a_ep_counter_day": "Daily Research Log Count",
        "a_multi_series_binge": "Multi-Division Task Force",
        "a_midnight_binge": "Midnight Laboratory Experiment",
        "a_new_year_binge": "New Year's Transmutation Oath",

        // ── ANIME GENRES ──
        "a_genre_action": "Combat Alchemy Specialist",
        "a_genre_adventure": "Journey for the Philosopher's Stone",
        "a_genre_comedy": "Hughes Family Comedy Hour",
        "a_genre_drama": "Trisha Elric's Farewell",
        "a_genre_fantasy": "Alchemic Fantasy Realm",
        "a_genre_horror": "Chimera Laboratory Horror",
        "a_genre_mystery": "Conspiracy of the Homunculi",
        "a_genre_romance": "Equivalent Hearts Exchange",
        "a_genre_scifi": "Alchemic Science Breakthrough",
        "a_genre_sol": "Life in Resembool",
        "a_genre_sports": "Automail Combat Training",
        "a_genre_supernatural": "Truth Beyond the Gate",
        "a_genre_thriller": "Homunculus Pursuit Thriller",
        "a_genre_mecha": "Alphonse Armor Construct",
        "a_genre_music": "Amestris Military March",
        "a_genre_psychological": "Father's Grand Design",
        "a_genre_ecchi": "Resembool Hot Springs",
        "a_genre_mahou_shoujo": "Alchemic Artistry",
        "a_tag_isekai": "Beyond the Gate of Truth",
        "a_tag_harem": "Elric Squad Assembled",
        "a_tag_bl": "Brothers in Alchemy",
        "a_tag_gl": "Hawkeye & Elric Duo",
        "a_tag_historical": "Amestris Historical Chronicles",
        "a_tag_military": "State Military Operations",
        "a_tag_school": "Izumi Curtis's Training",
        "a_tag_martial_arts": "Alphonse's Combat Style",
        "a_tag_vampire": "Homunculus Blood Regeneration",
        "a_tag_samurai": "Samurai of Xing",
        "a_tag_space": "Dimensional Gate Space",
        "a_tag_parody": "Chibi Elric Brothers",
        "a_tag_idol": "Armstrong's Artistic Flex",
        "a_tag_post_apocalyptic": "Post-Promised Day Era",
        "a_tag_cyberpunk": "Automail Engineering Tech",
        "a_tag_shounen": "Burning Resolve of Youth",
        "a_tag_seinen": "Ishval War Reality",
        "a_tag_shoujo": "Winry's Heart",
        "a_tag_josei": "Hawkeye's Perspective",
        "a_tag_survival": "Survival in the Northern Wall",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full State Alchemist License",
        "a_mega_completionist": "Fullmetal Completionist",
        "a_completion_rate_50": "Halfway to the Philosopher's Stone",
        "a_completion_rate_75": "Approaching the Gate",
        "a_completion_rate_90": "Truth Nearly Understood",
        "a_no_drop": "No Comrade Left Behind",
        "a_long_runner_complete": "Long Alchemic Campaign Endured",
        "a_sequel_chain": "Brotherhood Sequel Chain",
        "a_clean_list": "Clean Military Record",
        "a_from_ptw": "Mission Dossier Activated",
        "a_rewatch_master": "Transmutation Memory Replay",
        "a_short_complete": "Quick Field Operation",
        "a_same_day_start_finish": "Same-Day State Mission",
        "a_revival": "Alphonse's Body Restored",
        "a_zero_to_hero": "Youngest State Alchemist",
        "a_five_genre_complete": "Five Disciplines of Alchemy",
        "a_full_franchise": "Full Amestris Dossier",
        "a_batch_complete": "Batch Mission Cleared",
        "a_paused_to_done": "Returned from Absence",
        "a_completion_spree": "Transmutation Spree",
        "a_multi_rewatch": "Multi-Timeline Alchemic Review",
        "a_dropped_recovery": "Recovered from Failed Transmutation",
        "a_ten_perfect_scores": "Ten Perfect Evaluations",
        "a_seasonal_clear": "Seasonal State Exam Cleared",
        "a_complete_genre_span": "All-Around State Alchemist",
        "a_monthly_completions": "Monthly Military Reports",
        "a_yearly_completions": "Annual State Review",
        "a_rapid_complete": "Rapid Transmutation Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal State Alchemist",
        "a_studio_devotee": "Studio Bones Devotee",
        "a_rewatcher": "Alchemic Rewatch Patrol",
        "a_triple_rewatch": "Triple Transmutation Rewatch",
        "a_annual_tradition": "Annual Resembool Festival",
        "a_director_fan": "Director's Alchemic Vision",
        "a_voice_actor_fan": "Voice of the Alchemists",
        "a_ost_lover": "Again & Rewrite Lover",
        "a_source_reader": "Arakawa's Original Manga",
        "a_waiting_weekly": "Weekly State Broadcast Wait",
        "a_childhood_revisit": "Return to Resembool",
        "a_saga_tracker": "Fullmetal Saga Tracker",
        "a_genre_loyalty": "Alchemic Genre Loyalty",
        "a_decade_watcher": "Decade-Long FMA Fan",
        "a_adaptation_hunter": "Alchemic Adaptation Hunter",
        "a_original_anime_fan": "Original 2003 Alchemist",
        "a_long_commitment": "Long-Term Amestris Commitment",
        "a_perfect_attendance": "Perfect Attendance at HQ",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Alchemic Catalog",
        "a_franchise_collector": "FMA Universe Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Alchemy Mastery",
        "a_staff_follower": "Military Staff Dossier",
        "a_multi_season_fan": "Multi-Season Amestris Veteran",
        "a_format_diversity": "Diverse Alchemic Formats",
        "a_year_dedication": "Year of Unwavering Resolve",
        "a_season_dedication": "Season of Burning Determination",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Alchemic Discipline Explorer",
        "a_studio_hopper": "Laboratory Transfer Student",
        "a_tag_explorer": "Tag Reconnaissance Alchemist",
        "a_decade_hopper": "Amestris Era to Modern Day",
        "a_hidden_gem": "Hidden Alchemic Formula",
        "a_popular_taste": "Popular Among State Alchemists",
        "a_retro_appreciator": "Golden Age Alchemist Appreciator",
        "a_modern_viewer": "Modern Era Viewer",
        "a_cross_demographic": "Cross-Division Scout",
        "a_underdog_fan": "Underdog Elric Spirit",
        "a_variety_week": "Week of Varied Transmutations",
        "a_foreign_cinema": "Xingese Foreign Film",
        "a_classic_connoisseur": "Classic Alchemy Connoisseur",
        "a_every_season": "Every Season Enlisted",
        "a_award_winner": "State Award Recipient",
        "a_niche_explorer": "Underground Lab Explorer",
        "a_global_anime": "Global Alchemic Network",
        "a_cult_classic": "Cult Classic Transmutation",
        "a_random_pick": "Random Mission Assignment",
        "a_new_genre_month": "New Discipline Monthly Discovery",
        "a_seasonal_completionist": "Seasonal Mission Complete",
        "a_unpopular_opinion": "Unpopular Alchemic Opinion",
        "a_top_rated_viewer": "Top-Ranked State Intel",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into the Unknown",
        "a_upcoming_watcher": "Upcoming Alchemic Debut",
        "a_short_series_explorer": "Short Mission Explorer",
        "a_long_series_explorer": "Long Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Owl Alchemist",
        "a_early_bird": "Dawn Patrol Alchemist",
        "a_lunch_break": "Lunch at Central Mess Hall",
        "a_golden_hour": "Golden Hour Transmutation",
        "a_four_am_club": "4 AM Laboratory Session",
        "a_witching_hour": "Homunculus Witching Hour",
        "a_new_year_watch": "New Year's Alchemic Oath",
        "a_midnight_premiere": "Midnight State Premiere",
        "a_all_hours": "All-Hours Alchemist on Duty",
        "a_dawn_warrior": "Dawn Warrior Alchemist",
        "a_afternoon_delight": "Afternoon Research Session",
        "a_prime_time": "Prime Time Showdown at Central",
        "a_workday_watcher": "On-Duty State Watcher",
        "a_sunday_marathon": "Sunday Training Marathon",
        "a_rainy_day": "Rainy Day in East City",
        "a_morning_routine": "Morning Transmutation Routine",
        "a_night_shift": "Nighttime Military Shift",
        "a_twilight_zone": "Twilight Gate Zone",
        "a_seasonal_premier": "Season Premiere Alchemic Debut",
        "a_clock_collector": "Clock Tower Collector",
        "a_weekend_binge_hours": "Weekend Alchemic Binge Hours",
        "a_late_night_regular": "Late Night Regular Patrol",
        "a_sunrise_watcher": "Sunrise Over Resembool",
        "a_holiday_watcher": "Holiday Military Duty",
        "a_every_day_of_week": "Every Day an Alchemist",
        "a_monthly_hours": "Monthly Research Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Mustang Squad Gathering",
        "a_party_host": "Hughes Family Party Host",
        "a_social_butterfly": "Central Ballroom Social",
        "a_group_binge": "Elric Brothers Group Watch",
        "a_party_regular": "Regular Training Partner",
        "a_sync_viewer": "Synchronized Transmutation",
        "a_commentator": "Armstrong's Dramatic Commentary",
        "a_party_marathon": "State Alchemy Exam Marathon",
        "a_full_house": "Full Military Assembly",
        "a_community_pillar": "Pillar of the State",
        "a_watch_party_streak": "Consecutive Gathering Streak",
        "a_diverse_party": "Diverse Squad Team-Up",
        "a_late_night_party": "Late Night Central Party",
        "a_party_veteran": "Veteran Social Alchemist",
        "a_genre_party": "Cross-Discipline Party",
        "a_weekly_party": "Weekly Squad Gathering",
        "a_silent_viewer": "Silent Observer Hawkeye",
        "a_recommendation_giver": "State Recommendation Letter",
        "a_party_completionist": "Social Alchemist Completionist",
        "a_social_scorer": "Social State Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Formation",
        "a_fibonacci": "Fibonacci Transmutation Sequence",
        "a_palindrome_day": "Palindrome Time Rift",
        "a_binary_day": "Binary Alchemic Analysis",
        "a_full_moon": "Full Moon Philosopher's Glow",
        "a_leap_year": "Leap Year Time Skip",
        "a_time_traveler": "Memories Beyond the Gate",
        "a_genre_clash": "Alchemist vs. Homunculus Clash",
        "a_triple_seven": "Triple Seven Alchemic Combo",
        "a_thousand_complete": "Thousand Transmutations Complete",
        "a_pi_episodes": "Pi Calculation of Circles",
        "a_synchronicity": "Transmutation Synchronicity",
        "a_world_record": "World Record Alchemic Feat",
        "a_nice": "Nice Transmutation Count",
        "a_power_level": "Philosopher's Stone Power Level",
        "a_answer_42": "The Answer to Father's Riddle",
        "a_square_number": "Perfect Circle Formation",
        "a_prime_count": "Prime Number of Transmutations",
        "a_matching_date": "Matching Incident Date",
        "a_century_episode": "Century Episode Alchemic Arc",
        "a_double_digits": "Double Digit State Rank",
        "a_one_two_three": "Circles One Two Three",
        "a_lucky_seven": "Seven Lucky Alchemists",
        "a_all_tens": "All Tens Alchemic Score",
        "a_exact_hundred_eps": "Exact Hundred Alchemic Deeds",
        "a_year_match_count": "Year Match State Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Alchemist",
        "a_movie_buff": "Conqueror of Shamballa",
        "a_ova_hunter": "OVA Training Day Hunter",
        "a_ona_explorer": "ONA Alchemist Explorer",
        "a_special_watcher": "Special Episode Alchemist",
        "a_short_king": "Short Transmutation King",
        "a_variety_pack": "All-Format Alchemic Pack",
        "a_film_festival": "FMA Film Festival",
        "a_music_video": "Alchemic Theme Collection",
        "a_tv_short": "Quick Alchemic Clip",
        "a_movie_marathon": "Alchemic Movie Marathon",
        "a_double_length": "Double-Length Brotherhood Special",
        "a_anthology": "Alchemic Anthology",
        "a_mini_series": "Mini Alchemic Series",
        "a_theatrical": "Theatrical Alchemic Debut",
        "a_format_master": "Format Master Alchemist",
        "a_long_movie": "Feature-Length Sacred Star",
        "a_back_catalog": "Alchemic Back Catalog",
        "a_cm_watcher": "Commercial Break Alchemist",
        "a_pv_collector": "Alchemic Preview Collector",
        "a_format_balance": "Balanced Alchemic Formats",
        "a_episodic_master": "Episodic Alchemy Master",
        "a_sequel_movie": "Sequel Alchemic Movie",
        "a_recap_watcher": "Recap Briefing Alchemist",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Transmutation Streak",
        "a_mega_streak": "Mega Equivalent Exchange Streak",
        "a_weekly_warrior": "Weekly Warrior Alchemist",
        "a_monthly_watcher": "Monthly State Duty",
        "a_comeback": "Return from Beyond the Gate",
        "a_weekend_streak": "Weekend Alchemic Streak",
        "a_no_zero_days": "No Zero Days in Amestris",
        "a_iron_will": "Iron Will of an Alchemist",
        "a_habit_formed": "Research Regimen Formed",
        "a_consistent_pace": "Consistent Alchemic Pace",
        "a_year_long": "Year-Long Philosopher's Quest",
        "a_double_streak": "Double Streak Transmutation",
        "a_streak_recovery": "Streak Recovery Transmutation",
        "a_daily_minimum": "Daily Minimum Research",
        "a_winter_streak": "Winter at Briggs Streak",
        "a_summer_streak": "Summer Training Streak",
        "a_morning_streak": "Morning Transmutation Streak",
        "a_night_streak": "Night Laboratory Streak",
        "a_unbreakable": "Unbreakable Northern Wall",
        "a_eternal_flame": "Mustang's Eternal Flame",
        "a_completion_streak": "Mission Completion Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Episode Alchemic Arc",
        "a_genre_streak": "Genre Streak Alchemic Run",
        "a_studio_streak": "Studio Loyalty Alchemist",
        "a_perfect_week": "Perfect Week of Alchemy",

        // ── ANIME SCORING ──
        "a_critic": "State Military Critic",
        "a_perfect_ten": "Perfect 10 State Score",
        "a_harsh_critic": "Izumi Curtis's Harsh Judgment",
        "a_fair_judge": "Mustang's Fair Assessment",
        "a_generous_spirit": "Generous Alchemic Spirit",
        "a_score_all": "Full State Evaluation",
        "a_wide_range": "Wide Range Alchemic Assessment",
        "a_controversial": "Controversial State Ranking",
        "a_consistent_scorer": "Consistent State Evaluator",
        "a_score_sniper": "Hawkeye's Precision Score",
        "a_evolving_taste": "Evolving Alchemic Taste",
        "a_bell_curve": "Bell Curve of State Scores",
        "a_picky_watcher": "Selective Alchemic Judge",
        "a_100_rated": "Century of State Evaluations",
        "a_500_rated": "Five Hundred State Reports",
        "a_mediocre_majority": "Middle Rank Alchemist",
        "a_rating_spree": "Rating Transmutation Spree",
        "a_score_variance": "Variable State Ratings",
        "a_masterpiece_hunter": "Masterpiece Alchemic Hunter",
        "a_contrarian": "Contrarian State Critic",
        "a_optimist": "Optimist Like Alphonse",
        "a_score_distributor": "Score Distributor Alchemist",
        "a_genre_critic": "Genre Alchemy Critic",
        "a_mean_above_8": "Elite State Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Alchemic Resolution",
        "a_valentines_weeb": "Valentine's Equivalent Hearts",
        "a_pi_day": "Pi Day Transmutation Circle",
        "a_april_fools": "April Fools Alchemic Prank",
        "a_international_anime_day": "International Alchemist Day",
        "a_star_wars_day": "Star Wars Alchemic Crossover",
        "a_summer_solstice": "Summer Solstice Transmutation",
        "a_tanabata": "Tanabata Alchemic Wish",
        "a_friday_13th": "Friday 13th Homunculus Attack",
        "a_halloween_spirit": "Halloween Alphonse Costume",
        "a_thanksgiving_binge": "Thanksgiving Resembool Feast",
        "a_christmas_special": "Christmas in Central City",
        "a_new_years_eve": "New Year's Eve State Gala",
        "a_birthday_watch": "Alchemist Birthday Celebration",
        "a_holiday_marathon": "Holiday State Marathon",
        "a_independence_day": "Amestris Independence Day",
        "a_culture_day": "Xerxes Culture Festival",
        "a_spring_equinox": "Spring Equinox Transmutation",
        "a_earth_day": "Earth Day Alchemic Balance",
        "a_labor_day": "State Labor Day",
        "a_winter_solstice": "Winter Solstice at Briggs",
        "a_anime_birthday": "Anime Anniversary Alchemist",
        "a_every_holiday": "Every Holiday Alchemist",
        "a_consecutive_holidays": "Consecutive Holiday Missions",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Alchemic Awakening",
        "a_meta_collector": "State License Collector",
        "a_meta_category_starter": "Alchemic Category Initiation",
        "a_meta_tier_climber": "State Rank Promotion",
        "a_meta_tier_max": "Führer-Level Rank Achieved",
        "a_meta_xp_earner": "XP from Transmutations",
        "a_meta_difficulty_easy": "Easy Training Exercise",
        "a_meta_difficulty_hard": "Legendary: Promised Day Battle",
        "a_meta_unlock_spree": "Alchemic Unlock Spree",
        "a_meta_completionist": "Meta State Completionist",
        "a_meta_diverse": "Diverse Alchemic Portfolio",
        "a_meta_dominator": "Meta Pillar of the State",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter: The Two Alchemists",
        "m_chapter_counter": "Alchemic Page Counter",
        "m_chapter_titan": "Philosopher's Stone-Class Chapter",
        "m_reading_hours": "Hours Studying Alchemic Formulas",
        "m_reading_time_lord": "Total Concentration Reading",
        "m_manga_collector": "FMA Manga Collector",
        "m_library_legend": "Central Library Manga Legend",
        "m_first_complete": "First Manga Mission Done",
        "m_hundred_club": "Hundred-Chapter Alchemic Club",
        "m_first_day": "First Day of Alchemic Study",
        "m_first_rating": "First Manga State Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Alchemy",
        "m_volume_collector": "Volume Stockpile Alchemist",
        "m_year_explorer": "Year of Manga Alchemic Study",
        "m_century_reader": "Century-Chapter Alchemic Reader",
        "m_five_hundred_ch": "Five Hundred Alchemic Chapters",
        "m_thousand_ch": "Thousand-Chapter Transmutation",
        "m_reading_ten": "Ten Manga at Once Alchemist",
        "m_ptr_hoarder": "Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Alchemic Retreat",
        "m_season_reader": "Seasonal State Reading",
        "m_active_reader": "Active Field Reader Alchemist",
        "m_five_thousand_ch": "Five Thousand Chapters Deep",
        "m_ten_completed": "Ten Alchemic Manga Complete",
        "m_fifty_completed": "Fifty Manga Missions Done",
        "m_five_hundred_completed": "Five Hundred Manga Victories",
        "m_mean_score_tracker": "Average Manga State Rating",
        "m_unique_authors": "Unique Mangaka Encounters",
        "m_all_status": "All Reading Statuses Filed",
        "m_first_favorite": "First Manga Alchemic Bond",
        "m_favorites_collector": "Manga Favorites Arsenal",
        "m_days_spent_reading": "Days in Central Reading Hall",

        // ── MANGA BINGE ──
        "m_binge_reader": "Non-Stop Alchemic Reading",
        "m_marathon_reader": "Promised Day Reading Marathon",
        "m_weekend_reader": "Weekend Central Reading",
        "m_non_stop_reading": "Relentless Page Transmutation",
        "m_one_more_chapter": "One More Chapter Transmutation",
        "m_speed_read": "Automail Speed Read",
        "m_double_story": "Double Alchemic Feature",
        "m_triple_read": "Triple Reading Transmutation",
        "m_five_a_day": "Five Alchemic Reads a Day",
        "m_chapter_chain": "Chapter Chain Reaction",
        "m_volume_binge": "Volume Binge Transmutation",
        "m_power_reader": "Power Reader Alchemist",
        "m_half_day_read": "Half-Day Alchemic Study",
        "m_full_day_read": "Full-Day Manga Research",
        "m_power_weekend": "Power Weekend State Reading",
        "m_binge_king": "King of Alchemic Manga",
        "m_no_sleep_read": "All-Night Alchemic Reading",
        "m_full_series_rush": "Full Series Rush Transmutation",
        "m_seven_day_challenge": "Seven-Day Alchemic Challenge",
        "m_hundred_day_read": "Hundred-Day State Grind",
        "m_volume_rush": "Volume Rush Transmutation",
        "m_series_sweep": "Series Sweep Alchemist",
        "m_genre_binge": "Cross-Genre Alchemic Reading",
        "m_author_binge": "Arakawa Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Alchemic Count",
        "m_multi_series_binge": "Multi-Series Alchemic Reading",
        "m_midnight_binge": "Midnight Laboratory Reading",
        "m_new_year_binge": "New Year's Reading Transmutation",
        "m_forty_eight_hour": "Forty-Eight Hour Alchemic Read",
        "m_oneshot_binge": "Oneshot Alchemic Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Alchemy Manga Specialist",
        "m_genre_adventure": "Alchemic Adventure Manga",
        "m_genre_comedy": "Comedy at Hughes Household",
        "m_genre_drama": "Drama of the Elric Brothers",
        "m_genre_fantasy": "Fantasy Alchemy Manga",
        "m_genre_horror": "Chimera Horror Manga",
        "m_genre_mystery": "Mystery of the Philosopher's Stone",
        "m_genre_romance": "Alchemic Romance Manga",
        "m_genre_scifi": "Sci-Fi Alchemic Engineering",
        "m_genre_sol": "Resembool Life Slice of Life",
        "m_genre_sports": "Automail Combat Sports Manga",
        "m_genre_supernatural": "Supernatural Alchemy Manga",
        "m_genre_thriller": "Homunculus Thriller Manga",
        "m_genre_psychological": "Psychological Alchemic Warfare",
        "m_genre_isekai": "Gate of Truth Isekai Manga",
        "m_genre_shounen": "Shounen Alchemic Heart Manga",
        "m_genre_ecchi": "Hot Spring Chapter Manga",
        "m_genre_mahou_shoujo": "Magical Alchemic Manga",
        "m_genre_mecha": "Alphonse Armor Manga",
        "m_genre_music": "Military Band Manga",
        "m_tag_isekai_new": "New World Gate Manga",
        "m_tag_harem": "Alchemic Squad Manga",
        "m_tag_bl": "Brothers in Alchemy Manga",
        "m_tag_gl": "Alchemic Duo Manga",
        "m_tag_historical": "Amestris History Manga",
        "m_tag_military": "State Military Manga",
        "m_tag_school": "Izumi's Training Manga",
        "m_tag_martial_arts": "Combat Alchemy Manga",
        "m_tag_vampire": "Homunculus Regeneration Manga",
        "m_tag_samurai": "Xingese Warrior Manga",
        "m_tag_space": "Gate Dimensional Manga",
        "m_tag_parody": "Chibi Elric Parody Manga",
        "m_tag_idol": "Armstrong Artistic Manga",
        "m_tag_post_apocalyptic": "Post-Promised Day Manga",
        "m_tag_cyberpunk": "Automail Tech Manga",
        "m_tag_shoujo": "Winry's Story Manga",
        "m_tag_survival": "Survival at Briggs Manga",
        "m_tag_cooking": "Resembool Home Cooking Manga",
        "m_tag_medical": "Alchemic Medical Research Manga",
        "m_tag_villainess": "Homunculus Redemption Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full State Manga License",
        "m_mega_completionist": "Supreme Alchemic Reader",
        "m_completion_rate_50": "Halfway to Philosopher's Reader",
        "m_completion_rate_75": "Approaching Full Manga Mastery",
        "m_completion_rate_90": "Gate of Truth Manga Mastery",
        "m_no_drop": "No Manga Abandoned Alchemist",
        "m_long_runner_complete": "Long Alchemic Manga Endurance",
        "m_sequel_chain": "Brotherhood Sequel Reading Chain",
        "m_clean_list": "Clean Alchemic Reading Record",
        "m_from_ptr": "State Orders: Read Manga",
        "m_reread_master": "Transmutation Circle Reread",
        "m_oneshot_complete": "Oneshot Alchemic Specialist",
        "m_same_day_start_finish": "Same-Day Alchemic Manga Blitz",
        "m_revival": "Alphonse's Manga Revival",
        "m_zero_to_hundred": "Apprentice to State Alchemist Reader",
        "m_five_genre_complete": "Five-Genre Alchemic Mastery",
        "m_full_collection": "Full Alchemic Manga Collection",
        "m_batch_complete": "Batch Mission Clear Alchemist",
        "m_paused_to_done": "Returned from Manga Hiatus",
        "m_completion_spree": "Transmutation Reading Spree",
        "m_format_completionist": "Format Completion Alchemic Badge",
        "m_catch_up": "Caught Up with Serialization",
        "m_multi_reread": "Multi-Reread Alchemic Manga",
        "m_dropped_recovery": "Recovered from Failed Reading",
        "m_ten_perfect_scores": "Ten Perfect Alchemic Scores",
        "m_complete_genre_span": "All-Around Alchemic Reader",
        "m_monthly_completions": "Monthly State Manga Reports",
        "m_yearly_completions": "Annual State Manga Review",
        "m_rapid_complete": "Rapid Alchemic Manga Clear",
        "m_author_complete": "Arakawa's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal State Manga Reader",
        "m_mangaka_lover": "Hiromu Arakawa Devotee",
        "m_rereader": "Alchemic Manga Rereader",
        "m_triple_reread": "Triple Alchemic Reread",
        "m_annual_reread": "Annual Alchemic Reread Tradition",
        "m_publisher_fan": "State Publisher Fan",
        "m_artist_fan": "Alchemic Artist Appreciation",
        "m_adaptation_compare": "Manga vs Brotherhood Compare",
        "m_source_material_fan": "Source Material Alchemic Fan",
        "m_waiting_weekly": "Weekly Alchemic Chapter Wait",
        "m_classic_reader": "Classic Alchemy Manga Reader",
        "m_saga_reader": "Elric Saga Reader",
        "m_genre_loyalty": "Genre Loyalty Alchemic Medal",
        "m_decade_reader": "Decade-Long Alchemic Reader",
        "m_ln_adaptation": "Light Novel Alchemic Adaptation",
        "m_original_work": "Original Alchemic Manga Work",
        "m_long_commitment": "Long-Term Alchemic Commitment",
        "m_up_to_date": "Up-to-Date with Alchemic Manga",
        "m_favorite_mangaka": "Favorite Alchemic Mangaka",
        "m_complete_portfolio": "Complete Alchemic Portfolio",
        "m_franchise_collector": "FMA Franchise Collector",
        "m_serialization_follower": "Alchemic Serialization Follower",
        "m_genre_master": "Genre Alchemic Manga Mastery",
        "m_multi_series_author": "Multi-Series Alchemic Author Fan",
        "m_format_diversity": "Diverse Alchemic Reading Formats",
        "m_year_dedication": "Year of Alchemic Reading",
        "m_ongoing_follower": "Ongoing Alchemic Series Follower",
        "m_genre_loyalty_50": "Fifty Alchemic Genre Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Alchemic Genre Explorer",
        "m_publisher_hopper": "State Publisher Transfer",
        "m_tag_explorer": "Alchemic Tag Recon Mission",
        "m_decade_hopper": "Era-Hopping Alchemic Reader",
        "m_hidden_gem": "Hidden Alchemic Gem Manga",
        "m_popular_taste": "Popular Among State Readers",
        "m_retro_reader": "Retro Alchemy Manga Reader",
        "m_modern_reader": "Modern Alchemic Era Reader",
        "m_cross_demographic": "Cross-Division Reader",
        "m_underdog_fan": "Underdog Alchemic Manga Fan",
        "m_variety_week": "Week of Varied Alchemic Reads",
        "m_manhwa_reader": "Manhwa Alchemic Reader",
        "m_manhua_reader": "Manhua Alchemic Reader",
        "m_classic_connoisseur": "Classic Alchemy Manga Connoisseur",
        "m_award_winner": "Award-Winning Alchemic Manga",
        "m_niche_explorer": "Underground Alchemic Manga",
        "m_world_manga": "World Alchemic Manga Intel",
        "m_cult_classic": "Cult Classic Alchemic Tale",
        "m_random_pick": "Random Alchemic Assignment",
        "m_new_genre_month": "New Alchemic Genre Monthly",
        "m_year_completionist": "Year Alchemic Manga Completionist",
        "m_unpopular_opinion": "Unpopular Alchemic Manga Opinion",
        "m_top_rated_reader": "Top-Ranked Alchemic Manga",
        "m_source_variety": "Alchemic Source Material Variety",
        "m_low_score_brave": "Brave Alchemic Low-Score Reader",
        "m_short_manga_explorer": "Short Alchemic Manga Skirmish",
        "m_long_manga_explorer": "Long Alchemic Manga Campaign",
        "m_serialization_explorer": "Alchemic Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Alchemic Reader",
        "m_early_bird": "Dawn Patrol Alchemic Reader",
        "m_lunch_reader": "Lunch at Central Reader",
        "m_commute_reader": "Commute to Central Reader",
        "m_four_am_club": "4 AM Alchemic Study Session",
        "m_new_year_read": "New Year's Alchemic Reading Oath",
        "m_all_hours": "All-Hours Alchemic Reader",
        "m_prime_time_reader": "Prime Time Alchemic Manga",
        "m_workday_reader": "On-Duty State Reader",
        "m_sunday_read": "Sunday Alchemic Reading Marathon",
        "m_morning_routine": "Morning Transmutation Reading",
        "m_night_shift_reader": "Night Shift Alchemic Reader",
        "m_seasonal_premier_read": "New Alchemic Release Reader",
        "m_clock_collector": "Clock Tower Alchemic Reading",
        "m_late_night_horror": "Midnight Chimera Horror Read",
        "m_afternoon_reader": "Afternoon Alchemic Reader",
        "m_golden_hour_reader": "Golden Hour Alchemic Reading",
        "m_dawn_reader": "Dawn Alchemic Reading",
        "m_twilight_reader": "Twilight Alchemic Reader",
        "m_midnight_start": "Midnight Alchemic Reading Start",
        "m_weekend_binge_hours": "Weekend Alchemic Binge Reading",
        "m_late_night_regular": "Late Night Regular Reader",
        "m_sunrise_reader": "Sunrise Over Resembool Reader",
        "m_every_day_of_week": "Every Day Alchemic Reading",
        "m_monthly_hours": "Monthly Alchemic Reading Hours",
        "m_bedtime_reader": "Bedtime Resembool Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Arakawa Art Appreciator",
        "m_webtoon_reader": "Alchemic Webtoon Reader",
        "m_full_color": "Full Color Alchemic Manga",
        "m_doujin_reader": "Alchemic Doujin Reader",
        "m_anthology_reader": "Alchemic Anthology Reader",
        "m_adaptation_reader": "Alchemic Adaptation Reader",
        "m_longstrip_reader": "Vertical Alchemic Scroll",
        "m_4koma_reader": "Alchemic 4-Koma Shorts",
        "m_oneshot_reader": "Alchemic Oneshot Mission",
        "m_format_variety": "Alchemic Format Variety",
        "m_light_novel_reader": "Alchemic Light Novel Reader",
        "m_novel_reader": "Alchemic Novel Archives",
        "m_visual_storyteller": "Visual Alchemic Narrator",
        "m_colored_classic": "Colored Classic Alchemic Manga",
        "m_webcomic_fan": "Alchemic Webcomic Fan",
        "m_manga_to_anime": "Manga to Brotherhood Compare",
        "m_seinen_reader": "Seinen Alchemic Reader",
        "m_josei_reader": "Josei Alchemic Perspective",
        "m_award_winning_art": "Award-Winning Alchemic Artwork",
        "m_debut_work": "Alchemic Debut Manuscript",
        "m_vertical_scroll": "Vertical Scroll Alchemic",
        "m_traditional_format": "Traditional Alchemic Format",
        "m_cross_media": "Cross-Media Alchemic Intel",
        "m_spinoff_reader": "Alchemic Spinoff Reader",
        "m_remake_reader": "Alchemic Remake Reader",
        "m_collaboration_reader": "Alchemic Collaboration Manga",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Alchemic Reading Streak",
        "m_mega_streak": "Mega Alchemic Reading Streak",
        "m_weekly_warrior": "Weekly Warrior Alchemic Reader",
        "m_monthly_reader": "Monthly Alchemic Reader",
        "m_comeback": "Alchemic Reader's Comeback",
        "m_weekend_streak": "Weekend Alchemic Reading Streak",
        "m_no_zero_days": "No Zero Alchemic Reading Days",
        "m_iron_will": "Iron Will Alchemic Reader",
        "m_habit_formed": "Alchemic Reading Habit Formed",
        "m_consistent_pace": "Consistent Alchemic Reading Pace",
        "m_year_long": "Year-Long Alchemic Reading",
        "m_double_streak": "Double Alchemic Reading Streak",
        "m_streak_recovery": "Alchemic Streak Recovery",
        "m_daily_minimum": "Daily Minimum Alchemic Pages",
        "m_winter_streak": "Winter Briggs Reading Streak",
        "m_summer_streak": "Summer Training Reading Streak",
        "m_morning_streak": "Morning Alchemic Reading Streak",
        "m_night_streak": "Night Alchemic Reading Streak",
        "m_unbreakable": "Unbreakable Alchemic Reader",
        "m_eternal_flame": "Mustang's Eternal Reading Flame",
        "m_chapter_a_day": "Chapter a Day Alchemist",
        "m_genre_streak": "Genre Alchemic Reading Streak",
        "m_completion_streak": "Alchemic Completion Reading Chain",
        "m_rating_streak": "Alchemic Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Alchemic Streak",
        "m_author_streak": "Author Alchemic Dedication Streak",
        "m_perfect_week_manga": "Perfect Alchemic Reading Week",
        "m_diverse_streak": "Diverse Alchemic Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Alchemic Manga Critic",
        "m_perfect_ten": "Perfect 10 Alchemic Manga",
        "m_harsh_critic": "Izumi's Reading Standards",
        "m_fair_judge": "Mustang's Manga Review",
        "m_generous_spirit": "Generous Alchemic Reader",
        "m_score_all": "Full State Manga Assessment",
        "m_wide_range": "Wide Range Alchemic Scores",
        "m_controversial": "Controversial Alchemic Rating",
        "m_consistent_scorer": "Consistent Alchemic Manga Scorer",
        "m_score_sniper": "Precision Alchemic Score Sniper",
        "m_evolving_taste": "Evolving Alchemic Reading Taste",
        "m_bell_curve": "Bell Curve Alchemic Scores",
        "m_picky_reader": "Selective Alchemic Reader",
        "m_100_rated": "Century of Alchemic Manga Ratings",
        "m_500_rated": "Five Hundred Alchemic Reports",
        "m_mediocre_majority": "Middle Rank Alchemic Reader",
        "m_rating_spree": "Alchemic Rating Spree",
        "m_score_variance": "Variable Alchemic Manga Scores",
        "m_binge_rater": "Binge Alchemic Rating Session",
        "m_reread_rerate": "Reread & Re-Rate Alchemic Manga",
        "m_masterpiece_hunter": "Masterpiece Alchemic Manga Hunter",
        "m_contrarian": "Contrarian Alchemic Reader",
        "m_optimist": "Optimist Alchemic Reader",
        "m_score_distributor": "Alchemic Score Distributor",
        "m_genre_critic": "Genre Alchemic Manga Critic",
        "m_mean_above_8": "Elite Alchemic Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Alchemic Reading Vow",
        "m_valentines_read": "Valentine's Alchemic Reading",
        "m_pi_day": "Pi Day Alchemic Chapter Count",
        "m_april_fools": "April Fools Alchemic Manga",
        "m_international_manga_day": "International Alchemic Manga Day",
        "m_free_comic_day": "Free Alchemic Comic Day",
        "m_summer_solstice": "Summer Solstice Alchemic Reading",
        "m_tanabata": "Tanabata Alchemic Reading Wish",
        "m_friday_13th": "Friday 13th Homunculus Manga",
        "m_halloween_read": "Halloween Chimera Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Alchemic Feast",
        "m_christmas_read": "Christmas at Central Reading",
        "m_new_years_eve": "New Year's Eve Alchemic Read",
        "m_birthday_read": "Birthday Alchemic Reading Gift",
        "m_holiday_marathon": "Holiday Alchemic Reading Marathon",
        "m_independence_day": "Amestris Independence Reading Day",
        "m_culture_day": "Xerxes Culture Festival Reading",
        "m_spring_equinox": "Spring Equinox Alchemic Reading",
        "m_earth_day": "Earth Day Alchemic Reading",
        "m_labor_day": "State Labor Reading Day",
        "m_winter_solstice": "Winter Solstice Alchemic Reading",
        "m_manga_birthday": "Alchemic Manga Birthday",
        "m_every_holiday_reader": "Every Holiday Alchemic Reader",
        "m_consecutive_holidays": "Consecutive Holiday Alchemic Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Alchemic Milestone",
        "m_fibonacci": "Fibonacci Transmutation Pattern",
        "m_palindrome_day": "Palindrome Alchemic Reading Day",
        "m_binary_day": "Binary Alchemic Reading Day",
        "m_full_moon_read": "Full Moon Philosopher's Read",
        "m_leap_year_read": "Leap Year Alchemic Reading",
        "m_triple_seven": "Triple Seven Alchemic Combo",
        "m_thousand_complete": "Thousand Alchemic Manga Victories",
        "m_nice": "Nice Alchemic Chapter Count",
        "m_power_level_chapters": "Philosopher's Stone Chapter Power",
        "m_answer_42": "Answer to Father's Riddle Manga",
        "m_square_number": "Perfect Alchemic Formation",
        "m_prime_count": "Prime Alchemic Chapter Count",
        "m_matching_date": "Matching Alchemic Reading Date",
        "m_century_chapter": "Century Alchemic Chapter",
        "m_pi_chapters": "Pi Alchemic Chapter Calculation",
        "m_synchronicity": "Transmutation Reading Synchronicity",
        "m_world_record": "World Record Alchemic Chapters",
        "m_genre_clash": "Genre Clash Alchemic Reading",
        "m_time_traveler": "Gate of Truth Memory Reading",
        "m_double_digits": "Double Digit Alchemic Milestone",
        "m_one_two_three": "Circles One Two Three Manga",
        "m_lucky_seven": "Seven Lucky Alchemic Chapters",
        "m_exact_hundred_ch": "Exact Hundred Alchemic Chapters",
        "m_year_match_count": "Year Match Alchemic Chapter Count",
        "m_chapter_match_date": "Chapter Date Alchemic Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Alchemic Manga Format",
        "m_manhwa_format": "Manhwa Alchemic Format",
        "m_manhua_format": "Manhua Alchemic Format",
        "m_ln_format": "Light Novel Alchemic Format",
        "m_oneshot_format": "Oneshot Alchemic Format",
        "m_doujin_format": "Doujin Alchemic Format",
        "m_novel_format": "Novel Alchemic Format",
        "m_format_master_manga": "Format Master Alchemic Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Alchemic Reading Awakened",
        "m_meta_collector": "Alchemic Reading Badge Collector",
        "m_meta_category_starter": "Alchemic Category Initiation",
        "m_meta_tier_climber": "Alchemic Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Alchemic Reading Rank",
        "m_meta_xp_earner": "XP from Alchemic Reading",
        "m_meta_difficulty_easy": "Easy Alchemic Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Alchemic Manga Challenge",
        "m_meta_unlock_spree": "Alchemic Reading Unlock Spree",
        "m_meta_completionist": "Meta Alchemic Reading Completionist",
        "m_meta_diverse": "Diverse Alchemic Reading Portfolio",
        "m_meta_dominator": "Meta Alchemic Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#08060a",
        primary: "#c8a028",
        secondary: "#e0b830",
        accent: "#f0d050",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/fullmetal-alchemist.jpg",
    particleColor: "#c07830",
    backgroundDim: 0.28,
    backgroundBlur: 26,
    particleTypes: {
        transmutation_sparks: { label: "Transmutation Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 65 },
        alchemy_circles: { label: "Alchemy Circles", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        philosopher_glow: { label: "Philosopher's Glow", maxCount: 12, defaultEnabled: true, defaultIntensity: 50 },
        automail_fragments: { label: "Automail Fragments", maxCount: 8, defaultEnabled: true, defaultIntensity: 60 },
        homunculus_marks: { label: "Homunculus Marks", maxCount: 10, defaultEnabled: true, defaultIntensity: 45 },
    },
    playerIconOverrides: fullmetalAlchemistPlayerIcons,
    milestoneNames: {
        1:   "Civilian",
        8:   "Aspiring Alchemist",
        18:  "State Alchemist",
        30:  "Major",
        42:  "Lt. Colonel",
        55:  "Colonel",
        70:  "General",
        85:  "F\u00FChrer",
        100: "Truth",
    },
}
