import { AnimeThemeConfig } from "./types"
import {
    GiDeathSkull,
    GiSkullCrossedBones,
    GiBullseye,
    GiAnvilImpact,
    GiSpiralArrow,
    GiChainedHeart,
    GiEagleEmblem,
    GiResize,
    GiTrophyCup,
    GiPalette,
    GiAlarmClock,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const gantzTheme: AnimeThemeConfig = {
    id: "gantz",
    displayName: "Gantz",
    description: "You are dead. GANTZ has other plans. Don black combat suits and hunt alien targets before the clock hits zero.",
    fontFamily: "'Share Tech Mono', monospace",
    fontHref: "https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap",
    cssVars: {
        // Brand → black steel
        "--color-brand-200": "190 190 190",
        "--color-brand-300": "155 155 155",
        "--color-brand-400": "110 110 110",
        "--color-brand-500": "75 75 75",
        "--color-brand-600": "55 55 55",
        "--color-brand-700": "38 38 38",
        "--color-brand-800": "24 24 24",
        "--color-brand-900": "14 14 14",
        "--color-brand-950": "6 6 6",
        "--brand": "51 51 51",
        // Near-black background
        "--background": "#020202",
        "--paper": "#060606",
        "--color-gray-950": "2 2 2",
        "--color-gray-900": "6 6 6",
        "--color-gray-800": "14 14 14",
        "--color-gray-700": "26 26 26",
        "--color-gray-600": "42 42 42",
        "--color-gray-500": "70 70 70",
        "--color-gray-400": "115 115 115",
        "--color-gray-300": "160 160 160",
        "--color-gray-200": "200 200 200",
        "--color-gray-100": "228 228 228",
        "--color-gray-50": "244 244 244",
    },
    sidebarOverrides: {
        "home": { icon: GiDeathSkull, label: "GANTZ Room" },
        "schedule": { icon: GiAlarmClock, label: "Mission Timer" },
        "manga": { icon: LuBookOpen, label: "Mission Files" },
        "lists": { icon: GiSkullCrossedBones, label: "Hunter Roster" },
        "discover": { icon: GiBullseye, label: "Next Target Zone" },
        "torrent-list": { icon: GiAnvilImpact, label: "Weapon Drop" },
        "debrid": { icon: GiSpiralArrow, label: "GANTZ Data Stream" },
        "unmatched": { icon: GiChainedHeart, label: "MIA Hunters" },
        "enmasse": { icon: GiResize, label: "Mass Operation" },
        "scan-summaries": { icon: TbReportSearch, label: "Mission Reports" },
        "auto-downloader": { icon: LuRss, label: "Target Feed" },
        "community": { icon: GiEagleEmblem, label: "Hunter Network" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Mission Alerts" },
        "achievements": { icon: GiTrophyCup, label: "Point Tally" },
        "theme-manager": { icon: GiPalette, label: "Suit Colors" },
        "extensions": { icon: BiExtension, label: "Suit Modules" },
        "sync": { icon: IoCloudOfflineOutline, label: "GANTZ Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Sphere Control" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Resurrection Experience",
        "a_episode_counter": "Mission Point Counter",
        "a_episode_titan": "Boss-Level Alien Target",
        "a_hours_invested": "Hours Inside the Sphere",
        "a_time_lord": "GANTZ's Temporal Control",
        "a_anime_collector": "Black Suit Arsenal Collector",
        "a_library_legend": "Mission Database Legend",
        "a_first_complete": "First Mission Survived",
        "a_hundred_club": "Hundred Point Club",
        "a_first_day": "First Day Dead",
        "a_first_rating": "First Mission Debrief",
        "a_ten_thousand_min": "Ten Thousand Hunting Minutes",
        "a_season_veteran": "Veteran Black Suit",
        "a_year_explorer": "Year of GANTZ Missions",
        "a_century_watcher": "Hundred Missions Witnessed",
        "a_five_hundred_eps": "Five Hundred Alien Kills",
        "a_thousand_eps": "Thousand Targets Hunted",
        "a_watching_ten": "Ten Mission Fronts",
        "a_ptw_hoarder": "Mission Queue Hoarder",
        "a_dropped_honesty": "Mission Abandoned Truth",
        "a_five_thousand_eps": "Five Thousand Point Value",
        "a_ten_completed": "Ten Campaigns Done",
        "a_fifty_completed": "Fifty Missions Complete",
        "a_five_hundred_completed": "Five Hundred Alien Victories",
        "a_mean_score_tracker": "Average Mission Score",
        "a_unique_studios": "Unique Target Species Count",
        "a_days_spent_watching": "Days Inside the Sphere",
        "a_all_status": "All Hunter Statuses",
        "a_first_favorite": "First Partner Bond",
        "a_favorites_collector": "Team Bond Collector",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Hunt Run",
        "a_marathon_runner": "Mission-to-Mission Marathon",
        "a_weekend_warrior": "Weekend Alien Warrior",
        "a_non_stop": "Relentless Target Advance",
        "a_one_more_episode": "One More Mission",
        "a_speed_run": "Speed Run Before Zero",
        "a_double_feature": "Double Mission Feature",
        "a_triple_threat": "Triple Target Takedown",
        "a_five_a_day": "Five Episodes a Day",
        "a_back_to_back": "Back-to-Back Alien Hunts",
        "a_seasonal_binge": "Full Mission Arc",
        "a_cour_crusher": "District Hunter Crusher",
        "a_half_day_watch": "Half-Day Sphere Session",
        "a_full_day_watch": "Full Day in the Sphere",
        "a_power_weekend": "Power Weekend Hunt",
        "a_binge_king": "King of the GANTZ Binge",
        "a_no_sleep": "All-Night Vigil Before Zero",
        "a_entire_season": "Full Season Hunt Clear",
        "a_seven_day_challenge": "Seven-Day Death Watch",
        "a_hundred_day_binge": "Hundred-Day Mission Siege",
        "a_genre_binge": "Cross-Target Training Run",
        "a_studio_binge": "Allied Team Binge",
        "a_season_sweep": "Season Sweep Hunt",
        "a_forty_eight_hour": "Forty-Eight Hour Standoff",
        "a_ep_counter_day": "Daily Kill Count",
        "a_multi_series_binge": "Multi-Mission Campaign",
        "a_midnight_binge": "Midnight Hunt Session",
        "a_new_year_binge": "New Year's Hunt Blitz",

        // ── ANIME GENRES ──
        "a_genre_action": "Alien Combat Specialist",
        "a_genre_adventure": "Beyond the GANTZ Room",
        "a_genre_comedy": "Suzuki's Absurd Moment",
        "a_genre_drama": "Kato's Noble Sacrifice",
        "a_genre_fantasy": "GANTZ Sphere Mystery",
        "a_genre_horror": "Alien Body Horror",
        "a_genre_mystery": "Sphere Intelligence Unknown",
        "a_genre_romance": "Heart Amid the Hunt",
        "a_genre_scifi": "GANTZ Technology Study",
        "a_genre_sol": "Life Between Missions",
        "a_genre_sports": "Training Before the Clock",
        "a_genre_supernatural": "Resurrection Power",
        "a_genre_thriller": "Clock Hits Zero Thriller",
        "a_genre_mecha": "Anti-Alien Suit Tech",
        "a_genre_music": "GANTZ Mission Soundtrack",
        "a_genre_psychological": "Kurono's Mental Breaking",
        "a_genre_ecchi": "Pre-Mission Locker Room",
        "a_genre_mahou_shoujo": "Sphere Granted Power",
        "a_tag_isekai": "Transported to GANTZ Room",
        "a_tag_harem": "Mission Squad Bond",
        "a_tag_bl": "Hunters in Arms",
        "a_tag_gl": "Shield Hunters",
        "a_tag_historical": "Alien Invasion History",
        "a_tag_military": "Black Suit Discipline",
        "a_tag_school": "Hunters in School",
        "a_tag_martial_arts": "Hand-to-Hand Combat",
        "a_tag_vampire": "Alien Blood Hunter",
        "a_tag_samurai": "Katana-Class Hunter",
        "a_tag_space": "Alien Home World",
        "a_tag_parody": "GANTZ Parody Target",
        "a_tag_idol": "Sphere's Favorite Hunter",
        "a_tag_post_apocalyptic": "Post-Mission Desolation",
        "a_tag_cyberpunk": "Black Suit Cyberpunk",
        "a_tag_shounen": "Shounen Hunter Spirit",
        "a_tag_seinen": "Seinen Death Reality",
        "a_tag_shoujo": "Heart of a Hunter",
        "a_tag_josei": "Deep Devotion to Survival",
        "a_tag_survival": "Survival Before Zero",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Mission Report Card",
        "a_mega_completionist": "Supreme Hunter Status",
        "a_completion_rate_50": "Halfway to 100 Points",
        "a_completion_rate_75": "75 Points Earned",
        "a_completion_rate_90": "90 Points to Freedom",
        "a_no_drop": "No Mission Abandoned",
        "a_long_runner_complete": "Long Hunt Endurance",
        "a_sequel_chain": "Mission Chain Continued",
        "a_clean_list": "Clean Mission Record",
        "a_from_ptw": "Sphere Orders Executed",
        "a_rewatch_master": "Mission Tape Rewatch",
        "a_short_complete": "Quick Target Down",
        "a_same_day_start_finish": "Same-Day Mission Clear",
        "a_revival": "Revived by the Sphere",
        "a_zero_to_hero": "Dead Man to Elite Hunter",
        "a_five_genre_complete": "Five-Hunt Mastery",
        "a_full_franchise": "Full GANTZ Dossier",
        "a_batch_complete": "Batch Mission Clear",
        "a_paused_to_done": "Back from Death's Door",
        "a_completion_spree": "Completion Kill Spree",
        "a_multi_rewatch": "Multi-Mission Replay",
        "a_dropped_recovery": "Recovered from the Sphere",
        "a_ten_perfect_scores": "Ten Perfect Mission Scores",
        "a_seasonal_clear": "Seasonal Hunt Clear",
        "a_complete_genre_span": "All-Target Scout",
        "a_monthly_completions": "Monthly Mission Reports",
        "a_yearly_completions": "Yearly Hunt Champion",
        "a_rapid_complete": "Lightning Mission Clear",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal GANTZ Hunter",
        "a_studio_devotee": "Gonzo/MAPPA Devotee",
        "a_rewatcher": "Mission Tape Rewatcher",
        "a_triple_rewatch": "Triple Mission Rewatch",
        "a_annual_tradition": "Annual GANTZ Tradition",
        "a_director_fan": "Director's Vision Follower",
        "a_voice_actor_fan": "Voice of Kurono Fan",
        "a_ost_lover": "GANTZ OST Devotee",
        "a_source_reader": "Hiroya Oku's Manga Reader",
        "a_waiting_weekly": "Weekly Intel Signal Wait",
        "a_childhood_revisit": "Return to the Sphere",
        "a_saga_tracker": "GANTZ Saga Tracker",
        "a_genre_loyalty": "Hunter Genre Loyalty",
        "a_decade_watcher": "Decade-Long GANTZ Fan",
        "a_adaptation_hunter": "Adaptation Recon",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Hunt Devotion",
        "a_perfect_attendance": "Perfect Mission Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Anime Catalog",
        "a_franchise_collector": "GANTZ Universe Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Mastery Achieved",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Season Hunter Fan",
        "a_format_diversity": "Diverse Tactical Formats",
        "a_year_dedication": "Year of GANTZ Devotion",
        "a_season_dedication": "Season of Unwavering Hunt",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Known Targets",
        "a_studio_hopper": "Hunter Faction Transfer",
        "a_tag_explorer": "Tag Recon Mission",
        "a_decade_hopper": "Time via Sphere Control",
        "a_hidden_gem": "Hidden Alien Encounter",
        "a_popular_taste": "Popular Among Hunters",
        "a_retro_appreciator": "Pre-Mission Era Appreciator",
        "a_modern_viewer": "Modern Hunter Viewer",
        "a_cross_demographic": "Cross-Demographic Hunter",
        "a_underdog_fan": "Underdog Hunter Spirit",
        "a_variety_week": "Week of Varied Tactics",
        "a_foreign_cinema": "Foreign Intelligence Cinema",
        "a_classic_connoisseur": "Classic Hunt Connoisseur",
        "a_every_season": "Every Season Deployed",
        "a_award_winner": "Medal of Alien Valor",
        "a_niche_explorer": "Niche Target Explorer",
        "a_global_anime": "Global Alliance Entry",
        "a_cult_classic": "Underground Cult Classic",
        "a_random_pick": "Random Mission Assignment",
        "a_new_genre_month": "New Target Monthly",
        "a_seasonal_completionist": "Seasonal Hunt Clear",
        "a_unpopular_opinion": "Unpopular Hunter Opinion",
        "a_top_rated_viewer": "Top-Rated Intel Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Mission Intel",
        "a_short_series_explorer": "Short Hunt Explorer",
        "a_long_series_explorer": "Long Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Watch Before Zero",
        "a_early_bird": "Dawn Hunt Patrol",
        "a_lunch_break": "Pre-Mission Meal Break",
        "a_golden_hour": "Golden Hour Before Zero",
        "a_four_am_club": "4 AM Mission Alert",
        "a_witching_hour": "Midnight Sphere Activation",
        "a_new_year_watch": "New Year's Survival Oath",
        "a_midnight_premiere": "Midnight Mission Premiere",
        "a_all_hours": "All-Hours GANTZ Scout",
        "a_dawn_warrior": "Dawn Warrior Hunter",
        "a_afternoon_delight": "Afternoon Mission Drill",
        "a_prime_time": "Prime Time Engagement",
        "a_workday_watcher": "On-Duty Hunt Watcher",
        "a_sunday_marathon": "Sunday Hunt Marathon",
        "a_rainy_day": "Rainy Day in the Sphere",
        "a_morning_routine": "Morning Formation",
        "a_night_shift": "Night Shift Hunt Patrol",
        "a_twilight_zone": "Twilight Sphere Zone",
        "a_seasonal_premier": "Season Premiere Hunt",
        "a_clock_collector": "Zero Clock Collector",
        "a_weekend_binge_hours": "Weekend Hunt Operations",
        "a_late_night_regular": "Late Night Sphere Patrol",
        "a_sunrise_watcher": "Sunrise Over the Sphere",
        "a_holiday_watcher": "Holiday Hunt Watch",
        "a_every_day_of_week": "Every Day Deployed",
        "a_monthly_hours": "Monthly Hunt Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Hunt Team Formation",
        "a_party_host": "Mission Commander",
        "a_social_butterfly": "Pre-Mission Socialite",
        "a_group_binge": "Group Hunt Volley",
        "a_party_regular": "Regular Hunt Partner",
        "a_sync_viewer": "Synchronized Hunt Maneuver",
        "a_commentator": "Battle Commentator",
        "a_party_marathon": "Marathon Hunt Run",
        "a_full_house": "Full Squad Assembled",
        "a_community_pillar": "Pillar of the Hunters",
        "a_watch_party_streak": "Consecutive Hunt Streak",
        "a_diverse_party": "Diverse Hunter Party",
        "a_late_night_party": "Late Night Pre-Mission Party",
        "a_party_veteran": "Veteran Hunt Captain",
        "a_genre_party": "Cross-Genre Formation",
        "a_weekly_party": "Weekly Hunters' Gathering",
        "a_silent_viewer": "Silent GANTZ Observer",
        "a_recommendation_giver": "Commander's Recommendation",
        "a_party_completionist": "Party Hunt Completionist",
        "a_social_scorer": "Social Hunt Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Formation",
        "a_fibonacci": "Fibonacci Target Sequence",
        "a_palindrome_day": "Palindrome Mission Day",
        "a_binary_day": "Binary Signal Day",
        "a_full_moon": "Full Moon Sphere Activation",
        "a_leap_year": "Leap Year Mission Skip",
        "a_time_traveler": "Sphere's Time Control",
        "a_genre_clash": "Hunters vs Aliens Clash",
        "a_triple_seven": "Triple Seven Point Score",
        "a_thousand_complete": "Thousand Battles for Survival",
        "a_pi_episodes": "Pi Mission Calculation",
        "a_synchronicity": "Sphere Synchronicity",
        "a_world_record": "World Record Alien Kill",
        "a_nice": "Nice Kill Count",
        "a_power_level": "Black Suit Power Level",
        "a_answer_42": "The Answer to Survival",
        "a_square_number": "Perfect Squad Formation",
        "a_prime_count": "Prime Number of Targets",
        "a_matching_date": "Matching Intel Date",
        "a_century_episode": "Century Episode Assault",
        "a_double_digits": "Double Digit Point Score",
        "a_one_two_three": "Kurono Kato GANTZ",
        "a_lucky_seven": "Lucky Seven Survivors",
        "a_all_tens": "All Tens Mission Score",
        "a_exact_hundred_eps": "Exact Hundred Points",
        "a_year_match_count": "Year Match Point Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Hunter",
        "a_movie_buff": "GANTZ Film Operations",
        "a_ova_hunter": "OVA Intel Hunter",
        "a_ona_explorer": "ONA Scout Explorer",
        "a_special_watcher": "Special Mission Viewer",
        "a_short_king": "Short Engagement King",
        "a_variety_pack": "All-Format Regiment",
        "a_film_festival": "GANTZ Film Festival",
        "a_music_video": "Sphere Sound Collection",
        "a_tv_short": "Quick Recon Clip",
        "a_movie_marathon": "Movie Marathon Blitz",
        "a_double_length": "Double-Length Mission",
        "a_anthology": "GANTZ Anthology",
        "a_mini_series": "Mini Mission Collection",
        "a_theatrical": "Theatrical Deployment",
        "a_format_master": "Format Master Hunter",
        "a_long_movie": "Feature-Length Expedition",
        "a_back_catalog": "Back Catalog Hunt Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Tactical Formats",
        "a_episodic_master": "Episodic Mission Master",
        "a_sequel_movie": "Sequel Operation Film",
        "a_recap_watcher": "Briefing Recap Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Hunt Streak",
        "a_mega_streak": "Mega Mission Streak",
        "a_weekly_warrior": "Weekly Warrior of the Sphere",
        "a_monthly_watcher": "Monthly Hunt Duty",
        "a_comeback": "Return from the Dead",
        "a_weekend_streak": "Weekend Hunt Streak",
        "a_no_zero_days": "No Zero Hunt Days",
        "a_iron_will": "Iron Will of the Hunters",
        "a_habit_formed": "Hunt Regimen Formed",
        "a_consistent_pace": "Consistent Hunt Advance",
        "a_year_long": "Year-Long Hunt Campaign",
        "a_double_streak": "Double Streak Hunt",
        "a_streak_recovery": "Revival Corps Recovery",
        "a_daily_minimum": "Daily Minimum Hunt",
        "a_winter_streak": "Winter Hunt Campaign",
        "a_summer_streak": "Summer Offensive Hunt",
        "a_morning_streak": "Morning Drill Hunt",
        "a_night_streak": "Night Patrol Hunt",
        "a_unbreakable": "Unbreakable Hunter Will",
        "a_eternal_flame": "Eternal GANTZ Flame",
        "a_completion_streak": "Completion Mission Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Mission Offensive",
        "a_genre_streak": "Genre Streak Sortie",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Week of Hunts",

        // ── ANIME SCORING ──
        "a_critic": "Mission Debrief Critic",
        "a_perfect_ten": "Perfect 100-Point Rating",
        "a_harsh_critic": "Gantz Sphere's Standards",
        "a_fair_judge": "Kato's Fair Assessment",
        "a_generous_spirit": "Generous Hunter Spirit",
        "a_score_all": "Full Roster Evaluation",
        "a_wide_range": "Wide Range Tactical Rating",
        "a_controversial": "Controversial Mission Decision",
        "a_consistent_scorer": "Consistent Hunt Evaluator",
        "a_score_sniper": "Precision Target Sniper",
        "a_evolving_taste": "Evolving Hunt Strategy",
        "a_bell_curve": "Bell Curve of Mission Scores",
        "a_picky_watcher": "Selective Mission Commander",
        "a_100_rated": "Century of Evaluations",
        "a_500_rated": "Five Hundred Field Reports",
        "a_mediocre_majority": "Middle Ground Hunter",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Variable Mission Ratings",
        "a_masterpiece_hunter": "Masterpiece Hunt Finder",
        "a_contrarian": "Contrarian Hunter Opinion",
        "a_optimist": "Optimist Despite the Deaths",
        "a_score_distributor": "Score Distributor General",
        "a_genre_critic": "Genre Mission Critic",
        "a_mean_above_8": "Elite Hunt Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Survival Vow",
        "a_valentines_weeb": "Valentine's Hunt Day",
        "a_pi_day": "Pi Day Mission Calc",
        "a_april_fools": "April Fools Fake Mission",
        "a_international_anime_day": "International Hunter Day",
        "a_star_wars_day": "Alien Invasion Day",
        "a_summer_solstice": "Summer Solstice Hunt",
        "a_tanabata": "Tanabata Wish to Live",
        "a_friday_13th": "Friday 13th Death Night",
        "a_halloween_spirit": "Halloween Alien Horror",
        "a_thanksgiving_binge": "Thanksgiving Survival Feast",
        "a_christmas_special": "Midwinter Mission Special",
        "a_new_years_eve": "New Year's Eve Final Hunt",
        "a_birthday_watch": "Birthday Resurrection Watch",
        "a_holiday_marathon": "Holiday Hunt Marathon",
        "a_independence_day": "Hunter Independence Day",
        "a_culture_day": "Hunter Culture Day",
        "a_spring_equinox": "Spring Mission Advance",
        "a_earth_day": "Protect This World Day",
        "a_labor_day": "Hunter Labor Day",
        "a_winter_solstice": "Winter Solstice Hunt",
        "a_anime_birthday": "Anime Anniversary Watch",
        "a_every_holiday": "Every Holiday Hunter",
        "a_consecutive_holidays": "Consecutive Holiday Hunts",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Suit Power Awakened",
        "a_meta_collector": "GANTZ Badge Collector",
        "a_meta_category_starter": "Category Initiation Rite",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Elite Hunter Rank",
        "a_meta_xp_earner": "XP from Hunt Points",
        "a_meta_difficulty_easy": "Easy Training Mission",
        "a_meta_difficulty_hard": "Legendary Difficulty: Boss Target",
        "a_meta_unlock_spree": "Unlock Spree Thunder Kill",
        "a_meta_completionist": "Meta Completionist Commander",
        "a_meta_diverse": "Diverse Hunt Portfolio",
        "a_meta_dominator": "Meta Dominator of the Sphere",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter Revived",
        "m_chapter_counter": "Chapter Kill Counter",
        "m_chapter_titan": "Boss Alien Chapter",
        "m_reading_hours": "Hours Reading Mission Files",
        "m_reading_time_lord": "Sphere's Reading Control",
        "m_manga_collector": "Black Suit Archive Collector",
        "m_library_legend": "Mission Database Legend",
        "m_first_complete": "First Manga Mission Done",
        "m_hundred_club": "Hundred-Chapter Hunter Club",
        "m_first_day": "First Day of Reading",
        "m_first_rating": "First Mission Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Intel",
        "m_volume_collector": "Volume Stockpile Collector",
        "m_year_explorer": "Year of Manga Exploration",
        "m_century_reader": "Century-Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Chapters Hunted",
        "m_thousand_ch": "Thousand-Chapter Campaign",
        "m_reading_ten": "Ten Manuscripts at Once",
        "m_ptr_hoarder": "Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Mission Retreat",
        "m_season_reader": "Seasonal Reading Rotation",
        "m_active_reader": "Active Field Reader",
        "m_five_thousand_ch": "Five Thousand Chapters Deep",
        "m_ten_completed": "Ten Manga Campaigns Complete",
        "m_fifty_completed": "Fifty Manga Missions Done",
        "m_five_hundred_completed": "Five Hundred Manga Victories",
        "m_mean_score_tracker": "Average Manuscript Rating",
        "m_unique_authors": "Unique Author Encounters",
        "m_all_status": "All Reading Hunt Statuses",
        "m_first_favorite": "First Manga Bond",
        "m_favorites_collector": "Manga Arsenal Collector",
        "m_days_spent_reading": "Days in Reading Sphere",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading Hunt",
        "m_marathon_reader": "Sphere-to-Sphere Marathon",
        "m_weekend_reader": "Weekend Hunt Reading",
        "m_non_stop_reading": "Non-Stop Page Turning",
        "m_one_more_chapter": "One More Chapter Hunt",
        "m_speed_read": "Speed Read Before Zero",
        "m_double_story": "Double Mission Feature",
        "m_triple_read": "Triple Reading Assault",
        "m_five_a_day": "Five Reads a Day",
        "m_chapter_chain": "Chapter Chain Hunt",
        "m_volume_binge": "Volume Binge Bombardment",
        "m_power_reader": "Power Reader Scout",
        "m_half_day_read": "Half-Day Archive Dive",
        "m_full_day_read": "Full-Day Mission Study",
        "m_power_weekend": "Power Weekend Reading",
        "m_binge_king": "King of the Reading Sphere",
        "m_no_sleep_read": "All-Night Hunt Reading",
        "m_full_series_rush": "Full Series Rush Attack",
        "m_seven_day_challenge": "Seven-Day Intel Gathering",
        "m_hundred_day_read": "Hundred-Day Reading Siege",
        "m_volume_rush": "Volume Rush Deployment",
        "m_series_sweep": "Series Sweep Hunt",
        "m_genre_binge": "Cross-Genre Reading Run",
        "m_author_binge": "Hiroya Oku Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Kill Count",
        "m_multi_series_binge": "Multi-Series Reading Front",
        "m_midnight_binge": "Midnight Archive Session",
        "m_new_year_binge": "New Year's Reading Charge",
        "m_forty_eight_hour": "Forty-Eight Hour Reading Siege",
        "m_oneshot_binge": "Oneshot Blitz Attack",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Manuscript Specialist",
        "m_genre_adventure": "Adventure Beyond the Sphere",
        "m_genre_comedy": "Comedy Amid the Hunt",
        "m_genre_drama": "Drama of Death's Mercy",
        "m_genre_fantasy": "Fantasy of the Sphere",
        "m_genre_horror": "Alien Horror Manuscript",
        "m_genre_mystery": "Mystery of the Sphere",
        "m_genre_romance": "Romance Under the Clock",
        "m_genre_scifi": "Sci-Fi Suit Engineering",
        "m_genre_sol": "Slice of Life Between Hunts",
        "m_genre_sports": "Training Circuit Manga",
        "m_genre_supernatural": "Supernatural Sphere Power",
        "m_genre_thriller": "Thriller Intelligence Report",
        "m_genre_psychological": "Psychological Warfare Reader",
        "m_genre_isekai": "Isekai Beyond Death",
        "m_genre_shounen": "Shounen Hunt Spirit",
        "m_genre_ecchi": "Pre-Mission Locker Chapter",
        "m_genre_mahou_shoujo": "Power of the Sphere",
        "m_genre_mecha": "Anti-Alien Suit Blueprints",
        "m_genre_music": "GANTZ Mission Songs",
        "m_tag_isekai_new": "New World Beyond Death",
        "m_tag_harem": "Squad Bonds Manga",
        "m_tag_bl": "Hunters in Arms Manga",
        "m_tag_gl": "Shield Hunters Manga",
        "m_tag_historical": "Alien Invasion History Manga",
        "m_tag_military": "Black Suit Operations Manga",
        "m_tag_school": "Hunters in School Manga",
        "m_tag_martial_arts": "Combat Manual",
        "m_tag_vampire": "Alien Blood Manga",
        "m_tag_samurai": "Blade Hunter Manga",
        "m_tag_space": "Alien Home World Manga",
        "m_tag_parody": "Chibi Hunt Manga",
        "m_tag_idol": "Sphere's Favorite Manga",
        "m_tag_post_apocalyptic": "Post-Hunt Manga",
        "m_tag_cyberpunk": "Black Suit Cyberpunk Manga",
        "m_tag_shoujo": "Heart of a Hunter Manga",
        "m_tag_survival": "Survival Before Zero Manga",
        "m_tag_cooking": "Hunt Rations Cookbook",
        "m_tag_medical": "Field Medic Manga",
        "m_tag_villainess": "GANTZ Experiment Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Mission Completionist",
        "m_mega_completionist": "Supreme Manga Commander",
        "m_completion_rate_50": "Halfway to 100 Points",
        "m_completion_rate_75": "Approaching Freedom",
        "m_completion_rate_90": "Final Chapter Approaching",
        "m_no_drop": "No Manuscript Abandoned",
        "m_long_runner_complete": "Long Series Endurance",
        "m_sequel_chain": "Sequel Chain of Command",
        "m_clean_list": "Clean Reading Record",
        "m_from_ptr": "Orders Received: Read",
        "m_reread_master": "Mission Tape Reread",
        "m_oneshot_complete": "Oneshot Mission Specialist",
        "m_same_day_start_finish": "Same-Day Reading Blitz",
        "m_revival": "Revival Through the Sphere",
        "m_zero_to_hundred": "Rookie to Elite Hunter",
        "m_five_genre_complete": "Five-Genre Mastery",
        "m_full_collection": "Full Archive Collection",
        "m_batch_complete": "Batch Hunt Clearance",
        "m_paused_to_done": "Back from Death's Hiatus",
        "m_completion_spree": "Completion Kill Barrage",
        "m_format_completionist": "Format Completion Badge",
        "m_catch_up": "Caught Up with Serialization",
        "m_multi_reread": "Multi-Pass Reread",
        "m_dropped_recovery": "Recovered from the Sphere",
        "m_ten_perfect_scores": "Ten Perfect Scores",
        "m_complete_genre_span": "All-Genre Reading Scout",
        "m_monthly_completions": "Monthly Manuscript Victories",
        "m_yearly_completions": "Yearly Reading Campaign",
        "m_rapid_complete": "Rapid Intel Processing",
        "m_author_complete": "Hiroya Oku Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal GANTZ Reader",
        "m_mangaka_lover": "Hiroya Oku Devotee",
        "m_rereader": "Mission Tape Rereader",
        "m_triple_reread": "Triple Reread Expedition",
        "m_annual_reread": "Annual Hunt Reread",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Oku Art Devotee",
        "m_adaptation_compare": "Manga vs Anime Compare",
        "m_source_material_fan": "Source Material Scout",
        "m_waiting_weekly": "Weekly Chapter Signal Wait",
        "m_classic_reader": "Classic Manuscript Reader",
        "m_saga_reader": "GANTZ Saga Reader",
        "m_genre_loyalty": "Hunter Genre Loyalty",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "Light Novel Adaptation Intel",
        "m_original_work": "Original Manga Work",
        "m_long_commitment": "Long-Term Reading Commitment",
        "m_up_to_date": "Up-to-Date with the Hunt",
        "m_favorite_mangaka": "Favorite Mangaka Honored",
        "m_complete_portfolio": "Complete Reading Portfolio",
        "m_franchise_collector": "GANTZ Franchise Collector",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Mastery Earned",
        "m_multi_series_author": "Multi-Series Author Fan",
        "m_format_diversity": "Diverse Reading Formats",
        "m_year_dedication": "Year of Hunt Reading",
        "m_ongoing_follower": "Ongoing Series Follower",
        "m_genre_loyalty_50": "Fifty Genre Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Territory Scout",
        "m_publisher_hopper": "Publisher Faction Transfer",
        "m_tag_explorer": "Manga Tag Recon Mission",
        "m_decade_hopper": "Decade-Hopping via Sphere",
        "m_hidden_gem": "Hidden Alien Target",
        "m_popular_taste": "Popular Among Hunters",
        "m_retro_reader": "Retro Manuscript Appreciator",
        "m_modern_reader": "Modern Hunt Reader",
        "m_cross_demographic": "Cross-Demographic Scout",
        "m_underdog_fan": "Underdog Hunter Reader",
        "m_variety_week": "Week of Varied Readings",
        "m_manhwa_reader": "Manhwa Intel Reader",
        "m_manhua_reader": "Manhua Intel Reader",
        "m_classic_connoisseur": "Classic Hunt Manuscript",
        "m_award_winner": "Award-Winning Manuscript",
        "m_niche_explorer": "Niche Territory Reader",
        "m_world_manga": "World Manga Intel",
        "m_cult_classic": "Cult Classic GANTZ",
        "m_random_pick": "Random Reading Assignment",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Reading Completionist",
        "m_unpopular_opinion": "Unpopular Hunt Opinion",
        "m_top_rated_reader": "Top-Rated Intel Source",
        "m_source_variety": "Source Material Variety",
        "m_low_score_brave": "Brave Low-Score Reader",
        "m_short_manga_explorer": "Short Hunt Manga Explorer",
        "m_long_manga_explorer": "Long Campaign Manuscript",
        "m_serialization_explorer": "Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Sphere Reader",
        "m_early_bird": "Dawn Patrol Reader",
        "m_lunch_reader": "Pre-Mission Meal Reader",
        "m_commute_reader": "Travel to Sphere Reader",
        "m_four_am_club": "4 AM Sentry Reader",
        "m_new_year_read": "New Year's Reading Oath",
        "m_all_hours": "All-Hours Archive Access",
        "m_prime_time_reader": "Prime Time Manuscript",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Reading Marathon",
        "m_morning_routine": "Morning Formation Reading",
        "m_night_shift_reader": "Night Shift Sphere Read",
        "m_seasonal_premier_read": "New Release Intel",
        "m_clock_collector": "Zero Clock Reader",
        "m_late_night_horror": "Midnight Alien Horror Read",
        "m_afternoon_reader": "Afternoon Sphere Reading",
        "m_golden_hour_reader": "Golden Hour Reading",
        "m_dawn_reader": "Dawn Reading Scout",
        "m_twilight_reader": "Twilight Sphere Reading",
        "m_midnight_start": "Midnight Reading Mission",
        "m_weekend_binge_hours": "Weekend Binge Reading",
        "m_late_night_regular": "Late Night Regular Reader",
        "m_sunrise_reader": "Sunrise Over the Sphere",
        "m_every_day_of_week": "Every Day Reading Duty",
        "m_monthly_hours": "Monthly Reading Hours Logged",
        "m_bedtime_reader": "Bedtime Sphere Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Hiroya Oku Art Appreciator",
        "m_webtoon_reader": "Webtoon Intelligence",
        "m_full_color": "Full Color Manuscript",
        "m_doujin_reader": "Underground Doujin Reader",
        "m_anthology_reader": "Anthology Collection Reader",
        "m_adaptation_reader": "Adaptation Study Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Comedy Shorts",
        "m_oneshot_reader": "Oneshot Mission Reader",
        "m_format_variety": "Format Tactical Variety",
        "m_light_novel_reader": "Light Novel Intel Reader",
        "m_novel_reader": "Novel Archive Reader",
        "m_visual_storyteller": "Visual Battle Narrator",
        "m_colored_classic": "Colored Classic Manuscript",
        "m_webcomic_fan": "Webcomic Hunt Fan",
        "m_manga_to_anime": "Manga to Anime Comparison",
        "m_seinen_reader": "Seinen Hunt Reader",
        "m_josei_reader": "Josei Perspective Reader",
        "m_award_winning_art": "Medal-Winning Artwork",
        "m_debut_work": "Debut Manuscript",
        "m_vertical_scroll": "Vertical Scroll Intel",
        "m_traditional_format": "Traditional Format Reader",
        "m_cross_media": "Cross-Media Intelligence",
        "m_spinoff_reader": "Spinoff Mission Reader",
        "m_remake_reader": "Remake Reading Assignment",
        "m_collaboration_reader": "Joint Operation Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Reading Patrol Streak",
        "m_mega_streak": "Mega Reading Hunt Streak",
        "m_weekly_warrior": "Weekly Warrior Reader",
        "m_monthly_reader": "Monthly Sphere Reader",
        "m_comeback": "Reader's Return from Death",
        "m_weekend_streak": "Weekend Reading Streak",
        "m_no_zero_days": "No Zero Reading Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Regimen Formed",
        "m_consistent_pace": "Consistent Reading Advance",
        "m_year_long": "Year-Long Reading Campaign",
        "m_double_streak": "Double Reading Streak",
        "m_streak_recovery": "Reading Streak Recovery",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Reading Campaign",
        "m_summer_streak": "Summer Reading Offensive",
        "m_morning_streak": "Morning Reading Formation",
        "m_night_streak": "Night Hunt Reading",
        "m_unbreakable": "Unbreakable Reading Will",
        "m_eternal_flame": "Eternal GANTZ Knowledge",
        "m_chapter_a_day": "Chapter a Day Discipline",
        "m_genre_streak": "Genre Reading Streak",
        "m_completion_streak": "Completion Reading Chain",
        "m_rating_streak": "Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Hiroya Oku Dedication",
        "m_perfect_week_manga": "Perfect Reading Week",
        "m_diverse_streak": "Diverse Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "GANTZ Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Mission Manga",
        "m_harsh_critic": "Sphere's Harsh Standards",
        "m_fair_judge": "Kato's Fair Review",
        "m_generous_spirit": "Generous Hunter Spirit",
        "m_score_all": "Full Manuscript Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Reading Opinion",
        "m_consistent_scorer": "Consistent Manuscript Scorer",
        "m_score_sniper": "Precision Score Sniper",
        "m_evolving_taste": "Evolving Hunt Taste",
        "m_bell_curve": "Bell Curve of Scores",
        "m_picky_reader": "Selective Hunt Reader",
        "m_100_rated": "Century of Ratings Filed",
        "m_500_rated": "Five Hundred Rating Reports",
        "m_mediocre_majority": "Middle Ground Hunter",
        "m_rating_spree": "Rating Barrage Filed",
        "m_score_variance": "Variable Manuscript Scores",
        "m_binge_rater": "Binge Rating Session",
        "m_reread_rerate": "Reread and Re-Rate",
        "m_masterpiece_hunter": "Masterpiece Hunt Finder",
        "m_contrarian": "Contrarian Hunt Reader",
        "m_optimist": "Optimistic Hunter Reader",
        "m_score_distributor": "Score Distributor General",
        "m_genre_critic": "Genre Hunt Critic",
        "m_mean_above_8": "Elite Hunt Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Reading Vow",
        "m_valentines_read": "Valentine's Hunt Bond",
        "m_pi_day": "Pi Day Chapter Count",
        "m_april_fools": "April Fools Hunt Prank",
        "m_international_manga_day": "International Manga Day",
        "m_free_comic_day": "Free Comic Hunt Day",
        "m_summer_solstice": "Summer Solstice Hunt Read",
        "m_tanabata": "Tanabata Hunt Wish",
        "m_friday_13th": "Friday 13th Death Read",
        "m_halloween_read": "Halloween Alien Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Read Feast",
        "m_christmas_read": "Midwinter Mission Read",
        "m_new_years_eve": "New Year's Eve Final Read",
        "m_birthday_read": "Birthday Resurrection Read",
        "m_holiday_marathon": "Holiday Reading Marathon",
        "m_independence_day": "Hunter Independence Read",
        "m_culture_day": "Hunt Culture Day Read",
        "m_spring_equinox": "Spring Mission Reading",
        "m_earth_day": "Protect This World Read",
        "m_labor_day": "Garrison Labor Read",
        "m_winter_solstice": "Winter Solstice Hunt Read",
        "m_manga_birthday": "Manga Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Reader",
        "m_consecutive_holidays": "Consecutive Holiday Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Milestone",
        "m_fibonacci": "Fibonacci Mission Pattern",
        "m_palindrome_day": "Palindrome Reading Day",
        "m_binary_day": "Binary Signal Reading Day",
        "m_full_moon_read": "Full Moon Sphere Read",
        "m_leap_year_read": "Leap Year Reading",
        "m_triple_seven": "Triple Seven Point Chapters",
        "m_thousand_complete": "Thousand Manga Victories",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Black Suit Level Chapters",
        "m_answer_42": "Answer 42 Reading",
        "m_square_number": "Perfect Squad Chapters",
        "m_prime_count": "Prime Chapter Count",
        "m_matching_date": "Matching Intel Reading Date",
        "m_century_chapter": "Century Chapter Milestone",
        "m_pi_chapters": "Pi Mission Calculation",
        "m_synchronicity": "Sphere Reading Synchronicity",
        "m_world_record": "World Record Chapter Count",
        "m_genre_clash": "Genre Clash Hunt Read",
        "m_time_traveler": "Sphere Time-Traveling Reader",
        "m_double_digits": "Double Digit Milestone",
        "m_one_two_three": "Kurono Kato Sphere",
        "m_lucky_seven": "Seven Lucky Chapters",
        "m_exact_hundred_ch": "Exact Hundred Chapters",
        "m_year_match_count": "Year Match Chapter Count",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Manhwa Format Reader",
        "m_manhua_format": "Manhua Format Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Operative",
        "m_doujin_format": "Doujin Format Reader",
        "m_novel_format": "Novel Format Reader",
        "m_format_master_manga": "Format Master Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Suit Power Unlocked",
        "m_meta_collector": "GANTZ Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Reading Rank Promotion",
        "m_meta_tier_max": "Elite Hunter Rank",
        "m_meta_xp_earner": "XP from Hunt Points",
        "m_meta_difficulty_easy": "Easy Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Manuscript Challenge",
        "m_meta_unlock_spree": "Hunt Unlock Barrage",
        "m_meta_completionist": "Meta Reading Completionist",
        "m_meta_diverse": "Diverse Hunt Portfolio",
        "m_meta_dominator": "Meta Hunt Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020202",
        primary: "#333333",
        secondary: "#222222",
        accent: "#00cc44",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/gantz.jpg",
    particleColor: "#304050",
    backgroundDim: 0.35,
    backgroundBlur: 15,
    particleTypes: {
        gantz_data: { label: "GANTZ Data", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        suit_sparks: { label: "Suit Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        alien_fragments: { label: "Alien Fragments", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        mission_alerts: { label: "Mission Alerts", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1:   "Traffic Fatality",
        5:   "GANTZ Revived",
        15:  "Black Suit Rookie",
        30:  "Alien Hunter",
        45:  "100-Point Earner",
        60:  "Senior Hunter",
        80:  "Mission Veteran",
        100: "Free from GANTZ",
    },
}
