import { AnimeThemeConfig } from "./types"
import { GiSamuraiHelmet, GiAlienEgg, GiNoodles, GiBroadsword, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiWoodBeam } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const gintamaTheme: AnimeThemeConfig = {
    id: "gintama",
    displayName: "Gintama",
    description: "In an alternate Edo where aliens called Amanto have taken over feudal Japan, former samurai Gintoki Sakata works odd jobs with his freelancer agency Yorozuya, battling gravity-defying hair and weekly anime budget constraints.",
    fontFamily: "'M PLUS Rounded 1c', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "225 218 180",
        "--color-brand-300": "205 194 148",
        "--color-brand-400": "182 168 112",
        "--color-brand-500": "158 140 72",
        "--color-brand-600": "128 110 45",
        "--color-brand-700": "95 80 22",
        "--color-brand-800": "62 52 8",
        "--color-brand-900": "32 26 2",
        "--color-brand-950": "15 12 0",
        "--brand": "158 140 72",
        "--background": "#040402",
        "--paper": "#0c0b05",
        "--color-gray-950": "4 4 2",
        "--color-gray-900": "10 10 5",
        "--color-gray-800": "18 18 9",
        "--color-gray-700": "30 30 15",
        "--color-gray-600": "50 48 25",
        "--color-gray-500": "80 78 45",
        "--color-gray-400": "118 112 74",
        "--color-gray-300": "158 150 105",
        "--color-gray-200": "192 186 148",
        "--color-gray-100": "218 212 182",
        "--color-gray-50": "238 235 215",
    },
    sidebarOverrides: {
        "home": { icon: GiSamuraiHelmet, label: "Kabuki District" },
        "schedule": { icon: GiAlarmClock, label: "Odd Jobs Schedule" },
        "manga": { icon: LuBookOpen, label: "Jump Issues" },
        "lists": { icon: GiNoodles, label: "Job List" },
        "discover": { icon: GiBullseye, label: "New Clients" },
        "torrent-list": { icon: GiBroadsword, label: "Bokken Cache" },
        "debrid": { icon: GiAlienEgg, label: "Alien Market" },
        "unmatched": { icon: GiWoodBeam, label: "Lost Jobs" },
        "enmasse": { icon: GiResize, label: "Yorozuya Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Job Reports" },
        "auto-downloader": { icon: LuRss, label: "Weekly Jump Feed" },
        "community": { icon: GiSamuraiHelmet, label: "Yorozuya" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Odd Job Alerts" },
        "achievements": { icon: GiTrophy, label: "Gintoki's Trophies" },
        "milestones": { icon: LuFlag, label: "Odd Jobs Goals" },
        "theme-manager": { icon: GiPalette, label: "Silver Soul" },
        "extensions": { icon: BiExtension, label: "Alien Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Edo Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Gintoki's Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Odd Job",
        "a_first_complete": "Yorozuya Founded",
        "a_hundred_club": "Hundred Episodes",
        "a_time_lord": "Edo Veteran",
        "a_anime_collector": "Jump Collection",
        "a_library_legend": "Gintama Archives",
        "a_binge_king": "Episode Marathon",
        "a_no_sleep": "All-Night Comedy",
        "a_marathon_runner": "Gin-san's Run",
        "a_speed_run": "Kagura's Speed",
        "a_completionist": "All Arcs",
        "a_mega_completionist": "Sorachi Master",
        "a_loyal_fan": "Gintoki's Ally",
        "a_rewatcher": "Edo Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Yoshida Shouyou",
        "a_genre_adventure": "Rakuyo Rescue",
        "a_genre_comedy": "Bentendo Owee",
        "a_genre_drama": "Farewell Shinsengumi",
        "a_genre_fantasy": "Alien Edo",
        "a_genre_horror": "Four Devas",
        "a_genre_romance": "Gintoki Tsukuyo",
        "a_genre_scifi": "Alien Technology",
        "a_genre_supernatural": "Yoshiwara",
        "a_genre_psychological": "Gintoki's Past",
        "a_genre_mecha": "Gengai's Robots",
        "a_critic": "Jump Critic",
        "a_perfect_ten": "Silver Soul Perfect",
        "a_harsh_critic": "Sorachi Standard",
        "a_daily_streak": "Daily Odd Job",
        "a_mega_streak": "Endless Jobs",
        "a_year_long": "Year in Edo",
        "a_iron_will": "Gintoki's Steel",
        "a_hidden_gem": "Rare Episode",
        "a_cult_classic": "Gintama Classic",
        "a_classic_connoisseur": "2006 Fan",
        "a_new_years_resolution": "New Year Arc",
        "a_christmas_special": "Winter Special",
        "a_meta_tier_max": "Gintama Legend",
        "a_meta_completionist": "All Episodes",
        "a_sequel_chain": "Gintama: The Final",
        "a_zero_to_hero": "Failure to Legend",
        "a_night_owl": "Night Comedy",
        "a_early_bird": "Morning Jump",
        "m_first_chapter": "First Chapter",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Jump Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Gintama Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Edo Return",
        "m_genre_action": "Shogun Assassination",
        "m_genre_adventure": "Rakuyo Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Alien Chapter",
        "m_genre_horror": "Kintoki Chapter",
        "m_genre_drama": "Friendship Chapter",
        "m_genre_scifi": "Futuristic Edo",
        "m_genre_supernatural": "Soul Chapter",
        "m_genre_psychological": "Gintoki Depth",
        "m_critic": "Jump Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Gintama Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Gin-san Resolve",
        "m_hidden_gem": "Rare Chapter",
        "m_cult_classic": "Sorachi Classic",
        "m_mangaka_lover": "Sorachi Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Gintama Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Sorachi Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040402",
        primary: "#9e8c48",
        secondary: "#806e2d",
        accent: "#c04040",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/gintama.jpg",
    particleColor: "#c0b060",
    backgroundDim: 0.3,
    backgroundBlur: 16,
    particleTypes: {
        silver_dust: { label: "Silver Dust", maxCount: 16, defaultEnabled: true, defaultIntensity: 50 },
        bokken_sparks: { label: "Bokken Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1: "New Odd-Job Hire",
        5: "Gintoki Sakata",
        15: "Yorozuya Member",
        30: "Kabuki Regular",
        50: "Gin-san's Ally",
        75: "Silver Soul",
        100: "Edo Legend",
    },
}
