import { AnimeThemeConfig } from "./types"
import {
    GiFeather,
    GiRaven,
    GiBinoculars,
    GiAlarmClock,
    GiChainedHeart,
    GiTrophy,
    GiPalette,
    GiSettingsKnobs,
    GiAnvilImpact,
    GiResize,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuList, LuUsers } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const goodnightPunpunTheme: AnimeThemeConfig = {
    id: "goodnight-punpun",
    displayName: "Goodnight Punpun",
    description: "Oyasumi Punpun. A bird-boy grows up in silence and sorrow — existential dread, first love, and the god who never answers.",
    fontFamily: "'Noto Serif JP', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@300;400;600&display=swap",
    cssVars: {
        // Brand → muted slate-indigo, cold and distant
        "--color-brand-200": "185 196 212",
        "--color-brand-300": "148 160 180",
        "--color-brand-400": "112 125 148",
        "--color-brand-500": "74 88 112",
        "--color-brand-600": "54 67 88",
        "--color-brand-700": "40 50 68",
        "--color-brand-800": "28 35 52",
        "--color-brand-900": "17 22 36",
        "--color-brand-950": "9 12 22",
        "--brand": "74 88 112",
        // Near-void background, barely a hue
        "--background": "#050607",
        "--paper": "#0c0e12",
        "--color-gray-950": "5 6 7",
        "--color-gray-900": "12 14 18",
        "--color-gray-800": "22 26 34",
        "--color-gray-700": "36 42 54",
        "--color-gray-600": "58 65 82",
        "--color-gray-500": "86 94 115",
        "--color-gray-400": "122 130 150",
        "--color-gray-300": "158 165 182",
        "--color-gray-200": "192 197 210",
        "--color-gray-100": "220 223 232",
        "--color-gray-50": "240 242 247",
    },
    sidebarOverrides: {
        "home":            { icon: GiFeather,             label: "Punpun's World" },
        "schedule":        { icon: GiAlarmClock,          label: "Days Passing" },
        "manga":           { icon: LuBookOpen,            label: "Silent Pages" },
        "lists":           { icon: LuList,                label: "Memory Scroll" },
        "discover":        { icon: GiBinoculars,          label: "Lost in Mist" },
        "torrent-list":    { icon: GiAnvilImpact,         label: "Falling Papers" },
        "debrid":          { icon: GiChainedHeart,        label: "Broken Bonds" },
        "unmatched":       { icon: GiRaven,               label: "Lost Birds" },
        "enmasse":         { icon: GiResize,              label: "Grey Flock" },
        "scan-summaries":  { icon: TbReportSearch,        label: "Bird Reports" },
        "auto-downloader": { icon: LuRss,                 label: "Faint Signals" },
        "community":       { icon: LuUsers,               label: "God's Children" },
        "search":          { icon: FiSearch,              label: "Search" },
        "notifications":   { icon: LuBell,                label: "God Speaks" },
        "achievements":    { icon: GiTrophy,              label: "Punpun Earned" },
        "theme-manager":   { icon: GiPalette,             label: "Paper Tones" },
        "extensions":      { icon: BiExtension,           label: "Feather Wings" },
        "sync":            { icon: IoCloudOfflineOutline, label: "Fading Echo" },
        "settings":        { icon: GiSettingsKnobs,       label: "Life Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode":          "First Flutter",
        "a_episode_counter":        "Daily Ache",
        "a_episode_titan":          "Giant Sorrow",
        "a_hours_invested":         "Hollow Hours",
        "a_time_lord":              "God's Time",
        "a_anime_collector":        "Bird Hoard",
        "a_library_legend":         "Aiko's Library",
        "a_first_complete":         "Complete Nothing",
        "a_hundred_club":           "Hundred Days",
        "a_first_day":              "Day One",
        "a_first_rating":           "Judged Again",
        "a_ten_thousand_min":       "Ten Thousand Aches",
        "a_season_veteran":         "Surviving Seasons",
        "a_year_explorer":          "Lost Year",
        "a_century_watcher":        "Hundred Watched",
        "a_five_hundred_eps":       "Five Hundred Cries",
        "a_thousand_eps":           "Thousand Sorrows",
        "a_watching_ten":           "Fragmented Mind",
        "a_ptw_hoarder":            "Unfulfilled Plans",
        "a_dropped_honesty":        "Gave Up Again",
        "a_five_thousand_eps":      "Five Thousand Tears",
        "a_ten_completed":          "Ten Complete",
        "a_fifty_completed":        "Fifty Farewells",
        "a_five_hundred_completed": "Five Hundred Ends",
        "a_mean_score_tracker":     "Hollow Rating",
        "a_unique_studios":         "Many Voices",
        "a_days_spent_watching":    "Days Forgotten",
        "a_all_status":             "All Emotions",
        "a_first_favorite":         "First Love",
        "a_favorites_collector":    "Loves Lost",

        // ── ANIME BINGE ──
        "a_binge_watcher":      "Endless Watching",
        "a_marathon_runner":    "Running Nowhere",
        "a_weekend_warrior":    "Weekend Alone",
        "a_non_stop":           "Can't Stop",
        "a_one_more_episode":   "One More Night",
        "a_speed_run":          "Running Away",
        "a_double_feature":     "Double Grief",
        "a_triple_threat":      "Triple Void",
        "a_five_a_day":         "Five Each Day",
        "a_back_to_back":       "Back to Back",
        "a_seasonal_binge":     "Season of Pain",
        "a_cour_crusher":       "Crushed Again",
        "a_half_day_watch":     "Half a Day",
        "a_full_day_watch":     "Full Day Gone",
        "a_power_weekend":      "Powerless Weekend",
        "a_binge_king":         "King of Nothing",
        "a_no_sleep":           "Sleepless Punpun",
        "a_entire_season":      "Season Complete",
        "a_seven_day_challenge":"Seven Dark Days",
        "a_hundred_day_binge":  "Hundred Hollow Days",
        "a_genre_binge":        "All Genres Hurt",
        "a_studio_binge":       "Studio Devotion",
        "a_season_sweep":       "Season Swept",
        "a_forty_eight_hour":   "Forty-Eight Hours",
        "a_ep_counter_day":     "Daily Episodes",
        "a_multi_series_binge": "Many Stories",
        "a_midnight_binge":     "Midnight Bird",
        "a_new_year_binge":     "New Year Bird",

        // ── ANIME GENRES ──
        "a_genre_action":       "Fighting Bird",
        "a_genre_adventure":    "Bird Wanders",
        "a_genre_comedy":       "Fake Smiles",
        "a_genre_drama":        "Pure Drama",
        "a_genre_fantasy":      "God's World",
        "a_genre_horror":       "Inner Terror",
        "a_genre_mystery":      "Aiko's Secret",
        "a_genre_romance":      "First Love Pain",
        "a_genre_scifi":        "Strange World",
        "a_genre_sol":          "Ordinary Days",
        "a_genre_sports":       "Childhood Games",
        "a_genre_supernatural": "God Appears",
        "a_genre_thriller":     "Dread Lives",
        "a_genre_mecha":        "Metal Cage",
        "a_genre_music":        "Punpun's Song",
        "a_genre_psychological":"Broken Mind",
        "a_genre_ecchi":        "Awkward Moments",
        "a_genre_mahou_shoujo": "Wish Denied",
        "a_tag_isekai":         "New World Bird",
        "a_tag_harem":          "Loved by Few",
        "a_tag_bl":             "Friends Only",
        "a_tag_gl":             "Girls' Bond",
        "a_tag_historical":     "Past Wounds",
        "a_tag_military":       "No Escape",
        "a_tag_school":         "School Days",
        "a_tag_martial_arts":   "No Fighting",
        "a_tag_vampire":        "Bloodless Hurt",
        "a_tag_samurai":        "No Honor",
        "a_tag_space":          "Cosmic Void",
        "a_tag_parody":         "Mock Life",
        "a_tag_idol":           "False Light",
        "a_tag_post_apocalyptic":"After Everything",
        "a_tag_cyberpunk":      "Digital Grief",
        "a_tag_shounen":        "Young Punpun",
        "a_tag_seinen":         "Grown Punpun",
        "a_tag_shoujo":         "Aiko's Heart",
        "a_tag_josei":          "Harumi's View",
        "a_tag_survival":       "Just Surviving",

        // ── ANIME COMPLETION ──
        "a_completionist":          "Bird Complete",
        "a_mega_completionist":     "Punpun Completes",
        "a_completion_rate_50":     "Halfway There",
        "a_completion_rate_75":     "Almost Gone",
        "a_completion_rate_90":     "Nearly Done",
        "a_no_drop":                "No Giving Up",
        "a_long_runner_complete":   "Long Journey End",
        "a_sequel_chain":           "Chain of Pain",
        "a_clean_list":             "Clean Slate",
        "a_from_ptw":               "Finally Watched",
        "a_rewatch_master":         "Seen It Again",
        "a_short_complete":         "Short Goodbye",
        "a_same_day_start_finish":  "One Day Story",
        "a_revival":                "Bird Revived",
        "a_zero_to_hero":           "Punpun Grows",
        "a_five_genre_complete":    "Five Genre Tears",
        "a_full_franchise":         "All Stories",
        "a_batch_complete":         "Batch Done",
        "a_paused_to_done":         "Finally Done",
        "a_completion_spree":       "Completion Spree",
        "a_multi_rewatch":          "Watched Again",
        "a_dropped_recovery":       "Picked Up Again",
        "a_ten_perfect_scores":     "Perfect Ten Times",
        "a_seasonal_clear":         "Season Cleared",
        "a_complete_genre_span":    "All Genres",
        "a_monthly_completions":    "Monthly Grief",
        "a_yearly_completions":     "Yearly Farewells",
        "a_rapid_complete":         "Quick Goodbye",

        // ── ANIME DEDICATION ──
        "a_loyal_fan":          "Loyal Bird",
        "a_studio_devotee":     "Studio Devotee",
        "a_rewatcher":          "Watched Twice",
        "a_triple_rewatch":     "Three Times Hurt",
        "a_annual_tradition":   "Annual Grief",
        "a_director_fan":       "Inio's Vision",
        "a_voice_actor_fan":    "Bird's Voice",
        "a_ost_lover":          "Sad Melodies",
        "a_source_reader":      "Inio's Work",
        "a_waiting_weekly":     "Waiting for God",
        "a_childhood_revisit":  "Childhood Ghosts",
        "a_saga_tracker":       "Saga Tracked",
        "a_genre_loyalty":      "Genre Faithful",
        "a_decade_watcher":     "Decade Long",
        "a_adaptation_hunter":  "All Versions",
        "a_original_anime_fan": "Original Broadcast",
        "a_long_commitment":    "Long Devotion",
        "a_perfect_attendance": "Always There",
        "a_favorite_studio_5":  "Five Studios",
        "a_complete_catalog":   "Catalog Done",
        "a_franchise_collector":"All Parts",
        "a_airing_follower":    "Following Along",
        "a_genre_master":       "Genre Master",
        "a_staff_follower":     "Staff Devotee",
        "a_multi_season_fan":   "Many Seasons",
        "a_format_diversity":   "Every Format",
        "a_year_dedication":    "Year Dedicated",
        "a_season_dedication":  "Season Devoted",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer":         "Exploring Pain",
        "a_studio_hopper":          "Studio Hopper",
        "a_tag_explorer":           "Tag Wanderer",
        "a_decade_hopper":          "Time Hopper",
        "a_hidden_gem":             "Hidden Bird",
        "a_popular_taste":          "Popular Choice",
        "a_retro_appreciator":      "Retro Memory",
        "a_modern_viewer":          "Modern Times",
        "a_cross_demographic":      "All Demographics",
        "a_underdog_fan":           "Underdog Fan",
        "a_variety_week":           "Varied Week",
        "a_foreign_cinema":         "Foreign Films",
        "a_classic_connoisseur":    "Classic Lover",
        "a_every_season":           "Every Season",
        "a_award_winner":           "Award Found",
        "a_niche_explorer":         "Niche Explorer",
        "a_global_anime":           "Global View",
        "a_cult_classic":           "Cult Classic",
        "a_random_pick":            "Random Choice",
        "a_new_genre_month":        "New Genre Month",
        "a_seasonal_completionist": "Season Complete",
        "a_unpopular_opinion":      "Alone Opinion",
        "a_top_rated_viewer":       "Top Rated",
        "a_source_variety":         "Source Variety",
        "a_low_score_brave":        "Brave Watcher",
        "a_upcoming_watcher":       "Upcoming Shows",
        "a_short_series_explorer":  "Short Journeys",
        "a_long_series_explorer":   "Long Journey",

        // ── ANIME TIME ──
        "a_night_owl":          "Night Bird",
        "a_early_bird":         "Dawn Bird",
        "a_lunch_break":        "Midday Break",
        "a_golden_hour":        "Golden Fade",
        "a_four_am_club":       "4 AM Punpun",
        "a_witching_hour":      "Witching Hour",
        "a_new_year_watch":     "New Year Bird",
        "a_midnight_premiere":  "Midnight Start",
        "a_all_hours":          "All Hours",
        "a_dawn_warrior":       "Dawn Watch",
        "a_afternoon_delight":  "Afternoon Light",
        "a_prime_time":         "Prime Time",
        "a_workday_watcher":    "Work Hours",
        "a_sunday_marathon":    "Sunday Grief",
        "a_rainy_day":          "Rainy Day",
        "a_morning_routine":    "Morning Bird",
        "a_night_shift":        "Night Watch",
        "a_twilight_zone":      "Twilight Zone",
        "a_seasonal_premier":   "Season Premiere",
        "a_clock_collector":    "Clock Watcher",
        "a_weekend_binge_hours":"Weekend Hours",
        "a_late_night_regular": "Late Night",
        "a_sunrise_watcher":    "Sunrise View",
        "a_holiday_watcher":    "Holiday Bird",
        "a_every_day_of_week":  "Every Day",
        "a_monthly_hours":      "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party":            "First Gathering",
        "a_party_host":             "Party Host",
        "a_social_butterfly":       "Social Punpun",
        "a_group_binge":            "Group Grief",
        "a_party_regular":          "Regular Party",
        "a_sync_viewer":            "Synced Pain",
        "a_commentator":            "Voice of Grief",
        "a_party_marathon":         "Marathon Party",
        "a_full_house":             "Full Group",
        "a_community_pillar":       "Community Pillar",
        "a_watch_party_streak":     "Party Streak",
        "a_diverse_party":          "Diverse Group",
        "a_late_night_party":       "Late Night Party",
        "a_party_veteran":          "Party Veteran",
        "a_genre_party":            "Genre Party",
        "a_weekly_party":           "Weekly Group",
        "a_silent_viewer":          "Silent Punpun",
        "a_recommendation_giver":   "Bird Recommends",
        "a_party_completionist":    "Party Complete",
        "a_social_scorer":          "Social Score",

        // ── ANIME SPECIAL ──
        "a_round_number":       "Round Number",
        "a_fibonacci":          "Fibonacci Bird",
        "a_palindrome_day":     "Palindrome Day",
        "a_binary_day":         "Binary Bird",
        "a_full_moon":          "Full Moon God",
        "a_leap_year":          "Leap Year",
        "a_time_traveler":      "Time Bends",
        "a_genre_clash":        "Genre Clash",
        "a_triple_seven":       "Triple Seven",
        "a_thousand_complete":  "Thousand Done",
        "a_pi_episodes":        "Pi Punpun",
        "a_synchronicity":      "Synchronicity",
        "a_world_record":       "World Record",
        "a_nice":               "Nice One",
        "a_power_level":        "Power Level",
        "a_answer_42":          "Answer Found",
        "a_square_number":      "Perfect Square",
        "a_prime_count":        "Prime Count",
        "a_matching_date":      "Date Match",
        "a_century_episode":    "Century Episodes",
        "a_double_digits":      "Double Digits",
        "a_one_two_three":      "One Two Three",
        "a_lucky_seven":        "Lucky Seven",
        "a_all_tens":           "All Tens",
        "a_exact_hundred_eps":  "Exact Hundred",
        "a_year_match_count":   "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher":       "TV Punpun",
        "a_movie_buff":       "Bird Cinema",
        "a_ova_hunter":       "OVA Hunter",
        "a_ona_explorer":     "ONA Explorer",
        "a_special_watcher":  "Special Bird",
        "a_short_king":       "Short Bird",
        "a_variety_pack":     "All Formats",
        "a_film_festival":    "Film Festival",
        "a_music_video":      "Music Video",
        "a_tv_short":         "TV Short",
        "a_movie_marathon":   "Movie Marathon",
        "a_double_length":    "Double Length",
        "a_anthology":        "Anthology",
        "a_mini_series":      "Mini Series",
        "a_theatrical":       "Theatrical",
        "a_format_master":    "Format Master",
        "a_long_movie":       "Long Film",
        "a_back_catalog":     "Back Catalog",
        "a_cm_watcher":       "CM Watcher",
        "a_pv_collector":     "PV Collector",
        "a_format_balance":   "Balanced Formats",
        "a_episodic_master":  "Episodic Master",
        "a_sequel_movie":     "Sequel Film",
        "a_recap_watcher":    "Recap Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak":       "Daily Grief",
        "a_mega_streak":        "Mega Streak",
        "a_weekly_warrior":     "Weekly Warrior",
        "a_monthly_watcher":    "Monthly Watch",
        "a_comeback":           "Bird Returns",
        "a_weekend_streak":     "Weekend Streak",
        "a_no_zero_days":       "No Zero Days",
        "a_iron_will":          "Iron Will",
        "a_habit_formed":       "Habit Formed",
        "a_consistent_pace":    "Steady Pace",
        "a_year_long":          "Year Long",
        "a_double_streak":      "Double Streak",
        "a_streak_recovery":    "Streak Recovered",
        "a_daily_minimum":      "Daily Minimum",
        "a_winter_streak":      "Winter Bird",
        "a_summer_streak":      "Summer Bird",
        "a_morning_streak":     "Morning Streak",
        "a_night_streak":       "Night Streak",
        "a_unbreakable":        "Unbreakable Bird",
        "a_eternal_flame":      "Eternal Flame",
        "a_completion_streak":  "Completion Chain",
        "a_rating_streak":      "Rating Streak",
        "a_multi_ep_streak":    "Multi-Episode Streak",
        "a_genre_streak":       "Genre Streak",
        "a_studio_streak":      "Studio Streak",
        "a_perfect_week":       "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic":             "Punpun Judges",
        "a_perfect_ten":        "Perfect Ten",
        "a_harsh_critic":       "God Judges",
        "a_fair_judge":         "Fair Judgment",
        "a_generous_spirit":    "Kind Punpun",
        "a_score_all":          "All Scored",
        "a_wide_range":         "Wide Range",
        "a_controversial":      "Divisive Score",
        "a_consistent_scorer":  "Steady Judge",
        "a_score_sniper":       "Precise Judge",
        "a_evolving_taste":     "Taste Changes",
        "a_bell_curve":         "Bell Curve",
        "a_picky_watcher":      "Picky Bird",
        "a_100_rated":          "Hundred Rated",
        "a_500_rated":          "Five Hundred Rated",
        "a_mediocre_majority":  "Middle Ground",
        "a_rating_spree":       "Rating Spree",
        "a_score_variance":     "Varied Scores",
        "a_masterpiece_hunter": "Masterpiece Found",
        "a_contrarian":         "Against Tide",
        "a_optimist":           "Still Hopeful",
        "a_score_distributor":  "Score Spread",
        "a_genre_critic":       "Genre Critic",
        "a_mean_above_8":       "Above Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution":   "New Year Vow",
        "a_valentines_weeb":        "Valentine Bird",
        "a_pi_day":                 "Pi Day Bird",
        "a_april_fools":            "God's Prank",
        "a_international_anime_day":"Anime Day",
        "a_star_wars_day":          "Star Wars Day",
        "a_summer_solstice":        "Summer Solstice",
        "a_tanabata":               "Tanabata Wish",
        "a_friday_13th":            "Unlucky Bird",
        "a_halloween_spirit":       "Halloween Bird",
        "a_thanksgiving_binge":     "Thanksgiving Bird",
        "a_christmas_special":      "Christmas Grief",
        "a_new_years_eve":          "Year's End",
        "a_birthday_watch":         "Birthday Bird",
        "a_holiday_marathon":       "Holiday Marathon",
        "a_independence_day":       "Free Bird Day",
        "a_culture_day":            "Culture Day",
        "a_spring_equinox":         "Spring Bird",
        "a_earth_day":              "Earth Day Bird",
        "a_labor_day":              "Labor Day Bird",
        "a_winter_solstice":        "Winter Solstice",
        "a_anime_birthday":         "Anime Birthday",
        "a_every_holiday":          "All Holidays",
        "a_consecutive_holidays":   "Holiday Streak",

        // ── ANIME META ──
        "a_meta_first_unlock":      "First Awakening",
        "a_meta_collector":         "Badge Collector",
        "a_meta_category_starter":  "Category Start",
        "a_meta_tier_climber":      "Tier Climber",
        "a_meta_tier_max":          "Max Tier",
        "a_meta_xp_earner":         "XP Earned",
        "a_meta_difficulty_easy":   "Easy Mode",
        "a_meta_difficulty_hard":   "God Mode",
        "a_meta_unlock_spree":      "Unlock Spree",
        "a_meta_completionist":     "Meta Complete",
        "a_meta_diverse":           "Diverse Meta",
        "a_meta_dominator":         "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter":          "First Page",
        "m_chapter_counter":        "Chapter Count",
        "m_chapter_titan":          "Chapter Giant",
        "m_reading_hours":          "Reading Hours",
        "m_reading_time_lord":      "God's Pages",
        "m_manga_collector":        "Manga Hoard",
        "m_library_legend":         "Library Legend",
        "m_first_complete":         "First Complete",
        "m_hundred_club":           "Hundred Read",
        "m_first_day":              "First Reading Day",
        "m_first_rating":           "First Rating",
        "m_ten_thousand_pages":     "Ten Thousand Pages",
        "m_volume_collector":       "Volume Hoard",
        "m_year_explorer":          "Year Reading",
        "m_century_reader":         "Century Reader",
        "m_five_hundred_ch":        "Five Hundred Chapters",
        "m_thousand_ch":            "Thousand Chapters",
        "m_reading_ten":            "Ten at Once",
        "m_ptr_hoarder":            "Backlog Hoarder",
        "m_dropped_honesty":        "Honest Drop",
        "m_season_reader":          "Season Reader",
        "m_active_reader":          "Active Reader",
        "m_five_thousand_ch":       "Five Thousand Chapters",
        "m_ten_completed":          "Ten Manga Done",
        "m_fifty_completed":        "Fifty Manga Done",
        "m_five_hundred_completed": "Five Hundred Manga",
        "m_mean_score_tracker":     "Average Score",
        "m_unique_authors":         "Many Authors",
        "m_all_status":             "All Statuses",
        "m_first_favorite":         "First Favorite",
        "m_favorites_collector":    "Favorites Kept",
        "m_days_spent_reading":     "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader":       "Binge Reader",
        "m_marathon_reader":    "Marathon Reader",
        "m_weekend_reader":     "Weekend Reading",
        "m_non_stop_reading":   "Non-Stop Pages",
        "m_one_more_chapter":   "One More Chapter",
        "m_speed_read":         "Speed Reader",
        "m_double_story":       "Double Story",
        "m_triple_read":        "Triple Read",
        "m_five_a_day":         "Five Chapters Daily",
        "m_chapter_chain":      "Chapter Chain",
        "m_volume_binge":       "Volume Binge",
        "m_power_reader":       "Power Reader",
        "m_half_day_read":      "Half Day Read",
        "m_full_day_read":      "Full Day Read",
        "m_power_weekend":      "Power Weekend",
        "m_binge_king":         "Binge King",
        "m_no_sleep_read":      "No Sleep Read",
        "m_full_series_rush":   "Series Rush",
        "m_seven_day_challenge":"Seven Day Read",
        "m_hundred_day_read":   "Hundred Day Read",
        "m_volume_rush":        "Volume Rush",
        "m_series_sweep":       "Series Sweep",
        "m_genre_binge":        "Genre Binge",
        "m_author_binge":       "Author Binge",
        "m_chapter_counter_day":"Daily Chapters",
        "m_multi_series_binge": "Multi-Series Read",
        "m_midnight_binge":     "Midnight Read",
        "m_new_year_binge":     "New Year Pages",
        "m_forty_eight_hour":   "Forty-Eight Hours",
        "m_oneshot_binge":      "Oneshot Binge",

        // ── MANGA GENRES ──
        "m_genre_action":       "Action Pages",
        "m_genre_adventure":    "Adventure Pages",
        "m_genre_comedy":       "Comedy Pages",
        "m_genre_drama":        "Drama Pages",
        "m_genre_fantasy":      "Fantasy World",
        "m_genre_horror":       "Horror Pages",
        "m_genre_mystery":      "Mystery Pages",
        "m_genre_romance":      "Romance Pages",
        "m_genre_scifi":        "Sci-Fi Pages",
        "m_genre_sol":          "Daily Life Pages",
        "m_genre_sports":       "Sports Pages",
        "m_genre_supernatural": "Supernatural Pages",
        "m_genre_thriller":     "Thriller Pages",
        "m_genre_psychological":"Mind Pages",
        "m_genre_isekai":       "Isekai Pages",
        "m_genre_shounen":      "Shounen Pages",
        "m_genre_ecchi":        "Awkward Pages",
        "m_genre_mahou_shoujo": "Magic Girl Pages",
        "m_genre_mecha":        "Mecha Pages",
        "m_genre_music":        "Music Pages",
        "m_tag_isekai_new":     "New World Pages",
        "m_tag_harem":          "Many Loves",
        "m_tag_bl":             "Male Bonds",
        "m_tag_gl":             "Female Bonds",
        "m_tag_historical":     "History Pages",
        "m_tag_military":       "War Pages",
        "m_tag_school":         "School Pages",
        "m_tag_martial_arts":   "Fighting Pages",
        "m_tag_vampire":        "Vampire Pages",
        "m_tag_samurai":        "Samurai Pages",
        "m_tag_space":          "Space Pages",
        "m_tag_parody":         "Parody Pages",
        "m_tag_idol":           "Idol Pages",
        "m_tag_post_apocalyptic":"After World",
        "m_tag_cyberpunk":      "Cyber Pages",
        "m_tag_shoujo":         "Shoujo Pages",
        "m_tag_survival":       "Survival Pages",
        "m_tag_cooking":        "Cooking Pages",
        "m_tag_medical":        "Medical Pages",
        "m_tag_villainess":     "Villainess Pages",

        // ── MANGA COMPLETION ──
        "m_completionist":          "Manga Complete",
        "m_mega_completionist":     "Super Complete",
        "m_completion_rate_50":     "Half Done",
        "m_completion_rate_75":     "Mostly Done",
        "m_completion_rate_90":     "Almost Done",
        "m_no_drop":                "Never Dropped",
        "m_long_runner_complete":   "Long Series Done",
        "m_sequel_chain":           "Sequel Chain",
        "m_clean_list":             "Clean Record",
        "m_from_ptr":               "Finally Read",
        "m_reread_master":          "Reread Master",
        "m_oneshot_complete":       "Oneshots Done",
        "m_same_day_start_finish":  "One Day Read",
        "m_revival":                "Reader Revived",
        "m_zero_to_hundred":        "Cadet Scholar",
        "m_five_genre_complete":    "Five Genres Done",
        "m_full_collection":        "Full Collection",
        "m_batch_complete":         "Batch Complete",
        "m_paused_to_done":         "Finally Finished",
        "m_completion_spree":       "Spree Complete",
        "m_format_completionist":   "Format Complete",
        "m_catch_up":               "Caught Up",
        "m_multi_reread":           "Multi Reread",
        "m_dropped_recovery":       "Recovered Reader",
        "m_ten_perfect_scores":     "Ten Perfects",
        "m_complete_genre_span":    "All Genres Read",
        "m_monthly_completions":    "Monthly Complete",
        "m_yearly_completions":     "Yearly Complete",
        "m_rapid_complete":         "Rapid Read",
        "m_author_complete":        "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader":           "Loyal Reader",
        "m_mangaka_lover":          "Punpun's Creator",
        "m_rereader":               "Rereader",
        "m_triple_reread":          "Three Rereads",
        "m_annual_reread":          "Annual Reread",
        "m_publisher_fan":          "Publisher Fan",
        "m_artist_fan":             "Artist Fan",
        "m_adaptation_compare":     "Compare Sources",
        "m_source_material_fan":    "Source Fan",
        "m_waiting_weekly":         "Weekly Wait",
        "m_classic_reader":         "Classic Reader",
        "m_saga_reader":            "Saga Reader",
        "m_genre_loyalty":          "Genre Loyal",
        "m_decade_reader":          "Decade Reader",
        "m_ln_adaptation":          "Novel Adapted",
        "m_original_work":          "Original Work",
        "m_long_commitment":        "Long Commitment",
        "m_up_to_date":             "Up to Date",
        "m_favorite_mangaka":       "Favorite Creator",
        "m_complete_portfolio":     "Complete Portfolio",
        "m_franchise_collector":    "Franchise Kept",
        "m_serialization_follower": "Follows Series",
        "m_genre_master":           "Genre Master",
        "m_multi_series_author":    "Multi-Series Author",
        "m_format_diversity":       "Format Diversity",
        "m_year_dedication":        "Year Devoted",
        "m_ongoing_follower":       "Ongoing Follower",
        "m_genre_loyalty_50":       "Fifty Genre Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer":         "Genre Explorer",
        "m_publisher_hopper":       "Publisher Hopper",
        "m_tag_explorer":           "Tag Explorer",
        "m_decade_hopper":          "Decade Hopper",
        "m_hidden_gem":             "Hidden Gem",
        "m_popular_taste":          "Popular Taste",
        "m_retro_reader":           "Retro Reader",
        "m_modern_reader":          "Modern Reader",
        "m_cross_demographic":      "Cross Demo",
        "m_underdog_fan":           "Underdog Fan",
        "m_variety_week":           "Varied Week",
        "m_manhwa_reader":          "Manhwa Read",
        "m_manhua_reader":          "Manhua Read",
        "m_classic_connoisseur":    "Classic Connoisseur",
        "m_award_winner":           "Award Winner",
        "m_niche_explorer":         "Niche Explorer",
        "m_world_manga":            "World Manga",
        "m_cult_classic":           "Cult Classic",
        "m_random_pick":            "Random Pick",
        "m_new_genre_month":        "New Genre Month",
        "m_year_completionist":     "Year Complete",
        "m_unpopular_opinion":      "Alone Opinion",
        "m_top_rated_reader":       "Top Rated",
        "m_source_variety":         "Source Variety",
        "m_low_score_brave":        "Brave Reader",
        "m_short_manga_explorer":   "Short Manga",
        "m_long_manga_explorer":    "Long Manga",
        "m_serialization_explorer": "Series Explorer",

        // ── MANGA TIME ──
        "m_night_owl":              "Night Reader",
        "m_early_bird":             "Dawn Reader",
        "m_lunch_reader":           "Lunch Reader",
        "m_commute_reader":         "Commute Read",
        "m_four_am_club":           "4 AM Reader",
        "m_new_year_read":          "New Year Read",
        "m_all_hours":              "All Hours Read",
        "m_prime_time_reader":      "Prime Time Read",
        "m_workday_reader":         "Work Read",
        "m_sunday_read":            "Sunday Read",
        "m_morning_routine":        "Morning Read",
        "m_night_shift_reader":     "Night Shift Read",
        "m_seasonal_premier_read":  "New Release Read",
        "m_clock_collector":        "Clock Collector",
        "m_late_night_horror":      "Midnight Horror",
        "m_afternoon_reader":       "Afternoon Read",
        "m_golden_hour_reader":     "Golden Hour Read",
        "m_dawn_reader":            "Dawn Reading",
        "m_twilight_reader":        "Twilight Read",
        "m_midnight_start":         "Midnight Start",
        "m_weekend_binge_hours":    "Weekend Hours",
        "m_late_night_regular":     "Late Night Regular",
        "m_sunrise_reader":         "Sunrise Read",
        "m_every_day_of_week":      "Every Day Read",
        "m_monthly_hours":          "Monthly Hours",
        "m_bedtime_reader":         "Bedtime Read",

        // ── MANGA CREATIVE ──
        "m_art_appreciator":        "Art Appreciator",
        "m_webtoon_reader":         "Webtoon Read",
        "m_full_color":             "Full Color",
        "m_doujin_reader":          "Doujin Read",
        "m_anthology_reader":       "Anthology Read",
        "m_adaptation_reader":      "Adaptation Read",
        "m_longstrip_reader":       "Long Strip",
        "m_4koma_reader":           "Four Koma",
        "m_oneshot_reader":         "Oneshot Read",
        "m_format_variety":         "Format Variety",
        "m_light_novel_reader":     "Light Novel",
        "m_novel_reader":           "Novel Read",
        "m_visual_storyteller":     "Visual Story",
        "m_colored_classic":        "Colored Classic",
        "m_webcomic_fan":           "Webcomic Fan",
        "m_manga_to_anime":         "Manga to Anime",
        "m_seinen_reader":          "Seinen Read",
        "m_josei_reader":           "Josei Read",
        "m_award_winning_art":      "Award Art",
        "m_debut_work":             "Debut Work",
        "m_vertical_scroll":        "Vertical Scroll",
        "m_traditional_format":     "Traditional Format",
        "m_cross_media":            "Cross Media",
        "m_spinoff_reader":         "Spinoff Read",
        "m_remake_reader":          "Remake Read",
        "m_collaboration_reader":   "Collab Read",

        // ── MANGA STREAKS ──
        "m_daily_streak":       "Daily Reading",
        "m_mega_streak":        "Mega Reading Streak",
        "m_weekly_warrior":     "Weekly Reader",
        "m_monthly_reader":     "Monthly Reader",
        "m_comeback":           "Reading Returns",
        "m_weekend_streak":     "Weekend Reading",
        "m_no_zero_days":       "No Zero Days",
        "m_iron_will":          "Iron Reader",
        "m_habit_formed":       "Reading Habit",
        "m_consistent_pace":    "Steady Reading",
        "m_year_long":          "Year Reading",
        "m_double_streak":      "Double Reading Streak",
        "m_streak_recovery":    "Streak Recovery",
        "m_daily_minimum":      "Daily Pages",
        "m_winter_streak":      "Winter Reading",
        "m_summer_streak":      "Summer Reading",
        "m_morning_streak":     "Morning Read Streak",
        "m_night_streak":       "Night Read Streak",
        "m_unbreakable":        "Unbreakable",
        "m_eternal_flame":      "Eternal Flame",
        "m_chapter_a_day":      "Chapter Daily",
        "m_genre_streak":       "Genre Reading Streak",
        "m_completion_streak":  "Completion Streak",
        "m_rating_streak":      "Rating Streak",
        "m_multi_ch_streak":    "Multi-Chapter Streak",
        "m_author_streak":      "Author Reading Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak":     "Diverse Reading",

        // ── MANGA SCORING ──
        "m_critic":             "Manga Critic",
        "m_perfect_ten":        "Perfect Score",
        "m_harsh_critic":       "Harsh Critic",
        "m_fair_judge":         "Fair Judge",
        "m_generous_spirit":    "Generous Spirit",
        "m_score_all":          "All Scored",
        "m_wide_range":         "Wide Range",
        "m_controversial":      "Controversial",
        "m_consistent_scorer":  "Consistent Scorer",
        "m_score_sniper":       "Score Sniper",
        "m_evolving_taste":     "Evolving Taste",
        "m_bell_curve":         "Bell Curve",
        "m_picky_reader":       "Picky Reader",
        "m_100_rated":          "Hundred Rated",
        "m_500_rated":          "Five Hundred Rated",
        "m_mediocre_majority":  "Middle Ground",
        "m_rating_spree":       "Rating Spree",
        "m_score_variance":     "Score Variance",
        "m_binge_rater":        "Binge Rater",
        "m_reread_rerate":      "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Found",
        "m_contrarian":         "Contrarian",
        "m_optimist":           "Optimist Reader",
        "m_score_distributor":  "Score Distributor",
        "m_genre_critic":       "Genre Critic",
        "m_mean_above_8":       "Above Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution":   "Year's Promise",
        "m_valentines_read":        "Valentine Read",
        "m_pi_day":                 "Pi Day Read",
        "m_april_fools":            "April Fools Read",
        "m_international_manga_day":"Manga Day",
        "m_free_comic_day":         "Free Comic Day",
        "m_summer_solstice":        "Summer Reading",
        "m_tanabata":               "Tanabata Read",
        "m_friday_13th":            "Unlucky Read",
        "m_halloween_read":         "Halloween Read",
        "m_thanksgiving_binge":     "Thankful Read",
        "m_christmas_read":         "Christmas Read",
        "m_new_years_eve":          "Year End Read",
        "m_birthday_read":          "Birthday Read",
        "m_holiday_marathon":       "Holiday Read Marathon",
        "m_independence_day":       "Freedom Day",
        "m_culture_day":            "Culture Read",
        "m_spring_equinox":         "Spring Read",
        "m_earth_day":              "Earth Day Read",
        "m_labor_day":              "Labor Read",
        "m_winter_solstice":        "Winter Read",
        "m_manga_birthday":         "Manga Birthday",
        "m_every_holiday_reader":   "Holiday Reader",
        "m_consecutive_holidays":   "Holiday Streak",

        // ── MANGA SPECIAL ──
        "m_round_number":       "Round Pages",
        "m_fibonacci":          "Fibonacci Pages",
        "m_palindrome_day":     "Palindrome Read",
        "m_binary_day":         "Binary Read",
        "m_full_moon_read":     "Full Moon Read",
        "m_leap_year_read":     "Leap Year Read",
        "m_triple_seven":       "Triple Seven",
        "m_thousand_complete":  "Thousand Done",
        "m_nice":               "Nice Number",
        "m_power_level_chapters":"Power Chapters",
        "m_answer_42":          "Answer Found",
        "m_square_number":      "Square Pages",
        "m_prime_count":        "Prime Count",
        "m_matching_date":      "Date Match",
        "m_century_chapter":    "Century Chapter",
        "m_pi_chapters":        "Pi Chapters",
        "m_synchronicity":      "Synchronicity",
        "m_world_record":       "World Record",
        "m_genre_clash":        "Genre Clash",
        "m_time_traveler":      "Time Reader",
        "m_double_digits":      "Double Digits",
        "m_one_two_three":      "One Two Three",
        "m_lucky_seven":        "Lucky Seven",
        "m_exact_hundred_ch":   "Exact Hundred",
        "m_year_match_count":   "Year Match",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format":       "Manga Format",
        "m_manhwa_format":      "Manhwa Format",
        "m_manhua_format":      "Manhua Format",
        "m_ln_format":          "Light Novel Format",
        "m_oneshot_format":     "Oneshot Format",
        "m_doujin_format":      "Doujin Format",
        "m_novel_format":       "Novel Format",
        "m_format_master_manga":"Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock":      "First Power",
        "m_meta_collector":         "Badge Keeper",
        "m_meta_category_starter":  "Category Starter",
        "m_meta_tier_climber":      "Tier Climber",
        "m_meta_tier_max":          "Max Tier",
        "m_meta_xp_earner":         "XP Earned",
        "m_meta_difficulty_easy":   "Easy Reader",
        "m_meta_difficulty_hard":   "God Reader",
        "m_meta_unlock_spree":      "Unlock Spree",
        "m_meta_completionist":     "Meta Complete",
        "m_meta_diverse":           "Diverse Portfolio",
        "m_meta_dominator":         "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050607",
        primary: "#4a5870",
        secondary: "#364358",
        accent: "#7a6040",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/goodnight-punpun.png",
    particleColor: "#505050",
    backgroundDim: 0.3,
    backgroundBlur: 30,
    particleTypes: {
        bird_feathers: { label: "Bird Feathers", maxCount: 15, defaultEnabled: true, defaultIntensity: 50 },
        grey_mist:     { label: "Grey Mist",     maxCount: 8,  defaultEnabled: true, defaultIntensity: 45 },
        torn_papers:   { label: "Torn Papers",   maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        fading_light:  { label: "Fading Light",  maxCount: 6,  defaultEnabled: true, defaultIntensity: 40 },
    },
    playerIconOverrides: undefined,
    milestoneNames: {
        1:   "Innocent Bird",
        5:   "First Love",
        15:  "Growing Up",
        30:  "High School",
        45:  "Tokyo Drift",
        60:  "Broken Adult",
        80:  "God's Child",
        100: "Goodnight Punpun",
    },
}
