import { AnimeThemeConfig } from "./types"
import {
    GiBookshelf,
    GiGraduateCap,
    GiScooter,
    GiPunch,
    GiFist,
    GiMuscleUp,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
    GiTeacher,
    GiSchoolBag,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const greatTeacherOnizukaTheme: AnimeThemeConfig = {
    id: "great-teacher-onizuka",
    displayName: "Great Teacher Onizuka",
    description: "22 years old. Former bike gang leader turned greatest teacher. Eikichi Onizuka takes on Holy Forest Academy's Class 3-4 with fists, heart, and a motorcycle.",
    fontFamily: "'Bangers', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Bangers&display=swap",
    cssVars: {
        // Brand → bold orange with warm tones
        "--color-brand-200": "255 210 150",
        "--color-brand-300": "255 195 115",
        "--color-brand-400": "255 180 75",
        "--color-brand-500": "255 165 0",
        "--color-brand-600": "220 140 0",
        "--color-brand-700": "180 115 0",
        "--color-brand-800": "140 88 0",
        "--color-brand-900": "95 58 0",
        "--color-brand-950": "50 30 0",
        "--brand": "255 165 0",
        // Dark warm background
        "--background": "#0a0700",
        "--paper": "#140e00",
        "--color-gray-950": "10 7 0",
        "--color-gray-900": "20 14 0",
        "--color-gray-800": "35 26 8",
        "--color-gray-700": "55 42 15",
        "--color-gray-600": "80 62 28",
        "--color-gray-500": "110 90 50",
        "--color-gray-400": "145 125 85",
        "--color-gray-300": "180 165 130",
        "--color-gray-200": "210 200 175",
        "--color-gray-100": "232 226 212",
        "--color-gray-50": "246 243 236",
    },
    sidebarOverrides: {
        "home": { icon: GiTeacher, label: "Homeroom" },
        "schedule": { icon: GiAlarmClock, label: "Class Schedule" },
        "manga": { icon: LuBookOpen, label: "School Library" },
        "lists": { icon: GiBookshelf, label: "Class Roster" },
        "discover": { icon: GiBullseye, label: "After School" },
        "torrent-list": { icon: GiAnvilImpact, label: "Supply Closet" },
        "debrid": { icon: GiScooter, label: "Bike Garage" },
        "unmatched": { icon: GiSchoolBag, label: "Lost & Found" },
        "enmasse": { icon: GiResize, label: "Mass Lesson" },
        "scan-summaries": { icon: TbReportSearch, label: "Report Cards" },
        "auto-downloader": { icon: LuRss, label: "PA System" },
        "community": { icon: GiGraduateCap, label: "Faculty Room" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "School Bell" },
        "achievements": { icon: GiTrophy, label: "Honor Roll" },
        "theme-manager": { icon: GiPalette, label: "Chalkboard" },
        "extensions": { icon: BiExtension, label: "Extra Credit" },
        "sync": { icon: IoCloudOfflineOutline, label: "Homework Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Principal's Office" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Period",
        "a_episode_counter": "Attendance Count",
        "a_episode_titan": "Honor Student",
        "a_hours_invested": "Study Hours",
        "a_time_lord": "Tenure Track",
        "a_anime_collector": "Locker Stash",
        "a_library_legend": "Library King",
        "a_first_complete": "First Graduation",
        "a_hundred_club": "Century Club",
        "a_first_day": "Orientation Day",
        "a_first_rating": "First Grade",
        "a_ten_thousand_min": "Ten Thousand Minutes",
        "a_season_veteran": "Veteran Teacher",
        "a_year_explorer": "School Year",
        "a_century_watcher": "Hundred Lessons",
        "a_five_hundred_eps": "Five Hundred Classes",
        "a_thousand_eps": "Thousand Lectures",
        "a_watching_ten": "Ten Subjects",
        "a_ptw_hoarder": "Syllabus Hoarder",
        "a_dropped_honesty": "Honest Dropout",
        "a_five_thousand_eps": "Five Thousand Periods",
        "a_ten_completed": "Ten Semesters",
        "a_fifty_completed": "Fifty Courses",
        "a_five_hundred_completed": "Five Hundred Diplomas",
        "a_mean_score_tracker": "Grade Average",
        "a_unique_studios": "Partner Schools",
        "a_days_spent_watching": "Days Teaching",
        "a_all_status": "All Statuses",
        "a_first_favorite": "Teacher's Pet",
        "a_favorites_collector": "Class Favorites",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Cram Session",
        "a_marathon_runner": "Study Marathon",
        "a_weekend_warrior": "Weekend Warrior",
        "a_non_stop": "No Recess",
        "a_one_more_episode": "One More Lesson",
        "a_speed_run": "Speed Learner",
        "a_double_feature": "Double Period",
        "a_triple_threat": "Triple Threat",
        "a_five_a_day": "Five Classes",
        "a_back_to_back": "Back to Back",
        "a_seasonal_binge": "Full Semester",
        "a_cour_crusher": "Cour Crusher",
        "a_half_day_watch": "Half Day",
        "a_full_day_watch": "Full Day",
        "a_power_weekend": "Power Weekend",
        "a_binge_king": "Binge Principal",
        "a_no_sleep": "All-Nighter",
        "a_entire_season": "Rapid Course",
        "a_seven_day_challenge": "Week Challenge",
        "a_hundred_day_binge": "Hundred Day Term",
        "a_genre_binge": "Elective Binge",
        "a_studio_binge": "Studio Binge",
        "a_season_sweep": "Semester Sweep",
        "a_forty_eight_hour": "Forty-Eight Hours",
        "a_ep_counter_day": "Daily Roll Call",
        "a_multi_series_binge": "Multi-Subject Day",
        "a_midnight_binge": "Midnight Study",
        "a_new_year_binge": "New Year Cram",

        // ── ANIME GENRES ──
        "a_genre_action": "Fist Fighter",
        "a_genre_adventure": "Field Trip",
        "a_genre_comedy": "Class Clown",
        "a_genre_drama": "School Drama",
        "a_genre_fantasy": "Dream Lesson",
        "a_genre_horror": "Ghost Stories",
        "a_genre_mystery": "Mystery Class",
        "a_genre_romance": "Love Letter",
        "a_genre_scifi": "Science Lab",
        "a_genre_sol": "Daily Life",
        "a_genre_sports": "Gym Class",
        "a_genre_supernatural": "Occult Club",
        "a_genre_thriller": "Suspense Hour",
        "a_genre_mecha": "Shop Class",
        "a_genre_music": "Music Room",
        "a_genre_psychological": "Counselor Visit",
        "a_genre_ecchi": "Locker Room",
        "a_genre_mahou_shoujo": "Magic Hour",
        "a_tag_isekai": "Transfer Student",
        "a_tag_harem": "Fan Club",
        "a_tag_bl": "Study Partners",
        "a_tag_gl": "Best Friends",
        "a_tag_historical": "History Class",
        "a_tag_military": "Discipline Hall",
        "a_tag_school": "School Spirit",
        "a_tag_martial_arts": "Karate Club",
        "a_tag_vampire": "Night Class",
        "a_tag_samurai": "Kendo Club",
        "a_tag_space": "Astronomy Club",
        "a_tag_parody": "Comedy Sketch",
        "a_tag_idol": "School Idol",
        "a_tag_post_apocalyptic": "Aftermath Class",
        "a_tag_cyberpunk": "Computer Lab",
        "a_tag_shounen": "Hot Blooded",
        "a_tag_seinen": "Adult Education",
        "a_tag_shoujo": "Girls' Talk",
        "a_tag_josei": "Staff Room",
        "a_tag_survival": "Survival Camp",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Report Card",
        "a_mega_completionist": "Valedictorian",
        "a_completion_rate_50": "Midterm Pass",
        "a_completion_rate_75": "Honor Roll",
        "a_completion_rate_90": "Near Perfect",
        "a_no_drop": "No Absences",
        "a_long_runner_complete": "Long Semester",
        "a_sequel_chain": "Sequel Course",
        "a_clean_list": "Clean Record",
        "a_from_ptw": "Assignment Done",
        "a_rewatch_master": "Review Master",
        "a_short_complete": "Quick Quiz",
        "a_same_day_start_finish": "Same Day Finish",
        "a_revival": "Second Chance",
        "a_zero_to_hero": "Zero to Hero",
        "a_five_genre_complete": "Five Electives",
        "a_full_franchise": "Full Curriculum",
        "a_batch_complete": "Batch Graded",
        "a_paused_to_done": "Back from Leave",
        "a_completion_spree": "Grading Spree",
        "a_multi_rewatch": "Multi Review",
        "a_dropped_recovery": "Recovered Grade",
        "a_ten_perfect_scores": "Ten Perfects",
        "a_seasonal_clear": "Seasonal Clear",
        "a_complete_genre_span": "All Subjects",
        "a_monthly_completions": "Monthly Grades",
        "a_yearly_completions": "Annual Awards",
        "a_rapid_complete": "Speed Grading",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Student",
        "a_studio_devotee": "School Devotee",
        "a_rewatcher": "Rewatch Class",
        "a_triple_rewatch": "Triple Rewatch",
        "a_annual_tradition": "Annual Tradition",
        "a_director_fan": "Director's Fan",
        "a_voice_actor_fan": "Drama Club",
        "a_ost_lover": "School Anthem",
        "a_source_reader": "Textbook Reader",
        "a_waiting_weekly": "Weekly Wait",
        "a_childhood_revisit": "Nostalgia Trip",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Subject Loyalty",
        "a_decade_watcher": "Decade Student",
        "a_adaptation_hunter": "Adaptation Hunter",
        "a_original_anime_fan": "Original Fan",
        "a_long_commitment": "Long Commitment",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Studios",
        "a_complete_catalog": "Full Catalog",
        "a_franchise_collector": "Series Collector",
        "a_airing_follower": "Airing Follower",
        "a_genre_master": "Subject Master",
        "a_staff_follower": "Staff Follower",
        "a_multi_season_fan": "Multi-Season Fan",
        "a_format_diversity": "Format Diversity",
        "a_year_dedication": "Year Dedicated",
        "a_season_dedication": "Season Dedicated",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Elective Explorer",
        "a_studio_hopper": "School Transfer",
        "a_tag_explorer": "Tag Explorer",
        "a_decade_hopper": "Era Hopper",
        "a_hidden_gem": "Hidden Gem",
        "a_popular_taste": "Popular Pick",
        "a_retro_appreciator": "Retro Fan",
        "a_modern_viewer": "Modern Viewer",
        "a_cross_demographic": "Cross Demo",
        "a_underdog_fan": "Underdog Fan",
        "a_variety_week": "Variety Week",
        "a_foreign_cinema": "Foreign Film",
        "a_classic_connoisseur": "Classic Buff",
        "a_every_season": "Every Season",
        "a_award_winner": "Award Winner",
        "a_niche_explorer": "Niche Explorer",
        "a_global_anime": "Global Watch",
        "a_cult_classic": "Cult Classic",
        "a_random_pick": "Random Pick",
        "a_new_genre_month": "New Elective",
        "a_seasonal_completionist": "Seasonal Clear",
        "a_unpopular_opinion": "Rebel Opinion",
        "a_top_rated_viewer": "Top Rated",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Pick",
        "a_upcoming_watcher": "Upcoming Watch",
        "a_short_series_explorer": "Short Series",
        "a_long_series_explorer": "Long Series",

        // ── ANIME TIME ──
        "a_night_owl": "Night Study",
        "a_early_bird": "Early Bird",
        "a_lunch_break": "Lunch Break",
        "a_golden_hour": "Golden Hour",
        "a_four_am_club": "4 AM Club",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Watch",
        "a_midnight_premiere": "Midnight Show",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Patrol",
        "a_afternoon_delight": "Free Period",
        "a_prime_time": "Prime Time",
        "a_workday_watcher": "School Hours",
        "a_sunday_marathon": "Sunday Marathon",
        "a_rainy_day": "Rainy Recess",
        "a_morning_routine": "Morning Bell",
        "a_night_shift": "Night Shift",
        "a_twilight_zone": "Twilight Zone",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Watcher",
        "a_weekend_binge_hours": "Weekend Hours",
        "a_late_night_regular": "Late Night Owl",
        "a_sunrise_watcher": "Sunrise Watch",
        "a_holiday_watcher": "Holiday Watch",
        "a_every_day_of_week": "Every Weekday",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Hangout",
        "a_party_host": "Class President",
        "a_social_butterfly": "Social Butterfly",
        "a_group_binge": "Group Study",
        "a_party_regular": "Regular Crew",
        "a_sync_viewer": "Sync Watch",
        "a_commentator": "Commentator",
        "a_party_marathon": "Party Marathon",
        "a_full_house": "Full Classroom",
        "a_community_pillar": "School Pillar",
        "a_watch_party_streak": "Party Streak",
        "a_diverse_party": "Mixed Group",
        "a_late_night_party": "Late Night Party",
        "a_party_veteran": "Party Veteran",
        "a_genre_party": "Genre Party",
        "a_weekly_party": "Weekly Hangout",
        "a_silent_viewer": "Quiet Student",
        "a_recommendation_giver": "Recommender",
        "a_party_completionist": "Party Complete",
        "a_social_scorer": "Social Score",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Math Genius",
        "a_palindrome_day": "Palindrome Day",
        "a_binary_day": "Binary Day",
        "a_full_moon": "Full Moon Night",
        "a_leap_year": "Leap Year",
        "a_time_traveler": "Time Traveler",
        "a_genre_clash": "Genre Clash",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Complete",
        "a_pi_episodes": "Pi Episodes",
        "a_synchronicity": "Synchronicity",
        "a_world_record": "World Record",
        "a_nice": "Nice Number",
        "a_power_level": "Power Level",
        "a_answer_42": "Answer Forty-Two",
        "a_square_number": "Square Number",
        "a_prime_count": "Prime Count",
        "a_matching_date": "Matching Date",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Watcher",
        "a_movie_buff": "Movie Buff",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Watcher",
        "a_short_king": "Short King",
        "a_variety_pack": "Variety Pack",
        "a_film_festival": "Film Festival",
        "a_music_video": "Music Video",
        "a_tv_short": "TV Short",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Anthology",
        "a_mini_series": "Mini Series",
        "a_theatrical": "Theatrical",
        "a_format_master": "Format Master",
        "a_long_movie": "Long Movie",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "CM Watcher",
        "a_pv_collector": "PV Collector",
        "a_format_balance": "Format Balance",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Movie",
        "a_recap_watcher": "Recap Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Streak",
        "a_mega_streak": "Mega Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Watch",
        "a_comeback": "Comeback Kid",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Steady Pace",
        "a_year_long": "Year Long",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Finish Streak",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi Streak",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Tough Grader",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Harsh Grader",
        "a_fair_judge": "Fair Judge",
        "a_generous_spirit": "Easy Grader",
        "a_score_all": "Grade Everyone",
        "a_wide_range": "Wide Range",
        "a_controversial": "Hot Take",
        "a_consistent_scorer": "Steady Grader",
        "a_score_sniper": "Score Sniper",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Picky Student",
        "a_100_rated": "Hundred Graded",
        "a_500_rated": "Five Hundred Graded",
        "a_mediocre_majority": "Average Joe",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Hunter",
        "a_contrarian": "Contrarian",
        "a_optimist": "Class Optimist",
        "a_score_distributor": "Score Spreader",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Pledge",
        "a_valentines_weeb": "Valentine's Watch",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Fools Prank",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "May Fourth",
        "a_summer_solstice": "Summer Break",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday Thirteenth",
        "a_halloween_spirit": "Halloween Watch",
        "a_thanksgiving_binge": "Thanksgiving Binge",
        "a_christmas_special": "Christmas Special",
        "a_new_years_eve": "New Year's Eve",
        "a_birthday_watch": "Birthday Watch",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Independence Day",
        "a_culture_day": "Culture Fest",
        "a_spring_equinox": "Spring Festival",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Day",
        "a_winter_solstice": "Winter Break",
        "a_anime_birthday": "Anime Birthday",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Holiday Streak",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Unlock",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Start",
        "a_meta_tier_climber": "Tier Climber",
        "a_meta_tier_max": "Max Tier",
        "a_meta_xp_earner": "XP Earner",
        "a_meta_difficulty_easy": "Easy Mode",
        "a_meta_difficulty_hard": "Hard Mode",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Complete",
        "a_meta_diverse": "Meta Diverse",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter",
        "m_chapter_counter": "Chapter Count",
        "m_chapter_titan": "Top Reader",
        "m_reading_hours": "Reading Hours",
        "m_reading_time_lord": "Reading Tenure",
        "m_manga_collector": "Manga Stash",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Finished",
        "m_hundred_club": "Hundred Club",
        "m_first_day": "First Read Day",
        "m_first_rating": "First Review",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Hoarder",
        "m_year_explorer": "Year of Reading",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Read",
        "m_thousand_ch": "Thousand Chapters",
        "m_reading_ten": "Ten at Once",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Drop",
        "m_season_reader": "Seasonal Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand Read",
        "m_ten_completed": "Ten Finished",
        "m_fifty_completed": "Fifty Finished",
        "m_five_hundred_completed": "Five Hundred Done",
        "m_mean_score_tracker": "Score Average",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Faves Collector",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Reading Binge",
        "m_marathon_reader": "Reading Marathon",
        "m_weekend_reader": "Weekend Reader",
        "m_non_stop_reading": "Non-Stop Pages",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Reader",
        "m_double_story": "Double Feature",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five a Day",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half Day Read",
        "m_full_day_read": "Full Day Read",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge King",
        "m_no_sleep_read": "No Sleep Read",
        "m_full_series_rush": "Series Rush",
        "m_seven_day_challenge": "Week Challenge",
        "m_hundred_day_read": "Hundred Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Binge",
        "m_author_binge": "Author Binge",
        "m_chapter_counter_day": "Daily Chapters",
        "m_multi_series_binge": "Multi Series",
        "m_midnight_binge": "Midnight Read",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "Forty-Eight Hours",
        "m_oneshot_binge": "Oneshot Binge",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Read",
        "m_genre_adventure": "Adventure Read",
        "m_genre_comedy": "Comedy Read",
        "m_genre_drama": "Drama Read",
        "m_genre_fantasy": "Fantasy Read",
        "m_genre_horror": "Horror Read",
        "m_genre_mystery": "Mystery Read",
        "m_genre_romance": "Romance Read",
        "m_genre_scifi": "Sci-Fi Read",
        "m_genre_sol": "Slice of Life",
        "m_genre_sports": "Sports Read",
        "m_genre_supernatural": "Supernatural Read",
        "m_genre_thriller": "Thriller Read",
        "m_genre_psychological": "Psych Read",
        "m_genre_isekai": "Isekai Read",
        "m_genre_shounen": "Shounen Read",
        "m_genre_ecchi": "Ecchi Read",
        "m_genre_mahou_shoujo": "Mahou Read",
        "m_genre_mecha": "Mecha Read",
        "m_genre_music": "Music Read",
        "m_tag_isekai_new": "New World Read",
        "m_tag_harem": "Harem Read",
        "m_tag_bl": "BL Read",
        "m_tag_gl": "GL Read",
        "m_tag_historical": "Historical Read",
        "m_tag_military": "Military Read",
        "m_tag_school": "School Read",
        "m_tag_martial_arts": "Martial Arts",
        "m_tag_vampire": "Vampire Read",
        "m_tag_samurai": "Samurai Read",
        "m_tag_space": "Space Read",
        "m_tag_parody": "Parody Read",
        "m_tag_idol": "Idol Read",
        "m_tag_post_apocalyptic": "Post-Apocalyptic",
        "m_tag_cyberpunk": "Cyberpunk Read",
        "m_tag_shoujo": "Shoujo Read",
        "m_tag_survival": "Survival Read",
        "m_tag_cooking": "Cooking Read",
        "m_tag_medical": "Medical Read",
        "m_tag_villainess": "Villainess Read",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Marks",
        "m_mega_completionist": "Mega Graduate",
        "m_completion_rate_50": "Halfway Done",
        "m_completion_rate_75": "Almost There",
        "m_completion_rate_90": "Near Perfection",
        "m_no_drop": "No Drops",
        "m_long_runner_complete": "Long Runner",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean List",
        "m_from_ptr": "From Backlog",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same Day Clear",
        "m_revival": "Revival Read",
        "m_zero_to_hundred": "Zero to Hundred",
        "m_five_genre_complete": "Five Genres",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Complete",
        "m_paused_to_done": "Resumed Done",
        "m_completion_spree": "Finish Spree",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi Reread",
        "m_dropped_recovery": "Drop Recovery",
        "m_ten_perfect_scores": "Ten Perfects",
        "m_complete_genre_span": "All Genres",
        "m_monthly_completions": "Monthly Clears",
        "m_yearly_completions": "Yearly Clears",
        "m_rapid_complete": "Rapid Finish",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Lover",
        "m_rereader": "Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Fan",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Fan",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyalty",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Fave Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Franchise Fan",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Master",
        "m_multi_series_author": "Author Devotee",
        "m_format_diversity": "Format Variety",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Fan",
        "m_genre_loyalty_50": "Fifty Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Explorer",
        "m_decade_hopper": "Decade Hopper",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Taste",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross Demo",
        "m_underdog_fan": "Underdog Pick",
        "m_variety_week": "Variety Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Fan",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Niche Reader",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre Try",
        "m_year_completionist": "Year Complete",
        "m_unpopular_opinion": "Rebel Opinion",
        "m_top_rated_reader": "Top Rated",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Manga",
        "m_long_manga_explorer": "Long Manga",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Early Reader",
        "m_lunch_reader": "Lunch Reader",
        "m_commute_reader": "Commute Read",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All Hours",
        "m_prime_time_reader": "Prime Reader",
        "m_workday_reader": "Workday Read",
        "m_sunday_read": "Sunday Read",
        "m_morning_routine": "Morning Read",
        "m_night_shift_reader": "Night Shift",
        "m_seasonal_premier_read": "New Release",
        "m_clock_collector": "Clock Reader",
        "m_late_night_horror": "Late Horror",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Read",
        "m_dawn_reader": "Dawn Reader",
        "m_twilight_reader": "Twilight Read",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Hours",
        "m_late_night_regular": "Late Regular",
        "m_sunrise_reader": "Sunrise Read",
        "m_every_day_of_week": "Every Day",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Lover",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Fan",
        "m_adaptation_reader": "Adaptation Read",
        "m_longstrip_reader": "Longstrip Read",
        "m_4koma_reader": "4-Koma Fan",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Mix",
        "m_light_novel_reader": "Light Novel",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Story",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Read",
        "m_cross_media": "Cross Media",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collab Reader",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Streak",
        "m_mega_streak": "Mega Streak",
        "m_weekly_warrior": "Weekly Warrior",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Comeback Read",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Reader",
        "m_habit_formed": "Habit Formed",
        "m_consistent_pace": "Steady Pace",
        "m_year_long": "Year Long",
        "m_double_streak": "Double Streak",
        "m_streak_recovery": "Streak Recovery",
        "m_daily_minimum": "Daily Minimum",
        "m_winter_streak": "Winter Streak",
        "m_summer_streak": "Summer Streak",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Streak",
        "m_unbreakable": "Unbreakable",
        "m_eternal_flame": "Eternal Reader",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Finish Streak",
        "m_rating_streak": "Rating Streak",
        "m_multi_ch_streak": "Multi Streak",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Strict Grader",
        "m_perfect_ten": "Perfect Ten",
        "m_harsh_critic": "Harsh Review",
        "m_fair_judge": "Fair Review",
        "m_generous_spirit": "Easy Review",
        "m_score_all": "Score All",
        "m_wide_range": "Wide Range",
        "m_controversial": "Hot Take",
        "m_consistent_scorer": "Steady Scorer",
        "m_score_sniper": "Score Sniper",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Picky Reader",
        "m_100_rated": "Hundred Rated",
        "m_500_rated": "Five Hundred Rated",
        "m_mediocre_majority": "Average Score",
        "m_rating_spree": "Rating Spree",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Rerate Reread",
        "m_masterpiece_hunter": "Masterpiece Find",
        "m_contrarian": "Contrarian",
        "m_optimist": "Optimist Reader",
        "m_score_distributor": "Score Spread",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Read",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Fools",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Read",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Friday 13th Read",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thanksgiving Read",
        "m_christmas_read": "Christmas Read",
        "m_new_years_eve": "New Year's Eve",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Marathon",
        "m_independence_day": "Independence Read",
        "m_culture_day": "Culture Day",
        "m_spring_equinox": "Spring Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Winter Read",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "Every Holiday",
        "m_consecutive_holidays": "Holiday Streak",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number",
        "m_fibonacci": "Fibonacci Count",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven",
        "m_thousand_complete": "Thousand Done",
        "m_nice": "Nice Number",
        "m_power_level_chapters": "Power Level",
        "m_answer_42": "Answer Forty-Two",
        "m_square_number": "Square Number",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Matching Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Synchronicity",
        "m_world_record": "World Record",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time Traveler",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Match",
        "m_chapter_match_date": "Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Unlock",
        "m_meta_collector": "Badge Collector",
        "m_meta_category_starter": "Category Start",
        "m_meta_tier_climber": "Tier Climber",
        "m_meta_tier_max": "Max Tier",
        "m_meta_xp_earner": "XP Earner",
        "m_meta_difficulty_easy": "Easy Mode",
        "m_meta_difficulty_hard": "Hard Mode",
        "m_meta_unlock_spree": "Unlock Spree",
        "m_meta_completionist": "Meta Complete",
        "m_meta_diverse": "Meta Diverse",
        "m_meta_dominator": "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#0a0700",
        primary: "#ffa500",
        secondary: "#dc8c00",
        accent: "#ff8c00",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/great-teacher-onizuka.jpg",
    particleColor: "#d87828",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        chalk_dust: { label: "Chalk Dust", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        paper_planes: { label: "Paper Planes", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        motorcycle_sparks: { label: "Motorcycle Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        school_bells: { label: "School Bells", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Delinquent",
        5:   "Substitute",
        15:  "Homeroom",
        30:  "GTO",
        45:  "Students' Hero",
        60:  "Legend",
        80:  "Greatest Teacher",
        100: "Onizuka-sensei",
    },
}
