import { AnimeThemeConfig } from "./types"
import { GiRobotLeg, GiMissileSwarm, GiShield, GiCrossedSwords, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiArmorVest } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const gundamTheme: AnimeThemeConfig = {
    id: "gundam",
    displayName: "Mobile Suit Gundam",
    description: "The One Year War rages between Earth Federation and Zeon — aboard White Base, young Amuro Ray pilots the RX-78-2 and discovers that war is not about heroes, only people.",
    fontFamily: "'Rajdhani', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;600;700&display=swap",
    cssVars: {
        "--color-brand-200": "160 195 255",
        "--color-brand-300": "100 158 245",
        "--color-brand-400": "50 118 232",
        "--color-brand-500": "18 84 208",
        "--color-brand-600": "12 66 172",
        "--color-brand-700": "8 50 132",
        "--color-brand-800": "5 34 92",
        "--color-brand-900": "2 18 54",
        "--color-brand-950": "1 9 30",
        "--brand": "18 84 208",
        "--background": "#020409",
        "--paper": "#05091a",
        "--color-gray-950": "2 4 9",
        "--color-gray-900": "5 9 20",
        "--color-gray-800": "10 18 38",
        "--color-gray-700": "18 30 62",
        "--color-gray-600": "30 48 95",
        "--color-gray-500": "50 72 135",
        "--color-gray-400": "85 112 172",
        "--color-gray-300": "128 155 200",
        "--color-gray-200": "168 188 222",
        "--color-gray-100": "204 215 238",
        "--color-gray-50": "232 238 250",
    },
    sidebarOverrides: {
        "home": { icon: GiRobotLeg, label: "White Base" },
        "schedule": { icon: GiAlarmClock, label: "Battle Schedule" },
        "manga": { icon: LuBookOpen, label: "War Archives" },
        "lists": { icon: GiShield, label: "Federation Roster" },
        "discover": { icon: GiBullseye, label: "Enemy Recon" },
        "torrent-list": { icon: GiMissileSwarm, label: "Beam Cache" },
        "debrid": { icon: GiArmorVest, label: "MS Hangar" },
        "unmatched": { icon: GiCrossedSwords, label: "Unidentified Units" },
        "enmasse": { icon: GiResize, label: "Fleet Mobilize" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Fed Intelligence" },
        "community": { icon: GiRobotLeg, label: "White Base Crew" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Battle Stations" },
        "achievements": { icon: GiTrophy, label: "War Medals" },
        "milestones": { icon: LuFlag, label: "Mobile Goals" },
        "theme-manager": { icon: GiPalette, label: "MS Colors" },
        "extensions": { icon: BiExtension, label: "MS Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "Fed Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Cockpit Controls" },
    },
    achievementNames: {
        "a_first_episode": "First Sortie",
        "a_first_complete": "War Ended",
        "a_hundred_club": "Hundred Battles",
        "a_time_lord": "War Veteran",
        "a_anime_collector": "MS Collection",
        "a_library_legend": "War Archives",
        "a_binge_king": "Non-Stop Battle",
        "a_no_sleep": "All-Night Combat",
        "a_marathon_runner": "Year-Long War",
        "a_speed_run": "Flash Sortie",
        "a_completionist": "War Complete",
        "a_mega_completionist": "Universal Century Master",
        "a_loyal_fan": "Loyal Fed Pilot",
        "a_rewatcher": "War Revisited",
        "a_decade_watcher": "Decade War Fan",
        "a_genre_action": "Combat Ace",
        "a_genre_adventure": "Space Explorer",
        "a_genre_comedy": "Hayato's Rivalry",
        "a_genre_drama": "War's True Face",
        "a_genre_fantasy": "Newtype Awakening",
        "a_genre_horror": "Zeon Terror",
        "a_genre_romance": "Amuro and Sayla",
        "a_genre_scifi": "Mobile Suit Science",
        "a_genre_supernatural": "Newtype Powers",
        "a_genre_psychological": "Amuro's Trauma",
        "a_genre_mecha": "Mecha Realist",
        "a_critic": "War Analyst",
        "a_perfect_ten": "Perfect Campaign",
        "a_harsh_critic": "Strict Tactician",
        "a_daily_streak": "Daily Briefing",
        "a_mega_streak": "Eternal Campaign",
        "a_year_long": "One Year War",
        "a_iron_will": "Soldier's Will",
        "a_hidden_gem": "Hidden MS",
        "a_cult_classic": "Gundam Legacy",
        "a_classic_connoisseur": "UC Classic Fan",
        "a_new_years_resolution": "New Year Sortie",
        "a_christmas_special": "Space Colony Holiday",
        "a_meta_tier_max": "Newtype Captain",
        "a_meta_completionist": "Complete Registry",
        "a_sequel_chain": "Sequel Cleared",
        "a_zero_to_hero": "Civilian to Pilot",
        "a_night_owl": "Night Patrol",
        "a_early_bird": "Dawn Launch",
        "m_first_chapter": "First Brief",
        "m_first_complete": "Mission Done",
        "m_hundred_club": "Hundred Entries",
        "m_binge_king": "Marathon Brief",
        "m_completionist": "Full Dossier",
        "m_mega_completionist": "EFSF Master",
        "m_loyal_reader": "Fed Reader",
        "m_rereader": "Battle Reread",
        "m_genre_action": "Action Dossier",
        "m_genre_adventure": "Space Reader",
        "m_genre_romance": "Hearts at War",
        "m_genre_fantasy": "Newtype Reader",
        "m_genre_horror": "Zeon Files",
        "m_genre_drama": "War Drama",
        "m_genre_scifi": "MS Specs Fan",
        "m_genre_supernatural": "Newtype Tales",
        "m_genre_psychological": "Mind of a Pilot",
        "m_critic": "Field Critic",
        "m_perfect_ten": "Perfect Intel",
        "m_daily_streak": "Daily Log",
        "m_mega_streak": "Unbroken Campaign",
        "m_year_long": "Year of War",
        "m_iron_will": "Iron Soldier",
        "m_hidden_gem": "Hidden File",
        "m_cult_classic": "Classic Series",
        "m_mangaka_lover": "Artist Fan",
        "m_source_material_fan": "Source Reader",
        "m_meta_tier_max": "Fleet Admiral",
        "m_meta_completionist": "Full Archives",
        "m_art_appreciator": "MS Art Fan",
        "m_manga_to_anime": "Source Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020409",
        primary: "#1254d0",
        secondary: "#0c42ac",
        accent: "#cc3020",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/gundam.jpg",
    particleColor: "#5090e8",
    backgroundDim: 0.4,
    backgroundBlur: 22,
    particleTypes: {
        beam_fire: { label: "Beam Fire", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        stars: { label: "Stars", maxCount: 30, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1: "Civilian",
        5: "Fed Recruit",
        15: "MS Pilot",
        30: "Amuro Ray",
        50: "White Base Ace",
        75: "Newtype",
        100: "Legend of the One Year War",
    },
}
