import { AnimeThemeConfig } from "./types"
import {
    GiSchoolBag,
    GiSparkles,
    GiBookshelf,
    GiCrystalBall,
    GiHourglass,
    GiMusicalNotes,
    GiMagnifyingGlass,
    GiStaryu,
    GiLightBulb,
    GiRibbonMedal,
    GiPalette,
    GiAlarmClock,
    GiSettingsKnobs,
    GiResize,
    GiAnvilImpact,
    GiTrophy,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const haruhiSuzumiyaTheme: AnimeThemeConfig = {
    id: "haruhi-suzumiya",
    displayName: "The Melancholy of Haruhi Suzumiya",
    description: "The SOS Brigade awaits. A radiant yellow interface channeling god-like powers, closed spaces, and the endless eccentricity of Haruhi's world.",
    fontFamily: "'Quicksand', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&display=swap",
    cssVars: {
        // Brand → vivid yellow radiating Haruhi's energy
        "--color-brand-200": "255 230 130",
        "--color-brand-300": "255 220 80",
        "--color-brand-400": "255 210 40",
        "--color-brand-500": "255 200 0",
        "--color-brand-600": "215 170 0",
        "--color-brand-700": "170 135 0",
        "--color-brand-800": "120 95 0",
        "--color-brand-900": "75 60 0",
        "--color-brand-950": "40 30 0",
        "--brand": "255 200 0",
        // Dark warm background
        "--background": "#0a0800",
        "--paper": "#140e00",
        "--color-gray-950": "10 8 0",
        "--color-gray-900": "20 14 0",
        "--color-gray-800": "35 28 8",
        "--color-gray-700": "55 45 15",
        "--color-gray-600": "80 68 30",
        "--color-gray-500": "110 95 55",
        "--color-gray-400": "150 135 95",
        "--color-gray-300": "185 172 140",
        "--color-gray-200": "212 204 180",
        "--color-gray-100": "235 230 215",
        "--color-gray-50": "248 245 238",
    },
    sidebarOverrides: {
        "home": { icon: GiSchoolBag, label: "Clubroom" },
        "schedule": { icon: GiAlarmClock, label: "Brigade Schedule" },
        "manga": { icon: LuBookOpen, label: "SOS Archives" },
        "lists": { icon: GiBookshelf, label: "Brigade Registry" },
        "discover": { icon: GiCrystalBall, label: "Closed Space" },
        "torrent-list": { icon: GiAnvilImpact, label: "Data Packets" },
        "debrid": { icon: GiHourglass, label: "Time Slip Cache" },
        "unmatched": { icon: GiStaryu, label: "Lost Entities" },
        "enmasse": { icon: GiResize, label: "Mass Mobilization" },
        "scan-summaries": { icon: TbReportSearch, label: "Observation Logs" },
        "auto-downloader": { icon: LuRss, label: "Auto Retrieval" },
        "community": { icon: GiSparkles, label: "Brigade Members" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "SOS Alerts" },
        "achievements": { icon: GiTrophy, label: "Brigade Awards" },
        "theme-manager": { icon: GiPalette, label: "Costume Change" },
        "extensions": { icon: BiExtension, label: "Special Abilities" },
        "sync": { icon: IoCloudOfflineOutline, label: "Dimensional Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Brigade HQ" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Broadcast",
        "a_episode_counter": "Episode Tally",
        "a_episode_titan": "Ultra Director",
        "a_hours_invested": "Brigade Hours",
        "a_time_lord": "Endless Recursion",
        "a_anime_collector": "Anime Hoarder",
        "a_library_legend": "Nagato's Collection",
        "a_first_complete": "First Completion",
        "a_hundred_club": "Hundred Club",
        "a_first_day": "Enrollment Day",
        "a_first_rating": "First Critique",
        "a_ten_thousand_min": "Ten Thousand",
        "a_season_veteran": "Seasoned Member",
        "a_year_explorer": "Year Explorer",
        "a_century_watcher": "Century Watcher",
        "a_five_hundred_eps": "Five Hundred",
        "a_thousand_eps": "Thousand Episodes",
        "a_watching_ten": "Ten Simultaneous",
        "a_ptw_hoarder": "Backlog Hoarder",
        "a_dropped_honesty": "Honest Drop",
        "a_five_thousand_eps": "Five Thousand",
        "a_ten_completed": "Ten Complete",
        "a_fifty_completed": "Fifty Complete",
        "a_five_hundred_completed": "Five Hundred Done",
        "a_mean_score_tracker": "Score Tracker",
        "a_unique_studios": "Studio Variety",
        "a_days_spent_watching": "Days Watching",
        "a_all_status": "All Statuses",
        "a_first_favorite": "First Favorite",
        "a_favorites_collector": "Favorites Hoard",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Binge Session",
        "a_marathon_runner": "Endless Eight",
        "a_weekend_warrior": "Weekend Brigade",
        "a_non_stop": "Non-Stop Watch",
        "a_one_more_episode": "One More!",
        "a_speed_run": "Speed Viewing",
        "a_double_feature": "Double Feature",
        "a_triple_threat": "Triple Threat",
        "a_five_a_day": "Five Daily",
        "a_back_to_back": "Back to Back",
        "a_seasonal_binge": "Seasonal Binge",
        "a_cour_crusher": "Cour Crusher",
        "a_half_day_watch": "Half-Day Watch",
        "a_full_day_watch": "Full-Day Watch",
        "a_power_weekend": "Power Weekend",
        "a_binge_king": "Binge Chief",
        "a_no_sleep": "Sleepless Night",
        "a_entire_season": "Season Swept",
        "a_seven_day_challenge": "Seven Day Run",
        "a_hundred_day_binge": "Hundred Day Siege",
        "a_genre_binge": "Genre Binge",
        "a_studio_binge": "Studio Binge",
        "a_season_sweep": "Season Sweep",
        "a_forty_eight_hour": "Forty-Eight Hours",
        "a_ep_counter_day": "Daily Counter",
        "a_multi_series_binge": "Multi-Series Binge",
        "a_midnight_binge": "Midnight Binge",
        "a_new_year_binge": "New Year Binge",

        // ── ANIME GENRES ──
        "a_genre_action": "Action Club",
        "a_genre_adventure": "Adventure Quest",
        "a_genre_comedy": "Comedy Gold",
        "a_genre_drama": "Drama Melancholy",
        "a_genre_fantasy": "Fantasy Realm",
        "a_genre_horror": "Horror Night",
        "a_genre_mystery": "Mystery Solver",
        "a_genre_romance": "Romance Arc",
        "a_genre_scifi": "Sci-Fi Data",
        "a_genre_sol": "School Life",
        "a_genre_sports": "Sports Day",
        "a_genre_supernatural": "Supernatural Power",
        "a_genre_thriller": "Thriller Pursuit",
        "a_genre_mecha": "Mecha Otaku",
        "a_genre_music": "God Knows...",
        "a_genre_psychological": "Psyche Dive",
        "a_genre_ecchi": "Mikuru Beam",
        "a_genre_mahou_shoujo": "Magical Girl",
        "a_tag_isekai": "Other World",
        "a_tag_harem": "Brigade Bonds",
        "a_tag_bl": "Close Comrades",
        "a_tag_gl": "Dear Friends",
        "a_tag_historical": "History Club",
        "a_tag_military": "Military Buff",
        "a_tag_school": "North High",
        "a_tag_martial_arts": "Martial Arts",
        "a_tag_vampire": "Night Entity",
        "a_tag_samurai": "Sword Path",
        "a_tag_space": "Outer Space",
        "a_tag_parody": "Parody Skit",
        "a_tag_idol": "SOS Idol",
        "a_tag_post_apocalyptic": "Post-Apocalypse",
        "a_tag_cyberpunk": "Cyber Entity",
        "a_tag_shounen": "Shounen Spirit",
        "a_tag_seinen": "Seinen Depth",
        "a_tag_shoujo": "Shoujo Heart",
        "a_tag_josei": "Josei Lens",
        "a_tag_survival": "Survival Game",

        // ── ANIME COMPLETION ──
        "a_completionist": "Completionist",
        "a_mega_completionist": "Mega Complete",
        "a_completion_rate_50": "Halfway There",
        "a_completion_rate_75": "Almost Done",
        "a_completion_rate_90": "Nearly Perfect",
        "a_no_drop": "No Drops",
        "a_long_runner_complete": "Long Runner",
        "a_sequel_chain": "Sequel Chain",
        "a_clean_list": "Clean List",
        "a_from_ptw": "Backlog Cleared",
        "a_rewatch_master": "Déjà Vu",
        "a_short_complete": "Quick Finish",
        "a_same_day_start_finish": "Same-Day Clear",
        "a_revival": "Revival Watch",
        "a_zero_to_hero": "Zero to Hero",
        "a_five_genre_complete": "Five Genres",
        "a_full_franchise": "Full Franchise",
        "a_batch_complete": "Batch Clear",
        "a_paused_to_done": "Resumed Done",
        "a_completion_spree": "Spree Clear",
        "a_multi_rewatch": "Multi-Rewatch",
        "a_dropped_recovery": "Drop Recovery",
        "a_ten_perfect_scores": "Ten Perfects",
        "a_seasonal_clear": "Seasonal Clear",
        "a_complete_genre_span": "Genre Span",
        "a_monthly_completions": "Monthly Clears",
        "a_yearly_completions": "Yearly Clears",
        "a_rapid_complete": "Rapid Finish",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Haruhiist",
        "a_studio_devotee": "KyoAni Devotee",
        "a_rewatcher": "Rewatch Loop",
        "a_triple_rewatch": "Triple Loop",
        "a_annual_tradition": "Annual Ritual",
        "a_director_fan": "Director Fan",
        "a_voice_actor_fan": "Seiyuu Fan",
        "a_ost_lover": "OST Lover",
        "a_source_reader": "Source Reader",
        "a_waiting_weekly": "Weekly Wait",
        "a_childhood_revisit": "Childhood Revisit",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Genre Loyalty",
        "a_decade_watcher": "Decade Watcher",
        "a_adaptation_hunter": "Adaptation Hunter",
        "a_original_anime_fan": "Original Fan",
        "a_long_commitment": "Long Commitment",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Studios",
        "a_complete_catalog": "Full Catalog",
        "a_franchise_collector": "Franchise Buff",
        "a_airing_follower": "Airing Follower",
        "a_genre_master": "Genre Master",
        "a_staff_follower": "Staff Follower",
        "a_multi_season_fan": "Multi-Season Fan",
        "a_format_diversity": "Format Diversity",
        "a_year_dedication": "Year Dedicated",
        "a_season_dedication": "Season Devoted",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Genre Explorer",
        "a_studio_hopper": "Studio Hopper",
        "a_tag_explorer": "Tag Explorer",
        "a_decade_hopper": "Decade Hopper",
        "a_hidden_gem": "Hidden Gem",
        "a_popular_taste": "Popular Pick",
        "a_retro_appreciator": "Retro Viewer",
        "a_modern_viewer": "Modern Viewer",
        "a_cross_demographic": "Cross-Demographic",
        "a_underdog_fan": "Underdog Fan",
        "a_variety_week": "Variety Week",
        "a_foreign_cinema": "Foreign Cinema",
        "a_classic_connoisseur": "Classic Taste",
        "a_every_season": "Every Season",
        "a_award_winner": "Award Viewer",
        "a_niche_explorer": "Niche Explorer",
        "a_global_anime": "Global Anime",
        "a_cult_classic": "Cult Classic",
        "a_random_pick": "Random Pick",
        "a_new_genre_month": "New Genre",
        "a_seasonal_completionist": "Seasonal Sweep",
        "a_unpopular_opinion": "Rebel Opinion",
        "a_top_rated_viewer": "Top Rated",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Viewer",
        "a_upcoming_watcher": "Upcoming Watch",
        "a_short_series_explorer": "Short Explorer",
        "a_long_series_explorer": "Long Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Owl",
        "a_early_bird": "Early Bird",
        "a_lunch_break": "Lunch Break",
        "a_golden_hour": "Golden Hour",
        "a_four_am_club": "4 AM Club",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Watch",
        "a_midnight_premiere": "Midnight Premiere",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Watcher",
        "a_afternoon_delight": "Afternoon Session",
        "a_prime_time": "Prime Time",
        "a_workday_watcher": "Workday Watch",
        "a_sunday_marathon": "Sunday Marathon",
        "a_rainy_day": "Rainy Day",
        "a_morning_routine": "Morning Routine",
        "a_night_shift": "Night Shift",
        "a_twilight_zone": "Twilight Zone",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Collector",
        "a_weekend_binge_hours": "Weekend Hours",
        "a_late_night_regular": "Late Night",
        "a_sunrise_watcher": "Sunrise Watch",
        "a_holiday_watcher": "Holiday Watch",
        "a_every_day_of_week": "Every Day",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Gathering",
        "a_party_host": "Brigade Leader",
        "a_social_butterfly": "Social Butterfly",
        "a_group_binge": "Group Screening",
        "a_party_regular": "Regular Member",
        "a_sync_viewer": "Synced Viewing",
        "a_commentator": "Commentator",
        "a_party_marathon": "Party Marathon",
        "a_full_house": "Full Clubroom",
        "a_community_pillar": "Brigade Pillar",
        "a_watch_party_streak": "Party Streak",
        "a_diverse_party": "Diverse Party",
        "a_late_night_party": "Late Night Party",
        "a_party_veteran": "Party Veteran",
        "a_genre_party": "Genre Party",
        "a_weekly_party": "Weekly Party",
        "a_silent_viewer": "Kyon's Sigh",
        "a_recommendation_giver": "Recommender",
        "a_party_completionist": "Party Completionist",
        "a_social_scorer": "Social Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Fibonacci Spark",
        "a_palindrome_day": "Palindrome Day",
        "a_binary_day": "Binary Day",
        "a_full_moon": "Full Moon",
        "a_leap_year": "Leap Year",
        "a_time_traveler": "Time Traveler",
        "a_genre_clash": "Genre Clash",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Done",
        "a_pi_episodes": "Pi Episodes",
        "a_synchronicity": "Synchronicity",
        "a_world_record": "World Record",
        "a_nice": "Nice",
        "a_power_level": "God Power",
        "a_answer_42": "Answer: 42",
        "a_square_number": "Square Number",
        "a_prime_count": "Prime Count",
        "a_matching_date": "Date Match",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Watcher",
        "a_movie_buff": "Movie Buff",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Watcher",
        "a_short_king": "Short King",
        "a_variety_pack": "Variety Pack",
        "a_film_festival": "Film Festival",
        "a_music_video": "Music Video",
        "a_tv_short": "TV Short",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Anthology",
        "a_mini_series": "Mini Series",
        "a_theatrical": "Theatrical Run",
        "a_format_master": "Format Master",
        "a_long_movie": "Long Movie",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "CM Watcher",
        "a_pv_collector": "PV Collector",
        "a_format_balance": "Format Balance",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Movie",
        "a_recap_watcher": "Recap Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Streak",
        "a_mega_streak": "Mega Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Watcher",
        "a_comeback": "Comeback Arc",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Steady Pace",
        "a_year_long": "Year-Long Streak",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Chain",
        "a_multi_ep_streak": "Multi-Ep Streak",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Harsh Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Kyon's Snark",
        "a_fair_judge": "Fair Judge",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Score All",
        "a_wide_range": "Wide Range",
        "a_controversial": "Controversial",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Score Sniper",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Picky Watcher",
        "a_100_rated": "Hundred Rated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Hunt",
        "a_contrarian": "Contrarian",
        "a_optimist": "Optimist",
        "a_score_distributor": "Score Spread",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Vow",
        "a_valentines_weeb": "Valentine Watch",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Fools",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "Star Wars Day",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday 13th",
        "a_halloween_spirit": "Halloween Spirit",
        "a_thanksgiving_binge": "Thanksgiving Binge",
        "a_christmas_special": "Christmas Special",
        "a_new_years_eve": "New Year's Eve",
        "a_birthday_watch": "Birthday Watch",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Independence Day",
        "a_culture_day": "Culture Festival",
        "a_spring_equinox": "Spring Equinox",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Day",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anime Birthday",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Holiday Streak",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Unlock",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Start",
        "a_meta_tier_climber": "Tier Climber",
        "a_meta_tier_max": "Max Tier",
        "a_meta_xp_earner": "XP Earner",
        "a_meta_difficulty_easy": "Easy Mode",
        "a_meta_difficulty_hard": "God Mode",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Complete",
        "a_meta_diverse": "Diverse Meta",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter",
        "m_chapter_counter": "Chapter Counter",
        "m_chapter_titan": "Chapter Titan",
        "m_reading_hours": "Reading Hours",
        "m_reading_time_lord": "Time Lord Reader",
        "m_manga_collector": "Manga Collector",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Manga Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "First Reading Day",
        "m_first_rating": "First Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Collector",
        "m_year_explorer": "Year Reading",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Ch",
        "m_thousand_ch": "Thousand Chapters",
        "m_reading_ten": "Reading Ten",
        "m_ptr_hoarder": "Backlog Reader",
        "m_dropped_honesty": "Honest Drop",
        "m_season_reader": "Season Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand Ch",
        "m_ten_completed": "Ten Manga Done",
        "m_fifty_completed": "Fifty Manga Done",
        "m_five_hundred_completed": "Five Hundred Done",
        "m_mean_score_tracker": "Score Tracker",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Favorites Hoard",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reader",
        "m_marathon_reader": "Reading Marathon",
        "m_weekend_reader": "Weekend Reader",
        "m_non_stop_reading": "Non-Stop Read",
        "m_one_more_chapter": "One More!",
        "m_speed_read": "Speed Read",
        "m_double_story": "Double Story",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five Daily",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Read",
        "m_full_day_read": "Full-Day Read",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge Ruler",
        "m_no_sleep_read": "Sleepless Read",
        "m_full_series_rush": "Series Rush",
        "m_seven_day_challenge": "Seven Day Read",
        "m_hundred_day_read": "Hundred Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Binge",
        "m_author_binge": "Author Binge",
        "m_chapter_counter_day": "Daily Chapters",
        "m_multi_series_binge": "Multi-Series Read",
        "m_midnight_binge": "Midnight Read",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "Forty-Eight Hours",
        "m_oneshot_binge": "Oneshot Binge",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Reader",
        "m_genre_adventure": "Adventure Reader",
        "m_genre_comedy": "Comedy Reader",
        "m_genre_drama": "Drama Reader",
        "m_genre_fantasy": "Fantasy Reader",
        "m_genre_horror": "Horror Reader",
        "m_genre_mystery": "Mystery Reader",
        "m_genre_romance": "Romance Reader",
        "m_genre_scifi": "Sci-Fi Reader",
        "m_genre_sol": "Slice of Life",
        "m_genre_sports": "Sports Reader",
        "m_genre_supernatural": "Supernatural Read",
        "m_genre_thriller": "Thriller Reader",
        "m_genre_psychological": "Psyche Reader",
        "m_genre_isekai": "Isekai Reader",
        "m_genre_shounen": "Shounen Reader",
        "m_genre_ecchi": "Ecchi Reader",
        "m_genre_mahou_shoujo": "Mahou Reader",
        "m_genre_mecha": "Mecha Reader",
        "m_genre_music": "Music Reader",
        "m_tag_isekai_new": "New World Read",
        "m_tag_harem": "Harem Read",
        "m_tag_bl": "BL Reader",
        "m_tag_gl": "GL Reader",
        "m_tag_historical": "History Reader",
        "m_tag_military": "Military Read",
        "m_tag_school": "School Reader",
        "m_tag_martial_arts": "Martial Reader",
        "m_tag_vampire": "Vampire Read",
        "m_tag_samurai": "Samurai Read",
        "m_tag_space": "Space Reader",
        "m_tag_parody": "Parody Reader",
        "m_tag_idol": "Idol Reader",
        "m_tag_post_apocalyptic": "Post-Apocalypse",
        "m_tag_cyberpunk": "Cyberpunk Read",
        "m_tag_shoujo": "Shoujo Reader",
        "m_tag_survival": "Survival Read",
        "m_tag_cooking": "Cooking Reader",
        "m_tag_medical": "Medical Reader",
        "m_tag_villainess": "Villainess Read",

        // ── MANGA COMPLETION ──
        "m_completionist": "Completionist",
        "m_mega_completionist": "Mega Complete",
        "m_completion_rate_50": "Halfway Read",
        "m_completion_rate_75": "Almost Read",
        "m_completion_rate_90": "Nearly Done",
        "m_no_drop": "No Drops",
        "m_long_runner_complete": "Long Runner",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean List",
        "m_from_ptr": "Backlog Cleared",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Read",
        "m_revival": "Revival Read",
        "m_zero_to_hundred": "Zero to Hero",
        "m_five_genre_complete": "Five Genres",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Clear",
        "m_paused_to_done": "Resumed Done",
        "m_completion_spree": "Spree Clear",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi-Reread",
        "m_dropped_recovery": "Drop Recovery",
        "m_ten_perfect_scores": "Ten Perfects",
        "m_complete_genre_span": "Genre Span",
        "m_monthly_completions": "Monthly Clears",
        "m_yearly_completions": "Yearly Clears",
        "m_rapid_complete": "Rapid Finish",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Fan",
        "m_rereader": "Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Fan",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Fan",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyalty",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Fave Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Franchise Buff",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Master",
        "m_multi_series_author": "Multi-Author Fan",
        "m_format_diversity": "Format Diversity",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Explorer",
        "m_decade_hopper": "Decade Hopper",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Pick",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross-Demographic",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Variety Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Taste",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Niche Explorer",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre",
        "m_year_completionist": "Year Complete",
        "m_unpopular_opinion": "Rebel Opinion",
        "m_top_rated_reader": "Top Rated",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Explorer",
        "m_long_manga_explorer": "Long Explorer",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl",
        "m_early_bird": "Early Bird",
        "m_lunch_reader": "Lunch Reader",
        "m_commute_reader": "Commute Reader",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All Hours",
        "m_prime_time_reader": "Prime Time",
        "m_workday_reader": "Workday Reader",
        "m_sunday_read": "Sunday Read",
        "m_morning_routine": "Morning Read",
        "m_night_shift_reader": "Night Shift",
        "m_seasonal_premier_read": "New Release",
        "m_clock_collector": "Clock Collector",
        "m_late_night_horror": "Midnight Horror",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Hour",
        "m_dawn_reader": "Dawn Reader",
        "m_twilight_reader": "Twilight Read",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Hours",
        "m_late_night_regular": "Late Night",
        "m_sunrise_reader": "Sunrise Read",
        "m_every_day_of_week": "Every Day",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Read",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Story",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Read",
        "m_cross_media": "Cross Media",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collab Reader",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Streak",
        "m_mega_streak": "Mega Streak",
        "m_weekly_warrior": "Weekly Warrior",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Comeback Arc",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Will",
        "m_habit_formed": "Habit Formed",
        "m_consistent_pace": "Steady Pace",
        "m_year_long": "Year-Long Streak",
        "m_double_streak": "Double Streak",
        "m_streak_recovery": "Streak Recovery",
        "m_daily_minimum": "Daily Minimum",
        "m_winter_streak": "Winter Streak",
        "m_summer_streak": "Summer Streak",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Streak",
        "m_unbreakable": "Unbreakable",
        "m_eternal_flame": "Eternal Flame",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Completion Chain",
        "m_rating_streak": "Rating Chain",
        "m_multi_ch_streak": "Multi-Ch Streak",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manga Critic",
        "m_perfect_ten": "Perfect Ten",
        "m_harsh_critic": "Harsh Critic",
        "m_fair_judge": "Fair Judge",
        "m_generous_spirit": "Generous Spirit",
        "m_score_all": "Score All",
        "m_wide_range": "Wide Range",
        "m_controversial": "Controversial",
        "m_consistent_scorer": "Consistent Scorer",
        "m_score_sniper": "Score Sniper",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Picky Reader",
        "m_100_rated": "Hundred Rated",
        "m_500_rated": "Five Hundred Rated",
        "m_mediocre_majority": "Middle Ground",
        "m_rating_spree": "Rating Spree",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Hunt",
        "m_contrarian": "Contrarian",
        "m_optimist": "Optimist",
        "m_score_distributor": "Score Spread",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Vow",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day",
        "m_april_fools": "April Fools",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Solstice",
        "m_tanabata": "Tanabata Wish",
        "m_friday_13th": "Friday 13th",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thanksgiving Read",
        "m_christmas_read": "Christmas Read",
        "m_new_years_eve": "New Year's Eve",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Marathon",
        "m_independence_day": "Independence Day",
        "m_culture_day": "Culture Festival",
        "m_spring_equinox": "Spring Equinox",
        "m_earth_day": "Earth Day",
        "m_labor_day": "Labor Day",
        "m_winter_solstice": "Winter Solstice",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "Every Holiday",
        "m_consecutive_holidays": "Holiday Streak",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number",
        "m_fibonacci": "Fibonacci Read",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven",
        "m_thousand_complete": "Thousand Done",
        "m_nice": "Nice",
        "m_power_level_chapters": "Power Level",
        "m_answer_42": "Answer: 42",
        "m_square_number": "Square Number",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Date Match",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Synchronicity",
        "m_world_record": "World Record",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time Traveler",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Match",
        "m_chapter_match_date": "Chapter Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Unlock",
        "m_meta_collector": "Badge Collector",
        "m_meta_category_starter": "Category Start",
        "m_meta_tier_climber": "Tier Climber",
        "m_meta_tier_max": "Max Tier",
        "m_meta_xp_earner": "XP Earner",
        "m_meta_difficulty_easy": "Easy Mode",
        "m_meta_difficulty_hard": "God Mode",
        "m_meta_unlock_spree": "Unlock Spree",
        "m_meta_completionist": "Meta Complete",
        "m_meta_diverse": "Diverse Meta",
        "m_meta_dominator": "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#0a0800",
        primary: "#ffc800",
        secondary: "#d7aa00",
        accent: "#aa8700",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        sos_sparks: { label: "SOS Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 60 },
        hair_ribbon: { label: "Hair Ribbon", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        closed_space_orbs: { label: "Closed Space Orbs", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        melancholy_glow: { label: "Melancholy Glow", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Normal Student",
        5:   "SOS Member",
        15:  "Brigade Chief",
        30:  "Slider",
        45:  "Esper Ally",
        60:  "Time Traveler",
        80:  "Data Entity",
        100: "God of the World",
    },
}
