import { AnimeThemeConfig } from "./types"
import {
    GiCoffin,
    GiCrossedPistols,
    GiBullets,
    GiBat,
    GiChainedHeart,
    GiResize,
    GiSettingsKnobs,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiChurch,
    GiMoon,
    GiSkullCrossedBones,
    GiAnvilImpact,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const hellsingTheme: AnimeThemeConfig = {
    id: "hellsing",
    displayName: "Hellsing",
    description: "The bird of Hermes is my name. Crimson-soaked interface channeling Alucard, the Hellsing Organization, and the eternal war against the undead.",
    fontFamily: "'Pirata One', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Pirata+One&display=swap",
    cssVars: {
        // Brand → deep crimson blood-red
        "--color-brand-200": "230 120 120",
        "--color-brand-300": "215 80 80",
        "--color-brand-400": "200 45 45",
        "--color-brand-500": "180 20 20",
        "--color-brand-600": "150 14 14",
        "--color-brand-700": "120 10 10",
        "--color-brand-800": "90 6 6",
        "--color-brand-900": "60 4 4",
        "--color-brand-950": "35 2 2",
        "--brand": "180 20 20",
        // Near-black with blood undertone
        "--background": "#0a0204",
        "--paper": "#140408",
        "--color-gray-950": "10 2 4",
        "--color-gray-900": "20 4 8",
        "--color-gray-800": "35 10 16",
        "--color-gray-700": "55 20 28",
        "--color-gray-600": "80 35 42",
        "--color-gray-500": "110 55 65",
        "--color-gray-400": "145 85 95",
        "--color-gray-300": "175 125 135",
        "--color-gray-200": "205 165 172",
        "--color-gray-100": "230 208 212",
        "--color-gray-50": "245 235 237",
    },
    sidebarOverrides: {
        "home": { icon: GiCoffin, label: "Hellsing Manor" },
        "schedule": { icon: GiAlarmClock, label: "Midnight Orders" },
        "manga": { icon: LuBookOpen, label: "Blood Archives" },
        "lists": { icon: GiCrossedPistols, label: "Target Dossiers" },
        "discover": { icon: GiMoon, label: "Night Hunt" },
        "torrent-list": { icon: GiBullets, label: "Silver Rounds" },
        "debrid": { icon: GiBat, label: "Bat Swarm" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Souls" },
        "enmasse": { icon: GiResize, label: "Ghoul Purge" },
        "scan-summaries": { icon: TbReportSearch, label: "Recon Intel" },
        "auto-downloader": { icon: LuRss, label: "Blood Signal" },
        "community": { icon: GiChurch, label: "Iscariot Vatican" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Night Alerts" },
        "achievements": { icon: GiTrophy, label: "Blood Trophies" },
        "theme-manager": { icon: GiPalette, label: "Crimson Palette" },
        "extensions": { icon: BiExtension, label: "Dark Augments" },
        "sync": { icon: IoCloudOfflineOutline, label: "Coffin Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Control Art" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Blood",
        "a_episode_counter": "Kill Tally",
        "a_episode_titan": "Elder Vampire",
        "a_hours_invested": "Eternal Vigil",
        "a_time_lord": "Immortal Hours",
        "a_anime_collector": "Arsenal Vault",
        "a_library_legend": "Hellsing Archives",
        "a_first_complete": "Mission Cleared",
        "a_hundred_club": "Century Kills",
        "a_first_day": "Enlistment Night",
        "a_first_rating": "Target Assessed",
        "a_ten_thousand_min": "Ten Thousand Nights",
        "a_season_veteran": "Veteran Hunter",
        "a_year_explorer": "Year of Darkness",
        "a_century_watcher": "Hundred Hunts",
        "a_five_hundred_eps": "Five Hundred Fangs",
        "a_thousand_eps": "Thousand Souls",
        "a_watching_ten": "Ten Fronts",
        "a_ptw_hoarder": "Coffin Stockpile",
        "a_dropped_honesty": "Merciful Release",
        "a_five_thousand_eps": "Five Thousand Dead",
        "a_ten_completed": "Ten Purges",
        "a_fifty_completed": "Fifty Exterminations",
        "a_five_hundred_completed": "Mass Extermination",
        "a_mean_score_tracker": "Combat Rating",
        "a_unique_studios": "Allied Orders",
        "a_days_spent_watching": "Days in Darkness",
        "a_all_status": "All Deployments",
        "a_first_favorite": "Blood Bond",
        "a_favorites_collector": "Crimson Collection",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Blood Frenzy",
        "a_marathon_runner": "Nightlong Hunt",
        "a_weekend_warrior": "Weekend Carnage",
        "a_non_stop": "Relentless Thirst",
        "a_one_more_episode": "One More Kill",
        "a_speed_run": "Silver Blitz",
        "a_double_feature": "Double Tap",
        "a_triple_threat": "Triple Fang",
        "a_five_a_day": "Five Kills Daily",
        "a_back_to_back": "Consecutive Strikes",
        "a_seasonal_binge": "Full Campaign",
        "a_cour_crusher": "Cour Crusher",
        "a_half_day_watch": "Half-Night Vigil",
        "a_full_day_watch": "Full Night Vigil",
        "a_power_weekend": "Bloody Weekend",
        "a_binge_king": "Binge Nosferatu",
        "a_no_sleep": "Sleepless Undead",
        "a_entire_season": "Rapid Annihilation",
        "a_seven_day_challenge": "Seven Night Hunt",
        "a_hundred_day_binge": "Hundred Night Siege",
        "a_genre_binge": "Cross-Genre Feeding",
        "a_studio_binge": "Studio Bloodbath",
        "a_season_sweep": "Season Purge",
        "a_forty_eight_hour": "Forty-Eight Hours",
        "a_ep_counter_day": "Daily Body Count",
        "a_multi_series_binge": "Multi-Front War",
        "a_midnight_binge": "Midnight Feast",
        "a_new_year_binge": "New Year Bloodlust",

        // ── ANIME GENRES ──
        "a_genre_action": "Gun Specialist",
        "a_genre_adventure": "Dark Expedition",
        "a_genre_comedy": "Gallows Humor",
        "a_genre_drama": "Crimson Drama",
        "a_genre_fantasy": "Occult Fantasy",
        "a_genre_horror": "True Horror",
        "a_genre_mystery": "Shadow Mystery",
        "a_genre_romance": "Forbidden Blood",
        "a_genre_scifi": "Dark Technology",
        "a_genre_sol": "Night Life",
        "a_genre_sports": "Combat Training",
        "a_genre_supernatural": "Supernatural Power",
        "a_genre_thriller": "Vampire Pursuit",
        "a_genre_mecha": "War Machine",
        "a_genre_music": "Requiem Mass",
        "a_genre_psychological": "Broken Psyche",
        "a_genre_ecchi": "Midnight Temptation",
        "a_genre_mahou_shoujo": "Dark Sorcery",
        "a_tag_isekai": "Other Realm",
        "a_tag_harem": "Servant Bonds",
        "a_tag_bl": "Brothers Damned",
        "a_tag_gl": "Sisters Cursed",
        "a_tag_historical": "Ancient History",
        "a_tag_military": "Military Order",
        "a_tag_school": "Night Academy",
        "a_tag_martial_arts": "Fang Combat",
        "a_tag_vampire": "True Kindred",
        "a_tag_samurai": "Blade Master",
        "a_tag_space": "Void Beyond",
        "a_tag_parody": "Bloody Parody",
        "a_tag_idol": "Dark Idol",
        "a_tag_post_apocalyptic": "After Millennium",
        "a_tag_cyberpunk": "Neon Darkness",
        "a_tag_shounen": "Young Blood",
        "a_tag_seinen": "Mature Darkness",
        "a_tag_shoujo": "Crimson Heart",
        "a_tag_josei": "Dark Elegance",
        "a_tag_survival": "Undead Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Dossier",
        "a_mega_completionist": "Supreme Vampire",
        "a_completion_rate_50": "Halfway Dead",
        "a_completion_rate_75": "Nearing Undeath",
        "a_completion_rate_90": "Almost Immortal",
        "a_no_drop": "No Mercy Shown",
        "a_long_runner_complete": "Long Campaign",
        "a_sequel_chain": "Chain of Souls",
        "a_clean_list": "Clean Service",
        "a_from_ptw": "Orders Executed",
        "a_rewatch_master": "Memory Replay",
        "a_short_complete": "Quick Kill",
        "a_same_day_start_finish": "Same Night Kill",
        "a_revival": "Undead Revival",
        "a_zero_to_hero": "Ghoul to King",
        "a_five_genre_complete": "Five-Genre Mastery",
        "a_full_franchise": "Full Intel File",
        "a_batch_complete": "Batch Execution",
        "a_paused_to_done": "Back from Grave",
        "a_completion_spree": "Killing Spree",
        "a_multi_rewatch": "Eternal Rewatch",
        "a_dropped_recovery": "Recovered Soul",
        "a_ten_perfect_scores": "Ten Perfect Kills",
        "a_seasonal_clear": "Seasonal Purge",
        "a_complete_genre_span": "All-Terrain Hunter",
        "a_monthly_completions": "Monthly Reports",
        "a_yearly_completions": "Yearly Crusade",
        "a_rapid_complete": "Lightning Raid",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Servant",
        "a_studio_devotee": "Studio Devotee",
        "a_rewatcher": "Night Rewatch",
        "a_triple_rewatch": "Triple Rewatch",
        "a_annual_tradition": "Annual Ritual",
        "a_director_fan": "Director's Vision",
        "a_voice_actor_fan": "Voice of Night",
        "a_ost_lover": "Dark Requiem",
        "a_source_reader": "Original Texts",
        "a_waiting_weekly": "Weekly Vigil",
        "a_childhood_revisit": "Return to Crypt",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Loyal Darkness",
        "a_decade_watcher": "Decade Undead",
        "a_adaptation_hunter": "Adaptation Hunt",
        "a_original_anime_fan": "Original Broadcast",
        "a_long_commitment": "Eternal Commitment",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Full Catalog",
        "a_franchise_collector": "Franchise Collector",
        "a_airing_follower": "Currently Airing",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Staff Dossier",
        "a_multi_season_fan": "Multi-Season Vet",
        "a_format_diversity": "Diverse Formats",
        "a_year_dedication": "Year of Blood",
        "a_season_dedication": "Season of Darkness",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Shadow Explorer",
        "a_studio_hopper": "Studio Transfer",
        "a_tag_explorer": "Tag Recon",
        "a_decade_hopper": "Decade Hopper",
        "a_hidden_gem": "Hidden Crypt",
        "a_popular_taste": "Popular Blood",
        "a_retro_appreciator": "Retro Nosferatu",
        "a_modern_viewer": "Modern Vampire",
        "a_cross_demographic": "Cross Demographic",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Hunts",
        "a_foreign_cinema": "Foreign Intel",
        "a_classic_connoisseur": "Classic Connoisseur",
        "a_every_season": "Every Season",
        "a_award_winner": "Blood Medal",
        "a_niche_explorer": "Niche Territory",
        "a_global_anime": "Global Alliance",
        "a_cult_classic": "Cult Classic",
        "a_random_pick": "Random Assignment",
        "a_new_genre_month": "New Terrain",
        "a_seasonal_completionist": "Seasonal Clear",
        "a_unpopular_opinion": "Heretical Opinion",
        "a_top_rated_viewer": "Top-Rated Intel",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Descent",
        "a_upcoming_watcher": "Upcoming Intel",
        "a_short_series_explorer": "Short Skirmish",
        "a_long_series_explorer": "Long Crusade",

        // ── ANIME TIME ──
        "a_night_owl": "Night Owl",
        "a_early_bird": "Dawn Patrol",
        "a_lunch_break": "Midday Rest",
        "a_golden_hour": "Golden Dusk",
        "a_four_am_club": "4 AM Sentry",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Oath",
        "a_midnight_premiere": "Midnight Premiere",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Shade",
        "a_prime_time": "Prime Darkness",
        "a_workday_watcher": "On-Duty Watcher",
        "a_sunday_marathon": "Sunday Bloodbath",
        "a_rainy_day": "Rainy Night",
        "a_morning_routine": "Morning Ritual",
        "a_night_shift": "Night Shift",
        "a_twilight_zone": "Twilight Zone",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge",
        "a_late_night_regular": "Late Night Regular",
        "a_sunrise_watcher": "Sunrise Retreat",
        "a_holiday_watcher": "Holiday Guard",
        "a_every_day_of_week": "Every Night",
        "a_monthly_hours": "Monthly Vigil",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Gathering",
        "a_party_host": "Coven Master",
        "a_social_butterfly": "Social Predator",
        "a_group_binge": "Group Feeding",
        "a_party_regular": "Regular Attendant",
        "a_sync_viewer": "Synchronized Hunt",
        "a_commentator": "Battle Narrator",
        "a_party_marathon": "Marathon Coven",
        "a_full_house": "Full Assembly",
        "a_community_pillar": "Pillar of Night",
        "a_watch_party_streak": "Coven Streak",
        "a_diverse_party": "Diverse Coven",
        "a_late_night_party": "Late Night Coven",
        "a_party_veteran": "Veteran Host",
        "a_genre_party": "Cross-Genre Coven",
        "a_weekly_party": "Weekly Gathering",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Dark Recommendation",
        "a_party_completionist": "Coven Completionist",
        "a_social_scorer": "Social Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Fibonacci Blood",
        "a_palindrome_day": "Palindrome Night",
        "a_binary_day": "Binary Darkness",
        "a_full_moon": "Full Moon",
        "a_leap_year": "Leap Year",
        "a_time_traveler": "Time Immortal",
        "a_genre_clash": "Genre Clash",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Slain",
        "a_pi_episodes": "Pi Calculation",
        "a_synchronicity": "Blood Synchronicity",
        "a_world_record": "World Record",
        "a_nice": "Nice Count",
        "a_power_level": "Alucard's Power",
        "a_answer_42": "Answer Forty-Two",
        "a_square_number": "Perfect Formation",
        "a_prime_count": "Prime Kills",
        "a_matching_date": "Matching Date",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast",
        "a_movie_buff": "Film Operative",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Operative",
        "a_short_king": "Short King",
        "a_variety_pack": "All Formats",
        "a_film_festival": "Film Festival",
        "a_music_video": "Dark Anthem",
        "a_tv_short": "Quick Recon",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Dark Anthology",
        "a_mini_series": "Mini Campaign",
        "a_theatrical": "Theatrical Night",
        "a_format_master": "Format Master",
        "a_long_movie": "Feature Length",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "Commercial Watcher",
        "a_pv_collector": "Preview Collector",
        "a_format_balance": "Balanced Formats",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Film",
        "a_recap_watcher": "Recap Briefing",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Nightly Streak",
        "a_mega_streak": "Mega Bloodstreak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Patrol",
        "a_comeback": "Return from Hell",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Rest Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Consistent March",
        "a_year_long": "Year-Long Hunt",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable Will",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Episode Streak",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Blood Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Harsh Judgment",
        "a_fair_judge": "Fair Judge",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Full Evaluation",
        "a_wide_range": "Wide Range",
        "a_controversial": "Heretical Score",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Casull Sniper",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Selective Hunter",
        "a_100_rated": "Century Rated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Variable Scores",
        "a_masterpiece_hunter": "Masterpiece Hunter",
        "a_contrarian": "Contrarian Blood",
        "a_optimist": "Dark Optimist",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Vow",
        "a_valentines_weeb": "Valentine Fang",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Fools",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "Empire Day",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Night",
        "a_friday_13th": "Friday Thirteenth",
        "a_halloween_spirit": "Halloween Spirit",
        "a_thanksgiving_binge": "Thanksgiving Feast",
        "a_christmas_special": "Midwinter Blood",
        "a_new_years_eve": "New Year's Eve",
        "a_birthday_watch": "Birthday Hunt",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Independence Night",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Equinox",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Day",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anime Anniversary",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Consecutive Holidays",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Awakening",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Initiation",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Max Rank",
        "a_meta_xp_earner": "Blood XP",
        "a_meta_difficulty_easy": "Easy Hunt",
        "a_meta_difficulty_hard": "Legendary Hunt",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Completionist",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter",
        "m_chapter_counter": "Chapter Tally",
        "m_chapter_titan": "Elder Chapter",
        "m_reading_hours": "Reading Vigil",
        "m_reading_time_lord": "Immortal Reader",
        "m_manga_collector": "Manuscript Vault",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Tome Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "First Reading Night",
        "m_first_rating": "Manuscript Assessed",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Stockpile",
        "m_year_explorer": "Year Reading Dark",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Read",
        "m_thousand_ch": "Thousand Consumed",
        "m_reading_ten": "Ten Manuscripts",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Retreat",
        "m_season_reader": "Season Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Tomes Done",
        "m_fifty_completed": "Fifty Tomes Done",
        "m_five_hundred_completed": "Mass Completion",
        "m_mean_score_tracker": "Average Rating",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Favorites Vault",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Reading Frenzy",
        "m_marathon_reader": "Reading Marathon",
        "m_weekend_reader": "Weekend Reading",
        "m_non_stop_reading": "Non-Stop Pages",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Reading",
        "m_double_story": "Double Story",
        "m_triple_read": "Triple Reading",
        "m_five_a_day": "Five Daily Reads",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Night Read",
        "m_full_day_read": "Full Night Read",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge Nosferatu",
        "m_no_sleep_read": "Sleepless Reading",
        "m_full_series_rush": "Full Series Rush",
        "m_seven_day_challenge": "Seven Night Read",
        "m_hundred_day_read": "Hundred Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Feeding",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Count",
        "m_multi_series_binge": "Multi-Series Binge",
        "m_midnight_binge": "Midnight Reading",
        "m_new_year_binge": "New Year Reading",
        "m_forty_eight_hour": "Forty-Eight Hours",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Manuscript",
        "m_genre_adventure": "Dark Adventure",
        "m_genre_comedy": "Gallows Comedy",
        "m_genre_drama": "Blood Drama",
        "m_genre_fantasy": "Occult Reading",
        "m_genre_horror": "Horror Manuscript",
        "m_genre_mystery": "Shadow Mystery",
        "m_genre_romance": "Forbidden Romance",
        "m_genre_scifi": "Dark Sci-Fi",
        "m_genre_sol": "Night Slice",
        "m_genre_sports": "Combat Sports",
        "m_genre_supernatural": "Supernatural Read",
        "m_genre_thriller": "Thriller Dossier",
        "m_genre_psychological": "Psyche Warfare",
        "m_genre_isekai": "Other World",
        "m_genre_shounen": "Young Blood Read",
        "m_genre_ecchi": "Temptation Read",
        "m_genre_mahou_shoujo": "Dark Magic Read",
        "m_genre_mecha": "War Machine Read",
        "m_genre_music": "Requiem Pages",
        "m_tag_isekai_new": "New Realm Read",
        "m_tag_harem": "Servant Bonds Read",
        "m_tag_bl": "Damned Brothers",
        "m_tag_gl": "Cursed Sisters",
        "m_tag_historical": "Ancient Read",
        "m_tag_military": "Military Read",
        "m_tag_school": "Night School",
        "m_tag_martial_arts": "Fang Combat Read",
        "m_tag_vampire": "True Kindred Read",
        "m_tag_samurai": "Blade Read",
        "m_tag_space": "Void Reading",
        "m_tag_parody": "Bloody Parody Read",
        "m_tag_idol": "Dark Idol Read",
        "m_tag_post_apocalyptic": "Post-War Read",
        "m_tag_cyberpunk": "Neon Dark Read",
        "m_tag_shoujo": "Crimson Heart Read",
        "m_tag_survival": "Undead Survival Read",
        "m_tag_cooking": "Blood Recipes",
        "m_tag_medical": "Field Medic Read",
        "m_tag_villainess": "Villainess Read",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manuscript",
        "m_mega_completionist": "Supreme Reader",
        "m_completion_rate_50": "Halfway Consumed",
        "m_completion_rate_75": "Nearing Completion",
        "m_completion_rate_90": "Almost Done",
        "m_no_drop": "No Drop Policy",
        "m_long_runner_complete": "Long Runner Done",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean Record",
        "m_from_ptr": "Orders Read",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Specialist",
        "m_same_day_start_finish": "Same Night Read",
        "m_revival": "Undead Reader",
        "m_zero_to_hundred": "Zero to Hundred",
        "m_five_genre_complete": "Five Genre Clear",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Cleared",
        "m_paused_to_done": "Back from Grave",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi Reread",
        "m_dropped_recovery": "Recovered Read",
        "m_ten_perfect_scores": "Ten Perfect Reads",
        "m_complete_genre_span": "All-Genre Reader",
        "m_monthly_completions": "Monthly Completions",
        "m_yearly_completions": "Yearly Completions",
        "m_rapid_complete": "Rapid Completion",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Devotee",
        "m_rereader": "Night Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Ritual Read",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Devotee",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Fan",
        "m_waiting_weekly": "Weekly Blood Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyalty",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "Novel Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Eternal Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Favorite Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Franchise Vault",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Master",
        "m_multi_series_author": "Multi-Series Author",
        "m_format_diversity": "Format Diversity",
        "m_year_dedication": "Year Dedication",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Genre Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Recon Read",
        "m_decade_hopper": "Decade Hopper Read",
        "m_hidden_gem": "Hidden Crypt Read",
        "m_popular_taste": "Popular Taste",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross Demographic",
        "m_underdog_fan": "Underdog Reader",
        "m_variety_week": "Varied Week Read",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Manuscript",
        "m_award_winner": "Award Winner Read",
        "m_niche_explorer": "Niche Explorer",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic Read",
        "m_random_pick": "Random Pick Read",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Completionist",
        "m_unpopular_opinion": "Heretical Read",
        "m_top_rated_reader": "Top-Rated Reader",
        "m_source_variety": "Source Variety Read",
        "m_low_score_brave": "Brave Low Score",
        "m_short_manga_explorer": "Short Manga Read",
        "m_long_manga_explorer": "Long Manga Read",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Midday Reader",
        "m_commute_reader": "Commute Reader",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All Hours Read",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Reading",
        "m_morning_routine": "Morning Reading",
        "m_night_shift_reader": "Night Shift Read",
        "m_seasonal_premier_read": "New Release Read",
        "m_clock_collector": "Clock Collector Read",
        "m_late_night_horror": "Midnight Horror Read",
        "m_afternoon_reader": "Afternoon Reader",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Reading",
        "m_twilight_reader": "Twilight Reader",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Binge Read",
        "m_late_night_regular": "Late Night Reader",
        "m_sunrise_reader": "Sunrise Reader",
        "m_every_day_of_week": "Every Day Read",
        "m_monthly_hours": "Monthly Hours Read",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color Read",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Reader",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel Reader",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Narrator",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award-Winning Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross Media",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collab Reader",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Nightly Read Streak",
        "m_mega_streak": "Mega Read Streak",
        "m_weekly_warrior": "Weekly Reader",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader's Return",
        "m_weekend_streak": "Weekend Read Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Will Read",
        "m_habit_formed": "Reading Habit",
        "m_consistent_pace": "Consistent Pace",
        "m_year_long": "Year-Long Reading",
        "m_double_streak": "Double Read Streak",
        "m_streak_recovery": "Streak Recovery Read",
        "m_daily_minimum": "Daily Minimum Read",
        "m_winter_streak": "Winter Read Streak",
        "m_summer_streak": "Summer Read Streak",
        "m_morning_streak": "Morning Read Streak",
        "m_night_streak": "Night Read Streak",
        "m_unbreakable": "Unbreakable Reader",
        "m_eternal_flame": "Eternal Knowledge",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Read Streak",
        "m_completion_streak": "Completion Streak",
        "m_rating_streak": "Rating Read Streak",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Read Week",
        "m_diverse_streak": "Diverse Read Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manuscript Critic",
        "m_perfect_ten": "Perfect Ten Read",
        "m_harsh_critic": "Harsh Reader",
        "m_fair_judge": "Fair Judge Read",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Full Assessment",
        "m_wide_range": "Wide Range Read",
        "m_controversial": "Controversial Read",
        "m_consistent_scorer": "Consistent Read Score",
        "m_score_sniper": "Jackal Sniper",
        "m_evolving_taste": "Evolving Reader",
        "m_bell_curve": "Bell Curve Read",
        "m_picky_reader": "Selective Reader",
        "m_100_rated": "Century Rated Read",
        "m_500_rated": "Five Hundred Read",
        "m_mediocre_majority": "Middle Ground Read",
        "m_rating_spree": "Rating Spree Read",
        "m_score_variance": "Score Variance Read",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Read",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimist Reader",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Critic Read",
        "m_mean_above_8": "Elite Read Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Read Vow",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Fools Read",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Solstice Reading",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Friday 13th Read",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thanksgiving Read",
        "m_christmas_read": "Midwinter Reading",
        "m_new_years_eve": "New Year Eve Read",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Read Run",
        "m_independence_day": "Independence Read",
        "m_culture_day": "Culture Day Read",
        "m_spring_equinox": "Spring Equinox Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Winter Solstice Read",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "Every Holiday Read",
        "m_consecutive_holidays": "Consecutive Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Read",
        "m_fibonacci": "Fibonacci Chapters",
        "m_palindrome_day": "Palindrome Read",
        "m_binary_day": "Binary Read Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven Read",
        "m_thousand_complete": "Thousand Complete",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Power Level Read",
        "m_answer_42": "Answer Forty-Two Read",
        "m_square_number": "Square Number Read",
        "m_prime_count": "Prime Count Read",
        "m_matching_date": "Matching Date Read",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Blood Sync Read",
        "m_world_record": "World Record Read",
        "m_genre_clash": "Genre Clash Read",
        "m_time_traveler": "Time Traveler Read",
        "m_double_digits": "Double Digits Read",
        "m_one_two_three": "One Two Three Read",
        "m_lucky_seven": "Lucky Seven Read",
        "m_exact_hundred_ch": "Exact Hundred Read",
        "m_year_match_count": "Year Match Read",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master Read",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Read Unlock",
        "m_meta_collector": "Read Badge Vault",
        "m_meta_category_starter": "Category Started",
        "m_meta_tier_climber": "Read Rank Up",
        "m_meta_tier_max": "Max Read Rank",
        "m_meta_xp_earner": "Blood XP Read",
        "m_meta_difficulty_easy": "Easy Read",
        "m_meta_difficulty_hard": "Legendary Read",
        "m_meta_unlock_spree": "Unlock Spree Read",
        "m_meta_completionist": "Meta Read Complete",
        "m_meta_diverse": "Diverse Read",
        "m_meta_dominator": "Meta Read Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#0a0204",
        primary: "#b41414",
        secondary: "#960e0e",
        accent: "#e07878",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/hellsing.jpg",
    particleColor: "#c02020",
    backgroundDim: 0.3,
    backgroundBlur: 20,
    particleTypes: {
        blood_rain: { label: "Blood Rain", maxCount: 16, defaultEnabled: true, defaultIntensity: 60 },
        bullet_trails: { label: "Bullet Trails", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        bat_swarm: { label: "Bat Swarm", maxCount: 12, defaultEnabled: true, defaultIntensity: 50 },
        pentagram_glow: { label: "Pentagram Glow", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Civilian",
        5:   "Recruit",
        15:  "Agent",
        30:  "Draculina",
        45:  "True Vampire",
        60:  "No Life King",
        80:  "Cromwell",
        100: "Alucard",
    },
}
