import { AnimeThemeConfig } from "./types"
import {
    GiVillage,
    GiSickle,
    GiCycle,
    GiDeathSkull,
    GiCrossedSwords,
    GiBrokenSkull,
    GiFist,
    GiScrollQuill,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const higurashiTheme: AnimeThemeConfig = {
    id: "higurashi",
    displayName: "Higurashi: When They Cry",
    description: "Oyashiro-sama is watching. Crimson-drenched interface woven with Hinamizawa's endless summer, cursed loops, and the club's desperate struggle against fate.",
    fontFamily: "'Creepster', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Creepster&display=swap",
    cssVars: {
        // Brand → dark blood red
        "--color-brand-200": "210 130 130",
        "--color-brand-300": "190 90 90",
        "--color-brand-400": "165 50 50",
        "--color-brand-500": "140 20 20",
        "--color-brand-600": "115 15 15",
        "--color-brand-700": "90 10 10",
        "--color-brand-800": "65 8 8",
        "--color-brand-900": "42 5 5",
        "--color-brand-950": "22 2 2",
        "--brand": "140 20 20",
        // Dark horror background
        "--background": "#080304",
        "--paper": "#100608",
        "--color-gray-950": "8 3 4",
        "--color-gray-900": "16 6 8",
        "--color-gray-800": "28 14 18",
        "--color-gray-700": "45 25 30",
        "--color-gray-600": "68 42 48",
        "--color-gray-500": "98 68 75",
        "--color-gray-400": "138 108 115",
        "--color-gray-300": "175 150 156",
        "--color-gray-200": "208 192 196",
        "--color-gray-100": "232 222 225",
        "--color-gray-50": "246 240 242",
    },
    sidebarOverrides: {
        "home": { icon: GiVillage, label: "Hinamizawa" },
        "schedule": { icon: GiAlarmClock, label: "Fragment Schedule" },
        "manga": { icon: LuBookOpen, label: "Curse Archives" },
        "lists": { icon: GiSickle, label: "Club Roster" },
        "discover": { icon: GiBullseye, label: "Beyond the Dam" },
        "torrent-list": { icon: GiAnvilImpact, label: "Offering Drops" },
        "debrid": { icon: GiCycle, label: "Loop Operations" },
        "unmatched": { icon: GiBrokenSkull, label: "Lost Souls" },
        "enmasse": { icon: GiResize, label: "Mass Outbreak" },
        "scan-summaries": { icon: TbReportSearch, label: "Autopsy Reports" },
        "auto-downloader": { icon: LuRss, label: "Cicada Signals" },
        "community": { icon: GiDeathSkull, label: "Village Council" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Shrine Bells" },
        "achievements": { icon: GiTrophy, label: "Sin Ledger" },
        "theme-manager": { icon: GiPalette, label: "Fragment Colors" },
        "extensions": { icon: BiExtension, label: "Curse Tools" },
        "sync": { icon: IoCloudOfflineOutline, label: "Timeline Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ritual Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Night in Hinamizawa",
        "a_episode_counter": "Cicada Kill Count",
        "a_episode_titan": "Curse-Class Episode",
        "a_hours_invested": "Hours Under Curse",
        "a_time_lord": "Oyashiro's Memories",
        "a_anime_collector": "Ritual Tool Collector",
        "a_library_legend": "Rika's Library Legend",
        "a_first_complete": "First Fragment Complete",
        "a_hundred_club": "Hundred Cursed Nights",
        "a_first_day": "Transfer Day",
        "a_first_rating": "Villager Evaluation",
        "a_ten_thousand_min": "Ten Thousand Cursed Minutes",
        "a_season_veteran": "Veteran Looper",
        "a_year_explorer": "Year Lost in Loops",
        "a_century_watcher": "Hundred-Episode Curse",
        "a_five_hundred_eps": "Five Hundred Fragments",
        "a_thousand_eps": "Thousand Dark Cycles",
        "a_watching_ten": "Ten Fronts Unraveling",
        "a_ptw_hoarder": "Shrine Offering Hoarder",
        "a_dropped_honesty": "Abandoned Fragment",
        "a_five_thousand_eps": "Five Thousand Screams",
        "a_ten_completed": "Ten Arcs Survived",
        "a_fifty_completed": "Fifty Rituals Complete",
        "a_five_hundred_completed": "Five Hundred Sins Atoned",
        "a_mean_score_tracker": "Average Curse Rating",
        "a_unique_studios": "Allied Shrines",
        "a_days_spent_watching": "Days Under Oyashiro",
        "a_all_status": "All Curse Statuses",
        "a_first_favorite": "First Village Bond",
        "a_favorites_collector": "Bonds of the Club",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Hysteria",
        "a_marathon_runner": "Dusk-to-Dawn Marathon",
        "a_weekend_warrior": "Weekend Villager",
        "a_non_stop": "Relentless Paranoia",
        "a_one_more_episode": "One More Fragment",
        "a_speed_run": "Cleaver Dash",
        "a_double_feature": "Double Curse Night",
        "a_triple_threat": "Triple Victim Count",
        "a_five_a_day": "Five Sins a Day",
        "a_back_to_back": "Back-to-Back Loops",
        "a_seasonal_binge": "Full Curse Arc",
        "a_cour_crusher": "Village Crusher",
        "a_half_day_watch": "Half-Day Vigil",
        "a_full_day_watch": "Full Day Cursed",
        "a_power_weekend": "Power Weekend Madness",
        "a_binge_king": "King of Despair",
        "a_no_sleep": "Sleepless in Hinamizawa",
        "a_entire_season": "Rapid Fragment Clear",
        "a_seven_day_challenge": "Seven-Day Curse",
        "a_hundred_day_binge": "Hundred-Day Siege",
        "a_genre_binge": "Cross-Curse Training",
        "a_studio_binge": "Allied Shrine Binge",
        "a_season_sweep": "Season Purge",
        "a_forty_eight_hour": "Forty-Eight Hour Psychosis",
        "a_ep_counter_day": "Daily Sin Count",
        "a_multi_series_binge": "Multi-Fragment Binge",
        "a_midnight_binge": "Midnight Ritual Watch",
        "a_new_year_binge": "New Year's Outbreak",

        // ── ANIME GENRES ──
        "a_genre_action": "Cleaver Specialist",
        "a_genre_adventure": "Beyond the Village",
        "a_genre_comedy": "Club Game Moment",
        "a_genre_drama": "Satoko's Tears",
        "a_genre_fantasy": "Miracle Fragment",
        "a_genre_horror": "Hinamizawa Horror",
        "a_genre_mystery": "Dam Conspiracy",
        "a_genre_romance": "Heart of the Shrine",
        "a_genre_scifi": "Syndrome Science",
        "a_genre_sol": "Life in the Village",
        "a_genre_sports": "Club Penalty Games",
        "a_genre_supernatural": "Oyashiro's Power",
        "a_genre_thriller": "Paranoia Pursuit",
        "a_genre_mecha": "Ritual Weaponry",
        "a_genre_music": "Higurashi no Naku",
        "a_genre_psychological": "Rena's Inner Demons",
        "a_genre_ecchi": "Hot Spring Episode",
        "a_genre_mahou_shoujo": "Miracle Witch Rika",
        "a_tag_isekai": "Transported to Hinamizawa",
        "a_tag_harem": "Club Bonds",
        "a_tag_bl": "Brothers in Madness",
        "a_tag_gl": "Cotton Drifting Sisters",
        "a_tag_historical": "Village History",
        "a_tag_military": "Curse Enforcement",
        "a_tag_school": "Village School",
        "a_tag_martial_arts": "Bat Combat Style",
        "a_tag_vampire": "Blood Curse Line",
        "a_tag_samurai": "Cleaver Blade Style",
        "a_tag_space": "Beyond the Curse",
        "a_tag_parody": "Club Game Parody",
        "a_tag_idol": "Shrine Maiden Idol",
        "a_tag_post_apocalyptic": "Post-Disaster Village",
        "a_tag_cyberpunk": "Syndrome Tech",
        "a_tag_shounen": "Keiichi's Will",
        "a_tag_seinen": "Harsh Village Truth",
        "a_tag_shoujo": "Mion's Devotion",
        "a_tag_josei": "Takano's Obsession",
        "a_tag_survival": "Survival in Hinamizawa",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Fragment Report",
        "a_mega_completionist": "Curse Breaker",
        "a_completion_rate_50": "Halfway Through the Loop",
        "a_completion_rate_75": "Approaching the Truth",
        "a_completion_rate_90": "Miracle Nearly Reached",
        "a_no_drop": "No Soul Left Behind",
        "a_long_runner_complete": "Long Curse Endurance",
        "a_sequel_chain": "Fragment Chain Link",
        "a_clean_list": "Clean Village Record",
        "a_from_ptw": "Offering Accepted",
        "a_rewatch_master": "Memory Replay Loop",
        "a_short_complete": "Quick Ritual Victory",
        "a_same_day_start_finish": "Same-Day Exorcism",
        "a_revival": "Revived by Miracle",
        "a_zero_to_hero": "Victim to Savior",
        "a_five_genre_complete": "Five-Branch Curse Mastery",
        "a_full_franchise": "Full Shrine Dossier",
        "a_batch_complete": "Batch Ritual Clear",
        "a_paused_to_done": "Returned from Madness",
        "a_completion_spree": "Completion Bloodbath",
        "a_multi_rewatch": "Multi-Loop Replay",
        "a_dropped_recovery": "Escaped the Curse",
        "a_ten_perfect_scores": "Ten Perfect Rituals",
        "a_seasonal_clear": "Seasonal Fragment Clear",
        "a_complete_genre_span": "All-Terrain Villager",
        "a_monthly_completions": "Monthly Curse Reports",
        "a_yearly_completions": "Yearly Campaign Victor",
        "a_rapid_complete": "Lightning Exorcism",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Shrine Keeper",
        "a_studio_devotee": "Studio DEEN Devotee",
        "a_rewatcher": "Curse Rewatch Loop",
        "a_triple_rewatch": "Triple Fragment Rewatch",
        "a_annual_tradition": "Annual Watanagashi",
        "a_director_fan": "Director's Dark Vision",
        "a_voice_actor_fan": "Voice of the Cursed",
        "a_ost_lover": "Dear You Listener",
        "a_source_reader": "Ryukishi07's Texts",
        "a_waiting_weekly": "Weekly Cicada Wait",
        "a_childhood_revisit": "Return to Hinamizawa",
        "a_saga_tracker": "Saga of Fragments",
        "a_genre_loyalty": "Curse Loyalty Badge",
        "a_decade_watcher": "Decade-Long Cursed",
        "a_adaptation_hunter": "Adaptation Hunt",
        "a_original_anime_fan": "Original Broadcast Victim",
        "a_long_commitment": "Long-Term Curse Duty",
        "a_perfect_attendance": "Perfect Club Attendance",
        "a_favorite_studio_5": "Five Cursed Studios",
        "a_complete_catalog": "Complete Curse Catalog",
        "a_franchise_collector": "Higurashi Collector",
        "a_airing_follower": "Currently Airing Curse",
        "a_genre_master": "Genre Curse Mastered",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Season Looper",
        "a_format_diversity": "Diverse Curse Formats",
        "a_year_dedication": "Year of Devotion",
        "a_season_dedication": "Season of Suffering",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Village",
        "a_studio_hopper": "Shrine Transfer",
        "a_tag_explorer": "Tag Curse Mission",
        "a_decade_hopper": "Decade Loop Hop",
        "a_hidden_gem": "Hidden Ritual Site",
        "a_popular_taste": "Popular Among Villagers",
        "a_retro_appreciator": "Pre-Dam Era Watcher",
        "a_modern_viewer": "Modern Fragment Viewer",
        "a_cross_demographic": "Cross-Curse Scout",
        "a_underdog_fan": "Underdog Village Spirit",
        "a_variety_week": "Week of Varied Sins",
        "a_foreign_cinema": "Foreign Horror Cinema",
        "a_classic_connoisseur": "Classic Horror Master",
        "a_every_season": "Every Season Cursed",
        "a_award_winner": "Shrine Medal",
        "a_niche_explorer": "Niche Curse Explorer",
        "a_global_anime": "Global Village Entry",
        "a_cult_classic": "Cult Classic Curse",
        "a_random_pick": "Random Fate Assignment",
        "a_new_genre_month": "New Curse Monthly",
        "a_seasonal_completionist": "Seasonal Purge Clear",
        "a_unpopular_opinion": "Unpopular Village Opinion",
        "a_top_rated_viewer": "Top-Rated Horror Source",
        "a_source_variety": "Source Curse Variety",
        "a_low_score_brave": "Brave Descent",
        "a_upcoming_watcher": "Upcoming Fragment Intel",
        "a_short_series_explorer": "Short Horror Explorer",
        "a_long_series_explorer": "Long Curse Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Owl Watcher",
        "a_early_bird": "Dawn Village Patrol",
        "a_lunch_break": "Lunch Break Calm",
        "a_golden_hour": "Golden Hour Sunset",
        "a_four_am_club": "4 AM Cicada Cry",
        "a_witching_hour": "Oyashiro's Witching Hour",
        "a_new_year_watch": "New Year's Shrine Visit",
        "a_midnight_premiere": "Midnight Curse Premiere",
        "a_all_hours": "All-Hours Paranoia",
        "a_dawn_warrior": "Dawn Survivor",
        "a_afternoon_delight": "Afternoon Club Game",
        "a_prime_time": "Prime Time Horror",
        "a_workday_watcher": "On-Duty Watcher",
        "a_sunday_marathon": "Sunday Ritual Marathon",
        "a_rainy_day": "Rainy Day Curse",
        "a_morning_routine": "Morning Village Walk",
        "a_night_shift": "Night Shift Paranoia",
        "a_twilight_zone": "Twilight Hinamizawa",
        "a_seasonal_premier": "Season Premiere Curse",
        "a_clock_collector": "Clock Tower Collector",
        "a_weekend_binge_hours": "Weekend Binge Horror",
        "a_late_night_regular": "Late Night Ritual",
        "a_sunrise_watcher": "Sunrise Over the Dam",
        "a_holiday_watcher": "Holiday Shrine Duty",
        "a_every_day_of_week": "Every Day Cursed",
        "a_monthly_hours": "Monthly Curse Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Club Meeting",
        "a_party_host": "Club President",
        "a_social_butterfly": "Village Socialite",
        "a_group_binge": "Group Penalty Game",
        "a_party_regular": "Regular Club Member",
        "a_sync_viewer": "Synchronized Scream",
        "a_commentator": "Village Commentator",
        "a_party_marathon": "Marathon Club Session",
        "a_full_house": "Full Club Assembled",
        "a_community_pillar": "Pillar of Hinamizawa",
        "a_watch_party_streak": "Consecutive Club Streak",
        "a_diverse_party": "Diverse Club Party",
        "a_late_night_party": "Late Night Club Game",
        "a_party_veteran": "Veteran Club Leader",
        "a_genre_party": "Cross-Genre Club",
        "a_weekly_party": "Weekly Club Gathering",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Village Recommendation",
        "a_party_completionist": "Club Completionist",
        "a_social_scorer": "Social Curse Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Curse Count",
        "a_fibonacci": "Fibonacci Fragment",
        "a_palindrome_day": "Palindrome Loop Day",
        "a_binary_day": "Binary Curse Day",
        "a_full_moon": "Full Moon Watanagashi",
        "a_leap_year": "Leap Year Time Loop",
        "a_time_traveler": "Rika's Time Travel",
        "a_genre_clash": "Horror Genre Clash",
        "a_triple_seven": "Triple Seven Sins",
        "a_thousand_complete": "Thousand Curses Broken",
        "a_pi_episodes": "Pi Curse Calculation",
        "a_synchronicity": "Fragment Synchronicity",
        "a_world_record": "World Record Loops",
        "a_nice": "Nice Curse Count",
        "a_power_level": "Oyashiro Power Level",
        "a_answer_42": "Answer to the Curse",
        "a_square_number": "Perfect Ritual Square",
        "a_prime_count": "Prime Curse Count",
        "a_matching_date": "Matching Fate Date",
        "a_century_episode": "Century Episode Curse",
        "a_double_digits": "Double Digit Sins",
        "a_one_two_three": "Question Answer Arc",
        "a_lucky_seven": "Seven Lucky Survivors",
        "a_all_tens": "All Tens Curse Score",
        "a_exact_hundred_eps": "Exact Hundred Fragments",
        "a_year_match_count": "Year Match Curse",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Cursed",
        "a_movie_buff": "Horror Film Night",
        "a_ova_hunter": "OVA Curse Hunter",
        "a_ona_explorer": "ONA Fragment Scout",
        "a_special_watcher": "Special Ritual Watcher",
        "a_short_king": "Short Scream King",
        "a_variety_pack": "All-Format Curse",
        "a_film_festival": "Horror Film Festival",
        "a_music_video": "Dear You Collection",
        "a_tv_short": "Quick Horror Clip",
        "a_movie_marathon": "Movie Marathon Curse",
        "a_double_length": "Double-Length Fragment",
        "a_anthology": "Curse Anthology",
        "a_mini_series": "Mini Curse Series",
        "a_theatrical": "Theatrical Horror",
        "a_format_master": "Format Curse Master",
        "a_long_movie": "Feature-Length Nightmare",
        "a_back_catalog": "Back Catalog Curses",
        "a_cm_watcher": "Commercial Watcher",
        "a_pv_collector": "Preview Curse Signal",
        "a_format_balance": "Balanced Curse Formats",
        "a_episodic_master": "Episodic Horror Master",
        "a_sequel_movie": "Sequel Curse Film",
        "a_recap_watcher": "Recap Ritual Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Curse Streak",
        "a_mega_streak": "Mega Loop Streak",
        "a_weekly_warrior": "Weekly Village Warrior",
        "a_monthly_watcher": "Monthly Shrine Duty",
        "a_comeback": "Return from Madness",
        "a_weekend_streak": "Weekend Curse Streak",
        "a_no_zero_days": "No Zero Cursed Days",
        "a_iron_will": "Iron Will Survivor",
        "a_habit_formed": "Curse Habit Formed",
        "a_consistent_pace": "Consistent March Forward",
        "a_year_long": "Year-Long Curse",
        "a_double_streak": "Double Streak Madness",
        "a_streak_recovery": "Sanity Recovery",
        "a_daily_minimum": "Daily Minimum Offering",
        "a_winter_streak": "Winter Curse Streak",
        "a_summer_streak": "Summer Cicada Streak",
        "a_morning_streak": "Morning Village Streak",
        "a_night_streak": "Night Patrol Streak",
        "a_unbreakable": "Unbreakable Rika's Will",
        "a_eternal_flame": "Eternal Shrine Flame",
        "a_completion_streak": "Completion Curse Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Fragment Streak",
        "a_genre_streak": "Genre Curse Streak",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Week Survived",

        // ── ANIME SCORING ──
        "a_critic": "Village Tribunal Judge",
        "a_perfect_ten": "Perfect Ten Ritual",
        "a_harsh_critic": "Mion's Harsh Judgment",
        "a_fair_judge": "Rika's Fair Sight",
        "a_generous_spirit": "Generous Villager",
        "a_score_all": "Full Curse Evaluation",
        "a_wide_range": "Wide Range Judgment",
        "a_controversial": "Controversial Verdict",
        "a_consistent_scorer": "Consistent Evaluator",
        "a_score_sniper": "Precision Curse Sniper",
        "a_evolving_taste": "Evolving Fragment Taste",
        "a_bell_curve": "Bell Curve of Curses",
        "a_picky_watcher": "Selective Observer",
        "a_100_rated": "Century of Verdicts",
        "a_500_rated": "Five Hundred Judgments",
        "a_mediocre_majority": "Middle Ground Cursed",
        "a_rating_spree": "Rating Bloodbath",
        "a_score_variance": "Variable Curse Ratings",
        "a_masterpiece_hunter": "Masterpiece Curse Hunter",
        "a_contrarian": "Contrarian Villager",
        "a_optimist": "Optimist Despite Curses",
        "a_score_distributor": "Score Shrine Keeper",
        "a_genre_critic": "Genre Horror Critic",
        "a_mean_above_8": "Elite Curse Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Shrine Vow",
        "a_valentines_weeb": "Valentine's Curse Bond",
        "a_pi_day": "Pi Day Fragment Calc",
        "a_april_fools": "April Fools Trick",
        "a_international_anime_day": "International Curse Day",
        "a_star_wars_day": "Shrine Empire Day",
        "a_summer_solstice": "Summer Solstice Ritual",
        "a_tanabata": "Tanabata Shrine Wish",
        "a_friday_13th": "Friday 13th Curse",
        "a_halloween_spirit": "Watanagashi Halloween",
        "a_thanksgiving_binge": "Harvest Feast Binge",
        "a_christmas_special": "Midwinter Curse Special",
        "a_new_years_eve": "New Year's Eve Vigil",
        "a_birthday_watch": "Birthday Curse Watch",
        "a_holiday_marathon": "Holiday Ritual Marathon",
        "a_independence_day": "Village Liberation Day",
        "a_culture_day": "Hinamizawa Culture Day",
        "a_spring_equinox": "Spring Equinox Rite",
        "a_earth_day": "Protect the Village Day",
        "a_labor_day": "Village Labor Day",
        "a_winter_solstice": "Winter Solstice Curse",
        "a_anime_birthday": "Anime Curse Anniversary",
        "a_every_holiday": "Every Holiday Cursed",
        "a_consecutive_holidays": "Consecutive Ritual Days",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Sin Awakened",
        "a_meta_collector": "Shrine Badge Collector",
        "a_meta_category_starter": "Curse Initiation Rite",
        "a_meta_tier_climber": "Village Rank Promotion",
        "a_meta_tier_max": "Shrine Maiden Rank",
        "a_meta_xp_earner": "XP from Curses",
        "a_meta_difficulty_easy": "Easy Penalty Game",
        "a_meta_difficulty_hard": "Legendary Curse Loop",
        "a_meta_unlock_spree": "Unlock Curse Spree",
        "a_meta_completionist": "Meta Curse Completionist",
        "a_meta_diverse": "Diverse Curse Portfolio",
        "a_meta_dominator": "Meta Fragment Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter of Sin",
        "m_chapter_counter": "Chapter Curse Counter",
        "m_chapter_titan": "Chapter Curse Assault",
        "m_reading_hours": "Hours Reading Curses",
        "m_reading_time_lord": "Oyashiro's Reading Memory",
        "m_manga_collector": "Curse Archive Collector",
        "m_library_legend": "Rika's Book Legend",
        "m_first_complete": "First Manga Fragment Done",
        "m_hundred_club": "Hundred-Chapter Curse",
        "m_first_day": "First Day Reading Sins",
        "m_first_rating": "First Manuscript Verdict",
        "m_ten_thousand_pages": "Ten Thousand Cursed Pages",
        "m_volume_collector": "Volume Curse Stockpile",
        "m_year_explorer": "Year of Manga Curses",
        "m_century_reader": "Century-Chapter Cursed",
        "m_five_hundred_ch": "Five Hundred Dark Chapters",
        "m_thousand_ch": "Thousand-Chapter Curse",
        "m_reading_ten": "Ten Manuscripts Cursed",
        "m_ptr_hoarder": "Reading Curse Hoarder",
        "m_dropped_honesty": "Honest Curse Retreat",
        "m_season_reader": "Seasonal Curse Reading",
        "m_active_reader": "Active Curse Reader",
        "m_five_thousand_ch": "Five Thousand Pages Deep",
        "m_ten_completed": "Ten Manga Curses Done",
        "m_fifty_completed": "Fifty Curse Arcs Done",
        "m_five_hundred_completed": "Five Hundred Sins Read",
        "m_mean_score_tracker": "Average Manuscript Curse",
        "m_unique_authors": "Unique Cursed Authors",
        "m_all_status": "All Reading Statuses",
        "m_first_favorite": "First Manga Curse Bond",
        "m_favorites_collector": "Manga Curse Favorites",
        "m_days_spent_reading": "Days in Cursed Archive",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading Horror",
        "m_marathon_reader": "Dusk-to-Dawn Reading",
        "m_weekend_reader": "Weekend Curse Reading",
        "m_non_stop_reading": "Non-Stop Page Terror",
        "m_one_more_chapter": "One More Dark Chapter",
        "m_speed_read": "Cleaver Speed Read",
        "m_double_story": "Double Curse Story",
        "m_triple_read": "Triple Horror Read",
        "m_five_a_day": "Five Reads a Day",
        "m_chapter_chain": "Chapter Curse Chain",
        "m_volume_binge": "Volume Horror Binge",
        "m_power_reader": "Power Curse Reader",
        "m_half_day_read": "Half-Day Archive Dive",
        "m_full_day_read": "Full-Day Curse Study",
        "m_power_weekend": "Power Weekend Horror",
        "m_binge_king": "King of Horror Binge",
        "m_no_sleep_read": "Sleepless Curse Reading",
        "m_full_series_rush": "Full Series Curse Rush",
        "m_seven_day_challenge": "Seven-Day Curse Read",
        "m_hundred_day_read": "Hundred-Day Reading Siege",
        "m_volume_rush": "Volume Curse Deployment",
        "m_series_sweep": "Series Purge Reading",
        "m_genre_binge": "Cross-Curse Maneuver",
        "m_author_binge": "Author Curse Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Curse",
        "m_multi_series_binge": "Multi-Curse Reading",
        "m_midnight_binge": "Midnight Curse Session",
        "m_new_year_binge": "New Year's Horror Read",
        "m_forty_eight_hour": "Forty-Eight Hour Terror",
        "m_oneshot_binge": "Oneshot Horror Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Horror Specialist",
        "m_genre_adventure": "Adventure Beyond Village",
        "m_genre_comedy": "Club Game Comedy",
        "m_genre_drama": "Drama of the Cursed",
        "m_genre_fantasy": "Fantasy of Fragments",
        "m_genre_horror": "Hinamizawa Horror Manga",
        "m_genre_mystery": "Mystery of the Dam",
        "m_genre_romance": "Romance Under Curse",
        "m_genre_scifi": "Sci-Fi Syndrome Manga",
        "m_genre_sol": "Slice of Village Life",
        "m_genre_sports": "Club Game Sports",
        "m_genre_supernatural": "Supernatural Curse Powers",
        "m_genre_thriller": "Thriller Paranoia Manga",
        "m_genre_psychological": "Psychological Horror Read",
        "m_genre_isekai": "Isekai Fragment Manga",
        "m_genre_shounen": "Shounen Curse Heart",
        "m_genre_ecchi": "Hot Springs Chapter",
        "m_genre_mahou_shoujo": "Miracle Witch Manga",
        "m_genre_mecha": "Ritual Weapon Blueprints",
        "m_genre_music": "Higurashi Song Manga",
        "m_tag_isekai_new": "New Cursed World",
        "m_tag_harem": "Club Bonds Manga",
        "m_tag_bl": "Brothers in Sin Manga",
        "m_tag_gl": "Shrine Sisters Manga",
        "m_tag_historical": "Village History Manga",
        "m_tag_military": "Curse Force Manga",
        "m_tag_school": "Village School Manga",
        "m_tag_martial_arts": "Bat Combat Manual",
        "m_tag_vampire": "Blood Curse Manga",
        "m_tag_samurai": "Cleaver Master Manga",
        "m_tag_space": "Beyond the Dam Manga",
        "m_tag_parody": "Chibi Club Manga",
        "m_tag_idol": "Shrine Maiden Manga",
        "m_tag_post_apocalyptic": "Post-Curse Manga",
        "m_tag_cyberpunk": "Syndrome Tech Manga",
        "m_tag_shoujo": "Mion's Story Manga",
        "m_tag_survival": "Village Survival Manga",
        "m_tag_cooking": "Village Feast Cookbook",
        "m_tag_medical": "Clinic Irie Manga",
        "m_tag_villainess": "Takano Villain Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Curse Completionist",
        "m_mega_completionist": "Supreme Curse Breaker",
        "m_completion_rate_50": "Halfway Through Sin",
        "m_completion_rate_75": "Approaching Miracle",
        "m_completion_rate_90": "Final Fragment Near",
        "m_no_drop": "No Manuscript Abandoned",
        "m_long_runner_complete": "Long Curse Endurance",
        "m_sequel_chain": "Sequel Curse Chain",
        "m_clean_list": "Clean Reading Record",
        "m_from_ptr": "Offering Received: Read",
        "m_reread_master": "Memory Loop Reread",
        "m_oneshot_complete": "Oneshot Curse Specialist",
        "m_same_day_start_finish": "Same-Day Horror Blitz",
        "m_revival": "Revival Through Miracle",
        "m_zero_to_hundred": "Victim to Scholar",
        "m_five_genre_complete": "Five-Curse Mastery",
        "m_full_collection": "Full Curse Collection",
        "m_batch_complete": "Batch Curse Clearance",
        "m_paused_to_done": "Back from Hiatus",
        "m_completion_spree": "Completion Curse Barrage",
        "m_format_completionist": "Format Curse Badge",
        "m_catch_up": "Caught Up with Curse",
        "m_multi_reread": "Multi-Loop Reread",
        "m_dropped_recovery": "Recovered from Darkness",
        "m_ten_perfect_scores": "Ten Perfect Curse Scores",
        "m_complete_genre_span": "All-Genre Curse Scout",
        "m_monthly_completions": "Monthly Curse Victories",
        "m_yearly_completions": "Yearly Horror Campaign",
        "m_rapid_complete": "Rapid Exorcism Reading",
        "m_author_complete": "Author's Curse Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Curse Reader",
        "m_mangaka_lover": "Ryukishi07 Devotee",
        "m_rereader": "Curse Loop Rereader",
        "m_triple_reread": "Triple Curse Reread",
        "m_annual_reread": "Annual Watanagashi Reread",
        "m_publisher_fan": "Publisher Curse Fan",
        "m_artist_fan": "Artist Shrine Medal",
        "m_adaptation_compare": "Manga vs Anime Curse",
        "m_source_material_fan": "Source Curse Reader",
        "m_waiting_weekly": "Weekly Chapter Vigil",
        "m_classic_reader": "Classic Curse Reader",
        "m_saga_reader": "Saga of Fragments Reader",
        "m_genre_loyalty": "Genre Curse Medal",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "Light Novel Curse Intel",
        "m_original_work": "Original Curse Work",
        "m_long_commitment": "Long-Term Curse Vow",
        "m_up_to_date": "Up-to-Date with Curses",
        "m_favorite_mangaka": "Favorite Cursed Author",
        "m_complete_portfolio": "Complete Curse Portfolio",
        "m_franchise_collector": "Higurashi Manga Collector",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Curse Mastery",
        "m_multi_series_author": "Multi-Curse Author Fan",
        "m_format_diversity": "Diverse Curse Formats",
        "m_year_dedication": "Year of Devoted Reading",
        "m_ongoing_follower": "Ongoing Curse Follower",
        "m_genre_loyalty_50": "Fifty Genre Curse Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Curse Scout",
        "m_publisher_hopper": "Publisher Shrine Transfer",
        "m_tag_explorer": "Manga Tag Curse Recon",
        "m_decade_hopper": "Decade Loop Reader",
        "m_hidden_gem": "Hidden Ritual Gem",
        "m_popular_taste": "Popular Among Cursed",
        "m_retro_reader": "Retro Curse Appreciator",
        "m_modern_reader": "Modern Fragment Reader",
        "m_cross_demographic": "Cross-Demographic Cursed",
        "m_underdog_fan": "Underdog Villager Fan",
        "m_variety_week": "Week of Varied Curses",
        "m_manhwa_reader": "Manhwa Horror Reader",
        "m_manhua_reader": "Manhua Horror Reader",
        "m_classic_connoisseur": "Classic Horror Manuscript",
        "m_award_winner": "Medal-Winning Curse",
        "m_niche_explorer": "Niche Curse Reader",
        "m_world_manga": "World Curse Intel",
        "m_cult_classic": "Cult Classic Horror",
        "m_random_pick": "Random Fate Reading",
        "m_new_genre_month": "New Curse Genre Monthly",
        "m_year_completionist": "Year Curse Completionist",
        "m_unpopular_opinion": "Unpopular Village Take",
        "m_top_rated_reader": "Top-Rated Horror Source",
        "m_source_variety": "Source Curse Variety",
        "m_low_score_brave": "Brave Dark Descent",
        "m_short_manga_explorer": "Short Horror Manga",
        "m_long_manga_explorer": "Long Curse Manuscript",
        "m_serialization_explorer": "Serialization Curse Scout",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Curse Reader",
        "m_early_bird": "Dawn Village Reader",
        "m_lunch_reader": "Lunch Break Reader",
        "m_commute_reader": "Travel to Village",
        "m_four_am_club": "4 AM Cicada Reader",
        "m_new_year_read": "New Year's Curse Read",
        "m_all_hours": "All-Hours Archive Access",
        "m_prime_time_reader": "Prime Time Horror",
        "m_workday_reader": "On-Duty Curse Reader",
        "m_sunday_read": "Sunday Ritual Reading",
        "m_morning_routine": "Morning Village Reading",
        "m_night_shift_reader": "Night Shift Cursed",
        "m_seasonal_premier_read": "New Release Curse",
        "m_clock_collector": "Clock Tower Reading",
        "m_late_night_horror": "Midnight Horror Read",
        "m_afternoon_reader": "Afternoon Shrine Reading",
        "m_golden_hour_reader": "Golden Hour Reading",
        "m_dawn_reader": "Dawn Curse Reader",
        "m_twilight_reader": "Twilight Village Read",
        "m_midnight_start": "Midnight Reading Curse",
        "m_weekend_binge_hours": "Weekend Horror Binge",
        "m_late_night_regular": "Late Night Curse Read",
        "m_sunrise_reader": "Sunrise Over Dam Reader",
        "m_every_day_of_week": "Every Day Cursed Read",
        "m_monthly_hours": "Monthly Curse Hours",
        "m_bedtime_reader": "Bedtime Horror Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Curse Art Appreciator",
        "m_webtoon_reader": "Webtoon Horror Intel",
        "m_full_color": "Full Color Curse",
        "m_doujin_reader": "Underground Doujin Curse",
        "m_anthology_reader": "Curse Anthology Reader",
        "m_adaptation_reader": "Adaptation Curse Reader",
        "m_longstrip_reader": "Vertical Scroll Horror",
        "m_4koma_reader": "4-Koma Club Shorts",
        "m_oneshot_reader": "Oneshot Curse Reader",
        "m_format_variety": "Format Curse Variety",
        "m_light_novel_reader": "Light Novel Horror",
        "m_novel_reader": "Novel Curse Reader",
        "m_visual_storyteller": "Visual Horror Narrator",
        "m_colored_classic": "Colored Curse Classic",
        "m_webcomic_fan": "Webcomic Horror Fan",
        "m_manga_to_anime": "Manga to Anime Curse",
        "m_seinen_reader": "Seinen Horror Reader",
        "m_josei_reader": "Josei Curse Reader",
        "m_award_winning_art": "Medal-Winning Horror Art",
        "m_debut_work": "Debut Curse Manuscript",
        "m_vertical_scroll": "Vertical Horror Scroll",
        "m_traditional_format": "Traditional Curse Format",
        "m_cross_media": "Cross-Media Horror",
        "m_spinoff_reader": "Spinoff Curse Reader",
        "m_remake_reader": "Remake Curse Reading",
        "m_collaboration_reader": "Joint Curse Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Curse Reading Streak",
        "m_mega_streak": "Mega Horror Reading Streak",
        "m_weekly_warrior": "Weekly Warrior Reader",
        "m_monthly_reader": "Monthly Shrine Reader",
        "m_comeback": "Reader's Curse Return",
        "m_weekend_streak": "Weekend Curse Streak",
        "m_no_zero_days": "No Zero Cursed Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Curse Reading Habit",
        "m_consistent_pace": "Consistent Horror Pace",
        "m_year_long": "Year-Long Curse Reading",
        "m_double_streak": "Double Curse Streak",
        "m_streak_recovery": "Reading Sanity Recovery",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Horror Streak",
        "m_summer_streak": "Summer Cicada Streak",
        "m_morning_streak": "Morning Reading Streak",
        "m_night_streak": "Night Horror Streak",
        "m_unbreakable": "Unbreakable Curse Will",
        "m_eternal_flame": "Eternal Shrine Flame",
        "m_chapter_a_day": "Chapter a Day Cursed",
        "m_genre_streak": "Genre Curse Streak",
        "m_completion_streak": "Completion Curse Chain",
        "m_rating_streak": "Rating Curse Streak",
        "m_multi_ch_streak": "Multi-Chapter Horror",
        "m_author_streak": "Author Curse Dedication",
        "m_perfect_week_manga": "Perfect Cursed Week",
        "m_diverse_streak": "Diverse Horror Streak",

        // ── MANGA SCORING ──
        "m_critic": "Village Manuscript Critic",
        "m_perfect_ten": "Perfect Ten Curse",
        "m_harsh_critic": "Mion's Harsh Standards",
        "m_fair_judge": "Rika's Fair Review",
        "m_generous_spirit": "Generous Cursed Spirit",
        "m_score_all": "Full Curse Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Village Take",
        "m_consistent_scorer": "Consistent Horror Scorer",
        "m_score_sniper": "Precision Curse Sniper",
        "m_evolving_taste": "Evolving Horror Taste",
        "m_bell_curve": "Bell Curve of Sin",
        "m_picky_reader": "Selective Curse Reader",
        "m_100_rated": "Century of Curse Verdicts",
        "m_500_rated": "Five Hundred Sin Ratings",
        "m_mediocre_majority": "Middle Ground Cursed",
        "m_rating_spree": "Rating Horror Barrage",
        "m_score_variance": "Variable Curse Scores",
        "m_binge_rater": "Binge Curse Rating",
        "m_reread_rerate": "Reread & Re-Rate Curse",
        "m_masterpiece_hunter": "Masterpiece Horror Hunter",
        "m_contrarian": "Contrarian Cursed Reader",
        "m_optimist": "Optimist Despite Horrors",
        "m_score_distributor": "Score Shrine Keeper",
        "m_genre_critic": "Genre Horror Critic",
        "m_mean_above_8": "Elite Horror Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Curse Vow",
        "m_valentines_read": "Valentine's Horror Bond",
        "m_pi_day": "Pi Day Curse Calc",
        "m_april_fools": "April Fools Trick Read",
        "m_international_manga_day": "International Curse Day",
        "m_free_comic_day": "Free Curse Comic Day",
        "m_summer_solstice": "Summer Solstice Horror",
        "m_tanabata": "Tanabata Curse Wish",
        "m_friday_13th": "Friday 13th Horror Read",
        "m_halloween_read": "Watanagashi Halloween Read",
        "m_thanksgiving_binge": "Harvest Horror Feast",
        "m_christmas_read": "Midwinter Curse Reading",
        "m_new_years_eve": "New Year's Eve Horror",
        "m_birthday_read": "Birthday Curse Reading",
        "m_holiday_marathon": "Holiday Horror Marathon",
        "m_independence_day": "Village Liberation Read",
        "m_culture_day": "Culture Day Horror",
        "m_spring_equinox": "Spring Equinox Curse",
        "m_earth_day": "Earth Day Village Read",
        "m_labor_day": "Village Labor Reading",
        "m_winter_solstice": "Winter Solstice Horror",
        "m_manga_birthday": "Manga Curse Anniversary",
        "m_every_holiday_reader": "Every Holiday Cursed",
        "m_consecutive_holidays": "Consecutive Curse Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Curse Milestone",
        "m_fibonacci": "Fibonacci Curse Pattern",
        "m_palindrome_day": "Palindrome Loop Read",
        "m_binary_day": "Binary Curse Reading",
        "m_full_moon_read": "Full Moon Horror Read",
        "m_leap_year_read": "Leap Year Curse Read",
        "m_triple_seven": "Triple Seven Curses",
        "m_thousand_complete": "Thousand Curses Read",
        "m_nice": "Nice Curse Chapter",
        "m_power_level_chapters": "Oyashiro-Level Chapters",
        "m_answer_42": "Answer to Reading Curse",
        "m_square_number": "Perfect Curse Square",
        "m_prime_count": "Prime Chapter Curse",
        "m_matching_date": "Matching Curse Date",
        "m_century_chapter": "Century Chapter Horror",
        "m_pi_chapters": "Pi Chapter Curse Calc",
        "m_synchronicity": "Fragment Reading Sync",
        "m_world_record": "World Record Cursed",
        "m_genre_clash": "Genre Horror Clash",
        "m_time_traveler": "Time-Traveling Reader",
        "m_double_digits": "Double Digit Curse",
        "m_one_two_three": "One Two Three Sins",
        "m_lucky_seven": "Seven Lucky Chapters",
        "m_exact_hundred_ch": "Exact Hundred Cursed",
        "m_year_match_count": "Year Match Curse Read",
        "m_chapter_match_date": "Chapter Date Curse",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Curse Specialist",
        "m_manhwa_format": "Manhwa Horror Format",
        "m_manhua_format": "Manhua Horror Format",
        "m_ln_format": "Light Novel Curse",
        "m_oneshot_format": "Oneshot Curse Operative",
        "m_doujin_format": "Doujin Horror Format",
        "m_novel_format": "Novel Curse Format",
        "m_format_master_manga": "Format Horror Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Curse Power Unlocked",
        "m_meta_collector": "Reading Curse Collector",
        "m_meta_category_starter": "Category Curse Initiation",
        "m_meta_tier_climber": "Reading Curse Promotion",
        "m_meta_tier_max": "Maximum Curse Rank",
        "m_meta_xp_earner": "XP from Horror Reading",
        "m_meta_difficulty_easy": "Easy Curse Exercise",
        "m_meta_difficulty_hard": "Legendary Horror Challenge",
        "m_meta_unlock_spree": "Reading Curse Barrage",
        "m_meta_completionist": "Meta Horror Completionist",
        "m_meta_diverse": "Diverse Horror Portfolio",
        "m_meta_dominator": "Meta Curse Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#080304",
        primary: "#8c1414",
        secondary: "#730f0f",
        accent: "#d42020",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/higurashi.png",
    particleColor: "#b03060",
    backgroundDim: 0.3,
    backgroundBlur: 20,
    particleTypes: {
        cicada_swarm: { label: "Cicada Swarm", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        curse_mist: { label: "Curse Mist", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        cleaver_gleam: { label: "Cleaver Gleam", maxCount: 6, defaultEnabled: true, defaultIntensity: 45 },
        cotton_drift: { label: "Cotton Drift", maxCount: 10, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Transfer Student",
        5:   "Club Member",
        15:  "Cursed",
        30:  "Paranoid",
        45:  "Loop Aware",
        60:  "Sin Bearer",
        80:  "Rika's Will",
        100: "When They Cry",
    },
}
