import { AnimeThemeConfig } from "./types"
import { GiSchoolBag, GiHeartKey, GiPaintBrush, GiDramaMasks, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const horimiyaTheme: AnimeThemeConfig = {
    id: "horimiya",
    displayName: "Horimiya",
    description: "Popular student Kyouko Hori and quiet loner Izumi Miyamura each hide secret sides of themselves — when they accidentally discover each other's true faces outside school, an unexpected friendship blossoms into romance.",
    fontFamily: "'M PLUS 1p', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 210 175",
        "--color-brand-300": "248 180 130",
        "--color-brand-400": "235 148 82",
        "--color-brand-500": "215 112 35",
        "--color-brand-600": "178 80 8",
        "--color-brand-700": "135 52 2",
        "--color-brand-800": "88 30 0",
        "--color-brand-900": "46 14 0",
        "--color-brand-950": "20 5 0",
        "--brand": "215 112 35",
        "--background": "#060300",
        "--paper": "#0e0800",
        "--color-gray-950": "6 3 0",
        "--color-gray-900": "12 8 2",
        "--color-gray-800": "22 14 5",
        "--color-gray-700": "36 24 10",
        "--color-gray-600": "58 40 18",
        "--color-gray-500": "92 65 32",
        "--color-gray-400": "132 100 58",
        "--color-gray-300": "174 142 98",
        "--color-gray-200": "208 180 140",
        "--color-gray-100": "230 210 178",
        "--color-gray-50": "248 235 215",
    },
    sidebarOverrides: {
        "home": { icon: GiSchoolBag, label: "Katagiri High" },
        "schedule": { icon: GiAlarmClock, label: "School Schedule" },
        "manga": { icon: LuBookOpen, label: "Class Notes" },
        "lists": { icon: GiFlowerEmblem, label: "Friend Registry" },
        "discover": { icon: GiBullseye, label: "New Friends" },
        "torrent-list": { icon: GiPaintBrush, label: "Art Cache" },
        "debrid": { icon: GiDramaMasks, label: "Hidden Store" },
        "unmatched": { icon: GiHeartKey, label: "Lost Moments" },
        "enmasse": { icon: GiResize, label: "School Events" },
        "scan-summaries": { icon: TbReportSearch, label: "School Reports" },
        "auto-downloader": { icon: LuRss, label: "School Feed" },
        "community": { icon: GiSchoolBag, label: "Friend Circle" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "School Alerts" },
        "achievements": { icon: GiTrophy, label: "School Trophies" },
        "milestones": { icon: LuFlag, label: "Couple Goals" },
        "theme-manager": { icon: GiPalette, label: "Warm Orange" },
        "extensions": { icon: BiExtension, label: "School Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "School Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Hori's Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Meeting",
        "a_first_complete": "True Romance",
        "a_hundred_club": "Hundred Chapters",
        "a_time_lord": "School Veteran",
        "a_anime_collector": "Moment Collection",
        "a_library_legend": "Katagiri Archives",
        "a_binge_king": "Romance Marathon",
        "a_no_sleep": "All-Night Chat",
        "a_marathon_runner": "Hori's Dash",
        "a_speed_run": "Miyamura Speed",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Hero Master",
        "a_loyal_fan": "Miyamura's Partner",
        "a_rewatcher": "School Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "None Here",
        "a_genre_adventure": "School Life",
        "a_genre_comedy": "Group Chaos",
        "a_genre_drama": "Miyamura's Past",
        "a_genre_fantasy": "School Dream",
        "a_genre_horror": "None Here",
        "a_genre_romance": "Hori Miyamura",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Hidden Self",
        "a_genre_mecha": "None Here",
        "a_critic": "School Critic",
        "a_perfect_ten": "Perfect Couple",
        "a_harsh_critic": "Hori Standard",
        "a_daily_streak": "Daily School",
        "a_mega_streak": "Endless School",
        "a_year_long": "Full School Year",
        "a_iron_will": "Miyamura's Change",
        "a_hidden_gem": "Hidden Episode",
        "a_cult_classic": "Cozy Classic",
        "a_classic_connoisseur": "2011 Fan",
        "a_new_years_resolution": "New Year Together",
        "a_christmas_special": "Winter Romance",
        "a_meta_tier_max": "Horimiya Legend",
        "a_meta_completionist": "All Arcs",
        "a_sequel_chain": "Piece Anime",
        "a_zero_to_hero": "Lonely to Loved",
        "a_night_owl": "Night Chat",
        "a_early_bird": "Morning School",
        "m_first_chapter": "First Chapter",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Romance Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Horimiya Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "School Return",
        "m_genre_action": "None Here",
        "m_genre_adventure": "School Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Dream Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Truth Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Hidden Depth",
        "m_critic": "School Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "School Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "True Self Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Hero Classic",
        "m_mangaka_lover": "Hero Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Horimiya Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Hero Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060300",
        primary: "#d77023",
        secondary: "#b25008",
        accent: "#6080c8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/horimiya.jpg",
    particleColor: "#e09040",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        warm_leaves: { label: "Warm Leaves", maxCount: 16, defaultEnabled: true, defaultIntensity: 52 },
        heart_confetti: { label: "Heart Confetti", maxCount: 12, defaultEnabled: true, defaultIntensity: 42 },
    },
    milestoneNames: {
        1: "Chance Meeting",
        5: "Hori or Miyamura",
        15: "Secret Keepers",
        30: "True Friends",
        50: "Romance Blooms",
        75: "Couple Confirmed",
        100: "Horimiya Legend",
    },
}
