import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiCrossedSwords,
    GiHorseHead,
    GiChainedHeart,
    GiCompass,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiResize,
    GiSettingsKnobs,
    GiAnvilImpact,
    GiScrollUnfurled,
    GiShield,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const initialDTheme: AnimeThemeConfig = {
    id: "initial-d",
    displayName: "Initial D",
    description: "Eurobeat never stops! Mountain pass mastery, drift techniques, and the legend of the Fujiwara Tofu Shop delivery driver.",
    fontFamily: "'Bebas Neue', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
    cssVars: {
        "--color-brand-200": "185 215 255",
        "--color-brand-300": "130 175 240",
        "--color-brand-400": "70 130 215",
        "--color-brand-500": "0 51 136",
        "--color-brand-600": "0 42 110",
        "--color-brand-700": "0 32 85",
        "--color-brand-800": "0 22 60",
        "--color-brand-900": "0 13 38",
        "--color-brand-950": "0 6 20",
        "--brand": "0 51 136",
        "--background": "#030508",
        "--paper": "#060a12",
        "--color-gray-950": "3 5 8",
        "--color-gray-900": "6 10 18",
        "--color-gray-800": "12 18 32",
        "--color-gray-700": "22 32 52",
        "--color-gray-600": "38 55 80",
        "--color-gray-500": "60 85 118",
        "--color-gray-400": "92 122 162",
        "--color-gray-300": "132 162 198",
        "--color-gray-200": "172 198 225",
        "--color-gray-100": "210 225 240",
        "--color-gray-50": "235 242 250",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Fujiwara Tofu Shop" },
        "schedule": { icon: GiAlarmClock, label: "Night Run Timer" },
        "manga": { icon: LuBookOpen, label: "Driver's Manual" },
        "lists": { icon: GiCrossedSwords, label: "Rival Driver List" },
        "discover": { icon: GiCompass, label: "Mountain Pass Scout" },
        "torrent-list": { icon: GiAnvilImpact, label: "Tofu Delivery Cache" },
        "debrid": { icon: GiHorseHead, label: "Engine Power Lines" },
        "unmatched": { icon: GiChainedHeart, label: "Unmatched Rivals" },
        "enmasse": { icon: GiResize, label: "Team Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Stage Race Intel" },
        "auto-downloader": { icon: LuRss, label: "Race Stage Signals" },
        "community": { icon: GiEagleEmblem, label: "Project D Network" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Race Start Alerts" },
        "achievements": { icon: GiTrophy, label: "Stage Victories" },
        "theme-manager": { icon: GiPalette, label: "Drift Palette" },
        "extensions": { icon: BiExtension, label: "Tuning Extensions" },
        "sync": { icon: IoCloudOfflineOutline, label: "Akagi Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ryosuke's Strategy" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Run on Akagi Mountain",
        "a_episode_counter": "Downhill Pass Count",
        "a_episode_titan": "Full Street Race Engagement",
        "a_hours_invested": "Hours Behind the Wheel",
        "a_time_lord": "Mountain Pass Memories",
        "a_anime_collector": "Racing Arsenal Collector",
        "a_library_legend": "Fujiwara's Racing Legend",
        "a_first_complete": "First Mountain Campaign Complete",
        "a_hundred_club": "Century of Pass Victories",
        "a_first_day": "First Night Delivery Run",
        "a_first_rating": "First Stage Race Rating",
        "a_ten_thousand_min": "Ten Thousand Minutes Drifting",
        "a_season_veteran": "Veteran Mountain Racer",
        "a_year_explorer": "Year of Mountain Exploration",
        "a_century_watcher": "Hundred-Episode Race Watch",
        "a_five_hundred_eps": "Five Hundred Corner Entries",
        "a_thousand_eps": "Thousand Rival Encounters",
        "a_watching_ten": "Ten Mountain Fronts Simultaneously",
        "a_ptw_hoarder": "Unraced Stage Backlog",
        "a_dropped_honesty": "Strategic Pit Stop Retreat",
        "a_five_thousand_eps": "Five Thousand Mountain Runs",
        "a_ten_completed": "Ten Mountain Campaigns Complete",
        "a_fifty_completed": "Fifty Stage Victories",
        "a_five_hundred_completed": "Five Hundred Pass Victories",
        "a_mean_score_tracker": "Average Stage Race Rating",
        "a_unique_studios": "Allied Racing Factions",
        "a_days_spent_watching": "Days on the Mountain Pass",
        "a_all_status": "All Driver Statuses",
        "a_first_favorite": "First Racing Bond",
        "a_favorites_collector": "Rivals Turned Comrades",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Eurobeat Engine",
        "a_marathon_runner": "Mountain-to-Mountain Marathon",
        "a_weekend_warrior": "Weekend Warrior Downhill",
        "a_non_stop": "Relentless Mountain Advance",
        "a_one_more_episode": "One More Downhill Pass",
        "a_speed_run": "AE86 Blitz Mode",
        "a_double_feature": "Double Mountain Stage",
        "a_triple_threat": "Triple Pass Takedown",
        "a_five_a_day": "Five Passes a Day",
        "a_back_to_back": "Back-to-Back Mountain Battles",
        "a_seasonal_binge": "Full Project D Campaign",
        "a_cour_crusher": "Mountain Range Crusher",
        "a_half_day_watch": "Half-Day Night Run",
        "a_full_day_watch": "Full Day of Eurobeat",
        "a_power_weekend": "Power Weekend Racing Offensive",
        "a_binge_king": "Commander of Eurobeat Ops",
        "a_no_sleep": "All-Night Tofu Delivery Run",
        "a_entire_season": "Rapid Mountain Campaign Clear",
        "a_seven_day_challenge": "Seven-Day Racing Reclamation",
        "a_hundred_day_binge": "Hundred-Day Stage Siege",
        "a_genre_binge": "Cross-Team Training",
        "a_studio_binge": "Allied Racing Binge",
        "a_season_sweep": "Mountain Season Sweep",
        "a_forty_eight_hour": "Forty-Eight Hour Mountain Standoff",
        "a_ep_counter_day": "Daily Stage Count",
        "a_multi_series_binge": "Multi-Mountain Campaign",
        "a_midnight_binge": "Midnight Mountain Reconnaissance",
        "a_new_year_binge": "New Year's Full Throttle",

        // ── ANIME GENRES ──
        "a_genre_action": "High-Speed Action Specialist",
        "a_genre_adventure": "Beyond Akagi Mountain",
        "a_genre_comedy": "Itsuki's Comedy Moment",
        "a_genre_drama": "Takumi's Vow",
        "a_genre_fantasy": "Mountain Pass Dimension",
        "a_genre_horror": "Rival Driver Terror",
        "a_genre_mystery": "Secret Downhill Technique",
        "a_genre_romance": "Heart of the Mountain Racer",
        "a_genre_scifi": "AE86 Technology",
        "a_genre_sol": "Life in Akagi Town",
        "a_genre_sports": "Mountain Race Training Grounds",
        "a_genre_supernatural": "God Foot Transformation",
        "a_genre_thriller": "Night Race Pursuit",
        "a_genre_mecha": "Racing Machine Analysis",
        "a_genre_music": "Eurobeat Collection",
        "a_genre_psychological": "Driver's Inner War",
        "a_genre_ecchi": "Gas Station Episode",
        "a_genre_mahou_shoujo": "Drift Technique Wielder",
        "a_tag_isekai": "Transported to Mountain Pass",
        "a_tag_harem": "Racing Team Bonds",
        "a_tag_bl": "Driver Comrades",
        "a_tag_gl": "Racing Sisters",
        "a_tag_historical": "Japanese Mountain Touge History",
        "a_tag_military": "Racing Discipline",
        "a_tag_school": "Usui Technical High School",
        "a_tag_martial_arts": "Drift Fighting Style",
        "a_tag_vampire": "Night Driver",
        "a_tag_samurai": "Mountain Pass Warrior",
        "a_tag_space": "Beyond the Mountain Range",
        "a_tag_parody": "Itsuki's Parody Moment",
        "a_tag_idol": "Mountain Racing Idol",
        "a_tag_post_apocalyptic": "Post-Project D Era",
        "a_tag_cyberpunk": "Racing Tech Mod",
        "a_tag_shounen": "Dedicate Your Downhill Run",
        "a_tag_seinen": "Harsh Reality of Street Racing",
        "a_tag_shoujo": "Natsuki's Devotion",
        "a_tag_josei": "Mogi's Perspective",
        "a_tag_survival": "Survival on the Mountain Pass",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Stage Race Report",
        "a_mega_completionist": "Project D Complete",
        "a_completion_rate_50": "Halfway to Project D",
        "a_completion_rate_75": "Approaching the Final Stage",
        "a_completion_rate_90": "Final Rival Nearly Defeated",
        "a_no_drop": "No Stage Left Unfinished",
        "a_long_runner_complete": "Long Mountain Campaign Endurance",
        "a_sequel_chain": "Operation Mountain Chain",
        "a_clean_list": "Clean Stage Record",
        "a_from_ptw": "Orders from Ryosuke Executed",
        "a_rewatch_master": "Mountain Memory Replay",
        "a_short_complete": "Quick Stage Skirmish Victory",
        "a_same_day_start_finish": "Same-Day Rival Elimination",
        "a_revival": "Revived by Eurobeat",
        "a_zero_to_hero": "Delivery Boy to God Foot",
        "a_five_genre_complete": "Five-Branch Racing Mastery",
        "a_full_franchise": "Full Initial D Dossier",
        "a_batch_complete": "Batch Stage Clear",
        "a_paused_to_done": "Returned from the Mountain",
        "a_completion_spree": "Completion Downhill Strike",
        "a_multi_rewatch": "Multi-Season Mountain Campaign",
        "a_dropped_recovery": "Recovered from Mechanical Failure",
        "a_ten_perfect_scores": "Ten Perfect Stage Scores",
        "a_seasonal_clear": "Seasonal Mountain Clear",
        "a_complete_genre_span": "All-Terrain Racer",
        "a_monthly_completions": "Monthly Stage Reports",
        "a_yearly_completions": "Yearly Mountain Campaign Victor",
        "a_rapid_complete": "Lightning Stage Clear",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Project D Member",
        "a_studio_devotee": "OB/DEEN Studio Devotee",
        "a_rewatcher": "Mountain Recon Rewatch",
        "a_triple_rewatch": "Triple Mountain Expedition Rewatch",
        "a_annual_tradition": "Annual Akagi Night Run",
        "a_director_fan": "Director's Mountain Vision",
        "a_voice_actor_fan": "Voice of the God Foot",
        "a_ost_lover": "Eurobeat Forever",
        "a_source_reader": "Shigeno's Original Manga",
        "a_waiting_weekly": "Weekly Stage Signal Wait",
        "a_childhood_revisit": "Return to Akagi Mountain",
        "a_saga_tracker": "Saga of the Mountain Racer",
        "a_genre_loyalty": "Mountain Loyalty Badge",
        "a_decade_watcher": "Decade-Long Mountain Racer",
        "a_adaptation_hunter": "Adaptation Reconnaissance",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Mountain Duty",
        "a_perfect_attendance": "Perfect Racing Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Mountain Catalog",
        "a_franchise_collector": "Initial D Universe Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Mastery Achieved",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Season Mountain Veteran",
        "a_format_diversity": "Diverse Racing Formats",
        "a_year_dedication": "Year of Dedication to the Mountain",
        "a_season_dedication": "Season of Unwavering Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond the Mountain",
        "a_studio_hopper": "Racing Team Transfer",
        "a_tag_explorer": "Tag Reconnaissance Mission",
        "a_decade_hopper": "Decade-Hopping Mountain Racer",
        "a_hidden_gem": "Hidden Mountain Pass Secret",
        "a_popular_taste": "Popular Among Mountain Racers",
        "a_retro_appreciator": "Pre-AE86 Era Appreciator",
        "a_modern_viewer": "Modern Racing Viewer",
        "a_cross_demographic": "Cross-Demographic Scout",
        "a_underdog_fan": "Underdog Delivery Driver Spirit",
        "a_variety_week": "Week of Varied Mountain Stages",
        "a_foreign_cinema": "Foreign Racing Cinema",
        "a_classic_connoisseur": "Classic Mountain Connoisseur",
        "a_every_season": "Every Stage Completed",
        "a_award_winner": "Medal of the Mountain Pass",
        "a_niche_explorer": "Niche Mountain Explorer",
        "a_global_anime": "Global Racing Alliance",
        "a_cult_classic": "Mountain Cult Classic",
        "a_random_pick": "Random Stage Assignment",
        "a_new_genre_month": "New Mountain Terrain Monthly",
        "a_seasonal_completionist": "Seasonal Mountain Clear",
        "a_unpopular_opinion": "Unpopular Racing Opinion",
        "a_top_rated_viewer": "Top-Rated Stage Intel",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Stage Intel",
        "a_short_series_explorer": "Short Stage Explorer",
        "a_long_series_explorer": "Long Mountain Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Run on Akagi Mountain",
        "a_early_bird": "Dawn Tofu Delivery Run",
        "a_lunch_break": "Gas Station Lunch Break",
        "a_golden_hour": "Golden Hour Mountain View",
        "a_four_am_club": "4 AM Mountain Patrol",
        "a_witching_hour": "Midnight Mountain Hour",
        "a_new_year_watch": "New Year's Downhill Oath",
        "a_midnight_premiere": "Midnight Stage Deployment",
        "a_all_hours": "All-Hours Mountain Racer",
        "a_dawn_warrior": "Dawn Warrior of Akagi Mountain",
        "a_afternoon_delight": "Afternoon Mountain Drill",
        "a_prime_time": "Prime Time Race Engagement",
        "a_workday_watcher": "On-Duty Mountain Watcher",
        "a_sunday_marathon": "Sunday Mountain Marathon",
        "a_rainy_day": "Rainy Day Mountain Run",
        "a_morning_routine": "Morning Mountain Formation",
        "a_night_shift": "Night Shift Mountain Guard",
        "a_twilight_zone": "Twilight Mountain Zone",
        "a_seasonal_premier": "Season Premiere Race",
        "a_clock_collector": "Mountain Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge Mountain Operations",
        "a_late_night_regular": "Late Night Regular Mountain Run",
        "a_sunrise_watcher": "Sunrise Over Akagi Mountain",
        "a_holiday_watcher": "Holiday Mountain Patrol",
        "a_every_day_of_week": "Every Day on the Mountain",
        "a_monthly_hours": "Monthly Mountain Hours Logged",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Racing Formation",
        "a_party_host": "Project D Commander",
        "a_social_butterfly": "Akagi Town Socialite",
        "a_group_binge": "Group Stage Volley",
        "a_party_regular": "Regular Racing Partner",
        "a_sync_viewer": "Synchronized Mountain Maneuver",
        "a_commentator": "Race Battle Commentator",
        "a_party_marathon": "Marathon Mountain Run",
        "a_full_house": "Full Project D Team Assembled",
        "a_community_pillar": "Pillar of the Mountain Racers",
        "a_watch_party_streak": "Consecutive Racing Formation Streak",
        "a_diverse_party": "Diverse Racing Party",
        "a_late_night_party": "Late Night Mountain Party",
        "a_party_veteran": "Veteran Mountain Squad Leader",
        "a_genre_party": "Cross-Genre Racing Formation",
        "a_weekly_party": "Weekly Comrades' Gathering",
        "a_silent_viewer": "Silent Bunta Observer",
        "a_recommendation_giver": "Ryosuke's Recommendation",
        "a_party_completionist": "Party Mountain Completionist",
        "a_social_scorer": "Social Racing Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Mountain Formation",
        "a_fibonacci": "Fibonacci Mountain Stage Sequence",
        "a_palindrome_day": "Palindrome Mountain Time",
        "a_binary_day": "Binary Stage Signal Day",
        "a_full_moon": "Full Moon Mountain Run",
        "a_leap_year": "Leap Year Mountain Time Skip",
        "a_time_traveler": "Mountain Pass Time Traveler",
        "a_genre_clash": "Uphill vs. Downhill Clash",
        "a_triple_seven": "Triple Seven Mountain Passes",
        "a_thousand_complete": "Thousand Victories for Project D",
        "a_pi_episodes": "Pi Mountain Stage Calculation",
        "a_synchronicity": "Mountain Pass Synchronicity",
        "a_world_record": "World Record Stage Victory",
        "a_nice": "Nice Stage Count",
        "a_power_level": "God Foot Power Level",
        "a_answer_42": "The Answer to Takumi's Question",
        "a_square_number": "Perfect Racing Formation",
        "a_prime_count": "Prime Number of Stage Victories",
        "a_matching_date": "Matching Stage Intel Date",
        "a_century_episode": "Century Episode Mountain Assault",
        "a_double_digits": "Double Digit Stage Victories",
        "a_one_two_three": "Stage One Two Three",
        "a_lucky_seven": "Seven Lucky Racers",
        "a_all_tens": "All Tens Racing Score",
        "a_exact_hundred_eps": "Exact Hundred Stage Engagements",
        "a_year_match_count": "Year Match Stage Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Mountain Racer",
        "a_movie_buff": "Initial D Movie Operations",
        "a_ova_hunter": "OVA Mountain Hunter",
        "a_ona_explorer": "ONA Scout Explorer",
        "a_special_watcher": "Special Episode Operative",
        "a_short_king": "Short Stage King",
        "a_variety_pack": "All-Format Racing Corps",
        "a_film_festival": "Mountain Film Festival",
        "a_music_video": "Eurobeat Music Video Collection",
        "a_tv_short": "Quick Recon Clip",
        "a_movie_marathon": "Movie Marathon Blitz",
        "a_double_length": "Double-Length Mountain Operation",
        "a_anthology": "Project D Anthology",
        "a_mini_series": "Mini Mountain Campaign",
        "a_theatrical": "Theatrical Mountain Deployment",
        "a_format_master": "Format Master Mountain Racer",
        "a_long_movie": "Feature-Length Mountain Expedition",
        "a_back_catalog": "Back Catalog Mountain Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Mountain Formats",
        "a_episodic_master": "Episodic Mountain Campaign Master",
        "a_sequel_movie": "Sequel Mountain Operation Film",
        "a_recap_watcher": "Recap Briefing Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Mountain Patrol Streak",
        "a_mega_streak": "Mega Mountain Expedition Streak",
        "a_weekly_warrior": "Weekly Warrior of the Mountain",
        "a_monthly_watcher": "Monthly Mountain Duty",
        "a_comeback": "Return from the Mountain",
        "a_weekend_streak": "Weekend Mountain Sortie Streak",
        "a_no_zero_days": "No Zero Days on the Mountain",
        "a_iron_will": "Iron Will of the Mountain Racer",
        "a_habit_formed": "Mountain Training Regimen Formed",
        "a_consistent_pace": "Consistent Mountain Advance",
        "a_year_long": "Year-Long Mountain Campaign",
        "a_double_streak": "Double Mountain Streak Assault",
        "a_streak_recovery": "Pit Stop Recovery",
        "a_daily_minimum": "Daily Minimum Mountain Duty",
        "a_winter_streak": "Winter Mountain Campaign Streak",
        "a_summer_streak": "Summer Mountain Offensive Streak",
        "a_morning_streak": "Morning Mountain Drill Streak",
        "a_night_streak": "Night Mountain Patrol Streak",
        "a_unbreakable": "Unbreakable Mountain Racer Will",
        "a_eternal_flame": "Eternal Eurobeat Flame",
        "a_completion_streak": "Completion Stage Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Stage Mountain Offensive",
        "a_genre_streak": "Genre Streak Sortie",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Week of Mountain Service",

        // ── ANIME SCORING ──
        "a_critic": "Ryosuke Tribunal Judge",
        "a_perfect_ten": "Perfect 10 Stage Rating",
        "a_harsh_critic": "Ryosuke's Harsh Standards",
        "a_fair_judge": "Bunta's Fair Assessment",
        "a_generous_spirit": "Generous Racing Comrade",
        "a_score_all": "Full Stage Roster Evaluation",
        "a_wide_range": "Wide Range Racing Assessment",
        "a_controversial": "Controversial Mountain Decision",
        "a_consistent_scorer": "Consistent Stage Evaluator",
        "a_score_sniper": "Precision Downhill Sniper",
        "a_evolving_taste": "Evolving Driving Strategy",
        "a_bell_curve": "Bell Curve of Stage Scores",
        "a_picky_watcher": "Selective Mountain Commander",
        "a_100_rated": "Century of Stage Evaluations",
        "a_500_rated": "Five Hundred Mountain Reports",
        "a_mediocre_majority": "Middle Ground Mountain Strategist",
        "a_rating_spree": "Rating Stage Barrage",
        "a_score_variance": "Variable Mountain Ratings",
        "a_masterpiece_hunter": "Masterpiece Mountain Hunter",
        "a_contrarian": "Contrarian Mountain Scout",
        "a_optimist": "Optimist Despite the Rivals",
        "a_score_distributor": "Score Distributor General",
        "a_genre_critic": "Genre Mountain Tactical Critic",
        "a_mean_above_8": "Elite Mountain Combat Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow for the Mountain",
        "a_valentines_weeb": "Valentine's Mountain Dedication",
        "a_pi_day": "Pi Day Stage Calculation",
        "a_april_fools": "April Fools Itsuki Prank",
        "a_international_anime_day": "International Mountain Racer Day",
        "a_star_wars_day": "Rival Empire Day",
        "a_summer_solstice": "Summer Solstice Mountain Expedition",
        "a_tanabata": "Tanabata Wish for the Mountain",
        "a_friday_13th": "Friday 13th Night Run",
        "a_halloween_spirit": "Halloween Mountain Horror",
        "a_thanksgiving_binge": "Thanksgiving Mountain Feast",
        "a_christmas_special": "Midwinter Mountain Festival Special",
        "a_new_years_eve": "New Year's Eve Final Mountain Stand",
        "a_birthday_watch": "Birthday Mountain Watch",
        "a_holiday_marathon": "Holiday Mountain Marathon",
        "a_independence_day": "Mountain Independence Day",
        "a_culture_day": "Touge Culture Day",
        "a_spring_equinox": "Spring Mountain Advance",
        "a_earth_day": "Protect This Mountain World Day",
        "a_labor_day": "Mountain Labor Day",
        "a_winter_solstice": "Winter Solstice Mountain Run",
        "a_anime_birthday": "Anime Anniversary Celebration",
        "a_every_holiday": "Every Holiday Mountain Racer",
        "a_consecutive_holidays": "Consecutive Holiday Stage Deployments",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Downhill Power Awakened",
        "a_meta_collector": "Project D Badge Collector",
        "a_meta_category_starter": "Category Initiation Rite",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "God Foot Rank",
        "a_meta_xp_earner": "XP from Stage Victories",
        "a_meta_difficulty_easy": "Easy Training Stage",
        "a_meta_difficulty_hard": "Legendary Difficulty: Emperor",
        "a_meta_unlock_spree": "Unlock Spree Downhill",
        "a_meta_completionist": "Meta Completionist Mountain Racer",
        "a_meta_diverse": "Diverse Mountain Portfolio",
        "a_meta_dominator": "Meta Dominator of Mountain Passes",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter on Akagi Mountain",
        "m_chapter_counter": "Chapter Stage Counter",
        "m_chapter_titan": "Chapter Mountain Assault",
        "m_reading_hours": "Hours Studying Racing Texts",
        "m_reading_time_lord": "Mountain Reading Memory",
        "m_manga_collector": "Racing Archive Collector",
        "m_library_legend": "Fujiwara Racing Legend",
        "m_first_complete": "First Manga Mountain Journey Done",
        "m_hundred_club": "Hundred-Chapter Stage Club",
        "m_first_day": "First Day of Mountain Reading",
        "m_first_rating": "First Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Stage Intel",
        "m_volume_collector": "Volume Stage Stockpile Collector",
        "m_year_explorer": "Year of Mountain Manga Exploration",
        "m_century_reader": "Century-Chapter Mountain Reader",
        "m_five_hundred_ch": "Five Hundred Chapters of Stages",
        "m_thousand_ch": "Thousand-Chapter Mountain Campaign",
        "m_reading_ten": "Ten Racing Manuscripts at Once",
        "m_ptr_hoarder": "Mountain Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Mountain Retreat",
        "m_season_reader": "Seasonal Stage Reading Rotation",
        "m_active_reader": "Active Mountain Field Reader",
        "m_five_thousand_ch": "Five Thousand Mountain Chapters Deep",
        "m_ten_completed": "Ten Racing Manga Campaigns Complete",
        "m_fifty_completed": "Fifty Stage Manga Missions Done",
        "m_five_hundred_completed": "Five Hundred Stage Manga Victories",
        "m_mean_score_tracker": "Average Mountain Manuscript Rating",
        "m_unique_authors": "Unique Racing Author Encounters",
        "m_all_status": "All Mountain Reading Statuses",
        "m_first_favorite": "First Racing Manga Bond",
        "m_favorites_collector": "Racing Manga Favorites Arsenal",
        "m_days_spent_reading": "Days in the Mountain Archives",

        // ── MANGA BINGE ──
        "m_binge_reader": "Stage Binge Reading Advance",
        "m_marathon_reader": "Mountain-to-Mountain Reading Marathon",
        "m_weekend_reader": "Weekend Mountain Reading",
        "m_non_stop_reading": "Non-Stop Stage Page Turning",
        "m_one_more_chapter": "One More Stage Chapter Charge",
        "m_speed_read": "AE86 Speed Read",
        "m_double_story": "Double Mountain Manuscript Feature",
        "m_triple_read": "Triple Stage Reading Assault",
        "m_five_a_day": "Five Stage Reads a Day",
        "m_chapter_chain": "Stage Chapter Chain Offensive",
        "m_volume_binge": "Volume Mountain Binge Bombardment",
        "m_power_reader": "Power Stage Reader Scout",
        "m_half_day_read": "Half-Day Mountain Archive Dive",
        "m_full_day_read": "Full-Day Stage Manuscript Study",
        "m_power_weekend": "Power Weekend Mountain Reading",
        "m_binge_king": "King of the Mountain Reading Corps",
        "m_no_sleep_read": "All-Night Mountain Reading",
        "m_full_series_rush": "Full Mountain Series Rush Attack",
        "m_seven_day_challenge": "Seven-Day Stage Intel Gathering",
        "m_hundred_day_read": "Hundred-Day Mountain Reading Siege",
        "m_volume_rush": "Mountain Volume Rush Deployment",
        "m_series_sweep": "Mountain Series Sweep Operation",
        "m_genre_binge": "Cross-Genre Mountain Maneuver",
        "m_author_binge": "Shigeno Focused Deep Dive",
        "m_chapter_counter_day": "Daily Stage Chapter Count",
        "m_multi_series_binge": "Multi-Series Mountain Reading Front",
        "m_midnight_binge": "Midnight Mountain Archive Session",
        "m_new_year_binge": "New Year's Mountain Reading Charge",
        "m_forty_eight_hour": "Forty-Eight Hour Mountain Reading Siege",
        "m_oneshot_binge": "Oneshot Stage Blitz Attack",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Stage Manuscript Specialist",
        "m_genre_adventure": "Adventure Beyond Akagi",
        "m_genre_comedy": "Comedy in Akagi Town",
        "m_genre_drama": "Drama of the Mountain Racer",
        "m_genre_fantasy": "Fantasy of the Mountain Pass",
        "m_genre_horror": "Night Racing Horror Manuscript",
        "m_genre_mystery": "Secret Drift Technique Mystery",
        "m_genre_romance": "Romance in Racing World",
        "m_genre_scifi": "Sci-Fi Turbo Technology",
        "m_genre_sol": "Slice of Life in Akagi Town",
        "m_genre_sports": "Mountain Racing Sports",
        "m_genre_supernatural": "God Foot Powers",
        "m_genre_thriller": "Night Stage Thriller Report",
        "m_genre_psychological": "Psychological Mountain Warfare",
        "m_genre_isekai": "Isekai to Mountain Pass",
        "m_genre_shounen": "Shounen Heart of a Mountain Racer",
        "m_genre_ecchi": "Gas Station Chapter",
        "m_genre_mahou_shoujo": "Power of the Mountain Pass",
        "m_genre_mecha": "Racing Machine Blueprints",
        "m_genre_music": "Eurobeat Folk Songs",
        "m_tag_isekai_new": "New World Beyond the Mountain",
        "m_tag_harem": "Racing Bonds Manga",
        "m_tag_bl": "Driver Brothers Manga",
        "m_tag_gl": "Racing Sisters Manga",
        "m_tag_historical": "Touge History Manga",
        "m_tag_military": "Racing Operations Manga",
        "m_tag_school": "Usui Technical High School Manga",
        "m_tag_martial_arts": "Drift Combat Manual",
        "m_tag_vampire": "Night Driver Blood Manga",
        "m_tag_samurai": "Mountain Pass Warrior Manga",
        "m_tag_space": "Beyond Mountain Range Manga",
        "m_tag_parody": "Chibi Itsuki Manga",
        "m_tag_idol": "Mountain Idol Manga",
        "m_tag_post_apocalyptic": "Post-Project D Manga",
        "m_tag_cyberpunk": "Turbo Technology Manga",
        "m_tag_shoujo": "Natsuki's Story Manga",
        "m_tag_survival": "Mountain Survival Manga",
        "m_tag_cooking": "Tofu Shop Cookbook",
        "m_tag_medical": "Pit Crew Medic Manga",
        "m_tag_villainess": "Rival Team Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Mountain Manga Campaign Completionist",
        "m_mega_completionist": "Supreme Mountain Manga Commander",
        "m_completion_rate_50": "Halfway to Project D",
        "m_completion_rate_75": "Approaching the Final Stage",
        "m_completion_rate_90": "Final Mountain Chapter Approaching",
        "m_no_drop": "No Mountain Manuscript Abandoned",
        "m_long_runner_complete": "Long Mountain Series Endurance Medal",
        "m_sequel_chain": "Sequel Mountain Chain of Command",
        "m_clean_list": "Clean Mountain Reading Record",
        "m_from_ptr": "Orders Received: Read",
        "m_reread_master": "Mountain Memory Replay Reread",
        "m_oneshot_complete": "Oneshot Stage Mission Specialist",
        "m_same_day_start_finish": "Same-Day Mountain Reading Blitz",
        "m_revival": "Revival Through Eurobeat",
        "m_zero_to_hundred": "Delivery Boy to Mountain Scholar",
        "m_five_genre_complete": "Five-Genre Mountain Mastery",
        "m_full_collection": "Full Mountain Archive Collection",
        "m_batch_complete": "Batch Stage Clearance",
        "m_paused_to_done": "Back from Mountain Hiatus",
        "m_completion_spree": "Completion Mountain Barrage",
        "m_format_completionist": "Format Mountain Completion Badge",
        "m_catch_up": "Caught Up with Stage Serialization",
        "m_multi_reread": "Multi-Pass Mountain Reread",
        "m_dropped_recovery": "Recovered from Mechanical Failure",
        "m_ten_perfect_scores": "Ten Perfect Mountain Manuscript Scores",
        "m_complete_genre_span": "All-Genre Mountain Reading Scout",
        "m_monthly_completions": "Monthly Mountain Manuscript Victories",
        "m_yearly_completions": "Yearly Mountain Reading Campaign",
        "m_rapid_complete": "Rapid Stage Intel Processing",
        "m_author_complete": "Shigeno's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Mountain Reader",
        "m_mangaka_lover": "Shigeno Devotee",
        "m_rereader": "Mountain Scout Rereader",
        "m_triple_reread": "Triple Mountain Reread Expedition",
        "m_annual_reread": "Annual Akagi Night Run Reread",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Artist Appreciation Medal",
        "m_adaptation_compare": "Manga vs Anime Mountain Compare",
        "m_source_material_fan": "Source Material Mountain Scout",
        "m_waiting_weekly": "Weekly Stage Chapter Signal Wait",
        "m_classic_reader": "Classic Mountain Manuscript Reader",
        "m_saga_reader": "Saga of the Mountain Racer Reader",
        "m_genre_loyalty": "Genre Mountain Loyalty Medal",
        "m_decade_reader": "Decade-Long Mountain Reader",
        "m_ln_adaptation": "Light Novel Adaptation Intel",
        "m_original_work": "Original Mountain Manga Work",
        "m_long_commitment": "Long-Term Mountain Reading Commitment",
        "m_up_to_date": "Up-to-Date with the Mountain Front",
        "m_favorite_mangaka": "Favorite Mangaka Honored",
        "m_complete_portfolio": "Complete Mountain Reading Portfolio",
        "m_franchise_collector": "Initial D Franchise Collector",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Mountain Mastery Earned",
        "m_multi_series_author": "Multi-Series Author Fan",
        "m_format_diversity": "Diverse Mountain Reading Formats",
        "m_year_dedication": "Year of Dedicated Mountain Reading",
        "m_ongoing_follower": "Ongoing Mountain Series Follower",
        "m_genre_loyalty_50": "Fifty Genre Mountain Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Mountain Territory Scout",
        "m_publisher_hopper": "Publisher Mountain Transfer",
        "m_tag_explorer": "Mountain Manga Tag Recon Mission",
        "m_decade_hopper": "Decade-Hopping Mountain Racer",
        "m_hidden_gem": "Hidden Mountain Pass Gem",
        "m_popular_taste": "Popular Among Mountain Racers",
        "m_retro_reader": "Pre-AE86 Era Reader",
        "m_modern_reader": "Modern Mountain Reader",
        "m_cross_demographic": "Cross-Demographic Mountain Scout",
        "m_underdog_fan": "Underdog Delivery Driver Fan",
        "m_variety_week": "Week of Varied Mountain Readings",
        "m_manhwa_reader": "Manhwa Intelligence Reader",
        "m_manhua_reader": "Manhua Intelligence Reader",
        "m_classic_connoisseur": "Classic Mountain Manuscript",
        "m_award_winner": "Medal-Winning Mountain Manuscript",
        "m_niche_explorer": "Niche Mountain Territory Reader",
        "m_world_manga": "World Mountain Manga Intel",
        "m_cult_classic": "Mountain Cult Classic Underground",
        "m_random_pick": "Random Mountain Reading Assignment",
        "m_new_genre_month": "New Mountain Genre Deployment Monthly",
        "m_year_completionist": "Year Mountain Reading Completionist",
        "m_unpopular_opinion": "Unpopular Mountain Opinion",
        "m_top_rated_reader": "Top-Rated Mountain Intel Source",
        "m_source_variety": "Source Material Variety",
        "m_low_score_brave": "Brave Low-Score Mountain Reader",
        "m_short_manga_explorer": "Short Mountain Manga Skirmish",
        "m_long_manga_explorer": "Long Mountain Campaign Manuscript",
        "m_serialization_explorer": "Mountain Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Mountain Reader",
        "m_early_bird": "Dawn Mountain Patrol Reader",
        "m_lunch_reader": "Gas Station Lunch Reader",
        "m_commute_reader": "Mountain Commute Reader",
        "m_four_am_club": "4 AM Mountain Sentry Reader",
        "m_new_year_read": "New Year's Mountain Reading Oath",
        "m_all_hours": "All-Hours Mountain Archive Access",
        "m_prime_time_reader": "Prime Time Mountain Manuscript",
        "m_workday_reader": "On-Duty Mountain Reader",
        "m_sunday_read": "Sunday Mountain Reading Marathon",
        "m_morning_routine": "Morning Mountain Formation Reading",
        "m_night_shift_reader": "Night Shift Mountain Reader",
        "m_seasonal_premier_read": "New Mountain Release Intel",
        "m_clock_collector": "Mountain Clock Reading Time",
        "m_late_night_horror": "Midnight Mountain Horror Read",
        "m_afternoon_reader": "Afternoon Mountain Reading",
        "m_golden_hour_reader": "Golden Hour Mountain Reading",
        "m_dawn_reader": "Dawn Mountain Reading Scout",
        "m_twilight_reader": "Twilight Mountain Reading",
        "m_midnight_start": "Midnight Mountain Reading Mission",
        "m_weekend_binge_hours": "Weekend Mountain Binge Reading Ops",
        "m_late_night_regular": "Late Night Mountain Regular Reader",
        "m_sunrise_reader": "Sunrise Over Akagi Mountain Reader",
        "m_every_day_of_week": "Every Day Mountain Reading Duty",
        "m_monthly_hours": "Monthly Mountain Reading Hours Logged",
        "m_bedtime_reader": "Bedtime Mountain Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Shigeno Art Appreciator",
        "m_webtoon_reader": "Webtoon Intelligence",
        "m_full_color": "Full Color Mountain Manuscript",
        "m_doujin_reader": "Underground Mountain Doujin Reader",
        "m_anthology_reader": "Anthology Collection Reader",
        "m_adaptation_reader": "Adaptation Study Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Itsuki Shorts",
        "m_oneshot_reader": "Oneshot Stage Mission Reader",
        "m_format_variety": "Format Mountain Tactical Variety",
        "m_light_novel_reader": "Light Novel Intel Reader",
        "m_novel_reader": "Novel Mountain Archive Reader",
        "m_visual_storyteller": "Visual Mountain Battle Narrator",
        "m_colored_classic": "Colored Classic Mountain Manuscript",
        "m_webcomic_fan": "Webcomic Underground Fan",
        "m_manga_to_anime": "Manga to Anime Mountain Comparison",
        "m_seinen_reader": "Seinen Mountain Reader",
        "m_josei_reader": "Josei Mountain Perspective Reader",
        "m_award_winning_art": "Medal-Winning Mountain Artwork",
        "m_debut_work": "Debut Mountain Manuscript",
        "m_vertical_scroll": "Vertical Scroll Mountain Intel",
        "m_traditional_format": "Traditional Mountain Format Reader",
        "m_cross_media": "Cross-Media Mountain Intelligence",
        "m_spinoff_reader": "Mountain Spinoff Reader",
        "m_remake_reader": "Remake Mountain Reading Assignment",
        "m_collaboration_reader": "Joint Mountain Operation Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Mountain Reading Patrol Streak",
        "m_mega_streak": "Mega Mountain Reading Campaign Streak",
        "m_weekly_warrior": "Weekly Mountain Warrior Reader",
        "m_monthly_reader": "Monthly Mountain Reader",
        "m_comeback": "Reader's Return to the Mountain",
        "m_weekend_streak": "Weekend Mountain Reading Streak",
        "m_no_zero_days": "No Zero Mountain Reading Days",
        "m_iron_will": "Iron Will Mountain Reader",
        "m_habit_formed": "Mountain Reading Regimen Formed",
        "m_consistent_pace": "Consistent Mountain Reading Advance",
        "m_year_long": "Year-Long Mountain Reading Campaign",
        "m_double_streak": "Double Mountain Reading Streak",
        "m_streak_recovery": "Mountain Reading Streak Recovery",
        "m_daily_minimum": "Daily Minimum Mountain Pages",
        "m_winter_streak": "Winter Mountain Reading Campaign",
        "m_summer_streak": "Summer Mountain Reading Offensive",
        "m_morning_streak": "Morning Mountain Reading Formation",
        "m_night_streak": "Night Mountain Reading Patrol",
        "m_unbreakable": "Unbreakable Mountain Reading Will",
        "m_eternal_flame": "Eternal Eurobeat Flame of Knowledge",
        "m_chapter_a_day": "Chapter a Day Mountain Discipline",
        "m_genre_streak": "Genre Mountain Reading Streak",
        "m_completion_streak": "Completion Mountain Reading Chain",
        "m_rating_streak": "Mountain Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Mountain Streak",
        "m_author_streak": "Shigeno Dedication Streak",
        "m_perfect_week_manga": "Perfect Mountain Reading Week",
        "m_diverse_streak": "Diverse Mountain Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Mountain Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Mountain Manuscript",
        "m_harsh_critic": "Ryosuke's Reading Standards",
        "m_fair_judge": "Bunta's Fair Review",
        "m_generous_spirit": "Generous Mountain Reader",
        "m_score_all": "Full Mountain Manuscript Assessment",
        "m_wide_range": "Wide Range Mountain Scores",
        "m_controversial": "Controversial Mountain Reading Opinion",
        "m_consistent_scorer": "Consistent Mountain Manuscript Scorer",
        "m_score_sniper": "Precision Downhill Score Sniper",
        "m_evolving_taste": "Evolving Mountain Reading Taste",
        "m_bell_curve": "Bell Curve of Mountain Scores",
        "m_picky_reader": "Selective Mountain Reading Commander",
        "m_100_rated": "Century of Mountain Ratings Filed",
        "m_500_rated": "Five Hundred Mountain Rating Reports",
        "m_mediocre_majority": "Middle Ground Mountain Reader",
        "m_rating_spree": "Mountain Rating Barrage Filed",
        "m_score_variance": "Variable Mountain Manuscript Scores",
        "m_binge_rater": "Mountain Binge Rating Session",
        "m_reread_rerate": "Reread and Re-Rate Mountain Intel",
        "m_masterpiece_hunter": "Masterpiece Mountain Manuscript Hunter",
        "m_contrarian": "Contrarian Mountain Reader",
        "m_optimist": "Optimistic Mountain Reader Scout",
        "m_score_distributor": "Score Distributor General",
        "m_genre_critic": "Genre Mountain Reading Critic",
        "m_mean_above_8": "Elite Mountain Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Mountain Reading Vow",
        "m_valentines_read": "Valentine's Mountain Reading Bond",
        "m_pi_day": "Pi Day Stage Chapter Count",
        "m_april_fools": "April Fools Itsuki Chibi",
        "m_international_manga_day": "International Mountain Manga Day",
        "m_free_comic_day": "Free Comic Mountain Day",
        "m_summer_solstice": "Summer Solstice Mountain Reading",
        "m_tanabata": "Tanabata Mountain Reading Wish",
        "m_friday_13th": "Friday 13th Night Run Manuscript",
        "m_halloween_read": "Halloween Night Mountain Reading",
        "m_thanksgiving_binge": "Thanksgiving Mountain Reading Feast",
        "m_christmas_read": "Midwinter Mountain Festival Reading",
        "m_new_years_eve": "New Year's Eve Final Mountain Read",
        "m_birthday_read": "Birthday Mountain Reading Gift",
        "m_holiday_marathon": "Holiday Mountain Reading Marathon",
        "m_independence_day": "Mountain Independence Reading",
        "m_culture_day": "Touge Culture Day Manuscript",
        "m_spring_equinox": "Spring Mountain Equinox Reading",
        "m_earth_day": "Earth Day Mountain Conservation Read",
        "m_labor_day": "Mountain Labor Reading Day",
        "m_winter_solstice": "Winter Solstice Mountain Reading",
        "m_manga_birthday": "Mountain Manga Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Mountain Reader",
        "m_consecutive_holidays": "Consecutive Holiday Mountain Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Mountain Milestone",
        "m_fibonacci": "Fibonacci Mountain Chapter Pattern",
        "m_palindrome_day": "Palindrome Mountain Reading Day",
        "m_binary_day": "Binary Stage Signal Reading Day",
        "m_full_moon_read": "Full Moon Mountain Read",
        "m_leap_year_read": "Leap Year Mountain Reading",
        "m_triple_seven": "Triple Seven Mountain Passes",
        "m_thousand_complete": "Thousand Mountain Manga Victories",
        "m_nice": "Nice Stage Chapter Count",
        "m_power_level_chapters": "God Foot-Level Chapters",
        "m_answer_42": "Answer to Takumi's Reading",
        "m_square_number": "Perfect Mountain Formation Chapters",
        "m_prime_count": "Prime Stage Chapter Count",
        "m_matching_date": "Matching Mountain Intel Reading Date",
        "m_century_chapter": "Century Stage Chapter Milestone",
        "m_pi_chapters": "Pi Stage Chapter Calculation",
        "m_synchronicity": "Mountain Reading Synchronicity",
        "m_world_record": "World Record Mountain Chapter Count",
        "m_genre_clash": "Genre Mountain Clash Reading",
        "m_time_traveler": "Time-Traveling Mountain Reader",
        "m_double_digits": "Double Digit Mountain Milestone",
        "m_one_two_three": "Downhill One Two Three",
        "m_lucky_seven": "Seven Lucky Mountain Chapters",
        "m_exact_hundred_ch": "Exact Hundred Mountain Chapters Read",
        "m_year_match_count": "Year Match Mountain Chapter Count",
        "m_chapter_match_date": "Mountain Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Manhwa Format Reader",
        "m_manhua_format": "Manhua Format Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Operative",
        "m_doujin_format": "Doujin Format Reader",
        "m_novel_format": "Novel Format Reader",
        "m_format_master_manga": "Format Master Mountain Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Mountain Reading Power Unlocked",
        "m_meta_collector": "Mountain Reading Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Mountain Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Mountain Reading Rank",
        "m_meta_xp_earner": "XP from Mountain Reading Intel",
        "m_meta_difficulty_easy": "Easy Stage Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Mountain Manuscript Challenge",
        "m_meta_unlock_spree": "Mountain Reading Unlock Barrage",
        "m_meta_completionist": "Meta Mountain Reading Completionist",
        "m_meta_diverse": "Diverse Mountain Reading Portfolio",
        "m_meta_dominator": "Meta Mountain Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030508",
        primary: "#003388",
        secondary: "#002266",
        accent: "#f0f0e8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        tire_smoke: { label: "Tire Smoke", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        night_sparks: { label: "Night Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        rain_drops: { label: "Rain Drops", maxCount: 16, defaultEnabled: true, defaultIntensity: 45 },
        headlight_beams: { label: "Headlight Beams", maxCount: 4, defaultEnabled: true, defaultIntensity: 60 },
    },
    milestoneNames: {
        1:   "Tofu Delivery Boy",
        5:   "Akagi Mountain Racer",
        15:  "Red Suns Rival",
        30:  "Emperor Challenger",
        45:  "Impact Blue Encounter",
        60:  "Project D Member",
        80:  "Project D Ace",
        100: "God Foot",
    },
}
