import { AnimeThemeConfig } from "./types"
import { jujutsuKaisenPlayerIcons } from "./player-icons"
import {
    GiCrystalBall,
    GiDeathSkull,
    GiEvilHand,
    GiMagicSwirl,
    GiMuscleUp,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiLightningBranches,
    GiResize,
    GiSettingsKnobs,
    GiShadowFollower,
    GiSkullCrossedBones,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const jujutsuKaisenTheme: AnimeThemeConfig = {
    id: "jujutsu-kaisen",
    displayName: "Jujutsu Kaisen",
    description: "Unleash your cursed energy and enter the world of jujutsu sorcery — dark indigo and violet cursed energy aesthetics.",
    fontFamily: "'Lexend', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Lexend:wght@300;400;500;600;700&display=swap",
    cssVars: {
        // Brand → indigo-violet cursed energy palette
        "--color-brand-200": "180 160 255",
        "--color-brand-300": "160 130 245",
        "--color-brand-400": "140 100 235",
        "--color-brand-500": "120 75 220",
        "--color-brand-600": "100 60 200",
        "--color-brand-700": "80 45 170",
        "--color-brand-800": "60 30 140",
        "--color-brand-900": "40 20 110",
        "--color-brand-950": "25 12 80",
        "--brand": "100 60 200",
        // Deep cursed backgrounds
        "--background": "#040208",
        "--paper": "#0a0612",
        // Violet-tinted grays
        "--color-gray-950": "4 2 8",
        "--color-gray-900": "10 6 18",
        "--color-gray-800": "20 14 34",
        "--color-gray-700": "34 26 56",
        "--color-gray-600": "54 44 80",
        "--color-gray-500": "80 68 110",
        "--color-gray-400": "120 108 150",
        "--color-gray-300": "164 152 190",
        "--color-gray-200": "200 192 218",
        "--color-gray-100": "226 222 236",
        "--color-gray-50": "244 242 248",
    },
    sidebarOverrides: {
        "home": { icon: GiCrystalBall, label: "Jujutsu High" },
        "schedule": { icon: GiAlarmClock, label: "Mission Schedule" },
        "manga": { icon: LuBookOpen, label: "Cursed Scrolls" },
        "lists": { icon: GiShadowFollower, label: "Cursed Techniques" },
        "discover": { icon: GiBullseye, label: "Domain Expansion" },
        "torrent-list": { icon: GiLightningBranches, label: "Cursed Energy Flow" },
        "debrid": { icon: GiSkullCrossedBones, label: "Curse Bounties" },
        "unmatched": { icon: GiEvilHand, label: "Unregistered Curses" },
        "enmasse": { icon: GiResize, label: "Sorcerer Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Jujutsu Reports" },
        "auto-downloader": { icon: LuRss, label: "Cursed Intel Feed" },
        "community": { icon: GiDeathSkull, label: "Tokyo / Kyoto School" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Cursed Alerts" },
        "achievements": { icon: GiTrophy, label: "Sorcerer Grades" },
        "theme-manager": { icon: GiPalette, label: "Cursed Aesthetics" },
        "extensions": { icon: BiExtension, label: "Binding Vow Plugins" },
        "sync": { icon: IoCloudOfflineOutline, label: "Tengen's Barrier Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Higher-Ups' Orders" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Cursed Finger Consumed",
        "a_episode_counter": "Cursed Energy Counter",
        "a_episode_titan": "Special Grade Feat",
        "a_hours_invested": "Hours in Jujutsu High",
        "a_time_lord": "Master of Cursed Time",
        "a_anime_collector": "Cursed Object Collector",
        "a_library_legend": "Jujutsu Archives Legend",
        "a_first_complete": "First Curse Exorcised",
        "a_hundred_club": "Century of Exorcisms",
        "a_first_day": "Enrollment Day at Jujutsu High",
        "a_first_rating": "First Sorcerer Grading",
        "a_ten_thousand_min": "Ten Thousand Minutes of Cursed Energy",
        "a_season_veteran": "Veteran Jujutsu Sorcerer",
        "a_year_explorer": "Year at Jujutsu High",
        "a_century_watcher": "Hundred-Episode Sorcerer Path",
        "a_five_hundred_eps": "Five Hundred Cursed Encounters",
        "a_thousand_eps": "Thousand Cursed Techniques",
        "a_watching_ten": "Ten Domains Active",
        "a_ptw_hoarder": "Mission Backlog Hoarder",
        "a_dropped_honesty": "Tactical Sorcerer Retreat",
        "a_five_thousand_eps": "Five Thousand Cursed Spirits",
        "a_ten_completed": "Ten Missions Completed",
        "a_fifty_completed": "Fifty Curses Vanquished",
        "a_five_hundred_completed": "Five Hundred Exorcisms",
        "a_mean_score_tracker": "Average Sorcerer Grade",
        "a_unique_studios": "Allied Jujutsu Schools",
        "a_days_spent_watching": "Days Training at Jujutsu High",
        "a_all_status": "All Mission Statuses Filed",
        "a_first_favorite": "First Bond with a Sorcerer",
        "a_favorites_collector": "Itadori Squad Bonds",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Cursed Energy Surge",
        "a_marathon_runner": "Shibuya Incident Marathon",
        "a_weekend_warrior": "Weekend Curse Patrol",
        "a_non_stop": "Relentless Cursed Flow",
        "a_one_more_episode": "One More Binding Vow",
        "a_speed_run": "Black Flash Rush",
        "a_double_feature": "Twin Cursed Technique Strike",
        "a_triple_threat": "Triple Domain Expansion",
        "a_five_a_day": "Five Exorcisms at Dusk",
        "a_back_to_back": "Back-to-Back Curse Hunts",
        "a_seasonal_binge": "Full Arc Cursed Training",
        "a_cour_crusher": "Exchange Event Crusher",
        "a_half_day_watch": "Half-Day at Jujutsu High",
        "a_full_day_watch": "Full Day Sorcerer Training",
        "a_power_weekend": "Power Weekend at the School",
        "a_binge_king": "King of Curses Viewer",
        "a_no_sleep": "All-Night Curse Stakeout",
        "a_entire_season": "Rapid Arc Exorcism",
        "a_seven_day_challenge": "Seven-Day Sorcerer Exam",
        "a_hundred_day_binge": "Hundred-Day Cursed Grind",
        "a_genre_binge": "Cross-Technique Training",
        "a_studio_binge": "MAPPA Studio Binge",
        "a_season_sweep": "Season Sweep Exorcism",
        "a_forty_eight_hour": "Forty-Eight Hour Shibuya",
        "a_ep_counter_day": "Daily Exorcism Count",
        "a_multi_series_binge": "Multi-Sorcerer Task Force",
        "a_midnight_binge": "Midnight Curse Patrol",
        "a_new_year_binge": "New Year's Cursed Energy Rush",

        // ── ANIME GENRES ──
        "a_genre_action": "Cursed Combat Specialist",
        "a_genre_adventure": "Journey Beyond the Veil",
        "a_genre_comedy": "Todo's Best Friend Comedy",
        "a_genre_drama": "Itadori's Origin Drama",
        "a_genre_fantasy": "Cursed Fantasy Realm",
        "a_genre_horror": "Cursed Spirit Horror",
        "a_genre_mystery": "Brain's True Identity Mystery",
        "a_genre_romance": "Heart of the Sorcerer",
        "a_genre_scifi": "Cursed Energy Science",
        "a_genre_sol": "Life at Jujutsu High",
        "a_genre_sports": "Goodwill Event Grounds",
        "a_genre_supernatural": "Cursed Supernatural Singularity",
        "a_genre_thriller": "Culling Game Thriller",
        "a_genre_mecha": "Mechamaru's Puppet Body",
        "a_genre_music": "Jujutsu Kaisen OST Lover",
        "a_genre_psychological": "Geto's Twisted Philosophy",
        "a_genre_ecchi": "Hidden Inventory Interlude",
        "a_genre_mahou_shoujo": "Cursed Magical Sorcery",
        "a_tag_isekai": "Transported to a Cursed Realm",
        "a_tag_harem": "Sorcerer Squad Assembled",
        "a_tag_bl": "Brothers in Sorcery",
        "a_tag_gl": "Sorcerer Duo Partners",
        "a_tag_historical": "Heian Era Chronicles",
        "a_tag_military": "Jujutsu Higher-Ups Operations",
        "a_tag_school": "Jujutsu High Academy",
        "a_tag_martial_arts": "Cursed Martial Arts Master",
        "a_tag_vampire": "Cursed Blood Technique",
        "a_tag_samurai": "Samurai-Era Sorcerer",
        "a_tag_space": "Infinite Void Domain",
        "a_tag_parody": "Chibi Jujutsu Sorcerers",
        "a_tag_idol": "Utahime's Stage Performance",
        "a_tag_post_apocalyptic": "Post-Shibuya Aftermath",
        "a_tag_cyberpunk": "Mechamaru's Tech Network",
        "a_tag_shounen": "Burning Sorcerer Spirit",
        "a_tag_seinen": "Veteran Sorcerer Reality",
        "a_tag_shoujo": "Nobara's Fierce Heart",
        "a_tag_josei": "Shoko's Perspective",
        "a_tag_survival": "Survival in the Culling Game",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Sorcerer License",
        "a_mega_completionist": "Special Grade Sorcerer",
        "a_completion_rate_50": "Halfway to Special Grade",
        "a_completion_rate_75": "Approaching Grade One",
        "a_completion_rate_90": "Domain Nearly Perfected",
        "a_no_drop": "No Sorcerer Left Behind",
        "a_long_runner_complete": "Long Cursed War Endurance",
        "a_sequel_chain": "Sequel Mission Chain",
        "a_clean_list": "Clean Sorcerer Record",
        "a_from_ptw": "Mission Scroll Activated",
        "a_rewatch_master": "Reverse Cursed Technique Replay",
        "a_short_complete": "Quick Curse Capture",
        "a_same_day_start_finish": "Same-Night Curse Resolution",
        "a_revival": "Itadori's Revival from Death",
        "a_zero_to_hero": "Vessel to Special Grade",
        "a_five_genre_complete": "Five Technique Mastery",
        "a_full_franchise": "Full Jujutsu Dossier",
        "a_batch_complete": "Batch Exorcism Clear",
        "a_paused_to_done": "Returned from Recovery",
        "a_completion_spree": "Black Flash Spree",
        "a_multi_rewatch": "Multi-Timeline Memory Replay",
        "a_dropped_recovery": "Recovered from Sukuna's Curse",
        "a_ten_perfect_scores": "Ten Perfect Sorcerer Scores",
        "a_seasonal_clear": "Seasonal Exam Clear",
        "a_complete_genre_span": "All-Around Jujutsu Sorcerer",
        "a_monthly_completions": "Monthly Jujutsu Reports",
        "a_yearly_completions": "Annual Sorcerer Review",
        "a_rapid_complete": "Black Flash Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Jujutsu Sorcerer",
        "a_studio_devotee": "Studio MAPPA Devotee",
        "a_rewatcher": "Jujutsu Rewatch Patrol",
        "a_triple_rewatch": "Triple Cursed Rewatch",
        "a_annual_tradition": "Annual Goodwill Event",
        "a_director_fan": "Director's Cursed Vision",
        "a_voice_actor_fan": "Voice of the Sorcerers",
        "a_ost_lover": "Kaikai Kitan & Lost in Paradise",
        "a_source_reader": "Akutami's Original Manga",
        "a_waiting_weekly": "Weekly Jujutsu Broadcast Wait",
        "a_childhood_revisit": "Return to Jujutsu Origins",
        "a_saga_tracker": "Jujutsu Saga Tracker",
        "a_genre_loyalty": "Sorcerer Genre Loyalty Badge",
        "a_decade_watcher": "Decade-Long Jujutsu Fan",
        "a_adaptation_hunter": "Cursed Adaptation Hunter",
        "a_original_anime_fan": "Original Broadcast Sorcerer",
        "a_long_commitment": "Long-Term Jujutsu Commitment",
        "a_perfect_attendance": "Perfect Attendance at Training",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Cursed Catalog",
        "a_franchise_collector": "Jujutsu Universe Collector",
        "a_airing_follower": "Currently Airing Cursed Intel",
        "a_genre_master": "Genre Technique Mastery",
        "a_staff_follower": "Sorcerer Staff Dossier",
        "a_multi_season_fan": "Multi-Season Sorcerer Veteran",
        "a_format_diversity": "Diverse Sorcerer Formats",
        "a_year_dedication": "Year of Unwavering Cursed Energy",
        "a_season_dedication": "Season of Burning Determination",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Cursed Technique Explorer",
        "a_studio_hopper": "School Transfer Student",
        "a_tag_explorer": "Tag Reconnaissance Sorcerer",
        "a_decade_hopper": "Heian Era to Modern Day",
        "a_hidden_gem": "Hidden Cursed Technique Found",
        "a_popular_taste": "Popular Among Sorcerers",
        "a_retro_appreciator": "Golden Age Sorcerer Appreciator",
        "a_modern_viewer": "Modern Sorcerer Viewer",
        "a_cross_demographic": "Cross-School Scout",
        "a_underdog_fan": "Underdog Itadori Spirit",
        "a_variety_week": "Week of Varied Techniques",
        "a_foreign_cinema": "Overseas Sorcerer Cinema",
        "a_classic_connoisseur": "Classic Jujutsu Connoisseur",
        "a_every_season": "Every Season Enlisted",
        "a_award_winner": "Sorcerer Award Winner",
        "a_niche_explorer": "Underground Sorcerer Explorer",
        "a_global_anime": "Global Jujutsu Network",
        "a_cult_classic": "Cult Classic Cursed Tale",
        "a_random_pick": "Random Mission Assignment",
        "a_new_genre_month": "New Technique Monthly Discovery",
        "a_seasonal_completionist": "Seasonal Mission Complete",
        "a_unpopular_opinion": "Unpopular Sorcerer Opinion",
        "a_top_rated_viewer": "Top-Ranked Sorcerer Intel",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Cursed Darkness",
        "a_upcoming_watcher": "Upcoming Cursed Debut Watch",
        "a_short_series_explorer": "Short Mission Explorer",
        "a_long_series_explorer": "Long Arc Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Patrol Curse Hunter",
        "a_early_bird": "Dawn Patrol Sorcerer",
        "a_lunch_break": "Lunch at Jujutsu High",
        "a_golden_hour": "Golden Hour Exorcism",
        "a_four_am_club": "4 AM Cursed Training",
        "a_witching_hour": "Cursed Spirit's Witching Hour",
        "a_new_year_watch": "New Year's Sorcerer Oath",
        "a_midnight_premiere": "Midnight Cursed Premiere",
        "a_all_hours": "All-Hours Sorcerer on Duty",
        "a_dawn_warrior": "Dawn Warrior Sorcerer",
        "a_afternoon_delight": "Afternoon Training Session",
        "a_prime_time": "Prime Time Cursed Showdown",
        "a_workday_watcher": "On-Duty Sorcerer Watcher",
        "a_sunday_marathon": "Sunday Training Marathon",
        "a_rainy_day": "Rainy Day at Jujutsu High",
        "a_morning_routine": "Morning Cursed Energy Routine",
        "a_night_shift": "Nighttime Sorcerer Shift",
        "a_twilight_zone": "Twilight Cursed Zone",
        "a_seasonal_premier": "Season Premiere Cursed Debut",
        "a_clock_collector": "Clock Tower Collector",
        "a_weekend_binge_hours": "Weekend Sorcerer Binge Hours",
        "a_late_night_regular": "Late Night Regular Patrol",
        "a_sunrise_watcher": "Sunrise Over Jujutsu High",
        "a_holiday_watcher": "Holiday Sorcerer Duty",
        "a_every_day_of_week": "Every Day a Jujutsu Sorcerer",
        "a_monthly_hours": "Monthly Training Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Sorcerer Squad Gathering",
        "a_party_host": "Jujutsu High Host Gojo",
        "a_social_butterfly": "Social Butterfly Sorcerer",
        "a_group_binge": "Sorcerer Group Watch",
        "a_party_regular": "Regular Training Partner",
        "a_sync_viewer": "Synchronized Cursed Technique",
        "a_commentator": "Todo's Flamboyant Commentary",
        "a_party_marathon": "Sorcerer Training Marathon",
        "a_full_house": "Full Jujutsu Assembly",
        "a_community_pillar": "Pillar of Jujutsu Society",
        "a_watch_party_streak": "Consecutive Gathering Streak",
        "a_diverse_party": "Diverse Sorcerer Team-Up",
        "a_late_night_party": "Late Night Jujutsu Party",
        "a_party_veteran": "Veteran Sorcerer Social",
        "a_genre_party": "Cross-Technique Party",
        "a_weekly_party": "Weekly Sorcerer Gathering",
        "a_silent_viewer": "Silent Observer Megumi",
        "a_recommendation_giver": "Gojo's Recommendation Letter",
        "a_party_completionist": "Social Sorcerer Completionist",
        "a_social_scorer": "Social Sorcerer Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Formation",
        "a_fibonacci": "Fibonacci Cursed Sequence",
        "a_palindrome_day": "Palindrome Time Rift",
        "a_binary_day": "Binary Cursed Analysis",
        "a_full_moon": "Full Moon Curse Awakening",
        "a_leap_year": "Leap Year Time Skip",
        "a_time_traveler": "Memories of the Heian Era",
        "a_genre_clash": "Sorcerer vs. Curse Clash",
        "a_triple_seven": "Triple Seven Cursed Combo",
        "a_thousand_complete": "Thousand Exorcisms",
        "a_pi_episodes": "Pi Calculation of Techniques",
        "a_synchronicity": "Cursed Synchronicity",
        "a_world_record": "World Record Cursed Feat",
        "a_nice": "Nice Cursed Energy Count",
        "a_power_level": "Unlimited Void Power Level",
        "a_answer_42": "The Answer to Kenjaku's Riddle",
        "a_square_number": "Perfect Formation Number",
        "a_prime_count": "Prime Number of Exorcisms",
        "a_matching_date": "Matching Incident Date",
        "a_century_episode": "Century Episode Cursed Arc",
        "a_double_digits": "Double Digit Sorcerer Rank",
        "a_one_two_three": "Techniques One Two Three",
        "a_lucky_seven": "Seven Lucky Sorcerers",
        "a_all_tens": "All Tens Sorcerer Score",
        "a_exact_hundred_eps": "Exact Hundred Cursed Deeds",
        "a_year_match_count": "Year Match Exorcism Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Sorcerer",
        "a_movie_buff": "Jujutsu Kaisen 0 Movie",
        "a_ova_hunter": "OVA Training Day Hunter",
        "a_ona_explorer": "ONA Sorcerer Explorer",
        "a_special_watcher": "Special Episode Sorcerer",
        "a_short_king": "Short Exorcism King",
        "a_variety_pack": "All-Format Sorcerer Pack",
        "a_film_festival": "Jujutsu Film Festival",
        "a_music_video": "Sorcerer Theme Collection",
        "a_tv_short": "Quick Cursed Clip",
        "a_movie_marathon": "Cursed Movie Marathon",
        "a_double_length": "Double-Length Sorcerer Special",
        "a_anthology": "Jujutsu Anthology",
        "a_mini_series": "Mini Sorcerer Series",
        "a_theatrical": "Theatrical Cursed Debut",
        "a_format_master": "Format Master Sorcerer",
        "a_long_movie": "Feature-Length Jujutsu 0",
        "a_back_catalog": "Sorcerer Back Catalog",
        "a_cm_watcher": "Commercial Break Sorcerer",
        "a_pv_collector": "Cursed Preview Collector",
        "a_format_balance": "Balanced Sorcerer Formats",
        "a_episodic_master": "Episodic Cursed Master",
        "a_sequel_movie": "Sequel Cursed Movie",
        "a_recap_watcher": "Recap Briefing Sorcerer",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Cursed Patrol Streak",
        "a_mega_streak": "Mega Cursed Energy Streak",
        "a_weekly_warrior": "Weekly Warrior Sorcerer",
        "a_monthly_watcher": "Monthly Sorcerer Duty",
        "a_comeback": "Return from Recovery Ward",
        "a_weekend_streak": "Weekend Sorcerer Streak",
        "a_no_zero_days": "No Zero Days in Jujutsu",
        "a_iron_will": "Iron Will of a Sorcerer",
        "a_habit_formed": "Cursed Energy Regimen Formed",
        "a_consistent_pace": "Consistent Sorcerer Pace",
        "a_year_long": "Year-Long Cursed War",
        "a_double_streak": "Double Streak Cursed Combo",
        "a_streak_recovery": "Shoko's Streak Recovery",
        "a_daily_minimum": "Daily Minimum Patrol",
        "a_winter_streak": "Winter Cursed Streak",
        "a_summer_streak": "Summer Training Camp Streak",
        "a_morning_streak": "Morning Cursed Energy Streak",
        "a_night_streak": "Night Patrol Streak",
        "a_unbreakable": "Unbreakable Like Gojo",
        "a_eternal_flame": "Todo's Eternal Boogie Woogie",
        "a_completion_streak": "Mission Completion Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Episode Cursed Arc",
        "a_genre_streak": "Genre Streak Sorcerer Run",
        "a_studio_streak": "Studio Loyalty Sorcerer",
        "a_perfect_week": "Perfect Week of Exorcisms",

        // ── ANIME SCORING ──
        "a_critic": "Jujutsu Public Safety Critic",
        "a_perfect_ten": "Perfect 10 Sorcerer Score",
        "a_harsh_critic": "Nanami's Harsh Judgment",
        "a_fair_judge": "Gojo's Fair Assessment",
        "a_generous_spirit": "Generous Sorcerer Spirit",
        "a_score_all": "Full Sorcerer Evaluation",
        "a_wide_range": "Wide Range Cursed Assessment",
        "a_controversial": "Controversial Sorcerer Ranking",
        "a_consistent_scorer": "Consistent Sorcerer Evaluator",
        "a_score_sniper": "Nanami's Precision Score",
        "a_evolving_taste": "Evolving Cursed Taste",
        "a_bell_curve": "Bell Curve of Sorcerer Scores",
        "a_picky_watcher": "Selective Sorcerer Judge",
        "a_100_rated": "Century of Sorcerer Evaluations",
        "a_500_rated": "Five Hundred Sorcerer Reports",
        "a_mediocre_majority": "Grade Two Majority",
        "a_rating_spree": "Rating Concentration Spree",
        "a_score_variance": "Variable Sorcerer Ratings",
        "a_masterpiece_hunter": "Masterpiece Curse Hunter",
        "a_contrarian": "Contrarian Jujutsu Critic",
        "a_optimist": "Optimist Like Itadori",
        "a_score_distributor": "Score Distributor Sorcerer",
        "a_genre_critic": "Genre Technique Critic",
        "a_mean_above_8": "Elite Special Grade Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Sorcerer Resolution",
        "a_valentines_weeb": "Valentine's Cursed Heart",
        "a_pi_day": "Pi Day Cursed Calculation",
        "a_april_fools": "April Fools Cursed Prank",
        "a_international_anime_day": "International Sorcerer Day",
        "a_star_wars_day": "Star Wars Cursed Crossover",
        "a_summer_solstice": "Summer Solstice Training Day",
        "a_tanabata": "Tanabata Sorcerer Wish",
        "a_friday_13th": "Friday 13th Curse Outbreak",
        "a_halloween_spirit": "Halloween Cursed Costume",
        "a_thanksgiving_binge": "Thanksgiving Sorcerer Feast",
        "a_christmas_special": "Christmas at Jujutsu High",
        "a_new_years_eve": "New Year's Eve Sorcerer Gala",
        "a_birthday_watch": "Sorcerer Birthday Celebration",
        "a_holiday_marathon": "Holiday Jujutsu Marathon",
        "a_independence_day": "Sorcerer Independence Day",
        "a_culture_day": "Jujutsu Culture Festival",
        "a_spring_equinox": "Spring Cursed Bloom",
        "a_earth_day": "Earth Day Cursed Cleansing",
        "a_labor_day": "Sorcerer Labor Day",
        "a_winter_solstice": "Winter Solstice Exorcism",
        "a_anime_birthday": "Anime Anniversary Sorcerer",
        "a_every_holiday": "Every Holiday Sorcerer",
        "a_consecutive_holidays": "Consecutive Holiday Patrols",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Cursed Technique Awakened",
        "a_meta_collector": "Sorcerer License Collector",
        "a_meta_category_starter": "Cursed Category Initiation",
        "a_meta_tier_climber": "Sorcerer Grade Promotion",
        "a_meta_tier_max": "Special Grade Achieved",
        "a_meta_xp_earner": "XP from Cursed Exorcisms",
        "a_meta_difficulty_easy": "Easy Cursed Training",
        "a_meta_difficulty_hard": "Legendary: Domain Expansion Battle",
        "a_meta_unlock_spree": "Cursed Technique Unlock Spree",
        "a_meta_completionist": "Meta Jujutsu Completionist",
        "a_meta_diverse": "Diverse Sorcerer Portfolio",
        "a_meta_dominator": "Meta Pillar of Jujutsu",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter: Ryomen Sukuna",
        "m_chapter_counter": "Cursed Scroll Page Counter",
        "m_chapter_titan": "Special Grade-Class Chapter",
        "m_reading_hours": "Hours Studying Cursed Techniques",
        "m_reading_time_lord": "Total Concentration Reading",
        "m_manga_collector": "Jujutsu Manga Collector",
        "m_library_legend": "Jujutsu Archives Legend",
        "m_first_complete": "First Manga Exorcism Done",
        "m_hundred_club": "Hundred-Chapter Sorcerer Club",
        "m_first_day": "First Day of Jujutsu Reading",
        "m_first_rating": "First Manga Sorcerer Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Cursed Lore",
        "m_volume_collector": "Volume Stockpile Sorcerer",
        "m_year_explorer": "Year of Manga Jujutsu Study",
        "m_century_reader": "Century-Chapter Cursed Reader",
        "m_five_hundred_ch": "Five Hundred Sorcerer Chapters",
        "m_thousand_ch": "Thousand-Chapter Cursed Surge",
        "m_reading_ten": "Ten Manga at Once Sorcerer",
        "m_ptr_hoarder": "Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Sorcerer Retreat",
        "m_season_reader": "Seasonal Jujutsu Reading",
        "m_active_reader": "Active Field Reader Sorcerer",
        "m_five_thousand_ch": "Five Thousand Chapters Deep",
        "m_ten_completed": "Ten Cursed Manga Complete",
        "m_fifty_completed": "Fifty Manga Missions Done",
        "m_five_hundred_completed": "Five Hundred Manga Victories",
        "m_mean_score_tracker": "Average Manga Sorcerer Rating",
        "m_unique_authors": "Unique Mangaka Encounters",
        "m_all_status": "All Reading Statuses Sorcerer",
        "m_first_favorite": "First Manga Sorcerer Bond",
        "m_favorites_collector": "Manga Favorites Arsenal",
        "m_days_spent_reading": "Days in Jujutsu Reading Hall",

        // ── MANGA BINGE ──
        "m_binge_reader": "Non-Stop Cursed Reading",
        "m_marathon_reader": "Shibuya Incident Reading Marathon",
        "m_weekend_reader": "Weekend Jujutsu Reading",
        "m_non_stop_reading": "Relentless Page Cursing",
        "m_one_more_chapter": "One More Cursed Chapter",
        "m_speed_read": "Black Flash Speed Read",
        "m_double_story": "Double Cursed Feature",
        "m_triple_read": "Triple Cursed Reading",
        "m_five_a_day": "Five Cursed Reads a Day",
        "m_chapter_chain": "Chapter Chain Combo",
        "m_volume_binge": "Volume Binge Concentration",
        "m_power_reader": "Power Reader Sorcerer",
        "m_half_day_read": "Half-Day Sorcerer Study",
        "m_full_day_read": "Full-Day Manga Training",
        "m_power_weekend": "Power Weekend Jujutsu Reading",
        "m_binge_king": "King of Cursed Manga",
        "m_no_sleep_read": "All-Night Cursed Reading",
        "m_full_series_rush": "Full Series Cursed Rush",
        "m_seven_day_challenge": "Seven-Day Sorcerer Challenge",
        "m_hundred_day_read": "Hundred-Day Jujutsu Grind",
        "m_volume_rush": "Volume Rush Concentration",
        "m_series_sweep": "Series Sweep Sorcerer",
        "m_genre_binge": "Cross-Genre Cursed Reading",
        "m_author_binge": "Akutami Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Sorcerer Count",
        "m_multi_series_binge": "Multi-Series Cursed Reading",
        "m_midnight_binge": "Midnight Cursed Reading",
        "m_new_year_binge": "New Year's Reading Exorcism",
        "m_forty_eight_hour": "Forty-Eight Hour Cursed Read",
        "m_oneshot_binge": "Oneshot Cursed Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Cursed Manga Specialist",
        "m_genre_adventure": "Sorcerer Adventure Manga",
        "m_genre_comedy": "Comedy at Jujutsu High",
        "m_genre_drama": "Drama of Itadori's Path",
        "m_genre_fantasy": "Fantasy Cursed Manga",
        "m_genre_horror": "Cursed Spirit Horror Manga",
        "m_genre_mystery": "Mystery of Kenjaku",
        "m_genre_romance": "Sorcerer Romance Manga",
        "m_genre_scifi": "Sci-Fi Cursed Engineering",
        "m_genre_sol": "Jujutsu High Slice of Life",
        "m_genre_sports": "Goodwill Event Sports Manga",
        "m_genre_supernatural": "Supernatural Cursed Manga",
        "m_genre_thriller": "Culling Game Thriller Manga",
        "m_genre_psychological": "Psychological Cursed Warfare",
        "m_genre_isekai": "Isekai Cursed Manga",
        "m_genre_shounen": "Shounen Sorcerer Heart Manga",
        "m_genre_ecchi": "Hidden Inventory Chapter Manga",
        "m_genre_mahou_shoujo": "Magical Cursed Sorcery Manga",
        "m_genre_mecha": "Mechamaru Puppet Manga",
        "m_genre_music": "Sorcerer Sound Manga",
        "m_tag_isekai_new": "New World Cursed Manga",
        "m_tag_harem": "Sorcerer Squad Manga",
        "m_tag_bl": "Brothers in Jujutsu Manga",
        "m_tag_gl": "Sorcerer Duo Manga",
        "m_tag_historical": "Heian History Manga",
        "m_tag_military": "Higher-Ups Military Manga",
        "m_tag_school": "Jujutsu Academy Manga",
        "m_tag_martial_arts": "Cursed Martial Arts Manga",
        "m_tag_vampire": "Cursed Blood Art Manga",
        "m_tag_samurai": "Cursed Blade Manga",
        "m_tag_space": "Infinite Void Manga",
        "m_tag_parody": "Chibi Jujutsu Parody Manga",
        "m_tag_idol": "Utahime Idol Manga",
        "m_tag_post_apocalyptic": "Post-Shibuya Manga",
        "m_tag_cyberpunk": "Mechamaru Tech Manga",
        "m_tag_shoujo": "Nobara's Story Manga",
        "m_tag_survival": "Survival in Culling Game Manga",
        "m_tag_cooking": "Itadori's Cooking Manga",
        "m_tag_medical": "Shoko's Medical Manga",
        "m_tag_villainess": "Cursed Redemption Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Sorcerer Manga License",
        "m_mega_completionist": "Supreme Jujutsu Reader",
        "m_completion_rate_50": "Halfway to Special Grade Reader",
        "m_completion_rate_75": "Approaching Full Manga Mastery",
        "m_completion_rate_90": "Domain Manga Mastery",
        "m_no_drop": "No Manga Abandoned Sorcerer",
        "m_long_runner_complete": "Long Cursed Manga Endurance",
        "m_sequel_chain": "Sorcerer Sequel Chain",
        "m_clean_list": "Clean Sorcerer Reading Record",
        "m_from_ptr": "Higher-Ups' Orders: Read Manga",
        "m_reread_master": "Reverse Cursed Reread Replay",
        "m_oneshot_complete": "Oneshot Cursed Specialist",
        "m_same_day_start_finish": "Same-Day Cursed Manga Blitz",
        "m_revival": "Itadori's Revival Reread",
        "m_zero_to_hundred": "Vessel to Manga Special Grade",
        "m_five_genre_complete": "Five-Genre Sorcerer Mastery",
        "m_full_collection": "Full Cursed Manga Collection",
        "m_batch_complete": "Batch Mission Clear Sorcerer",
        "m_paused_to_done": "Returned from Manga Hiatus",
        "m_completion_spree": "Black Flash Reading Spree",
        "m_format_completionist": "Format Completion Sorcerer Badge",
        "m_catch_up": "Caught Up with Serialization",
        "m_multi_reread": "Multi-Reread Cursed Manga",
        "m_dropped_recovery": "Recovered from Manga Dropout",
        "m_ten_perfect_scores": "Ten Perfect Sorcerer Scores",
        "m_complete_genre_span": "All-Around Cursed Reader",
        "m_monthly_completions": "Monthly Sorcerer Manga Reports",
        "m_yearly_completions": "Annual Jujutsu Manga Review",
        "m_rapid_complete": "Rapid Cursed Manga Clear",
        "m_author_complete": "Author's Complete Cursed Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Jujutsu Manga Reader",
        "m_mangaka_lover": "Akutami Devotee",
        "m_rereader": "Cursed Manga Rereader",
        "m_triple_reread": "Triple Cursed Reread",
        "m_annual_reread": "Annual Cursed Reread Tradition",
        "m_publisher_fan": "Sorcerer Publisher Fan",
        "m_artist_fan": "Cursed Artist Appreciation",
        "m_adaptation_compare": "Manga vs Anime Sorcerer Compare",
        "m_source_material_fan": "Source Material Sorcerer Fan",
        "m_waiting_weekly": "Weekly Cursed Chapter Wait",
        "m_classic_reader": "Classic Cursed Manga Reader",
        "m_saga_reader": "Cursed Saga Reader",
        "m_genre_loyalty": "Genre Loyalty Sorcerer Medal",
        "m_decade_reader": "Decade-Long Cursed Reader",
        "m_ln_adaptation": "Light Novel Cursed Adaptation",
        "m_original_work": "Original Cursed Manga Work",
        "m_long_commitment": "Long-Term Sorcerer Commitment",
        "m_up_to_date": "Up-to-Date with Cursed Manga",
        "m_favorite_mangaka": "Favorite Cursed Mangaka",
        "m_complete_portfolio": "Complete Cursed Portfolio",
        "m_franchise_collector": "Jujutsu Franchise Collector",
        "m_serialization_follower": "Cursed Serialization Follower",
        "m_genre_master": "Genre Cursed Manga Mastery",
        "m_multi_series_author": "Multi-Series Cursed Author Fan",
        "m_format_diversity": "Diverse Cursed Reading Formats",
        "m_year_dedication": "Year of Jujutsu Reading",
        "m_ongoing_follower": "Ongoing Cursed Series Follower",
        "m_genre_loyalty_50": "Fifty Cursed Genre Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Cursed Genre Explorer",
        "m_publisher_hopper": "Jujutsu Publisher Transfer",
        "m_tag_explorer": "Sorcerer Tag Recon Mission",
        "m_decade_hopper": "Era-Hopping Cursed Reader",
        "m_hidden_gem": "Hidden Cursed Gem Manga",
        "m_popular_taste": "Popular Among Sorcerer Readers",
        "m_retro_reader": "Retro Cursed Manga Reader",
        "m_modern_reader": "Modern Cursed Era Reader",
        "m_cross_demographic": "Cross-School Reader",
        "m_underdog_fan": "Underdog Cursed Manga Fan",
        "m_variety_week": "Week of Varied Cursed Reads",
        "m_manhwa_reader": "Manhwa Cursed Reader",
        "m_manhua_reader": "Manhua Cursed Reader",
        "m_classic_connoisseur": "Classic Cursed Manga Connoisseur",
        "m_award_winner": "Award-Winning Cursed Manga",
        "m_niche_explorer": "Underground Cursed Manga",
        "m_world_manga": "World Cursed Manga Intel",
        "m_cult_classic": "Cult Classic Cursed Tale Manga",
        "m_random_pick": "Random Cursed Assignment",
        "m_new_genre_month": "New Cursed Genre Monthly",
        "m_year_completionist": "Year Cursed Manga Completionist",
        "m_unpopular_opinion": "Unpopular Cursed Manga Opinion",
        "m_top_rated_reader": "Top-Ranked Cursed Manga",
        "m_source_variety": "Cursed Source Material Variety",
        "m_low_score_brave": "Brave Cursed Low-Score Reader",
        "m_short_manga_explorer": "Short Cursed Manga Skirmish",
        "m_long_manga_explorer": "Long Cursed Manga Campaign",
        "m_serialization_explorer": "Cursed Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Cursed Reader",
        "m_early_bird": "Dawn Patrol Cursed Reader",
        "m_lunch_reader": "Lunch at Jujutsu High Reader",
        "m_commute_reader": "Commute to Jujutsu High Reader",
        "m_four_am_club": "4 AM Cursed Study Session",
        "m_new_year_read": "New Year's Sorcerer Reading Oath",
        "m_all_hours": "All-Hours Cursed Reader",
        "m_prime_time_reader": "Prime Time Cursed Manga",
        "m_workday_reader": "On-Duty Sorcerer Reader",
        "m_sunday_read": "Sunday Cursed Reading Marathon",
        "m_morning_routine": "Morning Cursed Energy Reading",
        "m_night_shift_reader": "Night Shift Cursed Reader",
        "m_seasonal_premier_read": "New Cursed Release Reader",
        "m_clock_collector": "Clock Tower Cursed Reading",
        "m_late_night_horror": "Midnight Cursed Horror Read",
        "m_afternoon_reader": "Afternoon Cursed Reader",
        "m_golden_hour_reader": "Golden Hour Cursed Reading",
        "m_dawn_reader": "Dawn Cursed Reading",
        "m_twilight_reader": "Twilight Cursed Reader",
        "m_midnight_start": "Midnight Cursed Reading Start",
        "m_weekend_binge_hours": "Weekend Cursed Binge Reading",
        "m_late_night_regular": "Late Night Regular Reader",
        "m_sunrise_reader": "Sunrise Over Jujutsu High Reader",
        "m_every_day_of_week": "Every Day Cursed Reading",
        "m_monthly_hours": "Monthly Cursed Reading Hours",
        "m_bedtime_reader": "Bedtime Jujutsu Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Akutami Art Appreciator",
        "m_webtoon_reader": "Cursed Webtoon Reader",
        "m_full_color": "Full Color Cursed Manga",
        "m_doujin_reader": "Cursed Doujin Reader",
        "m_anthology_reader": "Cursed Anthology Reader",
        "m_adaptation_reader": "Cursed Adaptation Reader",
        "m_longstrip_reader": "Vertical Cursed Scroll",
        "m_4koma_reader": "Cursed 4-Koma Shorts",
        "m_oneshot_reader": "Cursed Oneshot Mission",
        "m_format_variety": "Cursed Format Variety",
        "m_light_novel_reader": "Cursed Light Novel Reader",
        "m_novel_reader": "Cursed Novel Archives",
        "m_visual_storyteller": "Visual Cursed Narrator",
        "m_colored_classic": "Colored Classic Cursed Manga",
        "m_webcomic_fan": "Cursed Webcomic Fan",
        "m_manga_to_anime": "Manga to Anime Cursed Compare",
        "m_seinen_reader": "Seinen Cursed Reader",
        "m_josei_reader": "Josei Cursed Perspective",
        "m_award_winning_art": "Award-Winning Cursed Artwork",
        "m_debut_work": "Cursed Debut Manuscript",
        "m_vertical_scroll": "Vertical Scroll Cursed Energy",
        "m_traditional_format": "Traditional Cursed Format",
        "m_cross_media": "Cross-Media Cursed Intel",
        "m_spinoff_reader": "Cursed Spinoff Reader",
        "m_remake_reader": "Cursed Remake Reader",
        "m_collaboration_reader": "Cursed Collaboration Manga",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Cursed Reading Streak",
        "m_mega_streak": "Mega Cursed Reading Streak",
        "m_weekly_warrior": "Weekly Warrior Cursed Reader",
        "m_monthly_reader": "Monthly Cursed Reader",
        "m_comeback": "Cursed Reader's Comeback",
        "m_weekend_streak": "Weekend Cursed Reading Streak",
        "m_no_zero_days": "No Zero Cursed Reading Days",
        "m_iron_will": "Iron Will Cursed Reader",
        "m_habit_formed": "Cursed Reading Habit Formed",
        "m_consistent_pace": "Consistent Cursed Reading Pace",
        "m_year_long": "Year-Long Cursed Reading",
        "m_double_streak": "Double Cursed Reading Streak",
        "m_streak_recovery": "Cursed Streak Recovery",
        "m_daily_minimum": "Daily Minimum Cursed Pages",
        "m_winter_streak": "Winter Cursed Reading Streak",
        "m_summer_streak": "Summer Training Reading Streak",
        "m_morning_streak": "Morning Cursed Reading Streak",
        "m_night_streak": "Night Cursed Reading Streak",
        "m_unbreakable": "Unbreakable Cursed Reader",
        "m_eternal_flame": "Todo's Eternal Reading Energy",
        "m_chapter_a_day": "Chapter a Day Sorcerer",
        "m_genre_streak": "Genre Cursed Reading Streak",
        "m_completion_streak": "Cursed Completion Reading Chain",
        "m_rating_streak": "Cursed Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Cursed Streak",
        "m_author_streak": "Author Cursed Dedication Streak",
        "m_perfect_week_manga": "Perfect Cursed Reading Week",
        "m_diverse_streak": "Diverse Cursed Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Cursed Manga Critic",
        "m_perfect_ten": "Perfect 10 Cursed Manga",
        "m_harsh_critic": "Nanami's Reading Standards",
        "m_fair_judge": "Gojo's Manga Review",
        "m_generous_spirit": "Generous Cursed Reader",
        "m_score_all": "Full Sorcerer Manga Assessment",
        "m_wide_range": "Wide Range Cursed Scores",
        "m_controversial": "Controversial Cursed Rating",
        "m_consistent_scorer": "Consistent Cursed Manga Scorer",
        "m_score_sniper": "Precision Cursed Score Sniper",
        "m_evolving_taste": "Evolving Cursed Reading Taste",
        "m_bell_curve": "Bell Curve Cursed Scores",
        "m_picky_reader": "Selective Cursed Reader",
        "m_100_rated": "Century of Cursed Manga Ratings",
        "m_500_rated": "Five Hundred Cursed Manga Reports",
        "m_mediocre_majority": "Grade Two Cursed Reader",
        "m_rating_spree": "Cursed Rating Spree",
        "m_score_variance": "Variable Cursed Manga Scores",
        "m_binge_rater": "Binge Cursed Rating Session",
        "m_reread_rerate": "Reread & Re-Rate Cursed Manga",
        "m_masterpiece_hunter": "Masterpiece Cursed Manga Hunter",
        "m_contrarian": "Contrarian Cursed Reader",
        "m_optimist": "Optimist Cursed Reader",
        "m_score_distributor": "Cursed Score Distributor",
        "m_genre_critic": "Genre Cursed Manga Critic",
        "m_mean_above_8": "Elite Cursed Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Cursed Reading Vow",
        "m_valentines_read": "Valentine's Cursed Reading",
        "m_pi_day": "Pi Day Cursed Chapter Count",
        "m_april_fools": "April Fools Cursed Manga",
        "m_international_manga_day": "International Cursed Manga Day",
        "m_free_comic_day": "Free Cursed Comic Day",
        "m_summer_solstice": "Summer Solstice Cursed Reading",
        "m_tanabata": "Tanabata Cursed Reading Wish",
        "m_friday_13th": "Friday 13th Cursed Manga",
        "m_halloween_read": "Halloween Cursed Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Cursed Reading Feast",
        "m_christmas_read": "Christmas Jujutsu High Reading",
        "m_new_years_eve": "New Year's Eve Cursed Read",
        "m_birthday_read": "Birthday Cursed Reading Gift",
        "m_holiday_marathon": "Holiday Cursed Reading Marathon",
        "m_independence_day": "Sorcerer Independence Reading Day",
        "m_culture_day": "Jujutsu Culture Festival Reading",
        "m_spring_equinox": "Spring Cursed Reading",
        "m_earth_day": "Earth Day Cursed Reading",
        "m_labor_day": "Sorcerer Labor Reading Day",
        "m_winter_solstice": "Winter Solstice Cursed Reading",
        "m_manga_birthday": "Cursed Manga Birthday",
        "m_every_holiday_reader": "Every Holiday Cursed Reader",
        "m_consecutive_holidays": "Consecutive Holiday Cursed Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Sorcerer Milestone",
        "m_fibonacci": "Fibonacci Cursed Pattern",
        "m_palindrome_day": "Palindrome Cursed Reading Day",
        "m_binary_day": "Binary Cursed Reading Day",
        "m_full_moon_read": "Full Moon Cursed Read",
        "m_leap_year_read": "Leap Year Cursed Reading",
        "m_triple_seven": "Triple Seven Sorcerer Combo",
        "m_thousand_complete": "Thousand Cursed Manga Victories",
        "m_nice": "Nice Cursed Chapter Count",
        "m_power_level_chapters": "Unlimited Void Chapter Power",
        "m_answer_42": "Answer to Kenjaku's Riddle Manga",
        "m_square_number": "Perfect Sorcerer Formation",
        "m_prime_count": "Prime Cursed Chapter Count",
        "m_matching_date": "Matching Cursed Reading Date",
        "m_century_chapter": "Century Cursed Chapter",
        "m_pi_chapters": "Pi Cursed Chapter Calculation",
        "m_synchronicity": "Cursed Reading Synchronicity",
        "m_world_record": "World Record Cursed Chapters",
        "m_genre_clash": "Genre Clash Cursed Reading",
        "m_time_traveler": "Heian Era Memory Reading",
        "m_double_digits": "Double Digit Cursed Milestone",
        "m_one_two_three": "Techniques One Two Three Manga",
        "m_lucky_seven": "Seven Lucky Sorcerer Chapters",
        "m_exact_hundred_ch": "Exact Hundred Cursed Chapters",
        "m_year_match_count": "Year Match Cursed Chapter Count",
        "m_chapter_match_date": "Chapter Date Cursed Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Cursed Manga Format",
        "m_manhwa_format": "Manhwa Cursed Format",
        "m_manhua_format": "Manhua Cursed Format",
        "m_ln_format": "Light Novel Cursed Format",
        "m_oneshot_format": "Oneshot Cursed Format",
        "m_doujin_format": "Doujin Cursed Format",
        "m_novel_format": "Novel Cursed Format",
        "m_format_master_manga": "Format Master Cursed Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Cursed Reading Awakened",
        "m_meta_collector": "Cursed Reading Badge Collector",
        "m_meta_category_starter": "Cursed Category Initiation",
        "m_meta_tier_climber": "Cursed Reading Grade Promotion",
        "m_meta_tier_max": "Maximum Cursed Reading Grade",
        "m_meta_xp_earner": "XP from Cursed Reading",
        "m_meta_difficulty_easy": "Easy Cursed Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Cursed Manga Challenge",
        "m_meta_unlock_spree": "Cursed Reading Unlock Spree",
        "m_meta_completionist": "Meta Cursed Reading Completionist",
        "m_meta_diverse": "Diverse Cursed Reading Portfolio",
        "m_meta_dominator": "Meta Cursed Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040208",
        primary: "#6432c8",
        secondary: "#8050e0",
        accent: "#a070f0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/jujutsu-kaisen.png",
    particleColor: "#4060b0",
    backgroundDim: 0.28,
    backgroundBlur: 28,
    particleTypes: {
        cursed_energy: { label: "Cursed Energy", maxCount: 16, defaultEnabled: true, defaultIntensity: 65 },
        domain_cracks: { label: "Domain Cracks", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        sukuna_marks: { label: "Sukuna Marks", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        reverse_cursed: { label: "Reverse Cursed", maxCount: 12, defaultEnabled: true, defaultIntensity: 60 },
        black_flash: { label: "Black Flash", maxCount: 6, defaultEnabled: true, defaultIntensity: 70 },
    },
    playerIconOverrides: jujutsuKaisenPlayerIcons,
    milestoneNames: {
        1:   "Grade 4",
        8:   "Grade 3",
        18:  "Semi-Grade 2",
        28:  "Grade 2",
        40:  "Semi-Grade 1",
        52:  "Grade 1",
        65:  "Special Grade",
        80:  "Jujutsu Elders",
        100: "Gojo-Level",
    },
}
