import { AnimeThemeConfig } from "./types"
import {
    GiVortex,
    GiSandsOfTime,
    GiSkull,
    GiEyeball,
    GiSpiderWeb,
    GiBrain,
    GiPuzzle,
    GiGhost,
    GiResize,
    GiTrophy,
    GiPalette,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const junjiItoTheme: AnimeThemeConfig = {
    id: "junji-ito",
    displayName: "Junji Ito",
    description: "Enter the spiral. Tomie whispers, Uzumaki coils tighten, Souichi grins, and the Enigma of Amigara Fault calls your name.",
    fontFamily: "'Nosifer', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Nosifer&display=swap",
    cssVars: {
        // Brand → dark purple with body-horror undertones
        "--color-brand-200": "180 130 180",
        "--color-brand-300": "150 90 150",
        "--color-brand-400": "118 58 118",
        "--color-brand-500": "80 30 80",
        "--color-brand-600": "64 20 64",
        "--color-brand-700": "48 12 48",
        "--color-brand-800": "34 6 34",
        "--color-brand-900": "20 3 20",
        "--color-brand-950": "10 1 10",
        "--brand": "80 30 80",
        // Abyss-black background
        "--background": "#060306",
        "--paper": "#0c060c",
        "--color-gray-950": "6 3 6",
        "--color-gray-900": "12 6 12",
        "--color-gray-800": "24 14 24",
        "--color-gray-700": "38 24 38",
        "--color-gray-600": "58 40 58",
        "--color-gray-500": "82 62 82",
        "--color-gray-400": "125 102 125",
        "--color-gray-300": "162 142 162",
        "--color-gray-200": "198 184 198",
        "--color-gray-100": "228 220 228",
        "--color-gray-50": "244 240 244",
    },
    sidebarOverrides: {
        "home": { icon: GiVortex, label: "The Spiral" },
        "schedule": { icon: GiSandsOfTime, label: "Cursed Calendar" },
        "manga": { icon: LuBookOpen, label: "Forbidden Tomes" },
        "lists": { icon: GiSkull, label: "Death Registry" },
        "discover": { icon: GiEyeball, label: "Glimpse Beyond" },
        "torrent-list": { icon: GiSpiderWeb, label: "Web of Flesh" },
        "debrid": { icon: GiBrain, label: "Neural Harvest" },
        "unmatched": { icon: GiGhost, label: "Lost Souls" },
        "enmasse": { icon: GiResize, label: "Mass Infection" },
        "scan-summaries": { icon: TbReportSearch, label: "Autopsy Reports" },
        "auto-downloader": { icon: LuRss, label: "Whispered Feed" },
        "community": { icon: GiPuzzle, label: "Amigara Fault" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Death Knells" },
        "achievements": { icon: GiTrophy, label: "Cursed Trophies" },
        "theme-manager": { icon: GiPalette, label: "Ink & Shadow" },
        "extensions": { icon: BiExtension, label: "Body Extensions" },
        "sync": { icon: IoCloudOfflineOutline, label: "Phantom Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Twisted Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Nightmare",
        "a_episode_counter": "Horror Tally",
        "a_episode_titan": "Abyssal Count",
        "a_hours_invested": "Cursed Hours",
        "a_time_lord": "Time Aberration",
        "a_anime_collector": "Cursed Collection",
        "a_library_legend": "Forbidden Library",
        "a_first_complete": "First Ritual",
        "a_hundred_club": "Centipede Club",
        "a_first_day": "First Infection",
        "a_first_rating": "First Autopsy",
        "a_ten_thousand_min": "Eternal Dread",
        "a_season_veteran": "Horror Veteran",
        "a_year_explorer": "Year of Dread",
        "a_century_watcher": "Century Haunt",
        "a_five_hundred_eps": "Flesh Archive",
        "a_thousand_eps": "Thousand Terrors",
        "a_watching_ten": "Ten Spirals",
        "a_ptw_hoarder": "Dread Hoarder",
        "a_dropped_honesty": "Severed Nerve",
        "a_five_thousand_eps": "Infinite Spiral",
        "a_ten_completed": "Ten Curses",
        "a_fifty_completed": "Fifty Nightmares",
        "a_five_hundred_completed": "Mass Haunting",
        "a_mean_score_tracker": "Horror Rating",
        "a_unique_studios": "Twisted Studios",
        "a_days_spent_watching": "Days Consumed",
        "a_all_status": "All Afflictions",
        "a_first_favorite": "First Obsession",
        "a_favorites_collector": "Obsession Hoard",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Sleepless Terror",
        "a_marathon_runner": "Horror Marathon",
        "a_weekend_warrior": "Weekend Dread",
        "a_non_stop": "Relentless Spiral",
        "a_one_more_episode": "One More Curse",
        "a_speed_run": "Frantic Escape",
        "a_double_feature": "Double Haunt",
        "a_triple_threat": "Triple Curse",
        "a_five_a_day": "Five Torments",
        "a_back_to_back": "Endless Corridor",
        "a_seasonal_binge": "Seasonal Plague",
        "a_cour_crusher": "Cour Crusher",
        "a_half_day_watch": "Half-Day Vigil",
        "a_full_day_watch": "Full-Day Descent",
        "a_power_weekend": "Nightmare Weekend",
        "a_binge_king": "Binge Abomination",
        "a_no_sleep": "Insomnia Curse",
        "a_entire_season": "Season Consumed",
        "a_seven_day_challenge": "Seven-Day Haunt",
        "a_hundred_day_binge": "Hundred-Day Curse",
        "a_genre_binge": "Genre Infection",
        "a_studio_binge": "Studio Devourer",
        "a_season_sweep": "Season Devoured",
        "a_forty_eight_hour": "Sleepless Vigil",
        "a_ep_counter_day": "Daily Torment",
        "a_multi_series_binge": "Multi-Horror Binge",
        "a_midnight_binge": "Midnight Dread",
        "a_new_year_binge": "New Year Hex",

        // ── ANIME GENRES ──
        "a_genre_action": "Violent Spiral",
        "a_genre_adventure": "Forbidden Path",
        "a_genre_comedy": "Twisted Laughter",
        "a_genre_drama": "Agonized Flesh",
        "a_genre_fantasy": "Dark Fantasy",
        "a_genre_horror": "Pure Horror",
        "a_genre_mystery": "Enigma Seeker",
        "a_genre_romance": "Cursed Love",
        "a_genre_scifi": "Body Technology",
        "a_genre_sol": "Quiet Dread",
        "a_genre_sports": "Twisted Contest",
        "a_genre_supernatural": "Supernatural Curse",
        "a_genre_thriller": "Crawling Fear",
        "a_genre_mecha": "Flesh Machine",
        "a_genre_music": "Haunted Melody",
        "a_genre_psychological": "Fractured Mind",
        "a_genre_ecchi": "Flesh Display",
        "a_genre_mahou_shoujo": "Dark Witch",
        "a_tag_isekai": "Other Realm",
        "a_tag_harem": "Twisted Bonds",
        "a_tag_bl": "Darkened Bond",
        "a_tag_gl": "Shadow Sisters",
        "a_tag_historical": "Ancient Horror",
        "a_tag_military": "War Horror",
        "a_tag_school": "Cursed Academy",
        "a_tag_martial_arts": "Body Combat",
        "a_tag_vampire": "Blood Curse",
        "a_tag_samurai": "Blade Phantom",
        "a_tag_space": "Cosmic Horror",
        "a_tag_parody": "Horror Parody",
        "a_tag_idol": "Cursed Stage",
        "a_tag_post_apocalyptic": "After Ruin",
        "a_tag_cyberpunk": "Flesh Circuit",
        "a_tag_shounen": "Young Horror",
        "a_tag_seinen": "Mature Terror",
        "a_tag_shoujo": "Dark Devotion",
        "a_tag_josei": "Obsessive Gaze",
        "a_tag_survival": "Survival Horror",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Dissection",
        "a_mega_completionist": "Master Collector",
        "a_completion_rate_50": "Half Consumed",
        "a_completion_rate_75": "Nearly Devoured",
        "a_completion_rate_90": "Almost Whole",
        "a_no_drop": "No Escape",
        "a_long_runner_complete": "Long Nightmare",
        "a_sequel_chain": "Chain Link",
        "a_clean_list": "Clean Dissection",
        "a_from_ptw": "Fate Accepted",
        "a_rewatch_master": "Recurring Dream",
        "a_short_complete": "Quick Death",
        "a_same_day_start_finish": "Same-Day Curse",
        "a_revival": "Resurrection Hex",
        "a_zero_to_hero": "Worm to Horror",
        "a_five_genre_complete": "Five Afflictions",
        "a_full_franchise": "Full Corruption",
        "a_batch_complete": "Batch Consumed",
        "a_paused_to_done": "Returned Curse",
        "a_completion_spree": "Horror Spree",
        "a_multi_rewatch": "Recurring Vision",
        "a_dropped_recovery": "Recovered Flesh",
        "a_ten_perfect_scores": "Ten Perfections",
        "a_seasonal_clear": "Seasonal Purge",
        "a_complete_genre_span": "Genre Dissection",
        "a_monthly_completions": "Monthly Horrors",
        "a_yearly_completions": "Yearly Nightmares",
        "a_rapid_complete": "Rapid Infection",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Devotee",
        "a_studio_devotee": "Studio Thrall",
        "a_rewatcher": "Haunted Rewatch",
        "a_triple_rewatch": "Triple Haunting",
        "a_annual_tradition": "Annual Ritual",
        "a_director_fan": "Director's Curse",
        "a_voice_actor_fan": "Whispered Voice",
        "a_ost_lover": "Eerie Soundtrack",
        "a_source_reader": "Source Grimoire",
        "a_waiting_weekly": "Weekly Dread",
        "a_childhood_revisit": "Childhood Horror",
        "a_saga_tracker": "Saga Stalker",
        "a_genre_loyalty": "Genre Devotion",
        "a_decade_watcher": "Decade Haunted",
        "a_adaptation_hunter": "Adaptation Seeker",
        "a_original_anime_fan": "Original Horror",
        "a_long_commitment": "Long Torment",
        "a_perfect_attendance": "Perfect Curse",
        "a_favorite_studio_5": "Five Dark Studios",
        "a_complete_catalog": "Complete Grimoire",
        "a_franchise_collector": "Franchise Horror",
        "a_airing_follower": "Airing Dread",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Staff Obsession",
        "a_multi_season_fan": "Multi-Season Haunt",
        "a_format_diversity": "Diverse Horrors",
        "a_year_dedication": "Year of Horror",
        "a_season_dedication": "Season of Dread",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Genre Crawler",
        "a_studio_hopper": "Studio Drifter",
        "a_tag_explorer": "Tag Excavator",
        "a_decade_hopper": "Decade Phantom",
        "a_hidden_gem": "Hidden Curse",
        "a_popular_taste": "Popular Dread",
        "a_retro_appreciator": "Retro Horror",
        "a_modern_viewer": "Modern Malice",
        "a_cross_demographic": "Cross Affliction",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Horrors",
        "a_foreign_cinema": "Foreign Fright",
        "a_classic_connoisseur": "Classic Terror",
        "a_every_season": "Every Curse",
        "a_award_winner": "Cursed Award",
        "a_niche_explorer": "Niche Horror",
        "a_global_anime": "Global Nightmare",
        "a_cult_classic": "Cult Horror",
        "a_random_pick": "Random Curse",
        "a_new_genre_month": "Monthly Discovery",
        "a_seasonal_completionist": "Seasonal Rite",
        "a_unpopular_opinion": "Twisted Opinion",
        "a_top_rated_viewer": "Top Rated Dread",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Descent",
        "a_upcoming_watcher": "Upcoming Terror",
        "a_short_series_explorer": "Brief Nightmare",
        "a_long_series_explorer": "Long Descent",

        // ── ANIME TIME ──
        "a_night_owl": "Night Crawler",
        "a_early_bird": "Dawn Phantom",
        "a_lunch_break": "Midday Shadow",
        "a_golden_hour": "Golden Nightmare",
        "a_four_am_club": "4 AM Specter",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Omen",
        "a_midnight_premiere": "Midnight Terror",
        "a_all_hours": "All-Hours Haunt",
        "a_dawn_warrior": "Dawn Wraith",
        "a_afternoon_delight": "Afternoon Shade",
        "a_prime_time": "Prime Nightmare",
        "a_workday_watcher": "Workday Horror",
        "a_sunday_marathon": "Sunday Descent",
        "a_rainy_day": "Rainy Nightmare",
        "a_morning_routine": "Morning Ritual",
        "a_night_shift": "Night Terror",
        "a_twilight_zone": "Twilight Spiral",
        "a_seasonal_premier": "Seasonal Premiere",
        "a_clock_collector": "Clock Curse",
        "a_weekend_binge_hours": "Weekend Vigil",
        "a_late_night_regular": "Late Night Haunt",
        "a_sunrise_watcher": "Sunrise Omen",
        "a_holiday_watcher": "Holiday Horror",
        "a_every_day_of_week": "Every Day Cursed",
        "a_monthly_hours": "Monthly Haunting",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Séance",
        "a_party_host": "Séance Host",
        "a_social_butterfly": "Social Specter",
        "a_group_binge": "Group Haunt",
        "a_party_regular": "Regular Ghoul",
        "a_sync_viewer": "Synced Spiral",
        "a_commentator": "Dark Narrator",
        "a_party_marathon": "Marathon Séance",
        "a_full_house": "Full Coven",
        "a_community_pillar": "Pillar of Dread",
        "a_watch_party_streak": "Séance Streak",
        "a_diverse_party": "Diverse Coven",
        "a_late_night_party": "Midnight Coven",
        "a_party_veteran": "Veteran Ghoul",
        "a_genre_party": "Genre Séance",
        "a_weekly_party": "Weekly Gathering",
        "a_silent_viewer": "Silent Watcher",
        "a_recommendation_giver": "Cursed Whisper",
        "a_party_completionist": "Coven Complete",
        "a_social_scorer": "Social Phantom",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Aberration",
        "a_fibonacci": "Fibonacci Spiral",
        "a_palindrome_day": "Palindrome Curse",
        "a_binary_day": "Binary Horror",
        "a_full_moon": "Full Moon Curse",
        "a_leap_year": "Leap Year Hex",
        "a_time_traveler": "Temporal Rift",
        "a_genre_clash": "Genre Collision",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Horrors",
        "a_pi_episodes": "Pi Calculation",
        "a_synchronicity": "Dark Synchronicity",
        "a_world_record": "World Record Haunt",
        "a_nice": "Nice Spiral",
        "a_power_level": "Power Grotesque",
        "a_answer_42": "Answer to Fear",
        "a_square_number": "Square Anomaly",
        "a_prime_count": "Prime Aberration",
        "a_matching_date": "Matching Omen",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens Cursed",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Haunt",
        "a_movie_buff": "Film Horror",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Curse",
        "a_short_king": "Short Fright",
        "a_variety_pack": "All-Format Horror",
        "a_film_festival": "Horror Festival",
        "a_music_video": "Cursed Clip",
        "a_tv_short": "Quick Scare",
        "a_movie_marathon": "Film Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Horror Anthology",
        "a_mini_series": "Mini Nightmare",
        "a_theatrical": "Theatrical Horror",
        "a_format_master": "Format Phantom",
        "a_long_movie": "Long Film",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "Commercial Curse",
        "a_pv_collector": "Preview Omen",
        "a_format_balance": "Format Balance",
        "a_episodic_master": "Episodic Phantom",
        "a_sequel_movie": "Sequel Horror",
        "a_recap_watcher": "Recap Haunt",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Haunt",
        "a_mega_streak": "Mega Spiral",
        "a_weekly_warrior": "Weekly Wraith",
        "a_monthly_watcher": "Monthly Phantom",
        "a_comeback": "Dark Return",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Cursed",
        "a_consistent_pace": "Consistent Dread",
        "a_year_long": "Year-Long Curse",
        "a_double_streak": "Double Spiral",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Horror",
        "a_summer_streak": "Summer Terror",
        "a_morning_streak": "Morning Haunt",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable Will",
        "a_eternal_flame": "Eternal Darkness",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Episode Hex",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Horror Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Harsh Judgment",
        "a_fair_judge": "Fair Autopsy",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Score All",
        "a_wide_range": "Wide Spectrum",
        "a_controversial": "Controversial Curse",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Score Sniper",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Picky Watcher",
        "a_100_rated": "Hundred Rated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Mediocre Majority",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Seeker",
        "a_contrarian": "Contrarian Spirit",
        "a_optimist": "Dark Optimist",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Vow",
        "a_valentines_weeb": "Valentine Curse",
        "a_pi_day": "Pi Day Spiral",
        "a_april_fools": "April Fools Hex",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "May Fourth",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Curse",
        "a_friday_13th": "Friday the 13th",
        "a_halloween_spirit": "Halloween Horror",
        "a_thanksgiving_binge": "Thanksgiving Feast",
        "a_christmas_special": "Midwinter Curse",
        "a_new_years_eve": "New Year's Eve",
        "a_birthday_watch": "Birthday Curse",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Independence Hex",
        "a_culture_day": "Culture Curse",
        "a_spring_equinox": "Spring Equinox",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Curse",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anime Birthday",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Consecutive Curses",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Awakening",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Initiate",
        "a_meta_tier_climber": "Tier Climber",
        "a_meta_tier_max": "Maximum Tier",
        "a_meta_xp_earner": "XP Harvester",
        "a_meta_difficulty_easy": "Easy Horror",
        "a_meta_difficulty_hard": "Legendary Terror",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Completionist",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Ink Drop",
        "m_chapter_counter": "Chapter Tally",
        "m_chapter_titan": "Colossal Chapter",
        "m_reading_hours": "Ink-Stained Hours",
        "m_reading_time_lord": "Time Warp Reader",
        "m_manga_collector": "Tome Collector",
        "m_library_legend": "Forbidden Tome",
        "m_first_complete": "First Tome Sealed",
        "m_hundred_club": "Hundred Scrawls",
        "m_first_day": "First Dark Page",
        "m_first_rating": "First Ink Verdict",
        "m_ten_thousand_pages": "Ten Thousand Scrawls",
        "m_volume_collector": "Volume Hoarder",
        "m_year_explorer": "Year of Ink",
        "m_century_reader": "Century of Pages",
        "m_five_hundred_ch": "Five Hundred Inked",
        "m_thousand_ch": "Thousand Scratches",
        "m_reading_ten": "Ten Open Tomes",
        "m_ptr_hoarder": "Backlog Abyss",
        "m_dropped_honesty": "Severed Bookmark",
        "m_season_reader": "Seasonal Ink",
        "m_active_reader": "Active Scrawler",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Tomes Sealed",
        "m_fifty_completed": "Fifty Tomes Sealed",
        "m_five_hundred_completed": "Mass Sealing",
        "m_mean_score_tracker": "Ink Rating",
        "m_unique_authors": "Unique Mangaka",
        "m_all_status": "All Ink Statuses",
        "m_first_favorite": "First Ink Love",
        "m_favorites_collector": "Dark Favorites",
        "m_days_spent_reading": "Days in Ink",

        // ── MANGA BINGE ──
        "m_binge_reader": "Ink Binge",
        "m_marathon_reader": "Ink Marathon",
        "m_weekend_reader": "Weekend Ink",
        "m_non_stop_reading": "Non-Stop Scrawl",
        "m_one_more_chapter": "One More Page",
        "m_speed_read": "Speed Scrawl",
        "m_double_story": "Double Tome",
        "m_triple_read": "Triple Tome",
        "m_five_a_day": "Five Daily Tomes",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Consumed",
        "m_power_reader": "Power Scrawler",
        "m_half_day_read": "Half-Day Ink",
        "m_full_day_read": "Full-Day Ink",
        "m_power_weekend": "Power Ink Weekend",
        "m_binge_king": "Ink Devourer",
        "m_no_sleep_read": "Sleepless Ink",
        "m_full_series_rush": "Full Tome Rush",
        "m_seven_day_challenge": "Seven-Day Ink",
        "m_hundred_day_read": "Hundred-Day Ink",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Swept",
        "m_genre_binge": "Genre Ink Binge",
        "m_author_binge": "Author Consumed",
        "m_chapter_counter_day": "Daily Ink Count",
        "m_multi_series_binge": "Multi-Tome Binge",
        "m_midnight_binge": "Midnight Ink",
        "m_new_year_binge": "New Year Ink",
        "m_forty_eight_hour": "Forty-Eight Ink",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Ink",
        "m_genre_adventure": "Adventure Ink",
        "m_genre_comedy": "Comedy Ink",
        "m_genre_drama": "Drama Ink",
        "m_genre_fantasy": "Fantasy Ink",
        "m_genre_horror": "Horror Ink",
        "m_genre_mystery": "Mystery Ink",
        "m_genre_romance": "Romance Ink",
        "m_genre_scifi": "Sci-Fi Ink",
        "m_genre_sol": "Slice of Dread",
        "m_genre_sports": "Sports Ink",
        "m_genre_supernatural": "Supernatural Ink",
        "m_genre_thriller": "Thriller Ink",
        "m_genre_psychological": "Psych Ink",
        "m_genre_isekai": "Isekai Ink",
        "m_genre_shounen": "Shounen Ink",
        "m_genre_ecchi": "Ecchi Ink",
        "m_genre_mahou_shoujo": "Mahou Ink",
        "m_genre_mecha": "Mecha Ink",
        "m_genre_music": "Music Ink",
        "m_tag_isekai_new": "New Realm Ink",
        "m_tag_harem": "Harem Ink",
        "m_tag_bl": "BL Ink",
        "m_tag_gl": "GL Ink",
        "m_tag_historical": "Historical Ink",
        "m_tag_military": "Military Ink",
        "m_tag_school": "School Ink",
        "m_tag_martial_arts": "Martial Arts Ink",
        "m_tag_vampire": "Vampire Ink",
        "m_tag_samurai": "Samurai Ink",
        "m_tag_space": "Space Ink",
        "m_tag_parody": "Parody Ink",
        "m_tag_idol": "Idol Ink",
        "m_tag_post_apocalyptic": "Post-Ruin Ink",
        "m_tag_cyberpunk": "Cyberpunk Ink",
        "m_tag_shoujo": "Shoujo Ink",
        "m_tag_survival": "Survival Ink",
        "m_tag_cooking": "Cooking Ink",
        "m_tag_medical": "Medical Ink",
        "m_tag_villainess": "Villainess Ink",

        // ── MANGA COMPLETION ──
        "m_completionist": "Tome Completionist",
        "m_mega_completionist": "Mega Completionist",
        "m_completion_rate_50": "Half Devoured",
        "m_completion_rate_75": "Nearly Finished",
        "m_completion_rate_90": "Almost Consumed",
        "m_no_drop": "No Tome Dropped",
        "m_long_runner_complete": "Long Tome Done",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean Ink List",
        "m_from_ptr": "Orders Consumed",
        "m_reread_master": "Reread Phantom",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Tome",
        "m_revival": "Tome Revival",
        "m_zero_to_hundred": "Zero to Hundred",
        "m_five_genre_complete": "Five Genre Tomes",
        "m_full_collection": "Full Ink Archive",
        "m_batch_complete": "Batch Devoured",
        "m_paused_to_done": "Resumed Tome",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi Reread",
        "m_dropped_recovery": "Recovered Tome",
        "m_ten_perfect_scores": "Ten Ink Perfects",
        "m_complete_genre_span": "Genre Span",
        "m_monthly_completions": "Monthly Tomes",
        "m_yearly_completions": "Yearly Tomes",
        "m_rapid_complete": "Rapid Finish",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Devotee",
        "m_rereader": "Ink Reread",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Thrall",
        "m_artist_fan": "Artist Devotee",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Material",
        "m_waiting_weekly": "Weekly Ink Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyalty",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Favorite Mangaka",
        "m_complete_portfolio": "Complete Portfolio",
        "m_franchise_collector": "Franchise Ink",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Ink Master",
        "m_multi_series_author": "Multi-Series Author",
        "m_format_diversity": "Format Diversity",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Explorer",
        "m_decade_hopper": "Decade Hopper",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Taste",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross Demographic",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Variety Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Connoisseur",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Niche Explorer",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Manga",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre Month",
        "m_year_completionist": "Year Complete",
        "m_unpopular_opinion": "Unpopular Opinion",
        "m_top_rated_reader": "Top Rated",
        "m_source_variety": "Source Ink Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Manga",
        "m_long_manga_explorer": "Long Manga",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Ink Owl",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Midday Pages",
        "m_commute_reader": "Commute Reader",
        "m_four_am_club": "4 AM Ink",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All-Hours Ink",
        "m_prime_time_reader": "Prime Time Ink",
        "m_workday_reader": "Workday Reader",
        "m_sunday_read": "Sunday Ink",
        "m_morning_routine": "Morning Ink Ritual",
        "m_night_shift_reader": "Night Shift Ink",
        "m_seasonal_premier_read": "New Release Ink",
        "m_clock_collector": "Clock Ink",
        "m_late_night_horror": "Late Night Horror",
        "m_afternoon_reader": "Afternoon Ink",
        "m_golden_hour_reader": "Golden Hour Ink",
        "m_dawn_reader": "Dawn Ink Scout",
        "m_twilight_reader": "Twilight Ink",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Ink Binge",
        "m_late_night_regular": "Late Night Ink",
        "m_sunrise_reader": "Sunrise Ink",
        "m_every_day_of_week": "Every Day Ink",
        "m_monthly_hours": "Monthly Ink Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Reader",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel Reader",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Storyteller",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga to Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award Winning Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross Media",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collaboration Ink",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Ink Streak",
        "m_mega_streak": "Mega Ink Streak",
        "m_weekly_warrior": "Weekly Ink Warrior",
        "m_monthly_reader": "Monthly Ink Reader",
        "m_comeback": "Ink Comeback",
        "m_weekend_streak": "Weekend Ink Streak",
        "m_no_zero_days": "No Zero Ink Days",
        "m_iron_will": "Iron Ink Will",
        "m_habit_formed": "Ink Habit Formed",
        "m_consistent_pace": "Consistent Ink Pace",
        "m_year_long": "Year-Long Ink",
        "m_double_streak": "Double Ink Streak",
        "m_streak_recovery": "Ink Streak Recovery",
        "m_daily_minimum": "Daily Ink Minimum",
        "m_winter_streak": "Winter Ink Streak",
        "m_summer_streak": "Summer Ink Streak",
        "m_morning_streak": "Morning Ink Streak",
        "m_night_streak": "Night Ink Streak",
        "m_unbreakable": "Unbreakable Ink",
        "m_eternal_flame": "Eternal Ink Flame",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Ink Streak",
        "m_completion_streak": "Completion Ink Chain",
        "m_rating_streak": "Rating Ink Streak",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Ink Streak",
        "m_perfect_week_manga": "Perfect Ink Week",
        "m_diverse_streak": "Diverse Ink Streak",

        // ── MANGA SCORING ──
        "m_critic": "Ink Critic",
        "m_perfect_ten": "Perfect Ink Ten",
        "m_harsh_critic": "Harsh Ink Critic",
        "m_fair_judge": "Fair Ink Judge",
        "m_generous_spirit": "Generous Ink Spirit",
        "m_score_all": "Score All Ink",
        "m_wide_range": "Wide Ink Range",
        "m_controversial": "Controversial Ink",
        "m_consistent_scorer": "Consistent Ink Scorer",
        "m_score_sniper": "Ink Score Sniper",
        "m_evolving_taste": "Evolving Ink Taste",
        "m_bell_curve": "Ink Bell Curve",
        "m_picky_reader": "Picky Ink Reader",
        "m_100_rated": "Hundred Ink Rated",
        "m_500_rated": "Five Hundred Ink",
        "m_mediocre_majority": "Ink Middle Ground",
        "m_rating_spree": "Ink Rating Spree",
        "m_score_variance": "Ink Score Variance",
        "m_binge_rater": "Binge Ink Rater",
        "m_reread_rerate": "Reread Re-Rate",
        "m_masterpiece_hunter": "Ink Masterpiece",
        "m_contrarian": "Ink Contrarian",
        "m_optimist": "Ink Optimist",
        "m_score_distributor": "Ink Distributor",
        "m_genre_critic": "Genre Ink Critic",
        "m_mean_above_8": "Elite Ink Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Ink Vow",
        "m_valentines_read": "Valentine Ink",
        "m_pi_day": "Pi Day Chapters",
        "m_april_fools": "April Fools Ink",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Ink Solstice",
        "m_tanabata": "Tanabata Ink",
        "m_friday_13th": "Friday 13th Ink",
        "m_halloween_read": "Halloween Ink",
        "m_thanksgiving_binge": "Thanksgiving Ink",
        "m_christmas_read": "Midwinter Ink",
        "m_new_years_eve": "New Year Ink Eve",
        "m_birthday_read": "Birthday Ink",
        "m_holiday_marathon": "Holiday Ink Marathon",
        "m_independence_day": "Independence Ink",
        "m_culture_day": "Culture Ink Day",
        "m_spring_equinox": "Spring Ink Equinox",
        "m_earth_day": "Earth Ink Day",
        "m_labor_day": "Labor Ink Day",
        "m_winter_solstice": "Winter Ink Solstice",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "Every Holiday Ink",
        "m_consecutive_holidays": "Consecutive Ink Days",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Ink Number",
        "m_fibonacci": "Fibonacci Ink",
        "m_palindrome_day": "Palindrome Ink Day",
        "m_binary_day": "Binary Ink Day",
        "m_full_moon_read": "Full Moon Ink",
        "m_leap_year_read": "Leap Year Ink",
        "m_triple_seven": "Triple Seven Ink",
        "m_thousand_complete": "Thousand Ink Done",
        "m_nice": "Nice Ink Count",
        "m_power_level_chapters": "Power Ink Level",
        "m_answer_42": "Ink Answer 42",
        "m_square_number": "Square Ink Number",
        "m_prime_count": "Prime Ink Count",
        "m_matching_date": "Matching Ink Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Ink Chapters",
        "m_synchronicity": "Ink Synchronicity",
        "m_world_record": "Ink World Record",
        "m_genre_clash": "Genre Ink Clash",
        "m_time_traveler": "Ink Time Traveler",
        "m_double_digits": "Double Ink Digits",
        "m_one_two_three": "Ink One Two Three",
        "m_lucky_seven": "Lucky Ink Seven",
        "m_exact_hundred_ch": "Exact Hundred Ink",
        "m_year_match_count": "Year Ink Match",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Ink Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Ink Awakening",
        "m_meta_collector": "Ink Badge Collector",
        "m_meta_category_starter": "Category Ink Start",
        "m_meta_tier_climber": "Ink Tier Climber",
        "m_meta_tier_max": "Maximum Ink Tier",
        "m_meta_xp_earner": "Ink XP Harvester",
        "m_meta_difficulty_easy": "Easy Ink Horror",
        "m_meta_difficulty_hard": "Legendary Ink Terror",
        "m_meta_unlock_spree": "Ink Unlock Spree",
        "m_meta_completionist": "Ink Meta Complete",
        "m_meta_diverse": "Diverse Ink Portfolio",
        "m_meta_dominator": "Ink Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060306",
        primary: "#501e50",
        secondary: "#401440",
        accent: "#8b2060",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.3,
    backgroundBlur: 30,
    particleTypes: {
        spiral_tendrils: { label: "Spiral Tendrils", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        ink_splatter: { label: "Ink Splatter", maxCount: 12, defaultEnabled: true, defaultIntensity: 50 },
        shadow_crawl: { label: "Shadow Crawl", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        eye_blink: { label: "Eye Blink", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Reader",
        5:   "Disturbed",
        15:  "Obsessed",
        30:  "Spiral Touched",
        45:  "Body Horror",
        60:  "Tomie's Gaze",
        80:  "Amigara Fault",
        100: "Junji Ito Collection",
    },
}
