import { AnimeThemeConfig } from "./types"
import { GiMusicalNotes, GiGuitar, GiGrandPiano, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiHeartKey } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kidsOnTheSlopeTheme: AnimeThemeConfig = {
    id: "kids-on-the-slope",
    displayName: "Kids on the Slope",
    description: "Introverted classical pianist Kaoru moves to Kyushu in 1966 and befriends wild drummer Sentaro — through jazz, summer and hardship, an unlikely friendship and love story unfolds in postwar Japan.",
    fontFamily: "'Libre Baskerville', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap",
    cssVars: {
        "--color-brand-200": "220 192 160",
        "--color-brand-300": "195 162 122",
        "--color-brand-400": "168 130 82",
        "--color-brand-500": "140 98 44",
        "--color-brand-600": "110 72 18",
        "--color-brand-700": "80 50 8",
        "--color-brand-800": "54 32 3",
        "--color-brand-900": "30 16 1",
        "--color-brand-950": "16 8 0",
        "--brand": "140 98 44",
        "--background": "#050300",
        "--paper": "#0e0900",
        "--color-gray-950": "5 3 0",
        "--color-gray-900": "12 8 2",
        "--color-gray-800": "22 16 6",
        "--color-gray-700": "38 28 12",
        "--color-gray-600": "60 45 24",
        "--color-gray-500": "95 74 46",
        "--color-gray-400": "138 112 82",
        "--color-gray-300": "175 152 122",
        "--color-gray-200": "205 185 158",
        "--color-gray-100": "225 212 192",
        "--color-gray-50": "242 235 222",
    },
    sidebarOverrides: {
        "home": { icon: GiMusicalNotes, label: "Kyushu" },
        "schedule": { icon: GiAlarmClock, label: "Practice Schedule" },
        "manga": { icon: LuBookOpen, label: "Jazz Notes" },
        "lists": { icon: GiGuitar, label: "Jazz Playlist" },
        "discover": { icon: GiBullseye, label: "New Sessions" },
        "torrent-list": { icon: GiMusicalNotes, label: "Sheet Music" },
        "debrid": { icon: GiGrandPiano, label: "Jazz Store" },
        "unmatched": { icon: GiHeartKey, label: "Lost Notes" },
        "enmasse": { icon: GiResize, label: "Band Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Session Records" },
        "auto-downloader": { icon: LuRss, label: "Jazz Feed" },
        "community": { icon: GiMusicalNotes, label: "Jazz Circle" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Music Alerts" },
        "achievements": { icon: GiTrophy, label: "Jazz Trophies" },
        "milestones": { icon: LuFlag, label: "Jazz Goals" },
        "theme-manager": { icon: GiPalette, label: "Sepia Colors" },
        "extensions": { icon: BiExtension, label: "Music Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Jazz Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Tempo Settings" },
    },
    achievementNames: {
        "a_first_episode": "Jazz Found",
        "a_first_complete": "Final Session",
        "a_hundred_club": "Hundred Songs",
        "a_time_lord": "Jazz Veteran",
        "a_anime_collector": "Record Collection",
        "a_library_legend": "Jazz Archives",
        "a_binge_king": "Music Marathon",
        "a_no_sleep": "All-Night Jazz",
        "a_marathon_runner": "Long Session",
        "a_speed_run": "Sentaro's Beat",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Kodama Master",
        "a_loyal_fan": "Sentaro's Friend",
        "a_rewatcher": "Kyushu Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "None Here",
        "a_genre_adventure": "Kyushu Journey",
        "a_genre_comedy": "Sentaro's Antics",
        "a_genre_drama": "Friendship Story",
        "a_genre_fantasy": "Music World",
        "a_genre_horror": "Loss",
        "a_genre_romance": "Ritsuko's Heart",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Jazz Magic",
        "a_genre_psychological": "Kaoru's Growth",
        "a_genre_mecha": "None Here",
        "a_critic": "Music Judge",
        "a_perfect_ten": "Perfect Session",
        "a_harsh_critic": "Kaoru's Standard",
        "a_daily_streak": "Daily Practice",
        "a_mega_streak": "Endless Practice",
        "a_year_long": "Year of Jazz",
        "a_iron_will": "Kaoru's Passion",
        "a_hidden_gem": "Hidden Track",
        "a_cult_classic": "Kodama Classic",
        "a_classic_connoisseur": "2003 Fan",
        "a_new_years_resolution": "New Year Session",
        "a_christmas_special": "Winter Concert",
        "a_meta_tier_max": "Jazz Legend",
        "a_meta_completionist": "All Sessions",
        "a_sequel_chain": "Manga Continues",
        "a_zero_to_hero": "Loner to Jazz Lover",
        "a_night_owl": "Night Jazz",
        "a_early_bird": "Morning Practice",
        "m_first_chapter": "First Note",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Music Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Jazz Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Jazz Return",
        "m_genre_action": "None Here",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Music Chapter",
        "m_genre_horror": "Loss Chapter",
        "m_genre_drama": "Friendship Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_supernatural": "Jazz Chapter",
        "m_genre_psychological": "Growth Depth",
        "m_critic": "Jazz Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Jazz Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Musician Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Jazz Classic",
        "m_mangaka_lover": "Kodama Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Jazz Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "60s Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050300",
        primary: "#8c622c",
        secondary: "#6e4812",
        accent: "#6080c0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/kids-on-the-slope.jpg",
    particleColor: "#c09060",
    backgroundDim: 0.3,
    backgroundBlur: 14,
    particleTypes: {
        music_notes: { label: "Jazz Notes", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
        vinyl_dust: { label: "Vinyl Dust", maxCount: 10, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1: "Classical Student",
        5: "Kaoru Nishimi",
        15: "Jazz Initiate",
        30: "Basement Player",
        50: "Jazz Soul",
        75: "Sentaro's Partner",
        100: "Jazz Legend",
    },
}
