import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiSwordWound,
    GiChainedHeart,
    GiMuscleUp,
    GiCrossedSwords,
    GiHorseHead,
    GiFist,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const kingdomTheme: AnimeThemeConfig = {
    id: "kingdom",
    displayName: "Kingdom",
    description: "Forge your path to Great General. Warring States command interface with Qin army discipline, battlefield strategy, and the dream of unification under heaven.",
    fontFamily: "'Noto Serif SC', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;700&display=swap",
    cssVars: {
        // Brand → battle red
        "--color-brand-200": "220 140 140",
        "--color-brand-300": "210 100 100",
        "--color-brand-400": "200 65 65",
        "--color-brand-500": "180 40 40",
        "--color-brand-600": "150 30 30",
        "--color-brand-700": "120 22 22",
        "--color-brand-800": "90 15 15",
        "--color-brand-900": "60 10 10",
        "--color-brand-950": "35 5 5",
        "--brand": "180 40 40",
        // Dark scorched background
        "--background": "#080304",
        "--paper": "#100608",
        "--color-gray-950": "8 3 4",
        "--color-gray-900": "16 6 8",
        "--color-gray-800": "28 12 16",
        "--color-gray-700": "45 22 28",
        "--color-gray-600": "68 38 44",
        "--color-gray-500": "98 62 70",
        "--color-gray-400": "138 100 108",
        "--color-gray-300": "175 145 152",
        "--color-gray-200": "208 188 192",
        "--color-gray-100": "232 220 224",
        "--color-gray-50": "246 240 242",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Royal Court" },
        "schedule": { icon: GiAlarmClock, label: "War Council" },
        "manga": { icon: LuBookOpen, label: "Bamboo Scrolls" },
        "lists": { icon: GiCrossedSwords, label: "Army Roster" },
        "discover": { icon: GiBullseye, label: "Uncharted Lands" },
        "torrent-list": { icon: GiAnvilImpact, label: "Supply Lines" },
        "debrid": { icon: GiHorseHead, label: "Cavalry Charge" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Soldiers" },
        "enmasse": { icon: GiResize, label: "Mass Formation" },
        "scan-summaries": { icon: TbReportSearch, label: "Scout Reports" },
        "auto-downloader": { icon: LuRss, label: "Signal Fires" },
        "community": { icon: GiEagleEmblem, label: "Allied States" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "War Drums" },
        "achievements": { icon: GiTrophy, label: "Meritorious Deeds" },
        "theme-manager": { icon: GiPalette, label: "Banner Colors" },
        "extensions": { icon: BiExtension, label: "War Attachments" },
        "sync": { icon: IoCloudOfflineOutline, label: "Messenger Hawks" },
        "settings": { icon: GiSettingsKnobs, label: "Strategist's Tent" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Sortie",
        "a_episode_counter": "Battle Tally",
        "a_episode_titan": "Titan's March",
        "a_hours_invested": "Frontline Hours",
        "a_time_lord": "Eternal Strategist",
        "a_anime_collector": "Arsenal Amassed",
        "a_library_legend": "Scroll Keeper",
        "a_first_complete": "Campaign Won",
        "a_hundred_club": "Century Siege",
        "a_first_day": "Enlistment Day",
        "a_first_rating": "Field Appraisal",
        "a_ten_thousand_min": "Ten-Thousand Watch",
        "a_season_veteran": "Warring Veteran",
        "a_year_explorer": "Year-Long March",
        "a_century_watcher": "Hundred Battles",
        "a_five_hundred_eps": "Five Hundred Clashes",
        "a_thousand_eps": "Thousand Engagements",
        "a_watching_ten": "Ten-Front War",
        "a_ptw_hoarder": "Supply Hoarder",
        "a_dropped_honesty": "Tactical Retreat",
        "a_five_thousand_eps": "Five Thousand Raids",
        "a_ten_completed": "Ten Victories",
        "a_fifty_completed": "Fifty Conquests",
        "a_five_hundred_completed": "Five Hundred Triumphs",
        "a_mean_score_tracker": "Average Merit",
        "a_unique_studios": "Allied Kingdoms",
        "a_days_spent_watching": "Days at War",
        "a_all_status": "All Deployments",
        "a_first_favorite": "Sworn Oath",
        "a_favorites_collector": "Bonds Forged",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Relentless Advance",
        "a_marathon_runner": "Forced March",
        "a_weekend_warrior": "Weekend Warrior",
        "a_non_stop": "Unstoppable Charge",
        "a_one_more_episode": "One More Skirmish",
        "a_speed_run": "Lightning Raid",
        "a_double_feature": "Double Strike",
        "a_triple_threat": "Triple Assault",
        "a_five_a_day": "Five-Kill Day",
        "a_back_to_back": "Consecutive Duels",
        "a_seasonal_binge": "Full Campaign",
        "a_cour_crusher": "District Taken",
        "a_half_day_watch": "Half-Day Siege",
        "a_full_day_watch": "Full-Day Battle",
        "a_power_weekend": "Weekend Offensive",
        "a_binge_king": "Binge Commander",
        "a_no_sleep": "Night Siege",
        "a_entire_season": "Swift Conquest",
        "a_seven_day_challenge": "Seven-Day Campaign",
        "a_hundred_day_binge": "Hundred-Day War",
        "a_genre_binge": "Cross-State Raids",
        "a_studio_binge": "Allied Binge",
        "a_season_sweep": "Season Swept",
        "a_forty_eight_hour": "Forty-Eight Standoff",
        "a_ep_counter_day": "Daily Kill Count",
        "a_multi_series_binge": "Multi-Front War",
        "a_midnight_binge": "Midnight Raid",
        "a_new_year_binge": "New Year Charge",

        // ── ANIME GENRES ──
        "a_genre_action": "Vanguard Fighter",
        "a_genre_adventure": "Uncharted Plains",
        "a_genre_comedy": "Camp Jester",
        "a_genre_drama": "Oath of Kings",
        "a_genre_fantasy": "Heavenly Mandate",
        "a_genre_horror": "Battlefield Terror",
        "a_genre_mystery": "Hidden Stratagem",
        "a_genre_romance": "Wartime Bond",
        "a_genre_scifi": "Crossbow Innovation",
        "a_genre_sol": "Life in Qin",
        "a_genre_sports": "Training Grounds",
        "a_genre_supernatural": "Divine Mandate",
        "a_genre_thriller": "Ambush Pursuit",
        "a_genre_mecha": "Siege Engines",
        "a_genre_music": "War Drums Beat",
        "a_genre_psychological": "Mind of Strategist",
        "a_genre_ecchi": "Hot Spring Camp",
        "a_genre_mahou_shoujo": "Mystic Priestess",
        "a_tag_isekai": "Foreign Lands",
        "a_tag_harem": "Royal Retinue",
        "a_tag_bl": "Brothers in Arms",
        "a_tag_gl": "Shield Maidens",
        "a_tag_historical": "Warring States",
        "a_tag_military": "Military Discipline",
        "a_tag_school": "Strategist Academy",
        "a_tag_martial_arts": "Martial Prowess",
        "a_tag_vampire": "Blood Pact",
        "a_tag_samurai": "Blade of Qin",
        "a_tag_space": "Beyond the Plains",
        "a_tag_parody": "Camp Humor",
        "a_tag_idol": "Banner Bearer",
        "a_tag_post_apocalyptic": "Scorched Lands",
        "a_tag_cyberpunk": "Forged Arsenal",
        "a_tag_shounen": "Heart of Shin",
        "a_tag_seinen": "Harsh Realities",
        "a_tag_shoujo": "Maiden's Resolve",
        "a_tag_josei": "Court Intrigue",
        "a_tag_survival": "Survive the Plains",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full War Report",
        "a_mega_completionist": "Supreme Commander",
        "a_completion_rate_50": "Half Unified",
        "a_completion_rate_75": "Nearing Conquest",
        "a_completion_rate_90": "Unification Imminent",
        "a_no_drop": "No Deserters",
        "a_long_runner_complete": "Endurance March",
        "a_sequel_chain": "Chain of Command",
        "a_clean_list": "Clean Ledger",
        "a_from_ptw": "Orders Executed",
        "a_rewatch_master": "Retold Legends",
        "a_short_complete": "Quick Skirmish",
        "a_same_day_start_finish": "Same-Day Victory",
        "a_revival": "Risen from Ashes",
        "a_zero_to_hero": "Servant to General",
        "a_five_genre_complete": "Five-State Mastery",
        "a_full_franchise": "Full Dossier",
        "a_batch_complete": "Batch Cleared",
        "a_paused_to_done": "Back from Exile",
        "a_completion_spree": "Victory Spree",
        "a_multi_rewatch": "Multi-Retelling",
        "a_dropped_recovery": "Recovered Soldier",
        "a_ten_perfect_scores": "Ten Perfect Marks",
        "a_seasonal_clear": "Seasonal Offensive",
        "a_complete_genre_span": "All-Terrain Scout",
        "a_monthly_completions": "Monthly Conquest",
        "a_yearly_completions": "Yearly Campaign",
        "a_rapid_complete": "Rapid Conquest",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Retainer",
        "a_studio_devotee": "Devoted Vassal",
        "a_rewatcher": "Retold Campaign",
        "a_triple_rewatch": "Thrice Remembered",
        "a_annual_tradition": "Annual Rites",
        "a_director_fan": "Visionary Follower",
        "a_voice_actor_fan": "Voice of Command",
        "a_ost_lover": "War Hymn Lover",
        "a_source_reader": "Original Scrolls",
        "a_waiting_weekly": "Weekly Signal Wait",
        "a_childhood_revisit": "Return to Origin",
        "a_saga_tracker": "Saga of Qin",
        "a_genre_loyalty": "Loyalty Badge",
        "a_decade_watcher": "Decade Veteran",
        "a_adaptation_hunter": "Adaptation Scout",
        "a_original_anime_fan": "Original Broadcast",
        "a_long_commitment": "Long-Term Garrison",
        "a_perfect_attendance": "Perfect Formation",
        "a_favorite_studio_5": "Five Allied Houses",
        "a_complete_catalog": "Complete Archive",
        "a_franchise_collector": "Dynasty Collector",
        "a_airing_follower": "Current Intel",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Staff Dossier",
        "a_multi_season_fan": "Multi-Season Vet",
        "a_format_diversity": "Diverse Tactics",
        "a_year_dedication": "Year of Service",
        "a_season_dedication": "Season of Duty",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Unknown Territory",
        "a_studio_hopper": "State Transfer",
        "a_tag_explorer": "Recon Mission",
        "a_decade_hopper": "Era Traveler",
        "a_hidden_gem": "Hidden Stronghold",
        "a_popular_taste": "Popular Decree",
        "a_retro_appreciator": "Ancient Wisdom",
        "a_modern_viewer": "Modern Strategist",
        "a_cross_demographic": "Cross-Border Scout",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Tactics",
        "a_foreign_cinema": "Foreign Intelligence",
        "a_classic_connoisseur": "Classic Warfare",
        "a_every_season": "Every Season Served",
        "a_award_winner": "Medal of Valor",
        "a_niche_explorer": "Niche Territory",
        "a_global_anime": "Global Alliance",
        "a_cult_classic": "Underground Classic",
        "a_random_pick": "Random Deployment",
        "a_new_genre_month": "New Terrain Monthly",
        "a_seasonal_completionist": "Seasonal Clear",
        "a_unpopular_opinion": "Contrarian Strategy",
        "a_top_rated_viewer": "Top-Rated Intel",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Charge",
        "a_upcoming_watcher": "Upcoming Intel",
        "a_short_series_explorer": "Short Skirmish",
        "a_long_series_explorer": "Long Campaign",

        // ── ANIME TIME ──
        "a_night_owl": "Night Watch",
        "a_early_bird": "Dawn Patrol",
        "a_lunch_break": "Mess Hall Rest",
        "a_golden_hour": "Golden Hour",
        "a_four_am_club": "4 AM Sentry",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Oath",
        "a_midnight_premiere": "Midnight Sortie",
        "a_all_hours": "All-Hours Scout",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Drill",
        "a_prime_time": "Prime Engagement",
        "a_workday_watcher": "On-Duty Watch",
        "a_sunday_marathon": "Sunday March",
        "a_rainy_day": "Rainy Encampment",
        "a_morning_routine": "Morning Formation",
        "a_night_shift": "Night Garrison",
        "a_twilight_zone": "Twilight Plains",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Sundial Keeper",
        "a_weekend_binge_hours": "Weekend Siege",
        "a_late_night_regular": "Late Night Patrol",
        "a_sunrise_watcher": "Sunrise Over Qin",
        "a_holiday_watcher": "Holiday Guard",
        "a_every_day_of_week": "Every Day Deployed",
        "a_monthly_hours": "Monthly Duty",

        // ── ANIME SOCIAL ──
        "a_first_party": "First War Council",
        "a_party_host": "Council Commander",
        "a_social_butterfly": "Camp Socialite",
        "a_group_binge": "Group Assault",
        "a_party_regular": "Sparring Partner",
        "a_sync_viewer": "Synchronized March",
        "a_commentator": "Battle Narrator",
        "a_party_marathon": "Formation March",
        "a_full_house": "Full Unit Assembled",
        "a_community_pillar": "Pillar of State",
        "a_watch_party_streak": "Council Streak",
        "a_diverse_party": "Diverse Alliance",
        "a_late_night_party": "Late Night Camp",
        "a_party_veteran": "Veteran Leader",
        "a_genre_party": "Cross-Genre Council",
        "a_weekly_party": "Weekly Gathering",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "General's Order",
        "a_party_completionist": "Council Completionist",
        "a_social_scorer": "Social Merit",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Formation",
        "a_fibonacci": "Fibonacci Array",
        "a_palindrome_day": "Palindrome Omen",
        "a_binary_day": "Binary Signal",
        "a_full_moon": "Full Moon Omen",
        "a_leap_year": "Leap Year March",
        "a_time_traveler": "Era Traveler",
        "a_genre_clash": "State vs State",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Victories",
        "a_pi_episodes": "Pi Calculation",
        "a_synchronicity": "Fated Convergence",
        "a_world_record": "World Record",
        "a_nice": "Auspicious Tally",
        "a_power_level": "General's Power",
        "a_answer_42": "Sage's Answer",
        "a_square_number": "Perfect Square",
        "a_prime_count": "Prime Headcount",
        "a_matching_date": "Matching Omens",
        "a_century_episode": "Century Assault",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "Three Great Heavens",
        "a_lucky_seven": "Seven Generals",
        "a_all_tens": "All Tens Merit",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match Tally",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "Broadcast Scout",
        "a_movie_buff": "War Film Buff",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Operative",
        "a_short_king": "Short Raid King",
        "a_variety_pack": "All-Format Army",
        "a_film_festival": "War Film Fest",
        "a_music_video": "War Anthem Video",
        "a_tv_short": "Quick Recon",
        "a_movie_marathon": "Film Blitz",
        "a_double_length": "Double-Length Siege",
        "a_anthology": "War Anthology",
        "a_mini_series": "Mini Campaign",
        "a_theatrical": "Theatrical Decree",
        "a_format_master": "Format Conqueror",
        "a_long_movie": "Feature Expedition",
        "a_back_catalog": "Archive Garrison",
        "a_cm_watcher": "Signal Watcher",
        "a_pv_collector": "Preview Collector",
        "a_format_balance": "Balanced Formats",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Operation",
        "a_recap_watcher": "Briefing Recap",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Patrol",
        "a_mega_streak": "Mega Campaign",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Garrison",
        "a_comeback": "Return from Exile",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Discipline Forged",
        "a_consistent_pace": "Steady Advance",
        "a_year_long": "Year-Long War",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Recovered Morale",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Campaign",
        "a_summer_streak": "Summer Offensive",
        "a_morning_streak": "Morning Drill",
        "a_night_streak": "Night Patrol",
        "a_unbreakable": "Unbreakable Will",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Episode Push",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Loyalty",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "War Tribunal",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Harsh Overlord",
        "a_fair_judge": "Fair Magistrate",
        "a_generous_spirit": "Generous Lord",
        "a_score_all": "Full Evaluation",
        "a_wide_range": "Wide Assessment",
        "a_controversial": "Controversial Edict",
        "a_consistent_scorer": "Steady Evaluator",
        "a_score_sniper": "Precision Strike",
        "a_evolving_taste": "Evolving Strategy",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Selective General",
        "a_100_rated": "Century Rated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Found",
        "a_contrarian": "Contrarian View",
        "a_optimist": "Optimistic Lord",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Vow",
        "a_valentines_weeb": "Valentine's Oath",
        "a_pi_day": "Pi Day Omen",
        "a_april_fools": "Fool's Decree",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "Empire Day",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Cursed Thirteenth",
        "a_halloween_spirit": "Phantom Army",
        "a_thanksgiving_binge": "Harvest Feast",
        "a_christmas_special": "Midwinter Festival",
        "a_new_years_eve": "Year's Final Stand",
        "a_birthday_watch": "Birthday Rites",
        "a_holiday_marathon": "Holiday Campaign",
        "a_independence_day": "Liberation Day",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Advance",
        "a_earth_day": "Land Preservation",
        "a_labor_day": "Laborer's Rest",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anniversary Rites",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Consecutive Feasts",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Awakening",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Initiation Rite",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Great General Rank",
        "a_meta_xp_earner": "Merit Earned",
        "a_meta_difficulty_easy": "Easy Skirmish",
        "a_meta_difficulty_hard": "Legendary Siege",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Completionist",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Scroll",
        "m_chapter_counter": "Chapter Tally",
        "m_chapter_titan": "Titan's Chapter",
        "m_reading_hours": "Study Hours",
        "m_reading_time_lord": "Eternal Scholar",
        "m_manga_collector": "Scroll Collector",
        "m_library_legend": "Archive Legend",
        "m_first_complete": "First Text Done",
        "m_hundred_club": "Hundred Scrolls",
        "m_first_day": "First Reading Day",
        "m_first_rating": "First Appraisal",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Stockpile",
        "m_year_explorer": "Year of Study",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Read",
        "m_thousand_ch": "Thousand Chapters",
        "m_reading_ten": "Ten At Once",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Withdrawal",
        "m_season_reader": "Seasonal Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Texts Done",
        "m_fifty_completed": "Fifty Completed",
        "m_five_hundred_completed": "Five Hundred Wins",
        "m_mean_score_tracker": "Average Appraisal",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "Sworn Favorite",
        "m_favorites_collector": "Favorites Arsenal",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading",
        "m_marathon_reader": "Reading Marathon",
        "m_weekend_reader": "Weekend Scrolls",
        "m_non_stop_reading": "Non-Stop Pages",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Reading",
        "m_double_story": "Double Manuscript",
        "m_triple_read": "Triple Reading",
        "m_five_a_day": "Five Daily Reads",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Archive",
        "m_full_day_read": "Full-Day Study",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge Warlord",
        "m_no_sleep_read": "All-Night Study",
        "m_full_series_rush": "Series Rush",
        "m_seven_day_challenge": "Seven-Day Intel",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Swept",
        "m_genre_binge": "Cross-Genre Read",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Count",
        "m_multi_series_binge": "Multi-Series Front",
        "m_midnight_binge": "Midnight Archive",
        "m_new_year_binge": "New Year Reading",
        "m_forty_eight_hour": "Forty-Eight Hours",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Scrolls",
        "m_genre_adventure": "Adventure Scrolls",
        "m_genre_comedy": "Comedy Scrolls",
        "m_genre_drama": "Drama of Kings",
        "m_genre_fantasy": "Fantasy Scrolls",
        "m_genre_horror": "Horror Scrolls",
        "m_genre_mystery": "Mystery Scrolls",
        "m_genre_romance": "Romance Scrolls",
        "m_genre_scifi": "Sci-Fi Scrolls",
        "m_genre_sol": "Daily Life Scrolls",
        "m_genre_sports": "Sports Scrolls",
        "m_genre_supernatural": "Supernatural Texts",
        "m_genre_thriller": "Thriller Intel",
        "m_genre_psychological": "Psych Warfare",
        "m_genre_isekai": "Isekai Scrolls",
        "m_genre_shounen": "Shounen Heart",
        "m_genre_ecchi": "Camp Humor Read",
        "m_genre_mahou_shoujo": "Mystic Texts",
        "m_genre_mecha": "Siege Blueprints",
        "m_genre_music": "War Song Texts",
        "m_tag_isekai_new": "New World Scrolls",
        "m_tag_harem": "Retinue Scrolls",
        "m_tag_bl": "Brothers Manga",
        "m_tag_gl": "Shield Maiden Manga",
        "m_tag_historical": "Historical Annals",
        "m_tag_military": "Military Texts",
        "m_tag_school": "Academy Manga",
        "m_tag_martial_arts": "Martial Arts Manual",
        "m_tag_vampire": "Blood Pact Manga",
        "m_tag_samurai": "Swordsman Manga",
        "m_tag_space": "Distant Lands Manga",
        "m_tag_parody": "Parody Scrolls",
        "m_tag_idol": "Banner Manga",
        "m_tag_post_apocalyptic": "Scorched Earth Manga",
        "m_tag_cyberpunk": "Forged Tech Manga",
        "m_tag_shoujo": "Maiden's Manga",
        "m_tag_survival": "Survival Manga",
        "m_tag_cooking": "Field Rations Book",
        "m_tag_medical": "Field Medic Manual",
        "m_tag_villainess": "Court Schemer Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Scroll Completionist",
        "m_mega_completionist": "Supreme Scholar",
        "m_completion_rate_50": "Half Conquered",
        "m_completion_rate_75": "Nearing Triumph",
        "m_completion_rate_90": "Almost Unified",
        "m_no_drop": "No Scroll Dropped",
        "m_long_runner_complete": "Long Text Endured",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean Record",
        "m_from_ptr": "Orders Read",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Read",
        "m_revival": "Revived Text",
        "m_zero_to_hundred": "Novice to Scholar",
        "m_five_genre_complete": "Five-Genre Mastery",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Cleared",
        "m_paused_to_done": "Back from Hiatus",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Badge",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi-Reread",
        "m_dropped_recovery": "Recovered Text",
        "m_ten_perfect_scores": "Ten Perfect Reads",
        "m_complete_genre_span": "All-Genre Reader",
        "m_monthly_completions": "Monthly Victories",
        "m_yearly_completions": "Yearly Campaign",
        "m_rapid_complete": "Rapid Processing",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Scholar",
        "m_mangaka_lover": "Mangaka Devotee",
        "m_rereader": "Devoted Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Tradition",
        "m_publisher_fan": "Publisher Vassal",
        "m_artist_fan": "Artist Tribute",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Material Fan",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyalty",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "Light Novel Intel",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Honored Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Dynasty Archive",
        "m_serialization_follower": "Serial Tracker",
        "m_genre_master": "Genre Mastered",
        "m_multi_series_author": "Multi-Series Author",
        "m_format_diversity": "Diverse Formats",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Loyal Reads",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Scout",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Recon",
        "m_decade_hopper": "Decade Hopper",
        "m_hidden_gem": "Hidden Stronghold",
        "m_popular_taste": "Popular Taste",
        "m_retro_reader": "Retro Appreciator",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross-Border Reader",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Varied Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Connoisseur",
        "m_award_winner": "Award-Winning Read",
        "m_niche_explorer": "Niche Explorer",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic",
        "m_random_pick": "Random Assignment",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Completionist",
        "m_unpopular_opinion": "Unpopular Opinion",
        "m_top_rated_reader": "Top-Rated Reader",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Manga Scout",
        "m_long_manga_explorer": "Long Manga Scout",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Midday Reader",
        "m_commute_reader": "Travel Reader",
        "m_four_am_club": "4 AM Scholar",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All-Hours Access",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Study",
        "m_morning_routine": "Morning Routine",
        "m_night_shift_reader": "Night Shift Reader",
        "m_seasonal_premier_read": "New Release Intel",
        "m_clock_collector": "Sundial Reader",
        "m_late_night_horror": "Midnight Horror",
        "m_afternoon_reader": "Afternoon Reader",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Study",
        "m_twilight_reader": "Twilight Reader",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Read Ops",
        "m_late_night_regular": "Late Night Regular",
        "m_sunrise_reader": "Sunrise Reader",
        "m_every_day_of_week": "Every Day Read",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color Scroll",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Reader",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel Reader",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Narrator",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award-Winning Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross-Media Intel",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Joint Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read Streak",
        "m_mega_streak": "Mega Read Streak",
        "m_weekly_warrior": "Weekly Reader",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader's Return",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Read Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Habit Formed",
        "m_consistent_pace": "Consistent Pace",
        "m_year_long": "Year-Long Reading",
        "m_double_streak": "Double Read Streak",
        "m_streak_recovery": "Streak Recovery",
        "m_daily_minimum": "Daily Minimum",
        "m_winter_streak": "Winter Reading",
        "m_summer_streak": "Summer Reading",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Read Streak",
        "m_unbreakable": "Unbreakable Reader",
        "m_eternal_flame": "Flame of Knowledge",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Completion Streak",
        "m_rating_streak": "Rating Streak",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Read Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manuscript Critic",
        "m_perfect_ten": "Perfect Ten Read",
        "m_harsh_critic": "Harsh Magistrate",
        "m_fair_judge": "Fair Appraiser",
        "m_generous_spirit": "Generous Spirit",
        "m_score_all": "Full Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Take",
        "m_consistent_scorer": "Consistent Scorer",
        "m_score_sniper": "Precision Score",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve Scores",
        "m_picky_reader": "Selective Reader",
        "m_100_rated": "Century Rated",
        "m_500_rated": "Five Hundred Rated",
        "m_mediocre_majority": "Middle Ground",
        "m_rating_spree": "Rating Spree",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Re-Rate",
        "m_masterpiece_hunter": "Masterpiece Found",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimist Reader",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Resolve",
        "m_valentines_read": "Valentine's Read",
        "m_pi_day": "Pi Day Chapter",
        "m_april_fools": "Fool's Scroll",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Scroll Day",
        "m_summer_solstice": "Summer Reading",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Cursed Reading",
        "m_halloween_read": "Halloween Horror",
        "m_thanksgiving_binge": "Harvest Binge",
        "m_christmas_read": "Midwinter Read",
        "m_new_years_eve": "Year's Final Read",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Marathon",
        "m_independence_day": "Liberation Read",
        "m_culture_day": "Culture Read",
        "m_spring_equinox": "Spring Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Winter Reading",
        "m_manga_birthday": "Manga Anniversary",
        "m_every_holiday_reader": "Every Holiday Read",
        "m_consecutive_holidays": "Consecutive Holidays",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Milestone",
        "m_fibonacci": "Fibonacci Chapter",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven Read",
        "m_thousand_complete": "Thousand Complete",
        "m_nice": "Auspicious Count",
        "m_power_level_chapters": "General's Chapters",
        "m_answer_42": "Sage's Reading",
        "m_square_number": "Square Formation",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Date Matched",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Fated Reading",
        "m_world_record": "World Record Read",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time-Traveling Read",
        "m_double_digits": "Double Digit Read",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Match Count",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Specialist",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Scroll Opened",
        "m_meta_collector": "Reading Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Reading Rank Up",
        "m_meta_tier_max": "Maximum Rank",
        "m_meta_xp_earner": "Reading Merit",
        "m_meta_difficulty_easy": "Easy Reading",
        "m_meta_difficulty_hard": "Legendary Text",
        "m_meta_unlock_spree": "Unlock Barrage",
        "m_meta_completionist": "Meta Completionist",
        "m_meta_diverse": "Diverse Reader",
        "m_meta_dominator": "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#080304",
        primary: "#b42828",
        secondary: "#961e1e",
        accent: "#d4a050",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/kingdom.jpg",
    particleColor: "#906040",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        war_banners: { label: "War Banners", maxCount: 8, defaultEnabled: true, defaultIntensity: 55 },
        arrow_rain: { label: "Arrow Rain", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        dust_clouds: { label: "Dust Clouds", maxCount: 10, defaultEnabled: true, defaultIntensity: 45 },
        flame_siege: { label: "Flame Siege", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Servant",
        5:   "Foot Soldier",
        15:  "Hundred-Man",
        30:  "Thousand-Man",
        45:  "General",
        60:  "Great General",
        80:  "Unifier",
        100: "King of Qin",
    },
}
