import { AnimeThemeConfig } from "./types"
import {
    GiGooExplosion, GiMagicAxe, GiSpellBook, GiScrollUnfurled,
    GiFlame, GiWaterDrop, GiSwordClash, GiCrown,
    GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss } from "react-icons/lu"
import { BiExtension } from "react-icons/bi"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { TbReportSearch } from "react-icons/tb"

export const konosubaTheme: AnimeThemeConfig = {
    id: "konosuba",
    displayName: "KonoSuba",
    description: "Useless but loveable party. Comedy isekai in red & gold.",
    fontFamily: "'Fredoka One', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    cssVars: {
        "--color-brand-200": "255 200 140",
        "--color-brand-300": "255 165 70",
        "--color-brand-400": "240 120 15",
        "--color-brand-500": "205 85 0",
        "--color-brand-600": "162 60 0",
        "--color-brand-700": "120 40 0",
        "--color-brand-800": "80 25 0",
        "--color-brand-900": "48 14 0",
        "--color-brand-950": "24 6 0",
        "--brand": "215 90 5",
        "--background": "#0d0500",
        "--paper": "#180900",
        "--color-gray-950": "10 4 0",
        "--color-gray-900": "20 9 0",
        "--color-gray-800": "36 18 4",
        "--color-gray-700": "55 28 8",
        "--color-gray-600": "80 45 15",
        "--color-gray-500": "115 70 30",
        "--color-gray-400": "165 112 65",
        "--color-gray-300": "205 155 100",
        "--color-gray-200": "235 195 148",
        "--color-gray-100": "248 228 198",
        "--color-gray-50":  "254 248 235",
    },
    sidebarOverrides: {
        "home":           { icon: GiGooExplosion,     label: "Axel Town" },
        "schedule":       { icon: GiAlarmClock,    label: "Quest Board" },
        "manga":          { icon: GiScrollUnfurled,label: "Kazuma's Records" },
        "lists":          { icon: GiSpellBook,     label: "Guild Registry" },
        "discover":       { icon: GiMagicAxe,      label: "Dungeon Hunt" },
        "torrent-list":   { icon: GiFlame,         label: "Megumin Ops" },
        "unmatched":      { icon: GiWaterDrop,     label: "Aqua's Mistakes" },
        "scan-summaries": { icon: TbReportSearch,  label: "Guild Reports" },
        "auto-downloader":{ icon: LuRss,           label: "Quest Feed" },
        "search":         { icon: FiSearch,        label: "Search" },
        "notifications":  { icon: LuBell,          label: "Party Alerts" },
        "achievements":   { icon: GiCrown,         label: "Adventurer Rank" },
        "theme-manager":  { icon: GiPalette,       label: "Party Colors" },
        "extensions":     { icon: BiExtension,     label: "Contracts" },
        "settings":       { icon: GiSettingsKnobs, label: "Kazuma's Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "NEET Isekai'd Again",
        "a_episode_counter": "Daily Explosion Log",
        "a_episode_titan": "Unlimited EXPLOSION Works",
        "a_hours_invested": "Hours Adventuring in Axel",
        "a_time_lord": "Kazuma's Borrowed Time",
        "a_anime_collector": "Guild Card Collection",
        "a_library_legend": "Kazuma's Full Archive",
        "a_first_complete": "Quest Complete!",
        "a_hundred_club": "Axel Veteran Adventurer",
        "a_first_day": "First Day at the Guild",
        "a_first_rating": "Cadet Guild Rating",
        "a_ten_thousand_min": "Ten Thousand Guild Minutes",
        "a_season_veteran": "Seasonal Quest Veteran",
        "a_year_explorer": "Year in Axel Town",
        "a_century_watcher": "Hundred-Episode EXPLOSION",
        "a_five_hundred_eps": "Five Hundred Quests Logged",
        "a_thousand_eps": "Thousand Episode Campaign",
        "a_watching_ten": "Ten Simultaneous Quests",
        "a_ptw_hoarder": "Kazuma's Quest Backlog",
        "a_dropped_honesty": "Strategic Party Retreat",
        "a_five_thousand_eps": "Five Thousand Sorties",
        "a_ten_completed": "Ten Quests Complete",
        "a_fifty_completed": "Fifty Guild Missions Done",
        "a_five_hundred_completed": "Five Hundred Victories",
        "a_mean_score_tracker": "Average Guild Rating",
        "a_unique_studios": "Allied Guild Parties",
        "a_days_spent_watching": "Days in Axel Town",
        "a_all_status": "All Party Statuses",
        "a_first_favorite": "First Party Member Bond",
        "a_favorites_collector": "Party Favorites Assembled",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Megumin's Explosion Binge",
        "a_marathon_runner": "Axel-to-Capital Marathon",
        "a_weekend_warrior": "Weekend Dungeon Dive",
        "a_non_stop": "Relentless EXPLOSION Streak",
        "a_one_more_episode": "One More Quest Kazuma",
        "a_speed_run": "Steal Skill Speed Run",
        "a_double_feature": "Double EXPLOSION Barrage",
        "a_triple_threat": "Triple Threat Archwizard",
        "a_five_a_day": "Five Quests a Day",
        "a_back_to_back": "Back-to-Back Dungeon Runs",
        "a_seasonal_binge": "Full Season Arc Rush",
        "a_cour_crusher": "Dungeon Crusher",
        "a_half_day_watch": "Half-Day at the Guild",
        "a_full_day_watch": "Full Day Party Adventure",
        "a_power_weekend": "Power Weekend Party Raid",
        "a_binge_king": "Kazuma's Binge Commander",
        "a_no_sleep": "All-Night Guild Tavern",
        "a_entire_season": "Full Season Quest Clear",
        "a_seven_day_challenge": "Seven-Day Guild Challenge",
        "a_hundred_day_binge": "Hundred-Day Quest Siege",
        "a_genre_binge": "Cross-Genre Party Binge",
        "a_studio_binge": "Allied Studio Binge",
        "a_season_sweep": "Season Sweep EXPLOSION",
        "a_forty_eight_hour": "Forty-Eight Hour Party",
        "a_ep_counter_day": "Daily Episode Kill Count",
        "a_multi_series_binge": "Multi-Front Guild Campaign",
        "a_midnight_binge": "Midnight Tavern Binge",
        "a_new_year_binge": "New Year's EXPLOSION Charge",

        // ── ANIME GENRES ──
        "a_genre_action": "Combat in the Dungeon",
        "a_genre_adventure": "Beyond Axel Town",
        "a_genre_comedy": "Kazuma's Comedy Hour",
        "a_genre_drama": "Darkness's Inner Torment",
        "a_genre_fantasy": "Isekai Fantasy Master",
        "a_genre_horror": "Undead Wiz's Terror",
        "a_genre_mystery": "Vanir's Dark Secrets",
        "a_genre_romance": "Aqua Rejects Kazuma",
        "a_genre_scifi": "Devil's Magical Technology",
        "a_genre_sol": "Slice of Axel Life",
        "a_genre_sports": "Guild Training Grounds",
        "a_genre_supernatural": "Aqua's Divine Powers",
        "a_genre_thriller": "Demon King Approaches",
        "a_genre_mecha": "Magical Artillery Unit",
        "a_genre_music": "Aqua's Off-Key Hymn",
        "a_genre_psychological": "Kazuma's Inner Nihilism",
        "a_genre_ecchi": "Hot Spring Aqua Incident",
        "a_genre_mahou_shoujo": "Megumin Archmage Mode",
        "a_tag_isekai": "Isekai'd via Truck-kun",
        "a_tag_harem": "Useless Party Harem",
        "a_tag_bl": "Guild Bros Bonding",
        "a_tag_gl": "Wiz and Aqua Alliance",
        "a_tag_historical": "Demon King's History",
        "a_tag_military": "Axis Crusader Corps",
        "a_tag_school": "Adventurer Academy Logs",
        "a_tag_martial_arts": "Kazuma's Steal Technique",
        "a_tag_vampire": "Undead Shopkeeper Files",
        "a_tag_samurai": "Sword Master Darkness",
        "a_tag_space": "Beyond the Kingdom",
        "a_tag_parody": "Aqua Fails Again",
        "a_tag_idol": "Aqua's Divine Idol Show",
        "a_tag_post_apocalyptic": "After Demon King Falls",
        "a_tag_cyberpunk": "Devil Machine Parts",
        "a_tag_shounen": "Kazuma Dedicates Heart",
        "a_tag_seinen": "Harsh Reality of NEETs",
        "a_tag_shoujo": "Megumin's Devotion",
        "a_tag_josei": "Darkness's Obsession",
        "a_tag_survival": "Surviving the Demon Army",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Guild Quest Report",
        "a_mega_completionist": "Guild Master Rank",
        "a_completion_rate_50": "Halfway to Demon King",
        "a_completion_rate_75": "Approaching the Castle",
        "a_completion_rate_90": "Demon King Nearly Defeated",
        "a_no_drop": "No Quest Abandoned",
        "a_long_runner_complete": "Long Campaign Endurance",
        "a_sequel_chain": "Sequel Quest Chain",
        "a_clean_list": "Clean Guild Record",
        "a_from_ptw": "PTW Quest Executed",
        "a_rewatch_master": "Comedy Replay Master",
        "a_short_complete": "Quick Dungeon Victory",
        "a_same_day_start_finish": "Same-Day Quest Clear",
        "a_revival": "Revived by Aqua",
        "a_zero_to_hero": "NEET to Adventurer",
        "a_five_genre_complete": "Five-Genre Guild Mastery",
        "a_full_franchise": "Full KonoSuba Dossier",
        "a_batch_complete": "Batch Quest Clearance",
        "a_paused_to_done": "Returned from Death",
        "a_completion_spree": "Completion EXPLOSION Spree",
        "a_multi_rewatch": "Multi-Rewatch Kazuma",
        "a_dropped_recovery": "Recovered from Defeat",
        "a_ten_perfect_scores": "Ten Perfect Quest Scores",
        "a_seasonal_clear": "Seasonal EXPLOSION Clear",
        "a_complete_genre_span": "All-Terrain Guild Scout",
        "a_monthly_completions": "Monthly Mission Reports",
        "a_yearly_completions": "Yearly Campaign Victor",
        "a_rapid_complete": "Lightning Quest Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Party Alliance",
        "a_studio_devotee": "KonoSuba Studio Devotee",
        "a_rewatcher": "Comedy Rewatch Scout",
        "a_triple_rewatch": "Triple EXPLOSION Rewatch",
        "a_annual_tradition": "Annual Axel Revisit",
        "a_director_fan": "Director's Vision Fan",
        "a_voice_actor_fan": "Voice of the Party",
        "a_ost_lover": "KonoSuba OST Fanatic",
        "a_source_reader": "LN Reader Kazuma",
        "a_waiting_weekly": "Weekly Episode Wait",
        "a_childhood_revisit": "Return to Axel Town",
        "a_saga_tracker": "KonoSuba Saga Tracker",
        "a_genre_loyalty": "Isekai Comedy Loyalty",
        "a_decade_watcher": "Decade-Long Party Member",
        "a_adaptation_hunter": "Adaptation Scout",
        "a_original_anime_fan": "Original Broadcast Fan",
        "a_long_commitment": "Long-Term Party Duty",
        "a_perfect_attendance": "Perfect Guild Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Guild Catalog",
        "a_franchise_collector": "KonoSuba Universe Fan",
        "a_airing_follower": "Airing Episode Intel",
        "a_genre_master": "Genre Mastery Achieved",
        "a_staff_follower": "Staff Roster Tracker",
        "a_multi_season_fan": "Multi-Season Veteran",
        "a_format_diversity": "Diverse Tactical Formats",
        "a_year_dedication": "Year of Party Dedication",
        "a_season_dedication": "Season of Guild Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Axel",
        "a_studio_hopper": "Guild Party Transfer",
        "a_tag_explorer": "Tag Recon Mission",
        "a_decade_hopper": "Decade-Hopping Kazuma",
        "a_hidden_gem": "Hidden Dungeon Gem",
        "a_popular_taste": "Popular at the Guild",
        "a_retro_appreciator": "Pre-Isekai Appreciator",
        "a_modern_viewer": "Modern Adventurer Viewer",
        "a_cross_demographic": "Cross-Party Scout",
        "a_underdog_fan": "Underdog Kazuma Spirit",
        "a_variety_week": "Week of Varied Quests",
        "a_foreign_cinema": "Foreign Guild Cinema",
        "a_classic_connoisseur": "Classic Quest Connoisseur",
        "a_every_season": "Every Season Adventured",
        "a_award_winner": "Guild Medal of Honor",
        "a_niche_explorer": "Niche Dungeon Explorer",
        "a_global_anime": "Global Guild Alliance",
        "a_cult_classic": "Axel Cult Classic",
        "a_random_pick": "Random Quest Assignment",
        "a_new_genre_month": "New Terrain Monthly",
        "a_seasonal_completionist": "Seasonal Quest Clear",
        "a_unpopular_opinion": "Unpopular Party Opinion",
        "a_top_rated_viewer": "Top-Rated Guild Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Low-Score Charge",
        "a_upcoming_watcher": "Upcoming Quest Intel",
        "a_short_series_explorer": "Short Quest Explorer",
        "a_long_series_explorer": "Long Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Late Night Tavern Watch",
        "a_early_bird": "Dawn Patrol Kazuma",
        "a_lunch_break": "Guild Mess Hall Break",
        "a_golden_hour": "Golden Hour EXPLOSION",
        "a_four_am_club": "4 AM Dungeon Sentry",
        "a_witching_hour": "Undead Witching Hour",
        "a_new_year_watch": "New Year's Isekai Oath",
        "a_midnight_premiere": "Midnight Quest Deployment",
        "a_all_hours": "All-Hours Party Member",
        "a_dawn_warrior": "Dawn Warrior Kazuma",
        "a_afternoon_delight": "Afternoon Guild Drill",
        "a_prime_time": "Prime Time Engagement",
        "a_workday_watcher": "On-Duty Guild Watcher",
        "a_sunday_marathon": "Sunday Quest Marathon",
        "a_rainy_day": "Rainy Day in Axel",
        "a_morning_routine": "Morning Guild Formation",
        "a_night_shift": "Night Shift at Guild",
        "a_twilight_zone": "Twilight Beyond the Gate",
        "a_seasonal_premier": "Season Premiere Sortie",
        "a_clock_collector": "Clock Tower Collector",
        "a_weekend_binge_hours": "Weekend Binge Operations",
        "a_late_night_regular": "Late Night Tavern Regular",
        "a_sunrise_watcher": "Sunrise Over Axel",
        "a_holiday_watcher": "Holiday Guild Duty",
        "a_every_day_of_week": "Every Day Adventuring",
        "a_monthly_hours": "Monthly Duty Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Guild Party Formation",
        "a_party_host": "Party Quest Commander",
        "a_social_butterfly": "Guild Tavern Socialite",
        "a_group_binge": "Group EXPLOSION Volley",
        "a_party_regular": "Regular Sparring Partner",
        "a_sync_viewer": "Synchronized Party Maneuver",
        "a_commentator": "Quest Battle Commentator",
        "a_party_marathon": "Marathon Party Run",
        "a_full_house": "Full Guild Assembled",
        "a_community_pillar": "Pillar of the Guild",
        "a_watch_party_streak": "Consecutive Party Streak",
        "a_diverse_party": "Diverse Party Members",
        "a_late_night_party": "Late Night Tavern Party",
        "a_party_veteran": "Veteran Party Leader",
        "a_genre_party": "Cross-Genre Party",
        "a_weekly_party": "Weekly Guild Gathering",
        "a_silent_viewer": "Silent Kazuma Observer",
        "a_recommendation_giver": "Guild Recommendation",
        "a_party_completionist": "Party Quest Completionist",
        "a_social_scorer": "Social Guild Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Formation",
        "a_fibonacci": "Fibonacci EXPLOSION Sequence",
        "a_palindrome_day": "Palindrome Day EXPLOSION",
        "a_binary_day": "Binary Signal Flare Day",
        "a_full_moon": "Full Moon Undead Night",
        "a_leap_year": "Leap Year Isekai Skip",
        "a_time_traveler": "Kazuma's Future Memory",
        "a_genre_clash": "Party vs Demon Clash",
        "a_triple_seven": "Triple Seven Lucky Stats",
        "a_thousand_complete": "Thousand Quest Victories",
        "a_pi_episodes": "Pi Episode Calculation",
        "a_synchronicity": "Party Synchronicity",
        "a_world_record": "World Record EXPLOSION",
        "a_nice": "Nice Guild Count",
        "a_power_level": "Kazuma Luck Stat",
        "a_answer_42": "Answer to Axel's Question",
        "a_square_number": "Perfect Party Formation",
        "a_prime_count": "Prime Number of Quests",
        "a_matching_date": "Matching Guild Date",
        "a_century_episode": "Century Episode EXPLOSION",
        "a_double_digits": "Double Digit Quests",
        "a_one_two_three": "Kazuma Aqua Megumin",
        "a_lucky_seven": "Luck Stat Maxed",
        "a_all_tens": "All Tens Combat Score",
        "a_exact_hundred_eps": "Exact Hundred Episodes",
        "a_year_match_count": "Year Match Quest Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Adventurer",
        "a_movie_buff": "KonoSuba Movie Operations",
        "a_ova_hunter": "OVA Hot Spring Hunter",
        "a_ona_explorer": "ONA Quest Explorer",
        "a_special_watcher": "Special Episode Operative",
        "a_short_king": "Short Quest King",
        "a_variety_pack": "All-Format Party",
        "a_film_festival": "KonoSuba Film Festival",
        "a_music_video": "Aqua Hymn Collection",
        "a_tv_short": "Quick Recon Clip",
        "a_movie_marathon": "Movie Marathon Blitz",
        "a_double_length": "Double-Length Quest",
        "a_anthology": "KonoSuba Anthology",
        "a_mini_series": "Mini Campaign Collection",
        "a_theatrical": "Theatrical EXPLOSION",
        "a_format_master": "Format Master Adventurer",
        "a_long_movie": "Feature-Length Adventure",
        "a_back_catalog": "Back Catalog Guild Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Tactical Formats",
        "a_episodic_master": "Episodic Quest Master",
        "a_sequel_movie": "Sequel Quest Film",
        "a_recap_watcher": "Guild Briefing Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Party Outing",
        "a_mega_streak": "Kazuma's Perseverance",
        "a_weekly_warrior": "Weekly Warrior of Axel",
        "a_monthly_watcher": "Monthly Guild Duty",
        "a_comeback": "Return from Death",
        "a_weekend_streak": "Weekend Quest Streak",
        "a_no_zero_days": "No Zero Days in Axel",
        "a_iron_will": "Iron Will of the Party",
        "a_habit_formed": "Training Regimen Formed",
        "a_consistent_pace": "Consistent March Forward",
        "a_year_long": "Year-Long Campaign",
        "a_double_streak": "Double Streak Assault",
        "a_streak_recovery": "Guild Recovery",
        "a_daily_minimum": "Daily Minimum Duty",
        "a_winter_streak": "Winter Quest Streak",
        "a_summer_streak": "Summer EXPLOSION Streak",
        "a_morning_streak": "Morning Guild Streak",
        "a_night_streak": "Night Tavern Streak",
        "a_unbreakable": "Unbreakable Kazuma Will",
        "a_eternal_flame": "Eternal EXPLOSION Flame",
        "a_completion_streak": "Completion Mission Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Episode Offensive",
        "a_genre_streak": "Genre Streak Sortie",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Week of Service",

        // ── ANIME SCORING ──
        "a_critic": "Guild Tribunal Judge",
        "a_perfect_ten": "EXPLOSION! Perfect Ten",
        "a_harsh_critic": "Megumin's Harsh Standards",
        "a_fair_judge": "Kazuma's Fair Assessment",
        "a_generous_spirit": "Aqua's Generous Spirit",
        "a_score_all": "Full Guild Evaluation",
        "a_wide_range": "Wide Range Tactical Assessment",
        "a_controversial": "Controversial Party Decision",
        "a_consistent_scorer": "Consistent Guild Evaluator",
        "a_score_sniper": "Precision Steal Sniper",
        "a_evolving_taste": "Evolving Party Strategy",
        "a_bell_curve": "Bell Curve Quest Scores",
        "a_picky_watcher": "Selective Commander",
        "a_100_rated": "Century of Evaluations",
        "a_500_rated": "Five Hundred Field Reports",
        "a_mediocre_majority": "Average Guild Strategist",
        "a_rating_spree": "Rating EXPLOSION Barrage",
        "a_score_variance": "Variable Quest Ratings",
        "a_masterpiece_hunter": "Masterpiece Quest Hunter",
        "a_contrarian": "Contrarian Kazuma",
        "a_optimist": "Optimist Despite Aqua",
        "a_score_distributor": "Score Distributor General",
        "a_genre_critic": "Genre Tactical Critic",
        "a_mean_above_8": "Elite Guild Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Isekai Vow",
        "a_valentines_weeb": "Valentine's Dedication",
        "a_pi_day": "Pi Day Quest Calc",
        "a_april_fools": "April Fools Aqua Prank",
        "a_international_anime_day": "International Guild Day",
        "a_star_wars_day": "Demon King Empire Day",
        "a_summer_solstice": "Summer Solstice Quest",
        "a_tanabata": "Tanabata Wish for Luck",
        "a_friday_13th": "Friday 13th Undead Attack",
        "a_halloween_spirit": "Halloween Wiz Horror",
        "a_thanksgiving_binge": "Thanksgiving Harvest Feast",
        "a_christmas_special": "Winter Festival Special",
        "a_new_years_eve": "New Year's Eve Final Stand",
        "a_birthday_watch": "Birthday Guild Watch",
        "a_holiday_marathon": "Holiday Quest Marathon",
        "a_independence_day": "Axel Independence Day",
        "a_culture_day": "KonoSuba Culture Day",
        "a_spring_equinox": "Spring Equinox Advance",
        "a_earth_day": "Protect This World Day",
        "a_labor_day": "Guild Labor Day",
        "a_winter_solstice": "Winter Solstice Quest",
        "a_anime_birthday": "Anime Anniversary Celebration",
        "a_every_holiday": "Every Holiday Adventurer",
        "a_consecutive_holidays": "Consecutive Holiday Quests",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Skill Awakened",
        "a_meta_collector": "Guild Badge Collector",
        "a_meta_category_starter": "Category Initiation Rite",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Archwizard-Class Rank",
        "a_meta_xp_earner": "XP from EXPLOSION",
        "a_meta_difficulty_easy": "Easy Training Exercise",
        "a_meta_difficulty_hard": "Legendary Difficulty Demon King",
        "a_meta_unlock_spree": "Unlock Spree EXPLOSION",
        "a_meta_completionist": "Meta Completionist Kazuma",
        "a_meta_diverse": "Diverse Party Portfolio",
        "a_meta_dominator": "Meta Dominator of Axel",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First LN Chapter Read",
        "m_chapter_counter": "Chapter Quest Counter",
        "m_chapter_titan": "Chapter EXPLOSION Assault",
        "m_reading_hours": "Hours Reading Guild Logs",
        "m_reading_time_lord": "Kazuma's Reading Time",
        "m_manga_collector": "KonoSuba Archive Collector",
        "m_library_legend": "Kazuma's Library Legend",
        "m_first_complete": "First Manga Quest Done",
        "m_hundred_club": "Hundred-Chapter Guild Club",
        "m_first_day": "First Day Reading Quest",
        "m_first_rating": "First Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages Read",
        "m_volume_collector": "Volume Stockpile Collector",
        "m_year_explorer": "Year of Manga Exploration",
        "m_century_reader": "Century-Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Chapters Read",
        "m_thousand_ch": "Thousand-Chapter Campaign",
        "m_reading_ten": "Ten Manuscripts at Once",
        "m_ptr_hoarder": "Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Party Retreat",
        "m_season_reader": "Seasonal Reading Rotation",
        "m_active_reader": "Active Guild Reader",
        "m_five_thousand_ch": "Five Thousand Chapters Deep",
        "m_ten_completed": "Ten Manga Quests Complete",
        "m_fifty_completed": "Fifty Manga Missions Done",
        "m_five_hundred_completed": "Five Hundred Manga Victories",
        "m_mean_score_tracker": "Average Manuscript Rating",
        "m_unique_authors": "Unique Author Encounters",
        "m_all_status": "All Reading Statuses",
        "m_first_favorite": "First Manga Comrade Bond",
        "m_favorites_collector": "Manga Favorites Arsenal",
        "m_days_spent_reading": "Days in the Reading Guild",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading EXPLOSION",
        "m_marathon_reader": "Axel-to-Capital Reading",
        "m_weekend_reader": "Weekend Guild Reading",
        "m_non_stop_reading": "Non-Stop Page Turning",
        "m_one_more_chapter": "One More Chapter Charge",
        "m_speed_read": "EXPLOSION Speed Read",
        "m_double_story": "Double Manuscript Feature",
        "m_triple_read": "Triple Reading Assault",
        "m_five_a_day": "Five Reads a Day",
        "m_chapter_chain": "Chapter Chain Offensive",
        "m_volume_binge": "Volume Binge Bombardment",
        "m_power_reader": "Power Reader Scout",
        "m_half_day_read": "Half-Day Archive Dive",
        "m_full_day_read": "Full-Day Manuscript Study",
        "m_power_weekend": "Power Weekend Reading",
        "m_binge_king": "King of the Reading Guild",
        "m_no_sleep_read": "All-Night Guild Reading",
        "m_full_series_rush": "Full Series Rush Attack",
        "m_seven_day_challenge": "Seven-Day Reading Challenge",
        "m_hundred_day_read": "Hundred-Day Reading Siege",
        "m_volume_rush": "Volume Rush Deployment",
        "m_series_sweep": "Series Sweep EXPLOSION",
        "m_genre_binge": "Cross-Genre Binge Maneuver",
        "m_author_binge": "Author Focused Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Count",
        "m_multi_series_binge": "Multi-Series Reading Front",
        "m_midnight_binge": "Midnight Archive Session",
        "m_new_year_binge": "New Year's Reading Charge",
        "m_forty_eight_hour": "Forty-Eight Hour Reading",
        "m_oneshot_binge": "Oneshot Blitz Attack",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Manuscript Specialist",
        "m_genre_adventure": "Adventure Beyond Axel",
        "m_genre_comedy": "Comedy in the Guild",
        "m_genre_drama": "Drama of Aqua's Tears",
        "m_genre_fantasy": "Fantasy Isekai Manuscript",
        "m_genre_horror": "Wiz Horror Manuscript",
        "m_genre_mystery": "Mystery of Vanir's Shop",
        "m_genre_romance": "Aqua Rejects Kazuma Manga",
        "m_genre_scifi": "Devil Technology Manuscript",
        "m_genre_sol": "Slice of Axel Life Manga",
        "m_genre_sports": "Guild Training Sports",
        "m_genre_supernatural": "Aqua's Divine Powers Manga",
        "m_genre_thriller": "Demon King Approaches Manga",
        "m_genre_psychological": "Kazuma's Nihilism Manga",
        "m_genre_isekai": "Isekai'd via Truck Manga",
        "m_genre_shounen": "Kazuma Heart Dedication",
        "m_genre_ecchi": "Hot Springs Chapter Manga",
        "m_genre_mahou_shoujo": "Megumin Archmage Manga",
        "m_genre_mecha": "Magical Artillery Manga",
        "m_genre_music": "Aqua's Hymn Manga",
        "m_tag_isekai_new": "New World Isekai Manga",
        "m_tag_harem": "Useless Harem Manga",
        "m_tag_bl": "Guild Bros Manga",
        "m_tag_gl": "Shield Sisters Manga",
        "m_tag_historical": "Demon King's History Manga",
        "m_tag_military": "Axis Crusader Manga",
        "m_tag_school": "Adventurer Academy Manga",
        "m_tag_martial_arts": "Steal Technique Manga",
        "m_tag_vampire": "Undead Shopkeeper Manga",
        "m_tag_samurai": "Darkness Blade Manga",
        "m_tag_space": "Beyond the Kingdom Manga",
        "m_tag_parody": "Aqua Fails Again Manga",
        "m_tag_idol": "Aqua Idol Manga",
        "m_tag_post_apocalyptic": "Post-Demon King Manga",
        "m_tag_cyberpunk": "Devil Tech Manga",
        "m_tag_shoujo": "Megumin's Story Manga",
        "m_tag_survival": "Surviving Axel Manga",
        "m_tag_cooking": "Guild Kitchen Cookbook",
        "m_tag_medical": "Aqua Healer Manga",
        "m_tag_villainess": "Darkness Warrior Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Guild Completionist",
        "m_mega_completionist": "Supreme Manga Commander",
        "m_completion_rate_50": "Halfway to Demon King",
        "m_completion_rate_75": "Approaching the Castle",
        "m_completion_rate_90": "Final Chapter Approaching",
        "m_no_drop": "No Manuscript Abandoned",
        "m_long_runner_complete": "Long Series Endurance",
        "m_sequel_chain": "Sequel Quest Chain",
        "m_clean_list": "Clean Reading Record",
        "m_from_ptr": "Orders Received Read",
        "m_reread_master": "Comedy Reread Master",
        "m_oneshot_complete": "Oneshot Quest Specialist",
        "m_same_day_start_finish": "Same-Day Manga Blitz",
        "m_revival": "Revived by Aqua Reader",
        "m_zero_to_hundred": "NEET to Scholar",
        "m_five_genre_complete": "Five-Genre Mastery",
        "m_full_collection": "Full KonoSuba Collection",
        "m_batch_complete": "Batch Quest Clearance",
        "m_paused_to_done": "Back from Hiatus",
        "m_completion_spree": "Completion EXPLOSION Barrage",
        "m_format_completionist": "Format Completion Badge",
        "m_catch_up": "Caught Up with Serialization",
        "m_multi_reread": "Multi-Pass Reread",
        "m_dropped_recovery": "Recovered from Defeat",
        "m_ten_perfect_scores": "Ten Perfect Manga Scores",
        "m_complete_genre_span": "All-Genre Reading Scout",
        "m_monthly_completions": "Monthly Manga Victories",
        "m_yearly_completions": "Yearly Reading Campaign",
        "m_rapid_complete": "Rapid Intel Processing",
        "m_author_complete": "Author's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Guild Reader",
        "m_mangaka_lover": "KonoSuba Mangaka Devotee",
        "m_rereader": "Party Rereader",
        "m_triple_reread": "Triple Reread EXPLOSION",
        "m_annual_reread": "Annual Axel Reread",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Artist Appreciation Medal",
        "m_adaptation_compare": "Manga vs Anime Compare",
        "m_source_material_fan": "Source Material Scout",
        "m_waiting_weekly": "Weekly Chapter Wait",
        "m_classic_reader": "Classic Guild Manuscript",
        "m_saga_reader": "KonoSuba Saga Reader",
        "m_genre_loyalty": "Isekai Genre Loyalty",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "Light Novel Adaptation",
        "m_original_work": "Original Manga Work",
        "m_long_commitment": "Long-Term Reading Commitment",
        "m_up_to_date": "Up-to-Date with Guild",
        "m_favorite_mangaka": "Favorite Mangaka Honored",
        "m_complete_portfolio": "Complete Reading Portfolio",
        "m_franchise_collector": "KonoSuba Franchise Fan",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Mastery Earned",
        "m_multi_series_author": "Multi-Series Author Fan",
        "m_format_diversity": "Diverse Reading Formats",
        "m_year_dedication": "Year of Dedicated Reading",
        "m_ongoing_follower": "Ongoing Series Follower",
        "m_genre_loyalty_50": "Fifty Genre Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Territory Scout",
        "m_publisher_hopper": "Publisher Party Transfer",
        "m_tag_explorer": "Manga Tag Recon",
        "m_decade_hopper": "Decade-Hopping Kazuma",
        "m_hidden_gem": "Hidden Dungeon Gem",
        "m_popular_taste": "Popular at the Guild",
        "m_retro_reader": "Retro Manuscript Appreciator",
        "m_modern_reader": "Modern Adventurer Reader",
        "m_cross_demographic": "Cross-Party Scout",
        "m_underdog_fan": "Underdog Kazuma Fan",
        "m_variety_week": "Week of Varied Readings",
        "m_manhwa_reader": "Manhwa Guild Reader",
        "m_manhua_reader": "Manhua Guild Reader",
        "m_classic_connoisseur": "Classic Quest Manuscript",
        "m_award_winner": "Medal-Winning Manuscript",
        "m_niche_explorer": "Niche Dungeon Reader",
        "m_world_manga": "World Manga Intel",
        "m_cult_classic": "Axel Cult Classic",
        "m_random_pick": "Random Reading Assignment",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Reading Completionist",
        "m_unpopular_opinion": "Unpopular Party Opinion",
        "m_top_rated_reader": "Top-Rated Guild Source",
        "m_source_variety": "Source Material Variety",
        "m_low_score_brave": "Brave Low-Score Reader",
        "m_short_manga_explorer": "Short Quest Manga",
        "m_long_manga_explorer": "Long Campaign Manuscript",
        "m_serialization_explorer": "Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Guild Reader",
        "m_early_bird": "Dawn Patrol Reader",
        "m_lunch_reader": "Guild Mess Hall Reader",
        "m_commute_reader": "Travel to Guild Reader",
        "m_four_am_club": "4 AM Dungeon Reader",
        "m_new_year_read": "New Year's Reading Oath",
        "m_all_hours": "All-Hours Archive Access",
        "m_prime_time_reader": "Prime Time Manuscript",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Reading Marathon",
        "m_morning_routine": "Morning Formation Reading",
        "m_night_shift_reader": "Night Shift Reader",
        "m_seasonal_premier_read": "New Release Intel",
        "m_clock_collector": "Clock Tower Reading Time",
        "m_late_night_horror": "Midnight Wiz Horror Read",
        "m_afternoon_reader": "Afternoon Guild Reading",
        "m_golden_hour_reader": "Golden Hour Reading",
        "m_dawn_reader": "Dawn Reading Scout",
        "m_twilight_reader": "Twilight Gate Reading",
        "m_midnight_start": "Midnight Reading Mission",
        "m_weekend_binge_hours": "Weekend Binge Reading",
        "m_late_night_regular": "Late Night Regular Reader",
        "m_sunrise_reader": "Sunrise Over Axel Reader",
        "m_every_day_of_week": "Every Day Reading Duty",
        "m_monthly_hours": "Monthly Reading Hours",
        "m_bedtime_reader": "Bedtime Guild Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "KonoSuba Art Appreciator",
        "m_webtoon_reader": "Webtoon Guild Reader",
        "m_full_color": "Full Color Manuscript",
        "m_doujin_reader": "Underground Doujin Reader",
        "m_anthology_reader": "Anthology Collection Reader",
        "m_adaptation_reader": "Adaptation Study Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Comedy Shorts",
        "m_oneshot_reader": "Oneshot Quest Reader",
        "m_format_variety": "Format Tactical Variety",
        "m_light_novel_reader": "Light Novel Reader",
        "m_novel_reader": "Novel Archive Reader",
        "m_visual_storyteller": "Visual Quest Narrator",
        "m_colored_classic": "Colored Classic Manga",
        "m_webcomic_fan": "Webcomic Underground Fan",
        "m_manga_to_anime": "Manga to Anime Compare",
        "m_seinen_reader": "Seinen Guild Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Medal-Winning Artwork",
        "m_debut_work": "Debut Manuscript",
        "m_vertical_scroll": "Vertical Scroll Intel",
        "m_traditional_format": "Traditional Format Reader",
        "m_cross_media": "Cross-Media Intelligence",
        "m_spinoff_reader": "Spinoff Quest Reader",
        "m_remake_reader": "Remake Reading Assignment",
        "m_collaboration_reader": "Joint Quest Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Quest Reading Streak",
        "m_mega_streak": "Mega Reading EXPLOSION",
        "m_weekly_warrior": "Weekly Warrior Reader",
        "m_monthly_reader": "Monthly Guild Reader",
        "m_comeback": "Reader's Return to Axel",
        "m_weekend_streak": "Weekend Reading Streak",
        "m_no_zero_days": "No Zero Reading Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Regimen Formed",
        "m_consistent_pace": "Consistent Reading Advance",
        "m_year_long": "Year-Long Reading Campaign",
        "m_double_streak": "Double Reading Streak",
        "m_streak_recovery": "Reading Streak Recovery",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Reading Campaign",
        "m_summer_streak": "Summer EXPLOSION Reading",
        "m_morning_streak": "Morning Reading Formation",
        "m_night_streak": "Night Reading Patrol",
        "m_unbreakable": "Unbreakable Reading Will",
        "m_eternal_flame": "Eternal EXPLOSION Knowledge",
        "m_chapter_a_day": "Chapter a Day Discipline",
        "m_genre_streak": "Genre Reading Streak",
        "m_completion_streak": "Completion Reading Chain",
        "m_rating_streak": "Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Dedication Streak",
        "m_perfect_week_manga": "Perfect Reading Week",
        "m_diverse_streak": "Diverse Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Guild Manuscript Critic",
        "m_perfect_ten": "Perfect 10 EXPLOSION Manga",
        "m_harsh_critic": "Megumin's Reading Standards",
        "m_fair_judge": "Kazuma's Fair Review",
        "m_generous_spirit": "Aqua's Generous Reading",
        "m_score_all": "Full Manuscript Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Reading Opinion",
        "m_consistent_scorer": "Consistent Manga Scorer",
        "m_score_sniper": "Precision Score Sniper",
        "m_evolving_taste": "Evolving Reading Taste",
        "m_bell_curve": "Bell Curve of Scores",
        "m_picky_reader": "Selective Reading Commander",
        "m_100_rated": "Century of Ratings Filed",
        "m_500_rated": "Five Hundred Rating Reports",
        "m_mediocre_majority": "Average Guild Reader",
        "m_rating_spree": "Rating EXPLOSION Barrage",
        "m_score_variance": "Variable Manuscript Scores",
        "m_binge_rater": "Binge Rating Session",
        "m_reread_rerate": "Reread and Re-Rate",
        "m_masterpiece_hunter": "Masterpiece Manga Hunter",
        "m_contrarian": "Contrarian Kazuma Reader",
        "m_optimist": "Optimistic Guild Reader",
        "m_score_distributor": "Score Distributor General",
        "m_genre_critic": "Genre Reading Critic",
        "m_mean_above_8": "Elite Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Reading Vow",
        "m_valentines_read": "Valentine's Reading Bond",
        "m_pi_day": "Pi Day Chapter Count",
        "m_april_fools": "April Fools Aqua Chibi",
        "m_international_manga_day": "International Manga Day",
        "m_free_comic_day": "Free Comic Guild Day",
        "m_summer_solstice": "Summer Solstice Reading",
        "m_tanabata": "Tanabata Reading Wish",
        "m_friday_13th": "Friday 13th Undead Manga",
        "m_halloween_read": "Halloween Wiz Reading",
        "m_thanksgiving_binge": "Thanksgiving Reading Feast",
        "m_christmas_read": "Winter Festival Reading",
        "m_new_years_eve": "New Year's Eve Final Read",
        "m_birthday_read": "Birthday Reading Gift",
        "m_holiday_marathon": "Holiday Reading Marathon",
        "m_independence_day": "Axel Independence Reading",
        "m_culture_day": "Culture Day Manuscript",
        "m_spring_equinox": "Spring Equinox Reading",
        "m_earth_day": "Earth Day Conservation Read",
        "m_labor_day": "Guild Labor Reading Day",
        "m_winter_solstice": "Winter Solstice Reading",
        "m_manga_birthday": "Manga Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Reader",
        "m_consecutive_holidays": "Consecutive Holiday Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Milestone",
        "m_fibonacci": "Fibonacci Chapter Pattern",
        "m_palindrome_day": "Palindrome Reading Day",
        "m_binary_day": "Binary Signal Reading Day",
        "m_full_moon_read": "Full Moon Undead Read",
        "m_leap_year_read": "Leap Year Reading",
        "m_triple_seven": "Triple Seven Lucky Chapters",
        "m_thousand_complete": "Thousand Manga Victories",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Kazuma-Level Chapters",
        "m_answer_42": "Answer to Axel's Reading",
        "m_square_number": "Perfect Formation Chapters",
        "m_prime_count": "Prime Chapter Count",
        "m_matching_date": "Matching Guild Reading Date",
        "m_century_chapter": "Century Chapter Milestone",
        "m_pi_chapters": "Pi Chapter Calculation",
        "m_synchronicity": "Party Reading Synchronicity",
        "m_world_record": "World Record Chapters",
        "m_genre_clash": "Genre Clash Reading",
        "m_time_traveler": "Time-Traveling Reader",
        "m_double_digits": "Double Digit Milestone",
        "m_one_two_three": "Kazuma Aqua Megumin Manga",
        "m_lucky_seven": "Seven Lucky Chapters",
        "m_exact_hundred_ch": "Exact Hundred Chapters",
        "m_year_match_count": "Year Match Chapter Count",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Manhwa Format Reader",
        "m_manhua_format": "Manhua Format Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Operative",
        "m_doujin_format": "Doujin Format Reader",
        "m_novel_format": "Novel Format Reader",
        "m_format_master_manga": "Format Master Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Reading Skill Unlocked",
        "m_meta_collector": "Reading Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Reading Rank",
        "m_meta_xp_earner": "XP from Reading",
        "m_meta_difficulty_easy": "Easy Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Manga Challenge",
        "m_meta_unlock_spree": "Reading Unlock EXPLOSION",
        "m_meta_completionist": "Meta Reading Completionist",
        "m_meta_diverse": "Diverse Party Reading",
        "m_meta_dominator": "Meta Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg:        "#0d0500",
        primary:   "#d75a05",
        secondary: "#ff9030",
        accent:    "#f0d040",
    },
    milestoneNames: {
        1:   "NEET Isekai'd",
        5:   "Beginner Adventurer",
        12:  "Regular Adventurer",
        22:  "Intermediate Adventurer",
        35:  "Senior Adventurer",
        50:  "Intermediate Archwizard",
        65:  "Arch Priest",
        80:  "Archwizard (EXPLOSION!)",
        100: "Demon King's Castle Conqueror",
    },
}
