import { AnimeThemeConfig } from "./types"
import {
    GiTopHat,
    GiPistolGun,
    GiKey,
    GiChainedHeart,
    GiGasMask,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const lupinIiiTheme: AnimeThemeConfig = {
    id: "lupin-iii",
    displayName: "Lupin III",
    description: "Gentleman thief vibes. Globe-trotting heists with Jigen, Goemon, Fujiko, and Inspector Zenigata always one step behind.",
    fontFamily: "'Rubik', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap",
    cssVars: {
        // Brand → red jacket
        "--color-brand-200": "245 160 168",
        "--color-brand-300": "238 115 122",
        "--color-brand-400": "230 78 88",
        "--color-brand-500": "220 50 60",
        "--color-brand-600": "185 40 50",
        "--color-brand-700": "150 30 38",
        "--color-brand-800": "110 20 28",
        "--color-brand-900": "70 12 18",
        "--color-brand-950": "40 5 10",
        "--brand": "220 50 60",
        // Dark noir background
        "--background": "#0a0304",
        "--paper": "#140608",
        "--color-gray-950": "10 3 4",
        "--color-gray-900": "20 6 8",
        "--color-gray-800": "34 14 18",
        "--color-gray-700": "55 28 34",
        "--color-gray-600": "78 48 55",
        "--color-gray-500": "108 76 82",
        "--color-gray-400": "148 118 124",
        "--color-gray-300": "182 160 165",
        "--color-gray-200": "212 198 202",
        "--color-gray-100": "232 224 226",
        "--color-gray-50": "246 241 243",
    },
    sidebarOverrides: {
        "home": { icon: GiTopHat, label: "Lupin's Hideout" },
        "schedule": { icon: GiAlarmClock, label: "Heist Schedule" },
        "manga": { icon: LuBookOpen, label: "Stolen Archives" },
        "lists": { icon: GiKey, label: "Target Dossiers" },
        "discover": { icon: GiBullseye, label: "Next Mark" },
        "torrent-list": { icon: GiAnvilImpact, label: "Black Market" },
        "debrid": { icon: GiPistolGun, label: "Jigen's Arsenal" },
        "unmatched": { icon: GiChainedHeart, label: "Cold Cases" },
        "enmasse": { icon: GiResize, label: "Mass Heist" },
        "scan-summaries": { icon: TbReportSearch, label: "Recon Reports" },
        "auto-downloader": { icon: LuRss, label: "Dead Drops" },
        "community": { icon: GiGasMask, label: "Underworld" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Tip-Offs" },
        "achievements": { icon: GiTrophy, label: "Heist Trophies" },
        "theme-manager": { icon: GiPalette, label: "Disguise Kit" },
        "extensions": { icon: BiExtension, label: "Gadgets" },
        "sync": { icon: IoCloudOfflineOutline, label: "Safehouse Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Operations HQ" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Heist",
        "a_episode_counter": "Heist Tally",
        "a_episode_titan": "Grand Heist",
        "a_hours_invested": "Stakeout Hours",
        "a_time_lord": "Time Bandit",
        "a_anime_collector": "Loot Hoard",
        "a_library_legend": "Archive Thief",
        "a_first_complete": "Clean Getaway",
        "a_hundred_club": "Century Caper",
        "a_first_day": "Rookie Thief",
        "a_first_rating": "Loot Appraisal",
        "a_ten_thousand_min": "Ten Grand",
        "a_season_veteran": "Veteran Grifter",
        "a_year_explorer": "Globe Trotter",
        "a_century_watcher": "Hundred Jobs",
        "a_five_hundred_eps": "Five Hundred Marks",
        "a_thousand_eps": "Thousand Scores",
        "a_watching_ten": "Ten Marks",
        "a_ptw_hoarder": "Wish List",
        "a_dropped_honesty": "Botched Job",
        "a_five_thousand_eps": "Grand Larceny",
        "a_ten_completed": "Ten Getaways",
        "a_fifty_completed": "Fifty Capers",
        "a_five_hundred_completed": "Master Burglar",
        "a_mean_score_tracker": "Average Haul",
        "a_unique_studios": "Allied Fences",
        "a_days_spent_watching": "Days Casing",
        "a_all_status": "All Aliases",
        "a_first_favorite": "First Mark",
        "a_favorites_collector": "Trophy Case",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Crime Spree",
        "a_marathon_runner": "Marathon Caper",
        "a_weekend_warrior": "Weekend Heist",
        "a_non_stop": "Unstoppable",
        "a_one_more_episode": "One More Job",
        "a_speed_run": "Speed Theft",
        "a_double_feature": "Double Cross",
        "a_triple_threat": "Triple Threat",
        "a_five_a_day": "Five-Finger Discount",
        "a_back_to_back": "Back-to-Back",
        "a_seasonal_binge": "Seasonal Spree",
        "a_cour_crusher": "Vault Crusher",
        "a_half_day_watch": "Half-Day Stake",
        "a_full_day_watch": "Full Stakeout",
        "a_power_weekend": "Power Weekend",
        "a_binge_king": "King of Thieves",
        "a_no_sleep": "All-Night Job",
        "a_entire_season": "Clean Sweep",
        "a_seven_day_challenge": "Seven-Day Caper",
        "a_hundred_day_binge": "Hundred-Day Con",
        "a_genre_binge": "Genre Spree",
        "a_studio_binge": "Studio Robbery",
        "a_season_sweep": "Season Heist",
        "a_forty_eight_hour": "Forty-Eight Hours",
        "a_ep_counter_day": "Daily Loot",
        "a_multi_series_binge": "Multi-Target Run",
        "a_midnight_binge": "Midnight Raid",
        "a_new_year_binge": "New Year Score",

        // ── ANIME GENRES ──
        "a_genre_action": "Action Caper",
        "a_genre_adventure": "Adventure Job",
        "a_genre_comedy": "Comic Relief",
        "a_genre_drama": "Dramatic Reveal",
        "a_genre_fantasy": "Fantasy Heist",
        "a_genre_horror": "Horror Vault",
        "a_genre_mystery": "Mystery Caper",
        "a_genre_romance": "Stolen Hearts",
        "a_genre_scifi": "Sci-Fi Gadgets",
        "a_genre_sol": "Hideout Life",
        "a_genre_sports": "Athletic Escape",
        "a_genre_supernatural": "Phantom Thief",
        "a_genre_thriller": "Thriller Chase",
        "a_genre_mecha": "Mecha Heist",
        "a_genre_music": "Jazz Heist",
        "a_genre_psychological": "Mind Games",
        "a_genre_ecchi": "Fujiko's Charm",
        "a_genre_mahou_shoujo": "Magic Trick",
        "a_tag_isekai": "Foreign Caper",
        "a_tag_harem": "Lupin's Ladies",
        "a_tag_bl": "Partners in Crime",
        "a_tag_gl": "Lady Thieves",
        "a_tag_historical": "Historical Heist",
        "a_tag_military": "Military Target",
        "a_tag_school": "Academy Heist",
        "a_tag_martial_arts": "Goemon's Way",
        "a_tag_vampire": "Night Prowler",
        "a_tag_samurai": "Zantetsuken",
        "a_tag_space": "Space Caper",
        "a_tag_parody": "Parody Disguise",
        "a_tag_idol": "Spotlight Thief",
        "a_tag_post_apocalyptic": "Post-Heist Ruins",
        "a_tag_cyberpunk": "Cyber Heist",
        "a_tag_shounen": "Young Thief",
        "a_tag_seinen": "Master Criminal",
        "a_tag_shoujo": "Jewel Thief",
        "a_tag_josei": "Refined Taste",
        "a_tag_survival": "Survival Instinct",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Dossier",
        "a_mega_completionist": "Master Dossier",
        "a_completion_rate_50": "Halfway There",
        "a_completion_rate_75": "Almost Clean",
        "a_completion_rate_90": "Near Flawless",
        "a_no_drop": "No Job Dropped",
        "a_long_runner_complete": "Long Con",
        "a_sequel_chain": "Chain Heist",
        "a_clean_list": "Clean Record",
        "a_from_ptw": "Executed Orders",
        "a_rewatch_master": "Case Review",
        "a_short_complete": "Quick Score",
        "a_same_day_start_finish": "Same-Day Job",
        "a_revival": "Back in Action",
        "a_zero_to_hero": "Rags to Riches",
        "a_five_genre_complete": "Five-Genre Thief",
        "a_full_franchise": "Full Franchise",
        "a_batch_complete": "Batch Heist",
        "a_paused_to_done": "Resumed Caper",
        "a_completion_spree": "Completion Spree",
        "a_multi_rewatch": "Multi-Review",
        "a_dropped_recovery": "Recovered Loot",
        "a_ten_perfect_scores": "Ten Flawless",
        "a_seasonal_clear": "Seasonal Clear",
        "a_complete_genre_span": "Genre Sweep",
        "a_monthly_completions": "Monthly Report",
        "a_yearly_completions": "Annual Haul",
        "a_rapid_complete": "Rapid Heist",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Accomplice",
        "a_studio_devotee": "Studio Devotee",
        "a_rewatcher": "Rewatch Recon",
        "a_triple_rewatch": "Triple Review",
        "a_annual_tradition": "Annual Tradition",
        "a_director_fan": "Director's Cut",
        "a_voice_actor_fan": "Voice Disguise",
        "a_ost_lover": "Jazz Aficionado",
        "a_source_reader": "Source Material",
        "a_waiting_weekly": "Weekly Stakeout",
        "a_childhood_revisit": "Childhood Heist",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Genre Loyalty",
        "a_decade_watcher": "Decade Thief",
        "a_adaptation_hunter": "Adaptation Recon",
        "a_original_anime_fan": "Original Broadcast",
        "a_long_commitment": "Long Commitment",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Studios",
        "a_complete_catalog": "Complete Catalog",
        "a_franchise_collector": "Franchise Vault",
        "a_airing_follower": "Current Intel",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Crew Dossier",
        "a_multi_season_fan": "Multi-Season Fan",
        "a_format_diversity": "Diverse Formats",
        "a_year_dedication": "Year of Thievery",
        "a_season_dedication": "Season of Crime",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "New Territory",
        "a_studio_hopper": "Studio Hopper",
        "a_tag_explorer": "Tag Recon",
        "a_decade_hopper": "Decade Hopper",
        "a_hidden_gem": "Hidden Treasure",
        "a_popular_taste": "Popular Taste",
        "a_retro_appreciator": "Vintage Score",
        "a_modern_viewer": "Modern Caper",
        "a_cross_demographic": "Cross-Border Job",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Targets",
        "a_foreign_cinema": "Foreign Film",
        "a_classic_connoisseur": "Classic Score",
        "a_every_season": "Every Season",
        "a_award_winner": "Award Winner",
        "a_niche_explorer": "Niche Explorer",
        "a_global_anime": "Global Caper",
        "a_cult_classic": "Cult Classic",
        "a_random_pick": "Random Mark",
        "a_new_genre_month": "Monthly Discovery",
        "a_seasonal_completionist": "Seasonal Sweep",
        "a_unpopular_opinion": "Unpopular Take",
        "a_top_rated_viewer": "Top-Rated Intel",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Gamble",
        "a_upcoming_watcher": "Upcoming Intel",
        "a_short_series_explorer": "Short Job",
        "a_long_series_explorer": "Extended Caper",

        // ── ANIME TIME ──
        "a_night_owl": "Night Prowl",
        "a_early_bird": "Dawn Recon",
        "a_lunch_break": "Lunch Break",
        "a_golden_hour": "Golden Hour",
        "a_four_am_club": "4 AM Lookout",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Heist",
        "a_midnight_premiere": "Midnight Premiere",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Escape",
        "a_afternoon_delight": "Afternoon Stake",
        "a_prime_time": "Prime Time",
        "a_workday_watcher": "On-Duty Watch",
        "a_sunday_marathon": "Sunday Marathon",
        "a_rainy_day": "Rainy Day Job",
        "a_morning_routine": "Morning Routine",
        "a_night_shift": "Night Shift",
        "a_twilight_zone": "Twilight Heist",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge",
        "a_late_night_regular": "Late Night Run",
        "a_sunrise_watcher": "Sunrise Escape",
        "a_holiday_watcher": "Holiday Watch",
        "a_every_day_of_week": "Every Day Active",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Crew",
        "a_party_host": "Crew Leader",
        "a_social_butterfly": "Social Charmer",
        "a_group_binge": "Group Heist",
        "a_party_regular": "Regular Crew",
        "a_sync_viewer": "Synchronized Job",
        "a_commentator": "Commentator",
        "a_party_marathon": "Crew Marathon",
        "a_full_house": "Full House",
        "a_community_pillar": "Underworld Pillar",
        "a_watch_party_streak": "Crew Streak",
        "a_diverse_party": "Diverse Crew",
        "a_late_night_party": "Late Night Crew",
        "a_party_veteran": "Veteran Leader",
        "a_genre_party": "Genre Crew",
        "a_weekly_party": "Weekly Meet",
        "a_silent_viewer": "Silent Partner",
        "a_recommendation_giver": "Tip-Off",
        "a_party_completionist": "Crew Completionist",
        "a_social_scorer": "Social Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Fibonacci Code",
        "a_palindrome_day": "Palindrome Day",
        "a_binary_day": "Binary Code",
        "a_full_moon": "Full Moon Job",
        "a_leap_year": "Leap Year",
        "a_time_traveler": "Time Traveler",
        "a_genre_clash": "Genre Clash",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Scores",
        "a_pi_episodes": "Pi Calculation",
        "a_synchronicity": "Synchronicity",
        "a_world_record": "World Record",
        "a_nice": "Nice Haul",
        "a_power_level": "Power Level",
        "a_answer_42": "Answer Forty-Two",
        "a_square_number": "Square Number",
        "a_prime_count": "Prime Count",
        "a_matching_date": "Matching Date",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast",
        "a_movie_buff": "Movie Heist",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Episode",
        "a_short_king": "Short King",
        "a_variety_pack": "Variety Pack",
        "a_film_festival": "Film Festival",
        "a_music_video": "Music Video",
        "a_tv_short": "Quick Clip",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Anthology",
        "a_mini_series": "Mini Caper",
        "a_theatrical": "Theatrical Run",
        "a_format_master": "Format Master",
        "a_long_movie": "Feature Length",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "Commercial Break",
        "a_pv_collector": "Preview Collector",
        "a_format_balance": "Format Balance",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Film",
        "a_recap_watcher": "Recap Viewer",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Streak",
        "a_mega_streak": "Mega Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Watch",
        "a_comeback": "Grand Return",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Steady Pace",
        "a_year_long": "Year-Long Caper",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Episode Run",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Art Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Harsh Appraiser",
        "a_fair_judge": "Fair Judge",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Full Appraisal",
        "a_wide_range": "Wide Range",
        "a_controversial": "Controversial Take",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Precision Sniper",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Picky Connoisseur",
        "a_100_rated": "Century Rated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Hunter",
        "a_contrarian": "Contrarian",
        "a_optimist": "Optimist",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Vow",
        "a_valentines_weeb": "Valentine Theft",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Fools",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "Empire Day",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday Thirteenth",
        "a_halloween_spirit": "Halloween Heist",
        "a_thanksgiving_binge": "Thanksgiving Feast",
        "a_christmas_special": "Christmas Caper",
        "a_new_years_eve": "New Year's Eve",
        "a_birthday_watch": "Birthday Score",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Independence Day",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Equinox",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Day",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anime Birthday",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Holiday Streak",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Unlock",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Starter",
        "a_meta_tier_climber": "Rank Climber",
        "a_meta_tier_max": "Maximum Rank",
        "a_meta_xp_earner": "XP Earner",
        "a_meta_difficulty_easy": "Easy Pickings",
        "a_meta_difficulty_hard": "Impossible Heist",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Complete",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page Lifted",
        "m_chapter_counter": "Chapter Tally",
        "m_chapter_titan": "Grand Chapter",
        "m_reading_hours": "Recon Hours",
        "m_reading_time_lord": "Reading Bandit",
        "m_manga_collector": "Manuscript Thief",
        "m_library_legend": "Library Heist",
        "m_first_complete": "First Read Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "Reading Debut",
        "m_first_rating": "First Appraisal",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Vault",
        "m_year_explorer": "Year of Reading",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Read",
        "m_thousand_ch": "Thousand Chapters",
        "m_reading_ten": "Ten at Once",
        "m_ptr_hoarder": "Backlog Vault",
        "m_dropped_honesty": "Honest Drop",
        "m_season_reader": "Seasonal Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Read Done",
        "m_fifty_completed": "Fifty Reads Done",
        "m_five_hundred_completed": "Five Hundred Done",
        "m_mean_score_tracker": "Average Rating",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Favorites Vault",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Reading Spree",
        "m_marathon_reader": "Marathon Read",
        "m_weekend_reader": "Weekend Read",
        "m_non_stop_reading": "Non-Stop Pages",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Read",
        "m_double_story": "Double Feature",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five a Day",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Read",
        "m_full_day_read": "Full-Day Read",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge Monarch",
        "m_no_sleep_read": "All-Night Read",
        "m_full_series_rush": "Series Rush",
        "m_seven_day_challenge": "Seven-Day Read",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Binge",
        "m_author_binge": "Author Binge",
        "m_chapter_counter_day": "Daily Chapters",
        "m_multi_series_binge": "Multi-Series Run",
        "m_midnight_binge": "Midnight Read",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "Forty-Eight Hours",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Loot",
        "m_genre_adventure": "Adventure Score",
        "m_genre_comedy": "Comedy Gold",
        "m_genre_drama": "Drama Heist",
        "m_genre_fantasy": "Fantasy Vault",
        "m_genre_horror": "Horror Haul",
        "m_genre_mystery": "Mystery Case",
        "m_genre_romance": "Romance Theft",
        "m_genre_scifi": "Sci-Fi Gadget",
        "m_genre_sol": "Hideout Read",
        "m_genre_sports": "Sports Heist",
        "m_genre_supernatural": "Phantom Pages",
        "m_genre_thriller": "Thriller Read",
        "m_genre_psychological": "Mind Heist",
        "m_genre_isekai": "Isekai Caper",
        "m_genre_shounen": "Shounen Score",
        "m_genre_ecchi": "Ecchi Swipe",
        "m_genre_mahou_shoujo": "Magic Ploy",
        "m_genre_mecha": "Mecha Loot",
        "m_genre_music": "Jazz Pages",
        "m_tag_isekai_new": "New World Job",
        "m_tag_harem": "Harem Heist",
        "m_tag_bl": "Crew Bonds",
        "m_tag_gl": "Lady Partners",
        "m_tag_historical": "Historical Loot",
        "m_tag_military": "Military Intel",
        "m_tag_school": "Academy Job",
        "m_tag_martial_arts": "Martial Artistry",
        "m_tag_vampire": "Night Read",
        "m_tag_samurai": "Blade Reader",
        "m_tag_space": "Space Loot",
        "m_tag_parody": "Parody Score",
        "m_tag_idol": "Idol Swipe",
        "m_tag_post_apocalyptic": "Post-Ruin Read",
        "m_tag_cyberpunk": "Cyber Loot",
        "m_tag_shoujo": "Shoujo Gem",
        "m_tag_survival": "Survival Read",
        "m_tag_cooking": "Cooking Heist",
        "m_tag_medical": "Medical Intel",
        "m_tag_villainess": "Villainess Ploy",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Collection",
        "m_mega_completionist": "Mega Collection",
        "m_completion_rate_50": "Halfway Done",
        "m_completion_rate_75": "Almost There",
        "m_completion_rate_90": "Nearly Complete",
        "m_no_drop": "Nothing Dropped",
        "m_long_runner_complete": "Long Read Done",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean Ledger",
        "m_from_ptr": "Orders Read",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Read",
        "m_revival": "Reading Revival",
        "m_zero_to_hundred": "Zero to Hundred",
        "m_five_genre_complete": "Five-Genre Read",
        "m_full_collection": "Full Archive",
        "m_batch_complete": "Batch Clear",
        "m_paused_to_done": "Back to Reading",
        "m_completion_spree": "Completion Blitz",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi-Reread",
        "m_dropped_recovery": "Dropped Recovery",
        "m_ten_perfect_scores": "Ten Perfect",
        "m_complete_genre_span": "All-Genre Read",
        "m_monthly_completions": "Monthly Reads",
        "m_yearly_completions": "Yearly Reads",
        "m_rapid_complete": "Rapid Read",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Fan",
        "m_rereader": "Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Art Appreciator",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Fan",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyal",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Fave Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Franchise Loot",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Expert",
        "m_multi_series_author": "Multi-Series Fan",
        "m_format_diversity": "Format Variety",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Tracker",
        "m_genre_loyalty_50": "Fifty Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Explorer",
        "m_decade_hopper": "Decade Jumper",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Pick",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross-Demo Read",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Varied Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Taste",
        "m_award_winner": "Award Read",
        "m_niche_explorer": "Niche Find",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Favorite",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "Monthly Genre",
        "m_year_completionist": "Year Clear",
        "m_unpopular_opinion": "Unpopular Pick",
        "m_top_rated_reader": "Top-Rated Read",
        "m_source_variety": "Source Mix",
        "m_low_score_brave": "Brave Read",
        "m_short_manga_explorer": "Short Explorer",
        "m_long_manga_explorer": "Long Explorer",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Lunch Reader",
        "m_commute_reader": "Commute Read",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Pages",
        "m_all_hours": "All Hours Read",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "Workday Reader",
        "m_sunday_read": "Sunday Read",
        "m_morning_routine": "Morning Read",
        "m_night_shift_reader": "Night Shift Read",
        "m_seasonal_premier_read": "New Release",
        "m_clock_collector": "Time Collector",
        "m_late_night_horror": "Midnight Horror",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Pages",
        "m_twilight_reader": "Twilight Read",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Hours",
        "m_late_night_regular": "Late Night Read",
        "m_sunrise_reader": "Sunrise Read",
        "m_every_day_of_week": "Every Day Read",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Connoisseur",
        "m_webtoon_reader": "Webtoon Read",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Read",
        "m_adaptation_reader": "Adaptation Read",
        "m_longstrip_reader": "Longstrip Read",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Read",
        "m_format_variety": "Format Mix",
        "m_light_novel_reader": "Light Novel",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Story",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Read",
        "m_josei_reader": "Josei Read",
        "m_award_winning_art": "Award Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross-Media",
        "m_spinoff_reader": "Spinoff Read",
        "m_remake_reader": "Remake Read",
        "m_collaboration_reader": "Collab Read",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read Streak",
        "m_mega_streak": "Mega Read Streak",
        "m_weekly_warrior": "Weekly Reader",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader Comeback",
        "m_weekend_streak": "Weekend Read Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Reader",
        "m_habit_formed": "Habit Reader",
        "m_consistent_pace": "Steady Reader",
        "m_year_long": "Year-Long Read",
        "m_double_streak": "Double Read Streak",
        "m_streak_recovery": "Streak Recovery",
        "m_daily_minimum": "Daily Minimum",
        "m_winter_streak": "Winter Read Streak",
        "m_summer_streak": "Summer Read Streak",
        "m_morning_streak": "Morning Read Streak",
        "m_night_streak": "Night Read Streak",
        "m_unbreakable": "Unbreakable Reader",
        "m_eternal_flame": "Eternal Reader",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Read Streak",
        "m_completion_streak": "Completion Run",
        "m_rating_streak": "Rating Streak",
        "m_multi_ch_streak": "Multi-Chapter Run",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Read Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manga Critic",
        "m_perfect_ten": "Perfect Ten",
        "m_harsh_critic": "Harsh Critic",
        "m_fair_judge": "Fair Reader",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Full Rating",
        "m_wide_range": "Wide Range",
        "m_controversial": "Controversial",
        "m_consistent_scorer": "Consistent Rater",
        "m_score_sniper": "Score Sniper",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Picky Reader",
        "m_100_rated": "Century Rated",
        "m_500_rated": "Five Hundred",
        "m_mediocre_majority": "Middle Ground",
        "m_rating_spree": "Rating Barrage",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Hunt",
        "m_contrarian": "Contrarian",
        "m_optimist": "Optimist",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Vow",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Fools",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Read",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Friday 13th Read",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thanksgiving Read",
        "m_christmas_read": "Christmas Read",
        "m_new_years_eve": "NYE Read",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Marathon",
        "m_independence_day": "Independence Read",
        "m_culture_day": "Culture Read",
        "m_spring_equinox": "Spring Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Winter Read",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "Every Holiday",
        "m_consecutive_holidays": "Holiday Chain",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number",
        "m_fibonacci": "Fibonacci Read",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven",
        "m_thousand_complete": "Thousand Done",
        "m_nice": "Nice Count",
        "m_power_level_chapters": "Power Level",
        "m_answer_42": "Answer Forty-Two",
        "m_square_number": "Square Number",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Matching Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Synchronicity",
        "m_world_record": "World Record",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time Traveler",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Match",
        "m_chapter_match_date": "Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Unlock",
        "m_meta_collector": "Badge Collector",
        "m_meta_category_starter": "Category Start",
        "m_meta_tier_climber": "Rank Climber",
        "m_meta_tier_max": "Maximum Rank",
        "m_meta_xp_earner": "XP Earner",
        "m_meta_difficulty_easy": "Easy Read",
        "m_meta_difficulty_hard": "Impossible Read",
        "m_meta_unlock_spree": "Unlock Barrage",
        "m_meta_completionist": "Meta Complete",
        "m_meta_diverse": "Diverse Reader",
        "m_meta_dominator": "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#0a0304",
        primary: "#dc323c",
        secondary: "#962832",
        accent: "#d4a843",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/lupin-iii.jpg",
    particleColor: "#c04030",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        gold_coins: { label: "Gold Coins", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        smoke_trails: { label: "Smoke Trails", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        spotlight_sweep: { label: "Spotlight Sweep", maxCount: 6, defaultEnabled: true, defaultIntensity: 50 },
        card_flip: { label: "Card Flip", maxCount: 10, defaultEnabled: true, defaultIntensity: 60 },
    },
    milestoneNames: {
        1:   "Pickpocket",
        5:   "Thief",
        15:  "Heist Planner",
        30:  "Gentleman Thief",
        45:  "World's Most Wanted",
        60:  "ICPO Target",
        80:  "Master Thief",
        100: "Lupin the Third",
    },
}
