import { AnimeThemeConfig } from "./types"
import { GiSawedOffShotgun, GiCherish, GiCoffeeCup, GiTargetArrows, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiDramaMasks, GiHeartKey, GiStarFormation } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const lycorisRecoilTheme: AnimeThemeConfig = {
    id: "lycoris-recoil",
    displayName: "Lycoris Recoil",
    description: "Former DA agent Chisato Nishikigi and reserved marksman Takina Inoue run the LycoReco café by day — and protect the city as elite Lycoris operatives by night, in a thrilling action series wrapped in cherry-blossom warmth.",
    fontFamily: "'Zen Kaku Gothic New', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 190 210",
        "--color-brand-300": "248 150 178",
        "--color-brand-400": "235 100 140",
        "--color-brand-500": "210 58 100",
        "--color-brand-600": "170 28 65",
        "--color-brand-700": "125 10 40",
        "--color-brand-800": "80 0 22",
        "--color-brand-900": "42 0 10",
        "--color-brand-950": "20 0 4",
        "--brand": "210 58 100",
        "--background": "#040101",
        "--paper": "#0e0304",
        "--color-gray-950": "4 1 1",
        "--color-gray-900": "10 4 5",
        "--color-gray-800": "20 8 10",
        "--color-gray-700": "35 14 18",
        "--color-gray-600": "56 24 30",
        "--color-gray-500": "88 45 55",
        "--color-gray-400": "130 80 92",
        "--color-gray-300": "172 120 135",
        "--color-gray-200": "210 162 175",
        "--color-gray-100": "235 198 208",
        "--color-gray-50": "250 228 235",
    },
    sidebarOverrides: {
        "home": { icon: GiCoffeeCup, label: "LycoReco Café" },
        "schedule": { icon: GiAlarmClock, label: "Mission Schedule" },
        "manga": { icon: LuBookOpen, label: "Field Reports" },
        "lists": { icon: GiFlowerEmblem, label: "Target Registry" },
        "discover": { icon: GiBullseye, label: "New Missions" },
        "torrent-list": { icon: GiSawedOffShotgun, label: "Weapon Cache" },
        "debrid": { icon: GiDramaMasks, label: "Covert Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Packages" },
        "enmasse": { icon: GiResize, label: "Joint Operations" },
        "scan-summaries": { icon: TbReportSearch, label: "Mission Logs" },
        "auto-downloader": { icon: LuRss, label: "DA Intel Feed" },
        "community": { icon: GiCherish, label: "Chisato's Circle" },
        "achievements": { icon: GiTrophy, label: "Lycoris Awards" },
        "milestones": { icon: LuFlag, label: "DA Milestones" },
        "search": { icon: FiSearch, label: "Target Search" },
        "notifications": { icon: LuBell, label: "DA Alerts" },
        "theme-manager": { icon: GiPalette, label: "Café Ambiance" },
        "extensions": { icon: BiExtension, label: "DA Modules" },
        "sync": { icon: IoCloudOfflineOutline, label: "Radio Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Takina's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Customer",
        "a_first_complete": "Mission Complete",
        "a_hundred_club": "Hundred Targets",
        "a_time_lord": "Veteran Lycoris",
        "a_anime_collector": "Lycoris Archive",
        "a_library_legend": "DA Database",
        "a_binge_king": "Action Marathon",
        "a_no_sleep": "All-Night Watch",
        "a_marathon_runner": "Chisato's Sprint",
        "a_speed_run": "Takina Speed",
        "a_completionist": "Full Debrief",
        "a_mega_completionist": "DA Master",
        "a_loyal_fan": "Devoted Partner",
        "a_rewatcher": "Mission Replay",
        "a_decade_watcher": "Decade Lycoris",
        "a_genre_action": "Café Action",
        "a_genre_adventure": "City Adventure",
        "a_genre_comedy": "Café Chaos",
        "a_genre_drama": "Lycoris Drama",
        "a_genre_fantasy": "Wish Crystal",
        "a_genre_horror": "None Here",
        "a_genre_romance": "Partners' Bond",
        "a_genre_scifi": "DA Tech",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Mind of Chisato",
        "a_genre_mecha": "None Here",
        "a_critic": "Takina's Review",
        "a_perfect_ten": "Perfect Mission",
        "a_harsh_critic": "DA Standard",
        "a_daily_streak": "Daily Patrol",
        "a_mega_streak": "Endless Duty",
        "a_year_long": "Full Year Lycoris",
        "a_iron_will": "Chisato's Resolve",
        "a_hidden_gem": "Hidden Bloom",
        "a_cult_classic": "Cherry Classic",
        "a_classic_connoisseur": "2022 Fan",
        "a_new_years_resolution": "New Year Patrol",
        "a_christmas_special": "Winter Café",
        "a_meta_tier_max": "True Lycoris",
        "a_meta_completionist": "All Files",
        "a_sequel_chain": "Chisato's Chain",
        "a_zero_to_hero": "New Recruit",
        "a_night_owl": "Night Shift",
        "a_early_bird": "Dawn Patrol",
        "m_first_chapter": "First Report",
        "m_first_complete": "Mission Filed",
        "m_hundred_club": "Hundred Pages",
        "m_binge_king": "Café Reading",
        "m_completionist": "Full Dossier",
        "m_mega_completionist": "DA Expert",
        "m_loyal_reader": "Devoted Agent",
        "m_rereader": "Second Read",
        "m_genre_action": "Action Report",
        "m_genre_adventure": "Field Chapter",
        "m_genre_romance": "Bond Chapter",
        "m_genre_fantasy": "Wish Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "DA Drama",
        "m_genre_scifi": "Tech Report",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Mind Report",
        "m_critic": "Takina's Notes",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Agent Streak",
        "m_year_long": "Year Mission",
        "m_iron_will": "Resolve Chapter",
        "m_hidden_gem": "Hidden File",
        "m_cult_classic": "Classic File",
        "m_mangaka_lover": "Artist Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Lycoris Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Café Art",
        "m_manga_to_anime": "Adapted Mission",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040101",
        primary: "#d23a64",
        secondary: "#aa1c41",
        accent: "#b0b8c8",
    },
    particleColor: "#e878a0",
    backgroundDim: 0.28,
    backgroundBlur: 16,
    particleTypes: {
        cherry_petals: { label: "Cherry Petals", maxCount: 20, defaultEnabled: true, defaultIntensity: 60 },
        golden_sparks: { label: "Golden Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 35 },
    },
    milestoneNames: {
        1: "New Lycoris",
        5: "Café Waitress",
        15: "Field Agent",
        30: "Senior Lycoris",
        50: "Elite Operative",
        75: "DA Legend",
        100: "Chisato's Equal",
    },
}
