import { AnimeThemeConfig } from "./types"
import { GiLanternFlame, GiMagicLamp, GiAncientSword, GiCrown, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiObelisk } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const magiTheme: AnimeThemeConfig = {
    id: "magi",
    displayName: "Magi: The Labyrinth of Magic",
    description: "In a world of dungeons containing ancient treasures, young Magi Aladdin and wanderer Alibaba set out to capture the dungeon Amon — and are drawn into a grand conflict over the fate of the world.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 225 165",
        "--color-brand-300": "248 200 112",
        "--color-brand-400": "235 172 55",
        "--color-brand-500": "215 140 0",
        "--color-brand-600": "172 108 0",
        "--color-brand-700": "130 78 0",
        "--color-brand-800": "88 50 0",
        "--color-brand-900": "50 28 0",
        "--color-brand-950": "26 14 0",
        "--brand": "215 140 0",
        "--background": "#060300",
        "--paper": "#0e0900",
        "--color-gray-950": "6 3 0",
        "--color-gray-900": "14 9 0",
        "--color-gray-800": "26 17 4",
        "--color-gray-700": "44 30 8",
        "--color-gray-600": "68 50 18",
        "--color-gray-500": "105 80 38",
        "--color-gray-400": "148 122 78",
        "--color-gray-300": "186 163 120",
        "--color-gray-200": "214 195 160",
        "--color-gray-100": "232 220 194",
        "--color-gray-50": "245 238 225",
    },
    sidebarOverrides: {
        "home": { icon: GiObelisk, label: "Dungeon Gate" },
        "schedule": { icon: GiAlarmClock, label: "Dungeon Schedule" },
        "manga": { icon: LuBookOpen, label: "Magi Files" },
        "lists": { icon: GiMagicLamp, label: "Djinn Registry" },
        "discover": { icon: GiBullseye, label: "Dungeon Hunt" },
        "torrent-list": { icon: GiLanternFlame, label: "Magic Cache" },
        "debrid": { icon: GiCrown, label: "King Store" },
        "unmatched": { icon: GiAncientSword, label: "Unknown Dungeons" },
        "enmasse": { icon: GiResize, label: "Kingdom Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Dungeon Reports" },
        "auto-downloader": { icon: LuRss, label: "Magic Feed" },
        "community": { icon: GiMagicLamp, label: "Dungeon Conquerors" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Djinn Alerts" },
        "achievements": { icon: GiTrophy, label: "King Vessels" },
        "milestones": { icon: LuFlag, label: "Djinn Goals" },
        "theme-manager": { icon: GiPalette, label: "Desert Colors" },
        "extensions": { icon: BiExtension, label: "Djinn Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Rukh Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Magi Settings" },
    },
    achievementNames: {
        "a_first_episode": "Djinn Equip",
        "a_first_complete": "King Vessel",
        "a_hundred_club": "Hundred Dungeons",
        "a_time_lord": "Dungeon Veteran",
        "a_anime_collector": "Djinn Collection",
        "a_library_legend": "Solomon's Archives",
        "a_binge_king": "Dungeon Marathon",
        "a_no_sleep": "All-Night Conquest",
        "a_marathon_runner": "Magic Carpet Ride",
        "a_speed_run": "Aladdin's Flight",
        "a_completionist": "All Dungeons",
        "a_mega_completionist": "Ohtaka Master",
        "a_loyal_fan": "Aladdin's Friend",
        "a_rewatcher": "Dungeon Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Djinn Battle",
        "a_genre_adventure": "Desert Journey",
        "a_genre_comedy": "Aladdin's Curiosity",
        "a_genre_drama": "Alibaba's Kingdom",
        "a_genre_fantasy": "Magic World",
        "a_genre_horror": "Dark Rukh",
        "a_genre_romance": "Morgiana's Heart",
        "a_genre_scifi": "Rukh Science",
        "a_genre_supernatural": "Djinn Power",
        "a_genre_psychological": "King's Burden",
        "a_genre_mecha": "None Here",
        "a_critic": "King Judge",
        "a_perfect_ten": "Amon Equip",
        "a_harsh_critic": "Scheherazade's Review",
        "a_daily_streak": "Daily Quest",
        "a_mega_streak": "Endless Adventure",
        "a_year_long": "Year of Magic",
        "a_iron_will": "Alibaba's Vow",
        "a_hidden_gem": "Hidden Dungeon",
        "a_cult_classic": "Ohtaka Classic",
        "a_classic_connoisseur": "2009 Fan",
        "a_new_years_resolution": "New Year Quest",
        "a_christmas_special": "Desert Winter",
        "a_meta_tier_max": "Magi",
        "a_meta_completionist": "All King Vessels",
        "a_sequel_chain": "Kingdom of Magic",
        "a_zero_to_hero": "Wanderer to King",
        "a_night_owl": "Night Quest",
        "a_early_bird": "Desert Dawn",
        "m_first_chapter": "First Dungeon",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Magic Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Magi Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Desert Return",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Morgiana Chapter",
        "m_genre_fantasy": "Magic Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_drama": "Kingdom Chapter",
        "m_genre_scifi": "Rukh Chapter",
        "m_genre_supernatural": "Djinn Chapter",
        "m_genre_psychological": "Burden Depth",
        "m_critic": "Dungeon Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Desert Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "King Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Arabian Classic",
        "m_mangaka_lover": "Ohtaka Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Magi Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Arabian Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Desert Dawn Read",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060300",
        primary: "#d78c00",
        secondary: "#826000",
        accent: "#8060d0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/magi.jpg",
    particleColor: "#f0b820",
    backgroundDim: 0.32,
    backgroundBlur: 16,
    particleTypes: {
        rukh_birds: { label: "Rukh Birds", maxCount: 18, defaultEnabled: true, defaultIntensity: 60 },
        desert_sand: { label: "Desert Sand", maxCount: 15, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1: "Wanderer",
        5: "Aladdin",
        15: "Dungeon Conqueror",
        30: "King Vessel",
        50: "Djinn Equip",
        75: "Solomon's Proxy",
        100: "Magi",
    },
}
