import { AnimeThemeConfig } from "./types"
import { GiRobotLeg, GiLaserWarning, GiMissileSwarm, GiRadarCrossSection, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiPadlock } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const mazingerZTheme: AnimeThemeConfig = {
    id: "mazinger-z",
    displayName: "Mazinger Z",
    description: "Pilot the first super robot — iron armor, rocket punches, and photon energy against the armies of Dr. Hell. You are the devil or god — it is your choice.",
    fontFamily: "'Russo One', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Russo+One&display=swap",
    cssVars: {
        "--color-brand-200": "255 155 155",
        "--color-brand-300": "248 105 105",
        "--color-brand-400": "235 65 65",
        "--color-brand-500": "218 28 28",
        "--color-brand-600": "182 18 18",
        "--color-brand-700": "142 12 12",
        "--color-brand-800": "100 8 8",
        "--color-brand-900": "62 4 4",
        "--color-brand-950": "36 2 2",
        "--brand": "218 28 28",
        "--background": "#090505",
        "--paper": "#130808",
        "--color-gray-950": "9 5 5",
        "--color-gray-900": "18 10 10",
        "--color-gray-800": "32 20 20",
        "--color-gray-700": "52 34 34",
        "--color-gray-600": "78 54 54",
        "--color-gray-500": "115 85 85",
        "--color-gray-400": "156 126 126",
        "--color-gray-300": "190 165 165",
        "--color-gray-200": "216 198 198",
        "--color-gray-100": "234 222 222",
        "--color-gray-50": "247 243 243",
    },
    sidebarOverrides: {
        "home": { icon: GiRobotLeg, label: "Photon Lab" },
        "schedule": { icon: GiAlarmClock, label: "Scramble Timer" },
        "manga": { icon: LuBookOpen, label: "Research Files" },
        "lists": { icon: GiPadlock, label: "Mission Roster" },
        "discover": { icon: GiBullseye, label: "Enemy Recon" },
        "torrent-list": { icon: GiMissileSwarm, label: "Rocket Punch Cache" },
        "debrid": { icon: GiLaserWarning, label: "Photon Energy" },
        "unmatched": { icon: GiRadarCrossSection, label: "Lost Signals" },
        "enmasse": { icon: GiResize, label: "Fortress Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "HQ Transmissions" },
        "community": { icon: GiRobotLeg, label: "Robot Corps" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Scramble Alerts" },
        "achievements": { icon: GiTrophy, label: "Hero Medals" },
        "milestones": { icon: LuFlag, label: "Pilot Goals" },
        "theme-manager": { icon: GiPalette, label: "Armor Design" },
        "extensions": { icon: BiExtension, label: "Weapon Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "Lab Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Pilder Controls" },
    },
    achievementNames: {
        "a_first_episode": "First Launch",
        "a_first_complete": "Mission Complete",
        "a_hundred_club": "Hundred Sorties",
        "a_time_lord": "Iron Veteran",
        "a_anime_collector": "Arsenal Collected",
        "a_library_legend": "Lab Archives",
        "a_binge_king": "Continuous Sortie",
        "a_no_sleep": "All-Night Defense",
        "a_marathon_runner": "Endless Battle",
        "a_speed_run": "Quick Launch",
        "a_completionist": "Full Mission Clear",
        "a_mega_completionist": "Supreme Defender",
        "a_loyal_fan": "Loyal Pilot",
        "a_rewatcher": "Replay Battles",
        "a_decade_watcher": "Decade Defender",
        "a_genre_action": "Combat Specialist",
        "a_genre_adventure": "Uncharted Territory",
        "a_genre_comedy": "Kouji's Antics",
        "a_genre_drama": "Heart of Steel",
        "a_genre_fantasy": "Super Robot World",
        "a_genre_horror": "Dr. Hell's Terror",
        "a_genre_romance": "Sayaka's Strength",
        "a_genre_scifi": "Photon Science",
        "a_genre_supernatural": "Mechanical Marvel",
        "a_genre_psychological": "Pilot's Will",
        "a_genre_mecha": "Mecha Pioneer",
        "a_critic": "Steel Judge",
        "a_perfect_ten": "Perfect Score",
        "a_harsh_critic": "Uncompromising Eye",
        "a_daily_streak": "Daily Patrol",
        "a_mega_streak": "Iron Streak",
        "a_year_long": "Year on Guard",
        "a_iron_will": "Iron Will",
        "a_hidden_gem": "Hidden Weapon",
        "a_cult_classic": "Giant Robot Legacy",
        "a_classic_connoisseur": "70s Classic Fan",
        "a_new_years_resolution": "New Year Launch",
        "a_christmas_special": "Holiday Sortie",
        "a_meta_tier_max": "Max Power Level",
        "a_meta_completionist": "Complete Arsenal",
        "a_sequel_chain": "Sequel Cleared",
        "a_zero_to_hero": "Coal Boy to Pilot",
        "a_night_owl": "Night Patrol",
        "a_early_bird": "Dawn Scramble",
        "m_first_chapter": "First Page",
        "m_first_complete": "Volume Complete",
        "m_hundred_club": "Century Chapters",
        "m_binge_king": "Marathon Reader",
        "m_completionist": "Full Collection",
        "m_mega_completionist": "Master Archivist",
        "m_loyal_reader": "Loyal Reader",
        "m_rereader": "Reread Veteran",
        "m_genre_action": "Action Fan",
        "m_genre_adventure": "Explorer",
        "m_genre_romance": "Heart Reader",
        "m_genre_fantasy": "Fantasy World",
        "m_genre_horror": "Dark Tales",
        "m_genre_drama": "Drama Reader",
        "m_genre_scifi": "Sci-Fi Lover",
        "m_genre_supernatural": "Super Power",
        "m_genre_psychological": "Deep Reader",
        "m_critic": "Manga Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Marathon Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Dedication",
        "m_hidden_gem": "Hidden Find",
        "m_cult_classic": "Classic Work",
        "m_mangaka_lover": "Artist Fan",
        "m_source_material_fan": "Source First",
        "m_meta_tier_max": "Max Collection",
        "m_meta_completionist": "Complete Reader",
        "m_art_appreciator": "Art Admirer",
        "m_manga_to_anime": "Source to Screen",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#090505",
        primary: "#da1c1c",
        secondary: "#8e0c0c",
        accent: "#b87818",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/mazinger-z.jpg",
    particleColor: "#da1c1c",
    backgroundDim: 0.35,
    backgroundBlur: 20,
    particleTypes: {
        rocket_punches: { label: "Rocket Punches", maxCount: 8, defaultEnabled: true, defaultIntensity: 60 },
        photon_sparks: { label: "Photon Sparks", maxCount: 15, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1: "Pilot Trainee",
        5: "Kouji Kabuto",
        15: "Rocket Punch",
        30: "Iron Castle",
        50: "Boss Borot",
        75: "Great Mazinger",
        100: "Grendizer Legend",
    },
}
