import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiSwordWound,
    GiChainedHeart,
    GiMuscleUp,
    GiCrossedSwords,
    GiHorseHead,
    GiFist,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const miraiNikkiTheme: AnimeThemeConfig = {
    id: "mirai-nikki",
    displayName: "Mirai Nikki",
    description: "The survival game begins. Wield your future diary, outwit the other holders, and claim the throne of Deus Ex Machina — if Yuno lets you.",
    fontFamily: "'Caveat', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&display=swap",
    cssVars: {
        // Brand → yandere pink
        "--color-brand-200": "255 170 195",
        "--color-brand-300": "255 130 165",
        "--color-brand-400": "255 90 130",
        "--color-brand-500": "255 50 100",
        "--color-brand-600": "210 35 80",
        "--color-brand-700": "165 25 60",
        "--color-brand-800": "120 15 45",
        "--color-brand-900": "80 8 30",
        "--color-brand-950": "45 3 15",
        "--brand": "255 50 100",
        // Dark crimson-black background
        "--background": "#0a0306",
        "--paper": "#140610",
        "--color-gray-950": "10 3 6",
        "--color-gray-900": "20 6 16",
        "--color-gray-800": "35 14 26",
        "--color-gray-700": "55 25 40",
        "--color-gray-600": "80 40 58",
        "--color-gray-500": "110 62 82",
        "--color-gray-400": "145 95 118",
        "--color-gray-300": "180 135 155",
        "--color-gray-200": "210 175 190",
        "--color-gray-100": "232 210 220",
        "--color-gray-50": "245 235 240",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Yukiteru's Room" },
        "schedule": { icon: GiAlarmClock, label: "Future Entries" },
        "manga": { icon: LuBookOpen, label: "Diary Pages" },
        "lists": { icon: GiCrossedSwords, label: "Holder Roster" },
        "discover": { icon: GiBullseye, label: "Survival Game" },
        "torrent-list": { icon: GiAnvilImpact, label: "Dead End Drops" },
        "debrid": { icon: GiHorseHead, label: "Escape Routes" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Holders" },
        "enmasse": { icon: GiResize, label: "Mass Prediction" },
        "scan-summaries": { icon: TbReportSearch, label: "Diary Scans" },
        "auto-downloader": { icon: LuRss, label: "Future Signals" },
        "community": { icon: GiEagleEmblem, label: "Causality Hub" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Dead End Alerts" },
        "achievements": { icon: GiTrophy, label: "Survival Trophies" },
        "theme-manager": { icon: GiPalette, label: "Diary Covers" },
        "extensions": { icon: BiExtension, label: "Diary Plugins" },
        "sync": { icon: IoCloudOfflineOutline, label: "Causality Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Deus Settings" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Entry",
        "a_episode_counter": "Diary Counter",
        "a_episode_titan": "Titan Entry",
        "a_hours_invested": "Hours Predicted",
        "a_time_lord": "Time Lord",
        "a_anime_collector": "Diary Collector",
        "a_library_legend": "Archive Legend",
        "a_first_complete": "Game Cleared",
        "a_hundred_club": "Hundred Entries",
        "a_first_day": "First Prediction",
        "a_first_rating": "First Judgment",
        "a_ten_thousand_min": "Ten Thousand",
        "a_season_veteran": "Veteran Holder",
        "a_year_explorer": "Year Foretold",
        "a_century_watcher": "Century Watcher",
        "a_five_hundred_eps": "Five Hundred",
        "a_thousand_eps": "Thousand Fates",
        "a_watching_ten": "Ten Diaries",
        "a_ptw_hoarder": "Fate Hoarder",
        "a_dropped_honesty": "Honest Retreat",
        "a_five_thousand_eps": "Five Thousand",
        "a_ten_completed": "Ten Cleared",
        "a_fifty_completed": "Fifty Survived",
        "a_five_hundred_completed": "Five Hundred Won",
        "a_mean_score_tracker": "Average Fate",
        "a_unique_studios": "Allied Holders",
        "a_days_spent_watching": "Days Survived",
        "a_all_status": "All Statuses",
        "a_first_favorite": "First Obsession",
        "a_favorites_collector": "Obsession Hoard",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Yandere Binge",
        "a_marathon_runner": "Diary Marathon",
        "a_weekend_warrior": "Weekend Holder",
        "a_non_stop": "Relentless Love",
        "a_one_more_episode": "One More Entry",
        "a_speed_run": "Speed Prediction",
        "a_double_feature": "Double Entry",
        "a_triple_threat": "Triple Threat",
        "a_five_a_day": "Five Entries",
        "a_back_to_back": "Back to Back",
        "a_seasonal_binge": "Seasonal Purge",
        "a_cour_crusher": "Cour Crushed",
        "a_half_day_watch": "Half-Day Diary",
        "a_full_day_watch": "Full-Day Vigil",
        "a_power_weekend": "Power Weekend",
        "a_binge_king": "Binge Sovereign",
        "a_no_sleep": "Sleepless Yuno",
        "a_entire_season": "Rapid Prophecy",
        "a_seven_day_challenge": "Seven-Day Game",
        "a_hundred_day_binge": "Hundred-Day Hunt",
        "a_genre_binge": "Genre Bloodbath",
        "a_studio_binge": "Studio Stalking",
        "a_season_sweep": "Season Swept",
        "a_forty_eight_hour": "Forty-Eight Hours",
        "a_ep_counter_day": "Daily Entries",
        "a_multi_series_binge": "Multi-Diary Binge",
        "a_midnight_binge": "Midnight Stalking",
        "a_new_year_binge": "New Year Hunt",

        // ── ANIME GENRES ──
        "a_genre_action": "Action Diary",
        "a_genre_adventure": "Escape Route",
        "a_genre_comedy": "Comic Relief",
        "a_genre_drama": "Yuno's Tears",
        "a_genre_fantasy": "Deus Realm",
        "a_genre_horror": "Horror Entry",
        "a_genre_mystery": "Mystery Holder",
        "a_genre_romance": "Yandere Love",
        "a_genre_scifi": "Future Tech",
        "a_genre_sol": "Peaceful Days",
        "a_genre_sports": "Dart Throw",
        "a_genre_supernatural": "Divine Power",
        "a_genre_thriller": "Survival Thrill",
        "a_genre_mecha": "Mecha Diary",
        "a_genre_music": "Yuno's Melody",
        "a_genre_psychological": "Broken Psyche",
        "a_genre_ecchi": "Forbidden Page",
        "a_genre_mahou_shoujo": "Magical Holder",
        "a_tag_isekai": "Parallel World",
        "a_tag_harem": "Holder Bonds",
        "a_tag_bl": "Fated Pair",
        "a_tag_gl": "Diary Sisters",
        "a_tag_historical": "Past Timeline",
        "a_tag_military": "Tactical Diary",
        "a_tag_school": "School Days",
        "a_tag_martial_arts": "Combat Entry",
        "a_tag_vampire": "Blood Diary",
        "a_tag_samurai": "Blade Holder",
        "a_tag_space": "Cosmic Fate",
        "a_tag_parody": "Parody Entry",
        "a_tag_idol": "Idol Holder",
        "a_tag_post_apocalyptic": "Dead World",
        "a_tag_cyberpunk": "Cyber Diary",
        "a_tag_shounen": "Young Holder",
        "a_tag_seinen": "Dark Prophecy",
        "a_tag_shoujo": "Love Letter",
        "a_tag_josei": "Mature Entry",
        "a_tag_survival": "Survival Instinct",

        // ── ANIME COMPLETION ──
        "a_completionist": "Game Complete",
        "a_mega_completionist": "Mega Victor",
        "a_completion_rate_50": "Halfway Dead",
        "a_completion_rate_75": "Final Four",
        "a_completion_rate_90": "Endgame Near",
        "a_no_drop": "No Abandonment",
        "a_long_runner_complete": "Long Survival",
        "a_sequel_chain": "Sequel Chain",
        "a_clean_list": "Clean Record",
        "a_from_ptw": "Fate Accepted",
        "a_rewatch_master": "Rewind Time",
        "a_short_complete": "Quick Kill",
        "a_same_day_start_finish": "Same-Day Clear",
        "a_revival": "Second World",
        "a_zero_to_hero": "Zero to God",
        "a_five_genre_complete": "Five Genres",
        "a_full_franchise": "Full Dossier",
        "a_batch_complete": "Batch Purged",
        "a_paused_to_done": "Resumed Fate",
        "a_completion_spree": "Spree Killer",
        "a_multi_rewatch": "Multi-Rewind",
        "a_dropped_recovery": "Fate Recovered",
        "a_ten_perfect_scores": "Ten Perfects",
        "a_seasonal_clear": "Season Purged",
        "a_complete_genre_span": "Genre Sweep",
        "a_monthly_completions": "Monthly Kills",
        "a_yearly_completions": "Yearly Victor",
        "a_rapid_complete": "Rapid Finish",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Stalker",
        "a_studio_devotee": "Studio Devotee",
        "a_rewatcher": "Diary Reread",
        "a_triple_rewatch": "Triple Rewatch",
        "a_annual_tradition": "Annual Ritual",
        "a_director_fan": "Director's Pawn",
        "a_voice_actor_fan": "Voice Obsessed",
        "a_ost_lover": "Blood Teller",
        "a_source_reader": "Source Diary",
        "a_waiting_weekly": "Weekly Wait",
        "a_childhood_revisit": "Childhood Diary",
        "a_saga_tracker": "Saga Tracked",
        "a_genre_loyalty": "Genre Loyalty",
        "a_decade_watcher": "Decade Holder",
        "a_adaptation_hunter": "Adaptation Hunt",
        "a_original_anime_fan": "Original Fan",
        "a_long_commitment": "Long Obsession",
        "a_perfect_attendance": "Perfect Record",
        "a_favorite_studio_5": "Five Studios",
        "a_complete_catalog": "Full Catalog",
        "a_franchise_collector": "Franchise Hoard",
        "a_airing_follower": "Airing Tracked",
        "a_genre_master": "Genre Mastered",
        "a_staff_follower": "Staff Stalked",
        "a_multi_season_fan": "Multi-Season",
        "a_format_diversity": "Format Variety",
        "a_year_dedication": "Year Devoted",
        "a_season_dedication": "Season Devoted",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Genre Scout",
        "a_studio_hopper": "Studio Hopper",
        "a_tag_explorer": "Tag Explorer",
        "a_decade_hopper": "Decade Leap",
        "a_hidden_gem": "Hidden Diary",
        "a_popular_taste": "Popular Pick",
        "a_retro_appreciator": "Retro Entry",
        "a_modern_viewer": "Modern Holder",
        "a_cross_demographic": "Cross-Demographic",
        "a_underdog_fan": "Underdog Bet",
        "a_variety_week": "Varied Week",
        "a_foreign_cinema": "Foreign Intel",
        "a_classic_connoisseur": "Classic Fate",
        "a_every_season": "Every Season",
        "a_award_winner": "Award Winner",
        "a_niche_explorer": "Niche Found",
        "a_global_anime": "Global Entry",
        "a_cult_classic": "Cult Diary",
        "a_random_pick": "Random Fate",
        "a_new_genre_month": "New Genre",
        "a_seasonal_completionist": "Seasonal Clear",
        "a_unpopular_opinion": "Lone Opinion",
        "a_top_rated_viewer": "Top Rated",
        "a_source_variety": "Source Varied",
        "a_low_score_brave": "Brave Entry",
        "a_upcoming_watcher": "Upcoming Fate",
        "a_short_series_explorer": "Short Series",
        "a_long_series_explorer": "Long Series",

        // ── ANIME TIME ──
        "a_night_owl": "Night Stalker",
        "a_early_bird": "Dawn Diary",
        "a_lunch_break": "Lunch Entry",
        "a_golden_hour": "Golden Hour",
        "a_four_am_club": "4 AM Yandere",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Vow",
        "a_midnight_premiere": "Midnight Fate",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Entry",
        "a_prime_time": "Prime Diary",
        "a_workday_watcher": "Workday Watch",
        "a_sunday_marathon": "Sunday Game",
        "a_rainy_day": "Rainy Diary",
        "a_morning_routine": "Morning Entry",
        "a_night_shift": "Night Vigil",
        "a_twilight_zone": "Twilight Fate",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Keeper",
        "a_weekend_binge_hours": "Weekend Binge",
        "a_late_night_regular": "Late Night",
        "a_sunrise_watcher": "Sunrise Watch",
        "a_holiday_watcher": "Holiday Entry",
        "a_every_day_of_week": "Every Day",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Alliance",
        "a_party_host": "Game Master",
        "a_social_butterfly": "Social Holder",
        "a_group_binge": "Group Survival",
        "a_party_regular": "Regular Ally",
        "a_sync_viewer": "Synced Diaries",
        "a_commentator": "Commentator",
        "a_party_marathon": "Party Marathon",
        "a_full_house": "Full Roster",
        "a_community_pillar": "Pillar Holder",
        "a_watch_party_streak": "Party Streak",
        "a_diverse_party": "Diverse Alliance",
        "a_late_night_party": "Late Night Party",
        "a_party_veteran": "Veteran Ally",
        "a_genre_party": "Genre Party",
        "a_weekly_party": "Weekly Pact",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Fate Advisor",
        "a_party_completionist": "Party Clear",
        "a_social_scorer": "Social Score",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Fibonacci Fate",
        "a_palindrome_day": "Palindrome Day",
        "a_binary_day": "Binary Entry",
        "a_full_moon": "Full Moon",
        "a_leap_year": "Leap Year",
        "a_time_traveler": "Time Leaper",
        "a_genre_clash": "Genre Clash",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Won",
        "a_pi_episodes": "Pi Episodes",
        "a_synchronicity": "Synchronicity",
        "a_world_record": "World Record",
        "a_nice": "Nice Count",
        "a_power_level": "God Power",
        "a_answer_42": "Answer Forty-Two",
        "a_square_number": "Square Entry",
        "a_prime_count": "Prime Count",
        "a_matching_date": "Matching Date",
        "a_century_episode": "Century Entry",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Matched",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Diary",
        "a_movie_buff": "Movie Entry",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Entry",
        "a_short_king": "Short King",
        "a_variety_pack": "Variety Pack",
        "a_film_festival": "Film Festival",
        "a_music_video": "Music Diary",
        "a_tv_short": "Quick Entry",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Diary Anthology",
        "a_mini_series": "Mini Diary",
        "a_theatrical": "Theatrical Fate",
        "a_format_master": "Format Master",
        "a_long_movie": "Long Feature",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "CM Watcher",
        "a_pv_collector": "PV Collector",
        "a_format_balance": "Format Balance",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Film",
        "a_recap_watcher": "Recap Entry",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Stalking",
        "a_mega_streak": "Mega Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Watch",
        "a_comeback": "Yuno's Return",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Steady Pace",
        "a_year_long": "Year-Long Game",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Revived",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Hunt",
        "a_summer_streak": "Summer Hunt",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable Bond",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Episode",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Diary Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Harsh Judge",
        "a_fair_judge": "Fair Verdict",
        "a_generous_spirit": "Kind Heart",
        "a_score_all": "All Scored",
        "a_wide_range": "Wide Range",
        "a_controversial": "Controversial",
        "a_consistent_scorer": "Consistent Score",
        "a_score_sniper": "Score Sniper",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Picky Holder",
        "a_100_rated": "Hundred Rated",
        "a_500_rated": "Five Hundred",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Hunt",
        "a_contrarian": "Contrarian",
        "a_optimist": "Blind Faith",
        "a_score_distributor": "Score Spread",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Vow",
        "a_valentines_weeb": "Yandere Valentine",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Prank",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "Star Wars Day",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday Thirteenth",
        "a_halloween_spirit": "Halloween Dead",
        "a_thanksgiving_binge": "Thankful Binge",
        "a_christmas_special": "Bloody Christmas",
        "a_new_years_eve": "Eve Countdown",
        "a_birthday_watch": "Birthday Entry",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Freedom Day",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Equinox",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Day",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anime Birthday",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Holiday Streak",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Awakening",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Start",
        "a_meta_tier_climber": "Tier Climber",
        "a_meta_tier_max": "Maximum Tier",
        "a_meta_xp_earner": "XP Earned",
        "a_meta_difficulty_easy": "Easy Mode",
        "a_meta_difficulty_hard": "Dead End",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Complete",
        "a_meta_diverse": "Diverse Meta",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page",
        "m_chapter_counter": "Page Counter",
        "m_chapter_titan": "Titan Chapter",
        "m_reading_hours": "Hours Reading",
        "m_reading_time_lord": "Reading Lord",
        "m_manga_collector": "Manga Hoarder",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Finished",
        "m_hundred_club": "Hundred Pages",
        "m_first_day": "Reading Start",
        "m_first_rating": "First Rating",
        "m_ten_thousand_pages": "Ten Thousand",
        "m_volume_collector": "Volume Hoarder",
        "m_year_explorer": "Year of Pages",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred",
        "m_thousand_ch": "Thousand Read",
        "m_reading_ten": "Ten at Once",
        "m_ptr_hoarder": "Backlog Hoard",
        "m_dropped_honesty": "Dropped Honest",
        "m_season_reader": "Season Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand",
        "m_ten_completed": "Ten Finished",
        "m_fifty_completed": "Fifty Finished",
        "m_five_hundred_completed": "Five Hundred Done",
        "m_mean_score_tracker": "Mean Score",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Favorites Hoard",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reader",
        "m_marathon_reader": "Reading Marathon",
        "m_weekend_reader": "Weekend Pages",
        "m_non_stop_reading": "Non-Stop Read",
        "m_one_more_chapter": "One More Page",
        "m_speed_read": "Speed Reader",
        "m_double_story": "Double Story",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five Daily",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Devoured",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Read",
        "m_full_day_read": "Full-Day Read",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge Ruler",
        "m_no_sleep_read": "Sleepless Read",
        "m_full_series_rush": "Series Rushed",
        "m_seven_day_challenge": "Seven-Day Read",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rushed",
        "m_series_sweep": "Series Swept",
        "m_genre_binge": "Genre Devoured",
        "m_author_binge": "Author Obsessed",
        "m_chapter_counter_day": "Daily Chapters",
        "m_multi_series_binge": "Multi-Series",
        "m_midnight_binge": "Midnight Read",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "Forty-Eight Hour",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Pages",
        "m_genre_adventure": "Adventure Read",
        "m_genre_comedy": "Comedy Pages",
        "m_genre_drama": "Drama Diary",
        "m_genre_fantasy": "Fantasy Realm",
        "m_genre_horror": "Horror Pages",
        "m_genre_mystery": "Mystery Read",
        "m_genre_romance": "Romance Diary",
        "m_genre_scifi": "Sci-Fi Pages",
        "m_genre_sol": "Peaceful Read",
        "m_genre_sports": "Sports Pages",
        "m_genre_supernatural": "Divine Pages",
        "m_genre_thriller": "Thriller Diary",
        "m_genre_psychological": "Psyche Diary",
        "m_genre_isekai": "Isekai Pages",
        "m_genre_shounen": "Shounen Read",
        "m_genre_ecchi": "Forbidden Read",
        "m_genre_mahou_shoujo": "Magic Pages",
        "m_genre_mecha": "Mecha Read",
        "m_genre_music": "Music Pages",
        "m_tag_isekai_new": "New World",
        "m_tag_harem": "Harem Pages",
        "m_tag_bl": "BL Diary",
        "m_tag_gl": "GL Diary",
        "m_tag_historical": "History Pages",
        "m_tag_military": "Military Read",
        "m_tag_school": "School Diary",
        "m_tag_martial_arts": "Combat Pages",
        "m_tag_vampire": "Vampire Diary",
        "m_tag_samurai": "Samurai Read",
        "m_tag_space": "Space Pages",
        "m_tag_parody": "Parody Diary",
        "m_tag_idol": "Idol Pages",
        "m_tag_post_apocalyptic": "Dead World Read",
        "m_tag_cyberpunk": "Cyber Pages",
        "m_tag_shoujo": "Shoujo Diary",
        "m_tag_survival": "Survival Read",
        "m_tag_cooking": "Cooking Diary",
        "m_tag_medical": "Medical Pages",
        "m_tag_villainess": "Villainess Diary",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Complete",
        "m_mega_completionist": "Mega Reader",
        "m_completion_rate_50": "Halfway Read",
        "m_completion_rate_75": "Almost Done",
        "m_completion_rate_90": "Final Pages",
        "m_no_drop": "No Drops",
        "m_long_runner_complete": "Long Runner",
        "m_sequel_chain": "Sequel Chained",
        "m_clean_list": "Clean List",
        "m_from_ptr": "Plan Executed",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Finish",
        "m_revival": "Reading Revival",
        "m_zero_to_hundred": "Zero to Hero",
        "m_five_genre_complete": "Five Genres",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Cleared",
        "m_paused_to_done": "Pause Resumed",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi-Reread",
        "m_dropped_recovery": "Drop Recovered",
        "m_ten_perfect_scores": "Ten Perfects",
        "m_complete_genre_span": "Genre Span",
        "m_monthly_completions": "Monthly Done",
        "m_yearly_completions": "Yearly Done",
        "m_rapid_complete": "Rapid Finish",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Lover",
        "m_rereader": "Diary Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Devotee",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Fan",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyal",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Fav Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Franchise Hoard",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Mastered",
        "m_multi_series_author": "Multi-Author",
        "m_format_diversity": "Format Diverse",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Tracked",
        "m_genre_loyalty_50": "Fifty Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Scout",
        "m_decade_hopper": "Decade Hopper",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Taste",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross-Demographic",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Variety Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Taste",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Niche Explorer",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre",
        "m_year_completionist": "Year Complete",
        "m_unpopular_opinion": "Lone Opinion",
        "m_top_rated_reader": "Top Rated",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Manga",
        "m_long_manga_explorer": "Long Manga",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Lunch Pages",
        "m_commute_reader": "Commute Read",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All Hours",
        "m_prime_time_reader": "Prime Reader",
        "m_workday_reader": "Workday Read",
        "m_sunday_read": "Sunday Read",
        "m_morning_routine": "Morning Pages",
        "m_night_shift_reader": "Night Shift",
        "m_seasonal_premier_read": "New Release",
        "m_clock_collector": "Clock Reader",
        "m_late_night_horror": "Late Horror",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Reader",
        "m_dawn_reader": "Dawn Pages",
        "m_twilight_reader": "Twilight Read",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Hours",
        "m_late_night_regular": "Late Regular",
        "m_sunrise_reader": "Sunrise Read",
        "m_every_day_of_week": "Every Day",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Read",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Lover",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Read",
        "m_adaptation_reader": "Adaptation Read",
        "m_longstrip_reader": "Longstrip Read",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Story",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Read",
        "m_cross_media": "Cross-Media",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collab Reader",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Reading",
        "m_mega_streak": "Mega Reading",
        "m_weekly_warrior": "Weekly Reader",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader's Return",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Reader",
        "m_habit_formed": "Habit Formed",
        "m_consistent_pace": "Steady Reading",
        "m_year_long": "Year-Long Read",
        "m_double_streak": "Double Streak",
        "m_streak_recovery": "Streak Revived",
        "m_daily_minimum": "Daily Pages",
        "m_winter_streak": "Winter Reading",
        "m_summer_streak": "Summer Reading",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Streak",
        "m_unbreakable": "Unbreakable",
        "m_eternal_flame": "Eternal Diary",
        "m_chapter_a_day": "Chapter Daily",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Done Streak",
        "m_rating_streak": "Rating Streak",
        "m_multi_ch_streak": "Multi-Chapter",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manga Critic",
        "m_perfect_ten": "Perfect Ten",
        "m_harsh_critic": "Harsh Reader",
        "m_fair_judge": "Fair Judge",
        "m_generous_spirit": "Kind Reader",
        "m_score_all": "All Scored",
        "m_wide_range": "Wide Range",
        "m_controversial": "Controversial",
        "m_consistent_scorer": "Steady Scorer",
        "m_score_sniper": "Score Sniper",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Picky Reader",
        "m_100_rated": "Hundred Rated",
        "m_500_rated": "Five Hundred",
        "m_mediocre_majority": "Middle Ground",
        "m_rating_spree": "Rating Spree",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Hunt",
        "m_contrarian": "Contrarian",
        "m_optimist": "Optimist Reader",
        "m_score_distributor": "Score Spread",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Read",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Prank",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Read",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Friday Thirteenth",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thankful Read",
        "m_christmas_read": "Christmas Read",
        "m_new_years_eve": "Eve Reading",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Reading",
        "m_independence_day": "Freedom Read",
        "m_culture_day": "Culture Read",
        "m_spring_equinox": "Spring Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Read",
        "m_winter_solstice": "Winter Read",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "Every Holiday",
        "m_consecutive_holidays": "Holiday Chain",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number",
        "m_fibonacci": "Fibonacci Read",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven",
        "m_thousand_complete": "Thousand Done",
        "m_nice": "Nice Count",
        "m_power_level_chapters": "Power Level",
        "m_answer_42": "Answer Forty-Two",
        "m_square_number": "Square Number",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Matching Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Synchronicity",
        "m_world_record": "World Record",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time Traveler",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Matched",
        "m_chapter_match_date": "Date Matched",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Unlock",
        "m_meta_collector": "Badge Collector",
        "m_meta_category_starter": "Category Start",
        "m_meta_tier_climber": "Tier Climber",
        "m_meta_tier_max": "Maximum Tier",
        "m_meta_xp_earner": "XP Earned",
        "m_meta_difficulty_easy": "Easy Read",
        "m_meta_difficulty_hard": "Hard Read",
        "m_meta_unlock_spree": "Unlock Spree",
        "m_meta_completionist": "Meta Complete",
        "m_meta_diverse": "Diverse Meta",
        "m_meta_dominator": "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#0a0306",
        primary: "#ff3264",
        secondary: "#d12350",
        accent: "#ff6b8a",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/mirai-nikki.png",
    particleColor: "#d040a0",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        diary_pages: { label: "Diary Pages", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        blood_splatter: { label: "Blood Splatter", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        clock_gears: { label: "Clock Gears", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
        heart_shards: { label: "Heart Shards", maxCount: 10, defaultEnabled: true, defaultIntensity: 60 },
    },
    milestoneNames: {
        1:   "First",
        5:   "Diary Holder",
        15:  "Alliance",
        30:  "Survivor",
        45:  "Yuno's Love",
        60:  "Dead End",
        80:  "God Candidate",
        100: "Deus",
    },
}
