import { AnimeThemeConfig } from "./types"
import {
    GiMicroscope,
    GiChessKing,
    GiBullseye,
    GiChainedHeart,
    GiResize,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiSettingsKnobs,
    GiAnvilImpact,
    GiEagleEmblem,
    GiBrain,
    GiCrossedSwords,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const monsterTheme: AnimeThemeConfig = {
    id: "monster",
    displayName: "Monster",
    description: "Look at me. The monster inside me has grown this large. Dr. Tenma's pursuit across Europe, Johan's nameless terror, and the truth buried in Kinderheim 511.",
    fontFamily: "'Cormorant Garamond', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&display=swap",
    cssVars: {
        // Brand → deep forest green (26 74 26 base)
        "--color-brand-200": "120 170 120",
        "--color-brand-300": "85 138 85",
        "--color-brand-400": "52 105 52",
        "--color-brand-500": "26 74 26",
        "--color-brand-600": "20 58 20",
        "--color-brand-700": "15 44 15",
        "--color-brand-800": "10 30 10",
        "--color-brand-900": "6 20 6",
        "--color-brand-950": "3 12 3",
        "--brand": "26 74 26",
        // Near-black with faint green tint
        "--background": "#040604",
        "--paper": "#0a0e0a",
        "--color-gray-950": "4 6 4",
        "--color-gray-900": "10 14 10",
        "--color-gray-800": "20 28 20",
        "--color-gray-700": "34 46 34",
        "--color-gray-600": "52 68 52",
        "--color-gray-500": "78 96 78",
        "--color-gray-400": "115 135 115",
        "--color-gray-300": "155 172 155",
        "--color-gray-200": "192 205 192",
        "--color-gray-100": "222 230 222",
        "--color-gray-50": "240 245 240",
    },
    sidebarOverrides: {
        "home": { icon: GiMicroscope, label: "The Clinic" },
        "schedule": { icon: GiAlarmClock, label: "Case Timeline" },
        "manga": { icon: LuBookOpen, label: "Case Files" },
        "lists": { icon: GiChessKing, label: "Patient Records" },
        "discover": { icon: GiBullseye, label: "Investigation" },
        "torrent-list": { icon: GiAnvilImpact, label: "Evidence Locker" },
        "debrid": { icon: GiCrossedSwords, label: "Black Market" },
        "unmatched": { icon: GiChainedHeart, label: "Missing Persons" },
        "enmasse": { icon: GiResize, label: "Mass Profile" },
        "scan-summaries": { icon: TbReportSearch, label: "Autopsy Reports" },
        "auto-downloader": { icon: LuRss, label: "Wiretaps" },
        "community": { icon: GiEagleEmblem, label: "Interpol" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Case Alerts" },
        "achievements": { icon: GiTrophy, label: "Cases Solved" },
        "theme-manager": { icon: GiPalette, label: "Disguises" },
        "extensions": { icon: BiExtension, label: "Forensic Tools" },
        "sync": { icon: IoCloudOfflineOutline, label: "Encrypted Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Headquarters" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Operation",
        "a_episode_counter": "Case Counter",
        "a_episode_titan": "Monster Encounter",
        "a_hours_invested": "Invested Hours",
        "a_time_lord": "Lost Memories",
        "a_anime_collector": "File Collector",
        "a_library_legend": "Library Phantom",
        "a_first_complete": "Case Closed",
        "a_hundred_club": "Hundred Cases",
        "a_first_day": "Düsseldorf Arrival",
        "a_first_rating": "First Diagnosis",
        "a_ten_thousand_min": "Tenma's Vigil",
        "a_season_veteran": "Veteran Inspector",
        "a_year_explorer": "Year in Europe",
        "a_century_watcher": "Hundred Sessions",
        "a_five_hundred_eps": "Five Hundred Clues",
        "a_thousand_eps": "Thousand Encounters",
        "a_watching_ten": "Ten Open Cases",
        "a_ptw_hoarder": "Cold Case Hoard",
        "a_dropped_honesty": "Abandoned Lead",
        "a_five_thousand_eps": "Five Thousand Leads",
        "a_ten_completed": "Ten Solved",
        "a_fifty_completed": "Fifty Resolved",
        "a_five_hundred_completed": "Five Hundred Solved",
        "a_mean_score_tracker": "Average Prognosis",
        "a_unique_studios": "Allied Agencies",
        "a_days_spent_watching": "Days Investigating",
        "a_all_status": "All Statuses Filed",
        "a_first_favorite": "First Suspect",
        "a_favorites_collector": "Persons of Interest",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Obsessive Pursuit",
        "a_marathon_runner": "Prague Marathon",
        "a_weekend_warrior": "Weekend Stakeout",
        "a_non_stop": "Sleepless Night",
        "a_one_more_episode": "One More Clue",
        "a_speed_run": "Emergency Triage",
        "a_double_feature": "Double Exposure",
        "a_triple_threat": "Triple Identity",
        "a_five_a_day": "Five a Day",
        "a_back_to_back": "Back to Back",
        "a_seasonal_binge": "Full Investigation",
        "a_cour_crusher": "District Sweep",
        "a_half_day_watch": "Half-Day Vigil",
        "a_full_day_watch": "Full-Day Watch",
        "a_power_weekend": "Power Weekend",
        "a_binge_king": "Binge Obsession",
        "a_no_sleep": "Tenma's Insomnia",
        "a_entire_season": "Rapid Pursuit",
        "a_seven_day_challenge": "Seven-Day Hunt",
        "a_hundred_day_binge": "Hundred-Day Trail",
        "a_genre_binge": "Cross-Border Chase",
        "a_studio_binge": "Agency Binge",
        "a_season_sweep": "Season Sweep",
        "a_forty_eight_hour": "Forty-Eight Hours",
        "a_ep_counter_day": "Daily Case Log",
        "a_multi_series_binge": "Multi-Case Blitz",
        "a_midnight_binge": "Midnight Research",
        "a_new_year_binge": "New Year's Chase",

        // ── ANIME GENRES ──
        "a_genre_action": "Violent Encounter",
        "a_genre_adventure": "European Odyssey",
        "a_genre_comedy": "Grimmer's Laugh",
        "a_genre_drama": "Human Drama",
        "a_genre_fantasy": "Johan's Illusion",
        "a_genre_horror": "Nameless Monster",
        "a_genre_mystery": "Deep Mystery",
        "a_genre_romance": "Fragile Bond",
        "a_genre_scifi": "Experimental Data",
        "a_genre_sol": "Quiet Life",
        "a_genre_sports": "Physical Recovery",
        "a_genre_supernatural": "Unnatural Gift",
        "a_genre_thriller": "Pure Thriller",
        "a_genre_mecha": "Surgical Precision",
        "a_genre_music": "Melancholy Melody",
        "a_genre_psychological": "Johan's Game",
        "a_genre_ecchi": "Hidden Desire",
        "a_genre_mahou_shoujo": "Inner Light",
        "a_tag_isekai": "Another Country",
        "a_tag_harem": "Entangled Lives",
        "a_tag_bl": "Brothers in Arms",
        "a_tag_gl": "Bound Sisters",
        "a_tag_historical": "Post-War Europe",
        "a_tag_military": "Military Record",
        "a_tag_school": "Kinderheim 511",
        "a_tag_martial_arts": "Self Defense",
        "a_tag_vampire": "Blood Lineage",
        "a_tag_samurai": "Blade Discipline",
        "a_tag_space": "Distant Horizon",
        "a_tag_parody": "Grimmer's Smile",
        "a_tag_idol": "Public Facade",
        "a_tag_post_apocalyptic": "Ruined Innocence",
        "a_tag_cyberpunk": "Surveillance Net",
        "a_tag_shounen": "Tenma's Resolve",
        "a_tag_seinen": "Harsh Reality",
        "a_tag_shoujo": "Nina's Memory",
        "a_tag_josei": "Eva's Obsession",
        "a_tag_survival": "Survival Instinct",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Dossier",
        "a_mega_completionist": "Master Investigator",
        "a_completion_rate_50": "Halfway Truth",
        "a_completion_rate_75": "Closing In",
        "a_completion_rate_90": "Almost Solved",
        "a_no_drop": "No Case Dropped",
        "a_long_runner_complete": "Long Investigation",
        "a_sequel_chain": "Chain of Evidence",
        "a_clean_list": "Clean Record",
        "a_from_ptw": "Orders Executed",
        "a_rewatch_master": "Memory Replay",
        "a_short_complete": "Quick Resolution",
        "a_same_day_start_finish": "Same-Day Closure",
        "a_revival": "Revived Case",
        "a_zero_to_hero": "Intern to Chief",
        "a_five_genre_complete": "Five-Branch Mastery",
        "a_full_franchise": "Complete Dossier",
        "a_batch_complete": "Batch Cleared",
        "a_paused_to_done": "Cold Case Solved",
        "a_completion_spree": "Closure Spree",
        "a_multi_rewatch": "Multiple Reviews",
        "a_dropped_recovery": "Recovered Lead",
        "a_ten_perfect_scores": "Ten Perfect Ops",
        "a_seasonal_clear": "Seasonal Clear",
        "a_complete_genre_span": "All-Terrain Pursuit",
        "a_monthly_completions": "Monthly Reports",
        "a_yearly_completions": "Annual Review",
        "a_rapid_complete": "Rapid Closure",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Associate",
        "a_studio_devotee": "Madhouse Devotee",
        "a_rewatcher": "Case Review",
        "a_triple_rewatch": "Triple Review",
        "a_annual_tradition": "Annual Ritual",
        "a_director_fan": "Director's Vision",
        "a_voice_actor_fan": "Voice Recognized",
        "a_ost_lover": "Haunting Score",
        "a_source_reader": "Urasawa's Pages",
        "a_waiting_weekly": "Weekly Anticipation",
        "a_childhood_revisit": "Return to Prague",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Genre Loyalty",
        "a_decade_watcher": "Decade Observer",
        "a_adaptation_hunter": "Adaptation Study",
        "a_original_anime_fan": "Original Broadcast",
        "a_long_commitment": "Long Commitment",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Catalog",
        "a_franchise_collector": "Franchise Collector",
        "a_airing_follower": "Currently Airing",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Staff Dossier",
        "a_multi_season_fan": "Multi-Season Fan",
        "a_format_diversity": "Diverse Formats",
        "a_year_dedication": "Year Dedicated",
        "a_season_dedication": "Season Devoted",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Unknown Territory",
        "a_studio_hopper": "Agency Transfer",
        "a_tag_explorer": "Tag Reconnaissance",
        "a_decade_hopper": "Decade Traveler",
        "a_hidden_gem": "Hidden Truth",
        "a_popular_taste": "Popular Opinion",
        "a_retro_appreciator": "Retro Appreciation",
        "a_modern_viewer": "Modern Perspective",
        "a_cross_demographic": "Cross-Demographic",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Week",
        "a_foreign_cinema": "Foreign Intelligence",
        "a_classic_connoisseur": "Classic Taste",
        "a_every_season": "Every Season",
        "a_award_winner": "Award Winner",
        "a_niche_explorer": "Niche Territory",
        "a_global_anime": "Global Reach",
        "a_cult_classic": "Cult Following",
        "a_random_pick": "Random Assignment",
        "a_new_genre_month": "New Genre Monthly",
        "a_seasonal_completionist": "Seasonal Closure",
        "a_unpopular_opinion": "Contrarian View",
        "a_top_rated_viewer": "Top-Rated Source",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Choice",
        "a_upcoming_watcher": "Upcoming Intel",
        "a_short_series_explorer": "Short Case File",
        "a_long_series_explorer": "Long Case File",

        // ── ANIME TIME ──
        "a_night_owl": "Night Owl",
        "a_early_bird": "Dawn Patrol",
        "a_lunch_break": "Cafeteria Break",
        "a_golden_hour": "Golden Hour",
        "a_four_am_club": "4 AM Stakeout",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year's Oath",
        "a_midnight_premiere": "Midnight Debut",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Investigator",
        "a_afternoon_delight": "Afternoon Session",
        "a_prime_time": "Prime Time",
        "a_workday_watcher": "On-Duty Viewer",
        "a_sunday_marathon": "Sunday Marathon",
        "a_rainy_day": "Rainy Munich Day",
        "a_morning_routine": "Morning Rounds",
        "a_night_shift": "Night Shift",
        "a_twilight_zone": "Twilight Zone",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Collector",
        "a_weekend_binge_hours": "Weekend Hours",
        "a_late_night_regular": "Late Night Regular",
        "a_sunrise_watcher": "Sunrise Watcher",
        "a_holiday_watcher": "Holiday Watch",
        "a_every_day_of_week": "Every Day Active",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Meeting",
        "a_party_host": "Case Leader",
        "a_social_butterfly": "Social Contact",
        "a_group_binge": "Group Pursuit",
        "a_party_regular": "Regular Contact",
        "a_sync_viewer": "Synchronized View",
        "a_commentator": "Case Commentator",
        "a_party_marathon": "Marathon Meeting",
        "a_full_house": "Full Assembly",
        "a_community_pillar": "Community Pillar",
        "a_watch_party_streak": "Meeting Streak",
        "a_diverse_party": "Diverse Assembly",
        "a_late_night_party": "Late Gathering",
        "a_party_veteran": "Veteran Host",
        "a_genre_party": "Genre Gathering",
        "a_weekly_party": "Weekly Meeting",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Recommendation",
        "a_party_completionist": "Party Complete",
        "a_social_scorer": "Social Rating",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Fibonacci Pattern",
        "a_palindrome_day": "Palindrome Day",
        "a_binary_day": "Binary Code Day",
        "a_full_moon": "Full Moon Night",
        "a_leap_year": "Leap Year",
        "a_time_traveler": "Time Traveler",
        "a_genre_clash": "Genre Collision",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Complete",
        "a_pi_episodes": "Pi Calculation",
        "a_synchronicity": "Synchronicity",
        "a_world_record": "World Record",
        "a_nice": "Nice Count",
        "a_power_level": "Power Level",
        "a_answer_42": "The Answer",
        "a_square_number": "Perfect Square",
        "a_prime_count": "Prime Count",
        "a_matching_date": "Matching Date",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast",
        "a_movie_buff": "Film Noir",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Episode",
        "a_short_king": "Short King",
        "a_variety_pack": "All Formats",
        "a_film_festival": "Film Festival",
        "a_music_video": "Music Collection",
        "a_tv_short": "Quick Clip",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Case Anthology",
        "a_mini_series": "Mini Series",
        "a_theatrical": "Theatrical Release",
        "a_format_master": "Format Master",
        "a_long_movie": "Feature Length",
        "a_back_catalog": "Archive Files",
        "a_cm_watcher": "Commercial Break",
        "a_pv_collector": "Preview Collector",
        "a_format_balance": "Balanced Formats",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Film",
        "a_recap_watcher": "Recap Session",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Patrol",
        "a_mega_streak": "Mega Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Watch",
        "a_comeback": "Return to Duty",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Consistent Pace",
        "a_year_long": "Year-Long Case",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable Will",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Episode Run",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Harsh Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Lunge's Standards",
        "a_fair_judge": "Fair Judgment",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Full Evaluation",
        "a_wide_range": "Wide Range",
        "a_controversial": "Controversial Case",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Precision Scorer",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Selective Viewer",
        "a_100_rated": "Century Rated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Hunt",
        "a_contrarian": "Contrarian Stance",
        "a_optimist": "Quiet Optimist",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow",
        "a_valentines_weeb": "Valentine's Case",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Deception",
        "a_international_anime_day": "International Day",
        "a_star_wars_day": "Empire Day",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday the 13th",
        "a_halloween_spirit": "Halloween Spirit",
        "a_thanksgiving_binge": "Thanksgiving Feast",
        "a_christmas_special": "Christmas Special",
        "a_new_years_eve": "New Year's Eve",
        "a_birthday_watch": "Birthday Watch",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Independence Day",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Equinox",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Day",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anniversary Day",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Consecutive Holidays",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Awakening",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Initiated",
        "a_meta_tier_climber": "Rank Climbed",
        "a_meta_tier_max": "Maximum Rank",
        "a_meta_xp_earner": "XP Earned",
        "a_meta_difficulty_easy": "Easy Procedure",
        "a_meta_difficulty_hard": "Legendary Difficulty",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Complete",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter Read",
        "m_chapter_counter": "Chapter Counter",
        "m_chapter_titan": "Monster Chapter",
        "m_reading_hours": "Reading Hours",
        "m_reading_time_lord": "Lost Reading Time",
        "m_manga_collector": "Manuscript Collector",
        "m_library_legend": "Archive Legend",
        "m_first_complete": "First Manga Closed",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "First Reading Day",
        "m_first_rating": "First Review",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Collector",
        "m_year_explorer": "Year of Reading",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Read",
        "m_thousand_ch": "Thousand Chapters",
        "m_reading_ten": "Ten Manuscripts",
        "m_ptr_hoarder": "Backlog Hoarder",
        "m_dropped_honesty": "Honest Abandonment",
        "m_season_reader": "Seasonal Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Manga Done",
        "m_fifty_completed": "Fifty Manga Done",
        "m_five_hundred_completed": "Five Hundred Done",
        "m_mean_score_tracker": "Average Review",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Reading Statuses",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Favorites Collected",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reader",
        "m_marathon_reader": "Marathon Reader",
        "m_weekend_reader": "Weekend Reader",
        "m_non_stop_reading": "Non-Stop Reading",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Read",
        "m_double_story": "Double Story",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five Daily Reads",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Reading",
        "m_full_day_read": "Full-Day Reading",
        "m_power_weekend": "Power Weekend Read",
        "m_binge_king": "Binge Reader King",
        "m_no_sleep_read": "Sleepless Reading",
        "m_full_series_rush": "Full Series Rush",
        "m_seven_day_challenge": "Seven-Day Read",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Binge Read",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Log",
        "m_multi_series_binge": "Multi-Series Read",
        "m_midnight_binge": "Midnight Reading",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "Forty-Eight Read",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Manuscript",
        "m_genre_adventure": "Adventure Abroad",
        "m_genre_comedy": "Dark Comedy",
        "m_genre_drama": "Dramatic Record",
        "m_genre_fantasy": "Fantasy Document",
        "m_genre_horror": "Horror Manuscript",
        "m_genre_mystery": "Mystery Dossier",
        "m_genre_romance": "Romance File",
        "m_genre_scifi": "Sci-Fi Report",
        "m_genre_sol": "Slice of Life",
        "m_genre_sports": "Sports Record",
        "m_genre_supernatural": "Supernatural Case",
        "m_genre_thriller": "Thriller Dossier",
        "m_genre_psychological": "Psychological File",
        "m_genre_isekai": "Isekai Document",
        "m_genre_shounen": "Shounen Record",
        "m_genre_ecchi": "Ecchi Record",
        "m_genre_mahou_shoujo": "Mahou Shoujo File",
        "m_genre_mecha": "Mecha Blueprint",
        "m_genre_music": "Music Record",
        "m_tag_isekai_new": "New World File",
        "m_tag_harem": "Harem Dossier",
        "m_tag_bl": "BL Manuscript",
        "m_tag_gl": "GL Manuscript",
        "m_tag_historical": "Historical Record",
        "m_tag_military": "Military Dossier",
        "m_tag_school": "School Record",
        "m_tag_martial_arts": "Combat Manual",
        "m_tag_vampire": "Vampire File",
        "m_tag_samurai": "Samurai Record",
        "m_tag_space": "Space Document",
        "m_tag_parody": "Parody Manuscript",
        "m_tag_idol": "Idol Dossier",
        "m_tag_post_apocalyptic": "Post-Apocalyptic File",
        "m_tag_cyberpunk": "Cyberpunk Record",
        "m_tag_shoujo": "Shoujo Manuscript",
        "m_tag_survival": "Survival Record",
        "m_tag_cooking": "Cooking Manuscript",
        "m_tag_medical": "Medical Record",
        "m_tag_villainess": "Villainess Dossier",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Completionist",
        "m_mega_completionist": "Supreme Reader",
        "m_completion_rate_50": "Halfway Through",
        "m_completion_rate_75": "Nearing the End",
        "m_completion_rate_90": "Almost Complete",
        "m_no_drop": "No Manga Dropped",
        "m_long_runner_complete": "Long Series Done",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean Reading List",
        "m_from_ptr": "Backlog Executed",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Complete",
        "m_same_day_start_finish": "Same-Day Finish",
        "m_revival": "Revival Read",
        "m_zero_to_hundred": "Zero to Hundred",
        "m_five_genre_complete": "Five Genre Mastery",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Cleared",
        "m_paused_to_done": "Paused to Done",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi Reread",
        "m_dropped_recovery": "Dropped Recovery",
        "m_ten_perfect_scores": "Ten Perfect Scores",
        "m_complete_genre_span": "Genre Span Read",
        "m_monthly_completions": "Monthly Completions",
        "m_yearly_completions": "Yearly Completions",
        "m_rapid_complete": "Rapid Complete",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Urasawa Devotee",
        "m_rereader": "Case Rereader",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Appreciation",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Material Fan",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyal",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Favorite Mangaka",
        "m_complete_portfolio": "Complete Portfolio",
        "m_franchise_collector": "Franchise Collected",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Master Read",
        "m_multi_series_author": "Multi-Series Author",
        "m_format_diversity": "Format Diversity",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Genre Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Explorer",
        "m_decade_hopper": "Decade Hopper",
        "m_hidden_gem": "Hidden Gem Found",
        "m_popular_taste": "Popular Taste",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross-Demographic Read",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Varied Reading Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Connoisseur",
        "m_award_winner": "Award-Winning Read",
        "m_niche_explorer": "Niche Explorer",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic Read",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre Monthly",
        "m_year_completionist": "Year Completionist",
        "m_unpopular_opinion": "Unpopular Opinion",
        "m_top_rated_reader": "Top-Rated Reader",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Low Score",
        "m_short_manga_explorer": "Short Manga Read",
        "m_long_manga_explorer": "Long Manga Read",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Lunch Reader",
        "m_commute_reader": "Commute Reader",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All Hours Read",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "Workday Reader",
        "m_sunday_read": "Sunday Reading",
        "m_morning_routine": "Morning Reading",
        "m_night_shift_reader": "Night Shift Read",
        "m_seasonal_premier_read": "New Release Read",
        "m_clock_collector": "Clock Collector Read",
        "m_late_night_horror": "Late Night Horror",
        "m_afternoon_reader": "Afternoon Reader",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Reading",
        "m_twilight_reader": "Twilight Reader",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Binge Read",
        "m_late_night_regular": "Late Night Regular",
        "m_sunrise_reader": "Sunrise Reader",
        "m_every_day_of_week": "Every Day Read",
        "m_monthly_hours": "Monthly Hours Read",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color Read",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Reader",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel Read",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Storyteller",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga to Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award-Winning Art",
        "m_debut_work": "Debut Work Read",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross-Media Read",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collaboration Read",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read Streak",
        "m_mega_streak": "Mega Read Streak",
        "m_weekly_warrior": "Weekly Reader",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader's Return",
        "m_weekend_streak": "Weekend Read Streak",
        "m_no_zero_days": "No Zero Read Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Habit",
        "m_consistent_pace": "Consistent Reading",
        "m_year_long": "Year-Long Reading",
        "m_double_streak": "Double Read Streak",
        "m_streak_recovery": "Streak Recovery",
        "m_daily_minimum": "Daily Minimum Read",
        "m_winter_streak": "Winter Read Streak",
        "m_summer_streak": "Summer Read Streak",
        "m_morning_streak": "Morning Read Streak",
        "m_night_streak": "Night Read Streak",
        "m_unbreakable": "Unbreakable Reader",
        "m_eternal_flame": "Eternal Read Flame",
        "m_chapter_a_day": "Chapter a Day",
        "m_genre_streak": "Genre Read Streak",
        "m_completion_streak": "Completion Streak",
        "m_rating_streak": "Rating Read Streak",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Read Week",
        "m_diverse_streak": "Diverse Read Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manuscript Critic",
        "m_perfect_ten": "Perfect Ten Read",
        "m_harsh_critic": "Harsh Read Critic",
        "m_fair_judge": "Fair Read Judge",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Full Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Read",
        "m_consistent_scorer": "Consistent Reader",
        "m_score_sniper": "Precision Reader",
        "m_evolving_taste": "Evolving Read Taste",
        "m_bell_curve": "Bell Curve Read",
        "m_picky_reader": "Selective Reader",
        "m_100_rated": "Century Read Rated",
        "m_500_rated": "Five Hundred Read",
        "m_mediocre_majority": "Middle Ground Read",
        "m_rating_spree": "Rating Read Spree",
        "m_score_variance": "Score Read Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Reader",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimistic Reader",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Read Critic",
        "m_mean_above_8": "Elite Read Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Read Vow",
        "m_valentines_read": "Valentine's Read",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Fool Read",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Read",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Friday 13th Read",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thanksgiving Read",
        "m_christmas_read": "Christmas Read",
        "m_new_years_eve": "New Year's Eve Read",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Read Binge",
        "m_independence_day": "Independence Read",
        "m_culture_day": "Culture Day Read",
        "m_spring_equinox": "Spring Equinox Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Winter Solstice Read",
        "m_manga_birthday": "Manga Anniversary",
        "m_every_holiday_reader": "Every Holiday Read",
        "m_consecutive_holidays": "Consecutive Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Read",
        "m_fibonacci": "Fibonacci Chapters",
        "m_palindrome_day": "Palindrome Read",
        "m_binary_day": "Binary Day Read",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven Read",
        "m_thousand_complete": "Thousand Complete",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Power Level Read",
        "m_answer_42": "The Answer Read",
        "m_square_number": "Perfect Square Read",
        "m_prime_count": "Prime Count Read",
        "m_matching_date": "Matching Date Read",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters Read",
        "m_synchronicity": "Synchronicity Read",
        "m_world_record": "World Record Read",
        "m_genre_clash": "Genre Clash Read",
        "m_time_traveler": "Time Traveler Read",
        "m_double_digits": "Double Digits Read",
        "m_one_two_three": "One Two Three Read",
        "m_lucky_seven": "Lucky Seven Read",
        "m_exact_hundred_ch": "Exact Hundred Read",
        "m_year_match_count": "Year Match Read",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Specialist",
        "m_manhwa_format": "Manhwa Specialist",
        "m_manhua_format": "Manhua Specialist",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Specialist",
        "m_doujin_format": "Doujin Specialist",
        "m_novel_format": "Novel Specialist",
        "m_format_master_manga": "Format Master Read",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Read Unlock",
        "m_meta_collector": "Read Badge Collector",
        "m_meta_category_starter": "Category Started",
        "m_meta_tier_climber": "Read Rank Climbed",
        "m_meta_tier_max": "Maximum Read Rank",
        "m_meta_xp_earner": "Read XP Earned",
        "m_meta_difficulty_easy": "Easy Read",
        "m_meta_difficulty_hard": "Legendary Read",
        "m_meta_unlock_spree": "Read Unlock Spree",
        "m_meta_completionist": "Meta Read Complete",
        "m_meta_diverse": "Diverse Read Set",
        "m_meta_dominator": "Meta Read Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040604",
        primary: "#1a4a1a",
        secondary: "#143a14",
        accent: "#7a6930",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/monster.png",
    particleColor: "#707070",
    backgroundDim: 0.3,
    backgroundBlur: 20,
    particleTypes: {
        dark_mist: { label: "Dark Mist", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        rain_drops: { label: "Rain Drops", maxCount: 16, defaultEnabled: true, defaultIntensity: 55 },
        thriller_shadows: { label: "Thriller Shadows", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        paper_trail: { label: "Paper Trail", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Doctor",
        5:   "Surgeon",
        15:  "Creator",
        30:  "Fugitive",
        45:  "Seeker",
        60:  "Hunter",
        80:  "Confronted",
        100: "Defeated",
    },
}
