import { AnimeThemeConfig } from "./types"
import { narutoPlayerIcons } from "./player-icons"
import {
    GiScrollUnfurled,
    GiFlame,
    GiKatana,
    GiNinjaHead,
    GiSpikedDragonHead,
    GiWingfoot,
    GiSwordman,
    GiSpellBook,
    GiStarSwirl,
    GiTrophyCup,
    GiPalette,
    GiAlarmClock,
    GiEagleHead,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuFolderSearch, LuRefreshCw } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { HiOutlineServerStack } from "react-icons/hi2"
import { MdOutlineConnectWithoutContact } from "react-icons/md"
import { TbReportSearch } from "react-icons/tb"

export const narutoTheme: AnimeThemeConfig = {
    id: "naruto",
    displayName: "Naruto",
    description: "Hidden Leaf Village aesthetics. Kyuubi chakra particles. Jutsu-named achievements.",
    fontFamily: "'Rajdhani', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&display=swap",
    cssVars: {
        // Brand → orange/red Naruto palette
        "--color-brand-200": "255 210 160",
        "--color-brand-300": "255 170 80",
        "--color-brand-400": "240 120 30",
        "--color-brand-500": "220 80 0",
        "--color-brand-600": "180 55 0",
        "--color-brand-700": "140 35 0",
        "--color-brand-800": "100 20 0",
        "--color-brand-900": "70 8 0",
        "--color-brand-950": "40 0 0",
        "--brand": "220 100 20",
        // Dark warm background
        "--background": "#0a0400",
        "--paper": "#140800",
        "--color-gray-950": "10 4 0",
        "--color-gray-900": "20 9 0",
        "--color-gray-800": "35 18 5",
        "--color-gray-700": "55 28 10",
        "--color-gray-600": "75 40 15",
        "--color-gray-500": "110 65 25",
        "--color-gray-400": "160 105 55",
        "--color-gray-300": "195 145 90",
        "--color-gray-200": "225 190 145",
        "--color-gray-100": "245 225 195",
        "--color-gray-50": "255 248 235",
    },
    sidebarOverrides: {
        "home": { icon: GiScrollUnfurled, label: "Village Home" },
        "schedule": { icon: GiAlarmClock, label: "Mission Board" },
        "manga": { icon: GiSpellBook, label: "Scroll Archive" },
        "lists": { icon: GiNinjaHead, label: "Ninja Registry" },
        "discover": { icon: GiWingfoot, label: "Scout Missions" },
        "torrent-list": { icon: GiAnvilImpact, label: "Supply Drops" },
        "debrid": { icon: GiSwordman, label: "Shinobi Ops" },
        "unmatched": { icon: GiEagleHead, label: "Lost Scrolls" },
        "enmasse": { icon: GiResize, label: "Mass Summon" },
        "scan-summaries": { icon: TbReportSearch, label: "Intel Reports" },
        "auto-downloader": { icon: LuRss, label: "Messenger Hawk" },
        "community": { icon: GiSpikedDragonHead, label: "Shinobi Alliance" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Alerts" },
        "achievements": { icon: GiTrophyCup, label: "Rank Board" },
        "theme-manager": { icon: GiPalette, label: "Clan Colors" },
        "extensions": { icon: BiExtension, label: "Contracts" },
        "sync": { icon: IoCloudOfflineOutline, label: "Shadow Clone" },
        "settings": { icon: GiSettingsKnobs, label: "Hokage's Scroll" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Jutsu Mastered",
        "a_episode_counter": "Chakra Points",
        "a_episode_titan": "Tailed Beast Chakra",
        "a_hours_invested": "Training Hours",
        "a_time_lord": "Eternal Mangekyō",
        "a_anime_collector": "Scroll Collection",
        "a_library_legend": "Kage-Level Archive",
        "a_first_complete": "First Mission Complete",
        "a_hundred_club": "Leaf Genin Squad",
        "a_first_day": "Day of Enrollment",
        "a_first_rating": "Mission Assessment",
        "a_ten_thousand_min": "Ten Thousand Seals",
        "a_season_veteran": "Four Seasons Shinobi",
        "a_year_explorer": "Years in Service",
        "a_century_watcher": "100-Jutsu Practice",
        "a_five_hundred_eps": "Five Hundred Hand Signs",
        "a_thousand_eps": "Thousand Shadow Clones",
        "a_watching_ten": "Ten-Clone Juggler",
        "a_ptw_hoarder": "Scroll Hoarder",
        "a_dropped_honesty": "Failed Missions",
        // ── ANIME BINGE ──
        "a_binge_watcher": "Shadow Clone Training",
        "a_marathon_runner": "S-Rank Marathon",
        "a_weekend_warrior": "Weekend Warrior Ninja",
        "a_non_stop": "Continuous Sage Mode",
        "a_one_more_episode": "One More Hand Sign",
        "a_speed_run": "Leaf Hurricane Speed",
        "a_double_feature": "Double Summon",
        "a_triple_threat": "Triple Threat Squad",
        "a_five_a_day": "Five-Element Barrage",
        "a_back_to_back": "Consecutive Jutsu",
        "a_seasonal_binge": "Full Seasonal Mission",
        "a_cour_crusher": "Cour Crusher",
        "a_half_day_watch": "Half-Day Training Arc",
        "a_full_day_watch": "Full Day Immersion",
        "a_power_weekend": "Power Weekend Spar",
        "a_binge_king": "Binge King Hokage",
        "a_no_sleep": "All-Night Watch Stand",
        "a_entire_season": "Rapid-Fire Mission Set",
        "a_seven_day_challenge": "Seven Deadly Missions",
        "a_hundred_day_binge": "Hundred-Day Spar",
        // ── ANIME GENRES ──
        "a_genre_action": "Action Connoisseur",
        "a_genre_adventure": "Wandering Shinobi",
        "a_genre_comedy": "Konohamaru's Heir",
        "a_genre_drama": "Tear Seal Wielder",
        "a_genre_fantasy": "Fantasy Realm Traveler",
        "a_genre_horror": "Fear No Genjutsu",
        "a_genre_mystery": "ANBU Intel Specialist",
        "a_genre_romance": "Romantic Shinobi",
        "a_genre_scifi": "Scientific Ninja Tool Expert",
        "a_genre_sol": "Slice of Village Life",
        "a_genre_sports": "Tournament Fighter",
        "a_genre_supernatural": "Cursed Seal Bearer",
        "a_genre_thriller": "High-Stakes Mission",
        "a_genre_mecha": "Puppet Master",
        "a_genre_music": "Song Ninja",
        "a_genre_psychological": "Genjutsu Specialist",
        "a_genre_ecchi": "Pervy Sage Apprentice",
        "a_genre_mahou_shoujo": "Chakra Conjurer",
        // ── ANIME COMPLETION ──
        "a_completionist": "Mission Completionist",
        "a_mega_completionist": "S-Rank Legend",
        "a_completion_rate_50": "Halfway to Hokage",
        "a_completion_rate_75": "Almost Jonin",
        "a_completion_rate_90": "Elite Jonin",
        "a_no_drop": "Never Abandon a Mission",
        "a_long_runner_complete": "Long-Runner Shinobi",
        "a_sequel_chain": "Sequel Chain Jutsu",
        "a_clean_list": "Clean Mission Record",
        "a_from_ptw": "Executed Operation",
        "a_rewatch_master": "Rewind Jutsu Master",
        "a_short_complete": "Swift Ops Specialist",
        "a_same_day_start_finish": "Same-Day Mission Clear",
        "a_revival": "Revival Jutsu",
        "a_zero_to_hero": "From Academy to Hokage",
        "a_five_genre_complete": "Five-Style Jutsu",
        "a_full_franchise": "Full Clan Mastery",
        "a_batch_complete": "Rapid Mission Clearance",
        "a_paused_to_done": "Unsealed Missions",
        "a_completion_spree": "Mission Surge",
        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Sworn Allegiance",
        "a_studio_devotee": "Clan Devotee",
        "a_rewatcher": "Rewind Scroll",
        "a_triple_rewatch": "Triple Shadow Clone",
        "a_annual_tradition": "Annual Rite",
        "a_director_fan": "Sensei's Student",
        "a_voice_actor_fan": "Familiar Voice",
        "a_ost_lover": "Sound Ninja",
        "a_source_reader": "Source Code Breaker",
        "a_waiting_weekly": "Weekly Watcher",
        "a_childhood_revisit": "Childhood Academy",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Genre Loyalty Seal",
        "a_decade_watcher": "Decade Veteran",
        "a_adaptation_hunter": "Light Novel Hunter",
        "a_original_anime_fan": "Original Scroll Fan",
        "a_long_commitment": "Long-Term Assignment",
        "a_perfect_attendance": "Perfect Attendance Genin",
        "a_favorite_studio_5": "Clan Loyalty",
        "a_complete_catalog": "Full Clan Catalog",
        "a_franchise_collector": "Franchise Chakra Network",
        "a_airing_follower": "Airing Mission Follower",
        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Jutsu Style Explorer",
        "a_studio_hopper": "Clan Hopper",
        "a_tag_explorer": "Tag Seal Explorer",
        "a_decade_hopper": "Era Traveler",
        "a_hidden_gem": "Hidden Leaf Treasure",
        "a_popular_taste": "Popular Path",
        "a_retro_appreciator": "Old Scroll Collector",
        "a_modern_viewer": "Current Generation",
        "a_cross_demographic": "Cross-Village Scout",
        "a_underdog_fan": "Underdog Champion",
        "a_variety_week": "Week of Variety Jutsu",
        "a_foreign_cinema": "Foreign Rogue Ninja",
        "a_classic_connoisseur": "Classic Scroll Collector",
        "a_every_season": "Four-Season Shinobi",
        "a_award_winner": "Elite Ranked Shows",
        "a_niche_explorer": "Rare Jutsu Practitioner",
        "a_global_anime": "World Shinobi Summit",
        "a_cult_classic": "Cult Technique Fan",
        "a_random_pick": "Random Summon",
        "a_new_genre_month": "New Technique Unlocked",
        "a_seasonal_completionist": "Seasonal Sweep",
        "a_unpopular_opinion": "Unpopular Jutsu",
        // ── ANIME TIME ──
        "a_night_owl": "Night-Shift ANBU",
        "a_early_bird": "Dawn Training Session",
        "a_lunch_break": "Midday Mission Break",
        "a_golden_hour": "Golden Hour Spar",
        "a_four_am_club": "4 AM Training Ritual",
        "a_witching_hour": "Dead of Night Mission",
        "a_new_year_watch": "New Year's Mission",
        "a_midnight_premiere": "Midnight Scroll Opening",
        "a_all_hours": "All Hours Shinobi",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Spar",
        "a_prime_time": "Prime Time Ninja",
        "a_workday_watcher": "Workday Shinobi",
        "a_sunday_marathon": "Sunday Endurance Training",
        "a_rainy_day": "Rainy Day Scroll",
        "a_morning_routine": "Morning Training Regimen",
        "a_night_shift": "Night Shift ANBU",
        "a_twilight_zone": "Twilight Zone Patrol",
        "a_seasonal_premier": "Season Opener Mission",
        "a_clock_collector": "Time Seal Collection",
        // ── ANIME SOCIAL ──
        "a_first_party": "First Squad Mission",
        "a_party_host": "Squad Captain",
        "a_social_butterfly": "Alliance Builder",
        "a_group_binge": "Group Training",
        "a_party_regular": "Regular Watch Party Ninja",
        "a_sync_viewer": "In-Sync Formation",
        "a_commentator": "Commentator",
        "a_party_marathon": "Four-Hour Squad Session",
        "a_full_house": "Five-Man Cell",
        "a_community_pillar": "Village Pillar",
        "a_watch_party_streak": "Consecutive Squad Ops",
        "a_diverse_party": "Diverse Jutsu Party",
        "a_late_night_party": "Midnight Squad Session",
        "a_party_veteran": "Watch Party Veteran",
        // ── ANIME SPECIAL ──
        "a_round_number": "Round Completion Seal",
        "a_fibonacci": "Fibonacci Sequence Jutsu",
        "a_palindrome_day": "Palindrome Seal Day",
        "a_binary_day": "Binary Scroll Day",
        "a_full_moon": "Full Moon Howl",
        "a_leap_year": "Leap Year Shinobi",
        "a_time_traveler": "Time-Leap Technique",
        "a_genre_clash": "Clash of Jutsu Styles",
        "a_triple_seven": "Triple Seven Seals",
        "a_thousand_complete": "One Thousand Completions",
        "a_pi_episodes": "Pi Episode Seal",
        "a_synchronicity": "Perfect Synchronicity",
        "a_world_record": "Personal Jutsu Record",
        "a_nice": "Nice Jutsu",
        "a_power_level": "Over Nine Thousand",
        "a_answer_42": "The Ultimate Answer",
        "a_square_number": "Perfect Square Formation",
        "a_prime_count": "Prime Number Shinobi",
        "a_matching_date": "Matching Seal Date",
        "a_century_episode": "Century Episode",
        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Mission Watcher",
        "a_movie_buff": "Cinematic Techniques",
        "a_ova_hunter": "OVA Scroll Hunter",
        "a_ona_explorer": "ONA Scout",
        "a_special_watcher": "Special Jutsu Watcher",
        "a_short_king": "Rapid-Fire Ninja",
        "a_variety_pack": "All-Format Specialist",
        "a_film_festival": "Film Festival Ninja",
        "a_music_video": "Sound Style Collector",
        "a_tv_short": "Quick-Strike Collector",
        "a_movie_marathon": "Movie Marathon Sprint",
        "a_double_length": "Extended Technique",
        "a_anthology": "Anthology Archive",
        "a_mini_series": "Mini Scroll Collection",
        "a_theatrical": "Theatrical Release Fan",
        "a_format_master": "Format Master Shinobi",
        "a_long_movie": "Epic Film Jutsu",
        "a_back_catalog": "Back Catalog Retrieval",
        // ── ANIME STREAKS ──
        "a_daily_streak": "Consecutive Days of Training",
        "a_mega_streak": "Mega Streak Jutsu",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Dedication",
        "a_comeback": "Revival After Defeat",
        "a_weekend_streak": "Weekend Training Streak",
        "a_no_zero_days": "Zero Missed Days",
        "a_iron_will": "Iron Will Shinobi",
        "a_habit_formed": "Habit Seal Formed",
        "a_consistent_pace": "Steady Chakra Flow",
        "a_year_long": "Year-Long Devotion",
        "a_double_streak": "Double Streak Jutsu",
        "a_streak_recovery": "Streak Recovery Jutsu",
        "a_daily_minimum": "Daily Minimum Training",
        "a_winter_streak": "Winter Endurance",
        "a_summer_streak": "Summer Festival Training",
        "a_morning_streak": "Morning Ritual Streak",
        "a_night_streak": "Midnight Training Streak",
        "a_unbreakable": "Unbreakable Shinobi",
        "a_eternal_flame": "Eternal Flame of Will",
        // ── ANIME SCORING ──
        "a_critic": "Mission Evaluator",
        "a_perfect_ten": "Perfect Score Seal",
        "a_harsh_critic": "Harsh Mission Judge",
        "a_fair_judge": "Balanced Assessor",
        "a_generous_spirit": "Generous Evaluator",
        "a_score_all": "Full Mission Assessment",
        "a_wide_range": "Full Range Evaluator",
        "a_controversial": "Controversial Opinion",
        "a_consistent_scorer": "Consistent Rating",
        "a_score_sniper": "Score Sniper Seal",
        "a_evolving_taste": "Evolving Jutsu Style",
        "a_bell_curve": "Bell Curve Formation",
        "a_picky_watcher": "Picky Shinobi",
        "a_100_rated": "Century Evaluator",
        "a_500_rated": "Master Evaluator",
        "a_mediocre_majority": "Middle Path Shinobi",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Variable Jutsu Strength",
        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow",
        "a_valentines_weeb": "Valentine's Ninja",
        "a_pi_day": "Pi Day Technique",
        "a_april_fools": "April Fools Genjutsu",
        "a_international_anime_day": "International Ninja Day",
        "a_star_wars_day": "Futuristic Jutsu Day",
        "a_summer_solstice": "Solstice Training",
        "a_tanabata": "Tanabata Celebration",
        "a_friday_13th": "13th Shadow",
        "a_halloween_spirit": "Halloween Genjutsu",
        "a_thanksgiving_binge": "Feast of Missions",
        "a_christmas_special": "Winter Festival Scroll",
        "a_new_years_eve": "Year-End Ceremony",
        "a_birthday_watch": "Birthday Training",
        "a_holiday_marathon": "Holiday Season Grind",
        "a_independence_day": "Freedom Seal Day",
        "a_culture_day": "Culture Day Ceremony",
        "a_spring_equinox": "Spring Awakening",
        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Seal Inscribed",
        "m_chapter_counter": "Seal Counter",
        "m_chapter_titan": "Tailed Beast Ink",
        "m_reading_hours": "Scroll Study Hours",
        "m_reading_time_lord": "Infinite Scroll Archive",
        "m_manga_collector": "Scroll Collector",
        "m_library_legend": "Kage-Level Library",
        "m_first_complete": "First Scroll Completed",
        "m_hundred_club": "Hundred Scrolls Club",
        "m_first_day": "First Day at the Academy",
        "m_first_rating": "First Scroll Grade",
        "m_ten_thousand_pages": "Ten Thousand Seals",
        "m_volume_collector": "Volume Archive",
        "m_year_explorer": "Scroll Era Explorer",
        "m_century_reader": "Century Scroll",
        "m_five_hundred_ch": "Five Hundred Seals",
        "m_thousand_ch": "Thousand Seals Studied",
        "m_reading_ten": "Ten Scrolls at Once",
        "m_ptr_hoarder": "Plan to Study Hoarder",
        "m_dropped_honesty": "Abandoned Seals",
        "m_season_reader": "Season Scroll Reader",
        "m_active_reader": "Active Scroll Student",
        // ── MANGA BINGE ──
        "m_binge_reader": "Scroll Binge Reader",
        "m_marathon_reader": "Marathon Scroll Session",
        "m_weekend_reader": "Weekend Scroll Reader",
        "m_non_stop_reading": "Non-Stop Inscription",
        "m_one_more_chapter": "One More Seal",
        "m_speed_read": "Speed Seal Study",
        "m_double_story": "Double Scroll Day",
        "m_triple_read": "Triple Scroll Day",
        "m_five_a_day": "Five-Scroll Day",
        "m_chapter_chain": "Seal Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Scroll Study",
        "m_full_day_read": "Full-Day Training Arc",
        "m_power_weekend": "Power Weekend Scroll",
        "m_binge_king": "Binge King Scribe",
        "m_no_sleep_read": "All-Night Inscription",
        "m_full_series_rush": "Full Series Rapid Read",
        "m_seven_day_challenge": "Seven Scroll Challenge",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        // ── MANGA GENRES ──
        "m_genre_action": "Action Scroll Collector",
        "m_genre_adventure": "Adventure Scroll Explorer",
        "m_genre_comedy": "Comedy Seal",
        "m_genre_drama": "Tear-Drop Scroll",
        "m_genre_fantasy": "Fantasy Realm Scribe",
        "m_genre_horror": "Fear No Darkness",
        "m_genre_mystery": "Mystery Scroll Solver",
        "m_genre_romance": "Romantic Scroll",
        "m_genre_scifi": "Sci-Ninja Tools",
        "m_genre_sol": "Village Life Scroll",
        "m_genre_sports": "Tournament Scroll",
        "m_genre_supernatural": "Curse Seal Scroll",
        "m_genre_thriller": "High-Stakes Scroll",
        "m_genre_psychological": "Mind Jutsu Scroll",
        "m_genre_isekai": "Isekai Summon",
        "m_genre_shounen": "Shounen Heart",
        "m_genre_ecchi": "Pervy Sage Favorites",
        "m_genre_mahou_shoujo": "Chakra Girl Scroll",
        "m_genre_mecha": "Puppet Scroll",
        "m_genre_music": "Sound Ninja Scroll",
        // ── MANGA COMPLETION ──
        "m_completionist": "Scroll Completionist",
        "m_mega_completionist": "Kage-Rank Completionist",
        "m_completion_rate_50": "Halfway Through the Scrolls",
        "m_completion_rate_75": "Almost Jonin Rank",
        "m_completion_rate_90": "Perfectionist Scribe",
        "m_no_drop": "Never Abandons a Scroll",
        "m_long_runner_complete": "Epic Scroll Finisher",
        "m_sequel_chain": "Sequel Scroll Chain",
        "m_clean_list": "Clean Scroll List",
        "m_from_ptr": "Completed the Plan",
        "m_reread_master": "Rewind Scroll Master",
        "m_oneshot_complete": "Oneshot Completionist",
        "m_same_day_start_finish": "Same-Day Scroll Clear",
        "m_revival": "Scroll Revival",
        "m_zero_to_hundred": "Zero to Hundred Scrolls",
        "m_five_genre_complete": "Five-Style Scroll",
        "m_full_collection": "Complete Scroll Collection",
        "m_batch_complete": "Rapid Scroll Clearance",
        "m_paused_to_done": "Unsealed Old Scrolls",
        "m_completion_spree": "Scroll Completion Surge",
        "m_format_completionist": "Format Scroll Completionist",
        "m_catch_up": "Catch-Up Jutsu",
        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Sworn Scroll Allegiance",
        "m_mangaka_lover": "Mangaka Devotee",
        "m_rereader": "Reread Scroll",
        "m_triple_reread": "Triple Reread Seal",
        "m_annual_reread": "Annual Reread Rite",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Devotee",
        "m_adaptation_compare": "Adaptation Comparer",
        "m_source_material_fan": "Canon Source Fan",
        "m_waiting_weekly": "Weekly Scroll Follower",
        "m_classic_reader": "Classic Era Scroll",
        "m_saga_reader": "Saga Scroll Reader",
        "m_genre_loyalty": "Genre Scroll Loyalty",
        "m_decade_reader": "Decade Scroll Reader",
        "m_ln_adaptation": "Light Novel Scroll",
        "m_original_work": "Original Scroll Work",
        "m_long_commitment": "Long Scroll Assignment",
        "m_up_to_date": "Up-to-Date Scribe",
        "m_favorite_mangaka": "Favorite Sensei",
        "m_complete_portfolio": "Complete Scroll Portfolio",
        "m_franchise_collector": "Franchise Scroll Network",
        "m_serialization_follower": "Serial Scroll Follower",
        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Jutsu Style Reader",
        "m_publisher_hopper": "Publisher Jumper",
        "m_tag_explorer": "Seal Tag Explorer",
        "m_decade_hopper": "Era Scroll Traveler",
        "m_hidden_gem": "Hidden Gem Scroll",
        "m_popular_taste": "Popular Scroll Path",
        "m_retro_reader": "Old Era Scroll Reader",
        "m_modern_reader": "Modern Scroll Reader",
        "m_cross_demographic": "Cross-Village Scroll Scout",
        "m_underdog_fan": "Underdog Scroll Champion",
        "m_variety_week": "Week of Varied Scrolls",
        "m_manhwa_reader": "Foreign Scroll (Korea)",
        "m_manhua_reader": "Foreign Scroll (China)",
        "m_classic_connoisseur": "Classic Scroll Connoisseur",
        "m_award_winner": "Award-Winning Scrolls",
        "m_niche_explorer": "Niche Scroll Style",
        "m_world_manga": "World Scroll Summit",
        "m_cult_classic": "Cult Scroll",
        "m_random_pick": "Random Summon Scroll",
        "m_new_genre_month": "New Jutsu Style Scroll",
        "m_year_completionist": "Year Scroll Completionist",
        "m_unpopular_opinion": "Unpopular Scroll Opinion",
        // ── MANGA TIME ──
        "m_night_owl": "Night-Shift Scribe",
        "m_early_bird": "Dawn Scroll Study",
        "m_lunch_reader": "Midday Mission Read",
        "m_commute_reader": "Commute Scroll",
        "m_four_am_club": "4 AM Reading Ritual",
        "m_new_year_read": "New Year Scroll",
        "m_all_hours": "All-Hours Scribe",
        "m_prime_time_reader": "Prime Time Reader",
        "m_workday_reader": "Workday Scroll Study",
        "m_sunday_read": "Sunday Scroll Marathon",
        "m_morning_routine": "Morning Scroll Ritual",
        "m_night_shift_reader": "Night Shift Scribe",
        "m_seasonal_premier_read": "New Release Scroll",
        "m_clock_collector": "Clock Seal Collection",
        "m_late_night_horror": "Midnight Horror Scroll",
        "m_afternoon_reader": "Afternoon Scroll Session",
        "m_golden_hour_reader": "Golden Hour Scroll",
        "m_dawn_reader": "Dawn Scroll Reader",
        "m_twilight_reader": "Twilight Scroll",
        "m_midnight_start": "Midnight Scroll Begin",
        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Scroll Appreciator",
        "m_webtoon_reader": "Webtoon Scroll Reader",
        "m_full_color": "Full Color Scroll",
        "m_doujin_reader": "Doujin Scroll Reader",
        "m_anthology_reader": "Anthology Scroll",
        "m_adaptation_reader": "Adaptation Scroll",
        "m_longstrip_reader": "Long Strip Scroll",
        "m_4koma_reader": "4-Koma Seal",
        "m_oneshot_reader": "Oneshot Seal",
        "m_format_variety": "Scroll Format Variety",
        "m_light_novel_reader": "Light Novel Scroll",
        "m_novel_reader": "Novel Scroll",
        "m_visual_storyteller": "Visual Scroll Storyteller",
        "m_colored_classic": "Colored Classic Scroll",
        "m_webcomic_fan": "Webcomic Scroll Fan",
        "m_manga_to_anime": "Canon Comparison",
        "m_seinen_reader": "Seinen Scroll",
        "m_josei_reader": "Josei Scroll",
        "m_award_winning_art": "Award-Winning Scroll Art",
        "m_debut_work": "Debut Scroll",
        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Scroll Training",
        "m_mega_streak": "Mega Reading Streak",
        "m_weekly_warrior": "Weekly Scroll Warrior",
        "m_monthly_reader": "Monthly Scroll Devotion",
        "m_comeback": "Scroll Comeback",
        "m_weekend_streak": "Weekend Scroll Streak",
        "m_no_zero_days": "Zero Missed Scroll Days",
        "m_iron_will": "Iron Will Scribe",
        "m_habit_formed": "Scroll Habit Formed",
        "m_consistent_pace": "Consistent Scroll Pace",
        "m_year_long": "Year-Long Scroll Journey",
        "m_double_streak": "Double Scroll Streak",
        "m_streak_recovery": "Scroll Streak Revival",
        "m_daily_minimum": "Daily Minimum Scroll",
        "m_winter_streak": "Winter Scroll Streak",
        "m_summer_streak": "Summer Scroll Streak",
        "m_morning_streak": "Morning Scroll Streak",
        "m_night_streak": "Midnight Scroll Streak",
        "m_unbreakable": "Unbreakable Scribe",
        "m_eternal_flame": "Eternal Flame of Ink",
        "m_chapter_a_day": "Chapters Every Day",
        "m_genre_streak": "Genre Streak Scribe",
        // ── MANGA SCORING ──
        "m_critic": "Scroll Critic",
        "m_perfect_ten": "Perfect Scroll Rating",
        "m_harsh_critic": "Harsh Scroll Judge",
        "m_fair_judge": "Balanced Scroll Assessor",
        "m_generous_spirit": "Generous Scribe",
        "m_score_all": "Full Scroll Assessment",
        "m_wide_range": "Full Range Scroll Judge",
        "m_controversial": "Controversial Scroll Opinion",
        "m_consistent_scorer": "Consistent Scroll Scorer",
        "m_score_sniper": "Scroll Score Sniper",
        "m_evolving_taste": "Evolving Scroll Style",
        "m_bell_curve": "Scroll Bell Curve",
        "m_picky_reader": "Picky Scribe",
        "m_100_rated": "Century Scroll Critic",
        "m_500_rated": "Master Scroll Critic",
        "m_mediocre_majority": "Middle Path Scribe",
        "m_rating_spree": "Scroll Rating Spree",
        "m_score_variance": "Variable Scroll Strength",
        "m_binge_rater": "Binge Rating Session",
        "m_reread_rerate": "Reread & Re-Evaluate",
        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Scroll Vow",
        "m_valentines_read": "Valentine's Scribe",
        "m_pi_day": "Pi Day Scroll",
        "m_april_fools": "April Fools Genjutsu Read",
        "m_international_manga_day": "International Scroll Day",
        "m_free_comic_day": "Free Scroll Day",
        "m_summer_solstice": "Solstice Scroll",
        "m_tanabata": "Tanabata Scroll",
        "m_friday_13th": "Cursed Seal Friday",
        "m_halloween_read": "Halloween Horror Scroll",
        "m_thanksgiving_binge": "Feast of Scrolls",
        "m_christmas_read": "Winter Scroll Festival",
        "m_new_years_eve": "Year-End Scroll",
        "m_birthday_read": "Birthday Scroll",
        "m_holiday_marathon": "Holiday Scroll Marathon",
        "m_independence_day": "Freedom Scroll Day",
        "m_culture_day": "Culture Day Scroll",
        "m_spring_equinox": "Spring Scroll Awakening",
        // ── MANGA SPECIAL ──
        "m_round_number": "Round Scroll Count",
        "m_fibonacci": "Fibonacci Seal",
        "m_palindrome_day": "Palindrome Scroll Day",
        "m_binary_day": "Binary Scroll Day",
        "m_full_moon_read": "Full Moon Scroll",
        "m_leap_year_read": "Leap Year Scroll",
        "m_triple_seven": "Triple Seven Scrolls",
        "m_thousand_complete": "One Thousand Scrolls",
        "m_nice": "Nice Scribe",
        "m_power_level_chapters": "Over Nine Thousand Chapters",
        "m_answer_42": "The Ultimate Answer Read",
        "m_square_number": "Perfect Square Scribe",
        "m_prime_count": "Prime Scroll Count",
        "m_matching_date": "Matching Seal Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapter Seal",
        "m_synchronicity": "Scroll Synchronicity",
        "m_world_record": "Personal Scroll Record",
        "m_genre_clash": "Genre Clash Scroll",
        "m_time_traveler": "Scroll Time Traveler",

        // ── ANIME MILESTONES (additions) ──
        "a_five_thousand_eps": "Five Thousand Shadow Clones",
        "a_ten_completed": "Ten Missions Accomplished",
        "a_fifty_completed": "Fifty-Mission Jonin",
        "a_five_hundred_completed": "Five Hundred Jutsu Victories",
        "a_mean_score_tracker": "Average Mission Rating",
        "a_unique_studios": "Allied Village Count",
        "a_days_spent_watching": "Days in Hidden Leaf",
        "a_all_status": "All Ninja Status Logged",
        "a_first_favorite": "First Comrade Seal",
        "a_favorites_collector": "Bonds of the Leaf Village",

        // ── ANIME BINGE (additions) ──
        "a_genre_binge": "Cross-Style Jutsu Binge",
        "a_studio_binge": "Allied Village Marathon",
        "a_season_sweep": "Season Sweep Jutsu",
        "a_forty_eight_hour": "Forty-Eight Hour Endurance",
        "a_ep_counter_day": "Daily Episode Mission Count",
        "a_multi_series_binge": "Multi-Front Ninja Training",
        "a_midnight_binge": "Midnight Chakra Surge",
        "a_new_year_binge": "New Year's Rasengan Burst",

        // ── ANIME GENRES (additions) ──
        "a_tag_isekai": "Summoned to Another Dimension",
        "a_tag_harem": "Konoha Fan Club",
        "a_tag_bl": "Brothers in Arms Bond",
        "a_tag_gl": "Kunoichi Sisters Bond",
        "a_tag_historical": "First Hokage's Legacy",
        "a_tag_military": "Shinobi Military Tactics",
        "a_tag_school": "Ninja Academy",
        "a_tag_martial_arts": "Taijutsu Specialist",
        "a_tag_vampire": "Jashin Curse Blood",
        "a_tag_samurai": "Land of Iron Blade",
        "a_tag_space": "Kaguya's Dimension",
        "a_tag_parody": "Konohamaru Sexy Jutsu",
        "a_tag_idol": "Hidden Leaf Idol",
        "a_tag_post_apocalyptic": "Post-Fourth Ninja War",
        "a_tag_cyberpunk": "Scientific Ninja Tools",
        "a_tag_shounen": "This is My Nindo",
        "a_tag_seinen": "Mature Shinobi Reality",
        "a_tag_shoujo": "Sakura's Inner Fire",
        "a_tag_josei": "Kunoichi's World View",
        "a_tag_survival": "Shinobi World Survival",

        // ── ANIME COMPLETION (additions) ──
        "a_multi_rewatch": "Multi-Shadow Clone Rewatch",
        "a_dropped_recovery": "Mission Revival Jutsu",
        "a_ten_perfect_scores": "Ten Perfect Mission Scores",
        "a_seasonal_clear": "Seasonal Arc Cleared",
        "a_complete_genre_span": "All Jutsu Style Mastery",
        "a_monthly_completions": "Monthly Mission Completions",
        "a_yearly_completions": "Yearly Ninja Campaign",
        "a_rapid_complete": "Shunshin Speed Clear",

        // ── ANIME DEDICATION (additions) ──
        "a_genre_master": "Jutsu Genre Mastery",
        "a_staff_follower": "Sensei Roster Tracker",
        "a_multi_season_fan": "Multi-Season Ninja Fan",
        "a_format_diversity": "All Jutsu Format Diversity",
        "a_year_dedication": "Year of Nindo Dedication",
        "a_season_dedication": "Season of Ninja Devotion",

        // ── ANIME DISCOVERY (additions) ──
        "a_top_rated_viewer": "Top-Ranked Mission Intel",
        "a_source_variety": "Source Material Diversity",
        "a_low_score_brave": "D-Rank Scroll Bravery",
        "a_upcoming_watcher": "Upcoming Mission Scouting",
        "a_short_series_explorer": "Short Mission Explorer",
        "a_long_series_explorer": "Long Campaign Explorer",

        // ── ANIME TIME (additions) ──
        "a_weekend_binge_hours": "Weekend Training Marathon",
        "a_late_night_regular": "Late Night ANBU Regular",
        "a_sunrise_watcher": "Sunrise Over Konoha",
        "a_holiday_watcher": "Leaf Village Festival Watch",
        "a_every_day_of_week": "Every Day a Shinobi",
        "a_monthly_hours": "Monthly Training Hours",

        // ── ANIME SOCIAL (additions) ──
        "a_genre_party": "Cross-Style Squad Formation",
        "a_weekly_party": "Weekly Comrades Gathering",
        "a_silent_viewer": "Silent Sasuke Watcher",
        "a_recommendation_giver": "Sensei's Recommendation",
        "a_party_completionist": "Squad Mission Completionist",
        "a_social_scorer": "Alliance Combat Scorer",

        // ── ANIME SPECIAL (additions) ──
        "a_double_digits": "Double Digit Hand Seals",
        "a_one_two_three": "Ichi Ni San Jutsu",
        "a_lucky_seven": "Seven Lucky Ninja",
        "a_all_tens": "All Tens Jutsu Score",
        "a_exact_hundred_eps": "Hundred Episode Milestone",
        "a_year_match_count": "Year Match Chakra Count",

        // ── ANIME FORMATS (additions) ──
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Jutsu Collector",
        "a_format_balance": "Balanced Jutsu Formats",
        "a_episodic_master": "Episodic Mission Master",
        "a_sequel_movie": "Sequel Film Jutsu",
        "a_recap_watcher": "Recap Briefing Watcher",

        // ── ANIME STREAKS (additions) ──
        "a_completion_streak": "Mission Completion Chain",
        "a_rating_streak": "Rating Mission Streak",
        "a_multi_ep_streak": "Multi-Episode Offensive",
        "a_genre_streak": "Genre Streak Training",
        "a_studio_streak": "Studio Village Loyalty",
        "a_perfect_week": "Perfect Week of Training",

        // ── ANIME SCORING (additions) ──
        "a_masterpiece_hunter": "Masterpiece Jutsu Hunter",
        "a_contrarian": "Contrarian Ninja Path",
        "a_optimist": "Undying Leaf Optimism",
        "a_score_distributor": "Score Distributor Hokage",
        "a_genre_critic": "Genre Mission Critic",
        "a_mean_above_8": "Elite Jutsu Average",

        // ── ANIME HOLIDAY (additions) ──
        "a_earth_day": "Protect the Ninja World",
        "a_labor_day": "Genin Corps Labor Day",
        "a_winter_solstice": "Winter Training Ground",
        "a_anime_birthday": "Series Anniversary Ninja",
        "a_every_holiday": "Every Festival Watcher",
        "a_consecutive_holidays": "Consecutive Festival Missions",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Jutsu Unlocked",
        "a_meta_collector": "Achievement Badge Collector",
        "a_meta_category_starter": "Category Initiation Seal",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Hokage-Class Achiever",
        "a_meta_xp_earner": "XP from Chakra Training",
        "a_meta_difficulty_easy": "Easy D-Rank Mission",
        "a_meta_difficulty_hard": "Legendary S-Rank Challenge",
        "a_meta_unlock_spree": "Achievement Burst Jutsu",
        "a_meta_completionist": "Meta Completionist Hokage",
        "a_meta_diverse": "Diverse Ninja Portfolio",
        "a_meta_dominator": "Meta Dominator Shinobi",

        // ── MANGA MILESTONES (additions) ──
        "m_five_thousand_ch": "Five Thousand Seal Chapters",
        "m_ten_completed": "Ten Scroll Missions Done",
        "m_fifty_completed": "Fifty Scroll Completions",
        "m_five_hundred_completed": "Five Hundred Scroll Victories",
        "m_mean_score_tracker": "Average Scroll Grade",
        "m_unique_authors": "Unique Sensei Counted",
        "m_all_status": "All Scroll Statuses",
        "m_first_favorite": "First Scroll Favorite",
        "m_favorites_collector": "Scroll Favorites Sealed",
        "m_days_spent_reading": "Days in the Scroll Archives",

        // ── MANGA BINGE (additions) ──
        "m_genre_binge": "Cross-Genre Scroll Binge",
        "m_author_binge": "Sensei Author Deep Dive",
        "m_chapter_counter_day": "Daily Seal Chapter Count",
        "m_multi_series_binge": "Multi-Series Scroll Front",
        "m_midnight_binge": "Midnight Scroll Immersion",
        "m_new_year_binge": "New Year's Scroll Burst",
        "m_forty_eight_hour": "Forty-Eight Hour Scroll Read",
        "m_oneshot_binge": "Oneshot Jutsu Blitz",

        // ── MANGA GENRES (additions) ──
        "m_tag_isekai_new": "Summoning Scroll World",
        "m_tag_harem": "Fan Club Scroll",
        "m_tag_bl": "Brotherly Scroll Bond",
        "m_tag_gl": "Kunoichi Scroll Sisters",
        "m_tag_historical": "Senju History Scroll",
        "m_tag_military": "Military Ninja Scroll",
        "m_tag_school": "Academy Scroll",
        "m_tag_martial_arts": "Taijutsu Combat Scroll",
        "m_tag_vampire": "Jashin Cult Scroll",
        "m_tag_samurai": "Land of Iron Scroll",
        "m_tag_space": "Dimension Rift Scroll",
        "m_tag_parody": "Chibi Leaf Scroll Parody",
        "m_tag_idol": "Village Pop Idol Scroll",
        "m_tag_post_apocalyptic": "Post-War Scroll",
        "m_tag_cyberpunk": "Sci-Ninja Tool Scroll",
        "m_tag_shoujo": "Sakura's Inner Scroll",
        "m_tag_survival": "Survival Scroll Arc",
        "m_tag_cooking": "Choji's Cookbook Scroll",
        "m_tag_medical": "Medical Nin Scroll",
        "m_tag_villainess": "Root Operative Scroll",

        // ── MANGA COMPLETION (additions) ──
        "m_multi_reread": "Multi-Pass Scroll Session",
        "m_dropped_recovery": "Scroll Comeback Jutsu",
        "m_ten_perfect_scores": "Ten Perfect Seal Grades",
        "m_complete_genre_span": "All Genre Scroll Scout",
        "m_monthly_completions": "Monthly Scroll Victories",
        "m_yearly_completions": "Yearly Scroll Campaign",
        "m_rapid_complete": "Shunshin Scroll Clear",
        "m_author_complete": "Sensei's Full Works Read",

        // ── MANGA DEDICATION (additions) ──
        "m_genre_master": "Genre Scroll Mastery",
        "m_multi_series_author": "Multi-Series Sensei Fan",
        "m_format_diversity": "Diverse Scroll Formats",
        "m_year_dedication": "Year of Scroll Dedication",
        "m_ongoing_follower": "Ongoing Scroll Follower",
        "m_genre_loyalty_50": "Fifty Chapter Genre Loyalty",

        // ── MANGA DISCOVERY (additions) ──
        "m_top_rated_reader": "Top-Ranked Scroll Source",
        "m_source_variety": "Source Scroll Diversity",
        "m_low_score_brave": "Low-Rank Scroll Courage",
        "m_short_manga_explorer": "Short Mission Scroll",
        "m_long_manga_explorer": "Long Campaign Scroll",
        "m_serialization_explorer": "Serialization Scroll Explorer",

        // ── MANGA TIME (additions) ──
        "m_weekend_binge_hours": "Weekend Scroll Training Ops",
        "m_late_night_regular": "Late Night Scroll Sentinel",
        "m_sunrise_reader": "Sunrise Over the Leaf Reader",
        "m_every_day_of_week": "Every Day Scroll Duty",
        "m_monthly_hours": "Monthly Scroll Hours Logged",
        "m_bedtime_reader": "Bedtime Barracks Scroll",

        // ── MANGA CREATIVE (additions) ──
        "m_vertical_scroll": "Vertical Scroll Format",
        "m_traditional_format": "Traditional Manga Format",
        "m_cross_media": "Cross-Media Ninja Intel",
        "m_spinoff_reader": "Spinoff Scroll Arc",
        "m_remake_reader": "Remake Scroll Mission",
        "m_collaboration_reader": "Joint Operation Scroll",

        // ── MANGA STREAKS (additions) ──
        "m_completion_streak": "Scroll Completion Chain",
        "m_rating_streak": "Scroll Rating Filed",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Sensei Dedication Streak",
        "m_perfect_week_manga": "Perfect Scroll Reading Week",
        "m_diverse_streak": "Diverse Scroll Streak",

        // ── MANGA SCORING (additions) ──
        "m_masterpiece_hunter": "Masterpiece Scroll Hunt",
        "m_contrarian": "Contrarian Scroll Opinion",
        "m_optimist": "Leaf Village Scroll Optimist",
        "m_score_distributor": "Score Distributor Sensei",
        "m_genre_critic": "Genre Scroll Critic",
        "m_mean_above_8": "Elite Scroll Average",

        // ── MANGA HOLIDAY (additions) ──
        "m_earth_day": "Earth Day Scroll Read",
        "m_labor_day": "Genin Labor Scroll Day",
        "m_winter_solstice": "Winter Solstice Scroll",
        "m_manga_birthday": "Manga Anniversary Ninja",
        "m_every_holiday_reader": "Every Festival Reader",
        "m_consecutive_holidays": "Consecutive Festival Reads",

        // ── MANGA SPECIAL (additions) ──
        "m_double_digits": "Double Digit Seal Read",
        "m_one_two_three": "Three Seals Pattern",
        "m_lucky_seven": "Seven Lucky Scroll Signs",
        "m_exact_hundred_ch": "Exactly One Hundred Scrolls",
        "m_year_match_count": "Year Match Seal Count",
        "m_chapter_match_date": "Chapter Date Alignment",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Korean Scroll Style",
        "m_manhua_format": "Chinese Scroll Style",
        "m_ln_format": "Light Novel Scroll",
        "m_oneshot_format": "Oneshot Seal Format",
        "m_doujin_format": "Underground Doujin Scroll",
        "m_novel_format": "Novel Scroll Format",
        "m_format_master_manga": "Format Master Scribe",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Scroll Power Unlocked",
        "m_meta_collector": "Scroll Badge Collector",
        "m_meta_category_starter": "Category Seal Initiation",
        "m_meta_tier_climber": "Scroll Rank Promotion",
        "m_meta_tier_max": "Kage-Rank Reading Level",
        "m_meta_xp_earner": "XP from Scroll Training",
        "m_meta_difficulty_easy": "Easy D-Rank Scroll",
        "m_meta_difficulty_hard": "S-Rank Scroll Challenge",
        "m_meta_unlock_spree": "Scroll Achievement Burst",
        "m_meta_completionist": "Meta Scroll Completionist",
        "m_meta_diverse": "Diverse Scroll Arsenal",
        "m_meta_dominator": "Scroll Meta Dominator",
    },
    musicUrl: "/public/themes/naruto-opening.mp3",
    previewColors: {
        bg: "#0a0400",
        primary: "#dc5000",
        secondary: "#f07010",
        accent: "#ff8c20",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/naruto.jpg",
    particleColor: "#dc5000",
    backgroundDim: 0.30,
    backgroundBlur: 30,
    particleTypes: {
        leaves: { label: "Falling Leaves", maxCount: 15, defaultEnabled: true, defaultIntensity: 60 },
        wisps: { label: "Chakra Wisps", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        kunai: { label: "Kunai & Shuriken", maxCount: 8, defaultEnabled: true, defaultIntensity: 45 },
        village: { label: "Village Silhouette", maxCount: 1, defaultEnabled: true, defaultIntensity: 50 },
        sharingan: { label: "Sharingan Watermark", maxCount: 1, defaultEnabled: true, defaultIntensity: 50 },
    },
    playerIconOverrides: narutoPlayerIcons,
    milestoneNames: {
        1:   "Academy Student",
        5:   "Genin",
        15:  "Chunin",
        25:  "Tokubetsu Jonin",
        35:  "Jonin",
        45:  "ANBU",
        60:  "Kage",
        80:  "Sage Mode",
        100: "Otsutsuki",
    },
}
