import { AnimeThemeConfig } from "./types"
import { GiRobotGolem, GiCat, GiDeer, GiMilkCarton, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiPencilBrush } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const nichijouTheme: AnimeThemeConfig = {
    id: "nichijou",
    displayName: "Nichijou",
    description: "Three high school girls live hilariously mundane lives alongside Nano, a robot who goes to their school, the young Professor who built her, and Sakamoto — a cat who can talk. Daily life has never been so dramatic or absurd.",
    fontFamily: "'Quicksand', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600;700&display=swap",
    cssVars: {
        "--color-brand-200": "218 185 240",
        "--color-brand-300": "195 148 232",
        "--color-brand-400": "170 108 218",
        "--color-brand-500": "145 68 200",
        "--color-brand-600": "115 42 170",
        "--color-brand-700": "85 22 135",
        "--color-brand-800": "56 8 100",
        "--color-brand-900": "28 2 60",
        "--color-brand-950": "12 0 28",
        "--brand": "145 68 200",
        "--background": "#040206",
        "--paper": "#0a050e",
        "--color-gray-950": "4 2 6",
        "--color-gray-900": "10 5 14",
        "--color-gray-800": "18 10 24",
        "--color-gray-700": "30 18 40",
        "--color-gray-600": "50 30 65",
        "--color-gray-500": "80 52 100",
        "--color-gray-400": "120 85 148",
        "--color-gray-300": "162 128 192",
        "--color-gray-200": "198 170 225",
        "--color-gray-100": "222 205 240",
        "--color-gray-50": "240 230 250",
    },
    sidebarOverrides: {
        "home": { icon: GiRobotGolem, label: "Nano's World" },
        "schedule": { icon: GiAlarmClock, label: "Class Schedule" },
        "manga": { icon: LuBookOpen, label: "Arawi's Manga" },
        "lists": { icon: GiPencilBrush, label: "Daily Events" },
        "discover": { icon: GiBullseye, label: "New Moments" },
        "torrent-list": { icon: GiCat, label: "Sakamoto's Picks" },
        "debrid": { icon: GiDeer, label: "Nano's Store" },
        "unmatched": { icon: GiMilkCarton, label: "Lost Episodes" },
        "enmasse": { icon: GiResize, label: "School Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Daily Reports" },
        "auto-downloader": { icon: LuRss, label: "Life Feed" },
        "community": { icon: GiRobotGolem, label: "Hakase's Lab" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Daily Alerts" },
        "achievements": { icon: GiTrophy, label: "Daily Trophies" },
        "milestones": { icon: LuFlag, label: "Daily Goals" },
        "theme-manager": { icon: GiPalette, label: "Pastel Colors" },
        "extensions": { icon: BiExtension, label: "Robot Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Daily Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Nano's Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Day",
        "a_first_complete": "Graduation",
        "a_hundred_club": "Hundred Episodes",
        "a_time_lord": "Daily Life Veteran",
        "a_anime_collector": "Episode Collection",
        "a_library_legend": "Nichijou Archives",
        "a_binge_king": "Daily Marathon",
        "a_no_sleep": "All-Night Laughs",
        "a_marathon_runner": "Long School Day",
        "a_speed_run": "Yuuko's Speed",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Arawi Master",
        "a_loyal_fan": "Nano's Friend",
        "a_rewatcher": "Daily Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Over-Dramatic Action",
        "a_genre_adventure": "Town Exploration",
        "a_genre_comedy": "Absurd Humor",
        "a_genre_drama": "Daily Drama",
        "a_genre_fantasy": "Deer Fantasy",
        "a_genre_horror": "Daiku-Sensei Horror",
        "a_genre_romance": "Mio Likes Somebody",
        "a_genre_scifi": "Nano's Science",
        "a_genre_supernatural": "Talking Cat",
        "a_genre_psychological": "Deep Thoughts",
        "a_genre_mecha": "Nano Robot",
        "a_critic": "Absurdist Critic",
        "a_perfect_ten": "Perfect Daily Life",
        "a_harsh_critic": "Yukko's Standard",
        "a_daily_streak": "Truly Daily",
        "a_mega_streak": "Endless Days",
        "a_year_long": "Year of Dailies",
        "a_iron_will": "Nano's Determination",
        "a_hidden_gem": "Hidden Sketch",
        "a_cult_classic": "KyoAni Classic",
        "a_classic_connoisseur": "2011 Fan",
        "a_new_years_resolution": "New Year Sketch",
        "a_christmas_special": "Winter Daily",
        "a_meta_tier_max": "Nichijou Legend",
        "a_meta_completionist": "All Sketches",
        "a_sequel_chain": "Manga Continues",
        "a_zero_to_hero": "Ordinary to Extraordinary",
        "a_night_owl": "Night Daily",
        "a_early_bird": "Morning Class",
        "m_first_chapter": "First Sketch",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Daily Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Nichijou Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Daily Return",
        "m_genre_action": "Dramatic Sketch",
        "m_genre_adventure": "Town Sketch",
        "m_genre_romance": "Mio's Chapter",
        "m_genre_fantasy": "Robot Chapter",
        "m_genre_horror": "Shark Chapter",
        "m_genre_drama": "Mai's Chapter",
        "m_genre_scifi": "Nano's Chapter",
        "m_genre_supernatural": "Sakamoto's Chapter",
        "m_genre_psychological": "Deep Daily",
        "m_critic": "Sketch Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Daily Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Nano Resolve",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "KyoAni Classic",
        "m_mangaka_lover": "Arawi Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Nichijou Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Arawi's Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040206",
        primary: "#9144c8",
        secondary: "#732aaa",
        accent: "#f0a020",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/nichijou.jpg",
    particleColor: "#c080e0",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        kawaii_sparkles: { label: "Kawaii Sparkles", maxCount: 20, defaultEnabled: true, defaultIntensity: 60 },
        screw_bolts: { label: "Nano's Screws", maxCount: 8, defaultEnabled: true, defaultIntensity: 35 },
    },
    milestoneNames: {
        1: "Transfer Student",
        5: "Yuuko Aioi",
        15: "Nano's Screw",
        30: "Class Regular",
        50: "Hakase's Lab",
        75: "Daily Life Hero",
        100: "Nichijou Legend",
    },
}
