import { AnimeThemeConfig } from "./types"
import { GiMicrophone, GiStarFormation, GiFilmProjector, GiStarMedal, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiDramaMasks, GiHeartKey, GiDiamondRing } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const oshinoKoTheme: AnimeThemeConfig = {
    id: "oshi-no-ko",
    displayName: "Oshi no Ko",
    description: "Doctor Gorou Amemiya is reincarnated as the son of his idol Ai Hoshino, entering the brutal world of entertainment and vowing to uncover the dark secrets of the industry that shattered his new family.",
    fontFamily: "'Noto Serif JP', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 176 238",
        "--color-brand-300": "250 120 220",
        "--color-brand-400": "238 64 195",
        "--color-brand-500": "208 22 162",
        "--color-brand-600": "165 0 128",
        "--color-brand-700": "120 0 94",
        "--color-brand-800": "78 0 60",
        "--color-brand-900": "40 0 32",
        "--color-brand-950": "16 0 14",
        "--brand": "208 22 162",
        "--background": "#030004",
        "--paper": "#0a0010",
        "--color-gray-950": "3 0 4",
        "--color-gray-900": "8 0 12",
        "--color-gray-800": "18 4 24",
        "--color-gray-700": "32 10 42",
        "--color-gray-600": "52 20 68",
        "--color-gray-500": "85 38 108",
        "--color-gray-400": "128 72 155",
        "--color-gray-300": "170 112 198",
        "--color-gray-200": "208 158 232",
        "--color-gray-100": "232 198 248",
        "--color-gray-50": "248 232 255",
    },
    sidebarOverrides: {
        "home": { icon: GiStarFormation, label: "Idol Stage" },
        "schedule": { icon: GiAlarmClock, label: "Showtime" },
        "manga": { icon: LuBookOpen, label: "Scripts" },
        "lists": { icon: GiFlowerEmblem, label: "Idol Registry" },
        "discover": { icon: GiBullseye, label: "New Stars" },
        "torrent-list": { icon: GiFilmProjector, label: "Reel Cache" },
        "debrid": { icon: GiDramaMasks, label: "Secret Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Idols" },
        "enmasse": { icon: GiResize, label: "Agency Op" },
        "scan-summaries": { icon: TbReportSearch, label: "Audit Reports" },
        "auto-downloader": { icon: LuRss, label: "Agency Feed" },
        "community": { icon: GiMicrophone, label: "Fan Circle" },
        "achievements": { icon: GiTrophy, label: "Star Awards" },
        "milestones": { icon: LuFlag, label: "Career Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Industry Alerts" },
        "theme-manager": { icon: GiPalette, label: "Star Palette" },
        "extensions": { icon: BiExtension, label: "Industry Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Star Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Aqua's Config" },
    },
    achievementNames: {
        "a_first_episode": "Curtains Rise",
        "a_first_complete": "Show Complete",
        "a_hundred_club": "Hundred Stars",
        "a_time_lord": "Industry Veteran",
        "a_anime_collector": "Star Archive",
        "a_library_legend": "Script Library",
        "a_binge_king": "Stage Marathon",
        "a_no_sleep": "All-Night Stage",
        "a_marathon_runner": "Ruby's Run",
        "a_speed_run": "Aqua's Speed",
        "a_completionist": "Full Performance",
        "a_mega_completionist": "Idol Master",
        "a_loyal_fan": "True Fan",
        "a_rewatcher": "Encore Viewer",
        "a_decade_watcher": "Decade on Stage",
        "a_genre_action": "Stage Action",
        "a_genre_adventure": "Industry Journey",
        "a_genre_comedy": "Idol Comedy",
        "a_genre_drama": "Industry Drama",
        "a_genre_fantasy": "Star Dream",
        "a_genre_horror": "Dark Industry",
        "a_genre_romance": "Idol Love",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Starlit Spirit",
        "a_genre_psychological": "Aqua's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Industry Critic",
        "a_perfect_ten": "Perfect Score",
        "a_harsh_critic": "Ai's Standard",
        "a_daily_streak": "Daily Spotlight",
        "a_mega_streak": "Eternal Spotlight",
        "a_year_long": "Year on Stage",
        "a_iron_will": "Aqua's Drive",
        "a_hidden_gem": "Hidden Star",
        "a_cult_classic": "Idol Classic",
        "a_classic_connoisseur": "2023 Fan",
        "a_new_years_resolution": "New Year Star",
        "a_christmas_special": "Winter Concert",
        "a_meta_tier_max": "True Star",
        "a_meta_completionist": "All Stars",
        "a_sequel_chain": "Aqua's Chain",
        "a_zero_to_hero": "Fan to Star",
        "a_night_owl": "Night Performer",
        "a_early_bird": "Dawn Rehearsal",
        "m_first_chapter": "First Act",
        "m_first_complete": "Arc Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Stage Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Oshi Expert",
        "m_loyal_reader": "Devoted Fan",
        "m_rereader": "Encore Read",
        "m_genre_action": "Action Act",
        "m_genre_adventure": "Journey Act",
        "m_genre_romance": "Love Act",
        "m_genre_fantasy": "Star Act",
        "m_genre_horror": "Dark Act",
        "m_genre_drama": "Drama Act",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "Spirit Act",
        "m_genre_psychological": "Inner Act",
        "m_critic": "Ai's Review",
        "m_perfect_ten": "Perfect Act",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Star Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Resolve",
        "m_hidden_gem": "Hidden Act",
        "m_cult_classic": "Timeless Act",
        "m_mangaka_lover": "Aka Akasaka Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Oshi Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Star Beauty",
        "m_manga_to_anime": "Adapted Star",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030004",
        primary: "#d016a2",
        secondary: "#a50080",
        accent: "#40d0e8",
    },
    particleColor: "#e840c8",
    backgroundDim: 0.30,
    backgroundBlur: 18,
    particleTypes: {
        star_fragments: { label: "Star Fragments", maxCount: 20, defaultEnabled: true, defaultIntensity: 58 },
        sparkles: { label: "Stage Sparkles", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1: "Fan in the Dark",
        5: "New Hopeful",
        15: "Agency Recruit",
        30: "Rising Star",
        50: "Industry Pro",
        75: "Star Performer",
        100: "Ai's Legacy",
    },
}
