import { AnimeThemeConfig } from "./types"
import { GiRose, GiCrown, GiGoldBar, GiCherish, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiDiamondHard } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const ouranHostClubTheme: AnimeThemeConfig = {
    id: "ouran-host-club",
    displayName: "Ouran High School Host Club",
    description: "When scholarship student Haruhi breaks an expensive vase, she's forced to join the Host Club — a group of rich, eccentric boys who entertain female clients. A reverse harem comedy with real heart.",
    fontFamily: "'Playfair Display', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400&display=swap",
    cssVars: {
        "--color-brand-200": "255 228 190",
        "--color-brand-300": "248 204 148",
        "--color-brand-400": "235 176 100",
        "--color-brand-500": "218 146 52",
        "--color-brand-600": "180 116 30",
        "--color-brand-700": "140 88 16",
        "--color-brand-800": "100 62 8",
        "--color-brand-900": "60 36 3",
        "--color-brand-950": "34 20 1",
        "--brand": "218 146 52",
        "--background": "#060500",
        "--paper": "#100e02",
        "--color-gray-950": "6 5 0",
        "--color-gray-900": "14 12 2",
        "--color-gray-800": "26 22 6",
        "--color-gray-700": "44 38 12",
        "--color-gray-600": "68 60 24",
        "--color-gray-500": "105 95 48",
        "--color-gray-400": "148 138 92",
        "--color-gray-300": "186 178 138",
        "--color-gray-200": "214 208 175",
        "--color-gray-100": "232 228 208",
        "--color-gray-50": "246 244 235",
    },
    sidebarOverrides: {
        "home": { icon: GiRose, label: "Music Room 3" },
        "schedule": { icon: GiAlarmClock, label: "Club Schedule" },
        "manga": { icon: LuBookOpen, label: "Club Records" },
        "lists": { icon: GiCrown, label: "Host Registry" },
        "discover": { icon: GiBullseye, label: "New Clients" },
        "torrent-list": { icon: GiGoldBar, label: "Club Treasury" },
        "debrid": { icon: GiDiamondHard, label: "Elite Store" },
        "unmatched": { icon: GiCherish, label: "New Members" },
        "enmasse": { icon: GiResize, label: "Club Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Guest Reports" },
        "auto-downloader": { icon: LuRss, label: "Club Announcements" },
        "community": { icon: GiRose, label: "Host Club" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Club Bells" },
        "achievements": { icon: GiTrophy, label: "Elite Trophies" },
        "milestones": { icon: LuFlag, label: "Host Goals" },
        "theme-manager": { icon: GiPalette, label: "Club Colors" },
        "extensions": { icon: BiExtension, label: "Host Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Club Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Tamaki's Rules" },
    },
    achievementNames: {
        "a_first_episode": "Welcome, Princess",
        "a_first_complete": "Host Club Complete",
        "a_hundred_club": "Hundred Guests",
        "a_time_lord": "Host Club Veteran",
        "a_anime_collector": "Rose Collection",
        "a_library_legend": "Club Archives",
        "a_binge_king": "Club Marathon",
        "a_no_sleep": "All-Night Hosting",
        "a_marathon_runner": "Endless Events",
        "a_speed_run": "Twins Trick",
        "a_completionist": "All Members",
        "a_mega_completionist": "Hatori Master",
        "a_loyal_fan": "Haruhi's Friend",
        "a_rewatcher": "Club Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Karate Haruhi",
        "a_genre_adventure": "Club Field Trip",
        "a_genre_comedy": "Tamaki's Antics",
        "a_genre_drama": "Family Secrets",
        "a_genre_fantasy": "Host World",
        "a_genre_horror": "Mother Control",
        "a_genre_romance": "Haruhi's Heart",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "Nekozawa Cult",
        "a_genre_psychological": "Kyoya's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Host Judge",
        "a_perfect_ten": "Top Host",
        "a_harsh_critic": "Kyoya's Review",
        "a_daily_streak": "Daily Club",
        "a_mega_streak": "Endless Hosting",
        "a_year_long": "Full Club Year",
        "a_iron_will": "Haruhi's Independence",
        "a_hidden_gem": "Hidden Episode",
        "a_cult_classic": "Hatori Classic",
        "a_classic_connoisseur": "2006 Fan",
        "a_new_years_resolution": "New Year Club",
        "a_christmas_special": "Holiday Ball",
        "a_meta_tier_max": "Tamaki's Daddy",
        "a_meta_completionist": "Complete Club",
        "a_sequel_chain": "Manga Continues",
        "a_zero_to_hero": "Commoner to Host",
        "a_night_owl": "Night Club",
        "a_early_bird": "Morning Rose",
        "m_first_chapter": "First Guest",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Club Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Host Expert",
        "m_loyal_reader": "Club Reader",
        "m_rereader": "Club Return",
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Trip Chapter",
        "m_genre_romance": "Love Chapter",
        "m_genre_fantasy": "Club World",
        "m_genre_horror": "Drama Chapter",
        "m_genre_drama": "Family Chapter",
        "m_genre_scifi": "Unusual Chapter",
        "m_genre_supernatural": "Nekozawa Chapter",
        "m_genre_psychological": "Kyoya Chapter",
        "m_critic": "Host Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Club Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Haruhi Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Comedy",
        "m_mangaka_lover": "Hatori Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Host Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Rose Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060500",
        primary: "#da9234",
        secondary: "#8c5810",
        accent: "#e0a0c8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/ouran-host-club.jpg",
    particleColor: "#f8c860",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        rose_petals: { label: "Rose Petals", maxCount: 20, defaultEnabled: true, defaultIntensity: 60 },
        sparkles: { label: "Elite Sparkles", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
        1: "Scholarship Student",
        5: "Haruhi",
        15: "Host Member",
        30: "Popular Host",
        50: "Club Insider",
        75: "Host Legend",
        100: "Ouran Elite",
    },
}
