import { AnimeThemeConfig } from "./types"
import {
    GiSkullCrack, GiKeyLock, GiCrown, GiDeathZone,
    GiScrollUnfurled, GiSpellBook, GiCastle, GiHourglass,
    GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss } from "react-icons/lu"
import { BiExtension } from "react-icons/bi"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { TbReportSearch } from "react-icons/tb"

export const overlordTheme: AnimeThemeConfig = {
    id: "overlord",
    displayName: "Overlord",
    description: "Momonga's unmatched supremacy. Dark overlord black & bone gold.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700;900&display=swap",
    cssVars: {
        "--color-brand-200": "215 195 130",
        "--color-brand-300": "185 158 75",
        "--color-brand-400": "155 122 30",
        "--color-brand-500": "122 90 8",
        "--color-brand-600": "92 65 2",
        "--color-brand-700": "65 44 0",
        "--color-brand-800": "42 28 0",
        "--color-brand-900": "24 15 0",
        "--color-brand-950": "10 6 0",
        "--brand": "135 98 14",
        "--background": "#030200",
        "--paper": "#080600",
        "--color-gray-950": "3 2 0",
        "--color-gray-900": "8 6 0",
        "--color-gray-800": "18 14 2",
        "--color-gray-700": "30 24 5",
        "--color-gray-600": "50 40 10",
        "--color-gray-500": "82 65 22",
        "--color-gray-400": "130 105 50",
        "--color-gray-300": "175 148 90",
        "--color-gray-200": "215 192 138",
        "--color-gray-100": "240 228 190",
        "--color-gray-50":  "252 248 238",
    },
    sidebarOverrides: {
        "home":           { icon: GiCastle,        label: "Nazarick" },
        "schedule":       { icon: GiAlarmClock,    label: "Overlord's Schedule" },
        "manga":          { icon: GiScrollUnfurled,label: "Supreme Being Files" },
        "lists":          { icon: GiSpellBook,     label: "Floor Guardian Registry" },
        "discover":       { icon: GiDeathZone,     label: "World Conquest" },
        "torrent-list":   { icon: GiKeyLock,       label: "Ainz's Operations" },
        "unmatched":      { icon: GiSkullCrack,         label: "The Unmatched" },
        "scan-summaries": { icon: TbReportSearch,  label: "Nazarick Reports" },
        "auto-downloader":{ icon: LuRss,           label: "Intelligence Feed" },
        "search":         { icon: FiSearch,        label: "Search" },
        "notifications":  { icon: LuBell,          label: "Overlord Decrees" },
        "achievements":   { icon: GiCrown,         label: "World Champion Tier" },
        "theme-manager":  { icon: GiPalette,       label: "Tomb Colors" },
        "extensions":     { icon: BiExtension,     label: "Contracts" },
        "settings":       { icon: GiSettingsKnobs, label: "Ainz Ooal Gown Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode":            "Logged Into Yggdrasil",
        "a_episode_counter":          "World Items Collected",
        "a_episode_titan":            "Yggdrasil World Domination",
        "a_hours_invested":           "Nazarick Vigil Hours",
        "a_time_lord":                "Ainz's Timeless Memory",
        "a_anime_collector":          "Nazarick Archive",
        "a_library_legend":           "Supreme Being Archive",
        "a_first_complete":           "First Arc Conquered",
        "a_hundred_club":             "Nazarick Resident",
        "a_first_day":                "Enlistment in Nazarick",
        "a_first_rating":             "Floor Guardian Rating",
        "a_ten_thousand_min":         "Ten Thousand Undead Minutes",
        "a_season_veteran":           "Veteran Floor Guardian",
        "a_year_explorer":            "Year of Conquest",
        "a_century_watcher":          "Century of Domination",
        "a_five_hundred_eps":         "Five Hundred Undead Acts",
        "a_thousand_eps":             "Thousand Nazarick Encounters",
        "a_watching_ten":             "Ten Fronts of Nazarick",
        "a_ptw_hoarder":              "Nazarick Treasury Hoarder",
        "a_dropped_honesty":          "Retreat to the Tomb",
        "a_five_thousand_eps":        "Five Thousand Undead Sorties",
        "a_ten_completed":            "Ten Dungeons Cleared",
        "a_fifty_completed":          "Fifty Conquests Completed",
        "a_five_hundred_completed":   "Five Hundred Victories for Ainz",
        "a_mean_score_tracker":       "Average Guardian Ranking",
        "a_unique_studios":           "Unique Guild Alliances",
        "a_days_spent_watching":      "Days Defending Nazarick",
        "a_all_status":               "All Undead Statuses",
        "a_first_favorite":           "First Supreme Bond",
        "a_favorites_collector":      "Bonds of Nazarick",

        // ── ANIME BINGE ──
        "a_binge_watcher":            "Ainz's Conquest Marathon",
        "a_marathon_runner":          "Tomb-to-Tomb Marathon",
        "a_weekend_warrior":          "Weekend Warrior of Nazarick",
        "a_non_stop":                 "Relentless Undead Advance",
        "a_one_more_episode":         "One More Conquest",
        "a_speed_run":                "Shalltear Speed Assault",
        "a_double_feature":           "Double Floor Assault",
        "a_triple_threat":            "Triple Guardian Takedown",
        "a_five_a_day":               "Five Floors a Day",
        "a_back_to_back":             "Back-to-Back Domination",
        "a_seasonal_binge":           "Full Campaign Arc",
        "a_cour_crusher":             "Floor Crusher",
        "a_half_day_watch":           "Half-Day Undead Vigil",
        "a_full_day_watch":           "Full Day in Nazarick",
        "a_power_weekend":            "Power Weekend Conquest",
        "a_binge_king":               "Overlord of Binge Ops",
        "a_no_sleep":                 "All-Night Undead Vigil",
        "a_entire_season":            "Rapid Dungeon Clear",
        "a_seven_day_challenge":      "Seven-Day Nazarick Siege",
        "a_hundred_day_binge":        "Hundred-Day Undead Siege",
        "a_genre_binge":              "Cross-Floor Training",
        "a_studio_binge":             "Supreme Guild Binge",
        "a_season_sweep":             "Season Sweep Conquest",
        "a_forty_eight_hour":         "Forty-Eight Hour Standoff",
        "a_ep_counter_day":           "Daily Floor Count",
        "a_multi_series_binge":       "Multi-Dungeon Campaign",
        "a_midnight_binge":           "Midnight Tomb Session",
        "a_new_year_binge":           "New Year's Domination",

        // ── ANIME GENRES ──
        "a_genre_action":             "Floor Guardian Combat",
        "a_genre_adventure":          "Beyond Nazarick's Walls",
        "a_genre_comedy":             "Ainz's Accidental Blunder",
        "a_genre_drama":              "Ainz's Loneliness",
        "a_genre_fantasy":            "Isekai Overlord",
        "a_genre_horror":             "Undead Terror",
        "a_genre_mystery":            "Tomb's Hidden Secrets",
        "a_genre_romance":            "Albedo's Devotion",
        "a_genre_scifi":              "Yggdrasil Technology",
        "a_genre_sol":                "Life in Nazarick",
        "a_genre_sports":             "Floor Guardian Training",
        "a_genre_supernatural":       "Supreme Being Power",
        "a_genre_thriller":           "Demiurge's Calculated Plans",
        "a_genre_mecha":              "Nazarick Golem Corps",
        "a_genre_music":              "Nazarick Hymns",
        "a_genre_psychological":      "Demiurge's Inner Plans",
        "a_genre_ecchi":              "Albedo's Obsession",
        "a_genre_mahou_shoujo":       "World Item Wielder",
        "a_tag_isekai":               "Transported to New World",
        "a_tag_harem":                "Pleiades Battle Maids",
        "a_tag_bl":                   "Nazarick Brothers Bond",
        "a_tag_gl":                   "Shalltear's Dark Sisters",
        "a_tag_historical":           "Yggdrasil's Ancient History",
        "a_tag_military":             "Undead Army Discipline",
        "a_tag_school":               "NPC Academy Nazarick",
        "a_tag_martial_arts":         "Gazef's Combat Style",
        "a_tag_vampire":              "Shalltear Bloodfallen",
        "a_tag_samurai":              "Ainz's Blade Mastery",
        "a_tag_space":                "Beyond the New World",
        "a_tag_parody":               "Chibi Nazarick Shorts",
        "a_tag_idol":                 "Floor Guardian Idol",
        "a_tag_post_apocalyptic":     "Post-World Collapse Era",
        "a_tag_cyberpunk":            "Yggdrasil Tech Uprising",
        "a_tag_shounen":              "Dedicate Soul to Ainz",
        "a_tag_seinen":               "Dark Reality of Nazarick",
        "a_tag_shoujo":               "Mare's Hidden Secret",
        "a_tag_josei":                "Shalltear's Obsession",
        "a_tag_survival":             "Survival in New World",

        // ── ANIME COMPLETION ──
        "a_completionist":            "Full Nazarick Expedition",
        "a_mega_completionist":       "Supreme Overlord",
        "a_completion_rate_50":       "Halfway to Total Domination",
        "a_completion_rate_75":       "Approaching Ainz's Throne",
        "a_completion_rate_90":       "Paths Nearly Conquered",
        "a_no_drop":                  "No Floor Abandoned",
        "a_long_runner_complete":     "Long Campaign Endurance",
        "a_sequel_chain":             "Nazarick Chain Command",
        "a_clean_list":               "Clean Guild Record",
        "a_from_ptw":                 "Orders Received Executed",
        "a_rewatch_master":           "Re-Enter Yggdrasil",
        "a_short_complete":           "Quick Skirmish Victory",
        "a_same_day_start_finish":    "Same-Day Dungeon Clear",
        "a_revival":                  "Revived by Ainz's Power",
        "a_zero_to_hero":             "NPC to Guardian",
        "a_five_genre_complete":      "Five-Floor Mastery",
        "a_full_franchise":           "Full Nazarick Dossier",
        "a_batch_complete":           "Batch Deployment Clear",
        "a_paused_to_done":           "Returned from Tomb Rest",
        "a_completion_spree":         "Completion Bone Barrage",
        "a_multi_rewatch":            "Multi-Timeline Domination",
        "a_dropped_recovery":         "Recovered from Nazarick",
        "a_ten_perfect_scores":       "Ten Perfect Undead Scores",
        "a_seasonal_clear":           "Seasonal Conquest Clear",
        "a_complete_genre_span":      "All-Terrain Overlord",
        "a_monthly_completions":      "Monthly Dungeon Reports",
        "a_yearly_completions":       "Yearly Campaign Victor",
        "a_rapid_complete":           "Lightning Domination Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan":                "Sworn to Ainz Ooal Gown",
        "a_studio_devotee":           "Supreme Being Devotee",
        "a_rewatcher":                "Nazarick Recon Rewatch",
        "a_triple_rewatch":           "Triple Dungeon Rewatch",
        "a_annual_tradition":         "Annual Remembrance Nazarick",
        "a_director_fan":             "Maruyama's Vision Follower",
        "a_voice_actor_fan":          "Voice of the Guardians",
        "a_ost_lover":                "Nazarick Hymn Lover",
        "a_source_reader":            "Original Overlord Texts",
        "a_waiting_weekly":           "Weekly Domination Signal Wait",
        "a_childhood_revisit":        "Return to Nazarick",
        "a_saga_tracker":             "Saga of Ainz Tracker",
        "a_genre_loyalty":            "Guardian Loyalty Badge",
        "a_decade_watcher":           "Decade-Long Overlord",
        "a_adaptation_hunter":        "Adaptation Reconnaissance",
        "a_original_anime_fan":       "Original Broadcast Veteran",
        "a_long_commitment":          "Long-Term Undead Duty",
        "a_perfect_attendance":       "Perfect Formation Attendance",
        "a_favorite_studio_5":        "Five Allied Studios",
        "a_complete_catalog":         "Complete Nazarick Catalog",
        "a_franchise_collector":      "Overlord Universe Collector",
        "a_airing_follower":          "Currently Airing Intel",
        "a_genre_master":             "Genre Mastery Achieved",
        "a_staff_follower":           "Staff Dossier Tracker",
        "a_multi_season_fan":         "Multi-Season Veteran",
        "a_format_diversity":         "Diverse Tactical Formats",
        "a_year_dedication":          "Year of Dedication to Ainz",
        "a_season_dedication":        "Season of Unwavering Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer":           "Scout Beyond Nazarick",
        "a_studio_hopper":            "Guild Regiment Transfer",
        "a_tag_explorer":             "Nazarick Tag Recon",
        "a_decade_hopper":            "Time via Ainz's Magic",
        "a_hidden_gem":               "Hidden Nazarick Treasure",
        "a_popular_taste":            "Popular Among NPCs",
        "a_retro_appreciator":        "Pre-Tomb Era Appreciator",
        "a_modern_viewer":            "Modern New World Viewer",
        "a_cross_demographic":        "Cross-Demographic Guardian",
        "a_underdog_fan":             "Underdog NPC Spirit",
        "a_variety_week":             "Week of Varied Floors",
        "a_foreign_cinema":           "Foreign World Cinema",
        "a_classic_connoisseur":      "Classic Yggdrasil Connoisseur",
        "a_every_season":             "Every Season Conquered",
        "a_award_winner":             "Nazarick Medal of Honor",
        "a_niche_explorer":           "Niche Territory Explorer",
        "a_global_anime":             "Global Alliance Entry",
        "a_cult_classic":             "Underground Tomb Classic",
        "a_random_pick":              "Random Mission Assignment",
        "a_new_genre_month":          "New Floor Monthly",
        "a_seasonal_completionist":   "Seasonal Campaign Clear",
        "a_unpopular_opinion":        "Unpopular Ainz Opinion",
        "a_top_rated_viewer":         "Top-Rated Nazarick Source",
        "a_source_variety":           "Source Material Variety",
        "a_low_score_brave":          "Brave Charge Low Scores",
        "a_upcoming_watcher":         "Upcoming Operation Intel",
        "a_short_series_explorer":    "Short Dungeon Explorer",
        "a_long_series_explorer":     "Long Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl":                "Undead Night Session",
        "a_early_bird":               "Dawn Patrol Nazarick",
        "a_lunch_break":              "Nazarick Mess Hall",
        "a_golden_hour":              "Golden Hour Bone Magic",
        "a_four_am_club":             "4 AM Undead Sentry",
        "a_witching_hour":            "Undead Witching Hour",
        "a_new_year_watch":           "New Year's Oath to Ainz",
        "a_midnight_premiere":        "Midnight Tomb Deployment",
        "a_all_hours":                "All-Hours Overlord",
        "a_dawn_warrior":             "Dawn Warrior Undead",
        "a_afternoon_delight":        "Afternoon Floor Drill",
        "a_prime_time":               "Prime Time Domination",
        "a_workday_watcher":          "On-Duty Watcher",
        "a_sunday_marathon":          "Sunday Dungeon Marathon",
        "a_rainy_day":                "Rainy Day in Tomb",
        "a_morning_routine":          "Morning Tomb Formation",
        "a_night_shift":              "Night Shift Undead Guard",
        "a_twilight_zone":            "Twilight Beyond Nazarick",
        "a_seasonal_premier":         "Season Premiere Conquest",
        "a_clock_collector":          "Clock Tower Collector",
        "a_weekend_binge_hours":      "Weekend Binge Operations",
        "a_late_night_regular":       "Late Night Undead Patrol",
        "a_sunrise_watcher":          "Sunrise Over Nazarick",
        "a_holiday_watcher":          "Holiday Tomb Guard",
        "a_every_day_of_week":        "Every Day Deployed",
        "a_monthly_hours":            "Monthly Undead Hours",

        // ── ANIME SOCIAL ──
        "a_first_party":              "First Nazarick Formation",
        "a_party_host":               "Dungeon Floor Commander",
        "a_social_butterfly":         "Nazarick Socialite",
        "a_group_binge":              "Group Undead Volley",
        "a_party_regular":            "Regular Guild Partner",
        "a_sync_viewer":              "Synchronized Tomb Maneuver",
        "a_commentator":              "Nazarick Battle Commentator",
        "a_party_marathon":           "Marathon Formation Run",
        "a_full_house":               "Full Nazarick Assembled",
        "a_community_pillar":         "Pillar of the Guild",
        "a_watch_party_streak":       "Consecutive Guardian Streak",
        "a_diverse_party":            "Diverse Nazarick Party",
        "a_late_night_party":         "Late Night Tomb Party",
        "a_party_veteran":            "Veteran Guardian Leader",
        "a_genre_party":              "Cross-Genre Formation",
        "a_weekly_party":             "Weekly Guardians' Gathering",
        "a_silent_viewer":            "Silent Ainz Observer",
        "a_recommendation_giver":     "Overlord's Recommendation",
        "a_party_completionist":      "Party Conquest Completionist",
        "a_social_scorer":            "Social Guardian Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number":             "Round Number Formation",
        "a_fibonacci":                "Fibonacci Undead Sequence",
        "a_palindrome_day":           "Palindrome Time Rift",
        "a_binary_day":               "Binary Nazarick Signal",
        "a_full_moon":                "Full Moon Undead Transformation",
        "a_leap_year":                "Leap Year Time Skip",
        "a_time_traveler":            "Ainz's Future Memory",
        "a_genre_clash":              "Overlord vs World Clash",
        "a_triple_seven":             "Triple Seven Floors",
        "a_thousand_complete":        "Thousand Battles for Ainz",
        "a_pi_episodes":              "Pi Tomb Calculation",
        "a_synchronicity":            "Nazarick Synchronicity",
        "a_world_record":             "World Record Undead Kill",
        "a_nice":                     "Nice Kill Count",
        "a_power_level":              "Ainz Power Level",
        "a_answer_42":                "The Answer to Nazarick",
        "a_square_number":            "Perfect Tomb Formation",
        "a_prime_count":              "Prime Undead Slain Count",
        "a_matching_date":            "Matching Nazarick Date",
        "a_century_episode":          "Century Episode Conquest",
        "a_double_digits":            "Double Digit Kills",
        "a_one_two_three":            "Floors One Two Three",
        "a_lucky_seven":              "Seven Lucky Guardians",
        "a_all_tens":                 "All Tens Combat Score",
        "a_exact_hundred_eps":        "Exact Hundred Engagements",
        "a_year_match_count":         "Year Match Kill Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher":               "TV Broadcast Overlord",
        "a_movie_buff":               "Nazarick Movie Operations",
        "a_ova_hunter":               "OVA Pleiades Hunter",
        "a_ona_explorer":             "ONA Scout Explorer",
        "a_special_watcher":          "Special Episode Operative",
        "a_short_king":               "Short Engagement King",
        "a_variety_pack":             "All-Format Guardian",
        "a_film_festival":            "Nazarick Film Festival",
        "a_music_video":              "Nazarick Hymn Collection",
        "a_tv_short":                 "Quick Recon Clip",
        "a_movie_marathon":           "Movie Marathon Blitz",
        "a_double_length":            "Double-Length Conquest",
        "a_anthology":                "Nazarick Anthology",
        "a_mini_series":              "Mini Campaign Collection",
        "a_theatrical":               "Theatrical Deployment",
        "a_format_master":            "Format Master Overlord",
        "a_long_movie":               "Feature-Length Expedition",
        "a_back_catalog":             "Back Catalog Tomb Files",
        "a_cm_watcher":               "Commercial Break Watcher",
        "a_pv_collector":             "Preview Signal Collector",
        "a_format_balance":           "Balanced Tactical Formats",
        "a_episodic_master":          "Episodic Campaign Master",
        "a_sequel_movie":             "Sequel Conquest Film",
        "a_recap_watcher":            "Recap Briefing Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak":             "Daily Domination Streak",
        "a_mega_streak":              "Mega Nazarick Streak",
        "a_weekly_warrior":           "Weekly Warrior of Nazarick",
        "a_monthly_watcher":          "Monthly Undead Duty",
        "a_comeback":                 "Return from Tomb Rest",
        "a_weekend_streak":           "Weekend Sortie Streak",
        "a_no_zero_days":             "No Zero Days in Tomb",
        "a_iron_will":                "Iron Will of Ainz",
        "a_habit_formed":             "Undead Training Formed",
        "a_consistent_pace":          "Consistent March Forward",
        "a_year_long":                "Year-Long Campaign",
        "a_double_streak":            "Double Streak Assault",
        "a_streak_recovery":          "Nazarick Recovery",
        "a_daily_minimum":            "Daily Minimum Duty",
        "a_winter_streak":            "Winter Campaign Streak",
        "a_summer_streak":            "Summer Conquest Streak",
        "a_morning_streak":           "Morning Drill Streak",
        "a_night_streak":             "Night Undead Patrol",
        "a_unbreakable":              "Unbreakable Will of Ainz",
        "a_eternal_flame":            "Eternal Flame of Nazarick",
        "a_completion_streak":        "Completion Mission Chain",
        "a_rating_streak":            "Rating Streak Report",
        "a_multi_ep_streak":          "Multi-Episode Offensive",
        "a_genre_streak":             "Genre Streak Conquest",
        "a_studio_streak":            "Guild Loyalty Streak",
        "a_perfect_week":             "Perfect Week of Service",

        // ── ANIME SCORING ──
        "a_critic":                   "World Champion Evaluator",
        "a_perfect_ten":              "Perfect World Domination",
        "a_harsh_critic":             "Demiurge's Harsh Standards",
        "a_fair_judge":               "Ainz's Fair Assessment",
        "a_generous_spirit":          "Generous Guardian",
        "a_score_all":                "Full Roster Evaluation",
        "a_wide_range":               "Wide Range Assessment",
        "a_controversial":            "Controversial Ainz Decision",
        "a_consistent_scorer":        "Consistent Evaluator",
        "a_score_sniper":             "Precision Undead Sniper",
        "a_evolving_taste":           "Evolving Nazarick Strategy",
        "a_bell_curve":               "Bell Curve of Domination",
        "a_picky_watcher":            "Selective Overlord",
        "a_100_rated":                "Century of Evaluations",
        "a_500_rated":                "Five Hundred Field Reports",
        "a_mediocre_majority":        "Middle Ground Strategist",
        "a_rating_spree":             "Rating Bone Barrage",
        "a_score_variance":           "Variable Combat Ratings",
        "a_masterpiece_hunter":       "Masterpiece Nazarick Hunter",
        "a_contrarian":               "Contrarian Ainz Scout",
        "a_optimist":                 "Optimist Despite Undeath",
        "a_score_distributor":        "Score Distributor General",
        "a_genre_critic":             "Genre Tactical Critic",
        "a_mean_above_8":             "Elite Combat Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution":     "New Year's Vow for Ainz",
        "a_valentines_weeb":          "Valentine's Dedication",
        "a_pi_day":                   "Pi Day Tomb Calc",
        "a_april_fools":              "April Fools Undead Prank",
        "a_international_anime_day":  "International Overlord Day",
        "a_star_wars_day":            "Nazarick Empire Day",
        "a_summer_solstice":          "Summer Solstice Conquest",
        "a_tanabata":                 "Tanabata Wish for Ainz",
        "a_friday_13th":              "Friday the 13th Undead",
        "a_halloween_spirit":         "Halloween Undead Horror",
        "a_thanksgiving_binge":       "Thanksgiving Nazarick Feast",
        "a_christmas_special":        "Midwinter Tomb Special",
        "a_new_years_eve":            "New Year's Eve Conquest",
        "a_birthday_watch":           "Birthday Enlistment Nazarick",
        "a_holiday_marathon":         "Holiday Dungeon Marathon",
        "a_independence_day":         "Nazarick Independence Day",
        "a_culture_day":              "Nazarick Culture Day",
        "a_spring_equinox":           "Spring Equinox Advance",
        "a_earth_day":                "Protect New World Day",
        "a_labor_day":                "Undead Labor Day",
        "a_winter_solstice":          "Winter Solstice in Tomb",
        "a_anime_birthday":           "Anime Anniversary Celebration",
        "a_every_holiday":            "Every Holiday Guardian",
        "a_consecutive_holidays":     "Consecutive Holiday Conquests",

        // ── ANIME META ──
        "a_meta_first_unlock":        "First Undead Power Awakened",
        "a_meta_collector":           "Nazarick Badge Collector",
        "a_meta_category_starter":    "Category Initiation Rite",
        "a_meta_tier_climber":        "Floor Rank Promotion",
        "a_meta_tier_max":            "Sorcerer King Rank",
        "a_meta_xp_earner":           "XP from Domination",
        "a_meta_difficulty_easy":     "Easy Training Exercise",
        "a_meta_difficulty_hard":     "Legendary Difficulty Ainz",
        "a_meta_unlock_spree":        "Unlock Spree Bone Barrage",
        "a_meta_completionist":       "Meta Completionist Overlord",
        "a_meta_diverse":             "Diverse Nazarick Portfolio",
        "a_meta_dominator":           "Meta Dominator Ainz",

        // ── MANGA MILESTONES ──
        "m_first_chapter":            "First Volume of Nazarick",
        "m_chapter_counter":          "Yggdrasil Chapter Counter",
        "m_chapter_titan":            "Chapter Undead Assault",
        "m_reading_hours":            "Hours Studying Tomb Texts",
        "m_reading_time_lord":        "Ainz's Reading Memory",
        "m_manga_collector":          "Nazarick Manga Archive",
        "m_library_legend":           "Supreme Being Legend",
        "m_first_complete":           "First Manga Conquered",
        "m_hundred_club":             "Hundred-Chapter Nazarick",
        "m_first_day":                "First Day of Tomb Training",
        "m_first_rating":             "First Manuscript Rating",
        "m_ten_thousand_pages":       "Ten Thousand Pages Devoured",
        "m_volume_collector":         "Volume Stockpile Collector",
        "m_year_explorer":            "Year of Manga Conquest",
        "m_century_reader":           "Century-Chapter Reader",
        "m_five_hundred_ch":          "Five Hundred Chapters Consumed",
        "m_thousand_ch":              "Thousand-Chapter Campaign",
        "m_reading_ten":              "Ten Manuscripts at Once",
        "m_ptr_hoarder":              "Reading Backlog Hoarder",
        "m_dropped_honesty":          "Honest Tactical Retreat",
        "m_season_reader":            "Seasonal Undead Reading",
        "m_active_reader":            "Active Nazarick Reader",
        "m_five_thousand_ch":         "Five Thousand Chapters Deep",
        "m_ten_completed":            "Ten Manga Conquered",
        "m_fifty_completed":          "Fifty Manga Victories",
        "m_five_hundred_completed":   "Five Hundred Manga Victories",
        "m_mean_score_tracker":       "Average Guardian Rating",
        "m_unique_authors":           "Unique Author Encounters",
        "m_all_status":               "All Reading Statuses",
        "m_first_favorite":           "First Manga Guardian Bond",
        "m_favorites_collector":      "Manga Favorites Arsenal",
        "m_days_spent_reading":       "Days in Nazarick Archives",

        // ── MANGA BINGE ──
        "m_binge_reader":             "World Domination Marathon",
        "m_marathon_reader":          "Tomb-to-Tomb Reading Marathon",
        "m_weekend_reader":           "Weekend Tomb Reading",
        "m_non_stop_reading":         "Non-Stop Undead Reading",
        "m_one_more_chapter":         "One More Conquest Chapter",
        "m_speed_read":               "Ainz Speed Reading",
        "m_double_story":             "Double Manuscript Feature",
        "m_triple_read":              "Triple Reading Assault",
        "m_five_a_day":               "Five Reads a Day",
        "m_chapter_chain":            "Chapter Chain Offensive",
        "m_volume_binge":             "Volume Binge Bombardment",
        "m_power_reader":             "Power Reader Guardian",
        "m_half_day_read":            "Half-Day Archive Dive",
        "m_full_day_read":            "Full-Day Tomb Study",
        "m_power_weekend":            "Power Weekend Reading",
        "m_binge_king":               "King of Reading Nazarick",
        "m_no_sleep_read":            "All-Night Tomb Reading",
        "m_full_series_rush":         "Full Series Conquest Rush",
        "m_seven_day_challenge":      "Seven-Day Intel Gathering",
        "m_hundred_day_read":         "Hundred-Day Reading Siege",
        "m_volume_rush":              "Volume Rush Deployment",
        "m_series_sweep":             "Series Sweep Conquest",
        "m_genre_binge":              "Cross-Genre Maneuver",
        "m_author_binge":             "Author Focused Deep Dive",
        "m_chapter_counter_day":      "Daily Chapter Kill Count",
        "m_multi_series_binge":       "Multi-Series Reading Front",
        "m_midnight_binge":           "Midnight Tomb Session",
        "m_new_year_binge":           "New Year's Reading Conquest",
        "m_forty_eight_hour":         "Forty-Eight Hour Reading Siege",
        "m_oneshot_binge":            "Oneshot Blitz Conquest",

        // ── MANGA GENRES ──
        "m_genre_action":             "Action Guardian Specialist",
        "m_genre_adventure":          "Adventure Beyond Nazarick",
        "m_genre_comedy":             "Ainz's Accidental Comedy",
        "m_genre_drama":              "Drama of Ainz's Loneliness",
        "m_genre_fantasy":            "Fantasy of New World",
        "m_genre_horror":             "Undead Horror Manuscript",
        "m_genre_mystery":            "Mystery of the Tomb",
        "m_genre_romance":            "Romance Under Dark Skies",
        "m_genre_scifi":              "Sci-Fi Yggdrasil Engineering",
        "m_genre_sol":                "Slice of Life in Tomb",
        "m_genre_sports":             "Guardian Training Sports",
        "m_genre_supernatural":       "Supernatural Guardian Powers",
        "m_genre_thriller":           "Thriller Ainz Intelligence",
        "m_genre_psychological":      "Psychological Warfare Reader",
        "m_genre_isekai":             "Isekai Beyond the World",
        "m_genre_shounen":            "Shounen Heart of Ainz",
        "m_genre_ecchi":              "Albedo's Obsession Chapter",
        "m_genre_mahou_shoujo":       "Power of World Items",
        "m_genre_mecha":              "Nazarick Golem Blueprints",
        "m_genre_music":              "Nazarick Folk Songs",
        "m_tag_isekai_new":           "New World Beyond Sea",
        "m_tag_harem":                "Pleiades Bonds Manga",
        "m_tag_bl":                   "Brothers in Arms Manga",
        "m_tag_gl":                   "Shield Sisters Manga",
        "m_tag_historical":           "Yggdrasil History Manga",
        "m_tag_military":             "Undead Military Manga",
        "m_tag_school":               "Nazarick Academy Manga",
        "m_tag_martial_arts":         "Gazef Combat Manual",
        "m_tag_vampire":              "Shalltear Blood Manga",
        "m_tag_samurai":              "Blade Master Manga",
        "m_tag_space":                "Beyond the Horizon Manga",
        "m_tag_parody":               "Chibi Nazarick Manga",
        "m_tag_idol":                 "Guardian Idol Manga",
        "m_tag_post_apocalyptic":     "Post-Domination Manga",
        "m_tag_cyberpunk":            "Yggdrasil Technology Manga",
        "m_tag_shoujo":               "Albedo's Story Manga",
        "m_tag_survival":             "Tomb Survival Manga",
        "m_tag_cooking":              "Nazarick Rations Cookbook",
        "m_tag_medical":              "Nazarick Field Medic Manga",
        "m_tag_villainess":           "Warrior Candidate Manga",

        // ── MANGA COMPLETION ──
        "m_completionist":            "Manga Conquest Completionist",
        "m_mega_completionist":       "Supreme Manga Overlord",
        "m_completion_rate_50":       "Halfway to the Truth",
        "m_completion_rate_75":       "Approaching Ainz's Throne",
        "m_completion_rate_90":       "Final Chapter Approaching",
        "m_no_drop":                  "No Manuscript Abandoned",
        "m_long_runner_complete":     "Long Series Endurance Medal",
        "m_sequel_chain":             "Sequel Chain of Command",
        "m_clean_list":               "Clean Reading Record",
        "m_from_ptr":                 "Orders Received Read",
        "m_reread_master":            "Memory Replay Reread",
        "m_oneshot_complete":         "Oneshot Mission Specialist",
        "m_same_day_start_finish":    "Same-Day Reading Blitz",
        "m_revival":                  "Revival Through Ainz",
        "m_zero_to_hundred":          "NPC to Scholar",
        "m_five_genre_complete":      "Five-Genre Mastery",
        "m_full_collection":          "Full Nazarick Collection",
        "m_batch_complete":           "Batch Clearance",
        "m_paused_to_done":           "Back from Hiatus",
        "m_completion_spree":         "Completion Bone Barrage",
        "m_format_completionist":     "Format Completion Badge",
        "m_catch_up":                 "Caught Up with Ainz",
        "m_multi_reread":             "Multi-Pass Reread",
        "m_dropped_recovery":         "Recovered from the Tomb",
        "m_ten_perfect_scores":       "Ten Perfect Manuscript Scores",
        "m_complete_genre_span":      "All-Genre Reading Overlord",
        "m_monthly_completions":      "Monthly Manuscript Victories",
        "m_yearly_completions":       "Yearly Reading Campaign",
        "m_rapid_complete":           "Rapid Intel Processing",
        "m_author_complete":          "Author's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader":             "Loyal Nazarick Reader",
        "m_mangaka_lover":            "Maruyama Devotee",
        "m_rereader":                 "Guardian Rereader",
        "m_triple_reread":            "Triple Reread Conquest",
        "m_annual_reread":            "Annual Remembrance Reread",
        "m_publisher_fan":            "Publisher Alliance Fan",
        "m_artist_fan":               "Artist Appreciation Medal",
        "m_adaptation_compare":       "Manga vs Anime Ainz",
        "m_source_material_fan":      "Source Material Overlord",
        "m_waiting_weekly":           "Weekly Chapter Signal Wait",
        "m_classic_reader":           "Classic Manuscript Reader",
        "m_saga_reader":              "Saga of Ainz Reader",
        "m_genre_loyalty":            "Genre Loyalty Medal",
        "m_decade_reader":            "Decade-Long Reader",
        "m_ln_adaptation":            "Light Novel Adaptation Intel",
        "m_original_work":            "Original Manga Work",
        "m_long_commitment":          "Long-Term Reading Commitment",
        "m_up_to_date":               "Up-to-Date with Nazarick",
        "m_favorite_mangaka":         "Favorite Mangaka Honored",
        "m_complete_portfolio":       "Complete Reading Portfolio",
        "m_franchise_collector":      "Overlord Franchise Collector",
        "m_serialization_follower":   "Serialization Tracker",
        "m_genre_master":             "Genre Mastery Earned",
        "m_multi_series_author":      "Multi-Series Author Fan",
        "m_format_diversity":         "Diverse Reading Formats",
        "m_year_dedication":          "Year of Dedicated Reading",
        "m_ongoing_follower":         "Ongoing Series Follower",
        "m_genre_loyalty_50":         "Fifty Genre Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer":           "Genre Territory Overlord",
        "m_publisher_hopper":         "Publisher Guild Transfer",
        "m_tag_explorer":             "Manga Tag Recon",
        "m_decade_hopper":            "Decade-Hopping via Ainz",
        "m_hidden_gem":               "Hidden Tomb Treasure",
        "m_popular_taste":            "Popular Among Guardians",
        "m_retro_reader":             "Retro Manuscript Appreciator",
        "m_modern_reader":            "Modern Era Reader",
        "m_cross_demographic":        "Cross-Demographic Overlord",
        "m_underdog_fan":             "Underdog NPC Fan",
        "m_variety_week":             "Week of Varied Readings",
        "m_manhwa_reader":            "Manhwa Intelligence Reader",
        "m_manhua_reader":            "Manhua Intelligence Reader",
        "m_classic_connoisseur":      "Classic Nazarick Manuscript",
        "m_award_winner":             "Medal-Winning Manuscript",
        "m_niche_explorer":           "Niche Territory Reader",
        "m_world_manga":              "World Manga Intel",
        "m_cult_classic":             "Tomb Cult Classic",
        "m_random_pick":              "Random Reading Assignment",
        "m_new_genre_month":          "New Genre Deployment Monthly",
        "m_year_completionist":       "Year Reading Completionist",
        "m_unpopular_opinion":        "Unpopular Ainz Opinion",
        "m_top_rated_reader":         "Top-Rated Intel Source",
        "m_source_variety":           "Source Material Variety",
        "m_low_score_brave":          "Brave Low-Score Reader",
        "m_short_manga_explorer":     "Short Manga Skirmish",
        "m_long_manga_explorer":      "Long Campaign Manuscript",
        "m_serialization_explorer":   "Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl":                "Night Owl Tomb Reader",
        "m_early_bird":               "Dawn Patrol Reader",
        "m_lunch_reader":             "Nazarick Mess Hall Reader",
        "m_commute_reader":           "Travel to Nazarick Reader",
        "m_four_am_club":             "4 AM Undead Reader",
        "m_new_year_read":            "New Year's Reading Oath",
        "m_all_hours":                "All-Hours Archive Access",
        "m_prime_time_reader":        "Prime Time Manuscript",
        "m_workday_reader":           "On-Duty Nazarick Reader",
        "m_sunday_read":              "Sunday Dungeon Marathon",
        "m_morning_routine":          "Morning Tomb Formation Reading",
        "m_night_shift_reader":       "Night Shift Reader",
        "m_seasonal_premier_read":    "New Release Intel",
        "m_clock_collector":          "Clock Tower Reading Time",
        "m_late_night_horror":        "Midnight Undead Horror Read",
        "m_afternoon_reader":         "Afternoon Tomb Reading",
        "m_golden_hour_reader":       "Golden Hour Reading",
        "m_dawn_reader":              "Dawn Reading Overlord",
        "m_twilight_reader":          "Twilight Tomb Reading",
        "m_midnight_start":           "Midnight Reading Mission",
        "m_weekend_binge_hours":      "Weekend Binge Reading Ops",
        "m_late_night_regular":       "Late Night Regular Reader",
        "m_sunrise_reader":           "Sunrise Over Nazarick Reader",
        "m_every_day_of_week":        "Every Day Reading Duty",
        "m_monthly_hours":            "Monthly Reading Hours Logged",
        "m_bedtime_reader":           "Bedtime Tomb Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator":          "Nazarick Art Appreciator",
        "m_webtoon_reader":           "Webtoon Intelligence",
        "m_full_color":               "Full Color Manuscript",
        "m_doujin_reader":            "Underground Doujin Reader",
        "m_anthology_reader":         "Anthology Collection Reader",
        "m_adaptation_reader":        "Adaptation Study Reader",
        "m_longstrip_reader":         "Vertical Scroll Reader",
        "m_4koma_reader":             "4-Koma Comedy Shorts",
        "m_oneshot_reader":           "Oneshot Mission Reader",
        "m_format_variety":           "Format Tactical Variety",
        "m_light_novel_reader":       "Light Novel Intel Reader",
        "m_novel_reader":             "Novel Archive Reader",
        "m_visual_storyteller":       "Visual Battle Narrator",
        "m_colored_classic":          "Colored Classic Manuscript",
        "m_webcomic_fan":             "Webcomic Underground Fan",
        "m_manga_to_anime":           "Manga to Anime Ainz",
        "m_seinen_reader":            "Seinen Nazarick Reader",
        "m_josei_reader":             "Josei Perspective Reader",
        "m_award_winning_art":        "Medal-Winning Artwork",
        "m_debut_work":               "Debut Manuscript",
        "m_vertical_scroll":          "Vertical Scroll Intel",
        "m_traditional_format":       "Traditional Format Reader",
        "m_cross_media":              "Cross-Media Intelligence",
        "m_spinoff_reader":           "Spinoff Mission Reader",
        "m_remake_reader":            "Remake Reading Assignment",
        "m_collaboration_reader":     "Joint Operation Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak":             "Daily Overlord Reading",
        "m_mega_streak":              "Mega Reading Campaign Streak",
        "m_weekly_warrior":           "Weekly Warrior Reader",
        "m_monthly_reader":           "Monthly Tomb Reader",
        "m_comeback":                 "Reader's Return to Tomb",
        "m_weekend_streak":           "Weekend Reading Streak",
        "m_no_zero_days":             "No Zero Reading Days",
        "m_iron_will":                "Iron Will Reader",
        "m_habit_formed":             "Reading Regimen Formed",
        "m_consistent_pace":          "Consistent Reading Advance",
        "m_year_long":                "Year-Long Reading Campaign",
        "m_double_streak":            "Double Reading Streak",
        "m_streak_recovery":          "Reading Streak Recovery",
        "m_daily_minimum":            "Daily Minimum Pages",
        "m_winter_streak":            "Winter Reading Campaign",
        "m_summer_streak":            "Summer Reading Conquest",
        "m_morning_streak":           "Morning Reading Formation",
        "m_night_streak":             "Night Reading Patrol",
        "m_unbreakable":              "Unbreakable Reading Will",
        "m_eternal_flame":            "Eternal Flame of Knowledge",
        "m_chapter_a_day":            "Chapter a Day Discipline",
        "m_genre_streak":             "Genre Reading Streak",
        "m_completion_streak":        "Completion Reading Chain",
        "m_rating_streak":            "Rating Streak Filed",
        "m_multi_ch_streak":          "Multi-Chapter Streak",
        "m_author_streak":            "Author Dedication Streak",
        "m_perfect_week_manga":       "Perfect Reading Week",
        "m_diverse_streak":           "Diverse Reading Streak",

        // ── MANGA SCORING ──
        "m_critic":                   "Nazarick Manuscript Critic",
        "m_perfect_ten":              "Perfect Overlord Rating",
        "m_harsh_critic":             "Demiurge's Reading Standards",
        "m_fair_judge":               "Ainz's Fair Review",
        "m_generous_spirit":          "Generous Reader Spirit",
        "m_score_all":                "Full Manuscript Assessment",
        "m_wide_range":               "Wide Range Scores",
        "m_controversial":            "Controversial Ainz Opinion",
        "m_consistent_scorer":        "Consistent Manuscript Scorer",
        "m_score_sniper":             "Precision Score Sniper",
        "m_evolving_taste":           "Evolving Reading Taste",
        "m_bell_curve":               "Bell Curve of Scores",
        "m_picky_reader":             "Selective Overlord Reader",
        "m_100_rated":                "Century of Ratings Filed",
        "m_500_rated":                "Five Hundred Rating Reports",
        "m_mediocre_majority":        "Middle Ground Reader",
        "m_rating_spree":             "Rating Bone Barrage Filed",
        "m_score_variance":           "Variable Manuscript Scores",
        "m_binge_rater":              "Binge Rating Session",
        "m_reread_rerate":            "Reread Re-Rate Ainz",
        "m_masterpiece_hunter":       "Masterpiece Manuscript Hunter",
        "m_contrarian":               "Contrarian Overlord Reader",
        "m_optimist":                 "Optimistic Reader Overlord",
        "m_score_distributor":        "Score Distributor General",
        "m_genre_critic":             "Genre Reading Critic",
        "m_mean_above_8":             "Elite Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution":     "New Year's Reading Vow",
        "m_valentines_read":          "Valentine's Reading Bond",
        "m_pi_day":                   "Pi Day Chapter Count",
        "m_april_fools":              "April Fools Chibi Nazarick",
        "m_international_manga_day":  "International Manga Day",
        "m_free_comic_day":           "Free Comic Tomb Day",
        "m_summer_solstice":          "Summer Solstice Reading",
        "m_tanabata":                 "Tanabata Reading Wish",
        "m_friday_13th":              "Friday 13th Undead Manuscript",
        "m_halloween_read":           "Halloween Horror Reading",
        "m_thanksgiving_binge":       "Thanksgiving Reading Feast",
        "m_christmas_read":           "Midwinter Tomb Reading",
        "m_new_years_eve":            "New Year's Eve Final Read",
        "m_birthday_read":            "Birthday Reading Gift",
        "m_holiday_marathon":         "Holiday Reading Marathon",
        "m_independence_day":         "Nazarick Independence Reading",
        "m_culture_day":              "Culture Day Manuscript",
        "m_spring_equinox":           "Spring Equinox Reading",
        "m_earth_day":                "Earth Day Tome Read",
        "m_labor_day":                "Nazarick Labor Reading Day",
        "m_winter_solstice":          "Winter Solstice Tomb Reading",
        "m_manga_birthday":           "Manga Birthday Celebration",
        "m_every_holiday_reader":     "Every Holiday Reader",
        "m_consecutive_holidays":     "Consecutive Holiday Reads",

        // ── MANGA SPECIAL ──
        "m_round_number":             "Round Number Milestone",
        "m_fibonacci":                "Fibonacci Chapter Pattern",
        "m_palindrome_day":           "Palindrome Reading Day",
        "m_binary_day":               "Binary Signal Reading Day",
        "m_full_moon_read":           "Full Moon Undead Read",
        "m_leap_year_read":           "Leap Year Reading",
        "m_triple_seven":             "Triple Seven Floors Reading",
        "m_thousand_complete":        "Thousand Manga Victories",
        "m_nice":                     "Nice Chapter Count",
        "m_power_level_chapters":     "Ainz-Level Chapters",
        "m_answer_42":                "Answer to Nazarick",
        "m_square_number":            "Perfect Formation Chapters",
        "m_prime_count":              "Prime Chapter Count",
        "m_matching_date":            "Matching Nazarick Date",
        "m_century_chapter":          "Century Chapter Milestone",
        "m_pi_chapters":              "Pi Chapter Calculation",
        "m_synchronicity":            "Nazarick Reading Synchronicity",
        "m_world_record":             "World Record Chapter Count",
        "m_genre_clash":              "Genre Clash Reading",
        "m_time_traveler":            "Time-Traveling Reader",
        "m_double_digits":            "Double Digit Milestone",
        "m_one_two_three":            "Floors One Two Three",
        "m_lucky_seven":              "Seven Lucky Chapters",
        "m_exact_hundred_ch":         "Exact Hundred Chapters Read",
        "m_year_match_count":         "Year Match Chapter Count",
        "m_chapter_match_date":       "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format":             "Manga Format Specialist",
        "m_manhwa_format":            "Manhwa Format Reader",
        "m_manhua_format":            "Manhua Format Reader",
        "m_ln_format":                "Light Novel Format",
        "m_oneshot_format":           "Oneshot Format Operative",
        "m_doujin_format":            "Doujin Format Reader",
        "m_novel_format":             "Novel Format Reader",
        "m_format_master_manga":      "Format Master Reader",

        // ── MANGA META ──
        "m_meta_first_unlock":        "First Reading Power Unlocked",
        "m_meta_collector":           "Reading Badge Collector",
        "m_meta_category_starter":    "Category Initiation",
        "m_meta_tier_climber":        "Reading Rank Promotion",
        "m_meta_tier_max":            "Maximum Reading Rank",
        "m_meta_xp_earner":           "XP from Reading Tome",
        "m_meta_difficulty_easy":     "Easy Reading Exercise",
        "m_meta_difficulty_hard":     "Legendary Manuscript Ainz",
        "m_meta_unlock_spree":        "Reading Unlock Barrage",
        "m_meta_completionist":       "Meta Reading Completionist",
        "m_meta_diverse":             "Diverse Reading Portfolio",
        "m_meta_dominator":           "Meta Dominator Ainz",
    },
    musicUrl: "",
    previewColors: {
        bg:        "#030200",
        primary:   "#87620e",
        secondary: "#c09030",
        accent:    "#505050",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/overlord.png",
    particleColor: "#a06020",
    backgroundDim: 0.30,
    backgroundBlur: 30,
    milestoneNames: {
        1:   "NPC",
        5:   "Yggdrasil Player",
        14:  "Guild Member",
        26:  "Floor Guardian",
        40:  "Pleiades Battle Maid",
        55:  "Supreme Being",
        70:  "Sorcerer King",
        85:  "World Item Holder",
        100: "Ainz Ooal Gown",
    },
}
