import { AnimeThemeConfig } from "./types"
import {
    GiBrain,
    GiScrollUnfurled,
    GiMagnifyingGlass,
    GiEyeball,
    GiSpiralArrow,
    GiDeathSkull,
    GiMuscleUp,
    GiResize,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiSettingsKnobs,
    GiDna1,
    GiScales,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const parasiteTheme: AnimeThemeConfig = {
    id: "parasyte",
    displayName: "Parasyte",
    description: "What is it to be human? Shinichi and Migi — one body, two minds — face alien parasites reshaping humanity from within.",
    fontFamily: "'Share Tech Mono', monospace",
    fontHref: "https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap",
    cssVars: {
        "--color-brand-200": "190 240 205",
        "--color-brand-300": "140 215 160",
        "--color-brand-400": "80 182 108",
        "--color-brand-500": "46 158 74",
        "--color-brand-600": "28 128 52",
        "--color-brand-700": "16 98 36",
        "--color-brand-800": "8 68 22",
        "--color-brand-900": "3 42 12",
        "--color-brand-950": "1 22 6",
        "--brand": "46 158 74",
        "--background": "#060806",
        "--paper": "#0d110d",
        "--color-gray-950": "6 8 6",
        "--color-gray-900": "14 18 14",
        "--color-gray-800": "24 30 24",
        "--color-gray-700": "38 48 38",
        "--color-gray-600": "58 72 58",
        "--color-gray-500": "86 102 86",
        "--color-gray-400": "126 142 126",
        "--color-gray-300": "166 178 166",
        "--color-gray-200": "200 210 200",
        "--color-gray-100": "228 235 228",
        "--color-gray-50": "243 248 243",
    },
    sidebarOverrides: {
        "home": { icon: GiBrain, label: "Izumi's Home" },
        "schedule": { icon: GiAlarmClock, label: "Parasite Schedule" },
        "manga": { icon: LuBookOpen, label: "Biology Reports" },
        "lists": { icon: GiScrollUnfurled, label: "Parasite Registry" },
        "discover": { icon: GiMagnifyingGlass, label: "Human Evolution" },
        "torrent-list": { icon: GiEyeball, label: "Parasite Cache" },
        "debrid": { icon: GiSpiralArrow, label: "Gotou Navigation" },
        "unmatched": { icon: GiDeathSkull, label: "Undetected Parasites" },
        "enmasse": { icon: GiResize, label: "Mass Infection" },
        "scan-summaries": { icon: TbReportSearch, label: "Species Reports" },
        "auto-downloader": { icon: LuRss, label: "Migi's Detection" },
        "community": { icon: GiMuscleUp, label: "Human-Parasite Alliance" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Parasite Warning" },
        "achievements": { icon: GiTrophy, label: "Evolution Feats" },
        "theme-manager": { icon: GiPalette, label: "Bio Colors" },
        "extensions": { icon: BiExtension, label: "Migi Attachments" },
        "sync": { icon: IoCloudOfflineOutline, label: "Migi Link" },
        "settings": { icon: GiSettingsKnobs, label: "Reiko's Command" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Normal High Schooler",
        "a_episode_counter": "Parasite Encounter Count",
        "a_episode_titan": "Special-Class Parasite Encounter",
        "a_hours_invested": "Hours Coexisting with Migi",
        "a_time_lord": "Migi's Sleep Cycle",
        "a_anime_collector": "Arsenal of the Hybrid",
        "a_library_legend": "Biology Library Legend",
        "a_first_complete": "First Parasite Eliminated",
        "a_hundred_club": "Century of Parasite Studies",
        "a_first_day": "First Day as Host",
        "a_first_rating": "Hybrid Assessment",
        "a_ten_thousand_min": "Ten Thousand Minutes Coexisting",
        "a_season_veteran": "Veteran Parasite Host",
        "a_year_explorer": "Year Among Parasites",
        "a_century_watcher": "Hundred Episodes of Evolution",
        "a_five_hundred_eps": "Five Hundred Migi Strikes",
        "a_thousand_eps": "Thousand Parasite Encounters",
        "a_watching_ten": "Ten Hosts Watched",
        "a_ptw_hoarder": "Backlog of Bio Studies",
        "a_dropped_honesty": "Strategic Human Retreat",
        "a_five_thousand_eps": "Five Thousand Sorties",
        "a_ten_completed": "Ten Evolution Campaigns",
        "a_fifty_completed": "Fifty Parasite Arcs Done",
        "a_five_hundred_completed": "Five Hundred Bio Victories",
        "a_mean_score_tracker": "Average Bio Rating",
        "a_unique_studios": "Allied Research Labs",
        "a_days_spent_watching": "Days with Migi",
        "a_all_status": "All Host Statuses",
        "a_first_favorite": "First Bond with Migi",
        "a_favorites_collector": "Host-Parasite Bonds",
        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Parasite Study",
        "a_marathon_runner": "Evolution Marathon Runner",
        "a_weekend_warrior": "Weekend Bio Researcher",
        "a_non_stop": "Relentless Like Shinichi",
        "a_one_more_episode": "One More Evolution Stage",
        "a_speed_run": "Migi Speed Dash",
        "a_double_feature": "Double Bio Feature",
        "a_triple_threat": "Triple Parasite Takedown",
        "a_five_a_day": "Five Species a Day",
        "a_back_to_back": "Back-to-Back Bio Arcs",
        "a_seasonal_binge": "Full Evolution Arc Clear",
        "a_cour_crusher": "Bio Cour Crusher",
        "a_half_day_watch": "Half Day of Bio Study",
        "a_full_day_watch": "Full Day Among Parasites",
        "a_power_weekend": "Power Weekend Bio Research",
        "a_binge_king": "King of the Parasite Studies",
        "a_no_sleep": "All-Night Migi Vigil",
        "a_entire_season": "Full Bio Arc Clear",
        "a_seven_day_challenge": "Seven-Day Evolution Siege",
        "a_hundred_day_binge": "Hundred-Day Bio Siege",
        "a_genre_binge": "Cross-Genre Bio Fantasy",
        "a_studio_binge": "Studio Alliance Binge",
        "a_season_sweep": "Season Sweep of Evolution",
        "a_forty_eight_hour": "Forty-Eight Hour Bio Study",
        "a_ep_counter_day": "Daily Parasite Count",
        "a_multi_series_binge": "Multi-Front Bio Campaign",
        "a_midnight_binge": "Midnight Migi Session",
        "a_new_year_binge": "New Year's Parasite Charge",
        // ── ANIME GENRES ──
        "a_genre_action": "Migi Combat Specialist",
        "a_genre_adventure": "Journey of a Hybrid",
        "a_genre_comedy": "Migi's Logical Moments",
        "a_genre_drama": "Shinichi's Inner Conflict",
        "a_genre_fantasy": "Parasite World Realm",
        "a_genre_horror": "Parasite Attack Horror",
        "a_genre_mystery": "Mystery of the Parasites",
        "a_genre_romance": "Shinichi and Murano's Bond",
        "a_genre_scifi": "Parasite Biology Tech",
        "a_genre_sol": "Normal School Days",
        "a_genre_sports": "Parasite Training Grounds",
        "a_genre_supernatural": "Parasite Evolution Power",
        "a_genre_thriller": "Gotou Pursuit Thriller",
        "a_genre_mecha": "Migi's Blade Extensions",
        "a_genre_music": "Parasyte OST Collection",
        "a_genre_psychological": "What Is Humanity",
        "a_genre_ecchi": "Hot Spring Bio Reprieve",
        "a_genre_mahou_shoujo": "Migi's Cell Division Magic",
        "a_tag_isekai": "Transported to Parasite World",
        "a_tag_harem": "Host-Parasite Bonds",
        "a_tag_bl": "Shinichi and Migi Bond",
        "a_tag_gl": "Reiko Tamura's Perspective",
        "a_tag_historical": "Parasite Evolution History",
        "a_tag_military": "Anti-Parasite Military",
        "a_tag_school": "High School Parasite Host",
        "a_tag_martial_arts": "Migi Combat Mastery",
        "a_tag_vampire": "Parasite Blood Feeding",
        "a_tag_samurai": "Parasite Blade Style",
        "a_tag_space": "Parasite Origin Beyond",
        "a_tag_parody": "Chibi Parasite Parody",
        "a_tag_idol": "Migi Logical Idol",
        "a_tag_post_apocalyptic": "Post-Parasite Invasion World",
        "a_tag_cyberpunk": "Bio-Weapon Tech",
        "a_tag_shounen": "Shinichi's Determined Heart",
        "a_tag_seinen": "Parasyte Seinen Reality",
        "a_tag_shoujo": "Murano's Devotion",
        "a_tag_josei": "Reiko's Philosophy",
        "a_tag_survival": "Surviving Parasite Attacks",
        // ── ANIME COMPLETION ──
        "a_completionist": "Full Parasite Study Report",
        "a_mega_completionist": "Chief Bio Commander",
        "a_completion_rate_50": "Halfway to Gotou",
        "a_completion_rate_75": "Approaching True Humanity",
        "a_completion_rate_90": "Final Parasite Nearly Down",
        "a_no_drop": "No Host Left Behind",
        "a_long_runner_complete": "Long Bio Journey Complete",
        "a_sequel_chain": "Evolution Chain Complete",
        "a_clean_list": "Clean Host Record",
        "a_from_ptw": "Orders Received Studied",
        "a_rewatch_master": "Reliving Migi's Contract",
        "a_short_complete": "Quick Parasite Skirmish",
        "a_same_day_start_finish": "Same-Day Parasite Elimination",
        "a_revival": "Revived by Migi",
        "a_zero_to_hero": "Ordinary to Hybrid",
        "a_five_genre_complete": "Five-Genre Bio Mastery",
        "a_full_franchise": "Full Parasyte Dossier",
        "a_batch_complete": "Batch Bio Clear",
        "a_paused_to_done": "Returned from Bio Hiatus",
        "a_completion_spree": "Completion Migi Slash",
        "a_multi_rewatch": "Multi-Timeline Evolution",
        "a_dropped_recovery": "Recovered from Parasite Attack",
        "a_ten_perfect_scores": "Ten Perfect Bio Scores",
        "a_seasonal_clear": "Seasonal Bio Campaign Clear",
        "a_complete_genre_span": "All-Terrain Bio Researcher",
        "a_monthly_completions": "Monthly Bio Reports",
        "a_yearly_completions": "Yearly Bio Campaign",
        "a_rapid_complete": "Lightning Bio Raid",
        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Parasyte Devotee",
        "a_studio_devotee": "Studio Bio Devotee",
        "a_rewatcher": "Parasite Recon Rewatch",
        "a_triple_rewatch": "Triple Bio Rewatch",
        "a_annual_tradition": "Annual Migi Remembrance",
        "a_director_fan": "Shimizu's Vision Follower",
        "a_voice_actor_fan": "Voice of the Hybrids",
        "a_ost_lover": "Parasyte OST Devotee",
        "a_source_reader": "Iwaaki's Original Manga",
        "a_waiting_weekly": "Weekly Bio Chapter Wait",
        "a_childhood_revisit": "Return to Normal Days",
        "a_saga_tracker": "Saga of the Parasite Tracker",
        "a_genre_loyalty": "Bio Genre Loyalty",
        "a_decade_watcher": "Decade-Long Parasite Watcher",
        "a_adaptation_hunter": "Parasyte Adaptation Hunt",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Host Duty",
        "a_perfect_attendance": "Perfect Bio Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Bio Catalog",
        "a_franchise_collector": "Parasyte Universe Collector",
        "a_airing_follower": "Currently Airing Bio Intel",
        "a_genre_master": "Bio Genre Mastery",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Arc Bio Veteran",
        "a_format_diversity": "Diverse Bio Formats",
        "a_year_dedication": "Year of Dedication to Shinichi",
        "a_season_dedication": "Season of Bio Service",
        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Known Biology",
        "a_studio_hopper": "Lab Transfer",
        "a_tag_explorer": "Bio Tag Recon Mission",
        "a_decade_hopper": "Time via Migi's Memory",
        "a_hidden_gem": "Hidden Bio Gem",
        "a_popular_taste": "Popular Among Bio Researchers",
        "a_retro_appreciator": "Pre-Invasion Era Appreciator",
        "a_modern_viewer": "Modern Bio Viewer",
        "a_cross_demographic": "Cross-Demographic Hybrid",
        "a_underdog_fan": "Underdog Host Spirit",
        "a_variety_week": "Week of Varied Species",
        "a_foreign_cinema": "Foreign Bio Cinema",
        "a_classic_connoisseur": "Classic Bio Fan",
        "a_every_season": "Every Season Among Parasites",
        "a_award_winner": "Medal of Bio Valor",
        "a_niche_explorer": "Niche Bio Territory",
        "a_global_anime": "Global Bio Alliance",
        "a_cult_classic": "Parasyte Cult Classic",
        "a_random_pick": "Random Bio Assignment",
        "a_new_genre_month": "New Bio Territory Monthly",
        "a_seasonal_completionist": "Seasonal Bio Campaign Clear",
        "a_unpopular_opinion": "Unpopular Bio Opinion",
        "a_top_rated_viewer": "Top-Rated Bio Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Bio Intel",
        "a_short_series_explorer": "Short Bio Skirmish Explorer",
        "a_long_series_explorer": "Long Bio Campaign Explorer",
        // ── ANIME TIME ──
        "a_night_owl": "Night Watch with Migi",
        "a_early_bird": "Dawn Bio Study",
        "a_lunch_break": "School Lunch Break",
        "a_golden_hour": "Golden Hour Before Transformation",
        "a_four_am_club": "4 AM Migi Sentry",
        "a_witching_hour": "Parasite Witching Hour",
        "a_new_year_watch": "New Year's Humanity Oath",
        "a_midnight_premiere": "Midnight Parasyte Premiere",
        "a_all_hours": "All-Hours Bio Vigil",
        "a_dawn_warrior": "Dawn Hybrid Warrior",
        "a_afternoon_delight": "Afternoon Bio Rest",
        "a_prime_time": "Prime Time Parasite Battle",
        "a_workday_watcher": "On-Duty Bio Watcher",
        "a_sunday_marathon": "Sunday Evolution Marathon",
        "a_rainy_day": "Rainy Day Bio Study",
        "a_morning_routine": "Morning Bio Formation",
        "a_night_shift": "Night Shift Parasite Guard",
        "a_twilight_zone": "Twilight Parasite Zone",
        "a_seasonal_premier": "Season Premiere Evolution",
        "a_clock_collector": "Parasite Clock Collector",
        "a_weekend_binge_hours": "Weekend Bio Binge Ops",
        "a_late_night_regular": "Late Night Regular Researcher",
        "a_sunrise_watcher": "Sunrise Over Bio Ruins",
        "a_holiday_watcher": "Holiday Bio Duty",
        "a_every_day_of_week": "Every Day a Hybrid",
        "a_monthly_hours": "Monthly Bio Duty Hours",
        // ── ANIME SOCIAL ──
        "a_first_party": "First Bio Crew Formation",
        "a_party_host": "Bio Research Commander",
        "a_social_butterfly": "School Socialite",
        "a_group_binge": "Group Parasite Viewing",
        "a_party_regular": "Regular Bio Partner",
        "a_sync_viewer": "Synchronized Migi Maneuver",
        "a_commentator": "Bio Battle Commentator",
        "a_party_marathon": "Marathon Bio Run",
        "a_full_house": "Full Bio Research Team",
        "a_community_pillar": "Pillar of the Bio Lab",
        "a_watch_party_streak": "Consecutive Bio Streak",
        "a_diverse_party": "Diverse Bio Party",
        "a_late_night_party": "Late Night Bio Party",
        "a_party_veteran": "Veteran Bio Leader",
        "a_genre_party": "Cross-Genre Bio Formation",
        "a_weekly_party": "Weekly Researchers' Gathering",
        "a_silent_viewer": "Silent Like Migi Observer",
        "a_recommendation_giver": "Hybrid's Recommendation",
        "a_party_completionist": "Party Bio Completionist",
        "a_social_scorer": "Social Bio Scorer",
        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Bio Formation",
        "a_fibonacci": "Fibonacci Cell Division Sequence",
        "a_palindrome_day": "Palindrome Bio Loop",
        "a_binary_day": "Binary Migi Signal Day",
        "a_full_moon": "Full Moon Parasite Transformation",
        "a_leap_year": "Leap Year Evolution Skip",
        "a_time_traveler": "Migi's Memory Archive",
        "a_genre_clash": "Shinichi vs Gotou Clash",
        "a_triple_seven": "Triple Seven Parasite Forms",
        "a_thousand_complete": "Thousand Bio Battles",
        "a_pi_episodes": "Pi Bio Calculation",
        "a_synchronicity": "Host-Parasite Synchronicity",
        "a_world_record": "World Record Parasite Kill",
        "a_nice": "Nice Bio Count",
        "a_power_level": "Migi Power Level",
        "a_answer_42": "Answer to Humanity's Question",
        "a_square_number": "Perfect Bio Formation",
        "a_prime_count": "Prime Parasite Count",
        "a_matching_date": "Matching Bio Date",
        "a_century_episode": "Century Episode Bio Study",
        "a_double_digits": "Double Digit Species",
        "a_one_two_three": "Shinichi Migi Murano",
        "a_lucky_seven": "Seven Lucky Hosts",
        "a_all_tens": "All Tens Bio Score",
        "a_exact_hundred_eps": "Exact Hundred Bio Studies",
        "a_year_match_count": "Year Match Parasite Count",
        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Bio Watcher",
        "a_movie_buff": "Parasyte Movie Evolution",
        "a_ova_hunter": "OVA Bio Hunter",
        "a_ona_explorer": "ONA Bio Explorer",
        "a_special_watcher": "Special Bio Episode",
        "a_short_king": "Short Skirmish Bio King",
        "a_variety_pack": "All-Format Bio Regiment",
        "a_film_festival": "Bio Film Festival",
        "a_music_video": "Parasyte Music Video",
        "a_tv_short": "Quick Bio Recon Clip",
        "a_movie_marathon": "Bio Movie Marathon",
        "a_double_length": "Double-Length Bio Operation",
        "a_anthology": "Parasyte Anthology",
        "a_mini_series": "Mini Bio Campaign",
        "a_theatrical": "Theatrical Bio Premiere",
        "a_format_master": "Format Master Hybrid",
        "a_long_movie": "Feature-Length Bio Expedition",
        "a_back_catalog": "Back Catalog Bio Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Bio Collector",
        "a_format_balance": "Balanced Bio Formats",
        "a_episodic_master": "Episodic Bio Master",
        "a_sequel_movie": "Sequel Bio Film",
        "a_recap_watcher": "Recap Bio Briefing",
        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Bio Patrol Streak",
        "a_mega_streak": "Mega Bio Campaign Streak",
        "a_weekly_warrior": "Weekly Bio Warrior",
        "a_monthly_watcher": "Monthly Bio Duty",
        "a_comeback": "Return from Parasite Attack",
        "a_weekend_streak": "Weekend Bio Sortie Streak",
        "a_no_zero_days": "No Zero Bio Days",
        "a_iron_will": "Iron Will of the Hybrid",
        "a_habit_formed": "Bio Training Regimen Formed",
        "a_consistent_pace": "Consistent Bio Evolution",
        "a_year_long": "Year-Long Bio Campaign",
        "a_double_streak": "Double Bio Assault Streak",
        "a_streak_recovery": "Recovery After Parasite Attack",
        "a_daily_minimum": "Daily Minimum Bio Duty",
        "a_winter_streak": "Winter Bio Campaign",
        "a_summer_streak": "Summer Bio Offensive",
        "a_morning_streak": "Morning Bio Drill Streak",
        "a_night_streak": "Night Bio Patrol Streak",
        "a_unbreakable": "Unbreakable Hybrid Will",
        "a_eternal_flame": "Eternal Flame of Evolution",
        "a_completion_streak": "Completion Bio Chain",
        "a_rating_streak": "Rating Bio Streak",
        "a_multi_ep_streak": "Multi-Episode Bio Offensive",
        "a_genre_streak": "Genre Bio Streak",
        "a_studio_streak": "Studio Bio Loyalty Streak",
        "a_perfect_week": "Perfect Week of Bio Service",
        // ── ANIME SCORING ──
        "a_critic": "Bio Tribunal Judge",
        "a_perfect_ten": "Perfect 10 Bio Rating",
        "a_harsh_critic": "Gotou's Harsh Standards",
        "a_fair_judge": "Reiko's Fair Assessment",
        "a_generous_spirit": "Generous Hybrid Spirit",
        "a_score_all": "Full Bio Roster Evaluation",
        "a_wide_range": "Wide Range Bio Assessment",
        "a_controversial": "Controversial Evolution Decision",
        "a_consistent_scorer": "Consistent Bio Evaluator",
        "a_score_sniper": "Precision Bio Sniper",
        "a_evolving_taste": "Evolving Bio Strategy",
        "a_bell_curve": "Bell Curve Bio Scores",
        "a_picky_watcher": "Selective Bio Commander",
        "a_100_rated": "Century of Bio Evaluations",
        "a_500_rated": "Five Hundred Bio Reports",
        "a_mediocre_majority": "Middle Ground Bio Strategist",
        "a_rating_spree": "Bio Rating Barrage",
        "a_score_variance": "Variable Bio Ratings",
        "a_masterpiece_hunter": "Masterpiece Bio Hunter",
        "a_contrarian": "Contrarian Bio Scout",
        "a_optimist": "Optimist of Humanity",
        "a_score_distributor": "Score Distributor Bio General",
        "a_genre_critic": "Genre Bio Critic",
        "a_mean_above_8": "Elite Bio Average",
        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Humanity Vow",
        "a_valentines_weeb": "Valentine's Hybrid Bond",
        "a_pi_day": "Pi Day Bio Calculation",
        "a_april_fools": "April Fools Parasite Prank",
        "a_international_anime_day": "International Hybrid Day",
        "a_star_wars_day": "Parasite Empire Day",
        "a_summer_solstice": "Summer Solstice Bio Expedition",
        "a_tanabata": "Tanabata Wish for Humanity",
        "a_friday_13th": "Friday the 13th Parasite Attack",
        "a_halloween_spirit": "Halloween Parasite Horror",
        "a_thanksgiving_binge": "Thanksgiving Bio Feast",
        "a_christmas_special": "Midwinter Bio Festival",
        "a_new_years_eve": "New Year's Eve Hybrid Stand",
        "a_birthday_watch": "Birthday Host Enlistment",
        "a_holiday_marathon": "Holiday Bio Marathon",
        "a_independence_day": "Human Independence Day",
        "a_culture_day": "Parasite Culture Day",
        "a_spring_equinox": "Spring Bio Advance",
        "a_earth_day": "Protect Earth from Parasites",
        "a_labor_day": "Bio Lab Labor Day",
        "a_winter_solstice": "Winter Bio Solstice",
        "a_anime_birthday": "Parasyte Anniversary",
        "a_every_holiday": "Every Holiday Bio Scout",
        "a_consecutive_holidays": "Consecutive Holiday Bio Studies",
        // ── ANIME META ──
        "a_meta_first_unlock": "First Hybrid Power Awakened",
        "a_meta_collector": "Bio Badge Collector",
        "a_meta_category_starter": "Category Bio Initiation",
        "a_meta_tier_climber": "Rank in the Bio Lab",
        "a_meta_tier_max": "Hybrid-Class Researcher",
        "a_meta_xp_earner": "XP from Parasite Kills",
        "a_meta_difficulty_easy": "Easy Bio Exercise",
        "a_meta_difficulty_hard": "Legendary Gotou Mode",
        "a_meta_unlock_spree": "Unlock Spree Migi Slash",
        "a_meta_completionist": "Meta Bio Completionist",
        "a_meta_diverse": "Diverse Bio Portfolio",
        "a_meta_dominator": "Meta Dominator of Parasites",
        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Bio Chapter",
        "m_chapter_counter": "Parasite Chapter Counter",
        "m_chapter_titan": "Legendary Chapter Evolution",
        "m_reading_hours": "Hours Studying Bio Texts",
        "m_reading_time_lord": "Migi's Reading Memory",
        "m_manga_collector": "Bio Archive Collector",
        "m_library_legend": "Bio Library Reading Legend",
        "m_first_complete": "First Bio Manga Done",
        "m_hundred_club": "Hundred-Chapter Bio Club",
        "m_first_day": "First Day Bio Reading",
        "m_first_rating": "First Bio Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Bio Pages",
        "m_volume_collector": "Bio Volume Collector",
        "m_year_explorer": "Year of Bio Exploration",
        "m_century_reader": "Century Bio Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Bio Chapters",
        "m_thousand_ch": "Thousand-Chapter Bio Campaign",
        "m_reading_ten": "Ten Bio Manuscripts at Once",
        "m_ptr_hoarder": "Bio Reading Backlog",
        "m_dropped_honesty": "Honest Bio Retreat",
        "m_season_reader": "Bio Seasonal Reading",
        "m_active_reader": "Active Bio Field Reader",
        "m_five_thousand_ch": "Five Thousand Bio Chapters",
        "m_ten_completed": "Ten Bio Manga Complete",
        "m_fifty_completed": "Fifty Bio Missions Done",
        "m_five_hundred_completed": "Five Hundred Bio Victories",
        "m_mean_score_tracker": "Average Bio Manuscript Rating",
        "m_unique_authors": "Unique Bio Author Encounters",
        "m_all_status": "All Bio Reading Statuses",
        "m_first_favorite": "First Bio Manga Bond",
        "m_favorites_collector": "Bio Favorites Arsenal",
        "m_days_spent_reading": "Days in Bio Garrison",
        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Bio Reading Advance",
        "m_marathon_reader": "Evolution Marathon Reader",
        "m_weekend_reader": "Weekend Bio Reading",
        "m_non_stop_reading": "Non-Stop Bio Page Turning",
        "m_one_more_chapter": "One More Bio Chapter",
        "m_speed_read": "Migi Speed Read",
        "m_double_story": "Double Bio Manuscript",
        "m_triple_read": "Triple Bio Reading",
        "m_five_a_day": "Five Bio Reads a Day",
        "m_chapter_chain": "Bio Chapter Chain",
        "m_volume_binge": "Bio Volume Binge",
        "m_power_reader": "Power Bio Reader",
        "m_half_day_read": "Half-Day Bio Archive",
        "m_full_day_read": "Full-Day Bio Study",
        "m_power_weekend": "Power Bio Weekend Reading",
        "m_binge_king": "King of the Bio Reading Corps",
        "m_no_sleep_read": "All-Night Bio Reading",
        "m_full_series_rush": "Full Bio Series Rush",
        "m_seven_day_challenge": "Seven-Day Bio Gathering",
        "m_hundred_day_read": "Hundred-Day Bio Reading",
        "m_volume_rush": "Bio Volume Rush",
        "m_series_sweep": "Bio Series Sweep",
        "m_genre_binge": "Cross-Genre Bio Reading",
        "m_author_binge": "Iwaaki Deep Dive",
        "m_chapter_counter_day": "Daily Bio Chapter Count",
        "m_multi_series_binge": "Multi-Series Bio Reading",
        "m_midnight_binge": "Midnight Bio Archive",
        "m_new_year_binge": "New Year's Bio Reading",
        "m_forty_eight_hour": "Forty-Eight Hour Bio Reading",
        "m_oneshot_binge": "Oneshot Bio Blitz",
        // ── MANGA GENRES ──
        "m_genre_action": "Bio Action Manuscript",
        "m_genre_adventure": "Adventure of the Hybrid",
        "m_genre_comedy": "Migi's Logical Chapters",
        "m_genre_drama": "Drama of Coexistence",
        "m_genre_fantasy": "Fantasy of Parasite World",
        "m_genre_horror": "Parasite Horror Manuscript",
        "m_genre_mystery": "Mystery of the Invaders",
        "m_genre_romance": "Shinichi and Murano Bond",
        "m_genre_scifi": "Bio Tech Manga",
        "m_genre_sol": "Normal School Life Manga",
        "m_genre_sports": "Bio Training Sports",
        "m_genre_supernatural": "Supernatural Parasite Power",
        "m_genre_thriller": "Gotou Thriller Manga",
        "m_genre_psychological": "What is Human Manga",
        "m_genre_isekai": "Isekai Beyond Bio World",
        "m_genre_shounen": "Bio Shounen Heart",
        "m_genre_ecchi": "Bio Hot Springs Manga",
        "m_genre_mahou_shoujo": "Cell Division Manga",
        "m_genre_mecha": "Migi Weapon Blueprints",
        "m_genre_music": "Parasyte OST Collection",
        "m_tag_isekai_new": "New World of Parasites",
        "m_tag_harem": "Host-Parasite Manga",
        "m_tag_bl": "Shinichi and Migi Manga",
        "m_tag_gl": "Reiko's Story Manga",
        "m_tag_historical": "Parasite Invasion History",
        "m_tag_military": "Anti-Parasite Military Manga",
        "m_tag_school": "High School Parasite Manga",
        "m_tag_martial_arts": "Migi Combat Manual",
        "m_tag_vampire": "Parasite Blood Manga",
        "m_tag_samurai": "Parasite Blade Master",
        "m_tag_space": "Parasite Origin Beyond",
        "m_tag_parody": "Chibi Parasite Corps Manga",
        "m_tag_idol": "Migi Idol Manga",
        "m_tag_post_apocalyptic": "Post-Invasion Manga",
        "m_tag_cyberpunk": "Bio-Weapon Tech Manga",
        "m_tag_shoujo": "Murano's Story Manga",
        "m_tag_survival": "Survival Among Parasites Manga",
        "m_tag_cooking": "Bio Lab Rations Cookbook",
        "m_tag_medical": "Parasite Field Medic Manga",
        "m_tag_villainess": "Reiko Tamura Manga",
        // ── MANGA COMPLETION ──
        "m_completionist": "Bio Manga Completionist",
        "m_mega_completionist": "Supreme Bio Commander",
        "m_completion_rate_50": "Halfway to Gotou",
        "m_completion_rate_75": "Approaching True Humanity",
        "m_completion_rate_90": "Final Bio Chapter Near",
        "m_no_drop": "No Bio Manuscript Abandoned",
        "m_long_runner_complete": "Long Bio Series Endurance",
        "m_sequel_chain": "Sequel Bio Arc Chain",
        "m_clean_list": "Clean Bio Reading Record",
        "m_from_ptr": "Orders Received Bio Read",
        "m_reread_master": "Migi Memory Reread",
        "m_oneshot_complete": "Oneshot Bio Mission",
        "m_same_day_start_finish": "Same-Day Bio Blitz",
        "m_revival": "Revival by Migi's Blood",
        "m_zero_to_hundred": "Normal Student to Bio Scholar",
        "m_five_genre_complete": "Five Bio Genres Mastered",
        "m_full_collection": "Full Bio Archive",
        "m_batch_complete": "Bio Batch Clearance",
        "m_paused_to_done": "Back from Bio Hiatus",
        "m_completion_spree": "Bio Completion Barrage",
        "m_format_completionist": "Bio Format Completion",
        "m_catch_up": "Caught Up with Bio Serialization",
        "m_multi_reread": "Multi-Pass Bio Reread",
        "m_dropped_recovery": "Recovered from Parasite Grip",
        "m_ten_perfect_scores": "Ten Perfect Bio Scores",
        "m_complete_genre_span": "All-Genre Bio Scout",
        "m_monthly_completions": "Monthly Bio Victories",
        "m_yearly_completions": "Yearly Bio Campaign",
        "m_rapid_complete": "Rapid Bio Processing",
        "m_author_complete": "Iwaaki's Complete Works",
        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Bio Reader",
        "m_mangaka_lover": "Iwaaki Devotee",
        "m_rereader": "Parasite Saga Rereader",
        "m_triple_reread": "Triple Bio Reread",
        "m_annual_reread": "Annual Parasite Reread",
        "m_publisher_fan": "Bio Publisher Fan",
        "m_artist_fan": "Iwaaki Art Appreciation",
        "m_adaptation_compare": "Bio Manga vs Anime Compare",
        "m_source_material_fan": "Bio Source Material Scout",
        "m_waiting_weekly": "Weekly Bio Chapter Wait",
        "m_classic_reader": "Classic Bio Manuscript",
        "m_saga_reader": "Saga of Parasyte Reader",
        "m_genre_loyalty": "Bio Genre Loyalty",
        "m_decade_reader": "Decade-Long Bio Reader",
        "m_ln_adaptation": "Bio Light Novel Intel",
        "m_original_work": "Iwaaki's Original Work",
        "m_long_commitment": "Long-Term Bio Reading",
        "m_up_to_date": "Up-to-Date with Parasytes",
        "m_favorite_mangaka": "Iwaaki Honored",
        "m_complete_portfolio": "Complete Bio Portfolio",
        "m_franchise_collector": "Parasyte Franchise Collector",
        "m_serialization_follower": "Bio Serialization Tracker",
        "m_genre_master": "Bio Genre Mastery",
        "m_multi_series_author": "Multi-Series Bio Author Fan",
        "m_format_diversity": "Diverse Bio Reading Formats",
        "m_year_dedication": "Year of Bio Reading",
        "m_ongoing_follower": "Ongoing Bio Series",
        "m_genre_loyalty_50": "Fifty Bio Genre Chapters",
        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Bio Genre Territory Scout",
        "m_publisher_hopper": "Bio Publisher Transfer",
        "m_tag_explorer": "Bio Tag Recon Mission",
        "m_decade_hopper": "Bio Decade Hopping",
        "m_hidden_gem": "Hidden Bio Gem",
        "m_popular_taste": "Popular Among Bio Researchers",
        "m_retro_reader": "Retro Bio Manuscript",
        "m_modern_reader": "Modern Bio Era Reader",
        "m_cross_demographic": "Cross-Demographic Bio Scout",
        "m_underdog_fan": "Underdog Host Fan",
        "m_variety_week": "Week of Bio Readings",
        "m_manhwa_reader": "Bio Manhwa Reader",
        "m_manhua_reader": "Bio Manhua Reader",
        "m_classic_connoisseur": "Classic Bio Connoisseur",
        "m_award_winner": "Medal-Winning Bio Manuscript",
        "m_niche_explorer": "Niche Bio Territory",
        "m_world_manga": "World Bio Manga",
        "m_cult_classic": "Parasyte Cult Classic",
        "m_random_pick": "Random Bio Assignment",
        "m_new_genre_month": "New Bio Genre Monthly",
        "m_year_completionist": "Year Bio Completionist",
        "m_unpopular_opinion": "Unpopular Bio Opinion",
        "m_top_rated_reader": "Top-Rated Bio Source",
        "m_source_variety": "Bio Source Variety",
        "m_low_score_brave": "Brave Bio Low-Score Reader",
        "m_short_manga_explorer": "Short Bio Skirmish",
        "m_long_manga_explorer": "Long Bio Campaign Manuscript",
        "m_serialization_explorer": "Bio Serialization Explorer",
        // ── MANGA TIME ──
        "m_night_owl": "Night Bio Reading",
        "m_early_bird": "Dawn Bio Reading",
        "m_lunch_reader": "School Lunch Bio Reading",
        "m_commute_reader": "Bio Commute Reading",
        "m_four_am_club": "4 AM Bio Sentry Reader",
        "m_new_year_read": "New Year's Bio Reading Oath",
        "m_all_hours": "All-Hours Bio Archive",
        "m_prime_time_reader": "Prime Time Bio Manuscript",
        "m_workday_reader": "On-Duty Bio Reader",
        "m_sunday_read": "Sunday Bio Reading Marathon",
        "m_morning_routine": "Morning Bio Formation Reading",
        "m_night_shift_reader": "Night Shift Bio Reader",
        "m_seasonal_premier_read": "Bio New Release Intel",
        "m_clock_collector": "Parasite Clock Collector",
        "m_late_night_horror": "Midnight Parasite Horror Read",
        "m_afternoon_reader": "Afternoon Bio Reading",
        "m_golden_hour_reader": "Golden Hour Bio Reading",
        "m_dawn_reader": "Dawn Bio Reading Scout",
        "m_twilight_reader": "Twilight Bio Reading",
        "m_midnight_start": "Midnight Bio Reading Mission",
        "m_weekend_binge_hours": "Weekend Bio Binge Reading",
        "m_late_night_regular": "Late Night Bio Reader",
        "m_sunrise_reader": "Sunrise Over Bio Ruins Reader",
        "m_every_day_of_week": "Every Day Bio Reading",
        "m_monthly_hours": "Monthly Bio Hours Logged",
        "m_bedtime_reader": "Bedtime Bio Reader",
        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Iwaaki Art Appreciator",
        "m_webtoon_reader": "Bio Webtoon Intelligence",
        "m_full_color": "Full Color Bio Manuscript",
        "m_doujin_reader": "Underground Bio Doujin",
        "m_anthology_reader": "Bio Anthology Reader",
        "m_adaptation_reader": "Bio Adaptation Study",
        "m_longstrip_reader": "Vertical Bio Scroll Reader",
        "m_4koma_reader": "4-Koma Bio Comedy",
        "m_oneshot_reader": "Oneshot Bio Mission Reader",
        "m_format_variety": "Bio Format Variety",
        "m_light_novel_reader": "Bio Light Novel Reader",
        "m_novel_reader": "Bio Novel Archive Reader",
        "m_visual_storyteller": "Bio Battle Narrator",
        "m_colored_classic": "Colored Bio Classic",
        "m_webcomic_fan": "Bio Webcomic Fan",
        "m_manga_to_anime": "Bio Manga to Anime",
        "m_seinen_reader": "Seinen Bio Reader",
        "m_josei_reader": "Josei Bio Perspective",
        "m_award_winning_art": "Medal-Winning Bio Artwork",
        "m_debut_work": "Bio Debut Manuscript",
        "m_vertical_scroll": "Vertical Bio Scroll Intel",
        "m_traditional_format": "Traditional Bio Format",
        "m_cross_media": "Bio Cross-Media Intel",
        "m_spinoff_reader": "Bio Spinoff Mission",
        "m_remake_reader": "Bio Remake Assignment",
        "m_collaboration_reader": "Bio Joint Operation Manuscript",
        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Bio Reading Streak",
        "m_mega_streak": "Mega Bio Reading Streak",
        "m_weekly_warrior": "Weekly Bio Warrior Reader",
        "m_monthly_reader": "Monthly Bio Reader",
        "m_comeback": "Return from Bio Exile",
        "m_weekend_streak": "Weekend Bio Reading Streak",
        "m_no_zero_days": "No Zero Bio Reading Days",
        "m_iron_will": "Iron Will Bio Reader",
        "m_habit_formed": "Bio Reading Regimen",
        "m_consistent_pace": "Consistent Bio Advance",
        "m_year_long": "Year-Long Bio Reading",
        "m_double_streak": "Double Bio Reading Streak",
        "m_streak_recovery": "Bio Reading Streak Recovery",
        "m_daily_minimum": "Daily Bio Minimum Pages",
        "m_winter_streak": "Winter Bio Reading Campaign",
        "m_summer_streak": "Summer Bio Offensive Reading",
        "m_morning_streak": "Morning Bio Formation Reading",
        "m_night_streak": "Night Bio Patrol Reading",
        "m_unbreakable": "Unbreakable Bio Reading Will",
        "m_eternal_flame": "Eternal Flame of Bio Knowledge",
        "m_chapter_a_day": "Chapter a Day Bio Discipline",
        "m_genre_streak": "Genre Bio Reading Streak",
        "m_completion_streak": "Completion Bio Reading Chain",
        "m_rating_streak": "Bio Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Bio Streak",
        "m_author_streak": "Iwaaki Dedication Streak",
        "m_perfect_week_manga": "Perfect Bio Reading Week",
        "m_diverse_streak": "Diverse Bio Reading Streak",
        // ── MANGA SCORING ──
        "m_critic": "Bio Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Bio Manuscript",
        "m_harsh_critic": "Gotou's Reading Standards",
        "m_fair_judge": "Reiko's Fair Review",
        "m_generous_spirit": "Generous Bio Reader Spirit",
        "m_score_all": "Full Bio Manuscript Assessment",
        "m_wide_range": "Wide Range Bio Scores",
        "m_controversial": "Controversial Bio Opinion",
        "m_consistent_scorer": "Consistent Bio Scorer",
        "m_score_sniper": "Precision Bio Score Sniper",
        "m_evolving_taste": "Evolving Bio Reading Taste",
        "m_bell_curve": "Bell Curve Bio Scores",
        "m_picky_reader": "Selective Bio Commander Reader",
        "m_100_rated": "Century of Bio Ratings",
        "m_500_rated": "Five Hundred Bio Rating Reports",
        "m_mediocre_majority": "Middle Ground Bio Reader",
        "m_rating_spree": "Bio Rating Barrage",
        "m_score_variance": "Variable Bio Manuscript Scores",
        "m_binge_rater": "Binge Bio Rating Session",
        "m_reread_rerate": "Reread and Re-Rate Bio Manga",
        "m_masterpiece_hunter": "Masterpiece Bio Manuscript Hunter",
        "m_contrarian": "Contrarian Bio Reader",
        "m_optimist": "Optimistic Bio Reader",
        "m_score_distributor": "Score Distributor Bio General",
        "m_genre_critic": "Genre Bio Reading Critic",
        "m_mean_above_8": "Elite Bio Reading Average",
        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Bio Reading Vow",
        "m_valentines_read": "Valentine's Bio Bond Read",
        "m_pi_day": "Pi Day Bio Chapter Count",
        "m_april_fools": "April Fools Bio Chibi",
        "m_international_manga_day": "International Bio Manga Day",
        "m_free_comic_day": "Free Bio Comic Day",
        "m_summer_solstice": "Summer Solstice Bio Reading",
        "m_tanabata": "Tanabata Bio Reading Wish",
        "m_friday_13th": "Friday 13th Parasite Manuscript",
        "m_halloween_read": "Halloween Bio Horror Read",
        "m_thanksgiving_binge": "Thanksgiving Bio Reading Feast",
        "m_christmas_read": "Midwinter Bio Festival Read",
        "m_new_years_eve": "New Year's Eve Bio Final Read",
        "m_birthday_read": "Birthday Bio Reading Gift",
        "m_holiday_marathon": "Holiday Bio Reading Marathon",
        "m_independence_day": "Human Independence Reading",
        "m_culture_day": "Bio Culture Day Manuscript",
        "m_spring_equinox": "Spring Bio Equinox Reading",
        "m_earth_day": "Earth Day Bio Conservation",
        "m_labor_day": "Bio Labor Reading Day",
        "m_winter_solstice": "Winter Bio Solstice Reading",
        "m_manga_birthday": "Parasyte Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Bio Reader",
        "m_consecutive_holidays": "Consecutive Bio Holiday Reads",
        // ── MANGA SPECIAL ──
        "m_round_number": "Bio Round Number Milestone",
        "m_fibonacci": "Bio Fibonacci Chapter Pattern",
        "m_palindrome_day": "Palindrome Bio Reading Day",
        "m_binary_day": "Binary Bio Signal Day",
        "m_full_moon_read": "Full Moon Bio Read",
        "m_leap_year_read": "Leap Year Bio Reading",
        "m_triple_seven": "Triple Seven Bio Forms",
        "m_thousand_complete": "Thousand Bio Victories",
        "m_nice": "Nice Bio Chapter Count",
        "m_power_level_chapters": "Migi-Level Bio Chapters",
        "m_answer_42": "Answer to Humanity's Reading",
        "m_square_number": "Perfect Bio Formation Chapters",
        "m_prime_count": "Prime Bio Chapter Count",
        "m_matching_date": "Matching Bio Reading Date",
        "m_century_chapter": "Century Bio Chapter Milestone",
        "m_pi_chapters": "Pi Bio Chapter Calculation",
        "m_synchronicity": "Bio Reading Synchronicity",
        "m_world_record": "World Record Bio Chapter Count",
        "m_genre_clash": "Bio Genre Clash Reading",
        "m_time_traveler": "Time-Traveling Bio Reader",
        "m_double_digits": "Double Digit Bio Milestone",
        "m_one_two_three": "Shinichi Migi Murano Chapters",
        "m_lucky_seven": "Seven Lucky Bio Chapters",
        "m_exact_hundred_ch": "Exact Hundred Bio Chapters",
        "m_year_match_count": "Year Match Bio Count",
        "m_chapter_match_date": "Chapter Bio Date Match",
        // ── MANGA FORMATS ──
        "m_manga_format": "Bio Manga Format Specialist",
        "m_manhwa_format": "Bio Manhwa Format Reader",
        "m_manhua_format": "Bio Manhua Format Reader",
        "m_ln_format": "Bio Light Novel Format",
        "m_oneshot_format": "Oneshot Bio Format",
        "m_doujin_format": "Bio Doujin Format Reader",
        "m_novel_format": "Bio Novel Format Reader",
        "m_format_master_manga": "Format Bio Master Reader",
        // ── MANGA META ──
        "m_meta_first_unlock": "First Hybrid Reading Power",
        "m_meta_collector": "Bio Reading Badge Collector",
        "m_meta_category_starter": "Bio Category Initiation",
        "m_meta_tier_climber": "Bio Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Bio Reading Rank",
        "m_meta_xp_earner": "XP from Bio Reading Intel",
        "m_meta_difficulty_easy": "Easy Bio Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Gotou Manuscript",
        "m_meta_unlock_spree": "Bio Reading Unlock Barrage",
        "m_meta_completionist": "Meta Bio Completionist",
        "m_meta_diverse": "Diverse Bio Portfolio",
        "m_meta_dominator": "Meta Dominator Bio Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060806",
        primary: "#2e9e4a",
        secondary: "#1e7838",
        accent: "#8090a0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        cell_division: { label: "Cell Division", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        parasite_tendrils: { label: "Parasite Tendrils", maxCount: 8, defaultEnabled: true, defaultIntensity: 55 },
        biology_sparks: { label: "Biology Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
        alien_matter: { label: "Alien Matter", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1: "Normal High Schooler",
        5: "Migi's Host",
        15: "Parasite Detector",
        30: "Hybrid Specimen",
        45: "Reiko's Target",
        60: "Gotou's Adversary",
        80: "Evolutionary Anomaly",
        100: "Neither Human Nor Parasite",
    },
}
