import { AnimeThemeConfig } from "./types"
import {
    GiMirrorMirror,
    GiTheaterCurtains,
    GiLightBulb,
    GiBrokenShield,
    GiShadowFollower,
    GiEvilEyes,
    GiPuzzle,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const perfectBlueTheme: AnimeThemeConfig = {
    id: "perfect-blue",
    displayName: "Perfect Blue",
    description: "Who are you? A fractured psychological thriller interface inspired by Mima Kirigoe's descent — shattered mirrors, stolen identities, and Satoshi Kon's masterpiece of paranoia.",
    fontFamily: "'Lora', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;1,400&display=swap",
    cssVars: {
        // Brand → deep blue (30 90 200)
        "--color-brand-200": "140 175 235",
        "--color-brand-300": "100 145 220",
        "--color-brand-400": "60 115 210",
        "--color-brand-500": "30 90 200",
        "--color-brand-600": "22 72 170",
        "--color-brand-700": "16 55 140",
        "--color-brand-800": "10 40 110",
        "--color-brand-900": "6 25 80",
        "--color-brand-950": "3 12 50",
        "--brand": "30 90 200",
        // Near-black background
        "--background": "#020408",
        "--paper": "#040810",
        "--color-gray-950": "2 4 8",
        "--color-gray-900": "4 8 16",
        "--color-gray-800": "10 18 32",
        "--color-gray-700": "20 32 55",
        "--color-gray-600": "38 52 78",
        "--color-gray-500": "62 78 108",
        "--color-gray-400": "100 118 152",
        "--color-gray-300": "148 162 190",
        "--color-gray-200": "192 200 218",
        "--color-gray-100": "224 228 238",
        "--color-gray-50": "242 244 248",
    },
    sidebarOverrides: {
        "home": { icon: GiMirrorMirror, label: "Reflection" },
        "schedule": { icon: GiAlarmClock, label: "Scene Schedule" },
        "manga": { icon: LuBookOpen, label: "Rumi's Scripts" },
        "lists": { icon: GiTheaterCurtains, label: "Cast List" },
        "discover": { icon: GiBullseye, label: "Audition Call" },
        "torrent-list": { icon: GiAnvilImpact, label: "Raw Footage" },
        "debrid": { icon: GiBrokenShield, label: "Shattered Takes" },
        "unmatched": { icon: GiShadowFollower, label: "Lost Identity" },
        "enmasse": { icon: GiResize, label: "Mass Exposure" },
        "scan-summaries": { icon: TbReportSearch, label: "Case Files" },
        "auto-downloader": { icon: LuRss, label: "Stalker Feed" },
        "community": { icon: GiEvilEyes, label: "Me-Mania's Room" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Paranoia Alerts" },
        "achievements": { icon: GiTrophy, label: "Fractured Roles" },
        "theme-manager": { icon: GiPalette, label: "Scene Palette" },
        "extensions": { icon: BiExtension, label: "Double Vision" },
        "sync": { icon: IoCloudOfflineOutline, label: "Mirror Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Director's Cut" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Audition",
        "a_episode_counter": "Scene Counter",
        "a_episode_titan": "Starring Role",
        "a_hours_invested": "Hours On Set",
        "a_time_lord": "Rewound Memory",
        "a_anime_collector": "Role Collector",
        "a_library_legend": "Filmography Legend",
        "a_first_complete": "First Wrap",
        "a_hundred_club": "Hundred Takes",
        "a_first_day": "Debut Day",
        "a_first_rating": "First Review",
        "a_ten_thousand_min": "Ten Thousand Minutes",
        "a_season_veteran": "Season Veteran",
        "a_year_explorer": "Year In Spotlight",
        "a_century_watcher": "Century Screening",
        "a_five_hundred_eps": "Five Hundred Frames",
        "a_thousand_eps": "Thousand Scenes",
        "a_watching_ten": "Ten Personas",
        "a_ptw_hoarder": "Script Hoarder",
        "a_dropped_honesty": "Honest Exit",
        "a_five_thousand_eps": "Five Thousand Cuts",
        "a_ten_completed": "Ten Films Wrapped",
        "a_fifty_completed": "Fifty Curtain Calls",
        "a_five_hundred_completed": "Five Hundred Roles",
        "a_mean_score_tracker": "Average Critique",
        "a_unique_studios": "Unique Studios",
        "a_days_spent_watching": "Days In Darkness",
        "a_all_status": "All Statuses",
        "a_first_favorite": "First Obsession",
        "a_favorites_collector": "Obsession Collector",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Dissociative Binge",
        "a_marathon_runner": "Sleepless Marathon",
        "a_weekend_warrior": "Weekend Fugue",
        "a_non_stop": "Relentless Spiral",
        "a_one_more_episode": "One More Scene",
        "a_speed_run": "Speed Exposure",
        "a_double_feature": "Double Feature",
        "a_triple_threat": "Triple Identity",
        "a_five_a_day": "Five A Day",
        "a_back_to_back": "Back To Back",
        "a_seasonal_binge": "Full Season Blur",
        "a_cour_crusher": "Cour Crusher",
        "a_half_day_watch": "Half-Day Trance",
        "a_full_day_watch": "Full-Day Delusion",
        "a_power_weekend": "Power Weekend",
        "a_binge_king": "Binge Monarch",
        "a_no_sleep": "Sleepless Night",
        "a_entire_season": "Entire Season",
        "a_seven_day_challenge": "Seven-Day Spiral",
        "a_hundred_day_binge": "Hundred-Day Fixation",
        "a_genre_binge": "Genre Crossover",
        "a_studio_binge": "Studio Immersion",
        "a_season_sweep": "Season Sweep",
        "a_forty_eight_hour": "Forty-Eight Hours",
        "a_ep_counter_day": "Daily Scene Count",
        "a_multi_series_binge": "Multi-Role Binge",
        "a_midnight_binge": "Midnight Screening",
        "a_new_year_binge": "New Year Illusion",

        // ── ANIME GENRES ──
        "a_genre_action": "Violent Scene",
        "a_genre_adventure": "Stranger's Journey",
        "a_genre_comedy": "Nervous Laughter",
        "a_genre_drama": "Dramatic Shift",
        "a_genre_fantasy": "Delusional Fantasy",
        "a_genre_horror": "Real Horror",
        "a_genre_mystery": "Unsolved Case",
        "a_genre_romance": "Toxic Devotion",
        "a_genre_scifi": "Distorted Future",
        "a_genre_sol": "Lost Normalcy",
        "a_genre_sports": "Stage Performer",
        "a_genre_supernatural": "Paranormal Glimpse",
        "a_genre_thriller": "Thriller Expert",
        "a_genre_mecha": "Mechanical Illusion",
        "a_genre_music": "Idol's Melody",
        "a_genre_psychological": "Psychological Depth",
        "a_genre_ecchi": "Provocative Role",
        "a_genre_mahou_shoujo": "Magical Persona",
        "a_tag_isekai": "Alternate Reality",
        "a_tag_harem": "Crowd Of Faces",
        "a_tag_bl": "Hidden Bond",
        "a_tag_gl": "Mirror Sisters",
        "a_tag_historical": "Buried Past",
        "a_tag_military": "Tactical Pursuit",
        "a_tag_school": "School Flashback",
        "a_tag_martial_arts": "Violent Reflex",
        "a_tag_vampire": "Blood Fixation",
        "a_tag_samurai": "Blade Memory",
        "a_tag_space": "Void Gazing",
        "a_tag_parody": "Twisted Parody",
        "a_tag_idol": "Idol Complex",
        "a_tag_post_apocalyptic": "After The Fall",
        "a_tag_cyberpunk": "Digital Stalker",
        "a_tag_shounen": "Youthful Mask",
        "a_tag_seinen": "Adult Reality",
        "a_tag_shoujo": "Fragile Facade",
        "a_tag_josei": "Bitter Truth",
        "a_tag_survival": "Survival Instinct",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Exposure",
        "a_mega_completionist": "Mega Obsessive",
        "a_completion_rate_50": "Halfway Unraveled",
        "a_completion_rate_75": "Almost Broken",
        "a_completion_rate_90": "Near Complete",
        "a_no_drop": "No Escape",
        "a_long_runner_complete": "Long Nightmare",
        "a_sequel_chain": "Sequel Thread",
        "a_clean_list": "Clean Record",
        "a_from_ptw": "Script Fulfilled",
        "a_rewatch_master": "Déjà Vu",
        "a_short_complete": "Quick Scene",
        "a_same_day_start_finish": "Same-Day Wrap",
        "a_revival": "Revival Take",
        "a_zero_to_hero": "Unknown To Star",
        "a_five_genre_complete": "Five Genre Roles",
        "a_full_franchise": "Full Franchise",
        "a_batch_complete": "Batch Processing",
        "a_paused_to_done": "Returned Role",
        "a_completion_spree": "Completion Frenzy",
        "a_multi_rewatch": "Multi Replay",
        "a_dropped_recovery": "Recovered Scene",
        "a_ten_perfect_scores": "Ten Perfect Takes",
        "a_seasonal_clear": "Seasonal Clear",
        "a_complete_genre_span": "Genre Spectrum",
        "a_monthly_completions": "Monthly Wraps",
        "a_yearly_completions": "Yearly Portfolio",
        "a_rapid_complete": "Rapid Closure",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Follower",
        "a_studio_devotee": "Studio Devotee",
        "a_rewatcher": "Obsessive Replay",
        "a_triple_rewatch": "Triple Rewatch",
        "a_annual_tradition": "Annual Ritual",
        "a_director_fan": "Director's Muse",
        "a_voice_actor_fan": "Voice Fixation",
        "a_ost_lover": "Haunting Score",
        "a_source_reader": "Source Material",
        "a_waiting_weekly": "Weekly Anticipation",
        "a_childhood_revisit": "Childhood Ghost",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Genre Loyalty",
        "a_decade_watcher": "Decade Observer",
        "a_adaptation_hunter": "Adaptation Hunter",
        "a_original_anime_fan": "Original Broadcast",
        "a_long_commitment": "Long Commitment",
        "a_perfect_attendance": "Perfect Attendance",
        "a_favorite_studio_5": "Five Studios",
        "a_complete_catalog": "Complete Catalog",
        "a_franchise_collector": "Franchise Obsession",
        "a_airing_follower": "Currently Airing",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Staff Dossier",
        "a_multi_season_fan": "Multi-Season Fan",
        "a_format_diversity": "Format Diversity",
        "a_year_dedication": "Year Dedicated",
        "a_season_dedication": "Season Devoted",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Unknown Territory",
        "a_studio_hopper": "Studio Transfer",
        "a_tag_explorer": "Tag Investigation",
        "a_decade_hopper": "Decade Shifter",
        "a_hidden_gem": "Hidden Scene",
        "a_popular_taste": "Popular Opinion",
        "a_retro_appreciator": "Retro Appreciator",
        "a_modern_viewer": "Modern Viewer",
        "a_cross_demographic": "Cross Demographic",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Week",
        "a_foreign_cinema": "Foreign Cinema",
        "a_classic_connoisseur": "Classic Thriller",
        "a_every_season": "Every Season",
        "a_award_winner": "Award Winner",
        "a_niche_explorer": "Niche Explorer",
        "a_global_anime": "Global Entry",
        "a_cult_classic": "Cult Following",
        "a_random_pick": "Random Casting",
        "a_new_genre_month": "New Genre Monthly",
        "a_seasonal_completionist": "Seasonal Wrap",
        "a_unpopular_opinion": "Unpopular Verdict",
        "a_top_rated_viewer": "Top Rated Viewer",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Viewing",
        "a_upcoming_watcher": "Upcoming Intel",
        "a_short_series_explorer": "Short Film Fan",
        "a_long_series_explorer": "Long Feature Fan",

        // ── ANIME TIME ──
        "a_night_owl": "Insomniac Owl",
        "a_early_bird": "Dawn Paranoia",
        "a_lunch_break": "Midday Break",
        "a_golden_hour": "Golden Hour",
        "a_four_am_club": "4 AM Terrors",
        "a_witching_hour": "Witching Hour",
        "a_new_year_watch": "New Year Watch",
        "a_midnight_premiere": "Midnight Premiere",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Watcher",
        "a_afternoon_delight": "Afternoon Scene",
        "a_prime_time": "Prime Time",
        "a_workday_watcher": "Workday Viewer",
        "a_sunday_marathon": "Sunday Marathon",
        "a_rainy_day": "Rainy Day Mood",
        "a_morning_routine": "Morning Routine",
        "a_night_shift": "Night Shift",
        "a_twilight_zone": "Twilight Zone",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge",
        "a_late_night_regular": "Late Night Regular",
        "a_sunrise_watcher": "Sunrise Watcher",
        "a_holiday_watcher": "Holiday Viewing",
        "a_every_day_of_week": "Every Day",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Gathering",
        "a_party_host": "Party Director",
        "a_social_butterfly": "Social Persona",
        "a_group_binge": "Group Screening",
        "a_party_regular": "Regular Attendee",
        "a_sync_viewer": "Synced Viewing",
        "a_commentator": "Scene Commentator",
        "a_party_marathon": "Marathon Party",
        "a_full_house": "Full Audience",
        "a_community_pillar": "Community Pillar",
        "a_watch_party_streak": "Party Streak",
        "a_diverse_party": "Diverse Crowd",
        "a_late_night_party": "Late Night Party",
        "a_party_veteran": "Veteran Host",
        "a_genre_party": "Genre Party",
        "a_weekly_party": "Weekly Gathering",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Recommender",
        "a_party_completionist": "Party Completionist",
        "a_social_scorer": "Social Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Fibonacci Pattern",
        "a_palindrome_day": "Palindrome Day",
        "a_binary_day": "Binary Signal",
        "a_full_moon": "Full Moon Night",
        "a_leap_year": "Leap Year Glitch",
        "a_time_traveler": "Time Distortion",
        "a_genre_clash": "Genre Collision",
        "a_triple_seven": "Triple Seven",
        "a_thousand_complete": "Thousand Complete",
        "a_pi_episodes": "Pi Episodes",
        "a_synchronicity": "Synchronicity",
        "a_world_record": "World Record",
        "a_nice": "Nice Count",
        "a_power_level": "Power Level",
        "a_answer_42": "The Answer",
        "a_square_number": "Square Number",
        "a_prime_count": "Prime Count",
        "a_matching_date": "Matching Date",
        "a_century_episode": "Century Episode",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "One Two Three",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Exact Hundred",
        "a_year_match_count": "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast",
        "a_movie_buff": "Film Buff",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Explorer",
        "a_special_watcher": "Special Viewing",
        "a_short_king": "Short King",
        "a_variety_pack": "Variety Pack",
        "a_film_festival": "Film Festival",
        "a_music_video": "Music Reel",
        "a_tv_short": "Quick Clip",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Anthology Reel",
        "a_mini_series": "Mini Series",
        "a_theatrical": "Theatrical Cut",
        "a_format_master": "Format Master",
        "a_long_movie": "Feature Length",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "Commercial Break",
        "a_pv_collector": "Preview Collector",
        "a_format_balance": "Format Balance",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Film",
        "a_recap_watcher": "Recap Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Obsession",
        "a_mega_streak": "Mega Fixation",
        "a_weekly_warrior": "Weekly Stalker",
        "a_monthly_watcher": "Monthly Routine",
        "a_comeback": "Comeback Scene",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Habit Formed",
        "a_consistent_pace": "Consistent Pace",
        "a_year_long": "Year-Long Spiral",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Recovery",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Streak",
        "a_summer_streak": "Summer Streak",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable",
        "a_eternal_flame": "Eternal Flame",
        "a_completion_streak": "Completion Chain",
        "a_rating_streak": "Rating Streak",
        "a_multi_ep_streak": "Multi-Episode Run",
        "a_genre_streak": "Genre Streak",
        "a_studio_streak": "Studio Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Harsh Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Ruthless Review",
        "a_fair_judge": "Fair Verdict",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Score All",
        "a_wide_range": "Wide Range",
        "a_controversial": "Controversial Take",
        "a_consistent_scorer": "Consistent Scorer",
        "a_score_sniper": "Precision Scorer",
        "a_evolving_taste": "Evolving Taste",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Selective Eye",
        "a_100_rated": "Century Rated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Rating Spree",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Hunter",
        "a_contrarian": "Contrarian View",
        "a_optimist": "Eternal Optimist",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year Resolve",
        "a_valentines_weeb": "Valentine Obsession",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Deception",
        "a_international_anime_day": "Anime Day",
        "a_star_wars_day": "Empire Day",
        "a_summer_solstice": "Summer Solstice",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday The 13th",
        "a_halloween_spirit": "Halloween Spirit",
        "a_thanksgiving_binge": "Thanksgiving Binge",
        "a_christmas_special": "Christmas Special",
        "a_new_years_eve": "New Year's Eve",
        "a_birthday_watch": "Birthday Viewing",
        "a_holiday_marathon": "Holiday Marathon",
        "a_independence_day": "Independence Day",
        "a_culture_day": "Culture Day",
        "a_spring_equinox": "Spring Equinox",
        "a_earth_day": "Earth Day",
        "a_labor_day": "Labor Day",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anime Anniversary",
        "a_every_holiday": "Every Holiday",
        "a_consecutive_holidays": "Consecutive Holidays",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Awakening",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Category Initiated",
        "a_meta_tier_climber": "Tier Climber",
        "a_meta_tier_max": "Maximum Tier",
        "a_meta_xp_earner": "XP Earned",
        "a_meta_difficulty_easy": "Easy Take",
        "a_meta_difficulty_hard": "Impossible Scene",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Completionist",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Meta Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Page Turn",
        "m_chapter_counter": "Chapter Counter",
        "m_chapter_titan": "Major Chapter",
        "m_reading_hours": "Hours Reading",
        "m_reading_time_lord": "Time Lord Reader",
        "m_manga_collector": "Manga Collector",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_first_day": "First Reading Day",
        "m_first_rating": "First Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Collector",
        "m_year_explorer": "Year Of Reading",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred Read",
        "m_thousand_ch": "Thousand Chapters",
        "m_reading_ten": "Ten Simultaneous",
        "m_ptr_hoarder": "Reading Hoarder",
        "m_dropped_honesty": "Honest Drop",
        "m_season_reader": "Seasonal Reader",
        "m_active_reader": "Active Reader",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Completed",
        "m_fifty_completed": "Fifty Completed",
        "m_five_hundred_completed": "Five Hundred Done",
        "m_mean_score_tracker": "Average Score",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Fixation",
        "m_favorites_collector": "Favorites Hoard",
        "m_days_spent_reading": "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reader",
        "m_marathon_reader": "Marathon Reader",
        "m_weekend_reader": "Weekend Reader",
        "m_non_stop_reading": "Non-Stop Pages",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Read",
        "m_double_story": "Double Story",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five Daily Reads",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half-Day Read",
        "m_full_day_read": "Full-Day Read",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Binge Monarch",
        "m_no_sleep_read": "Sleepless Read",
        "m_full_series_rush": "Series Rush",
        "m_seven_day_challenge": "Seven-Day Read",
        "m_hundred_day_read": "Hundred-Day Read",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Binge",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapters",
        "m_multi_series_binge": "Multi-Series Read",
        "m_midnight_binge": "Midnight Read",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "Forty-Eight Hours",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Pages",
        "m_genre_adventure": "Adventure Read",
        "m_genre_comedy": "Comedy Relief",
        "m_genre_drama": "Dramatic Pages",
        "m_genre_fantasy": "Fantasy Escape",
        "m_genre_horror": "Horror Panels",
        "m_genre_mystery": "Mystery Unread",
        "m_genre_romance": "Dark Romance",
        "m_genre_scifi": "Sci-Fi Pages",
        "m_genre_sol": "Quiet Life",
        "m_genre_sports": "Sports Panel",
        "m_genre_supernatural": "Supernatural Read",
        "m_genre_thriller": "Thriller Panels",
        "m_genre_psychological": "Psychological Read",
        "m_genre_isekai": "Isekai Read",
        "m_genre_shounen": "Shounen Read",
        "m_genre_ecchi": "Provocative Pages",
        "m_genre_mahou_shoujo": "Magical Read",
        "m_genre_mecha": "Mecha Blueprint",
        "m_genre_music": "Musical Score",
        "m_tag_isekai_new": "New World Read",
        "m_tag_harem": "Ensemble Cast",
        "m_tag_bl": "Hidden Bonds",
        "m_tag_gl": "Mirror Bond",
        "m_tag_historical": "Historical Record",
        "m_tag_military": "Military Intel",
        "m_tag_school": "School Memory",
        "m_tag_martial_arts": "Combat Manual",
        "m_tag_vampire": "Blood Pages",
        "m_tag_samurai": "Blade Chronicle",
        "m_tag_space": "Void Chronicle",
        "m_tag_parody": "Twisted Pages",
        "m_tag_idol": "Idol Memoir",
        "m_tag_post_apocalyptic": "Post-Collapse",
        "m_tag_cyberpunk": "Digital Noir",
        "m_tag_shoujo": "Fragile Pages",
        "m_tag_survival": "Survival Pages",
        "m_tag_cooking": "Bitter Recipe",
        "m_tag_medical": "Case Study",
        "m_tag_villainess": "Villainess Read",

        // ── MANGA COMPLETION ──
        "m_completionist": "Full Manuscript",
        "m_mega_completionist": "Mega Completionist",
        "m_completion_rate_50": "Halfway There",
        "m_completion_rate_75": "Almost Done",
        "m_completion_rate_90": "Near Finale",
        "m_no_drop": "Never Dropped",
        "m_long_runner_complete": "Long Series Done",
        "m_sequel_chain": "Sequel Chain",
        "m_clean_list": "Clean Record",
        "m_from_ptr": "List Fulfilled",
        "m_reread_master": "Reread Master",
        "m_oneshot_complete": "Oneshot Complete",
        "m_same_day_start_finish": "Same-Day Read",
        "m_revival": "Revived Read",
        "m_zero_to_hundred": "Zero To Hero",
        "m_five_genre_complete": "Five Genres Done",
        "m_full_collection": "Full Collection",
        "m_batch_complete": "Batch Clear",
        "m_paused_to_done": "Resumed Read",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Complete",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi Reread",
        "m_dropped_recovery": "Recovered Read",
        "m_ten_perfect_scores": "Ten Perfects",
        "m_complete_genre_span": "Genre Span",
        "m_monthly_completions": "Monthly Reads",
        "m_yearly_completions": "Yearly Reads",
        "m_rapid_complete": "Rapid Finish",
        "m_author_complete": "Author Complete",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Devotee",
        "m_rereader": "Obsessive Reread",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Admirer",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Fan",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Devoted",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Commitment",
        "m_up_to_date": "Up To Date",
        "m_favorite_mangaka": "Favorite Author",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Franchise Collector",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Master",
        "m_multi_series_author": "Multi-Series Fan",
        "m_format_diversity": "Format Diversity",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Follower",
        "m_genre_loyalty_50": "Fifty Loyal Reads",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Explorer",
        "m_publisher_hopper": "Publisher Hopper",
        "m_tag_explorer": "Tag Explorer",
        "m_decade_hopper": "Decade Hopper",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Taste",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross Demographic",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Varied Week",
        "m_manhwa_reader": "Manhwa Reader",
        "m_manhua_reader": "Manhua Reader",
        "m_classic_connoisseur": "Classic Connoisseur",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Niche Explorer",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Classic",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre Month",
        "m_year_completionist": "Year Completionist",
        "m_unpopular_opinion": "Unpopular Opinion",
        "m_top_rated_reader": "Top Rated Reader",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Manga Fan",
        "m_long_manga_explorer": "Long Manga Fan",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl",
        "m_early_bird": "Early Bird",
        "m_lunch_reader": "Lunch Reader",
        "m_commute_reader": "Commute Reader",
        "m_four_am_club": "4 AM Reader",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All Hours",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "Workday Reader",
        "m_sunday_read": "Sunday Read",
        "m_morning_routine": "Morning Read",
        "m_night_shift_reader": "Night Shift Read",
        "m_seasonal_premier_read": "New Release",
        "m_clock_collector": "Clock Collector",
        "m_late_night_horror": "Late Night Horror",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Reader",
        "m_twilight_reader": "Twilight Reader",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Reading",
        "m_late_night_regular": "Late Night Regular",
        "m_sunrise_reader": "Sunrise Reader",
        "m_every_day_of_week": "Every Day Read",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Reader",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Doujin Reader",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Reader",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Reader",
        "m_oneshot_reader": "Oneshot Reader",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "Light Novel Fan",
        "m_novel_reader": "Novel Reader",
        "m_visual_storyteller": "Visual Narrator",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga Vs Anime",
        "m_seinen_reader": "Seinen Reader",
        "m_josei_reader": "Josei Reader",
        "m_award_winning_art": "Award-Winning Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross Media",
        "m_spinoff_reader": "Spinoff Reader",
        "m_remake_reader": "Remake Reader",
        "m_collaboration_reader": "Collab Reader",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Reading",
        "m_mega_streak": "Mega Streak",
        "m_weekly_warrior": "Weekly Warrior",
        "m_monthly_reader": "Monthly Reader",
        "m_comeback": "Reader Comeback",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Discipline",
        "m_habit_formed": "Habit Formed",
        "m_consistent_pace": "Consistent Pace",
        "m_year_long": "Year-Long Read",
        "m_double_streak": "Double Streak",
        "m_streak_recovery": "Streak Restored",
        "m_daily_minimum": "Daily Minimum",
        "m_winter_streak": "Winter Streak",
        "m_summer_streak": "Summer Streak",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Streak",
        "m_unbreakable": "Unbreakable Will",
        "m_eternal_flame": "Eternal Focus",
        "m_chapter_a_day": "Chapter A Day",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Completion Chain",
        "m_rating_streak": "Rating Streak",
        "m_multi_ch_streak": "Multi-Chapter Run",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Manuscript Critic",
        "m_perfect_ten": "Perfect Ten",
        "m_harsh_critic": "Harsh Standards",
        "m_fair_judge": "Fair Assessment",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Score All",
        "m_wide_range": "Wide Range",
        "m_controversial": "Controversial Score",
        "m_consistent_scorer": "Consistent Scorer",
        "m_score_sniper": "Precision Score",
        "m_evolving_taste": "Evolving Taste",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Selective Reader",
        "m_100_rated": "Century Rated",
        "m_500_rated": "Five Hundred Rated",
        "m_mediocre_majority": "Middle Ground",
        "m_rating_spree": "Rating Spree",
        "m_score_variance": "Score Variance",
        "m_binge_rater": "Binge Rater",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Hunter",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimistic Reader",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Resolve",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day Read",
        "m_april_fools": "April Deception",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic Day",
        "m_summer_solstice": "Summer Reading",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Friday 13th Read",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Thanksgiving Read",
        "m_christmas_read": "Christmas Read",
        "m_new_years_eve": "New Year's Eve",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Marathon",
        "m_independence_day": "Independence Read",
        "m_culture_day": "Culture Day Read",
        "m_spring_equinox": "Spring Read",
        "m_earth_day": "Earth Day Read",
        "m_labor_day": "Labor Day Read",
        "m_winter_solstice": "Winter Read",
        "m_manga_birthday": "Manga Anniversary",
        "m_every_holiday_reader": "Every Holiday",
        "m_consecutive_holidays": "Consecutive Holidays",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number",
        "m_fibonacci": "Fibonacci Chapter",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Day",
        "m_full_moon_read": "Full Moon Read",
        "m_leap_year_read": "Leap Year Read",
        "m_triple_seven": "Triple Seven",
        "m_thousand_complete": "Thousand Complete",
        "m_nice": "Nice Count",
        "m_power_level_chapters": "Power Level",
        "m_answer_42": "The Answer",
        "m_square_number": "Square Number",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Matching Date",
        "m_century_chapter": "Century Chapter",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Synchronicity",
        "m_world_record": "World Record",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time Traveler",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Match",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Format",
        "m_manhua_format": "Manhua Format",
        "m_ln_format": "Light Novel",
        "m_oneshot_format": "Oneshot Format",
        "m_doujin_format": "Doujin Format",
        "m_novel_format": "Novel Format",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Unlocked",
        "m_meta_collector": "Badge Collector",
        "m_meta_category_starter": "Category Started",
        "m_meta_tier_climber": "Tier Climber",
        "m_meta_tier_max": "Maximum Tier",
        "m_meta_xp_earner": "XP Earned",
        "m_meta_difficulty_easy": "Easy Read",
        "m_meta_difficulty_hard": "Impossible Read",
        "m_meta_unlock_spree": "Unlock Spree",
        "m_meta_completionist": "Meta Complete",
        "m_meta_diverse": "Diverse Portfolio",
        "m_meta_dominator": "Meta Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020408",
        primary: "#1e5ac8",
        secondary: "#1648aa",
        accent: "#8cabed",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/perfect-blue.jpg",
    particleColor: "#4060c0",
    backgroundDim: 0.3,
    backgroundBlur: 20,
    particleTypes: {
        shattered_glass: { label: "Shattered Glass", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        spotlight_flicker: { label: "Spotlight Flicker", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        camera_flash: { label: "Camera Flash", maxCount: 10, defaultEnabled: true, defaultIntensity: 45 },
        mirror_shards: { label: "Mirror Shards", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
    },
    milestoneNames: {
        1:   "Fan",
        5:   "Idol",
        15:  "Actress",
        30:  "Double",
        45:  "Paranoia",
        60:  "Illusion",
        80:  "Shattered",
        100: "Perfect Blue",
    },
}
