import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiCrossedSwords,
    GiHorseHead,
    GiChainedHeart,
    GiCompass,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiResize,
    GiSettingsKnobs,
    GiAnvilImpact,
    GiMuscleUp,
    GiShield,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const ranma12Theme: AnimeThemeConfig = {
    id: "ranma-12",
    displayName: "Ranma ½",
    description: "I don't need your help! Anything-goes martial arts chaos, Jusenkyo curses, and a dojo full of fiancées in Nerima.",
    fontFamily: "'Fredoka One', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    cssVars: {
        "--color-brand-200": "255 200 195",
        "--color-brand-300": "240 155 140",
        "--color-brand-400": "225 95 75",
        "--color-brand-500": "204 34 8",
        "--color-brand-600": "170 22 5",
        "--color-brand-700": "128 14 3",
        "--color-brand-800": "88 8 2",
        "--color-brand-900": "50 3 1",
        "--color-brand-950": "24 1 0",
        "--brand": "204 34 8",
        "--background": "#060406",
        "--paper": "#0e0c10",
        "--color-gray-950": "6 4 6",
        "--color-gray-900": "12 8 14",
        "--color-gray-800": "22 15 25",
        "--color-gray-700": "36 25 40",
        "--color-gray-600": "58 40 65",
        "--color-gray-500": "88 65 98",
        "--color-gray-400": "130 105 145",
        "--color-gray-300": "168 148 182",
        "--color-gray-200": "202 188 212",
        "--color-gray-100": "228 220 235",
        "--color-gray-50": "245 240 248",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Tendo Dojo" },
        "schedule": { icon: GiAlarmClock, label: "Battle Schedule" },
        "manga": { icon: LuBookOpen, label: "Martial Arts Archive" },
        "lists": { icon: GiCrossedSwords, label: "Rival Roster" },
        "discover": { icon: GiCompass, label: "Nerima Exploration" },
        "torrent-list": { icon: GiAnvilImpact, label: "Training Cache" },
        "debrid": { icon: GiHorseHead, label: "Panda Dad Lines" },
        "unmatched": { icon: GiChainedHeart, label: "Unclaimed Fiancées" },
        "enmasse": { icon: GiResize, label: "Chaos Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Dojo Reports" },
        "auto-downloader": { icon: LuRss, label: "Battle Signals" },
        "community": { icon: GiEagleEmblem, label: "Amazon Community" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Dojo Alerts" },
        "achievements": { icon: GiTrophy, label: "Martial Arts Trophies" },
        "theme-manager": { icon: GiPalette, label: "Dojo Palette" },
        "extensions": { icon: BiExtension, label: "Dojo Extensions" },
        "sync": { icon: IoCloudOfflineOutline, label: "Jusenkyo Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Tendo HQ" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Splash in Jusenkyo Springs",
        "a_episode_counter": "Anything-Goes Move Count",
        "a_episode_titan": "Full Chaos Engagement",
        "a_hours_invested": "Hours in Nerima",
        "a_time_lord": "Chaos Realm Memories",
        "a_anime_collector": "Nerima Arsenal Collector",
        "a_library_legend": "Tendo Dojo Legend",
        "a_first_complete": "First Dojo Journey Complete",
        "a_hundred_club": "Century of Battle Victories",
        "a_first_day": "First Day in Nerima",
        "a_first_rating": "Martial Arts Evaluation",
        "a_ten_thousand_min": "Ten Thousand Minutes in Nerima",
        "a_season_veteran": "Veteran Anything-Goes Fighter",
        "a_year_explorer": "Year of Nerima Exploration",
        "a_century_watcher": "Hundred-Episode Chaos Watch",
        "a_five_hundred_eps": "Five Hundred Anything-Goes Moves",
        "a_thousand_eps": "Thousand Rival Encounters",
        "a_watching_ten": "Ten Dojo Fronts Simultaneously",
        "a_ptw_hoarder": "Unchallenged Rival Backlog",
        "a_dropped_honesty": "Strategic Dojo Retreat",
        "a_five_thousand_eps": "Five Thousand Nerima Battles",
        "a_ten_completed": "Ten Chaos Arcs Complete",
        "a_fifty_completed": "Fifty Dojo Missions",
        "a_five_hundred_completed": "Five Hundred Anything-Goes Victories",
        "a_mean_score_tracker": "Average Chaos Rating",
        "a_unique_studios": "Allied Dojo Factions",
        "a_days_spent_watching": "Days Defending Tendo Dojo",
        "a_all_status": "All Martial Artist Statuses",
        "a_first_favorite": "First Nerima Bond",
        "a_favorites_collector": "Bonds of Nerima's Chaos",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Anything-Goes Assault",
        "a_marathon_runner": "Jusenkyo-to-Nerima Marathon",
        "a_weekend_warrior": "Weekend Warrior Fighter",
        "a_non_stop": "Relentless Chaos Advance",
        "a_one_more_episode": "One More Chaos Battle",
        "a_speed_run": "Anything-Goes Blitz",
        "a_double_feature": "Double Dojo Strike",
        "a_triple_threat": "Triple Rival Takedown",
        "a_five_a_day": "Five Battles a Day",
        "a_back_to_back": "Back-to-Back Chaos Engagements",
        "a_seasonal_binge": "Full Nerima Chaos Campaign",
        "a_cour_crusher": "District Chaos Crusher",
        "a_half_day_watch": "Half-Day Dojo Shift",
        "a_full_day_watch": "Full Day in Nerima",
        "a_power_weekend": "Power Weekend Chaos Offensive",
        "a_binge_king": "Commander of Chaos Binge Ops",
        "a_no_sleep": "All-Night Vigil at Tendo Dojo",
        "a_entire_season": "Rapid Chaos Campaign Clear",
        "a_seven_day_challenge": "Seven-Day Nerima Reclamation",
        "a_hundred_day_binge": "Hundred-Day Chaos Siege",
        "a_genre_binge": "Cross-Dojo Training",
        "a_studio_binge": "Allied Dojo Binge",
        "a_season_sweep": "Season Sweep Chaos Operation",
        "a_forty_eight_hour": "Forty-Eight Hour Chaos Standoff",
        "a_ep_counter_day": "Daily Battle Count",
        "a_multi_series_binge": "Multi-Front Chaos Campaign",
        "a_midnight_binge": "Midnight Nerima Reconnaissance",
        "a_new_year_binge": "New Year's Anything-Goes Charge",

        // ── ANIME GENRES ──
        "a_genre_action": "Anything-Goes Action Specialist",
        "a_genre_adventure": "Beyond Jusenkyo Springs",
        "a_genre_comedy": "Happosai's Comedy Moment",
        "a_genre_drama": "Ranma's Vow",
        "a_genre_fantasy": "Jusenkyo Dimension",
        "a_genre_horror": "Nerima Chaos Terror",
        "a_genre_mystery": "Curse Mystery",
        "a_genre_romance": "Heart of the Anything-Goes Fighter",
        "a_genre_scifi": "Curse Technology",
        "a_genre_sol": "Life in Nerima",
        "a_genre_sports": "Dojo Training Grounds",
        "a_genre_supernatural": "Cursed Spring Transformation",
        "a_genre_thriller": "Shampoo Pursuit",
        "a_genre_mecha": "Anti-Chaos Artillery",
        "a_genre_music": "Call of the Chaos Dojo",
        "a_genre_psychological": "Ranma's Inner War",
        "a_genre_ecchi": "Nerima Hot Spring Episode",
        "a_genre_mahou_shoujo": "Curse Wielder",
        "a_tag_isekai": "Transported to Jusenkyo",
        "a_tag_harem": "Nerima Fiancée Chaos",
        "a_tag_bl": "Martial Arts Brothers",
        "a_tag_gl": "Shield Sisters of the Dojo",
        "a_tag_historical": "Anything-Goes Martial Arts History",
        "a_tag_military": "Dojo Discipline",
        "a_tag_school": "Furinkan High School",
        "a_tag_martial_arts": "Anything-Goes Fighting Style",
        "a_tag_vampire": "Cursed Bloodline",
        "a_tag_samurai": "Dojo Blade Style",
        "a_tag_space": "Beyond Nerima",
        "a_tag_parody": "Happosai Parody",
        "a_tag_idol": "Dojo Idol Wings",
        "a_tag_post_apocalyptic": "Post-Chaos Nerima Era",
        "a_tag_cyberpunk": "Curse Tech",
        "a_tag_shounen": "Dedicate Your Anything-Goes",
        "a_tag_seinen": "Harsh Reality of Dojo Wars",
        "a_tag_shoujo": "Akane's Devotion",
        "a_tag_josei": "Shampoo's Obsession",
        "a_tag_survival": "Survival in Nerima",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Chaos Expedition Report",
        "a_mega_completionist": "Chaos King Complete",
        "a_completion_rate_50": "Halfway to the Final Battle",
        "a_completion_rate_75": "Approaching Saffron",
        "a_completion_rate_90": "Curse Nearly Broken",
        "a_no_drop": "No Martial Artist Left Behind",
        "a_long_runner_complete": "Long Chaos Campaign Endurance",
        "a_sequel_chain": "Operation Chaos Chain",
        "a_clean_list": "Clean Chaos Record",
        "a_from_ptw": "Orders from Soun Executed",
        "a_rewatch_master": "Chaos Memory Replay",
        "a_short_complete": "Quick Chaos Skirmish Victory",
        "a_same_day_start_finish": "Same-Day Chaos Elimination",
        "a_revival": "Revived by Anything-Goes",
        "a_zero_to_hero": "Lost Boy to Chaos Master",
        "a_five_genre_complete": "Five-Branch Chaos Mastery",
        "a_full_franchise": "Full Nerima Chaos Dossier",
        "a_batch_complete": "Batch Chaos Clear",
        "a_paused_to_done": "Returned from Jusenkyo",
        "a_completion_spree": "Completion Chaos Strike",
        "a_multi_rewatch": "Multi-Timeline via Jusenkyo",
        "a_dropped_recovery": "Recovered from Chaos Curse",
        "a_ten_perfect_scores": "Ten Perfect Chaos Scores",
        "a_seasonal_clear": "Seasonal Chaos Clear",
        "a_complete_genre_span": "All-Terrain Chaos Fighter",
        "a_monthly_completions": "Monthly Chaos Reports",
        "a_yearly_completions": "Yearly Chaos Campaign Victor",
        "a_rapid_complete": "Lightning Chaos Raid Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Nerima Chaos Member",
        "a_studio_devotee": "DLE/Fuji TV Devotee",
        "a_rewatcher": "Chaos Recon Rewatch",
        "a_triple_rewatch": "Triple Chaos Expedition Rewatch",
        "a_annual_tradition": "Annual Nerima Day",
        "a_director_fan": "Director's Chaos Vision Follower",
        "a_voice_actor_fan": "Voice of the Chaos Fighter",
        "a_ost_lover": "Ranma ½ Ending Theme!",
        "a_source_reader": "Takahashi's Original Chaos Texts",
        "a_waiting_weekly": "Weekly Chaos Signal Wait",
        "a_childhood_revisit": "Return to Tendo Dojo",
        "a_saga_tracker": "Saga of the Chaos Tracker",
        "a_genre_loyalty": "Chaos Loyalty Badge",
        "a_decade_watcher": "Decade-Long Chaos Fighter",
        "a_adaptation_hunter": "Adaptation Reconnaissance",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Chaos Duty",
        "a_perfect_attendance": "Perfect Chaos Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Chaos Catalog",
        "a_franchise_collector": "Ranma Universe Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Mastery Achieved",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Season Chaos Veteran",
        "a_format_diversity": "Diverse Chaos Formats",
        "a_year_dedication": "Year of Dedication to Chaos",
        "a_season_dedication": "Season of Unwavering Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Nerima",
        "a_studio_hopper": "Dojo Transfer",
        "a_tag_explorer": "Tag Reconnaissance Mission",
        "a_decade_hopper": "Time via Jusenkyo",
        "a_hidden_gem": "Hidden Chaos Technique Secret",
        "a_popular_taste": "Popular Among Nerima Folk",
        "a_retro_appreciator": "Pre-Chaos Era Appreciator",
        "a_modern_viewer": "Modern Chaos Viewer",
        "a_cross_demographic": "Cross-Demographic Scout",
        "a_underdog_fan": "Underdog Anything-Goes Spirit",
        "a_variety_week": "Week of Varied Chaos Types",
        "a_foreign_cinema": "Chinese Amazon Cinema",
        "a_classic_connoisseur": "Classic Chaos Connoisseur",
        "a_every_season": "Every Season Deployed",
        "a_award_winner": "Medal of the Anything-Goes",
        "a_niche_explorer": "Niche Chaos Explorer",
        "a_global_anime": "Global Alliance Entry",
        "a_cult_classic": "Nerima Cult Classic",
        "a_random_pick": "Random Chaos Mission",
        "a_new_genre_month": "New Chaos Terrain Monthly",
        "a_seasonal_completionist": "Seasonal Chaos Clear",
        "a_unpopular_opinion": "Unpopular Chaos Opinion",
        "a_top_rated_viewer": "Top-Rated Chaos Intel",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Chaos Operation Intel",
        "a_short_series_explorer": "Short Chaos Skirmish Explorer",
        "a_long_series_explorer": "Long Chaos Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Watch in Nerima",
        "a_early_bird": "Dawn Chaos Patrol",
        "a_lunch_break": "Kasumi's Lunch Break",
        "a_golden_hour": "Golden Hour at the Dojo",
        "a_four_am_club": "4 AM Chaos Sentry",
        "a_witching_hour": "Chaos Witching Hour",
        "a_new_year_watch": "New Year's Oath at the Dojo",
        "a_midnight_premiere": "Midnight Chaos Deployment",
        "a_all_hours": "All-Hours Chaos Fighter",
        "a_dawn_warrior": "Dawn Warrior of Nerima",
        "a_afternoon_delight": "Afternoon Dojo Drill",
        "a_prime_time": "Prime Time Chaos Engagement",
        "a_workday_watcher": "On-Duty Watcher",
        "a_sunday_marathon": "Sunday Chaos Marathon",
        "a_rainy_day": "Rainy Day in Nerima",
        "a_morning_routine": "Morning Chaos Formation",
        "a_night_shift": "Night Shift Dojo Guard",
        "a_twilight_zone": "Twilight Beyond Jusenkyo",
        "a_seasonal_premier": "Season Premiere Sortie",
        "a_clock_collector": "Chaos Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge Chaos Operations",
        "a_late_night_regular": "Late Night Regular Patrol",
        "a_sunrise_watcher": "Sunrise Over Tendo Dojo",
        "a_holiday_watcher": "Holiday Chaos Guard Duty",
        "a_every_day_of_week": "Every Day Chaos Deployed",
        "a_monthly_hours": "Monthly Chaos Duty Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Chaos Formation",
        "a_party_host": "Nerima Chaos Commander",
        "a_social_butterfly": "Nerima Socialite",
        "a_group_binge": "Group Anything-Goes Volley",
        "a_party_regular": "Regular Chaos Partner",
        "a_sync_viewer": "Synchronized Chaos Maneuver",
        "a_commentator": "Chaos Battle Commentator",
        "a_party_marathon": "Marathon Chaos Run",
        "a_full_house": "Full Nerima Chaos Group Assembled",
        "a_community_pillar": "Pillar of the Chaos Fighters",
        "a_watch_party_streak": "Consecutive Chaos Formation Streak",
        "a_diverse_party": "Diverse Chaos Party",
        "a_late_night_party": "Late Night Nerima Party",
        "a_party_veteran": "Veteran Chaos Squad Leader",
        "a_genre_party": "Cross-Genre Chaos Formation",
        "a_weekly_party": "Weekly Comrades' Gathering",
        "a_silent_viewer": "Silent Ryoga Observer",
        "a_recommendation_giver": "Commander's Recommendation",
        "a_party_completionist": "Party Chaos Completionist",
        "a_social_scorer": "Social Chaos Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Chaos Formation",
        "a_fibonacci": "Fibonacci Curse Sequence",
        "a_palindrome_day": "Palindrome Time Rift",
        "a_binary_day": "Binary Chaos Signal Day",
        "a_full_moon": "Full Moon Anything-Goes Transformation",
        "a_leap_year": "Leap Year Time Skip",
        "a_time_traveler": "Jusenkyo Time Traveler",
        "a_genre_clash": "Male vs. Female Ranma Clash",
        "a_triple_seven": "Triple Seven Chaos Fighters",
        "a_thousand_complete": "Thousand Chaos for the Dojo",
        "a_pi_episodes": "Pi Anything-Goes Calculation",
        "a_synchronicity": "Chaos Synchronicity",
        "a_world_record": "World Record Chaos Victory",
        "a_nice": "Nice Chaos Count",
        "a_power_level": "Anything-Goes Power Level",
        "a_answer_42": "The Answer to Ranma's Question",
        "a_square_number": "Perfect Chaos Formation",
        "a_prime_count": "Prime Number of Chaos Victories",
        "a_matching_date": "Matching Intel Date",
        "a_century_episode": "Century Episode Chaos Assault",
        "a_double_digits": "Double Digit Chaos Victories",
        "a_one_two_three": "Boy Girl Neither",
        "a_lucky_seven": "Seven Lucky Chaos Fighters",
        "a_all_tens": "All Tens Chaos Score",
        "a_exact_hundred_eps": "Exact Hundred Chaos Engagements",
        "a_year_match_count": "Year Match Chaos Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Chaos Fighter",
        "a_movie_buff": "Ranma ½ Movie Operations",
        "a_ova_hunter": "OVA Chaos Hunter",
        "a_ona_explorer": "ONA Scout Explorer",
        "a_special_watcher": "Special Episode Operative",
        "a_short_king": "Short Chaos Engagement King",
        "a_variety_pack": "All-Format Chaos Corps",
        "a_film_festival": "Nerima Film Festival",
        "a_music_video": "Ranma ½ Ending Collection",
        "a_tv_short": "Quick Recon Clip",
        "a_movie_marathon": "Movie Marathon Blitz",
        "a_double_length": "Double-Length Chaos Operation",
        "a_anthology": "Nerima Chaos Anthology",
        "a_mini_series": "Mini Chaos Campaign",
        "a_theatrical": "Theatrical Chaos Deployment",
        "a_format_master": "Format Master Chaos Fighter",
        "a_long_movie": "Feature-Length Chaos Expedition",
        "a_back_catalog": "Back Catalog Chaos Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Chaos Formats",
        "a_episodic_master": "Episodic Chaos Campaign Master",
        "a_sequel_movie": "Sequel Chaos Operation Film",
        "a_recap_watcher": "Recap Briefing Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Chaos Patrol Streak",
        "a_mega_streak": "Mega Chaos Expedition Streak",
        "a_weekly_warrior": "Weekly Warrior of Nerima",
        "a_monthly_watcher": "Monthly Chaos Duty",
        "a_comeback": "Return to Tendo Dojo",
        "a_weekend_streak": "Weekend Chaos Sortie Streak",
        "a_no_zero_days": "No Zero Days in Nerima",
        "a_iron_will": "Iron Will of the Chaos Fighter",
        "a_habit_formed": "Chaos Training Regimen Formed",
        "a_consistent_pace": "Consistent Chaos March Forward",
        "a_year_long": "Year-Long Chaos Campaign",
        "a_double_streak": "Double Chaos Streak Assault",
        "a_streak_recovery": "Chaos Medical Recovery",
        "a_daily_minimum": "Daily Minimum Chaos Duty",
        "a_winter_streak": "Winter Chaos Campaign Streak",
        "a_summer_streak": "Summer Chaos Offensive Streak",
        "a_morning_streak": "Morning Chaos Drill Streak",
        "a_night_streak": "Night Chaos Patrol Streak",
        "a_unbreakable": "Unbreakable Will of the Chaos Fighter",
        "a_eternal_flame": "Eternal Chaos Flame",
        "a_completion_streak": "Completion Chaos Mission Chain",
        "a_rating_streak": "Rating Chaos Report Streak",
        "a_multi_ep_streak": "Multi-Episode Chaos Offensive",
        "a_genre_streak": "Genre Streak Sortie",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Week of Chaos Service",

        // ── ANIME SCORING ──
        "a_critic": "Soun Tribunal Judge",
        "a_perfect_ten": "Perfect 10 Chaos Rating",
        "a_harsh_critic": "Ryoga's Harsh Standards",
        "a_fair_judge": "Kasumi's Fair Assessment",
        "a_generous_spirit": "Generous Chaos Comrade",
        "a_score_all": "Full Chaos Roster Evaluation",
        "a_wide_range": "Wide Range Chaos Assessment",
        "a_controversial": "Controversial Chaos Decision",
        "a_consistent_scorer": "Consistent Chaos Evaluator",
        "a_score_sniper": "Precision Anything-Goes Sniper",
        "a_evolving_taste": "Evolving Chaos Strategy",
        "a_bell_curve": "Bell Curve of Chaos Scores",
        "a_picky_watcher": "Selective Chaos Commander",
        "a_100_rated": "Century of Chaos Evaluations",
        "a_500_rated": "Five Hundred Chaos Reports",
        "a_mediocre_majority": "Middle Ground Chaos Strategist",
        "a_rating_spree": "Rating Chaos Barrage",
        "a_score_variance": "Variable Chaos Ratings",
        "a_masterpiece_hunter": "Masterpiece Chaos Hunter",
        "a_contrarian": "Contrarian Chaos Scout",
        "a_optimist": "Optimist Despite the Chaos",
        "a_score_distributor": "Score Distributor General",
        "a_genre_critic": "Genre Chaos Tactical Critic",
        "a_mean_above_8": "Elite Chaos Combat Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow for the Dojo",
        "a_valentines_weeb": "Valentine's Chaos Dedication",
        "a_pi_day": "Pi Day Chaos Calculation",
        "a_april_fools": "April Fools Happosai Prank",
        "a_international_anime_day": "International Chaos Fighter Day",
        "a_star_wars_day": "Rival Empire Day",
        "a_summer_solstice": "Summer Solstice Chaos Expedition",
        "a_tanabata": "Tanabata Wish for the Dojo",
        "a_friday_13th": "Friday 13th Chaos Attack",
        "a_halloween_spirit": "Halloween Chaos Horror",
        "a_thanksgiving_binge": "Thanksgiving Chaos Feast",
        "a_christmas_special": "Midwinter Nerima Festival Special",
        "a_new_years_eve": "New Year's Eve Final Chaos Stand",
        "a_birthday_watch": "Birthday Chaos Watch",
        "a_holiday_marathon": "Holiday Chaos Marathon",
        "a_independence_day": "Nerima Independence Day",
        "a_culture_day": "Anything-Goes Culture Day",
        "a_spring_equinox": "Spring Chaos Advance",
        "a_earth_day": "Protect This Chaos World Day",
        "a_labor_day": "Nerima Labor Day",
        "a_winter_solstice": "Winter Solstice in Nerima",
        "a_anime_birthday": "Anime Anniversary Celebration",
        "a_every_holiday": "Every Holiday Chaos Fighter",
        "a_consecutive_holidays": "Consecutive Holiday Chaos Deployments",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Chaos Power Awakened",
        "a_meta_collector": "Nerima Chaos Badge Collector",
        "a_meta_category_starter": "Category Initiation Rite",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Grand Master Chaos Rank",
        "a_meta_xp_earner": "XP from Chaos Victories",
        "a_meta_difficulty_easy": "Easy Training Exercise",
        "a_meta_difficulty_hard": "Legendary Difficulty: Saffron",
        "a_meta_unlock_spree": "Unlock Spree Chaos",
        "a_meta_completionist": "Meta Completionist Chaos Fighter",
        "a_meta_diverse": "Diverse Chaos Portfolio",
        "a_meta_dominator": "Meta Dominator of Nerima",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter of Chaos",
        "m_chapter_counter": "Chapter Chaos Sortie Counter",
        "m_chapter_titan": "Chapter Chaos Assault",
        "m_reading_hours": "Hours Studying Chaos Texts",
        "m_reading_time_lord": "Jusenkyo Reading Memory",
        "m_manga_collector": "Chaos Archive Collector",
        "m_library_legend": "Tendo Dojo Book Legend",
        "m_first_complete": "First Manga Chaos Journey Done",
        "m_hundred_club": "Hundred-Chapter Chaos Club",
        "m_first_day": "First Day of Chaos Reading",
        "m_first_rating": "First Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Chaos Intel",
        "m_volume_collector": "Volume Chaos Stockpile Collector",
        "m_year_explorer": "Year of Chaos Manga Exploration",
        "m_century_reader": "Century-Chapter Chaos Reader",
        "m_five_hundred_ch": "Five Hundred Chapters of Chaos",
        "m_thousand_ch": "Thousand-Chapter Chaos Campaign",
        "m_reading_ten": "Ten Chaos Manuscripts at Once",
        "m_ptr_hoarder": "Chaos Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Chaos Retreat",
        "m_season_reader": "Seasonal Chaos Reading Rotation",
        "m_active_reader": "Active Chaos Field Reader",
        "m_five_thousand_ch": "Five Thousand Chaos Chapters Deep",
        "m_ten_completed": "Ten Chaos Manga Campaigns Complete",
        "m_fifty_completed": "Fifty Chaos Manga Missions Done",
        "m_five_hundred_completed": "Five Hundred Chaos Manga Victories",
        "m_mean_score_tracker": "Average Chaos Manuscript Rating",
        "m_unique_authors": "Unique Chaos Author Encounters",
        "m_all_status": "All Chaos Reading Statuses",
        "m_first_favorite": "First Chaos Manga Bond",
        "m_favorites_collector": "Chaos Manga Favorites Arsenal",
        "m_days_spent_reading": "Days in the Chaos Archives",

        // ── MANGA BINGE ──
        "m_binge_reader": "Chaos Binge Reading Advance",
        "m_marathon_reader": "Jusenkyo-to-Nerima Marathon",
        "m_weekend_reader": "Weekend Chaos Reading",
        "m_non_stop_reading": "Non-Stop Chaos Page Turning",
        "m_one_more_chapter": "One More Chaos Chapter Charge",
        "m_speed_read": "Anything-Goes Speed Read",
        "m_double_story": "Double Chaos Manuscript Feature",
        "m_triple_read": "Triple Chaos Reading Assault",
        "m_five_a_day": "Five Chaos Reads a Day",
        "m_chapter_chain": "Chaos Chapter Chain Offensive",
        "m_volume_binge": "Volume Chaos Binge Bombardment",
        "m_power_reader": "Power Chaos Reader Scout",
        "m_half_day_read": "Half-Day Chaos Archive Dive",
        "m_full_day_read": "Full-Day Chaos Manuscript Study",
        "m_power_weekend": "Power Weekend Chaos Reading",
        "m_binge_king": "King of the Chaos Reading Corps",
        "m_no_sleep_read": "All-Night Chaos Reading",
        "m_full_series_rush": "Full Chaos Series Rush Attack",
        "m_seven_day_challenge": "Seven-Day Chaos Intel Gathering",
        "m_hundred_day_read": "Hundred-Day Chaos Reading Siege",
        "m_volume_rush": "Chaos Volume Rush Deployment",
        "m_series_sweep": "Chaos Series Sweep Operation",
        "m_genre_binge": "Cross-Genre Chaos Maneuver",
        "m_author_binge": "Takahashi Focused Deep Dive",
        "m_chapter_counter_day": "Daily Chaos Chapter Kill Count",
        "m_multi_series_binge": "Multi-Series Chaos Reading Front",
        "m_midnight_binge": "Midnight Chaos Archive Session",
        "m_new_year_binge": "New Year's Chaos Reading Charge",
        "m_forty_eight_hour": "Forty-Eight Hour Chaos Reading Siege",
        "m_oneshot_binge": "Oneshot Chaos Blitz Attack",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Chaos Manuscript Specialist",
        "m_genre_adventure": "Adventure Beyond Nerima",
        "m_genre_comedy": "Comedy in the Chaos Dojo",
        "m_genre_drama": "Drama of the Anything-Goes Fighter",
        "m_genre_fantasy": "Fantasy of Jusenkyo",
        "m_genre_horror": "Chaos Horror Manuscript",
        "m_genre_mystery": "Mystery of the Curse",
        "m_genre_romance": "Romance in Chaos",
        "m_genre_scifi": "Sci-Fi Curse Technology",
        "m_genre_sol": "Slice of Life in Nerima",
        "m_genre_sports": "Anything-Goes Sports",
        "m_genre_supernatural": "Supernatural Curse Powers",
        "m_genre_thriller": "Chaos Thriller Report",
        "m_genre_psychological": "Psychological Chaos Warfare Reader",
        "m_genre_isekai": "Isekai Through Jusenkyo",
        "m_genre_shounen": "Shounen Heart of a Chaos Fighter",
        "m_genre_ecchi": "Hot Springs Chaos Chapter",
        "m_genre_mahou_shoujo": "Power of the Curse",
        "m_genre_mecha": "Anti-Chaos Weapon Blueprints",
        "m_genre_music": "Chaos Dojo Folk Songs",
        "m_tag_isekai_new": "New World Through Jusenkyo",
        "m_tag_harem": "Chaos Fiancée Bonds Manga",
        "m_tag_bl": "Martial Arts Brothers Manga",
        "m_tag_gl": "Shield Sisters of the Dojo Manga",
        "m_tag_historical": "Anything-Goes History Manga",
        "m_tag_military": "Dojo Operations Manga",
        "m_tag_school": "Furinkan High School Manga",
        "m_tag_martial_arts": "Anything-Goes Combat Manual",
        "m_tag_vampire": "Cursed Blood Manga",
        "m_tag_samurai": "Dojo Blade Master Manga",
        "m_tag_space": "Beyond Nerima Manga",
        "m_tag_parody": "Chibi Happosai Manga",
        "m_tag_idol": "Dojo Idol Manga",
        "m_tag_post_apocalyptic": "Post-Chaos Nerima Manga",
        "m_tag_cyberpunk": "Curse Technology Manga",
        "m_tag_shoujo": "Akane's Story Manga",
        "m_tag_survival": "Chaos Survival Manga",
        "m_tag_cooking": "Dojo Rations Cookbook",
        "m_tag_medical": "Field Medic Manga",
        "m_tag_villainess": "Chaos Fiancée Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Chaos Manga Campaign Completionist",
        "m_mega_completionist": "Supreme Chaos Manga Commander",
        "m_completion_rate_50": "Halfway to the Final Chaos",
        "m_completion_rate_75": "Approaching Saffron's Defeat",
        "m_completion_rate_90": "Final Chaos Chapter Approaching",
        "m_no_drop": "No Chaos Manuscript Abandoned",
        "m_long_runner_complete": "Long Chaos Series Endurance Medal",
        "m_sequel_chain": "Sequel Chaos Chain of Command",
        "m_clean_list": "Clean Chaos Reading Record",
        "m_from_ptr": "Orders Received: Read",
        "m_reread_master": "Chaos Memory Replay Reread",
        "m_oneshot_complete": "Oneshot Chaos Mission Specialist",
        "m_same_day_start_finish": "Same-Day Chaos Reading Blitz",
        "m_revival": "Revival Through Anything-Goes",
        "m_zero_to_hundred": "Lost Boy to Chaos Scholar",
        "m_five_genre_complete": "Five-Genre Chaos Mastery",
        "m_full_collection": "Full Chaos Archive Collection",
        "m_batch_complete": "Batch Chaos Clearance",
        "m_paused_to_done": "Back from Chaos Hiatus",
        "m_completion_spree": "Completion Chaos Barrage",
        "m_format_completionist": "Format Chaos Completion Badge",
        "m_catch_up": "Caught Up with Chaos Serialization",
        "m_multi_reread": "Multi-Pass Chaos Reread",
        "m_dropped_recovery": "Recovered from Chaos Curse",
        "m_ten_perfect_scores": "Ten Perfect Chaos Manuscript Scores",
        "m_complete_genre_span": "All-Genre Chaos Reading Scout",
        "m_monthly_completions": "Monthly Chaos Manuscript Victories",
        "m_yearly_completions": "Yearly Chaos Reading Campaign",
        "m_rapid_complete": "Rapid Chaos Intel Processing",
        "m_author_complete": "Takahashi's Complete Chaos Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Chaos Reader",
        "m_mangaka_lover": "Takahashi Devotee",
        "m_rereader": "Chaos Scout Rereader",
        "m_triple_reread": "Triple Chaos Reread Expedition",
        "m_annual_reread": "Annual Nerima Chaos Reread",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Artist Appreciation Medal",
        "m_adaptation_compare": "Manga vs Anime Chaos Compare",
        "m_source_material_fan": "Source Material Chaos Scout",
        "m_waiting_weekly": "Weekly Chaos Chapter Signal Wait",
        "m_classic_reader": "Classic Chaos Manuscript Reader",
        "m_saga_reader": "Saga of the Chaos Fighter Reader",
        "m_genre_loyalty": "Genre Chaos Loyalty Medal",
        "m_decade_reader": "Decade-Long Chaos Reader",
        "m_ln_adaptation": "Light Novel Adaptation Intel",
        "m_original_work": "Original Chaos Manga Work",
        "m_long_commitment": "Long-Term Chaos Reading Commitment",
        "m_up_to_date": "Up-to-Date with the Chaos Front Lines",
        "m_favorite_mangaka": "Favorite Mangaka Honored",
        "m_complete_portfolio": "Complete Chaos Reading Portfolio",
        "m_franchise_collector": "Ranma Franchise Collector",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Chaos Mastery Earned",
        "m_multi_series_author": "Multi-Series Takahashi Fan",
        "m_format_diversity": "Diverse Chaos Reading Formats",
        "m_year_dedication": "Year of Dedicated Chaos Reading",
        "m_ongoing_follower": "Ongoing Chaos Series Follower",
        "m_genre_loyalty_50": "Fifty Genre Chaos Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Chaos Territory Scout",
        "m_publisher_hopper": "Publisher Chaos Transfer",
        "m_tag_explorer": "Chaos Manga Tag Recon Mission",
        "m_decade_hopper": "Decade-Hopping via Jusenkyo",
        "m_hidden_gem": "Hidden Chaos Technique Gem",
        "m_popular_taste": "Popular Among Nerima Folk",
        "m_retro_reader": "Pre-Chaos Era Reader",
        "m_modern_reader": "Modern Chaos Reader",
        "m_cross_demographic": "Cross-Demographic Chaos Scout",
        "m_underdog_fan": "Underdog Anything-Goes Fan",
        "m_variety_week": "Week of Varied Chaos Readings",
        "m_manhwa_reader": "Manhwa Intelligence Reader",
        "m_manhua_reader": "Manhua Intelligence Reader",
        "m_classic_connoisseur": "Classic Chaos Manuscript",
        "m_award_winner": "Medal-Winning Chaos Manuscript",
        "m_niche_explorer": "Niche Chaos Territory Reader",
        "m_world_manga": "World Chaos Manga Intel",
        "m_cult_classic": "Nerima Cult Classic Underground",
        "m_random_pick": "Random Chaos Reading Assignment",
        "m_new_genre_month": "New Chaos Genre Deployment Monthly",
        "m_year_completionist": "Year Chaos Reading Completionist",
        "m_unpopular_opinion": "Unpopular Chaos Opinion",
        "m_top_rated_reader": "Top-Rated Chaos Intel Source",
        "m_source_variety": "Source Material Variety",
        "m_low_score_brave": "Brave Low-Score Chaos Reader",
        "m_short_manga_explorer": "Short Chaos Manga Skirmish",
        "m_long_manga_explorer": "Long Chaos Campaign Manuscript",
        "m_serialization_explorer": "Chaos Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Chaos Reader",
        "m_early_bird": "Dawn Chaos Patrol Reader",
        "m_lunch_reader": "Kasumi's Lunch Reader",
        "m_commute_reader": "Jusenkyo Commute Reader",
        "m_four_am_club": "4 AM Chaos Sentry Reader",
        "m_new_year_read": "New Year's Chaos Reading Oath",
        "m_all_hours": "All-Hours Chaos Archive Access",
        "m_prime_time_reader": "Prime Time Chaos Manuscript",
        "m_workday_reader": "On-Duty Chaos Reader",
        "m_sunday_read": "Sunday Chaos Reading Marathon",
        "m_morning_routine": "Morning Chaos Formation Reading",
        "m_night_shift_reader": "Night Shift Chaos Reader",
        "m_seasonal_premier_read": "New Chaos Release Intel",
        "m_clock_collector": "Chaos Clock Reading Time",
        "m_late_night_horror": "Midnight Chaos Horror Read",
        "m_afternoon_reader": "Afternoon Chaos Reading",
        "m_golden_hour_reader": "Golden Hour at the Dojo Reading",
        "m_dawn_reader": "Dawn Chaos Reading Scout",
        "m_twilight_reader": "Twilight Jusenkyo Reading",
        "m_midnight_start": "Midnight Chaos Reading Mission",
        "m_weekend_binge_hours": "Weekend Chaos Binge Reading Ops",
        "m_late_night_regular": "Late Night Chaos Regular Reader",
        "m_sunrise_reader": "Sunrise Over Tendo Dojo Reader",
        "m_every_day_of_week": "Every Day Chaos Reading Duty",
        "m_monthly_hours": "Monthly Chaos Reading Hours Logged",
        "m_bedtime_reader": "Bedtime Chaos Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Takahashi Art Appreciator",
        "m_webtoon_reader": "Webtoon Intelligence",
        "m_full_color": "Full Color Chaos Manuscript",
        "m_doujin_reader": "Underground Chaos Doujin Reader",
        "m_anthology_reader": "Anthology Collection Reader",
        "m_adaptation_reader": "Adaptation Study Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Happosai Shorts",
        "m_oneshot_reader": "Oneshot Chaos Mission Reader",
        "m_format_variety": "Format Chaos Tactical Variety",
        "m_light_novel_reader": "Light Novel Intel Reader",
        "m_novel_reader": "Novel Chaos Archive Reader",
        "m_visual_storyteller": "Visual Chaos Battle Narrator",
        "m_colored_classic": "Colored Classic Chaos Manuscript",
        "m_webcomic_fan": "Webcomic Underground Fan",
        "m_manga_to_anime": "Manga to Anime Chaos Comparison",
        "m_seinen_reader": "Seinen Chaos Reader",
        "m_josei_reader": "Josei Chaos Perspective Reader",
        "m_award_winning_art": "Medal-Winning Chaos Artwork",
        "m_debut_work": "Debut Chaos Manuscript",
        "m_vertical_scroll": "Vertical Scroll Chaos Intel",
        "m_traditional_format": "Traditional Chaos Format Reader",
        "m_cross_media": "Cross-Media Chaos Intelligence",
        "m_spinoff_reader": "Chaos Spinoff Reader",
        "m_remake_reader": "Remake Chaos Reading Assignment",
        "m_collaboration_reader": "Joint Chaos Operation Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Chaos Reading Patrol Streak",
        "m_mega_streak": "Mega Chaos Reading Campaign Streak",
        "m_weekly_warrior": "Weekly Chaos Warrior Reader",
        "m_monthly_reader": "Monthly Chaos Reader",
        "m_comeback": "Reader's Return to Nerima",
        "m_weekend_streak": "Weekend Chaos Reading Streak",
        "m_no_zero_days": "No Zero Chaos Reading Days",
        "m_iron_will": "Iron Will Chaos Reader",
        "m_habit_formed": "Chaos Reading Regimen Formed",
        "m_consistent_pace": "Consistent Chaos Reading Advance",
        "m_year_long": "Year-Long Chaos Reading Campaign",
        "m_double_streak": "Double Chaos Reading Streak",
        "m_streak_recovery": "Chaos Reading Streak Recovery",
        "m_daily_minimum": "Daily Minimum Chaos Pages",
        "m_winter_streak": "Winter Chaos Reading Campaign",
        "m_summer_streak": "Summer Chaos Reading Offensive",
        "m_morning_streak": "Morning Chaos Reading Formation",
        "m_night_streak": "Night Chaos Reading Patrol",
        "m_unbreakable": "Unbreakable Chaos Reading Will",
        "m_eternal_flame": "Eternal Chaos Flame of Knowledge",
        "m_chapter_a_day": "Chapter a Day Chaos Discipline",
        "m_genre_streak": "Genre Chaos Reading Streak",
        "m_completion_streak": "Completion Chaos Reading Chain",
        "m_rating_streak": "Chaos Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Chaos Streak",
        "m_author_streak": "Takahashi Chaos Dedication Streak",
        "m_perfect_week_manga": "Perfect Chaos Reading Week",
        "m_diverse_streak": "Diverse Chaos Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Chaos Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Chaos Manuscript",
        "m_harsh_critic": "Ryoga's Reading Standards",
        "m_fair_judge": "Kasumi's Fair Review",
        "m_generous_spirit": "Generous Chaos Reader",
        "m_score_all": "Full Chaos Manuscript Assessment",
        "m_wide_range": "Wide Range Chaos Scores",
        "m_controversial": "Controversial Chaos Reading Opinion",
        "m_consistent_scorer": "Consistent Chaos Manuscript Scorer",
        "m_score_sniper": "Precision Anything-Goes Score Sniper",
        "m_evolving_taste": "Evolving Chaos Reading Taste",
        "m_bell_curve": "Bell Curve of Chaos Scores",
        "m_picky_reader": "Selective Chaos Reading Commander",
        "m_100_rated": "Century of Chaos Ratings Filed",
        "m_500_rated": "Five Hundred Chaos Rating Reports",
        "m_mediocre_majority": "Middle Ground Chaos Reader",
        "m_rating_spree": "Chaos Rating Barrage Filed",
        "m_score_variance": "Variable Chaos Manuscript Scores",
        "m_binge_rater": "Chaos Binge Rating Session",
        "m_reread_rerate": "Reread and Re-Rate Chaos Intel",
        "m_masterpiece_hunter": "Masterpiece Chaos Manuscript Hunter",
        "m_contrarian": "Contrarian Chaos Reader",
        "m_optimist": "Optimistic Chaos Reader Scout",
        "m_score_distributor": "Score Distributor General",
        "m_genre_critic": "Genre Chaos Reading Critic",
        "m_mean_above_8": "Elite Chaos Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Chaos Reading Vow",
        "m_valentines_read": "Valentine's Chaos Reading Bond",
        "m_pi_day": "Pi Day Chaos Chapter Count",
        "m_april_fools": "April Fools Happosai Chibi",
        "m_international_manga_day": "International Chaos Manga Day",
        "m_free_comic_day": "Free Comic Chaos Day",
        "m_summer_solstice": "Summer Solstice Chaos Reading",
        "m_tanabata": "Tanabata Chaos Reading Wish",
        "m_friday_13th": "Friday 13th Chaos Manuscript",
        "m_halloween_read": "Halloween Chaos Horror Reading",
        "m_thanksgiving_binge": "Thanksgiving Chaos Reading Feast",
        "m_christmas_read": "Midwinter Chaos Festival Reading",
        "m_new_years_eve": "New Year's Eve Final Chaos Read",
        "m_birthday_read": "Birthday Chaos Reading Gift",
        "m_holiday_marathon": "Holiday Chaos Reading Marathon",
        "m_independence_day": "Nerima Independence Reading",
        "m_culture_day": "Anything-Goes Culture Day Manuscript",
        "m_spring_equinox": "Spring Chaos Equinox Reading",
        "m_earth_day": "Earth Day Chaos Conservation Read",
        "m_labor_day": "Nerima Labor Reading Day",
        "m_winter_solstice": "Winter Solstice Chaos Reading",
        "m_manga_birthday": "Chaos Manga Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Chaos Reader",
        "m_consecutive_holidays": "Consecutive Holiday Chaos Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Chaos Milestone",
        "m_fibonacci": "Fibonacci Chaos Chapter Pattern",
        "m_palindrome_day": "Palindrome Chaos Reading Day",
        "m_binary_day": "Binary Chaos Signal Reading Day",
        "m_full_moon_read": "Full Moon Chaos Read",
        "m_leap_year_read": "Leap Year Chaos Reading",
        "m_triple_seven": "Triple Seven Chaos Fighters",
        "m_thousand_complete": "Thousand Chaos Manga Victories",
        "m_nice": "Nice Chaos Chapter Count",
        "m_power_level_chapters": "Anything-Goes-Level Chapters",
        "m_answer_42": "Answer to Ranma's Reading",
        "m_square_number": "Perfect Chaos Formation Chapters",
        "m_prime_count": "Prime Chaos Chapter Count",
        "m_matching_date": "Matching Chaos Intel Reading Date",
        "m_century_chapter": "Century Chaos Chapter Milestone",
        "m_pi_chapters": "Pi Chaos Chapter Calculation",
        "m_synchronicity": "Chaos Reading Synchronicity",
        "m_world_record": "World Record Chaos Chapter Count",
        "m_genre_clash": "Genre Chaos Clash Reading",
        "m_time_traveler": "Time-Traveling Chaos Reader",
        "m_double_digits": "Double Digit Chaos Milestone",
        "m_one_two_three": "Boy Girl Panda One Two Three",
        "m_lucky_seven": "Seven Lucky Chaos Chapters",
        "m_exact_hundred_ch": "Exact Hundred Chaos Chapters Read",
        "m_year_match_count": "Year Match Chaos Chapter Count",
        "m_chapter_match_date": "Chaos Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Manhwa Format Reader",
        "m_manhua_format": "Manhua Format Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Operative",
        "m_doujin_format": "Doujin Format Reader",
        "m_novel_format": "Novel Format Reader",
        "m_format_master_manga": "Format Master Chaos Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Chaos Reading Power Unlocked",
        "m_meta_collector": "Chaos Reading Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Chaos Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Chaos Reading Rank",
        "m_meta_xp_earner": "XP from Chaos Reading Intel",
        "m_meta_difficulty_easy": "Easy Chaos Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Chaos Manuscript Challenge",
        "m_meta_unlock_spree": "Chaos Reading Unlock Barrage",
        "m_meta_completionist": "Meta Chaos Reading Completionist",
        "m_meta_diverse": "Diverse Chaos Reading Portfolio",
        "m_meta_dominator": "Meta Chaos Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060406",
        primary: "#cc2208",
        secondary: "#aa1506",
        accent: "#0055cc",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/ranma-12.jpg",
    particleColor: "#e85050",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        water_droplets: { label: "Water Droplets", maxCount: 14, defaultEnabled: true, defaultIntensity: 55 },
        ki_blast: { label: "Ki Blast", maxCount: 8, defaultEnabled: true, defaultIntensity: 60 },
        martial_sparks: { label: "Martial Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 50 },
        hot_cold_steam: { label: "Hot & Cold Steam", maxCount: 10, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1:   "Cursed Springs Victim",
        5:   "Tendo Dojo Resident",
        15:  "Anything-Goes Fighter",
        30:  "Nerima Chaos Veteran",
        45:  "Shampoo's Target",
        60:  "Herb Battle Survived",
        80:  "Saffron Challenger",
        100: "Jusenkyo Curse Remains",
    },
}
