import { AnimeThemeConfig } from "./types"
import {
    GiSnowflake1, GiCrystalBall, GiIceSpear, GiSilverBullet,
    GiScrollUnfurled, GiSpellBook, GiHourglass, GiCrown,
    GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss } from "react-icons/lu"
import { BiExtension } from "react-icons/bi"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { TbReportSearch } from "react-icons/tb"

export const reZeroTheme: AnimeThemeConfig = {
    id: "re-zero",
    displayName: "Re:Zero",
    description: "Return by Death. Silver & midnight blue. Subaru's undying resolve.",
    fontFamily: "'Nunito', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&display=swap",
    cssVars: {
        "--color-brand-200": "195 220 255",
        "--color-brand-300": "140 180 240",
        "--color-brand-400": "85 135 215",
        "--color-brand-500": "45 95 190",
        "--color-brand-600": "25 65 155",
        "--color-brand-700": "12 42 115",
        "--color-brand-800": "5 25 78",
        "--color-brand-900": "2 12 48",
        "--color-brand-950": "0 5 25",
        "--brand": "55 105 200",
        "--background": "#000510",
        "--paper": "#000a1e",
        "--color-gray-950": "0 4 10",
        "--color-gray-900": "2 10 22",
        "--color-gray-800": "5 20 40",
        "--color-gray-700": "10 35 65",
        "--color-gray-600": "20 55 95",
        "--color-gray-500": "40 85 140",
        "--color-gray-400": "85 135 195",
        "--color-gray-300": "135 178 225",
        "--color-gray-200": "185 212 245",
        "--color-gray-100": "225 238 252",
        "--color-gray-50":  "245 250 255",
    },
    sidebarOverrides: {
        "home":           { icon: GiCrystalBall,   label: "Royal Selection" },
        "schedule":       { icon: GiAlarmClock,    label: "Return Timeline" },
        "manga":          { icon: GiScrollUnfurled,label: "Witch Archives" },
        "lists":          { icon: GiSpellBook,     label: "Spirit Registry" },
        "discover":       { icon: GiSnowflake1,    label: "Emilia's Path" },
        "torrent-list":   { icon: GiIceSpear,      label: "Sanctuary Ops" },
        "unmatched":      { icon: GiHourglass,     label: "Lost Checkpoints" },
        "scan-summaries": { icon: TbReportSearch,  label: "Mission Reports" },
        "auto-downloader":{ icon: LuRss,           label: "Beatrice's Library" },
        "search":         { icon: FiSearch,        label: "Search" },
        "notifications":  { icon: LuBell,          label: "Return Alerts" },
        "achievements":   { icon: GiCrown,         label: "Royal Candidate" },
        "theme-manager":  { icon: GiPalette,       label: "Roswaal Colors" },
        "extensions":     { icon: BiExtension,     label: "Contracts" },
        "settings":       { icon: GiSettingsKnobs, label: "Beatrice's Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode":              "First Return By Death",
        "a_episode_counter":            "Death Loop Count",
        "a_episode_titan":              "Thousand Deaths Survived",
        "a_hours_invested":             "Hours in the Loop",
        "a_time_lord":                  "Return By Death Time Lord",
        "a_anime_collector":            "Isekai Archive Collector",
        "a_library_legend":             "Beatrice's Library Legend",
        "a_first_complete":             "First Loop Broken",
        "a_hundred_club":               "Royal Capital Hundred Club",
        "a_first_day":                  "First Day in Another World",
        "a_first_rating":               "First Loop Evaluation",
        "a_ten_thousand_min":           "Ten Thousand Loop Minutes",
        "a_season_veteran":             "Season Arc Veteran",
        "a_year_explorer":              "Year of Parallel Worlds",
        "a_century_watcher":            "Hundred Episode Watcher",
        "a_five_hundred_eps":           "Five Hundred Deaths Survived",
        "a_thousand_eps":               "Thousand Episode Archive",
        "a_watching_ten":               "Ten Parallel Loops Active",
        "a_ptw_hoarder":                "Checkpoint Hoarder",
        "a_dropped_honesty":            "Honest Tactical Retreat",
        "a_five_thousand_eps":          "Five Thousand Episodes Watched",
        "a_ten_completed":              "Ten Arcs Conquered",
        "a_fifty_completed":            "Fifty Loops Completed",
        "a_five_hundred_completed":     "Five Hundred Victories",
        "a_mean_score_tracker":         "Average Loop Score",
        "a_unique_studios":             "Unique Studio Alliances",
        "a_days_spent_watching":        "Days Lost in Loops",
        "a_all_status":                 "All Loop Statuses",
        "a_first_favorite":             "First Roswaal Manor Bond",
        "a_favorites_collector":        "Bonds of the Royal Capital",

        // ── ANIME BINGE ──
        "a_binge_watcher":              "Non-Stop Return Marathon",
        "a_marathon_runner":            "Arc-to-Arc Marathon",
        "a_weekend_warrior":            "Weekend Loop Warrior",
        "a_non_stop":                   "Relentless Loop Advance",
        "a_one_more_episode":           "One More Death and Return",
        "a_speed_run":                  "Spirit Arts Speed Run",
        "a_double_feature":             "Double Return Feature",
        "a_triple_threat":              "Triple Loop Cleared",
        "a_five_a_day":                 "Five Deaths a Day",
        "a_back_to_back":               "Back-to-Back Loops",
        "a_seasonal_binge":             "Full Arc Campaign",
        "a_cour_crusher":               "Sanctuary Crusher",
        "a_half_day_watch":             "Half-Day Sanctuary Watch",
        "a_full_day_watch":             "Full Day in the Loop",
        "a_power_weekend":              "Power Weekend at the Manor",
        "a_binge_king":                 "King of Return Marathons",
        "a_no_sleep":                   "All-Night Death Cycle",
        "a_entire_season":              "Full Season Loop Clear",
        "a_seven_day_challenge":        "Seven-Day Loop Challenge",
        "a_hundred_day_binge":          "Hundred-Day Return Siege",
        "a_genre_binge":                "Cross-Genre Loop Binge",
        "a_studio_binge":               "Allied Studio Binge",
        "a_season_sweep":               "Season Sweep Loop",
        "a_forty_eight_hour":           "Forty-Eight Hour Return",
        "a_ep_counter_day":             "Daily Loop Counter",
        "a_multi_series_binge":         "Multi-Arc Campaign",
        "a_midnight_binge":             "Midnight Return Ritual",
        "a_new_year_binge":             "New Year's Loop Charge",

        // ── ANIME GENRES ──
        "a_genre_action":               "Sin Archbishop Slayer",
        "a_genre_adventure":            "Beyond Lugnica's Borders",
        "a_genre_comedy":               "Subaru's Self-Introduction",
        "a_genre_drama":                "Emilia's Frozen Kingdom",
        "a_genre_fantasy":              "Paths of the Witch",
        "a_genre_horror":               "Return By Death Terror",
        "a_genre_mystery":              "Witch's Unseen Hand",
        "a_genre_romance":              "Emilia's Knight",
        "a_genre_scifi":                "Witch Factor Science",
        "a_genre_sol":                  "Life at Roswaal Manor",
        "a_genre_sports":               "Royal Selection Games",
        "a_genre_supernatural":         "Unseen Hands Power",
        "a_genre_thriller":             "Sloth Archbishop Pursuit",
        "a_genre_mecha":                "Iron Fang Mercenaries",
        "a_genre_music":                "Re:Zero Soundtrack Lover",
        "a_genre_psychological":        "Return By Death Trauma",
        "a_genre_ecchi":                "Hot Springs Loop Episode",
        "a_genre_mahou_shoujo":         "Spirit Arts Wielder",
        "a_tag_isekai":                 "Transported to Another World",
        "a_tag_harem":                  "Roswaal Manor Residents",
        "a_tag_bl":                     "Subaru's Male Bonds",
        "a_tag_gl":                     "Emilia and Rem's Bond",
        "a_tag_historical":             "Lugnica Kingdom History",
        "a_tag_military":               "Royal Knight Discipline",
        "a_tag_school":                 "Aldebaran's Academy",
        "a_tag_martial_arts":           "Reinhard's Sword Saint Style",
        "a_tag_vampire":                "Elior Forest Spirits",
        "a_tag_samurai":                "Sword Saint Style",
        "a_tag_space":                  "Beyond Lugnica's World",
        "a_tag_parody":                 "Subaru's Isekai Parody",
        "a_tag_idol":                   "Emilia's Idol Arc",
        "a_tag_post_apocalyptic":       "Post-Satella Apocalypse",
        "a_tag_cyberpunk":              "Witch Factor Technology",
        "a_tag_shounen":                "Dedicate Your Heart Loop",
        "a_tag_seinen":                 "Harsh Reality of Loops",
        "a_tag_shoujo":                 "Rem's Devotion Arc",
        "a_tag_josei":                  "Emilia's Obsession",
        "a_tag_survival":               "Survival by Returning",

        // ── ANIME COMPLETION ──
        "a_completionist":              "Full Loop Report",
        "a_mega_completionist":         "Commander of All Loops",
        "a_completion_rate_50":         "Halfway to Breaking the Curse",
        "a_completion_rate_75":         "Approaching the Witch's Gospel",
        "a_completion_rate_90":         "Paths Nearly Unlocked",
        "a_no_drop":                    "Never Abandon the Loop",
        "a_long_runner_complete":       "Long Arc Endurance",
        "a_sequel_chain":               "Sequential Arc Chain",
        "a_clean_list":                 "Clean Loop Record",
        "a_from_ptw":                   "Orders Received and Returned",
        "a_rewatch_master":             "Return By Rewatch",
        "a_short_complete":             "Quick Isekai Victory",
        "a_same_day_start_finish":      "Same-Day Loop Elimination",
        "a_revival":                    "Revived by Return By Death",
        "a_zero_to_hero":               "Ordinary to Hero",
        "a_five_genre_complete":        "Five-Genre Mastery",
        "a_full_franchise":             "Full Re:Zero Dossier",
        "a_batch_complete":             "Batch Arc Clearance",
        "a_paused_to_done":             "Returned from Checkpoint",
        "a_completion_spree":           "Completion Loop Chain",
        "a_multi_rewatch":              "Multi-Timeline Rewatch",
        "a_dropped_recovery":           "Recovered from the Witch's Grasp",
        "a_ten_perfect_scores":         "Ten Perfect Loop Scores",
        "a_seasonal_clear":             "Seasonal Arc Complete",
        "a_complete_genre_span":        "All-Genre Loop Scout",
        "a_monthly_completions":        "Monthly Loop Reports",
        "a_yearly_completions":         "Yearly Campaign Victor",
        "a_rapid_complete":             "Lightning Loop Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan":                  "Loyal Royal Selection Member",
        "a_studio_devotee":             "White Fox Devotee",
        "a_rewatcher":                  "Return Recon Rewatch",
        "a_triple_rewatch":             "Triple Loop Rewatch",
        "a_annual_tradition":           "Annual Return Remembrance",
        "a_director_fan":               "Watanabe's Vision Follower",
        "a_voice_actor_fan":            "Voice of the Royal Capital",
        "a_ost_lover":                  "Redo of the Restart",
        "a_source_reader":              "Nagatsuki's Original Texts",
        "a_waiting_weekly":             "Weekly Return Signal Wait",
        "a_childhood_revisit":          "Return to First Loop",
        "a_saga_tracker":               "Saga of Subaru Tracker",
        "a_genre_loyalty":              "Royal Selection Loyalty Badge",
        "a_decade_watcher":             "Decade-Long Loop Watcher",
        "a_adaptation_hunter":          "Adaptation Loop Recon",
        "a_original_anime_fan":         "Original Broadcast Veteran",
        "a_long_commitment":            "Long-Term Loop Duty",
        "a_perfect_attendance":         "Perfect Loop Attendance",
        "a_favorite_studio_5":          "Five Allied Studios",
        "a_complete_catalog":           "Complete Royal Archive",
        "a_franchise_collector":        "Re:Zero Universe Collector",
        "a_airing_follower":            "Currently Airing Intel",
        "a_genre_master":               "Genre Mastery Achieved",
        "a_staff_follower":             "Staff Dossier Tracker",
        "a_multi_season_fan":           "Multi-Arc Veteran",
        "a_format_diversity":           "Diverse Tactical Formats",
        "a_year_dedication":            "Year of Dedication to Emilia",
        "a_season_dedication":          "Season of Unwavering Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer":             "Scout Beyond Known Territory",
        "a_studio_hopper":              "Studio Loop Transfer",
        "a_tag_explorer":               "Tag Recon Mission",
        "a_decade_hopper":              "Time Loop Decade Hopper",
        "a_hidden_gem":                 "Hidden Elior Forest Gem",
        "a_popular_taste":              "Popular Among the Manor",
        "a_retro_appreciator":          "Pre-Isekai Era Appreciator",
        "a_modern_viewer":              "Modern Loop Viewer",
        "a_cross_demographic":          "Cross-Loop Demographic",
        "a_underdog_fan":               "Underdog Subaru Spirit",
        "a_variety_week":               "Week of Varied Loops",
        "a_foreign_cinema":             "Foreign Kingdom Cinema",
        "a_classic_connoisseur":        "Classic Isekai Connoisseur",
        "a_every_season":               "Every Season Deployed",
        "a_award_winner":               "Royal Selection Medal",
        "a_niche_explorer":             "Niche Kingdom Explorer",
        "a_global_anime":               "Global Alliance Entry",
        "a_cult_classic":               "Witch Cult Classic",
        "a_random_pick":                "Random Loop Assignment",
        "a_new_genre_month":            "New Territory Monthly",
        "a_seasonal_completionist":     "Seasonal Arc Complete",
        "a_unpopular_opinion":          "Unpopular Loop Opinion",
        "a_top_rated_viewer":           "Top-Rated Royal Intel",
        "a_source_variety":             "Source Material Variety",
        "a_low_score_brave":            "Brave Loop into Low Scores",
        "a_upcoming_watcher":           "Upcoming Arc Intel",
        "a_short_series_explorer":      "Short Loop Explorer",
        "a_long_series_explorer":       "Long Arc Explorer",

        // ── ANIME TIME ──
        "a_night_owl":                  "Midnight Return Ritual",
        "a_early_bird":                 "Dawn Loop Patrol",
        "a_lunch_break":                "Lunch Break at the Manor",
        "a_golden_hour":                "Golden Hour Return",
        "a_four_am_club":               "4 AM Return Checkpoint",
        "a_witching_hour":              "Witch's Hour",
        "a_new_year_watch":             "New Year's Oath to Emilia",
        "a_midnight_premiere":          "Midnight Loop Premiere",
        "a_all_hours":                  "All-Hours Loop Watcher",
        "a_dawn_warrior":               "Dawn Loop Warrior",
        "a_afternoon_delight":          "Afternoon at the Manor",
        "a_prime_time":                 "Prime Time Engagement",
        "a_workday_watcher":            "On-Duty Watcher",
        "a_sunday_marathon":            "Sunday Loop Marathon",
        "a_rainy_day":                  "Rainy Day in Lugunica",
        "a_morning_routine":            "Morning Loop Formation",
        "a_night_shift":                "Night Shift Loop Patrol",
        "a_twilight_zone":              "Twilight Beyond the Loop",
        "a_seasonal_premier":           "Season Arc Premiere",
        "a_clock_collector":            "Hourglass Collector",
        "a_weekend_binge_hours":        "Weekend Loop Binge Ops",
        "a_late_night_regular":         "Late Night Loop Regular",
        "a_sunrise_watcher":            "Sunrise Over Lugnica",
        "a_holiday_watcher":            "Holiday Loop Duty",
        "a_every_day_of_week":          "Every Day in the Loop",
        "a_monthly_hours":              "Monthly Loop Hours",

        // ── ANIME SOCIAL ──
        "a_first_party":                "First Royal Selection Squad",
        "a_party_host":                 "Roswaal Manor Host",
        "a_social_butterfly":           "Manor Hall Socialite",
        "a_group_binge":                "Group Spirit Pact Volley",
        "a_party_regular":              "Regular Loop Partner",
        "a_sync_viewer":                "Synchronized Loop Maneuver",
        "a_commentator":                "Loop Battle Commentator",
        "a_party_marathon":             "Marathon Loop Formation",
        "a_full_house":                 "Full Roswaal Manor Squad",
        "a_community_pillar":           "Pillar of the Kingdom",
        "a_watch_party_streak":         "Consecutive Loop Streak",
        "a_diverse_party":              "Diverse Royal Capital Party",
        "a_late_night_party":           "Late Night Manor Party",
        "a_party_veteran":              "Veteran Loop Squad Leader",
        "a_genre_party":                "Cross-Genre Loop Formation",
        "a_weekly_party":               "Weekly Comrades' Gathering",
        "a_silent_viewer":              "Silent Beatrice Observer",
        "a_recommendation_giver":       "Subaru's Recommendation",
        "a_party_completionist":        "Party Loop Completionist",
        "a_social_scorer":              "Social Loop Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number":               "Round Number Return",
        "a_fibonacci":                  "Fibonacci Death Sequence",
        "a_palindrome_day":             "Palindrome Return Day",
        "a_binary_day":                 "Binary Checkpoint Day",
        "a_full_moon":                  "Full Moon Spirit Transformation",
        "a_leap_year":                  "Leap Year Time Skip",
        "a_time_traveler":              "Subaru's Future Memory",
        "a_genre_clash":                "Witch vs. Kingdom Clash",
        "a_triple_seven":               "Triple Seven Arcs",
        "a_thousand_complete":          "Thousand Loops for Emilia",
        "a_pi_episodes":                "Pi Loop Calculation",
        "a_synchronicity":              "Loop Synchronicity",
        "a_world_record":               "World Record Death Count",
        "a_nice":                       "Nice Loop Count",
        "a_power_level":                "Reinhard Power Level",
        "a_answer_42":                  "The Answer to Subaru's Question",
        "a_square_number":              "Perfect Loop Formation",
        "a_prime_count":                "Prime Number of Deaths",
        "a_matching_date":              "Matching Loop Date",
        "a_century_episode":            "Century Episode Return",
        "a_double_digits":              "Double Digit Deaths",
        "a_one_two_three":              "Witch, Knight, Spirit",
        "a_lucky_seven":                "Seven Lucky Loop Days",
        "a_all_tens":                   "All Tens Loop Score",
        "a_exact_hundred_eps":          "Exact Hundred Loops",
        "a_year_match_count":           "Year Match Return Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher":                 "TV Broadcast Scout",
        "a_movie_buff":                 "White Fox Film Operations",
        "a_ova_hunter":                 "Memory Snow OVA Hunter",
        "a_ona_explorer":               "ONA Loop Explorer",
        "a_special_watcher":            "Special Episode Operative",
        "a_short_king":                 "Short Arc King",
        "a_variety_pack":               "All-Format Kingdom",
        "a_film_festival":              "Witch Film Festival",
        "a_music_video":                "Redo Collection",
        "a_tv_short":                   "Quick Recon Clip",
        "a_movie_marathon":             "Movie Loop Marathon",
        "a_double_length":              "Double-Length Loop",
        "a_anthology":                  "Royal Capital Anthology",
        "a_mini_series":                "Mini Arc Collection",
        "a_theatrical":                 "Theatrical Loop Deployment",
        "a_format_master":              "Format Master Scout",
        "a_long_movie":                 "Feature-Length Loop",
        "a_back_catalog":               "Back Catalog Loop Files",
        "a_cm_watcher":                 "Commercial Break Watcher",
        "a_pv_collector":               "Preview Loop Collector",
        "a_format_balance":             "Balanced Loop Formats",
        "a_episodic_master":            "Episodic Loop Master",
        "a_sequel_movie":               "Sequel Loop Film",
        "a_recap_watcher":              "Recap Loop Briefing",

        // ── ANIME STREAKS ──
        "a_daily_streak":               "Daily Loop Streak",
        "a_mega_streak":                "Mega Return Streak",
        "a_weekly_warrior":             "Weekly Warrior of the Loops",
        "a_monthly_watcher":            "Monthly Loop Duty",
        "a_comeback":                   "Return from Outside the Loop",
        "a_weekend_streak":             "Weekend Return Streak",
        "a_no_zero_days":               "No Zero Days in the Loop",
        "a_iron_will":                  "Subaru's Iron Will",
        "a_habit_formed":               "Loop Regimen Formed",
        "a_consistent_pace":            "Consistent March Forward",
        "a_year_long":                  "Year-Long Loop Campaign",
        "a_double_streak":              "Double Return Streak",
        "a_streak_recovery":            "Loop Recovery Streak",
        "a_daily_minimum":              "Daily Minimum Loop Duty",
        "a_winter_streak":              "Winter Loop Campaign",
        "a_summer_streak":              "Summer Loop Offensive",
        "a_morning_streak":             "Morning Loop Formation",
        "a_night_streak":               "Night Loop Patrol",
        "a_unbreakable":                "Unbreakable Will of Subaru",
        "a_eternal_flame":              "Eternal Flame of Return",
        "a_completion_streak":          "Completion Loop Chain",
        "a_rating_streak":              "Rating Streak Report",
        "a_multi_ep_streak":            "Multi-Episode Return Streak",
        "a_genre_streak":               "Genre Loop Streak",
        "a_studio_streak":              "Studio Loyalty Streak",
        "a_perfect_week":               "Perfect Week of Returns",

        // ── ANIME SCORING ──
        "a_critic":                     "Royal Selection Judge",
        "a_perfect_ten":                "Perfect 10 Loop Rating",
        "a_harsh_critic":               "Beatrice's Harsh Standards",
        "a_fair_judge":                 "Roswaal's Fair Assessment",
        "a_generous_spirit":            "Generous Emilia Spirit",
        "a_score_all":                  "Full Roster Evaluation",
        "a_wide_range":                 "Wide Range Loop Assessment",
        "a_controversial":              "Controversial Return Decision",
        "a_consistent_scorer":          "Consistent Loop Evaluator",
        "a_score_sniper":               "Precision Spirit Arrow Sniper",
        "a_evolving_taste":             "Evolving Return Strategy",
        "a_bell_curve":                 "Bell Curve of Loop Scores",
        "a_picky_watcher":              "Selective Royal Knight",
        "a_100_rated":                  "Century of Evaluations",
        "a_500_rated":                  "Five Hundred Field Reports",
        "a_mediocre_majority":          "Middle Ground Strategist",
        "a_rating_spree":               "Rating Return Barrage",
        "a_score_variance":             "Variable Loop Ratings",
        "a_masterpiece_hunter":         "Masterpiece Loop Hunter",
        "a_contrarian":                 "Contrarian Royal Scout",
        "a_optimist":                   "Optimist Despite the Deaths",
        "a_score_distributor":          "Score Distributor Knight",
        "a_genre_critic":               "Genre Loop Critic",
        "a_mean_above_8":               "Elite Loop Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution":       "New Year's Vow for Emilia",
        "a_valentines_weeb":            "Valentine's Return Dedication",
        "a_pi_day":                     "Pi Day Loop Calculation",
        "a_april_fools":                "April Fools Return Prank",
        "a_international_anime_day":    "International Loop Day",
        "a_star_wars_day":              "Witch Cult Empire Day",
        "a_summer_solstice":            "Summer Solstice Loop",
        "a_tanabata":                   "Tanabata Wish for Emilia",
        "a_friday_13th":                "Friday 13th Death Loop",
        "a_halloween_spirit":           "Halloween Witch Horror",
        "a_thanksgiving_binge":         "Thanksgiving Loop Feast",
        "a_christmas_special":          "Midwinter Festival Special",
        "a_new_years_eve":              "New Year's Eve Final Return",
        "a_birthday_watch":             "Birthday Loop Watch",
        "a_holiday_marathon":           "Holiday Loop Marathon",
        "a_independence_day":           "Lugunica Independence Day",
        "a_culture_day":                "Lugunica Culture Day",
        "a_spring_equinox":             "Spring Equinox Loop Advance",
        "a_earth_day":                  "Protect This World Day",
        "a_labor_day":                  "Roswaal Mansion Labor Day",
        "a_winter_solstice":            "Winter Solstice Return",
        "a_anime_birthday":             "Anime Anniversary Return",
        "a_every_holiday":              "Every Holiday Loop Scout",
        "a_consecutive_holidays":       "Consecutive Holiday Returns",

        // ── ANIME META ──
        "a_meta_first_unlock":          "First Return Power Awakened",
        "a_meta_collector":             "Royal Selection Badge Collector",
        "a_meta_category_starter":      "Category Initiation Loop",
        "a_meta_tier_climber":          "Rank Promotion in Lugunica",
        "a_meta_tier_max":              "Royal Knight Max Rank",
        "a_meta_xp_earner":             "XP from Return Deaths",
        "a_meta_difficulty_easy":       "Easy Loop Exercise",
        "a_meta_difficulty_hard":       "Legendary Difficulty: Witch",
        "a_meta_unlock_spree":          "Unlock Loop Thunder Barrage",
        "a_meta_completionist":         "Meta Completionist Knight",
        "a_meta_diverse":               "Diverse Royal Portfolio",
        "a_meta_dominator":             "Meta Dominator of Loops",

        // ── MANGA MILESTONES ──
        "m_first_chapter":              "First LN Chapter Return",
        "m_chapter_counter":            "Chapter Loop Counter",
        "m_chapter_titan":              "Chapter Witch Assault",
        "m_reading_hours":              "Hours Studying Witch Texts",
        "m_reading_time_lord":          "Return By Death Reading Memory",
        "m_manga_collector":            "Royal Archive Collector",
        "m_library_legend":             "Beatrice's Sea Book Legend",
        "m_first_complete":             "First Manga Arc Done",
        "m_hundred_club":               "Hundred-Chapter Royal Club",
        "m_first_day":                  "First Day of Reading Training",
        "m_first_rating":               "First Manuscript Rating",
        "m_ten_thousand_pages":         "Ten Thousand Pages of Loop Intel",
        "m_volume_collector":           "Volume Archive Collector",
        "m_year_explorer":              "Year of Manga Exploration",
        "m_century_reader":             "Century-Chapter Reader",
        "m_five_hundred_ch":            "Five Hundred Chapters Read",
        "m_thousand_ch":                "Thousand-Chapter Campaign",
        "m_reading_ten":                "Ten Manuscripts at Once",
        "m_ptr_hoarder":                "Reading Backlog Hoarder",
        "m_dropped_honesty":            "Honest Loop Retreat",
        "m_season_reader":              "Seasonal Reading Rotation",
        "m_active_reader":              "Active Loop Reader",
        "m_five_thousand_ch":           "Five Thousand Chapters Deep",
        "m_ten_completed":              "Ten Manga Arcs Complete",
        "m_fifty_completed":            "Fifty Manga Missions Done",
        "m_five_hundred_completed":     "Five Hundred Manga Victories",
        "m_mean_score_tracker":         "Average Manuscript Rating",
        "m_unique_authors":             "Unique Author Encounters",
        "m_all_status":                 "All Reading Loop Statuses",
        "m_first_favorite":             "First Manga Bond",
        "m_favorites_collector":        "Manga Favorites Arsenal",
        "m_days_spent_reading":         "Days in the Reading Loop",

        // ── MANGA BINGE ──
        "m_binge_reader":               "Binge Reading Return",
        "m_marathon_reader":            "Arc-to-Arc Reading Marathon",
        "m_weekend_reader":             "Weekend Manor Reading",
        "m_non_stop_reading":           "Non-Stop Page Turning",
        "m_one_more_chapter":           "One More Chapter Return",
        "m_speed_read":                 "Spirit Arts Speed Read",
        "m_double_story":               "Double Manuscript Feature",
        "m_triple_read":                "Triple Reading Return",
        "m_five_a_day":                 "Five Reads a Day",
        "m_chapter_chain":              "Chapter Chain Return",
        "m_volume_binge":               "Volume Binge Bombardment",
        "m_power_reader":               "Power Reader Scout",
        "m_half_day_read":              "Half-Day Archive Dive",
        "m_full_day_read":              "Full-Day Manuscript Study",
        "m_power_weekend":              "Power Weekend Reading",
        "m_binge_king":                 "King of the Reading Loop",
        "m_no_sleep_read":              "All-Night Loop Reading",
        "m_full_series_rush":           "Full Series Rush Return",
        "m_seven_day_challenge":        "Seven-Day Intel Gathering",
        "m_hundred_day_read":           "Hundred-Day Reading Return",
        "m_volume_rush":                "Volume Rush Deployment",
        "m_series_sweep":               "Series Sweep Return",
        "m_genre_binge":                "Cross-Genre Loop Binge",
        "m_author_binge":               "Author Focused Deep Dive",
        "m_chapter_counter_day":        "Daily Chapter Loop Count",
        "m_multi_series_binge":         "Multi-Series Reading Front",
        "m_midnight_binge":             "Midnight Archive Return",
        "m_new_year_binge":             "New Year's Reading Return",
        "m_forty_eight_hour":           "Forty-Eight Hour Reading Return",
        "m_oneshot_binge":              "Oneshot Loop Blitz",

        // ── MANGA GENRES ──
        "m_genre_action":               "Action Arc Specialist",
        "m_genre_adventure":            "Adventure Beyond Lugunica",
        "m_genre_comedy":               "Comedy at Roswaal Manor",
        "m_genre_drama":                "Drama of Satella's Love",
        "m_genre_fantasy":              "Fantasy of the Witch's Gospel",
        "m_genre_horror":               "Witch Horror Manuscript",
        "m_genre_mystery":              "Mystery of Echidna's Tea Party",
        "m_genre_romance":              "Romance of the Royal Selection",
        "m_genre_scifi":                "Sci-Fi Witch Factor",
        "m_genre_sol":                  "Slice of Life at the Manor",
        "m_genre_sports":               "Royal Capital Sports",
        "m_genre_supernatural":         "Unseen Hand Power",
        "m_genre_thriller":             "Thriller Archbishop Hunt",
        "m_genre_psychological":        "Return Psychological Manga",
        "m_genre_isekai":               "Isekai Another World Manga",
        "m_genre_shounen":              "Shounen Heart of Subaru",
        "m_genre_ecchi":                "Manor Hot Springs Chapter",
        "m_genre_mahou_shoujo":         "Spirit Contract Manga",
        "m_genre_mecha":                "Iron Fang Weapon Manga",
        "m_genre_music":                "Lugunica Folk Songs",
        "m_tag_isekai_new":             "New World Another Dimension",
        "m_tag_harem":                  "Roswaal Manor Manga Harem",
        "m_tag_bl":                     "Subaru's Male Bonds Manga",
        "m_tag_gl":                     "Emilia and Rem Manga",
        "m_tag_historical":             "Lugunica Kingdom History Manga",
        "m_tag_military":               "Royal Guard Operations Manga",
        "m_tag_school":                 "Lugunica Academy Manga",
        "m_tag_martial_arts":           "Reinhard Sword Saint Manual",
        "m_tag_vampire":                "Elior Forest Spirit Manga",
        "m_tag_samurai":                "Blade Master Manga",
        "m_tag_space":                  "Beyond the Kingdom Manga",
        "m_tag_parody":                 "Chibi Return Manga",
        "m_tag_idol":                   "Emilia Idol Manga",
        "m_tag_post_apocalyptic":       "Post-Satella Manga",
        "m_tag_cyberpunk":              "Witch Factor Tech Manga",
        "m_tag_shoujo":                 "Rem's Story Manga",
        "m_tag_survival":               "Return Survival Manga",
        "m_tag_cooking":                "Manor Kitchen Cookbook",
        "m_tag_medical":                "Crusch Field Medic Manga",
        "m_tag_villainess":             "Witch Candidate Manga",

        // ── MANGA COMPLETION ──
        "m_completionist":              "Manga Arc Completionist",
        "m_mega_completionist":         "Supreme Manga Knight",
        "m_completion_rate_50":         "Halfway to the Truth",
        "m_completion_rate_75":         "Approaching the Gospel",
        "m_completion_rate_90":         "Final Arc Approaching",
        "m_no_drop":                    "No Manuscript Abandoned",
        "m_long_runner_complete":       "Long Series Endurance Medal",
        "m_sequel_chain":               "Sequel Arc of Command",
        "m_clean_list":                 "Clean Reading Record",
        "m_from_ptr":                   "Orders Received: Read",
        "m_reread_master":              "Memory Loop Reread",
        "m_oneshot_complete":           "Oneshot Mission Specialist",
        "m_same_day_start_finish":      "Same-Day Reading Return",
        "m_revival":                    "Revival Through the Loop",
        "m_zero_to_hundred":            "Commoner to Royal Scholar",
        "m_five_genre_complete":        "Five-Genre Mastery",
        "m_full_collection":            "Full Archive Collection",
        "m_batch_complete":             "Batch Arc Clearance",
        "m_paused_to_done":             "Back from Reading Loop",
        "m_completion_spree":           "Completion Return Barrage",
        "m_format_completionist":       "Format Completion Badge",
        "m_catch_up":                   "Caught Up with Serialization",
        "m_multi_reread":               "Multi-Pass Loop Reread",
        "m_dropped_recovery":           "Recovered from Witch's Grasp",
        "m_ten_perfect_scores":         "Ten Perfect Manuscript Scores",
        "m_complete_genre_span":        "All-Genre Reading Scout",
        "m_monthly_completions":        "Monthly Manuscript Victories",
        "m_yearly_completions":         "Yearly Reading Campaign",
        "m_rapid_complete":             "Rapid Loop Processing",
        "m_author_complete":            "Author's Complete Loop Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader":               "Loyal Royal Reader",
        "m_mangaka_lover":              "Nagatsuki Devotee",
        "m_rereader":                   "Loop Rereader",
        "m_triple_reread":              "Triple Reread Return",
        "m_annual_reread":              "Annual Return Reread",
        "m_publisher_fan":              "Publisher Alliance Fan",
        "m_artist_fan":                 "Otsuka Art Appreciation Medal",
        "m_adaptation_compare":         "Manga vs Anime Loop Compare",
        "m_source_material_fan":        "Source Material Loop Scout",
        "m_waiting_weekly":             "Weekly Chapter Return Wait",
        "m_classic_reader":             "Classic Manuscript Reader",
        "m_saga_reader":                "Saga of Subaru Reader",
        "m_genre_loyalty":              "Genre Loyalty Medal",
        "m_decade_reader":              "Decade-Long Reader",
        "m_ln_adaptation":              "Light Novel Adaptation Intel",
        "m_original_work":              "Original Loop Manga",
        "m_long_commitment":            "Long-Term Reading Commitment",
        "m_up_to_date":                 "Up-to-Date with the Arc",
        "m_favorite_mangaka":           "Favorite Mangaka Honored",
        "m_complete_portfolio":         "Complete Reading Portfolio",
        "m_franchise_collector":        "Re:Zero Franchise Collector",
        "m_serialization_follower":     "Serialization Tracker",
        "m_genre_master":               "Genre Mastery Earned",
        "m_multi_series_author":        "Multi-Series Author Fan",
        "m_format_diversity":           "Diverse Reading Formats",
        "m_year_dedication":            "Year of Dedicated Reading",
        "m_ongoing_follower":           "Ongoing Arc Follower",
        "m_genre_loyalty_50":           "Fifty Genre Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer":             "Genre Territory Scout",
        "m_publisher_hopper":           "Publisher Loop Transfer",
        "m_tag_explorer":               "Manga Tag Recon Mission",
        "m_decade_hopper":              "Decade-Hopping via Loop",
        "m_hidden_gem":                 "Hidden Elior Forest Gem",
        "m_popular_taste":              "Popular Among Recruits",
        "m_retro_reader":               "Retro Manuscript Appreciator",
        "m_modern_reader":              "Modern Loop Reader",
        "m_cross_demographic":          "Cross-Loop Demographic Reader",
        "m_underdog_fan":               "Underdog Loop Fan",
        "m_variety_week":               "Week of Varied Readings",
        "m_manhwa_reader":              "Manhwa Return Intelligence",
        "m_manhua_reader":              "Manhua Return Intelligence",
        "m_classic_connoisseur":        "Classic Isekai Manuscript",
        "m_award_winner":               "Medal-Winning Manuscript",
        "m_niche_explorer":             "Niche Territory Reader",
        "m_world_manga":                "World Manga Intel",
        "m_cult_classic":               "Witch Cult Classic Manga",
        "m_random_pick":                "Random Loop Reading Assignment",
        "m_new_genre_month":            "New Genre Loop Monthly",
        "m_year_completionist":         "Year Reading Loop Completionist",
        "m_unpopular_opinion":          "Unpopular Loop Reading Opinion",
        "m_top_rated_reader":           "Top-Rated Loop Intel Source",
        "m_source_variety":             "Source Material Variety",
        "m_low_score_brave":            "Brave Low-Score Reader",
        "m_short_manga_explorer":       "Short Manga Loop Explorer",
        "m_long_manga_explorer":        "Long Arc Manuscript",
        "m_serialization_explorer":     "Serialization Loop Explorer",

        // ── MANGA TIME ──
        "m_night_owl":                  "Night Owl Loop Reader",
        "m_early_bird":                 "Dawn Loop Reader",
        "m_lunch_reader":               "Mess Hall Reader",
        "m_commute_reader":             "Travel to the Manor Reader",
        "m_four_am_club":               "4 AM Return Sentry Reader",
        "m_new_year_read":              "New Year's Reading Return",
        "m_all_hours":                  "All-Hours Archive Access",
        "m_prime_time_reader":          "Prime Time Manuscript",
        "m_workday_reader":             "On-Duty Reader",
        "m_sunday_read":                "Sunday Reading Return",
        "m_morning_routine":            "Morning Loop Reading",
        "m_night_shift_reader":         "Night Shift Loop Reader",
        "m_seasonal_premier_read":      "New Arc Release Intel",
        "m_clock_collector":            "Hourglass Reading Time",
        "m_late_night_horror":          "Midnight Witch Horror Read",
        "m_afternoon_reader":           "Afternoon Manor Reading",
        "m_golden_hour_reader":         "Golden Hour Reading",
        "m_dawn_reader":                "Dawn Reading Return",
        "m_twilight_reader":            "Twilight Loop Reading",
        "m_midnight_start":             "Midnight Reading Return",
        "m_weekend_binge_hours":        "Weekend Binge Loop Reading",
        "m_late_night_regular":         "Late Night Regular Loop Reader",
        "m_sunrise_reader":             "Sunrise Over Lugunica Reader",
        "m_every_day_of_week":          "Every Day Loop Reading",
        "m_monthly_hours":              "Monthly Loop Hours Logged",
        "m_bedtime_reader":             "Bedtime Manor Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator":            "Otsuka Art Appreciator",
        "m_webtoon_reader":             "Webtoon Loop Intelligence",
        "m_full_color":                 "Full Color Loop Manuscript",
        "m_doujin_reader":              "Underground Doujin Reader",
        "m_anthology_reader":           "Royal Capital Anthology Reader",
        "m_adaptation_reader":          "Adaptation Loop Study Reader",
        "m_longstrip_reader":           "Vertical Scroll Reader",
        "m_4koma_reader":               "4-Koma Comedy Shorts",
        "m_oneshot_reader":             "Oneshot Return Reader",
        "m_format_variety":             "Format Loop Variety",
        "m_light_novel_reader":         "Light Novel Loop Reader",
        "m_novel_reader":               "Novel Loop Archive Reader",
        "m_visual_storyteller":         "Visual Loop Narrator",
        "m_colored_classic":            "Colored Classic Manuscript",
        "m_webcomic_fan":               "Webcomic Underground Fan",
        "m_manga_to_anime":             "Manga to Anime Loop Comparison",
        "m_seinen_reader":              "Seinen Loop Reader",
        "m_josei_reader":               "Josei Loop Perspective",
        "m_award_winning_art":          "Medal-Winning Artwork",
        "m_debut_work":                 "Debut Loop Manuscript",
        "m_vertical_scroll":            "Vertical Scroll Loop Intel",
        "m_traditional_format":         "Traditional Format Reader",
        "m_cross_media":                "Cross-Media Loop Intelligence",
        "m_spinoff_reader":             "Loop Spinoff Reader",
        "m_remake_reader":              "Remake Loop Assignment",
        "m_collaboration_reader":       "Joint Operation Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak":               "Daily Loop Reading Streak",
        "m_mega_streak":                "Mega Return Reading Streak",
        "m_weekly_warrior":             "Weekly Warrior Reader",
        "m_monthly_reader":             "Monthly Loop Reader",
        "m_comeback":                   "Reader's Return from the Loop",
        "m_weekend_streak":             "Weekend Reading Return",
        "m_no_zero_days":               "No Zero Reading Loop Days",
        "m_iron_will":                  "Subaru's Iron Reading Will",
        "m_habit_formed":               "Reading Loop Regimen Formed",
        "m_consistent_pace":            "Consistent Loop Reading Advance",
        "m_year_long":                  "Year-Long Reading Return",
        "m_double_streak":              "Double Reading Return Streak",
        "m_streak_recovery":            "Reading Return Recovery",
        "m_daily_minimum":              "Daily Minimum Loop Pages",
        "m_winter_streak":              "Winter Reading Return",
        "m_summer_streak":              "Summer Reading Offensive",
        "m_morning_streak":             "Morning Reading Loop Formation",
        "m_night_streak":               "Night Reading Loop Patrol",
        "m_unbreakable":                "Unbreakable Reading Will",
        "m_eternal_flame":              "Eternal Flame of Knowledge",
        "m_chapter_a_day":              "Chapter a Day Return",
        "m_genre_streak":               "Genre Reading Return Streak",
        "m_completion_streak":          "Completion Reading Chain",
        "m_rating_streak":              "Rating Streak Filed",
        "m_multi_ch_streak":            "Multi-Chapter Return Streak",
        "m_author_streak":              "Author Loop Dedication Streak",
        "m_perfect_week_manga":         "Perfect Reading Week",
        "m_diverse_streak":             "Diverse Reading Return Streak",

        // ── MANGA SCORING ──
        "m_critic":                     "Royal Manuscript Critic",
        "m_perfect_ten":                "Perfect 10 Manuscript",
        "m_harsh_critic":               "Beatrice's Reading Standards",
        "m_fair_judge":                 "Roswaal's Fair Review",
        "m_generous_spirit":            "Generous Reader Spirit",
        "m_score_all":                  "Full Manuscript Assessment",
        "m_wide_range":                 "Wide Range Loop Scores",
        "m_controversial":              "Controversial Reading Loop",
        "m_consistent_scorer":          "Consistent Manuscript Scorer",
        "m_score_sniper":               "Precision Loop Score Sniper",
        "m_evolving_taste":             "Evolving Loop Reading Taste",
        "m_bell_curve":                 "Bell Curve of Loop Scores",
        "m_picky_reader":               "Selective Royal Reader",
        "m_100_rated":                  "Century of Ratings Filed",
        "m_500_rated":                  "Five Hundred Rating Reports",
        "m_mediocre_majority":          "Middle Ground Reader",
        "m_rating_spree":               "Rating Return Barrage",
        "m_score_variance":             "Variable Loop Scores",
        "m_binge_rater":                "Binge Rating Return",
        "m_reread_rerate":              "Reread and Re-Rate Loop",
        "m_masterpiece_hunter":         "Masterpiece Loop Hunter",
        "m_contrarian":                 "Contrarian Loop Reader",
        "m_optimist":                   "Optimistic Reader Despite Death",
        "m_score_distributor":          "Score Distributor Knight",
        "m_genre_critic":               "Genre Loop Reading Critic",
        "m_mean_above_8":               "Elite Reading Return Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution":       "New Year's Reading Vow",
        "m_valentines_read":            "Valentine's Reading Return",
        "m_pi_day":                     "Pi Day Chapter Return",
        "m_april_fools":                "April Fools Subaru Prank",
        "m_international_manga_day":    "International Manga Return Day",
        "m_free_comic_day":             "Free Comic Return Day",
        "m_summer_solstice":            "Summer Solstice Reading",
        "m_tanabata":                   "Tanabata Reading Return",
        "m_friday_13th":                "Friday 13th Death Reading",
        "m_halloween_read":             "Halloween Witch Reading",
        "m_thanksgiving_binge":         "Thanksgiving Reading Return",
        "m_christmas_read":             "Midwinter Festival Reading",
        "m_new_years_eve":              "New Year's Eve Final Return",
        "m_birthday_read":              "Birthday Reading Return",
        "m_holiday_marathon":           "Holiday Reading Marathon",
        "m_independence_day":           "Lugunica Independence Reading",
        "m_culture_day":                "Culture Day Manuscript",
        "m_spring_equinox":             "Spring Equinox Reading",
        "m_earth_day":                  "Protect This World Reading",
        "m_labor_day":                  "Mansion Labor Reading Day",
        "m_winter_solstice":            "Winter Solstice Loop Reading",
        "m_manga_birthday":             "Manga Birthday Return",
        "m_every_holiday_reader":       "Every Holiday Loop Reader",
        "m_consecutive_holidays":       "Consecutive Holiday Returns",

        // ── MANGA SPECIAL ──
        "m_round_number":               "Round Number Return Milestone",
        "m_fibonacci":                  "Fibonacci Loop Chapter Pattern",
        "m_palindrome_day":             "Palindrome Reading Return",
        "m_binary_day":                 "Binary Signal Reading Day",
        "m_full_moon_read":             "Full Moon Witch Read",
        "m_leap_year_read":             "Leap Year Reading Return",
        "m_triple_seven":               "Triple Seven Arcs of Reading",
        "m_thousand_complete":          "Thousand Manga Victories",
        "m_nice":                       "Nice Chapter Count",
        "m_power_level_chapters":       "Reinhard-Level Chapters",
        "m_answer_42":                  "Answer to Subaru's Reading",
        "m_square_number":              "Perfect Formation Chapters",
        "m_prime_count":                "Prime Chapter Return Count",
        "m_matching_date":              "Matching Loop Reading Date",
        "m_century_chapter":            "Century Chapter Return",
        "m_pi_chapters":                "Pi Chapter Loop Calculation",
        "m_synchronicity":              "Loop Reading Synchronicity",
        "m_world_record":               "World Record Chapter Return",
        "m_genre_clash":                "Genre Clash Loop Reading",
        "m_time_traveler":              "Time-Traveling Loop Reader",
        "m_double_digits":              "Double Digit Loop Milestone",
        "m_one_two_three":              "Witch Knight Spirit",
        "m_lucky_seven":                "Seven Lucky Loop Chapters",
        "m_exact_hundred_ch":           "Exact Hundred Chapters Read",
        "m_year_match_count":           "Year Match Chapter Return",
        "m_chapter_match_date":         "Chapter Return Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format":               "Manga Format Specialist",
        "m_manhwa_format":              "Manhwa Format Reader",
        "m_manhua_format":              "Manhua Format Reader",
        "m_ln_format":                  "Light Novel Loop Format",
        "m_oneshot_format":             "Oneshot Loop Format",
        "m_doujin_format":              "Doujin Format Reader",
        "m_novel_format":               "Novel Loop Format",
        "m_format_master_manga":        "Format Master Loop Reader",

        // ── MANGA META ──
        "m_meta_first_unlock":          "First Reading Power Unlocked",
        "m_meta_collector":             "Reading Badge Collector",
        "m_meta_category_starter":      "Category Return Initiation",
        "m_meta_tier_climber":          "Reading Rank Loop Promotion",
        "m_meta_tier_max":              "Maximum Return Reading Rank",
        "m_meta_xp_earner":             "XP from Loop Reading",
        "m_meta_difficulty_easy":       "Easy Loop Reading Exercise",
        "m_meta_difficulty_hard":       "Legendary Witch Manuscript",
        "m_meta_unlock_spree":          "Reading Loop Unlock Barrage",
        "m_meta_completionist":         "Meta Return Completionist",
        "m_meta_diverse":               "Diverse Return Portfolio",
        "m_meta_dominator":             "Meta Return Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg:        "#000510",
        primary:   "#2d5fc8",
        secondary: "#6699ee",
        accent:    "#c8a0f0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/re-zero.jpg",
    particleColor: "#2d5fc8",
    backgroundDim: 0.30,
    backgroundBlur: 30,
    milestoneNames: {
        1:   "Isekai'd",
        5:   "Roswaal Manor Guest",
        15:  "Royal Selection Candidate",
        28:  "Witch's Disciple",
        42:  "Archbishop Target",
        58:  "Covenant Knight",
        72:  "Sin Archbishop Rival",
        86:  "Sword Saint Level",
        100: "Witch of Envy's Equal",
    },
}
