import { AnimeThemeConfig } from "./types"
import {
    GiKatana,
    GiCrossedSwords,
    GiHorseHead,
    GiChainedHeart,
    GiCompass,
    GiSwordman,
    GiEagleEmblem,
    GiFist,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiResize,
    GiSettingsKnobs,
    GiScrollUnfurled,
    GiAnvilImpact,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const rourouniKenshinTheme: AnimeThemeConfig = {
    id: "rurouni-kenshin",
    displayName: "Rurouni Kenshin",
    description: "Dedicate the reverse blade to peace. Meiji-era aesthetics with crimson robe precision, sakura serenity, and Battōsai's restrained power.",
    fontFamily: "'Noto Serif JP', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;500;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 210 205",
        "--color-brand-300": "245 160 145",
        "--color-brand-400": "230 90 70",
        "--color-brand-500": "204 17 0",
        "--color-brand-600": "170 12 0",
        "--color-brand-700": "130 8 0",
        "--color-brand-800": "90 5 0",
        "--color-brand-900": "50 2 0",
        "--color-brand-950": "25 1 0",
        "--brand": "204 17 0",
        "--background": "#060403",
        "--paper": "#0d0805",
        "--color-gray-950": "6 4 3",
        "--color-gray-900": "13 8 5",
        "--color-gray-800": "24 15 10",
        "--color-gray-700": "38 25 18",
        "--color-gray-600": "58 42 32",
        "--color-gray-500": "90 68 55",
        "--color-gray-400": "130 108 95",
        "--color-gray-300": "168 148 138",
        "--color-gray-200": "200 185 178",
        "--color-gray-100": "228 218 213",
        "--color-gray-50": "245 240 238",
    },
    sidebarOverrides: {
        "home": { icon: GiKatana, label: "Kamiya Dojo" },
        "schedule": { icon: GiAlarmClock, label: "Meiji Era Schedule" },
        "manga": { icon: LuBookOpen, label: "Battōsai's Chronicle" },
        "lists": { icon: GiCrossedSwords, label: "Sword Registry" },
        "discover": { icon: GiCompass, label: "Wanderer's Path" },
        "torrent-list": { icon: GiAnvilImpact, label: "Supply Provisions" },
        "debrid": { icon: GiHorseHead, label: "Meiji Cavalry" },
        "unmatched": { icon: GiChainedHeart, label: "Wandering Souls" },
        "enmasse": { icon: GiResize, label: "Mass Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Meiji Intel" },
        "auto-downloader": { icon: LuRss, label: "Signal Flares" },
        "community": { icon: GiEagleEmblem, label: "Meiji Government" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Dojo Alerts" },
        "achievements": { icon: GiTrophy, label: "Kenshin's Legacy" },
        "theme-manager": { icon: GiPalette, label: "Brush Palette" },
        "extensions": { icon: BiExtension, label: "Dojo Extensions" },
        "sync": { icon: IoCloudOfflineOutline, label: "Rurouni Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Dojo Command" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Steps as a Wanderer",
        "a_episode_counter": "Sakabato Strike Count",
        "a_episode_titan": "Battōsai-Class Duel",
        "a_hours_invested": "Hours on the Meiji Road",
        "a_time_lord": "Ten Swords Remembered",
        "a_anime_collector": "Dojo Arsenal Collector",
        "a_library_legend": "Kaoru's Library Legend",
        "a_first_complete": "First Journey Complete",
        "a_hundred_club": "Century of Duels",
        "a_first_day": "Enlistment in the Meiji Era",
        "a_first_rating": "Rurouni Evaluation",
        "a_ten_thousand_min": "Ten Thousand Minutes of Wandering",
        "a_season_veteran": "Veteran Rurouni",
        "a_year_explorer": "Year on the Meiji Road",
        "a_century_watcher": "Hundred-Episode Swordsman",
        "a_five_hundred_eps": "Five Hundred Blade Arcs",
        "a_thousand_eps": "Thousand Dojo Sessions",
        "a_watching_ten": "Ten Paths Walked Simultaneously",
        "a_ptw_hoarder": "Dojo Training Backlog",
        "a_dropped_honesty": "Sheathed the Blade Early",
        "a_five_thousand_eps": "Five Thousand Wanders",
        "a_ten_completed": "Ten Roads Traveled",
        "a_fifty_completed": "Fifty Missions of Peace",
        "a_five_hundred_completed": "Five Hundred Acts of Peace",
        "a_mean_score_tracker": "Average Combat Rating",
        "a_unique_studios": "Allied Dojo Factions",
        "a_days_spent_watching": "Days Defending Meiji Peace",
        "a_all_status": "All Wanderer Statuses",
        "a_first_favorite": "First Comrade of the Dojo",
        "a_favorites_collector": "Bonds of the Kenshin-gumi",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Battōsai Flight",
        "a_marathon_runner": "Dojo-to-Dojo Marathon",
        "a_weekend_warrior": "Weekend Warrior Rurouni",
        "a_non_stop": "Relentless Meiji Advance",
        "a_one_more_episode": "One More Duel",
        "a_speed_run": "Hiten Mitsurugi Blitz",
        "a_double_feature": "Double Sword Strike",
        "a_triple_threat": "Triple Duel Takedown",
        "a_five_a_day": "Five Duels a Day",
        "a_back_to_back": "Back-to-Back Battles",
        "a_seasonal_binge": "Full Kyoto Arc Campaign",
        "a_cour_crusher": "Meiji District Crusher",
        "a_half_day_watch": "Half-Day Dojo Shift",
        "a_full_day_watch": "Full Day on the Dojo Road",
        "a_power_weekend": "Power Weekend Offensive",
        "a_binge_king": "Commander of Binge Wandering",
        "a_no_sleep": "All-Night Vigil at Kamiya Dojo",
        "a_entire_season": "Rapid Kyoto Campaign Clear",
        "a_seven_day_challenge": "Seven-Day Reclamation",
        "a_hundred_day_binge": "Hundred-Day Aizu Siege",
        "a_genre_binge": "Cross-Sword Style Training",
        "a_studio_binge": "Allied Dojo Binge",
        "a_season_sweep": "Season Sweep Operation",
        "a_forty_eight_hour": "Forty-Eight Hour Standoff",
        "a_ep_counter_day": "Daily Duel Count",
        "a_multi_series_binge": "Multi-Front Campaign",
        "a_midnight_binge": "Midnight Meiji Reconnaissance",
        "a_new_year_binge": "New Year's Battōsai Charge",

        // ── ANIME GENRES ──
        "a_genre_action": "Hiten Mitsurugi Action",
        "a_genre_adventure": "Road Beyond the Dojo",
        "a_genre_comedy": "Yahiko's Potato Moment",
        "a_genre_drama": "Kenshin's Vow of Peace",
        "a_genre_fantasy": "Succession Technique Mastered",
        "a_genre_horror": "Battōsai's Terror",
        "a_genre_mystery": "Cross-Scar Mystery",
        "a_genre_romance": "Heart of the Wanderer",
        "a_genre_scifi": "Meiji Technology",
        "a_genre_sol": "Life at Kamiya Dojo",
        "a_genre_sports": "Kendo Training Grounds",
        "a_genre_supernatural": "Battōsai's Aura",
        "a_genre_thriller": "Shishio Pursuit",
        "a_genre_mecha": "Meiji Cannon Artillery",
        "a_genre_music": "Call of the Rurouni",
        "a_genre_psychological": "Kenshin's Inner War",
        "a_genre_ecchi": "Hot Spring Episode Recruit",
        "a_genre_mahou_shoujo": "Sakura Wield Wielder",
        "a_tag_isekai": "Transported to Meiji Era",
        "a_tag_harem": "Kenshin-gumi Bonds",
        "a_tag_bl": "Comrades in the Dojo",
        "a_tag_gl": "Shield Sisters of Kamiya",
        "a_tag_historical": "Meiji Restoration History",
        "a_tag_military": "Meiji Military Discipline",
        "a_tag_school": "Kamiya Kasshin School",
        "a_tag_martial_arts": "Hiten Mitsurugi Ryu",
        "a_tag_vampire": "Battōsai Bloodline",
        "a_tag_samurai": "Meiji Swordsman Style",
        "a_tag_space": "Beyond the Meiji Horizon",
        "a_tag_parody": "Yahiko Cleaning Parody",
        "a_tag_idol": "Wings of Peace Idol",
        "a_tag_post_apocalyptic": "Post-Bakumatsu Era",
        "a_tag_cyberpunk": "Meiji Industrial Tech",
        "a_tag_shounen": "Dedicate Your Sakabato",
        "a_tag_seinen": "Harsh Reality of Meiji War",
        "a_tag_shoujo": "Kaoru's Devotion",
        "a_tag_josei": "Misao's Obsession",
        "a_tag_survival": "Survival in the Meiji Era",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Meiji Expedition Report",
        "a_mega_completionist": "Hitokiri-in-Chief",
        "a_completion_rate_50": "Halfway to Kyoto",
        "a_completion_rate_75": "Approaching Shishio's Lair",
        "a_completion_rate_90": "Succession Technique Unlocked",
        "a_no_drop": "No Wanderer Left Behind",
        "a_long_runner_complete": "Long Journey Endurance",
        "a_sequel_chain": "Operation Chain Duel",
        "a_clean_list": "Clean Dojo Record",
        "a_from_ptw": "Orders Received and Executed",
        "a_rewatch_master": "Memory Replay via Hiten",
        "a_short_complete": "Quick Skirmish Victory",
        "a_same_day_start_finish": "Same-Day Duel Elimination",
        "a_revival": "Revived by the Sakabato",
        "a_zero_to_hero": "Wanderer to Swordmaster",
        "a_five_genre_complete": "Five-Style Sword Mastery",
        "a_full_franchise": "Full Kenshin-gumi Dossier",
        "a_batch_complete": "Batch Mission Clear",
        "a_paused_to_done": "Returned from Wandering",
        "a_completion_spree": "Completion Sakabato Strike",
        "a_multi_rewatch": "Multi-Timeline via Battōsai",
        "a_dropped_recovery": "Recovered from Shishio's Grip",
        "a_ten_perfect_scores": "Ten Perfect Duel Scores",
        "a_seasonal_clear": "Seasonal Meiji Clear",
        "a_complete_genre_span": "All-Terrain Wanderer",
        "a_monthly_completions": "Monthly Mission Reports",
        "a_yearly_completions": "Yearly Meiji Campaign Victor",
        "a_rapid_complete": "Lightning Raid Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Kenshin-gumi Member",
        "a_studio_devotee": "Watsuki/Studio Deen Devotee",
        "a_rewatcher": "Rurouni Recon Rewatch",
        "a_triple_rewatch": "Triple Meiji Expedition Rewatch",
        "a_annual_tradition": "Annual Remembrance Day",
        "a_director_fan": "Director's Vision Follower",
        "a_voice_actor_fan": "Voice of the Wanderer",
        "a_ost_lover": "Heart of Sword!",
        "a_source_reader": "Watsuki's Original Texts",
        "a_waiting_weekly": "Weekly Signal Flare Wait",
        "a_childhood_revisit": "Return to Kamiya Dojo",
        "a_saga_tracker": "Saga of the Wanderer Tracker",
        "a_genre_loyalty": "Dojo Loyalty Badge",
        "a_decade_watcher": "Decade-Long Rurouni",
        "a_adaptation_hunter": "Adaptation Reconnaissance",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Dojo Duty",
        "a_perfect_attendance": "Perfect Formation Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Meiji Catalog",
        "a_franchise_collector": "Kenshin Universe Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Mastery Achieved",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Season Veteran",
        "a_format_diversity": "Diverse Tactical Formats",
        "a_year_dedication": "Year of Dedication to Peace",
        "a_season_dedication": "Season of Unwavering Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Known Territory",
        "a_studio_hopper": "Dojo Transfer",
        "a_tag_explorer": "Tag Reconnaissance Mission",
        "a_decade_hopper": "Time via Battōsai's Memories",
        "a_hidden_gem": "Hidden Reverse-Blade Secret",
        "a_popular_taste": "Popular Among Meiji Folk",
        "a_retro_appreciator": "Pre-Meiji Era Appreciator",
        "a_modern_viewer": "Modern Meiji Viewer",
        "a_cross_demographic": "Cross-Demographic Rurouni",
        "a_underdog_fan": "Underdog Wanderer Spirit",
        "a_variety_week": "Week of Varied Sword Styles",
        "a_foreign_cinema": "Foreign Intelligence Cinema",
        "a_classic_connoisseur": "Classic Bakumatsu Connoisseur",
        "a_every_season": "Every Season Deployed",
        "a_award_winner": "Medal of Peace",
        "a_niche_explorer": "Niche Territory Explorer",
        "a_global_anime": "Global Alliance Entry",
        "a_cult_classic": "Underground Cult Classic",
        "a_random_pick": "Random Mission Assignment",
        "a_new_genre_month": "New Terrain Monthly",
        "a_seasonal_completionist": "Seasonal Meiji Clear",
        "a_unpopular_opinion": "Unpopular Tactical Opinion",
        "a_top_rated_viewer": "Top-Rated Intel Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Operation Intel",
        "a_short_series_explorer": "Short Skirmish Explorer",
        "a_long_series_explorer": "Long Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Watch on the Dojo Road",
        "a_early_bird": "Dawn Patrol Rurouni",
        "a_lunch_break": "Kaoru's Lunch Break",
        "a_golden_hour": "Golden Hour Sakura",
        "a_four_am_club": "4 AM Meiji Sentry",
        "a_witching_hour": "Battōsai Witching Hour",
        "a_new_year_watch": "New Year's Oath to Peace",
        "a_midnight_premiere": "Midnight Deployment",
        "a_all_hours": "All-Hours Wanderer",
        "a_dawn_warrior": "Dawn Warrior of Meiji",
        "a_afternoon_delight": "Afternoon Dojo Drill",
        "a_prime_time": "Prime Time Engagement",
        "a_workday_watcher": "On-Duty Watcher",
        "a_sunday_marathon": "Sunday Expedition Marathon",
        "a_rainy_day": "Rainy Day in Edo",
        "a_morning_routine": "Morning Kamiya Formation",
        "a_night_shift": "Night Shift Dojo Guard",
        "a_twilight_zone": "Twilight Beyond the Meiji Gate",
        "a_seasonal_premier": "Season Premiere Sortie",
        "a_clock_collector": "Meiji Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge Operations",
        "a_late_night_regular": "Late Night Regular Patrol",
        "a_sunrise_watcher": "Sunrise Over Kyoto",
        "a_holiday_watcher": "Holiday Guard Duty",
        "a_every_day_of_week": "Every Day Deployed",
        "a_monthly_hours": "Monthly Duty Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Kenshin-gumi Formation",
        "a_party_host": "Dojo Commander",
        "a_social_butterfly": "Dojo Socialite",
        "a_group_binge": "Group Battōsai Volley",
        "a_party_regular": "Regular Sparring Partner",
        "a_sync_viewer": "Synchronized Hiten Maneuver",
        "a_commentator": "Battle Commentator",
        "a_party_marathon": "Marathon Dojo Run",
        "a_full_house": "Full Kenshin-gumi Assembled",
        "a_community_pillar": "Pillar of the Dojo",
        "a_watch_party_streak": "Consecutive Formation Streak",
        "a_diverse_party": "Diverse Kenshin-gumi Party",
        "a_late_night_party": "Late Night Dojo Party",
        "a_party_veteran": "Veteran Squad Leader",
        "a_genre_party": "Cross-Genre Formation",
        "a_weekly_party": "Weekly Comrades' Gathering",
        "a_silent_viewer": "Silent Saitō Observer",
        "a_recommendation_giver": "Commander's Recommendation",
        "a_party_completionist": "Party Operation Completionist",
        "a_social_scorer": "Social Combat Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Formation",
        "a_fibonacci": "Fibonacci Sword Sequence",
        "a_palindrome_day": "Palindrome Time Rift",
        "a_binary_day": "Binary Signal Flare Day",
        "a_full_moon": "Full Moon Battōsai Form",
        "a_leap_year": "Leap Year Time Skip",
        "a_time_traveler": "Attack Titan's Future Memory",
        "a_genre_clash": "Rurouni vs. Hitokiri Clash",
        "a_triple_seven": "Triple Seven Sword Stances",
        "a_thousand_complete": "Thousand Duels for Peace",
        "a_pi_episodes": "Pi Succession Calculation",
        "a_synchronicity": "Hiten Synchronicity",
        "a_world_record": "World Record Duel Kill",
        "a_nice": "Nice Slice Count",
        "a_power_level": "Battōsai Power Level",
        "a_answer_42": "The Answer to Kenshin's Vow",
        "a_square_number": "Perfect Dojo Formation",
        "a_prime_count": "Prime Number of Duels",
        "a_matching_date": "Matching Intel Date",
        "a_century_episode": "Century Episode Assault",
        "a_double_digits": "Double Digit Kills",
        "a_one_two_three": "Three Sacred Vows of Kenshin",
        "a_lucky_seven": "Seven Lucky Wanderers",
        "a_all_tens": "All Tens Dojo Score",
        "a_exact_hundred_eps": "Exact Hundred Engagements",
        "a_year_match_count": "Year Match Kill Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Wanderer",
        "a_movie_buff": "Kenshin Movie Operations",
        "a_ova_hunter": "OVA Tsuioku-hen Hunter",
        "a_ona_explorer": "ONA Scout Explorer",
        "a_special_watcher": "Special Episode Operative",
        "a_short_king": "Short Engagement King",
        "a_variety_pack": "All-Format Dojo",
        "a_film_festival": "Meiji Film Festival",
        "a_music_video": "Heart of Sword Collection",
        "a_tv_short": "Quick Recon Clip",
        "a_movie_marathon": "Movie Marathon Blitz",
        "a_double_length": "Double-Length Operation",
        "a_anthology": "Kenshin-gumi Anthology",
        "a_mini_series": "Mini Campaign Collection",
        "a_theatrical": "Theatrical Deployment",
        "a_format_master": "Format Master Wanderer",
        "a_long_movie": "Feature-Length Expedition",
        "a_back_catalog": "Back Catalog Dojo Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Tactical Formats",
        "a_episodic_master": "Episodic Campaign Master",
        "a_sequel_movie": "Sequel Operation Film",
        "a_recap_watcher": "Recap Briefing Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Patrol Streak",
        "a_mega_streak": "Mega Expedition Streak",
        "a_weekly_warrior": "Weekly Warrior of the Dojo",
        "a_monthly_watcher": "Monthly Dojo Duty",
        "a_comeback": "Return from the Wandering Road",
        "a_weekend_streak": "Weekend Duel Streak",
        "a_no_zero_days": "No Zero Days on the Road",
        "a_iron_will": "Iron Will of the Rurouni",
        "a_habit_formed": "Dojo Regimen Formed",
        "a_consistent_pace": "Consistent March Forward",
        "a_year_long": "Year-Long Meiji Campaign",
        "a_double_streak": "Double Streak Assault",
        "a_streak_recovery": "Dojo Recovery",
        "a_daily_minimum": "Daily Minimum Duty",
        "a_winter_streak": "Winter Campaign Streak",
        "a_summer_streak": "Summer Offensive Streak",
        "a_morning_streak": "Morning Drill Streak",
        "a_night_streak": "Night Patrol Streak",
        "a_unbreakable": "Unbreakable Will for Peace",
        "a_eternal_flame": "Eternal Flame of the Rurouni",
        "a_completion_streak": "Completion Mission Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Episode Offensive",
        "a_genre_streak": "Genre Streak Sortie",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Week of Service",

        // ── ANIME SCORING ──
        "a_critic": "Saitō Tribunal Judge",
        "a_perfect_ten": "Perfect 10 Duel Rating",
        "a_harsh_critic": "Saitō's Harsh Standards",
        "a_fair_judge": "Kenshin's Fair Assessment",
        "a_generous_spirit": "Generous Comrade",
        "a_score_all": "Full Roster Evaluation",
        "a_wide_range": "Wide Range Duel Assessment",
        "a_controversial": "Controversial Command Decision",
        "a_consistent_scorer": "Consistent Evaluator",
        "a_score_sniper": "Precision Sakabato Sniper",
        "a_evolving_taste": "Evolving Strategy",
        "a_bell_curve": "Bell Curve of Duel Scores",
        "a_picky_watcher": "Selective Dojo Commander",
        "a_100_rated": "Century of Evaluations",
        "a_500_rated": "Five Hundred Field Reports",
        "a_mediocre_majority": "Middle Ground Strategist",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Variable Duel Ratings",
        "a_masterpiece_hunter": "Masterpiece Intel Hunter",
        "a_contrarian": "Contrarian Wanderer",
        "a_optimist": "Optimist Despite the Odds",
        "a_score_distributor": "Score Distributor General",
        "a_genre_critic": "Genre Tactical Critic",
        "a_mean_above_8": "Elite Combat Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow for Peace",
        "a_valentines_weeb": "Valentine's Dedication",
        "a_pi_day": "Pi Day Succession Calc",
        "a_april_fools": "April Fools Prank",
        "a_international_anime_day": "International Wanderer Day",
        "a_star_wars_day": "Meiji Empire Day",
        "a_summer_solstice": "Summer Solstice Expedition",
        "a_tanabata": "Tanabata Wish for Peace",
        "a_friday_13th": "Friday the 13th Battōsai Attack",
        "a_halloween_spirit": "Halloween Hitokiri Horror",
        "a_thanksgiving_binge": "Thanksgiving Harvest Feast",
        "a_christmas_special": "Midwinter Festival Special",
        "a_new_years_eve": "New Year's Eve Final Duel",
        "a_birthday_watch": "Birthday Dojo Watch",
        "a_holiday_marathon": "Holiday Campaign Marathon",
        "a_independence_day": "Meiji Independence Day",
        "a_culture_day": "Meiji Culture Day",
        "a_spring_equinox": "Spring Sakura Advance",
        "a_earth_day": "Protect This Meiji World Day",
        "a_labor_day": "Dojo Labor Day",
        "a_winter_solstice": "Winter Solstice on the Road",
        "a_anime_birthday": "Anime Anniversary Celebration",
        "a_every_holiday": "Every Holiday Wanderer",
        "a_consecutive_holidays": "Consecutive Holiday Deployments",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Sword Power Awakened",
        "a_meta_collector": "Kenshin-gumi Badge Collector",
        "a_meta_category_starter": "Category Initiation Rite",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Hitokiri-Class Rank",
        "a_meta_xp_earner": "XP from Duel Kills",
        "a_meta_difficulty_easy": "Easy Training Exercise",
        "a_meta_difficulty_hard": "Legendary Difficulty: Shishio",
        "a_meta_unlock_spree": "Unlock Spree Sakabato",
        "a_meta_completionist": "Meta Completionist Commander",
        "a_meta_diverse": "Diverse Dojo Portfolio",
        "a_meta_dominator": "Meta Dominator of Duels",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter of Wandering",
        "m_chapter_counter": "Chapter Duel Counter",
        "m_chapter_titan": "Chapter Battōsai Assault",
        "m_reading_hours": "Hours Studying Sword Texts",
        "m_reading_time_lord": "Hiten Mitsurugi's Reading Memory",
        "m_manga_collector": "Dojo Archive Collector",
        "m_library_legend": "Kaoru's Scroll Book Legend",
        "m_first_complete": "First Manga Expedition Done",
        "m_hundred_club": "Hundred-Chapter Dojo Club",
        "m_first_day": "First Day of Reading Training",
        "m_first_rating": "First Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Intel",
        "m_volume_collector": "Volume Stockpile Collector",
        "m_year_explorer": "Year of Manga Exploration",
        "m_century_reader": "Century-Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Chapters Consumed",
        "m_thousand_ch": "Thousand-Chapter Campaign",
        "m_reading_ten": "Ten Manuscripts at Once",
        "m_ptr_hoarder": "Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Tactical Retreat",
        "m_season_reader": "Seasonal Reading Rotation",
        "m_active_reader": "Active Field Reader",
        "m_five_thousand_ch": "Five Thousand Chapters Deep",
        "m_ten_completed": "Ten Manga Campaigns Complete",
        "m_fifty_completed": "Fifty Manga Missions Done",
        "m_five_hundred_completed": "Five Hundred Manga Victories",
        "m_mean_score_tracker": "Average Manuscript Rating",
        "m_unique_authors": "Unique Author Encounters",
        "m_all_status": "All Reading Statuses",
        "m_first_favorite": "First Manga Comrade Bond",
        "m_favorites_collector": "Manga Favorites Arsenal",
        "m_days_spent_reading": "Days in the Reading Dojo",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading Advance",
        "m_marathon_reader": "Dojo-to-Dojo Reading Marathon",
        "m_weekend_reader": "Weekend Dojo Reading",
        "m_non_stop_reading": "Non-Stop Page Turning",
        "m_one_more_chapter": "One More Chapter Charge",
        "m_speed_read": "Hiten Speed Read",
        "m_double_story": "Double Manuscript Feature",
        "m_triple_read": "Triple Reading Assault",
        "m_five_a_day": "Five Reads a Day",
        "m_chapter_chain": "Chapter Chain Offensive",
        "m_volume_binge": "Volume Binge Bombardment",
        "m_power_reader": "Power Reader Scout",
        "m_half_day_read": "Half-Day Archive Dive",
        "m_full_day_read": "Full-Day Manuscript Study",
        "m_power_weekend": "Power Weekend Reading",
        "m_binge_king": "King of the Reading Dojo",
        "m_no_sleep_read": "All-Night Dojo Reading",
        "m_full_series_rush": "Full Series Rush Attack",
        "m_seven_day_challenge": "Seven-Day Intel Gathering",
        "m_hundred_day_read": "Hundred-Day Reading Siege",
        "m_volume_rush": "Volume Rush Deployment",
        "m_series_sweep": "Series Sweep Operation",
        "m_genre_binge": "Cross-Genre Maneuver",
        "m_author_binge": "Author Focused Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Kill Count",
        "m_multi_series_binge": "Multi-Series Reading Front",
        "m_midnight_binge": "Midnight Archive Session",
        "m_new_year_binge": "New Year's Reading Charge",
        "m_forty_eight_hour": "Forty-Eight Hour Reading Siege",
        "m_oneshot_binge": "Oneshot Blitz Attack",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Manuscript Specialist",
        "m_genre_adventure": "Adventure Beyond the Dojo",
        "m_genre_comedy": "Comedy in the Kamiya Dojo",
        "m_genre_drama": "Drama of the Wanderer's Legacy",
        "m_genre_fantasy": "Fantasy of the Succession Technique",
        "m_genre_horror": "Battōsai Horror Manuscript",
        "m_genre_mystery": "Mystery of the Cross-Scar",
        "m_genre_romance": "Romance Under the Sakura",
        "m_genre_scifi": "Sci-Fi Meiji Engineering",
        "m_genre_sol": "Slice of Life in the Dojo",
        "m_genre_sports": "Kendo Training Sports",
        "m_genre_supernatural": "Supernatural Sword Powers",
        "m_genre_thriller": "Thriller Intelligence Report",
        "m_genre_psychological": "Psychological Warfare Reader",
        "m_genre_isekai": "Isekai Beyond the Meiji Gate",
        "m_genre_shounen": "Shounen Heart of a Wanderer",
        "m_genre_ecchi": "Hot Springs Chapter",
        "m_genre_mahou_shoujo": "Power of the Sakabato",
        "m_genre_mecha": "Anti-Shogunate Weapon Blueprints",
        "m_genre_music": "Meiji Folk Songs",
        "m_tag_isekai_new": "New World Beyond the Sea",
        "m_tag_harem": "Kenshin-gumi Bonds Manga",
        "m_tag_bl": "Brothers in the Dojo Manga",
        "m_tag_gl": "Shield Sisters Manga",
        "m_tag_historical": "Meiji History Manga",
        "m_tag_military": "Military Operations Manga",
        "m_tag_school": "Kamiya Kasshin Academy Manga",
        "m_tag_martial_arts": "Hiten Mitsurugi Manual",
        "m_tag_vampire": "Battōsai Blood Manga",
        "m_tag_samurai": "Blade Master Manga",
        "m_tag_space": "Beyond the Horizon Manga",
        "m_tag_parody": "Chibi Dojo Manga",
        "m_tag_idol": "Wings of Peace Manga",
        "m_tag_post_apocalyptic": "Post-Bakumatsu Manga",
        "m_tag_cyberpunk": "Meiji Technology Manga",
        "m_tag_shoujo": "Kaoru's Story Manga",
        "m_tag_survival": "Meiji Survival Manga",
        "m_tag_cooking": "Dojo Rations Cookbook",
        "m_tag_medical": "Field Medic Manga",
        "m_tag_villainess": "Warrior Candidate Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Campaign Completionist",
        "m_mega_completionist": "Supreme Manga Commander",
        "m_completion_rate_50": "Halfway to the Truth",
        "m_completion_rate_75": "Approaching Kyoto",
        "m_completion_rate_90": "Final Chapter Approaching",
        "m_no_drop": "No Manuscript Abandoned",
        "m_long_runner_complete": "Long Series Endurance Medal",
        "m_sequel_chain": "Sequel Chain of Command",
        "m_clean_list": "Clean Reading Record",
        "m_from_ptr": "Orders Received: Read",
        "m_reread_master": "Memory Replay Reread",
        "m_oneshot_complete": "Oneshot Mission Specialist",
        "m_same_day_start_finish": "Same-Day Reading Blitz",
        "m_revival": "Revival Through the Dojo",
        "m_zero_to_hundred": "Wanderer to Scholar",
        "m_five_genre_complete": "Five-Genre Mastery",
        "m_full_collection": "Full Archive Collection",
        "m_batch_complete": "Batch Clearance",
        "m_paused_to_done": "Back from Wandering",
        "m_completion_spree": "Completion Barrage",
        "m_format_completionist": "Format Completion Badge",
        "m_catch_up": "Caught Up with Serialization",
        "m_multi_reread": "Multi-Pass Reread",
        "m_dropped_recovery": "Recovered from the Road",
        "m_ten_perfect_scores": "Ten Perfect Manuscript Scores",
        "m_complete_genre_span": "All-Genre Reading Scout",
        "m_monthly_completions": "Monthly Manuscript Victories",
        "m_yearly_completions": "Yearly Reading Campaign",
        "m_rapid_complete": "Rapid Intel Processing",
        "m_author_complete": "Author's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Dojo Reader",
        "m_mangaka_lover": "Watsuki Devotee",
        "m_rereader": "Scout Rereader",
        "m_triple_reread": "Triple Reread Expedition",
        "m_annual_reread": "Annual Remembrance Reread",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Artist Appreciation Medal",
        "m_adaptation_compare": "Manga vs Anime Compare",
        "m_source_material_fan": "Source Material Scout",
        "m_waiting_weekly": "Weekly Chapter Signal Wait",
        "m_classic_reader": "Classic Manuscript Reader",
        "m_saga_reader": "Saga of the Wanderer Reader",
        "m_genre_loyalty": "Genre Loyalty Medal",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "Light Novel Adaptation Intel",
        "m_original_work": "Original Manga Work",
        "m_long_commitment": "Long-Term Reading Commitment",
        "m_up_to_date": "Up-to-Date with the Front Lines",
        "m_favorite_mangaka": "Favorite Mangaka Honored",
        "m_complete_portfolio": "Complete Reading Portfolio",
        "m_franchise_collector": "Kenshin Franchise Collector",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Mastery Earned",
        "m_multi_series_author": "Multi-Series Author Fan",
        "m_format_diversity": "Diverse Reading Formats",
        "m_year_dedication": "Year of Dedicated Reading",
        "m_ongoing_follower": "Ongoing Series Follower",
        "m_genre_loyalty_50": "Fifty Genre Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Territory Scout",
        "m_publisher_hopper": "Publisher Transfer",
        "m_tag_explorer": "Manga Tag Recon Mission",
        "m_decade_hopper": "Decade-Hopping via Battōsai",
        "m_hidden_gem": "Hidden Sakabato Gem",
        "m_popular_taste": "Popular Among Meiji Folk",
        "m_retro_reader": "Retro Manuscript Appreciator",
        "m_modern_reader": "Modern Era Reader",
        "m_cross_demographic": "Cross-Demographic Scout",
        "m_underdog_fan": "Underdog Wanderer Fan",
        "m_variety_week": "Week of Varied Readings",
        "m_manhwa_reader": "Manhwa Intelligence Reader",
        "m_manhua_reader": "Manhua Intelligence Reader",
        "m_classic_connoisseur": "Classic Warfare Manuscript",
        "m_award_winner": "Medal-Winning Manuscript",
        "m_niche_explorer": "Niche Territory Reader",
        "m_world_manga": "World Manga Intel",
        "m_cult_classic": "Cult Classic Underground",
        "m_random_pick": "Random Reading Assignment",
        "m_new_genre_month": "New Genre Deployment Monthly",
        "m_year_completionist": "Year Reading Completionist",
        "m_unpopular_opinion": "Unpopular Tactical Opinion",
        "m_top_rated_reader": "Top-Rated Intel Source",
        "m_source_variety": "Source Material Variety",
        "m_low_score_brave": "Brave Low-Score Reader",
        "m_short_manga_explorer": "Short Manga Skirmish",
        "m_long_manga_explorer": "Long Campaign Manuscript",
        "m_serialization_explorer": "Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Dojo Reader",
        "m_early_bird": "Dawn Patrol Reader",
        "m_lunch_reader": "Kaoru's Lunch Reader",
        "m_commute_reader": "Travel to Meiji HQ Reader",
        "m_four_am_club": "4 AM Sentry Reader",
        "m_new_year_read": "New Year's Reading Oath",
        "m_all_hours": "All-Hours Archive Access",
        "m_prime_time_reader": "Prime Time Manuscript",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Reading Marathon",
        "m_morning_routine": "Morning Formation Reading",
        "m_night_shift_reader": "Night Shift Reader",
        "m_seasonal_premier_read": "New Release Intel",
        "m_clock_collector": "Meiji Clock Reading Time",
        "m_late_night_horror": "Midnight Battōsai Horror Read",
        "m_afternoon_reader": "Afternoon Dojo Reading",
        "m_golden_hour_reader": "Golden Hour Reading",
        "m_dawn_reader": "Dawn Reading Scout",
        "m_twilight_reader": "Twilight Dojo Reading",
        "m_midnight_start": "Midnight Reading Mission",
        "m_weekend_binge_hours": "Weekend Binge Reading Ops",
        "m_late_night_regular": "Late Night Regular Reader",
        "m_sunrise_reader": "Sunrise Over Kyoto Reader",
        "m_every_day_of_week": "Every Day Reading Duty",
        "m_monthly_hours": "Monthly Reading Hours Logged",
        "m_bedtime_reader": "Bedtime Dojo Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Watsuki Art Appreciator",
        "m_webtoon_reader": "Webtoon Intelligence",
        "m_full_color": "Full Color Manuscript",
        "m_doujin_reader": "Underground Doujin Reader",
        "m_anthology_reader": "Anthology Collection Reader",
        "m_adaptation_reader": "Adaptation Study Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Comedy Shorts",
        "m_oneshot_reader": "Oneshot Mission Reader",
        "m_format_variety": "Format Tactical Variety",
        "m_light_novel_reader": "Light Novel Intel Reader",
        "m_novel_reader": "Novel Archive Reader",
        "m_visual_storyteller": "Visual Battle Narrator",
        "m_colored_classic": "Colored Classic Manuscript",
        "m_webcomic_fan": "Webcomic Underground Fan",
        "m_manga_to_anime": "Manga to Anime Comparison",
        "m_seinen_reader": "Seinen Meiji Reader",
        "m_josei_reader": "Josei Perspective Reader",
        "m_award_winning_art": "Medal-Winning Artwork",
        "m_debut_work": "Debut Manuscript",
        "m_vertical_scroll": "Vertical Scroll Intel",
        "m_traditional_format": "Traditional Format Reader",
        "m_cross_media": "Cross-Media Intelligence",
        "m_spinoff_reader": "Spinoff Mission Reader",
        "m_remake_reader": "Remake Reading Assignment",
        "m_collaboration_reader": "Joint Operation Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Reading Patrol Streak",
        "m_mega_streak": "Mega Reading Campaign Streak",
        "m_weekly_warrior": "Weekly Warrior Reader",
        "m_monthly_reader": "Monthly Dojo Reader",
        "m_comeback": "Reader's Return from the Road",
        "m_weekend_streak": "Weekend Reading Streak",
        "m_no_zero_days": "No Zero Reading Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Regimen Formed",
        "m_consistent_pace": "Consistent Reading Advance",
        "m_year_long": "Year-Long Reading Campaign",
        "m_double_streak": "Double Reading Streak",
        "m_streak_recovery": "Reading Streak Recovery",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Reading Campaign",
        "m_summer_streak": "Summer Reading Offensive",
        "m_morning_streak": "Morning Reading Formation",
        "m_night_streak": "Night Reading Patrol",
        "m_unbreakable": "Unbreakable Reading Will",
        "m_eternal_flame": "Eternal Flame of Knowledge",
        "m_chapter_a_day": "Chapter a Day Discipline",
        "m_genre_streak": "Genre Reading Streak",
        "m_completion_streak": "Completion Reading Chain",
        "m_rating_streak": "Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Dedication Streak",
        "m_perfect_week_manga": "Perfect Reading Week",
        "m_diverse_streak": "Diverse Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Meiji Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Manuscript",
        "m_harsh_critic": "Saitō's Reading Standards",
        "m_fair_judge": "Kenshin's Fair Review",
        "m_generous_spirit": "Generous Reader Spirit",
        "m_score_all": "Full Manuscript Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Reading Opinion",
        "m_consistent_scorer": "Consistent Manuscript Scorer",
        "m_score_sniper": "Precision Score Sniper",
        "m_evolving_taste": "Evolving Reading Taste",
        "m_bell_curve": "Bell Curve of Scores",
        "m_picky_reader": "Selective Reading Commander",
        "m_100_rated": "Century of Ratings Filed",
        "m_500_rated": "Five Hundred Rating Reports",
        "m_mediocre_majority": "Middle Ground Reader",
        "m_rating_spree": "Rating Barrage Filed",
        "m_score_variance": "Variable Manuscript Scores",
        "m_binge_rater": "Binge Rating Session",
        "m_reread_rerate": "Reread and Re-Rate Intel",
        "m_masterpiece_hunter": "Masterpiece Manuscript Hunter",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimistic Reader Scout",
        "m_score_distributor": "Score Distributor General",
        "m_genre_critic": "Genre Reading Critic",
        "m_mean_above_8": "Elite Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Reading Vow",
        "m_valentines_read": "Valentine's Reading Bond",
        "m_pi_day": "Pi Day Chapter Count",
        "m_april_fools": "April Fools Chibi Dojo",
        "m_international_manga_day": "International Manga Day",
        "m_free_comic_day": "Free Comic Dojo Day",
        "m_summer_solstice": "Summer Solstice Reading",
        "m_tanabata": "Tanabata Reading Wish",
        "m_friday_13th": "Friday 13th Battōsai Manuscript",
        "m_halloween_read": "Halloween Horror Reading",
        "m_thanksgiving_binge": "Thanksgiving Reading Feast",
        "m_christmas_read": "Midwinter Festival Reading",
        "m_new_years_eve": "New Year's Eve Final Read",
        "m_birthday_read": "Birthday Reading Gift",
        "m_holiday_marathon": "Holiday Reading Marathon",
        "m_independence_day": "Meiji Independence Reading",
        "m_culture_day": "Culture Day Manuscript",
        "m_spring_equinox": "Spring Equinox Reading",
        "m_earth_day": "Earth Day Conservation Read",
        "m_labor_day": "Dojo Labor Reading Day",
        "m_winter_solstice": "Winter Solstice Reading",
        "m_manga_birthday": "Manga Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Reader",
        "m_consecutive_holidays": "Consecutive Holiday Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Milestone",
        "m_fibonacci": "Fibonacci Chapter Pattern",
        "m_palindrome_day": "Palindrome Reading Day",
        "m_binary_day": "Binary Signal Reading Day",
        "m_full_moon_read": "Full Moon Battōsai Read",
        "m_leap_year_read": "Leap Year Reading",
        "m_triple_seven": "Triple Seven Dojo Walls",
        "m_thousand_complete": "Thousand Manga Victories",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Battōsai-Level Chapters",
        "m_answer_42": "Answer to Kenshin's Reading",
        "m_square_number": "Perfect Formation Chapters",
        "m_prime_count": "Prime Chapter Count",
        "m_matching_date": "Matching Intel Reading Date",
        "m_century_chapter": "Century Chapter Milestone",
        "m_pi_chapters": "Pi Chapter Calculation",
        "m_synchronicity": "Hiten Reading Synchronicity",
        "m_world_record": "World Record Chapter Count",
        "m_genre_clash": "Genre Clash Reading",
        "m_time_traveler": "Time-Traveling Reader",
        "m_double_digits": "Double Digit Milestone",
        "m_one_two_three": "Three Vows One Two Three",
        "m_lucky_seven": "Seven Lucky Chapters",
        "m_exact_hundred_ch": "Exact Hundred Chapters Read",
        "m_year_match_count": "Year Match Chapter Count",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Manhwa Format Reader",
        "m_manhua_format": "Manhua Format Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Operative",
        "m_doujin_format": "Doujin Format Reader",
        "m_novel_format": "Novel Format Reader",
        "m_format_master_manga": "Format Master Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Reading Power Unlocked",
        "m_meta_collector": "Reading Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Reading Rank",
        "m_meta_xp_earner": "XP from Reading Intel",
        "m_meta_difficulty_easy": "Easy Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Manuscript Challenge",
        "m_meta_unlock_spree": "Reading Unlock Barrage",
        "m_meta_completionist": "Meta Reading Completionist",
        "m_meta_diverse": "Diverse Reading Portfolio",
        "m_meta_dominator": "Meta Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060403",
        primary: "#cc1100",
        secondary: "#a00d00",
        accent: "#ffaab0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        sakura_petals: { label: "Sakura Petals", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        sword_sparks: { label: "Sword Sparks", maxCount: 10, defaultEnabled: true, defaultIntensity: 60 },
        battousai_aura: { label: "Battōsai Aura", maxCount: 6, defaultEnabled: true, defaultIntensity: 45 },
        meiji_ink: { label: "Meiji Ink", maxCount: 8, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Wandering Swordsman",
        5:   "Kamiya Dojo Guest",
        15:  "Meiji Defender",
        30:  "Cross-Scar Recognized",
        45:  "Battōsai Rumored",
        60:  "Shishio's Rival",
        80:  "Succession Technique",
        100: "The Man Who Doesn't Kill",
    },
}
