import { AnimeThemeConfig } from "./types"
import { GiDesert, GiLightningBow, GiGooExplosion, GiFist, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiRadarDish } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const sCryEdTheme: AnimeThemeConfig = {
    id: "s-cry-ed",
    displayName: "s-CRY-ed",
    description: "In the Lost Ground — a region cut off from mainland Japan — people called Alter users manifest physical manifestations of their psyche. Kazuma and Ryuho clash in an explosive battle of wills.",
    fontFamily: "'Exo 2', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Exo+2:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 170 110",
        "--color-brand-300": "245 138 55",
        "--color-brand-400": "228 105 8",
        "--color-brand-500": "204 76 0",
        "--color-brand-600": "166 58 0",
        "--color-brand-700": "128 42 0",
        "--color-brand-800": "90 28 0",
        "--color-brand-900": "54 16 0",
        "--color-brand-950": "30 8 0",
        "--brand": "204 76 0",
        "--background": "#060200",
        "--paper": "#0e0600",
        "--color-gray-950": "6 2 0",
        "--color-gray-900": "14 6 0",
        "--color-gray-800": "28 12 4",
        "--color-gray-700": "46 22 8",
        "--color-gray-600": "72 38 16",
        "--color-gray-500": "110 64 32",
        "--color-gray-400": "155 102 65",
        "--color-gray-300": "192 142 105",
        "--color-gray-200": "218 178 148",
        "--color-gray-100": "234 208 184",
        "--color-gray-50": "246 236 224",
    },
    sidebarOverrides: {
        "home": { icon: GiDesert, label: "Lost Ground" },
        "schedule": { icon: GiAlarmClock, label: "Battle Schedule" },
        "manga": { icon: LuBookOpen, label: "Alter Files" },
        "lists": { icon: GiFist, label: "Alter Users" },
        "discover": { icon: GiBullseye, label: "Lost Ground Recon" },
        "torrent-list": { icon: GiGooExplosion, label: "Alter Cache" },
        "debrid": { icon: GiLightningBow, label: "Alter Power" },
        "unmatched": { icon: GiRadarDish, label: "Unknown Alters" },
        "enmasse": { icon: GiResize, label: "HOLD Ops" },
        "scan-summaries": { icon: TbReportSearch, label: "Incident Reports" },
        "auto-downloader": { icon: LuRss, label: "HOLD Feed" },
        "community": { icon: GiFist, label: "Alter Community" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Alter Alerts" },
        "achievements": { icon: GiTrophy, label: "Battle Trophies" },
        "milestones": { icon: LuFlag, label: "Alter Goals" },
        "theme-manager": { icon: GiPalette, label: "Alter Colors" },
        "extensions": { icon: BiExtension, label: "Alter Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Lost Ground Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Alter Settings" },
    },
    achievementNames: {
        "a_first_episode": "Alter Awakened",
        "a_first_complete": "Final Clash",
        "a_hundred_club": "Hundred Battles",
        "a_time_lord": "Alter Veteran",
        "a_anime_collector": "Alter Cache",
        "a_library_legend": "Lost Ground Archives",
        "a_binge_king": "Battle Marathon",
        "a_no_sleep": "All-Night Fight",
        "a_marathon_runner": "Desert Run",
        "a_speed_run": "Shell Bullet Speed",
        "a_completionist": "Lost Ground Cleared",
        "a_mega_completionist": "Scryed Master",
        "a_loyal_fan": "Kazuma's Spirit",
        "a_rewatcher": "Battle Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Alter Combat",
        "a_genre_adventure": "Lost Ground Journey",
        "a_genre_comedy": "Beach Episodes",
        "a_genre_drama": "Rival Drama",
        "a_genre_fantasy": "Alter World",
        "a_genre_horror": "HOLD Terror",
        "a_genre_romance": "Kanami's Light",
        "a_genre_scifi": "Alter Science",
        "a_genre_supernatural": "Alter Power",
        "a_genre_psychological": "Rival Conflict",
        "a_genre_mecha": "None Here",
        "a_critic": "Battle Judge",
        "a_perfect_ten": "Shell Bullet Perfect",
        "a_harsh_critic": "Strict Review",
        "a_daily_streak": "Daily Battle",
        "a_mega_streak": "Endless Fighting",
        "a_year_long": "Year of Alters",
        "a_iron_will": "Kazuma's Will",
        "a_hidden_gem": "Scryed Gem",
        "a_cult_classic": "Sunrise Classic",
        "a_classic_connoisseur": "2001 Fan",
        "a_new_years_resolution": "New Battle",
        "a_christmas_special": "Holiday Fight",
        "a_meta_tier_max": "Ultimate Alter",
        "a_meta_completionist": "Complete Archive",
        "a_sequel_chain": "None",
        "a_zero_to_hero": "Outlaw to Hero",
        "a_night_owl": "Desert Night",
        "a_early_bird": "Dawn Battle",
        "m_first_chapter": "First Alter",
        "m_first_complete": "Arc Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Alter Marathon",
        "m_completionist": "Full Series",
        "m_mega_completionist": "Scryed Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Battle Revisit",
        "m_genre_action": "Combat Chapter",
        "m_genre_adventure": "Desert Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Alter Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_drama": "Clash Chapter",
        "m_genre_scifi": "Tech Chapter",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Scryed Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Alter Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Fighter Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Sunrise Classic",
        "m_mangaka_lover": "Author Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Alter Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Desert Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060200",
        primary: "#cc4c00",
        secondary: "#863000",
        accent: "#2080d0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/s-cry-ed.jpg",
    particleColor: "#f07030",
    backgroundDim: 0.38,
    backgroundBlur: 20,
    particleTypes: {
        alter_shards: { label: "Alter Shards", maxCount: 15, defaultEnabled: true, defaultIntensity: 65 },
        dust: { label: "Desert Dust", maxCount: 20, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1: "Lost Ground Dweller",
        5: "Kazuma",
        15: "Alter User",
        30: "Shell Bullet",
        50: "HOLD Rival",
        75: "Ryuho's Equal",
        100: "Alter Legend",
    },
}
