import { AnimeThemeConfig } from "./types"
import { GiArmorVest, GiShield, GiGoldBar, GiLightningBow, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiCrown } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const saintSeiyaTheme: AnimeThemeConfig = {
    id: "saint-seiya",
    displayName: "Saint Seiya",
    description: "The Bronze Saints fight for the goddess Athena in divine armor forged from the stars — their Cosmo burns to absolute zero and then beyond, smashing the speed of light.",
    fontFamily: "'Cinzel Decorative', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 220 130",
        "--color-brand-300": "248 195 70",
        "--color-brand-400": "235 165 15",
        "--color-brand-500": "215 135 0",
        "--color-brand-600": "178 108 0",
        "--color-brand-700": "140 82 0",
        "--color-brand-800": "100 58 0",
        "--color-brand-900": "60 34 0",
        "--color-brand-950": "35 19 0",
        "--brand": "215 135 0",
        "--background": "#060504",
        "--paper": "#100c08",
        "--color-gray-950": "6 5 4",
        "--color-gray-900": "14 12 9",
        "--color-gray-800": "26 22 17",
        "--color-gray-700": "44 38 30",
        "--color-gray-600": "68 58 46",
        "--color-gray-500": "105 92 74",
        "--color-gray-400": "148 132 110",
        "--color-gray-300": "186 172 150",
        "--color-gray-200": "214 202 182",
        "--color-gray-100": "232 224 210",
        "--color-gray-50": "246 242 234",
    },
    sidebarOverrides: {
        "home": { icon: GiArmorVest, label: "Sanctuary" },
        "schedule": { icon: GiAlarmClock, label: "Battle Schedule" },
        "manga": { icon: LuBookOpen, label: "Sacred Texts" },
        "lists": { icon: GiShield, label: "Saint Registry" },
        "discover": { icon: GiBullseye, label: "Cloth Scouting" },
        "torrent-list": { icon: GiGoldBar, label: "Cloth Cache" },
        "debrid": { icon: GiLightningBow, label: "Cosmo Energy" },
        "unmatched": { icon: GiCrown, label: "Unknown Saints" },
        "enmasse": { icon: GiResize, label: "Army Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Athena's Voice" },
        "community": { icon: GiArmorVest, label: "Bronze Saints" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Cosmo Pulse" },
        "achievements": { icon: GiTrophy, label: "Saint Medals" },
        "milestones": { icon: LuFlag, label: "Cloth Goals" },
        "theme-manager": { icon: GiPalette, label: "Cloth Colors" },
        "extensions": { icon: BiExtension, label: "Cloth Upgrades" },
        "sync": { icon: IoCloudOfflineOutline, label: "Sanctuary Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Cosmo Settings" },
    },
    achievementNames: {
        "a_first_episode": "Cloth Awakened",
        "a_first_complete": "Athena Saved",
        "a_hundred_club": "Hundred Battles",
        "a_time_lord": "Gold Saint",
        "a_anime_collector": "Cloth Collection",
        "a_library_legend": "Sacred Archives",
        "a_binge_king": "Cosmo Marathon",
        "a_no_sleep": "All-Night Battle",
        "a_marathon_runner": "Sanctuary Run",
        "a_speed_run": "Light Speed Punch",
        "a_completionist": "Sanctuary Cleared",
        "a_mega_completionist": "Kurumada Master",
        "a_loyal_fan": "Seiya's Ally",
        "a_rewatcher": "Return to Sanctuary",
        "a_decade_watcher": "Decade Saint",
        "a_genre_action": "Cosmo Combat",
        "a_genre_adventure": "World Journey",
        "a_genre_comedy": "Bronze Crew",
        "a_genre_drama": "Saint's Sacrifice",
        "a_genre_fantasy": "Olympian World",
        "a_genre_horror": "Gold Saint Fear",
        "a_genre_romance": "Athena's Love",
        "a_genre_scifi": "Cosmo Science",
        "a_genre_supernatural": "Divine Cosmos",
        "a_genre_psychological": "Saint's Will",
        "a_genre_mecha": "Cloth Machine",
        "a_critic": "Cloth Judge",
        "a_perfect_ten": "Seventh Sense",
        "a_harsh_critic": "Strict Judge",
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Eternal Cosmo",
        "a_year_long": "Year of Battles",
        "a_iron_will": "Saint's Will",
        "a_hidden_gem": "Legendary Cloth",
        "a_cult_classic": "Kurumada Classic",
        "a_classic_connoisseur": "86 Classic Fan",
        "a_new_years_resolution": "New Year Battle",
        "a_christmas_special": "Winter Cosmo",
        "a_meta_tier_max": "Gold Saint Level",
        "a_meta_completionist": "Complete Cloths",
        "a_sequel_chain": "Hades Sequel",
        "a_zero_to_hero": "Orphan to Saint",
        "a_night_owl": "Night Battle",
        "a_early_bird": "Dawn Training",
        "m_first_chapter": "First Clash",
        "m_first_complete": "Arc Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Cosmo Marathon",
        "m_completionist": "Full Series",
        "m_mega_completionist": "Gold Master",
        "m_loyal_reader": "Bronze Reader",
        "m_rereader": "Cloth Revisit",
        "m_genre_action": "Combat Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Athena Chapter",
        "m_genre_fantasy": "Olympus Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_drama": "Sacrifice Chapter",
        "m_genre_scifi": "Cosmo Chapter",
        "m_genre_supernatural": "Divine Chapter",
        "m_genre_psychological": "Will Chapter",
        "m_critic": "Saint Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Clash",
        "m_mega_streak": "Unbroken Cosmo",
        "m_year_long": "Year Reading",
        "m_iron_will": "Saint's Iron",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Battle",
        "m_mangaka_lover": "Kurumada Fan",
        "m_source_material_fan": "Original Reader",
        "m_meta_tier_max": "Complete Arsenal",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Cloth Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060504",
        primary: "#d78700",
        secondary: "#8c5200",
        accent: "#7090d8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/saint-seiya.jpg",
    particleColor: "#f0c040",
    backgroundDim: 0.38,
    backgroundBlur: 22,
    particleTypes: {
        cosmo_sparks: { label: "Cosmo Sparks", maxCount: 20, defaultEnabled: true, defaultIntensity: 65 },
        stars: { label: "Zodiac Stars", maxCount: 15, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
        1: "Aspiring Saint",
        5: "Bronze Saint",
        15: "Pegasus Seiya",
        30: "Silver Saint",
        50: "Gold Cloth Guardian",
        75: "Seventh Sense",
        100: "Guardian of Athena",
    },
}
