import { AnimeThemeConfig } from "./types"
import { GiShiningSword, GiGhost, GiCrystalBall, GiFlame, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiAcorn } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const shamanKingTheme: AnimeThemeConfig = {
    id: "shaman-king",
    displayName: "Shaman King",
    description: "Every 500 years, a tournament selects the Shaman King who can commune with the Great Spirit and reshape the world. Yoh Asakura fights alongside his ancestor Amidamaru to claim the throne.",
    fontFamily: "'Cinzel', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "220 185 130",
        "--color-brand-300": "198 155 85",
        "--color-brand-400": "175 125 42",
        "--color-brand-500": "150 98 8",
        "--color-brand-600": "122 76 4",
        "--color-brand-700": "94 56 2",
        "--color-brand-800": "66 38 1",
        "--color-brand-900": "40 22 0",
        "--color-brand-950": "22 12 0",
        "--brand": "150 98 8",
        "--background": "#060502",
        "--paper": "#0c0a04",
        "--color-gray-950": "6 5 2",
        "--color-gray-900": "14 12 5",
        "--color-gray-800": "26 22 10",
        "--color-gray-700": "44 38 18",
        "--color-gray-600": "68 58 32",
        "--color-gray-500": "105 92 58",
        "--color-gray-400": "148 134 100",
        "--color-gray-300": "186 172 145",
        "--color-gray-200": "214 202 178",
        "--color-gray-100": "232 224 210",
        "--color-gray-50": "246 242 235",
    },
    sidebarOverrides: {
        "home": { icon: GiShiningSword, label: "Spirit World" },
        "schedule": { icon: GiAlarmClock, label: "Tournament Draw" },
        "manga": { icon: LuBookOpen, label: "Spirit Scrolls" },
        "lists": { icon: GiGhost, label: "Spirit Registry" },
        "discover": { icon: GiBullseye, label: "Shaman Hunt" },
        "torrent-list": { icon: GiFlame, label: "Furyoku Cache" },
        "debrid": { icon: GiCrystalBall, label: "Spirit Link" },
        "unmatched": { icon: GiAcorn, label: "Lost Spirits" },
        "enmasse": { icon: GiResize, label: "Team Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Reports" },
        "auto-downloader": { icon: LuRss, label: "Spirit Feed" },
        "community": { icon: GiShiningSword, label: "Shaman Community" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Spirit Calls" },
        "achievements": { icon: GiTrophy, label: "Shaman Titles" },
        "milestones": { icon: LuFlag, label: "Spirit Goals" },
        "theme-manager": { icon: GiPalette, label: "Spirit Colors" },
        "extensions": { icon: BiExtension, label: "Oversoul Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Spirit Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Furyoku Settings" },
    },
    achievementNames: {
        "a_first_episode": "Spirit Seen",
        "a_first_complete": "King Crowned",
        "a_hundred_club": "Hundred Spirits",
        "a_time_lord": "Shaman Master",
        "a_anime_collector": "Oversoul Cache",
        "a_library_legend": "Spirit Archives",
        "a_binge_king": "Tournament Marathon",
        "a_no_sleep": "All-Night Training",
        "a_marathon_runner": "Shaman Path",
        "a_speed_run": "Yoh Sprint",
        "a_completionist": "King Earned",
        "a_mega_completionist": "Takei Master",
        "a_loyal_fan": "Yoh's Ally",
        "a_rewatcher": "Spirit Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Shaman Combat",
        "a_genre_adventure": "Spirit Journey",
        "a_genre_comedy": "Yoh's Ease",
        "a_genre_drama": "Hao's Shadow",
        "a_genre_fantasy": "Spirit World",
        "a_genre_horror": "Hao's Terror",
        "a_genre_romance": "Yoh and Anna",
        "a_genre_scifi": "Furyoku Science",
        "a_genre_supernatural": "Shaman Power",
        "a_genre_psychological": "Hao's Mind",
        "a_genre_mecha": "Oversoul Form",
        "a_critic": "Shaman Judge",
        "a_perfect_ten": "Great Oversoul",
        "a_harsh_critic": "Strict Anna",
        "a_daily_streak": "Daily Training",
        "a_mega_streak": "Endless Training",
        "a_year_long": "Tournament Year",
        "a_iron_will": "Yoh's Spirit",
        "a_hidden_gem": "Hidden Spirit",
        "a_cult_classic": "Shaman Classic",
        "a_classic_connoisseur": "2000 Fan",
        "a_new_years_resolution": "New Year Training",
        "a_christmas_special": "Winter Ceremony",
        "a_meta_tier_max": "Shaman King",
        "a_meta_completionist": "Complete Spirits",
        "a_sequel_chain": "Flowers Sequel",
        "a_zero_to_hero": "Lazy Boy to King",
        "a_night_owl": "Night Training",
        "a_early_bird": "Dawn Spirit",
        "m_first_chapter": "First Spirit",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Spirit Marathon",
        "m_completionist": "Full Journey",
        "m_mega_completionist": "Shaman Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Spirit Return",
        "m_genre_action": "Combat Chapter",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Anna Chapter",
        "m_genre_fantasy": "Spirit Chapter",
        "m_genre_horror": "Hao Chapter",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "Furyoku Chapter",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Shaman Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Spirit Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Spirit Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Manga",
        "m_mangaka_lover": "Takei Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "King Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Spirit Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060502",
        primary: "#966208",
        secondary: "#5e3802",
        accent: "#8090e0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/shaman-king.jpg",
    particleColor: "#c8a030",
    backgroundDim: 0.35,
    backgroundBlur: 18,
    particleTypes: {
        spirits: { label: "Floating Spirits", maxCount: 12, defaultEnabled: true, defaultIntensity: 55 },
        furyoku: { label: "Furyoku Flames", maxCount: 10, defaultEnabled: true, defaultIntensity: 60 },
    },
    milestoneNames: {
        1: "Spirit Novice",
        5: "Yoh Asakura",
        15: "Tournament Entry",
        30: "Amidamaru Partner",
        50: "X-Laws Rival",
        75: "Hao's Equal",
        100: "Shaman King",
    },
}
