import { AnimeThemeConfig } from "./types"
import { GiJoystick, GiCastle, GiArrowhead, GiLightningTrio, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiBroadsword, GiHeartKey, GiCrown } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const shangriLaFrontierTheme: AnimeThemeConfig = {
    id: "shangri-la-frontier",
    displayName: "Shangri-La Frontier",
    description: "Gamer Rakurou Hizutome specialises in conquering terrible games — but when friends convince him to try the legendary full-dive VR title Shangri-La Frontier, he discovers a massive world with hidden depths no guide can prepare you for.",
    fontFamily: "'Rajdhani', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 198 140",
        "--color-brand-300": "255 162 75",
        "--color-brand-400": "248 120 18",
        "--color-brand-500": "220 88 0",
        "--color-brand-600": "178 60 0",
        "--color-brand-700": "132 38 0",
        "--color-brand-800": "88 22 0",
        "--color-brand-900": "48 10 0",
        "--color-brand-950": "20 4 0",
        "--brand": "220 88 0",
        "--background": "#060200",
        "--paper": "#120500",
        "--color-gray-950": "6 2 0",
        "--color-gray-900": "14 5 0",
        "--color-gray-800": "26 10 2",
        "--color-gray-700": "44 18 4",
        "--color-gray-600": "70 32 8",
        "--color-gray-500": "110 58 18",
        "--color-gray-400": "158 96 42",
        "--color-gray-300": "200 138 78",
        "--color-gray-200": "228 178 120",
        "--color-gray-100": "245 210 162",
        "--color-gray-50": "255 238 210",
    },
    sidebarOverrides: {
        "home": { icon: GiJoystick, label: "Lobby" },
        "schedule": { icon: GiAlarmClock, label: "Server Time" },
        "manga": { icon: LuBookOpen, label: "Patch Notes" },
        "lists": { icon: GiFlowerEmblem, label: "Quest Log" },
        "discover": { icon: GiBullseye, label: "New Zones" },
        "torrent-list": { icon: GiArrowhead, label: "Gear Cache" },
        "debrid": { icon: GiCastle, label: "Vault Server" },
        "unmatched": { icon: GiHeartKey, label: "Lost Items" },
        "enmasse": { icon: GiResize, label: "Party Finder" },
        "scan-summaries": { icon: TbReportSearch, label: "Server Logs" },
        "auto-downloader": { icon: LuRss, label: "Patch Feed" },
        "community": { icon: GiBroadsword, label: "Player Guild" },
        "achievements": { icon: GiTrophy, label: "Achievement Scores" },
        "milestones": { icon: LuFlag, label: "Rank Milestones" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Server Alerts" },
        "theme-manager": { icon: GiPalette, label: "Neon Palette" },
        "extensions": { icon: BiExtension, label: "Game Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Server Sync" },
        "settings": { icon: GiSettingsKnobs, label: "SLF Config" },
    },
    achievementNames: {
        "a_first_episode": "Server Joined",
        "a_first_complete": "Dungeon Cleared",
        "a_hundred_club": "Hundred Quests",
        "a_time_lord": "Veteran Gamer",
        "a_anime_collector": "Game Archive",
        "a_library_legend": "Server Library",
        "a_binge_king": "Game Marathon",
        "a_no_sleep": "No-Sleep Run",
        "a_marathon_runner": "Hizutome's Run",
        "a_speed_run": "Speed Clear",
        "a_completionist": "100% Complete",
        "a_mega_completionist": "Master Gamer",
        "a_loyal_fan": "Main Account",
        "a_rewatcher": "New Game+",
        "a_decade_watcher": "Decade Grind",
        "a_genre_action": "Action Quest",
        "a_genre_adventure": "Open World",
        "a_genre_comedy": "Kusoge Comedy",
        "a_genre_drama": "Story Mode",
        "a_genre_fantasy": "RPG World",
        "a_genre_horror": "Horror Dungeon",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "VR World",
        "a_genre_supernatural": "Hidden Lore",
        "a_genre_psychological": "Mind Game",
        "a_genre_mecha": "None Here",
        "a_critic": "Game Critic",
        "a_perfect_ten": "Perfect Score",
        "a_harsh_critic": "Kusoge Hunter",
        "a_daily_streak": "Daily Login",
        "a_mega_streak": "Endless Grind",
        "a_year_long": "Year Online",
        "a_iron_will": "Never Quit",
        "a_hidden_gem": "Hidden Zone",
        "a_cult_classic": "Classic Server",
        "a_classic_connoisseur": "2023 Fan",
        "a_new_years_resolution": "New Year Quest",
        "a_christmas_special": "Winter Event",
        "a_meta_tier_max": "True Player",
        "a_meta_completionist": "All Quests",
        "a_sequel_chain": "Sequel Chain",
        "a_zero_to_hero": "LvL 1 to Legend",
        "a_night_owl": "Night Grind",
        "a_early_bird": "Dawn Login",
        "m_first_chapter": "Tutorial Done",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Chapter Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "SLF Expert",
        "m_loyal_reader": "Regular Reader",
        "m_rereader": "New Game+ Read",
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Adventure Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Fantasy Chapter",
        "m_genre_horror": "Horror Chapter",
        "m_genre_drama": "Story Chapter",
        "m_genre_scifi": "VR Chapter",
        "m_genre_supernatural": "Lore Chapter",
        "m_genre_psychological": "Depth Chapter",
        "m_critic": "Server Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Grind Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Gamer",
        "m_hidden_gem": "Hidden Zone",
        "m_cult_classic": "Classic Chapter",
        "m_mangaka_lover": "Fuji Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "SLF Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Game Art",
        "m_manga_to_anime": "Adapted Quest",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060200",
        primary: "#dc5800",
        secondary: "#b23c00",
        accent: "#20d8f0",
    },
    particleColor: "#f07820",
    backgroundDim: 0.26,
    backgroundBlur: 14,
    particleTypes: {
        neon_glitch: { label: "Neon Glitch", maxCount: 14, defaultEnabled: true, defaultIntensity: 48 },
        golden_sparks: { label: "Game Sparks", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1: "Tutorial Cleared",
        5: "Casual Player",
        15: "Consistent Grinder",
        30: "Clan Member",
        50: "Raid Leader",
        75: "Server Legend",
        100: "Shangri-La Frontier",
    },
}
