import { AnimeThemeConfig } from "./types"
import { GiSchoolBag, GiTeapot, GiFlowerEmblem, GiSun, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiPencilBrush, GiDramaMasks, GiHeartKey, GiCycling } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const skipAndLoaferTheme: AnimeThemeConfig = {
    id: "skip-and-loafer",
    displayName: "Skip and Loafer",
    description: "Optimistic small-town girl Mitsumi Iwakura moves to Tokyo to chase her ambitious life plan, and through a stumble on her first day of high school she befriends the effortlessly popular Sousuke Shima, beginning a warm coming-of-age story.",
    fontFamily: "'Kosugi Maru', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap",
    cssVars: {
        "--color-brand-200": "252 238 168",
        "--color-brand-300": "248 220 102",
        "--color-brand-400": "235 196 42",
        "--color-brand-500": "210 165 8",
        "--color-brand-600": "170 128 0",
        "--color-brand-700": "128 94 0",
        "--color-brand-800": "86 62 0",
        "--color-brand-900": "46 32 0",
        "--color-brand-950": "18 12 0",
        "--brand": "210 165 8",
        "--background": "#050500",
        "--paper": "#100f00",
        "--color-gray-950": "5 5 0",
        "--color-gray-900": "12 11 1",
        "--color-gray-800": "22 20 4",
        "--color-gray-700": "38 34 10",
        "--color-gray-600": "62 56 20",
        "--color-gray-500": "100 92 40",
        "--color-gray-400": "148 136 72",
        "--color-gray-300": "192 178 108",
        "--color-gray-200": "222 210 152",
        "--color-gray-100": "242 234 192",
        "--color-gray-50": "252 248 228",
    },
    sidebarOverrides: {
        "home": { icon: GiSun, label: "Mitsumi's World" },
        "schedule": { icon: GiAlarmClock, label: "Life Schedule" },
        "manga": { icon: LuBookOpen, label: "Life Plan" },
        "lists": { icon: GiFlowerEmblem, label: "Friends List" },
        "discover": { icon: GiBullseye, label: "New Encounters" },
        "torrent-list": { icon: GiSchoolBag, label: "School Cache" },
        "debrid": { icon: GiTeapot, label: "Warm Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Moments" },
        "enmasse": { icon: GiResize, label: "Friend Group" },
        "scan-summaries": { icon: TbReportSearch, label: "Life Reports" },
        "auto-downloader": { icon: LuRss, label: "Mitsumi's Feed" },
        "community": { icon: GiPencilBrush, label: "Tokyo Friends" },
        "achievements": { icon: GiTrophy, label: "Life Goals" },
        "milestones": { icon: LuFlag, label: "Life Plan Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Friend Alerts" },
        "theme-manager": { icon: GiPalette, label: "Yellow Palette" },
        "extensions": { icon: BiExtension, label: "Life Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Heart Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Mitsumi's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Day Tokyo",
        "a_first_complete": "Year Complete",
        "a_hundred_club": "Hundred Days",
        "a_time_lord": "Life Veteran",
        "a_anime_collector": "Memory Archive",
        "a_library_legend": "Life Library",
        "a_binge_king": "Youth Marathon",
        "a_no_sleep": "All-Night Study",
        "a_marathon_runner": "Mitsumi's Run",
        "a_speed_run": "Life Speed",
        "a_completionist": "Life Plan Done",
        "a_mega_completionist": "Perfect Life",
        "a_loyal_fan": "Loyal Friend",
        "a_rewatcher": "Replay Youth",
        "a_decade_watcher": "Decade Growth",
        "a_genre_action": "None Here",
        "a_genre_adventure": "City Adventure",
        "a_genre_comedy": "Life Comedy",
        "a_genre_drama": "Growing Up",
        "a_genre_fantasy": "None Here",
        "a_genre_horror": "None Here",
        "a_genre_romance": "Mitsumi's Heart",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Shima's Depth",
        "a_genre_mecha": "None Here",
        "a_critic": "Life Critic",
        "a_perfect_ten": "Perfect Year",
        "a_harsh_critic": "High Goals",
        "a_daily_streak": "Daily Growth",
        "a_mega_streak": "Endless Journey",
        "a_year_long": "Year of Youth",
        "a_iron_will": "Mitsumi's Spirit",
        "a_hidden_gem": "Hidden Gem",
        "a_cult_classic": "Slice of Life",
        "a_classic_connoisseur": "2023 Fan",
        "a_new_years_resolution": "New Year Goal",
        "a_christmas_special": "Winter Youth",
        "a_meta_tier_max": "True Self",
        "a_meta_completionist": "All Memories",
        "a_sequel_chain": "Life Chain",
        "a_zero_to_hero": "Country Girl in City",
        "a_night_owl": "Night Study",
        "a_early_bird": "Dawn Run",
        "m_first_chapter": "First Skip",
        "m_first_complete": "Arc Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Youth Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Skip Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Re-youth",
        "m_genre_action": "None Here",
        "m_genre_adventure": "Tokyo Chapter",
        "m_genre_romance": "Warm Chapter",
        "m_genre_fantasy": "None Here",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Life Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Inner Chapter",
        "m_critic": "Life Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Life Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Spirit",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Slice Classic",
        "m_mangaka_lover": "Misaki Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Skip Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Warm Art",
        "m_manga_to_anime": "Adapted Life",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050500",
        primary: "#d2a508",
        secondary: "#aa8000",
        accent: "#b08060",
    },
    particleColor: "#f0d040",
    backgroundDim: 0.22,
    backgroundBlur: 10,
    particleTypes: {
        sparkles: { label: "Warm Sparkles", maxCount: 18, defaultEnabled: true, defaultIntensity: 55 },
        falling_leaves: { label: "Petals", maxCount: 12, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1: "Small Town Girl",
        5: "Tokyo Freshman",
        15: "School Friend",
        30: "Growing Up",
        50: "Tokyo Local",
        75: "Life Planner",
        100: "Mitsumi's Dream",
    },
}
