import { AnimeThemeConfig } from "./types"
import {
    GiSlime, GiCrown, GiScrollUnfurled, GiSpellBook,
    GiDragonHead, GiMagicGate, GiPotionBall, GiShield,
    GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss } from "react-icons/lu"
import { BiExtension } from "react-icons/bi"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { TbReportSearch } from "react-icons/tb"

export const slimeIsekaiTheme: AnimeThemeConfig = {
    id: "slime-isekai",
    displayName: "That Time I Got Reincarnated as a Slime",
    description: "Rimuru's nation-building. Benevolent Demon Lord in teal & blue slime.",
    fontFamily: "'Quicksand', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&display=swap",
    cssVars: {
        "--color-brand-200": "160 240 240",
        "--color-brand-300": "80 215 215",
        "--color-brand-400": "20 188 185",
        "--color-brand-500": "0 155 152",
        "--color-brand-600": "0 120 118",
        "--color-brand-700": "0 88 86",
        "--color-brand-800": "0 58 57",
        "--color-brand-900": "0 35 34",
        "--color-brand-950": "0 16 16",
        "--brand": "5 162 158",
        "--background": "#00100f",
        "--paper": "#001a19",
        "--color-gray-950": "0 8 8",
        "--color-gray-900": "0 16 16",
        "--color-gray-800": "4 30 29",
        "--color-gray-700": "8 48 46",
        "--color-gray-600": "14 72 70",
        "--color-gray-500": "28 105 102",
        "--color-gray-400": "65 155 152",
        "--color-gray-300": "110 195 192",
        "--color-gray-200": "162 225 222",
        "--color-gray-100": "210 245 244",
        "--color-gray-50":  "240 254 253",
    },
    sidebarOverrides: {
        "home":           { icon: GiSlime,         label: "Tempest Kingdom" },
        "schedule":       { icon: GiAlarmClock,    label: "Kingdom Events" },
        "manga":          { icon: GiScrollUnfurled,label: "Great Sage Files" },
        "lists":          { icon: GiSpellBook,     label: "Monster Registry" },
        "discover":       { icon: GiDragonHead,    label: "Named Monster Hunt" },
        "torrent-list":   { icon: GiMagicGate,     label: "Tempest Ops" },
        "unmatched":      { icon: GiPotionBall,    label: "Unnamed Slimes" },
        "scan-summaries": { icon: TbReportSearch,  label: "Kingdom Reports" },
        "auto-downloader":{ icon: LuRss,           label: "Rimuru's Network" },
        "search":         { icon: FiSearch,        label: "Search" },
        "notifications":  { icon: LuBell,          label: "Kingdom Alerts" },
        "achievements":   { icon: GiCrown,         label: "Demon Lord Rank" },
        "theme-manager":  { icon: GiPalette,       label: "Slime Colors" },
        "extensions":     { icon: BiExtension,     label: "Contracts" },
        "settings":       { icon: GiSettingsKnobs, label: "Great Sage Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode":            "Reincarnated as a Slime",
        "a_episode_counter":          "Skills Absorbed",
        "a_episode_titan":            "True Demon Lord Awakening",
        "a_hours_invested":           "Nation-Building Hours",
        "a_time_lord":                "Great Sage's Timeless Data",
        "a_anime_collector":          "Tempest Archive",
        "a_library_legend":           "Great Sage Archive",
        "a_first_complete":           "First Nation Founded",
        "a_hundred_club":             "Tempest Citizen",
        "a_first_day":                "Slime's First Day",
        "a_first_rating":             "Rimuru's Evaluation",
        "a_ten_thousand_min":         "Ten Thousand Minutes of Slime",
        "a_season_veteran":           "Veteran Nation Builder",
        "a_year_explorer":            "Year in Tempest",
        "a_century_watcher":          "Hundred Episodes in Jura",
        "a_five_hundred_eps":         "Five Hundred Predations",
        "a_thousand_eps":             "Thousand Slime Encounters",
        "a_watching_ten":             "Ten Nations Simultaneously",
        "a_ptw_hoarder":              "Tempest Supply Hoarder",
        "a_dropped_honesty":          "Tactical Retreat from Jura",
        "a_five_thousand_eps":        "Five Thousand Slime Miles",
        "a_ten_completed":            "Ten Kingdoms Founded",
        "a_fifty_completed":          "Fifty Arcs Conquered",
        "a_five_hundred_completed":   "Five Hundred Victories for Tempest",
        "a_mean_score_tracker":       "Tempest Average Rating",
        "a_unique_studios":           "Allied Monster Nations",
        "a_days_spent_watching":      "Days in Tempest Kingdom",
        "a_all_status":               "All Deployment Statuses",
        "a_first_favorite":           "First Named Monster Bond",
        "a_favorites_collector":      "Tempest Allies Roster",

        // ── ANIME BINGE ──
        "a_binge_watcher":            "Tempest Nation Marathon",
        "a_marathon_runner":          "Forest-to-Forest Marathon",
        "a_weekend_warrior":          "Weekend Slime Watch",
        "a_non_stop":                 "Predator Non-Stop Advance",
        "a_one_more_episode":         "One More Naming Ceremony",
        "a_speed_run":                "Rimuru Speed Blitz",
        "a_double_feature":           "Double Skill Predation",
        "a_triple_threat":            "Triple Demon Lord Challenge",
        "a_five_a_day":               "Five Absorptions a Day",
        "a_back_to_back":             "Back-to-Back Evolutions",
        "a_seasonal_binge":           "Full Tempest Season Arc",
        "a_cour_crusher":             "Jura Forest Crusher",
        "a_half_day_watch":           "Half-Day in Tempest",
        "a_full_day_watch":           "Full Day in Kingdom",
        "a_power_weekend":            "Power Weekend Slime Ops",
        "a_binge_king":               "Rimuru Binge Commander",
        "a_no_sleep":                 "All-Night Tempest Council",
        "a_entire_season":            "Rapid Season Clear",
        "a_seven_day_challenge":      "Seven-Day Kingdom Build",
        "a_hundred_day_binge":        "Hundred-Day Slime Siege",
        "a_genre_binge":              "Cross-Nation Training",
        "a_studio_binge":             "Allied Studio Binge",
        "a_season_sweep":             "Season Sweep Tempest",
        "a_forty_eight_hour":         "Forty-Eight Hour Slime Watch",
        "a_ep_counter_day":           "Daily Predation Count",
        "a_multi_series_binge":       "Multi-Front Slime Campaign",
        "a_midnight_binge":           "Midnight Great Sage Session",
        "a_new_year_binge":           "New Year's Tempest Charge",

        // ── ANIME GENRES ──
        "a_genre_action":             "Predation Complete",
        "a_genre_adventure":          "Beyond the Jura Forest",
        "a_genre_comedy":             "Gobta's Blunder",
        "a_genre_drama":              "Rimuru's Vow",
        "a_genre_fantasy":            "Isekai Nation Builder",
        "a_genre_horror":             "Walpurgis Horror Night",
        "a_genre_mystery":            "Great Sage's Hidden Data",
        "a_genre_romance":            "Heart of Tempest",
        "a_genre_scifi":              "Rimuru's Unique Skills",
        "a_genre_sol":                "Life in Tempest Kingdom",
        "a_genre_sports":             "Monster Training Grounds",
        "a_genre_supernatural":       "Unique Skill Predator",
        "a_genre_thriller":           "Demon Lord Pursuit",
        "a_genre_mecha":              "Storm Dragon Veldora",
        "a_genre_music":              "Tempest Festival Songs",
        "a_genre_psychological":      "Rimuru's Inner Dialogue",
        "a_genre_ecchi":              "Hot Spring Slime Episode",
        "a_genre_mahou_shoujo":       "Great Sage Wielder",
        "a_tag_isekai":               "Reincarnated Into Another World",
        "a_tag_harem":                "Tempest Harem Bonds",
        "a_tag_bl":                   "Companions of Tempest",
        "a_tag_gl":                   "Shield Sisters of Tempest",
        "a_tag_historical":           "Ancient Jura History",
        "a_tag_military":             "Tempest Military Discipline",
        "a_tag_school":               "Monster Academy",
        "a_tag_martial_arts":         "Benimaru's Combat Style",
        "a_tag_vampire":              "Luminous Valentine",
        "a_tag_samurai":              "Hakuro's Blade Style",
        "a_tag_space":                "Beyond the Demon Lords",
        "a_tag_parody":               "Gobta Comedy Parody",
        "a_tag_idol":                 "Wings of Tempest Idol",
        "a_tag_post_apocalyptic":     "Post-Walpurgis Aftermath",
        "a_tag_cyberpunk":            "Tempest Technology",
        "a_tag_shounen":              "Dedicate to Tempest",
        "a_tag_seinen":               "Harsh Reality of Naming",
        "a_tag_shoujo":               "Shion's Devotion",
        "a_tag_josei":                "Treyni's Obsession",
        "a_tag_survival":             "Survival in the Jura Forest",

        // ── ANIME COMPLETION ──
        "a_completionist":            "All Arcs Mastered",
        "a_mega_completionist":       "Supreme Demon Lord",
        "a_completion_rate_50":       "Halfway to Demon Lord",
        "a_completion_rate_75":       "Approaching True Form",
        "a_completion_rate_90":       "Paths Nearly Unlocked",
        "a_no_drop":                  "Never Abandon Tempest",
        "a_long_runner_complete":     "Long Campaign Endurance",
        "a_sequel_chain":             "Tempest Sequel Chain",
        "a_clean_list":               "Clean Tempest Record",
        "a_from_ptw":                 "Orders Received from Rimuru",
        "a_rewatch_master":           "Great Sage Review",
        "a_short_complete":           "Quick Skirmish Victory",
        "a_same_day_start_finish":    "Same-Day Predation",
        "a_revival":                  "Revived by Great Sage",
        "a_zero_to_hero":             "Slime to Demon Lord",
        "a_five_genre_complete":      "Five-Branch Mastery",
        "a_full_franchise":           "Full Tempest Dossier",
        "a_batch_complete":           "Batch Deployment Clear",
        "a_paused_to_done":           "Returned from Magic Sleep",
        "a_completion_spree":         "Completion Predator Spree",
        "a_multi_rewatch":            "Multi-Timeline via Great Sage",
        "a_dropped_recovery":         "Recovered from Rimuru's Jaw",
        "a_ten_perfect_scores":       "Ten Perfect Slime Scores",
        "a_seasonal_clear":           "Seasonal Arc Clear",
        "a_complete_genre_span":      "All-Terrain Slime Scout",
        "a_monthly_completions":      "Monthly Mission Reports",
        "a_yearly_completions":       "Yearly Campaign Victor",
        "a_rapid_complete":           "Lightning Predation Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan":                "Tempest Alliance",
        "a_studio_devotee":           "8bit/Muse Devotee",
        "a_rewatcher":                "Great Sage Rewatch",
        "a_triple_rewatch":           "Triple Nation Rewatch",
        "a_annual_tradition":         "Annual Tempest Day",
        "a_director_fan":             "Kikuchi's Vision Follower",
        "a_voice_actor_fan":          "Voice of Tempest",
        "a_ost_lover":                "Rimuru's Slime Song",
        "a_source_reader":            "Fuse's Original Texts",
        "a_waiting_weekly":           "Weekly Tempest Signal Wait",
        "a_childhood_revisit":        "Return to Jura Forest",
        "a_saga_tracker":             "Saga of Tempest Tracker",
        "a_genre_loyalty":            "Nation Loyalty Badge",
        "a_decade_watcher":           "Decade-Long Slime Fan",
        "a_adaptation_hunter":        "Adaptation Reconnaissance",
        "a_original_anime_fan":       "Original Broadcast Veteran",
        "a_long_commitment":          "Long-Term Kingdom Duty",
        "a_perfect_attendance":       "Perfect Kingdom Attendance",
        "a_favorite_studio_5":        "Five Allied Studios",
        "a_complete_catalog":         "Complete Tempest Catalog",
        "a_franchise_collector":      "Slime Universe Collector",
        "a_airing_follower":          "Currently Airing Intel",
        "a_genre_master":             "Genre Mastery Achieved",
        "a_staff_follower":           "Staff Dossier Tracker",
        "a_multi_season_fan":         "Multi-Season Slime Fan",
        "a_format_diversity":         "Diverse Tempest Formats",
        "a_year_dedication":          "Year of Dedication to Tempest",
        "a_season_dedication":        "Season of Unwavering Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer":           "Scout Beyond Known Territory",
        "a_studio_hopper":            "Nation Transfer",
        "a_tag_explorer":             "Tag Reconnaissance Mission",
        "a_decade_hopper":            "Time via Great Sage",
        "a_hidden_gem":               "Hidden Jura Forest Gem",
        "a_popular_taste":            "Popular Among Slimes",
        "a_retro_appreciator":        "Pre-Tempest Era Appreciator",
        "a_modern_viewer":            "Modern Demon Lord Viewer",
        "a_cross_demographic":        "Cross-Demographic Scout",
        "a_underdog_fan":             "Underdog Slime Spirit",
        "a_variety_week":             "Week of Varied Tactics",
        "a_foreign_cinema":           "Foreign Intelligence Cinema",
        "a_classic_connoisseur":      "Classic Slime Connoisseur",
        "a_every_season":             "Every Season Deployed",
        "a_award_winner":             "Medal of Valor",
        "a_niche_explorer":           "Niche Territory Explorer",
        "a_global_anime":             "Global Alliance Entry",
        "a_cult_classic":             "Underground Cult Classic",
        "a_random_pick":              "Random Mission Assignment",
        "a_new_genre_month":          "New Terrain Monthly",
        "a_seasonal_completionist":   "Seasonal Campaign Clear",
        "a_unpopular_opinion":        "Unpopular Tactical Opinion",
        "a_top_rated_viewer":         "Top-Rated Tempest Source",
        "a_source_variety":           "Source Material Variety",
        "a_low_score_brave":          "Brave Charge into Low Scores",
        "a_upcoming_watcher":         "Upcoming Operation Intel",
        "a_short_series_explorer":    "Short Skirmish Explorer",
        "a_long_series_explorer":     "Long Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl":                "Night Council Meeting",
        "a_early_bird":               "Dawn Patrol in Tempest",
        "a_lunch_break":              "Tempest Mess Hall Break",
        "a_golden_hour":              "Golden Hour Slime Glow",
        "a_four_am_club":             "4 AM Tempest Sentry",
        "a_witching_hour":            "Demon Lord Witching Hour",
        "a_new_year_watch":           "New Year's Oath to Tempest",
        "a_midnight_premiere":        "Midnight Naming Ceremony",
        "a_all_hours":                "All-Hours Slime Scout",
        "a_dawn_warrior":             "Dawn Warrior of Tempest",
        "a_afternoon_delight":        "Afternoon Kingdom Drill",
        "a_prime_time":               "Prime Time Engagement",
        "a_workday_watcher":          "On-Duty Watcher",
        "a_sunday_marathon":          "Sunday Jura Forest Marathon",
        "a_rainy_day":                "Rainy Day in Tempest",
        "a_morning_routine":          "Morning Kingdom Formation",
        "a_night_shift":              "Night Shift Kingdom Garrison",
        "a_twilight_zone":            "Twilight Beyond Jura Forest",
        "a_seasonal_premier":         "Season Premiere Sortie",
        "a_clock_collector":          "Rimuru's Clock Tower",
        "a_weekend_binge_hours":      "Weekend Slime Binge Ops",
        "a_late_night_regular":       "Late Night Regular Patrol",
        "a_sunrise_watcher":          "Sunrise Over Tempest",
        "a_holiday_watcher":          "Holiday Kingdom Duty",
        "a_every_day_of_week":        "Every Day in Tempest",
        "a_monthly_hours":            "Monthly Kingdom Duty Hours",

        // ── ANIME SOCIAL ──
        "a_first_party":              "First Tempest Formation",
        "a_party_host":               "Kingdom Party Commander",
        "a_social_butterfly":         "Tempest Hall Socialite",
        "a_group_binge":              "Group Predator Volley",
        "a_party_regular":            "Regular Sparring Partner",
        "a_sync_viewer":              "Synchronized Slime Maneuver",
        "a_commentator":              "Battle Commentator",
        "a_party_marathon":           "Marathon Tempest Formation",
        "a_full_house":               "Full Squad Assembled",
        "a_community_pillar":         "Pillar of the Kingdom",
        "a_watch_party_streak":       "Consecutive Formation Streak",
        "a_diverse_party":            "Diverse Kingdom Party",
        "a_late_night_party":         "Late Night Barracks Party",
        "a_party_veteran":            "Veteran Squad Leader",
        "a_genre_party":              "Cross-Genre Formation",
        "a_weekly_party":             "Weekly Comrades' Gathering",
        "a_silent_viewer":            "Silent Rimuru Observer",
        "a_recommendation_giver":     "Rimuru's Recommendation",
        "a_party_completionist":      "Party Operation Completionist",
        "a_social_scorer":            "Social Kingdom Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number":             "Round Number Formation",
        "a_fibonacci":                "Fibonacci Slime Sequence",
        "a_palindrome_day":           "Palindrome Time Rift",
        "a_binary_day":               "Binary Signal Slime Day",
        "a_full_moon":                "Full Moon Slime Transformation",
        "a_leap_year":                "Leap Year Time Skip",
        "a_time_traveler":            "Great Sage's Future Memory",
        "a_genre_clash":              "Slime vs. Demon Clash",
        "a_triple_seven":             "Triple Seven Tempest Walls",
        "a_thousand_complete":        "Thousand Tempest Battles",
        "a_pi_episodes":              "Pi Tempest Calculation",
        "a_synchronicity":            "Great Sage Synchronicity",
        "a_world_record":             "World Record Predation",
        "a_nice":                     "Nice Predation Count",
        "a_power_level":              "Rimuru Power Level",
        "a_answer_42":                "The Answer to Tempest's Question",
        "a_square_number":            "Perfect Slime Formation",
        "a_prime_count":              "Prime Number of Slimes",
        "a_matching_date":            "Matching Tempest Date",
        "a_century_episode":          "Century Episode Tempest",
        "a_double_digits":            "Double Digit Absorptions",
        "a_one_two_three":            "Slime, Dragon, Demon Lord",
        "a_lucky_seven":              "Seven Lucky Named Monsters",
        "a_all_tens":                 "All Tens Tempest Score",
        "a_exact_hundred_eps":        "Exact Hundred Predations",
        "a_year_match_count":         "Year Match Predation Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher":               "TV Broadcast Slime",
        "a_movie_buff":               "Slime Movie Operations",
        "a_ova_hunter":               "OVA Tempest Hunter",
        "a_ona_explorer":             "ONA Slime Explorer",
        "a_special_watcher":          "Special Episode Operative",
        "a_short_king":               "Short Engagement King",
        "a_variety_pack":             "All-Format Nation",
        "a_film_festival":            "Slime Film Festival",
        "a_music_video":              "Tempest Soundtrack Collection",
        "a_tv_short":                 "Quick Slime Clip",
        "a_movie_marathon":           "Movie Marathon Blitz",
        "a_double_length":            "Double-Length Operation",
        "a_anthology":                "Tempest Anthology",
        "a_mini_series":              "Mini Slime Campaign",
        "a_theatrical":               "Theatrical Tempest Deployment",
        "a_format_master":            "Format Master Slime",
        "a_long_movie":               "Feature-Length Expedition",
        "a_back_catalog":             "Back Catalog Tempest Files",
        "a_cm_watcher":               "Commercial Break Watcher",
        "a_pv_collector":             "Preview Signal Collector",
        "a_format_balance":           "Balanced Tempest Formats",
        "a_episodic_master":          "Episodic Campaign Master",
        "a_sequel_movie":             "Sequel Operation Film",
        "a_recap_watcher":            "Recap Briefing Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak":             "Daily Nation-Building",
        "a_mega_streak":              "Rimuru's Resolve",
        "a_weekly_warrior":           "Weekly Warrior of Tempest",
        "a_monthly_watcher":          "Monthly Kingdom Duty",
        "a_comeback":                 "Return from Magic Sleep",
        "a_weekend_streak":           "Weekend Tempest Streak",
        "a_no_zero_days":             "No Zero Days in Tempest",
        "a_iron_will":                "Iron Will of Tempest",
        "a_habit_formed":             "Tempest Training Regimen",
        "a_consistent_pace":          "Consistent March Forward",
        "a_year_long":                "Year-Long Kingdom Campaign",
        "a_double_streak":            "Double Streak Predation",
        "a_streak_recovery":          "Healer's Recovery",
        "a_daily_minimum":            "Daily Minimum Duty",
        "a_winter_streak":            "Winter Kingdom Streak",
        "a_summer_streak":            "Summer Offensive Streak",
        "a_morning_streak":           "Morning Slime Drill Streak",
        "a_night_streak":             "Night Kingdom Patrol Streak",
        "a_unbreakable":              "Unbreakable Will of Tempest",
        "a_eternal_flame":            "Eternal Flame of Tempest",
        "a_completion_streak":        "Completion Mission Chain",
        "a_rating_streak":            "Rating Streak Report",
        "a_multi_ep_streak":          "Multi-Episode Offensive",
        "a_genre_streak":             "Genre Streak Sortie",
        "a_studio_streak":            "Studio Loyalty Streak",
        "a_perfect_week":             "Perfect Week of Service",

        // ── ANIME SCORING ──
        "a_critic":                   "Council Evaluator",
        "a_perfect_ten":              "True Demon Lord Rating",
        "a_harsh_critic":             "Rimuru's Harsh Standards",
        "a_fair_judge":               "Benimaru's Fair Assessment",
        "a_generous_spirit":          "Generous Slime Spirit",
        "a_score_all":                "Full Nation Evaluation",
        "a_wide_range":               "Wide Range Tempest Assessment",
        "a_controversial":            "Controversial Demon Lord Decision",
        "a_consistent_scorer":        "Consistent Tempest Evaluator",
        "a_score_sniper":             "Precision Great Sage Sniper",
        "a_evolving_taste":           "Evolving Tempest Strategy",
        "a_bell_curve":               "Bell Curve of Slime Scores",
        "a_picky_watcher":            "Selective Demon Lord",
        "a_100_rated":                "Century of Evaluations",
        "a_500_rated":                "Five Hundred Kingdom Reports",
        "a_mediocre_majority":        "Middle Ground Strategist",
        "a_rating_spree":             "Rating Predator Barrage",
        "a_score_variance":           "Variable Kingdom Ratings",
        "a_masterpiece_hunter":       "Masterpiece Slime Hunter",
        "a_contrarian":               "Contrarian Demon Lord",
        "a_optimist":                 "Optimist in Tempest",
        "a_score_distributor":        "Score Distributor General",
        "a_genre_critic":             "Genre Tempest Critic",
        "a_mean_above_8":             "Elite Tempest Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution":     "New Year's Vow for Tempest",
        "a_valentines_weeb":          "Valentine's Dedication",
        "a_pi_day":                   "Pi Day Tempest Calc",
        "a_april_fools":              "April Fools Slime Prank",
        "a_international_anime_day":  "International Slime Day",
        "a_star_wars_day":            "Demon Lord Empire Day",
        "a_summer_solstice":          "Summer Solstice Expedition",
        "a_tanabata":                 "Tanabata Wish for Tempest",
        "a_friday_13th":              "Friday the 13th Demon Attack",
        "a_halloween_spirit":         "Halloween Slime Horror",
        "a_thanksgiving_binge":       "Thanksgiving Tempest Feast",
        "a_christmas_special":        "Midwinter Festival Special",
        "a_new_years_eve":            "New Year's Eve Final Stand",
        "a_birthday_watch":           "Birthday Naming Ceremony",
        "a_holiday_marathon":         "Holiday Tempest Marathon",
        "a_independence_day":         "Tempest Independence Day",
        "a_culture_day":              "Tempest Culture Day",
        "a_spring_equinox":           "Spring Equinox Advance",
        "a_earth_day":                "Protect This World Day",
        "a_labor_day":                "Kingdom Labor Day",
        "a_winter_solstice":          "Winter Solstice in Tempest",
        "a_anime_birthday":           "Anime Anniversary Celebration",
        "a_every_holiday":            "Every Holiday Scout",
        "a_consecutive_holidays":     "Consecutive Holiday Deployments",

        // ── ANIME META ──
        "a_meta_first_unlock":        "First Slime Power Awakened",
        "a_meta_collector":           "Tempest Badge Collector",
        "a_meta_category_starter":    "Category Initiation Rite",
        "a_meta_tier_climber":        "Rank Promotion",
        "a_meta_tier_max":            "Demon Lord-Class Rank",
        "a_meta_xp_earner":           "XP from Predation",
        "a_meta_difficulty_easy":     "Easy Training Exercise",
        "a_meta_difficulty_hard":     "Legendary Difficulty: Demon Lord",
        "a_meta_unlock_spree":        "Unlock Predator Spree",
        "a_meta_completionist":       "Meta Completionist Commander",
        "a_meta_diverse":             "Diverse Tempest Portfolio",
        "a_meta_dominator":           "Meta Dominator of Tempest",

        // ── MANGA MILESTONES ──
        "m_first_chapter":            "First Chapter of Jura Forest",
        "m_chapter_counter":          "Chapter Predation Counter",
        "m_chapter_titan":            "Chapter Demon Lord Assault",
        "m_reading_hours":            "Hours Studying Tempest Texts",
        "m_reading_time_lord":        "Great Sage's Reading Memory",
        "m_manga_collector":          "Tempest Archive Collector",
        "m_library_legend":           "Great Sage Archive Legend",
        "m_first_complete":           "First Manga Nation Done",
        "m_hundred_club":             "Hundred-Chapter Slime Club",
        "m_first_day":                "First Day of Reading",
        "m_first_rating":             "First Manuscript Rating",
        "m_ten_thousand_pages":       "Ten Thousand Pages of Intel",
        "m_volume_collector":         "Volume Stockpile Collector",
        "m_year_explorer":            "Year of Manga Exploration",
        "m_century_reader":           "Century-Chapter Reader",
        "m_five_hundred_ch":          "Five Hundred Chapters Consumed",
        "m_thousand_ch":              "Thousand-Chapter Campaign",
        "m_reading_ten":              "Ten Manuscripts at Once",
        "m_ptr_hoarder":              "Reading Backlog Hoarder",
        "m_dropped_honesty":          "Honest Tactical Retreat",
        "m_season_reader":            "Seasonal Reading Rotation",
        "m_active_reader":            "Active Field Reader",
        "m_five_thousand_ch":         "Five Thousand Chapters Deep",
        "m_ten_completed":            "Ten Manga Campaigns Complete",
        "m_fifty_completed":          "Fifty Manga Missions Done",
        "m_five_hundred_completed":   "Five Hundred Manga Victories",
        "m_mean_score_tracker":       "Average Manuscript Rating",
        "m_unique_authors":           "Unique Author Encounters",
        "m_all_status":               "All Reading Deployment Statuses",
        "m_first_favorite":           "First Manga Comrade Bond",
        "m_favorites_collector":      "Manga Favorites Arsenal",
        "m_days_spent_reading":       "Days in the Reading Garrison",

        // ── MANGA BINGE ──
        "m_binge_reader":             "Marathon Nation Building",
        "m_marathon_reader":          "Forest-to-Forest Reading Marathon",
        "m_weekend_reader":           "Weekend Barracks Reading",
        "m_non_stop_reading":         "Non-Stop Slime Pages",
        "m_one_more_chapter":         "One More Chapter Charge",
        "m_speed_read":               "Rimuru Speed Read",
        "m_double_story":             "Double Manuscript Feature",
        "m_triple_read":              "Triple Reading Assault",
        "m_five_a_day":               "Five Reads a Day",
        "m_chapter_chain":            "Chapter Chain Offensive",
        "m_volume_binge":             "Volume Binge Bombardment",
        "m_power_reader":             "Power Reader Slime",
        "m_half_day_read":            "Half-Day Archive Dive",
        "m_full_day_read":            "Full-Day Manuscript Study",
        "m_power_weekend":            "Power Weekend Reading",
        "m_binge_king":               "King of the Reading Nation",
        "m_no_sleep_read":            "All-Night Tempest Reading",
        "m_full_series_rush":         "Full Series Rush Attack",
        "m_seven_day_challenge":      "Seven-Day Tempest Gathering",
        "m_hundred_day_read":         "Hundred-Day Reading Siege",
        "m_volume_rush":              "Volume Rush Deployment",
        "m_series_sweep":             "Series Sweep Operation",
        "m_genre_binge":              "Cross-Genre Maneuver",
        "m_author_binge":             "Author Focused Deep Dive",
        "m_chapter_counter_day":      "Daily Chapter Predation Count",
        "m_multi_series_binge":       "Multi-Series Reading Front",
        "m_midnight_binge":           "Midnight Archive Session",
        "m_new_year_binge":           "New Year's Reading Charge",
        "m_forty_eight_hour":         "Forty-Eight Hour Reading Siege",
        "m_oneshot_binge":            "Oneshot Blitz Attack",

        // ── MANGA GENRES ──
        "m_genre_action":             "Action Slime Specialist",
        "m_genre_adventure":          "Adventure in Jura Forest",
        "m_genre_comedy":             "Comedy in the Kingdom",
        "m_genre_drama":              "Drama of Tempest's Legacy",
        "m_genre_fantasy":            "Fantasy of the Slime",
        "m_genre_horror":             "Horror Slime Manuscript",
        "m_genre_mystery":            "Mystery of the Great Sage",
        "m_genre_romance":            "Romance Under the Slime Sky",
        "m_genre_scifi":              "Sci-Fi Tempest Technology",
        "m_genre_sol":                "Slice of Life in Tempest",
        "m_genre_sports":             "Monster Training Sports",
        "m_genre_supernatural":       "Supernatural Slime Powers",
        "m_genre_thriller":           "Thriller Demon Lord Report",
        "m_genre_psychological":      "Psychological Warfare Slime",
        "m_genre_isekai":             "Isekai Jura Reincarnation",
        "m_genre_shounen":            "Shounen Heart of a Slime",
        "m_genre_ecchi":              "Hot Springs Slime Chapter",
        "m_genre_mahou_shoujo":       "Power of the Great Sage",
        "m_genre_mecha":              "Anti-Demon Weapon Blueprints",
        "m_genre_music":              "Tempest Folk Songs",
        "m_tag_isekai_new":           "New World Beyond Tempest",
        "m_tag_harem":                "Tempest Harem Manga",
        "m_tag_bl":                   "Brothers of Tempest Manga",
        "m_tag_gl":                   "Shield Sisters of Tempest Manga",
        "m_tag_historical":           "Jura History Manga",
        "m_tag_military":             "Tempest Operations Manga",
        "m_tag_school":               "Monster Academy Manga",
        "m_tag_martial_arts":         "Benimaru Combat Manual",
        "m_tag_vampire":              "Slime Blood Manga",
        "m_tag_samurai":              "Hakuro Blade Manga",
        "m_tag_space":                "Beyond the Horizon Manga",
        "m_tag_parody":               "Chibi Slime Manga",
        "m_tag_idol":                 "Wings of Tempest Manga",
        "m_tag_post_apocalyptic":     "Post-Walpurgis Manga",
        "m_tag_cyberpunk":            "Tempest Technology Manga",
        "m_tag_shoujo":               "Shion's Story Manga",
        "m_tag_survival":             "Tempest Survival Manga",
        "m_tag_cooking":              "Tempest Rations Cookbook",
        "m_tag_medical":              "Field Healer Manga",
        "m_tag_villainess":           "Demon Lord Candidate Manga",

        // ── MANGA COMPLETION ──
        "m_completionist":            "Manga Nation Completionist",
        "m_mega_completionist":       "Supreme Manga Demon Lord",
        "m_completion_rate_50":       "Halfway to Demon Lord Truth",
        "m_completion_rate_75":       "Approaching True Form",
        "m_completion_rate_90":       "Final Chapter Approaching",
        "m_no_drop":                  "No Manuscript Abandoned",
        "m_long_runner_complete":     "Long Series Endurance Medal",
        "m_sequel_chain":             "Sequel Chain of Tempest",
        "m_clean_list":               "Clean Reading Record",
        "m_from_ptr":                 "Orders Received: Read",
        "m_reread_master":            "Great Sage Reread Memory",
        "m_oneshot_complete":         "Oneshot Mission Specialist",
        "m_same_day_start_finish":    "Same-Day Reading Blitz",
        "m_revival":                  "Revival Through Great Sage",
        "m_zero_to_hundred":          "Slime to Scholar",
        "m_five_genre_complete":      "Five-Genre Mastery",
        "m_full_collection":          "Full Tempest Collection",
        "m_batch_complete":           "Batch Clearance",
        "m_paused_to_done":           "Back from Hiatus",
        "m_completion_spree":         "Completion Predation Barrage",
        "m_format_completionist":     "Format Completion Badge",
        "m_catch_up":                 "Caught Up with Tempest",
        "m_multi_reread":             "Multi-Pass Reread",
        "m_dropped_recovery":         "Recovered from the Slime",
        "m_ten_perfect_scores":       "Ten Perfect Manuscript Scores",
        "m_complete_genre_span":      "All-Genre Reading Scout",
        "m_monthly_completions":      "Monthly Manuscript Victories",
        "m_yearly_completions":       "Yearly Reading Campaign",
        "m_rapid_complete":           "Rapid Slime Processing",
        "m_author_complete":          "Author's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader":             "Loyal Tempest Reader",
        "m_mangaka_lover":            "Fuse Devotee",
        "m_rereader":                 "Slime Rereader",
        "m_triple_reread":            "Triple Reread Expedition",
        "m_annual_reread":            "Annual Remembrance Reread",
        "m_publisher_fan":            "Publisher Alliance Fan",
        "m_artist_fan":               "Artist Appreciation Medal",
        "m_adaptation_compare":       "Manga vs Anime Comparison",
        "m_source_material_fan":      "Source Material Scout",
        "m_waiting_weekly":           "Weekly Chapter Signal Wait",
        "m_classic_reader":           "Classic Manuscript Reader",
        "m_saga_reader":              "Saga of Tempest Reader",
        "m_genre_loyalty":            "Genre Loyalty Medal",
        "m_decade_reader":            "Decade-Long Reader",
        "m_ln_adaptation":            "Light Novel Intel",
        "m_original_work":            "Original Manga Work",
        "m_long_commitment":          "Long-Term Reading Commitment",
        "m_up_to_date":               "Up-to-Date with Tempest",
        "m_favorite_mangaka":         "Favorite Mangaka Honored",
        "m_complete_portfolio":       "Complete Reading Portfolio",
        "m_franchise_collector":      "Slime Franchise Collector",
        "m_serialization_follower":   "Serialization Tracker",
        "m_genre_master":             "Genre Mastery Earned",
        "m_multi_series_author":      "Multi-Series Author Fan",
        "m_format_diversity":         "Diverse Reading Formats",
        "m_year_dedication":          "Year of Dedicated Reading",
        "m_ongoing_follower":         "Ongoing Series Follower",
        "m_genre_loyalty_50":         "Fifty Genre Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer":           "Genre Territory Scout",
        "m_publisher_hopper":         "Publisher Nation Transfer",
        "m_tag_explorer":             "Manga Tag Recon Mission",
        "m_decade_hopper":            "Decade-Hopping via Great Sage",
        "m_hidden_gem":               "Hidden Jura Forest Gem",
        "m_popular_taste":            "Popular Among Slimes",
        "m_retro_reader":             "Retro Manuscript Appreciator",
        "m_modern_reader":            "Modern Era Slime Reader",
        "m_cross_demographic":        "Cross-Demographic Scout",
        "m_underdog_fan":             "Underdog Slime Fan",
        "m_variety_week":             "Week of Varied Readings",
        "m_manhwa_reader":            "Manhwa Intelligence Reader",
        "m_manhua_reader":            "Manhua Intelligence Reader",
        "m_classic_connoisseur":      "Classic Tempest Manuscript",
        "m_award_winner":             "Medal-Winning Manuscript",
        "m_niche_explorer":           "Niche Territory Reader",
        "m_world_manga":              "World Manga Intel",
        "m_cult_classic":             "Cult Classic Underground",
        "m_random_pick":              "Random Reading Assignment",
        "m_new_genre_month":          "New Genre Deployment Monthly",
        "m_year_completionist":       "Year Reading Completionist",
        "m_unpopular_opinion":        "Unpopular Slime Opinion",
        "m_top_rated_reader":         "Top-Rated Tempest Source",
        "m_source_variety":           "Source Material Variety",
        "m_low_score_brave":          "Brave Low-Score Reader",
        "m_short_manga_explorer":     "Short Manga Skirmish",
        "m_long_manga_explorer":      "Long Campaign Manuscript",
        "m_serialization_explorer":   "Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl":                "Night Owl Tempest Reader",
        "m_early_bird":               "Dawn Patrol Reader",
        "m_lunch_reader":             "Tempest Mess Hall Reader",
        "m_commute_reader":           "Travel to Kingdom Reader",
        "m_four_am_club":             "4 AM Sentry Reader",
        "m_new_year_read":            "New Year's Reading Oath",
        "m_all_hours":                "All-Hours Archive Access",
        "m_prime_time_reader":        "Prime Time Manuscript",
        "m_workday_reader":           "On-Duty Reader",
        "m_sunday_read":              "Sunday Reading Marathon",
        "m_morning_routine":          "Morning Formation Reading",
        "m_night_shift_reader":       "Night Shift Reader",
        "m_seasonal_premier_read":    "New Release Intel",
        "m_clock_collector":          "Rimuru's Clock Tower Reading",
        "m_late_night_horror":        "Midnight Demon Lord Horror Read",
        "m_afternoon_reader":         "Afternoon Kingdom Reading",
        "m_golden_hour_reader":       "Golden Hour Reading",
        "m_dawn_reader":              "Dawn Reading Scout",
        "m_twilight_reader":          "Twilight Kingdom Reading",
        "m_midnight_start":           "Midnight Reading Mission",
        "m_weekend_binge_hours":      "Weekend Binge Reading Ops",
        "m_late_night_regular":       "Late Night Regular Reader",
        "m_sunrise_reader":           "Sunrise Over Tempest Reader",
        "m_every_day_of_week":        "Every Day Reading Duty",
        "m_monthly_hours":            "Monthly Reading Hours Logged",
        "m_bedtime_reader":           "Bedtime Kingdom Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator":          "Tempest Art Appreciator",
        "m_webtoon_reader":           "Webtoon Intelligence",
        "m_full_color":               "Full Color Manuscript",
        "m_doujin_reader":            "Underground Doujin Reader",
        "m_anthology_reader":         "Anthology Collection Reader",
        "m_adaptation_reader":        "Adaptation Study Reader",
        "m_longstrip_reader":         "Vertical Scroll Reader",
        "m_4koma_reader":             "4-Koma Comedy Shorts",
        "m_oneshot_reader":           "Oneshot Mission Reader",
        "m_format_variety":           "Format Tactical Variety",
        "m_light_novel_reader":       "Light Novel Intel Reader",
        "m_novel_reader":             "Novel Archive Reader",
        "m_visual_storyteller":       "Visual Battle Narrator",
        "m_colored_classic":          "Colored Classic Manuscript",
        "m_webcomic_fan":             "Webcomic Underground Fan",
        "m_manga_to_anime":           "Manga to Anime Comparison",
        "m_seinen_reader":            "Seinen Tempest Reader",
        "m_josei_reader":             "Josei Perspective Reader",
        "m_award_winning_art":        "Medal-Winning Artwork",
        "m_debut_work":               "Debut Manuscript",
        "m_vertical_scroll":          "Vertical Scroll Intel",
        "m_traditional_format":       "Traditional Format Reader",
        "m_cross_media":              "Cross-Media Intelligence",
        "m_spinoff_reader":           "Spinoff Mission Reader",
        "m_remake_reader":            "Remake Reading Assignment",
        "m_collaboration_reader":     "Joint Operation Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak":             "Daily Slime Study",
        "m_mega_streak":              "Mega Reading Campaign Streak",
        "m_weekly_warrior":           "Weekly Warrior Reader",
        "m_monthly_reader":           "Monthly Kingdom Reader",
        "m_comeback":                 "Reader's Return from Tempest",
        "m_weekend_streak":           "Weekend Reading Streak",
        "m_no_zero_days":             "No Zero Reading Days",
        "m_iron_will":                "Iron Will Slime Reader",
        "m_habit_formed":             "Reading Regimen Formed",
        "m_consistent_pace":          "Consistent Reading Advance",
        "m_year_long":                "Year-Long Reading Campaign",
        "m_double_streak":            "Double Reading Streak",
        "m_streak_recovery":          "Reading Streak Recovery",
        "m_daily_minimum":            "Daily Minimum Pages",
        "m_winter_streak":            "Winter Reading Campaign",
        "m_summer_streak":            "Summer Reading Offensive",
        "m_morning_streak":           "Morning Reading Formation",
        "m_night_streak":             "Night Reading Patrol",
        "m_unbreakable":              "Unbreakable Reading Will",
        "m_eternal_flame":            "Eternal Flame of Knowledge",
        "m_chapter_a_day":            "Chapter a Day Discipline",
        "m_genre_streak":             "Genre Reading Streak",
        "m_completion_streak":        "Completion Reading Chain",
        "m_rating_streak":            "Rating Streak Filed",
        "m_multi_ch_streak":          "Multi-Chapter Streak",
        "m_author_streak":            "Author Dedication Streak",
        "m_perfect_week_manga":       "Perfect Reading Week",
        "m_diverse_streak":           "Diverse Reading Streak",

        // ── MANGA SCORING ──
        "m_critic":                   "Tempest Manuscript Critic",
        "m_perfect_ten":              "True Demon Lord Manga",
        "m_harsh_critic":             "Rimuru's Reading Standards",
        "m_fair_judge":               "Benimaru's Fair Review",
        "m_generous_spirit":          "Generous Reader Spirit",
        "m_score_all":                "Full Manuscript Assessment",
        "m_wide_range":               "Wide Range Scores",
        "m_controversial":            "Controversial Reading Opinion",
        "m_consistent_scorer":        "Consistent Manuscript Scorer",
        "m_score_sniper":             "Precision Score Sniper",
        "m_evolving_taste":           "Evolving Reading Taste",
        "m_bell_curve":               "Bell Curve of Scores",
        "m_picky_reader":             "Selective Demon Lord Reader",
        "m_100_rated":                "Century of Ratings Filed",
        "m_500_rated":                "Five Hundred Rating Reports",
        "m_mediocre_majority":        "Middle Ground Reader",
        "m_rating_spree":             "Rating Predation Barrage",
        "m_score_variance":           "Variable Manuscript Scores",
        "m_binge_rater":              "Binge Rating Session",
        "m_reread_rerate":            "Reread & Re-Rate Intel",
        "m_masterpiece_hunter":       "Masterpiece Slime Hunter",
        "m_contrarian":               "Contrarian Reader",
        "m_optimist":                 "Optimistic Slime Reader",
        "m_score_distributor":        "Score Distributor General",
        "m_genre_critic":             "Genre Slime Critic",
        "m_mean_above_8":             "Elite Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution":     "New Year's Reading Vow",
        "m_valentines_read":          "Valentine's Reading Bond",
        "m_pi_day":                   "Pi Day Chapter Count",
        "m_april_fools":              "April Fools Chibi Slime",
        "m_international_manga_day":  "International Manga Day",
        "m_free_comic_day":           "Free Comic Tempest Day",
        "m_summer_solstice":          "Summer Solstice Reading",
        "m_tanabata":                 "Tanabata Reading Wish",
        "m_friday_13th":              "Friday 13th Slime Manuscript",
        "m_halloween_read":           "Halloween Horror Reading",
        "m_thanksgiving_binge":       "Thanksgiving Reading Feast",
        "m_christmas_read":           "Midwinter Festival Reading",
        "m_new_years_eve":            "New Year's Eve Final Read",
        "m_birthday_read":            "Birthday Reading Gift",
        "m_holiday_marathon":         "Holiday Reading Marathon",
        "m_independence_day":         "Tempest Independence Reading",
        "m_culture_day":              "Culture Day Manuscript",
        "m_spring_equinox":           "Spring Equinox Reading",
        "m_earth_day":                "Earth Day Conservation Read",
        "m_labor_day":                "Kingdom Labor Reading Day",
        "m_winter_solstice":          "Winter Solstice Reading",
        "m_manga_birthday":           "Manga Birthday Celebration",
        "m_every_holiday_reader":     "Every Holiday Reader",
        "m_consecutive_holidays":     "Consecutive Holiday Reads",

        // ── MANGA SPECIAL ──
        "m_round_number":             "Round Number Milestone",
        "m_fibonacci":                "Fibonacci Slime Pattern",
        "m_palindrome_day":           "Palindrome Reading Day",
        "m_binary_day":               "Binary Signal Reading Day",
        "m_full_moon_read":           "Full Moon Slime Read",
        "m_leap_year_read":           "Leap Year Reading",
        "m_triple_seven":             "Triple Seven Slime Walls",
        "m_thousand_complete":        "Thousand Slime Victories",
        "m_nice":                     "Nice Chapter Count",
        "m_power_level_chapters":     "Rimuru-Level Chapters",
        "m_answer_42":                "Answer to Tempest's Reading",
        "m_square_number":            "Perfect Formation Chapters",
        "m_prime_count":              "Prime Chapter Count",
        "m_matching_date":            "Matching Tempest Reading Date",
        "m_century_chapter":          "Century Chapter Milestone",
        "m_pi_chapters":              "Pi Chapter Calculation",
        "m_synchronicity":            "Great Sage Reading Sync",
        "m_world_record":             "World Record Chapter Count",
        "m_genre_clash":              "Genre Clash Reading",
        "m_time_traveler":            "Time-Traveling Slime Reader",
        "m_double_digits":            "Double Digit Milestone",
        "m_one_two_three":            "Slime One Two Three",
        "m_lucky_seven":              "Seven Lucky Chapters",
        "m_exact_hundred_ch":         "Exact Hundred Chapters Read",
        "m_year_match_count":         "Year Match Chapter Count",
        "m_chapter_match_date":       "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format":             "Manga Format Specialist",
        "m_manhwa_format":            "Manhwa Format Reader",
        "m_manhua_format":            "Manhua Format Reader",
        "m_ln_format":                "Light Novel Format",
        "m_oneshot_format":           "Oneshot Format Operative",
        "m_doujin_format":            "Doujin Format Reader",
        "m_novel_format":             "Novel Format Reader",
        "m_format_master_manga":      "Format Master Reader",

        // ── MANGA META ──
        "m_meta_first_unlock":        "First Reading Power Unlocked",
        "m_meta_collector":           "Reading Badge Collector",
        "m_meta_category_starter":    "Category Initiation",
        "m_meta_tier_climber":        "Reading Rank Promotion",
        "m_meta_tier_max":            "Maximum Reading Rank",
        "m_meta_xp_earner":           "XP from Reading Intel",
        "m_meta_difficulty_easy":     "Easy Reading Exercise",
        "m_meta_difficulty_hard":     "Legendary Manuscript Challenge",
        "m_meta_unlock_spree":        "Reading Unlock Barrage",
        "m_meta_completionist":       "Meta Reading Completionist",
        "m_meta_diverse":             "Diverse Reading Portfolio",
        "m_meta_dominator":           "Meta Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg:        "#00100f",
        primary:   "#05a29e",
        secondary: "#3ad0cc",
        accent:    "#7b5fc0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/slime-isekai.jpg",
    particleColor: "#3088b0",
    backgroundDim: 0.30,
    backgroundBlur: 30,
    milestoneNames: {
        1:   "Slime",
        5:   "Named Monster",
        14:  "Goblin Lord Ally",
        26:  "Tempest Founder",
        40:  "Demon Lord Candidate",
        55:  "True Demon Lord",
        70:  "Wisdom King Rimuru",
        85:  "Slime God",
        100: "Beyond Demon Lord",
    },
}
