import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiSwordWound,
    GiChainedHeart,
    GiMuscleUp,
    GiCrossedSwords,
    GiHorseHead,
    GiFist,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const soloLevelingTheme: AnimeThemeConfig = {
    id: "solo-leveling",
    displayName: "Solo Leveling",
    description: "Arise. From E-Rank hunter to Shadow Monarch — dominate every dungeon gate with Jin-Woo's relentless power and a shadow army at your command.",
    fontFamily: "'Exo 2', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Exo+2:wght@400;600;700&display=swap",
    cssVars: {
        // Brand → deep sovereign purple
        "--color-brand-200": "220 170 255",
        "--color-brand-300": "195 130 255",
        "--color-brand-400": "155 70 235",
        "--color-brand-500": "102 0 204",
        "--color-brand-600": "82 0 168",
        "--color-brand-700": "62 0 130",
        "--color-brand-800": "42 0 90",
        "--color-brand-900": "25 0 55",
        "--color-brand-950": "12 0 28",
        "--brand": "102 0 204",
        // Abyss-dark background
        "--background": "#030108",
        "--paper": "#07020f",
        "--color-gray-950": "3 1 8",
        "--color-gray-900": "7 2 15",
        "--color-gray-800": "15 5 30",
        "--color-gray-700": "28 10 52",
        "--color-gray-600": "50 20 85",
        "--color-gray-500": "80 50 120",
        "--color-gray-400": "125 100 160",
        "--color-gray-300": "170 150 200",
        "--color-gray-200": "205 190 225",
        "--color-gray-100": "230 220 245",
        "--color-gray-50": "245 240 252",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Shadow Domain" },
        "schedule": { icon: GiAlarmClock, label: "Gate Schedule" },
        "manga": { icon: LuBookOpen, label: "Hunter's Codex" },
        "lists": { icon: GiCrossedSwords, label: "Hunter Registry" },
        "discover": { icon: GiBullseye, label: "Dungeon Scout" },
        "torrent-list": { icon: GiAnvilImpact, label: "Loot Cache" },
        "debrid": { icon: GiMuscleUp, label: "Shadow Reserves" },
        "unmatched": { icon: GiChainedHeart, label: "Unbound Soldiers" },
        "enmasse": { icon: GiResize, label: "Mass Summon" },
        "scan-summaries": { icon: TbReportSearch, label: "Dungeon Intel" },
        "auto-downloader": { icon: LuRss, label: "Gate Signals" },
        "community": { icon: GiEagleEmblem, label: "Hunter Guild" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "System Alerts" },
        "achievements": { icon: GiTrophy, label: "Shadow Titles" },
        "theme-manager": { icon: GiPalette, label: "Shadow Palette" },
        "extensions": { icon: BiExtension, label: "System Modules" },
        "sync": { icon: IoCloudOfflineOutline, label: "Shadow Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Command Hub" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Gate",
        "a_episode_counter": "Gate Clears",
        "a_episode_titan": "Monarch Encounter",
        "a_hours_invested": "Shadow Hours",
        "a_time_lord": "Time Monarch",
        "a_anime_collector": "Hunter Arsenal",
        "a_library_legend": "Shadow Archive",
        "a_first_complete": "First Clear",
        "a_hundred_club": "S-Rank Gate",
        "a_first_day": "Awakening Day",
        "a_first_rating": "Hunter Assessment",
        "a_ten_thousand_min": "Ten Thousand Minutes",
        "a_season_veteran": "Veteran Hunter",
        "a_year_explorer": "Year Explored",
        "a_century_watcher": "Century Hunts",
        "a_five_hundred_eps": "Five Hundred Gates",
        "a_thousand_eps": "Thousand Encounters",
        "a_watching_ten": "Ten Gates Open",
        "a_ptw_hoarder": "Gate Backlog",
        "a_dropped_honesty": "Strategic Retreat",
        "a_five_thousand_eps": "Five Thousand Gates",
        "a_ten_completed": "Ten Cleared",
        "a_fifty_completed": "Fifty Cleared",
        "a_five_hundred_completed": "Five Hundred Cleared",
        "a_mean_score_tracker": "Hunter Rating",
        "a_unique_studios": "Allied Guilds",
        "a_days_spent_watching": "Shadow Days",
        "a_all_status": "All Statuses",
        "a_first_favorite": "Shadow Bond",
        "a_favorites_collector": "Shadow Army",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Shadow Binge",
        "a_marathon_runner": "Gate Marathon",
        "a_weekend_warrior": "Weekend Hunter",
        "a_non_stop": "Relentless Hunt",
        "a_one_more_episode": "One More Gate",
        "a_speed_run": "Speed Clear",
        "a_double_feature": "Double Clear",
        "a_triple_threat": "Triple Gate",
        "a_five_a_day": "Five Daily",
        "a_back_to_back": "Chain Clear",
        "a_seasonal_binge": "Season Sweep",
        "a_cour_crusher": "Arc Crusher",
        "a_half_day_watch": "Half Day",
        "a_full_day_watch": "Full Day",
        "a_power_weekend": "Power Weekend",
        "a_binge_king": "Binge Monarch",
        "a_no_sleep": "No Sleep",
        "a_entire_season": "Full Season",
        "a_seven_day_challenge": "Seven Days",
        "a_hundred_day_binge": "Hundred Days",
        "a_genre_binge": "Genre Sweep",
        "a_studio_binge": "Guild Sweep",
        "a_season_sweep": "Season Cleared",
        "a_forty_eight_hour": "48 Hour Hunt",
        "a_ep_counter_day": "Daily Count",
        "a_multi_series_binge": "Multi-Gate",
        "a_midnight_binge": "Midnight Hunt",
        "a_new_year_binge": "New Year Hunt",

        // ── ANIME GENRES ──
        "a_genre_action": "Combat Training",
        "a_genre_adventure": "Gate Explorer",
        "a_genre_comedy": "Hunter Humor",
        "a_genre_drama": "Jin-Woo's Vow",
        "a_genre_fantasy": "Monarch Realm",
        "a_genre_horror": "Shadow Terror",
        "a_genre_mystery": "Hidden Gate",
        "a_genre_romance": "Hunter's Heart",
        "a_genre_scifi": "System Tech",
        "a_genre_sol": "Casual Hunter",
        "a_genre_sports": "Rank Battle",
        "a_genre_supernatural": "Shadow Power",
        "a_genre_thriller": "Gate Pursuit",
        "a_genre_mecha": "Iron Soldier",
        "a_genre_music": "Shadow Anthem",
        "a_genre_psychological": "Mental Fortitude",
        "a_genre_ecchi": "Off-Duty Hunter",
        "a_genre_mahou_shoujo": "System Wielder",
        "a_tag_isekai": "Another Realm",
        "a_tag_harem": "Squad Bonds",
        "a_tag_bl": "Brothers Hunt",
        "a_tag_gl": "Shield Sisters",
        "a_tag_historical": "Hunter History",
        "a_tag_military": "Hunter Corps",
        "a_tag_school": "Hunter Academy",
        "a_tag_martial_arts": "Hand Combat",
        "a_tag_vampire": "Shadow Blood",
        "a_tag_samurai": "Shadow Blade",
        "a_tag_space": "Celestial Gate",
        "a_tag_parody": "E-Rank Parody",
        "a_tag_idol": "Shadow Idol",
        "a_tag_post_apocalyptic": "Post-Gate World",
        "a_tag_cyberpunk": "System Punk",
        "a_tag_shounen": "Rise Up",
        "a_tag_seinen": "Dark Reality",
        "a_tag_shoujo": "Heart of Steel",
        "a_tag_josei": "Shadow Devotion",
        "a_tag_survival": "Gate Survival",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Report",
        "a_mega_completionist": "Shadow Monarch",
        "a_completion_rate_50": "Halfway There",
        "a_completion_rate_75": "B-Rank Clear",
        "a_completion_rate_90": "A-Rank Clear",
        "a_no_drop": "No Retreat",
        "a_long_runner_complete": "Long Campaign",
        "a_sequel_chain": "Chain Clear",
        "a_clean_list": "Clean Record",
        "a_from_ptw": "Orders Executed",
        "a_rewatch_master": "Shadow Replay",
        "a_short_complete": "Quick Clear",
        "a_same_day_start_finish": "Same-Day Clear",
        "a_revival": "Shadow Revival",
        "a_zero_to_hero": "E to S Rank",
        "a_five_genre_complete": "Five Cleared",
        "a_full_franchise": "Full Dossier",
        "a_batch_complete": "Batch Clear",
        "a_paused_to_done": "Returned Hunter",
        "a_completion_spree": "Clear Spree",
        "a_multi_rewatch": "Multi Replay",
        "a_dropped_recovery": "Recovered",
        "a_ten_perfect_scores": "Ten Perfect",
        "a_seasonal_clear": "Season Clear",
        "a_complete_genre_span": "All Terrain",
        "a_monthly_completions": "Monthly Clear",
        "a_yearly_completions": "Yearly Victor",
        "a_rapid_complete": "Rapid Clear",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Hunter",
        "a_studio_devotee": "Guild Devotee",
        "a_rewatcher": "Shadow Rewatch",
        "a_triple_rewatch": "Triple Replay",
        "a_annual_tradition": "Annual Hunt",
        "a_director_fan": "Vision Follower",
        "a_voice_actor_fan": "Voice Hunter",
        "a_ost_lover": "Shadow OST",
        "a_source_reader": "Source Material",
        "a_waiting_weekly": "Weekly Wait",
        "a_childhood_revisit": "Origin Return",
        "a_saga_tracker": "Saga Tracker",
        "a_genre_loyalty": "Guild Loyalty",
        "a_decade_watcher": "Decade Hunt",
        "a_adaptation_hunter": "Adaptation Scout",
        "a_original_anime_fan": "Original Fan",
        "a_long_commitment": "Long Service",
        "a_perfect_attendance": "Perfect Record",
        "a_favorite_studio_5": "Five Guilds",
        "a_complete_catalog": "Full Catalog",
        "a_franchise_collector": "Universe Collector",
        "a_airing_follower": "Live Intel",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Staff Tracker",
        "a_multi_season_fan": "Multi-Season",
        "a_format_diversity": "Diverse Formats",
        "a_year_dedication": "Year Dedicated",
        "a_season_dedication": "Season Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Territory Scout",
        "a_studio_hopper": "Guild Transfer",
        "a_tag_explorer": "Tag Recon",
        "a_decade_hopper": "Time Hop",
        "a_hidden_gem": "Hidden Gate",
        "a_popular_taste": "Popular Hunter",
        "a_retro_appreciator": "Retro Scout",
        "a_modern_viewer": "Modern Rank",
        "a_cross_demographic": "Cross Scout",
        "a_underdog_fan": "Underdog Spirit",
        "a_variety_week": "Varied Week",
        "a_foreign_cinema": "Foreign Gate",
        "a_classic_connoisseur": "Classic Hunter",
        "a_every_season": "All Seasons",
        "a_award_winner": "Valor Medal",
        "a_niche_explorer": "Niche Gate",
        "a_global_anime": "Global Hunt",
        "a_cult_classic": "Cult Gate",
        "a_random_pick": "Random Gate",
        "a_new_genre_month": "New Terrain",
        "a_seasonal_completionist": "Season Clear",
        "a_unpopular_opinion": "Solo Opinion",
        "a_top_rated_viewer": "Top Ranked",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Charge",
        "a_upcoming_watcher": "Upcoming Gate",
        "a_short_series_explorer": "Short Gate",
        "a_long_series_explorer": "Long Campaign",

        // ── ANIME TIME ──
        "a_night_owl": "Night Hunter",
        "a_early_bird": "Dawn Patrol",
        "a_lunch_break": "Lunch Gate",
        "a_golden_hour": "Golden Gate",
        "a_four_am_club": "4 AM Hunt",
        "a_witching_hour": "Shadow Hour",
        "a_new_year_watch": "New Year Hunt",
        "a_midnight_premiere": "Midnight Gate",
        "a_all_hours": "All Hours",
        "a_dawn_warrior": "Dawn Warrior",
        "a_afternoon_delight": "Afternoon Hunt",
        "a_prime_time": "Prime Time",
        "a_workday_watcher": "On-Duty",
        "a_sunday_marathon": "Sunday Marathon",
        "a_rainy_day": "Rainy Gate",
        "a_morning_routine": "Morning Hunt",
        "a_night_shift": "Night Shift",
        "a_twilight_zone": "Twilight Gate",
        "a_seasonal_premier": "Season Premiere",
        "a_clock_collector": "Time Collector",
        "a_weekend_binge_hours": "Weekend Hunt",
        "a_late_night_regular": "Night Regular",
        "a_sunrise_watcher": "Sunrise Hunt",
        "a_holiday_watcher": "Holiday Guard",
        "a_every_day_of_week": "Daily Hunter",
        "a_monthly_hours": "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Squad",
        "a_party_host": "Party Leader",
        "a_social_butterfly": "Guild Social",
        "a_group_binge": "Group Hunt",
        "a_party_regular": "Regular Partner",
        "a_sync_viewer": "Sync Hunt",
        "a_commentator": "Battle Comm",
        "a_party_marathon": "Marathon Party",
        "a_full_house": "Full Squad",
        "a_community_pillar": "Pillar Hunter",
        "a_watch_party_streak": "Party Streak",
        "a_diverse_party": "Diverse Squad",
        "a_late_night_party": "Late Night",
        "a_party_veteran": "Veteran Leader",
        "a_genre_party": "Cross-Genre Party",
        "a_weekly_party": "Weekly Party",
        "a_silent_viewer": "Silent Hunter",
        "a_recommendation_giver": "Commander's Call",
        "a_party_completionist": "Party Clear",
        "a_social_scorer": "Social Score",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number",
        "a_fibonacci": "Shadow Sequence",
        "a_palindrome_day": "Time Rift",
        "a_binary_day": "Binary Gate",
        "a_full_moon": "Moon Gate",
        "a_leap_year": "Leap Year",
        "a_time_traveler": "Time Travel",
        "a_genre_clash": "Gate Clash",
        "a_triple_seven": "777 Gates",
        "a_thousand_complete": "Thousand Cleared",
        "a_pi_episodes": "Pi Gates",
        "a_synchronicity": "Shadow Sync",
        "a_world_record": "World Record",
        "a_nice": "Nice Count",
        "a_power_level": "Power Level",
        "a_answer_42": "Shadow 42",
        "a_square_number": "Perfect Square",
        "a_prime_count": "Prime Gates",
        "a_matching_date": "Date Match",
        "a_century_episode": "Century Gate",
        "a_double_digits": "Double Digits",
        "a_one_two_three": "E D C Rank",
        "a_lucky_seven": "Lucky Seven",
        "a_all_tens": "All Tens",
        "a_exact_hundred_eps": "Hundred Gates",
        "a_year_match_count": "Year Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Scout",
        "a_movie_buff": "Gate Movie",
        "a_ova_hunter": "OVA Hunter",
        "a_ona_explorer": "ONA Scout",
        "a_special_watcher": "Special Op",
        "a_short_king": "Short Gate",
        "a_variety_pack": "All Formats",
        "a_film_festival": "Gate Festival",
        "a_music_video": "Shadow MV",
        "a_tv_short": "Quick Recon",
        "a_movie_marathon": "Movie Marathon",
        "a_double_length": "Double Length",
        "a_anthology": "Shadow Anthology",
        "a_mini_series": "Mini Campaign",
        "a_theatrical": "Theater Gate",
        "a_format_master": "Format Master",
        "a_long_movie": "Feature Gate",
        "a_back_catalog": "Back Catalog",
        "a_cm_watcher": "Commercial Break",
        "a_pv_collector": "Preview Signal",
        "a_format_balance": "Balanced Formats",
        "a_episodic_master": "Episodic Master",
        "a_sequel_movie": "Sequel Film",
        "a_recap_watcher": "Recap Brief",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Streak",
        "a_mega_streak": "Shadow Streak",
        "a_weekly_warrior": "Weekly Warrior",
        "a_monthly_watcher": "Monthly Hunt",
        "a_comeback": "Gate Return",
        "a_weekend_streak": "Weekend Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will",
        "a_habit_formed": "Hunt Habit",
        "a_consistent_pace": "Steady Pace",
        "a_year_long": "Year Long",
        "a_double_streak": "Double Streak",
        "a_streak_recovery": "Streak Revival",
        "a_daily_minimum": "Daily Minimum",
        "a_winter_streak": "Winter Hunt",
        "a_summer_streak": "Summer Hunt",
        "a_morning_streak": "Morning Streak",
        "a_night_streak": "Night Streak",
        "a_unbreakable": "Unbreakable",
        "a_eternal_flame": "Eternal Shadow",
        "a_completion_streak": "Clear Chain",
        "a_rating_streak": "Rating Chain",
        "a_multi_ep_streak": "Multi-Gate Streak",
        "a_genre_streak": "Genre Chain",
        "a_studio_streak": "Guild Streak",
        "a_perfect_week": "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic": "Shadow Critic",
        "a_perfect_ten": "Perfect Ten",
        "a_harsh_critic": "Harsh Judge",
        "a_fair_judge": "Fair Assessment",
        "a_generous_spirit": "Generous Hunter",
        "a_score_all": "Full Roster",
        "a_wide_range": "Wide Range",
        "a_controversial": "Solo Opinion",
        "a_consistent_scorer": "Consistent Score",
        "a_score_sniper": "Precision Score",
        "a_evolving_taste": "Evolving Rank",
        "a_bell_curve": "Bell Curve",
        "a_picky_watcher": "Selective Hunter",
        "a_100_rated": "Century Rated",
        "a_500_rated": "Five Hundred",
        "a_mediocre_majority": "Middle Ground",
        "a_rating_spree": "Score Barrage",
        "a_score_variance": "Variable Scores",
        "a_masterpiece_hunter": "Masterpiece Hunt",
        "a_contrarian": "Solo Path",
        "a_optimist": "Hopeful Hunter",
        "a_score_distributor": "Score General",
        "a_genre_critic": "Genre Critic",
        "a_mean_above_8": "Elite Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow",
        "a_valentines_weeb": "Valentine Hunt",
        "a_pi_day": "Pi Day",
        "a_april_fools": "April Gate",
        "a_international_anime_day": "Hunter Day",
        "a_star_wars_day": "Monarch Empire",
        "a_summer_solstice": "Summer Gate",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Shadow Friday",
        "a_halloween_spirit": "Halloween Hunt",
        "a_thanksgiving_binge": "Harvest Feast",
        "a_christmas_special": "Winter Gate",
        "a_new_years_eve": "Final Hunt",
        "a_birthday_watch": "Birthday Hunt",
        "a_holiday_marathon": "Holiday Hunt",
        "a_independence_day": "Freedom Gate",
        "a_culture_day": "Culture Hunt",
        "a_spring_equinox": "Spring Gate",
        "a_earth_day": "Earth Gate",
        "a_labor_day": "Labor Gate",
        "a_winter_solstice": "Winter Solstice",
        "a_anime_birthday": "Anime Birthday",
        "a_every_holiday": "All Holidays",
        "a_consecutive_holidays": "Holiday Chain",

        // ── ANIME META ──
        "a_meta_first_unlock": "System Awakened",
        "a_meta_collector": "Badge Collector",
        "a_meta_category_starter": "Rank Initiate",
        "a_meta_tier_climber": "Rank Climber",
        "a_meta_tier_max": "S-Rank Hunter",
        "a_meta_xp_earner": "XP Gained",
        "a_meta_difficulty_easy": "Easy Mode",
        "a_meta_difficulty_hard": "Monarch Level",
        "a_meta_unlock_spree": "Unlock Spree",
        "a_meta_completionist": "Meta Complete",
        "a_meta_diverse": "Diverse Hunt",
        "a_meta_dominator": "Shadow Dominant",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter",
        "m_chapter_counter": "Chapter Count",
        "m_chapter_titan": "Monarch Chapter",
        "m_reading_hours": "Reading Hours",
        "m_reading_time_lord": "Time Monarch",
        "m_manga_collector": "Shadow Archive",
        "m_library_legend": "Library Legend",
        "m_first_complete": "First Clear",
        "m_hundred_club": "Hundred Club",
        "m_first_day": "First Day",
        "m_first_rating": "First Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Cache",
        "m_year_explorer": "Year Read",
        "m_century_reader": "Century Reader",
        "m_five_hundred_ch": "Five Hundred",
        "m_thousand_ch": "Thousand Read",
        "m_reading_ten": "Ten Active",
        "m_ptr_hoarder": "Reading Backlog",
        "m_dropped_honesty": "Honest Retreat",
        "m_season_reader": "Season Reader",
        "m_active_reader": "Active Scout",
        "m_five_thousand_ch": "Five Thousand",
        "m_ten_completed": "Ten Complete",
        "m_fifty_completed": "Fifty Done",
        "m_five_hundred_completed": "Five Hundred Done",
        "m_mean_score_tracker": "Mean Score",
        "m_unique_authors": "Unique Authors",
        "m_all_status": "All Statuses",
        "m_first_favorite": "First Favorite",
        "m_favorites_collector": "Favorites Cache",
        "m_days_spent_reading": "Shadow Days",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reader",
        "m_marathon_reader": "Gate Marathon",
        "m_weekend_reader": "Weekend Reader",
        "m_non_stop_reading": "Non-Stop Read",
        "m_one_more_chapter": "One More",
        "m_speed_read": "Speed Read",
        "m_double_story": "Double Read",
        "m_triple_read": "Triple Read",
        "m_five_a_day": "Five Daily",
        "m_chapter_chain": "Chapter Chain",
        "m_volume_binge": "Volume Binge",
        "m_power_reader": "Power Reader",
        "m_half_day_read": "Half Day",
        "m_full_day_read": "Full Day",
        "m_power_weekend": "Power Weekend",
        "m_binge_king": "Read Monarch",
        "m_no_sleep_read": "No Sleep",
        "m_full_series_rush": "Full Rush",
        "m_seven_day_challenge": "Seven Days",
        "m_hundred_day_read": "Hundred Days",
        "m_volume_rush": "Volume Rush",
        "m_series_sweep": "Series Sweep",
        "m_genre_binge": "Genre Sweep",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Count",
        "m_multi_series_binge": "Multi-Series",
        "m_midnight_binge": "Midnight Read",
        "m_new_year_binge": "New Year Read",
        "m_forty_eight_hour": "48 Hour Read",
        "m_oneshot_binge": "Oneshot Blitz",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Reader",
        "m_genre_adventure": "Gate Explorer",
        "m_genre_comedy": "Hunter Humor",
        "m_genre_drama": "Shadow Drama",
        "m_genre_fantasy": "Monarch Fantasy",
        "m_genre_horror": "Gate Horror",
        "m_genre_mystery": "Hidden Gate",
        "m_genre_romance": "Hunter Romance",
        "m_genre_scifi": "System Sci-Fi",
        "m_genre_sol": "Daily Life",
        "m_genre_sports": "Rank Sports",
        "m_genre_supernatural": "Shadow Power",
        "m_genre_thriller": "Gate Thriller",
        "m_genre_psychological": "Mental Fortitude",
        "m_genre_isekai": "Another World",
        "m_genre_shounen": "Rise Up",
        "m_genre_ecchi": "Off Duty",
        "m_genre_mahou_shoujo": "System User",
        "m_genre_mecha": "Iron Guard",
        "m_genre_music": "Shadow Song",
        "m_tag_isekai_new": "New World",
        "m_tag_harem": "Squad Bond",
        "m_tag_bl": "Brothers Hunt",
        "m_tag_gl": "Shield Sisters",
        "m_tag_historical": "Hunter History",
        "m_tag_military": "Hunter Corps",
        "m_tag_school": "Hunter Academy",
        "m_tag_martial_arts": "Hand Combat",
        "m_tag_vampire": "Shadow Blood",
        "m_tag_samurai": "Blade Master",
        "m_tag_space": "Celestial Gate",
        "m_tag_parody": "Hunter Parody",
        "m_tag_idol": "Shadow Idol",
        "m_tag_post_apocalyptic": "Post-Gate",
        "m_tag_cyberpunk": "System Punk",
        "m_tag_shoujo": "Hunter Heart",
        "m_tag_survival": "Gate Survival",
        "m_tag_cooking": "Hunter Rations",
        "m_tag_medical": "Field Medic",
        "m_tag_villainess": "Warrior Candidate",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Complete",
        "m_mega_completionist": "Shadow Monarch",
        "m_completion_rate_50": "Halfway Clear",
        "m_completion_rate_75": "B-Rank Clear",
        "m_completion_rate_90": "A-Rank Clear",
        "m_no_drop": "No Retreat",
        "m_long_runner_complete": "Long Endurance",
        "m_sequel_chain": "Chain Clear",
        "m_clean_list": "Clean Record",
        "m_from_ptr": "Ordered Read",
        "m_reread_master": "Shadow Reread",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Clear",
        "m_revival": "Shadow Revival",
        "m_zero_to_hundred": "E to S Rank",
        "m_five_genre_complete": "Five Genres",
        "m_full_collection": "Full Archive",
        "m_batch_complete": "Batch Clear",
        "m_paused_to_done": "Back Active",
        "m_completion_spree": "Clear Spree",
        "m_format_completionist": "Format Done",
        "m_catch_up": "Caught Up",
        "m_multi_reread": "Multi Reread",
        "m_dropped_recovery": "Recovered",
        "m_ten_perfect_scores": "Ten Perfect",
        "m_complete_genre_span": "All Genres",
        "m_monthly_completions": "Monthly Done",
        "m_yearly_completions": "Yearly Clear",
        "m_rapid_complete": "Rapid Clear",
        "m_author_complete": "Author Done",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Reader",
        "m_mangaka_lover": "Mangaka Devotee",
        "m_rereader": "Shadow Reread",
        "m_triple_reread": "Triple Reread",
        "m_annual_reread": "Annual Reread",
        "m_publisher_fan": "Publisher Fan",
        "m_artist_fan": "Artist Fan",
        "m_adaptation_compare": "Compare Intel",
        "m_source_material_fan": "Source Scout",
        "m_waiting_weekly": "Weekly Wait",
        "m_classic_reader": "Classic Reader",
        "m_saga_reader": "Saga Reader",
        "m_genre_loyalty": "Genre Loyal",
        "m_decade_reader": "Decade Reader",
        "m_ln_adaptation": "LN Adaptation",
        "m_original_work": "Original Work",
        "m_long_commitment": "Long Service",
        "m_up_to_date": "Up to Date",
        "m_favorite_mangaka": "Fave Mangaka",
        "m_complete_portfolio": "Full Portfolio",
        "m_franchise_collector": "Universe Collector",
        "m_serialization_follower": "Serial Tracker",
        "m_genre_master": "Genre Master",
        "m_multi_series_author": "Multi-Series",
        "m_format_diversity": "Diverse Formats",
        "m_year_dedication": "Year Dedicated",
        "m_ongoing_follower": "Ongoing Scout",
        "m_genre_loyalty_50": "Fifty Loyal",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Scout",
        "m_publisher_hopper": "Publisher Hop",
        "m_tag_explorer": "Tag Recon",
        "m_decade_hopper": "Decade Hop",
        "m_hidden_gem": "Hidden Gem",
        "m_popular_taste": "Popular Pick",
        "m_retro_reader": "Retro Reader",
        "m_modern_reader": "Modern Reader",
        "m_cross_demographic": "Cross Scout",
        "m_underdog_fan": "Underdog Fan",
        "m_variety_week": "Varied Week",
        "m_manhwa_reader": "Manhwa Scout",
        "m_manhua_reader": "Manhua Scout",
        "m_classic_connoisseur": "Classic Read",
        "m_award_winner": "Award Winner",
        "m_niche_explorer": "Niche Gate",
        "m_world_manga": "World Manga",
        "m_cult_classic": "Cult Read",
        "m_random_pick": "Random Pick",
        "m_new_genre_month": "New Genre",
        "m_year_completionist": "Year Reader",
        "m_unpopular_opinion": "Solo View",
        "m_top_rated_reader": "Top Ranked",
        "m_source_variety": "Source Variety",
        "m_low_score_brave": "Brave Reader",
        "m_short_manga_explorer": "Short Manga",
        "m_long_manga_explorer": "Long Manga",
        "m_serialization_explorer": "Serial Scout",

        // ── MANGA TIME ──
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
        "m_lunch_reader": "Lunch Read",
        "m_commute_reader": "Commute Read",
        "m_four_am_club": "4 AM Read",
        "m_new_year_read": "New Year Read",
        "m_all_hours": "All Hours",
        "m_prime_time_reader": "Prime Time",
        "m_workday_reader": "On-Duty Read",
        "m_sunday_read": "Sunday Read",
        "m_morning_routine": "Morning Read",
        "m_night_shift_reader": "Night Shift",
        "m_seasonal_premier_read": "New Release",
        "m_clock_collector": "Time Collector",
        "m_late_night_horror": "Late Night",
        "m_afternoon_reader": "Afternoon Read",
        "m_golden_hour_reader": "Golden Hour",
        "m_dawn_reader": "Dawn Read",
        "m_twilight_reader": "Twilight Read",
        "m_midnight_start": "Midnight Start",
        "m_weekend_binge_hours": "Weekend Read",
        "m_late_night_regular": "Night Regular",
        "m_sunrise_reader": "Sunrise Read",
        "m_every_day_of_week": "Daily Reader",
        "m_monthly_hours": "Monthly Hours",
        "m_bedtime_reader": "Bedtime Read",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Fan",
        "m_webtoon_reader": "Webtoon Scout",
        "m_full_color": "Full Color",
        "m_doujin_reader": "Shadow Doujin",
        "m_anthology_reader": "Anthology Read",
        "m_adaptation_reader": "Adapt Scout",
        "m_longstrip_reader": "Long Strip",
        "m_4koma_reader": "4-Koma Read",
        "m_oneshot_reader": "Oneshot Scout",
        "m_format_variety": "Format Variety",
        "m_light_novel_reader": "LN Scout",
        "m_novel_reader": "Novel Scout",
        "m_visual_storyteller": "Visual Narrator",
        "m_colored_classic": "Colored Classic",
        "m_webcomic_fan": "Webcomic Fan",
        "m_manga_to_anime": "Manga to Anime",
        "m_seinen_reader": "Seinen Scout",
        "m_josei_reader": "Josei Scout",
        "m_award_winning_art": "Award Art",
        "m_debut_work": "Debut Work",
        "m_vertical_scroll": "Vertical Scroll",
        "m_traditional_format": "Traditional Read",
        "m_cross_media": "Cross Media",
        "m_spinoff_reader": "Spinoff Scout",
        "m_remake_reader": "Remake Scout",
        "m_collaboration_reader": "Joint Read",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Streak",
        "m_mega_streak": "Shadow Streak",
        "m_weekly_warrior": "Weekly Warrior",
        "m_monthly_reader": "Monthly Read",
        "m_comeback": "Read Return",
        "m_weekend_streak": "Weekend Streak",
        "m_no_zero_days": "No Zero Days",
        "m_iron_will": "Iron Will",
        "m_habit_formed": "Read Habit",
        "m_consistent_pace": "Steady Pace",
        "m_year_long": "Year Long",
        "m_double_streak": "Double Streak",
        "m_streak_recovery": "Streak Revival",
        "m_daily_minimum": "Daily Min",
        "m_winter_streak": "Winter Streak",
        "m_summer_streak": "Summer Streak",
        "m_morning_streak": "Morning Streak",
        "m_night_streak": "Night Streak",
        "m_unbreakable": "Unbreakable",
        "m_eternal_flame": "Eternal Shadow",
        "m_chapter_a_day": "Chapter Daily",
        "m_genre_streak": "Genre Streak",
        "m_completion_streak": "Clear Chain",
        "m_rating_streak": "Rating Chain",
        "m_multi_ch_streak": "Multi-Chapter",
        "m_author_streak": "Author Streak",
        "m_perfect_week_manga": "Perfect Week",
        "m_diverse_streak": "Diverse Streak",

        // ── MANGA SCORING ──
        "m_critic": "Shadow Critic",
        "m_perfect_ten": "Perfect Ten",
        "m_harsh_critic": "Harsh Judge",
        "m_fair_judge": "Fair Review",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Full Assessment",
        "m_wide_range": "Wide Range",
        "m_controversial": "Solo Opinion",
        "m_consistent_scorer": "Consistent Score",
        "m_score_sniper": "Score Sniper",
        "m_evolving_taste": "Evolving Rank",
        "m_bell_curve": "Bell Curve",
        "m_picky_reader": "Selective Reader",
        "m_100_rated": "Century Rated",
        "m_500_rated": "Five Hundred",
        "m_mediocre_majority": "Middle Ground",
        "m_rating_spree": "Score Spree",
        "m_score_variance": "Variable Scores",
        "m_binge_rater": "Binge Rate",
        "m_reread_rerate": "Reread Rerate",
        "m_masterpiece_hunter": "Masterpiece Hunt",
        "m_contrarian": "Solo Path",
        "m_optimist": "Hopeful Reader",
        "m_score_distributor": "Score General",
        "m_genre_critic": "Genre Critic",
        "m_mean_above_8": "Elite Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Vow",
        "m_valentines_read": "Valentine Read",
        "m_pi_day": "Pi Day",
        "m_april_fools": "April Fools",
        "m_international_manga_day": "Manga Day",
        "m_free_comic_day": "Free Comic",
        "m_summer_solstice": "Summer Read",
        "m_tanabata": "Tanabata Read",
        "m_friday_13th": "Shadow Friday",
        "m_halloween_read": "Halloween Read",
        "m_thanksgiving_binge": "Feast Read",
        "m_christmas_read": "Winter Read",
        "m_new_years_eve": "Final Read",
        "m_birthday_read": "Birthday Read",
        "m_holiday_marathon": "Holiday Read",
        "m_independence_day": "Freedom Read",
        "m_culture_day": "Culture Read",
        "m_spring_equinox": "Spring Read",
        "m_earth_day": "Earth Day",
        "m_labor_day": "Labor Read",
        "m_winter_solstice": "Winter Read",
        "m_manga_birthday": "Manga Birthday",
        "m_every_holiday_reader": "All Holidays",
        "m_consecutive_holidays": "Holiday Chain",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number",
        "m_fibonacci": "Shadow Sequence",
        "m_palindrome_day": "Palindrome Day",
        "m_binary_day": "Binary Gate",
        "m_full_moon_read": "Moon Gate",
        "m_leap_year_read": "Leap Year",
        "m_triple_seven": "Triple Seven",
        "m_thousand_complete": "Thousand Done",
        "m_nice": "Nice Count",
        "m_power_level_chapters": "Power Level",
        "m_answer_42": "Shadow 42",
        "m_square_number": "Perfect Square",
        "m_prime_count": "Prime Count",
        "m_matching_date": "Date Match",
        "m_century_chapter": "Century Read",
        "m_pi_chapters": "Pi Chapters",
        "m_synchronicity": "Shadow Sync",
        "m_world_record": "World Record",
        "m_genre_clash": "Genre Clash",
        "m_time_traveler": "Time Travel",
        "m_double_digits": "Double Digits",
        "m_one_two_three": "One Two Three",
        "m_lucky_seven": "Lucky Seven",
        "m_exact_hundred_ch": "Exact Hundred",
        "m_year_match_count": "Year Count",
        "m_chapter_match_date": "Chapter Date",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format",
        "m_manhwa_format": "Manhwa Read",
        "m_manhua_format": "Manhua Read",
        "m_ln_format": "LN Format",
        "m_oneshot_format": "Oneshot Read",
        "m_doujin_format": "Doujin Read",
        "m_novel_format": "Novel Read",
        "m_format_master_manga": "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock": "System Unlocked",
        "m_meta_collector": "Badge Collector",
        "m_meta_category_starter": "Rank Initiate",
        "m_meta_tier_climber": "Rank Climber",
        "m_meta_tier_max": "S-Rank Reader",
        "m_meta_xp_earner": "XP Gained",
        "m_meta_difficulty_easy": "Easy Mode",
        "m_meta_difficulty_hard": "Monarch Level",
        "m_meta_unlock_spree": "Unlock Spree",
        "m_meta_completionist": "Meta Complete",
        "m_meta_diverse": "Diverse Reads",
        "m_meta_dominator": "Read Dominant",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030108",
        primary: "#6600cc",
        secondary: "#4d0099",
        accent: "#b300ff",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/solo-leveling.png",
    backgroundDim: 0.30,
    backgroundBlur: 30,
    particleColor: "#4060d0",
    particleTypes: {
        shadow_soldiers: { label: "Shadow Soldiers", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        purple_mist: { label: "Purple Mist", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        gate_sparks: { label: "Gate Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        level_up: { label: "Level Up", maxCount: 6, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1:   "E-Rank",
        5:   "D-Rank",
        15:  "C-Rank",
        30:  "B-Rank",
        45:  "A-Rank",
        60:  "S-Rank",
        80:  "Shadow Commander",
        100: "Strongest Human",
    },
}
