import { AnimeThemeConfig } from "./types"
import { GiSteam, GiPotionBall, GiSpellBook, GiMagicSwirl, GiWaves, GiCrystalBall, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiCrossedSwords } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const spiritedAwayTheme: AnimeThemeConfig = {
    id: "spirited-away",
    displayName: "Spirited Away",
    description: "Welcome to the spirit world. Work hard, keep your name, and find your way back. The bathhouse awaits.",
    fontFamily: "'Pacifico', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Pacifico&display=swap",
    cssVars: {
        "--color-brand-200": "235 180 120",
        "--color-brand-300": "220 155 65",
        "--color-brand-400": "210 130 25",
        "--color-brand-500": "204 102 0",
        "--color-brand-600": "178 88 0",
        "--color-brand-700": "145 70 0",
        "--color-brand-800": "105 50 0",
        "--color-brand-900": "68 32 0",
        "--color-brand-950": "38 18 0",
        "--brand": "204 102 0",
        "--background": "#050402",
        "--paper": "#0d0b06",
        "--color-gray-950": "5 4 2",
        "--color-gray-900": "13 11 6",
        "--color-gray-800": "24 20 12",
        "--color-gray-700": "40 34 20",
        "--color-gray-600": "62 54 38",
        "--color-gray-500": "92 82 60",
        "--color-gray-400": "135 122 94",
        "--color-gray-300": "170 158 130",
        "--color-gray-200": "202 192 168",
        "--color-gray-100": "226 220 204",
        "--color-gray-50": "244 240 232",
    },
    sidebarOverrides: {
        "home": { icon: GiSteam, label: "Bathhouse Entrance" },
        "schedule": { icon: GiAlarmClock, label: "Spirit World Schedule" },
        "manga": { icon: LuBookOpen, label: "Yubaba's Archive" },
        "lists": { icon: GiSpellBook, label: "Spirit Registry" },
        "discover": { icon: GiWaves, label: "Beyond the River" },
        "torrent-list": { icon: GiPotionBall, label: "Boiler Room Drops" },
        "debrid": { icon: GiCrystalBall, label: "Zeniba's Cottage" },
        "unmatched": { icon: GiMagicSwirl, label: "Lost Spirits" },
        "enmasse": { icon: GiCrossedSwords, label: "Mass Cleansing" },
        "scan-summaries": { icon: TbReportSearch, label: "Spirit Reports" },
        "auto-downloader": { icon: LuRss, label: "Soot Sprite Signal" },
        "community": { icon: GiPotionBall, label: "Spirit Community" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Bathhouse Bell" },
        "achievements": { icon: GiTrophy, label: "Spirit Seals" },
        "theme-manager": { icon: GiPalette, label: "Spirit Colors" },
        "extensions": { icon: BiExtension, label: "Magic Attachments" },
        "sync": { icon: IoCloudOfflineOutline, label: "River Spirit Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Yubaba's Office" },
    },
    achievementNames: {
        "a_first_episode": "First Step Into the Spirit World",
        "a_episode_counter": "Soot Sprite Work Tally",
        "a_episode_titan": "Spirit Realm Immersion",
        "a_hours_invested": "Hours Toiling in the Bathhouse",
        "a_time_lord": "Haku's River Memory",
        "a_anime_collector": "Spirit World Collection",
        "a_library_legend": "Yubaba's Spell Archive",
        "a_first_complete": "First Journey Complete",
        "a_hundred_club": "Hundred Spirits Served",
        "a_first_day": "First Day at Work",
        "a_first_rating": "Chihiro's First Review",
        "a_ten_thousand_min": "Ten Thousand Minutes in the Baths",
        "a_season_veteran": "Seasoned Bathhouse Worker",
        "a_year_explorer": "Year in the Spirit World",
        "a_century_watcher": "Hundred Spirits Watched Over",
        "a_five_hundred_eps": "Five Hundred Spirit Encounters",
        "a_thousand_eps": "Thousand Bathhouse Duties",
        "a_watching_ten": "Ten Spirits Simultaneously Served",
        "a_ptw_hoarder": "Spirit Queue Hoarder",
        "a_dropped_honesty": "Strategic Retreat from Yubaba",
        "a_five_thousand_eps": "Five Thousand Spirit Services",
        "a_ten_completed": "Ten Journeys Completed",
        "a_fifty_completed": "Fifty Spirit Contracts Fulfilled",
        "a_five_hundred_completed": "Five Hundred River Crossings",
        "a_mean_score_tracker": "Average Spirit Rating",
        "a_unique_studios": "Diverse Spirit Encounters",
        "a_days_spent_watching": "Days in the Spirit Realm",
        "a_all_status": "All Spirit Statuses Known",
        "a_first_favorite": "First Spirit Bond",
        "a_favorites_collector": "Spirit Friends Collected",
        "a_binge_watcher": "Non-Stop Bathhouse Shift",
        "a_marathon_runner": "Endless Spirit World Marathon",
        "a_weekend_warrior": "Weekend Bathhouse Duty",
        "a_non_stop": "Relentless Spirit Service",
        "a_one_more_episode": "One More Spirit Encounter",
        "a_speed_run": "No-Face Gold Rush",
        "a_double_feature": "Double Spirit Service",
        "a_triple_threat": "Triple Bath Duty",
        "a_five_a_day": "Five Spirits Served Daily",
        "a_back_to_back": "Back-to-Back Spirit Shifts",
        "a_seasonal_binge": "Full Spirit Season",
        "a_cour_crusher": "Bathhouse Wing Cleaner",
        "a_half_day_watch": "Half-Day Spirit Shift",
        "a_full_day_watch": "Full Day in the Baths",
        "a_power_weekend": "Power Weekend Spirit Binge",
        "a_binge_king": "Master of the Bathhouse",
        "a_no_sleep": "All-Night Spirit Service",
        "a_entire_season": "Entire Spirit Season Clear",
        "a_seven_day_challenge": "Seven-Day Spirit Contract",
        "a_hundred_day_binge": "Hundred-Day Bathhouse Shift",
        "a_genre_binge": "Cross-Realm Spirit Binge",
        "a_studio_binge": "Studio Ghibli Devotion",
        "a_season_sweep": "Spirit Season Sweep",
        "a_forty_eight_hour": "Forty-Eight Hour Spirit Shift",
        "a_ep_counter_day": "Daily Spirit Encounter",
        "a_multi_series_binge": "Multi-Realm Spirit Journey",
        "a_midnight_binge": "Midnight in the Spirit World",
        "a_new_year_binge": "New Year Spirit Crossing",
        "a_genre_action": "Spirit World Action",
        "a_genre_adventure": "Beyond the Spirit Gate",
        "a_genre_comedy": "No-Face's Antics",
        "a_genre_drama": "Chihiro's Tears",
        "a_genre_fantasy": "Spirit Realm Fantasy",
        "a_genre_horror": "Yubaba's Terror",
        "a_genre_mystery": "Mystery of the River Spirit",
        "a_genre_romance": "Haku and Chihiro's Bond",
        "a_genre_scifi": "Spirit World Technology",
        "a_genre_sol": "Bathhouse Daily Life",
        "a_genre_sports": "Spirit Relay Race",
        "a_genre_supernatural": "Spirit World Powers",
        "a_genre_thriller": "Escape from Yubaba",
        "a_genre_mecha": "Dragon Form Haku",
        "a_genre_music": "Spirited Away Soundtrack",
        "a_genre_psychological": "Chihiro's Inner Strength",
        "a_genre_ecchi": "Hot Spring Spirits",
        "a_genre_mahou_shoujo": "Chihiro's Courage Magic",
        "a_tag_isekai": "Transported to Spirit World",
        "a_tag_harem": "Spirit Court Gathering",
        "a_tag_bl": "Spirit Brotherhood",
        "a_tag_gl": "Spirit Sisterhood",
        "a_tag_historical": "Ancient Spirit History",
        "a_tag_military": "Bathhouse Discipline",
        "a_tag_school": "Spirit World Education",
        "a_tag_martial_arts": "Spirit Combat Arts",
        "a_tag_vampire": "Spirit Consumption Power",
        "a_tag_samurai": "Spirit Warrior Style",
        "a_tag_space": "Beyond the Spirit Realm",
        "a_tag_parody": "Soot Sprite Comedy",
        "a_tag_idol": "Bathhouse Star Performer",
        "a_tag_post_apocalyptic": "After Yubaba's Rule",
        "a_tag_cyberpunk": "Spirit World Technology",
        "a_tag_shounen": "Chihiro's Brave Heart",
        "a_tag_seinen": "Adult Spirit World Reality",
        "a_tag_shoujo": "Chihiro's Devotion",
        "a_tag_josei": "Lin's Perspective",
        "a_tag_survival": "Survive the Spirit World",
        "a_completionist": "Complete Spirit Registry",
        "a_mega_completionist": "Grand Spirit Overseer",
        "a_completion_rate_50": "Halfway to Yubaba's Office",
        "a_completion_rate_75": "Approaching the River",
        "a_completion_rate_90": "Almost Home",
        "a_no_drop": "Never Abandoned a Spirit",
        "a_long_runner_complete": "Long Bathhouse Contract",
        "a_sequel_chain": "Spirit World Chain",
        "a_clean_list": "Clean Spirit Contract",
        "a_from_ptw": "Spirit Orders Executed",
        "a_rewatch_master": "Spirit Memory Replay",
        "a_short_complete": "Quick Spirit Encounter",
        "a_same_day_start_finish": "Same-Day Spirit Crossing",
        "a_revival": "Revived by River Spirit",
        "a_zero_to_hero": "Bathhouse Newbie to Expert",
        "a_five_genre_complete": "Five Spirit Realms Mastered",
        "a_full_franchise": "Complete Ghibli Universe",
        "a_batch_complete": "Batch Spirit Contracts Done",
        "a_paused_to_done": "Returned from Hiatus",
        "a_completion_spree": "Spirit Completion Spree",
        "a_multi_rewatch": "Multi-Spirit Replay",
        "a_dropped_recovery": "Rescued from the Mud",
        "a_ten_perfect_scores": "Ten Perfect Spirit Scores",
        "a_seasonal_clear": "Seasonal Spirit Clear",
        "a_complete_genre_span": "All Spirit Genres Known",
        "a_monthly_completions": "Monthly Spirit Contracts",
        "a_yearly_completions": "Yearly Spirit Journey",
        "a_rapid_complete": "Rapid Spirit Contract",
        "a_loyal_fan": "Loyal Bathhouse Employee",
        "a_studio_devotee": "Studio Ghibli Devotee",
        "a_rewatcher": "Spirit World Revisited",
        "a_triple_rewatch": "Three Spirit Journeys",
        "a_annual_tradition": "Annual Spirit World Visit",
        "a_director_fan": "Miyazaki's Vision Follower",
        "a_voice_actor_fan": "Voice of the Spirits",
        "a_ost_lover": "Joe Hisaishi's Melody",
        "a_source_reader": "Spirit World Texts",
        "a_waiting_weekly": "Weekly Spirit Update Wait",
        "a_childhood_revisit": "Return to Childhood Wonder",
        "a_saga_tracker": "Spirit Saga Tracker",
        "a_genre_loyalty": "Spirit Genre Loyalty",
        "a_decade_watcher": "Decade in the Spirit World",
        "a_adaptation_hunter": "Spirit Adaptation Hunter",
        "a_original_anime_fan": "Original Spirit Broadcast",
        "a_long_commitment": "Long Bathhouse Contract",
        "a_perfect_attendance": "Perfect Bathhouse Attendance",
        "a_favorite_studio_5": "Five Ghibli Favorites",
        "a_complete_catalog": "Complete Spirit Catalog",
        "a_franchise_collector": "Spirit World Collector",
        "a_airing_follower": "Currently Airing Spirits",
        "a_genre_master": "Spirit Genre Master",
        "a_staff_follower": "Spirit Staff Tracker",
        "a_multi_season_fan": "Multi-Season Spirit Fan",
        "a_format_diversity": "Diverse Spirit Formats",
        "a_year_dedication": "Year of Spirit Service",
        "a_season_dedication": "Season of Spirit Devotion",
        "a_genre_explorer": "Beyond Known Spirit Territory",
        "a_studio_hopper": "Studio Transfer",
        "a_tag_explorer": "Spirit Tag Explorer",
        "a_decade_hopper": "Decade-Hopping Spirits",
        "a_hidden_gem": "Hidden Spirit Treasure",
        "a_popular_taste": "Popular Among Spirits",
        "a_retro_appreciator": "Classic Spirit Appreciator",
        "a_modern_viewer": "Modern Spirit Viewer",
        "a_cross_demographic": "Cross-Realm Spirit Watcher",
        "a_underdog_fan": "Underdog Spirit Fan",
        "a_variety_week": "Week of Varied Spirits",
        "a_foreign_cinema": "Foreign Spirit Cinema",
        "a_classic_connoisseur": "Classic Ghibli Connoisseur",
        "a_every_season": "Every Spirit Season",
        "a_award_winner": "Spirit Award Winner",
        "a_niche_explorer": "Niche Spirit Explorer",
        "a_global_anime": "Global Spirit Entry",
        "a_cult_classic": "Cult Spirit Classic",
        "a_random_pick": "Random Spirit Assignment",
        "a_new_genre_month": "New Spirit Genre Monthly",
        "a_seasonal_completionist": "Seasonal Spirit Completionist",
        "a_unpopular_opinion": "Unpopular Spirit Opinion",
        "a_top_rated_viewer": "Top-Rated Spirit Source",
        "a_source_variety": "Spirit Source Variety",
        "a_low_score_brave": "Brave Low-Score Spirit",
        "a_upcoming_watcher": "Upcoming Spirit Intel",
        "a_short_series_explorer": "Short Spirit Journey",
        "a_long_series_explorer": "Long Spirit Expedition",
        "a_night_owl": "Night Shift in the Baths",
        "a_early_bird": "Dawn Bathhouse Opening",
        "a_lunch_break": "Bathhouse Lunch Break",
        "a_golden_hour": "Golden Hour Spirit Glow",
        "a_four_am_club": "4 AM Boiler Room Watch",
        "a_witching_hour": "Spirit Witching Hour",
        "a_new_year_watch": "New Year Spirit Crossing",
        "a_midnight_premiere": "Midnight Spirit Premiere",
        "a_all_hours": "All-Hours Bathhouse Watch",
        "a_dawn_warrior": "Dawn Bathhouse Worker",
        "a_afternoon_delight": "Afternoon Spirit Break",
        "a_prime_time": "Prime Spirit Hour",
        "a_workday_watcher": "On-Duty Spirit Watcher",
        "a_sunday_marathon": "Sunday Spirit Marathon",
        "a_rainy_day": "Rainy Day in the Spirit World",
        "a_morning_routine": "Morning Bathhouse Routine",
        "a_night_shift": "Night Spirit Shift",
        "a_twilight_zone": "Twilight River Crossing",
        "a_seasonal_premier": "Spirit Season Premiere",
        "a_clock_collector": "Spirit World Timekeeper",
        "a_weekend_binge_hours": "Weekend Spirit Binge",
        "a_late_night_regular": "Late Night Bathhouse Regular",
        "a_sunrise_watcher": "Sunrise Over the Spirit River",
        "a_holiday_watcher": "Holiday Spirit Duty",
        "a_every_day_of_week": "Every Day in the Baths",
        "a_monthly_hours": "Monthly Spirit Hours",
        "a_first_party": "First Spirit Gathering",
        "a_party_host": "Bathhouse Party Host",
        "a_social_butterfly": "Bathhouse Socialite",
        "a_group_binge": "Group Spirit Binge",
        "a_party_regular": "Regular Spirit Companion",
        "a_sync_viewer": "Synchronized Spirit Viewing",
        "a_commentator": "Spirit World Commentator",
        "a_party_marathon": "Spirit Marathon Party",
        "a_full_house": "Full Bathhouse",
        "a_community_pillar": "Pillar of the Spirit World",
        "a_watch_party_streak": "Consecutive Spirit Parties",
        "a_diverse_party": "Diverse Spirit Party",
        "a_late_night_party": "Late Night Bathhouse Party",
        "a_party_veteran": "Veteran Spirit Host",
        "a_genre_party": "Cross-Genre Spirit Party",
        "a_weekly_party": "Weekly Spirit Gathering",
        "a_silent_viewer": "Silent Spirit Observer",
        "a_recommendation_giver": "Spirit World Recommender",
        "a_party_completionist": "Party Spirit Completionist",
        "a_social_scorer": "Social Spirit Scorer",
        "a_round_number": "Round Spirit Milestone",
        "a_fibonacci": "Fibonacci Spirit Sequence",
        "a_palindrome_day": "Palindrome Spirit Day",
        "a_binary_day": "Binary Spirit Signal",
        "a_full_moon": "Full Moon Spirit Transformation",
        "a_leap_year": "Leap Year Spirit Jump",
        "a_time_traveler": "River Time Traveler",
        "a_genre_clash": "Spirit vs Human Clash",
        "a_triple_seven": "Triple Seven Bathhouse Floors",
        "a_thousand_complete": "Thousand Spirit Contracts",
        "a_pi_episodes": "Pi Spiral Calculation",
        "a_synchronicity": "Spirit World Synchronicity",
        "a_world_record": "Spirit World Record",
        "a_nice": "Nice Spirit Count",
        "a_power_level": "Haku's Dragon Power",
        "a_answer_42": "The Answer to Chihiro's Question",
        "a_square_number": "Perfect Spirit Formation",
        "a_prime_count": "Prime Number of Spirits",
        "a_matching_date": "Matching Spirit Date",
        "a_century_episode": "Century Spirit Encounter",
        "a_double_digits": "Double Digit Spirit Count",
        "a_one_two_three": "Soot Sprites One Two Three",
        "a_lucky_seven": "Seven Lucky Spirits",
        "a_all_tens": "Perfect Spirit Scores",
        "a_exact_hundred_eps": "Exact Hundred Spirits",
        "a_year_match_count": "Year Spirit Match",
        "a_tv_watcher": "TV Spirit Broadcast",
        "a_movie_buff": "Spirit World Film",
        "a_ova_hunter": "OVA Spirit Hunter",
        "a_ona_explorer": "ONA Spirit Explorer",
        "a_special_watcher": "Special Spirit Episode",
        "a_short_king": "Short Spirit Encounter",
        "a_variety_pack": "All-Format Spirit Pack",
        "a_film_festival": "Spirit Film Festival",
        "a_music_video": "Spirit World Music Video",
        "a_tv_short": "Quick Spirit Clip",
        "a_movie_marathon": "Spirit Movie Marathon",
        "a_double_length": "Double-Length Spirit Journey",
        "a_anthology": "Spirit World Anthology",
        "a_mini_series": "Mini Spirit Collection",
        "a_theatrical": "Theatrical Spirit Release",
        "a_format_master": "Spirit Format Master",
        "a_long_movie": "Feature-Length Spirit Journey",
        "a_back_catalog": "Back Catalog Spirit Files",
        "a_cm_watcher": "Spirit Commercial Watcher",
        "a_pv_collector": "Spirit Preview Collector",
        "a_format_balance": "Balanced Spirit Formats",
        "a_episodic_master": "Episodic Spirit Master",
        "a_sequel_movie": "Sequel Spirit Film",
        "a_recap_watcher": "Spirit Recap Watcher",
        "a_daily_streak": "Daily Spirit Shift Streak",
        "a_mega_streak": "Mega Spirit Streak",
        "a_weekly_warrior": "Weekly Spirit Warrior",
        "a_monthly_watcher": "Monthly Spirit Duty",
        "a_comeback": "Return from the Spirit World",
        "a_weekend_streak": "Weekend Spirit Streak",
        "a_no_zero_days": "No Zero Days in the Baths",
        "a_iron_will": "Iron Will Like Chihiro",
        "a_habit_formed": "Bathhouse Routine Formed",
        "a_consistent_pace": "Consistent Spirit Pace",
        "a_year_long": "Year-Long Spirit Contract",
        "a_double_streak": "Double Spirit Streak",
        "a_streak_recovery": "Spirit Streak Recovery",
        "a_daily_minimum": "Daily Spirit Minimum",
        "a_winter_streak": "Winter Spirit Streak",
        "a_summer_streak": "Summer Spirit Streak",
        "a_morning_streak": "Morning Spirit Streak",
        "a_night_streak": "Night Spirit Streak",
        "a_unbreakable": "Unbreakable Spirit Will",
        "a_eternal_flame": "Eternal Bathhouse Flame",
        "a_completion_streak": "Spirit Completion Chain",
        "a_rating_streak": "Spirit Rating Streak",
        "a_multi_ep_streak": "Multi-Spirit Offensive",
        "a_genre_streak": "Genre Spirit Streak",
        "a_studio_streak": "Studio Spirit Loyalty",
        "a_perfect_week": "Perfect Week of Spirit Service",
        "a_critic": "Yubaba's Spirit Critic",
        "a_perfect_ten": "Perfect Ten Spirit Score",
        "a_harsh_critic": "Harsh Spirit Judge",
        "a_fair_judge": "Fair Spirit Assessment",
        "a_generous_spirit": "Generous Like Zeniba",
        "a_score_all": "Full Spirit Evaluation",
        "a_wide_range": "Wide Spirit Score Range",
        "a_controversial": "Controversial Spirit Opinion",
        "a_consistent_scorer": "Consistent Spirit Scorer",
        "a_score_sniper": "Precision Spirit Scorer",
        "a_evolving_taste": "Evolving Spirit Taste",
        "a_bell_curve": "Bell Curve of Spirit Scores",
        "a_picky_watcher": "Selective Spirit Watcher",
        "a_100_rated": "Hundred Spirit Ratings",
        "a_500_rated": "Five Hundred Spirit Reports",
        "a_mediocre_majority": "Middle Ground Spirit Score",
        "a_rating_spree": "Spirit Rating Spree",
        "a_score_variance": "Variable Spirit Ratings",
        "a_masterpiece_hunter": "Masterpiece Spirit Hunter",
        "a_contrarian": "Contrarian Spirit Viewer",
        "a_optimist": "Optimist in the Spirit World",
        "a_score_distributor": "Spirit Score Distributor",
        "a_genre_critic": "Spirit Genre Critic",
        "a_mean_above_8": "Elite Spirit Average",
        "a_new_years_resolution": "New Year Spirit Vow",
        "a_valentines_weeb": "Valentine's Spirit Bond",
        "a_pi_day": "Pi Day Spiral Count",
        "a_april_fools": "April Fools Spirit Prank",
        "a_international_anime_day": "International Spirit Day",
        "a_star_wars_day": "Spirit Wars Day",
        "a_summer_solstice": "Summer Solstice Spirit Festival",
        "a_tanabata": "Tanabata Spirit Wish",
        "a_friday_13th": "Friday 13th Spirit Curse",
        "a_halloween_spirit": "Halloween Spirit Horror",
        "a_thanksgiving_binge": "Thanksgiving Spirit Feast",
        "a_christmas_special": "Midwinter Spirit Special",
        "a_new_years_eve": "New Year's Eve Spirit Crossing",
        "a_birthday_watch": "Birthday in the Spirit World",
        "a_holiday_marathon": "Holiday Spirit Marathon",
        "a_independence_day": "Spirit Independence Day",
        "a_culture_day": "Spirit Culture Day",
        "a_spring_equinox": "Spring Equinox Spirit",
        "a_earth_day": "Protect the Spirit World Day",
        "a_labor_day": "Bathhouse Labor Day",
        "a_winter_solstice": "Winter Solstice Spirit Night",
        "a_anime_birthday": "Spirit World Anniversary",
        "a_every_holiday": "Every Holiday Spirit",
        "a_consecutive_holidays": "Consecutive Spirit Holidays",
        "a_meta_first_unlock": "First Spirit Power Awakened",
        "a_meta_collector": "Spirit Badge Collector",
        "a_meta_category_starter": "Spirit Category Initiation",
        "a_meta_tier_climber": "Spirit Rank Promotion",
        "a_meta_tier_max": "Master Spirit Rank",
        "a_meta_xp_earner": "XP from Spirit Service",
        "a_meta_difficulty_easy": "Easy Spirit Exercise",
        "a_meta_difficulty_hard": "Legendary Spirit Challenge",
        "a_meta_unlock_spree": "Spirit Unlock Spree",
        "a_meta_completionist": "Meta Spirit Completionist",
        "a_meta_diverse": "Diverse Spirit Portfolio",
        "a_meta_dominator": "Spirit World Dominator",
        "m_first_chapter": "First Spirit World Chapter",
        "m_chapter_counter": "Chapter Spirit Counter",
        "m_chapter_titan": "Spirit Chapter Assault",
        "m_reading_hours": "Hours Reading Spirit Texts",
        "m_reading_time_lord": "Spirit Time Reading Memory",
        "m_manga_collector": "Spirit Manga Collector",
        "m_library_legend": "Yubaba's Library Legend",
        "m_first_complete": "First Spirit Manga Complete",
        "m_hundred_club": "Hundred Spirit Chapters",
        "m_first_day": "First Day Reading Spirits",
        "m_first_rating": "First Spirit Manga Rating",
        "m_ten_thousand_pages": "Ten Thousand Spirit Pages",
        "m_volume_collector": "Spirit Volume Collector",
        "m_year_explorer": "Year of Spirit Reading",
        "m_century_reader": "Century-Chapter Spirit Reader",
        "m_five_hundred_ch": "Five Hundred Spirit Chapters",
        "m_thousand_ch": "Thousand Spirit Pages",
        "m_reading_ten": "Ten Spirit Volumes at Once",
        "m_ptr_hoarder": "Spirit Reading Backlog",
        "m_dropped_honesty": "Honest Spirit Retreat",
        "m_season_reader": "Seasonal Spirit Reader",
        "m_active_reader": "Active Spirit Field Reader",
        "m_five_thousand_ch": "Five Thousand Spirit Chapters",
        "m_ten_completed": "Ten Spirit Manga Complete",
        "m_fifty_completed": "Fifty Spirit Stories Done",
        "m_five_hundred_completed": "Five Hundred Spirit Victories",
        "m_mean_score_tracker": "Average Spirit Manga Rating",
        "m_unique_authors": "Unique Spirit Authors",
        "m_all_status": "All Spirit Reading Statuses",
        "m_first_favorite": "First Spirit Manga Bond",
        "m_favorites_collector": "Spirit Favorites Arsenal",
        "m_days_spent_reading": "Days Reading in the Spirit World",
        "m_binge_reader": "Spirit Binge Reader",
        "m_marathon_reader": "Spirit World Reading Marathon",
        "m_weekend_reader": "Weekend Spirit Reading",
        "m_non_stop_reading": "Non-Stop Spirit Pages",
        "m_one_more_chapter": "One More Spirit Chapter",
        "m_speed_read": "No-Face Speed Read",
        "m_double_story": "Double Spirit Story",
        "m_triple_read": "Triple Spirit Reading",
        "m_five_a_day": "Five Spirit Reads Daily",
        "m_chapter_chain": "Spirit Chapter Chain",
        "m_volume_binge": "Spirit Volume Binge",
        "m_power_reader": "Spirit Power Reader",
        "m_half_day_read": "Half-Day Spirit Read",
        "m_full_day_read": "Full-Day Spirit Study",
        "m_power_weekend": "Power Weekend Spirit Reading",
        "m_binge_king": "King of Spirit Reading",
        "m_no_sleep_read": "All-Night Spirit Reading",
        "m_full_series_rush": "Full Spirit Series Rush",
        "m_seven_day_challenge": "Seven-Day Spirit Reading",
        "m_hundred_day_read": "Hundred-Day Spirit Read",
        "m_volume_rush": "Spirit Volume Rush",
        "m_series_sweep": "Spirit Series Sweep",
        "m_genre_binge": "Cross-Genre Spirit Read",
        "m_author_binge": "Spirit Author Deep Dive",
        "m_chapter_counter_day": "Daily Spirit Chapter Count",
        "m_multi_series_binge": "Multi-Spirit Reading Front",
        "m_midnight_binge": "Midnight Spirit Reading",
        "m_new_year_binge": "New Year Spirit Reading",
        "m_forty_eight_hour": "Forty-Eight Hour Spirit Read",
        "m_oneshot_binge": "Spirit Oneshot Blitz",
        "m_genre_action": "Spirit Action Manuscript",
        "m_genre_adventure": "Spirit World Adventure Read",
        "m_genre_comedy": "Soot Sprite Comedy Read",
        "m_genre_drama": "Chihiro's Drama Manga",
        "m_genre_fantasy": "Spirit Fantasy Manga",
        "m_genre_horror": "Yubaba's Horror Manga",
        "m_genre_mystery": "River Spirit Mystery",
        "m_genre_romance": "Haku's Romance Manga",
        "m_genre_scifi": "Spirit World Science",
        "m_genre_sol": "Bathhouse Daily Life Read",
        "m_genre_sports": "Spirit Sports Manga",
        "m_genre_supernatural": "Spirit Powers Manga",
        "m_genre_thriller": "Escape Thriller Manga",
        "m_genre_psychological": "Chihiro's Mind Manga",
        "m_genre_isekai": "Spirit World Isekai",
        "m_genre_shounen": "Brave Spirit Heart",
        "m_genre_ecchi": "Hot Spring Chapter",
        "m_genre_mahou_shoujo": "Magic Spirit Girl",
        "m_genre_mecha": "Spirit Dragon Mecha",
        "m_genre_music": "Spirit World Songs",
        "m_tag_isekai_new": "New Spirit World",
        "m_tag_harem": "Spirit Harem Manga",
        "m_tag_bl": "Spirit Brotherhood Manga",
        "m_tag_gl": "Spirit Sisterhood Manga",
        "m_tag_historical": "Spirit History Manga",
        "m_tag_military": "Bathhouse Operations Manga",
        "m_tag_school": "Spirit Academy Manga",
        "m_tag_martial_arts": "Spirit Combat Manga",
        "m_tag_vampire": "Spirit Consumption Manga",
        "m_tag_samurai": "Spirit Warrior Manga",
        "m_tag_space": "Spirit Sky Manga",
        "m_tag_parody": "Spirit Comedy Manga",
        "m_tag_idol": "Bathhouse Star Manga",
        "m_tag_post_apocalyptic": "Post-Spirit Rule Manga",
        "m_tag_cyberpunk": "Spirit Technology Manga",
        "m_tag_shoujo": "Chihiro's Story Manga",
        "m_tag_survival": "Spirit Survival Manga",
        "m_tag_cooking": "Bathhouse Recipe Manga",
        "m_tag_medical": "Spirit Healing Manga",
        "m_tag_villainess": "Yubaba Villainess Manga",
        "m_completionist": "Spirit Manga Completionist",
        "m_mega_completionist": "Supreme Spirit Reader",
        "m_completion_rate_50": "Halfway Through the Spirit World",
        "m_completion_rate_75": "Approaching the River Crossing",
        "m_completion_rate_90": "Almost Back Home",
        "m_no_drop": "Never Abandoned a Spirit Manga",
        "m_long_runner_complete": "Long Spirit Series Complete",
        "m_sequel_chain": "Spirit Sequel Chain",
        "m_clean_list": "Clean Spirit Reading Record",
        "m_from_ptr": "Spirit Orders Received: Read",
        "m_reread_master": "Spirit Memory Reread",
        "m_oneshot_complete": "Spirit Oneshot Complete",
        "m_same_day_start_finish": "Same-Day Spirit Reading",
        "m_revival": "Revival Through Spirit Waters",
        "m_zero_to_hundred": "Bathhouse Newbie to Scholar",
        "m_five_genre_complete": "Five Spirit Genres Mastered",
        "m_full_collection": "Full Spirit Archive",
        "m_batch_complete": "Batch Spirit Clearance",
        "m_paused_to_done": "Back from Spirit Hiatus",
        "m_completion_spree": "Spirit Reading Spree",
        "m_format_completionist": "Spirit Format Badge",
        "m_catch_up": "Caught Up with Spirit World",
        "m_multi_reread": "Multi-Pass Spirit Reread",
        "m_dropped_recovery": "Recovered from Spirit Mud",
        "m_ten_perfect_scores": "Ten Perfect Spirit Manga Scores",
        "m_complete_genre_span": "All-Genre Spirit Reader",
        "m_monthly_completions": "Monthly Spirit Completions",
        "m_yearly_completions": "Yearly Spirit Reading",
        "m_rapid_complete": "Rapid Spirit Processing",
        "m_author_complete": "Spirit Author Complete Works",
        "m_loyal_reader": "Loyal Spirit World Reader",
        "m_mangaka_lover": "Spirit Mangaka Devotee",
        "m_rereader": "Spirit World Rereader",
        "m_triple_reread": "Three Spirit Rereads",
        "m_annual_reread": "Annual Spirit Reread",
        "m_publisher_fan": "Spirit Publisher Fan",
        "m_artist_fan": "Spirit Artist Appreciation",
        "m_adaptation_compare": "Spirit Manga vs Anime",
        "m_source_material_fan": "Spirit Source Material Fan",
        "m_waiting_weekly": "Weekly Spirit Chapter Wait",
        "m_classic_reader": "Classic Spirit Reader",
        "m_saga_reader": "Spirit Saga Reader",
        "m_genre_loyalty": "Spirit Genre Loyalty",
        "m_decade_reader": "Decade Spirit Reader",
        "m_ln_adaptation": "Spirit Light Novel Intel",
        "m_original_work": "Original Spirit Work",
        "m_long_commitment": "Long Spirit Reading Commitment",
        "m_up_to_date": "Up-to-Date with Spirit World",
        "m_favorite_mangaka": "Favorite Spirit Mangaka",
        "m_complete_portfolio": "Complete Spirit Portfolio",
        "m_franchise_collector": "Spirit World Franchise",
        "m_serialization_follower": "Spirit Serialization Tracker",
        "m_genre_master": "Spirit Genre Mastery",
        "m_multi_series_author": "Multi-Series Spirit Author",
        "m_format_diversity": "Diverse Spirit Reading",
        "m_year_dedication": "Year of Spirit Reading",
        "m_ongoing_follower": "Ongoing Spirit Series",
        "m_genre_loyalty_50": "Fifty Spirit Genre Chapters",
        "m_genre_explorer": "Spirit Genre Territory",
        "m_publisher_hopper": "Spirit Publisher Transfer",
        "m_tag_explorer": "Spirit Tag Recon",
        "m_decade_hopper": "Decade Spirit Reader",
        "m_hidden_gem": "Hidden Spirit Gem",
        "m_popular_taste": "Popular Spirit Reading",
        "m_retro_reader": "Retro Spirit Reader",
        "m_modern_reader": "Modern Spirit Era Reader",
        "m_cross_demographic": "Cross-Realm Spirit Reader",
        "m_underdog_fan": "Underdog Spirit Fan",
        "m_variety_week": "Week of Spirit Varieties",
        "m_manhwa_reader": "Manhwa Spirit Reader",
        "m_manhua_reader": "Manhua Spirit Reader",
        "m_classic_connoisseur": "Classic Spirit Connoisseur",
        "m_award_winner": "Award-Winning Spirit Manga",
        "m_niche_explorer": "Niche Spirit Reader",
        "m_world_manga": "World Spirit Manga",
        "m_cult_classic": "Cult Spirit Classic",
        "m_random_pick": "Random Spirit Assignment",
        "m_new_genre_month": "New Spirit Genre Monthly",
        "m_year_completionist": "Year Spirit Completionist",
        "m_unpopular_opinion": "Unpopular Spirit Opinion",
        "m_top_rated_reader": "Top-Rated Spirit Reader",
        "m_source_variety": "Spirit Source Variety",
        "m_low_score_brave": "Brave Low-Score Spirit",
        "m_short_manga_explorer": "Short Spirit Manga",
        "m_long_manga_explorer": "Long Spirit Campaign",
        "m_serialization_explorer": "Spirit Serialization Explorer",
        "m_night_owl": "Night Spirit Reader",
        "m_early_bird": "Dawn Spirit Reader",
        "m_lunch_reader": "Bathhouse Lunch Reader",
        "m_commute_reader": "Travel to Spirit World Reader",
        "m_four_am_club": "4 AM Spirit Reader",
        "m_new_year_read": "New Year Spirit Reading",
        "m_all_hours": "All-Hours Spirit Reading",
        "m_prime_time_reader": "Prime Time Spirit Read",
        "m_workday_reader": "On-Duty Spirit Reader",
        "m_sunday_read": "Sunday Spirit Reading",
        "m_morning_routine": "Morning Spirit Reading",
        "m_night_shift_reader": "Night Shift Spirit Reader",
        "m_seasonal_premier_read": "New Spirit Release Intel",
        "m_clock_collector": "Spirit Clock Reader",
        "m_late_night_horror": "Midnight Spirit Horror Read",
        "m_afternoon_reader": "Afternoon Spirit Reading",
        "m_golden_hour_reader": "Golden Hour Spirit Read",
        "m_dawn_reader": "Dawn Spirit Reader",
        "m_twilight_reader": "Twilight Spirit Reading",
        "m_midnight_start": "Midnight Spirit Start",
        "m_weekend_binge_hours": "Weekend Spirit Binge Hours",
        "m_late_night_regular": "Late Night Spirit Reader",
        "m_sunrise_reader": "Sunrise Spirit Reader",
        "m_every_day_of_week": "Every Day Spirit Reading",
        "m_monthly_hours": "Monthly Spirit Hours Logged",
        "m_bedtime_reader": "Bedtime Spirit Reader",
        "m_art_appreciator": "Spirit Art Appreciator",
        "m_webtoon_reader": "Spirit Webtoon Reader",
        "m_full_color": "Full Color Spirit Manga",
        "m_doujin_reader": "Spirit Doujin Reader",
        "m_anthology_reader": "Spirit Anthology Reader",
        "m_adaptation_reader": "Spirit Adaptation Reader",
        "m_longstrip_reader": "Spirit Longstrip Reader",
        "m_4koma_reader": "Spirit 4-Koma Comedy",
        "m_oneshot_reader": "Spirit Oneshot Reader",
        "m_format_variety": "Spirit Format Variety",
        "m_light_novel_reader": "Spirit Light Novel Reader",
        "m_novel_reader": "Spirit Novel Reader",
        "m_visual_storyteller": "Spirit Visual Narrator",
        "m_colored_classic": "Colored Spirit Classic",
        "m_webcomic_fan": "Spirit Webcomic Fan",
        "m_manga_to_anime": "Spirit Manga to Anime",
        "m_seinen_reader": "Seinen Spirit Reader",
        "m_josei_reader": "Josei Spirit Reader",
        "m_award_winning_art": "Award-Winning Spirit Art",
        "m_debut_work": "Debut Spirit Work",
        "m_vertical_scroll": "Vertical Spirit Scroll",
        "m_traditional_format": "Traditional Spirit Format",
        "m_cross_media": "Cross-Media Spirit Intel",
        "m_spinoff_reader": "Spirit Spinoff Reader",
        "m_remake_reader": "Spirit Remake Reader",
        "m_collaboration_reader": "Joint Spirit Manuscript",
        "m_daily_streak": "Daily Spirit Reading Streak",
        "m_mega_streak": "Mega Spirit Reading Streak",
        "m_weekly_warrior": "Weekly Spirit Reader",
        "m_monthly_reader": "Monthly Spirit Reader",
        "m_comeback": "Return from Spirit Hiatus",
        "m_weekend_streak": "Weekend Spirit Reading Streak",
        "m_no_zero_days": "No Zero Spirit Reading Days",
        "m_iron_will": "Iron Will Spirit Reader",
        "m_habit_formed": "Spirit Reading Habit Formed",
        "m_consistent_pace": "Consistent Spirit Reading Pace",
        "m_year_long": "Year-Long Spirit Reading",
        "m_double_streak": "Double Spirit Reading Streak",
        "m_streak_recovery": "Spirit Reading Streak Recovery",
        "m_daily_minimum": "Daily Spirit Minimum Pages",
        "m_winter_streak": "Winter Spirit Reading",
        "m_summer_streak": "Summer Spirit Reading",
        "m_morning_streak": "Morning Spirit Formation",
        "m_night_streak": "Night Spirit Patrol",
        "m_unbreakable": "Unbreakable Spirit Reading Will",
        "m_eternal_flame": "Eternal Spirit Flame",
        "m_chapter_a_day": "Chapter a Day Spirit",
        "m_genre_streak": "Spirit Genre Reading Streak",
        "m_completion_streak": "Spirit Completion Chain",
        "m_rating_streak": "Spirit Rating Streak",
        "m_multi_ch_streak": "Multi-Chapter Spirit Streak",
        "m_author_streak": "Spirit Author Streak",
        "m_perfect_week_manga": "Perfect Spirit Reading Week",
        "m_diverse_streak": "Diverse Spirit Reading Streak",
        "m_critic": "Spirit Manga Critic",
        "m_perfect_ten": "Perfect Spirit Manga Score",
        "m_harsh_critic": "Harsh Spirit Reader",
        "m_fair_judge": "Fair Spirit Judge",
        "m_generous_spirit": "Generous Like Zeniba",
        "m_score_all": "Full Spirit Manga Assessment",
        "m_wide_range": "Wide Spirit Score Range",
        "m_controversial": "Controversial Spirit Reading",
        "m_consistent_scorer": "Consistent Spirit Scorer",
        "m_score_sniper": "Precision Spirit Scorer",
        "m_evolving_taste": "Evolving Spirit Taste",
        "m_bell_curve": "Spirit Bell Curve",
        "m_picky_reader": "Selective Spirit Reader",
        "m_100_rated": "Hundred Spirit Ratings Filed",
        "m_500_rated": "Five Hundred Spirit Reports",
        "m_mediocre_majority": "Middle Ground Spirit Reader",
        "m_rating_spree": "Spirit Rating Spree",
        "m_score_variance": "Variable Spirit Scores",
        "m_binge_rater": "Spirit Binge Rater",
        "m_reread_rerate": "Reread Spirit Re-Rate",
        "m_masterpiece_hunter": "Spirit Masterpiece Hunter",
        "m_contrarian": "Contrarian Spirit Reader",
        "m_optimist": "Spirit World Optimist",
        "m_score_distributor": "Spirit Score Distributor",
        "m_genre_critic": "Spirit Genre Critic",
        "m_mean_above_8": "Elite Spirit Reading Average",
        "m_new_years_resolution": "New Year Spirit Reading Vow",
        "m_valentines_read": "Valentine's Spirit Reading",
        "m_pi_day": "Pi Day Spirit Count",
        "m_april_fools": "April Fools Spirit Manga",
        "m_international_manga_day": "International Spirit Manga Day",
        "m_free_comic_day": "Free Spirit Comic Day",
        "m_summer_solstice": "Summer Solstice Spirit Read",
        "m_tanabata": "Tanabata Spirit Reading",
        "m_friday_13th": "Friday 13th Spirit Read",
        "m_halloween_read": "Halloween Spirit Reading",
        "m_thanksgiving_binge": "Thanksgiving Spirit Feast",
        "m_christmas_read": "Midwinter Spirit Reading",
        "m_new_years_eve": "New Year's Eve Spirit Read",
        "m_birthday_read": "Birthday Spirit Reading",
        "m_holiday_marathon": "Holiday Spirit Reading Marathon",
        "m_independence_day": "Spirit Independence Reading",
        "m_culture_day": "Spirit Culture Day Reading",
        "m_spring_equinox": "Spring Equinox Spirit Read",
        "m_earth_day": "Earth Day Spirit Read",
        "m_labor_day": "Bathhouse Labor Reading",
        "m_winter_solstice": "Winter Solstice Spirit Read",
        "m_manga_birthday": "Spirit Manga Birthday",
        "m_every_holiday_reader": "Every Holiday Spirit Reader",
        "m_consecutive_holidays": "Consecutive Spirit Holiday Reads",
        "m_round_number": "Round Spirit Chapter Milestone",
        "m_fibonacci": "Fibonacci Spirit Chapters",
        "m_palindrome_day": "Palindrome Spirit Day",
        "m_binary_day": "Binary Spirit Reading Day",
        "m_full_moon_read": "Full Moon Spirit Read",
        "m_leap_year_read": "Leap Year Spirit Reading",
        "m_triple_seven": "Triple Seven Spirit Chapters",
        "m_thousand_complete": "Thousand Spirit Manga Done",
        "m_nice": "Nice Spirit Chapter Count",
        "m_power_level_chapters": "Haku-Level Spirit Chapters",
        "m_answer_42": "Answer to Spirit Reading",
        "m_square_number": "Perfect Spirit Chapter Count",
        "m_prime_count": "Prime Spirit Chapter Count",
        "m_matching_date": "Matching Spirit Reading Date",
        "m_century_chapter": "Century Spirit Chapter",
        "m_pi_chapters": "Pi Spirit Chapter Calculation",
        "m_synchronicity": "Spirit Reading Synchronicity",
        "m_world_record": "World Record Spirit Chapters",
        "m_genre_clash": "Genre Spirit Clash",
        "m_time_traveler": "Spirit Time Reader",
        "m_double_digits": "Double Digit Spirit Chapters",
        "m_one_two_three": "Spirit One Two Three",
        "m_lucky_seven": "Seven Lucky Spirit Chapters",
        "m_exact_hundred_ch": "Exact Hundred Spirit Chapters",
        "m_year_match_count": "Year Spirit Chapter Match",
        "m_chapter_match_date": "Chapter Spirit Date Match",
        "m_manga_format": "Spirit Manga Format",
        "m_manhwa_format": "Spirit Manhwa Format",
        "m_manhua_format": "Spirit Manhua Format",
        "m_ln_format": "Spirit Light Novel Format",
        "m_oneshot_format": "Spirit Oneshot Format",
        "m_doujin_format": "Spirit Doujin Format",
        "m_novel_format": "Spirit Novel Format",
        "m_format_master_manga": "Spirit Format Master Reader",
        "m_meta_first_unlock": "First Spirit Reading Power",
        "m_meta_collector": "Spirit Reading Badge Collector",
        "m_meta_category_starter": "Spirit Category Initiation",
        "m_meta_tier_climber": "Spirit Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Spirit Reading Rank",
        "m_meta_xp_earner": "XP from Spirit Reading",
        "m_meta_difficulty_easy": "Easy Spirit Reading",
        "m_meta_difficulty_hard": "Legendary Spirit Challenge",
        "m_meta_unlock_spree": "Spirit Reading Unlock Spree",
        "m_meta_completionist": "Meta Spirit Completionist",
        "m_meta_diverse": "Diverse Spirit Reading Portfolio",
        "m_meta_dominator": "Spirit Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#050402",
        primary: "#cc6600",
        secondary: "#aa5500",
        accent: "#2266aa",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        bath_steam: { label: "Bath Steam", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
        spirit_sparks: { label: "Spirit Sparks", maxCount: 8, defaultEnabled: true, defaultIntensity: 50 },
        gold_coins: { label: "Gold Coins", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
        no_face_soot: { label: "Soot Sprites", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
    },
    milestoneNames: {
        1:   "Wandering Child",
        5:   "Bathhouse Employee",
        15:  "Haku's Helper",
        30:  "No-Face Ally",
        45:  "Yubaba's Target",
        60:  "Name Keeper",
        80:  "Spirit World Veteran",
        100: "Parents Restored",
    },
}
