import { AnimeThemeConfig } from "./types"
import {
    GiSpyglass, GiRing, GiScrollUnfurled, GiSpellBook,
    GiPistolGun, GiHeartInside, GiGrenade, GiStarMedal,
    GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss } from "react-icons/lu"
import { BiExtension } from "react-icons/bi"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { TbReportSearch } from "react-icons/tb"

export const spyXFamilyTheme: AnimeThemeConfig = {
    id: "spy-x-family",
    displayName: "Spy × Family",
    description: "Forger Family mission: peace. Espionage pink & agent gray.",
    fontFamily: "'Nunito', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap",
    cssVars: {
        "--color-brand-200": "255 200 220",
        "--color-brand-300": "248 155 185",
        "--color-brand-400": "235 105 148",
        "--color-brand-500": "210 60 110",
        "--color-brand-600": "170 30 80",
        "--color-brand-700": "125 12 55",
        "--color-brand-800": "82 3 35",
        "--color-brand-900": "48 0 20",
        "--color-brand-950": "22 0 9",
        "--brand": "220 65 115",
        "--background": "#0a0004",
        "--paper": "#160008",
        "--color-gray-950": "8 0 4",
        "--color-gray-900": "18 2 9",
        "--color-gray-800": "32 6 16",
        "--color-gray-700": "50 12 26",
        "--color-gray-600": "75 22 40",
        "--color-gray-500": "112 40 65",
        "--color-gray-400": "160 80 108",
        "--color-gray-300": "200 122 150",
        "--color-gray-200": "232 165 188",
        "--color-gray-100": "248 215 230",
        "--color-gray-50":  "254 245 250",
    },
    sidebarOverrides: {
        "home":           { icon: GiSpyglass,       label: "Mission: STRIX" },
        "schedule":       { icon: GiAlarmClock,   label: "Operation Timeline" },
        "manga":          { icon: GiScrollUnfurled,label: "WISE Files" },
        "lists":          { icon: GiSpellBook,    label: "Target Registry" },
        "discover":       { icon: GiPistolGun,    label: "Fieldwork" },
        "torrent-list":   { icon: GiGrenade,         label: "SSS Ops" },
        "unmatched":      { icon: GiRing,         label: "Unmatched Aliases" },
        "scan-summaries": { icon: TbReportSearch, label: "Mission Reports" },
        "auto-downloader":{ icon: LuRss,          label: "Handler Feed" },
        "search":         { icon: FiSearch,       label: "Search" },
        "notifications":  { icon: LuBell,         label: "Handler Alerts" },
        "achievements":   { icon: GiStarMedal,    label: "Mission Rank" },
        "theme-manager":  { icon: GiPalette,      label: "Forger Colors" },
        "extensions":     { icon: BiExtension,    label: "Contracts" },
        "settings":       { icon: GiSettingsKnobs,label: "WISE Config" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "Operation Strix Begins",
        "a_episode_counter": "Mission Ops Tally",
        "a_episode_titan": "S-Rank Operation",
        "a_hours_invested": "Hours Undercover",
        "a_time_lord": "Twilight's Archive",
        "a_anime_collector": "WISE Arsenal",
        "a_library_legend": "Eden Grand Library",
        "a_first_complete": "Mission Accomplished",
        "a_hundred_club": "Century Dossier",
        "a_first_day": "Eden Enrollment Day",
        "a_first_rating": "Cadet Evaluation",
        "a_ten_thousand_min": "Deep Cover Tenure",
        "a_season_veteran": "Veteran Operative",
        "a_year_explorer": "Year-Long Mission",
        "a_century_watcher": "Hundred Ops Logged",
        "a_five_hundred_eps": "Five Hundred Briefs",
        "a_thousand_eps": "Thousand Intel Drops",
        "a_watching_ten": "Ten Active Covers",
        "a_ptw_hoarder": "Dossier Hoarder",
        "a_dropped_honesty": "Mission Aborted",
        "a_five_thousand_eps": "Five Thousand Sorties",
        "a_ten_completed": "Ten Ops Cleared",
        "a_fifty_completed": "Fifty Missions Done",
        "a_five_hundred_completed": "Elite Agent Record",
        "a_mean_score_tracker": "Handler's Average",
        "a_unique_studios": "Allied Agencies",
        "a_days_spent_watching": "Days Undercover",
        "a_all_status": "Full Clearance Level",
        "a_first_favorite": "First Safe House",
        "a_favorites_collector": "Favorite Assets",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Forger Family Marathon",
        "a_marathon_runner": "Operation Strix Sprint",
        "a_weekend_warrior": "Weekend Field Op",
        "a_non_stop": "Nonstop Pursuit",
        "a_one_more_episode": "One More Briefing",
        "a_speed_run": "Speed Extraction",
        "a_double_feature": "Double Agent Play",
        "a_triple_threat": "Triple Cross Job",
        "a_five_a_day": "Five Dead Drops",
        "a_back_to_back": "Consecutive Ops",
        "a_seasonal_binge": "Full Arc Sweep",
        "a_cour_crusher": "Cour Liquidation",
        "a_half_day_watch": "Half-Day Stakeout",
        "a_full_day_watch": "Full-Day Stakeout",
        "a_power_weekend": "Power Weekend Op",
        "a_binge_king": "Binge Commander",
        "a_no_sleep": "All-Night Vigil",
        "a_entire_season": "Rapid Op Clearance",
        "a_seven_day_challenge": "Seven-Day Mission",
        "a_hundred_day_binge": "Hundred-Day Siege",
        "a_genre_binge": "Cross-Agency Binge",
        "a_studio_binge": "Studio Infiltration",
        "a_season_sweep": "Season Sweep Op",
        "a_forty_eight_hour": "48-Hour Stakeout",
        "a_ep_counter_day": "Daily Sortie Tally",
        "a_multi_series_binge": "Multi-Front Op",
        "a_midnight_binge": "Midnight Recon Run",
        "a_new_year_binge": "New Year Offensive",

        // ── ANIME GENRES ──
        "a_genre_action": "Thorn Princess Strike",
        "a_genre_adventure": "Beyond Ostania",
        "a_genre_comedy": "Anya's Waku Waku",
        "a_genre_drama": "Forger Family Bond",
        "a_genre_fantasy": "Anya's Telepathy",
        "a_genre_horror": "Garden Nightmare",
        "a_genre_mystery": "Berlint Spy Mystery",
        "a_genre_romance": "Loid & Yor's Waltz",
        "a_genre_scifi": "WISE Technology",
        "a_genre_sol": "Forger Daily Life",
        "a_genre_sports": "Eden Dodgeball Champ",
        "a_genre_supernatural": "Esper Perception",
        "a_genre_thriller": "Twilight Pursuit",
        "a_genre_mecha": "Berlint Mechs",
        "a_genre_music": "Eden Recital Hall",
        "a_genre_psychological": "Anya Mind Reader",
        "a_genre_ecchi": "Beach Episode Op",
        "a_genre_mahou_shoujo": "Starlight Anya",
        "a_tag_isekai": "Another Country Op",
        "a_tag_harem": "Spy Handler Circle",
        "a_tag_bl": "Agent Brothers",
        "a_tag_gl": "Thorn Sisters",
        "a_tag_historical": "Cold War Archives",
        "a_tag_military": "WISE Military Branch",
        "a_tag_school": "Eden Academy Pupil",
        "a_tag_martial_arts": "Yor's Combat Arts",
        "a_tag_vampire": "Night Operative",
        "a_tag_samurai": "Blade Assassin",
        "a_tag_space": "Beyond Berlint",
        "a_tag_parody": "Forger Parody Skit",
        "a_tag_idol": "Anya Idol Stage",
        "a_tag_post_apocalyptic": "Post-War Berlint",
        "a_tag_cyberpunk": "Berlint Cyber Op",
        "a_tag_shounen": "Spy's Brave Heart",
        "a_tag_seinen": "Twilight's Burden",
        "a_tag_shoujo": "Becky's Diary",
        "a_tag_josei": "Yor's Resolve",
        "a_tag_survival": "Survival Mission",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Mission Report",
        "a_mega_completionist": "Legendary Agent",
        "a_completion_rate_50": "Halfway to Peace",
        "a_completion_rate_75": "Nearing World Peace",
        "a_completion_rate_90": "Peace Within Reach",
        "a_no_drop": "Never Abort Mission",
        "a_long_runner_complete": "Long Cover Closed",
        "a_sequel_chain": "Sequel Op Chain",
        "a_clean_list": "Clean Service Record",
        "a_from_ptw": "Orders Executed",
        "a_rewatch_master": "Strix Replay Op",
        "a_short_complete": "Quick Extraction",
        "a_same_day_start_finish": "Same-Day Clearance",
        "a_revival": "Cover Restored",
        "a_zero_to_hero": "Recruit to Agent",
        "a_five_genre_complete": "Five Branch Mastery",
        "a_full_franchise": "Full Franchise Intel",
        "a_batch_complete": "Batch Clearance Op",
        "a_paused_to_done": "Resumed Operation",
        "a_completion_spree": "Completion Barrage",
        "a_multi_rewatch": "Multi-Pass Review",
        "a_dropped_recovery": "Recovered Dead Drop",
        "a_ten_perfect_scores": "Ten Stella Stars",
        "a_seasonal_clear": "Seasonal Op Clear",
        "a_complete_genre_span": "All-Genre Agent",
        "a_monthly_completions": "Monthly Debrief",
        "a_yearly_completions": "Yearly Debriefing",
        "a_rapid_complete": "Flash Mission Done",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Forger Family Ally",
        "a_studio_devotee": "Studio Loyalist",
        "a_rewatcher": "Rewatch Operative",
        "a_triple_rewatch": "Triple Replay Op",
        "a_annual_tradition": "Annual Tradition",
        "a_director_fan": "Director's Asset",
        "a_voice_actor_fan": "Voice Intel Source",
        "a_ost_lover": "Mission Soundtrack",
        "a_source_reader": "Source Material Spy",
        "a_waiting_weekly": "Weekly Dead Drop",
        "a_childhood_revisit": "Anya's Nostalgia",
        "a_saga_tracker": "Strix Saga Tracker",
        "a_genre_loyalty": "Genre Loyalty Badge",
        "a_decade_watcher": "Decade-Long Agent",
        "a_adaptation_hunter": "Adaptation Recon",
        "a_original_anime_fan": "Broadcast Veteran",
        "a_long_commitment": "Long-Term Cover",
        "a_perfect_attendance": "Eden Attendance Star",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Catalog",
        "a_franchise_collector": "Franchise Intel",
        "a_airing_follower": "Airing Intel Watch",
        "a_genre_master": "Genre Mastery",
        "a_staff_follower": "Staff Dossier Filed",
        "a_multi_season_fan": "Multi-Season Vet",
        "a_format_diversity": "Diverse Formats",
        "a_year_dedication": "Year of Service",
        "a_season_dedication": "Season of Duty",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Genre Fieldwork",
        "a_studio_hopper": "Agency Transfer",
        "a_tag_explorer": "Tag Recon Mission",
        "a_decade_hopper": "Decade Infiltration",
        "a_hidden_gem": "Hidden Dead Drop",
        "a_popular_taste": "Popular Cover ID",
        "a_retro_appreciator": "Retro Intel Source",
        "a_modern_viewer": "Modern Operative",
        "a_cross_demographic": "Cross-Demographic Op",
        "a_underdog_fan": "Underdog Asset",
        "a_variety_week": "Variety Week Op",
        "a_foreign_cinema": "Foreign Intelligence",
        "a_classic_connoisseur": "Classic Spy Film",
        "a_every_season": "Every Season Active",
        "a_award_winner": "Stella Medal Earned",
        "a_niche_explorer": "Niche Territory Scout",
        "a_global_anime": "Global Alliance",
        "a_cult_classic": "Cult Classic Intel",
        "a_random_pick": "Random Assignment",
        "a_new_genre_month": "Monthly New Genre",
        "a_seasonal_completionist": "Seasonal Clear Op",
        "a_unpopular_opinion": "Contrarian Intel",
        "a_top_rated_viewer": "Top-Rated Source",
        "a_source_variety": "Source Variety",
        "a_low_score_brave": "Brave Recon Scout",
        "a_upcoming_watcher": "Upcoming Op Intel",
        "a_short_series_explorer": "Short Op Scout",
        "a_long_series_explorer": "Long Op Scout",

        // ── ANIME TIME ──
        "a_night_owl": "Night Mission Watch",
        "a_early_bird": "Dawn Briefing Hour",
        "a_lunch_break": "Lunch Cover Shift",
        "a_golden_hour": "Golden Hour Signal",
        "a_four_am_club": "4 AM Stakeout",
        "a_witching_hour": "Witching Hour Op",
        "a_new_year_watch": "New Year's Oath",
        "a_midnight_premiere": "Midnight Premiere",
        "a_all_hours": "All-Hours Agent",
        "a_dawn_warrior": "Dawn Operative",
        "a_afternoon_delight": "Afternoon Recon",
        "a_prime_time": "Prime Time Intel",
        "a_workday_watcher": "On-Duty Watcher",
        "a_sunday_marathon": "Sunday Op Marathon",
        "a_rainy_day": "Rainy Berlint Day",
        "a_morning_routine": "Morning Routine",
        "a_night_shift": "Night Shift Agent",
        "a_twilight_zone": "Twilight Hour",
        "a_seasonal_premier": "Season Premiere Op",
        "a_clock_collector": "Clock Tower Intel",
        "a_weekend_binge_hours": "Weekend Binge Ops",
        "a_late_night_regular": "Late Night Patrol",
        "a_sunrise_watcher": "Berlint Sunrise",
        "a_holiday_watcher": "Holiday Guard Duty",
        "a_every_day_of_week": "Every Day Active",
        "a_monthly_hours": "Monthly Hours Filed",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Squad Formation",
        "a_party_host": "Handler's Gathering",
        "a_social_butterfly": "Berlint Gala Socialite",
        "a_group_binge": "Group Stakeout Op",
        "a_party_regular": "Regular Meetup",
        "a_sync_viewer": "Synced Comms Link",
        "a_commentator": "Op Commentator",
        "a_party_marathon": "Party Marathon Op",
        "a_full_house": "Forger Full House",
        "a_community_pillar": "Community Pillar",
        "a_watch_party_streak": "Party Op Streak",
        "a_diverse_party": "Diverse Gathering",
        "a_late_night_party": "Late Night Gala",
        "a_party_veteran": "Veteran Party Host",
        "a_genre_party": "Genre Party Mix",
        "a_weekly_party": "Weekly Gathering",
        "a_silent_viewer": "Silent Observer",
        "a_recommendation_giver": "Handler's Tip",
        "a_party_completionist": "Party Completionist",
        "a_social_scorer": "Social Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Op",
        "a_fibonacci": "Fibonacci Cipher",
        "a_palindrome_day": "Palindrome Code Day",
        "a_binary_day": "Binary Signal Day",
        "a_full_moon": "Full Moon Mission",
        "a_leap_year": "Leap Year Op",
        "a_time_traveler": "Bond's Foresight",
        "a_genre_clash": "Genre Clash Op",
        "a_triple_seven": "Triple Seven Code",
        "a_thousand_complete": "Thousand Ops Done",
        "a_pi_episodes": "Pi Cipher Calc",
        "a_synchronicity": "Family Synchronicity",
        "a_world_record": "World Record Op",
        "a_nice": "Nice Op Count",
        "a_power_level": "Yor's Power Level",
        "a_answer_42": "Answer to Peace",
        "a_square_number": "Square Formation",
        "a_prime_count": "Prime Code Count",
        "a_matching_date": "Matching Intel Date",
        "a_century_episode": "Century Episode Op",
        "a_double_digits": "Double Digit Ops",
        "a_one_two_three": "Loid Anya Yor",
        "a_lucky_seven": "Lucky Seven Agents",
        "a_all_tens": "All Stella Stars",
        "a_exact_hundred_eps": "Exact Hundred Ops",
        "a_year_match_count": "Year Match Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Agent",
        "a_movie_buff": "Movie Night Forger",
        "a_ova_hunter": "OVA Hunter Op",
        "a_ona_explorer": "ONA Explorer Agent",
        "a_special_watcher": "Special Op Viewer",
        "a_short_king": "Short Mission King",
        "a_variety_pack": "All-Format Arsenal",
        "a_film_festival": "Berlint Film Fest",
        "a_music_video": "Spy Music Score",
        "a_tv_short": "Quick Intel Clip",
        "a_movie_marathon": "Movie Marathon Op",
        "a_double_length": "Double-Length Op",
        "a_anthology": "WISE Anthology",
        "a_mini_series": "Mini Mission Series",
        "a_theatrical": "Theatrical Debut",
        "a_format_master": "Format Master Spy",
        "a_long_movie": "Feature-Length Op",
        "a_back_catalog": "Back Catalog Files",
        "a_cm_watcher": "Commercial Intel",
        "a_pv_collector": "Preview Collector",
        "a_format_balance": "Balanced Formats",
        "a_episodic_master": "Episodic Op Master",
        "a_sequel_movie": "Sequel Film Op",
        "a_recap_watcher": "Debriefing Recap",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Op Streak",
        "a_mega_streak": "Mega Mission Streak",
        "a_weekly_warrior": "Weekly Warrior Agent",
        "a_monthly_watcher": "Monthly Watch Log",
        "a_comeback": "Agent's Return",
        "a_weekend_streak": "Weekend Op Streak",
        "a_no_zero_days": "No Zero Days",
        "a_iron_will": "Iron Will Agent",
        "a_habit_formed": "Spy Discipline",
        "a_consistent_pace": "Twilight's Pace",
        "a_year_long": "Year-Long Op Streak",
        "a_double_streak": "Double Streak Op",
        "a_streak_recovery": "Cover Recovery",
        "a_daily_minimum": "Daily Dead Drop",
        "a_winter_streak": "Winter Op Streak",
        "a_summer_streak": "Summer Op Streak",
        "a_morning_streak": "Morning Drill Streak",
        "a_night_streak": "Night Patrol Streak",
        "a_unbreakable": "Unbreakable Cover",
        "a_eternal_flame": "Eternal Mission Fire",
        "a_completion_streak": "Completion Chain Op",
        "a_rating_streak": "Rating Streak Filed",
        "a_multi_ep_streak": "Multi-Ep Streak",
        "a_genre_streak": "Genre Streak Op",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Eden Week",

        // ── ANIME SCORING ──
        "a_critic": "WISE Evaluator",
        "a_perfect_ten": "Perfect Stella Star",
        "a_harsh_critic": "Harsh Handler",
        "a_fair_judge": "Fair Assessment",
        "a_generous_spirit": "Generous Spirit",
        "a_score_all": "Full Roster Rated",
        "a_wide_range": "Wide Range Scores",
        "a_controversial": "Controversial Intel",
        "a_consistent_scorer": "Consistent Evaluator",
        "a_score_sniper": "Precision Sniper",
        "a_evolving_taste": "Evolving Tradecraft",
        "a_bell_curve": "Bell Curve Scores",
        "a_picky_watcher": "Selective Agent",
        "a_100_rated": "Century Evaluated",
        "a_500_rated": "Five Hundred Rated",
        "a_mediocre_majority": "Middle Ground Op",
        "a_rating_spree": "Rating Barrage",
        "a_score_variance": "Score Variance",
        "a_masterpiece_hunter": "Masterpiece Hunter",
        "a_contrarian": "Contrarian Agent",
        "a_optimist": "Optimist Spy",
        "a_score_distributor": "Score Distributor",
        "a_genre_critic": "Genre Intel Critic",
        "a_mean_above_8": "Elite Average Score",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow",
        "a_valentines_weeb": "Valentine's Cover Op",
        "a_pi_day": "Pi Day Cipher",
        "a_april_fools": "April Fools Decoy",
        "a_international_anime_day": "Int'l Spy Day",
        "a_star_wars_day": "Ostania Empire Day",
        "a_summer_solstice": "Summer Solstice Op",
        "a_tanabata": "Tanabata Wish",
        "a_friday_13th": "Friday 13th Op",
        "a_halloween_spirit": "Halloween Disguise",
        "a_thanksgiving_binge": "Thanksgiving Feast",
        "a_christmas_special": "Forger Christmas Eve",
        "a_new_years_eve": "New Year's Eve Gala",
        "a_birthday_watch": "Birthday Op Watch",
        "a_holiday_marathon": "Holiday Marathon Op",
        "a_independence_day": "Westalis Freedom Day",
        "a_culture_day": "Berlint Culture Day",
        "a_spring_equinox": "Spring Equinox Op",
        "a_earth_day": "World Peace Day",
        "a_labor_day": "Agent Labor Day",
        "a_winter_solstice": "Winter Gala Op",
        "a_anime_birthday": "Anime Anniversary",
        "a_every_holiday": "Every Holiday Agent",
        "a_consecutive_holidays": "Holiday Op Streak",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Power Awakened",
        "a_meta_collector": "Spy Badge Collector",
        "a_meta_category_starter": "Category Initiation",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "Master Agent Rank",
        "a_meta_xp_earner": "XP Earned on Op",
        "a_meta_difficulty_easy": "Easy Extraction Op",
        "a_meta_difficulty_hard": "Legendary Difficulty",
        "a_meta_unlock_spree": "Unlock Spree Op",
        "a_meta_completionist": "Meta Completionist",
        "a_meta_diverse": "Diverse Portfolio",
        "a_meta_dominator": "Meta Op Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Dead Drop Read",
        "m_chapter_counter": "Chapter Tally Count",
        "m_chapter_titan": "S-Class Chapter Op",
        "m_reading_hours": "Hours Reading Intel",
        "m_reading_time_lord": "Twilight's Library",
        "m_manga_collector": "WISE File Archive",
        "m_library_legend": "Eden Library Legend",
        "m_first_complete": "First File Closed",
        "m_hundred_club": "Hundred Chapter Club",
        "m_first_day": "First Reading Brief",
        "m_first_rating": "First File Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages",
        "m_volume_collector": "Volume Stockpile",
        "m_year_explorer": "Year of Reading Ops",
        "m_century_reader": "Century Reader Agent",
        "m_five_hundred_ch": "Five Hundred Chapters",
        "m_thousand_ch": "Thousand Chapter Intel",
        "m_reading_ten": "Ten Files Open",
        "m_ptr_hoarder": "Reading Backlog Pile",
        "m_dropped_honesty": "File Shelved",
        "m_season_reader": "Seasonal Reader",
        "m_active_reader": "Active Field Reader",
        "m_five_thousand_ch": "Five Thousand Deep",
        "m_ten_completed": "Ten Files Closed",
        "m_fifty_completed": "Fifty Files Done",
        "m_five_hundred_completed": "Elite Reader Record",
        "m_mean_score_tracker": "Average File Rating",
        "m_unique_authors": "Unique Contact Authors",
        "m_all_status": "All Read Statuses",
        "m_first_favorite": "First Favorite Asset",
        "m_favorites_collector": "Favorites Archive",
        "m_days_spent_reading": "Days Reading Intel",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading Op",
        "m_marathon_reader": "Reading Marathon Run",
        "m_weekend_reader": "Weekend Reading Op",
        "m_non_stop_reading": "Nonstop Page Intel",
        "m_one_more_chapter": "One More Chapter",
        "m_speed_read": "Speed Read Extraction",
        "m_double_story": "Double File Feature",
        "m_triple_read": "Triple Read Strike",
        "m_five_a_day": "Five Reads Daily",
        "m_chapter_chain": "Chapter Chain Link",
        "m_volume_binge": "Volume Binge Op",
        "m_power_reader": "Power Reader Agent",
        "m_half_day_read": "Half-Day Archive Dive",
        "m_full_day_read": "Full-Day Archive Op",
        "m_power_weekend": "Power Weekend Read",
        "m_binge_king": "Binge Read Commander",
        "m_no_sleep_read": "All-Night Reading",
        "m_full_series_rush": "Full Series Rush Op",
        "m_seven_day_challenge": "Seven-Day Intel Read",
        "m_hundred_day_read": "Hundred-Day Read Op",
        "m_volume_rush": "Volume Rush Blitz",
        "m_series_sweep": "Series Sweep Op",
        "m_genre_binge": "Genre Binge Op",
        "m_author_binge": "Author Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Tally",
        "m_multi_series_binge": "Multi-Series Binge",
        "m_midnight_binge": "Midnight Archive Run",
        "m_new_year_binge": "New Year Read Rush",
        "m_forty_eight_hour": "48-Hour Read Op",
        "m_oneshot_binge": "Oneshot Blitz Read",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Dossier Filed",
        "m_genre_adventure": "Adventure Intel File",
        "m_genre_comedy": "Comedy Intercept",
        "m_genre_drama": "Drama Dossier Filed",
        "m_genre_fantasy": "Fantasy Intel File",
        "m_genre_horror": "Horror Case File",
        "m_genre_mystery": "Mystery Dossier",
        "m_genre_romance": "Romance Case File",
        "m_genre_scifi": "Sci-Fi Blueprints",
        "m_genre_sol": "Slice of Cover Life",
        "m_genre_sports": "Eden Sports File",
        "m_genre_supernatural": "Supernatural File",
        "m_genre_thriller": "Thriller Dossier",
        "m_genre_psychological": "Psych Warfare File",
        "m_genre_isekai": "Isekai Intel File",
        "m_genre_shounen": "Shounen Spy Heart",
        "m_genre_ecchi": "Beach Chapter Filed",
        "m_genre_mahou_shoujo": "Starlight Anya File",
        "m_genre_mecha": "Mecha Blueprints",
        "m_genre_music": "Music Score Dossier",
        "m_tag_isekai_new": "New World Intel",
        "m_tag_harem": "Harem Case File",
        "m_tag_bl": "Brothers Intel File",
        "m_tag_gl": "Sisters Intel File",
        "m_tag_historical": "Cold War Archive",
        "m_tag_military": "WISE Military File",
        "m_tag_school": "Eden Transcript",
        "m_tag_martial_arts": "Yor's Combat Manual",
        "m_tag_vampire": "Night Ops File",
        "m_tag_samurai": "Blade Arts Dossier",
        "m_tag_space": "Deep Space Intel",
        "m_tag_parody": "Parody Case File",
        "m_tag_idol": "Idol Intel File",
        "m_tag_post_apocalyptic": "Post-War Archive",
        "m_tag_cyberpunk": "Cyber Ops File",
        "m_tag_shoujo": "Shoujo Case File",
        "m_tag_survival": "Survival Dossier",
        "m_tag_cooking": "Yor's Recipe File",
        "m_tag_medical": "Medic Intel File",
        "m_tag_villainess": "Villainess Dossier",

        // ── MANGA COMPLETION ──
        "m_completionist": "File Completionist",
        "m_mega_completionist": "Master Archivist",
        "m_completion_rate_50": "Halfway Decoded",
        "m_completion_rate_75": "Nearly Decoded",
        "m_completion_rate_90": "Almost Deciphered",
        "m_no_drop": "No File Abandoned",
        "m_long_runner_complete": "Long File Closed",
        "m_sequel_chain": "Sequel Chain Link",
        "m_clean_list": "Clean Reading Record",
        "m_from_ptr": "Orders Read & Filed",
        "m_reread_master": "Reread Specialist",
        "m_oneshot_complete": "Oneshot Done",
        "m_same_day_start_finish": "Same-Day Decode",
        "m_revival": "File Reopened",
        "m_zero_to_hundred": "Recruit to Scholar",
        "m_five_genre_complete": "Five Genre Mastery",
        "m_full_collection": "Full Archive Set",
        "m_batch_complete": "Batch Clearance Op",
        "m_paused_to_done": "Resumed Reading Op",
        "m_completion_spree": "Completion Spree",
        "m_format_completionist": "Format Completionist",
        "m_catch_up": "Caught Up to Intel",
        "m_multi_reread": "Multi-Pass Reread",
        "m_dropped_recovery": "Recovered Lost File",
        "m_ten_perfect_scores": "Ten Perfect Files",
        "m_complete_genre_span": "All-Genre Reader",
        "m_monthly_completions": "Monthly Files Closed",
        "m_yearly_completions": "Yearly File Report",
        "m_rapid_complete": "Rapid Decode Op",
        "m_author_complete": "Author Complete File",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal WISE Reader",
        "m_mangaka_lover": "Mangaka Devotee",
        "m_rereader": "Rereader Agent",
        "m_triple_reread": "Triple Reread Op",
        "m_annual_reread": "Annual Reread Rite",
        "m_publisher_fan": "Publisher Ally",
        "m_artist_fan": "Artist Appreciation",
        "m_adaptation_compare": "Adaptation Compare",
        "m_source_material_fan": "Source Material Fan",
        "m_waiting_weekly": "Weekly Drop Wait",
        "m_classic_reader": "Classic File Reader",
        "m_saga_reader": "Strix Saga Reader",
        "m_genre_loyalty": "Genre Loyalty Filed",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "LN Adaptation Intel",
        "m_original_work": "Original Work Fan",
        "m_long_commitment": "Long-Term Commitment",
        "m_up_to_date": "Up-to-Date Intel",
        "m_favorite_mangaka": "Favorite Mangaka",
        "m_complete_portfolio": "Complete Portfolio",
        "m_franchise_collector": "Franchise Collector",
        "m_serialization_follower": "Serial Follower",
        "m_genre_master": "Genre Master Agent",
        "m_multi_series_author": "Multi-Series Author",
        "m_format_diversity": "Diverse Formats",
        "m_year_dedication": "Year Dedicated Reader",
        "m_ongoing_follower": "Ongoing Op Follower",
        "m_genre_loyalty_50": "Fifty Genre Files",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Recon Scout",
        "m_publisher_hopper": "Publisher Transfer",
        "m_tag_explorer": "Tag Recon Op",
        "m_decade_hopper": "Decade Hopper Agent",
        "m_hidden_gem": "Hidden Asset Found",
        "m_popular_taste": "Popular Pick Filed",
        "m_retro_reader": "Retro File Reader",
        "m_modern_reader": "Modern Reader Agent",
        "m_cross_demographic": "Cross-Demographic Op",
        "m_underdog_fan": "Underdog Fan Agent",
        "m_variety_week": "Variety Week Read",
        "m_manhwa_reader": "Manhwa Intel Source",
        "m_manhua_reader": "Manhua Intel Source",
        "m_classic_connoisseur": "Classic Connoisseur",
        "m_award_winner": "Award-Winning File",
        "m_niche_explorer": "Niche Territory Scout",
        "m_world_manga": "World Manga Intel",
        "m_cult_classic": "Cult Classic Find",
        "m_random_pick": "Random Assignment",
        "m_new_genre_month": "Monthly New Genre",
        "m_year_completionist": "Year Completionist",
        "m_unpopular_opinion": "Bold Opinion Filed",
        "m_top_rated_reader": "Top-Rated Source",
        "m_source_variety": "Source Variety Read",
        "m_low_score_brave": "Brave Low Score",
        "m_short_manga_explorer": "Short File Scout",
        "m_long_manga_explorer": "Long File Scout",
        "m_serialization_explorer": "Serial Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Reader",
        "m_early_bird": "Dawn Read Briefing",
        "m_lunch_reader": "Lunch Break Read",
        "m_commute_reader": "Commute Intel Read",
        "m_four_am_club": "4 AM Sentry Read",
        "m_new_year_read": "New Year's Read Op",
        "m_all_hours": "All-Hours Reader",
        "m_prime_time_reader": "Prime Time Read",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Read Mission",
        "m_morning_routine": "Morning Read Brief",
        "m_night_shift_reader": "Night Shift Reader",
        "m_seasonal_premier_read": "New Release Intel",
        "m_clock_collector": "Clock Intel Collector",
        "m_late_night_horror": "Midnight Horror Read",
        "m_afternoon_reader": "Afternoon Intel Read",
        "m_golden_hour_reader": "Golden Hour Read",
        "m_dawn_reader": "Dawn Reader Agent",
        "m_twilight_reader": "Twilight Read Hour",
        "m_midnight_start": "Midnight Start Op",
        "m_weekend_binge_hours": "Weekend Binge Read",
        "m_late_night_regular": "Late Night Regular",
        "m_sunrise_reader": "Berlint Sunrise Read",
        "m_every_day_of_week": "Every Day Reading",
        "m_monthly_hours": "Monthly Hours Filed",
        "m_bedtime_reader": "Bedtime Intel Read",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Art Appreciator",
        "m_webtoon_reader": "Webtoon Intel Source",
        "m_full_color": "Full Color Dossier",
        "m_doujin_reader": "Doujin Reader Agent",
        "m_anthology_reader": "Anthology Reader",
        "m_adaptation_reader": "Adaptation Study",
        "m_longstrip_reader": "Longstrip Reader",
        "m_4koma_reader": "4-Koma Comedy Read",
        "m_oneshot_reader": "Oneshot Reader Op",
        "m_format_variety": "Format Intel Variety",
        "m_light_novel_reader": "Light Novel Reader",
        "m_novel_reader": "Novel Operative",
        "m_visual_storyteller": "Visual Narrator",
        "m_colored_classic": "Colored Classic File",
        "m_webcomic_fan": "Webcomic Fan Agent",
        "m_manga_to_anime": "Manga vs Anime Intel",
        "m_seinen_reader": "Seinen Reader Agent",
        "m_josei_reader": "Josei Reader Agent",
        "m_award_winning_art": "Award-Winning Art",
        "m_debut_work": "Debut Work Filed",
        "m_vertical_scroll": "Vertical Scroll Read",
        "m_traditional_format": "Traditional Format",
        "m_cross_media": "Cross-Media Intel",
        "m_spinoff_reader": "Spinoff Reader Op",
        "m_remake_reader": "Remake Reader Op",
        "m_collaboration_reader": "Collab Read Op",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Read Streak",
        "m_mega_streak": "Mega Read Streak",
        "m_weekly_warrior": "Weekly Reader Agent",
        "m_monthly_reader": "Monthly Reader Log",
        "m_comeback": "Reader's Return Op",
        "m_weekend_streak": "Weekend Read Streak",
        "m_no_zero_days": "No Zero Read Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Discipline",
        "m_consistent_pace": "Consistent Reader",
        "m_year_long": "Year-Long Read Op",
        "m_double_streak": "Double Read Streak",
        "m_streak_recovery": "Streak Recovery Op",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Read Streak",
        "m_summer_streak": "Summer Read Streak",
        "m_morning_streak": "Morning Read Streak",
        "m_night_streak": "Night Read Streak",
        "m_unbreakable": "Unbreakable Reader",
        "m_eternal_flame": "Eternal Reader Fire",
        "m_chapter_a_day": "Chapter a Day Op",
        "m_genre_streak": "Genre Read Streak",
        "m_completion_streak": "Done Streak Chain",
        "m_rating_streak": "Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Loyalty Streak",
        "m_perfect_week_manga": "Perfect Read Week",
        "m_diverse_streak": "Diverse Read Streak",

        // ── MANGA SCORING ──
        "m_critic": "Dossier Critic",
        "m_perfect_ten": "Perfect File Score",
        "m_harsh_critic": "Harsh Evaluator",
        "m_fair_judge": "Fair File Judge",
        "m_generous_spirit": "Generous Reader",
        "m_score_all": "Full File Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Review",
        "m_consistent_scorer": "Consistent Scorer",
        "m_score_sniper": "Precision Scorer",
        "m_evolving_taste": "Evolving Read Taste",
        "m_bell_curve": "Bell Curve Scores",
        "m_picky_reader": "Selective Reader",
        "m_100_rated": "Century of Ratings",
        "m_500_rated": "Five Hundred Rated",
        "m_mediocre_majority": "Middle Ground Read",
        "m_rating_spree": "Rating Spree Filed",
        "m_score_variance": "Score Variance Log",
        "m_binge_rater": "Binge Rater Agent",
        "m_reread_rerate": "Reread Re-Rate Op",
        "m_masterpiece_hunter": "Masterpiece Hunter",
        "m_contrarian": "Contrarian Reader",
        "m_optimist": "Optimist Reader Spy",
        "m_score_distributor": "Score Distributor",
        "m_genre_critic": "Genre Dossier Critic",
        "m_mean_above_8": "Elite Read Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year Read Vow",
        "m_valentines_read": "Valentine's Reading",
        "m_pi_day": "Pi Day Chapter Op",
        "m_april_fools": "April Fools Decoy",
        "m_international_manga_day": "Int'l Manga Day",
        "m_free_comic_day": "Free Comic Day Op",
        "m_summer_solstice": "Summer Solstice Read",
        "m_tanabata": "Tanabata Read Wish",
        "m_friday_13th": "Friday 13th Read",
        "m_halloween_read": "Halloween Read Op",
        "m_thanksgiving_binge": "Thanksgiving Binge",
        "m_christmas_read": "Forger Christmas Read",
        "m_new_years_eve": "NYE Read Op",
        "m_birthday_read": "Birthday Reading Op",
        "m_holiday_marathon": "Holiday Read Marathon",
        "m_independence_day": "Westalis Read Day",
        "m_culture_day": "Culture Day Read",
        "m_spring_equinox": "Spring Equinox Read",
        "m_earth_day": "Peace Day Read Op",
        "m_labor_day": "Labor Day Reading",
        "m_winter_solstice": "Winter Solstice Read",
        "m_manga_birthday": "Manga Anniversary",
        "m_every_holiday_reader": "Every Holiday Read",
        "m_consecutive_holidays": "Holiday Read Streak",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number File",
        "m_fibonacci": "Fibonacci Code Read",
        "m_palindrome_day": "Palindrome Read Day",
        "m_binary_day": "Binary Code Read",
        "m_full_moon_read": "Full Moon Read Op",
        "m_leap_year_read": "Leap Year Read Op",
        "m_triple_seven": "Triple Seven Files",
        "m_thousand_complete": "Thousand Files Done",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Yor's Chapter Power",
        "m_answer_42": "Answer to Peace",
        "m_square_number": "Square Chapter Count",
        "m_prime_count": "Prime Chapter Code",
        "m_matching_date": "Matching Read Date",
        "m_century_chapter": "Century Chapter Op",
        "m_pi_chapters": "Pi Chapter Cipher",
        "m_synchronicity": "Read Synchronicity",
        "m_world_record": "World Record Read",
        "m_genre_clash": "Genre Clash Read",
        "m_time_traveler": "Bond's Read Vision",
        "m_double_digits": "Double Digit Files",
        "m_one_two_three": "Loid Anya Yor Read",
        "m_lucky_seven": "Lucky Seven Files",
        "m_exact_hundred_ch": "Exact Hundred Ch",
        "m_year_match_count": "Year Match Chapters",
        "m_chapter_match_date": "Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Agent",
        "m_manhwa_format": "Manhwa Format Op",
        "m_manhua_format": "Manhua Format Op",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Op",
        "m_doujin_format": "Doujin Format Read",
        "m_novel_format": "Novel Format Op",
        "m_format_master_manga": "Format Master Read",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Read Awakened",
        "m_meta_collector": "Read Badge Collector",
        "m_meta_category_starter": "Category Initiated",
        "m_meta_tier_climber": "Read Rank Promoted",
        "m_meta_tier_max": "Max Reader Rank",
        "m_meta_xp_earner": "XP from Reading",
        "m_meta_difficulty_easy": "Easy Read Op",
        "m_meta_difficulty_hard": "Legendary Read Op",
        "m_meta_unlock_spree": "Read Unlock Spree",
        "m_meta_completionist": "Meta Read Complete",
        "m_meta_diverse": "Diverse Read Portfolio",
        "m_meta_dominator": "Meta Read Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg:        "#0a0004",
        primary:   "#dc4173",
        secondary: "#f07090",
        accent:    "#6080c0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/spy-x-family.png",
    particleColor: "#c87090",
    backgroundDim: 0.30,
    backgroundBlur: 30,
    milestoneNames: {
        1:   "Civilian",
        5:   "WISE Recruit",
        14:  "Agent Twilight's Partner",
        26:  "Thorn Princess Ally",
        40:  "Forger Family Member",
        55:  "Secret Keeper",
        70:  "Handler's Trusted",
        85:  "Donovan's Shadow",
        100: "World Peace Mission Complete",
    },
}
