import { AnimeThemeConfig } from "./types"
import {
    GiEyeTarget, GiBloodySword, GiSkullCrossedBones, GiDeathNote,
    GiFlame, GiSpellBook, GiScrollUnfurled, GiGhostAlly,
    GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss } from "react-icons/lu"
import { BiExtension } from "react-icons/bi"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { TbReportSearch } from "react-icons/tb"

export const tokyoGhoulTheme: AnimeThemeConfig = {
    id: "tokyo-ghoul",
    displayName: "Tokyo Ghoul",
    description: "Ghoul and dove collide. Kagune red & CCG steel. Eat or be eaten.",
    fontFamily: "'Rajdhani', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 170 170",
        "--color-brand-300": "240 100 100",
        "--color-brand-400": "210 40 40",
        "--color-brand-500": "175 10 10",
        "--color-brand-600": "135 5 5",
        "--color-brand-700": "95 2 2",
        "--color-brand-800": "60 0 0",
        "--color-brand-900": "35 0 0",
        "--color-brand-950": "15 0 0",
        "--brand": "190 15 15",
        "--background": "#070000",
        "--paper": "#0f0000",
        "--color-gray-950": "6 0 0",
        "--color-gray-900": "12 2 2",
        "--color-gray-800": "22 5 5",
        "--color-gray-700": "36 10 10",
        "--color-gray-600": "58 18 18",
        "--color-gray-500": "90 32 32",
        "--color-gray-400": "140 65 65",
        "--color-gray-300": "185 110 110",
        "--color-gray-200": "220 165 165",
        "--color-gray-100": "242 210 210",
        "--color-gray-50":  "252 245 245",
    },
    sidebarOverrides: {
        "home":           { icon: GiGhostAlly,       label: "Ward 20" },
        "schedule":       { icon: GiAlarmClock,      label: "Hunt Schedule" },
        "manga":          { icon: GiScrollUnfurled,  label: "CCG Files" },
        "lists":          { icon: GiDeathNote,       label: "Ghoul Registry" },
        "discover":       { icon: GiEyeTarget,       label: "Rinkaku Sight" },
        "torrent-list":   { icon: GiBloodySword,     label: "Ghoul Ops" },
        "unmatched":      { icon: GiSkullCrossedBones, label: "Lost Ghouls" },
        "scan-summaries": { icon: TbReportSearch,    label: "Investigation Reports" },
        "auto-downloader":{ icon: LuRss,             label: "Dove Network" },
        "search":         { icon: FiSearch,          label: "Search" },
        "notifications":  { icon: LuBell,            label: "Alerts" },
        "achievements":   { icon: GiTrophyCup,       label: "Rank Board" },
        "theme-manager":  { icon: GiPalette,         label: "Kagune Colors" },
        "extensions":     { icon: BiExtension,       label: "Contracts" },
        "settings":       { icon: GiSettingsKnobs,   label: "Director's Decree" },
    },
    achievementNames: {
        // ===== ANIME MILESTONES =====
        "a_first_episode": "First Kagune Awakening",
        "a_episode_counter": "Feeding Count",
        "a_episode_titan": "Ward Domination",
        "a_hours_invested": "Hours in the Wards",
        "a_time_lord": "Immortal Ghoul",
        "a_anime_collector": "Ghoul Archive",
        "a_library_legend": "CCG Legend Archive",
        "a_first_complete": "First Ghoul Exterminated",
        "a_hundred_club": "Ward 20 Resident",
        "a_first_day": "First Night Hunt",
        "a_first_rating": "RC Factor Assessment",
        "a_ten_thousand_min": "Ten Thousand Breaths",
        "a_season_veteran": "Seasoned Investigator",
        "a_year_explorer": "Year in the Wards",
        "a_century_watcher": "Century-Class Ghoul",
        "a_five_hundred_eps": "Five Hundred Feedings",
        "a_thousand_eps": "A Thousand Hunts",
        "a_watching_ten": "Ten Active Investigations",
        "a_ptw_hoarder": "CCG Case Backlog",
        "a_dropped_honesty": "Abandoned Ward",
        "a_five_thousand_eps": "Five Thousand RC Cells",
        "a_ten_completed": "Ten Ghouls Neutralized",
        "a_fifty_completed": "Fifty Ghoul Cases Closed",
        "a_five_hundred_completed": "Five Hundred Exterminations",
        "a_mean_score_tracker": "Average RC Level",
        "a_unique_studios": "Unique Ward Branches",
        "a_days_spent_watching": "Days as a Ghoul",
        "a_all_status": "Every Ghoul Rating",
        "a_first_favorite": "First Mask Collected",
        "a_favorites_collector": "Mask Collection",

        // ===== ANIME BINGE =====
        "a_binge_watcher": "Ghoul Binge Feeding",
        "a_marathon_runner": "Aogiri Marathon",
        "a_weekend_warrior": "Weekend Ward Patrol",
        "a_non_stop": "Non-Stop Kagune Rampage",
        "a_one_more_episode": "One More Bite",
        "a_speed_run": "Quinque Speed Blitz",
        "a_double_feature": "Double Kakuhou",
        "a_triple_threat": "Triple Kagune Strike",
        "a_five_a_day": "Five Feedings a Day",
        "a_back_to_back": "Back-to-Back Hunts",
        "a_seasonal_binge": "Seasonal Ward Sweep",
        "a_cour_crusher": "Cour Crusher Protocol",
        "a_half_day_watch": "Half-Day Stakeout",
        "a_full_day_watch": "Full-Day Investigation",
        "a_power_weekend": "Power Weekend at Anteiku",
        "a_binge_king": "Binge-Eating King",
        "a_no_sleep": "Sleepless in the 20th Ward",
        "a_entire_season": "Entire Ward Purge",
        "a_seven_day_challenge": "Seven-Day Ghoul Hunt",
        "a_hundred_day_binge": "Hundred-Day Cochlea Siege",
        "a_genre_binge": "Genre Kakuja Binge",
        "a_studio_binge": "Ward Studio Binge",
        "a_season_sweep": "Seasonal Extermination",
        "a_forty_eight_hour": "48-Hour Anteiku Shift",
        "a_ep_counter_day": "Daily Feeding Counter",
        "a_multi_series_binge": "Multi-Ward Raid",
        "a_midnight_binge": "Midnight Ward Patrol",
        "a_new_year_binge": "New Year's Ghoul Feast",

        // ===== ANIME GENRES =====
        "a_genre_action": "Kagune Brawler",
        "a_genre_adventure": "Ward Explorer",
        "a_genre_comedy": "Anteiku Coffee Break",
        "a_genre_drama": "Ken's Tragedy",
        "a_genre_fantasy": "Half-Ghoul Fantasy",
        "a_genre_horror": "Ward Horror Survivor",
        "a_genre_mystery": "CCG Investigator",
        "a_genre_romance": "Touka's Feelings",
        "a_genre_scifi": "RC Cell Science",
        "a_genre_sol": "Peaceful Anteiku Days",
        "a_genre_sports": "Ghoul Combat Training",
        "a_genre_supernatural": "Supernatural Kagune",
        "a_genre_thriller": "Aogiri Thriller",
        "a_genre_mecha": "Quinque Mech",
        "a_genre_music": "Unravel",
        "a_genre_psychological": "Ghoul Mind Split",
        "a_genre_ecchi": "Nutcracker's Dance",
        "a_genre_mahou_shoujo": "Magical Ghoul Girl",
        "a_tag_isekai": "Isekai'd to the Wards",
        "a_tag_harem": "Harem in the 20th Ward",
        "a_tag_bl": "Ghoul Bond",
        "a_tag_gl": "Ghoulette Alliance",
        "a_tag_historical": "Washuu Clan History",
        "a_tag_military": "CCG Military Division",
        "a_tag_school": "Kamii University",
        "a_tag_martial_arts": "Kagune Martial Arts",
        "a_tag_vampire": "Blood-Drinking Ghoul",
        "a_tag_samurai": "Quinque Swordsman",
        "a_tag_space": "Void Beyond the Wards",
        "a_tag_parody": "Ghoul Parody Show",
        "a_tag_idol": "Ghoul Idol Mask",
        "a_tag_post_apocalyptic": "Post-Dragon Tokyo",
        "a_tag_cyberpunk": "Cyberpunk Ward System",
        "a_tag_shounen": "Young Investigator Arc",
        "a_tag_seinen": "Seinen Ghoul Horror",
        "a_tag_shoujo": "Ghoul Maiden",
        "a_tag_josei": "Mature Ghoul Tale",
        "a_tag_survival": "Survive the Wards",

        // ===== ANIME COMPLETION =====
        "a_completionist": "CCG Extermination Complete",
        "a_mega_completionist": "All Wards Cleansed",
        "a_completion_rate_50": "Half the Wards Cleared",
        "a_completion_rate_75": "Aogiri Territory",
        "a_completion_rate_90": "Near-Total Ghoul Purge",
        "a_no_drop": "Never Stop Feeding",
        "a_long_runner_complete": "Long-Running Investigation Closed",
        "a_sequel_chain": "Sequel: re Chain",
        "a_clean_list": "Clean CCG Dossier",
        "a_from_ptw": "From Case File to Field",
        "a_rewatch_master": "Reread the Tragedy",
        "a_short_complete": "Quick Ghoul Dispatch",
        "a_same_day_start_finish": "Same-Day Extermination",
        "a_revival": "Ghoul Revival",
        "a_zero_to_hero": "Human to One-Eyed King",
        "a_five_genre_complete": "Five Ward Types Cleared",
        "a_full_franchise": "Full Ghoul Franchise",
        "a_batch_complete": "Batch Ghoul Purge",
        "a_paused_to_done": "Paused Investigation Closed",
        "a_completion_spree": "Extermination Spree",
        "a_multi_rewatch": "Multi-Kakuja Rewatch",
        "a_dropped_recovery": "Recovered Cold Case",
        "a_ten_perfect_scores": "Ten SSS-Rated Ghouls",
        "a_seasonal_clear": "Seasonal Ward Clearance",
        "a_complete_genre_span": "Complete Genre Kagune",
        "a_monthly_completions": "Monthly Extermination Quota",
        "a_yearly_completions": "Annual Ghoul Report",
        "a_rapid_complete": "Rapid Quinque Deployment",

        // ===== ANIME DEDICATION =====
        "a_loyal_fan": "Sworn Ghoul Alliance",
        "a_studio_devotee": "Devoted to Anteiku",
        "a_rewatcher": "Re-Investigating",
        "a_triple_rewatch": "Triple Kakuja Viewing",
        "a_annual_tradition": "Annual Tragedy Rewatch",
        "a_director_fan": "Following the Chairman",
        "a_voice_actor_fan": "Voice of the Ghoul",
        "a_ost_lover": "Unravel on Repeat",
        "a_source_reader": "Ishida Sui's Manga Reader",
        "a_waiting_weekly": "Waiting for Re: Chapters",
        "a_childhood_revisit": "Revisiting the 20th Ward",
        "a_saga_tracker": "Saga of the One-Eyed",
        "a_genre_loyalty": "Genre Ghoul Loyalty",
        "a_decade_watcher": "Decade in the Wards",
        "a_adaptation_hunter": "Adaptation Investigator",
        "a_original_anime_fan": "Original Root A Fan",
        "a_long_commitment": "Long-Term Ghoul Contract",
        "a_perfect_attendance": "Perfect Anteiku Attendance",
        "a_favorite_studio_5": "Five Favorite Ward Branches",
        "a_complete_catalog": "Complete CCG Catalog",
        "a_franchise_collector": "Ghoul Franchise Collector",
        "a_airing_follower": "Following the Broadcast",
        "a_genre_master": "Genre Ward Master",
        "a_staff_follower": "Following CCG Staff",
        "a_multi_season_fan": "Multi-Season Ghoul Fan",
        "a_format_diversity": "Diverse Kagune Forms",
        "a_year_dedication": "Year of the Ghoul",
        "a_season_dedication": "Seasonal Dedication to the Hunt",

        // ===== ANIME DISCOVERY =====
        "a_genre_explorer": "Ward Genre Explorer",
        "a_studio_hopper": "Ward Hopper",
        "a_tag_explorer": "Tag Explorer: Ghoul Files",
        "a_decade_hopper": "Decade-Hopping Investigator",
        "a_hidden_gem": "Hidden Ghoul in the Wards",
        "a_popular_taste": "Popular Ghoul Taste",
        "a_retro_appreciator": "Retro Ward Files",
        "a_modern_viewer": "Modern Ghoul Era",
        "a_cross_demographic": "Cross-Demographic Ghoul",
        "a_underdog_fan": "Underdog Ghoul Supporter",
        "a_variety_week": "Variety Week at Anteiku",
        "a_foreign_cinema": "Foreign Ghoul Cinema",
        "a_classic_connoisseur": "Classic Ghoul Connoisseur",
        "a_every_season": "Every Season's Ghoul",
        "a_award_winner": "Award-Winning Quinque",
        "a_niche_explorer": "Niche Ward Explorer",
        "a_global_anime": "Global Ghoul Network",
        "a_cult_classic": "Cult of the One-Eyed",
        "a_random_pick": "Random Ghoul Encounter",
        "a_new_genre_month": "New Ward Monthly",
        "a_seasonal_completionist": "Seasonal Completionist Dove",
        "a_unpopular_opinion": "Unpopular Ghoul Opinion",
        "a_top_rated_viewer": "Top-Rated Ghoul Viewer",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Low-Rated Hunt",
        "a_upcoming_watcher": "Upcoming Ghoul Watcher",
        "a_short_series_explorer": "Short Ghoul Story",
        "a_long_series_explorer": "Long Ghoul Saga",

        // ===== ANIME TIME =====
        "a_night_owl": "Night Hunt Specialist",
        "a_early_bird": "Early Morning Patrol",
        "a_lunch_break": "Anteiku Lunch Break",
        "a_golden_hour": "Golden Hour in the Ward",
        "a_four_am_club": "4 AM Ghoul Activity",
        "a_witching_hour": "The Witching Hour Hunt",
        "a_new_year_watch": "New Year's Eve Hunt",
        "a_midnight_premiere": "Midnight Ghoul Premiere",
        "a_all_hours": "All Hours of the Hunt",
        "a_dawn_warrior": "Dawn Patrol Investigator",
        "a_afternoon_delight": "Afternoon at Anteiku",
        "a_prime_time": "Prime Time in the Ward",
        "a_workday_watcher": "Workday Ghoul Watcher",
        "a_sunday_marathon": "Sunday Ghoul Marathon",
        "a_rainy_day": "Rainy Day in the 20th Ward",
        "a_morning_routine": "Morning Coffee at Anteiku",
        "a_night_shift": "Night Shift Investigator",
        "a_twilight_zone": "Twilight Between Human & Ghoul",
        "a_seasonal_premier": "Seasonal Ghoul Premiere",
        "a_clock_collector": "Clock Collector: All Hours",
        "a_weekend_binge_hours": "Weekend Binge in the Wards",
        "a_late_night_regular": "Late-Night Ward Regular",
        "a_sunrise_watcher": "Sunrise Over Tokyo",
        "a_holiday_watcher": "Holiday Ghoul Watcher",
        "a_every_day_of_week": "Every Day a Ghoul Day",
        "a_monthly_hours": "Monthly Hours Logged",

        // ===== ANIME SOCIAL =====
        "a_first_party": "First Anteiku Gathering",
        "a_party_host": "Anteiku Party Host",
        "a_social_butterfly": "Social Ghoul Butterfly",
        "a_group_binge": "Group Feeding Session",
        "a_party_regular": "Regular at Anteiku",
        "a_sync_viewer": "Synchronized Hunt Viewing",
        "a_commentator": "Ward Commentator",
        "a_party_marathon": "Ghoul Party Marathon",
        "a_full_house": "Full House at Anteiku",
        "a_community_pillar": "Pillar of the Ghoul Community",
        "a_watch_party_streak": "Watch Party Hunt Streak",
        "a_diverse_party": "Diverse Ward Party",
        "a_late_night_party": "Late-Night Ghoul Party",
        "a_party_veteran": "Veteran Ghoul Gatherer",
        "a_genre_party": "Genre-Themed Ghoul Party",
        "a_weekly_party": "Weekly Anteiku Meetup",
        "a_silent_viewer": "Silent Ghoul Observer",
        "a_recommendation_giver": "Ghoul Recommender",
        "a_party_completionist": "Party Completionist Ghoul",
        "a_social_scorer": "Social RC Scorer",

        // ===== ANIME SPECIAL =====
        "a_round_number": "Round RC Count",
        "a_fibonacci": "Fibonacci Kagune Pattern",
        "a_palindrome_day": "Palindrome Ghoul Day",
        "a_binary_day": "Binary RC Code",
        "a_full_moon": "Full Moon Hunt",
        "a_leap_year": "Leap Year Ghoul",
        "a_time_traveler": "Time-Displaced Ghoul",
        "a_genre_clash": "Genre Kagune Clash",
        "a_triple_seven": "Triple Seven RC Surge",
        "a_thousand_complete": "Thousand Ghouls Vanquished",
        "a_pi_episodes": "Pi Episodes of Tragedy",
        "a_synchronicity": "Ghoul Synchronicity",
        "a_world_record": "World Record Investigator",
        "a_nice": "Nice Ghoul Number",
        "a_power_level": "Over 9000 RC Cells",
        "a_answer_42": "42: Meaning of Ghoul Life",
        "a_square_number": "Square Kagune Formation",
        "a_prime_count": "Prime Ghoul Count",
        "a_matching_date": "Date Matches the Ward",
        "a_century_episode": "Century Episode in the Ward",
        "a_double_digits": "Double-Digit Ghoul Rank",
        "a_one_two_three": "1-2-3 Kagune Release",
        "a_lucky_seven": "Lucky Seven Wards",
        "a_all_tens": "All Tens: SSS Rating",
        "a_exact_hundred_eps": "Exactly One Hundred Hunts",
        "a_year_match_count": "Year Matches Ghoul Count",

        // ===== ANIME FORMATS =====
        "a_tv_watcher": "TV Ward Broadcast",
        "a_movie_buff": "Ghoul Movie Buff",
        "a_ova_hunter": "OVA: Jack & Pinto Hunter",
        "a_ona_explorer": "ONA Ghoul Explorer",
        "a_special_watcher": "Special Investigation Watcher",
        "a_short_king": "Short Ghoul Encounter",
        "a_variety_pack": "Variety Kagune Pack",
        "a_film_festival": "Ghoul Film Festival",
        "a_music_video": "Unravel Music Video",
        "a_tv_short": "TV Short: Ward Report",
        "a_movie_marathon": "Ghoul Movie Marathon",
        "a_double_length": "Double-Length Raid",
        "a_anthology": "Ghoul Anthology",
        "a_mini_series": "Mini-Series: Ward Stories",
        "a_theatrical": "Theatrical Ghoul Release",
        "a_format_master": "Format Master Investigator",
        "a_long_movie": "Long Ghoul Feature Film",
        "a_back_catalog": "CCG Back Catalog",
        "a_cm_watcher": "CM Spot Watcher",
        "a_pv_collector": "PV Ghoul Trailer Collector",
        "a_format_balance": "Balanced Kagune Formats",
        "a_episodic_master": "Episodic Ward Master",
        "a_sequel_movie": "Sequel: Re Movie",
        "a_recap_watcher": "Recap Ward Briefing",

        // ===== ANIME STREAKS =====
        "a_daily_streak": "Daily Feeding Ritual",
        "a_mega_streak": "Rize's Legacy Streak",
        "a_weekly_warrior": "Weekly Ward Warrior",
        "a_monthly_watcher": "Monthly Ghoul Report",
        "a_comeback": "Ghoul Comeback",
        "a_weekend_streak": "Weekend Hunt Streak",
        "a_no_zero_days": "No Zero Days in the Ward",
        "a_iron_will": "Iron Quinque Will",
        "a_habit_formed": "Ghoul Habit Formed",
        "a_consistent_pace": "Consistent Hunt Pace",
        "a_year_long": "Year-Long Ghoul Contract",
        "a_double_streak": "Double Kakuhou Streak",
        "a_streak_recovery": "Streak Recovery Protocol",
        "a_daily_minimum": "Daily Minimum Feeding",
        "a_winter_streak": "Winter Ward Streak",
        "a_summer_streak": "Summer Hunt Streak",
        "a_morning_streak": "Morning Patrol Streak",
        "a_night_streak": "Night Hunt Streak",
        "a_unbreakable": "Unbreakable Ghoul Will",
        "a_eternal_flame": "Eternal Kagune Flame",
        "a_completion_streak": "Completion Hunt Streak",
        "a_rating_streak": "Rating Streak: RC Levels",
        "a_multi_ep_streak": "Multi-Episode Hunt Streak",
        "a_genre_streak": "Genre Ward Streak",
        "a_studio_streak": "Studio Ward Streak",
        "a_perfect_week": "Perfect Week in the Ward",

        // ===== ANIME SCORING =====
        "a_critic": "Ghoul Evaluator",
        "a_perfect_ten": "One-Eyed King Rating",
        "a_harsh_critic": "Harsh CCG Critic",
        "a_fair_judge": "Fair Ghoul Judge",
        "a_generous_spirit": "Generous Anteiku Spirit",
        "a_score_all": "Full Ward Report",
        "a_wide_range": "Wide RC Range",
        "a_controversial": "Controversial Ghoul Take",
        "a_consistent_scorer": "Consistent RC Scorer",
        "a_score_sniper": "Quinque Score Sniper",
        "a_evolving_taste": "Evolving Ghoul Palate",
        "a_bell_curve": "Bell Curve of the Wards",
        "a_picky_watcher": "Picky Ghoul Eater",
        "a_100_rated": "100 RC Assessments",
        "a_500_rated": "500 RC Assessments",
        "a_mediocre_majority": "Mediocre Ward Majority",
        "a_rating_spree": "Rating Spree: Ghoul Files",
        "a_score_variance": "Score Variance Across Wards",
        "a_masterpiece_hunter": "Masterpiece Ghoul Hunter",
        "a_contrarian": "Contrarian Investigator",
        "a_optimist": "Optimistic Ghoul Outlook",
        "a_score_distributor": "Score Distributor: Ward Ledger",
        "a_genre_critic": "Genre Ghoul Critic",
        "a_mean_above_8": "Mean Above 8: Elite Ghoul",

        // ===== ANIME HOLIDAY =====
        "a_new_years_resolution": "New Year's Ghoul Resolution",
        "a_valentines_weeb": "Valentine's at Anteiku",
        "a_pi_day": "Pi Day: 3.14 Kagune",
        "a_april_fools": "April Fools' Ghoul Prank",
        "a_international_anime_day": "International Ghoul Day",
        "a_star_wars_day": "May the Kagune Be With You",
        "a_summer_solstice": "Summer Solstice Hunt",
        "a_tanabata": "Tanabata Wish: Ghoul's Prayer",
        "a_friday_13th": "Friday the 13th Ward",
        "a_halloween_spirit": "Halloween: Ghoul Mask Night",
        "a_thanksgiving_binge": "Thanksgiving Ghoul Feast",
        "a_christmas_special": "Christmas at Anteiku",
        "a_new_years_eve": "New Year's Eve in the Ward",
        "a_birthday_watch": "Birthday Hunt Watch",
        "a_holiday_marathon": "Holiday Ghoul Marathon",
        "a_independence_day": "Independence from the CCG",
        "a_culture_day": "Ghoul Culture Day",
        "a_spring_equinox": "Spring Equinox Awakening",
        "a_earth_day": "Earth Day: Ghoul Ecology",
        "a_labor_day": "Labor Day at Anteiku",
        "a_winter_solstice": "Winter Solstice in the Wards",
        "a_anime_birthday": "Anime Birthday: Kaneki's Day",
        "a_every_holiday": "Every Holiday a Ghoul Holiday",
        "a_consecutive_holidays": "Consecutive Holiday Hunts",

        // ===== ANIME META =====
        "a_meta_first_unlock": "First Ghoul Unlock",
        "a_meta_collector": "Ghoul Achievement Collector",
        "a_meta_category_starter": "Category Starter: Ward Initiate",
        "a_meta_tier_climber": "Tier Climber: Rising Ghoul",
        "a_meta_tier_max": "Max Tier: Dragon Ascension",
        "a_meta_xp_earner": "XP Earner: RC Cell Harvest",
        "a_meta_difficulty_easy": "Easy Difficulty: C-Rated",
        "a_meta_difficulty_hard": "Hard Difficulty: SSS-Rated",
        "a_meta_unlock_spree": "Unlock Spree: Kagune Burst",
        "a_meta_completionist": "Meta Completionist: V Agent",
        "a_meta_diverse": "Diverse Ghoul Achievements",
        "a_meta_dominator": "Meta Dominator: One-Eyed King",

        // ===== MANGA MILESTONES =====
        "m_first_chapter": "First Ukaku Strike",
        "m_chapter_counter": "Kagune Chapter Count",
        "m_chapter_titan": "Chapter Titan: Dragon Scale",
        "m_reading_hours": "Hours Reading Ishida's Work",
        "m_reading_time_lord": "Time Lord of :re",
        "m_manga_collector": "CCG Database",
        "m_library_legend": "Ghoul Library Legend",
        "m_first_complete": "First Manga Ghoul Slain",
        "m_hundred_club": "Hundred Chapter Ward",
        "m_first_day": "First Day Reading the Wards",
        "m_first_rating": "First RC Manga Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Tragedy",
        "m_volume_collector": "Volume Collector: Cochlea Archive",
        "m_year_explorer": "Year of Manga Investigations",
        "m_century_reader": "Century Reader: Ghoul Scholar",
        "m_five_hundred_ch": "Five Hundred Chapters Devoured",
        "m_thousand_ch": "A Thousand Chapters of Pain",
        "m_reading_ten": "Ten Active Manga Hunts",
        "m_ptr_hoarder": "Plan-to-Read Ghoul Backlog",
        "m_dropped_honesty": "Dropped Manga: Honest Ghoul",
        "m_season_reader": "Seasonal Manga Reader",
        "m_active_reader": "Active Ward Reader",
        "m_five_thousand_ch": "Five Thousand Chapters Consumed",
        "m_ten_completed": "Ten Manga Ghouls Eliminated",
        "m_fifty_completed": "Fifty Manga Cases Closed",
        "m_five_hundred_completed": "Five Hundred Manga Purges",
        "m_mean_score_tracker": "Mean Manga RC Level",
        "m_unique_authors": "Unique Mangaka Tracked",
        "m_all_status": "All Manga Ghoul Statuses",
        "m_first_favorite": "First Favorite Ghoul Manga",
        "m_favorites_collector": "Favorite Manga Mask Wall",
        "m_days_spent_reading": "Days Spent in Manga Wards",

        // ===== MANGA BINGE =====
        "m_binge_reader": "All-Night Ward Patrol",
        "m_marathon_reader": "Manga Marathon: Cochlea Break",
        "m_weekend_reader": "Weekend Manga Ward Patrol",
        "m_non_stop_reading": "Non-Stop Kagune Reading",
        "m_one_more_chapter": "One More Chapter of Pain",
        "m_speed_read": "Speed-Read: Quinque Strike",
        "m_double_story": "Double Ghoul Story",
        "m_triple_read": "Triple Kagune Read",
        "m_five_a_day": "Five Manga Feedings a Day",
        "m_chapter_chain": "Chapter Chain: Rinkaku Link",
        "m_volume_binge": "Volume Binge: Koukaku Crush",
        "m_power_reader": "Power Reader: Bikaku Blast",
        "m_half_day_read": "Half-Day Manga Stakeout",
        "m_full_day_read": "Full-Day Manga Investigation",
        "m_power_weekend": "Power Weekend at :re Café",
        "m_binge_king": "Binge-Reading Ghoul King",
        "m_no_sleep_read": "Sleepless Manga in the Ward",
        "m_full_series_rush": "Full Series Manga Rush",
        "m_seven_day_challenge": "Seven-Day Manga Ghoul Hunt",
        "m_hundred_day_read": "Hundred-Day Manga Siege",
        "m_volume_rush": "Volume Rush: Ward Blitz",
        "m_series_sweep": "Manga Series Ward Sweep",
        "m_genre_binge": "Genre Manga Kagune Binge",
        "m_author_binge": "Mangaka Author Binge",
        "m_chapter_counter_day": "Daily Chapter Feeding Count",
        "m_multi_series_binge": "Multi-Series Manga Raid",
        "m_midnight_binge": "Midnight Manga Ward Patrol",
        "m_new_year_binge": "New Year's Manga Feast",
        "m_forty_eight_hour": "48-Hour Manga Marathon",
        "m_oneshot_binge": "One-Shot Ghoul Binge",

        // ===== MANGA GENRES =====
        "m_genre_action": "Kagune Manga Combat",
        "m_genre_adventure": "Manga Ward Adventure",
        "m_genre_comedy": "Manga Anteiku Comedy",
        "m_genre_drama": "Manga Kaneki Drama",
        "m_genre_fantasy": "Manga Half-Ghoul Fantasy",
        "m_genre_horror": "Horror Ward Manga",
        "m_genre_mystery": "Manga CCG Mystery",
        "m_genre_romance": "Manga Ghoul Romance",
        "m_genre_scifi": "Manga RC Cell Sci-Fi",
        "m_genre_sol": "Manga Peaceful Anteiku",
        "m_genre_sports": "Manga Ghoul Sports",
        "m_genre_supernatural": "Manga Supernatural Kagune",
        "m_genre_thriller": "Manga Aogiri Thriller",
        "m_genre_psychological": "Manga Ghoul Psyche",
        "m_genre_isekai": "Manga Ghoul Isekai",
        "m_genre_shounen": "Manga Young Investigator",
        "m_genre_ecchi": "Manga Ghoul Ecchi",
        "m_genre_mahou_shoujo": "Manga Magical Ghoul",
        "m_genre_mecha": "Manga Quinque Mech",
        "m_genre_music": "Manga Ghoul Melody",
        "m_tag_isekai_new": "Manga New World Ghoul",
        "m_tag_harem": "Manga Ghoul Harem",
        "m_tag_bl": "Manga Ghoul Bond",
        "m_tag_gl": "Manga Ghoulette Alliance",
        "m_tag_historical": "Manga Washuu History",
        "m_tag_military": "Manga CCG Military",
        "m_tag_school": "Manga Kamii Academy",
        "m_tag_martial_arts": "Manga Kagune Arts",
        "m_tag_vampire": "Manga Blood Ghoul",
        "m_tag_samurai": "Manga Quinque Samurai",
        "m_tag_space": "Manga Void Beyond Wards",
        "m_tag_parody": "Manga Ghoul Parody",
        "m_tag_idol": "Manga Ghoul Idol",
        "m_tag_post_apocalyptic": "Manga Post-Dragon World",
        "m_tag_cyberpunk": "Manga Cyberpunk Ward",
        "m_tag_shoujo": "Manga Ghoul Maiden",
        "m_tag_survival": "Manga Ghoul Survival",
        "m_tag_cooking": "Manga Ghoul Cuisine",
        "m_tag_medical": "Manga RC Cell Medicine",
        "m_tag_villainess": "Manga Ghoul Villainess",

        // ===== MANGA COMPLETION =====
        "m_completionist": "Complete Ward Sweep",
        "m_mega_completionist": "Mega Manga Ghoul Purge",
        "m_completion_rate_50": "Half the Manga Wards Cleared",
        "m_completion_rate_75": "75% Manga Ward Control",
        "m_completion_rate_90": "Near-Total Manga Purge",
        "m_no_drop": "Never Drop a Manga Ward",
        "m_long_runner_complete": "Long-Running Manga Case Closed",
        "m_sequel_chain": "Manga Sequel :re Chain",
        "m_clean_list": "Clean Manga Dossier",
        "m_from_ptr": "From Reading List to Field",
        "m_reread_master": "Manga Reread Master",
        "m_oneshot_complete": "One-Shot Manga Complete",
        "m_same_day_start_finish": "Same-Day Manga Dispatch",
        "m_revival": "Manga Ghoul Revival",
        "m_zero_to_hundred": "Zero to Hundred: Manga Ghoul",
        "m_five_genre_complete": "Five Manga Genre Purges",
        "m_full_collection": "Full Manga Ghoul Collection",
        "m_batch_complete": "Batch Manga Purge",
        "m_paused_to_done": "Paused Manga Case Reopened",
        "m_completion_spree": "Manga Extermination Spree",
        "m_format_completionist": "Manga Format Completionist",
        "m_catch_up": "Manga Catch-Up: Ward Briefing",
        "m_multi_reread": "Multi-Reread: Kakuja Study",
        "m_dropped_recovery": "Manga Cold Case Recovery",
        "m_ten_perfect_scores": "Ten Perfect Manga Ghouls",
        "m_complete_genre_span": "Complete Manga Genre Kagune",
        "m_monthly_completions": "Monthly Manga Quota",
        "m_yearly_completions": "Annual Manga Ghoul Report",
        "m_rapid_complete": "Rapid Manga Quinque Strike",
        "m_author_complete": "Author Complete: Mangaka File",

        // ===== MANGA DEDICATION =====
        "m_loyal_reader": "Ghoul Manga Contract",
        "m_mangaka_lover": "Mangaka Devotee: Ishida Sui",
        "m_rereader": "Manga Re-Investigator",
        "m_triple_reread": "Triple Manga Kakuja",
        "m_annual_reread": "Annual Manga Tragedy Reread",
        "m_publisher_fan": "Publisher Fan: Shueisha Dove",
        "m_artist_fan": "Manga Artist Admirer",
        "m_adaptation_compare": "Anime vs Manga: Ghoul Compare",
        "m_source_material_fan": "Original Manga Source Fan",
        "m_waiting_weekly": "Waiting Weekly for :re Chapters",
        "m_classic_reader": "Classic Manga Ghoul Reader",
        "m_saga_reader": "Manga Saga of the One-Eyed",
        "m_genre_loyalty": "Manga Genre Ghoul Loyalty",
        "m_decade_reader": "Decade of Manga Wards",
        "m_ln_adaptation": "Light Novel Ghoul Adaptation",
        "m_original_work": "Original Manga Ghoul Work",
        "m_long_commitment": "Long Manga Ghoul Commitment",
        "m_up_to_date": "Up to Date on All Wards",
        "m_favorite_mangaka": "Favorite Ghoul Mangaka",
        "m_complete_portfolio": "Complete Mangaka Portfolio",
        "m_franchise_collector": "Manga Franchise Collector",
        "m_serialization_follower": "Serialization Follower: Weekly",
        "m_genre_master": "Manga Genre Ward Master",
        "m_multi_series_author": "Multi-Series Mangaka Fan",
        "m_format_diversity": "Manga Format Diversity",
        "m_year_dedication": "Year of Manga Dedication",
        "m_ongoing_follower": "Ongoing Manga Ward Follower",
        "m_genre_loyalty_50": "50 Manga in One Genre Ward",

        // ===== MANGA DISCOVERY =====
        "m_genre_explorer": "Manga Ward Genre Explorer",
        "m_publisher_hopper": "Manga Publisher Hopper",
        "m_tag_explorer": "Manga Tag Ghoul Explorer",
        "m_decade_hopper": "Manga Decade-Hopping Dove",
        "m_hidden_gem": "Hidden Manga Ghoul Gem",
        "m_popular_taste": "Popular Manga Ghoul Taste",
        "m_retro_reader": "Retro Manga Ward Files",
        "m_modern_reader": "Modern Manga Ghoul Era",
        "m_cross_demographic": "Cross-Demographic Manga Ghoul",
        "m_underdog_fan": "Manga Underdog Ghoul Fan",
        "m_variety_week": "Manga Variety Week at :re",
        "m_manhwa_reader": "Manhwa Ghoul Reader",
        "m_manhua_reader": "Manhua Ghoul Reader",
        "m_classic_connoisseur": "Classic Manga Connoisseur",
        "m_award_winner": "Award-Winning Manga Ghoul",
        "m_niche_explorer": "Niche Manga Ward Explorer",
        "m_world_manga": "World Manga Ghoul Network",
        "m_cult_classic": "Cult Manga Classic Ghoul",
        "m_random_pick": "Random Manga Ghoul Pick",
        "m_new_genre_month": "New Manga Genre Monthly",
        "m_year_completionist": "Yearly Manga Ward Sweep",
        "m_unpopular_opinion": "Unpopular Manga Ghoul Take",
        "m_top_rated_reader": "Top-Rated Manga Reader",
        "m_source_variety": "Manga Source Variety",
        "m_low_score_brave": "Brave Low-Rated Manga Hunt",
        "m_short_manga_explorer": "Short Manga Ghoul Story",
        "m_long_manga_explorer": "Long Manga Ghoul Saga",
        "m_serialization_explorer": "Serialization Explorer Ghoul",

        // ===== MANGA TIME =====
        "m_night_owl": "Night Owl Manga Reader",
        "m_early_bird": "Early Bird Manga Dove",
        "m_lunch_reader": "Lunch Break Manga Reader",
        "m_commute_reader": "Commute Manga Reader",
        "m_four_am_club": "4 AM Manga Ghoul Club",
        "m_new_year_read": "New Year Manga Reading",
        "m_all_hours": "All Hours Manga Ghoul",
        "m_prime_time_reader": "Prime Time Manga Reader",
        "m_workday_reader": "Workday Manga Investigator",
        "m_sunday_read": "Sunday Manga at Anteiku",
        "m_morning_routine": "Morning Manga Routine",
        "m_night_shift_reader": "Night Shift Manga Reader",
        "m_seasonal_premier_read": "Seasonal Manga Premiere",
        "m_clock_collector": "Manga Clock Collector",
        "m_late_night_horror": "Late-Night Horror Manga",
        "m_afternoon_reader": "Afternoon Manga at :re",
        "m_golden_hour_reader": "Golden Hour Manga Reader",
        "m_dawn_reader": "Dawn Manga Patrol Reader",
        "m_twilight_reader": "Twilight Manga Ghoul Reader",
        "m_midnight_start": "Midnight Manga Start",
        "m_weekend_binge_hours": "Weekend Manga Binge Hours",
        "m_late_night_regular": "Late-Night Manga Regular",
        "m_sunrise_reader": "Sunrise Manga Over Tokyo",
        "m_every_day_of_week": "Every Day Manga Ghoul",
        "m_monthly_hours": "Monthly Manga Hours Logged",
        "m_bedtime_reader": "Bedtime Manga Reader",

        // ===== MANGA CREATIVE =====
        "m_art_appreciator": "Ishida Sui Art Appreciator",
        "m_webtoon_reader": "Webtoon Ghoul Reader",
        "m_full_color": "Full-Color Ghoul Manga",
        "m_doujin_reader": "Doujin Ghoul Reader",
        "m_anthology_reader": "Ghoul Anthology Reader",
        "m_adaptation_reader": "Adaptation Manga Reader",
        "m_longstrip_reader": "Longstrip Ghoul Manga",
        "m_4koma_reader": "4-Koma Anteiku Strips",
        "m_oneshot_reader": "One-Shot Ghoul Story",
        "m_format_variety": "Manga Format Variety Ghoul",
        "m_light_novel_reader": "Ghoul Light Novel Reader",
        "m_novel_reader": "Ghoul Novel Reader",
        "m_visual_storyteller": "Visual Ghoul Storyteller",
        "m_colored_classic": "Colored Classic Ghoul Manga",
        "m_webcomic_fan": "Webcomic Ghoul Fan",
        "m_manga_to_anime": "Manga-to-Anime Ghoul Tracker",
        "m_seinen_reader": "Seinen Ghoul Reader",
        "m_josei_reader": "Josei Ghoul Reader",
        "m_award_winning_art": "Award-Winning Ghoul Art",
        "m_debut_work": "Mangaka Debut: Ghoul Origin",
        "m_vertical_scroll": "Vertical Scroll Ghoul",
        "m_traditional_format": "Traditional Manga Ghoul",
        "m_cross_media": "Cross-Media Ghoul Experience",
        "m_spinoff_reader": "Spinoff: Tokyo Ghoul Jack",
        "m_remake_reader": "Remake Ghoul Manga Reader",
        "m_collaboration_reader": "Collaboration Ghoul Reader",

        // ===== MANGA STREAKS =====
        "m_daily_streak": "Daily Ghoul Manga Ritual",
        "m_mega_streak": "Mega Manga Ghoul Streak",
        "m_weekly_warrior": "Weekly Manga Ward Warrior",
        "m_monthly_reader": "Monthly Manga Ghoul Reader",
        "m_comeback": "Manga Ghoul Comeback",
        "m_weekend_streak": "Weekend Manga Hunt Streak",
        "m_no_zero_days": "No Zero Manga Days",
        "m_iron_will": "Iron Quinque Manga Will",
        "m_habit_formed": "Manga Ghoul Habit Formed",
        "m_consistent_pace": "Consistent Manga Pace",
        "m_year_long": "Year-Long Manga Contract",
        "m_double_streak": "Double Manga Kakuhou Streak",
        "m_streak_recovery": "Manga Streak Recovery",
        "m_daily_minimum": "Daily Minimum Manga Feeding",
        "m_winter_streak": "Winter Manga Ward Streak",
        "m_summer_streak": "Summer Manga Hunt Streak",
        "m_morning_streak": "Morning Manga Patrol Streak",
        "m_night_streak": "Night Manga Hunt Streak",
        "m_unbreakable": "Unbreakable Manga Will",
        "m_eternal_flame": "Eternal Manga Kagune Flame",
        "m_chapter_a_day": "A Chapter a Day: Ghoul's Way",
        "m_genre_streak": "Manga Genre Ward Streak",
        "m_completion_streak": "Manga Completion Streak",
        "m_rating_streak": "Manga Rating RC Streak",
        "m_multi_ch_streak": "Multi-Chapter Manga Streak",
        "m_author_streak": "Mangaka Author Streak",
        "m_perfect_week_manga": "Perfect Manga Week",
        "m_diverse_streak": "Diverse Manga Ghoul Streak",

        // ===== MANGA SCORING =====
        "m_critic": "Manga Ghoul Critic",
        "m_perfect_ten": "One-Eyed Manga Rating",
        "m_harsh_critic": "Harsh Manga CCG Critic",
        "m_fair_judge": "Fair Manga Ghoul Judge",
        "m_generous_spirit": "Generous Manga Anteiku Spirit",
        "m_score_all": "Full Manga Ward Report",
        "m_wide_range": "Wide Manga RC Range",
        "m_controversial": "Controversial Manga Ghoul Take",
        "m_consistent_scorer": "Consistent Manga RC Scorer",
        "m_score_sniper": "Manga Quinque Score Sniper",
        "m_evolving_taste": "Evolving Manga Ghoul Palate",
        "m_bell_curve": "Manga Bell Curve of Wards",
        "m_picky_reader": "Picky Manga Ghoul Reader",
        "m_100_rated": "100 Manga RC Assessments",
        "m_500_rated": "500 Manga RC Assessments",
        "m_mediocre_majority": "Mediocre Manga Ward Majority",
        "m_rating_spree": "Manga Rating Spree: Ghoul Files",
        "m_score_variance": "Manga Score Ward Variance",
        "m_binge_rater": "Manga Binge Ghoul Rater",
        "m_reread_rerate": "Reread & Rerate Manga Ghoul",
        "m_masterpiece_hunter": "Manga Masterpiece Ghoul Hunter",
        "m_contrarian": "Manga Contrarian Investigator",
        "m_optimist": "Manga Optimistic Ghoul",
        "m_score_distributor": "Manga Score Ward Ledger",
        "m_genre_critic": "Manga Genre Ghoul Critic",
        "m_mean_above_8": "Manga Mean Above 8: Elite",

        // ===== MANGA HOLIDAY =====
        "m_new_years_resolution": "New Year's Manga Resolution",
        "m_valentines_read": "Valentine's Manga at :re",
        "m_pi_day": "Pi Day Manga: 3.14 Kagune",
        "m_april_fools": "April Fools' Manga Ghoul",
        "m_international_manga_day": "International Manga Ghoul Day",
        "m_free_comic_day": "Free Comic Ghoul Day",
        "m_summer_solstice": "Summer Solstice Manga Hunt",
        "m_tanabata": "Tanabata Manga Ghoul Wish",
        "m_friday_13th": "Friday the 13th Manga Ward",
        "m_halloween_read": "Halloween Manga Mask Night",
        "m_thanksgiving_binge": "Thanksgiving Manga Feast",
        "m_christmas_read": "Christmas Manga at Anteiku",
        "m_new_years_eve": "New Year's Eve Manga Ward",
        "m_birthday_read": "Birthday Manga Reading",
        "m_holiday_marathon": "Holiday Manga Ghoul Marathon",
        "m_independence_day": "Independence Manga Day",
        "m_culture_day": "Manga Ghoul Culture Day",
        "m_spring_equinox": "Spring Manga Equinox",
        "m_earth_day": "Earth Day Manga Ecology",
        "m_labor_day": "Labor Day Manga at Anteiku",
        "m_winter_solstice": "Winter Solstice Manga Wards",
        "m_manga_birthday": "Manga Birthday: Ishida's Day",
        "m_every_holiday_reader": "Every Holiday Manga Ghoul",
        "m_consecutive_holidays": "Consecutive Holiday Manga Hunts",

        // ===== MANGA SPECIAL =====
        "m_round_number": "Round Manga RC Number",
        "m_fibonacci": "Fibonacci Manga Kagune",
        "m_palindrome_day": "Palindrome Manga Ghoul Day",
        "m_binary_day": "Binary Manga RC Code",
        "m_full_moon_read": "Full Moon Manga Hunt",
        "m_leap_year_read": "Leap Year Manga Ghoul",
        "m_triple_seven": "Triple Seven Manga RC",
        "m_thousand_complete": "Thousand Manga Ghouls Vanquished",
        "m_nice": "Nice Manga Ghoul Number",
        "m_power_level_chapters": "Power Level Manga Chapters",
        "m_answer_42": "42: Manga Ghoul Meaning",
        "m_square_number": "Square Manga Kagune",
        "m_prime_count": "Prime Manga Ghoul Count",
        "m_matching_date": "Manga Date Matches Ward",
        "m_century_chapter": "Century Manga Chapter",
        "m_pi_chapters": "Pi Manga Chapters",
        "m_synchronicity": "Manga Ghoul Synchronicity",
        "m_world_record": "Manga World Record Ghoul",
        "m_genre_clash": "Manga Genre Kagune Clash",
        "m_time_traveler": "Manga Time-Displaced Ghoul",
        "m_double_digits": "Double-Digit Manga Ghoul",
        "m_one_two_three": "1-2-3 Manga Kagune Release",
        "m_lucky_seven": "Lucky Seven Manga Wards",
        "m_exact_hundred_ch": "Exactly Hundred Manga Chapters",
        "m_year_match_count": "Manga Year Matches Count",
        "m_chapter_match_date": "Chapter Matches Today's Date",

        // ===== MANGA FORMATS =====
        "m_manga_format": "Manga Format: Ward Standard",
        "m_manhwa_format": "Manhwa Format: Korean Ghoul",
        "m_manhua_format": "Manhua Format: Chinese Ghoul",
        "m_ln_format": "Light Novel Ghoul Format",
        "m_oneshot_format": "One-Shot Ghoul Format",
        "m_doujin_format": "Doujin Ghoul Format",
        "m_novel_format": "Novel Ghoul Format",
        "m_format_master_manga": "Manga Format Master Ghoul",

        // ===== MANGA META =====
        "m_meta_first_unlock": "First Manga Ghoul Unlock",
        "m_meta_collector": "Manga Ghoul Achievement Collector",
        "m_meta_category_starter": "Manga Category: Ward Initiate",
        "m_meta_tier_climber": "Manga Tier: Rising Ghoul",
        "m_meta_tier_max": "Manga Max Tier: Dragon Form",
        "m_meta_xp_earner": "Manga XP: RC Cell Harvest",
        "m_meta_difficulty_easy": "Manga Easy: C-Rated Ghoul",
        "m_meta_difficulty_hard": "Manga Hard: SSS-Rated Ghoul",
        "m_meta_unlock_spree": "Manga Unlock Spree: Kagune Burst",
        "m_meta_completionist": "Manga Meta: V Agent Complete",
        "m_meta_diverse": "Manga Diverse Ghoul Achievements",
        "m_meta_dominator": "Manga Dominator: One-Eyed King",
    },
    musicUrl: "",
    previewColors: {
        bg:        "#070000",
        primary:   "#bf0f0f",
        secondary: "#e03030",
        accent:    "#4a4a5a",
    },
    milestoneNames: {
        1:   "Human",
        5:   "Ghoul Awakened",
        15:  "One-Eyed",
        28:  "CCG Investigator",
        42:  "Special Class",
        58:  "Aogiri Executive",
        72:  "SS-Rated Ghoul",
        86:  "One-Eyed King",
        100: "Dragon",
    },
}
