import { AnimeThemeConfig } from "./types"
import {
    GiPalmTree, GiLanternFlame, GiScrollUnfurled, GiSpellBook,
    GiFlame, GiHeartInside, GiSwordClash, GiStarMedal,
    GiTrophyCup, GiPalette, GiSettingsKnobs, GiAlarmClock,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss } from "react-icons/lu"
import { BiExtension } from "react-icons/bi"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { TbReportSearch } from "react-icons/tb"

export const toradoraTheme: AnimeThemeConfig = {
    id: "toradora",
    displayName: "Toradora!",
    description: "The Palm-top Tiger and the delinquent. Orange & cyan romance.",
    fontFamily: "'Nunito', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap",
    cssVars: {
        "--color-brand-200": "255 200 140",
        "--color-brand-300": "255 165 70",
        "--color-brand-400": "245 125 18",
        "--color-brand-500": "215 90 0",
        "--color-brand-600": "170 65 0",
        "--color-brand-700": "125 44 0",
        "--color-brand-800": "82 28 0",
        "--color-brand-900": "48 15 0",
        "--color-brand-950": "22 6 0",
        "--brand": "225 95 5",
        "--background": "#0a0400",
        "--paper": "#150800",
        "--color-gray-950": "8 4 0",
        "--color-gray-900": "18 9 0",
        "--color-gray-800": "32 18 4",
        "--color-gray-700": "50 28 8",
        "--color-gray-600": "75 44 15",
        "--color-gray-500": "112 70 30",
        "--color-gray-400": "162 112 65",
        "--color-gray-300": "205 155 100",
        "--color-gray-200": "234 195 148",
        "--color-gray-100": "248 228 198",
        "--color-gray-50":  "254 248 235",
    },
    sidebarOverrides: {
        "home":           { icon: GiPalmTree,     label: "Ohashi High" },
        "schedule":       { icon: GiAlarmClock,   label: "Ryuji's Schedule" },
        "manga":          { icon: GiScrollUnfurled,label: "Taiga's Notes" },
        "lists":          { icon: GiSpellBook,    label: "Matchmaking Plans" },
        "discover":       { icon: GiHeartInside,  label: "Crush Hunting" },
        "torrent-list":   { icon: GiSwordClash,   label: "Tiger Ops" },
        "unmatched":      { icon: GiFlame,        label: "Unrequited Feelings" },
        "scan-summaries": { icon: TbReportSearch, label: "Plan Reports" },
        "auto-downloader":{ icon: LuRss,          label: "Gossip Feed" },
        "search":         { icon: FiSearch,       label: "Search" },
        "notifications":  { icon: LuBell,         label: "Alerts" },
        "achievements":   { icon: GiTrophyCup,    label: "Relationship Rank" },
        "theme-manager":  { icon: GiPalette,      label: "Orange Colors" },
        "extensions":     { icon: BiExtension,    label: "Contracts" },
        "settings":       { icon: GiSettingsKnobs,label: "Ryuji's Kitchen" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode":              "Tiger's Debut",
        "a_episode_counter":            "Dragon's Tally",
        "a_episode_titan":              "Tiger Rampage",
        "a_hours_invested":             "Ohashi Hours",
        "a_time_lord":                  "Timeless Tiger",
        "a_anime_collector":            "Orange Collection",
        "a_library_legend":             "Tiger Archive",
        "a_first_complete":             "Confession End",
        "a_hundred_club":               "Century Tiger",
        "a_first_day":                  "Enrollment Day",
        "a_first_rating":               "Tiger Rating",
        "a_ten_thousand_min":           "Ten Thousand Minutes",
        "a_season_veteran":             "Christmas Veteran",
        "a_year_explorer":              "Year's Journey",
        "a_century_watcher":            "Century Watcher",
        "a_five_hundred_eps":           "Five Hundred Views",
        "a_thousand_eps":               "Thousand Episodes",
        "a_watching_ten":               "Ten Tigers",
        "a_ptw_hoarder":                "Backlog Tiger",
        "a_dropped_honesty":            "Honest Retreat",
        "a_five_thousand_eps":          "Five Thousand Views",
        "a_ten_completed":              "Ten Complete",
        "a_fifty_completed":            "Fifty Complete",
        "a_five_hundred_completed":     "Five Hundred Done",
        "a_mean_score_tracker":         "Average Rating",
        "a_unique_studios":             "Studio Roster",
        "a_days_spent_watching":        "Days with Tiger",
        "a_all_status":                 "All Statuses",
        "a_first_favorite":             "First Favorite",
        "a_favorites_collector":        "Favorites Roster",

        // ── ANIME BINGE ──
        "a_binge_watcher":              "Tiger Binge",
        "a_marathon_runner":            "Festival Marathon",
        "a_weekend_warrior":            "Weekend Tiger",
        "a_non_stop":                   "Non-Stop Dragon",
        "a_one_more_episode":           "One More Episode",
        "a_speed_run":                  "Tiger Blitz",
        "a_double_feature":             "Double Tiger",
        "a_triple_threat":              "Triple Dragon",
        "a_five_a_day":                 "Five Daily",
        "a_back_to_back":               "Back-to-Back",
        "a_seasonal_binge":             "Season Sweep",
        "a_cour_crusher":               "Cour Crusher",
        "a_half_day_watch":             "Half-Day Watch",
        "a_full_day_watch":             "Full Day Tiger",
        "a_power_weekend":              "Power Weekend",
        "a_binge_king":                 "Binge King",
        "a_no_sleep":                   "All-Night Tiger",
        "a_entire_season":              "Rapid Season Clear",
        "a_seven_day_challenge":        "Seven-Day Sprint",
        "a_hundred_day_binge":          "Hundred-Day Binge",
        "a_genre_binge":                "Genre Marathon",
        "a_studio_binge":               "Studio Binge",
        "a_season_sweep":               "Season Cleared",
        "a_forty_eight_hour":           "Forty-Eight Hours",
        "a_ep_counter_day":             "Daily Count",
        "a_multi_series_binge":         "Multi-Series Run",
        "a_midnight_binge":             "Midnight Tiger",
        "a_new_year_binge":             "New Year Run",

        // ── ANIME GENRES ──
        "a_genre_action":               "Tiger Strikes",
        "a_genre_adventure":            "Dragon's Journey",
        "a_genre_comedy":               "Ryuuji's Blunder",
        "a_genre_drama":                "Taiga's Tears",
        "a_genre_fantasy":              "Dream Tiger",
        "a_genre_horror":               "Tiger's Wrath",
        "a_genre_mystery":              "Hidden Feelings",
        "a_genre_romance":              "Dragon's Heart",
        "a_genre_scifi":                "Future Tiger",
        "a_genre_sol":                  "Daily Life",
        "a_genre_sports":               "Tiger Training",
        "a_genre_supernatural":         "Tiger Spirit",
        "a_genre_thriller":             "Tiger Pursuit",
        "a_genre_mecha":                "Iron Tiger",
        "a_genre_music":                "Christmas Song",
        "a_genre_psychological":        "Taiga's Mind",
        "a_genre_ecchi":                "Accidental Peek",
        "a_genre_mahou_shoujo":         "Tiger Witch",
        "a_tag_isekai":                 "Another World",
        "a_tag_harem":                  "Tiger's Harem",
        "a_tag_bl":                     "Dragon Bond",
        "a_tag_gl":                     "Minori's Bond",
        "a_tag_historical":             "Ohashi History",
        "a_tag_military":               "Tiger Discipline",
        "a_tag_school":                 "Ohashi Academy",
        "a_tag_martial_arts":           "Tiger Combat",
        "a_tag_vampire":                "Tiger Blood",
        "a_tag_samurai":                "Dragon Blade",
        "a_tag_space":                  "Tiger Beyond",
        "a_tag_parody":                 "Tiger Parody",
        "a_tag_idol":                   "Tiger Idol",
        "a_tag_post_apocalyptic":       "After Christmas",
        "a_tag_cyberpunk":              "Neon Tiger",
        "a_tag_shounen":                "Tiger's Spirit",
        "a_tag_seinen":                 "Tiger's Truth",
        "a_tag_shoujo":                 "Taiga's Devotion",
        "a_tag_josei":                  "Minori's View",
        "a_tag_survival":               "Tiger Survival",

        // ── ANIME COMPLETION ──
        "a_completionist":              "Tiger Completionist",
        "a_mega_completionist":         "Grand Tiger",
        "a_completion_rate_50":         "Halfway There",
        "a_completion_rate_75":         "Almost Confessed",
        "a_completion_rate_90":         "Nearly Complete",
        "a_no_drop":                    "Never Drop Tiger",
        "a_long_runner_complete":       "Long Run Done",
        "a_sequel_chain":               "Dragon Chain",
        "a_clean_list":                 "Clean Record",
        "a_from_ptw":                   "Plans Executed",
        "a_rewatch_master":             "Christmas Rewatch",
        "a_short_complete":             "Quick Tiger",
        "a_same_day_start_finish":      "Same-Day Clear",
        "a_revival":                    "Tiger Revival",
        "a_zero_to_hero":               "Rookie to Tiger",
        "a_five_genre_complete":        "Five Genres Done",
        "a_full_franchise":             "Full Collection",
        "a_batch_complete":             "Batch Cleared",
        "a_paused_to_done":             "Resumed Tiger",
        "a_completion_spree":           "Completion Spree",
        "a_multi_rewatch":              "Multi Rewatch",
        "a_dropped_recovery":           "Tiger Recovery",
        "a_ten_perfect_scores":         "Ten Perfects",
        "a_seasonal_clear":             "Seasonal Tiger",
        "a_complete_genre_span":        "All Genres",
        "a_monthly_completions":        "Monthly Wins",
        "a_yearly_completions":         "Yearly Tiger",
        "a_rapid_complete":             "Lightning Tiger",

        // ── ANIME DEDICATION ──
        "a_loyal_fan":                  "Tiger Alliance",
        "a_studio_devotee":             "Studio Devotee",
        "a_rewatcher":                  "Tiger Rewatch",
        "a_triple_rewatch":             "Triple Christmas",
        "a_annual_tradition":           "Annual Tradition",
        "a_director_fan":               "Director's Fan",
        "a_voice_actor_fan":            "Voice Actor Fan",
        "a_ost_lover":                  "Pre-Parade Fan",
        "a_source_reader":              "LN Reader",
        "a_waiting_weekly":             "Weekly Wait",
        "a_childhood_revisit":          "Tiger Nostalgia",
        "a_saga_tracker":               "Dragon Saga",
        "a_genre_loyalty":              "Loyal Genre",
        "a_decade_watcher":             "Decade Tiger",
        "a_adaptation_hunter":          "Adaptation Fan",
        "a_original_anime_fan":         "Original Fan",
        "a_long_commitment":            "Long Devotion",
        "a_perfect_attendance":         "Perfect Attendance",
        "a_favorite_studio_5":          "Five Studios",
        "a_complete_catalog":           "Full Catalog",
        "a_franchise_collector":        "Tiger Universe",
        "a_airing_follower":            "Airing Fan",
        "a_genre_master":               "Genre Master",
        "a_staff_follower":             "Staff Devotee",
        "a_multi_season_fan":           "Multi-Season Fan",
        "a_format_diversity":           "Format Variety",
        "a_year_dedication":            "Year's Devotion",
        "a_season_dedication":          "Season's Faith",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer":             "Tiger Explorer",
        "a_studio_hopper":              "Studio Hopper",
        "a_tag_explorer":               "Tag Scout",
        "a_decade_hopper":              "Decade Hopper",
        "a_hidden_gem":                 "Hidden Tiger",
        "a_popular_taste":              "Popular Choice",
        "a_retro_appreciator":          "Retro Tiger",
        "a_modern_viewer":              "Modern Tiger",
        "a_cross_demographic":          "Cross-Genre Scout",
        "a_underdog_fan":               "Underdog Spirit",
        "a_variety_week":               "Variety Week",
        "a_foreign_cinema":             "Foreign Films",
        "a_classic_connoisseur":        "Classic Taste",
        "a_every_season":               "Every Season",
        "a_award_winner":               "Award Winner",
        "a_niche_explorer":             "Niche Tiger",
        "a_global_anime":               "Global Tiger",
        "a_cult_classic":               "Cult Classic",
        "a_random_pick":                "Random Tiger",
        "a_new_genre_month":            "New Genre",
        "a_seasonal_completionist":     "Seasonal Clear",
        "a_unpopular_opinion":          "Tiger's Verdict",
        "a_top_rated_viewer":           "Top Rated",
        "a_source_variety":             "Source Variety",
        "a_low_score_brave":            "Tiger Courage",
        "a_upcoming_watcher":           "Upcoming Watch",
        "a_short_series_explorer":      "Short Series",
        "a_long_series_explorer":       "Long Series",

        // ── ANIME TIME ──
        "a_night_owl":                  "Christmas Night",
        "a_early_bird":                 "Dawn Tiger",
        "a_lunch_break":                "Lunch Break",
        "a_golden_hour":                "Golden Tiger",
        "a_four_am_club":               "4 AM Tiger",
        "a_witching_hour":              "Tiger Hour",
        "a_new_year_watch":             "New Year Tiger",
        "a_midnight_premiere":          "Midnight Tiger",
        "a_all_hours":                  "All Hours",
        "a_dawn_warrior":               "Dawn Dragon",
        "a_afternoon_delight":          "Afternoon Tiger",
        "a_prime_time":                 "Prime Time",
        "a_workday_watcher":            "Workday Tiger",
        "a_sunday_marathon":            "Sunday Marathon",
        "a_rainy_day":                  "Rainy Day",
        "a_morning_routine":            "Morning Dragon",
        "a_night_shift":                "Night Tiger",
        "a_twilight_zone":              "Twilight Tiger",
        "a_seasonal_premier":           "Season Premiere",
        "a_clock_collector":            "Clock Tiger",
        "a_weekend_binge_hours":        "Weekend Binge",
        "a_late_night_regular":         "Late Night Tiger",
        "a_sunrise_watcher":            "Sunrise Tiger",
        "a_holiday_watcher":            "Holiday Tiger",
        "a_every_day_of_week":          "Daily Tiger",
        "a_monthly_hours":              "Monthly Hours",

        // ── ANIME SOCIAL ──
        "a_first_party":                "First Squad",
        "a_party_host":                 "Tiger's Party",
        "a_social_butterfly":           "Tiger Social",
        "a_group_binge":                "Group Tiger",
        "a_party_regular":              "Regular Tiger",
        "a_sync_viewer":                "Sync Tiger",
        "a_commentator":                "Tiger Comments",
        "a_party_marathon":             "Party Marathon",
        "a_full_house":                 "Full House",
        "a_community_pillar":           "Tiger Pillar",
        "a_watch_party_streak":         "Party Streak",
        "a_diverse_party":              "Diverse Crew",
        "a_late_night_party":           "Late Night Party",
        "a_party_veteran":              "Party Veteran",
        "a_genre_party":                "Genre Party",
        "a_weekly_party":               "Weekly Crew",
        "a_silent_viewer":              "Silent Dragon",
        "a_recommendation_giver":       "Tiger Recommends",
        "a_party_completionist":        "Party Complete",
        "a_social_scorer":              "Social Score",

        // ── ANIME SPECIAL ──
        "a_round_number":               "Round Tiger",
        "a_fibonacci":                  "Tiger Sequence",
        "a_palindrome_day":             "Palindrome Day",
        "a_binary_day":                 "Binary Tiger",
        "a_full_moon":                  "Full Moon Tiger",
        "a_leap_year":                  "Leap Tiger",
        "a_time_traveler":              "Tiger's Memory",
        "a_genre_clash":                "Tiger vs Dragon",
        "a_triple_seven":               "Triple Seven",
        "a_thousand_complete":          "Thousand Complete",
        "a_pi_episodes":                "Pi Tiger",
        "a_synchronicity":              "Tiger Sync",
        "a_world_record":               "Tiger Record",
        "a_nice":                       "Nice Tiger",
        "a_power_level":                "Tiger Power",
        "a_answer_42":                  "Tiger's Answer",
        "a_square_number":              "Square Tiger",
        "a_prime_count":                "Prime Tiger",
        "a_matching_date":              "Matching Date",
        "a_century_episode":            "Century Tiger",
        "a_double_digits":              "Double Digits",
        "a_one_two_three":              "One Two Three",
        "a_lucky_seven":                "Lucky Tiger",
        "a_all_tens":                   "All Tens",
        "a_exact_hundred_eps":          "Exact Hundred",
        "a_year_match_count":           "Year Match",

        // ── ANIME FORMATS ──
        "a_tv_watcher":                 "TV Tiger",
        "a_movie_buff":                 "Tiger Films",
        "a_ova_hunter":                 "OVA Tiger",
        "a_ona_explorer":               "ONA Tiger",
        "a_special_watcher":            "Special Tiger",
        "a_short_king":                 "Short Tiger",
        "a_variety_pack":               "All Formats",
        "a_film_festival":              "Tiger Festival",
        "a_music_video":                "Tiger MV",
        "a_tv_short":                   "TV Short",
        "a_movie_marathon":             "Movie Marathon",
        "a_double_length":              "Double Length",
        "a_anthology":                  "Tiger Anthology",
        "a_mini_series":                "Mini Tiger",
        "a_theatrical":                 "Tiger Theatre",
        "a_format_master":              "Format Master",
        "a_long_movie":                 "Long Film",
        "a_back_catalog":               "Back Catalog",
        "a_cm_watcher":                 "CM Tiger",
        "a_pv_collector":               "PV Collector",
        "a_format_balance":             "Format Balance",
        "a_episodic_master":            "Episodic Tiger",
        "a_sequel_movie":               "Sequel Film",
        "a_recap_watcher":              "Recap Tiger",

        // ── ANIME STREAKS ──
        "a_daily_streak":               "Daily Dragon",
        "a_mega_streak":                "Mega Tiger Streak",
        "a_weekly_warrior":             "Weekly Tiger",
        "a_monthly_watcher":            "Monthly Tiger",
        "a_comeback":                   "Tiger Returns",
        "a_weekend_streak":             "Weekend Streak",
        "a_no_zero_days":               "No Zero Days",
        "a_iron_will":                  "Tiger Iron Will",
        "a_habit_formed":               "Tiger Habit",
        "a_consistent_pace":            "Tiger Pace",
        "a_year_long":                  "Year-Long Tiger",
        "a_double_streak":              "Double Streak",
        "a_streak_recovery":            "Streak Recovered",
        "a_daily_minimum":              "Daily Minimum",
        "a_winter_streak":              "Winter Tiger",
        "a_summer_streak":              "Summer Tiger",
        "a_morning_streak":             "Morning Streak",
        "a_night_streak":               "Night Streak",
        "a_unbreakable":                "Tiger Unbreakable",
        "a_eternal_flame":              "Eternal Tiger",
        "a_completion_streak":          "Completion Streak",
        "a_rating_streak":              "Rating Streak",
        "a_multi_ep_streak":            "Multi-Ep Streak",
        "a_genre_streak":               "Genre Streak",
        "a_studio_streak":              "Studio Streak",
        "a_perfect_week":               "Perfect Week",

        // ── ANIME SCORING ──
        "a_critic":                     "Tiger Critic",
        "a_perfect_ten":                "Tiger's Ten",
        "a_harsh_critic":               "Harsh Tiger",
        "a_fair_judge":                 "Dragon's Judgment",
        "a_generous_spirit":            "Generous Tiger",
        "a_score_all":                  "Full Roster",
        "a_wide_range":                 "Wide Scores",
        "a_controversial":              "Controversial Tiger",
        "a_consistent_scorer":          "Consistent Tiger",
        "a_score_sniper":               "Tiger Sniper",
        "a_evolving_taste":             "Tiger Evolves",
        "a_bell_curve":                 "Bell Curve",
        "a_picky_watcher":              "Picky Tiger",
        "a_100_rated":                  "Hundred Ratings",
        "a_500_rated":                  "Five Hundred Ratings",
        "a_mediocre_majority":          "Middle Tiger",
        "a_rating_spree":               "Tiger Rampage",
        "a_score_variance":             "Tiger Variance",
        "a_masterpiece_hunter":         "Masterpiece Tiger",
        "a_contrarian":                 "Tiger Contrarian",
        "a_optimist":                   "Tiger Optimist",
        "a_score_distributor":          "Score Distributor",
        "a_genre_critic":               "Genre Critic",
        "a_mean_above_8":               "Elite Tiger",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution":       "Tiger's Vow",
        "a_valentines_weeb":            "Valentine Tiger",
        "a_pi_day":                     "Pi Tiger",
        "a_april_fools":                "Tiger Prank",
        "a_international_anime_day":    "Anime Tiger Day",
        "a_star_wars_day":              "Tiger Empire",
        "a_summer_solstice":            "Summer Tiger",
        "a_tanabata":                   "Tiger's Wish",
        "a_friday_13th":                "Friday Tiger",
        "a_halloween_spirit":           "Halloween Tiger",
        "a_thanksgiving_binge":         "Tiger Feast",
        "a_christmas_special":          "Christmas Tiger",
        "a_new_years_eve":              "New Year's Eve",
        "a_birthday_watch":             "Birthday Tiger",
        "a_holiday_marathon":           "Holiday Tiger",
        "a_independence_day":           "Tiger's Freedom",
        "a_culture_day":                "Tiger Culture Day",
        "a_spring_equinox":             "Spring Tiger",
        "a_earth_day":                  "Tiger Earth",
        "a_labor_day":                  "Tiger Labor",
        "a_winter_solstice":            "Winter Tiger",
        "a_anime_birthday":             "Anime Birthday",
        "a_every_holiday":              "Every Holiday",
        "a_consecutive_holidays":       "Holiday Streak",

        // ── ANIME META ──
        "a_meta_first_unlock":          "Tiger Awakens",
        "a_meta_collector":             "Tiger Badges",
        "a_meta_category_starter":      "Category Tiger",
        "a_meta_tier_climber":          "Tiger Climbs",
        "a_meta_tier_max":              "Tiger Maximum",
        "a_meta_xp_earner":             "Tiger XP",
        "a_meta_difficulty_easy":       "Easy Tiger",
        "a_meta_difficulty_hard":       "Tiger Legend",
        "a_meta_unlock_spree":          "Tiger Spree",
        "a_meta_completionist":         "Meta Tiger",
        "a_meta_diverse":               "Diverse Tiger",
        "a_meta_dominator":             "Tiger Dominator",

        // ── MANGA MILESTONES ──
        "m_first_chapter":              "First LN Chapter",
        "m_chapter_counter":            "Dragon's Pages",
        "m_chapter_titan":              "Tiger Chapter",
        "m_reading_hours":              "Reading Hours",
        "m_reading_time_lord":          "Timeless Reader",
        "m_manga_collector":            "Tiger Archive",
        "m_library_legend":             "Library Tiger",
        "m_first_complete":             "First LN Done",
        "m_hundred_club":               "Hundred Chapters",
        "m_first_day":                  "First Read Day",
        "m_first_rating":               "First Rating",
        "m_ten_thousand_pages":         "Ten Thousand Pages",
        "m_volume_collector":           "Volume Tiger",
        "m_year_explorer":              "Year Reader",
        "m_century_reader":             "Century Reader",
        "m_five_hundred_ch":            "Five Hundred Chapters",
        "m_thousand_ch":                "Thousand Chapters",
        "m_reading_ten":                "Ten Reading",
        "m_ptr_hoarder":                "PTR Hoarder",
        "m_dropped_honesty":            "Honest Drop",
        "m_season_reader":              "Season Reader",
        "m_active_reader":              "Active Tiger",
        "m_five_thousand_ch":           "Five Thousand Chapters",
        "m_ten_completed":              "Ten Complete",
        "m_fifty_completed":            "Fifty Complete",
        "m_five_hundred_completed":     "Five Hundred Done",
        "m_mean_score_tracker":         "Average Score",
        "m_unique_authors":             "Unique Authors",
        "m_all_status":                 "All Statuses",
        "m_first_favorite":             "First Favorite",
        "m_favorites_collector":        "Favorites Tiger",
        "m_days_spent_reading":         "Days Reading",

        // ── MANGA BINGE ──
        "m_binge_reader":               "Tiger Binge Read",
        "m_marathon_reader":            "Dragon Marathon",
        "m_weekend_reader":             "Weekend Reader",
        "m_non_stop_reading":           "Non-Stop Tiger",
        "m_one_more_chapter":           "One More Chapter",
        "m_speed_read":                 "Tiger Speed Read",
        "m_double_story":               "Double Story",
        "m_triple_read":                "Triple Tiger",
        "m_five_a_day":                 "Five Daily",
        "m_chapter_chain":              "Chapter Chain",
        "m_volume_binge":               "Volume Binge",
        "m_power_reader":               "Power Tiger",
        "m_half_day_read":              "Half-Day Read",
        "m_full_day_read":              "Full-Day Tiger",
        "m_power_weekend":              "Power Weekend",
        "m_binge_king":                 "Binge King",
        "m_no_sleep_read":              "All-Night Tiger",
        "m_full_series_rush":           "Series Rush",
        "m_seven_day_challenge":        "Seven Days",
        "m_hundred_day_read":           "Hundred Days",
        "m_volume_rush":                "Volume Rush",
        "m_series_sweep":               "Series Sweep",
        "m_genre_binge":                "Genre Binge",
        "m_author_binge":               "Author Binge",
        "m_chapter_counter_day":        "Daily Chapters",
        "m_multi_series_binge":         "Multi-Series",
        "m_midnight_binge":             "Midnight Tiger",
        "m_new_year_binge":             "New Year Read",
        "m_forty_eight_hour":           "Forty-Eight Hours",
        "m_oneshot_binge":              "Oneshot Binge",

        // ── MANGA GENRES ──
        "m_genre_action":               "Tiger Action",
        "m_genre_adventure":            "Dragon Adventure",
        "m_genre_comedy":               "Ryuuji's Confusion",
        "m_genre_drama":                "Taiga's Story",
        "m_genre_fantasy":              "Tiger Fantasy",
        "m_genre_horror":               "Tiger Horror",
        "m_genre_mystery":              "Hidden Crush",
        "m_genre_romance":              "Christmas Romance",
        "m_genre_scifi":                "Future Tiger",
        "m_genre_sol":                  "Daily Tiger",
        "m_genre_sports":               "Tiger Sports",
        "m_genre_supernatural":         "Tiger Spirit",
        "m_genre_thriller":             "Tiger Thriller",
        "m_genre_psychological":        "Tiger's Psych",
        "m_genre_isekai":               "Tiger World",
        "m_genre_shounen":              "Shounen Tiger",
        "m_genre_ecchi":                "Taiga's Glare",
        "m_genre_mahou_shoujo":         "Tiger Magic",
        "m_genre_mecha":                "Tiger Mech",
        "m_genre_music":                "Festival Song",
        "m_tag_isekai_new":             "New Tiger World",
        "m_tag_harem":                  "Tiger Harem",
        "m_tag_bl":                     "Dragon Bond",
        "m_tag_gl":                     "Tiger Sisters",
        "m_tag_historical":             "Tiger History",
        "m_tag_military":               "Tiger Military",
        "m_tag_school":                 "Ohashi School",
        "m_tag_martial_arts":           "Tiger Combat",
        "m_tag_vampire":                "Tiger Blood",
        "m_tag_samurai":                "Dragon Blade",
        "m_tag_space":                  "Tiger Space",
        "m_tag_parody":                 "Tiger Comedy",
        "m_tag_idol":                   "Tiger Idol",
        "m_tag_post_apocalyptic":       "Tiger Ruins",
        "m_tag_cyberpunk":              "Neon Tiger",
        "m_tag_shoujo":                 "Taiga Shoujo",
        "m_tag_survival":               "Tiger Survival",
        "m_tag_cooking":                "Ryuuji's Cooking",
        "m_tag_medical":                "Tiger Medical",
        "m_tag_villainess":             "Tiger Villainess",

        // ── MANGA COMPLETION ──
        "m_completionist":              "Tiger Complete",
        "m_mega_completionist":         "Grand Tiger",
        "m_completion_rate_50":         "Half Tiger",
        "m_completion_rate_75":         "Almost Tiger",
        "m_completion_rate_90":         "Nearly Done",
        "m_no_drop":                    "Never Drop",
        "m_long_runner_complete":       "Long Series Done",
        "m_sequel_chain":               "Tiger Chain",
        "m_clean_list":                 "Clean Tiger",
        "m_from_ptr":                   "PTR Executed",
        "m_reread_master":              "Reread Tiger",
        "m_oneshot_complete":           "Oneshot Tiger",
        "m_same_day_start_finish":      "Same-Day Tiger",
        "m_revival":                    "Tiger Revival",
        "m_zero_to_hundred":            "Rookie Tiger",
        "m_five_genre_complete":        "Five Genres",
        "m_full_collection":            "Full Tiger",
        "m_batch_complete":             "Batch Done",
        "m_paused_to_done":             "Back to Tiger",
        "m_completion_spree":           "Tiger Spree",
        "m_format_completionist":       "Format Tiger",
        "m_catch_up":                   "Caught Up",
        "m_multi_reread":               "Multi Reread",
        "m_dropped_recovery":           "Tiger Recovered",
        "m_ten_perfect_scores":         "Ten Perfects",
        "m_complete_genre_span":        "All Genres",
        "m_monthly_completions":        "Monthly Tiger",
        "m_yearly_completions":         "Yearly Tiger",
        "m_rapid_complete":             "Rapid Tiger",
        "m_author_complete":            "Author's Tiger",

        // ── MANGA DEDICATION ──
        "m_loyal_reader":               "Loyal Tiger",
        "m_mangaka_lover":              "Takemiya Fan",
        "m_rereader":                   "Tiger Reread",
        "m_triple_reread":              "Triple Tiger",
        "m_annual_reread":              "Annual Tiger",
        "m_publisher_fan":              "Publisher Fan",
        "m_artist_fan":                 "Artist Tiger",
        "m_adaptation_compare":         "LN vs Anime",
        "m_source_material_fan":        "Source Tiger",
        "m_waiting_weekly":             "Weekly Wait",
        "m_classic_reader":             "Classic Tiger",
        "m_saga_reader":                "Dragon Saga",
        "m_genre_loyalty":              "Loyal Genre",
        "m_decade_reader":              "Decade Tiger",
        "m_ln_adaptation":              "LN Adaptation",
        "m_original_work":              "Original Tiger",
        "m_long_commitment":            "Long Devotion",
        "m_up_to_date":                 "Current Tiger",
        "m_favorite_mangaka":           "Mangaka Fan",
        "m_complete_portfolio":         "Full Portfolio",
        "m_franchise_collector":        "Tiger Franchise",
        "m_serialization_follower":     "Tiger Tracker",
        "m_genre_master":               "Genre Tiger",
        "m_multi_series_author":        "Multi-Author Fan",
        "m_format_diversity":           "Format Tiger",
        "m_year_dedication":            "Year Tiger",
        "m_ongoing_follower":           "Ongoing Tiger",
        "m_genre_loyalty_50":           "Fifty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer":             "Tiger Explorer",
        "m_publisher_hopper":           "Publisher Hop",
        "m_tag_explorer":               "Tag Tiger",
        "m_decade_hopper":              "Decade Tiger",
        "m_hidden_gem":                 "Hidden Tiger",
        "m_popular_taste":              "Popular Tiger",
        "m_retro_reader":               "Retro Tiger",
        "m_modern_reader":              "Modern Tiger",
        "m_cross_demographic":          "Cross-Genre Tiger",
        "m_underdog_fan":               "Underdog Tiger",
        "m_variety_week":               "Variety Week",
        "m_manhwa_reader":              "Manhwa Tiger",
        "m_manhua_reader":              "Manhua Tiger",
        "m_classic_connoisseur":        "Classic Tiger",
        "m_award_winner":               "Award Tiger",
        "m_niche_explorer":             "Niche Tiger",
        "m_world_manga":                "World Tiger",
        "m_cult_classic":               "Cult Tiger",
        "m_random_pick":                "Random Tiger",
        "m_new_genre_month":            "New Genre",
        "m_year_completionist":         "Year Tiger",
        "m_unpopular_opinion":          "Tiger's Take",
        "m_top_rated_reader":           "Top Rated",
        "m_source_variety":             "Source Variety",
        "m_low_score_brave":            "Tiger Courage",
        "m_short_manga_explorer":       "Short Manga",
        "m_long_manga_explorer":        "Long Manga",
        "m_serialization_explorer":     "Serial Tiger",

        // ── MANGA TIME ──
        "m_night_owl":                  "Night Tiger",
        "m_early_bird":                 "Dawn Tiger",
        "m_lunch_reader":               "Lunch Tiger",
        "m_commute_reader":             "Commute Tiger",
        "m_four_am_club":               "4 AM Tiger",
        "m_new_year_read":              "New Year Tiger",
        "m_all_hours":                  "All Hours",
        "m_prime_time_reader":          "Prime Tiger",
        "m_workday_reader":             "Workday Tiger",
        "m_sunday_read":                "Sunday Tiger",
        "m_morning_routine":            "Morning Tiger",
        "m_night_shift_reader":         "Night Tiger",
        "m_seasonal_premier_read":      "Season Premiere",
        "m_clock_collector":            "Clock Tiger",
        "m_late_night_horror":          "Late Night Tiger",
        "m_afternoon_reader":           "Afternoon Tiger",
        "m_golden_hour_reader":         "Golden Tiger",
        "m_dawn_reader":                "Dawn Tiger",
        "m_twilight_reader":            "Twilight Tiger",
        "m_midnight_start":             "Midnight Tiger",
        "m_weekend_binge_hours":        "Weekend Binge",
        "m_late_night_regular":         "Late Night Regular",
        "m_sunrise_reader":             "Sunrise Tiger",
        "m_every_day_of_week":          "Daily Tiger",
        "m_monthly_hours":              "Monthly Hours",
        "m_bedtime_reader":             "Bedtime Tiger",

        // ── MANGA CREATIVE ──
        "m_art_appreciator":            "Art Tiger",
        "m_webtoon_reader":             "Webtoon Tiger",
        "m_full_color":                 "Full Color",
        "m_doujin_reader":              "Doujin Tiger",
        "m_anthology_reader":           "Anthology Tiger",
        "m_adaptation_reader":          "Adaptation Tiger",
        "m_longstrip_reader":           "Longstrip Tiger",
        "m_4koma_reader":               "4-Koma Tiger",
        "m_oneshot_reader":             "Oneshot Tiger",
        "m_format_variety":             "Format Tiger",
        "m_light_novel_reader":         "LN Tiger",
        "m_novel_reader":               "Novel Tiger",
        "m_visual_storyteller":         "Tiger Narrator",
        "m_colored_classic":            "Colored Tiger",
        "m_webcomic_fan":               "Webcomic Tiger",
        "m_manga_to_anime":             "LN to Anime",
        "m_seinen_reader":              "Seinen Tiger",
        "m_josei_reader":               "Josei Tiger",
        "m_award_winning_art":          "Award Art",
        "m_debut_work":                 "Debut Tiger",
        "m_vertical_scroll":            "Vertical Tiger",
        "m_traditional_format":         "Traditional Tiger",
        "m_cross_media":                "Cross-Media Tiger",
        "m_spinoff_reader":             "Spinoff Tiger",
        "m_remake_reader":              "Remake Tiger",
        "m_collaboration_reader":       "Collab Tiger",

        // ── MANGA STREAKS ──
        "m_daily_streak":               "Daily Dragon",
        "m_mega_streak":                "Mega Tiger Streak",
        "m_weekly_warrior":             "Weekly Tiger",
        "m_monthly_reader":             "Monthly Tiger",
        "m_comeback":                   "Tiger Returns",
        "m_weekend_streak":             "Weekend Streak",
        "m_no_zero_days":               "No Zero Days",
        "m_iron_will":                  "Iron Tiger",
        "m_habit_formed":               "Tiger Habit",
        "m_consistent_pace":            "Tiger Pace",
        "m_year_long":                  "Year-Long Tiger",
        "m_double_streak":              "Double Streak",
        "m_streak_recovery":            "Streak Recovered",
        "m_daily_minimum":              "Daily Minimum",
        "m_winter_streak":              "Winter Tiger",
        "m_summer_streak":              "Summer Tiger",
        "m_morning_streak":             "Morning Tiger",
        "m_night_streak":               "Night Tiger",
        "m_unbreakable":                "Unbreakable Tiger",
        "m_eternal_flame":              "Eternal Tiger",
        "m_chapter_a_day":              "Chapter Daily",
        "m_genre_streak":               "Genre Streak",
        "m_completion_streak":          "Completion Streak",
        "m_rating_streak":              "Rating Streak",
        "m_multi_ch_streak":            "Multi-Chapter",
        "m_author_streak":              "Author Devotion",
        "m_perfect_week_manga":         "Perfect Week",
        "m_diverse_streak":             "Diverse Tiger",

        // ── MANGA SCORING ──
        "m_critic":                     "Tiger Critic",
        "m_perfect_ten":                "Tiger's Ten",
        "m_harsh_critic":               "Harsh Tiger",
        "m_fair_judge":                 "Dragon's Judgment",
        "m_generous_spirit":            "Generous Tiger",
        "m_score_all":                  "Full Roster",
        "m_wide_range":                 "Wide Scores",
        "m_controversial":              "Tiger's Take",
        "m_consistent_scorer":          "Consistent Tiger",
        "m_score_sniper":               "Tiger Sniper",
        "m_evolving_taste":             "Tiger Evolves",
        "m_bell_curve":                 "Bell Curve",
        "m_picky_reader":               "Picky Tiger",
        "m_100_rated":                  "Hundred Ratings",
        "m_500_rated":                  "Five Hundred",
        "m_mediocre_majority":          "Middle Tiger",
        "m_rating_spree":               "Tiger Rampage",
        "m_score_variance":             "Tiger Variance",
        "m_binge_rater":                "Binge Rater",
        "m_reread_rerate":              "Reread Rerate",
        "m_masterpiece_hunter":         "Masterpiece Tiger",
        "m_contrarian":                 "Tiger Contrarian",
        "m_optimist":                   "Tiger Optimist",
        "m_score_distributor":          "Tiger Scorer",
        "m_genre_critic":               "Genre Critic",
        "m_mean_above_8":               "Elite Tiger",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution":       "Tiger's New Vow",
        "m_valentines_read":            "Valentine Tiger",
        "m_pi_day":                     "Pi Tiger",
        "m_april_fools":                "Tiger Prank",
        "m_international_manga_day":    "Manga Tiger Day",
        "m_free_comic_day":             "Free Comic Day",
        "m_summer_solstice":            "Summer Tiger",
        "m_tanabata":                   "Tiger's Wish",
        "m_friday_13th":                "Friday Tiger",
        "m_halloween_read":             "Halloween Tiger",
        "m_thanksgiving_binge":         "Tiger Feast",
        "m_christmas_read":             "Christmas Tiger",
        "m_new_years_eve":              "New Year's Eve",
        "m_birthday_read":              "Birthday Tiger",
        "m_holiday_marathon":           "Holiday Tiger",
        "m_independence_day":           "Tiger Freedom",
        "m_culture_day":                "Tiger Culture",
        "m_spring_equinox":             "Spring Tiger",
        "m_earth_day":                  "Tiger Earth",
        "m_labor_day":                  "Tiger Labor",
        "m_winter_solstice":            "Tiger Winter",
        "m_manga_birthday":             "Manga Birthday",
        "m_every_holiday_reader":       "Every Holiday",
        "m_consecutive_holidays":       "Holiday Streak",

        // ── MANGA SPECIAL ──
        "m_round_number":               "Round Tiger",
        "m_fibonacci":                  "Tiger Sequence",
        "m_palindrome_day":             "Palindrome Tiger",
        "m_binary_day":                 "Binary Tiger",
        "m_full_moon_read":             "Full Moon Tiger",
        "m_leap_year_read":             "Leap Tiger",
        "m_triple_seven":               "Triple Seven",
        "m_thousand_complete":          "Thousand Tiger",
        "m_nice":                       "Nice Tiger",
        "m_power_level_chapters":       "Tiger Power",
        "m_answer_42":                  "Tiger's Answer",
        "m_square_number":              "Square Tiger",
        "m_prime_count":                "Prime Tiger",
        "m_matching_date":              "Date Match",
        "m_century_chapter":            "Century Tiger",
        "m_pi_chapters":                "Pi Chapters",
        "m_synchronicity":              "Tiger Sync",
        "m_world_record":               "Tiger Record",
        "m_genre_clash":                "Tiger vs Dragon",
        "m_time_traveler":              "Tiger Travels",
        "m_double_digits":              "Double Digits",
        "m_one_two_three":              "One Two Three",
        "m_lucky_seven":                "Lucky Tiger",
        "m_exact_hundred_ch":           "Exact Hundred",
        "m_year_match_count":           "Year Match",
        "m_chapter_match_date":         "Chapter Date",

        // ── MANGA FORMATS ──
        "m_manga_format":               "Manga Tiger",
        "m_manhwa_format":              "Manhwa Tiger",
        "m_manhua_format":              "Manhua Tiger",
        "m_ln_format":                  "LN Tiger",
        "m_oneshot_format":             "Oneshot Tiger",
        "m_doujin_format":              "Doujin Tiger",
        "m_novel_format":               "Novel Tiger",
        "m_format_master_manga":        "Format Master",

        // ── MANGA META ──
        "m_meta_first_unlock":          "Tiger Awakens",
        "m_meta_collector":             "Tiger Badges",
        "m_meta_category_starter":      "Tiger Starts",
        "m_meta_tier_climber":          "Tiger Climbs",
        "m_meta_tier_max":              "Tiger Peak",
        "m_meta_xp_earner":             "Tiger XP",
        "m_meta_difficulty_easy":       "Easy Tiger",
        "m_meta_difficulty_hard":       "Tiger Legend",
        "m_meta_unlock_spree":          "Tiger Spree",
        "m_meta_completionist":         "Meta Tiger",
        "m_meta_diverse":               "Diverse Tiger",
        "m_meta_dominator":             "Tiger Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg:        "#0a0400",
        primary:   "#e15f05",
        secondary: "#f0900a",
        accent:    "#38c8d0",
    },
    milestoneNames: {
        1:   "Awkward Classmate",
        5:   "Forced Ally",
        14:  "Trusted Friend",
        26:  "Taiga's Protector",
        40:  "Mutual Crush Discoverer",
        55:  "Ami's Rival",
        70:  "Christmas Night Revelation",
        85:  "Dragon & Tiger",
        100: "True Feelings Confessed",
    },
}
