import { AnimeThemeConfig } from "./types"
import { GiCookingPot, GiMeat, GiFoodChain, GiForest, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiMuscleUp, GiHeartKey, GiEagleHead } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const torikoTheme: AnimeThemeConfig = {
    id: "toriko",
    displayName: "Toriko",
    description: "In a world where the best flavours of nature are the ultimate prize, the Gourmet Hunter Toriko ventures into the most dangerous wildernesses to capture legendary ingredients for his ever-growing Full Course Menu.",
    fontFamily: "'Permanent Marker', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap",
    cssVars: {
        "--color-brand-200": "252 220 140",
        "--color-brand-300": "245 190 70",
        "--color-brand-400": "230 158 10",
        "--color-brand-500": "200 124 0",
        "--color-brand-600": "160 92 0",
        "--color-brand-700": "118 64 0",
        "--color-brand-800": "78 40 0",
        "--color-brand-900": "42 18 0",
        "--color-brand-950": "18 6 0",
        "--brand": "200 124 0",
        "--background": "#060300",
        "--paper": "#120800",
        "--color-gray-950": "6 3 0",
        "--color-gray-900": "14 7 0",
        "--color-gray-800": "26 14 2",
        "--color-gray-700": "44 24 6",
        "--color-gray-600": "70 40 12",
        "--color-gray-500": "112 70 25",
        "--color-gray-400": "160 112 55",
        "--color-gray-300": "205 155 88",
        "--color-gray-200": "232 192 128",
        "--color-gray-100": "248 222 172",
        "--color-gray-50": "255 244 225",
    },
    sidebarOverrides: {
        "home": { icon: GiFoodChain, label: "Gourmet World" },
        "schedule": { icon: GiAlarmClock, label: "Hunt Schedule" },
        "manga": { icon: LuBookOpen, label: "Gourmet Bible" },
        "lists": { icon: GiFlowerEmblem, label: "Ingredient Registry" },
        "discover": { icon: GiBullseye, label: "New Beasts" },
        "torrent-list": { icon: GiMeat, label: "Full Course Cache" },
        "debrid": { icon: GiForest, label: "Gourmet Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Ingredients" },
        "enmasse": { icon: GiResize, label: "Combo Hunt" },
        "scan-summaries": { icon: TbReportSearch, label: "Hunt Reports" },
        "auto-downloader": { icon: LuRss, label: "Gourmet Feed" },
        "community": { icon: GiEagleHead, label: "Hunter Circle" },
        "achievements": { icon: GiTrophy, label: "Gourmet Trophies" },
        "milestones": { icon: LuFlag, label: "Full Course Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Ingredient Alerts" },
        "theme-manager": { icon: GiPalette, label: "Gold Palette" },
        "extensions": { icon: BiExtension, label: "Hunt Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Menu Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Toriko's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Hunt",
        "a_first_complete": "Ingredient Captured",
        "a_hundred_club": "Hundred Ingredients",
        "a_time_lord": "Master Hunter",
        "a_anime_collector": "Gourmet Archive",
        "a_library_legend": "Gourmet Library",
        "a_binge_king": "Feast Marathon",
        "a_no_sleep": "All-Night Hunt",
        "a_marathon_runner": "Toriko's Run",
        "a_speed_run": "Quick Capture",
        "a_completionist": "Full Course",
        "a_mega_completionist": "Gourmet God",
        "a_loyal_fan": "Loyal Partner",
        "a_rewatcher": "Replay Hunt",
        "a_decade_watcher": "Decade Hunter",
        "a_genre_action": "Gourmet Battle",
        "a_genre_adventure": "Gourmet World",
        "a_genre_comedy": "Komatsu Comedy",
        "a_genre_drama": "Gourmet Drama",
        "a_genre_fantasy": "Gourmet World",
        "a_genre_horror": "None Here",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "Gourmet Science",
        "a_genre_supernatural": "Gourmet Power",
        "a_genre_psychological": "Toriko's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Gourmet Critic",
        "a_perfect_ten": "Perfect Dish",
        "a_harsh_critic": "Gourmet Standard",
        "a_daily_streak": "Daily Hunt",
        "a_mega_streak": "Endless Feast",
        "a_year_long": "Year of Feasts",
        "a_iron_will": "Toriko's Hunger",
        "a_hidden_gem": "Hidden Ingredient",
        "a_cult_classic": "Gourmet Classic",
        "a_classic_connoisseur": "2011 Fan",
        "a_new_years_resolution": "New Year Feast",
        "a_christmas_special": "Winter Hunt",
        "a_meta_tier_max": "True Gourmet",
        "a_meta_completionist": "Full Course Done",
        "a_sequel_chain": "Toriko's Chain",
        "a_zero_to_hero": "Taste to Legend",
        "a_night_owl": "Night Hunt",
        "a_early_bird": "Dawn Hunt",
        "m_first_chapter": "First Bite",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Gourmet Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Toriko Expert",
        "m_loyal_reader": "Devoted Fan",
        "m_rereader": "Second Course",
        "m_genre_action": "Battle Chapter",
        "m_genre_adventure": "Hunt Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "Gourmet Chapter",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "Science Chapter",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Gourmet Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Gourmet Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Hunger",
        "m_hidden_gem": "Hidden Recipe",
        "m_cult_classic": "Classic Chapter",
        "m_mangaka_lover": "Shimabukuro Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Toriko Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Gourmet Art",
        "m_manga_to_anime": "Adapted Feast",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060300",
        primary: "#c87c00",
        secondary: "#a05c00",
        accent: "#40c050",
    },
    particleColor: "#e8a820",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        golden_sparks: { label: "Gourmet Sparks", maxCount: 16, defaultEnabled: true, defaultIntensity: 52 },
        falling_leaves: { label: "Nature Leaves", maxCount: 12, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
        1: "Amateur Hunter",
        5: "Rookie Hunter",
        15: "Gourmet Hunter",
        30: "Elite Hunter",
        50: "Gourmet King",
        75: "Gourmet Legend",
        100: "Gourmet God",
    },
}
