import { AnimeThemeConfig } from "./types"
import { GiLightningBow, GiBullHorns, GiHeartKey, GiCrown, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiStarFormation } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const urusei_yatsuraTheme: AnimeThemeConfig = {
    id: "urusei-yatsura",
    displayName: "Urusei Yatsura",
    description: "The world's unluckiest lecher Ataru Moroboshi must now live with Lum, the adorable horned alien oni who fell in love with him — zapping him is her love language.",
    fontFamily: "'M PLUS Rounded 1c', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@400;700&display=swap",
    cssVars: {
        "--color-brand-200": "255 240 130",
        "--color-brand-300": "252 225 70",
        "--color-brand-400": "244 205 10",
        "--color-brand-500": "228 182 0",
        "--color-brand-600": "190 150 0",
        "--color-brand-700": "150 116 0",
        "--color-brand-800": "108 82 0",
        "--color-brand-900": "66 48 0",
        "--color-brand-950": "38 27 0",
        "--brand": "228 182 0",
        "--background": "#060500",
        "--paper": "#110e00",
        "--color-gray-950": "6 5 0",
        "--color-gray-900": "14 12 2",
        "--color-gray-800": "26 22 6",
        "--color-gray-700": "44 38 12",
        "--color-gray-600": "68 60 22",
        "--color-gray-500": "105 92 40",
        "--color-gray-400": "148 134 78",
        "--color-gray-300": "186 174 118",
        "--color-gray-200": "214 204 158",
        "--color-gray-100": "232 226 192",
        "--color-gray-50": "246 244 228",
    },
    sidebarOverrides: {
        "home": { icon: GiBullHorns, label: "Tomobiki Town" },
        "schedule": { icon: GiAlarmClock, label: "Lum's Schedule" },
        "manga": { icon: LuBookOpen, label: "Oni Archives" },
        "lists": { icon: GiHeartKey, label: "Darling's List" },
        "discover": { icon: GiBullseye, label: "Space Scouting" },
        "torrent-list": { icon: GiLightningBow, label: "Thunder Cache" },
        "debrid": { icon: GiStarFormation, label: "Oni Technology" },
        "unmatched": { icon: GiCrown, label: "Lost Aliens" },
        "enmasse": { icon: GiResize, label: "Alien Gathering" },
        "scan-summaries": { icon: TbReportSearch, label: "Class Reports" },
        "auto-downloader": { icon: LuRss, label: "Alien Signals" },
        "community": { icon: GiBullHorns, label: "Tomobiki Class" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Lum's Zap" },
        "achievements": { icon: GiTrophy, label: "Darling's Wins" },
        "milestones": { icon: LuFlag, label: "Alien Goals" },
        "theme-manager": { icon: GiPalette, label: "Tiger Stripes" },
        "extensions": { icon: BiExtension, label: "Oni Powers" },
        "sync": { icon: IoCloudOfflineOutline, label: "Space Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Ataru's Controls" },
    },
    achievementNames: {
        "a_first_episode": "First Zap",
        "a_first_complete": "Darling Saved",
        "a_hundred_club": "Hundred Jolts",
        "a_time_lord": "Tomobiki Veteran",
        "a_anime_collector": "Alien Cache",
        "a_library_legend": "Oni Archives",
        "a_binge_king": "Non-Stop Chaos",
        "a_no_sleep": "All-Night Zap",
        "a_marathon_runner": "Chaos Marathon",
        "a_speed_run": "Ataru's Sprint",
        "a_completionist": "School Complete",
        "a_mega_completionist": "Rumiko Master",
        "a_loyal_fan": "Lum's Darling",
        "a_rewatcher": "Return to Tomobiki",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Thunder Action",
        "a_genre_adventure": "Space Adventure",
        "a_genre_comedy": "Romantic Chaos",
        "a_genre_drama": "True Feelings",
        "a_genre_fantasy": "Oni World",
        "a_genre_horror": "Alien Invasion",
        "a_genre_romance": "Lum's Love",
        "a_genre_scifi": "Alien Technology",
        "a_genre_supernatural": "Oni Power",
        "a_genre_psychological": "Ataru's Mind",
        "a_genre_mecha": "Flying Saucer",
        "a_critic": "Chaos Judge",
        "a_perfect_ten": "Perfect Storm",
        "a_harsh_critic": "Stern Teacher",
        "a_daily_streak": "Daily Zap",
        "a_mega_streak": "Endless Thunder",
        "a_year_long": "Year of Chaos",
        "a_iron_will": "Darling's Will",
        "a_hidden_gem": "Hidden Alien",
        "a_cult_classic": "Takahashi Classic",
        "a_classic_connoisseur": "80s Romcom Fan",
        "a_new_years_resolution": "New Year Zap",
        "a_christmas_special": "Holiday Thunder",
        "a_meta_tier_max": "Oni King",
        "a_meta_completionist": "Complete Collection",
        "a_sequel_chain": "School Sequel",
        "a_zero_to_hero": "Unlucky to Darling",
        "a_night_owl": "Night Chaos",
        "a_early_bird": "Dawn Zap",
        "m_first_chapter": "First Chapter",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Marathon Read",
        "m_completionist": "Full Series",
        "m_mega_completionist": "Manga Master",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Chaos Revisited",
        "m_genre_action": "Thunder Chapter",
        "m_genre_adventure": "Space Chapter",
        "m_genre_romance": "Love Chapter",
        "m_genre_fantasy": "Oni Chapter",
        "m_genre_horror": "Alien Horror",
        "m_genre_drama": "Drama Chapter",
        "m_genre_scifi": "Sci-Fi Chapter",
        "m_genre_supernatural": "Power Chapter",
        "m_genre_psychological": "Mind Chapter",
        "m_critic": "Manga Judge",
        "m_perfect_ten": "Perfect Score",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Thunder",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Dedication",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Manga",
        "m_mangaka_lover": "Takahashi Fan",
        "m_source_material_fan": "Original Reader",
        "m_meta_tier_max": "Oni Archive",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Lum Art Fan",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060500",
        primary: "#e4b600",
        secondary: "#967400",
        accent: "#2a9640",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/urusei-yatsura.jpg",
    particleColor: "#e4b600",
    backgroundDim: 0.3,
    backgroundBlur: 18,
    particleTypes: {
        lightning_bolts: { label: "Lightning Bolts", maxCount: 12, defaultEnabled: true, defaultIntensity: 65 },
        stars: { label: "Stars", maxCount: 20, defaultEnabled: true, defaultIntensity: 45 },
    },
    milestoneNames: {
        1: "Unlucky Boy",
        5: "Ataru Moroboshi",
        15: "Darling!",
        30: "Lum's Husband",
        50: "Tomobiki Veteran",
        75: "Chaos Master",
        100: "Rumiko's Legend",
    },
}
