import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiSwordWound,
    GiChainedHeart,
    GiCrossedSwords,
    GiHorseHead,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiBullseye,
    GiAnvilImpact,
    GiResize,
    GiSettingsKnobs,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const vagabondTheme: AnimeThemeConfig = {
    id: "vagabond",
    displayName: "Vagabond",
    description: "Invincible under heaven. Follow Miyamoto Musashi's path of relentless self-mastery through feudal Japan's duels, ink-brushed landscapes, and the Way of the Sword.",
    fontFamily: "'Noto Serif JP', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;700&display=swap",
    cssVars: {
        // Brand → deep ink-brown with parchment warmth
        "--color-brand-200": "228 205 182",
        "--color-brand-300": "202 170 138",
        "--color-brand-400": "160 112 74",
        "--color-brand-500": "107 64 32",
        "--color-brand-600": "82 46 20",
        "--color-brand-700": "60 32 12",
        "--color-brand-800": "40 20 7",
        "--color-brand-900": "24 11 3",
        "--color-brand-950": "13 5 1",
        "--brand": "107 64 32",
        // Dark ink background
        "--background": "#060402",
        "--paper": "#0f0805",
        "--color-gray-950": "6 4 2",
        "--color-gray-900": "10 7 4",
        "--color-gray-800": "18 13 8",
        "--color-gray-700": "30 22 14",
        "--color-gray-600": "46 34 22",
        "--color-gray-500": "70 52 36",
        "--color-gray-400": "105 80 60",
        "--color-gray-300": "148 120 96",
        "--color-gray-200": "185 160 138",
        "--color-gray-100": "218 202 184",
        "--color-gray-50": "240 232 222",
    },
    sidebarOverrides: {
        "home": { icon: GiSwordWound, label: "Musashi's Dojo" },
        "schedule": { icon: GiAlarmClock, label: "Training Schedule" },
        "manga": { icon: LuBookOpen, label: "Scroll Archives" },
        "lists": { icon: GiCrossedSwords, label: "Duelist Records" },
        "discover": { icon: GiBullseye, label: "Beyond the Dojo" },
        "torrent-list": { icon: GiAnvilImpact, label: "Forge Supplies" },
        "debrid": { icon: GiHorseHead, label: "Road Travel" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Wanderers" },
        "enmasse": { icon: GiResize, label: "Mass Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Dojo Reports" },
        "auto-downloader": { icon: LuRss, label: "Challenge Alerts" },
        "community": { icon: GiEagleEmblem, label: "Warrior Community" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Dojo Bells" },
        "achievements": { icon: GiTrophy, label: "Dueling Honors" },
        "theme-manager": { icon: GiPalette, label: "Ink Palette" },
        "extensions": { icon: BiExtension, label: "Blade Attachments" },
        "sync": { icon: IoCloudOfflineOutline, label: "Mountain Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Dojo Command" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Blade Drawn",
        "a_episode_counter": "Sparring Match Tally",
        "a_episode_titan": "Grand Duel Challenger",
        "a_hours_invested": "Hours on the Tokaido",
        "a_time_lord": "Timeless Warrior's Path",
        "a_anime_collector": "Ronin's Arsenal",
        "a_library_legend": "Mountain Library Legend",
        "a_first_complete": "First Journey Completed",
        "a_hundred_club": "Century of Clashes",
        "a_first_day": "First Day of Training",
        "a_first_rating": "Beginner's Assessment",
        "a_ten_thousand_min": "Ten Thousand Training Minutes",
        "a_season_veteran": "Seasonal Campaign Veteran",
        "a_year_explorer": "Year on the Tokaido",
        "a_century_watcher": "Hundred-Episode Vigil",
        "a_five_hundred_eps": "Five Hundred Clashes",
        "a_thousand_eps": "Thousand Road Encounters",
        "a_watching_ten": "Ten Journeys Simultaneously",
        "a_ptw_hoarder": "Unfinished Dojo List",
        "a_dropped_honesty": "Honorable Retreat",
        "a_five_thousand_eps": "Five Thousand Road Miles",
        "a_ten_completed": "Ten Paths Completed",
        "a_fifty_completed": "Fifty Duels Won",
        "a_five_hundred_completed": "Five Hundred Bushido Victories",
        "a_mean_score_tracker": "Average Duel Rating",
        "a_unique_studios": "Allied Dojos",
        "a_days_spent_watching": "Days on the Warrior's Path",
        "a_all_status": "All Wandering Statuses",
        "a_first_favorite": "First Cherished Rival",
        "a_favorites_collector": "Circle of Rivals",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Sword Practice",
        "a_marathon_runner": "Musashi's Road Marathon",
        "a_weekend_warrior": "Weekend Dojo Session",
        "a_non_stop": "Relentless Blade Training",
        "a_one_more_episode": "One More Round",
        "a_speed_run": "Lightning Draw Blitz",
        "a_double_feature": "Double Duel Session",
        "a_triple_threat": "Triple Road Challenge",
        "a_five_a_day": "Five Battles Daily",
        "a_back_to_back": "Back-to-Back Duels",
        "a_seasonal_binge": "Full Season Campaign",
        "a_cour_crusher": "Tokaido Crusher",
        "a_half_day_watch": "Half-Day Swordsmanship",
        "a_full_day_watch": "Full Day Under the Sky",
        "a_power_weekend": "Power Weekend in the Dojo",
        "a_binge_king": "Grandmaster of the Road",
        "a_no_sleep": "All-Night Vigil in the Wild",
        "a_entire_season": "Full Path Cleared",
        "a_seven_day_challenge": "Seven-Day Warrior's Trial",
        "a_hundred_day_binge": "Hundred-Day Isolation Training",
        "a_genre_binge": "Cross-Style Training",
        "a_studio_binge": "Allied Force Viewing",
        "a_season_sweep": "Season Sweep on the Road",
        "a_forty_eight_hour": "Forty-Eight Hour Vigil",
        "a_ep_counter_day": "Daily Battle Count",
        "a_multi_series_binge": "Multiple Road Campaigns",
        "a_midnight_binge": "Midnight Temple Training",
        "a_new_year_binge": "New Year's Vow of the Blade",

        // ── ANIME GENRES ──
        "a_genre_action": "Combat Sword Specialist",
        "a_genre_adventure": "Beyond the Mountain Pass",
        "a_genre_comedy": "Takuan's Wit",
        "a_genre_drama": "Musashi's Inner Conflict",
        "a_genre_fantasy": "Way Beyond the Mortal",
        "a_genre_horror": "Blade's Dark Shadow",
        "a_genre_mystery": "Unfathomable Opponent",
        "a_genre_romance": "Heart Behind the Sword",
        "a_genre_scifi": "Future of the Blade",
        "a_genre_sol": "Peaceful Dojo Life",
        "a_genre_sports": "Tournament Training Grounds",
        "a_genre_supernatural": "Spirit of the Sword",
        "a_genre_thriller": "Duel Under the Moon",
        "a_genre_mecha": "Iron Blade Warfare",
        "a_genre_music": "Song of the Ronin",
        "a_genre_psychological": "Musashi's Inner War",
        "a_genre_ecchi": "Riverside Bathing Scene",
        "a_genre_mahou_shoujo": "Wielder of Light",
        "a_tag_isekai": "Transported to Another Era",
        "a_tag_harem": "Rival and Ally Bonds",
        "a_tag_bl": "Brothers of the Blade",
        "a_tag_gl": "Sisters of the Path",
        "a_tag_historical": "Feudal Japan Chronicles",
        "a_tag_military": "Samurai Discipline",
        "a_tag_school": "Dojo Academy",
        "a_tag_martial_arts": "Way of the Warrior",
        "a_tag_vampire": "Demon Swordsman Legend",
        "a_tag_samurai": "Itto Ryu Blade Style",
        "a_tag_space": "Beyond the Known Horizon",
        "a_tag_parody": "Comedy Ronin Parody",
        "a_tag_idol": "Wings of the Wanderer",
        "a_tag_post_apocalyptic": "Post-Battle Desolation",
        "a_tag_cyberpunk": "Iron Age Technology",
        "a_tag_shounen": "Young Warrior's Spirit",
        "a_tag_seinen": "Harsh Reality of the Sword",
        "a_tag_shoujo": "Otsu's Devotion",
        "a_tag_josei": "Woman's Path Through War",
        "a_tag_survival": "Survival on the Road",

        // ── ANIME COMPLETION ──
        "a_completionist": "Complete Journey Record",
        "a_mega_completionist": "Grand Master Completionist",
        "a_completion_rate_50": "Halfway to Invincibility",
        "a_completion_rate_75": "Approaching the Summit",
        "a_completion_rate_90": "Nearly Invincible Under Heaven",
        "a_no_drop": "No Path Abandoned",
        "a_long_runner_complete": "Long Road Endurance",
        "a_sequel_chain": "Chain of Challenges",
        "a_clean_list": "Clean Dojo Record",
        "a_from_ptw": "Orders Given and Fulfilled",
        "a_rewatch_master": "Blade Technique Replay",
        "a_short_complete": "Quick Skirmish Resolved",
        "a_same_day_start_finish": "Same-Day Duel Settled",
        "a_revival": "Revived by the Way",
        "a_zero_to_hero": "Vagabond to Master",
        "a_five_genre_complete": "Five Arts of War Mastered",
        "a_full_franchise": "Complete Warrior's Dossier",
        "a_batch_complete": "Batch Dojo Cleared",
        "a_paused_to_done": "Returned from the Wilderness",
        "a_completion_spree": "Completion Blade Storm",
        "a_multi_rewatch": "Multi-Pass Blade Study",
        "a_dropped_recovery": "Recovered from Defeat",
        "a_ten_perfect_scores": "Ten Perfect Duel Scores",
        "a_seasonal_clear": "Seasonal Road Cleared",
        "a_complete_genre_span": "All-Terrain Swordsman",
        "a_monthly_completions": "Monthly Victory Reports",
        "a_yearly_completions": "Yearly Campaign Victor",
        "a_rapid_complete": "Lightning Quick Finish",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Dojo Member",
        "a_studio_devotee": "Studio Path Devotee",
        "a_rewatcher": "Blade Technique Revisit",
        "a_triple_rewatch": "Triple Path Rewatch",
        "a_annual_tradition": "Annual Training Day",
        "a_director_fan": "Sensei's Vision Follower",
        "a_voice_actor_fan": "Voice of the Ronin",
        "a_ost_lover": "Way of the Sword Melody",
        "a_source_reader": "Inoue's Original Manuscripts",
        "a_waiting_weekly": "Weekly Duel Signal Wait",
        "a_childhood_revisit": "Return to the Village",
        "a_saga_tracker": "Saga of Musashi Tracker",
        "a_genre_loyalty": "Style Loyalty Badge",
        "a_decade_watcher": "Decade-Long Swordsman",
        "a_adaptation_hunter": "Adaptation Reconnaissance",
        "a_original_anime_fan": "Original Broadcast Warrior",
        "a_long_commitment": "Long-Term Training Commitment",
        "a_perfect_attendance": "Perfect Dojo Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Warrior Catalog",
        "a_franchise_collector": "Warrior Universe Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Mastery Achieved",
        "a_staff_follower": "Sensei Roster Tracker",
        "a_multi_season_fan": "Multi-Season Dojo Veteran",
        "a_format_diversity": "Diverse Combat Formats",
        "a_year_dedication": "Year Dedicated to the Way",
        "a_season_dedication": "Season of Unwavering Training",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Known Styles",
        "a_studio_hopper": "Dojo Transfer Student",
        "a_tag_explorer": "Tag Reconnaissance Mission",
        "a_decade_hopper": "Time-Crossing Swordsman",
        "a_hidden_gem": "Hidden Mountain Dojo",
        "a_popular_taste": "Popular Among Students",
        "a_retro_appreciator": "Old School Dojo Style",
        "a_modern_viewer": "Modern Warrior's Path",
        "a_cross_demographic": "Cross-Style Swordsman",
        "a_underdog_fan": "Underdog Fighter Spirit",
        "a_variety_week": "Week of Varied Styles",
        "a_foreign_cinema": "Foreign School of Thought",
        "a_classic_connoisseur": "Classic Sword Art Connoisseur",
        "a_every_season": "Every Season Training",
        "a_award_winner": "Dojo Honor Medal",
        "a_niche_explorer": "Niche Style Explorer",
        "a_global_anime": "Global Warrior Alliance",
        "a_cult_classic": "Underground Dojo Classic",
        "a_random_pick": "Random Path Assignment",
        "a_new_genre_month": "New Style Monthly",
        "a_seasonal_completionist": "Seasonal Training Cleared",
        "a_unpopular_opinion": "Unpopular Sword Opinion",
        "a_top_rated_viewer": "Top-Rated Warrior Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge Despite Defeat",
        "a_upcoming_watcher": "Upcoming Duel Intel",
        "a_short_series_explorer": "Short Skirmish Explorer",
        "a_long_series_explorer": "Long Road Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Watch in the Mountains",
        "a_early_bird": "Dawn Training Session",
        "a_lunch_break": "Midday Rest Break",
        "a_golden_hour": "Golden Hour on the Road",
        "a_four_am_club": "4 AM Mountain Training",
        "a_witching_hour": "Demon's Hour Vigil",
        "a_new_year_watch": "New Year's Sword Oath",
        "a_midnight_premiere": "Midnight Duel by Moonlight",
        "a_all_hours": "All-Hours Warrior",
        "a_dawn_warrior": "Dawn Warrior Rising",
        "a_afternoon_delight": "Afternoon Sword Practice",
        "a_prime_time": "Prime Time Engagement",
        "a_workday_watcher": "On-Duty Swordsman",
        "a_sunday_marathon": "Sunday Temple Marathon",
        "a_rainy_day": "Rainy Day in the Forest",
        "a_morning_routine": "Morning Formation Training",
        "a_night_shift": "Night Shift Guard Duty",
        "a_twilight_zone": "Twilight Beyond the Pass",
        "a_seasonal_premier": "Season Premiere Duel",
        "a_clock_collector": "Time and the Blade",
        "a_weekend_binge_hours": "Weekend Training Marathon",
        "a_late_night_regular": "Late Night Regular Practice",
        "a_sunrise_watcher": "Sunrise Over the Mountains",
        "a_holiday_watcher": "Festival Day Training",
        "a_every_day_of_week": "Every Day of Discipline",
        "a_monthly_hours": "Monthly Training Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Training Party",
        "a_party_host": "Dojo Commander",
        "a_social_butterfly": "Dojo Socialite",
        "a_group_binge": "Group Training Session",
        "a_party_regular": "Regular Sparring Partner",
        "a_sync_viewer": "Synchronized Training",
        "a_commentator": "Battle Commentator",
        "a_party_marathon": "Marathon Training Run",
        "a_full_house": "Full Dojo Assembled",
        "a_community_pillar": "Pillar of the Dojo",
        "a_watch_party_streak": "Consecutive Training Streak",
        "a_diverse_party": "Diverse Warrior Party",
        "a_late_night_party": "Late Night Training Party",
        "a_party_veteran": "Veteran Squad Leader",
        "a_genre_party": "Cross-Style Formation",
        "a_weekly_party": "Weekly Comrades' Training",
        "a_silent_viewer": "Silent Musashi Observer",
        "a_recommendation_giver": "Sensei's Recommendation",
        "a_party_completionist": "Party Training Completionist",
        "a_social_scorer": "Social Duel Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Milestone",
        "a_fibonacci": "Fibonacci Sword Pattern",
        "a_palindrome_day": "Palindrome Battle Date",
        "a_binary_day": "Binary Signal Day",
        "a_full_moon": "Full Moon Duel Night",
        "a_leap_year": "Leap Year Time Skip",
        "a_time_traveler": "Wanderer's Future Memory",
        "a_genre_clash": "Sword vs. Gun Clash",
        "a_triple_seven": "Triple Lucky Seven",
        "a_thousand_complete": "Thousand Victories Claimed",
        "a_pi_episodes": "Pi Road Calculation",
        "a_synchronicity": "Path Synchronicity",
        "a_world_record": "World Record Duelist",
        "a_nice": "Nice Kill Count",
        "a_power_level": "Musashi Power Level",
        "a_answer_42": "Answer to the Warrior's Question",
        "a_square_number": "Perfect Dojo Formation",
        "a_prime_count": "Prime Number of Duels",
        "a_matching_date": "Matching Battle Date",
        "a_century_episode": "Century Episode Duel",
        "a_double_digits": "Double Digit Victories",
        "a_one_two_three": "One Two Three Steps",
        "a_lucky_seven": "Seven Lucky Swordsmen",
        "a_all_tens": "All Tens Combat Score",
        "a_exact_hundred_eps": "Exact Hundred Duels",
        "a_year_match_count": "Year Match Victory Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Swordsman",
        "a_movie_buff": "Sword Film Warrior",
        "a_ova_hunter": "OVA Lost Swordsman",
        "a_ona_explorer": "ONA Path Explorer",
        "a_special_watcher": "Special Episode Operative",
        "a_short_king": "Short Duel King",
        "a_variety_pack": "All-Format Warrior",
        "a_film_festival": "Warrior Film Festival",
        "a_music_video": "Road Song Collection",
        "a_tv_short": "Quick Duel Clip",
        "a_movie_marathon": "Movie Marathon Warrior",
        "a_double_length": "Double-Length Training",
        "a_anthology": "Swordsman's Anthology",
        "a_mini_series": "Mini Road Collection",
        "a_theatrical": "Theatrical Duel",
        "a_format_master": "Format Master Warrior",
        "a_long_movie": "Feature-Length Road Journey",
        "a_back_catalog": "Back Catalog Dojo Files",
        "a_cm_watcher": "Commercial Break Warrior",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Format Training",
        "a_episodic_master": "Episodic Campaign Master",
        "a_sequel_movie": "Sequel Road Film",
        "a_recap_watcher": "Recap Briefing Warrior",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Training Streak",
        "a_mega_streak": "Mega Warrior Streak",
        "a_weekly_warrior": "Weekly Warrior of the Road",
        "a_monthly_watcher": "Monthly Dojo Duty",
        "a_comeback": "Return from the Wilderness",
        "a_weekend_streak": "Weekend Training Streak",
        "a_no_zero_days": "No Zero Training Days",
        "a_iron_will": "Iron Will of the Warrior",
        "a_habit_formed": "Training Regimen Formed",
        "a_consistent_pace": "Consistent Road Forward",
        "a_year_long": "Year-Long Training Campaign",
        "a_double_streak": "Double Streak Duel",
        "a_streak_recovery": "Recovery from Defeat",
        "a_daily_minimum": "Daily Minimum Training",
        "a_winter_streak": "Winter Isolation Training",
        "a_summer_streak": "Summer Offensive Training",
        "a_morning_streak": "Morning Drill Streak",
        "a_night_streak": "Night Patrol Streak",
        "a_unbreakable": "Unbreakable Will of the Warrior",
        "a_eternal_flame": "Eternal Flame of the Blade",
        "a_completion_streak": "Completion Mission Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Episode Offensive",
        "a_genre_streak": "Style Streak Training",
        "a_studio_streak": "Dojo Loyalty Streak",
        "a_perfect_week": "Perfect Week of Discipline",

        // ── ANIME SCORING ──
        "a_critic": "Dojo Tribunal Judge",
        "a_perfect_ten": "Perfect Duel Rating",
        "a_harsh_critic": "Musashi's Harsh Standards",
        "a_fair_judge": "Takuan's Fair Assessment",
        "a_generous_spirit": "Generous Training Spirit",
        "a_score_all": "Full Dojo Evaluation",
        "a_wide_range": "Wide Range Assessment",
        "a_controversial": "Controversial Sword Decision",
        "a_consistent_scorer": "Consistent Duel Evaluator",
        "a_score_sniper": "Precision Sword Sniper",
        "a_evolving_taste": "Evolving Fighting Style",
        "a_bell_curve": "Bell Curve of Duels",
        "a_picky_watcher": "Selective Sword Master",
        "a_100_rated": "Century of Evaluations",
        "a_500_rated": "Five Hundred Field Reports",
        "a_mediocre_majority": "Middle Ground Swordsman",
        "a_rating_spree": "Rating Barrage Filed",
        "a_score_variance": "Variable Duel Ratings",
        "a_masterpiece_hunter": "Masterpiece Duel Hunter",
        "a_contrarian": "Contrarian Warrior",
        "a_optimist": "Optimist Despite Defeat",
        "a_score_distributor": "Score Distributor Master",
        "a_genre_critic": "Style Tactical Critic",
        "a_mean_above_8": "Elite Combat Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Warrior Vow",
        "a_valentines_weeb": "Valentine's Sword Dedication",
        "a_pi_day": "Pi Day Blade Calculation",
        "a_april_fools": "April Fools Road Prank",
        "a_international_anime_day": "International Warrior Day",
        "a_star_wars_day": "Feudal Empire Day",
        "a_summer_solstice": "Summer Solstice Journey",
        "a_tanabata": "Tanabata Wish for the Path",
        "a_friday_13th": "Friday the 13th Duel",
        "a_halloween_spirit": "Halloween Demon Swordsman",
        "a_thanksgiving_binge": "Harvest Feast Training",
        "a_christmas_special": "Midwinter Festival Duel",
        "a_new_years_eve": "New Year's Eve Final Stand",
        "a_birthday_watch": "Birthday Training Watch",
        "a_holiday_marathon": "Holiday Road Marathon",
        "a_independence_day": "Ronin Independence Day",
        "a_culture_day": "Samurai Culture Day",
        "a_spring_equinox": "Spring Equinox Journey",
        "a_earth_day": "Protect This Land Day",
        "a_labor_day": "Training Labor Day",
        "a_winter_solstice": "Winter Solstice on the Road",
        "a_anime_birthday": "Warrior Anniversary",
        "a_every_holiday": "Every Holiday Warrior",
        "a_consecutive_holidays": "Consecutive Training Festivals",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Sword Power Awakened",
        "a_meta_collector": "Warrior Badge Collector",
        "a_meta_category_starter": "Category Initiation Rite",
        "a_meta_tier_climber": "Rank Promotion Achieved",
        "a_meta_tier_max": "Grandmaster Rank",
        "a_meta_xp_earner": "XP from Blade Practice",
        "a_meta_difficulty_easy": "Easy Training Session",
        "a_meta_difficulty_hard": "Legendary Difficulty: Ganryu Island",
        "a_meta_unlock_spree": "Unlock Spree Blade Storm",
        "a_meta_completionist": "Meta Completionist Master",
        "a_meta_diverse": "Diverse Warrior Portfolio",
        "a_meta_dominator": "Meta Dominator of Duels",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter of the Road",
        "m_chapter_counter": "Chapter Duel Counter",
        "m_chapter_titan": "Chapter Grand Duel",
        "m_reading_hours": "Hours Studying Sword Texts",
        "m_reading_time_lord": "Timeless Reading Memory",
        "m_manga_collector": "Dojo Archive Collector",
        "m_library_legend": "Mountain Library Legend",
        "m_first_complete": "First Manga Journey Done",
        "m_hundred_club": "Hundred-Chapter Club",
        "m_first_day": "First Day of Reading",
        "m_first_rating": "First Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Wisdom",
        "m_volume_collector": "Volume Stockpile Collector",
        "m_year_explorer": "Year of Manuscript Study",
        "m_century_reader": "Century-Chapter Reader",
        "m_five_hundred_ch": "Five Hundred Chapters Deep",
        "m_thousand_ch": "Thousand-Chapter Campaign",
        "m_reading_ten": "Ten Manuscripts at Once",
        "m_ptr_hoarder": "Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Retreat from the Page",
        "m_season_reader": "Seasonal Reading Rotation",
        "m_active_reader": "Active Field Reader",
        "m_five_thousand_ch": "Five Thousand Pages of Ink",
        "m_ten_completed": "Ten Manga Journeys Done",
        "m_fifty_completed": "Fifty Manga Victories",
        "m_five_hundred_completed": "Five Hundred Manga Triumphs",
        "m_mean_score_tracker": "Average Manuscript Rating",
        "m_unique_authors": "Unique Author Encounters",
        "m_all_status": "All Reading Statuses",
        "m_first_favorite": "First Favorite Scroll",
        "m_favorites_collector": "Manga Favorites Collection",
        "m_days_spent_reading": "Days in the Study Hall",

        // ── MANGA BINGE ──
        "m_binge_reader": "Binge Reading Journey",
        "m_marathon_reader": "Road-to-Road Reading Marathon",
        "m_weekend_reader": "Weekend Dojo Reading",
        "m_non_stop_reading": "Non-Stop Page Turning",
        "m_one_more_chapter": "One More Chapter Battle",
        "m_speed_read": "Lightning Quick Read",
        "m_double_story": "Double Manuscript Session",
        "m_triple_read": "Triple Reading Assault",
        "m_five_a_day": "Five Reads Daily",
        "m_chapter_chain": "Chapter Chain Advance",
        "m_volume_binge": "Volume Binge Bombardment",
        "m_power_reader": "Power Reader Warrior",
        "m_half_day_read": "Half-Day Scroll Study",
        "m_full_day_read": "Full-Day Manuscript Study",
        "m_power_weekend": "Power Weekend Reading",
        "m_binge_king": "King of the Reading Hall",
        "m_no_sleep_read": "All-Night Dojo Reading",
        "m_full_series_rush": "Full Series Rush",
        "m_seven_day_challenge": "Seven-Day Wisdom Gathering",
        "m_hundred_day_read": "Hundred-Day Reading Trial",
        "m_volume_rush": "Volume Rush Deployment",
        "m_series_sweep": "Series Sweep Operation",
        "m_genre_binge": "Cross-Genre Reading Advance",
        "m_author_binge": "Author Focused Deep Dive",
        "m_chapter_counter_day": "Daily Chapter Count",
        "m_multi_series_binge": "Multi-Series Reading Front",
        "m_midnight_binge": "Midnight Scroll Session",
        "m_new_year_binge": "New Year's Reading Oath",
        "m_forty_eight_hour": "Forty-Eight Hour Reading Trial",
        "m_oneshot_binge": "Oneshot Blitz Attack",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Sword Manuscript",
        "m_genre_adventure": "Adventure on the Road",
        "m_genre_comedy": "Comedy in the Dojo",
        "m_genre_drama": "Drama of the Ronin's Path",
        "m_genre_fantasy": "Fantasy Beyond the Mountain",
        "m_genre_horror": "Horror of the Dark Blade",
        "m_genre_mystery": "Mystery of the Hidden Master",
        "m_genre_romance": "Romance Under the Stars",
        "m_genre_scifi": "Sci-Fi Sword Engineering",
        "m_genre_sol": "Peaceful Village Life",
        "m_genre_sports": "Training Tournament Sports",
        "m_genre_supernatural": "Supernatural Sword Powers",
        "m_genre_thriller": "Thriller Duel at Dawn",
        "m_genre_psychological": "Psychological Warrior's Mind",
        "m_genre_isekai": "Isekai Swordsman's Journey",
        "m_genre_shounen": "Shounen Warrior's Spirit",
        "m_genre_ecchi": "Hot Springs Scroll Chapter",
        "m_genre_mahou_shoujo": "Way of the Light",
        "m_genre_mecha": "Iron Blade Blueprints",
        "m_genre_music": "Road Songs Collection",
        "m_tag_isekai_new": "New World Beyond the Pass",
        "m_tag_harem": "Squad Bonds Manga",
        "m_tag_bl": "Brothers of the Blade Manga",
        "m_tag_gl": "Sisters of the Path Manga",
        "m_tag_historical": "Feudal Japan History Manga",
        "m_tag_military": "Samurai Operations Manga",
        "m_tag_school": "Dojo Academy Manga",
        "m_tag_martial_arts": "Way of the Warrior Manual",
        "m_tag_vampire": "Demon Swordsman Blood Manga",
        "m_tag_samurai": "Sword Master Manga",
        "m_tag_space": "Beyond the Horizon Manga",
        "m_tag_parody": "Chibi Ronin Manga",
        "m_tag_idol": "Wings of the Road Manga",
        "m_tag_post_apocalyptic": "Post-Battle Wasteland Manga",
        "m_tag_cyberpunk": "Iron Age Tech Manga",
        "m_tag_shoujo": "Otsu's Heart Manga",
        "m_tag_survival": "Survival on the Road Manga",
        "m_tag_cooking": "Road Rations Cookbook",
        "m_tag_medical": "Field Healer Manga",
        "m_tag_villainess": "Rival Warrior Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Manga Campaign Completionist",
        "m_mega_completionist": "Supreme Manga Master",
        "m_completion_rate_50": "Halfway to the Summit",
        "m_completion_rate_75": "Approaching the Final Duel",
        "m_completion_rate_90": "Nearly Invincible Under Heaven",
        "m_no_drop": "No Manuscript Abandoned",
        "m_long_runner_complete": "Long Road Endurance Medal",
        "m_sequel_chain": "Sequel Chain of Duels",
        "m_clean_list": "Clean Reading Record",
        "m_from_ptr": "Orders Received and Read",
        "m_reread_master": "Technique Replay Reread",
        "m_oneshot_complete": "Oneshot Mission Done",
        "m_same_day_start_finish": "Same-Day Road Completed",
        "m_revival": "Revived Through the Way",
        "m_zero_to_hundred": "Student to Sword Master",
        "m_five_genre_complete": "Five Styles Mastered",
        "m_full_collection": "Full Archive Collected",
        "m_batch_complete": "Batch Dojo Clearance",
        "m_paused_to_done": "Back from Wilderness Pause",
        "m_completion_spree": "Completion Blade Spree",
        "m_format_completionist": "Format Completion Badge",
        "m_catch_up": "Caught Up with the Road",
        "m_multi_reread": "Multi-Pass Scroll Study",
        "m_dropped_recovery": "Recovered from Defeat",
        "m_ten_perfect_scores": "Ten Perfect Manuscript Scores",
        "m_complete_genre_span": "All-Genre Warrior",
        "m_monthly_completions": "Monthly Manuscript Victories",
        "m_yearly_completions": "Yearly Reading Campaign",
        "m_rapid_complete": "Rapid Scroll Processing",
        "m_author_complete": "Author's Complete Scrolls",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Dojo Reader",
        "m_mangaka_lover": "Inoue Sensei Devotee",
        "m_rereader": "Blade Technique Rereader",
        "m_triple_reread": "Triple Road Reread",
        "m_annual_reread": "Annual Scroll Remembrance",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Inoue Art Appreciation",
        "m_adaptation_compare": "Manga vs Anime Compare",
        "m_source_material_fan": "Source Material Scout",
        "m_waiting_weekly": "Weekly Chapter Signal Wait",
        "m_classic_reader": "Classic Scroll Reader",
        "m_saga_reader": "Saga of Musashi Reader",
        "m_genre_loyalty": "Style Loyalty Medal",
        "m_decade_reader": "Decade-Long Reader",
        "m_ln_adaptation": "Light Novel Adaptation",
        "m_original_work": "Original Manga Work",
        "m_long_commitment": "Long-Term Study Commitment",
        "m_up_to_date": "Up-to-Date with the Road",
        "m_favorite_mangaka": "Favorite Artist Honored",
        "m_complete_portfolio": "Complete Reading Portfolio",
        "m_franchise_collector": "Warrior Franchise Collector",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Mastery Earned",
        "m_multi_series_author": "Multi-Series Author Fan",
        "m_format_diversity": "Diverse Reading Formats",
        "m_year_dedication": "Year Dedicated to Reading",
        "m_ongoing_follower": "Ongoing Road Follower",
        "m_genre_loyalty_50": "Fifty Style Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Style Territory Scout",
        "m_publisher_hopper": "Publisher School Transfer",
        "m_tag_explorer": "Manga Tag Recon Mission",
        "m_decade_hopper": "Decade-Crossing Reader",
        "m_hidden_gem": "Hidden Mountain Treasure",
        "m_popular_taste": "Popular Among Students",
        "m_retro_reader": "Old Scroll Appreciator",
        "m_modern_reader": "Modern Era Reader",
        "m_cross_demographic": "Cross-Style Scout",
        "m_underdog_fan": "Underdog Warrior Fan",
        "m_variety_week": "Week of Varied Scrolls",
        "m_manhwa_reader": "Manhwa Intelligence Reader",
        "m_manhua_reader": "Manhua Intelligence Reader",
        "m_classic_connoisseur": "Classic Sword Art Reader",
        "m_award_winner": "Medal-Winning Manuscript",
        "m_niche_explorer": "Niche Territory Reader",
        "m_world_manga": "World Manga Intel",
        "m_cult_classic": "Cult Classic Underground",
        "m_random_pick": "Random Scroll Assignment",
        "m_new_genre_month": "New Style Monthly Scroll",
        "m_year_completionist": "Year Reading Completionist",
        "m_unpopular_opinion": "Unpopular Reading Opinion",
        "m_top_rated_reader": "Top-Rated Scroll Source",
        "m_source_variety": "Source Material Variety",
        "m_low_score_brave": "Brave Low-Score Reader",
        "m_short_manga_explorer": "Short Duel Manga Explorer",
        "m_long_manga_explorer": "Long Road Manga Explorer",
        "m_serialization_explorer": "Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Scroll Reader",
        "m_early_bird": "Dawn Training Reader",
        "m_lunch_reader": "Midday Rest Reader",
        "m_commute_reader": "Road Journey Reader",
        "m_four_am_club": "4 AM Temple Reader",
        "m_new_year_read": "New Year's Reading Oath",
        "m_all_hours": "All-Hours Scroll Access",
        "m_prime_time_reader": "Prime Time Manuscript",
        "m_workday_reader": "On-Duty Reader",
        "m_sunday_read": "Sunday Temple Reading",
        "m_morning_routine": "Morning Formation Reading",
        "m_night_shift_reader": "Night Shift Scroll Reader",
        "m_seasonal_premier_read": "New Chapter Intel",
        "m_clock_collector": "Time and the Scroll",
        "m_late_night_horror": "Midnight Demon Blade Read",
        "m_afternoon_reader": "Afternoon Dojo Reading",
        "m_golden_hour_reader": "Golden Hour Scroll",
        "m_dawn_reader": "Dawn Reading Scout",
        "m_twilight_reader": "Twilight Mountain Reading",
        "m_midnight_start": "Midnight Reading Mission",
        "m_weekend_binge_hours": "Weekend Scroll Marathon",
        "m_late_night_regular": "Late Night Regular Reader",
        "m_sunrise_reader": "Sunrise Mountain Reader",
        "m_every_day_of_week": "Every Day of Reading",
        "m_monthly_hours": "Monthly Reading Hours",
        "m_bedtime_reader": "Bedtime Dojo Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Inoue's Ink Brush Art",
        "m_webtoon_reader": "Webtoon Road Intelligence",
        "m_full_color": "Full Color Scroll",
        "m_doujin_reader": "Underground Doujin Reader",
        "m_anthology_reader": "Warrior Anthology Collection",
        "m_adaptation_reader": "Adaptation Study Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Training Shorts",
        "m_oneshot_reader": "Oneshot Mission Reader",
        "m_format_variety": "Format Variety Training",
        "m_light_novel_reader": "Light Novel Scroll Reader",
        "m_novel_reader": "Novel Archive Reader",
        "m_visual_storyteller": "Visual Battle Narrator",
        "m_colored_classic": "Colored Classic Scroll",
        "m_webcomic_fan": "Webcomic Underground Fan",
        "m_manga_to_anime": "Manga to Anime Compare",
        "m_seinen_reader": "Seinen Warrior Reader",
        "m_josei_reader": "Josei Perspective Reader",
        "m_award_winning_art": "Medal-Winning Ink Art",
        "m_debut_work": "Debut Scroll Work",
        "m_vertical_scroll": "Vertical Scroll Intel",
        "m_traditional_format": "Traditional Format Reader",
        "m_cross_media": "Cross-Media Intelligence",
        "m_spinoff_reader": "Spinoff Mission Reader",
        "m_remake_reader": "Remake Reading Assignment",
        "m_collaboration_reader": "Joint Training Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Reading Patrol Streak",
        "m_mega_streak": "Mega Reading Warrior Streak",
        "m_weekly_warrior": "Weekly Warrior Reader",
        "m_monthly_reader": "Monthly Dojo Reader",
        "m_comeback": "Reader's Return from the Wild",
        "m_weekend_streak": "Weekend Reading Streak",
        "m_no_zero_days": "No Zero Reading Days",
        "m_iron_will": "Iron Will Reader",
        "m_habit_formed": "Reading Habit Formed",
        "m_consistent_pace": "Consistent Reading Advance",
        "m_year_long": "Year-Long Reading Journey",
        "m_double_streak": "Double Reading Streak",
        "m_streak_recovery": "Reading Streak Recovery",
        "m_daily_minimum": "Daily Minimum Pages",
        "m_winter_streak": "Winter Isolation Reading",
        "m_summer_streak": "Summer Reading Advance",
        "m_morning_streak": "Morning Reading Formation",
        "m_night_streak": "Night Reading Patrol",
        "m_unbreakable": "Unbreakable Reading Will",
        "m_eternal_flame": "Eternal Flame of Wisdom",
        "m_chapter_a_day": "Chapter a Day Discipline",
        "m_genre_streak": "Style Reading Streak",
        "m_completion_streak": "Completion Reading Chain",
        "m_rating_streak": "Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Streak",
        "m_author_streak": "Author Devotion Streak",
        "m_perfect_week_manga": "Perfect Reading Week",
        "m_diverse_streak": "Diverse Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Dojo Manuscript Critic",
        "m_perfect_ten": "Perfect Scroll Score",
        "m_harsh_critic": "Musashi's Reading Standards",
        "m_fair_judge": "Takuan's Fair Review",
        "m_generous_spirit": "Generous Reader Spirit",
        "m_score_all": "Full Manuscript Assessment",
        "m_wide_range": "Wide Range Scores",
        "m_controversial": "Controversial Reading View",
        "m_consistent_scorer": "Consistent Manuscript Scorer",
        "m_score_sniper": "Precision Score Sniper",
        "m_evolving_taste": "Evolving Sword Reading Taste",
        "m_bell_curve": "Bell Curve of Scrolls",
        "m_picky_reader": "Selective Sword Reader",
        "m_100_rated": "Century of Ratings Filed",
        "m_500_rated": "Five Hundred Rating Reports",
        "m_mediocre_majority": "Middle Ground Reader",
        "m_rating_spree": "Rating Barrage Filed",
        "m_score_variance": "Variable Manuscript Scores",
        "m_binge_rater": "Binge Rating Session",
        "m_reread_rerate": "Reread and Re-Rate",
        "m_masterpiece_hunter": "Masterpiece Scroll Hunter",
        "m_contrarian": "Contrarian Warrior Reader",
        "m_optimist": "Optimist Despite All",
        "m_score_distributor": "Score Distributor Sensei",
        "m_genre_critic": "Style Reading Critic",
        "m_mean_above_8": "Elite Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Reading Vow",
        "m_valentines_read": "Valentine's Road Bond",
        "m_pi_day": "Pi Day Chapter Count",
        "m_april_fools": "April Fools Chibi Ronin",
        "m_international_manga_day": "International Scroll Day",
        "m_free_comic_day": "Free Scroll Day",
        "m_summer_solstice": "Summer Solstice Reading",
        "m_tanabata": "Tanabata Reading Wish",
        "m_friday_13th": "Friday 13th Dark Duel",
        "m_halloween_read": "Halloween Demon Reading",
        "m_thanksgiving_binge": "Harvest Feast Reading",
        "m_christmas_read": "Midwinter Festival Reading",
        "m_new_years_eve": "New Year's Eve Final Read",
        "m_birthday_read": "Birthday Reading Gift",
        "m_holiday_marathon": "Holiday Reading Marathon",
        "m_independence_day": "Ronin Independence Reading",
        "m_culture_day": "Samurai Culture Reading",
        "m_spring_equinox": "Spring Equinox Reading",
        "m_earth_day": "Protect This Land Reading",
        "m_labor_day": "Training Labor Day Read",
        "m_winter_solstice": "Winter Solstice Scroll",
        "m_manga_birthday": "Manga Anniversary Reading",
        "m_every_holiday_reader": "Every Holiday Reader",
        "m_consecutive_holidays": "Consecutive Reading Festivals",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Milestone Scroll",
        "m_fibonacci": "Fibonacci Ink Pattern",
        "m_palindrome_day": "Palindrome Reading Day",
        "m_binary_day": "Binary Signal Reading",
        "m_full_moon_read": "Full Moon Duel Read",
        "m_leap_year_read": "Leap Year Reading Skip",
        "m_triple_seven": "Triple Seven Road Miles",
        "m_thousand_complete": "Thousand Scroll Victories",
        "m_nice": "Nice Chapter Count",
        "m_power_level_chapters": "Musashi-Level Chapters",
        "m_answer_42": "Answer to the Ronin's Quest",
        "m_square_number": "Perfect Formation Chapters",
        "m_prime_count": "Prime Chapter Count",
        "m_matching_date": "Matching Battle Date",
        "m_century_chapter": "Century Chapter Milestone",
        "m_pi_chapters": "Pi Chapter Calculation",
        "m_synchronicity": "Road Reading Synchronicity",
        "m_world_record": "World Record Chapter Count",
        "m_genre_clash": "Sword vs. Scroll Clash",
        "m_time_traveler": "Time-Crossing Reader",
        "m_double_digits": "Double Digit Chapters",
        "m_one_two_three": "One Two Three Scrolls",
        "m_lucky_seven": "Seven Lucky Chapters",
        "m_exact_hundred_ch": "Exact Hundred Chapters",
        "m_year_match_count": "Year Match Chapter Count",
        "m_chapter_match_date": "Chapter Date Alignment",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Warrior",
        "m_manhwa_format": "Manhwa Format Reader",
        "m_manhua_format": "Manhua Format Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Mission",
        "m_doujin_format": "Doujin Format Reader",
        "m_novel_format": "Novel Format Reader",
        "m_format_master_manga": "Format Master Warrior",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Reading Power Unlocked",
        "m_meta_collector": "Reading Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Reading Rank",
        "m_meta_xp_earner": "XP from Reading Wisdom",
        "m_meta_difficulty_easy": "Easy Scroll Exercise",
        "m_meta_difficulty_hard": "Legendary Scroll Challenge",
        "m_meta_unlock_spree": "Reading Unlock Storm",
        "m_meta_completionist": "Meta Reading Completionist",
        "m_meta_diverse": "Diverse Reading Portfolio",
        "m_meta_dominator": "Meta Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060402",
        primary: "#6b4020",
        secondary: "#4a2e12",
        accent: "#a08050",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/vagabond.png",
    particleColor: "#806040",
    backgroundDim: 0.3,
    backgroundBlur: 20,
    particleTypes: {
        ink_drops: { label: "Ink Drops", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        sword_sparks: { label: "Sword Sparks", maxCount: 14, defaultEnabled: true, defaultIntensity: 60 },
        autumn_leaves: { label: "Autumn Leaves", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
        brush_strokes: { label: "Brush Strokes", maxCount: 6, defaultEnabled: true, defaultIntensity: 40 },
    },
    milestoneNames: {
        1:   "Wandering Ronin",
        5:   "Duel Seeker",
        15:  "Budding Swordsman",
        30:  "Battle Scarred",
        45:  "Musashi's Path",
        60:  "Invincible Under Heaven",
        80:  "Way of the Sword",
        100: "Beyond Victory and Defeat",
    },
}
