import { AnimeThemeConfig } from "./types"
import { GiMusicalNotes, GiBookshelf, GiRose, GiHeartKey, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiCherish } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const whisperOfTheHeartTheme: AnimeThemeConfig = {
    id: "whisper-of-the-heart",
    displayName: "Whisper of the Heart",
    description: "Bookworm Shizuku keeps finding books that were checked out by someone named Seiji Amasawa — then they meet, and discover they share the same dreams of becoming creators.",
    fontFamily: "'Merriweather', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;1,300&display=swap",
    cssVars: {
        "--color-brand-200": "240 210 150",
        "--color-brand-300": "228 184 100",
        "--color-brand-400": "212 158 55",
        "--color-brand-500": "192 130 15",
        "--color-brand-600": "158 104 8",
        "--color-brand-700": "122 78 4",
        "--color-brand-800": "86 54 2",
        "--color-brand-900": "52 32 1",
        "--color-brand-950": "30 18 0",
        "--brand": "192 130 15",
        "--background": "#060500",
        "--paper": "#0e0c02",
        "--color-gray-950": "6 5 0",
        "--color-gray-900": "14 12 2",
        "--color-gray-800": "26 22 6",
        "--color-gray-700": "44 38 12",
        "--color-gray-600": "68 60 24",
        "--color-gray-500": "105 95 48",
        "--color-gray-400": "148 138 90",
        "--color-gray-300": "186 178 132",
        "--color-gray-200": "214 208 170",
        "--color-gray-100": "232 228 202",
        "--color-gray-50": "246 244 232",
    },
    sidebarOverrides: {
        "home": { icon: GiBookshelf, label: "Cozy Library" },
        "schedule": { icon: GiAlarmClock, label: "Reading Schedule" },
        "manga": { icon: LuBookOpen, label: "Shizuku's Books" },
        "lists": { icon: GiHeartKey, label: "Reading List" },
        "discover": { icon: GiBullseye, label: "Bookshop Explore" },
        "torrent-list": { icon: GiMusicalNotes, label: "Music Cache" },
        "debrid": { icon: GiCherish, label: "Antique Store" },
        "unmatched": { icon: GiRose, label: "Unread Books" },
        "enmasse": { icon: GiResize, label: "Book Club" },
        "scan-summaries": { icon: TbReportSearch, label: "Reading Notes" },
        "auto-downloader": { icon: LuRss, label: "Library Feed" },
        "community": { icon: GiBookshelf, label: "Reading Club" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Library Bells" },
        "achievements": { icon: GiTrophy, label: "Reading Badges" },
        "milestones": { icon: LuFlag, label: "Dream Goals" },
        "theme-manager": { icon: GiPalette, label: "Warm Colors" },
        "extensions": { icon: BiExtension, label: "Library Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Library Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Reading Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Checkout",
        "a_first_complete": "Story Written",
        "a_hundred_club": "Hundred Books",
        "a_time_lord": "Bookworm Elder",
        "a_anime_collector": "Book Collection",
        "a_library_legend": "Library Legend",
        "a_binge_king": "Reading Marathon",
        "a_no_sleep": "All-Night Writing",
        "a_marathon_runner": "Writing Marathon",
        "a_speed_run": "Speed Reader",
        "a_completionist": "Dream Fulfilled",
        "a_mega_completionist": "Miyazaki Expert",
        "a_loyal_fan": "Shizuku's Dream",
        "a_rewatcher": "Return to Library",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Story Action",
        "a_genre_adventure": "Writing Journey",
        "a_genre_comedy": "Library Moments",
        "a_genre_drama": "Creative Struggle",
        "a_genre_fantasy": "Baron's World",
        "a_genre_horror": "Writer's Block",
        "a_genre_romance": "Seiji's Dream",
        "a_genre_scifi": "Future Dreams",
        "a_genre_supernatural": "Moonlight Sonata",
        "a_genre_psychological": "Inner Voice",
        "a_genre_mecha": "None Needed",
        "a_critic": "Literary Critic",
        "a_perfect_ten": "Perfect Story",
        "a_harsh_critic": "Strict Review",
        "a_daily_streak": "Daily Writing",
        "a_mega_streak": "Unbroken Story",
        "a_year_long": "Year of Writing",
        "a_iron_will": "Writer's Will",
        "a_hidden_gem": "Hidden Book",
        "a_cult_classic": "Miyazaki Classic",
        "a_classic_connoisseur": "95 Classic Fan",
        "a_new_years_resolution": "New Year Story",
        "a_christmas_special": "Winter Writing",
        "a_meta_tier_max": "True Storyteller",
        "a_meta_completionist": "Complete Collection",
        "a_sequel_chain": "The Cat Returns",
        "a_zero_to_hero": "Dreamer to Writer",
        "a_night_owl": "Moonlit Writing",
        "a_early_bird": "Dawn Writing",
        "m_first_chapter": "First Page",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Reading Binge",
        "m_completionist": "Full Story",
        "m_mega_completionist": "Ghibli Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Book Revisit",
        "m_genre_action": "Story Action",
        "m_genre_adventure": "Journey Chapter",
        "m_genre_romance": "Heart Chapter",
        "m_genre_fantasy": "Dream Chapter",
        "m_genre_horror": "Block Chapter",
        "m_genre_drama": "Growth Chapter",
        "m_genre_scifi": "Future Chapter",
        "m_genre_supernatural": "Magic Chapter",
        "m_genre_psychological": "Inner Chapter",
        "m_critic": "Literary Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Reading",
        "m_year_long": "Year Reading",
        "m_iron_will": "Writer Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Ghibli",
        "m_mangaka_lover": "Author Fan",
        "m_source_material_fan": "Novel First",
        "m_meta_tier_max": "Story Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Warm Art",
        "m_manga_to_anime": "Novel Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060500",
        primary: "#c0820f",
        secondary: "#7a4e04",
        accent: "#9080c0",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/whisper-of-the-heart.jpg",
    particleColor: "#d8b060",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        dust_motes: { label: "Dust Motes", maxCount: 15, defaultEnabled: true, defaultIntensity: 45 },
        notes: { label: "Musical Notes", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
    },
    milestoneNames: {
        1: "Bookworm",
        5: "Shizuku",
        15: "Aspiring Writer",
        30: "Library Regular",
        50: "Creative Soul",
        75: "Storyteller",
        100: "True Author",
    },
}
