import { AnimeThemeConfig } from "./types"
import { GiCycle, GiWindSlap, GiRunningShoe, GiPunch, GiTrophy, GiPalette, GiSettingsKnobs, GiAlarmClock, GiBullseye, GiResize, GiFlowerEmblem, GiHelmet, GiHeartKey, GiRoad } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const windBreakerTheme: AnimeThemeConfig = {
    id: "wind-breaker",
    displayName: "Wind Breaker",
    description: "Loner Haruka Sakura transfers to Furin High — a school of delinquents who secretly protect their town from outside threats, clashing with gangs and building bonds through street brawls and unbreakable loyalty.",
    fontFamily: "'Bebas Neue', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
    cssVars: {
        "--color-brand-200": "255 188 148",
        "--color-brand-300": "252 148 80",
        "--color-brand-400": "242 105 28",
        "--color-brand-500": "215 72 0",
        "--color-brand-600": "172 48 0",
        "--color-brand-700": "128 28 0",
        "--color-brand-800": "86 14 0",
        "--color-brand-900": "46 6 0",
        "--color-brand-950": "20 2 0",
        "--brand": "215 72 0",
        "--background": "#060100",
        "--paper": "#110300",
        "--color-gray-950": "6 1 0",
        "--color-gray-900": "12 3 0",
        "--color-gray-800": "24 7 2",
        "--color-gray-700": "40 14 5",
        "--color-gray-600": "65 26 10",
        "--color-gray-500": "104 50 22",
        "--color-gray-400": "150 88 48",
        "--color-gray-300": "195 130 82",
        "--color-gray-200": "228 172 122",
        "--color-gray-100": "246 208 165",
        "--color-gray-50": "255 238 218",
    },
    sidebarOverrides: {
        "home": { icon: GiWindSlap, label: "Furin HQ" },
        "schedule": { icon: GiAlarmClock, label: "Crew Schedule" },
        "manga": { icon: LuBookOpen, label: "Street Code" },
        "lists": { icon: GiFlowerEmblem, label: "Crew Registry" },
        "discover": { icon: GiBullseye, label: "New Turf" },
        "torrent-list": { icon: GiHelmet, label: "Gear Cache" },
        "debrid": { icon: GiRoad, label: "Street Vault" },
        "unmatched": { icon: GiHeartKey, label: "Lost Members" },
        "enmasse": { icon: GiResize, label: "Crew Op" },
        "scan-summaries": { icon: TbReportSearch, label: "Battle Logs" },
        "auto-downloader": { icon: LuRss, label: "Street Intel" },
        "community": { icon: GiPunch, label: "Furin Circle" },
        "achievements": { icon: GiTrophy, label: "Street Trophies" },
        "milestones": { icon: LuFlag, label: "Crew Goals" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Street Alerts" },
        "theme-manager": { icon: GiPalette, label: "Street Palette" },
        "extensions": { icon: BiExtension, label: "Crew Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Crew Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Sakura's Config" },
    },
    achievementNames: {
        "a_first_episode": "First Brawl",
        "a_first_complete": "Fight Won",
        "a_hundred_club": "Hundred Fights",
        "a_time_lord": "Street Veteran",
        "a_anime_collector": "Street Archive",
        "a_library_legend": "Crew Library",
        "a_binge_king": "Street Marathon",
        "a_no_sleep": "All-Night Watch",
        "a_marathon_runner": "Sakura's Run",
        "a_speed_run": "Quick Fight",
        "a_completionist": "Full Crew",
        "a_mega_completionist": "Street Master",
        "a_loyal_fan": "Loyal Crew",
        "a_rewatcher": "Replay Brawl",
        "a_decade_watcher": "Decade Street",
        "a_genre_action": "Street Fight",
        "a_genre_adventure": "Crew Journey",
        "a_genre_comedy": "Street Comedy",
        "a_genre_drama": "Crew Drama",
        "a_genre_fantasy": "None Here",
        "a_genre_horror": "None Here",
        "a_genre_romance": "None Here",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Sakura's Mind",
        "a_genre_mecha": "None Here",
        "a_critic": "Street Critic",
        "a_perfect_ten": "Perfect Fight",
        "a_harsh_critic": "Furin Standard",
        "a_daily_streak": "Daily Workout",
        "a_mega_streak": "Endless Grind",
        "a_year_long": "Year on Streets",
        "a_iron_will": "Street Spirit",
        "a_hidden_gem": "Hidden Crew",
        "a_cult_classic": "Street Classic",
        "a_classic_connoisseur": "2024 Fan",
        "a_new_years_resolution": "New Year Fight",
        "a_christmas_special": "Winter Brawl",
        "a_meta_tier_max": "True Furin",
        "a_meta_completionist": "All Fights",
        "a_sequel_chain": "Sakura's Chain",
        "a_zero_to_hero": "Loner to Leader",
        "a_night_owl": "Night Patrol",
        "a_early_bird": "Dawn Training",
        "m_first_chapter": "First Punch",
        "m_first_complete": "Arc Complete",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Crew Binge",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Furin Expert",
        "m_loyal_reader": "Loyal Reader",
        "m_rereader": "Re-fight",
        "m_genre_action": "Action Chapter",
        "m_genre_adventure": "Street Chapter",
        "m_genre_romance": "None Here",
        "m_genre_fantasy": "None Here",
        "m_genre_horror": "None Here",
        "m_genre_drama": "Crew Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Inner Chapter",
        "m_critic": "Crew Review",
        "m_perfect_ten": "Perfect Chapter",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Street Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Iron Fist",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Classic Chapter",
        "m_mangaka_lover": "Street Manga Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Furin Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Street Art",
        "m_manga_to_anime": "Adapted Fight",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#060100",
        primary: "#d74800",
        secondary: "#ac3000",
        accent: "#808090",
    },
    particleColor: "#f06820",
    backgroundDim: 0.28,
    backgroundBlur: 12,
    particleTypes: {
        wind_streaks: { label: "Wind Streaks", maxCount: 16, defaultEnabled: true, defaultIntensity: 55 },
        ember_wisps: { label: "Street Embers", maxCount: 10, defaultEnabled: false, defaultIntensity: 35 },
    },
    milestoneNames: {
        1: "Lone Wolf",
        5: "Furin Newbie",
        15: "Street Brawler",
        30: "Crew Member",
        50: "Block Captain",
        75: "Furin Elite",
        100: "Wind Breaker",
    },
}
