import { AnimeThemeConfig } from "./types"
import { GiWolfHowl, GiSnowflake1, GiMoonBats, GiCrystalBall, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiMountainRoad } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const wolfRainTheme: AnimeThemeConfig = {
    id: "wolf-rain",
    displayName: "Wolf's Rain",
    description: "In a world where wolves are thought to be extinct, a pack of wolves disguised as humans searches for Paradise — a legendary land promised at the end of the world.",
    fontFamily: "'Crimson Text', serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;1,400&display=swap",
    cssVars: {
        "--color-brand-200": "190 200 230",
        "--color-brand-300": "148 162 210",
        "--color-brand-400": "108 125 188",
        "--color-brand-500": "72 90 165",
        "--color-brand-600": "50 65 136",
        "--color-brand-700": "32 44 106",
        "--color-brand-800": "18 26 76",
        "--color-brand-900": "8 14 46",
        "--color-brand-950": "4 7 26",
        "--brand": "72 90 165",
        "--background": "#020204",
        "--paper": "#060710",
        "--color-gray-950": "2 2 4",
        "--color-gray-900": "6 7 12",
        "--color-gray-800": "12 14 24",
        "--color-gray-700": "22 24 40",
        "--color-gray-600": "36 38 64",
        "--color-gray-500": "58 62 100",
        "--color-gray-400": "90 96 140",
        "--color-gray-300": "128 134 172",
        "--color-gray-200": "164 170 198",
        "--color-gray-100": "198 202 220",
        "--color-gray-50": "230 232 240",
    },
    sidebarOverrides: {
        "home": { icon: GiWolfHowl, label: "Pack Den" },
        "schedule": { icon: GiAlarmClock, label: "Migration" },
        "manga": { icon: LuBookOpen, label: "Pack Lore" },
        "lists": { icon: GiMoonBats, label: "Pack Registry" },
        "discover": { icon: GiBullseye, label: "Paradise Hunt" },
        "torrent-list": { icon: GiSnowflake1, label: "Trail Cache" },
        "debrid": { icon: GiCrystalBall, label: "Moon Flower" },
        "unmatched": { icon: GiMountainRoad, label: "Lost Pack" },
        "enmasse": { icon: GiResize, label: "Pack Deploy" },
        "scan-summaries": { icon: TbReportSearch, label: "Pack Reports" },
        "auto-downloader": { icon: LuRss, label: "Wolf Howl" },
        "community": { icon: GiWolfHowl, label: "Wolf Pack" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Howl Alerts" },
        "achievements": { icon: GiTrophy, label: "Wolf Totems" },
        "milestones": { icon: LuFlag, label: "Wolf Goals" },
        "theme-manager": { icon: GiPalette, label: "Moon Colors" },
        "extensions": { icon: BiExtension, label: "Pack Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Pack Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Wolf Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Howl",
        "a_first_complete": "Paradise Found",
        "a_hundred_club": "Hundred Miles",
        "a_time_lord": "Pack Elder",
        "a_anime_collector": "Flower Cache",
        "a_library_legend": "Wolf Lore",
        "a_binge_king": "Pack Marathon",
        "a_no_sleep": "All-Night Journey",
        "a_marathon_runner": "Long Migration",
        "a_speed_run": "Wolf Sprint",
        "a_completionist": "Paradise Reached",
        "a_mega_completionist": "BONES Expert",
        "a_loyal_fan": "Kiba's Pack",
        "a_rewatcher": "Paradise Revisit",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "Pack Battle",
        "a_genre_adventure": "Paradise Journey",
        "a_genre_comedy": "Hige's Moments",
        "a_genre_drama": "Pack Loss",
        "a_genre_fantasy": "Wolf World",
        "a_genre_horror": "Jagara's Terror",
        "a_genre_romance": "Cheza's Bloom",
        "a_genre_scifi": "Lunar Flowers",
        "a_genre_supernatural": "Wolf Disguise",
        "a_genre_psychological": "Kiba's Obsession",
        "a_genre_mecha": "None Here",
        "a_critic": "Pack Judge",
        "a_perfect_ten": "Moon Flower",
        "a_harsh_critic": "Strict Review",
        "a_daily_streak": "Daily Hunt",
        "a_mega_streak": "Endless Migration",
        "a_year_long": "Year of Howling",
        "a_iron_will": "Wolf's Will",
        "a_hidden_gem": "Hidden Path",
        "a_cult_classic": "Yoko Kanno Classic",
        "a_classic_connoisseur": "2003 Fan",
        "a_new_years_resolution": "New Year Hunt",
        "a_christmas_special": "Winter Migration",
        "a_meta_tier_max": "Paradise Gate",
        "a_meta_completionist": "Complete Pack",
        "a_sequel_chain": "OVA Complete",
        "a_zero_to_hero": "Stray to Pack",
        "a_night_owl": "Moonlit Hunt",
        "a_early_bird": "Dawn Howl",
        "m_first_chapter": "First Trail",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Miles",
        "m_binge_king": "Pack Marathon",
        "m_completionist": "Full Journey",
        "m_mega_completionist": "Wolf Expert",
        "m_loyal_reader": "Wolf Reader",
        "m_rereader": "Trail Revisit",
        "m_genre_action": "Combat Chapter",
        "m_genre_adventure": "Migration Chapter",
        "m_genre_romance": "Flower Chapter",
        "m_genre_fantasy": "Wolf Chapter",
        "m_genre_horror": "Dark Chapter",
        "m_genre_drama": "Pack Loss",
        "m_genre_scifi": "Moon Chapter",
        "m_genre_supernatural": "Spirit Chapter",
        "m_genre_psychological": "Obsession",
        "m_critic": "Wolf Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Unbroken Hunt",
        "m_year_long": "Year Reading",
        "m_iron_will": "Wolf Resolve",
        "m_hidden_gem": "Hidden Volume",
        "m_cult_classic": "Classic Manga",
        "m_mangaka_lover": "Author Fan",
        "m_source_material_fan": "Manga Version",
        "m_meta_tier_max": "Paradise Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Moon Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#020204",
        primary: "#485aa5",
        secondary: "#324188",
        accent: "#c8e8f8",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/wolf-rain.jpg",
    particleColor: "#8090d8",
    backgroundDim: 0.4,
    backgroundBlur: 22,
    particleTypes: {
        snowflakes: { label: "Snowflakes", maxCount: 25, defaultEnabled: true, defaultIntensity: 60 },
        moon_flowers: { label: "Moon Flowers", maxCount: 10, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
        1: "Lone Wolf",
        5: "Kiba",
        15: "Pack Member",
        30: "Trail Follower",
        50: "Cheza Seeker",
        75: "Pack Leader",
        100: "Paradise",
    },
}
