import { AnimeThemeConfig } from "./types"
import { GiComputerFan, GiGamepad, GiHeartKey, GiCoffeeCup, GiSettingsKnobs, GiPalette, GiTrophy, GiAlarmClock, GiBullseye, GiResize, GiBookCover } from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen, LuFlag } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const wotakoiTheme: AnimeThemeConfig = {
    id: "wotakoi",
    displayName: "Wotakoi: Love is Hard for Otaku",
    description: "Office worker Narumi Momose is a closeted fujoshi who reunites with childhood friend and hardcore gamer Hirotaka Nifuji — they decide to date despite both being otaku, leading to an endearingly awkward workplace romance.",
    fontFamily: "'Kosugi Maru', sans-serif",
    fontHref: "https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap",
    cssVars: {
        "--color-brand-200": "210 218 232",
        "--color-brand-300": "178 192 215",
        "--color-brand-400": "142 162 195",
        "--color-brand-500": "105 130 170",
        "--color-brand-600": "75 100 142",
        "--color-brand-700": "48 70 110",
        "--color-brand-800": "26 42 76",
        "--color-brand-900": "12 20 40",
        "--color-brand-950": "4 7 18",
        "--brand": "105 130 170",
        "--background": "#030405",
        "--paper": "#070a10",
        "--color-gray-950": "3 4 5",
        "--color-gray-900": "8 9 14",
        "--color-gray-800": "14 16 24",
        "--color-gray-700": "24 28 40",
        "--color-gray-600": "40 46 64",
        "--color-gray-500": "65 75 98",
        "--color-gray-400": "98 110 140",
        "--color-gray-300": "140 155 180",
        "--color-gray-200": "178 190 210",
        "--color-gray-100": "210 218 232",
        "--color-gray-50": "235 240 248",
    },
    sidebarOverrides: {
        "home": { icon: GiComputerFan, label: "Office Floor" },
        "schedule": { icon: GiAlarmClock, label: "Work Schedule" },
        "manga": { icon: LuBookOpen, label: "Doujin Shelf" },
        "lists": { icon: GiGamepad, label: "Game List" },
        "discover": { icon: GiBullseye, label: "New Events" },
        "torrent-list": { icon: GiBookCover, label: "Manga Cache" },
        "debrid": { icon: GiCoffeeCup, label: "Otaku Shop" },
        "unmatched": { icon: GiHeartKey, label: "Lost Episodes" },
        "enmasse": { icon: GiResize, label: "Comiket Events" },
        "scan-summaries": { icon: TbReportSearch, label: "Office Reports" },
        "auto-downloader": { icon: LuRss, label: "Otaku Feed" },
        "community": { icon: GiComputerFan, label: "Otaku Circle" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Event Alerts" },
        "achievements": { icon: GiTrophy, label: "Otaku Trophies" },
        "milestones": { icon: LuFlag, label: "Otaku Goals" },
        "theme-manager": { icon: GiPalette, label: "Office Colors" },
        "extensions": { icon: BiExtension, label: "Otaku Mods" },
        "sync": { icon: IoCloudOfflineOutline, label: "Otaku Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Narumi Settings" },
    },
    achievementNames: {
        "a_first_episode": "First Date",
        "a_first_complete": "Couple Official",
        "a_hundred_club": "Hundred Episodes",
        "a_time_lord": "Office Veteran",
        "a_anime_collector": "Otaku Collection",
        "a_library_legend": "Doujin Archives",
        "a_binge_king": "Otaku Marathon",
        "a_no_sleep": "Comiket All-Night",
        "a_marathon_runner": "Narumi's Run",
        "a_speed_run": "Hirotaka Speed",
        "a_completionist": "All Episodes",
        "a_mega_completionist": "Fujita Master",
        "a_loyal_fan": "Hirotaka's Partner",
        "a_rewatcher": "Office Return",
        "a_decade_watcher": "Decade Fan",
        "a_genre_action": "None Here",
        "a_genre_adventure": "Comiket Journey",
        "a_genre_comedy": "Closeted Otaku",
        "a_genre_drama": "Couples Talk",
        "a_genre_fantasy": "Otaku Dream",
        "a_genre_horror": "Social Exposure",
        "a_genre_romance": "Narumi Hirotaka",
        "a_genre_scifi": "None Here",
        "a_genre_supernatural": "None Here",
        "a_genre_psychological": "Otaku Feelings",
        "a_genre_mecha": "None Here",
        "a_critic": "Otaku Critic",
        "a_perfect_ten": "Perfect Couple",
        "a_harsh_critic": "Kabakura Standard",
        "a_daily_streak": "Daily Gaming",
        "a_mega_streak": "Endless Otaku",
        "a_year_long": "Year Together",
        "a_iron_will": "Narumi's Will",
        "a_hidden_gem": "Hidden Episode",
        "a_cult_classic": "Otaku Classic",
        "a_classic_connoisseur": "2014 Fan",
        "a_new_years_resolution": "New Year Together",
        "a_christmas_special": "Winter Date",
        "a_meta_tier_max": "Otaku Legend",
        "a_meta_completionist": "All Moments",
        "a_sequel_chain": "Manga Continues",
        "a_zero_to_hero": "Closeted to Open",
        "a_night_owl": "Night Gaming",
        "a_early_bird": "Morning Commute",
        "m_first_chapter": "First Chapter",
        "m_first_complete": "Volume Done",
        "m_hundred_club": "Hundred Chapters",
        "m_binge_king": "Otaku Marathon",
        "m_completionist": "Full Manga",
        "m_mega_completionist": "Wotakoi Expert",
        "m_loyal_reader": "Devoted Reader",
        "m_rereader": "Office Return",
        "m_genre_action": "None Here",
        "m_genre_adventure": "Comiket Chapter",
        "m_genre_romance": "Couple Chapter",
        "m_genre_fantasy": "Otaku Chapter",
        "m_genre_horror": "Exposed Chapter",
        "m_genre_drama": "Heart Chapter",
        "m_genre_scifi": "None Here",
        "m_genre_supernatural": "None Here",
        "m_genre_psychological": "Feelings Depth",
        "m_critic": "Otaku Critic",
        "m_perfect_ten": "Perfect Volume",
        "m_daily_streak": "Daily Read",
        "m_mega_streak": "Otaku Streak",
        "m_year_long": "Year Reading",
        "m_iron_will": "Otaku Resolve",
        "m_hidden_gem": "Hidden Chapter",
        "m_cult_classic": "Fujita Classic",
        "m_mangaka_lover": "Fujita Fan",
        "m_source_material_fan": "Manga First",
        "m_meta_tier_max": "Wotakoi Complete",
        "m_meta_completionist": "Full Library",
        "m_art_appreciator": "Fujita Art",
        "m_manga_to_anime": "Manga Adapted",
        "m_night_owl": "Night Reader",
        "m_early_bird": "Dawn Reader",
    },
    musicUrl: "",
    previewColors: {
        bg: "#030405",
        primary: "#6982aa",
        secondary: "#4b648e",
        accent: "#e08888",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "/themes/wotakoi.jpg",
    particleColor: "#8090b8",
    backgroundDim: 0.28,
    backgroundBlur: 14,
    particleTypes: {
        pixel_hearts: { label: "Pixel Hearts", maxCount: 15, defaultEnabled: true, defaultIntensity: 50 },
        game_bits: { label: "Game Bits", maxCount: 10, defaultEnabled: true, defaultIntensity: 38 },
    },
    milestoneNames: {
        1: "Closeted Otaku",
        5: "Narumi Momose",
        15: "Official Couple",
        30: "Comiket Regular",
        50: "Otaku Open",
        75: "Partner in Crime",
        100: "Otaku Legend",
    },
}
