import { AnimeThemeConfig } from "./types"
import {
    GiCastle,
    GiCrossedSwords,
    GiLightningBranches,
    GiChainedHeart,
    GiCompass,
    GiEagleEmblem,
    GiTrophy,
    GiPalette,
    GiAlarmClock,
    GiResize,
    GiSettingsKnobs,
    GiAnvilImpact,
    GiSpellBook,
    GiFlame,
} from "react-icons/gi"
import { FiSearch } from "react-icons/fi"
import { LuBell, LuRss, LuBookOpen } from "react-icons/lu"
import { IoCloudOfflineOutline } from "react-icons/io5"
import { BiExtension } from "react-icons/bi"
import { TbReportSearch } from "react-icons/tb"

export const yuyuHakushoTheme: AnimeThemeConfig = {
    id: "yuyu-hakusho",
    displayName: "Yu Yu Hakusho",
    description: "Spirit Gun! Underworld aesthetics with spirit detective swagger, Dark Tournament fury, and demon world power.",
    fontFamily: "'Fredoka One', cursive",
    fontHref: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
    cssVars: {
        "--color-brand-200": "165 240 195",
        "--color-brand-300": "110 225 158",
        "--color-brand-400": "55 200 115",
        "--color-brand-500": "0 170 68",
        "--color-brand-600": "0 140 55",
        "--color-brand-700": "0 108 42",
        "--color-brand-800": "0 78 30",
        "--color-brand-900": "0 48 18",
        "--color-brand-950": "0 25 10",
        "--brand": "0 170 68",
        "--background": "#040807",
        "--paper": "#091410",
        "--color-gray-950": "4 8 7",
        "--color-gray-900": "9 20 14",
        "--color-gray-800": "18 34 24",
        "--color-gray-700": "30 54 38",
        "--color-gray-600": "48 82 58",
        "--color-gray-500": "72 118 84",
        "--color-gray-400": "108 158 120",
        "--color-gray-300": "148 192 158",
        "--color-gray-200": "185 218 192",
        "--color-gray-100": "218 238 222",
        "--color-gray-50": "240 250 242",
    },
    sidebarOverrides: {
        "home": { icon: GiCastle, label: "Urameshi HQ" },
        "schedule": { icon: GiAlarmClock, label: "Spirit World Timer" },
        "manga": { icon: LuBookOpen, label: "Spirit Detective Files" },
        "lists": { icon: GiCrossedSwords, label: "Team Roster" },
        "discover": { icon: GiCompass, label: "Demon World Access" },
        "torrent-list": { icon: GiAnvilImpact, label: "Spirit Energy Cache" },
        "debrid": { icon: GiLightningBranches, label: "Spirit Gun Lines" },
        "unmatched": { icon: GiChainedHeart, label: "Lost Souls" },
        "enmasse": { icon: GiResize, label: "Spirit World Deployment" },
        "scan-summaries": { icon: TbReportSearch, label: "Spirit World Reports" },
        "auto-downloader": { icon: LuRss, label: "Psychic Signals" },
        "community": { icon: GiEagleEmblem, label: "Spirit Detective Agency" },
        "search": { icon: FiSearch, label: "Search" },
        "notifications": { icon: LuBell, label: "Botan's Signals" },
        "achievements": { icon: GiTrophy, label: "Tournament Trophies" },
        "theme-manager": { icon: GiPalette, label: "Spirit Palette" },
        "extensions": { icon: BiExtension, label: "Psychic Extensions" },
        "sync": { icon: IoCloudOfflineOutline, label: "Spirit World Sync" },
        "settings": { icon: GiSettingsKnobs, label: "Koenma's HQ" },
    },
    achievementNames: {
        // ── ANIME MILESTONES ──
        "a_first_episode": "First Spirit Detective Case",
        "a_episode_counter": "Spirit Gun Fire Count",
        "a_episode_titan": "S-Class Demon Engagement",
        "a_hours_invested": "Hours in Spirit World",
        "a_time_lord": "Demon World Memories",
        "a_anime_collector": "Spirit World Arsenal Collector",
        "a_library_legend": "Genkai's Library Legend",
        "a_first_complete": "First Spirit Journey Complete",
        "a_hundred_club": "Century of Demon Defeats",
        "a_first_day": "Spirit Detective Appointment Day",
        "a_first_rating": "Spirit Evaluation",
        "a_ten_thousand_min": "Ten Thousand Minutes in Spirit World",
        "a_season_veteran": "Veteran Spirit Detective",
        "a_year_explorer": "Year of Spirit Exploration",
        "a_century_watcher": "Hundred-Episode Spirit Duty",
        "a_five_hundred_eps": "Five Hundred Spirit Gun Shots",
        "a_thousand_eps": "Thousand Demon Encounters",
        "a_watching_ten": "Ten Spirit Fronts Simultaneously",
        "a_ptw_hoarder": "Spirit Energy Backlog Hoarder",
        "a_dropped_honesty": "Strategic Spirit Retreat",
        "a_five_thousand_eps": "Five Thousand Spirit Missions",
        "a_ten_completed": "Ten Spirit Arcs Complete",
        "a_fifty_completed": "Fifty Detective Missions",
        "a_five_hundred_completed": "Five Hundred Spirit Victories",
        "a_mean_score_tracker": "Average Spirit Power Rating",
        "a_unique_studios": "Allied Spirit World Factions",
        "a_days_spent_watching": "Days Defending Spirit World",
        "a_all_status": "All Spirit Detective Statuses",
        "a_first_favorite": "First Team Urameshi Bond",
        "a_favorites_collector": "Bonds of Team Urameshi",

        // ── ANIME BINGE ──
        "a_binge_watcher": "Non-Stop Spirit Gun Release",
        "a_marathon_runner": "Spirit World-to-Demon Marathon",
        "a_weekend_warrior": "Weekend Warrior Spirit Detective",
        "a_non_stop": "Relentless Spirit Energy Advance",
        "a_one_more_episode": "One More Spirit Battle",
        "a_speed_run": "Spirit Gun Blitz",
        "a_double_feature": "Double Spirit Strike",
        "a_triple_threat": "Triple Demon Takedown",
        "a_five_a_day": "Five Spirit Battles a Day",
        "a_back_to_back": "Back-to-Back Spirit Engagements",
        "a_seasonal_binge": "Full Dark Tournament Arc",
        "a_cour_crusher": "Demon City Crusher",
        "a_half_day_watch": "Half-Day Spirit Shift",
        "a_full_day_watch": "Full Day in Spirit World",
        "a_power_weekend": "Power Weekend Spirit Offensive",
        "a_binge_king": "Commander of Spirit Binge Ops",
        "a_no_sleep": "All-Night Vigil at Genkai's Temple",
        "a_entire_season": "Rapid Dark Tournament Clear",
        "a_seven_day_challenge": "Seven-Day Spirit Reclamation",
        "a_hundred_day_binge": "Hundred-Day Demon Siege",
        "a_genre_binge": "Cross-Spirit Training",
        "a_studio_binge": "Allied Spirit Binge",
        "a_season_sweep": "Season Sweep Spirit Operation",
        "a_forty_eight_hour": "Forty-Eight Hour Spirit Standoff",
        "a_ep_counter_day": "Daily Spirit Gun Count",
        "a_multi_series_binge": "Multi-Front Spirit Campaign",
        "a_midnight_binge": "Midnight Spirit Reconnaissance",
        "a_new_year_binge": "New Year's Spirit Gun Charge",

        // ── ANIME GENRES ──
        "a_genre_action": "Spirit Gun Action Specialist",
        "a_genre_adventure": "Beyond the Spirit World",
        "a_genre_comedy": "Kuwabara's Comedy Moment",
        "a_genre_drama": "Yusuke's Vow",
        "a_genre_fantasy": "Spirit World Dimension",
        "a_genre_horror": "Demon World Terror",
        "a_genre_mystery": "Spirit Detective Mystery",
        "a_genre_romance": "Heart of the Spirit Detective",
        "a_genre_scifi": "Spirit World Technology",
        "a_genre_sol": "Life in Sarayashiki",
        "a_genre_sports": "Dark Tournament Training Grounds",
        "a_genre_supernatural": "Demon Transformation Power",
        "a_genre_thriller": "Sensui Pursuit",
        "a_genre_mecha": "Anti-Demon Artillery",
        "a_genre_music": "Call of the Spirit Detective",
        "a_genre_psychological": "Kurama's Inner War",
        "a_genre_ecchi": "Spirit World Hot Spring Episode",
        "a_genre_mahou_shoujo": "Spirit Energy Wielder",
        "a_tag_isekai": "Transported to Spirit World",
        "a_tag_harem": "Team Urameshi Bonds",
        "a_tag_bl": "Comrades in Spirit World",
        "a_tag_gl": "Spirit Shield Sisters",
        "a_tag_historical": "Demon World History",
        "a_tag_military": "Spirit World Discipline",
        "a_tag_school": "Sarayashiki Junior High",
        "a_tag_martial_arts": "Toguro Fighting Style",
        "a_tag_vampire": "Demon Bloodline",
        "a_tag_samurai": "Hiei Blade Style",
        "a_tag_space": "Beyond the Demon World",
        "a_tag_parody": "Koenma Baby Parody",
        "a_tag_idol": "Spirit World Idol Wings",
        "a_tag_post_apocalyptic": "Post-Dark Tournament Era",
        "a_tag_cyberpunk": "Spirit World Tech",
        "a_tag_shounen": "Dedicate Your Spirit Gun",
        "a_tag_seinen": "Harsh Reality of Demon World",
        "a_tag_shoujo": "Keiko's Devotion",
        "a_tag_josei": "Genkai's Obsession",
        "a_tag_survival": "Survival in Demon World",

        // ── ANIME COMPLETION ──
        "a_completionist": "Full Spirit Detective Report",
        "a_mega_completionist": "Demon King Complete",
        "a_completion_rate_50": "Halfway to the Dark Tournament",
        "a_completion_rate_75": "Approaching the Sensui Arc",
        "a_completion_rate_90": "Demon World Nearly Unlocked",
        "a_no_drop": "No Spirit Detective Left Behind",
        "a_long_runner_complete": "Long Spirit Campaign Endurance",
        "a_sequel_chain": "Operation Spirit Chain",
        "a_clean_list": "Clean Spirit Detective Record",
        "a_from_ptw": "Orders from Koenma Executed",
        "a_rewatch_master": "Spirit Memory Replay",
        "a_short_complete": "Quick Spirit Skirmish Victory",
        "a_same_day_start_finish": "Same-Day Demon Elimination",
        "a_revival": "Revived by Spirit Energy",
        "a_zero_to_hero": "Delinquent to Spirit Detective",
        "a_five_genre_complete": "Five-Branch Spirit Mastery",
        "a_full_franchise": "Full Team Urameshi Dossier",
        "a_batch_complete": "Batch Deployment Clear",
        "a_paused_to_done": "Returned from the Demon World",
        "a_completion_spree": "Completion Spirit Gun Strike",
        "a_multi_rewatch": "Multi-Timeline via Spirit World",
        "a_dropped_recovery": "Recovered from Sensui's Grip",
        "a_ten_perfect_scores": "Ten Perfect Spirit Scores",
        "a_seasonal_clear": "Seasonal Spirit Clear",
        "a_complete_genre_span": "All-Terrain Spirit Detective",
        "a_monthly_completions": "Monthly Mission Reports",
        "a_yearly_completions": "Yearly Spirit Campaign Victor",
        "a_rapid_complete": "Lightning Spirit Raid Complete",

        // ── ANIME DEDICATION ──
        "a_loyal_fan": "Loyal Team Urameshi Member",
        "a_studio_devotee": "Pierrot Studio Devotee",
        "a_rewatcher": "Spirit Recon Rewatch",
        "a_triple_rewatch": "Triple Spirit Expedition Rewatch",
        "a_annual_tradition": "Annual Dark Tournament Day",
        "a_director_fan": "Director's Spirit Vision Follower",
        "a_voice_actor_fan": "Voice of the Spirit Detective",
        "a_ost_lover": "Smile Bomb!",
        "a_source_reader": "Togashi's Original Texts",
        "a_waiting_weekly": "Weekly Spirit Signal Wait",
        "a_childhood_revisit": "Return to Sarayashiki",
        "a_saga_tracker": "Saga of the Spirit Detective",
        "a_genre_loyalty": "Spirit Loyalty Badge",
        "a_decade_watcher": "Decade-Long Spirit Detective",
        "a_adaptation_hunter": "Adaptation Reconnaissance",
        "a_original_anime_fan": "Original Broadcast Veteran",
        "a_long_commitment": "Long-Term Spirit Duty",
        "a_perfect_attendance": "Perfect Spirit Attendance",
        "a_favorite_studio_5": "Five Allied Studios",
        "a_complete_catalog": "Complete Spirit Catalog",
        "a_franchise_collector": "Spirit World Universe Collector",
        "a_airing_follower": "Currently Airing Intel",
        "a_genre_master": "Genre Mastery Achieved",
        "a_staff_follower": "Staff Dossier Tracker",
        "a_multi_season_fan": "Multi-Season Spirit Veteran",
        "a_format_diversity": "Diverse Spirit Formats",
        "a_year_dedication": "Year of Dedication to Spirit World",
        "a_season_dedication": "Season of Unwavering Service",

        // ── ANIME DISCOVERY ──
        "a_genre_explorer": "Scout Beyond Spirit World",
        "a_studio_hopper": "Spirit Corps Transfer",
        "a_tag_explorer": "Tag Reconnaissance Mission",
        "a_decade_hopper": "Time via Spirit World",
        "a_hidden_gem": "Hidden Demon World Secret",
        "a_popular_taste": "Popular Among Sarayashiki Students",
        "a_retro_appreciator": "Pre-Spirit Detective Appreciator",
        "a_modern_viewer": "Modern Spirit Viewer",
        "a_cross_demographic": "Cross-Demographic Scout",
        "a_underdog_fan": "Underdog Delinquent Spirit",
        "a_variety_week": "Week of Varied Spirit Types",
        "a_foreign_cinema": "Foreign Intelligence Cinema",
        "a_classic_connoisseur": "Classic Spirit World Connoisseur",
        "a_every_season": "Every Season Deployed",
        "a_award_winner": "Medal of the Spirit Gun",
        "a_niche_explorer": "Niche Demon World Explorer",
        "a_global_anime": "Global Alliance Entry",
        "a_cult_classic": "Spirit World Cult Classic",
        "a_random_pick": "Random Mission Assignment",
        "a_new_genre_month": "New Spirit Terrain Monthly",
        "a_seasonal_completionist": "Seasonal Spirit Clear",
        "a_unpopular_opinion": "Unpopular Spirit Opinion",
        "a_top_rated_viewer": "Top-Rated Intel Source",
        "a_source_variety": "Source Material Variety",
        "a_low_score_brave": "Brave Charge into Low Scores",
        "a_upcoming_watcher": "Upcoming Spirit Operation Intel",
        "a_short_series_explorer": "Short Spirit Skirmish Explorer",
        "a_long_series_explorer": "Long Spirit Campaign Explorer",

        // ── ANIME TIME ──
        "a_night_owl": "Night Watch in Spirit World",
        "a_early_bird": "Dawn Spirit Patrol",
        "a_lunch_break": "Keiko's Lunch Break",
        "a_golden_hour": "Golden Hour Spirit Energy",
        "a_four_am_club": "4 AM Spirit Sentry",
        "a_witching_hour": "Demon Witching Hour",
        "a_new_year_watch": "New Year's Oath to Spirit World",
        "a_midnight_premiere": "Midnight Spirit Deployment",
        "a_all_hours": "All-Hours Spirit Detective",
        "a_dawn_warrior": "Dawn Warrior of Sarayashiki",
        "a_afternoon_delight": "Afternoon Spirit Drill",
        "a_prime_time": "Prime Time Spirit Engagement",
        "a_workday_watcher": "On-Duty Spirit Watcher",
        "a_sunday_marathon": "Sunday Spirit Marathon",
        "a_rainy_day": "Rainy Day in Sarayashiki",
        "a_morning_routine": "Morning Spirit Formation",
        "a_night_shift": "Night Shift Spirit Guard",
        "a_twilight_zone": "Twilight Beyond the Spirit Gate",
        "a_seasonal_premier": "Season Premiere Sortie",
        "a_clock_collector": "Spirit World Clock Collector",
        "a_weekend_binge_hours": "Weekend Binge Spirit Operations",
        "a_late_night_regular": "Late Night Regular Patrol",
        "a_sunrise_watcher": "Sunrise Over Demon World",
        "a_holiday_watcher": "Holiday Spirit Guard Duty",
        "a_every_day_of_week": "Every Day Spirit Deployed",
        "a_monthly_hours": "Monthly Spirit Duty Hours",

        // ── ANIME SOCIAL ──
        "a_first_party": "First Team Urameshi Formation",
        "a_party_host": "Spirit Commander",
        "a_social_butterfly": "Sarayashiki Socialite",
        "a_group_binge": "Group Spirit Gun Volley",
        "a_party_regular": "Regular Spirit Partner",
        "a_sync_viewer": "Synchronized Spirit Maneuver",
        "a_commentator": "Spirit Battle Commentator",
        "a_party_marathon": "Marathon Spirit Run",
        "a_full_house": "Full Team Urameshi Assembled",
        "a_community_pillar": "Pillar of the Spirit Detectives",
        "a_watch_party_streak": "Consecutive Spirit Formation Streak",
        "a_diverse_party": "Diverse Team Party",
        "a_late_night_party": "Late Night Spirit Party",
        "a_party_veteran": "Veteran Spirit Squad Leader",
        "a_genre_party": "Cross-Genre Formation",
        "a_weekly_party": "Weekly Comrades' Gathering",
        "a_silent_viewer": "Silent Hiei Observer",
        "a_recommendation_giver": "Spirit Commander's Recommendation",
        "a_party_completionist": "Party Spirit Completionist",
        "a_social_scorer": "Social Spirit Scorer",

        // ── ANIME SPECIAL ──
        "a_round_number": "Round Number Spirit Formation",
        "a_fibonacci": "Fibonacci Spirit Energy Sequence",
        "a_palindrome_day": "Palindrome Spirit Time Rift",
        "a_binary_day": "Binary Spirit Signal Day",
        "a_full_moon": "Full Moon Demon Transformation",
        "a_leap_year": "Leap Year Spirit Time Skip",
        "a_time_traveler": "Spirit World Time Traveler",
        "a_genre_clash": "Human vs. Demon Clash",
        "a_triple_seven": "Triple Seven Spirit Class Fighters",
        "a_thousand_complete": "Thousand Victories for Spirit World",
        "a_pi_episodes": "Pi Spirit Calculation",
        "a_synchronicity": "Spirit World Synchronicity",
        "a_world_record": "World Record Spirit Gun Kill",
        "a_nice": "Nice Spirit Count",
        "a_power_level": "S-Class Demon Power Level",
        "a_answer_42": "The Answer to Yusuke's Question",
        "a_square_number": "Perfect Spirit Formation",
        "a_prime_count": "Prime Number of Demons Slain",
        "a_matching_date": "Matching Intel Date",
        "a_century_episode": "Century Episode Spirit Assault",
        "a_double_digits": "Double Digit Spirit Kills",
        "a_one_two_three": "Human Spirit Demon Class",
        "a_lucky_seven": "Seven Lucky Spirit Detectives",
        "a_all_tens": "All Tens Spirit Score",
        "a_exact_hundred_eps": "Exact Hundred Spirit Engagements",
        "a_year_match_count": "Year Match Spirit Kill Count",

        // ── ANIME FORMATS ──
        "a_tv_watcher": "TV Broadcast Spirit Detective",
        "a_movie_buff": "Yu Yu Movie Operations",
        "a_ova_hunter": "OVA Spirit World Hunter",
        "a_ona_explorer": "ONA Scout Explorer",
        "a_special_watcher": "Special Episode Operative",
        "a_short_king": "Short Engagement King",
        "a_variety_pack": "All-Format Spirit Corps",
        "a_film_festival": "Spirit World Film Festival",
        "a_music_video": "Smile Bomb Collection",
        "a_tv_short": "Quick Recon Clip",
        "a_movie_marathon": "Movie Marathon Blitz",
        "a_double_length": "Double-Length Spirit Operation",
        "a_anthology": "Team Urameshi Anthology",
        "a_mini_series": "Mini Spirit Campaign",
        "a_theatrical": "Theatrical Spirit Deployment",
        "a_format_master": "Format Master Spirit Detective",
        "a_long_movie": "Feature-Length Spirit Expedition",
        "a_back_catalog": "Back Catalog Spirit Files",
        "a_cm_watcher": "Commercial Break Watcher",
        "a_pv_collector": "Preview Signal Collector",
        "a_format_balance": "Balanced Spirit Formats",
        "a_episodic_master": "Episodic Spirit Campaign Master",
        "a_sequel_movie": "Sequel Spirit Operation Film",
        "a_recap_watcher": "Recap Briefing Watcher",

        // ── ANIME STREAKS ──
        "a_daily_streak": "Daily Spirit Patrol Streak",
        "a_mega_streak": "Mega Spirit Expedition Streak",
        "a_weekly_warrior": "Weekly Warrior of Spirit World",
        "a_monthly_watcher": "Monthly Spirit Duty",
        "a_comeback": "Return from the Demon World",
        "a_weekend_streak": "Weekend Spirit Sortie Streak",
        "a_no_zero_days": "No Zero Days in Spirit World",
        "a_iron_will": "Iron Will of the Spirit Detective",
        "a_habit_formed": "Spirit Training Regimen Formed",
        "a_consistent_pace": "Consistent Spirit March Forward",
        "a_year_long": "Year-Long Spirit Campaign",
        "a_double_streak": "Double Spirit Streak Assault",
        "a_streak_recovery": "Spirit Medical Recovery",
        "a_daily_minimum": "Daily Minimum Spirit Duty",
        "a_winter_streak": "Winter Spirit Campaign Streak",
        "a_summer_streak": "Summer Spirit Offensive Streak",
        "a_morning_streak": "Morning Spirit Drill Streak",
        "a_night_streak": "Night Spirit Patrol Streak",
        "a_unbreakable": "Unbreakable Will of Spirit World",
        "a_eternal_flame": "Eternal Flame of the Spirit",
        "a_completion_streak": "Completion Mission Chain",
        "a_rating_streak": "Rating Streak Report",
        "a_multi_ep_streak": "Multi-Episode Spirit Offensive",
        "a_genre_streak": "Genre Streak Sortie",
        "a_studio_streak": "Studio Loyalty Streak",
        "a_perfect_week": "Perfect Week of Spirit Service",

        // ── ANIME SCORING ──
        "a_critic": "Koenma Tribunal Judge",
        "a_perfect_ten": "Perfect 10 Spirit Rating",
        "a_harsh_critic": "Toguro's Harsh Standards",
        "a_fair_judge": "Genkai's Fair Assessment",
        "a_generous_spirit": "Generous Spirit Comrade",
        "a_score_all": "Full Team Roster Evaluation",
        "a_wide_range": "Wide Range Spirit Assessment",
        "a_controversial": "Controversial Spirit Command Decision",
        "a_consistent_scorer": "Consistent Spirit Evaluator",
        "a_score_sniper": "Precision Spirit Gun Sniper",
        "a_evolving_taste": "Evolving Spirit Strategy",
        "a_bell_curve": "Bell Curve of Spirit Scores",
        "a_picky_watcher": "Selective Spirit Commander",
        "a_100_rated": "Century of Spirit Evaluations",
        "a_500_rated": "Five Hundred Spirit Reports",
        "a_mediocre_majority": "Middle Ground Spirit Strategist",
        "a_rating_spree": "Rating Spirit Barrage",
        "a_score_variance": "Variable Spirit Ratings",
        "a_masterpiece_hunter": "Masterpiece Spirit Hunter",
        "a_contrarian": "Contrarian Spirit Scout",
        "a_optimist": "Optimist Despite the Demons",
        "a_score_distributor": "Score Distributor General",
        "a_genre_critic": "Genre Spirit Tactical Critic",
        "a_mean_above_8": "Elite Spirit Combat Average",

        // ── ANIME HOLIDAY ──
        "a_new_years_resolution": "New Year's Vow for Spirit World",
        "a_valentines_weeb": "Valentine's Spirit Dedication",
        "a_pi_day": "Pi Day Spirit Calc",
        "a_april_fools": "April Fools Koenma Prank",
        "a_international_anime_day": "International Spirit Detective Day",
        "a_star_wars_day": "Demon Empire Day",
        "a_summer_solstice": "Summer Solstice Spirit Expedition",
        "a_tanabata": "Tanabata Wish for Spirit World",
        "a_friday_13th": "Friday the 13th Demon Attack",
        "a_halloween_spirit": "Halloween Demon Horror",
        "a_thanksgiving_binge": "Thanksgiving Spirit Feast",
        "a_christmas_special": "Midwinter Spirit Festival Special",
        "a_new_years_eve": "New Year's Eve Final Spirit Stand",
        "a_birthday_watch": "Birthday Spirit Watch",
        "a_holiday_marathon": "Holiday Spirit Marathon",
        "a_independence_day": "Spirit World Independence Day",
        "a_culture_day": "Demon World Culture Day",
        "a_spring_equinox": "Spring Spirit Advance",
        "a_earth_day": "Protect This Spirit World Day",
        "a_labor_day": "Spirit World Labor Day",
        "a_winter_solstice": "Winter Solstice in Demon World",
        "a_anime_birthday": "Anime Anniversary Celebration",
        "a_every_holiday": "Every Holiday Spirit Detective",
        "a_consecutive_holidays": "Consecutive Holiday Spirit Deployments",

        // ── ANIME META ──
        "a_meta_first_unlock": "First Spirit Power Awakened",
        "a_meta_collector": "Team Urameshi Badge Collector",
        "a_meta_category_starter": "Category Initiation Rite",
        "a_meta_tier_climber": "Rank Promotion",
        "a_meta_tier_max": "S-Class Demon Rank",
        "a_meta_xp_earner": "XP from Spirit Gun Kills",
        "a_meta_difficulty_easy": "Easy Spirit Training Exercise",
        "a_meta_difficulty_hard": "Legendary Difficulty: Sensui",
        "a_meta_unlock_spree": "Unlock Spree Spirit Gun",
        "a_meta_completionist": "Meta Completionist Spirit Detective",
        "a_meta_diverse": "Diverse Spirit Portfolio",
        "a_meta_dominator": "Meta Dominator of Spirit World",

        // ── MANGA MILESTONES ──
        "m_first_chapter": "First Chapter of Spirit Detective",
        "m_chapter_counter": "Chapter Spirit Sortie Counter",
        "m_chapter_titan": "Chapter Demon Assault",
        "m_reading_hours": "Hours Studying Spirit Texts",
        "m_reading_time_lord": "Spirit World Reading Memory",
        "m_manga_collector": "Spirit Archive Collector",
        "m_library_legend": "Genkai's Book Legend",
        "m_first_complete": "First Manga Spirit Journey Done",
        "m_hundred_club": "Hundred-Chapter Spirit Club",
        "m_first_day": "First Day of Spirit Reading",
        "m_first_rating": "First Manuscript Rating",
        "m_ten_thousand_pages": "Ten Thousand Pages of Spirit Intel",
        "m_volume_collector": "Volume Stockpile Collector",
        "m_year_explorer": "Year of Spirit Manga Exploration",
        "m_century_reader": "Century-Chapter Spirit Reader",
        "m_five_hundred_ch": "Five Hundred Chapters of Spirit",
        "m_thousand_ch": "Thousand-Chapter Spirit Campaign",
        "m_reading_ten": "Ten Spirit Manuscripts at Once",
        "m_ptr_hoarder": "Spirit Reading Backlog Hoarder",
        "m_dropped_honesty": "Honest Spirit Retreat",
        "m_season_reader": "Seasonal Spirit Reading Rotation",
        "m_active_reader": "Active Spirit Field Reader",
        "m_five_thousand_ch": "Five Thousand Spirit Chapters Deep",
        "m_ten_completed": "Ten Spirit Manga Campaigns Complete",
        "m_fifty_completed": "Fifty Spirit Manga Missions Done",
        "m_five_hundred_completed": "Five Hundred Spirit Manga Victories",
        "m_mean_score_tracker": "Average Spirit Manuscript Rating",
        "m_unique_authors": "Unique Spirit Author Encounters",
        "m_all_status": "All Spirit Reading Statuses",
        "m_first_favorite": "First Spirit Manga Bond",
        "m_favorites_collector": "Spirit Manga Favorites Arsenal",
        "m_days_spent_reading": "Days in the Spirit World Archives",

        // ── MANGA BINGE ──
        "m_binge_reader": "Spirit Binge Reading Advance",
        "m_marathon_reader": "Spirit World-to-Demon Marathon",
        "m_weekend_reader": "Weekend Spirit Reading",
        "m_non_stop_reading": "Non-Stop Spirit Page Turning",
        "m_one_more_chapter": "One More Spirit Chapter Charge",
        "m_speed_read": "Spirit Gun Speed Read",
        "m_double_story": "Double Spirit Manuscript Feature",
        "m_triple_read": "Triple Spirit Reading Assault",
        "m_five_a_day": "Five Spirit Reads a Day",
        "m_chapter_chain": "Spirit Chapter Chain Offensive",
        "m_volume_binge": "Volume Spirit Binge Bombardment",
        "m_power_reader": "Power Spirit Reader Scout",
        "m_half_day_read": "Half-Day Spirit Archive Dive",
        "m_full_day_read": "Full-Day Spirit Manuscript Study",
        "m_power_weekend": "Power Weekend Spirit Reading",
        "m_binge_king": "King of the Spirit Reading Corps",
        "m_no_sleep_read": "All-Night Spirit Reading",
        "m_full_series_rush": "Full Spirit Series Rush Attack",
        "m_seven_day_challenge": "Seven-Day Spirit Intel Gathering",
        "m_hundred_day_read": "Hundred-Day Spirit Reading Siege",
        "m_volume_rush": "Spirit Volume Rush Deployment",
        "m_series_sweep": "Spirit Series Sweep Operation",
        "m_genre_binge": "Cross-Genre Spirit Maneuver",
        "m_author_binge": "Togashi Focused Deep Dive",
        "m_chapter_counter_day": "Daily Spirit Chapter Kill Count",
        "m_multi_series_binge": "Multi-Series Spirit Reading Front",
        "m_midnight_binge": "Midnight Spirit Archive Session",
        "m_new_year_binge": "New Year's Spirit Reading Charge",
        "m_forty_eight_hour": "Forty-Eight Hour Spirit Reading Siege",
        "m_oneshot_binge": "Oneshot Spirit Blitz Attack",

        // ── MANGA GENRES ──
        "m_genre_action": "Action Spirit Manuscript Specialist",
        "m_genre_adventure": "Adventure Beyond Spirit World",
        "m_genre_comedy": "Comedy in Sarayashiki",
        "m_genre_drama": "Drama of the Spirit Detective",
        "m_genre_fantasy": "Fantasy of Spirit World",
        "m_genre_horror": "Demon Horror Manuscript",
        "m_genre_mystery": "Spirit Detective Mystery",
        "m_genre_romance": "Romance in Spirit World",
        "m_genre_scifi": "Sci-Fi Spirit Technology",
        "m_genre_sol": "Slice of Life in Sarayashiki",
        "m_genre_sports": "Dark Tournament Sports",
        "m_genre_supernatural": "Supernatural Spirit Powers",
        "m_genre_thriller": "Sensui Thriller Report",
        "m_genre_psychological": "Psychological Spirit Warfare Reader",
        "m_genre_isekai": "Isekai Through Spirit World",
        "m_genre_shounen": "Shounen Heart of a Spirit Detective",
        "m_genre_ecchi": "Spirit World Hot Springs Chapter",
        "m_genre_mahou_shoujo": "Power of Spirit Energy",
        "m_genre_mecha": "Anti-Demon Weapon Blueprints",
        "m_genre_music": "Spirit World Folk Songs",
        "m_tag_isekai_new": "New World Beyond Spirit World",
        "m_tag_harem": "Team Urameshi Bonds Manga",
        "m_tag_bl": "Brothers of Spirit World Manga",
        "m_tag_gl": "Spirit Shield Sisters Manga",
        "m_tag_historical": "Demon World History Manga",
        "m_tag_military": "Spirit World Operations Manga",
        "m_tag_school": "Sarayashiki Academy Manga",
        "m_tag_martial_arts": "Toguro Combat Manual",
        "m_tag_vampire": "Demon Blood Manga",
        "m_tag_samurai": "Hiei Blade Master Manga",
        "m_tag_space": "Beyond Demon World Manga",
        "m_tag_parody": "Chibi Koenma Manga",
        "m_tag_idol": "Spirit World Idol Manga",
        "m_tag_post_apocalyptic": "Post-Dark Tournament Manga",
        "m_tag_cyberpunk": "Spirit World Technology Manga",
        "m_tag_shoujo": "Keiko's Story Manga",
        "m_tag_survival": "Spirit World Survival Manga",
        "m_tag_cooking": "Spirit World Rations Cookbook",
        "m_tag_medical": "Field Medic Manga",
        "m_tag_villainess": "Demon Candidate Manga",

        // ── MANGA COMPLETION ──
        "m_completionist": "Spirit Manga Campaign Completionist",
        "m_mega_completionist": "Supreme Spirit Manga Commander",
        "m_completion_rate_50": "Halfway to the Dark Tournament",
        "m_completion_rate_75": "Approaching the Sensui Arc",
        "m_completion_rate_90": "Final Spirit Chapter Approaching",
        "m_no_drop": "No Spirit Manuscript Abandoned",
        "m_long_runner_complete": "Long Spirit Series Endurance Medal",
        "m_sequel_chain": "Sequel Spirit Chain of Command",
        "m_clean_list": "Clean Spirit Reading Record",
        "m_from_ptr": "Orders Received: Read",
        "m_reread_master": "Spirit Memory Replay Reread",
        "m_oneshot_complete": "Oneshot Spirit Mission Specialist",
        "m_same_day_start_finish": "Same-Day Spirit Reading Blitz",
        "m_revival": "Revival Through Spirit Energy",
        "m_zero_to_hundred": "Delinquent to Spirit Scholar",
        "m_five_genre_complete": "Five-Genre Spirit Mastery",
        "m_full_collection": "Full Spirit Archive Collection",
        "m_batch_complete": "Batch Spirit Clearance",
        "m_paused_to_done": "Back from Demon Hiatus",
        "m_completion_spree": "Completion Spirit Barrage",
        "m_format_completionist": "Format Spirit Completion Badge",
        "m_catch_up": "Caught Up with Spirit Serialization",
        "m_multi_reread": "Multi-Pass Spirit Reread",
        "m_dropped_recovery": "Recovered from Sensui's Grip",
        "m_ten_perfect_scores": "Ten Perfect Spirit Manuscript Scores",
        "m_complete_genre_span": "All-Genre Spirit Reading Scout",
        "m_monthly_completions": "Monthly Spirit Manuscript Victories",
        "m_yearly_completions": "Yearly Spirit Reading Campaign",
        "m_rapid_complete": "Rapid Spirit Intel Processing",
        "m_author_complete": "Togashi's Complete Works",

        // ── MANGA DEDICATION ──
        "m_loyal_reader": "Loyal Spirit World Reader",
        "m_mangaka_lover": "Togashi Devotee",
        "m_rereader": "Spirit Scout Rereader",
        "m_triple_reread": "Triple Spirit Reread Expedition",
        "m_annual_reread": "Annual Dark Tournament Reread",
        "m_publisher_fan": "Publisher Alliance Fan",
        "m_artist_fan": "Artist Appreciation Medal",
        "m_adaptation_compare": "Manga vs Anime Spirit Compare",
        "m_source_material_fan": "Source Material Spirit Scout",
        "m_waiting_weekly": "Weekly Spirit Chapter Signal Wait",
        "m_classic_reader": "Classic Spirit Manuscript Reader",
        "m_saga_reader": "Saga of the Spirit Detective Reader",
        "m_genre_loyalty": "Genre Spirit Loyalty Medal",
        "m_decade_reader": "Decade-Long Spirit Reader",
        "m_ln_adaptation": "Light Novel Adaptation Intel",
        "m_original_work": "Original Spirit Manga Work",
        "m_long_commitment": "Long-Term Spirit Reading Commitment",
        "m_up_to_date": "Up-to-Date with Spirit Front Lines",
        "m_favorite_mangaka": "Favorite Mangaka Honored",
        "m_complete_portfolio": "Complete Spirit Reading Portfolio",
        "m_franchise_collector": "Spirit World Franchise Collector",
        "m_serialization_follower": "Serialization Tracker",
        "m_genre_master": "Genre Spirit Mastery Earned",
        "m_multi_series_author": "Multi-Series Togashi Fan",
        "m_format_diversity": "Diverse Spirit Reading Formats",
        "m_year_dedication": "Year of Dedicated Spirit Reading",
        "m_ongoing_follower": "Ongoing Spirit Series Follower",
        "m_genre_loyalty_50": "Fifty Genre Spirit Loyalty Chapters",

        // ── MANGA DISCOVERY ──
        "m_genre_explorer": "Genre Spirit Territory Scout",
        "m_publisher_hopper": "Publisher Spirit Transfer",
        "m_tag_explorer": "Spirit Manga Tag Recon Mission",
        "m_decade_hopper": "Decade-Hopping via Spirit World",
        "m_hidden_gem": "Hidden Demon World Gem",
        "m_popular_taste": "Popular Among Sarayashiki Students",
        "m_retro_reader": "Pre-Spirit Era Appreciator",
        "m_modern_reader": "Modern Spirit Reader",
        "m_cross_demographic": "Cross-Demographic Spirit Scout",
        "m_underdog_fan": "Underdog Delinquent Fan",
        "m_variety_week": "Week of Varied Spirit Readings",
        "m_manhwa_reader": "Manhwa Intelligence Reader",
        "m_manhua_reader": "Manhua Intelligence Reader",
        "m_classic_connoisseur": "Classic Spirit Manuscript",
        "m_award_winner": "Medal-Winning Spirit Manuscript",
        "m_niche_explorer": "Niche Spirit Territory Reader",
        "m_world_manga": "World Spirit Manga Intel",
        "m_cult_classic": "Spirit World Cult Classic Underground",
        "m_random_pick": "Random Spirit Reading Assignment",
        "m_new_genre_month": "New Spirit Genre Deployment Monthly",
        "m_year_completionist": "Year Spirit Reading Completionist",
        "m_unpopular_opinion": "Unpopular Spirit Opinion",
        "m_top_rated_reader": "Top-Rated Spirit Intel Source",
        "m_source_variety": "Source Material Variety",
        "m_low_score_brave": "Brave Low-Score Spirit Reader",
        "m_short_manga_explorer": "Short Spirit Manga Skirmish",
        "m_long_manga_explorer": "Long Spirit Campaign Manuscript",
        "m_serialization_explorer": "Spirit Serialization Explorer",

        // ── MANGA TIME ──
        "m_night_owl": "Night Owl Spirit Reader",
        "m_early_bird": "Dawn Spirit Patrol Reader",
        "m_lunch_reader": "Keiko's Lunch Reader",
        "m_commute_reader": "Travel to Spirit World Reader",
        "m_four_am_club": "4 AM Spirit Sentry Reader",
        "m_new_year_read": "New Year's Spirit Reading Oath",
        "m_all_hours": "All-Hours Spirit Archive Access",
        "m_prime_time_reader": "Prime Time Spirit Manuscript",
        "m_workday_reader": "On-Duty Spirit Reader",
        "m_sunday_read": "Sunday Spirit Reading Marathon",
        "m_morning_routine": "Morning Spirit Formation Reading",
        "m_night_shift_reader": "Night Shift Spirit Reader",
        "m_seasonal_premier_read": "New Spirit Release Intel",
        "m_clock_collector": "Spirit Clock Reading Time",
        "m_late_night_horror": "Midnight Demon Horror Read",
        "m_afternoon_reader": "Afternoon Spirit Reading",
        "m_golden_hour_reader": "Golden Hour Spirit Energy Reading",
        "m_dawn_reader": "Dawn Spirit Reading Scout",
        "m_twilight_reader": "Twilight Spirit Reading",
        "m_midnight_start": "Midnight Spirit Reading Mission",
        "m_weekend_binge_hours": "Weekend Spirit Binge Reading Ops",
        "m_late_night_regular": "Late Night Spirit Regular Reader",
        "m_sunrise_reader": "Sunrise Over Demon World Reader",
        "m_every_day_of_week": "Every Day Spirit Reading Duty",
        "m_monthly_hours": "Monthly Spirit Reading Hours Logged",
        "m_bedtime_reader": "Bedtime Spirit Reader",

        // ── MANGA CREATIVE ──
        "m_art_appreciator": "Togashi Art Appreciator",
        "m_webtoon_reader": "Webtoon Intelligence",
        "m_full_color": "Full Color Spirit Manuscript",
        "m_doujin_reader": "Underground Spirit Doujin Reader",
        "m_anthology_reader": "Anthology Collection Reader",
        "m_adaptation_reader": "Adaptation Study Reader",
        "m_longstrip_reader": "Vertical Scroll Reader",
        "m_4koma_reader": "4-Koma Koenma Shorts",
        "m_oneshot_reader": "Oneshot Spirit Mission Reader",
        "m_format_variety": "Format Spirit Tactical Variety",
        "m_light_novel_reader": "Light Novel Intel Reader",
        "m_novel_reader": "Novel Spirit Archive Reader",
        "m_visual_storyteller": "Visual Spirit Battle Narrator",
        "m_colored_classic": "Colored Classic Spirit Manuscript",
        "m_webcomic_fan": "Webcomic Underground Fan",
        "m_manga_to_anime": "Manga to Anime Spirit Comparison",
        "m_seinen_reader": "Seinen Spirit Reader",
        "m_josei_reader": "Josei Spirit Perspective Reader",
        "m_award_winning_art": "Medal-Winning Spirit Artwork",
        "m_debut_work": "Debut Spirit Manuscript",
        "m_vertical_scroll": "Vertical Scroll Spirit Intel",
        "m_traditional_format": "Traditional Spirit Format Reader",
        "m_cross_media": "Cross-Media Spirit Intelligence",
        "m_spinoff_reader": "Spinoff Spirit Mission Reader",
        "m_remake_reader": "Remake Spirit Reading Assignment",
        "m_collaboration_reader": "Joint Spirit Operation Manuscript",

        // ── MANGA STREAKS ──
        "m_daily_streak": "Daily Spirit Reading Patrol Streak",
        "m_mega_streak": "Mega Spirit Reading Campaign Streak",
        "m_weekly_warrior": "Weekly Spirit Warrior Reader",
        "m_monthly_reader": "Monthly Spirit Reader",
        "m_comeback": "Reader's Return from Demon World",
        "m_weekend_streak": "Weekend Spirit Reading Streak",
        "m_no_zero_days": "No Zero Spirit Reading Days",
        "m_iron_will": "Iron Will Spirit Reader",
        "m_habit_formed": "Spirit Reading Regimen Formed",
        "m_consistent_pace": "Consistent Spirit Reading Advance",
        "m_year_long": "Year-Long Spirit Reading Campaign",
        "m_double_streak": "Double Spirit Reading Streak",
        "m_streak_recovery": "Spirit Reading Streak Recovery",
        "m_daily_minimum": "Daily Minimum Spirit Pages",
        "m_winter_streak": "Winter Spirit Reading Campaign",
        "m_summer_streak": "Summer Spirit Reading Offensive",
        "m_morning_streak": "Morning Spirit Reading Formation",
        "m_night_streak": "Night Spirit Reading Patrol",
        "m_unbreakable": "Unbreakable Spirit Reading Will",
        "m_eternal_flame": "Eternal Spirit Flame of Knowledge",
        "m_chapter_a_day": "Chapter a Day Spirit Discipline",
        "m_genre_streak": "Genre Spirit Reading Streak",
        "m_completion_streak": "Completion Spirit Reading Chain",
        "m_rating_streak": "Spirit Rating Streak Filed",
        "m_multi_ch_streak": "Multi-Chapter Spirit Streak",
        "m_author_streak": "Togashi Dedication Streak",
        "m_perfect_week_manga": "Perfect Spirit Reading Week",
        "m_diverse_streak": "Diverse Spirit Reading Streak",

        // ── MANGA SCORING ──
        "m_critic": "Spirit World Manuscript Critic",
        "m_perfect_ten": "Perfect 10 Spirit Manuscript",
        "m_harsh_critic": "Toguro's Reading Standards",
        "m_fair_judge": "Genkai's Fair Review",
        "m_generous_spirit": "Generous Spirit Reader",
        "m_score_all": "Full Spirit Manuscript Assessment",
        "m_wide_range": "Wide Range Spirit Scores",
        "m_controversial": "Controversial Spirit Reading Opinion",
        "m_consistent_scorer": "Consistent Spirit Manuscript Scorer",
        "m_score_sniper": "Precision Spirit Gun Score Sniper",
        "m_evolving_taste": "Evolving Spirit Reading Taste",
        "m_bell_curve": "Bell Curve of Spirit Scores",
        "m_picky_reader": "Selective Spirit Reading Commander",
        "m_100_rated": "Century of Spirit Ratings Filed",
        "m_500_rated": "Five Hundred Spirit Rating Reports",
        "m_mediocre_majority": "Middle Ground Spirit Reader",
        "m_rating_spree": "Spirit Rating Barrage Filed",
        "m_score_variance": "Variable Spirit Manuscript Scores",
        "m_binge_rater": "Spirit Binge Rating Session",
        "m_reread_rerate": "Reread and Re-Rate Spirit Intel",
        "m_masterpiece_hunter": "Masterpiece Spirit Manuscript Hunter",
        "m_contrarian": "Contrarian Spirit Reader",
        "m_optimist": "Optimistic Spirit Reader Scout",
        "m_score_distributor": "Score Distributor General",
        "m_genre_critic": "Genre Spirit Reading Critic",
        "m_mean_above_8": "Elite Spirit Reading Average",

        // ── MANGA HOLIDAY ──
        "m_new_years_resolution": "New Year's Spirit Reading Vow",
        "m_valentines_read": "Valentine's Spirit Reading Bond",
        "m_pi_day": "Pi Day Spirit Chapter Count",
        "m_april_fools": "April Fools Koenma Chibi",
        "m_international_manga_day": "International Spirit Manga Day",
        "m_free_comic_day": "Free Comic Spirit Day",
        "m_summer_solstice": "Summer Solstice Spirit Reading",
        "m_tanabata": "Tanabata Spirit Reading Wish",
        "m_friday_13th": "Friday 13th Demon Manuscript",
        "m_halloween_read": "Halloween Demon Horror Reading",
        "m_thanksgiving_binge": "Thanksgiving Spirit Reading Feast",
        "m_christmas_read": "Midwinter Spirit Festival Reading",
        "m_new_years_eve": "New Year's Eve Final Spirit Read",
        "m_birthday_read": "Birthday Spirit Reading Gift",
        "m_holiday_marathon": "Holiday Spirit Reading Marathon",
        "m_independence_day": "Spirit World Independence Reading",
        "m_culture_day": "Spirit World Culture Day Manuscript",
        "m_spring_equinox": "Spring Spirit Equinox Reading",
        "m_earth_day": "Earth Day Spirit Conservation Read",
        "m_labor_day": "Spirit World Labor Reading Day",
        "m_winter_solstice": "Winter Solstice Spirit Reading",
        "m_manga_birthday": "Spirit Manga Birthday Celebration",
        "m_every_holiday_reader": "Every Holiday Spirit Reader",
        "m_consecutive_holidays": "Consecutive Holiday Spirit Reads",

        // ── MANGA SPECIAL ──
        "m_round_number": "Round Number Spirit Milestone",
        "m_fibonacci": "Fibonacci Spirit Energy Chapter Pattern",
        "m_palindrome_day": "Palindrome Spirit Reading Day",
        "m_binary_day": "Binary Spirit Signal Reading Day",
        "m_full_moon_read": "Full Moon Demon Read",
        "m_leap_year_read": "Leap Year Spirit Reading",
        "m_triple_seven": "Triple Seven Spirit Classes",
        "m_thousand_complete": "Thousand Spirit Manga Victories",
        "m_nice": "Nice Spirit Chapter Count",
        "m_power_level_chapters": "S-Class Demon-Level Chapters",
        "m_answer_42": "Answer to Yusuke's Reading",
        "m_square_number": "Perfect Spirit Formation Chapters",
        "m_prime_count": "Prime Spirit Chapter Count",
        "m_matching_date": "Matching Spirit Intel Reading Date",
        "m_century_chapter": "Century Spirit Chapter Milestone",
        "m_pi_chapters": "Pi Spirit Chapter Calculation",
        "m_synchronicity": "Spirit World Reading Synchronicity",
        "m_world_record": "World Record Spirit Chapter Count",
        "m_genre_clash": "Genre Spirit Clash Reading",
        "m_time_traveler": "Time-Traveling Spirit Reader",
        "m_double_digits": "Double Digit Spirit Milestone",
        "m_one_two_three": "Human Spirit Demon One Two Three",
        "m_lucky_seven": "Seven Lucky Spirit Chapters",
        "m_exact_hundred_ch": "Exact Hundred Spirit Chapters Read",
        "m_year_match_count": "Year Match Spirit Chapter Count",
        "m_chapter_match_date": "Spirit Chapter Date Match",

        // ── MANGA FORMATS ──
        "m_manga_format": "Manga Format Specialist",
        "m_manhwa_format": "Manhwa Format Reader",
        "m_manhua_format": "Manhua Format Reader",
        "m_ln_format": "Light Novel Format",
        "m_oneshot_format": "Oneshot Format Operative",
        "m_doujin_format": "Doujin Format Reader",
        "m_novel_format": "Novel Format Reader",
        "m_format_master_manga": "Format Master Spirit Reader",

        // ── MANGA META ──
        "m_meta_first_unlock": "First Spirit Reading Power Unlocked",
        "m_meta_collector": "Spirit Reading Badge Collector",
        "m_meta_category_starter": "Category Initiation",
        "m_meta_tier_climber": "Spirit Reading Rank Promotion",
        "m_meta_tier_max": "Maximum Spirit Reading Rank",
        "m_meta_xp_earner": "XP from Spirit Reading Intel",
        "m_meta_difficulty_easy": "Easy Spirit Reading Exercise",
        "m_meta_difficulty_hard": "Legendary Spirit Manuscript Challenge",
        "m_meta_unlock_spree": "Spirit Reading Unlock Barrage",
        "m_meta_completionist": "Meta Spirit Reading Completionist",
        "m_meta_diverse": "Diverse Spirit Reading Portfolio",
        "m_meta_dominator": "Meta Spirit Reading Dominator",
    },
    musicUrl: "",
    previewColors: {
        bg: "#040807",
        primary: "#00aa44",
        secondary: "#008c37",
        accent: "#e8aa00",
    },
    hasAnimatedElements: true,
    backgroundImageUrl: "",
    backgroundDim: 0.25,
    backgroundBlur: 25,
    particleTypes: {
        spirit_gun_blast: { label: "Spirit Gun Blast", maxCount: 8, defaultEnabled: true, defaultIntensity: 60 },
        demon_energy: { label: "Demon Energy", maxCount: 10, defaultEnabled: true, defaultIntensity: 50 },
        rose_petals: { label: "Rose Petals", maxCount: 12, defaultEnabled: true, defaultIntensity: 45 },
        flame_sword: { label: "Flame Sword", maxCount: 6, defaultEnabled: true, defaultIntensity: 55 },
    },
    milestoneNames: {
        1:   "Delinquent Schoolboy",
        5:   "Spirit Detective Appointed",
        15:  "Dark Tournament Entry",
        30:  "Genkai's Heir",
        45:  "A-Class Demon",
        60:  "Sensui Confronted",
        80:  "S-Class Demon Level",
        100: "King of Demon World",
    },
}
